### ISSUE TITLE
Non-literal HTTP Response codes for python codegen?

### ISSUE THREAD

**Issue by ewillis-kxs** [OpenAPITools/openapi-generator#10015]
More a question than anything else but do we have to use numeric HTTP response codes in our flask-restx sources in order for the code generation to be successful?  In our sources, we define our responses using things like HttpStatus.Ok rather than 200 - but when I run the codegen over our sources, I end up with (e.g.) HttpStatus.ok being copied into the generated code without the import to make those names resolve - is it possible to configure the codegen to bring in specific imports to avoid this problem?  More generally do I have to use numbers for the HTTP response codes in my flask-restx sources in order to use the codegen?

**Comment by spacether** [comment]
Status codes are assumed to be http status codes.
Please read the docs on this here: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#responsesObject
If you want a default response, you can use the key of 'default'
