### ISSUE TITLE
[BUG] [csharp-client] Query parameters do not get escaped

### ISSUE THREAD

**Issue by HerrNiklasRaab** [OpenAPITools/openapi-generator#10018]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Query parameters do not get escaped, when using HttpClient (not Restsharp). When I pass a query parameter, let's say "2021-07-23T22:55:43.3041130+02:00" this gets added to the request URL like it is. Because the + is interpreted as whitespace the server receives this value "2021-07-23T22:55:43.3041130 02:00". See the + is replaced by the whitespace. Shouldn't the client that was generated make sure that all parameters are escaped? In this case the + should be replaced with %2B, right?

According to the spect this is the [expected behavior.](https://swagger.io/docs/specification/serialization/#:~:text=Additionally%2C%20the%20allowReserved,quotes%252Fh2g2.txt)

##### openapi-generator version

stable 5.2.0

##### OpenAPI declaration file content or url

In my case I used a query parameter with DateTimeOffset, but a query parameter with string would work as well.

##### Generation Details

targetFramework: net5.0
packageName: Brokkoli.Api.Client
sourceFolder: ""
useDateTimeOffset: true
library: httpclient

If this is actually a bug, I'm willing to sponsor work on this issue to the tune of $50.
cc @wing328

**Comment by wing328** [comment]
@HerrNiklasRaab I've filed #10069 to fix the issue.

**Comment by HerrNiklasRaab** [comment]
@wing328 Thanks! How do I pay once the PR has merged?

**Comment by wing328** [comment]
For payment, what about PayPal: https://www.paypal.com/paypalme/wing328 ?

I'll merge it later today if no question/feedback from anyone.

**Comment by HerrNiklasRaab** [comment]
I am not able to try it, right now. Looked at the PR, should be fixed. Payment is made thanks!

**Comment by wing328** [comment]
@HerrNiklasRaab thanks you! Have a nice weekend.

**Comment by HerrNiklasRaab** [comment]
@wing328 Why isn't this change in the newest version 5.2.1 or am I missing something?

**Comment by wing328** [comment]
@HerrNiklasRaab I think it's included in the v5.2.1 release. PM me via [Slack](https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g) if you need help.
