### ISSUE TITLE
[BUG] [typescript-angular] Add "header" to reserved words

### ISSUE THREAD

**Issue by JohnTraDolta** [OpenAPITools/openapi-generator#10020]
##### Description
Having a property in the swagger.json called "header". This result in a client with a parameter called header, later in that function a variable with the same name is instantiated

##### Solution 
Add header as a reserved word to enable the auto renaming functionality

**Comment by JohnTraDolta** [comment]
I can do a pr if anyone can point me in the right direction. 👍

**Comment by wing328** [comment]
@JohnTraDolta thanks for offering help to fix this. Can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM
