### ISSUE TITLE
[Symfony] Make controllers explicitly public

### ISSUE THREAD

**Issue by Addvilz** [OpenAPITools/openapi-generator#1002]
##### Description

Yet another Symfony4 compatibility fix. 

Since Symfony 3.4, services in container are private by default. Because of that, doing a resource import in root routing (for example, to prefix paths or do something similar) will not work, as the controllers are inaccessible, resulting in an error.

##### Suggest a fix/enhancement

The only backwards compatible fix is to mark these controller services public by default.

I will open a PR to address this issue.

**Comment by Addvilz** [comment]
P.S if anyone is interested, a monkey patch I have been using so far is to manually override controller services in the app services. Works fine for small api's with 1.3 controllers total, not so well if there are 100+...

**Comment by BenjaminHae** [comment]
I think this can be solved by adding the tag `controller.service_arguments` to the services.
