### ISSUE TITLE
[BUG] [Kotlin] Unresolved reference `AnyType`

### ISSUE THREAD

**Issue by IARI** [OpenAPITools/openapi-generator#10036]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Several models and *api classes depend on a type named `AnyType`. (for example an object-type schema with a property where the type is not specified)
However, `AnyType` is not generated as a model.

##### openapi-generator version

5.2.0

##### OpenAPI declaration file content or url

I am trying to generate the jira api, using
https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json

##### Generation Details

using the gradle plugin, excerpt from build.gradle.kts:
```Kotlin

plugins {
    kotlin("jvm") version "1.5.10"

    id("org.openapi.generator") version "5.2.0"
}

// ...

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "1.8"
    }
    // ...

    openApiGenerate {
        generatorName.set("kotlin")
        inputSpec.set(jiraApiSpec.absolutePath)
        outputDir.set(generatedDir)
        apiPackage.set("com.atlassian.jira.rest.api")
        modelPackage.set("com.atlassian.jira.rest.model")
        invokerPackage.set("com.atlassian.jira.rest.client")
        groupId.set("com.atlassian.jira.rest")
        library.set("jvm-okhttp4")
        configOptions.set(
            mapOf(
                "dateLibrary" to "java8"
            )
        )
    }
```

##### Steps to reproduce

1. download the jira api spec from above
2. make sure that jiraApiSpec is set to the download location
3. run `gradle openApiGenerate`
4. run `gradle build` on the generated gradle project

##### Related issues/PRs

Others appear to have had Issues with `AnyType` with other generators.
Some Have been fixed, others are open yet.
#7618 Swift (also #7617)
#9969 C
#7458 C#
#6332 Typescript
#6668 PhP

##### Suggest a fix

I am completely new to OpenAPI.
However according to @wing328 in https://github.com/OpenAPITools/openapi-generator/issues/6668#issuecomment-644849020_ it seems to have been added in mid-2020 - so I assume it has simply not been implemented for several generators - kotlin among them - yet.

**Comment by wing328** [comment]
@IARI I've filed #10070 to fix the issue.

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/10071 to fix other issues when using https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json to generate the Kotlin client.
