### ISSUE TITLE
[REQ] [dart-dio-next] Enum fallback values

### ISSUE THREAD

**Issue by josh-burton** [OpenAPITools/openapi-generator#10038]
BuiltValue supports setting an enum entry as a fallback to use if the serialized enum value doesn't exist.

This is great for backwards compatibility in APIs as an enum can fallback to an 'unknown' value.

```

## Describe the solution you'd like

In my API clients I generally modify the enum.mustache and inline_enum.mustache files to fallback to the first value.

```
  @BuiltValueEnumConst({{#isInteger}}wireNumber: {{{value}}}{{/isInteger}}{{^isInteger}}wireName: r{{{value}}}{{/isInteger}}{{#-first}}, fallback: true{{/-first}})
```

A config flag could be added to enable this behaviour, or perhaps something more advanced like a config flag to determine which enum value to fallback to.

e.g. "enumFallbackValue": "unknown"

If an enum class is generated and has an "unknown" value, the fallback would be set on that value.

@kuhnroyal any thoughts?

**Comment by kuhnroyal** [comment]
Didn't get the mention cause of formatting.
We should check if other generators have a fallback behavior.
Maybe just use `default`?

**Comment by kuhnroyal** [comment]
@wing328 Is there something like fallback values somewhere?

**Comment by kuhnroyal** [comment]
Ran into an unannounced API update today that introduced new enum values :)

Couple links for future reference:
https://github.com/OAI/OpenAPI-Specification/issues/1552
https://opensource.zalando.com/restful-api-guidelines/#112

**Comment by kuhnroyal** [comment]
@josh-burton What do you think about adding something like an `x-enum-fallback`?

**Comment by josh-burton** [comment]
@kuhnroyal yeah that would be great. Letting the user choose which value is the fallback would be the ideal solution.

**Comment by kuhnroyal** [comment]
@josh-burton This is fixed now :)
