### ISSUE TITLE
[dart][dart-dio-next] File arrays in Form parameter are generated as a single file in the api

### ISSUE THREAD

**Issue by ahmednfwela** [OpenAPITools/openapi-generator#10032]
#### Description

form parameters with file arrays generated according to [OAS3 ](https://swagger.io/docs/specification/describing-request-body/file-upload/)
are generated as a single `MultipartFile` instead of `List<MultipartFile>` (using `BuiltList<MultipartFile>` here is useless, since it doesn't get serialized)

#### openapi-generator version

5.2.0

#### OpenAPI declaration

```yaml
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
```

**Comment by itsAmitGoyani** [comment]
This bug is not only in dart-dio-next, but also in dart-dio. Need to fix in dart-dio as well.
