### ISSUE TITLE
[BUG] [dart] [dart-dio] File arrays in Form parameter are generated as a single file in the api

### ISSUE THREAD

**Issue by itsAmitGoyani** [OpenAPITools/openapi-generator#10043]
> I'm using OpenAPI Generator to generate Dart API code from swagger.json file.
> In that, form parameters with file arrays are generated as a single `Uint8List` instead of `List<Uint8List>`
> 
> #### openapi-generator version
> 5.2.0
> 
> #### OpenAPI declaration in json
> ```json
>      "requestBody": {
>          "content": {
>           "multipart/form-data": {
>              "schema": {
>                "required": [
>                  "description",
>                  "title"
>                ],
>                "type": "object",
>                "properties": {
>                  "title": {
>                    "type": "string"
>                  },
>                  "description": {
>                    "type": "string"
>                  },
>                  "attachments": {
>                    "type": "array",
>                    "items": {
>                      "type": "string",
>                      "format": "binary"
>                    }
>                  }
>                }
>              },
>              "encoding": {
>                "title": {
>                  "style": "form"
>                },
>                "description": {
>                  "style": "form"
>                },
>                "attachments": {
>                  "style": "form"
>                }
>              }
>            },
>            "application/json": {
>              "schema": {
>                "required": [
>                  "description",
>                  "title"
>                ],
>                "type": "object",
>                "properties": {
>                  "title": {
>                    "type": "string"
>                  },
>                  "description": {
>                    "type": "string"
>                  },
>                  "attachments": {
>                    "type": "array",
>                    "items": {
>                      "type": "string",
>                      "format": "binary"
>                    }
>                  }
>                }
>              },
>              "encoding": {
>                "title": {
>                  "style": "form"
>                },
>                "description": {
>                  "style": "form"
>                },
>                "attachments": {
>                  "style": "form"
>                }
>              }
>            }
>          }
>       },
> ```

**Comment by kuhnroyal** [comment]
Not gonna fix this for dart-dio, the generator is no longer maintained.

**Comment by kuhnroyal** [comment]
Please use the dart-dio-next generator where this has been fixed.
