### ISSUE TITLE
[REQ] [Dart-dio-next] No way to set dart version, it's always @dart=2.0

### ISSUE THREAD

**Issue by C0deZLee** [OpenAPITools/openapi-generator#10049]
### Is your feature request related to a problem? Please describe.

I cannot find how to generate the dart package using Dart 2.12.0+ It always generate with Dart 2.0, which is not ideal.

## Describe the solution you'd like

sudo openapi-generator-cli generate -g dart-dio-next --additional-properties=dartVersion=2.12.0

## Describe alternatives you've considered

None. I cannot manually replace all `// @dart=2.0` to `// @dart=2.12.0` and change all files to null safety.

## Additional context

Documents need to be improved

**Comment by kuhnroyal** [comment]
Not sure where you see this. `dart-dio-next` is always 2.12+ and doesn't use Dart version comments.
