### ISSUE TITLE
[BUG][kotlin] doulbe quotes of string default values are escaped 

### ISSUE THREAD

**Issue by m-kay** [OpenAPITools/openapi-generator#10059]
##### Description

When generating properties in Kotlin data classes with String default values the double quotes are escaped by mustache as `&quot;` 

##### openapi-generator version

5.2.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: default value test
  version: 1.0.0
paths: {}
components:
  schemas:
    TestModel:
      description: Model to test default value
      type: object
      properties:
        propWithDefault:
          type: string
          default: This is the default value.
```

##### Generation Details
Generated code:

```kotlin
data class TestModel(

    @field:JsonProperty("propWithDefault") val propWithDefault: kotlin.String? = &quot;This is the default value.&quot;
) {

}
```

**Comment by wing328** [comment]
Can you please try the latest master? I recall merging a PR recently related to this issue. Thanks.

**Comment by m-kay** [comment]
You are right, the issue is fixed in the latest master 👍
