### ISSUE TITLE
Trivial question: How to resolve / handle "$ref"

### ISSUE THREAD

**Issue by chatelao** [OpenAPITools/openapi-generator#1010]
Hi folks,

* How to I resolve one/all "$ref"?
* Is there an Wiki Page for this question?

Hope this is a 5 second question for most auf you 👍 

Regards
Olivier

**Comment by chatelao** [comment]
No, references inside a file. E.g.:

$ref:'#/components/schemas/my_type'

William Cheng <notifications@github.com> schrieb am Di., 11. Sep. 2018,
12:21:

**Comment by wing328** [comment]
OK, then I think examples are the best way to show how it works: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml (and search for `$ref`)

**Comment by chatelao** [comment]
The examples are not my problem, but how are they resolved (if at all)
inside the generators?

Sorry for this questions, hope wenn will Find it out 😊

William Cheng <notifications@github.com> schrieb am Di., 11. Sep. 2018,
19:39:

**Comment by wing328** [comment]
@canadaduane openapi-generator relies on the swagger-parser library to parse the spec into Java POJO.

**Comment by chatelao** [comment]
Okay, thank you. I will have a look at it.

William Cheng <notifications@github.com> schrieb am Di., 18. Sep. 2018,
13:16:
