### ISSUE TITLE
[BUG][Ruby][Faraday] Request options of build_request is empty

### ISSUE THREAD

**Issue by NivathaSV8** [OpenAPITools/openapi-generator#10137]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

openapi-generator-cli:v5.1.1

##### OpenAPI declaration file content or url

```
openapi: 3.0.3

info:
  title: 'Some title'
  version: '1.0'
  
servers:
  - url: 'https://localhost/api/v1'
        
paths:
  /customer:
    post:
      operationId: Post Customer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                accounts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        default: 'someone'
                      age:
                        type: integer
                        default: 18
      responses:
        '200':
          description: 'OK'
```

##### Steps to reproduce

Using the client and hit API as follows:
```
TestClient.configure do |config|
  config.scheme = 'localhost.com:4000'
  config.host = 'http'
  config.base_path = '/'
  config.debugging = true
  config.server_index = nil
  config.timeout = 120
end
```

##### Actual Ouput:

#<struct Faraday::Request method=:post, path="http://localhost.com:4000/api/v1/customer", params={}, headers={"Content-Type"=>"application/json", "User-Agent"=>"OpenAPI-Generator/1.0.0/ruby", "Accept"=>"application/json"}, body="{\"name\":\"Test\",\"age\":\"18\"}", options=#<Faraday::RequestOptions (empty)>>

##### Expected Output:
Faraday Request Options contains timeout set as mentioned above.

##### Related issues/PRs

N/A

##### Suggest a fix
**-req_opts.update :body => req_body**

request.headers = header_params
request.body = req_body
request.url url
request.params = query_params
**+request.options = req_opts**
download_file(request) if opts[:return_type] == 'File'

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix?

**Comment by NivathaSV8** [comment]
@wing328 I have created a PR with required changes. But I am sorry the CI actions have failed.
So can this issue be fixed based on the commits.

**Comment by NivathaSV8** [comment]
@cliffano @zlx @autopp Can someone please have a look on this issue and get it fixed.

**Comment by NivathaSV8** [comment]
@dkliban I could see similar change has been done by you, so can you please have a look on the commits and have this issue fixed.
