### ISSUE TITLE
Generating Unique Module Names

### ISSUE THREAD

**Issue by krnchee** [OpenAPITools/openapi-generator#1017]
##### Description

[PYTHON] I have two API specs, but the generator for python produces the same module name (openapi_client) for each one. I need to import both into a project. How can I configure the generator to produce to unique package names under the lib directory?

##### openapi-generator version

 3.0.0

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

java -jar ../../Nemo-thirdparty/openapi-generator-3.2.0/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ../test_spec_01.yaml -g python -o ./pyclient 

##### Steps to reproduce

Run command 

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

N/A

**Comment by anilj1** [comment]
This is exactly the question/problem I am also having. It is important to know how to generate the python package with API specification specific name. Without it, when I install the package into my virtual python variable (and even in default system level paths), it overwrites the previous 'openapi_client' package. 

Can someone please provide the way to generate unique/API specific python package? 

I have tried to generate the model and api packages with specific names by using following command line options, but the main package is still the same.

--model-package mymodel 
--api-package myapi

**Comment by anilj1** [comment]
Hi, for now, I programmatically, modified the setup.py file (after it is generated) and changed the value of NAME variable. This workaround has helped solve this problem and I am able to 'install' the individual python module.

Hope this helps others to follow the step and solve this problem in interim. This however should happen more formally from the code generator.

**Comment by anilj1** [comment]
Programmatic modification of the NAME variable in setup.py is not helping as it is not really changing the module name "openapi_client" when it installs the package. Can someone please provide a correct method to address this issue? Thank you.

**Comment by wing328** [comment]
Have you guys tried to customize the `packageName`?
```
$ java -jar "./modules/openapi-generator-cli/target/openapi-generator-cli.jar" config-help -g python

CONFIG OPTIONS
	packageName
	    python package name (convention: snake_case). (Default: openapi_client)

	projectName
	    python project name in setup.py (e.g. petstore-api).

	packageVersion
	    python package version. (Default: 1.0.0)

	packageUrl
	    python package URL.

	sortParamsByRequiredFlag
	    Sort method arguments to place required parameters before optional parameters. (Default: true)

	hideGenerationTimestamp
	    Hides the generation timestamp when files are generated. (Default: true)

	generateSourceCodeOnly
	    Specifies that only a library source code is to be generated. (Default: false)

	library
	    library template (sub-template) to use: asyncio, tornado, urllib3 (Default: urllib3)
```

For more information, please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md

**Comment by anilj1** [comment]
Thanks! No, we did not know about this. How do we pass or use these options? I did not see an example in the link you provided. 

I tried like the two options I provided above, but it did not help either. 
--package-name my_client_pkg --project-name my_client_proj

Note that I am using openapi-generator-3.2.0.

**Comment by anilj1** [comment]
Ok, I saw a note on how to use this.. 
Supported config options can be different per language. Running config-help -g {lang} will show available options. These options are applied via configuration file (e.g. config.json) or by passing them with -D{optionName}={optionValue}. (If -D{optionName} does not work, please open a ticket and we'll look into it)

I tried them as this. 
-D{packageName}={my_client_pkg} -D{projectName}={my_client_proj}

However this did not work. The package name is still created as "openapi_client". I will now try the config file method.

**Comment by anilj1** [comment]
Hello wind328, it worked through using the config file approach!! Thanks a lot for your help!! I will log a bug as it is not working with -D option.

**Comment by jmini** [comment]
> I tried them as this.
-D{packageName}={my_client_pkg} -D{projectName}={my_client_proj}

Why the bracket?

I think it should be:
```
-DpackageName=my_client_pkg -DprojectName=my_client_proj
```

(not tested, but it should work)

**Comment by anilj1** [comment]
> ```
> -DpackageName=my_client_pkg -DprojectName=my_client_proj
> ```
> (not tested, but it should work)
Yes, I tested this already and it worked for me. I just removed some of my intermediate posts and put a more appropriate one as an update.

**Comment by wing328** [comment]
Let us know if you guys still need any help. Closing this for the time being.
