### ISSUE TITLE
[BUG] CodegenParameter.baseType is different than CodegenProperty.baseType

### ISSUE THREAD

**Issue by ahmednfwela** [OpenAPITools/openapi-generator#10189]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating specs with a container type, the behavior of `CodegenParameter` and `CodegenProperty` is inconsistent.
- in  `CodegenParameter` the `baseType` refers to the `items` type
- in  `CodegenProperty` the `baseType` refers to the container type (the correct behavior)

e.g. generating `modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml` with any generator (tested with `csharp` and `dart-dio-next`)
- operation `createUsersWithArrayInput` has array of `User` as body parameter
  when debugging this:
  ```
  "bodyParam" : {
        "dataType" : "BuiltList<User>",
        "baseType" : "User",
  ...
  }
  ```
- Model `NullableClass` has property `array_nullable_prop` which is a list of objects
  when debugging this:
  ```
  {
      "dataType" : "BuiltList<JsonObject>",
      "datatypeWithEnum" : "BuiltList<JsonObject>",
      "baseType" : "BuiltList", 
  ...
  }
  ```

##### openapi-generator version

5.2.1 (latest master commit a7de7095a7bfb6f84f8a7115b009db612db24a26)

##### Generation Details

for `dart-dio-next`: `./bin/generate-samples.sh bin/configs/dart-dio-next* -- --global-property debugOperations,debugModels > log.txt`
for `csharp`: `./bin/generate-samples.sh bin/configs/other/openapi3/csharp-OpenAPIClientNetStandard.yaml -- --global-property debugOperations,debugModels > log_cs.txt`

cc @wing328 @kuhnroyal @agilob

**Comment by kuhnroyal** [comment]
Yea I have seen this before. Can you check what `items` and `mostInnerItems` give you?
The correct `baseType` should probably be `BuiltList`.

**Comment by ahmednfwela** [comment]
items and mostInnerItems are identical in both cases

**Comment by kuhnroyal** [comment]
And their `baseType` also seems correct. I think I have been using `mostInnerItems.baseType` when I needed that.

**Comment by ahmednfwela** [comment]
yes, the problem is there is no way to get the list type alone in the operation parameters

**Comment by kuhnroyal** [comment]
Yea, not sure where this is handled. You can try to rewrite the `baseType` similar to the handling here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java#L294

All the information needed (container type, unique items) should be available.

**Comment by ahmednfwela** [comment]
It seems that in multiple places the `baseType` is assigned to the inner/items type, giving us no way to get the array type
Culprits of this issue are in:

- https://github.com/OpenAPITools/openapi-generator/blob/ce587c7b57a79bb9dee80efc8ef1f6f2d24802f9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L4232-L4245

- https://github.com/OpenAPITools/openapi-generator/blob/ce587c7b57a79bb9dee80efc8ef1f6f2d24802f9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L4733-L4736

- https://github.com/OpenAPITools/openapi-generator/blob/ce587c7b57a79bb9dee80efc8ef1f6f2d24802f9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5111

- https://github.com/OpenAPITools/openapi-generator/blob/ce587c7b57a79bb9dee80efc8ef1f6f2d24802f9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L6904

- https://github.com/OpenAPITools/openapi-generator/blob/ce587c7b57a79bb9dee80efc8ef1f6f2d24802f9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L7091

- https://github.com/OpenAPITools/openapi-generator/blob/ce587c7b57a79bb9dee80efc8ef1f6f2d24802f9/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L7205

**Comment by ahmednfwela** [comment]
@wing328 friendly reminder for this issue since it's blocking multiple other PRs that target V7

**Comment by wing328** [comment]
Will try to take a look over the weekend. thanks for the reminder.

**Comment by cpuell** [comment]
Is this still on track to be fixed?

**Comment by ahmednfwela** [comment]
it was fixed recently by introducing containerType

**Comment by kuhnroyal** [comment]
So we can close this?
