### ISSUE TITLE
[BUG][TYPESCRIPT/ANGULAR] Using wrong keyword in generated AngularService (localVarHeaders instead of headers)

### ISSUE THREAD

**Issue by Schmitda** [OpenAPITools/openapi-generator#10182]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

Since the use of Version 5.2.1 (last Version used before was 5.0.0) we encounter a issue with the generation of Angular Service code. 
According to this [https://github.com/OpenAPITools/openapi-generator/pull/10091](https://github.com/OpenAPITools/openapi-generator/pull/10091) variables have been renamed for the generation of the Angular - Services. 

Unfortunately on Line https://github.com/OpenAPITools/openapi-generator/commit/664aa2d946236ce327cf56256947baeb68f828e4#diff-7de15eed36eb15ed45aef205826063248eaddf2b11511db6a4bb2679c2aca851R361 there seemed to went something wrong. 
The property "headers" which is part of the HTTPClient Options has also been renamed instead of the value. 
This should stay headers. 

This will cause a compilation error in angular and won't work as header information is not submitted. 

So the code should be: 
``` 
{
    ...
    headers: localVarHeaders,
   ...
}
```

But unfortunately the code generated is:

``` 
{
      ...
      localVarHeaders: localVarHeaders,
      ...
}
```

##### openapi-generator version

I am using the `"@openapitools/openapi-generator-cli": "2.3.10"` with `version-manager 5.2.1`. 
Reverting to Version 5.0.0 in the version-manager works. 

##### OpenAPI declaration file content or url

You may use the example schema to regenerate the issue: https://petstore.swagger.io/v2/swagger.json.

##### Generation Details

Can be generated with the following line: 

`        openapi-generator-cli generate -i https://petstore.swagger.io/v2/swagger.json -g typescript-angular -o src/app/swagger --type-mappings=object=any --skip-validate-spec`

##### Steps to reproduce

0. Create an Angular App
1. Install openapi-cli. `https://www.npmjs.com/package/@openapitools/openapi-generator-cli`
2. Set version in openapitools.json to 5.2.1
Here is my example: 

```
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.2.1"
  }
}
```

3. Generate Services for angular as described above
`        openapi-generator-cli generate -i https://petstore.swagger.io/v2/swagger.json -g typescript-angular -o src/app/swagger --type-mappings=object=any --skip-validate-spec`
4. Use petService via Dependency Injection in app.component.ts

5. Try compiling. `npm run start`
The pet.service.ts will cause a compilation error because localVarHeaders is not a known key for the httpClient options.

##### Related issues/PRs

No related issue found yet. 

##### Suggest a fix

[https://github.com/OpenAPITools/openapi-generator/commit/664aa2d946236ce327cf56256947baeb68f828e4#diff-7de15eed36eb15ed45aef205826063248eaddf2b11511db6a4bb2679c2aca851R361](https://github.com/OpenAPITools/openapi-generator/commit/664aa2d946236ce327cf56256947baeb68f828e4#diff-7de15eed36eb15ed45aef205826063248eaddf2b11511db6a4bb2679c2aca851R361)
So the code should be: 
``` 
{
    ...
    headers: localVarHeaders,
   ...
}
```

But unfortunately the code generated is:

``` 
{
      ...
      localVarHeaders: localVarHeaders,
      ...
}
```

Thanks for any comment on this issue. 
Best regards
Schmitda

**Comment by JohnTraDolta** [comment]
I was the one who made the changes and agree with this being a bug.
I can provide a fix if the owner wants me too

**Comment by Schmitda** [comment]
@JohnTraDolta Thanks for the quick response. 
Would be great if you find the time for a fix. 👍

**Comment by darrynhoskingluna** [comment]
I also just ran into this issue, along with angular 12 not being supported.

Currently follwing a work around from here where i manually update packages but still have this issue
#https://github.com/OpenAPITools/openapi-generator/issues/9511

**Comment by LPCmedia** [comment]
when can we expect this to be in the docker image ? all our builds are failing with this. 
thanks.

**Comment by LPCmedia** [comment]
looks like its published. Thanks.

**Comment by coder925** [comment]
@JohnTraDolta , Will this fix be included in an upcoming release `5.2.2` ?
Currently I have downgraded to `5.2.0` for `openapi-generator-cli` to avoid this issue.

**Comment by JohnTraDolta** [comment]
I'm sorry but I don't know as I only provided the fix and have nothing else to do with the project

**Comment by macjohnny** [comment]
It should be part of the next upcoming release, so 5.3.0

https://github.com/OpenAPITools/openapi-generator/milestones
