### ISSUE TITLE
[BUG][JavaSpring] Model classes attempt to use java.util.Arrays without importing it

### ISSUE THREAD

**Issue by anno1985** [OpenAPITools/openapi-generator#10213]
##### Description

The [`pojo.mustache`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache#L135,L155) template seems to attempt to use the `Arrays` class (four times) if `#vendorExtensions.x-jackson-optional-nullable-helpers` is set. However, the [`model.mustache`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/model.mustache) doesn't seem to `import java.util.Arrays;`. 

This results in a failing build at compile time (here with maven):
```
[ERROR] /path/to/target/generated-sources/openapi/src/gen/java/com/example/generated/model/MyModel.java:[100, 114] cannot find symbol
[ERROR]   symbol:   variable Arrays
[ERROR]   location: class com.example.generated.model.MyModel
```

The issue appears when using `openapi-generator-maven-plugin:5.2.1`

##### Suggest a fix
I'm not familiar with mustache syntax, but I'm guessing adding something similar to the following to `model.mustache` around line 32 should do the trick:
```
{{^isEnum}}
{{#vendorExtensions.x-jackson-optional-nullable-helpers}}
import java.util.Arrays;
{{/vendorExtensions.x-jackson-optional-nullable-helpers}}
{{/isEnum}}
```

Alternatively, the respective code lines in `pojo.mustache` could be changed to use the fully qualified class name, `java.util.Arrays` instead of just `Arrays` (on lines 135, 142, 147 and 155).

Note that I haven't verified if the import is actually added correctly already if `isByteArray` is set, in which case changes to lines 135 and 147 would be superfluous (and the first option, changes to imports, might be preferable to sometimes fully qualifying the class and sometimes (when dealing with ByteArrays) relying on imports).

**Comment by borsch** [comment]
Hi @anno1985 . Sorry, my bad. I have created PR to fix this issue - https://github.com/OpenAPITools/openapi-generator/pull/10234

**Comment by wing328** [comment]
@anno1985 we've merged the fix by @borsch . Can you please pull the latest master to give it another try?
