### ISSUE TITLE
[BUG][scala-akka] generates a readme linking to model docs that don't exist

### ISSUE THREAD

**Issue by ckipp01** [OpenAPITools/openapi-generator#10242]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

While using `scala-akka` generator it seems impossible to get the model docs generated. For example, I followed the instructions similar to those in the WIKI to test this against the current master branch:

```
git clone https://github.com/openapitools/openapi-generator.git
cd openapi-generator
mvn clean install
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
  -i modules/openapi-generator/src/test/resources/3_0/scala-akka/petstore.yaml \
  -o scala-test
  -g scala-akka
```

After doing this you'll see that there is a `README.md` created that has the following section:

```
## Documentation for Models

 - [ApiResponse](ApiResponse.md)
 - [Category](Category.md)
 - [Order](Order.md)
 - [Pet](Pet.md)
 - [Tag](Tag.md)
 - [User](User.md)
```

However, none of these model docs actually exist.

##### openapi-generator version

The last commit at the time of checking this is https://github.com/OpenAPITools/openapi-generator/commit/158649aff9a87b13b448880d7ca6a4ac35fadcc2

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/scala-akka/petstore.yaml

##### Generation Details

Just follow the steps up above in the description

##### Steps to reproduce

Just follow the steps up above in the description

##### Related issues/PRs

Not exactly sure if these are the same or related, but they all seems to have to do with scala-akka and doc generation not working as expected.

https://github.com/OpenAPITools/openapi-generator/issues/8966
https://github.com/OpenAPITools/openapi-generator/issues/5795

##### Suggest a fix

I'm pretty unfamiliar with how this is all supposed to work, so no idea.

**Comment by wing328** [comment]
Closed via the PR by @nMoncho 

Please pull the latest master to give it another try.
