### ISSUE TITLE
[BUG] [JAVA] [SPRING] [MVC] Generating code is referencing a generated model class which is not created [BIS]

### ISSUE THREAD

**Issue by sebastianblesgen** [OpenAPITools/openapi-generator#10254]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm facing the exact same issue as https://github.com/OpenAPITools/openapi-generator/issues/405 but in version 5.x.y.
When using multipart/form-data, referenced models are not generated.

It works well with 4.3.1.
##### openapi-generator version

5.0.0, 5.2.0
##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.2'
...
paths:
  '/workflows':
    post:
      operationId: create
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/xxx'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aaa'

...
components:
  schemas:
    yyy:
          type: object
          properties:
            zzz:
              type: object
              properties:
                name:
                  $ref: '#/components/schemas/name'
                mode:
                  $ref: '#/components/schemas/mode'
            documents:
              type: array
              items:
                type: string
                format: binary
          required:
            - zzz
            - documents
          additionalProperties: false

```

##### Generation Details
```xml
<plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>5.0.0</version>
                <executions>
                    <execution>
                        <id>server</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/contract/${project.artifactId}.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <modelNameSuffix>DTO</modelNameSuffix>
                            <configOptions>
                                <title>MyOrg</title>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <library>spring-mvc</library>
                                <useTags>false</useTags>
                                <serializableModel>true</serializableModel>
                                <swaggerDocketConfig>true</swaggerDocketConfig>
                                <delegatePattern>true</delegatePattern>
                                <dateLibrary>java8</dateLibrary>
                                <apiPackage>myorg.controllers</apiPackage>
                                <modelPackage>myorg.model</modelPackage>
                                <invokerPackage>myorg.invoker</invokerPackage>
                                <useOneOfInterfaces>true</useOneOfInterfaces>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

##### Steps to reproduce
Generate and check that models xxxDTO and deep object (zzzDTO, modeDTO) are not generated

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/405

**Comment by marcelstoer** [comment]
Did you set `-DskipFormModel=false` as described in #405 and https://openapi-generator.tech/docs/customization/#selective-generation?

**Comment by MRAfni** [comment]
Do you know if there's a way to set that in the pom rather than the command? I've tried everything I can think of (globalProperties in the plugin config, properties section of the pom, etc) and I've only got it to work if it's on the maven command.

**Comment by marcelstoer** [comment]
It says
> ...you can use system properties or [global properties](https://openapi-generator.tech/docs/globals) to control the output

But pay attention to https://openapi-generator.tech/docs/globals#note-on-global-property-declaration

**Comment by ryanwong113** [comment]
@MRAfni You can set it in the maven plugin too:
```
<configuration>
    <globalProperties>
        <skipFormModel>false</skipFormModel>
    </globalProperties>
</configuration>
```
