### ISSUE TITLE
Disable FAIL_ON_UNKNOWN_PROPERTIES in generated JSON.java?

### ISSUE THREAD

**Issue by marbrink** [OpenAPITools/openapi-generator#10306]
##### Description

I get com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException because the API I am using has a new field.
But I want my client to be able to just ignore unknown properties.
In a previous project I used openapi generator 4.3.1 and this was the behaviour.
However in newer versions like 5.1.1 or 5.2.1 this doesn't work anymore. I can see that in the generated invoker.JSON.java the FAIL_ON_UNKNOWN_PROPERTIES changed from false to true.
How can I configure the openapi generator, to ignore unknown properties, like it was before?

##### openapi-generator version

Worked in 4.3.1. Not anymore in 5.x

**Comment by wing328** [comment]
Can you try the following option by setting it to `true`?
```
	disallowAdditionalPropertiesIfNotPresent
	    If false, the 'additionalProperties' implementation (set to true by default) is compliant with the OAS and JSON schema specifications. If true (default), keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default. (Default: true)
	        false - The 'additionalProperties' implementation is compliant with the OAS and JSON schema specifications.
	        true - Keep the old (incorrect) behaviour that 'additionalProperties' is set to false by default.
```

**Comment by GitLinko** [comment]
`true` should be the default for that setting. But setting it to true or false doesn't fix my problem.
I thinkt this setting is for something else?

**Comment by snago** [comment]
We ran into this as well. We "fixed" it with `maven-antrun-plugin` like this:
```xml
<plugin>
    <artifactId>maven-antrun-plugin</artifactId>
    <executions>
        <execution>
            <phase>process-sources</phase>
            <configuration>
                <target>
                    <replace token="mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, true)"
                             value="mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)"
                             dir="target/generated-sources/openapi">
                        <include name="**/our_generated_client/invoker/JSON.java"/>
                    </replace>
                </target>
            </configuration>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by dermot-hardy** [comment]
I'm setting this to workaround the issue:

    <additionalModelTypeAnnotations>@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true)</additionalModelTypeAnnotations>

**Comment by josebarroszeiss** [comment]
I can confirm that works.

**Comment by fistons** [comment]
It works until the the generated code also include `@JsonIgnoreProperties` then compilation failure `com.fasterxml.jackson.annotation.JsonIgnoreProperties is not a repeatable annotation type
`
