### ISSUE TITLE
Query parameters not properly URL-encoded with typescript-axios

### ISSUE THREAD

**Issue by lroal** [OpenAPITools/openapi-generator#10347]
##### Description

The query parameters are not encoded when using axios.  
Here is an example where a query parameter firstName =  "Arne B".  
Then the request becomes: http://localhost:3000/clients?firstName=Arne+B
I would expect it to be:  http://localhost:3000/clients?firstName=Arne%20B

##### openapi-generator version 

Version 2.4.1

##### Generation Details
openapi-generator-cli generate -i http://localhost:3000/api-docs.json --additional-properties=supportsES6=true,useSingleRequestParameter=true -g typescript-axios -o src/api/apar/gen

**Comment by lroal** [comment]
This seems to be a problem with axios itself. https://github.com/axios/axios/issues/1111  
I am closing the issue.

**Comment by milch** [comment]
FYI this is not an issue with axios, it's that the generated code uses this code instead of axios to serialize the query parameters: https://github.com/OpenAPITools/openapi-generator/blob/78ea8afa8454b90185a3738f8ab476684e3f6669/samples/client/petstore/typescript-axios/builds/default/common.ts#L113
