### ISSUE TITLE
[BUG] [Typescript] Tests fail on request to petstore (HTTP 405)

### ISSUE THREAD

**Issue by bodograumann** [OpenAPITools/openapi-generator#10346]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
When running the generator tests for the consolidated typescript generator most of them fail with HTTP error code 405.
This is due to the fact, that we are calling the petstore api over simple `http`. The server then sends an HTTP 302 redirect to `https`. At that point, the client is following the redirect but replacing the `POST` method for creating the new Pet with the `GET` verb.

##### openapi-generator version

Tested on master (bc3ee3249899cc26567da77cf08ba85a64cf5049).

##### Steps to reproduce

Run tests with
```
mvn integration-test -f samples/openapi3/client/petstore/typescript/tests/default/pom.xml
```

Can also be reproduced with `httpie` as:
```
http -v POST http://petstore.swagger.io/v2/pet name=PetName photoUrls:="[]" -F
```

##### Suggest a fix

It would be better if the petstore api would redirect with HTTP 308 and thus forbid the change of method.
On our side though, we should always directly connect via https to the petstore sample server.
So in technical terms: `s|http://petstore.swagger.io/v2|https://petstore.swagger.io/v2|g`

We should do this change for all samples.

**Comment by bodograumann** [comment]
It seems there is a separate petstore api for openapi v3 at https://petstore3.swagger.io/
Maybe we should directly use that in the appropriate places.

While working on the tests I noticed, that the server alternates between returning 200 and 404 when getting a pet. Are there two instances behind the url?

**Comment by wing328** [comment]
@bodograumann for running the test server locally, please refer to https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests#how-to-add-integration-tests-for-new-petstore-samples.

**Comment by bodograumann** [comment]
That does indeed fix all the issues I was seeing.
Not running the integration tests against a live server also makes much more sense to me.
Thank you for the hint.
