### ISSUE TITLE
[BUG] [kotlin-client / okhttp] Dollar sign in query parameter names generated invalid code

### ISSUE THREAD

**Issue by kunzese** [OpenAPITools/openapi-generator#10350]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output? See *Suggest a fix*
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We consume a third-party API that has several query parameters that start with a dollar sign ($). Creating a kotlin-client with the okhttp lib results in an `Unresolved reference: expand` error, because the dollar sign is not escaped and is interpreted as a string template.

##### openapi-generator version

5.2.1

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: "1.0.0"
  title: "Demo"
paths:
  /:
    get:
      operationId: demo
      parameters:
        - in: query
          name: $expand
          schema:
            type: string
      responses:
        '200':
          description: OK
```

##### Generation Details

Via gradle plugin

```
openApiGenerate {
    generatorName = "kotlin"
    inputSpec = "$rootDir/specs/api.yaml"
}
```

##### Suggest a fix

Escape dollar signs in string literals.

`Unresolved reference: expand`

```kotlin
    fun demoRequestConfig(dollarExpand: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarExpand != null) {
                    put("$expand", listOf(dollarExpand.toString()))
                }
            }
        ...
```

Fixed:

```kotlin
    fun demoRequestConfig(dollarExpand: kotlin.String?) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, List<kotlin.String>>()
            .apply {
                if (dollarExpand != null) {
                    put("\$expand", listOf(dollarExpand.toString()))
                }
            }
        ...
```

**Comment by kunzese** [comment]
@mschaller FYI

**Comment by jyutzler** [comment]
Note: `$` is frequently used in JSON, for example in JSON Schema. Therefore this bug can manifest itself in many places.

**Comment by jyutzler** [comment]
There are multiple manifestations of this issue. The OP observes it in code generated from the src/main/resources/kotlin-client/libraries/jvm-okhttp/api.mustache template. For me, the generator is generating data classes with lines like:

>     @field:JsonProperty("\$foo", required = true) val dollarFoo: kotlin.String,

As with the solution presented above, a `\` is required before the $.

**Comment by wing328** [comment]
I've filed #16266 to fix the issue.
