### ISSUE TITLE
[BUG] [dart-dio-next] Enum values based on Integers, with format set to 'int64', are treated as Strings instead of Integers

### ISSUE THREAD

**Issue by dotdotcommadot** [OpenAPITools/openapi-generator#10410]
##### openapi-generator version
 - 5.2.1
 - dart-dio-next

##### Description

On my current setup, I'm generating enums in Dart (amongst a lot of other things) based on a yaml swagger file.
After generating the Enum, the issue I get is that a String is (badly) generated, while actually an integer should be generated instead.

This is the situation:
**Input (Yaml):**
```
 VehicleFuelType:
      type: integer
      format: int64
      enum:
        - 1
      x-enum-varnames:
        - One
```

**Output (Dart)**
```
 @BuiltValueEnumConst(wireName: r1)
 static const VehicleFuelTypeDto One = _$One;
```
==> The analyzer says it can't find an object called 'r1'
==> The issue is that _wireName_ should actually be _wireNumber_.

Actually two things are happening:
- The generator is trying to generate a string based on an int, this is why it says "r1" instead of "1". (the 'r' prefix tries --but fails-- to mark it as a raw String)
- So what would be a bit more correct than this, is that it would name it ```r'1'``` instead of ```r1```. In this case, the "1" would be a proper String.
- But what would be the **most correct**, is that it should be a _wireNumber_ instead of a _wireName_.

To be precise, this means the expected output would be:
```
 @BuiltValueEnumConst(wireNumber: 1)
 static const VehicleFuelTypeDto One = _$One;
```

**What's causing the issue**
When removing the property `format: int64` from the yaml, or when changing it to `format: int32`, all goes well.
The _wireNumber_ would be generated instead of the _wireName_.
It is clear that the issue is due to int64 not being recognized inside the format property.

##### OpenAPI declaration file content or url

For copyright reasons etc, I can only give you pseudo-code
```yaml
openapi: 3.0.1
info:
  title: Vehicles
  description: Some Description
  contact:
    email: some@contact.com
  license:
    name: license
  version: "1.0"
paths: {}
components:
  schemas:
    VehicleFuelType:
      type: integer
      format: int64
      enum:
        - 1
        - 2
      x-enum-varnames:
        - One
        - Two
```

##### Steps to reproduce

- use the code snippet above
- generate code using the dart-dio-next target

##### Suggest a fix

Actually, I assume the issue is in this file:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart-dio/enum.mustache

On line 14 it says:
```@BuiltValueEnumConst({{#isInteger}}wireNumber:```.
I think the problem is in the ```isInteger``` property: it will be true when using either int or int32, or no ```format``` at all. But it will be false when using int64 as a value.

**Comment by kuhnroyal** [comment]
Thanks for the report, I will try to take a look.

> I think the problem is in the isInteger property: it will be true when using either int or int32, or no format at all. But it will be false when using int64 as a value.
@wing328 Is this expected?
