### ISSUE TITLE
[BUG][GO] AnyOf causes compilation error for Go

### ISSUE THREAD

**Issue by deliveroo-andreik** [OpenAPITools/openapi-generator#10430]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generator produces broken code for `anyOf`

##### openapi-generator version

v5.2.1

##### Generation Details

generate \
  --global-property models \
  --global-property modelDocs=false \
  --additional-properties sourceFolder=dto,useOneOfDiscriminatorLookup=true\
  --model-package dto \
  --package-name dto \
  -i /local/docs/openapi.yaml \
  --generate-alias-as-model \
  -g go \
  -o /local/internal/server/rest

```go
func (dst *WebhookEvent) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err := json.Unmarshal(data, &jsonDict) // <---- compilation error as err already declared in var
	if err != nil {
		return fmt.Errorf("Failed to unmarshal JSON into map for the discrimintor lookup.")
	}
}
```
##### Suggest a fix

fix the template and remove unnecessary colon

**Comment by andrewkav** [comment]
fixed in https://github.com/OpenAPITools/openapi-generator/pull/10431
