### ISSUE TITLE
[spring/spring-boot] API generation fails when specification refs a requestBody with object type schema

### ISSUE THREAD

**Issue by rhamiltonsf** [OpenAPITools/openapi-generator#10435]
##### Description

Using the following schema, the openapi-generator-maven-plugin fails to recognize the model in the requestBody schema, and instead tries to import and use a model named `UNKNOWN_BASE_TYPE`. This only happens when I use a ref to the requestBody and if the requestBody schema is of type object.

##### openapi-generator version
5.2.1
5.1.0
4.3.1

##### OpenAPI declaration file content or URL
[Here](https://gist.github.com/rhamiltonsf/187de3326342235d914080d5e4778e57) is a minimum spec that reproduces the issue.

However note that [this spec](https://gist.github.com/rhamiltonsf/56b142ee74480fb93230b6808c015a27) and [this other spec](https://gist.github.com/rhamiltonsf/1cf8b3936a572e94b2eaf27be0836c86) both work.

##### Command line used for generation

This occurred using the openapi-generator-maven-plugin. See [example pom here](https://gist.github.com/rhamiltonsf/4a0bf8b56deb5b5bdcc66c76655708e8) for configurations.

##### Steps to reproduce

1. create a new maven project using [this pom](https://gist.github.com/rhamiltonsf/4a0bf8b56deb5b5bdcc66c76655708e8).
1. Create src/main/resources directory and, add [api.yaml](https://gist.github.com/rhamiltonsf/187de3326342235d914080d5e4778e57) to it
1. run `mvn clean install` from the pom directory

Expected Results:
The command should execute successfully and generate default API models, interfaces, and delegate.

Actual Results:
```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] ~/testproject/target/generated-sources/openapi/api/org/openapitools/api/DefaultApi.java:[8,30] package org.openapitools.model does not exist
[ERROR] ~/testproject/target/generated-sources/openapi/api/org/openapitools/api/DefaultApiDelegate.java:[3,30] package org.openapitools.model does not exist
[ERROR] ~/testproject/target/generated-sources/openapi/api/org/openapitools/api/DefaultApi.java:[43,106] cannot find symbol
  symbol:   class UNKNOWN_BASE_TYPE
  location: interface org.openapitools.api.DefaultApi
[ERROR] ~/testproject/target/generated-sources/openapi/api/org/openapitools/api/DefaultApiDelegate.java:[33,43] cannot find symbol
  symbol:   class UNKNOWN_BASE_TYPE
  location: interface org.openapitools.api.DefaultApiDelegate
```

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/12293 has been merged into master. Please pull the latest to give it a try.
