### ISSUE TITLE
Skip Converting Camel-case to Snake case for apis generated with python client[BUG] Description

### ISSUE THREAD

**Issue by Abhilash-vaidhya** [OpenAPITools/openapi-generator#10458]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

openapi-generator-cli:v4.3.1

##### OpenAPI declaration file content or url

I have been using openapi-generator to generate python clients from a JSON 
The JSON Schema follows CamelCase conventions.
The python clients that are produced from the openapi-generator converts the camelcase to snake case.
i am using the following command line to generate clients

```yaml
generate \
    -g python -i api.json  --generate-alias-as-model \
    --global-property=apis,models,apiDocs=false,modelDocs=false,apiTests=false,modelTests=false,supportingFiles \
    --skip-validate-spec --package-name x.x.x.x-o /x.
```

How do i skip the forced conversion of camel case to snake case by the rest api clients.?
Any help on this will be much useful

**Comment by FredyR4zox** [comment]
+1

**Comment by wodooraj** [comment]
+1

**Comment by spacether** [comment]
We now have the python-experimental generator which is faithful to the original spec case for:
- model properties
- endpoint parameters (request and response)
- request bodies
- response bodies

Read all about it here:
https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/python-fastapi/tests

Closing this issue because we now have a python generator that stays faithful to the spec case (Camel-case)
