### ISSUE TITLE
[BUG][PYTHON] Client response is not respecting capital letters

### ISSUE THREAD

**Issue by gmcrocetti** [OpenAPITools/openapi-generator#10469]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Python response containing keys in capital letters are being converted to lowercase. Therefore, schema is not being respect. I'm not sure if attribute map should be done at response time.

##### openapi-generator version

3.0.3

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Sample service
  version: 0.0.1
  description: response wrongly capitalized
paths:
  /foo:
    post:
      operationId: foo
      description: hello
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyRequest'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponse'
components:
  schemas:
    MyRequest:
      type: object
      properties:
        hello: 
          type: string
    MyResponse:
      type: object
      properties:
        QUICK:
          type: boolean
          readOnly: true
          default: false
        FOX:
          type: boolean
          readOnly: true
          default: false
      required:
      - QUICK
      - FOX
```

##### Generation Details

Python client was generated with default settings using the docker image provided (latest)

##### Steps to reproduce

1. Call your endpoint that returns capitalized letters. Response should be something like:
```json
{
    "QUICK": "foo",
    "FOX": "bar"
}
```
2. Python client parses response above and returns all entries in lowercase.
```json
{
    "quick": "foo",
    "fox": "bar"
}
```

##### Suggest a fix

It's ok controlling this in a request scenario, where the arguments to your class object are all lowercase but regarding the response, I don't this this parsing as valuable as API's consumer expects to receive a response matching the schema definition, which is not happening currently.
Expected output should mimic the schema:
```json
{
    "QUICK": "foo",
    "FOX": "bar"
}
```

**Comment by gmcrocetti** [comment]
> This issue is very similar to #5214

@spacether , thanks a lot for your quick feedback.

Yeah, it looks like, but at the same time it doesn't. #5214 wants to customize how parameters are going to be "translated" to the client. What I'm currently seeking is that the generated Python client respect the schema at response time.

#5214 will work smoothly because `foo_id` will be translated to `FooID` at request time, instead of what will happen in my use case, where one expects `KEY` and gets `key` at response time.

**Comment by spacether** [comment]
In my solution both the request and response stay as in spec case.

**Comment by gmcrocetti** [comment]
Alright, sounds good to me. Feel free to close :). Thanks a lot

**Comment by spacether** [comment]
Heads up there is a new client, python-experimental which uses spec naming for all endpoint parameters and model properties. It was added in: #8325
