### ISSUE TITLE
[Go] Add a generator for the gin framework

### ISSUE THREAD

**Issue by kemokemo** [OpenAPITools/openapi-generator#1047]
##### Description

I respect the generator of `go-server`.
Just like this, I also want a generator using [gin](https://github.com/gin-gonic/gin).

##### Suggest a fix/enhancement

How about `go-gin-server` as the name of generator?

**Comment by wing328** [comment]
@kemokemo thanks for offering help to create a server generator for Go Gin framework.

`go-gin-server` sounds good to me. If you need any help, please let us know.

**Comment by wing328** [comment]
PR merged. Thanks for your contribution!
