### ISSUE TITLE
[BUG][scala-http-client] Default body should not be a single space

### ISSUE THREAD

**Issue by mickaelmagniez** [OpenAPITools/openapi-generator#10560]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The default body sent (for example POST request without any body) is " " (single space character).

Some backends (for example `akka-http`) failed to parse it as json.

So it will be better so send an empty body rather than just a space.

##### openapi-generator version

5.2.1

**Comment by chameleon82** [comment]
Is that behavior related to scenario when client send header `Content-Type: application/json` ?

I that case it make sense to not send that header as well as there is no content.
