### ISSUE TITLE
[BUG] [PYTHON] Can't instantiate model if attribute is None, Python client

### ISSUE THREAD

**Issue by MasterSergius** [OpenAPITools/openapi-generator#10563]
##### Description

Response which comes from API can't be converted to model if some attributes is None. Python client. 

##### openapi-generator version

5.2.1

##### OpenAPI declaration file content or url

When user is not activated at the call moment, then this field will be null (None):

```json
"components":{
//...
  "schemas":{
      "User":
        //....
          "activated": {
            "type": "string",
            "format": "date-time",
            "readOnly": true
          },
//...
}
```

 
##### Generation Details

openapi-generator generate -i spec.json -g python -o ./ --package-name my_pkg

##### Steps to reproduce
1. Get response when from API with some attribute has value None
2. Observe error:
my_pkg.exceptions.ApiTypeError: Invalid type for variable 'activated'. Required value type is datetime and passed type was NoneType at ['received_data'][0]['activated']

The issue raises in `model_utils.py`, function `attempt_convert_item`:
```py
    valid_classes_ordered = order_response_types(valid_classes)
    valid_classes_coercible = remove_uncoercible(
        valid_classes_ordered, input_value, spec_property_naming)
    if not valid_classes_coercible or key_type:
        # we do not handle keytype errors, json will take care
        # of this for us
        if configuration is None or not configuration.discard_unknown_keys:
            raise get_type_error(input_value, path_to_item, valid_classes,
                                 key_type=key_type)
```

##### Related issues/PRs
N/A

##### Suggest a fix

None shouldn't be converted. It might refer to optional attribute of schema, but API might return null (None).

**Comment by spacether** [comment]
My understanding is that the `--library asyncio` code in the python generator is not fully working so it probably shouldn't be used as a baseline.

**Comment by spacether** [comment]
nullable: True is working in the python and python-experimental generators
