### ISSUE TITLE
[BUG][csharp-netcore] Failed to deserialize FileParameter when using HttpClient.

### ISSUE THREAD

**Issue by TORISOUP** [OpenAPITools/openapi-generator#10588]
##### Description

When a client that returns byte[] (FileParameter) as a response is created and called, FileParameter is interpreted as Json and decoded, resulting in an exception.

##### openapi-generator version

5.2.1.

##### Related issues/PRs

I'm sorry if this has already been pointed out.

##### Suggest a fix/enhancement

In the next conditional branch, it looks like the fact that FileParameter is passed is not taken into account.

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/httpclient/ApiClient.mustache#L99-L147

For now, by adding the following code, I was able to get the byte[] without any error.

```cs
if (type == typeof(FileParameter))
{
    return new FileParameter(await response.Content.ReadAsStreamAsync());
}
```

**Comment by NoTuxNoBux** [comment]
Hi

Any reason this has been closed? We ran into the same issue today. `FileParameter` is used correctly as class for responses that contain binary files, but when the API call is performed, the code still tries to deserialize it as JSON.

**Comment by TORISOUP** [comment]
The reason I closed the issue was not because it was resolved, but because I thought I made a mistake in the issue submission flow.

I have added the above process to deal with it, but it does not solve the root problem.
It may be a good idea to submit the issue again.

**Comment by TORISOUP** [comment]
I've reopened it for now.
However, I'm not sure if I've registered the issue in the correct flow. (Is the issue being managed outside of GitHub?)
