### ISSUE TITLE
[ASP.net CORE] Enhancement list

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#1060]
##### Description

- add .NET core version to the auto-generated [README](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/aspnetcore/2.1/README.mustache#L1)
- update Dockerfile with "microsoft/aspnetcore-build:2.1" instead: https://github.com/OpenAPITools/openapi-generator/pull/1008#discussion_r218474034
- add nullable support (ref: https://github.com/OpenAPITools/openapi-generator/pull/1059)
##### openapi-generator version

Latest master

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/1008

##### Suggest a fix/enhancement

If anyone wants to help on this, please rely to let us know.

**Comment by InfoSec812** [comment]
@wing328 Pretty sure this is completed, or am I misreading the linked issues?
