### ISSUE TITLE
[discussion][csharp-netcore][aspnetcore] Clean up of existing netcore generators for 6.x release

### ISSUE THREAD

**Issue by Blackclaws** [OpenAPITools/openapi-generator#10632]
There have been a lot of changes to the csharp-netcore generator over the past half-year, mainly driven by the fact that Restsharp will not work with never netcore versions without socket exhaustion and the addition of the httpclient library.

Due to the fact that the csharp-netcore generator, as well as the aspnetcore generator are currently supporting quite a large range of releases (from netstandard 2.0 and netcore 2.1 up to (soon) net 6.0) we've accumulated quite a bit of baggage in the form of workarounds/switches/special cases for specific versions. 

Also some of the newer versions have obsoleted certain functions that the old versions didn't even provide.

I would like to start a discussion here about how we could slim down the netcore and aspnetcore generators again. 

For aspnetcore one of the low hanging fruits is dropping support for anything below netcore 3.1. 

For csharp-netcore its dropping Restsharp and all associated old constructors in favor of built-in alternatives (httpclient, etc.). 

We probably won't be able to drop support for netstandard 2.0 anytime soon in the csharp-netcore generator as its the lowest common denominator for .net framework and Unity versions < 2021.2

I would also like to discuss dropping Newtonsoft.Json in favor of System.Text.Json, which again, swaps a dependency for something built in, for anything targeting netcoreapp 3.0 and higher.

Since 6.x is a major release we'll have the chance to do breaking changes here, so let's collect some.

@mandrean @frankyjuang @shibayan @Blackclaws @lucamazzanti @wing328 @devhl-labs

**Comment by Blackclaws** [comment]
I'm all for removing unmaintained csharp generators. Merging aspnetcore and csharp-netcore I'd be a bit more careful. They are essentially two very different things, one is a server, one is a client generator. The model files are identical but the api implementation is completely different. However I agree that we should be able to merge some parts and maybe reduce some of the duplication between the generators.

**Comment by jafin** [comment]
RE: Supported frameworks for csharp-netcore, from the discussion above would this be correct?

**DROP?**
```
FrameworkStrategy.NETSTANDARD_1_3,
FrameworkStrategy.NETSTANDARD_1_4,
FrameworkStrategy.NETSTANDARD_1_5,
FrameworkStrategy.NETSTANDARD_1_6,
FrameworkStrategy.NETCOREAPP_2_0,
FrameworkStrategy.NETCOREAPP_2_1,
FrameworkStrategy.NETCOREAPP_3_0,
FrameworkStrategy.NETFRAMEWORK_4_7,
```

**KEEP**
```
FrameworkStrategy.NETSTANDARD_2_0,
FrameworkStrategy.NETSTANDARD_2_1,
FrameworkStrategy.NETCOREAPP_3_1,
FrameworkStrategy.NET_5_0,
FrameworkStrategy.NET_6_0
```

**Comment by devhl-labs** [comment]
Drop any frameworks past end of life, plus any generators that are defunct like NancyFx.
```
FrameworkStrategy.NETCOREAPP_2_0,
FrameworkStrategy.NETCOREAPP_2_1,
FrameworkStrategy.NETCOREAPP_3_0,
```

I like the idea of making the latest version the default. Users who insist on an old version should be specifying their needs instead of assuming we wont move forward.

Regarding specifying what framework is supported, it should depend on the library being used. RestSharp may work in all, but my Generic Host library can only go back to .net Standard 2.0. There is no generic host before that.

I was already planning on submitting some PRs for this, but I'm holding off on any more work until my Generic Host PR gets merged **cough @wing328  cough**
