### ISSUE TITLE
[BUG][typescript-fetch] Causing an error GlobalFetch not found

### ISSUE THREAD

**Issue by krupalpatel92** [OpenAPITools/openapi-generator#10684]
Generating OpenAPI with **typescript-fetch**
`npx openapi-generator-cli generate -i ./swagger.json -g typescript-fetch -o ./src/apis`

![image](https://user-images.githubusercontent.com/6726905/138608343-040872c6-5eb8-4b2e-82af-e422eec3d9b4.png)

##### Description

`"openapi": "3.0.0"`

##### openapi-generator version
![image](https://user-images.githubusercontent.com/6726905/138608442-b801c961-12d9-4e1f-b86c-f5d481ebb210.png)

**openapitools.json**
![image](https://user-images.githubusercontent.com/6726905/138608391-0ddfb309-b927-44da-ba5e-97641376c660.png)

##### Steps to reproduce
1. `create-react-app` with TypeScript

2. `npx openapi-generator-cli generate -i ./swagger.json -g typescript-fetch -o ./src/apis`

3. `yarn start`

##### Solution tried
But didn't worked
![image](https://user-images.githubusercontent.com/6726905/138609337-8a86478f-59af-4e55-b542-bf5539652bcf.png)

**Comment by DanielRuf** [comment]
If anyone stumbles upon this too, you have to add `--additional-properties=typescriptThreePlus=true` to the CLI command.

**Comment by bwaldvogel** [comment]
> If anyone stumbles upon this too, you have to add `--additional-properties=typescriptThreePlus=true` to the CLI command.

Looks like this is no longer necessary with version 6.0.0 because of https://github.com/OpenAPITools/openapi-generator/pull/12123.
