### ISSUE TITLE
[BUG] [Qt][server] Generated Code not buildable

### ISSUE THREAD

**Issue by dropedout** [OpenAPITools/openapi-generator#10706]
#### Bug Report Checklist

- [x ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generated server example code does not build.

dropedout:openapi$ cd petstore-server/server
dropedout:server$ make
Build Directory not existing, creating...
cd build && cmake ../.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/openapi/petstore-server/server/build
make -j8 -C build all
make[1]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
make[2]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
make[3]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
Scanning dependencies of target QHTTPENGINE
make[3]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
make[3]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
[  3%] Creating directories for 'QHTTPENGINE'
[  7%] Performing download step (git clone) for 'QHTTPENGINE'
Cloning into 'QHTTPENGINE'...
Already on 'master'
Your branch is up to date with 'origin/master'.
[ 14%] Performing update step for 'QHTTPENGINE'
[ 14%] No patch step for 'QHTTPENGINE'
Current branch master is up to date.
[ 18%] Performing configure step for 'QHTTPENGINE'
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build
[ 22%] Performing build step for 'QHTTPENGINE'
make[4]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[5]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
Scanning dependencies of target qhttpengine_autogen
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[  6%] Automatic MOC for target qhttpengine
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[  6%] Built target qhttpengine_autogen
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
Scanning dependencies of target qhttpengine
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[ 18%] Building CXX object src/CMakeFiles/qhttpengine.dir/qhttpengine_autogen/mocs_compilation.cpp.o
[ 18%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/filesystemhandler.cpp.o
[ 25%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/basicauthmiddleware.cpp.o
[ 31%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/handler.cpp.o
[ 37%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/parser.cpp.o
[ 43%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/range.cpp.o
[ 50%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/server.cpp.o
[ 56%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/socket.cpp.o
[ 62%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/qiodevicecopier.cpp.o
[ 68%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/localfile.cpp.o
[ 75%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/localauthmiddleware.cpp.o
[ 81%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/qobjecthandler.cpp.o
[ 87%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/proxyhandler.cpp.o
[ 93%] Building CXX object src/CMakeFiles/qhttpengine.dir/src/proxysocket.cpp.o
[100%] Linking CXX shared library libqhttpengine.so
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[100%] Built target qhttpengine
make[5]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[4]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[ 25%] Performing install step for 'QHTTPENGINE'
make[4]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[5]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[  6%] Automatic MOC for target qhttpengine
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[  6%] Built target qhttpengine_autogen
make[6]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
make[6]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[100%] Built target qhttpengine
make[5]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
Install the project...
-- Install configuration: ""
-- Installing: /tmp/openapi/petstore-server/server/external/lib/libqhttpengine.so.1.0.1
-- Installing: /tmp/openapi/petstore-server/server/external/lib/libqhttpengine.so.1
-- Installing: /tmp/openapi/petstore-server/server/external/lib/libqhttpengine.so
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/basicauthmiddleware.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/filesystemhandler.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/handler.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/ibytearray.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/localauthmiddleware.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/localfile.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/middleware.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/parser.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/proxyhandler.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/qiodevicecopier.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/qobjecthandler.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/range.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/server.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/socket.h
-- Installing: /tmp/openapi/petstore-server/server/external/include/qhttpengine/qhttpengine_export.h
-- Installing: /tmp/openapi/petstore-server/server/external/lib/cmake/qhttpengine/qhttpengineConfig.cmake
-- Installing: /tmp/openapi/petstore-server/server/external/lib/cmake/qhttpengine/qhttpengineConfig-noconfig.cmake
-- Installing: /tmp/openapi/petstore-server/server/external/lib/cmake/qhttpengine/qhttpengineConfigVersion.cmake
-- Installing: /tmp/openapi/petstore-server/server/external/lib/pkgconfig/qhttpengine.pc
make[4]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build/QHTTPENGINE-prefix/src/QHTTPENGINE-build'
[ 29%] Completed 'QHTTPENGINE'
make[3]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
[ 29%] Built target QHTTPENGINE
make[3]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
Scanning dependencies of target cpp-qt-qhttpengine-server_autogen
make[3]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
make[3]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
[ 33%] Automatic MOC for target cpp-qt-qhttpengine-server
make[3]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
[ 33%] Built target cpp-qt-qhttpengine-server_autogen
make[3]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
Scanning dependencies of target cpp-qt-qhttpengine-server
make[3]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
make[3]: Entering directory '/home/dropedout/src/openapi/petstore-server/server/build'
[ 40%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/cpp-qt-qhttpengine-server_autogen/mocs_compilation.cpp.o
[ 40%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/handlers/OAIApiRouter.cpp.o
[ 44%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/handlers/OAIPetApiHandler.cpp.o
[ 48%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/handlers/OAIStoreApiHandler.cpp.o
[ 51%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/handlers/OAIUserApiHandler.cpp.o
[ 55%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/main.cpp.o
[ 59%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/models/OAIApiResponse.cpp.o
[ 62%] Building CXX object src/CMakeFiles/cpp-qt-qhttpengine-server.dir/models/OAICategory.cpp.o
In file included from /tmp/openapi/petstore-server/server/build/src/cpp-qt-qhttpengine-server_autogen/XPTOFSH3MW/moc_OAIApiRouter.cpp:9:0,
                 from /tmp/openapi/petstore-server/server/build/src/cpp-qt-qhttpengine-server_autogen/mocs_compilation.cpp:2:
/tmp/openapi/petstore-server/server/build/src/../../../../../../../../home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIApiRouter.h: In member function ‘virtual void OpenAPI::OAIApiRequestHandler::process(QHttpEngine::Socket*, const QString&)’:
/tmp/openapi/petstore-server/server/build/src/../../../../../../../../home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:30: error: ‘Socket’ has not been declared
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                              ^~~~~~
/tmp/openapi/petstore-server/server/build/src/../../../../../../../../home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:74: error: ‘m’ was not declared in this scope
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                                                                          ^
/tmp/openapi/petstore-server/server/build/src/../../../../../../../../home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:74: note: suggested alternative: ‘tm’
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                                                                          ^
                                                                          tm
In file included from /tmp/openapi/petstore-server/server/src/main.cpp:27:0:
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h: In member function ‘virtual void OpenAPI::OAIApiRequestHandler::process(QHttpEngine::Socket*, const QString&)’:
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:30: error: ‘Socket’ has not been declared
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                              ^~~~~~
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:74: error: ‘m’ was not declared in this scope
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                                                                          ^
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:74: note: suggested alternative: ‘tm’
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                                                                          ^
                                                                          tm
In file included from /tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.cpp:19:0:
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h: In member function ‘virtual void OpenAPI::OAIApiRequestHandler::process(QHttpEngine::Socket*, const QString&)’:
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:30: error: ‘Socket’ has not been declared
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                              ^~~~~~
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:74: error: ‘m’ was not declared in this scope
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                                                                          ^
/tmp/openapi/petstore-server/server/src/handlers/OAIApiRouter.h:50:74: note: suggested alternative: ‘tm’
             connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
                                                                          ^
                                                                          tm
src/CMakeFiles/cpp-qt-qhttpengine-server.dir/build.make:130: recipe for target 'src/CMakeFiles/cpp-qt-qhttpengine-server.dir/main.cpp.o' failed
make[3]: *** [src/CMakeFiles/cpp-qt-qhttpengine-server.dir/main.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
src/CMakeFiles/cpp-qt-qhttpengine-server.dir/build.make:65: recipe for target 'src/CMakeFiles/cpp-qt-qhttpengine-server.dir/cpp-qt-qhttpengine-server_autogen/mocs_compilation.cpp.o' failed
make[3]: *** [src/CMakeFiles/cpp-qt-qhttpengine-server.dir/cpp-qt-qhttpengine-server_autogen/mocs_compilation.cpp.o] Error 1
src/CMakeFiles/cpp-qt-qhttpengine-server.dir/build.make:78: recipe for target 'src/CMakeFiles/cpp-qt-qhttpengine-server.dir/handlers/OAIApiRouter.cpp.o' failed
make[3]: *** [src/CMakeFiles/cpp-qt-qhttpengine-server.dir/handlers/OAIApiRouter.cpp.o] Error 1
make[3]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
CMakeFiles/Makefile2:124: recipe for target 'src/CMakeFiles/cpp-qt-qhttpengine-server.dir/all' failed
make[2]: *** [src/CMakeFiles/cpp-qt-qhttpengine-server.dir/all] Error 2
make[2]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/dropedout/src/openapi/petstore-server/server/build'
Makefile:21: recipe for target 'all' failed
make: *** [all] Error 2

##### openapi-generator version

5.3.0

##### OpenAPI declaration file content or url

Swagger Petstore 1.0.0 

##### Generation Details

dropedout:openapi$ java -jar openapi-generator-cli/openapi-generator-cli.jar generate -i openapi.yaml -g cpp-qt-qhttpengine-server -o petstore-server
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: cpp-qt-qhttpengine-server (server)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'cpp-qt-qhttpengine-server' is considered stable.
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] INFO  o.o.c.languages.AbstractCppCodegen - Environment variable CPP_POST_PROCESS_FILE not defined so the C++ code may not be properly formatted. To define it, try 'export CPP_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[main] INFO  o.o.c.languages.AbstractCppCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIApiResponse.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIApiResponse.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAICategory.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAICategory.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIOrder.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIOrder.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIPet.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIPet.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAITag.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAITag.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIUser.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIUser.cpp
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.DefaultCodegen - Multiple MediaTypes found, using only the first one
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/json)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] WARN  o.o.codegen.utils.ModelUtils - Multiple schemas found in the OAS 'content' section, returning only the first one (application/xml)
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIPetApiHandler.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/requests/OAIPetApiRequest.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIPetApiHandler.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/requests/OAIPetApiRequest.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIStoreApiHandler.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/requests/OAIStoreApiRequest.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIStoreApiHandler.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/requests/OAIStoreApiRequest.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIUserApiHandler.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/requests/OAIUserApiRequest.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIUserApiHandler.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/requests/OAIUserApiRequest.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIHelpers.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIHelpers.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIObject.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIEnum.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIHttpFileElement.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/models/OAIHttpFileElement.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIApiRouter.h
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/handlers/OAIApiRouter.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/main.cpp
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/src/CMakeLists.txt
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/README.MD
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/Makefile
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/CMakeLists.txt
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/Dockerfile
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/server/LICENSE.txt
[main] INFO  o.o.codegen.TemplateManager - Skipped /home/dropedout/src/openapi/petstore-server/.openapi-generator-ignore (Skipped by supportingFiles options supplied by user.)
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/.openapi-generator/VERSION
[main] INFO  o.o.codegen.TemplateManager - writing file /home/dropedout/src/openapi/petstore-server/.openapi-generator/FILES
################################################################################
# Thanks for using OpenAPI Generator.                                          #
# Please consider donation to help us maintain this project 🙏                 #
# https://opencollective.com/openapi_generator/donate                          #
################################################################################

##### Steps to reproduce

1. export openapi.yaml
2. download generator jar file
3. call generator
4. go to generated code
5. type "make"
6. try it in docker

##### Related issues/PRs

none seen in PR list.

##### Suggest a fix
change the mustache file to no generate this faulty line.

            connect(socket, &Socket::readChannelFinished, [this, socket, m]() {
correct is:
            connect(socket, &QHttpEngine::Socket::readChannelFinished, [this, socket]() {

**Comment by wing328** [comment]
@dropedout can you please pull the latest master to give it another try as #11177 has been merged into master? Thanks.

**Comment by dropedout** [comment]
Fixed, Danke schön!

**Comment by dropedout** [comment]
Will close this now. Thanks for taking issue into account.
