### ISSUE TITLE
[BUG] [Core] ByteArray is marked as String at the same time

### ISSUE THREAD

**Issue by ityuhui** [OpenAPITools/openapi-generator#10725]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Hi @wing328 

I think some recent change of `openapi-generator core` breaks a behavior:  

e.g.
```
        "data": {
          "additionalProperties": {
            "format": "byte",
            "type": "string"
          },
```

At before (on September 16, 2021), the `data` will be marked as "isString" : false, "isByteArray" : true,
but today I found it will be marked as "isString" : true, "isByteArray" : true,

Could you please give me some suggestions/clues about this problem ? Thanks.

Involve @zhemant 

##### openapi-generator version

master

##### Generation Details

```shell
java -DdebugModels -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i /path/swagger.json  -g c    -o ../output --skip-validate-spec > log.txt
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/10034

**Comment by wing328** [comment]
Can you please do a `git bisect` to identify the commit causing the issue?

**Comment by ityuhui** [comment]
Thank you @wing328 . It's a good idea !

I found the commit(https://github.com/OpenAPITools/openapi-generator/pull/10334/files) that caused this issue. And can succeed to fix it by https://github.com/OpenAPITools/openapi-generator/pull/10334/files#r739936935

Could you and @spacether @agilob @therve check my fix solution ? Or may I submit a PR directly for your review ?

**Comment by spacether** [comment]
Can you please submit a PR for review?

**Comment by ityuhui** [comment]
> Can you please submit a PR for review?

Sure.
