### ISSUE TITLE
[rust client] Include an option to not generate Box-ed model types

### ISSUE THREAD

**Issue by miterst** [OpenAPITools/openapi-generator#10730]
### Is your feature request related to a problem? Please describe.

Boxing model types by default is too strict for many cases and can lead to unergonomic code when you have to map types later.
It would be nice to have the option to generate models that don't have boxed types.

## Describe the solution you'd like

An additional property that can enable/disable boxing, something like `boxModelTypes` that can be `true` by default.

## Describe alternatives you've considered

Using [User-defined Templates](https://openapi-generator.tech/docs/customization/#user-defined-templates) could be a workaround.

**Comment by wing328** [comment]
@JMLX42 thanks for pointing it out

@miterst please give it a try
