### ISSUE TITLE
[BUG] [aspnetcore] Unable to set primitive datatypes (with default spec) to the defaults of the primitive data type

### ISSUE THREAD

**Issue by flobuc** [OpenAPITools/openapi-generator#10772]
##### Description
If you specify a primitive datatype model property (like boolean or number) with a default value in the OpenAPI Spec, then it is not possible to set this value to the default value of the primitive datatype.
Sounds crazy, and it drives you crazy.
For example if you specify a boolean with the default "true", you are not able to send this boolean to false. Or more confusing, if you specify a number with a default other than 0 (e.g. 12) then you can't send this number to 0 (all other values are working).

##### openapi-generator version
5.x and also 6.0.x

###### generators 
aspnetcore , maybe also other C# generators (csharp, csharp-netcore)

##### OpenAPI declaration

    components:
      schemas:
        TESTOBJECT:
          type: object
            properties:
              TESTPROP1:
                type: boolean
                description: a boolean with default true
                default: true
              TESTPROP2:
                type: number
                format: int32
                description: a number with default 12
                default: 12

##### Generation Details
    powershell docker run --rm -v %OUTPUT_DIRECTORY%:/out -v %INTERFACE_DIRECTORY%:/specs openapitools/openapi-generator-cli generate -i specs/%INTERFACE_FILE% -o /out -g aspnetcore --additional-properties aspnetCoreVersion=5.0,buildTarget=library,operationModifier=abstract,packageName=%PACKAGE_NAME%,packageVersion=%INTERFACE_VERSION%,enumValueSuffix=,removeEnumValuePrefix=false

##### Request-Json
    {
        "TESTPROP1": false,
        "TESTPROP2": 0
    }

##### Actual model values
    TESTOBJECT {
       TESTPROP1: true
       TESTPROP2: 12
    }

##### Expected model values
    TESTOBJECT {
       TESTPROP1: false
       TESTPROP2: 0
    }

##### Suggest a fix
The problem is that the generator is not handling the default values.
Actual generated TESTOBJECT class:

    [DataMember(Name="TESTPROP1", EmitDefaultValue=false)]
    public bool TESTPROP1{ get; set; } = true;
    
    [DataMember(Name="TESTPROP2", EmitDefaultValue=false)]
    public decimal TESTPROP2{ get; set; } = 12;

Per default "EmitDefaultValue=false". So there is no mapping _false_ for TESTPROP1, because _false_ is the default value for a boolean. So it is not possible to set TESTPROP1 to _false_.
Also _0_ is not mapped for TESTPROP2, because _0_ is the default value for a decimal.

The fix would be to change modle.mustache to generate:

    [DataMember(Name="TESTPROP1", EmitDefaultValue=false)]
    [DefaultValue(true)]
    public bool TESTPROP1{ get; set; } = true;
  
    [DataMember(Name="TESTPROP2", EmitDefaultValue=false)]
    [DefaultValue(12)]
    public decimal TESTPROP2{ get; set; } = 12;

So the default-value for the primitive data type is changed, and _false_ and _0_ would be mapped.
So far i can test it, it was working with .NET 5.0

###### Workaround
If it is possible to change the OpenAPI-Spec, then you can also set `nullable=true`:

    components:
      schemas:
        TESTOBJECT:
          type: object
            properties:
              TESTPROP1:
                type: boolean
                description: a boolean with default true
                default: true
                nullable: true
              TESTPROP2:
                type: number
                format: int32
                description: a number with default 12
                default: 12
                nullable: true

With this spec the current 5.x generator generates `EmitDefaultValue=true` for the properties, so that all values (default or not are always mapped). But this has the drawback, that the generated properties are then nullable:

    [DataMember(Name="TESTPROP1", EmitDefaultValue=true)]
    public bool? TESTPROP1{ get; set; } = true;
    
    [DataMember(Name="TESTPROP2", EmitDefaultValue=true)]
    public decimal? TESTPROP2{ get; set; } = 12;

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/3274
https://github.com/OpenAPITools/openapi-generator/issues/4346
https://github.com/OpenAPITools/openapi-generator/issues/9071

**Comment by intelMatan** [comment]
@wing328 Hi, I'm having the same issue where my nuget is being generated with EmitDefaultValue=false for an int with a default of -1 causing 0 to be treated as null. From all I see that should be solved by these changes but I don't see what version this was fixed on or how to fix it. I upgraded to version 6.5.0 of swashbuckle which is the latest version I think and the issue still happens.
this is what my property looks like:
```
[Range(-1, int.MaxValue / 60, ErrorMessage = "Can't be negative number other than -1, can't exceed max int divide by 60.")]
[DefaultValue(-1)]
public int TimeoutGracePeriodInMinutes { get; set; } = -1;
```

I got a suggestion to use ShouldSerialize functions but I feel there should be a simpler solution. Can you help?
