### ISSUE TITLE
[BUG] [csharp-netcore] config option library doesn't work

### ISSUE THREAD

**Issue by incoventures** [OpenAPITools/openapi-generator#10804]
Version 5.3.0
when running
`openapi-generator-cli generate -i properties.json -g csharp-netcore --additional-properties=library=httpclient`
the generated code still uses RestSharp instead of HttpClient

**Comment by snickler** [comment]
You have to use `library` as a parameter rather than using it in `additional-properties`.

Basically it'll work if you delete `additional-properties=` from your command

**Comment by MichaelAuckland** [comment]
It works, thank you. It may be worth updating the docs https://openapi-generator.tech/docs/generators/csharp-netcore/
