### ISSUE TITLE
[REQ] Generate classes with Swagger 3 (OpenAPI) annotations

### ISSUE THREAD

**Issue by kdebski85** [OpenAPITools/openapi-generator#10814]
Currently, OpenAPI generator generates Java classes with annotations like `io.swagger.annotations.Api` from Swagger 2 (`io.swagger:swagger-annotations`).

These annotations are incompatible with OpenAPI projects like Springdoc (https://springdoc.org/).

OpenAPI generator should instead generate classes with Swagger 3 (OpenAPI) annotations (`io.swagger.core.v3:swagger-annotations`). I do not see any reason why to still use Swagger 2 annotations.

**Comment by baurchanu** [comment]
@kdebski85 hi, is this the feature that you want? If so it was merged to master branch recently and will be included in the next release

https://github.com/OpenAPITools/openapi-generator/issues/9774
https://github.com/OpenAPITools/openapi-generator/pull/9775

**Comment by kdebski85** [comment]
@baurchanu This is exactly what I need. I hope 5.4.0/6.0.0 will be released soon, so I can try it.
Thank you!

Maybe after a few releases, the default value of `oas3` parameter should switch to `true`
