### ISSUE TITLE
[BUG] Missing @Path annotation in generated Java when only operation in path  

### ISSUE THREAD

**Issue by JDUNNIN** [OpenAPITools/openapi-generator#10813]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Updating from `4.3.1` to `5.3.0` and using templates created with output of `openapi-generator author template -g jaxrs-spec --library openliberty`. We customised some mustache files but removing our changes we observe the same error. We did not change `apiMethod.mustache` line 2 which seems to be where bug would be somewhere.
```
@Path("{{{path}}}"){{/subresourceOperation}}{{#hasConsumes}}
``` 
I find that an operation is missing an `@Path("/{id}")` annotation, but only when it is the only entry under path.

e.g. 
```
/test/{id}  <-- bug
/good/{id}  <-- good
/good

```
##### openapi-generator version

`5.3.0` from `4.3.1`

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2

info:
  title: Employees
  version: "1.0"
  description: bug

paths:
  /errorBadMappingRetryFail/{id}:
    get:
      summary: Get an employees details
      operationId: errorBadMappingRetryFail
      tags:
        - employeez
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/employee'
          description: Employee
          
components:
  schemas:
    employee:
      type: object
      example:
        firstName: firstName
        lastName: lastName
        id: id
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
```

##### Generation Details

Using Gradle plugin `id 'org.openapi.generator' version '5.3.0'`

##### Steps to reproduce

Attempt to generate Java code expecting this content:
```java
package com.example;

import com.example.api.model.Employee;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.ws.rs.*;
import javax.ws.rs.core.Application;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;
import javax.ws.rs.core.UriInfo;


import java.io.InputStream;
import java.util.Map;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.*;
import javax.validation.Valid;

@Path("/errorBadMappingRetryFail")
@ApplicationScoped
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJAXRSSpecServerCodegen", date = "2021-11-03T11:43:51.308Z[Europe/London]")
public class ErrorBadMappingRetryFailApi {

    // redacted custom template code

    @GET
    @Path("/{id}")
    @Produces({ "application/json" })
    public Response errorBadMappingRetryFail(@Context HttpServletRequest request, String body) {
        // method arguments customised above (bug present with base template)      ^
        // redacted custom code
    }

}
```

Actual result:
```java
package com.example;

import com.example.api.model.Employee;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.ws.rs.*;
import javax.ws.rs.core.Application;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;
import javax.ws.rs.core.UriInfo;


import java.io.InputStream;
import java.util.Map;
import java.util.List;
import javax.servlet.http.HttpServletRequest;
import javax.validation.constraints.*;
import javax.validation.Valid;

@Path("/errorBadMappingRetryFail")
@ApplicationScoped
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJAXRSSpecServerCodegen", date = "2021-11-03T11:43:51.308Z[Europe/London]")
public class ErrorBadMappingRetryFailApi {

    // redacted custom template code

    @GET
    // !!!!!!!! <-- missing @Path annotation
    @Produces({ "application/json" })
    public Response errorBadMappingRetryFail(@Context HttpServletRequest request, String body) {
        // method arguments customised above (bug present with base template)      ^
        // redacted custom code
    }

}
```
This causes calls to /errorBadMappingRetryFail/100 to fail with a 404 not found.

Workaround (not suitable for us):
Adding in another path into the OAS like `/errorBadMappingRetryFail` results in the correct annotation being applied to the above operation.

##### Suggest a fix

Verify behaviour of single method + operation paths with parameters in path.

**Comment by JDUNNIN** [comment]
This was user error. Did not update `api.mustache` to use `commonPath` instead of `baseName`. `commonPath` contains `/errorBadMappingRetryFail/{id}` when no method level specific path is needed i.e. is unique.

**Comment by Evynglais** [comment]
Hi,

I'm having this exact problem, but don't understand your solution. My `api.mustache` contains the same block:

```
{{#subresourceOperation}}@Path("{{{path}}}"){{/subresourceOperation}}
```

and it isn't replaced when I've got one route under `paths:`. Can you please explain what you changed in your template to get this to work?

**Comment by JDUNNIN** [comment]
@Evynglais it's been a long time and I forget exactly and my last comment isn't what I have in use today. 

My api.mustache has `@Path("/{{{baseName}}}")` and my `apiMethod.mustache` has `@Path("{{{path}}}")`

Hopefully this helps!
