### ISSUE TITLE
[BUG] [javascript][ApiClient] Fix request "responseType"

### ISSUE THREAD

**Issue by edouardmercier** [OpenAPITools/openapi-generator#10833]
In the `master` branch, the JavaScript ApiClient uses the `responseType`with value `string` when the `returnType`parameter is set to `String`, which, on its turns attempts to the superagent XMLHttpRequest `responseType` with value `string` (which is not supported and generates a warning on the browser developer tools console with message "The provided value 'string' is not a valid enum value of type XMLHttpRequestResponseType.", see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) instead of `text`. 

Could you please change line 522 of the file `src/main/resources/Javascript/ApiClient.mustache` with

```
request.responseType('text');
```
?

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix? Thanks.

**Comment by edouardmercier** [comment]
@wing328, I'd like to submit a pull request but it seems that I miss permissions on the GitHub project to do so: could you make sure that external contributors are allowed to submit a PR, please?

**Comment by code1x1** [comment]
@edouardmercier you can fork the repository and create a pull request targeting this repo like this :point_up_2: :smiley:
