### ISSUE TITLE
[REQ] [typescript-angular] Support Angular 13

### ISSUE THREAD

**Issue by arrigod** [OpenAPITools/openapi-generator#10831]
##### Description

I would like to have the API clients generated using ngVersion=13.0.0.

##### Suggest a fix/enhancement

Allow the ngVersion to be set to 13 and generate the code compatible with this Angular version.

**Comment by macjohnny** [comment]
would you like to contribute this feature?
see this example: https://github.com/OpenAPITools/openapi-generator/pull/10336

**Comment by icorne** [comment]
The PR has been open for a while now, can we get some progress on this?

**Comment by macjohnny** [comment]
@icorne happy ro review your PR

**Comment by icorne** [comment]
But there's already a PR open?

**Comment by macjohnny** [comment]
Sorry, my bad, didnt see the PR
