### ISSUE TITLE
Invalid code gen when property $refs another object property

### ISSUE THREAD

**Issue by infogulch** [OpenAPITools/openapi-generator#1087]
##### Description

When an object property `$ref`erences another object property, as in `properties: page: $ref: '#/components/schemas/PaginationEnvelope/properties/page'`, generated code expects the last path element (`page` in this case) to exist as a type, but since it's a property it doesn't exist as a type and generated code fails to compile.

This occurs in at least Java and Go. I suspect others too, but they are untested.

##### openapi-generator version

`3.3.0-SNAPSHOT` via `docker run --rm openapitools/openapi-generator-cli version`

##### OpenAPI declaration file content or url

Here is a minimal (validated) test spec that exhibits the error, along with samples of generated code in Go and Java:

https://gist.github.com/infogulch/3e94068fcd46dcbf199503b3deeb272c

The full spec that originally exhibited the issue can be found here: https://developers.linode.com/api/v4/openapi.yaml ([rendered](https://developers.linode.com/api/v4)). It successfully passed validation with `openapi-generator-cli validate`. I have the Go output hosted at [infogulch/linode-sdk-go](https://github.com/infogulch/linode-sdk-go) which is still in initial commits stages.

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
	-i /local/openapi.yaml \
	-g go \
	-o /local/lsdk
```

##### Steps to reproduce

1. Generate code from the above spec either java and go (other languages unknown)
2. Generated code does not compile due to missing definitions. Example output:
  ```
  .\model_inline_response_200.go:14:7: undefined: Page
  .\model_inline_response_200.go:15:8: undefined: Pages
  .\model_inline_response_200.go:16:10: undefined: Results
  ```

##### Related issues/PRs

I was unable to find similar issues.

##### Suggest a fix/enhancement

Change the generator so that when a property references another property, the type information of the referenced property is essentially *copied* to the reference site. I.e. render `schema/properties/page` in this:

```
(snip)
              schema:
                type: object
                properties:
                  page:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/page'

components:
  schemas:
    PaginationEnvelope:
      properties:
        page:
          type: integer
          readOnly: true
          example: 1
```

as if it were written like this:

```
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    readOnly: true
                    example: 1
```

**Comment by wheezil** [comment]
Apologies if this is a dumb question...  Perhaps we should be talking about two different things: $ref vs $is?  Is it always possible to decide which of these operations is intended by context?

**Comment by wheezil** [comment]
Yes, sorry I was speaking about a hypothetical other operator.  Can you link to the Linode API for my own study?

**Comment by infogulch** [comment]
Ah I see. I'm not sure I see the full utility of an $is op over a slightly more flexible $ref, at least for this case. Maybe it would let you skip repeating whole sections at any point in the tree? Actually that seems like it might be pretty useful.

Yes it is linked under the "OpenAPI declaration file content" section in the issue. Sorry I didn't make it more obvious, here it is again: https://developers.linode.com/api/v4#

**Comment by spacether** [comment]
When declaring the object of a response, if one property is declared as a reference to a property in a schema

That's not supported. Please open an issue in the Swagger Parser repo instead for such use case: https://github.com/swagger-api/swagger-parser
