### ISSUE TITLE
[BUG] openapi-generator-cli generates invalid C# source code for twitter api spec (Class names begin with numbers)

### ISSUE THREAD

**Issue by Trolldemorted** [OpenAPITools/openapi-generator#10897]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
openapi-generator-cli is unable to generate C# code for Twitter's spec

##### openapi-generator version
`5.3.1`

##### OpenAPI declaration file content or url
https://api.twitter.com/2/openapi.json

##### Generation Details
```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i https://api.twitter.com/2/openapi.json \
    -g csharp-netcore \
    -o /local/out/C#
```

##### Steps to reproduce
- Execute generation command
- Try to build the generated code
- Observe that the C# code does not build because C# class names must not begin with numbers

**Comment by wing328** [comment]
@Trolldemorted thanks for reporting the issue. I've fixed the issue via https://github.com/OpenAPITools/openapi-generator/pull/11330

Please give the latest master a try and let us know if you still experience the same issue.
