### ISSUE TITLE
[Swift5] Generate models where optional properties (`x-swift-always-encode`) can be flagged to explicitly encode nil when empty

### ISSUE THREAD

**Issue by jarrodparkes** [OpenAPITools/openapi-generator#10926]
### Description

For certain API's, you must explicitly set optional properties to "null" to achieve a desired outcome.

For example, consider an API with the endpoint `PATCH /appointment/{appointment_id}` where the request body can be used to set an appointment's start time to "null" — this might transition the appointment to a "reschedule" state:

```json
{
  "start_time": null
}
```

**As of `openapi-generator@5.3.1`, optional properties are only encoded if a value is present (`encodeIfPresent`)**. For example:

```swift
public struct AppointmentPatchPayload: Codable {

    public private(set) var startAt: Date?

    public init(startAt: Date? = nil) {
        self.startAt = startAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startAt = "start_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(startAt, forKey: .startAt)
    }
}
```

**This issue is a request to modify the swift5 generator so that optional properties can be flagged to explicitly encode nil when empty.**

### openapi-generator version

`openapi-generator@5.3.1`; not a regression

### OpenAPI declaration file content or url

```json
{
  "title": "AppointmentPatchPayload",
  "type": "object",
  "description": "Payload for patching an appointment.",
  "properties": {
    "start_at": {
      "type": "string",
      "description": "The new date and time (ISO 8601 format) when the appointment is set to start.",
      "format": "date-time"
    }
}
```

### Command line used for generation

```bash
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v5.3.1 generate \
    -I /local/spec/out/Aryeo/Aryeo.MERGED.json \
    -g swift5 \
    --additional-properties readonlyProperties=true,hashableModels=false \
    --skip-validate-spec \
    -o /local/sdk
```

### Steps to reproduce

1. Create a spec containing a model (ex: AppointmentPatchPayload) with an optional/nullable property
2. Run the `swift5` generator
3. Observe the model

### Related issues/PRs

- (`swift4`, nil/unwrap behavior) https://github.com/OpenAPITools/openapi-generator/pull/1527
- (add new extension) https://github.com/OpenAPITools/openapi-generator/issues/1916
- (extensions not being loaded) https://github.com/OpenAPITools/openapi-generator/issues/10133

### Suggest a fix/enhancement

Support an OAS extension such as `x-swift-always-encode` to inform the `swift5` generator to always encode a value for optional properties. The resulting model might look like this:

```swift
public struct AppointmentPatchPayload: Codable {

    public private(set) var startAt: Date?

    public init(startAt: Date? = nil) {
        self.startAt = startAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startAt = "start_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let startAt = startAt {
            try container.encode(startAt, forKey: .startAt)
        } else {
            try container.encodeNil(forKey: .startAt)
        }
    }
}
```

**Comment by jarrodparkes** [comment]
swift maintainers: 

@jgavris @ehyche @Edubits @jaz-ah @4brunu

**Comment by spacether** [comment]
Why not update your spec to define those request body schemas to be nullable: true?
This is a normal openapi use case

**Comment by jarrodparkes** [comment]
@spacether I'm pretty sure defining the bodies as nullable will not change how the models are generated. currently they are always generated in a way where all nullable/optional properties will not be encoded if the value is null. this means, it is impossible to create a request body like...

```swift
{
  "start_time": null
}
```

Right now, regardless of the nullable property, if the `start_time` is nil, then it would be encoded as...


```swift
{}
```

**Comment by spacether** [comment]
Ah, thank you for explaining that. In python we encone None as null so I wasn't aware of this problem. Thanks!

**Comment by jarrodparkes** [comment]
@spacether no problem 👍

I sort of assumed that is how the Swift models would work out-of-the-box too, but I think I can understand the for/against arguments. at any rate, looking forward to getting this to be configurable on Swift side 😎

**Comment by jarrodparkes** [comment]
After more research, it looks like I identified a bug with the `swift5` generator (see the discussion [here](https://github.com/OpenAPITools/openapi-generator/pull/10929#discussion_r759566647)). It should be the case that if a property is both nullable AND required, then it should always be encoded:

```json
{
  "title": "AppointmentPatchPayload",
  "type": "object",
  "description": "Payload for patching an appointment.",
  "properties": {
    "start_at": {
      "type": "string",
      "description": "The new date and time (ISO 8601 format) when the appointment is set to start.",
      "format": "date-time",
      "x-nullable": true
    }
  }
  "required": [
    "start_at"
  ]
}
```

Becomes

```swift
public struct AppointmentPatchPayload: Codable {

    public private(set) var startAt: Date?

    public init(startAt: Date? = nil) {
        self.startAt = startAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case startAt = "start_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        // will encode `null` if nil, otherwise will encode the date value
        try container.encode(startAt, forKey: .startAt)
    }
}
```
