### ISSUE TITLE
[PHP-slim][Bug] Security schemes are always basic in generated code

### ISSUE THREAD

**Issue by Newspaperman57** [OpenAPITools/openapi-generator#1092]
##### Description
The PHP-slim generator always generates basic authentication, regardless of what is described in the YAML-file.
The included yaml-file describes an endpoint with bearer-authentication, but php-slim generates a basic-authentication instead.

##### openapi-generator version
Compiled from commit 8fb3b707a1c4eb462b068bf2c2d20d570d4bb1d9 on master-branch.
3.3.0 SNAPSHOT Also has this issue

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  version: 1.0.0
  title: MWE

servers:
  - url: "example.com"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

security:
  - bearerAuth: []

paths:
  /bearerSecured:
    get:
      responses:
        200: 
          description: "Success"
```

##### Command line used for generation

Put the above code in a file called 'test.yaml' in the repo-root and run the following command:
```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i test.yaml -g php-slim -o out
```
##### Steps to reproduce

Follow the steps above.
The wrong code can be found in /out/lib/SlimRouter.php at line 62, where it defines the basic authentication method:
```php
$basicAuth = new HttpBasicAuthentication([
    "secure" => false,
    "authenticator" => function ($arguments) {
        $user = $arguments["user"];
        $password = $arguments["password"];
        return false;
    }
]);
```

##### Related issues/PRs
Have not been able to find anything similar from php-slim 
##### Suggest a fix/enhancement

**Comment by macjohnny** [comment]
maybe @ybelenko has an idea?

**Comment by ybelenko** [comment]
First of all, only Basic security scheme is implemented in current PHP Slim generator. Other security schemes are ignored for now.
https://github.com/OpenAPITools/openapi-generator/blob/8fb3b707a1c4eb462b068bf2c2d20d570d4bb1d9/modules/openapi-generator/src/main/resources/php-slim-server/SlimRouter.mustache#L87-L94
Looks correct, please check if `$basicAuth` closure is applied to wrong endpoints, if so give us an example of `SlimRouter.php`.

**Comment by Newspaperman57** [comment]
Okay, thanks. I will implement what i need by hand then

**Comment by macjohnny** [comment]
@Newspaperman57 you could also try to improve https://github.com/OpenAPITools/openapi-generator/blob/8fb3b707a1c4eb462b068bf2c2d20d570d4bb1d9/modules/openapi-generator/src/main/resources/php-slim-server/SlimRouter.mustache#L87-L94 so that other users can benefit, too.

**Comment by ybelenko** [comment]
The major difficult to implement other security schemes was that it's rational to use welltested 3rd party middlewares. And it's important for all middlewares to follow same code pattern. I've done an investigation and found that most of authentication middlewares for Slim accept `authenticator` function.

Ref: [Middleware for Slim Framework v.3x](https://github.com/slimphp/Slim/wiki/Middleware-for-Slim-Framework-v3.x)

It seems to me that [Slim Token Authentication](https://github.com/dyorg/slim-token-authentication) package can cover both `apiKey` and `oauth2` schemes. After that only one key feature left, signing of `oauth2` token. I was planning to add these middlewares, but then I was more focused on unit tests enhancements for Slim codegen.

**Comment by Newspaperman57** [comment]
@ybelenko Sorry, i changed over to using Python as my backend as i have used it before and would be easier than learning a new framework in PHP from scratch, now when i had to write it from bottom myself.
