### ISSUE TITLE
[BUG] [swift5] Swift client does not respect explode: false for array query params

### ISSUE THREAD

**Issue by reubits** [OpenAPITools/openapi-generator#10944]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I was using the swift5 generated client with an array query parameter with `style: form` and `explode: false` expecting it to generate the query with comma-separated values as documented here:

https://swagger.io/docs/specification/serialization/#query

e.g. with the sample Pets API, `findPetsByStatus` with explode set to false for the `status` param produces this:

`http://petstore.swagger.io/v2/pet/findByStatus?status=available&status=another`

instead of this:

`http://petstore.swagger.io/v2/pet/findByStatus?status=available,another`

I get the same result as with `explode: true`. This was observed with both URLSession and Alamofire implementations.

##### openapi-generator version

5.3.0 (but also tested on 5.3.1, 5.4.0, 6.0.0)

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/reubits/PETS/main/petstore.yaml

##### Generation Details

`openapi-generator -i petstore.yaml -g swift5 -o OpenAPI --library alamofire`

##### Steps to reproduce

Run this sample project: 

https://github.com/reubits/PETS

and see `http://petstore.swagger.io/v2/pet/findByStatus?status=available&status=another` in the logs.

Expected: `http://petstore.swagger.io/v2/pet/findByStatus?status=available,another`

##### Suggest a fix

The generated helper function `APIHelper.mapValuesToQueryItems` seems to be unconditionally exploding the query params, e.g.

```
APIHelper.mapValuesToQueryItems([
            "status": status.encodeToJSON(),
        ])
```

**Comment by 4brunu** [comment]
@reubits could you please open a PR?

**Comment by reubits** [comment]
> @reubits could you please open a PR?

@4brunu yes I plan to but haven't had time yet.

**Comment by 4brunu** [comment]
Sure, when you have time 👍

**Comment by Jonas1893** [comment]
Hi @4brunu I gave it a shot and opened PR #13202 which should fix it. It would be great if you could have a look at it and provide some feedback 🙏
