### ISSUE TITLE
[BUG] [Typescript] Bug generating an unwanted wrapper object for the requests

### ISSUE THREAD

**Issue by mourad1081** [OpenAPITools/openapi-generator#10955]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

openapi-generator generates a wrapper around my object even though it should not to be compatible with the backend.

##### openapi-generator version

5.3.0

##### OpenAPI declaration file content or url

```yaml
  /api/users/login/:
    post:
      operationId: api_users_login_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
        required: true
      ...
```

##### Generation Details
```sh
openapi-generator-cli generate -i ./schema.yml -g typescript-fetch -o ./frontend/src/minerva2-api --additional-properties=supportsES6=true
```

generates this object: 

```ts
export interface ApiUsersLoginCreateRequest {
    credentials: Credentials;
}
```

whereas it would have been better to generate this:

```ts
export type ApiUsersLoginCreateRequest = Credentials;
```

or accept a Credentials as parameter of the api call. Instead, here is the api call that is generated:

```ts
async apiUsersLoginCreate(requestParameters: ApiUsersLoginCreateRequest, ...): Promise<...> {
    ...
}
```

My backend expects a Credentials object, not that weird wrapper.

##### Steps to reproduce
Simply use my yaml snippet

##### Suggest a fix

Is there an option to remove these unwanted wrappers?

**Comment by mourad1081** [comment]
Fixed by setting `useSingleRequestParameter` to false.

e.g.

```sh
openapi-generator-cli generate -i ./schema.yaml -g typescript-fetch -o ./frontend/src/minerva2-api --additional-properties=supportsES6=true,useSingleRequestParameter=false
```

**Comment by yankang-is24** [comment]
Setting `useSingleRequestParameter` to `false` was not helping me, I have to remove the option.
