### ISSUE TITLE
[BUG] [Java] The Java openapi client doesn't send query parameters that contain spaces.

### ISSUE THREAD

**Issue by alanxoc3** [OpenAPITools/openapi-generator#11032]
##### Description

The client that gets generated for java doesn't allow query parameters that only contain whitespace. Like "%20%20%0A". When the generated client makes a request like that, it will send an empty string instead.

The fix should be to just remove these lines: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/Pair.mustache#L44-L46

The original commit this came from is: https://github.com/OpenAPITools/openapi-generator/commit/7a9a41fe01d4c7d1f7bfc53c2c36440913c43e84

I don't understand why it would be a good idea to trim spaces here, hence the bug report.

##### openapi-generator version

master, see description.

##### Steps to reproduce

Pass just spaces as a query parameter to a generated java client. That query parameter will be empty before it sends the request.

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix?

**Comment by alanxoc3** [comment]
I just saw this. I'll get that done by tomorrow.

**Comment by alanxoc3** [comment]
Finally created it (a week later).

**Comment by alanxoc3** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/11160
