### ISSUE TITLE
[BUG] Empty schema not working anymore since v5.3.0

### ISSUE THREAD

**Issue by ramondeklein** [OpenAPITools/openapi-generator#11052]
Suppose I have a method that accepts any input in the body:
```yaml
---
openapi: 3.0.1
info:
  title: TEST
  version: v1
servers:
- url: http://localhost/
paths:
  "/":
    put:
      operationId: test
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        '204':
          description: Success
```
When using the `typescript-angular` converter, this resulted in the following method in `default.service.ts` (using v5.2.1):
```typescript
public test(body?: any, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined}): Observable<any>;
```
When using v5.3.0 the following method is generated:
```typescript
public test(UNKNOWN_PARAM_NAME?: , observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext}): Observable<any>;
```
No warnings are issued during code-generation and it's not related to the Typescript generator, because it also generates similar code for the C# and Java generators (all invalid syntax).

**Comment by ramondeklein** [comment]
A workaround is to use a schema that look like this:
```yaml
---
openapi: 3.0.1
info:
  title: TEST
  version: v1
servers:
- url: localhost/
paths:
  "/":
    put:
      operationId: test
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
          text/json:
            schema:
              type: object
          application/*+json:
            schema:
              type: object
      responses:
        '204':
          description: Success
```
This schema is more appropriate and also ensure that everything is working with v5.3.0+ generators again.

**Comment by ramondeklein** [comment]
I would prefer to have the situation from v5.2.1 back again. I guess it was introduced with PR #10334 where there are a lot of changes regarding to *any* types have been made.

**Comment by spacether** [comment]
Thank you for reporting this; I have a PR to fix it in the works; waiting for tests to pass on it now

**Comment by spacether** [comment]
@ramondeklein can you rebase on master and see if my merged fix solves the issue for you?

**Comment by ramondeklein** [comment]
@spacether I won't be back in the office until Wednesday, so it may take a while to check.

**Comment by ramondeklein** [comment]
@spacether It now generates a proper `body?: any` again, so this seems to be fixed. Thanks for fixing this. 👍🏻

**Comment by r-token** [comment]
@spacether I am seeing that `UNKNOWN_PARAM_NAME` issue again on v7.1.0. Version 6.6.0 does not have this problem. Building for a Swift 5 application.

**Comment by spacether** [comment]
I am no longer contributing to this project. Please reach out to active maintainers in github or Slack for help with this.

**Comment by r-token** [comment]
Whoops, sorry about that. @wing328 are you the right person to flag for this `UNKNOWN_PARAM_NAME` issue?

**Comment by edvinasstaupas** [comment]
@r-token have you open a new issue or found a fix for this?

**Comment by r-token** [comment]
@edvinasstaupas I have not. My team switched over to using the Java-based [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) instead to work around this problem. Unsure if it is still an issue in later versions after v7.1.0.

**Comment by wing328** [comment]
I did another tests with the latest master and no longer seeing the UNKNOWN_PARAM_NAME issue
```
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public test(body?: any, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public test(body?: any, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public test(body?: any, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public test(body?: any, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any> {

        let localVarHeaders = this.defaultHeaders;

```
