### ISSUE TITLE
[HELP] [swift5] Making multipart/form-data requests

### ISSUE THREAD

**Issue by denizdogan** [OpenAPITools/openapi-generator#11083]
What is the correct way of making multipart/form-data requests in Swift 5?

I've tried overriding the `Content-Type` header to `multipart/form-data` in my request builder factory, but the client still sends a request like:

```json
{"jsonData": {"video": "file://..."}}
```

Where is `"jsonData"` even coming from? It's not part of any of my models, it seems like something internal? I feel like I'm missing the place where I'm supposed to override something?

Many thanks!

**Comment by denizdogan** [comment]
@4brunu You've been super helpful with the other issues, hope you don't mind me pinging you about this one :)

**Comment by 4brunu** [comment]
You don't have to do nothing in the client side.
In the spec the ContentType of the endpoint must be specified as `multipart/form-data` and the swift generator, will automatically use the correct encoding. 

```
if contentType == "application/json" {
                encoding = JSONDataEncoding()
            } else if contentType == "multipart/form-data" {
                encoding = FormDataEncoding(contentTypeForFormPart: contentTypeForFormPart(fileURL:))
            } else if contentType == "application/x-www-form-urlencoded" {
                encoding = FormURLEncoding()
            } else {
                fatalError("Unsupported Media Type - \(contentType)")
            }
```

**Comment by denizdogan** [comment]
@4brunu That makes sense. The OpenAPI spec had the following:

```yaml
application/json:
  schema:
    $ref: '#/components/schemas/MyRequest'
application/x-www-form-urlencoded:
  schema:
    $ref: '#/components/schemas/MyRequest'
multipart/form-data:
  schema:
    $ref: '#/components/schemas/MyRequest'
```

So I was thinking there'd be something in the client that would let me "manually" pic the multipart/form-data version, but I was able to fix this on the server side instead! Thanks again :)

**Comment by 4brunu** [comment]
I'm grad the problem is fixed 👍
