### ISSUE TITLE
[rust-server] non-valid Rust produced in switch to OpenAPI v3

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#111]
The `rust-server` generator currently doesn't produce valid Rust. Let's fix this.  

Current known problems:
- [ ] Lots of TODOs/commented out code in RustServerCodegen.java
- [ ] Lingering references to 'swagger-codegen'
- [ ] It looks as if we used to do some sort of custom reference parsing. We end up with e.g. `    SuccessfulOperation ( #/components/schemas/Pet )`. It looks as if a fix for a similar issue recently went in https://github.com/OpenAPITools/openapi-generator/commit/d690f429dfa8918776537961468a1fb5e3f4b1ef - maybe we can do the same thing here?
- [ ] `pub struct ApiResponse(object);`
- [ ] CI

CI aside, this issue can be closed when `./bin/rust-server-petstore.sh` produces valid Rust.

(I may take a look at this at some point, but suspect it's unlikely in the immediate future. Others are very welcome to pick this up - I'd be happy to help/support such an effort.)

**Comment by onelson** [comment]
I noticed invalid rust on when trying to generate a client from a 3rd party service. Would the work for rust-server include the client generator?

As I understood it, `-server` was shorthand for both client and server. Is that right?

**Comment by bjgill** [comment]
I'm just working on `rust-server`, but (despite the name) that is a dual client+server generator. There's an issue for the current state of confusion: https://github.com/OpenAPITools/openapi-generator/issues/164
