### ISSUE TITLE
[BUG] [Swift5] special characters in enum values lead to Xcode compile error

### ISSUE THREAD

**Issue by mbruegmann** [OpenAPITools/openapi-generator#11107]
#### Bug Report Checklist

- [x] Have you provided a ~~full~~/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

EnumValues with special characters will produce enum var names with special characters which causes compile errors in Xcode.
In our example we have the following property:
```
 "aspectRatio" : {
          "type" : "string",
          "enum" : [ "1:1", "4:5", "4:3", "9:16", "16:9" ]
        }
```
... generating this code:
```
 public enum AspectRatio: String, Codable, CaseIterable {
        case _1:1 = "1:1"
        case _4:5 = "4:5"
        case _4:3 = "4:3"
        case _9:16 = "9:16"
        case _16:9 = "16:9"
    }
```

##### openapi-generator version

5.3.1

##### Generation Details

swift5

##### Suggest a fix

Add `.replaceAll("\\W+", "_")` in `public String toEnumVarName(String name, String datatype)` in class `Swift5ClientCodegen`.
This is also done in the `DefaultCodegen` class and in some of the other generator classes.

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix? Thanks.

**Comment by 4brunu** [comment]
I think this issue can now be closed
