### ISSUE TITLE
[REQ] [typescript-fetch] useSingleRequestParameter should mark parameter optional if all properties are optional 

### ISSUE THREAD

**Issue by davidgamero** [OpenAPITools/openapi-generator#11112]
### Is your feature request related to a problem? Please describe.

when useSingleRequestParameter has all optional parameters, an empty object still has to be passed producing `myApiCall({})` 

## Describe the solution you'd like

Functions with all optional parameters should include a default empty object parameter to make it optional instead of `myApiCall({})` 

When the default is in place, we can instead use `myApiCall()` 

See #6477 and related #6440

## Describe alternatives you've considered

Instead of making the parameter object itself optional, we can use the solution employed in the referenced PR to default which will effectively make it optional too

**Comment by gambtho** [comment]
resolves a problem we were having also, thanks @davidgamero

**Comment by Marcus-Hines** [comment]
I would love to see this change made.
