### ISSUE TITLE
Allow the user to pass in any headers per request.

### ISSUE THREAD

**Issue by Amelia0193** [OpenAPITools/openapi-generator#11139]
### Is your feature request related to a problem? Please describe.

User cannot pass a header parameter different from the ones in all_params to the request level. 

## Describe the solution you'd like

The header_params will be updated to get all the headers the users passed in, if none is defaulting to {}.

## Describe alternatives you've considered

Specify the header needed in the all_params and append it to the header_params. But you need to do that for all the parameters the user want to support. The above solution is a more generic one which I think simplifies and helps for the future.

**Comment by spacether** [comment]
@Amelia0193 which generator does this issue apply to? python-legacy?

**Comment by Amelia0193** [comment]
@spacether  Yes, is the python-legacy.
