### ISSUE TITLE
[BUG] [Java Spring OAS3] api.mustache does not import Hidden annotation when oas3 is enabled

### ISSUE THREAD

**Issue by jameswynn** [OpenAPITools/openapi-generator#11168]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When oas3 is enabled, the Hidden annotation should be imported. It is used by ServerWebExchange and Pageable.

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
paths:
  /thingy:
    get:
      operationId: get
      x-spring-paginated: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseList'
components:
  schemas:
    ResponseList:
      type: array
      items:
        $ref: '#/components/schemas/ResponseEntry'
    ResponseEntry:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
```

##### Generation Details

Generator name: spring
Library: spring-cloud
Config options:
 - oas3: true

###### Generated Code from an API:

```java
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
```

###### Expected Code from an API:

```java
import io.swagger.v3.oas.annotations.Hidden;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
```

##### Suggest a fix

Add a new import statement around line 11 of JavaSpring/api.mustache inside the oas3 block.

```java
import io.swagger.v3.oas.annotations.Hidden;
```

**Comment by wing328** [comment]
Closed via #11181. Please pull the latest master to give it another try.
