### ISSUE TITLE
Use type imports in typescript templates

### ISSUE THREAD

**Issue by wallw-teal** [OpenAPITools/openapi-generator#11179]
This is specifically for `typescript-fetch`, but may be applicable to all the TS templates:

The issue we are having is related to using `preserveValueImports` and `isolatedModules` in the TS config with TypeScript 4.5+. These are common config values for Svelte or Vue projects with TypeScript integration.
```
TS1444: 'ClassName' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.
```
(where "ClassName" is a model or api class)

Basically, it is complaining that one of the imports is only used as a type (which is true), and therefore should be `import type SomeType from ...;` instead.

## Describe the solution you'd like

I would like to see TS 3.8+ use type imports for imports which are only used as types.

## Describe alternatives you've considered

I am currently looking into simply suppressing the warning for our generated code only. Additionally, it may be possible to post process the files and fix them.

I can potentially help out with a PR if the team is amenable to this change, but I am not familiar enough with the templating system to know whether there is sufficient information there to only modify the template or if a larger change would be necessary.

**Comment by wallw-bits** [comment]
I am able to use template overrides to achieve that, so I think it should be possible to just update the templates. Here are my changes (which would probably need to be sequestered to 3.8+ in a PR here):

`apis.mustache`
```
import * as runtime from '../runtime';
{{#imports.0}}
import type {
    {{#imports}}
    {{className}},
    {{/imports}}
} from '../models';

import {
    {{#imports}}
    {{^withoutRuntimeChecks}}
    {{className}}FromJSON,
    {{className}}ToJSON,
    {{/withoutRuntimeChecks}}
    {{/imports}}
} from '../models';
{{/imports.0}}
```

`modelGeneric.mustache`
```
{{#imports}}
import type {
  {{{.}}},
} from './{{.}}';

import {
    {{.}}FromJSON,
    {{.}}FromJSONTyped,
    {{.}}ToJSON,
} from './{{.}}';
{{/imports}}
```

`modelOneOf.mustache`
```
{{#imports}}
import type {
  {{{.}}},
} from './{{.}}';

import {
    {{.}}FromJSON,
    {{.}}FromJSONTyped,
    {{.}}ToJSON,
} from './{{.}}';
{{/imports}}
```

**Comment by macjohnny** [comment]
The fix was merged in https://github.com/OpenAPITools/openapi-generator/pull/12534 and is available in the current snapshot version
