### ISSUE TITLE
[BUG] [swift5] modelNamePrefix gets prepended to AnyCodable

### ISSUE THREAD

**Issue by denizdogan** [OpenAPITools/openapi-generator#11185]
With `modelNamePrefix` set to `Foo`, all occurrences of `AnyCodable` in the generated models get named `FooAnyCodable`. Any ideas on how to fix this? I couldn't figure out where this happens exactly.

**Comment by 4brunu** [comment]
The solution may be in the file `Swift5ClientCodegen` add `AnyCodable` to the list of `reservedWords`, if this doesn't work, some custom logic in the method `toModelName` to avoid adding the prefix to `AnyCodable` maybe can do the trick

**Comment by faisalqublan** [comment]
Happens to me too, for `modelNamePrefix` and `modelNameSuffix`, any fix yet?
