### ISSUE TITLE
dart-dio-next: DioError [DioErrorType.other]: FormatException: Invalid HTTP header field value

### ISSUE THREAD

**Issue by srix55** [OpenAPITools/openapi-generator#11192]
[dart-dio-next] Error on setting header object
##### Description

Header json objects are allowed. I am trying to send in a header object that's defined in the openapi spec. Here's the api side.
```yaml
createRegistrationCode:
  get:
    summary: Get a registration code for adding a new player
    operationId: createRegistrationCode
    parameters:
      - in: header
        name: tracer
        schema:
          $ref: '../common/models/tracer.yaml#/Tracer'
    responses:
      '200': ...
```
I am generating the dart-dio-next client and setting the object without any complaints.
However, when I run it, I get the following error. That's the complete object I am sending. Note that the '\n's are pasted as is - that's not my intervention.
```
flutter: DioError [DioErrorType.other]: FormatException: Invalid HTTP header field value: "Tracer {\n  tracerId=TracerId {\n    userId=_user_,\n    timestamp=1640694471654,\n    sequence=1,\n    deviceInstanceId=Wiyhnm,\n  },\n  taskName=RegistrationCubit: Fetching data,\n  traces=[Trace {\n    timestamp=1640694471654,\n    subTaskName=RegistrationCubit: Fetching data,\n    message=,\n    traceState=start,\n  }, Trace {\n    timestamp=1640694471656,\n    subTaskName=CreateRegistrationCodeRepoImpl: createRegistrationCode,\n    message=,\n    traceState=start,\n  }],\n  metrics=[],\n  deviceDetails=DeviceDetails {\n    installationType=web,\n    deviceInfo=,\n  },\n}" (at character 9)
Tracer {
        ^
```

##### openapi-generator version

latest generator - 5.3.0 

Let me know what I can do. Thanks.

**Comment by kuhnroyal** [comment]
Can you add the stacktrace please

**Comment by kuhnroyal** [comment]
Try to sett if you can set the header on the Dart `HttpHeaders`.
Maybe you need to encode it to json before setting it.

**Comment by kuhnroyal** [comment]
@srix55 Any new information?

**Comment by srix55** [comment]
@kuhnroyal sorry for the delay. Let me look into it this weekend.

**Comment by srix55** [comment]
Hi @kuhnroyal it looks like headers are supposed to be strings. Even if I make custom objects out of it in my openAPI specs, the web server implementations with RestEasy complain on it. The error "Invalid HTTP header field value" is right. I guess the OpenAPI specs definition should not be saying that headers can be custom objects. I'm closing this error. Thanks for looking into it.

**Comment by kuhnroyal** [comment]
If you want to transmit objects as headers, you probably need an opinionated serialization mechanism on client and server. This is nothing we can provide out of the box.
