### ISSUE TITLE
[C#] Use html entities in javadoc of generated code

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#112]
##### Description

Similar to https://github.com/OpenAPITools/openapi-generator/pull/106, we want to apply similar fix to C# client: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp/api.mustache#L33

##### openapi-generator version

Latest master

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp/api.mustache#L33

##### Suggest a fix/enhancement

This change should be fairly straightforward. If anyone wants to help on this, please reply to let us know.

**Comment by albator1932** [comment]
Hi guys,

I checked the source and it appears that it is already {{.}} instead of {{{.}}} (which looks like correct to me).
Is this still an issue or am I missing something?

**Comment by wing328** [comment]
@albator1932 thanks for the review. I couldn't find again on which line we need to apply similar fix. If I find it, I'll reopen this issue to let you know.

Thanks again for offering help on this.
