### ISSUE TITLE
[BUG][JAVA] Path parameter encoding is using + instead of %20 for white spaces

### ISSUE THREAD

**Issue by sorin-florea** [OpenAPITools/openapi-generator#11242]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Path parameter encoding is using `+` instead of `%20` for white spaces when using `native` library for java.
The generated code is using `ApiClient.urlEncode(param.toString())` which in turn uses `URLEncoder.encode(s, UTF_8)`.

##### openapi-generator version

5.3.0 and master

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Bug reproducer
  description: API for param encoding
  version: "1.0.0"
servers:
  - url: localhost:8080
paths:
  /api/{someParam}:
    parameters:
      - in: path
        name: someParam
        schema:
          type: string
        required: true
        description: Some parameter.
    get:
      operationId: GetSomeParam
      summary: View some param
      responses:
        '200':
          description: Some return value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SomeReturnValue'
              example:
                someParam: someValue
components:
  schemas:
    SomeReturnValue:
      type: object
      required:
        - someParam
      properties:
        someParam:
          type: string
```

```json

{
  "library": "native",
  "dateLibrary": "java8",
  "modelPackage": "com.api.model",
  "apiPackage": "com.api",
  "invokerPackage": "com.api.client",
  "hideGenerationTimestamp": true,
  "openApiNullable": false,
  "useBeanValidation": false,
  "additionalModelTypeAnnotations": "@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)"
}

```

##### Generation Details

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java --library native -i  openapi.yaml -o client-test

##### Steps to reproduce

- generate client and call `api.getSomeParam("some parameter");`
- observe that the path is `http://localhost:8080/api/some+parameter`

##### Suggest a fix

Change encoding of path params when using the `native` library for java similar to okhttp implementation `URLEncoder.encode(str, "utf8").replaceAll("\\+", "%20");`

**Comment by wing328** [comment]
@sorin-florea thanks for reporting the issue. Can you please file a PR with the suggested fix?

**Comment by sorin-florea** [comment]
@wing328 will do

**Comment by sorin-florea** [comment]
@wing328 https://github.com/OpenAPITools/openapi-generator/pull/11257
