### ISSUE TITLE
[BUG] Generator discards plus and minus in timezone definitions and generates duplicate entries in enum

### ISSUE THREAD

**Issue by neeohw** [OpenAPITools/openapi-generator#11265]
##### Description

The csharp-netcore generator generates duplicate entries in the Timezone.cs model when all official timezones are defined in the openapi declaration. 

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or url

https://www.apimatic.io/api/api-entities/IJt6KSX8DsZ7zG62WC5QTePNRL9NzqNhZiMMj_PvGxGtPr0lRXN_EufgKn3frPaP/published-artifacts/transformations/generated-file?format=OpenApi3Yaml

##### Generation Details

Generate the client with openapi generator generate -g csharp-netcore

##### Steps to reproduce

- Download declaration from WePay dev: https://www.apimatic.io/api/api-entities/IJt6KSX8DsZ7zG62WC5QTePNRL9NzqNhZiMMj_PvGxGtPr0lRXN_EufgKn3frPaP/published-artifacts/transformations/generated-file?format=OpenApi3Yaml
- Generate the client with openapi generator generate -g csharp-netcore
- Observe Timezone.cs in the model directory to have twice EtcGMT0, EtcGMT1 ... because the input spec has both Etc/GMT+0 and Etc/GMT-0. These are official timezones.

##### Suggest a fix

Don't just drop special characters but replace them with their "word equivalent": + becomes "plus" and - becomes "minus"

**Comment by jornhd** [comment]
**Please fix this!** I'm facing the same problem with this enum:
```
"area": {
    "type": "string",
    "enum": ["AAB", "AAB+", "No area"]
}
```
This results in
```csharp
  public enum AreaEnum
  {
      /// <summary>
      /// Enum AAB for value: AAB
      /// </summary>
      [EnumMember(Value = "AAB")]
      AAB = 1,

      /// <summary>
      /// Enum AAB for value: AAB+
      /// </summary>
      [EnumMember(Value = "AAB+")]
      AAB = 2,

      /// <summary>
      /// Enum NoArea for value: No area
      /// </summary>
      [EnumMember(Value = "No area")]
      NoArea = 3
   }
```
where the generated enum class has **two** values named "AAB". 
A good solution would be as suggested to replace '+' sign with 'Plus' so "ABB+" becomes "AABPlus". Removing space and use PascalCase like in "NoArea" is fine though,

```csharp
            [EnumMember(Value = "AAB+")]
            AABPlus = 2,
```

**Comment by wing328** [comment]
please use the enumNameMapping option to have complete control of the enum naming:

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping
