### ISSUE TITLE
[BUG] NullPointerException when loading configuration

### ISSUE THREAD

**Issue by idkCpp** [OpenAPITools/openapi-generator#11276]
##### Description

I have an automatic build pipeline that uses the openapi generator to create a python-flask server.
Today the builds started failing with a NullPointerException and the below mentioned stack-trace.

##### openapi-generator version

I use the following Docker Image:
```openapitools/openapi-generator-cli                           latest           132da9168d58```

##### OpenAPI declaration file content or url

Seems to be irrelevant, also happens with the swagger petstore.

##### Generation Details

```
docker run --rm -u $(id -u) -v "$(pwd):/local" openapitools/openapi-generator-cli generate -i /local/openapi.yaml -g python-flask -o /local/app -c /local/config.json --package-name PKGNAM --skip-operation-example
```

Contents of `config.json`:
```json
{
        "packageName": "PKGNAM",
        "serverPort": "8080"
}
```

##### Output

```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.lang.String.concat(Unknown Source)
	at org.openapitools.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:48)
	at org.openapitools.codegen.config.CodegenConfigurator.fromFile(CodegenConfigurator.java:94)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:272)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

**Comment by JLEdward** [comment]
Also starting to get this NullPointerException from yesterday. Strangely I do not see any version changes on the openapi-generator-cli.jar:

> $ java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar version
> 5.4.0-SNAPSHOT
Anyone aware of any solution to this please?

**Comment by willgit-sl** [comment]
> Also starting to get this NullPointerException from yesterday. Strangely I do not see any version changes on the openapi-generator-cli.jar:
> 
> > $ java -jar /opt/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar version
> > 5.4.0-SNAPSHOT
> 
> Anyone aware of any solution to this please? For now I'm reverting to 5.3.1.

I'm seeing the same issue.  Didn't have to go back to 5.3.1, I just went back to commit 361b593d

**Comment by jld3103** [comment]
Hello, I'm also facing this issue and did a bisect and found out that commit dd3bba8c9442f2ee40d6ea8f0872ab0be43714b9 broke it. @spacether pinging you as the author of the commit.

**Comment by LPCmedia** [comment]
This is rather blocker for us. Can we revert or is there something we need to add to the config file ?

**Comment by idkCpp** [comment]
I now use `openapitools/openapi-generator-cli:latest-release` instead of `openapitools/openapi-generator-cli:latest`. For me this works fine.

**Comment by spacether** [comment]
Thank you for reporting this. I am investigating it.
Short term solutions are to use our latest release or to add the generator name into your config file. If I can't come up with a quick fix then I will revert it.

**Comment by spacether** [comment]
The master branch has been fixed by https://github.com/OpenAPITools/openapi-generator/pull/11316
Separately I will work on a new PR to add the feature back in and I will include a test which covers this use case of:
- g (generatorName) passed in to command line args
- generatorName not present in the config file
