### ISSUE TITLE
[Spring] Add support for Spring HATEOAS

### ISSUE THREAD

**Issue by mwoodland** [OpenAPITools/openapi-generator#1129]
I'm currently using the OpenAPI Spring generator to generate interface that I'm then using to implement my API.

I'm currently using templates to add the relevant bits of code when generating, however I think this would be something that could be part of the generator itself.

**Comment by cbornet** [comment]
Can you give more details on what you're doing ? HATEOAS is not really a good match for OpenAPI as it aims for dynamic APIs whereas OpenAPI describes static ones.
Also can you explain how you use the generated code ? It seems to me that it will only add a `self` link to the endpoint which doesn't have great value in itself

**Comment by mwoodland** [comment]
The key reason for using HATEOAS in my use case is to make the APIs discoverable. Please also note that HATEOAS is one of the guiding constraints for REST services and I am trying to produce RESTful APIs. Although the APIs will in my case be static they will contain for example nested objects, and pagination.

With nested objects rather than embedding the entire object I will be embedding a summary of an object with a link to the API for retrieving the full details of the object.

When responses are paginated in the paginated results I will be providing a summary object and a link to the API (e.g. adding the identifier to the URL) for the specific object with all details. Additionally I will be providing links to the first, previous, next and last pages of paginated responses.

**Comment by cbornet** [comment]
Yes, that's my point : HATEOAS is about dynamic self-discoverable APIs which means you shouldn't need OpenAPI (since you're discovering the API and it can change any moment). That said, if you use spring-hateoas as a framework to just add hypermedia links in your reponses and not as a true "engine of application state" then I can see the point.

**Comment by mwoodland** [comment]
I don't think generated APIs and self-discoverable APIs are mutually exclusive, and I don't think APIs have to be dynamic for there to be value in them being discoverable. The point is that you don't need to have documentation explaining the structure of the data that your REST APIs are representing, that you can work this out for yourself from the links.

I'm not entirely sure what you mean by dynamic APIs, although the APIs won't be changing all the time they will be changing between releases, and the underlying data that the APIs are exposing will be changing so the relationships between the various underlying objects will be changing dynamically even if the API specifications themselves are not.

**Comment by cbornet** [comment]
Closing as #1130 is merged.
