### ISSUE TITLE
[BUG][Python] Client generated allOf model broken since 5.2.0

### ISSUE THREAD

**Issue by Chekov2k** [OpenAPITools/openapi-generator#11299]
#### Bug Report Checklist

- [yes] Have you provided a full/minimal spec to reproduce the issue?
- [yes] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [no] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [yes] Have you searched for related issues/PRs?
- [yes] What's the actual output vs expected output?
- [no] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The allOf models for the python-client generator are broken since version 5.2.0

##### openapi-generator version

5.2.0 upwards creates broken model code

5.1.X works fine

##### OpenAPI declaration file content or url

Minimal example model code
```yaml

openapi: 3.0.2

info:
  title: Python AllOf bug demo
  description: Python AllOf bug demo
  version: 1.0.0

servers:
  - url: /bug

tags:
  - name: StreamOptions
    description: StreamOptions

paths:
  /StreamOptions:
    $ref: '#/components/schemas/StreamOptions'

components:
  schemas:
    StreamOptions:
      allOf:
        - $ref: "#/components/schemas/EgressThresholdOptions"
        - $ref: "#/components/schemas/PublishOptions"

    EgressThresholdOptions:
      type: object
      properties:
        egressThresholds:
          type: object
          additionalProperties:
            type: number
            minimum: 0
            maximum: 1
            example: 0.9

    PublishOptions:
      type: object
      properties:
        publish:
          type : object
          properties:
            egressUnknownDetections:
              type: boolean
              example: true
            filterZeroDetections:
              type: boolean
              example: true

```

##### Steps to reproduce

Use the following command to produce the model

```bash
openapi-generator generate -i api.yaml -g python -o .
```

Once generated, create the following python *bug.py* script to trigger the bug

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from copy import deepcopy

import openapi_client.models as cc
from openapi_client.configuration import Configuration
from openapi_client.model_utils import deserialize_model


def main():
    data = {"egressThresholds": {"person":0.8}, "publish": {"egressUnknownDetections": False}}
    model = deserialize_model(
        deepcopy(data),
        cc.StreamOptions,
        (),
        True,
        Configuration(discard_unknown_keys=True),
        True,
    )

    model.publish # breaks


if __name__ == "__main__":
    main()

```

This will result in the following error

```bash
./bug.py
Traceback (most recent call last):
  File "/Users/balzer/demo/./bug.py", line 26, in <module>
    main()
  File "/Users/balzer/demo/./bug.py", line 22, in main
    model.publish # breaks
  File "/Users/balzer/demo/openapi_client/model_utils.py", line 188, in __getattr__
    return self.__getitem__(attr)
  File "/Users/balzer/demo/openapi_client/model_utils.py", line 667, in __getitem__
    value = self.get(name, self.__unset_attribute_value__)
  File "/Users/balzer/demo/openapi_client/model_utils.py", line 658, in get
    raise ApiValueError(
openapi_client.exceptions.ApiValueError: Values stored for property publish in StreamOptions differ when looking at self and self's composed instances. All values must be the same at ['publish']
```

Turns out that the *values* list in *model_utils.ModelComposed.get* contains two entries:

```
[{'egress_unknown_detections': False}, {'egressUnknownDetections': False}]
```

The first object is of type *<class 'openapi_client.model.publish_options_publish.PublishOptionsPublish'>* and the other of type *<class 'dict'>*

See for possible reason below

##### Related issues/PRs

Have not found any related issue so far

##### Suggest a fix

Debugging the code, it seems that the method *_from_openapi_data* of a model calls *validate_get_composed_info* in *model_utils.py* . This call *get_allof_instances* and which is used to fill the *var_name_to_model_instances* variable.

This variable contains the model data for each composed model and looks like this:

```
<class 'openapi_client.model.egress_threshold_options.EgressThresholdOptions'> {'egress_thresholds': {'person': 0.8},
 'publish': {'egressUnknownDetections': False}}

<class 'openapi_client.model.publish_options.PublishOptions'> {'egress_thresholds': {'person': 0.8},
 'publish': {'egress_unknown_detections': False}}
```

For some reason, the *convert_js_args_to_python_args* is applied to some of the data and not to the others, i.e. for the *EgressThresholdOptions* model the *EgressThresholdOptions* data is converted but not the *PublishOptions* model data and vice versa.

Currently trying to find out where this happens.

**Comment by Chekov2k** [comment]
As a very hacky workaround, the input data to the model can be force to snake_case naming via a helper like this:

```python

def js_to_python(input_dict:dict, model_class:object)->dict:
    input_dict = change_keys_js_to_python(input_dict, model_class)
    for key in model_class.openapi_types.keys():
        data = input_dict.get(key)
        if data is None:
            continue

        for openapi_type in model_class.openapi_types[key]:
            if openapi_type in model_class.additional_properties_type:
                continue
            elif isinstance(openapi_type, dict):
                for inner_key in openapi_type.keys():
                    inner_data = data.get(inner_key)
                    if inner_data is None:
                        continue
                    inner_type = openapi_type[key]
                    if inner_type in model_class.additional_properties_type:
                        continue
                    data[inner_key] = js_to_python(inner_data, inner_type)
            elif isinstance(openapi_type, (list, tuple)):
                for inner_type in openapi_type:
                    if inner_type in model_class.additional_properties_type:
                        continue
                    data = js_to_python(data, inner_type)
            else:
                data = js_to_python(data, openapi_type)
            input_dict[key] = data
    return input_dict
```

And then the *model_utils.ModelComposed.get* method needs to try to convert the *value* added to *values* via the *to_dict()* method like this:

```python
        if model_instances:
            for model_instance in model_instances:
                if name in model_instance._data_store:
                    v = model_instance._data_store[name]
                    try:
                        v = v.to_dict()
                    except:
                        pass
                    if v not in values:
                        values.append(v)
        len_values = len(values)
```

I can't see how to prevent the *model_instance* cache to not get out of sync since each inner model does not know about the other inner models so can't modify its data store accordingly. This new checking logic seems inherently broken.

**Comment by Chekov2k** [comment]
Maybe the best idea is to clean the data store of each inner model from unrelated/unknown data?

**Comment by spacether** [comment]
Another option is to switch to using the [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata) generator it will not have this bug because spec case is used for all payloads so there is no conversion to snake case.

**Comment by Chekov2k** [comment]
Thank you, I will give that a try!

**Comment by mickelsonmichael** [comment]
Throwing another hat into the ring here, also experiencing this issue.

There are actually several instances of the object in the internal instance store, and the issue is that our object has an ID propery which is a custom schema in the spec that wraps a string. Something to the effect of:

```yaml
ObjectId:
  type: string
  example: 1234
```

When the instances are compared to verify all the values are equivalent, some of the values are an instance of the generated `ObjectId` type, while others are strings, resulting in the error above being thrown.

**Comment by spacether** [comment]
discard_unknown_keys is problematic because what key is unknown varies from schema to schema.
Have you tried using python-experimental?

**Comment by MAKOMO** [comment]
I also experienced this issue. I followed the suggestion of @spacether to try the [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata) generator from the current trunk and can report that it resolved the issue with allOf composition, which I experienced with all versions of the regular python generator since 5.2 up to the current 5.4, on my specification.

**Comment by the-akhil-nair** [comment]
I feel the issue is due to the creation of ```self._var_name_to_model_instances``` while doing the deserialization of the data.

Earlier the Python SDK code was using ```get_var_name_to_model_instances``` function which was adding var name to model instances that contain it. So ```<class 'openapi_client.model.stream_options_all_of'>``` will not part of mapping in ```self._var_name_to_model_instances```  for variable name **stream_options**.

Now with the latest Python SDK code following is the way through which ```var_name_to_model_instances``` is created:
```python
    for prop_name in model_args:
        if prop_name not in discarded_args:
            var_name_to_model_instances[prop_name] = [self] + composed_instances
```
Now as we can see that the ```var_name_to_model_instances``` is populated with ```self and composed_instance``` which will also contain **stream_options_all_of** as a composed instance and there will be no check that if **stream_options** is present in **composed_instances** or not. 

As there is no attribute_mapping found for **stream_options** in **stream_options_all_of**, the type for **stream_options** will be treated as dict for mapping **stream_options_all_of** as mentioned by @Chekov2k.

So what I suggest is the following code:
```python
    for prop_name in model_args:
        if prop_name not in discarded_args:
           var_name_to_model_instances[prop_name] = [self] + list(
                filter(
                    lambda x: prop_name in x.openapi_types, composed_instances))
```
 This way we can check if the property name is present in that composed instance or not. If it's okay for @spacether I can raise a PR for this.

**Comment by MAKOMO** [comment]
This works for me. Splendid!

**Comment by spacether** [comment]
Can you post a PR with a fix?
Will your solution work if a client needs to include `egress_unknown_detections` and `egressUnknownDetections` or should we ignore that as a seldom used corner case?
