### ISSUE TITLE
[BUG][typescript-fetch] Nullable date types are not marked as | null + coverters only check undefined

### ISSUE THREAD

**Issue by WilliamABradley** [OpenAPITools/openapi-generator#11307]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When calling an API with a null date, you can't because the typescript type is wrong, and if you fudge it, it will throw an error because .toISOString does not exist on null.

##### openapi-generator version

5.3.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Example
  version: v1
paths: {}
components:
  schemas:
    Date:
      type: string
      format: date-time
      nullable: true
```

##### Generation Details

```json
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "5.3.0",
    "generators": {
      "user-api": {
        "generatorName": "typescript-fetch",
        "output": "src/libs/user-api",
        "inputSpec": "https://.../users/v1/docs/spec/public/users/openapi.yml",
        "additionalProperties": {
          "modelPropertyNaming": "original",
          "enumNameSuffix": ""
        }
      }
    }
  }
}
```

##### Steps to reproduce

Run `openapi-generator-cli generate`

##### Suggest a fix

Make types:

```ts
col?: Date | null;
```

Make coverter:

```ts
'col': value.col === undefined ? undefined : (value.date_of_birth.toISOString()),
```

**Comment by WilliamABradley** [comment]
I have further learnt this was because of the use of a $ref, E.g. 

```yaml
openapi: 3.0.3
info:
  title: Example
  version: v1
paths: {}
components:
  schemas:
    Date:
      type: string
      format: date-time
     MyType:
       type: object
       properties:
         date:
           $ref: "#/components/schemas/Date"
           nullable: true
```

**Comment by kradical** [comment]
I hit this recently too. I tested against 6.1.0 and the bug appears to live on. I'd be happy to try my hand at a fix but its hard to tell if it would get prioritized / reviewed / merged 🤷

**Comment by tikki100** [comment]
This is still an issue in v. 7.11.0 but the issue has been closed as "not planned"?
