### ISSUE TITLE
[JAVA] Bug found in RFC3339DateFormat about clone method

### ISSUE THREAD

**Issue by fcanovas1986** [OpenAPITools/openapi-generator#11311]
##### Description

We have been noticed by a bug in this class from spotbugs-maven-plugin. When generating the **RFC3339DateFormat** class:

`[ERROR] Medium:xxxxxxxx.rest.client.invoker.RFC3339DateFormat.clone() does not call super.clone() [xxxxxxxxxx.rest.client.invoker.RFC3339DateFormat] At RFC3339DateFormat.java:[line 53] CN_IDIOM_NO_SUPER_CALL`

If I check the class template [RFC3339DateFormat.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/RFC3339DateFormat.mustache) I can see how it is true that the override method `clone()` does not call `super.clone()`. It only calls `return this;`, so it is not cloning the object.

```  
@Override
  public Object clone() {
    return this;
  }
```
Find the reference to this bug [here](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#cn-clone-method-does-not-call-super-clone-cn-idiom-no-super-call)

##### openapi-generator version

5.3.0

##### Suggest a fix/enhancement

Calling `super.clone` method inside `clone()` method of **RFC3339DateFormat** would be enough. I would be happy to contribute if you want.

**Comment by wing328** [comment]
@fcanovas1986 thanks for offering help to fix this bug. Please file a PR and we'll review accordingly.

**Comment by chriswhite199** [comment]
PR #11363 causes the clone method to raise a NullPointerException as `DateFormat.clone()` tries to clone both the `calendar` AND `numberFormat` field. `numberFormat` is uninitialized in the generated `RFC3339DateFormat` constructor, and so a NPE is thrown.

The [javadocs for DateFormat.numberField](https://docs.oracle.com/javase/8/docs/api/java/text/DateFormat.html) note:

> The number formatter that DateFormat uses to format numbers in dates and times. Subclasses should initialize this to a number format appropriate for the locale associated with this DateFormat.

I'll raise a separate issue for this, but just documenting here in case I get side tracked.
