### ISSUE TITLE
[erlang]Bug, upgrade erlang-server generated cowboy code's version, from 1.x to 2.x

### ISSUE THREAD

**Issue by guwenbin1991** [OpenAPITools/openapi-generator#1135]
[erlang]Bug, upgrade erlang-server generated cowboy code's version from 1.x to 2.x
##### Description
we're trying to generate erlang-server framework , but issue happens.
we found that the generated code's version is too low for us. we're using 2.4 cowboy, but the generated code still has 1.x API in cowboy. we suggest that we could upgrade the cowboy's API version.

take openapi_api.erl as example , the API used to read request's body is :cowboy_req:body,
the latest version is cowboy_req:read_body.
##### openapi-generator version

we're using the latest stable release:3.2
##### OpenAPI declaration file content or url

see the latest version of ts 29.571
##### Command line used for generation

java -jar openapi-generator-cli.jar generate -i EIPS_Nudm_UECM.yaml -g erlang-server -o server

##### Steps to reproduce
you could see the code that has been generated.

**Comment by feihongmeilian** [comment]
@wing328

**Comment by wing328** [comment]
@guwenbin1991 the erlang-serve generator has been upgraded to support cowboy 2.x. Can you please give it a try with the latest stable version and let us know if it's still an issue to you.

**Comment by guwenbin1991** [comment]
thanks, we will test it, and give the feedback. could you tell me the
version?

William Cheng <notifications@github.com> 于 2019年2月25日周一 19:27写道：

**Comment by wing328** [comment]
@guwenbin1991 Please try https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.0.0-beta2
