### ISSUE TITLE
[BUG] python. $ref and nullable could not work properly

### ISSUE THREAD

**Issue by 11010cy** [OpenAPITools/openapi-generator#11352]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

https://github.com/apache/airflow/blob/main/airflow/api_connexion/openapi/v1.yaml

at line 2661-2663:
```
dag_run_timeout:
              nullable: true
              $ref: '#/components/schemas/TimeDelta'
```

the _dag_run_timeout_ was  intended to be null or TimeDelta object. When I use openapi-generator-cli to generate client code, the openapi_types gets:

```
 @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
           ...
            'dag_run_timeout': (TimeDelta,),  # noqa: E501
           ...
        }
```

the _dag_run_timeout_ does not support None type. Could anyone explain this to me?

expected:
```
none_type = type(None)

 'dag_run_timeout': (TimeDelta, none_type,),  # noqa: E501
```

##### openapi-generator version

openapitools/openapi-generator-cli:5.3.0

##### OpenAPI declaration file content or url

https://github.com/apache/airflow/blob/main/airflow/api_connexion/openapi/v1.yaml

##### Steps to reproduce

https://github.com/apache/airflow/tree/main/clients

**Comment by spacether** [comment]
Per the openapi spec, properties adjacent to refs are ignored:
https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#reference-object
`This object cannot be extended with additional properties and any properties added SHALL be ignored.` except for summary and description.

**Comment by 11010cy** [comment]
@spacether I modified the code as you recommended:
```
dag_run_timeout:
 oneOf:
  - type: null
  - $ref: '#/components/schemas/TimeDelta'
```

The generated code would be expected like:
```
none_type = type(None)
'dag_run_timeout': (TimeDelta, none_type,),  # noqa: E501
```
, but got the following code:
```
'dag_run_timeout': (bool, date, datetime, dict, float, int, list, str, none_type,),  # noqa: E501
```
I am not sure whether it was intended to be so. Got any idea?

**Comment by spacether** [comment]
Our tooling has a bug with Inline composed schemas. Can you move the updated compossd schema into a component and $ref it?

**Comment by 11010cy** [comment]
@spacether Are there any plans to fix this bug? And when？

**Comment by spacether** [comment]
It's less of a big and more of most generators were not built in a way to support complex Inline composed schemas. I wrote python-experimental generator to support Inline schemas at any depth
