### ISSUE TITLE
[BUG] CMakeLists.txt gernerated by  cpp-qt-client is missing Qt5:.Gui dependency / linking

### ISSUE THREAD

**Issue by rejuce** [OpenAPITools/openapi-generator#11371]
#### Bug Report Checklist
tried with Qt5.14, Qt5.15, with gcc7 under Linux / ubunut 20.04

- [ ] What's the actual output vs expected output?
CMake should build, but fails with QDesktopServices.h can not be found. This header depens on Qt5:Gui which is not listed/linked in the autogernated CMakeLists.txt 

##### openapi-generator version
5.3.1

##### Suggest a fix
add
find_package(Qt5 COMPONENTS Gui REQUIRED)
and Qt5::Gui  under target_link_libraries in the generated CMakeLists.txt

**Comment by wing328** [comment]
Can you try installing Qt with the following commands as that's what we've in our CI?
```
sudo apt install -y --no-install-recommends qt5-default 
```
Ref: https://github.com/OpenAPITools/openapi-generator/blob/master/.travis.yml#L103
