### ISSUE TITLE
[Docs] Display use of colon for separating apis,models,supportingFiles

### ISSUE THREAD

**Issue by aderito7** [OpenAPITools/openapi-generator#11375]
Just came across this bit of [documentation](https://openapi-generator.tech/docs/configuration#tool-specific-declarations) that had me confused for a little while
```
openApiGenerate {
    globalProperties = [
        apis: "",
        models: "User,Pet"
    ]
}
```
I've soon learnt that the separator that should be used is a colon and not comma (i.e. `User:Pet` and **not** `User,Pet`).
If correct, was hoping this could be updated for any travelers arriving on the docs and spare them the head-scratching I endured.

**Comment by wing328** [comment]
@aderito7 thanks for the feedback. Do you mind filing a PR with the suggested change?

Have a nice weekend.
