### ISSUE TITLE
[BUG][PHP] PHP-Symfony 5.* generator does not work properly with 'additionalProperties'

### ISSUE THREAD

**Issue by Aleksst95** [OpenAPITools/openapi-generator#11419]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

PHP-Symfony 5.* generator creates wrong docs for 'additionalProperties'. It creates the wrong phpDoc for a map. Instead of `@Type("array<string, string>")` it makes `@Type("array<string>")`.

In version 4.* it works fine.

##### OpenAPI files

- [api.yaml](https://gist.github.com/Aleksst95/34239573c3e7a6d186777495f76ffdea)
- [model_generic.mustache](https://gist.github.com/Aleksst95/12f64129900a623a3a23a7d78ce43d46)
- [model_variables.mustache](https://gist.github.com/Aleksst95/642bfa873484860ba16efb048cdc84ae)

##### Generation Details

[Generator command](https://gist.github.com/Aleksst95/1fddb8ed0ea25b30f38e3a14b176e50c)

##### Steps to reproduce

1. take examples from `OpenAPI files` 
2. run the example from "generation details"

**Expected result:** `@Type("array<string, string>")` for the `param` property.

**Actual result:** `@Type("array<string>")` for the `param` property.

**Comment by wing328** [comment]
Which version of openapi-generator are you using? I think the latest stable version v5.3.1 has this issue fixed.

Also are you using customized templates?

**Comment by wing328** [comment]
https://gist.github.com/Aleksst95/642bfa873484860ba16efb048cdc84ae#file-model_variables-mustache-L33

that has been renamed to `isMap`

**Comment by Aleksst95** [comment]
Yeah, `isMap` works fine! Thank you!

**Comment by wing328** [comment]
👌
