### ISSUE TITLE
[JAVA] Crash happens generating classes with apt-maven-plugin

### ISSUE THREAD

**Issue by stefano-maglione** [OpenAPITools/openapi-generator#11435]
When generating code using apt-maven-plugin in Mac environment it crashes with below exception:

`[WARNING] /Users/fullname/Desktop/mine marketplace/BE/src/main/resources/static/api.yaml [0:0]: unexpected error in Open-API generation
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 1
    at java.lang.String.checkBoundsBeginEnd (String.java:3319)
    at java.lang.String.substring (String.java:1874)
    at io.swagger.v3.parser.util.OpenAPIDeserializer.getServer (OpenAPIDeserializer.java:481)`

**Comment by wing328** [comment]
> io.swagger.v3.parser.util.OpenAPIDeserializer

Looks to me the issue is with the parser instead. Please report the issue to https://github.com/swagger-api/swagger-parser

(I assume your spec has been validated)
