### ISSUE TITLE
[BUG] [Docs] Slack link on frontpage is invalid

### ISSUE THREAD

**Issue by jafin** [OpenAPITools/openapi-generator#11445]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Slack link on https://github.com/OpenAPITools/openapi-generator and https://openapi-generator.tech/ goes to an invalid link. 

```
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
```

##### Suggest a fix

Either:

- Fix the slack link if Slack is still active.
- Remove slack if not active.

**Comment by wing328** [comment]
can you please try this one: https://openapi-generator.slack.com/ ?

**Comment by jafin** [comment]
@wing328  sadly it's a no for that link, appears to be only for relevant existing members not invites, I suspect a new invite link needs to be generated?

![image](https://user-images.githubusercontent.com/127927/151696962-f78fdb10-1688-4aef-a3a6-b890bf628d58.png)
from https://slack.com/intl/en-au/help/articles/201330256-Invite-new-members-to-your-workspace

**Comment by wing328** [comment]
Please try this one: https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

I just learned that previous link was set to "Never expire" but it will expire (for security reasons) if more than 2000 users join via that link

**Comment by jafin** [comment]
@wing328 awesome thankst that works

**Comment by snowe2010** [comment]
can the link on the homepage be updated with the above (working) one?
