### ISSUE TITLE
[BUG] [SPRING] annotationLibrary is ignored

### ISSUE THREAD

**Issue by cdprete** [OpenAPITools/openapi-generator#11460]
Hi.
I'm using the latest version of the generator (5.3.1) and, according to the [spring](https://openapi-generator.tech/docs/generators/spring/) generator documentation, I should be able to not generate the Swagger annotations by setting `annotationLibrary` to `none` in the `configOptions` section of the plugin configuration in Maven, but it looks like such property is simply ignored.
As a workaround, I'm manually stripping away the imports and the annotations for now, but it's really not ideal.

**Comment by cachescrubber** [comment]
The feature is available starting with version 5.4.0, available soon.

**Comment by RomanSoloweow** [comment]
> Эта функция доступна, начиная с версии 5.4.0, доступной в ближайшее время.

I faced the same problem

**Comment by jstanik** [comment]
I tried it with 5.4.0 and got

`java.lang.IllegalArgumentException: The [springdoc] documentation provider does not support [none] as complementary annotation library`

**Comment by cachescrubber** [comment]
The `annotationLibrary` depends on the selected `documentationProvider`. Use **documentationProvider = none**. 

You could use `annotationLibrary` to override the default set by the documentationProvider. For example, choose **documentationProvider = none**. (not springbok/springfox runtime) but still annotate model and apis with swagger annotations.

**Comment by jdsee** [comment]
> The `annotationLibrary` depends on the selected `documentationProvider`. Use **documentationProvider = none**.

It would be great if this information was included in the error message. Something like "If you mean to disable the documentation annotations set 'documentProvider' to 'none'".

**Comment by rupert-jung-mw** [comment]
Even when specifing both `<annotationLibrary>` and `<documentationProvider>` to "none", it will still include (broken) Swagger Annotations. I actually just want to leave them away (SpringDoc is only used to generate an OpenAPI file from _our own_ RSET resources, it does not touch any generated client code.

When I just specify `<annotationLibrary>none</annotationLibrary>` it will abort with the error from above:

`java.lang.IllegalArgumentException: The [springdoc] documentation provider does not support [none] as complementary annotation library`

When I leave it on default, generator generates broken Kotlin Code (as of 7.20.0:

<img width="429" height="76" alt="Image" src="https://github.com/user-attachments/assets/70505885-cff6-4a59-ab4a-af97900cb684" />
