### ISSUE TITLE
[BUG][SPRING] Generates mutlible tags in Operation annotation if more then one tag is defined.

### ISSUE THREAD

**Issue by ugrave** [OpenAPITools/openapi-generator#11464]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If more than one tag is given in the api, the generator generates two tag entries in the operational annotation

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.3'
info:
  version: 1.0.0
  title: Example Api
paths:
  /:
    get:
      operationId: example
      tags:
        - tag1
        - tag2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
```

##### Generation Details

Using the spring generator with default annotationLibrary and documentation provider (springdoc).

The openapi declaration above creates this java file:
```java
    @Operation(
        operationId = "example",
        tags = { "tag1", "tag2" },
        tags = { "tag1", "tag2" },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  InlineResponse200.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/",
        produces = { "application/json" }
    )
    default ResponseEntity<InlineResponse200> example(
```

##### Steps to reproduce

See example project.

[bug-report.zip](https://github.com/OpenAPITools/openapi-generator/files/7969859/bug-report.zip)

**Comment by cachescrubber** [comment]
@ugrave Thanks for your contribution. Could you update the swagger1 `@ApiOperation` as well? Otherwise, the PR looks good.

@welshm, wing328  FYI.
