### ISSUE TITLE
[BUG] [JavaJaxRS] Combining `modelNameSuffix` and `import-mappings`

### ISSUE THREAD

**Issue by mickroll** [OpenAPITools/openapi-generator#11478]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We use `<modelNameSuffix>TO</modelNameSuffix>` to distinct all our generated models from our internal models and prevent name collissions. In our Spec, we define our Ids as follows (in an extra file `id.json`):
```
      "ExampleId": {
        "description": "The example Id.",
        "type": "string",
        "format": "uuid",
        "example": "53b1f9fe-44e1-11f0-1122-336652440000"
      }
```
The spec then references these id types:
```
      "ExampleWrapper": {
        "type": "object",
        "required": ["id", "name"],
        "properties": {
          "id": {
            "$ref": "id.json#/components/schemas/ExampleId"
          },
          "name": {
            "type": "string"
          }
        }
      }
```
To prevent OpenAPI-Generator from generating `ExampleId`-classes, we define a mapping configuration via `<configurationFile>configuration.json</configurationFile>`:
```
{
    "importMappings": {
        "ExampleId": "com.example.model.id.ExampleId"
    }
}
```
The referenced class `ExampleId` already exists of course.

All of this worked in `5.3.1` an lead to sources like this:
```
package com.example.api.generated.model;
[...]
import com.example.model.id.ExampleId;
[...]
public class ExampleWrapperTO {
[...]
  private @Valid ExampleId id;
  private @Valid String name;
[...]
}
```

With `5.4.0` this is generated:
```
package com.example.api.generated.model;
[...]
import com.example.api.generated.model.ExampleIdTO;
[...]
public class ExampleWrapperTO {
[...]
  private @Valid ExampleIdTO id;
  private @Valid String name;
[...]
```
Note: a `ExampleIdTO` is not generated! (we don't want it to, just a note)

I tracked the changed behaviour to https://github.com/OpenAPITools/openapi-generator/commit/33bce99b8e024e27709b2395df83b8ded3d56036#r65722393 but as the PR says, this change is intended. Was it really, given the example above? Or was using `modelNamePrefix`/`modelNameSuffix` out of scope for that PR?

###### Workaround

If i change our `configuration.json` to the following, valid sources are generated:
```
{
    "typeMappings": {
        "ExampleIdTO": "ExampleId",
    },
    "importMappings": {
        "ExampleId": "com.example.model.id.ExampleId",
        "ExampleIdTO": "com.example.model.id.ExampleId",
    }
}
```

But this seems very redundant and partly wrong to me. If i leave out any of the three definitions, it stops working:
- leave out `typeMappings.ExampleIdTO`: `ExampleWrapperTO` uses `ExampleIdTO` instead of `ExampleId`
- leave out `importMappings.ExampleId`: `ExampleWrapperTO` uses `UUID` instead of `ExampleId`
- leave out `importMappings.ExampleIdTO`: `ExampleWrapperTO` imports `com.example.api.generated.model.ExampleIdTO` (which doesn't exist), but not `com.example.model.id.ExampleId`, but uses `private @Valid ExampleId id`, which cannot be found

##### openapi-generator version

5.4.0 (worked in 5.3.1)

##### OpenAPI declaration file content or url

see above 

##### Generation Details

`openapi-generator-maven-plugin:5.4.0`
with config:
```
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/META-INF/openapi.json</inputSpec>
                            <configurationFile>${project.basedir}/src/main/openapi/generator/configuration.json</configurationFile>
                            <apiPackage>com.example.api.generated</apiPackage>
                            <modelPackage>com.example.api.generated.model</modelPackage>
                            <modelNameSuffix>TO</modelNameSuffix>
                            <generatorName>jaxrs-spec</generatorName>
                            <!-- <library>quarkus</library> would generate unnecessary Dockerfile etc. -->
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <returnResponse>false</returnResponse>
                                <sourceFolder>java</sourceFolder>
                                <useSwaggerAnnotations>false</useSwaggerAnnotations>
                                <generatePom>false</generatePom>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                        </configuration>
```

##### Related issues/PRs

#11217

##### Suggest a fix

Revert #11217 or some of its contents?

**Comment by anthonymayfield** [comment]
I'm also getting this issue and I'm using this workaround to fix it.  I'm setting a languageSpecificPrimitive, these should really be ignored by the modelNameSuffix as I'm already declaring what I want it to be called, if I want the Suffix on it I could just mention it there.

**Comment by pschichtel** [comment]
this seems to be exactly what I reported in the PR after my tests: https://github.com/OpenAPITools/openapi-generator/pull/12600#issuecomment-1162881085

@wing328 I guess there really is an issue

**Comment by wing328** [comment]
I'll try to take another look this weekend if someone can provide a minimal/full spec and the settings (e.g. --import-mappings) to reproduce the issue.

**Comment by mickroll** [comment]
This issue seems to have been fixed by introducing the new `schemaMappings` configuration option.

**Comment by pschichtel** [comment]
@mickroll will you create a new issue for this: https://github.com/OpenAPITools/openapi-generator/issues/11478#issuecomment-1173895292 ?

**Comment by mickroll** [comment]
> @mickroll will you create a new issue for this: https://github.com/OpenAPITools/openapi-generator/issues/11478#issuecomment-1173895292 ?

No i did not. Feel free to do so, please.
