### ISSUE TITLE
[BUG] [python-experimental] Type null not handled properly in toExampleValue

### ISSUE THREAD

**Issue by MalteEbner** [OpenAPITools/openapi-generator#11518]
##### Description

With the following configuration, the openapi-generator with python-experimental breaks
- openapi-generator-cli 5.4.0, installed via npm
- using python-experimental
- using the `OAI/OpenAPI-Specification/main/examples/v2.0/yaml/petstore.yaml`

Switching to python (non-experimental) or other specs solved the problem.

##### openapi-generator version
5.4.0

##### Steps to reproduce

Google colab for reproduction: https://colab.research.google.com/drive/1z2KnELth4HfaK-36ntjr_7v9g65QF63W?usp=sharing

Fully self-contained substeps in Google colab:
```python
# install openapi-generator-cli
!npm install -g @openapitools/openapi-generator-cli
!openapi-generator-cli version-manager set 5.4.0

# get the PetStore.yaml and generate it:
!wget https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v2.0/yaml/petstore.yaml
!ls
!openapi-generator-cli generate -i petstore.yaml -g python-experimental

# Error:
# first some
[main] WARN  o.o.c.l.AbstractPythonCodegen - Type null not handled properly in toExampleValue
# then finally a
java.lang.NullPointerException
```

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/10143
- https://github.com/OpenAPITools/openapi-generator/issues/8663 shows exactly the same error
- https://github.com/OpenAPITools/openapi-generator/issues/7824
- https://github.com/OpenAPITools/openapi-generator/pull/9131 fixed it in the python branch
##### Suggest a fix

- fix it in the generator

**Comment by MalteEbner** [comment]
@spacether Could you look into that, as you are the maintainer of python-experimental? I hope that this fully reproducible setup helps you.

**Comment by puneetugru** [comment]
+1.

Facing a similar issue while trying to use `python-experimental` to make models generated with non snake_case names.

It will be good to get this working.

``` console
openapi-generator --version
openapi-generator-cli 5.4.0
  commit : 4a36be7
  built  : 2022-01-31T05:31:36Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

**Comment by spacether** [comment]
Please know that only v3 specs are allowed in by python-experimental per: https://github.com/OpenAPITools/openapi-generator/pull/11931
Openapi v3.0.0 was released in  Jul 26, 2017 and python-experimental seeks to support the latest and greatest features.
Though swagger-parser converts v2 specs to v3 specs under the hood it's possible that that conversion has bugs or is missing info. Please convert your spec to v3 before using python-experimental.

For the null pointer exception, I am working for a PR in https://github.com/OpenAPITools/openapi-generator/pull/12019 to solve this issue.
