### ISSUE TITLE
[BUG][java][okhttp-gson-nextgen] validJsonObject ignores discriminator when attributes are not unique

### ISSUE THREAD

**Issue by holymaloney** [OpenAPITools/openapi-generator#11520]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using oneOf, using discriminator is not sufficient to deserialize. If the object type cannot be determined uniquely using attribute names, the deserialization fails.

##### openapi-generator version
5.4.0

##### OpenAPI declaration file content or url
https://github.com/hakonph/openapi-genertor-okhttp-gson-nextgen/blob/master/src/main/resources/error.yaml

(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->

##### Generation Details
Gradle generator
https://github.com/hakonph/openapi-genertor-okhttp-gson-nextgen/blob/1c815516cf5ea7705d466410faef2dc3b11dd8f5/build.gradle.kts#L13

##### Steps to reproduce
Run Gradle build on this project
https://github.com/hakonph/openapi-genertor-okhttp-gson-nextgen

See spesifically https://github.com/hakonph/openapi-genertor-okhttp-gson-nextgen/blob/master/src/test/java/no/test/kake/OpenapiGeneratorTest.java

##### Suggested fix
When discriminator is valid, run only validateJson on actual class, instead of running validateJson on all classes.

**Comment by hakonph** [comment]
I think i found the error, the template checks [`{{#useOneOfDiscriminatorLookup}}`](https://github.com/OpenAPITools/openapi-generator/blob/b72eba90cddddafd1def4189215d2bd306901901/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson-nextgen/anyof_model.mustache#L75) but it is not exposed in the java generator.

**Comment by wing328** [comment]
Thanks for reporting the issue. I'll try to look into this issue this week or next.

**Comment by wing328** [comment]
should be fixed by https://github.com/OpenAPITools/openapi-generator/pull/11735. Please give it another try with the latest master.
