### ISSUE TITLE
[REQ] [Java] [JAXRS-SPEC] Allow removing header parameters 

### ISSUE THREAD

**Issue by claudioaltamura** [OpenAPITools/openapi-generator#11540]
### Is your feature request related to a problem? Please describe.

I want to handle specific header parameters globally using an Http interceptor (Quarkus, ContainerRequestFilter). I don't want to have @ApiParam attribute for header parameters.

## Describe the solution you'd like

The Spring generator already knows the implicitHeaders config option  (https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/spring.md). 

That's want I would like to have plus the ability to specify which parameters to ignore, see [[REQ][JAVA][Spring] Allow choosing which headers to set as implicit in implicitHeaders configProps #8166)](https://github.com/OpenAPITools/openapi-generator/issues/8166) .

## Describe alternatives you've considered

Maybe I can achieve all this via templates (mustache/pebble)?
Or extending the generator.

I think that is a core functionality.

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/11819 by @borsch has been merged into master. Please pull the latest master to give it another try.
