### ISSUE TITLE
[question] what exactly is artifactVersion used for?

### ISSUE THREAD

**Issue by michabbb** [OpenAPITools/openapi-generator#11581]
hi, i hope it´s okay to ask this here.
for a very long time, I am using this great project to generate PHP SDKs.
in my config I am using for all SDKs and all versions of this package:

`"artifactVersion": "2.3.2",`

but to be honest, I don´t know where that initial value came from nor what it´s used for ;-))

i would be very happy if someone could enlighten me here cause google wasn´t helping me here.

thanks!!

**Comment by wing328** [comment]
looks like that's the version of the php sdk: https://github.com/OpenAPITools/openapi-generator/blob/023f4e760b65745213ea9aeb7eebea879d73788f/modules/openapi-generator/src/main/resources/php/composer.mustache#L5

hope this helps.
