### ISSUE TITLE
[Question] [python-fastapi] How to set _spec_property_naming = True via command line

### ISSUE THREAD

**Issue by puneetugru** [OpenAPITools/openapi-generator#11604]
##### Description

We have a requirement where we would like to generate only the model files, inheriting from `pydantic` BaseModel.

Hence, we would like to use `python-fastapi` as the generator type.

But, we would also like the `openapi-generator` to NOT generate model names with snake_case, but rather with camelCase.

As per #10458 the support exists as part of the `python-experimental` generator.

But, the same is failing due to #11518  

But, is there a way to set `_spec_property_naming = True` as a command-line argument with the generator set as `python-fastapi`?

##### openapi-generator version

``` console
openapi-generator --version
openapi-generator-cli 5.4.0
  commit : 4a36be7
  built  : 2022-01-31T05:31:36Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

**Comment by puneetugru** [comment]
> Hi @puneetugru just ran into the same issue ;-)
> 
> My first look into the code doesn't show me a link between the 2 generators (python and python-fastapi). I think the property you mentioned is not available in python-fastapi generator.
> 
> My understanding is: The generator converts to snake case here:
> 
> https://github.com/OpenAPITools/openapi-generator/blob/380aaa55a187b90c800e7d6c0ac44d43e5d1cf14/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonFastAPIServerCodegen.java#L86
> 
> and uses the template to end up with python code: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python-fastapi/model.mustache
> 
> and consequently also serializes into the same format - which is a problem, because that is NOT what the openapi spec (in my case yaml) said.
> 
> So far, I manually did the following changes for my models:
> 
> ```
> from pydantic import Field
> from .dependencies import SchemaConfig
> 
> classs SomeClass(BaseModel):
>     created_on: Optional[datetime] = Field(None, alias='createdOn')
>     class Config(SchemaConfig):
>         ...
> ```
> 
> ```
> class SchemaConfig:
>   allow_population_by_field_name = True
> ```
> 
> Fastapi serializes the models with the alias by default. The reason for the `SchemaConfig` is, that whenever you wan to create an instance with snake_case e.g.
> 
> ```
> SomeClass(created_on='...')
> ```
> 
> the `allow_population_by_field_name` needs to be set.
> 
> So my question to you and others (maybe active contributors to the python-fastapi module): Does this make sense? Should I try to add the code for this to the template?

Thank you @matgnt for your comment.

I've not used Fastapi extensively and hence I'll not be the correct person to answer your query related to adding code.

I expected that `_spec_property_naming=True` will work for `python-fastapi` generator option too, as I don't want to add code manually :-)

**Comment by matgnt** [comment]
@spacether Regarding the label, is python-fastapi client or 'server' label? It sounds like the requester want to use it (or the models) in a client, but the generator is a server generator. Maybe both labels?

**Comment by spacether** [comment]
Per [our docs, python-fastapi is a server generator](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-fastapi.md#metadata).
Thank you for pointing that out. This issue now has both tags.
