### ISSUE TITLE
[BUG][Python] Dict property checking for enum values not working correctly

### ISSUE THREAD

**Issue by vcutrona** [OpenAPITools/openapi-generator#11626]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The model validation is wrong for dictionaries with values in Enums. The check_allowed_values method checks dict keys, instead of dict values.

##### openapi-generator version

Docker image: openapitools/openapi-generator-cli 
Versions: 5.4.0, latest

##### OpenAPI declaration file content or URL
Code to reproduce the bug hosted at 

##### Generation Details

Generated via Docker, using the 'python' generator (all options to defaults)

##### Steps to reproduce

OS: Ubuntu 21.04
Python: 3.9.5

1) `curl https://gist.githubusercontent.com/vcutrona/adb7571338fce6cb5c495ba4abd725f7/raw/b736a812adcaac6a118f0f7c8d714f81084b63c4/openapi.yaml -o openapi.yaml`
2) `docker run --rm -v $PWD:/local openapitools/openapi-generator-cli:v5.4.0 generate -i /local/openapi.yaml -g python -o /local/out/py3`
3) `cd out/py3`
4) `pip install requests==2.26.0 jsonpickle==2.1.0`
5) execute the following code snippet:
```python
import jsonpickle
import requests

from openapi_client import ApiClient
from openapi_client.model.response_measurement_descriptor_dto import ResponseMeasurementDescriptorDto

url = "https://gist.githubusercontent.com/vcutrona/adb7571338fce6cb5c495ba4abd725f7/raw/ac160028dc81deda236cbdd2a444dc68b0fd5553/response-data.jsonpkl"
r = jsonpickle.decode(requests.get(url).json())
m = ApiClient().deserialize(r, (ResponseMeasurementDescriptorDto, ), True)
```

Exception thrown: `openapi_client.exceptions.ApiValueError: Invalid keys in ``fields`` [HR], must be a subset of [STRING, BOOLEAN, NUMBER]`
However, by inspecting the response, "HR" is a key, while "NUMBER" is the (right) value.

The same exception does not occur with the Java client (generated with the same generator).
I tested also step 2) using `openapitools/openapi-generator-cli:latest`.

##### Suggest a fix

In the generated Python client, the values check for the received object is made on dictionary keys, instead of dictionary values (see line 859 in openapi_client.model_utils). Manually changing input_values.keys() to input_values.values() solves the issue.

**Comment by spacether** [comment]
In this example, fields is a property and contains an object.
That object allows in a value which is an enum defined in additionalProperties.
This is working in the python client in v6.2.0 and higher
One can see that working in the model [MapTest](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/map_test.py#L238) which contains the property map_of_enum_string. That property is an object.
That object allows in a value which is an enum defined in [additionalProperties](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/map_test.py#L137)
And that additionalProperties definition is a [string enum with two values](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/map_test.py#L108).

**Comment by vcutrona** [comment]
I reopen this issue because I still encounter the same error (I'm now using the docker version of the generator v7.7.0).
In my example (OAS 3.0), `fields` is a key-value dictionary (defined as documented [here](https://swagger.io/docs/specification/data-models/dictionaries/)).
Also, the `additionalProperties` keyword is used to specify the type of values in that dictionary. 
In my example, `fields` accepts strings as values, in particular only those matching an enum (i.e., "STRING", "BOOLEAN", "NUMBER").

The python generator can indeed recognize this spec, generating the `MeasurementDescriptorDto` class as it follows:
```python
class MeasurementDescriptorDto(BaseModel):
    """
    MeasurementDescriptorDto
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    unit_of_measure_id: Optional[StrictStr] = Field(default=None, alias="unitOfMeasureId")
    taxonomy_item_id: Optional[StrictStr] = Field(default=None, alias="taxonomyItemId")
    scale_id: Optional[StrictStr] = Field(default=None, alias="scaleId")
    factory_entity_model_id: Optional[StrictStr] = Field(default=None, alias="factoryEntityModelId")
    categories_id: Optional[List[StrictStr]] = Field(default=None, alias="categoriesId")
    functional_module_inputs_id: Optional[List[StrictStr]] = Field(default=None, alias="functionalModuleInputsId")
    fields: Optional[Dict[str, StrictStr]] = None
    output_maps_id: Optional[List[StrictStr]] = Field(default=None, alias="outputMapsId")
```
Please note the type of `fields` declared as `Optional[Dict[str, StrictStr]]`.
Given that `fields` is a dictionary (optional), the following validator cannot work. Indeed, the validation is expecting a string value as input, not a dict:

```python
    @field_validator('fields')
    def fields_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['STRING', 'BOOLEAN', 'NUMBER']):
            raise ValueError("must be one of enum values ('STRING', 'BOOLEAN', 'NUMBER')")
        return value
```
The issue is that the validator should be applied to the values of the dictionary (i.e., `fields.values()`), not to the dictionary itself (i.e., `fields`).
The generated python client returns the exception
```
pydantic.error_wrappers.ValidationError: 1 validation error for MeasurementDescriptorDto
fields
  unhashable type: 'dict' (type=type_error)
```
The client is generated with the Docker image openapigenerator:v7.7.0 using the following command:
```bash
docker run --rm -v $(pwd):/app openapitools/openapi-generator-cli:v7.7.0 \
  generate -g python \
  -c /app/api/openapi-configs/python.yml \
  --additional-properties=packageVersion=2.2.0 \
  -i /app/api/openapi.json 
  -o /app/clients/python
```
Here is the `python.yml` config file:
```
packageName: python_client
projectName: python-client
hideGenerationTimestamp: true
generateSourceCodeOnly: false
mapNumberTo: Union[StrictFloat, StrictInt]
datetimeFormat: "%Y-%m-%dT%H:%M:%S%z"
dateFormat: "%Y-%m-%d"
useOneOfDiscriminatorLookup: false
library: urllib3
disallowAdditionalPropertiesIfNotPresent: true
```

Hope this helps. Thanks for your support.
