### ISSUE TITLE
[REQ][spring] Feature x-implements is not supported

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#11636]
### Is your feature request related to a problem? Please describe.

`x-implements` extension is not supported for spring server (for the different java clients it is supported).

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
components:
  schemas:
    MyDtoImpl:
      type: object
      description: To be override with the schema id
      x-implements: ['org.data.MyDto']
      properties:
        data:
          description: Data compliant with the schema defined at the description field
          type: object
```
`x-implements`  is not taken into account

##### Expected generation

```java
public class MyDtoImpl implements org.data.MyDto  {
...
}
```

## Describe the solution you'd like

Adapt the **pojo.mustache** template to take this extension into account.

https://github.com/OpenAPITools/openapi-generator/blob/b979eccf680a5b7f64c284221a5d2c868a4400ad/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache#L24-L26

What do you thinki?

**Comment by wing328** [comment]
Closed via #11784 by @borsch (Thank you)

@jorgerod please pull the latest master to give it another try.
