### ISSUE TITLE
[Python] to_dict function can not serialize a list obj containing some dictionarys.

### ISSUE THREAD

**Issue by YingChen1996** [OpenAPITools/openapi-generator#11676]
### Is your feature request related to a problem? Please describe.
I am generating client python code by swagger.json using openapi-generator-cli. To do that I used the

npm install @openapitools/openapi-generator-cli -g
openapi-generator-cli version-manager set 5.2.0
run just like: openapi-generator-cli generate -i ./swagger.json -g python-legacy -o ./_restclients --additional-properties packageName=designer

then it will gennerate to_dict function in each model class, which is like:

```
    def to_dict(self, serialize=False):
        """Returns the model properties as a dict"""
        result = {}

        def convert(x):
            if hasattr(x, "to_dict"):
                args = getfullargspec(x.to_dict).args
                if len(args) == 1:
                    return x.to_dict()
                else:
                    return x.to_dict(serialize)
            else:
                return x

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            attr = self.attribute_map.get(attr, attr) if serialize else attr
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: convert(x),
                    value
                ))
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], convert(item[1])),
                    value.items()
                ))
            else:
                result[attr] = convert(value)

        return result
```
But if x is a list obj which contains many dictionaries, it will return x directly in convert function. And this will raise error when json.dumps when those dictionaries' value is complex type. 

## Describe the solution you'd like
obj.to_dict() can return a fully serialized dictionary obj and can run json.dumps(obj=obj.to_dict()) successfully

**Comment by spacether** [comment]
How about upgrading to python in v6.2.0 where this is fixed?
In that version you can use [JsonEncoder.default()](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/api_client.py#L56)
to convert from a schema instance to python primitive json data.

**Comment by spacether** [comment]
Closing this because the bug has been fixed in a newer release
