### ISSUE TITLE
[BUG] [JAVA] API Client generation doesn't support Bearer Authentication  with openapi-generater V3.3.4 . It is creating basic authentication only although we have provided bearer autentication in yml

### ISSUE THREAD

**Issue by Pallshar** [OpenAPITools/openapi-generator#11681]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by wing328** [comment]
Please try the latest stable version instead to see if the issue still persists and open a new issue with the details instead.
