### ISSUE TITLE
[BUG] java-micronaut-server generator issues with datetime

### ISSUE THREAD

**Issue by mast7860** [OpenAPITools/openapi-generator#11694]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

jackson have issue deserialising the field as its a localDateTime and have OffsetSeconds in the format.

Generated Field

    @Nullable
    @ApiModelProperty(value = "last updated datetime")
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
       public LocaltDateTime getLastUpdatedDateTime() {
        return lastUpdatedDateTime;
    }

Expected Field

    @Nullable
    @ApiModelProperty(value = "last updated datetime")
    @JsonProperty(JSON_PROPERTY_LAST_UPDATED_DATE_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXX")
       public OffsettDateTime getLastUpdatedDateTime() {
        return lastUpdatedDateTime;
    }

Error : 

JSON: Unsupported field: OffsetSeconds

Which originates from java.time.LocalDate
```

private int get0(TemporalField field) {
        switch ((ChronoField) field) {
            case DAY_OF_WEEK: return getDayOfWeek().getValue();
            case ALIGNED_DAY_OF_WEEK_IN_MONTH: return ((day - 1) % 7) + 1;
            case ALIGNED_DAY_OF_WEEK_IN_YEAR: return ((getDayOfYear() - 1) % 7) + 1;
            case DAY_OF_MONTH: return day;
            case DAY_OF_YEAR: return getDayOfYear();
            case EPOCH_DAY: throw new UnsupportedTemporalTypeException("Invalid field 'EpochDay' for get() method, use getLong() instead");
            case ALIGNED_WEEK_OF_MONTH: return ((day - 1) / 7) + 1;
            case ALIGNED_WEEK_OF_YEAR: return ((getDayOfYear() - 1) / 7) + 1;
            case MONTH_OF_YEAR: return month;
            case PROLEPTIC_MONTH: throw new UnsupportedTemporalTypeException("Invalid field 'ProlepticMonth' for get() method, use getLong() instead");
            case YEAR_OF_ERA: return (year >= 1 ? year : 1 - year);
            case YEAR: return year;
            case ERA: return (year >= 1 ? 1 : 0);
        }
        throw new UnsupportedTemporalTypeException("Unsupported field: " + field);
    }
```

##### openapi-generator version

V 5.4.0

##### Generation Details

gradlePlugin = "org.openapi.generator"

generatorName = "java-micronaut-server"

##### Steps to reproduce

Add a date-time field to any swagger and generate the classes using the java-micronaut-server generator.

##### Related issues/PRs

This is recently released.

##### Suggest a fix

Change date-time from LocalDateTime to OffSetDateTime

**Comment by pfyod** [comment]
For some reason, the `dateLibrary` option is explicitly removed here: https://github.com/OpenAPITools/openapi-generator/blob/f03b1e7261b6758235cd6b5f236a31a240926b62/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaMicronautAbstractCodegen.java#L104-L105
 so it's impossible to override this.

**Comment by andriy-dmytruk** [comment]
Hi @mast7860, the date-time library option is not supported, since not all libraries could be supported by micronaut type converter, but I will look into that. For now the option was removed, but probably should be implemented later.

And yes, it seems more appropriate to use `OffsetDateTime` for datetime. 
Thank you for the suggested fix. I will create a respective pull request today.

**Comment by pfyod** [comment]
@andriy-dmytruk: I don't think that just removing `dateLibrary` argument is a good solution here. It makes it impossible to override type mappings manually (e.g. map `date-time` to `ZonedDateTime` or `OffsetDateTime`). Previous solution for that is setting `dateLibrary` to some unsupported value (e.g. `custom`) and providing own type / import mappings does not work for micronaut, since it's impossible to change `dateLibrary` from the default.

**Comment by andriy-dmytruk** [comment]
@pfyod Thanks for the comment.
I will stop removing the `dateLibrary` parameter. I will just provide a single supported value (of the java LocalDate), as it is the only currently supported. Will this solve the problem?

**Comment by pfyod** [comment]
Honestly, don't know much about this project. Wanted to try out and immediately stumbled on this issue, then tried to get why none of the settings I try work. I guess if you provide `java8` / `java8-localdatetime` as supported options (that leaves out `legacy`, `joda` and `threetenbp`, which I guess are not supported by micronaut), it should provide enough flexibility.

**Comment by andriy-dmytruk** [comment]
@mast7860 I think you can temporarily use the PR above. if you need But I hope it will get approved to the whole repository soon.

**Comment by mast7860** [comment]
@andriy-dmytruk  : Thanks for the having a look and fixing 👍

**Comment by andriy-dmytruk** [comment]
@mast7860 The PR was merged, so you can verify if it resolved your issue:
https://github.com/OpenAPITools/openapi-generator/pull/11871

**Comment by andriy-dmytruk** [comment]
@mast7860 You think you can close this issue, since it seems to be resolved?
