### ISSUE TITLE
[REQ] ts-angular: support scoped package names + custom registry

### ISSUE THREAD

**Issue by NewYearNewPhil** [OpenAPITools/openapi-generator#11700]
### Is your feature request related to a problem? Please describe.

When generating a client with the `ts-angular` with a [scoped](https://docs.npmjs.com/cli/v8/using-npm/scope) `npmName` and a custom `npmRepository`, the registry will not be picked up when trying to publish the package using `npm publish`. Instead, the package is sent to the public registry to be published (which doesnt work, they require scoped packages to explicitly allow this).
In the `package.json` the relevant section looks like this:
````
"name": "@scope/name",
...
"publishConfig": {
    "registry": "<custom registry>"
}
````

## Describe the solution you'd like

If the npmName describes a scoped package, add the scope to the publishConfig like so:
````
"name": "@scope/name",
...
"publishConfig": {
    "@scope:registry": "<custom registry>"
}
````

## Describe alternatives you've considered

This could be also be set in the `.npmrc` file:
````
echo "@scope:registry=<custom registry>" >> .npmrc
````
but then its wrong when publishing the source code in a repository.

## Additional context

Eases the process of setting up CI-processes. I assume the same issue exists on all Typescript generators and can be fixed in the same fashion, but I have not checked.

**Comment by andreperegrina** [comment]
You can modify the `package.mustache` and the custom registry just change this lines:
```
{{#npmRepository}},
    "publishConfig": {
        "register": "{{npmRepository}}"
    }{{/npmRepository}}
```
add the npmRepositoryRegister variable
```
{{#npmRepository}},
    "publishConfig": {
        "{{npmRepositoryRegister}}": "{{npmRepository}}"
    }{{/npmRepository}}
```
Then you just need to add the following lines in the file `openapitools.json`
```
"additionalProperties": {
          "npmName": "@user/test",
          "npmRepositoryRegister": "@user:registry:",
          "npmRepository": "https://gitlab.com/api/v4/projects/<project_id>/packages/npm/",
        }

```
