### ISSUE TITLE
[REQ][Java][Spring] Allow for extra class and field level annotations

### ISSUE THREAD

**Issue by jayfray12** [OpenAPITools/openapi-generator#11772]
### Is your feature request related to a problem? Please describe.

I'd like to add class and field level annotations on a per object level basis so I can use the OpenAPI generator to generate `Entity` classes for Hibernate and JPA

## Describe the solution you'd like

I'd like to be able to add an `x-class-extra-annotation` to the object in the spec or `x-field-extra-annotation` to a field similar to how the `x-extra-annotation` and `x-setter-extra-annotation` work.

## Describe alternatives you've considered

I've created my own mustache templates to achieve this but would be nice if it was in the upstream

**Comment by mirzaprangon** [comment]
As far as I can understand, this feature was tagged for miletone 6. Its already released right? Asking because this issue is still open.
