### ISSUE TITLE
[REQ] Possibility to remove service name from method name

### ISSUE THREAD

**Issue by angelaki** [OpenAPITools/openapi-generator#11783]
Just like probably many out there I needed to add the endpoint name to the operationId (https://github.com/OAI/OpenAPI-Specification/issues/381) to keep them unique.

Having two services (e.g. Service1 & Service2) both having a method "get" I get two operationIds (e.g. Service1_get & Service2_get).

The prefix (Service1_, Service2_) is totally useless but requred by OpenAPI. Now the service clients will get generated like

```
Service1 {
   Service1_get() { ... }
}

Service2 {
   Service2_get() { ... }
}
```

Is there maybe a possibility already to make both the methods just get named "get()"? Any ideas on this?

**Comment by spacether** [comment]
I am working on this in: https://github.com/OpenAPITools/openapi-generator/pull/13007
One will be able to use it like:
```
from package.paths import PathValues
from package.apis.path_to_api import path_to_api
path_enum = PathValues("some/path")
api = path_to_api[path_enum]
# api has .post/put/patch etc methods on it
```

**Comment by angelaki** [comment]
@spacether or anyone else here having this issue ... Any news / ideas on this?

**Comment by wing328** [comment]
@angelaki have you tried the `operationIdNameMappings` option to match the operationId to whatever method name you want?

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping

**Comment by wing328** [comment]
ok. have you tried the `--remove-operation-id-prefix` option?

ref: https://openapi-generator.tech/docs/usage/

**Comment by angelaki** [comment]
Works like a charm - thank you very much! What exactly does this option do? The docs aren't very transparent here. Does it look for a specific character? Or a name being repeated with every method?

**Comment by wing328** [comment]
remove operationId prefix (e.g. user_getName => getName)

ref: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-maven-plugin/README.md

**Comment by wing328** [comment]
@angelaki when you've time, can you please PM me via Slack?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
