### ISSUE TITLE
How do I add an interceptor to a typescript-axios client generated by an OpenAPI generator?

### ISSUE THREAD

**Issue by jasongonzales23** [OpenAPITools/openapi-generator#11799]
##### Description
I want to add an interceptor to the typescript-axios client for the purpose of logging all requests. I can't find any documentation that explains how to get at or create an axios instance for me to configure globally.

**Comment by qandrew** [comment]
+1, would be curious about this also

**Comment by ColeMurray** [comment]
The BaseAPI constructor exposes an axios instance that is used for the underlying requests.

When instantiating your Api object, you could pass in an axios instance with interceptors set on it:

```
export class BaseAPI {
    protected configuration: Configuration | undefined;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};
```

**Comment by Rupert-com** [comment]
Hey there,
had the same problem. I came up with this solution and it works. The DefaultApi has a protected axios property which can be accessed. But you have to use ``//@ts-ignore` hence the property is protected.

``` typescript
const finnhubClient = new DefaultApi({
  apiKey,
  isJsonMime: input => {
    try {
      JSON.parse(input)
      return true
    } catch (error) {}
    return false
  },
},undefined,)

//@ts-ignore
finnhubClient.axios.interceptors.response.use(
  response => response,
  error => {
    console.log('error: ', error)
    throw error
  }
)
```

Hope I could help.

**Comment by Villar74** [comment]
> The BaseAPI constructor exposes an axios instance that is used for the underlying requests.
> 
> When instantiating your Api object, you could pass in an axios instance with interceptors set on it:
> 
> ```
> export class BaseAPI {
>     protected configuration: Configuration | undefined;
> 
>     constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected axios: AxiosInstance = globalAxios) {
>         if (configuration) {
>             this.configuration = configuration;
>             this.basePath = configuration.basePath || this.basePath;
>         }
>     }
> };
> ```

@ColeMurray can you give an example how i can pass my axios instance to BaseApi?

**Comment by Villar74** [comment]
ok, i solve my problem, answer here: https://stackoverflow.com/questions/76330621/is-it-possible-to-pass-an-axiosinstance-to-openapi-generator-generated-typescrip
