### ISSUE TITLE
[BUG][JAVA] UNKNOWN_BASE_TYPE when using $ref to model in requestBodies

### ISSUE THREAD

**Issue by Swiftwork** [OpenAPITools/openapi-generator#11811]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Openapi generator fails to handle $ref to model in requestBodies resulting in UNKOWN_BASE_TYPE.

##### openapi-generator version

Version: `5.4.0`
Might be a regression as this has been mentioned before: https://github.com/OpenAPITools/openapi-generator/issues/2575

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
paths:
  /user:
    post:
      summary: Create New User
      operationId: post-user
      requestBody:
        $ref: '#/components/requestBodies/UserPost'
      responses:
        '200':
          description: OK
components:
  requestBodies:
    UserPost:
      content:
        application/json:
          schema:
            type: object
            properties:
              firstName:
                type: string
              lastName:
                type: string

```

##### Generation Details

Using `typescript-fetch`

```bash
openapi-generator-cli generate -g typescript-fetch -i spec.yaml -o gen
```

##### Steps to reproduce

[Reproduction](https://github.com/Swiftwork/openapi-generator-unknown-base-type)

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/2575

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/12293 has been merged into master. Please pull the latest to give it a try.

**Comment by Swiftwork** [comment]
@wing328 Great! Any way I can test master using the https://github.com/OpenAPITools/openapi-generator-cli?
