### ISSUE TITLE
[REQ] let typescript-fetch initOverrides optional to be a function

### ISSUE THREAD

**Issue by loynoir** [OpenAPITools/openapi-generator#11823]
### Is your feature request related to a problem? Please describe.

https://github.com/OpenAPITools/openapi-generator/issues/11744

Just like issue above, I also want to append header.

```js
const init = {
    method: context.method,
    headers: headers,
    body,
    credentials: this.configuration.credentials,
    ...initOverrides
};
```
But `{X, ...Y}` is one level merging, not deep merging. 

When `initOverrides` has key  `headers`, prev key `headers` is gone.

So, current implement can't append header.

## Describe the solution you'd like

Current signature
```ts
private createFetchParams(context: RequestOpts, initOverrides?: RequestInit)
```

Merging using `{X, ...Y}`

REQ
```ts
private createFetchParams(
    context: RequestOpts,
    initOverrides?: RequestInit | ((context: RequestOpts) => RequestInit)
)
```

Merging using `{X, ...Y(X) }`

## Describe alternatives you've considered

Convert `{X, ...Y}` to some deep merging library `fn(X, Y)`.

But consider `openapi-generator` target many language, I prefer former to decrease you guys maintenance burden. 

## Additional context

You guys are awesome. :)

**Comment by mkusaka** [comment]
@loynoir Hi 👋
Thank you for your request.
This feature implemented at #12098 and will release in  v6.0.0.
