### ISSUE TITLE
[BUG] [Java] Maven Build Fails Due to Source Being Java 1.7 but Lambda Expressions are in Generated Code when library resttemplate is used

### ISSUE THREAD

**Issue by greenjohn23** [OpenAPITools/openapi-generator#11822]
##### Description

When using Open API Generator for a Java project the Maven build fails on the generated project giving an error that indicates lambda expressions are not support by Java 1.7. This occurs when using the value `resttemplate` for the `library` configuration in Open API Generator 5.2.1 and later.

##### openapi-generator version

Maven build is successful with the `resttemplate` option when using version 5.2.0

Maven build fails with the `resttemplate` option when using versions 5.2.1, 5.3.0, 5.4.0

##### Generation Details

Using the node.js openapi-generator-cli to install and run the openapi-generator tool.
Using the openapitools.json to set the Open API Generator version

##### Steps to reproduce

Generate a swagger.json
Create a configuration file with the `libary` set to `resttemplate`
Invoke openapi-generator-cli with Java as the language, passing in the swagger.json and the configuration file
Build the generated project with Maven

```bash
[main] ERROR org.apache.maven.plugin.compiler.CompilerMojo - COMPILATION ERROR : 
[main] INFO org.apache.maven.plugin.compiler.CompilerMojo - -------------------------------------------------------------
[main] ERROR org.apache.maven.plugin.compiler.CompilerMojo - /C:/workspace/MyApp-API/MyApp/generated/openapigenerator/src/main/java/com/myApp/ApiClient.java:[532,44] lambda expressions are not supported in -source 1.7
  (use -source 8 or higher to enable lambda expressions)
[main] INFO org.apache.maven.plugin.compiler.CompilerMojo - 1 error
[main] INFO org.apache.maven.plugin.compiler.CompilerMojo - -------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - ------------------------------------------------------------------------
[main] INFO org.apache.maven.cli.event.ExecutionEventLogger - BUILD FAILURE
```

**Comment by borsch** [comment]
Affected by this PR https://github.com/OpenAPITools/openapi-generator/pull/9871
Assuming that soon project plan to migrate to java 8 as a minimal version I double that somebody gonna fix this.

**Comment by wing328** [comment]
@borsch is right

@greenjohn23 please upgrade to JDK 8 instead.
