### ISSUE TITLE
[BUG] CodegenProperty#isInherited not set right

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#11845]
Some properties do not have isInherited set correctly. See `modules\openapi-generator\src\test\resources\3_0\allOf.yaml`  Child properties Type, LastName, FirstName will have isInherited set to false when it should be true. This is in csharp-netcore, any library.

#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by ahmednfwela** [comment]
I have also encountered this problem on #12295 , will make a PR to solve it

**Comment by devhl-labs** [comment]
Fantastic. I have a hot fix in the CSharpNetCoreClientCodegen that can be removed once this is fixed. The url for this issue is in the code.
