### ISSUE TITLE
How to provide local file to Docker command

### ISSUE THREAD

**Issue by codertimu** [OpenAPITools/openapi-generator#11888]
```yaml
docker run --rm \
    -v $PWD:/local openapitools/openapi-generator-cli generate \
    -i /local/petstore.yaml \
    -g go \
    -o /local/out/go
```
[error] The spec file is not found: /local/petstore.yaml
[error] Check the path of the OpenAPI spec and try again.

I even tried providing the full path to the petstore.yaml but it gave the same error. In the example [here](https://github.com/OpenAPITools/openapi-generator#openapi-generator-cli-docker-image), a URL is used but doesn't apply for my case.
How can I use it with a local file?

**Comment by agilob** [comment]
This issue is a question more suitable for stackoverflow.

Mount it using a volume.

**Comment by codertimu** [comment]
my bad, you need to cd into the `local` directory.
