### ISSUE TITLE
[BUG] [Spring] Generator can't recognize response's model name & body's model

### ISSUE THREAD

**Issue by dadyarri** [OpenAPITools/openapi-generator#11901]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))? (Valid but have a circular refs)
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a **spring** code i got:
1. several `InlineResponse200` instead of defined response models with correct names in the schema
2. `UNKNOWN_BASE_TYPE` instead of defined body models

##### openapi-generator version

5.0.0 & master, didn't test with older versions

##### OpenAPI declaration file content or url

Providing minimal reproducing example:
https://gist.github.com/dadyarri/8f4dec5ebd9573b0687528f113577e60

##### Generation Details

```json
{
    "snapshotVersion": "false",
    "useTags": "true",
    "useOptional": "true"
}
```

##### Related issues/PRs
#2575
#11811

**Comment by borsch** [comment]
@dadyarri as temporal work around you can do the following - move all `requestBodies` & `responseBodies` under `components/schemas`

https://gist.github.com/borsch/ab2f0041d60c318963fcf578c09fc3c5

**Comment by HerrEiklar** [comment]
Hi @borsch any idea when/if this will be fixed?

Greetings Elias
