### ISSUE TITLE
[BUG] openapi-generator:jar:6.0.0-SNAPSHOT is missing

### ISSUE THREAD

**Issue by kidbai** [OpenAPITools/openapi-generator#11938]
`
To compile your library, enter the out/generators/my-codegen directory, run mvn package.
`

when I run the `mvn package`, some errors happen:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/1251979/159439724-218dfb80-906e-4c13-aaba-7d51c100e0ee.png">

How to solve this problem?

**Comment by wing328** [comment]
i think you need to do a "mvn clean install" in the project (root level) first.

**Comment by kidbai** [comment]
It gonna be ok when I choose release v5.4.0
