### ISSUE TITLE
Unit Tests generation with for OpenAPI generator

### ISSUE THREAD

**Issue by gpbcom** [OpenAPITools/openapi-generator#11930]
I am currently working with OpenAPI generator on a C++ project, I am trying to generate GMocks tests but I d'ont know the exact procedure, could you tell me the way to generate Unit tests with openapi-generator ?

I would like to know if it is possible to do that for cpp-restsdk and cpp-pistache-server ?

**Comment by gpbcom** [comment]
I already tried that, I ran the following command line `openpi-generator-cli generate -i ./api/openapi.yaml -g cpp-restsdk -c ./config.json -o ./output` Where am I suppose to add the option ? I have tried to add it in the command lne directly, or do I have to add it in the config.json file. Could you give me a command line example with the `generateGMocksForApis` option please ?

**Comment by wing328** [comment]
```
openpi-generator-cli generate -i ./api/openapi.yaml -g cpp-restsdk --additional-properties generateGMocksForApis=true -o ./output
```

**Comment by gpbcom** [comment]
Thank you, it solved my problem
