### ISSUE TITLE
[BUG][cpp-qt-client] compile error code for primitive types in body of put requests

### ISSUE THREAD

**Issue by rejuce** [OpenAPITools/openapi-generator#11984]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? 

- [ x] Have you searched for related issues/PRs?

##### Description

PUT requests that have a primitive type, like int or double or bool in the spec, cause compile erros
`OAIDefaultApi::putAvgF32BankNr(const qint32 &bank_nr, const ::OpenAPI::OptionalParam<double> &body)`
is generated with body type "double" 
later called with 
`        QByteArray output = body.value().asJson().toUtf8();`
which failes, as double is not class

##### openapi-generator version
5.4.0

##### OpenAPI declaration file content or url
see attached

##### Generation Details
default configuration

##### Steps to reproduce
generate qt client api with put request with primitive type request body

[VHCx64CtrREST.json.txt](https://github.com/OpenAPITools/openapi-generator/files/8361006/VHCx64CtrREST.json.txt)

##### proposed solution
change the output array initialistion for primitive types to 
`QByteArray output = QByteArray::number(body.value());`

**Comment by Thaulino** [comment]
Hi rejuce, 

Thanks for reporting this issue.
i have reproduced the error with a minimized version of your spec:

```
openapi: 3.0.0
info:
  title: VHCx64CtrREST
  version: '1.0'
  description: documents the REST API to the HyperCanX64 Control application
  contact:
    name: Grapho Metronic Mess und Regeltechnik Gmbh
    url: https://www.grapho-metronic.com/en/start-en.html
  license:
    name: proprietary
servers:
  - url: http://172.25.178.198:3000
    description: fos.local
paths:
  /avg/u32/{bankNr}:
    parameters:
      - schema:
          type: integer
          minimum: 1
          maximum: 10
        name: bankNr
        in: path
        required: true
        description: average bank number to be addressed
    put:
      summary: ''
      operationId: put-avg-u32-bankNr
      responses:
        '200':
          description: OK
        '404':
          description: Not Found
      description: adds a new value to averaging bank for unsinged32 values. banks from 1 to 9 are valid. the value is added and averaged ad OD 0x6500/subindex=bank. every sync clears all values and retains the last averaged. an maximum of 100000 values are retained
      requestBody:
        content:
          text/plain:
            schema:
              type: integer
              minimum: 0
              maximum: 4294967295
            examples:
              example-1:
                value: 123
        description: value to be added to the deque, overlong values are truncated without error
components:
  schemas: {}
  securitySchemes: {}
security: []
```

I investigated how we can implement your suggested fix and exported the variables during code generation by
```
java -jar openapi-generator-cli-6.0.0.jar generate -i code-#primitive-put/minspec.yaml -g cpp-qt-client --global-property debugOperations=true -o code-#primitive-put/ > debugOperatios.txt
``` 

![image](https://user-images.githubusercontent.com/7205940/166904832-f7bcdab6-c7d5-4dbb-bfc0-4a280cd40749.png)

From my point of view the information is present, it just needs some additional mustache template logic.
I will try to fix it in the upcoming days
