### ISSUE TITLE
[BUG] Can't generate aspnetcore 6 server stub

### ISSUE THREAD

**Issue by nishbat** [OpenAPITools/openapi-generator#12014]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am not able to generate the server stub for aspnetcore version 6 using java cli

##### openapi-generator version

I have downloaded latest version on windows os  using following command
Invoke-WebRequest -OutFile openapi-generator-cli.jar https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.4.0/openapi-generator-cli-5.4.0.jar

##### Steps to reproduce

Below is the command I am using

java -jar openapi-generator-cli.jar generate -g aspnetcore \
  --additional-properties aspnetCoreVersion=6.0 \
  --additional-properties classModifier=abstract \
  --additional-properties operationModifier=abstract \
  --additional-properties packageName=Pet \
  --additional-properties packageTitle=Pet.Api \
  -i party.yml \
  --skip-validate-spec \
  -o

Ouput

[main] INFO  o.o.codegen.DefaultGenerator - Generator 'aspnetcore' is considered stable.
[main] INFO  o.o.c.l.AbstractCSharpCodegen - Environment variable CSHARP_POST_PROCESS_FILE not defined so the C# code may not be properly formatted by uncrustify (0.66 or later) or other code formatter. To define it, try `export CSHARP_POST_PROCESS_FILE="/usr/local/bin/uncrustify --no-backup" && export UNCRUSTIFY_CONFIG=/path/to/uncrustify-rules.cfg` (Linux/Mac). Note: replace /path/to with the location of uncrustify-rules.cfg
[main] INFO  o.o.c.l.AbstractCSharpCodegen - NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[main] WARN  o.o.c.l.AspNetCoreServerCodegen - classModifier is abstract so forcing operationModifier to abstract
[main] WARN  o.o.c.l.AspNetCoreServerCodegen - operationModifier is abstract so forcing generateBody to false
Exception in thread "main" java.lang.IllegalArgumentException: aspnetCoreVersion: Invalid value '6.0'. ASP.NET Core version: 5.0, 3.1, 3.0, 2.2, 2.1, 2.0 (deprecated)
        at org.openapitools.codegen.languages.AspNetCoreServerCodegen.setCliOption(AspNetCoreServerCodegen.java:554)

**Comment by DanielHabenicht** [comment]
I can reproduce this bug with `"@openapitools/openapi-generator-cli": "2.4.26",`

**Comment by wing328** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: aspnetCoreVersion: Invalid value '6.0'. ASP.NET Core version: 5.0, 3.1, 3.0, 2.2, 2.1, 2.0 (deprecated)

6.0 needs to be a string so 

```
java -jar openapi-generator-cli.jar generate -g aspnetcore
--additional-properties aspnetCoreVersion="6.0"
--additional-properties classModifier=abstract
--additional-properties operationModifier=abstract
--additional-properties packageName=Pet
--additional-properties packageTitle=Pet.Api
-i party.yml
--skip-validate-spec
-o
```

**Comment by wing328** [comment]
please try v6.0.0-beta or the latest master instead as aspnet 6.x support was added after the v5.4.0 release.

**Comment by DanielHabenicht** [comment]
For future reference one can set the version in the configuration file: https://github.com/openapitools/openapi-generator-cli#configuration
