### ISSUE TITLE
[REQ] aspnetcore generator: inheritance

### ISSUE THREAD

**Issue by gsscoder** [OpenAPITools/openapi-generator#12013]
### Is your feature request related to a problem? Please describe.

Like with the online version (at swagger.io) I'd like that CLI tool allows me to enforce inheritance in generated types

```yml
    Item:
      required: [ walletAddress ]
      properties:
        walletAddress:
          type: string
          example: '0x008F7d856B71190c6E54x51a30A4ec34F68545e1'
        type:
          type: string
          example: 'itemtype'
        id:
          type: string
          example: 'pre_LfeolJ7DINWPTmQzArvT'
        createdAt:
          type: string
          format: date-time
          example: '2022-03-29T16:59:22.9033559Z'          
    Profile:
      description: Models a user profile
      allOf:
        - $ref: '#/components/schemas/Item'
        - type: object         
          properties:
            publicName:
              type: string
```

Models like these are generated as C# as independent types without inheritance

## Describe the solution you'd like

I'd like to get:
```
class Item { }
class Profile : Item { }
```

## Describe alternatives you've considered

post-processing generated file

Best regards and thank you for sharing the project

**Comment by wing328** [comment]
please enable the rule `REF_AS_PARENT_IN_ALLOF` in openapi normalizer: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer
