### ISSUE TITLE
[BUG] [SPRING] Model class is not generated if it is included only in multipart/form-data object

### ISSUE THREAD

**Issue by RamazanYapparov** [OpenAPITools/openapi-generator#12036]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generator does not generate model classes that used in `multipart/form-data` object.
Please see https://github.com/RamazanYapparov/multipart-demo repository with reproducible example.

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

https://github.com/RamazanYapparov/multipart-demo/blob/master/src/main/resources/server.yml

##### Generation Details

https://github.com/RamazanYapparov/multipart-demo/blob/master/pom.xml#L58-L78

###### Steps to reproduce in prepared project

- clone https://github.com/RamazanYapparov/multipart-demo
- run `./mvnw clean compile`
- result: compilation failure

###### Steps to reproduce from scratch

- create OpenAPI 3 spec containing the following:
  - two objects defined in `components.schemas`
  - first one is some `Payload` object with any set of fields
  - the second one is some `Upload` object with one field being a `$ref` to the first object and the second field being binary string
  - POST operation with `requestBody` consuming `multipart/form-data`
  - `requestBody` schema should be a `$ref` to `Upload` object
- run `openapi-generator` with provided schema  using `spring` generator
- result: `Payload` class is not generated

##### Related issues/PRs

Did not find anything related

**Comment by RockyMM** [comment]
Have you tested with the latest 6.0.0-SNAPSHOT? 

Seems that #10415 is related somehow?

**Comment by RamazanYapparov** [comment]
Just tested out with [openapi-generator-cli-6.0.0-20220403.092348-112.jar](https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.0.0-SNAPSHOT/openapi-generator-cli-6.0.0-20220403.092348-112.jar) and the issue still remains.

Looks like it is related to #10415 
Tried out using a workaround from [this comment](https://github.com/OpenAPITools/openapi-generator/issues/10415#issuecomment-1003067496) and it fixes the issue, but still, it is a workaround and not default behavior

**Comment by tofi86** [comment]
I can confirm this still happens with v6.0.1

**Comment by FreshDoktor** [comment]
It also happens in v6.2.0

**Comment by wing328** [comment]
```
[main] INFO  o.o.codegen.DefaultGenerator - Model PayloadTwo not generated since it's marked as unused (due to form parameters) and `skipFormModel` (global property) set to true (default)
[main] INFO  o.o.codegen.DefaultGenerator - Model UploadObject not generated since it's marked as unused (due to form parameters) and `skipFormModel` (global property) set to true (default)
```

please set the `skipFormModel` option to false instead as mentioned in the log.

**Comment by ayhanap** [comment]
for typescript-axios generator `skipFormModel` does not solve the issue, it generates a model but api code doesn't use the required logic. It only works if you inline `requestBody` instead of using `$ref`

**Comment by gabel** [comment]
If someone struggles with the `openapi-generator-maven-plugin` configuration for this issue like me. The configuration need to look like the following to generate the multipart/form-data models.

```xml
<configuration>
    <configOptions>
        ...
    </configOptions>
    <globalProperties>
        <skipFormModel>false</skipFormModel>
    </globalProperties>
</configuration>
```

**Comment by mohammedfahmi** [comment]
still doesn't generate the model for multipart/form-data content, here is my openapi-generator-maven-plugin configuration

`            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>
                                ${project.basedir}/src/main/resources/specs/bundled.yaml
                            </inputSpec>
                            <generatorName>spring</generatorName>
                            <apiPackage>***********************.api</apiPackage>
                            <modelPackage>***********************.model</modelPackage>
                            <configOptions>
                                <generateSupportingFiles>false</generateSupportingFiles>
                                <useOneOfInterfaces>true</useOneOfInterfaces>
                                <documentationProvider>springfox</documentationProvider>
                                <serializableModel>true</serializableModel>
                                <interfaceOnly>true</interfaceOnly>
                                <useTags>true</useTags>
                                <ignoreFileOverride>${project.basedir}/.openapi-generator-ignore</ignoreFileOverride>
                                <globalProperties>
                                    <skipFormModel>false</skipFormModel>
                                </globalProperties>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>`
