### ISSUE TITLE
[REQ] Client template for Jersey 3.x

### ISSUE THREAD

**Issue by andi-livn** [OpenAPITools/openapi-generator#12040]
The jakartified Jersey 3.0.0 was released in December 2020 and the current 3.0.4 was released Feb 2022. There are some breaking changes from Jersey 2 that will require a new template to add support for a Jersey 3 client

https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest3x/migration.html#mig-3.0.0

I'm mainly creating this ticket to have a place to gather feedback and gauge interest from the community for a Jersey 3 template.

**Comment by wing328** [comment]
@andi-livn I've filed https://github.com/OpenAPITools/openapi-generator/pull/12046 to add `jersey3` support.

Can you please review when you've time? Thank you.
