### ISSUE TITLE
[BUG][python][python-experimental] generator python-experimental does not support ContentType header with charset specification

### ISSUE THREAD

**Issue by MAKOMO** [OpenAPITools/openapi-generator#12049]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

A client generated using the python-experimental generator fails on a response with the valid header with a key error.

```
header: Content-Type: application/json; charset=utf-8
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/api/account_api_endpoints/authenticate.py", line 262, in authenticate
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/api_client.py", line 812, in deserialize
NotImplementedError: Deserialization of application/json; charset=utf-8 has not yet been implemented
```

**Comment by spacether** [comment]
@MAKOMO if you want this how about implementing a helper method that detects if the content-type is json. Then using the existing json serialization/deserialization in that case?

**Comment by spacether** [comment]
@MAKOMO now the generator supports it if you:
- pull master branch
- build openapi generator
- use python-experimental
Please see my above PR for the feature addition and the verification test case

**Comment by MAKOMO** [comment]
@spacether Justin, thanks for adding this. I did not know how to best fix this myself as I do not understand the architecture of this generator nor the whole openapi-generator (yet).

I did compile openapi-generator from current trunk including your fix and applied python-experimental to my specification which still just referred to the content type `application/json` as below

```
      responses:
        "200":
          description: Success
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/SuccessAuthentication"
```

and got this error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/api/account_api_endpoints/authenticate.py", line 182, in authenticate
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/api_client.py", line 825, in deserialize
KeyError: 'application/json; charset=utf-8'

After changing the expected content type to include the charset as follows

```
      responses:
        "200":
          description: Success
          content:
            "application/json; charset=utf-8":
              schema:
                $ref: "#/components/schemas/SuccessAuthentication"
```

The call worked without exception.

Note that with the standard python generator the original specification with just the content type response as "application/json" could process the servers response type which includes the charset specification too. Not sure what the correct behavior here is.

Now I have to find out why I cannot access the received data from within the Python client. The specification and client code worked perfectly with openapi-generator 5.1.1 using the standard python generator and stopped working since 5.2.0 (Issue #11299).

So my hope is now on the python-experimental generator, but I have a hard time to get this running too. With the following call from the generated client

```{python}
>>> api_response = api_instance.authenticate(credentials)
...
send: b'POST /api/v1/accounts/users/authenticate HTTP/1.1\r\nHost: localhost:62602\r\nAccept-Encoding: identity\r\nContent-Length: 51\r\nAccept: application/json; charset=utf-8, application/json\r\nContent-Type: application/json\r\nUser-Agent: OpenAPI-Generator/0.0.1/python\r\n\r\n'
send: b'{"email":"user@email.com","password":"geheim"}'
reply: 'HTTP/1.1 200 OK\r\n'
header: Access-Control-Allow-Origin: *
...
DEBUG:artisanplus.rest:response body: b'{"success":true,"result":{"user":{"user_id":"5b1127bf166e60272573a1b0","nickname":"John","account":{"_id":"5b1127be166e60272573a1af","limit":{"rlimit":500,"rused":21.6},"active":true,"currency":"CLP","coupons":1,"company":{"name":"Test","number":"123"},"customs":{"report_type":{"country":"Germany","variant":"Rosenheim"}},"settings":{"pref_roastreport_type":"open"}},"admin":true,"unit_system":"Metric","temperature_system":"Celsius","enabled_modules":["roastDateFilter","importBeans","reminders"],"token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1YjExMjdiZjE2NmU2MDI3MjU3M2ExYjAiLCJpYXQiOjE2NDk3NjAwNTQsImV4cCI6MTY0OTg0NjQ1NH0.Uo8-IgfRsPf_jcifvuKxaXFRGiEqKlKAqzhiXw2xPLc","language":"en","country":"Chile","readonly":false,"export":{"sep":"\\t","linesep":"\\r\\n","decsep":"."},"hts":3,"dsa":0,"energy_unit":"kWh"}},"error":""}'
>>> 
```

Now I get the following exceptions on accessing the data which I have to investigate:

```{python}
>>> api_response
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/dataclasses.py", line 405, in wrapper
    result = user_function(self)
  File "<string>", line 3, in __repr__
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/frozendict-2.3.1-py3.10.egg/frozendict/core.py", line 90, in __repr__
    body = super().__repr__(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/schemas.py", line 497, in __repr__
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/schemas.py", line 497, in __repr__
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/artisan.plus-0.0.1-py3.10.egg/artisanplus/schemas.py", line 497, in __repr__
  [Previous line repeated 245 more times]
RecursionError: maximum recursion depth exceeded while getting the str of an object
>>> api_response["result"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'ApiResponseFor200' object is not subscriptable
```

**Comment by spacether** [comment]
You're welcome for adding charset json + handling @MAKOMO 

What you are now describing is a separate issue. Can you open up a new issue on it?
Also, I can't tell what is happening only from the stack trace. For me or anyone else to be able to fix it, please also include your (yaml/json) endpoint definition, and the definition of the component schemas that the endpoint uses.
With that full information I can squash this bug.

**Comment by MAKOMO** [comment]
> You're welcome for adding charset json + handling @MAKOMO

If I would know how...
 
> What you are now describing is a separate issue. Can you open up a new issue on it? Also, I can't tell what is happening only from the stack trace. For me or anyone else to be able to fix it, please also include your (yaml/json) endpoint definition, and the definition of the component schemas that the endpoint uses. With that full information I can squash this bug.

Yep, I will open a separate issue for this. First I have to produce a small enough conclusive example that allows to reproduce this. Give me a moment.
