### ISSUE TITLE
multipart/form-data request is splitting up data field by field

### ISSUE THREAD

**Issue by bogdancondescu** [OpenAPITools/openapi-generator#12066]
Hello,

I'm using  openapi-generator maven plugin to generate the client side java classes and interfaces for a third-party API.
Generator version: 5.3.1 and FEIGN library to generate the client side.

API:
`requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '.domain#/components/schemas/Document'
            encoding:
              metadata:
                contentType: application/json
                style: form`
Domain:
` Document:
      type: object
      properties:
        metadata:
          $ref: '#/components/schemas/Metadata'
        document:
          type: string
          description: Array of bytes representing the content of the document
          format: binary`

When I'm sending the request the metadata is split field by field instead of having it sent over as JSON.

`
Content-Disposition: form-data; name="validUntilRevoked"
Content-Type: text/plain; charset=UTF-8

true
Content-Disposition: form-data; name="value"
Content-Type: text/plain; charset=UTF-8

lorem ipsum
Content-Disposition: form-data; name="extRef"
Content-Type: text/plain; charset=UTF-8

abc
Content-Disposition: form-data; name="issueDate"
Content-Type: text/plain; charset=UTF-8
1992-10-12`

I'm expecting to be sent over in this format:
`Content-Disposition: form-data; name="metadata"
Content-Type: text/plain; charset=UTF-8

{"evidenceType":"<string>","ext_ref":"<string>","issueDate":"<string>","validUntilRevoked":"<boolean>"}
`
Do you have any idea if this is a bug on the openapi generatoror in the feign client?

Any suggestions will be appreciated.

Thanks!

**Comment by borsch** [comment]
@bogdancondescu could you please share full yaml sample & generator configuration

as for now it seems like you need to set correct request type like this

```yaml
paths:
  /my-path:
    put:
      tags:
        - my-tag
      summary: doSmth
      operationId: doSmth
      requestBody:
        required: true
        content:
          application/json:        <<-- set this
            schema:
              $ref: '.domain#/components/schemas/Document'
```

**Comment by bogdancondescu** [comment]
@borsch Unfortunately I cannot share the file, but the idea is that this endpoint is used to publish files on the server.
The Document domain object contains two parameters, a file and Metadata information about that file. 
With that in mind, the content must be `multipart/form-data`.

**Comment by borsch** [comment]
@bogdancondescu 

> but the idea is that this endpoint is used to publish **files** on the server.

From this it seems like everything works fine. You can't set both content types `myltipart` to upload files and `application/json` to upload data in same request. If you really want to send file and data as json in single request then only thing that you can do is to manually serialize `Metadata` to json string, send it as form-data part, and on server side manually deserialize it to desized object

More info here:
- https://stackoverflow.com/questions/50774176/sending-file-and-json-in-post-multipart-form-data-request-with-axios - not your case but should show you how usually file + data object is sent

**Comment by Breina** [comment]
>You can't set both content types myltipart to upload files and application/json to upload data in same request.

If it is not already supported, I feel like it should in any case:

>   Each part MAY have an (optional) "Content-Type" header field, which
   defaults to "text/plain".  If the contents of a file are to be sent,
   the file data SHOULD be labeled with an appropriate media type, if
   known, or "application/octet-stream".

https://datatracker.ietf.org/doc/html/rfc7578#section-4.4

**Comment by bogdancondescu** [comment]
@borsch Thanks for your input. I've tried it out, but the issue is not solved, the metadata object is still splitting in the body.

**Comment by bogdancondescu** [comment]
I found the way to solve it, modifying the encoder of Feign client and adding JsonFormWriter as first writer.
` apiClient.getFeignBuilder().encoder(new SpringFormEncoder() {{`
`                var processor = (MultipartFormContentProcessor) getContentProcessor(ContentType.MULTIPART);`
`               processor.addFirstWriter(jsonFormWriter);`
`              processor.addFirstWriter(new SpringSingleMultipartFileWriter());`
`               processor.addFirstWriter(new SpringManyMultipartFilesWriter());`
`            }});`
