### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by zolv** [OpenAPITools/openapi-generator#12099]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

A generated Java code doesn't compile due to wrong syntax.

##### openapi-generator version

Openapi generator Gradle plugin: 5.4.0

##### OpenAPI declaration file content or url

The bug report project URL:
https://github.com/zolv/openapi-generator-bug-2

openapi yaml file:
https://github.com/zolv/openapi-generator-bug-2/blob/master/docs/openapi/api-broken.yml

##### Generation Details

Bug report project:
https://github.com/zolv/openapi-generator-bug-2

`build.gradle` is available here:
https://github.com/zolv/openapi-generator-bug-2/blob/master/build.gradle

openapi yaml file:
https://github.com/zolv/openapi-generator-bug-2/blob/master/docs/openapi/api-broken.yml

##### Steps to reproduce

```
gradle clean openapiGenerate build
```

Generated problematic Java code:
```
  public SomeRequest putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = ;  // <-- missing instantiation of map.
    }
    this.metadata.put(key, metadataItem);
    return this;
  }
```
Using version 4.x.x of gradle plugin, it works fine. It created a `metadata` field is initialized with `new HashMap`.

If the schema component is extracted into separated component type, it works fine. 
Fixed yaml file:
https://github.com/zolv/openapi-generator-bug-2/blob/master/docs/openapi/api-working.yml

**Comment by wing328** [comment]
I tried the latest master and it works fine now. Can you please give it a try?
