### ISSUE TITLE
[BUG] Package.json does not get generated for -g typescript-axios

### ISSUE THREAD

**Issue by Snazzie** [OpenAPITools/openapi-generator#12100]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

typescript-axios output does not contain package.json
typescript-fetch also doesnt output package.json

ive tried same definition file with typescript and that outputs a package.json

##### openapi-generator version

5.4.0
##### OpenAPI declaration file content or url
https://gist.github.com/Snazzie/b7131945180e688dd17de5d7d2c0a65f

##### Generation Details
`npx @openapitools/openapi-generator-cli generate -i OrgService.yaml -g typescript-axios -o ./CodeGen/v1/TypeScript/OrgsServiceApiClient`

![explorer_qAExPObG3L](https://user-images.githubusercontent.com/19627023/162596955-02168409-87ae-490e-8c33-b128918e123a.png)

**Comment by mkusaka** [comment]
@Snazzie Hi 👋.

It is likely that the [npmName](https://openapi-generator.tech/docs/generators/typescript-axios/#:~:text=true-,npmName,-The%20name%20under) option must be specified to generate package.json

For example,
```bash
npx @openapitools/openapi-generator-cli generate -i OrgService.yaml -g typescript-axios -o ./CodeGen/v1/TypeScript/OrgsServiceApiClient -p npmName=OrgService
```

This behavior seems to be the same for both typescript-axios and typescript-fetch generator.

Could you try it?

**Comment by Snazzie** [comment]
That fixed it. Thanks!

**Comment by ColeMurray** [comment]
@Snazzie Can you close this if the question is resolved?
