### ISSUE TITLE
[REQ] [python-fastapi] change src folder in python-fastapi generator

### ISSUE THREAD

**Issue by rk0n** [OpenAPITools/openapi-generator#12118]
### Is your feature request related to a problem? Please describe.
The FastAPI generator template generates a openapi_server package in folder src and leads to src/openapi_server as path.
The src part of the path cannot be changed although there is a constant in the python-fastapi codegen script

## Describe the solution you'd like
Use a variable in python-fastapi.yaml file (e.g.: sourceFolder) variable to define the path of the generated openapi_server code
So that the openapi_server package can be generated to src/apis/openapi_server or openapi_server for example.

## Describe alternatives you've considered
Tried to change this by template

## Additional context
Could deliver code for this feature and open to discuss about it

**Comment by rk0n** [comment]
#12119

**Comment by spacether** [comment]
This was fixed by the above PR
