### ISSUE TITLE
[BUG] [Java] Empty localVarContentTypes in PUT requests with no requestBody leads to exception

### ISSUE THREAD

**Issue by panargirakis** [OpenAPITools/openapi-generator#12143]
##### Description

The generated code for PUT requests with an empty request body raise a null pointer exception because the `localVarContentTypes` variable is generated with no default value.

In detail:

My schema specifies PUT requests that do not have a request body. For example:
```
/api/reservations/:
  /api/reservations/{id}/:
    put:
      operationId: reservations_update
      description: Check queue status or renew lease if reservation is ongoing
      parameters:
      - in: path
        name: id
        schema:
          type: string
          format: uuid
        description: A UUID string identifying this reservation session.
        required: true
      tags:
      - reservations
      security:
      - cookieAuth: []
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationSessionSerializerReadOnly'
          description: ''
```
The generated method does not specify a default Content-Type, like so:
```
public okhttp3.Call reservationsUpdateCall(UUID id, final ApiCallback _callback) throws ApiException {
    [...]
    final String[] localVarContentTypes = {
    
    };
    [...]
}
```

##### openapi-generator version

I generated using docker images. Both `openapitools/openapi-generator-cli:v5.4.0` and `openapitools/openapi-generator-cli:v6.0.0-beta` exhibit this issue.

The schema is validated through [apitools.dev](https://apitools.dev/swagger-parser/online/).

##### OpenAPI declaration file content or url

[Full schema here](https://gist.github.com/panargirakis/0d465f954f2c913ef3fc379f1b63da91)

##### Generation Details

Using the following docker-compose configuration:
```
version: '3'

services:
  openapi-generator-cli:
    image: openapitools/openapi-generator-cli:v5.4.0
    volumes:
      - ./:/local
```

Run the following script:
```
mkdir "temp"
curl https://gist.githubusercontent.com/panargirakis/0d465f954f2c913ef3fc379f1b63da91/raw/0135da54dc950da698e8104bad88ed52af5a6aa6/ResSystem_Schema_2.1.0.yml -o ./temp/latest_schema.yml
docker-compose run --rm openapi-generator-cli generate -i /local/temp/latest_schema.yml -g java -o /local/
```

##### Steps to reproduce

1. Generate using the steps above
2. The following methods will be missing a value in `localVarContentTypes`:
    a. DevicesApi:devicesReleaseUpdateCall
    b. GroupsApi:groupsReserveByNameUpdateCall
    c. ReservationsApi:reservationsUpdateCall
    d. and several more

##### Related issues/PRs

None I am aware of.

##### Suggest a fix

Simply adding a value in `localVarContentTypes` fixes the issue. For example, the original example works fine after adding `"application/json"`:
```
public okhttp3.Call reservationsUpdateCall(UUID id, final ApiCallback _callback) throws ApiException {
    [...]
    final String[] localVarContentTypes = {
        "application/json"
    };
    [...]
}
```

**Comment by borsch** [comment]
@panargirakis could you please clarify where exactly NPE occurs?

I found following. When `localVarContentTypes` is empty then result of ` localVarApiClient.selectHeaderContentType(localVarContentTypes);` would be null, but next `if (localVarContentType != null)` should handle that fine.

So in the end `localVarHeaderParams` would be without `Content-Type` header but this shouldn't produce NPE

```java
final String[] localVarContentTypes = {
            
};
final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
if (localVarContentType != null) {
    localVarHeaderParams.put("Content-Type", localVarContentType);
}
```

**Comment by panargirakis** [comment]
Hi @borsch, the NPE occurs at ApiClient.java:1133. 

Specifically, I think the following leads to the exception:
1. `localVarContentType` is null so the `Content-Type` header never gets added to `localVarHeaderParams`
2. in ApiClient.java:1119, this line returns null: `String contentType = headerParams.get("Content-Type");`
3. In ApiClient.java:1133 `MediaType.parse(contentType)` raises the exception

Stack trace:
```
Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull
java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.MediaType$Companion.parse, parameter $this$toMediaTypeOrNull
	at okhttp3.MediaType$Companion.parse(MediaType.kt)
	at okhttp3.MediaType.parse(MediaType.kt)
	at org.infra_sw.hwmux.client.ApiClient.buildRequest(ApiClient.java:1133)
	at org.infra_sw.hwmux.client.ApiClient.buildCall(ApiClient.java:1089)
	at org.infra_sw.hwmux.client.api.GroupsApi.groupsReserveUpdateCall(GroupsApi.java:1492)
	at org.infra_sw.hwmux.client.api.GroupsApi.groupsReserveUpdateValidateBeforeCall(GroupsApi.java:1504)
	at org.infra_sw.hwmux.client.api.GroupsApi.groupsReserveUpdateWithHttpInfo(GroupsApi.java:1541)
	at org.infra_sw.hwmux.client.api.GroupsApi.groupsReserveUpdate(GroupsApi.java:1523)
	at org.infra_sw.hwmux.client.api.GroupsApiTest.groupsReserveUpdateTest(GroupsApiTest.java:229)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	[...]
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```
