### ISSUE TITLE
Default MediaType for ApiClient 

### ISSUE THREAD

**Issue by uhushcha** [OpenAPITools/openapi-generator#12170]
https://github.com/OpenAPITools/openapi-generator/blob/6a77660b08eb16d1d1ed577778b11fe46219b559/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache#L563

Is it expected ? In previous version returned JSON by default 

`        if (contentTypes.length == 0) {
            return MediaType.APPLICATION_JSON;
        }
`

**Comment by wing328** [comment]
we no longer make application/json as the default as it may some use cases.

if the content-tyep is indeed "application/json", please update your spec accordingly.
