### ISSUE TITLE
[rust-server] HTTPS support is currently linux-only

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#1221]
##### Description

See https://github.com/Metaswitch/swagger-rs/issues/43. If you try to use HTTPS on a non-linux platform, you'll hit `unimplemented!("See issue #43 (https://github.com/Metaswitch/swagger-rs/issues/43)")`

##### Related issues/PRs

Found in https://github.com/OpenAPITools/openapi-generator/issues/1199#issuecomment-428744241

**Comment by bcourtine** [comment]
For client generation, is the problem reproducible with "Reqwest" library? I used Reqwest instead of Hyper specially to simplify https management.

**Comment by richardwhiuk** [comment]
Fixed in https://github.com/OpenAPITools/openapi-generator/pull/5564
