### ISSUE TITLE
[BUG][python] PEP8 E111 issue in rest.mustache file

### ISSUE THREAD

**Issue by swimmwatch** [OpenAPITools/openapi-generator#12228]
##### Description

Hello! I found [PEP8 E111](https://www.flake8rules.com/rules/E111.html) issue in [rest.mustache](https://github.com/OpenAPITools/openapi-generator/blob/85df431ebf7b2fbdb8fa95ba90d153df8a4ef98c/modules/openapi-generator/src/main/resources/python/rest.mustache).

##### openapi-generator version

5.4.0

##### OpenAPI declaration file content or url

None

##### Command line used for generation

docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i https://api.opendota.com/api \
    -g python \
    -o /local/out/python

##### Steps to reproduce

Generate code with python template

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/12229

##### Suggest a fix/enhancement

https://github.com/OpenAPITools/openapi-generator/pull/12229

**Comment by swimmwatch** [comment]
This problem was fixed

**Comment by wing328** [comment]
Thanks again for the PR.
