### ISSUE TITLE
[BUG] [Python] OneOf incorrectly propagates constraints

### ISSUE THREAD

**Issue by thomas-intellegens** [OpenAPITools/openapi-generator#12245]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generator attempts to propagate constraints up from inner models incorrectly. See the attached gist for an example, where the constraint from one branch of a OneOf clause has been carried into the parent despite the other branch explicitly contradicting that assertion.

##### openapi-generator version

Observed on 5.0.0 through 5.4.0 and 6.0.0-20220426.131944-144

##### OpenAPI declaration file content or url

https://gist.github.com/thomas-intellegens/5cc461232d394dbec324cbb1094a1fb0

##### Generation Details

Where mini.yaml is as attached above:
```bash
java -jar openapi-generator-cli-<v>.jar generate -i mini.yaml -g python -o /out/
```

##### Steps to reproduce

1. Run the above command.
2. Examine the resulting file in `/out/models/test_parent.py`
3. Resulting file contains:
    ```python
    ...
    allowed_values = {
       ('num',): {
          '0': 0,
       },
    }
    ...
    ```

This is incorrect according to the specification, and results in any response following the non-empty path being rejected incorrectly.

##### Related issues/PRs

As far as I can tell this hasn't been reported before, but it may potentially be connected to some of the many OneOf/AnyOf/AllOf bugs being reported.

##### Suggest a fix

I couldn't find the part responsible for constraint propagation, but in general it is only safe for AllOf constraints (unless the same constraint, or potentially a 'stricter' one though that may be hard to define, appears in every branch of an OneOf or AnyOf)

**Comment by spacether** [comment]
Can you please try this with python-experimental?
It has better composition support and schema isolation

**Comment by spacether** [comment]
Please upgrade to the python generator in our v6.2.0 release.
It does not propagate constraints higher so it closes out this issue
