### ISSUE TITLE
[BUG][python-experimental] calling a delete method with just a path parameter fails

### ISSUE THREAD

**Issue by MAKOMO** [OpenAPITools/openapi-generator#12265]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Calling a delete method with just a path parameter fails with 

```python
# python3 bug.py
Exception when calling Api: (0)
Reason: Cannot prepare a request message for provided
                             arguments. Please check that your arguments match
                             declared content type.
```

This works with a client generated with the standard python generator, changing the method call to

```
#main_api_instance.delete_coffee(path_params={"id":"12"})
main_api_instance.delete_coffee(12)
```

##### OpenAPI declaration file content or url

```yam
openapi: 3.0.3
info:
  title: delete
  description: delete with empty body
  version: 0.0.1
tags:
  - name: main
servers:
  - url: https://localhost:62602/api/v1
    description: Production server
paths:
  "/coffees/{id}":
    delete:
      operationId: deleteCoffee
      summary: Delete coffee
      description: Delete the coffee identified by the given id
      tags:
        - main
      parameters:
        - name: id
          in: path
          description: The internal object id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
        default:
          description: Unexpected error
```

##### Generation Details

Client generated with the current python_experimental from trunk

##### Steps to reproduce

```
# java -jar ./tools/Generator/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i delete-bug.yaml -g python-experimental -o ./_build/client/
# cd _build/client
# sudo python3 setup.py install
# cd
# python3 bug.py 
```

with `bug.py` as follows

```python
from pprint import pprint
import time

import openapi_client
from openapi_client.api import main_api

# Logging
import os
import logging
logging.basicConfig(level=os.environ.get("LOGLEVEL", "DEBUG"))


# Configure API
configuration = openapi_client.Configuration(
  server_index = 0
)
configuration.verify_ssl = False
configuration.debug = True


# Enter a context with an instance of the API client    
with openapi_client.ApiClient(configuration) as api_client:
    try:
        main_api_instance = main_api.MainApi(api_client)
        main_api_instance.delete_coffee(path_params={"id":"12"})
        #main_api_instance.delete_coffee(12)
    except openapi_client.ApiException as e:
        print("Exception when calling Api: %s\n" % e)
```

##### Related issues/PRs

None found

##### Suggest a fix

This fails in `rest.py:request()` which is called with
```
method=DELETE
url=https://localhost:62602/api/v1/coffees/12
query_params=None
headers?{'User-Agent': 'OpenAPI-Generator/1.0.0/python'}
fields=None
body=None
```
as `body` is None. Maybe `body` should be the empty string here?

It works in the client generated with the standard python generator as this is covered by the first case as `'Content-Type' not in headers`.

Maybe here the case of `body=None` and `query_params=None` with `Content-Type` not in headers should be covered here by setting the `body=""`?

**Comment by spacether** [comment]
@MAKOMO want to submit a PR fixing this? Is it blocked by the double encoding fix?

**Comment by MAKOMO** [comment]
@spacether : I would love to, but I feel that I do not have enough understanding of the intended architecture of all of this. Of course I could submit a PR with a quick fix, but that might break other things. I am also not even sure that what I am doing should work at all as I am not too firm in the OpenAPI specification language itself.

**Comment by MAKOMO** [comment]
I see no relation to the double encoding issue.

**Comment by spacether** [comment]
Hmm this is happening because there is no body in the request so there is no content-type.
You hit a corner case. Let me fix it.

**Comment by spacether** [comment]
Fixed!
