### ISSUE TITLE
nodejs-express-server model generation

### ISSUE THREAD

**Issue by usherj** [OpenAPITools/openapi-generator#12274]
I believe it is critical for any server implementation to include both controller and model aspects generated from the contract. This link https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/nodejs-express-server/README.md#models indicates that there is a question if models should be generated from this package. I would like to encourage you to provide models for this package so I can support this team.  

I have a team within my company that would like to generate based on contract using Node. 

I am not knowledgeable on node personally, but I can generate using existing generator, but no models are currently generated. Can you please provide way for this team to use this generator.

**Comment by usherj** [comment]
I am just going to do multiple code gens on same contract to accomplish providing models.

**Comment by wilml** [comment]
Can you clarify what you mean by doing "multiple code gens" to generate the model? The models included in the sample are in Javascript. Are you saying that you are using another Javascript generator?
