### ISSUE TITLE
[Question] [Go] How could I specify the generated golang client model files in a ceratin folder?

### ISSUE THREAD

**Issue by yzhaoyu** [OpenAPITools/openapi-generator#12307]
<img width="266" alt="企业微信截图_16519241735329" src="https://user-images.githubusercontent.com/33920876/167253008-71fa3d2a-02ce-4319-885e-cf3c4d39d59d.png"> 
As the image, there are too many model files in the generated golang client, how could I specify the model files in a certain folder for code clean?

**Comment by gcatanese** [comment]
I don't think this is supported (all generated code is placed in the specified `output` param)
