### ISSUE TITLE
[BUG][JAVA] ApiClientHttpRequestInterceptor.headersToString throws 

### ISSUE THREAD

**Issue by ohl-nemeses** [OpenAPITools/openapi-generator#12319]
#### Bug Report Checklist

- [-] Have you provided a full/minimal spec to reproduce the issue?
- [-] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [/] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [/] Have you searched for related issues/PRs?
- [/] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Method `headersToString` throws an `StringIndexOutOfBoundsException` in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L844 if given `HttpHeaders` are empty. 

##### openapi-generator version

I was using 
```xml
      <plugin>
        <groupId>io.swagger.codegen.v3</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>3.0.33</version>
      </plugin>
```

##### Generation Details
Java, RestTemplate

##### Steps to reproduce

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.base/java.lang.AbstractStringBuilder.setLength(AbstractStringBuilder.java:275)
        at java.base/java.lang.StringBuilder.setLength(StringBuilder.java:85)
        at com.anypackage.swagger.ApiClient$ApiClientHttpRequestInterceptor.headersToString(ApiClient.java:586)
        at com.anypackage.swagger.ApiClient$ApiClientHttpRequestInterceptor.logResponse(ApiClient.java:572)
        at com.anypackage.swagger.ApiClient$ApiClientHttpRequestInterceptor.intercept(ApiClient.java:558)
...
```
It is plain to see that the generated utility method is erroneous in corner cases:
```java
        private String headersToString(HttpHeaders headers) {
            StringBuilder builder = new StringBuilder();
            for (Entry<String, List<String>> entry : headers.entrySet()) {
                builder.append(entry.getKey()).append("=[");
                for (String value : entry.getValue()) {
                    builder.append(value).append(",");
                }
                builder.setLength(builder.length() - 1); // Get rid of trailing comma
                builder.append("],");
            }
            builder.setLength(builder.length() - 1); // Get rid of trailing comma
            return builder.toString();
        }
```

##### Related issues/PRs
None.
##### Suggest a fix
Return empty string if headers are empty or `null`.
```java
        private String headersToString(HttpHeaders headers) {
            if(headers == null || headers.isEmpty()) {
                return "";
            }
            StringBuilder builder = new StringBuilder();
            for (Entry<String, List<String>> entry : headers.entrySet()) {
                builder.append(entry.getKey()).append("=[");
                for (String value : entry.getValue()) {
                    builder.append(value).append(",");
                }
                builder.setLength(builder.length() - 1); // Get rid of trailing comma
                builder.append("],");
            }
            builder.setLength(builder.length() - 1); // Get rid of trailing comma
            return builder.toString();
        }
```

**Comment by wing328** [comment]
@ohl-nemeses thanks for reporting the issue. I wonder if you can file a PR with the suggested fix when you've time.

**Comment by ohl-nemeses** [comment]
Here you go: https://github.com/OpenAPITools/openapi-generator/pull/12327
