### ISSUE TITLE
[REQ] [Typescript] add repository field to package.json

### ISSUE THREAD

**Issue by witem** [OpenAPITools/openapi-generator#12333]
### Is your feature request related to a problem? Please describe.

In cases when we want to release generated client in a private repository `repository` field is required for GitHub Actions.

## Describe the solution you'd like

Add `repository` field based on: `gitHost`, `gitUserId`, `gitRepoId` values similar to other generators

**Comment by patriciarrsilva** [comment]
Hello!
Is this issue fixed?
There is a merged PR but the related issue is still open.
Also, I've tried to use the gitHost, gitUserId and gitRepoId properties and it is not working.

**Comment by witem** [comment]
@patriciarrsilva yes, this is fixed by PR
