### ISSUE TITLE
csharp-netcore generator is awful

### ISSUE THREAD

**Issue by fairking** [OpenAPITools/openapi-generator#12368]
Regarding this: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/csharp-netcore.md

1. no ability to disable validation. sometimes api descriped required parameters which are not required in some combinations with others. Please consider to have an option to disable this:
``` c#
if (customerId == null)
{
    throw new WebRef.AccessPay.Client.ApiException(400, "Missing required parameter 'customerId' when calling ContractQueryingAndCreationApi->ClientClientCodeCustomerCustomerIdContractGet");
}
```

2. Api response and api exception need more data provided (method, status code, url of the request). All that is missing.
``` c#
private ApiResponse<T> ToApiResponse<T>(IRestResponse<T> response)
{
    new ApiResponse<T>()
    {
        Url = response.ResponseUri.GetLeftPart(UriPartial.Path), // Added
        Method = response.Request.Method.ToString(), // Added
    }
}
public static readonly ExceptionFactory DefaultExceptionFactory = (methodName, response) =>
{
    return new ApiException(status,
                    string.Format("Error calling {0}: {1}", methodName, response.RawContent),
                    response.RawContent, response.Headers)
                {
                    Url = response.Url, // Added
                    Method = response.Method, // Added
                };
}
```

3. `response.Data` is always empty. Had to add manually the following lines:
``` c#
else if (typeof(T).Name == "Stream") // for binary response
{
    response.Data = (T)(object)new MemoryStream(response.RawBytes);
}
else // Added
{ // Added
    response.Data = JsonConvert.DeserializeObject<T>(response.Content); // Added
} // Added
```

4. RestSharp is not working properly. please consider to use HttpClient by default.

5. Please make code more readable and simple. In my opinion the client is overcomplicated. Complicated things never survive and always will be dead.

6. Allow to not throw an exception but return the original response with `status >= 400` as it is.

**Comment by devhl-labs** [comment]
@fairking I completely agree with everything you said, so much that I wrote my own library. It uses HttpClient, integrates with the generic host, and enables you to inherit the Api classes to define your own validation. You can give it a try by appending `--library generichost`.  The files are entirely different, so start with an empty folder if you can.

Note that there are two PRs submitted to fix some issues. Inheriting the api for custom validation is in one of them.

**Comment by alexeyzimarev** [comment]
> RestSharp is not working properly

I am sorry, but you are wrong here. If you use RestSharp according to the documentation, it works just fine.

**Comment by fairking** [comment]
Ok. I fixed my issue by implementing own generator.
Contributors are welcome: https://gitlab.com/fairking/unigen

Neither `nswag` or `codegen` are not working properly.
