### ISSUE TITLE
[python-experimental] `BoolSchema` `is_false()` method returns same result as `is_true()`

### ISSUE THREAD

**Issue by meawoppl** [OpenAPITools/openapi-generator#12388]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The logic generated by the `python-experimental` code generator has identical logic for the functions `is_true()` and `is_false()` on anything that uses `BoolSchema`

##### openapi-generator version

6.0.0 beta

##### OpenAPI declaration file content or url

```yaml
---
openapi: 3.0.1
info:
  contact:
    email: foo@bar.io
  description:
  title: API
  version: 0.1.0
servers:
  - url: "/"
paths:
  "/info":
    get:
      description: blah
      operationId: get_info
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: boolean
          description: Success - Information returned
      summary: BarBaz
```

##### Generation Details

```bash
java -jar .openapi/openapi-generator-cli.jar generate      \
        --input-spec openapi/observatory.yaml              \
        --generator-name python-experimental               \
        --output .openapi/observatory_api                  \
        --package-name=observatory_api
```

##### Steps to reproduce

```python
result = whatever.get_info()

# This is totally wrong
result.body.foo().is_false() == result.body.foo().is_true()
```

Note that in the generated file `schemas.py` `BoolClass` is generated as follows:
```python
class BoolClass(Singleton):
    @classmethod
    @property
    def TRUE(cls):
        return cls(True)

    @classmethod
    @property
    def FALSE(cls):
        return cls(False)

    @functools.cache
    def __bool__(self) -> bool:
        for key, instance in self._instances.items():
            if self is instance:
                return key[1]
        raise ValueError('Unable to find the boolean value of this instance')

    def is_true(self):
        return bool(self)

    def is_false(self):
        return bool(self)   # WTF ^^

```

See

##### Suggest a fix

Check out #12396

**Comment by meawoppl** [comment]
Fixed by: https://github.com/OpenAPITools/openapi-generator/pull/12396

**Comment by spacether** [comment]
While investigating this I also noticed that is_none, is_true, and is_false should be moved one class level higher into the base class mixings BoolBase NoneBase so those methods can be visible in pycharm.

**Comment by meawoppl** [comment]
Yeah, that would make more sense for sure. I was just pretty confused by
`result.bool_value.is_true() == result.bool_value.is_false()`
