### ISSUE TITLE
[BUG][JavaSpring] NumberFormatException on @QueryParam's defaultValue for long, float and double

### ISSUE THREAD

**Issue by juanpablo-santos** [OpenAPITools/openapi-generator#12434]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

`NumberFormatException` is raised for a QueryParam of type long/float/double variable with default value

##### openapi-generator version

At least v.4.3.1 through v.6.0.0-beta are affected by this bug

##### OpenAPI declaration file content or url

Having a query parameter like
```yaml
[...]
- name: planTypeId
  in: query
  description: |
    Identificator Origin of plan.
    * `1` - Digital
    * `2` - Analog
  schema:
  type: integer
  format: int64
  default: 1
```
for the JavaSpring language, generates something like:

```java
[...]
@Valid @RequestParam( value = "planTypeId", required = false, defaultValue = "1l" ) Long planTypeId
```

When that endpoint is invoked without specifying a value, the `defaultValue` is taken into account, which ends up yielding something like

```
Caused by: java.lang.NumberFormatException: For input string: "1l"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
at java.base/java.lang.Long.parseLong(Long.java:699)
at java.base/java.lang.Long.valueOf(Long.java:1151)
at org.springframework.util.NumberUtils.parseNumber(NumberUtils.java:214)
at org.springframework.beans.propertyeditors.CustomNumberEditor.setAsText(CustomNumberEditor.java:115)
at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:429)
at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:402)
at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:155)
at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:73)
at org.springframework.beans.TypeConverterSupport.convertIfNecessary(TypeConverterSupport.java:53)
at org.springframework.validation.DataBinder.convertIfNecessary(DataBinder.java:726)
```
Spring expects the value to not contain letters.

Code responsible of adding that extra `l` is located on [`AbstractJavaCodegen`](https://github.com/OpenAPITools/openapi-generator/blob/v6.0.0-beta/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L926-L934). Same thing happens for floats or doubles. Perhaps the JavaSpring language should overwrite that method and strip offending letters for those cases?

##### Generation Details

any contract with the java spring language with demo values will do, as long as there is at least one endpoint with a parameter of type long, float or double with a default value (like above)

##### Steps to reproduce

any endpoint with a parameter of type long, float or double with a default value (like above)

##### Related issues/PRs

issue #540 is the most related issue I've found, although it isn't that closely related.

##### Suggest a fix

Perhaps the JavaSpring language should overwrite that method and strip offending letters for those cases?

**Comment by borsch** [comment]
@juanpablo-santos to set default value for parameters this method is used - AbstractJavaCodegen#toDefaultParameterValue

I've tries to reproduce your this issue with latest master but everything works fine. Could you please share configuration of openapi-generator that you are using
