### ISSUE TITLE
[BUG] Codegen operation missing import of enum when enum is parameter

### ISSUE THREAD

**Issue by samuelo** [OpenAPITools/openapi-generator#12445]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When operation has enum as parameter, the enum is not added to the imports.

##### openapi-generator version

This is happening in master (6.0.0) and doesn't happen in 5.4.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  version: 1.0.0
  title: Example
  license:
    name: MIT
servers:
  - url: http://api.example.xyz/v1
paths:
  /pets/petType/{type}:
    get:
      parameters:
        - name: 'type'
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/PetByType'
      responses:
        '200':
          description: 'get by type'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'

components:
  schemas:
    Pet:
      type: object
      properties:
        petType:
          $ref: '#/components/schemas/PetByType'
      required:
        - petType
    Dog:
      allOf:
        # This field will not match to any type.
        - description: Dog information
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            hunts:
              type: boolean
            age:
              type: integer
    PetByType:
      type: string
      enum: [Cat, Dog]
```

##### Steps to reproduce

e.g. When generating java client code the enum import will be missing from the api class.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/12446
