### ISSUE TITLE
[Kotlin] [Feature] Add config to have internal visibility modifier added to all generated files

### ISSUE THREAD

**Issue by wittlock** [OpenAPITools/openapi-generator#12440]
##### Description

Kotlin has a nice feature with it's _internal_ visibility keyword to make classes only visible within the current module of the application. I quite like using it for generated code, which can be plentiful, to prevent it from bleeding into the rest of the project, keeping autocomplete less cluttered.
Adding internal to generated Kotlin classes does not break java interoperability but they do get slightly mangled names to make them more clearly unintended for use, see [documentation](https://kotlinlang.org/docs/java-to-kotlin-interop.html#visibility).

##### openapi-generator version

5.4.0

##### Suggest a fix/enhancement

I'm thinking this would be a fairly simple and small thing to add as a first contribution of my own to this project. So I'm planning on offering up the addition myself but going by the contributing guidelines I'm writing an issue about it first to see if there's feedback or objections to be had first.
Config option name suggestion would be simply _internal_ or _internalVisibility_ and default to false.

**Comment by mustafaozhan** [comment]
Looking forward to see this as well!

**Comment by soniaswer** [comment]
Hi there, I was wondering if it has been resolved yet or not? I have the same requirement, where I am supposed to add internal keyword to classes, and if possible to classes only in certain directory. So, was wondering if it was ever fixed. In case yes, what's the config param?

**Comment by wittlock** [comment]
Yeah, that looks like exactly what I was looking for. Closing this issue as it's now redundant.
