### ISSUE TITLE
PHP 5.x reaches the end of life by the end of 2018

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#1246]
##### Description

PHP 5.x reaches the end of life by the end of 2018 so we need to upgrade our PHP clients, servers to use PHP 7.x as the default.

Ref: http://php.net/supported-versions.php

##### openapi-generator version

I suggest we do it as part of the 4.0.0 release (next major release)

##### Suggest a fix/enhancement

If anyone wants to help on this, please reply to let us know.

**Comment by wing328** [comment]
cc @jebentier (2017/07) @dkarlovi (2017/07) @mandrean (2017/08) @jfastnacht (2017/09) @ackintosh (2017/09) @ybelenko (2018/07)

**Comment by ackintosh** [comment]
There are worthwhile challenges ✨:

- Replace deprecated stuffs
- Apply new features
- Update dependencies

[PHP: Migrating from PHP 5.6.x to PHP 7.0.x - Manual](http://php.net/manual/en/migration70.php)

**Comment by ybelenko** [comment]
I'm working on PHP Slim refactoring descripted in #426. In short it's separating generated stubs from user implementation. I'm quite sure that it will be breaking changes without fallback, so maybe we should include both migration to 7.0.x and interfaces/implementation refactoring to the next release?

@ackintosh @wing328 Does it sounds right to you?

**Comment by ackintosh** [comment]
Thanks for your great work. It sounds good to me. 👍

**Comment by jacobweber** [comment]
The php [README](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php/README.mustache) still says "Requirements: PHP 5.5 and later"

**Comment by wing328** [comment]
@jacobweber good catch. Do you mind filing a PR to update it (template)?

**Comment by arderyp** [comment]
So this issue is still out there.  Any hopes of addressing it soon?  5 is long gone by now.

**Comment by ybelenko** [comment]
### Current progress of migration to PHP 7.x:

| generator            | `README.md` | `composer.json` | `@phpdoc` |
|-----------------:|:---------------:|:-----------------:|:-----------:|
|php-client            |                            |             ✅             |                     |
|php-laravel          |                            |             ✅             |                     |
|php-lumen          |                             |             ✅             |                     |
|php-silex             |                             |                               |                     |
|php-slim              |             ✅           |            ✅             |         ✅       |
|php-slim4            |             ✅           |            ✅             |         ✅       |
|php-symfony *️⃣ |                            |                               |                     |
|php-ze-ph           |             ✅           |            ✅             |         ✅       |

*️⃣  has pull request, work in progress
