### ISSUE TITLE
[BUG][Typescript][csharp-netcore][Rust] Duplicate model files with just different interface name

### ISSUE THREAD

**Issue by coder925** [OpenAPITools/openapi-generator#12478]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

`6.0.0`

Regression: Yes. This issue does not occur in e.g. `6.0.0-beta` or `5.4.0`.

##### OpenAPI declaration file content or url

[swagger.json gist](https://gist.github.com/coder925/f98bbc3da8b33e79694f5139ab9e2e67)

##### Steps to reproduce

`openapi-generator-cli generate -g typescript-angular -i swagger.json -o ./src/app/person-api`

_Expected_ output in model folder:
- models.ts
- person.ts
- address.ts

_Actual_ output in model folder:
- models.ts
- person.ts
- address.ts
- personAddress.ts (duplicate of address.ts - just changed interface name)
- personsGetRequest.ts (duplicate of person.ts - just changed interface name)

##### Related issues/PRs

None found.

**Comment by Brutusn** [comment]
I have the same issue, issue still exists in v6.0.1

**Comment by coder925** [comment]
Issue still exists in v6.1.0.

**Comment by felschr** [comment]
Same things happens with the `csharp-netcore` generator, but the models are `class`es which make it even more of an issue.

**Comment by whirm** [comment]
Minimal example yaml:
```yaml
---
openapi: 3.0.3
info:
  title: Nesting Duplicates Models
  version: v1
paths:
  /api:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Foo'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Foo'
components:
  schemas:
    Foo:
      type: object
      properties:
        nested_bar:
          allOf:
          - $ref: '#/components/schemas/Bar'
    Bar:
      type: object
      properties:
        baz:
          type: boolean
```

Output in Rust:

```sh
# ls src/models -1
bar.rs
foo_nested_bar.rs
foo.rs
mod.rs
```

**Comment by whirm** [comment]
@coder925 Seeing that it's not just a Typescript issue, maybe it's worth updating the issue title/description?

**Comment by coder925** [comment]
> @coder925 Seeing that it's not just a Typescript issue, maybe it's worth updating the issue title/description?

@whirm , I have updated the title with the languages/libraries that the issue been verified for. Please give me a suggestion if you think the title can be improved further.

**Comment by whirm** [comment]
@spacether is this related to the discussion you are having with @kyrias on https://github.com/OpenAPITools/openapi-generator/issues/10780?

**Comment by spacether** [comment]
To me they look different. I think that this is caused by the inline model resolver extracting complex nested schemas into components and $refing them

**Comment by coder925** [comment]
I revisited this old issue and it seems to have been fixed. In version **7.3.0**, the steps to reproduce now generate the expected output. I will go ahead and close this issue.
