### ISSUE TITLE
[PHP] Incorrect return types if multiple responses are defined

### ISSUE THREAD

**Issue by fMads** [OpenAPITools/openapi-generator#125]
##### Description

If you define multiple responses, the codegen will only support the first one (typically 200).

##### openapi-generator version

3.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
  /path
    post:
      responses:
        200:
          schema:
            $ref: '#/definitions/EmptyResponse'
        202:
          schema:
            $ref: '#/definitions/InBackgroundResponse'
```

##### Suggest a fix/enhancement

Correctly generate the return-object based on the HTTP Status Code in the Response.
Also fix ReturnType info in DocBlock

**Comment by ackintosh** [comment]
@fMads #128 is merged! Thanks for your contribution.

**Comment by slind85** [comment]
This is still happening for Java
