### ISSUE TITLE
Kotlin: IntellJ idea plugin and gradle wrapper omitting

### ISSUE THREAD

**Issue by anttikarhu** [OpenAPITools/openapi-generator#12500]
Hi :) 

When generating a Kotlin API project, the source folders are not marked as such. Also if the project is to be part of a larger project, one should be able to omit the gradle wrapper part of the build.gradle to make it compilable.

I made a commit to a fork/branch following a custom template we use in our project: https://github.com/OpenAPITools/openapi-generator/compare/master...anttikarhu:kotlin-idea-plugin-and-omit-gradle-wrapper

It's very simple change, and I understand if it's something not wanted in the main, since you can easily create a custom template for it. What do you think?

**Comment by takkiraz** [comment]
@wing328 
I think this can be close, right?
