### ISSUE TITLE
[cpp-pistache-server] newItem.fromJson() always called even when type is std::string

### ISSUE THREAD

**Issue by brianwaters3** [OpenAPITools/openapi-generator#1251]
##### Description

The fromJson method defined via **model-source.mustache** declares newItem to be of type items.datatype.  When processing an array of stings this results in generating declaring newItem as std::string and subsequently attempting to execute the fromJson() method which is undefined.  In this case, here is a snippet of the generated code for UePerLocationReport::fromJson(nlohmann:json& val).

```
...
void UePerLocationReport::fromJson(nlohmann::json& val)
{
    setUeCount(val.at("ueCount"));
    {
        m_ExternalIds.clear();
        nlohmann::json jsonArray;
        if(val.find("externalIds") != val.end())
        {
        for( auto& item : val["externalIds"] )
        {

            if(item.is_null())
            {
                m_ExternalIds.push_back( std::string() );
            }
            else
            {
                std::string newItem;
                newItem.fromJson(item);
                m_ExternalIds.push_back( newItem );
            }

        }
        }
    }
...
```

##### openapi-generator version

3.3.0

##### OpenAPI declaration file content or url

Archive .zip contains the yaml and support files to reproduce the issue.

[Archive.zip](https://github.com/OpenAPITools/openapi-generator/files/2480769/Archive.zip)

##### Command line used for generation

java -jar ~/code/git/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i updated/TS29122_MonitoringEvent.yaml -g cpp-pistache-server --config __config__ -o ./src/MonitoringEvent/

Modify the openapi-generator-cli.jar path to match your system.

##### Steps to reproduce

1. Create a blank working directory
2. Unzip Archive.zip to the newly created directory.
3. Generate the source using the provided command making path adjustments for your system.
4. Install pistache.io.
4. Compile with the following command:

g++  -g -pthread -std=c++11  -I ./include -I ./src/MonitoringEvent/api -I ./src/MonitoringEvent/impl -I t8/src/MonitoringEvent/model  -c -o ./UePerLocationReport.o ./src/MonitoringEvent/model/UePerLocationReport.cpp

**Comment by wing328** [comment]
@brianwaters3 thanks for reporting the issue.

What does the correct code look like?

cc @ravinikam (2017/07) @stkrwork (2017/07) @fvarose (2017/11) @etherealjoy (2018/02) @martindelille (2018/03)

**Comment by MartinDelille** [comment]
@brianwaters3 Publishing the code on a gist or a github repository would make the analysis easier.

**Comment by etherealjoy** [comment]
This issue is known.
map/array support is lacking very much in most of the clients and server, especially nested maps/arrays.
However I have been able to get good nested map/array support only on `cpp-qt-client` and `cpp-qt5-qhhtengine-server` for now.
`cpp-pistache-server` also is also improving.

**Comment by etherealjoy** [comment]
@wing328 
After debugging the topic, it seems indeed the mustache files are correct in this regard.

It seems to me there is a regression somewhere that Array members don't have the type updated properly anymore.
I checked the `postProcessOperationsWithModels` and this `std::string` does not have `isString` set to true. 
so in the mustache `{{^items.isString}}` is passing and generating wrong code.
This is a new bug, I don't remember this issue before.

**Comment by CyrilleBenard** [comment]
Also interested in a fix 
(post to follow this issue :) )

**Comment by CyrilleBenard** [comment]
Any news on this bug fix ?
Last week I checked the current status of PR #1296 but it did not fixed this current issue.

**Comment by etherealjoy** [comment]
indeed, It solves at top level only. needs to be done still.

**Comment by etherealjoy** [comment]
I tried this now on the `4.0.0` branch and it is solved.
