### ISSUE TITLE
[REQ] OpenAPI Maven Codegen should start using Jakarta Bean Validation instead of Javax Bean Validation for bean validation

### ISSUE THREAD

**Issue by papatil-mdsol** [OpenAPITools/openapi-generator#12526]
### Is your feature request related to a problem? Please describe.
OpenAPI Maven Codegen is using Javax Bean Validation Library for bean validation, which is moved to Jakarta.

## Describe the solution you'd like
OpenAPI Maven Codegen should start using Jakarta Bean Validation instead Javax Bean Validation for bean validation

OpenAPI Maven Codegen should start using Jakarta Bean Validation instead Javax Bean Validation for bean validation

**Comment by honza-zidek** [comment]
Is there any progress please? 

With the release of Spring Boot 3.0, it is a **showstopper** now.

**Comment by propas** [comment]
Spring generator has "useSpringBoot3" config options. It should be true by default, but you have to specified it. 
<configOptions>
   <useSpringBoot3>true</useSpringBoot3>
</configOptions>

I have version of openapi-generator-maven-plugin 6.2.1

**Comment by honza-zidek** [comment]
@propas Spring generator, as the [documentation](https://openapi-generator.tech/docs/generators/spring/) says, is a SERVER generator type. We need this also in the CLIENT generator types, especially [java](https://openapi-generator.tech/docs/generators/java/).

**Comment by Franknjava** [comment]
This should be a general feature. We are genereting jaxrs-resteasy server for Quarkus and it is a showstopper with current version, too.

**Comment by m-goppelt** [comment]
Any updates on this?

**Comment by papatil-mdsol** [comment]
Closing the issue as OpenAPITools now supporting the Jakarta Bean Validation and Jakarta Persistence.
`<configOptions>
        <useBeanValidation>true</useBeanValidation>
        <useJakartaEe>true</useJakartaEe>
</configOptions>`
