### ISSUE TITLE
[BUG] [Kotlin-client] Handling default value of enum parameter

### ISSUE THREAD

**Issue by joethehoff** [OpenAPITools/openapi-generator#12531]
OpenAPIGenerator 6.0.0 produces incorrect kotlin code for a enum parameter with default value.

https://gist.github.com/joethehoff/7373e4b91b57531df6dc15162803f095

The generator produces following code:
```java
@Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun workOrdersGet(color: Color_workOrdersGet? = blue) : Unit {...}

    /**
     * enum for parameter color
     */
     enum class Color_workOrdersGet(val value: kotlin.String) {
         @Json(name = "blue") blue("blue"),
         @Json(name = "red") red("red"),
         @Json(name = "yellow") yellow("yellow"),
         @Json(name = "black") black("black")
     }

```
The kotlin compiler produces the error message:
Unresolved reference: blue

The generator configuration:
```xml
<configuration>
    <inputSpec>${project.basedir}/api/work-api.json</inputSpec>
    <generatorName>kotlin</generatorName>
    <generateApiTests>false</generateApiTests>
    <generateModelTests>false</generateModelTests>
    <apiPackage>xxx.controller</apiPackage>
    <modelPackage>xxx.gen.model</modelPackage>
    <apisToGenerate>WorkOrderServiceV2</apisToGenerate>
    <skipValidateSpec>true</skipValidateSpec>
    <configOptions>
        <enumPropertyNaming>camelCase</enumPropertyNaming>
    </configOptions>
    <additionalProperties>interfaceOnly</additionalProperties>
</configuration>
```

**Comment by Ranbato** [comment]
I have the same issue. I found that if I fully qualify the default (in the above case it would be `Color_workOrdersGet? = Color_workOrdersGet.blue ` that it compiles correctly.

**Comment by joethehoff** [comment]
> I have the same issue. I found that if I fully qualify the default (in the above case it would be `Color_workOrdersGet? = Color_workOrdersGet.blue ` that it compiles correctly.

Thank you for your advice, but i think this is only a workaround, because the name of the enum-class is a decision made by the generator. Therefore the generated enum class should not be referenced in the json definition of the api.

**Comment by leonfau** [comment]
Hey, I provided an example in the pull request thread: https://github.com/OpenAPITools/openapi-generator/pull/12850#issuecomment-1192267436
