### ISSUE TITLE
Inconsistent filenames in Typescript

### ISSUE THREAD

**Issue by smasala** [OpenAPITools/openapi-generator#1253]
##### Description

When using the argument `fileNaming=kebab-case`, the names in the api services are inconsistent with the actual filenames.

Api: `MySetType1Type2 -> my_set_type1_type2`
Filename: `mysettype1_type2`

##### openapi-generator version

3.3.1

##### Steps to reproduce

Declarations which include special characters (https://github.com/OpenAPITools/openapi-generator/issues/1137) and generate with: `fileNaming=kebab-case`

**Comment by wing328** [comment]
@smasala do you mind sharing a spec to reproduce the issue more easily?

cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01) @nicokoenig (2018/09)
--

**Comment by andrehaveman** [comment]
I have a similar issue with camelCase:

`MySet[Type1]`  in spec file becomes:
`mySet_Type1.ts`

but import in api service is:

`import { MySetType1 } from '../model/mySetType1';`

I used 3.3.1 with typescript-angular generator.

**Comment by smasala** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/eb4dfe0fc1362f82d91d8371e7493dc4e1195d24/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L383

How is this formatted / generated? In reference to https://github.com/OpenAPITools/openapi-generator/issues/1137 the `special` characters are already removed at this point. This is inconsistent with how filenames themselves are generated.

**Comment by andrehaveman** [comment]
We use a .Net Core backend with [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) generator. We have classes like MySet<Type1> which results in MySet[Type1] in the swagger.json file.

Version 3.2.3 didn't have this issue.

**Comment by wing328** [comment]
@andrehaveman I've merged the PR by @smasala into master. Can you give it a try using the SNAPSHOT version or the docker image?

**Comment by andrehaveman** [comment]
@wing328 Yes, it's working again. @smasala Thanks for fixing this :+1:.

**Comment by smasala** [comment]
@wing328 did this really make it into 3.3.3? The dock hub image generates wrong file names still but locally on master branch it is correct with the same spec.
