### ISSUE TITLE
[Question] How to add logging to the Swift5 Client?

### ISSUE THREAD

**Issue by wtlgo** [OpenAPITools/openapi-generator#12558]
Hello! Maybe this is a noob question, but I wasn't able to figure out that on my own.

I generated a Swift 5 client using this command
```
openapi-generator generate -i open-api.json -g swift5-client --additional-properties=objcCompatible=true
```
For debugging purposes, I wanted to add basic logging to the client to be able to see all raw HTTP requests it does and raw responses it gets, but couldn't figure out how to do that without copy-pasting the entirety of the `URLSessionImplementatios.swift` file. Is there any simple solution I am looking over?

JFI, I already have a custom `RequestBuilder` that handles authentication.

**Comment by aehlke** [comment]
to note, the above code is likely integrating the fantastic https://github.com/kean/Pulse
