### ISSUE TITLE
[BUG] [Java] [Native] Generated api client doesn't work for plain text response body types

### ISSUE THREAD

**Issue by wasifaleem** [OpenAPITools/openapi-generator#12616]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

v6.0.0

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/10885

##### Suggest a fix

if the response content type is `text/plain`  return as is, instead of parsing it via jackson

**Comment by GregoryWiltshire** [comment]
![image](https://user-images.githubusercontent.com/13462145/212362209-8781a1ae-1916-400e-98e9-b2feaba92f35.png)

Pretty sure I also had this issue (python client) with an existing api I have returning text/plain in the body, which I fixed with the above patch.
