### ISSUE TITLE
JAVA: Generated ApiException throws NullPointerException in method getMessage()

### ISSUE THREAD

**Issue by Matko88** [OpenAPITools/openapi-generator#12631]
I'm using Java 8.

##### Description

Generator generate non null-safe code and allow null pointer exception in class ApiException.

##### openapi-generator version

6.0.0

Examples:

Generated ApiException method:

    public String getMessage() {
        return String.format("Message: %s%nHTTP response code: %s%nHTTP response body: %s%nHTTP response headers: %s", super.getMessage(), this.getCode(), this.getResponseBody(), this.getResponseHeaders().toString());
    }

One of the constructors that allows null value:

    public ApiException(int code, String message) {
        super(message);
        this.code = 0;
        this.responseHeaders = null;
        this.responseBody = null;
        this.code = code;
    }

##### Steps to reproduce

I guess you can generate any client and the generated ApiException class will be the same. In my case, response headers were null and it caused NPE when I tried to print out the exception.

##### Suggest a fix/enhancement

Just add check, if value is null or prevent it from being null at first point.

**Comment by wing328** [comment]
can you please try the latest master? I pushed a fix after the v6.0.0 release.

**Comment by etiennestuder** [comment]
@wing328 Given a fix was pushed to master after 6.0.0, is it part of 6.0.1 that was released recently?

**Comment by wing328** [comment]
yes pls give it a try

**Comment by etiennestuder** [comment]
@wing328 We confirmed that it is fixed.
