### ISSUE TITLE
[BUG] kotlin generator for enum with name `name` doesn't compile

### ISSUE THREAD

**Issue by NikolayMetchev** [OpenAPITools/openapi-generator#12646]
#### Bug Report Checklist

- [X ] Have you provided a full/minimal spec to reproduce the issue?
- [ X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ X] Have you searched for related issues/PRs?
- [ X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If you use openapi generator to generate a client for Jira (https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json) and you use the `kotlin` generator the resulting code will not compile. It produces the following enum which doesn't compile because name is already a property in enum:

```
enum class OrderBy_getDashboardsPaginated(val value: kotlin.String) {
         @Json(name = "description") description("description"),
         @Json(name = "-description") minusDescription("-description"),
         @Json(name = "+description") plusDescription("+description"),
         @Json(name = "favorite_count") favoriteCount("favorite_count"),
         @Json(name = "-favorite_count") minusFavoriteCount("-favorite_count"),
         @Json(name = "+favorite_count") plusFavoriteCount("+favorite_count"),
         @Json(name = "id") id("id"),
         @Json(name = "-id") minusId("-id"),
         @Json(name = "+id") plusId("+id"),
         @Json(name = "is_favorite") isFavorite("is_favorite"),
         @Json(name = "-is_favorite") minusIsFavorite("-is_favorite"),
         @Json(name = "+is_favorite") plusIsFavorite("+is_favorite"),
         @Json(name = "name") name("name"),
         @Json(name = "-name") minusName("-name"),
         @Json(name = "+name") plusName("+name"),
         @Json(name = "owner") owner("owner"),
         @Json(name = "-owner") minusOwner("-owner"),
         @Json(name = "+owner") plusOwner("+owner")
     }
```

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url

https://developer.atlassian.com/cloud/jira/platform/swagger-v3.v3.json

##### Generation Details

kotlin generator

##### Steps to reproduce

run openApiGenerator with jira swagger file.

##### Suggest a fix

generate the actual enum name to be `name` in single quotes. You can do this for all enum names and the code should still compile.

**Comment by wing328** [comment]
Thanks for reporting the issue. Can you please file a PR with the suggested fix and we'll review accordingly?

**Comment by sebastian-ziegler** [comment]
Hello, I am also having an issue related with this.

I realised that the code generated on the request config looks like this if you use the value `PascalCase` with the config `enumPropertyNaming`

I realised that the name of the enum is being used as a value when is being passed as a parameter to make a call. But I think that actually it should use the actual value of the enum which is the correct name that is coming from the openApi definition.

```if (listingStatus != null) {
                    put("listing_status", listOf(listingStatus.toString())) // -> it is being generated like this
                }
                if (slug != null) {
                    put("slug", listOf(slug.toString())) // -> it is being generated like this
                }
                if (start != null) {
                    put("start", listOf(start.toString())) // -> it is being generated like this
                }
                if (limit != null) {
                    put("limit", listOf(limit.toString())) // -> it is being generated like this
                }
                if (sort != null) {
                    put("sort", listOf(sort.value)) // -> should be changed to be generated like this
                }`

**Comment by wing328** [comment]
@sebastian-ziegler  thanks for the fix, which has been merged into master.

@NikolayMetchev can you please pull the latest master to give it a try? (snapshot version can be found in the project's readme)

**Comment by NikolayMetchev** [comment]
Unfortunately the OpenAi generator didn't work well enough for us and we never adopted it. Perhaps one day in the future we can re-examine.

**Comment by contradictioned** [comment]
Hi, I am now at the same point: I generate kotlin code with an enum variant `name` and thus the source doesn't compile. I am using the gradle plugin `id("org.openapi.generator") version "7.0.1"`, and since the fixe mentioned above was tagged with 7.0.0 I assume it should be included.

However, I also saw that this fix was concerned with the jvm-okhttp generator, the original bug report mentioned kotlin and I am using the kotlin-server generator.
