### ISSUE TITLE
[BUG][KOTLIN] No JsonAdapter for LocalDateTime in Moshi serializer

### ISSUE THREAD

**Issue by toXel** [OpenAPITools/openapi-generator#1271]
##### Description

`date-time` fields can't be parsed from a generated Kotlin client with default configuration. It fails with this exception:
`java.lang.IllegalArgumentException: Platform class java.time.LocalDateTime annotated [] requires explicit JsonAdapter to be registered`

The reason for it is that in [Serializer.kt.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/Serializer.kt.mustache) Moshi only gets a JsonAdapter for the `java.util.Date` type but not for `java.time.LocalDateTime` (or `org.threeten.bp.LocalDateTime` when ThreeTen is used).

##### openapi-generator version

v3.3.1

##### Command line used for generation

`generate -g kotlin -i https://petstore.swagger.io/v2/swagger.yaml -o swaggerClientTest`

##### Steps to reproduce

It can be reproduced with the petstore swagger spec.

1. Generate Kotlin client with the command above.
2. Write a simple test like this:
```kotlin
@Test
fun getOrderById() {
    val order = StoreApi().getOrderById(1)
    assertNotNull(order)
}
```
3. It will fail with the respective exception.

##### Suggest a fix/enhancement

A workaround is to implement a `JsonAdapter` for the respective type and add it to Moshi in the generated `Serializer` class. Maybe this can be integrated in the generator.

**Comment by krevelen** [comment]
same for `java.util.UUID`

**Comment by jpmeijers** [comment]
I'm hitting this same issue with the `OffsetDateTime` type.

Applicable line in generated code looks like this:
```kt
    /* Absolute time when... */
    @Json(name = "absolute_time")
    val absoluteTime: java.time.OffsetDateTime? = null
```

Applicable lines in `api.swagger.json`:
```js
        "absolute_time": {
          "type": "string",
          "format": "date-time",
          "description": "Absolute time when ..."
        }
```

And the exception that moshi is throwing:
```
    java.lang.IllegalArgumentException: Platform class java.time.OffsetDateTime requires explicit JsonAdapter to be registered
    for class java.time.OffsetDateTime absoluteTime
```

**Comment by lmellick** [comment]
@jpmeijers did you find out how to use OffsetDateTime with Moshi? I have been trying to write a custom adapter but still getting errors. Thanks

**Comment by jpmeijers** [comment]
I'm not 100% sure as it's a while back, but looks like I created a custom adapter:
https://github.com/ttnmapper/ttnmapper-android-v3/blob/master/app/src/main/java/org/ttnmapper/phonesurveyor/model/ttnV3/OffsetDateTimeAdapter.kt

And then added that to the Moshi instance:
```
        val moshi = Moshi.Builder()
//                .add(KotlinJsonAdapterFactory())
                .add(OffsetDateTimeAdapter())
                .build()
```

**Comment by lmellick** [comment]
Thanks for the response! I have already tried that approach but get an error saying `com.squareup.moshi.JsonDataException: Expected a string but was BEGIN_OBJECT at path $.date`. Debugging the flow, it breaks after the "dateTime:" part of the serialised OffsetDateTime. If you have any ideas please let me know, thanks! Note: the OffsetDateTime is a property in another object.
