### ISSUE TITLE
Elixir Generator generates code with lots of warnings

### ISSUE THREAD

**Issue by halostatue** [OpenAPITools/openapi-generator#12731]
##### Description

When compiling Elixir code generated with `openapi-generator`, there are compiler warnings (this is using [ory/sdk/clients/client/elixir](https://github.com/ory/sdk/tree/master/clients/client/elixir):

```console
$ mix deps.get
warning: use Mix.Config is deprecated. Use the Config module instead
  config/config.exs:3

Resolving Hex dependencies...
Dependency resolution completed:
Unchanged:
  mime 2.0.2
  poison 3.1.0
  tesla 1.4.4
* Getting tesla (Hex package)
* Getting poison (Hex package)
* Getting mime (Hex package)
```

There are other warnings:

```console
$ mix compile
…
warning: found quoted atom "namespace" but the quotes are not required. Atoms made exclusively of ASCII letters, numbers, underscores, and optionally ending with ! or ? do not require quotes
  lib/ory/api/read.ex:38:7
…
```

The code in question for the latter (and there are *hundreds* of these) is

```elixir
    optional_params = %{
      :"namespace" => :query,
      :"object" => :query,
      :"relation" => :query,
      :"subject_id" => :query,
      :"subject_set.namespace" => :query,
      :"subject_set.object" => :query,
      :"subject_set.relation" => :query,
      :"max-depth" => :query
    }
```

It should be

```elixir
    optional_params = %{
      :namespace => :query,
      :object => :query,
      :relation => :query,
      :subject_id => :query,
      :"subject_set.namespace" => :query,
      :"subject_set.object" => :query,
      :"subject_set.relation" => :query,
      :"max-depth" => :query
    }
```

The atom issue can be changed to the correct format by the use of `mix format` in the target directory, but that requires a `.formatter.exs` be created (which should be in _every_ Elixir project at this point):

```elixir
[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
```

I will be opening at least one issue in the generated repo for some issues that I have seen, but for what I have highlighted here, these are issues in the Elixir generator or its templates (I reviewed the templates before opening this issue).

I’m happy to provide a PR, but I haven’t seriously done Java since JDK 1.1.

##### Related issues/PRs

- #12484 
- #4011
- #10755 (I will have to investigate, but this can probably be resolved by making sure references to the self module are changed to `__MODULE__`)
- #8804 (Jason is generally the preferred JSON parser/encoder in Elixir these days in any case)
- #12268 (this should be using `Application.compile_env/2` instead of `Application.get_env/2`, or using a code fallback)

**Comment by wing328** [comment]
@halostatue thanks for reporting the issue. 

Is there any Elixir code linter/formatter that can automatically fix issues like this? General speaking, we recommend users to run code linter/formatter to automatically format the auto-generated code based on their need.

**Comment by halostatue** [comment]
`mix format` can, but _only_ if a `.formatter.exs` is included at the root (suggested example in the body of my bug report), so a new template and file would need to be written. I would generally agree with you that running a code linter/formatter is a good step, but it does require having an Elixir environment set up—and for companies that generate libraries, they may not have that entirely in place (although to *compile* and *release* those libraries to Hex.pm, they have to have an Elixir environment set up in any case). If it’s *possible* to distinguish between the cases where atoms require quoting and generate atoms correctly, that would solve most of the issues that I saw:

> Atoms must be composed of Unicode characters such as letters, numbers, underscore, and @. If the keyword has a character that does not belong to the category above, such as spaces, you can wrap it in quotes…

The other is something where the differences exist between Elixir versions, but `use Mix.Config` was deprecated for `import Config` with Elixir 1.13 and the `Config` module (with `import Config`) was introduced in Elixir 1.9 (released in June 2019).

The use of `Application.compile_env/2` instead of `Application.get_env/2` was introduced in 1.10 (released in January 2020).

**Comment by wing328** [comment]
Agreed that my suggested solution is not perfect for those who do not have a proper elixir environment setup. My suggestion is still to go ahead to add the .formatter.exs file as the mix linter/formatter can fix other issues as well (e.g. trailing spaces, etc).

> The other is something where the differences exist between Elixir versions, but use Mix.Config was deprecated for import Config with Elixir 1.13 and the Config module (with import Config) was introduced in Elixir 1.9 (released in June 2019).


As Elixir 1.9 was released a few years before, let's move on to support newer version of Elixir instead.

Would you have time to contribute a PR to add the auto-generated `.formatter.exs` ? I can show you some good starting points.

**Comment by halostatue** [comment]
Hi, @wing328. I’ve put in a fairly meaty PR, but I do not consider the changes there to be *complete*, although they are at the moment *sufficient*. The way that the Tesla client is defined should be updated, and there should probably be a shift from `Poison` to `Jason` and/or a configuration option to choose.

Most of these could be made with a configuration option and a default, but it will be a deeper change that should be reviewed separately (and I will likely change them *first* in generated example code and backport it to the templates).

**Comment by halostatue** [comment]
I’ll be creating one more PR in the next week or so that should allow this to be closed, as at that point generated code should be warning free for the default cases.
