### ISSUE TITLE
[BUG] [Python-experimental] Certain types in nested component schemas are interpreted as DynamicSchema

### ISSUE THREAD

**Issue by mikeknep** [OpenAPITools/openapi-generator#12736]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am unable to construct a python-experimental-generated object that includes both a nested component schema property and `allOf`. Certain types (integer, number, boolean) become impossible to construct, being interpreted as a `DynamicSchema` instead of the actual type.

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0

info:
  version: 1.0.0
  title: BugReproduction

paths: {}

components:
  schemas:
    Dog:
      type: object
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Animal"
      properties:
        species:
          enum: ["canine"]
        age:
          $ref: "#/components/schemas/Age"

    Age:
      type: object
      additionalProperties: false
      properties:
        unit:
          type: string
        value:
          type: integer

    Cat:
      type: object
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Animal"
      properties:
        species:
          enum: ["feline"]
        favorite_milk:
          type: string

    Animal:
      type: object
      properties:
        species:
          type: string
      discriminator:
        propertyName: species
        mapping:
          canine: "#/components/schemas/Dog"
          feline: "#/components/schemas/Cat"
```

##### Generation Details

I've generated the schema above with both the standard python generator and python-experimental for side-by-side comparisons:
```
# Using the "standard" python generator, for comparison
openapi-generator generate \
  -i openapi_specs/main.yml \
  -g python \
  --additional-properties generateSourceCodeOnly=true \
  --additional-properties packageName=pystandard

# Using the python-experimental generator
_JAVA_OPTIONS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED" \
  openapi-generator generate \
  -i openapi_specs/main.yml \
  -g python-experimental \
  --additional-properties generateSourceCodeOnly=true \
  --additional-properties packageName=pyexperimental
```
(Note: the `_JAVA_OPTIONS` are passed to avoid this error:)
```
: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @2c1a7075
```

##### Steps to reproduce

- Run the generator steps above with the schema above
- Attempt to create an object (comment in/out the different imports to compare standard and experimental)
```python
# from pystandard.model.age import Age
# from pystandard.model.dog import Dog
from pyexperimental.model.age import Age
from pyexperimental.model.dog import Dog

def test_dog():
    Dog(species="canine", age=Age(unit="years", value=2))
```
The standard Dog can be created just fine, but the experimental Dog cannot be constructed:

```
pyexperimental.exceptions.ApiTypeError: Invalid type. Required value type is one of [Decimal, FileIO, NoneType, bool, bytes, frozendict, str, tuple] and passed type was DynamicSchema at ['args[0]']['age']['value']
```
I've changed the type of `value` to a few different simple types—string works fine, but integer/number/boolean all fail.

##### Related issues/PRs

None to my knowledge

##### Suggest a fix

Per @spacether:
>Hmm this may be because Animal sees Age as an AnyTypeSchema but a Dog instance is a DynamicSchema instance but it should be let through because Age is a DictSchema.

For wider context of my real-world use case: I have an API endpoint with a polymorphic request body—it can accept `oneOf` several animals (to run with the reproduction example). I have several different animals (not just two), and while most have pretty distinct properties (as above—Dog and Cat are quite distinct from one another), a few of them happen to have the exact same set of fields (say... `name` and `number_of_legs`). I need to be able to disambiguate between two animals with identical properties, so I'm adding the `species` field as a discriminator. Each specific animal defines species as an enum-of-one field to ensure a client doesn't create something like `Giraffe(species="canine")`.

In my real-world example there are additional, common, sometimes-optional properties that all Animals define, which is why I'm using `allOf`. Maybe the `species` property and discriminator mapping is not actually necessary in this case (since its hard-coded on each concrete animal schema), and I should just perform server-side switching using that field myself? I had assumed providing the discriminator block would yield some benefit in generated code. (Still pretty new to this tool in general so I don't know for sure, but all the polymorphism examples in the docs talk about using it.)

**Comment by spacether** [comment]
This is an important use case. Thank you for reporting this bug.
I know how to fix it.
Any instantiated model is a DynamicSchema because it is a class that has been composited using multiple other classes.
This error is happening because the age values is kept as an Age instance, but age is an additonalProperty in Animal, so it expects the value to be a (dict/list/str/int/bool/None) and it is an instance of DynamicSchema instead.

The solution is to convert all ingested instances into their primitive types (dict/list/str/int/bool/None) and store the erlier completed validations from the DynamicSchema class into the ValidationMetada. Then those schema classes will not have to rerun validations that were already run in Age when a Dog instance is instantiated using an `age=Age(...)` instance

**Comment by spacether** [comment]
@mikeknep a short term work around for this is to use `Dog._from_openapi_data(dict(species="canine", age=dict(unit="years", value=2)))`

**Comment by spacether** [comment]
All fixed, please pull the latest master branch (commit d6b360d47f2039c5a917ca86017c57eb91497c16 or later) and regenerate your client using it.

**Comment by caniko** [comment]
@spacether I am still getting this I am on the latest stable, 6.2.0.
