### ISSUE TITLE
[BUG] component that refs another component doesn't work

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#12730]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

component that refs another component doesn't work
This came up when working on https://github.com/OpenAPITools/openapi-generator/pull/12619

Feature: jsonschema.$ref

##### openapi-generator version

6.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: openapi 3.0.3 sample spec
  description: sample spec for testing openapi functionality, built from json schema
    tests for draft6
  version: 0.0.1
paths: {}
components:
  schemas:
    PropertyNamedRefThatIsNotAReference:
      properties:
        $ref:
          type: string
    ComponentRefsAnotherComponent:
      $ref: '#/components/schemas/PropertyNamedRefThatIsNotAReference'
```

##### Generation Details

Generate with python-experimental

##### Steps to reproduce

See above

##### Related issues/PRs

N/A

##### Suggest a fix

An import should be generated
I think that this used to work

**Comment by mikeknep** [comment]
Hey there, I was just writing up an issue earlier that I think may be similar to this. If you don't mind, I'll add the details here instead of opening a separate issue, but if they actually are two distinct problems I can reopen separately!

```yaml
openapi: 3.0.0

info:
  version: 1.0.0
  title: BugReproduction

paths: {}

components:
  schemas:
    Dog:
      type: object
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Animal"
      properties:
        species:
          enum: ["canine"]
        age:
          $ref: "#/components/schemas/Age"

    Age:
      type: object
      additionalProperties: false
      properties:
        unit:
          type: string
        value:
          type: integer

    Cat:
      type: object
      additionalProperties: false
      allOf:
        - $ref: "#/components/schemas/Animal"
      properties:
        species:
          enum: ["feline"]
        favorite_milk:
          type: string

    Animal:
      type: object
      properties:
        species:
          type: string
      discriminator:
        propertyName: species
        mapping:
          canine: "#/components/schemas/Dog"
          feline: "#/components/schemas/Cat"
```

##### Generation Details

```
# Using the "standard" python generator, for comparison
openapi-generator generate \
  -i openapi_specs/main.yml \
  -g python \
  --additional-properties generateSourceCodeOnly=true \
  --additional-properties packageName=pystandard

# Using the python-experimental generator
_JAVA_OPTIONS="--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED" \
  openapi-generator generate \
  -i openapi_specs/main.yml \
  -g python-experimental \
  --additional-properties generateSourceCodeOnly=true \
  --additional-properties packageName=pyexperimental
```

(Note: the `_JAVA_OPTIONS` are necessary to avoid this error message:)
```
: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.HashMap$Node[] java.util.HashMap.table accessible: module java.base does not "opens java.util" to unnamed module @2c1a7075
```

##### Steps to reproduce

- Run the generator commands above
- Run these tests (comment in/out the different imports to compare standard and experimental)
```
# from pystandard.model.age import Age
# from pystandard.model.dog import Dog
from pyexperimental.model.age import Age
from pyexperimental.model.dog import Dog

def test_dog():
    Dog(species="canine", age=Age(unit="years", value=2))
```
The standard `Dog` can be created just fine, but the experimental `Dog` cannot be constructed:
```
pyexperimental.exceptions.ApiTypeError: Invalid type. Required value type is one of [Decimal, FileIO, NoneType, bool, bytes, frozendict, str, tuple] and passed type was DynamicSchema at ['args[0]']['age']['value']
```
It appears string values in the nested component work fine, but integer, number, and boolean all lead to this error.

**Comment by spacether** [comment]
@mikeknep can you make a separate issue for that.
The property that you mention is a codegenProperty whereas the one that I am mentioning is a codegenModel sothey work differently.

**Comment by spacether** [comment]
This bug is also tracked here: https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/126

**Comment by spacether** [comment]
This will work in [openapi-json-schema-generator](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator) v 2.0.0 because it was fixed in https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/125

**Comment by Genymobile1** [comment]
[********)

**Comment by spacether** [comment]
FYi if you want to use this it is working in the v2.0.0 release of [openapi-json-schema-generator](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator).
That is where further development is being done on the python generator.
[Here is the definition of the component schema RefPet](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/modules/openapi-json-schema-generator/src/test/resources/3_0/python/petstore_customized.yaml#L2068)
```
    RefPet:
      $ref: '#/components/schemas/Pet'
```
And [here is the generated class](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/openapi3/client/petstore/python/src/petstore_api/components/schema/ref_pet.py#L14)
```
from petstore_api.components.schema import pet
RefPet = pet.Pet
```

**Comment by spacether** [comment]
If you want this to work use it from the new location
