### ISSUE TITLE
[html] bug in default infoUrl

### ISSUE THREAD

**Issue by ndjensen** [OpenAPITools/openapi-generator#1276]
##### Description
The default URL in the html generator is incorrect.  The default address is `https//openapi-generator.tech`.  It is missing a colon.  https://github.com/OpenAPITools/openapi-generator/blob/v3.3.1/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/StaticHtmlGenerator.java#L72

##### openapi-generator version
3.3.1

##### OpenAPI declaration file content or url
[petstore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml)

##### Command line used for generation
`java -jar openapi-generator-cli.jar generate -i ~/test_openapi/petstore.yaml -g html -o ~/openapi-output/petstore`

##### Steps to reproduce
Run the html generator without replacing the infoUrl through configuration options.

##### Suggest a fix/enhancement
Add a colon to line 72 of StaticHtmlGenerator.  While in the area, should consider changing the default Apache license URL to be `https` instead of `http`.

**Comment by wing328** [comment]
@ndjensen thanks for reporting the issue. May I know if you've time to contribute a fix?
