### ISSUE TITLE
[REQ] Python clientlib should have type annotations

### ISSUE THREAD

**Issue by benbariteau** [OpenAPITools/openapi-generator#12770]
### Is your feature request related to a problem? Please describe.
Without type annotations, it's possible to misuse generated libraries in ways that can't easily be caught before code is being run in an environment where such mistakes are costly (e.g. in production).

## Describe the solution you'd like
The python ecosystem as a whole is moving towards type annotations being typical in libraries. They would be especially useful here as network boundaries are where types are the most uncommon and we already have all of that information encoded in OpenAPI specs if we're using this generator. 

In the ideal case the resolution of this would be that type annotations are included in all public function and method parameters and return types as well as object variables.

## Describe alternatives you've considered
There isn't really any alternative to this that gives the same benefits. There are type guards on the existing code, but that can't be guaranteed to be hit until the code is run, instead of through static analysis.

**Comment by spacether** [comment]
@benbariteau have you tried python-experimental? It has type hints

**Comment by spacether** [comment]
python-experimental has type hints so I am closing this issue.
Here are some examples.
[The tag model](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/model/tag.py#L71)
```
class Tag(
    DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech
    Do not edit the class manually.
    """
    id = Int64Schema
    name = StrSchema


    def __new__(
        cls,
        *args: typing.Union[dict, frozendict, ],
        id: typing.Union[id, Unset] = unset,
        name: typing.Union[name, Unset] = unset,
        _configuration: typing.Optional[Configuration] = None,
        **kwargs: typing.Type[Schema],
    ) -> 'Tag':
        return super().__new__(
            cls,
            *args,
            id=id,
            name=name,
            _configuration=_configuration,
            **kwargs,
        )
```

[And here is an endpoint](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/paths/fake_refs_arraymodel/post.py#L174)
```
class ArrayModel(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    def array_model(
        self: BaseApi,
        body: typing.Union[SchemaForRequestBodyApplicationJson, Unset] = unset,
        content_type: str = 'application/json',
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        timeout: typing.Optional[typing.Union[int, typing.Tuple]] = None,
        skip_deserialization: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization
    ]:
        return self._array_model(
            body=body,
            content_type=content_type,
            accept_content_types=accept_content_types,
            stream=stream,
            timeout=timeout,
            skip_deserialization=skip_deserialization
        )
```
