### ISSUE TITLE
[BUG] [JAVA] [webclient] Model with readonly, nullable properties generates uncompilable code

### ISSUE THREAD

**Issue by kzander91** [OpenAPITools/openapi-generator#12790]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Model properties with `nullable: true` _and_ `readOnly: true` cause invalid code to be generated.

The `nullable: true` causes the type to be wrapped in `JsonNullable<T>`, and the `readOnly: true` causes a `@JsonCreator` constructor to be generated with argument type `T`, attempting to set the arg to the class field.

The example spec below results in the following Java class:
```java
// imports, annotations
public class TestObject {
  public static final String JSON_PROPERTY_MY_PROP = "myProp";
  private JsonNullable<String> myProp = JsonNullable.<String>undefined();

  public TestObject() { 
  }

  @JsonCreator
  public TestObject(
    @JsonProperty(JSON_PROPERTY_MY_PROP) String myProp
  ) {
    this();
    this.myProp = myProp; // <--- compiler error here, String cannot by assigned to JsonNullable<String>
  }

// getters, setters
}
```

##### openapi-generator version

5.3.1 and above.
I tracked it down to [this commit](https://github.com/OpenAPITools/openapi-generator/commit/e7c3bdacc2c5f3ebbdda80dee8c27fb55d65949a#diff-6fd4ec14f4f17c5ab1d6ce37b0bd8972457d43cc9ca547d74f192755a8d5207aR93), generating the same spec with 5.3.0 does not generate a `@JsonCreator` constructor and thus does not cause compiler errors.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
    title: Title
    version: "1"
paths:
    /test:
        get:
            responses:
                200:
                    description: Success
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TestObject'
components:
    schemas:
        TestObject:
            type: object
            properties:
                myProp:
                    type: string
                    nullable: true
                    readOnly: true
```

##### Generation Details

`java -jar openapi-generator-cli.jar generate -g java --library webclient -i spec.yaml -o out`

##### Steps to reproduce

1. Model with attributes being both `readOnly` and `nullable`.
2. Generate with generator `java` and library `webclient`.
3. Model property is of type `JsonNullable<String>`, constructor arg is of type `String`. Assignment takes place without wrapping into `JsonNullable`.

##### Related issues/PRs

#10086
#10113

**Comment by wtrocki** [comment]
@kzander91 We missing desired state. I think fix can be done in constructor (creating new 
JSONNullable object instead)

**Comment by kzander91** [comment]
@wtrocki That's because I'm not quite sure what the best solution is here, the "desired state" is that this works even if the generated attribute type is `JsonNullable`.
I guess the fix would be to wrap the constructor argument like so?
```java
this.myProp = JsonNullable.of(myProp);
```

**Comment by wtrocki** [comment]
Yes. JsonNullable is actually quite clever concept explained here:
https://github.com/OpenAPITools/jackson-databind-nullable

Problem we are facing here is that one flag in openapi changes state and second flag needs to be aware of that state (We cannot push string to nullable object anymore). 
I think fix for that can use one flag to guess state like this:
```
if(nullable == true){
  this.myProp = JsonNullable.of(myProp);
} else{
    this.myProp = myProp;
}
```

It should be trivial thing to contribute

**Comment by borsch** [comment]
HI
I'll try to fix this over weekend
