### ISSUE TITLE
[REQ] Typescript-axios ESM support

### ISSUE THREAD

**Issue by Snazzie** [OpenAPITools/openapi-generator#12828]
### Is your feature request related to a problem? Please describe.
Similar to https://github.com/OpenAPITools/openapi-generator/issues/8881 

## Describe the solution you'd like

Current output does not work with Vite builds. According to one of the Vite members, this should be fixed with ESM support.
https://github.com/vitejs/vite/issues/9017#issuecomment-1179696141 

Would be great if this was done so we can use it in Vite.

**Comment by miniengineer** [comment]
I am going to open a PR to add this to the `typescript-axios` client
We have similar issues =_=
