### ISSUE TITLE
[BUG] skipOperationExample is not copied to workflow settings from build.gradle

### ISSUE THREAD

**Issue by roedde** [OpenAPITools/openapi-generator#12844]
Using version 5.3.1 

In the class org.openapitools.codegen.config.WorkflowSettings the private constructor is called by Builder.build.

The Problem is in this Constructor the property skipOperationExample is not copied to the workflowsettings. 

adding the following line in the Constructor should solve the problem 

`this.skipOperationExample = builder.skipOperationExample;`

**Comment by wing328** [comment]
thanks for reporting the issue

if it's still an issue with the latest stable release v6.0.1, please file a PR and we'll review accordingly.
