### ISSUE TITLE
[BUG] [HTML2] Syntax Error in HTML-File: ", or ) expected"

### ISSUE THREAD

**Issue by kas1337** [OpenAPITools/openapi-generator#12842]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The html2-Generator generates a HTML-File with syntax error. Hence, the responses in the schema cannot be displayed.

##### openapi-generator version

v6.0.1 

v6.0.0 works fine

##### OpenAPI declaration file content or url

The entire json file and the resulting index.html file can be found here: https://gist.github.com/kas1337/c1f1a74ccbe485fffb168fd482e8089d

##### Generation Details & Steps to reproduce

I've tested with the latest master branch as described here https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator using the following command (Linux)

```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g html2 -i openapi.json
```

##### Actual output

See the lines from 1297. The are paranthesis missing to close the forEach-Loop. This error can be found multiple times.

```
Object.keys(schema.properties).forEach( (item) => {
  if (schema.properties[item].$ref != null) {
    schema.properties[item] = defsParser.$refs.get(schema.properties[item].$ref);
  }
```

##### Expected output

```
Object.keys(schema.properties).forEach( (item) => {
  if (schema.properties[item].$ref != null) {
    schema.properties[item] = defsParser.$refs.get(schema.properties[item].$ref);
  }
});
```

##### Related issues/PRs

-

##### Suggest a fix

- This PR is causing the issue https://github.com/OpenAPITools/openapi-generator/pull/12428
- You can see in the changed file https://github.com/OpenAPITools/openapi-generator/pull/12428/files the missing paranthesis as described above.
- This sample file https://github.com/OpenAPITools/openapi-generator/blob/master/samples/documentation/html2/index.html should also be fixed

Thank you!

**Comment by kas1337** [comment]
@wing328 Hey 👋 I tried to push a branch with the suggested fix so that I can open a PR. However, I get a 403-Error when trying to push the branch to the repository. Do I need some sort of access if i want to push to the repo? The error is 

````
$ git push -u origin fix_issue12842
remote: Permission to openapitools/openapi-generator.git denied to kas1337.
fatal: unable to access 'https://github.com/openapitools/openapi-generator.git/': The requested URL returned error: 403
````
The authentication seems to work right.

**Comment by kaihenkel** [comment]
#13272 addresses the same issue and was fixed recently
