### ISSUE TITLE
[BUG] Java Generator for Enum produces invalid fromValue method

### ISSUE THREAD

**Issue by brunoborges** [OpenAPITools/openapi-generator#12874]
The abstract Java codegen is generating a `fromValue` method that does not correctly compute the values of a Java Enum.

See the following spec:
```yaml
    TodoState:
      type: string
      enum:
        - todo
        - inprogress
        - done
```

The generator produces the following Enum:

```java
public enum TodoState {
  TODO("todo"), INPROGRESS("inprogress"), DONE("done");

  private String value;
  TodoState(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static TodoState fromValue(String value) {
    for (TodoState b : TodoState.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
```

If the URL param `{state}` contains value ` done` , the code fails to find the appropriate Enum type `DONE` due to a mismatch in the String case.

The method `fromValue` should check if there is a custom value associated to the enum, and compare with that instead if to respect the case.

**Error log**
```
2022-07-14 21:04:46.657  WARN 10016 --- [nio-8080-exec-9] .w.s.m.s.DefaultHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'com.example.openapi.model.TodoState'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@io.swagger.v3.oas.annotations.Parameter @org.springframework.web.bind.annotation.PathVariable com.example.openapi.model.TodoState] for value 'done'; nested exception is java.lang.IllegalArgumentException: No enum constant com.example.openapi.model.TodoState.done]
```

**Comment by wtrocki** [comment]
Hi @brunoborges Can you tell me what client generator this refers to? I will be happy to patch that but need to know exact java client that you have been using.

I do see this behaviour with RestEasy:

https://github.com/redhat-developer/app-services-sdk-java/blob/main/packages/kafka-instance-sdk/src/main/java/com/openshift/cloud/api/kas/auth/models/OffsetType.java

Also worth to mention that there is dedicated generator for quarkus ;)
https://github.com/quarkiverse/quarkus-openapi-generator

**Comment by wtrocki** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/12881

**Comment by brunoborges** [comment]
In my case, I am using the Spring generator. But the Rnun code generation is defined in the Abstract class inherited by the Spring one.
