### ISSUE TITLE
[BUG][typescript-fetch] Compile error when using "noImplicitOverride" in tsconfig

### ISSUE THREAD

**Issue by douniii** [OpenAPITools/openapi-generator#12948]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When compiling the generated code with a tsconfig where  `"noImplicitOverride": true` (see [here](https://www.typescriptlang.org/tsconfig#noImplicitOverride)) is set, the compiler complains about the not marked overrides:
`This member must have an 'override' modifier because it overrides a member in the base class 'Error'.`

##### openapi-generator version

6.0.1 (and master)
by using "@openapitools/openapi-generator-cli": "2.5.1"

##### OpenAPI declaration file content or url
N/A

##### Generation Details
```bash
openapi-generator-cli generate -i ./openapi.json -g typescript-fetch -o src/generated-sources/openapi --additional-properties=supportsES6=true,npmVersion=8.6.0,typescriptThreePlus=true
```

##### Steps to reproduce

Checkout https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/petstore/typescript-fetch/builds/es6-target
and add to the tsconfig  `"noImplicitOverride": true,`.
```json
{
  "compilerOptions": {
    "noImplicitOverride": true,
    "declaration": true,
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "dist",
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "exclude": [
    "dist",
    "node_modules"
  ]
}
```
and build it.
##### Suggest a fix
Place "override" before overridding props/methods
here
https://github.com/OpenAPITools/openapi-generator/blob/6d44f97d6cc4bcd11752ca6556075232dc4e5fdb/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L222
https://github.com/OpenAPITools/openapi-generator/blob/6d44f97d6cc4bcd11752ca6556075232dc4e5fdb/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L229
https://github.com/OpenAPITools/openapi-generator/blob/6d44f97d6cc4bcd11752ca6556075232dc4e5fdb/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L230
https://github.com/OpenAPITools/openapi-generator/blob/6d44f97d6cc4bcd11752ca6556075232dc4e5fdb/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L236

**Comment by cre8** [comment]
I am still getting the error with version `6.1.0`:
```
export class RequiredError extends Error {
    name: "RequiredError" = "RequiredError";
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}
```
here the name attribute gets overwritten ...

**Comment by macjohnny** [comment]
@cre8 do you want to fix this?

**Comment by cre8** [comment]
@macjohnny I can spend some time to dig deeper since you already made a merge that added the `override` part.

I am using the `typescript-axios` one to generate it. Have you checked this when updating the code?
