### ISSUE TITLE
[BUG][JAXRS-CXF-Client]Missing import of java.util.Objects in model classes

### ISSUE THREAD

**Issue by KiriRea** [OpenAPITools/openapi-generator#12944]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
I've generated jaxrs-cxf-client by OpenAPI Generator CLI (6.0.1).
After generate, I found all model classes have import error of "java.util.Objects;".
I think all model classess should be added import of "java.util.Objects;" during generating jaxrs-cxf-client.

![ObjectsError](https://user-images.githubusercontent.com/106964165/179898755-0a8470ac-a71a-4721-9643-98c658c8f788.png)

##### openapi-generator version
6.0.1

##### OpenAPI declaration file content or url
Any OpenAPI declaration file like below.
https://editor.swagger.io/
　File -> Convert and save as JSON

##### Generation Details
1. Access above link(https://editor.swagger.io/), and click "File" -> "Convert and save as JSON" (download swagger.json).
2. Generate jaxrs-cxf-client by openapi-generator-cli.jar.
```bash
java -jar openapi-generator-cli-6.0.1.jar generate -g jaxrs-cxf-client -o PetStoreSample -i swagger.json
```

##### Steps to reproduce
* After generate jaxrs-cxf-clint, check model classes.
* equals method and hashCode method have import error about java.util.Objects.

```java
public class Category  {
    ...
    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }
      Category category = (Category) o;
      return Objects.equals(id, category.id) &&
          Objects.equals(name, category.name);
    }

    @Override
    public int hashCode() {
      return Objects.hash(id, name);
    }
```

##### Related issues/PRs
None.

##### Suggest a fix
Automatically add "import java.util.Objects;" to each model class.

**Comment by MRAfni** [comment]
Fixed in pull #12766
