### ISSUE TITLE
[BUG][Go] anyOf with objects and arrays generates uncompilable model

### ISSUE THREAD

**Issue by MarcelGosselin** [OpenAPITools/openapi-generator#12955]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a schema has `anyOf` whose entries are either a plain _object_ or an _array_, the generated code contains invalid field names in the model.

Actual output:
```go
type Any struct {
	[]Any *[]Any
	map[string]interface{} *map[string]interface{}
}
```
Expected output (not necessarily an exact match):
```go
type Any struct {
	arrayOfAny *[]Any
	plainObject *map[string]interface{}
}
```

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

[OpenAPI with objects and arrays](https://gist.github.com/MarcelGosselin/3684f8ece2951b0908db065fbf161736)

##### Generation Details

Running the following without config file, from a folder containing only the file `openapi.json`
```sh
docker run --rm -it -v $(pwd):/src openapitools/openapi-generator-cli:v6.0.1 generate -i /src/openapi.json -g go -o /src
```

##### Steps to reproduce

1. Generate using above command line
2. Look at file `model_any.go`, it contains invalid property names `[]Any` and `map[string]interface{}`
    ```go
    type Any struct {
	    []Any *[]Any
	    bool *bool
	    float32 *float32
	    int32 *int32
	    map[string]interface{} *map[string]interface{}
	    string *string
    }
    ```

##### Related issues/PRs

1. [Similar one with oneOf](https://github.com/OpenAPITools/openapi-generator/issues/8769)
2. [More far fetched one with names starting with numbers](https://github.com/OpenAPITools/openapi-generator/issues/11320)

##### Suggest a fix

The file `modules/openapi-generator/src/main/resources/go/model_anyof.mustache` uses `#anyOf` which is a `Set<string>` in `CodegenModel.java`. Unfortunately in that case the string is a datatype that cannot be used as a field name. I can see 3 ways to fix this (my favorite is the third one):
1. (I don't know if it is possible in Mustache) In the mustache template, instead of
    ```
    {{#anyOf}}
    {{{.}}} *{{{.}}}
    {{/anyOf}}
    ``` 
    you could have something to normalize the identifier
    ```
    {{#anyOf}}
    {{{ toIdentifier(.) }}} *{{{.}}}
    {{/anyOf}}
    ``` 
3. Change the data type of the Set of CodegenModel.anyOf to be a class which contains 2 properties: DataType, IdentifierName. Then modify usages of anyOf in `model_anyof.mustache` and any other places to use the right property.
4. Use type definitions in Go anytime you encounter an array or object, something like the following.
    ```go
    type openApiObject map[string]interface{}
    type arrayOfAny []Any
    ```
     You could then use that typedef in the `Set<string>` which would make the generation give this instead
    ```go
    type Any struct {
	    arrayOfAny *arrayOfAny
	    bool *bool
	    float32 *float32
	    int32 *int32
	    openApiObject *openApiObject
	    string *string
    }
    ```

**Comment by ammmze** [comment]
I'm also running into this. It looks like there has been some modifications to the `model_oneof.mustache` to accommodate this. It looks like there was a [helper/lambda](https://github.com/OpenAPITools/openapi-generator/blob/e2b9f39b1905ec20db3aa67a03fed8eeb4cdbe0c/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/GoClientCodegen.java#L258) added named `lambda.type-to-name`, which will replace `[]` with `array_of_` and then after that it replaces `[` with `map_of_` and finally replaces `]` with  an empty string.

So in your example, instead of the following:
```go
type Any struct {
	[]Any *[]Any
	map[string]interface{} *map[string]interface{}
}
```

It would produce:
```go
type Any struct {
	array_of_Any *[]Any
	map_of_interface{} *map[string]interface{}
}
```

You can usage of that lambda in the `model_oneof.mustache` [here](https://github.com/OpenAPITools/openapi-generator/blob/7ea5d158f22f316e7f5f3a76795694999567cd1c/modules/openapi-generator/src/main/resources/go/model_oneof.mustache#L4).

However, there are some issues with that still:
1. Since the first letter is lower case, it not a public property, where all the other properties in the structs are all public.
2. It uses snake case instead of camel case.

**Comment by ammmze** [comment]
I still need to go through the contributor guidelines and see if we can get any test coverage or whatever this project looks for, but I think something like [this](https://github.com/OpenAPITools/openapi-generator/compare/master...ammmze:openapi-generator:golang-anyof-complex?expand=1) should do what we need here.

**Comment by AniketK-Crest** [comment]
Facing the same issue. Any updates??

**Comment by ctreatma** [comment]
We're also running into this issue.  I replicated the linked PR #13472 locally and confirmed that it fixes the generated Go code.  It looks like that PR has passed all automated checks.  What can we do to move the review process forward?

**Comment by wing328** [comment]
Thanks for the PR. I think a better way to fix this it to use `{{composedSchemas}}` tags, e.g. https://github.com/OpenAPITools/openapi-generator/blob/9f1fa0e44012a11f85d8360cfe5f634530e49e57/modules/openapi-generator/src/main/resources/r/modelOneOf.mustache#L100-L126

Do you mind using it in your fix?
