### ISSUE TITLE
[BUG] dart-dio anyOf for object with different refs generates incorrect code

### ISSUE THREAD

**Issue by FireMasterK** [OpenAPITools/openapi-generator#12963]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output? - unsure
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

5.3.1

##### OpenAPI declaration file content or URL

https://raw.githubusercontent.com/TeamPiped/OpenAPI/main/swagger.yaml

Problematic lines:
```yaml
components:
  schemas:
    SearchItem:
      type: object
      oneOf:
        - $ref: "#/components/schemas/StreamItem"
        - $ref: "#/components/schemas/ChannelItem"
        - $ref: "#/components/schemas/PlaylistItem"
    SearchPage:
      type: object
      properties:
        corrected:
          type: boolean
          description: Whether the search query was corrected.
        items:
          type: array
          items:
            $ref: "#/components/schemas/SearchItem"
```

##### Generation Details

```
openapi-generator-cli generate -i swagger.yaml -c dart.yaml -g dart-dio
```

dart.yaml:
```yaml
pubLibrary: piped
pubName: piped_api
pubDescription: Automatically generated OpenAPI bindings for Piped.
```

##### Steps to reproduce

- Run the generation command above
- duration would be a necessary field, although it need not be
- See: https://github.com/TeamPiped/piped_dart/blob/938917a83572fd65826d6b0fbafe013777c905fe/lib/src/model/search_item.dart#L35

##### Related issues/PRs

N/A

##### Suggest a fix

I would keep the field optional since not all schemas have it as a necessary field, or alternatively - better deserialize them into different classes based on the properties they have.

**Comment by AllenKaplan** [comment]
I believe this is related to https://github.com/OpenAPITools/openapi-generator/pull/12295

**Comment by ahmednfwela** [comment]
The PR to solve this has been merged, @FireMasterK can you still reproduce this on the master branch ?

**Comment by kuhnroyal** [comment]
@wing328 This can be closed.
