### ISSUE TITLE
[REQ] Add Cookie SecurityScheme For Kotlin Code Generator

### ISSUE THREAD

**Issue by adam-sherpa6** [OpenAPITools/openapi-generator#12976]
### Is your feature request related to a problem? Please describe.
For the project I'm on we are using your Kotlin code generator. In our api_endpoints.yaml config we are trying to add this under components:

```
securitySchemes:
  cookieAuth:
        type: apiKey
        in: cookie
        name: token
```

However, the project fails to build due to malformed Kotlin code in ApiClient.kt, due to an extra curly bracket getting generated:

```
protected fun <T> updateAuthParams(requestConfig: RequestConfig<T>) {
            if (apiKey["token"] != null) {
                if (apiKeyPrefix["token"] != null) {
                } else {
                }
            }
        }
    }
```

For context, we have this same yaml configuration for another project, except it uses the java generator. No issue is present on that project. If I set 'in' to anything other than 'cookie', the Kotlin code successfully generates.

## Describe the solution you'd like
When reading the differences between the kotlin and java code generators on your documentation, I noticed that for
[java](https://openapi-generator.tech/docs/generators/java/#parameter-feature) the "Cookie" box is checked, but it's not checked for [kotlin](https://openapi-generator.tech/docs/generators/kotlin/#parameter-feature) 
Could we get this added for the Kotlin generator too?

**Comment by wing328** [comment]
>However, the project fails to build due to malformed Kotlin code in ApiClient.kt, due to an extra curly bracket getting generated:

can you please file a PR with the suggested fix? let us know if you need any help with the PR.

**Comment by Ranbato** [comment]
I hit this also using https://github.com/eddyhub/unifi-controller-client/blob/fcd9f1a2393b4aa1585b3bee827e15880142061e/api/src/main/resources/openapi.yaml with the following parameters (although I also tried others and they all failed)
``` generatorName.set("kotlin")
    library.set("jvm-okhttp4")
    inputSpec.set(sourceYaml)
    outputDir.set("${project.rootDir}/src/generated")

    apiPackage.set("com.asdf.generated.api")
    packageName.set("com.asdf.generated")
    modelPackage.set("com.asdf.generated.model")

    generateModelDocumentation.set(true)
    generateApiDocumentation.set(true)
    generateModelTests.set(true)
    generateApiTests.set(true)

    // https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/spring.md
    configOptions.set(
        mapOf(
            "dateLibrary" to "java8",
            "serializableModel" to "true",
            "serializationLibrary" to "jackson",
            "useCoroutines" to "true",
            "swaggerAnnotations" to "false",
            "bigDecimalAsString" to "true",
            "hideGenerationTimestamp" to "true",
            "interfaceOnly" to "true",
            "useTags" to "true",
            "performBeanValidation" to "true",
            // a bug in jackson template means array works better than list
            "collectionType" to "array",
            "skipOverwrite" to "false", // XXX Warning!  TRUE means you have to do a clean if you want to regenerate!
            "enumPropertyNaming" to "UPPERCASE"
        )
    )```

**Comment by Ranbato** [comment]
Here is the equivalent code in a Java client
``` 
 private void updateParamsForAuth(String[] authNames, List<Pair> queryParams, Map<String, String> headerParams) {
    for (String authName : authNames) {
      Authentication auth = authentications.get(authName);
      if (auth == null) throw new RuntimeException("Authentication undefined: " + authName);
        auth.applyToParams(queryParams, headerParams);
    }
  }
```
which is called in `createRequest` as ` updateParamsForAuth(authNames, queryParams, headerParams);
`

I don't see apiKey or apiKeyPrefix getting set anywhere in the Kotlin code though.

**Comment by greenbourne277** [comment]
I think this commit should fix the issue https://github.com/OpenAPITools/openapi-generator/pull/17117

**Comment by wing328** [comment]
thanks for the PR from @greenbourne277 

please give it a try with the latest master

**Comment by greenbourne277** [comment]
@wing328 I test it as soon as v7.2.0 is released.

**Comment by greenbourne277** [comment]
@wing328 I tested it successfully with the current master :)
