### ISSUE TITLE
[BUG] Wrong generated import path for python-experimental generator

### ISSUE THREAD

**Issue by MRuecklCC** [OpenAPITools/openapi-generator#12986]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Generating code for [this spec](https://github.com/MRuecklCC/edu-sharing-client-python/blob/main/edu-sharing-api.json) with the `python-experimental` generator results in import errors from the generated code.

Actual output:
![image](https://user-images.githubusercontent.com/104451100/180464144-e34c5f32-02df-4de3-96ab-70775ac7265a.png)

Expected Output:
`from edu_sharing_client.api.admin_v1_endpoints.add_application import ...`

##### openapi-generator version
6.1.0-SNAPSHOT

##### OpenAPI declaration file content or url
https://github.com/MRuecklCC/edu-sharing-client-python/blob/main/edu-sharing-api.json

##### Generation Details
Tested with both the npm package, and latest docker image

**Comment by MRuecklCC** [comment]
Unfortunately [the templates](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/python-experimental) are beyond my comprehension (for now).

**Comment by spacether** [comment]
When investigating this, I filed this issue: https://github.com/MRuecklCC/edu-sharing-client-python/issues/1

**Comment by spacether** [comment]
I fixed the issue in this branch with your spec: https://github.com/OpenAPITools/openapi-generator/pull/13053
And I will merge in the fix in this PR: https://github.com/OpenAPITools/openapi-generator/pull/13054
