### ISSUE TITLE
[BUG][MAVEN] Import Mappings not working with Maven

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#13059]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

Code generation is not working after upgrade to version 6.0.1 from 5.3.0, because the import mappings are ignored

##### Description

Generation type is just Object instead of the real object imported object

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

Try this two options
```
        <importMappings>
              Bar=my.Bar
         </importMappings>

```

```
        <importMappings>
              <importMapping>Bar=my.Bar</importMapping>
         </importMappings>

```

```
  /foo/{bar}:
    parameters:
      - name: bar
        schema:
            $ref: '#/components/schemas/Bar'
        in: path
        required: true
    get:
      operationId: getBar
```

##### Generation Details

Before:

```
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/foo/{bar}",
        produces = "application/json"
    )
    ResponseEntity<BarDto> getBar(
         @PathVariable("bar") my.Bar bar
    );
```

After
```
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/foo/{bar}",
        produces = "application/json"
    )
    ResponseEntity<BarDto> getBar(
         @PathVariable("bar") Object bar
    );

```

**Comment by MelleD** [comment]
@cachescrubber 
@welshm 
@borsch

Does anyone of you have an idea where I should look?
The import mappings are set correctly in the config + generator and are read in.
But I can't find where the resolving should take place.
Anyone have an idea where I can look?

**Comment by borsch** [comment]
Hi @MelleD 

usually I do following

pom.xml contains
```xml
<importMappings>
  <importMapping>Bar=my.Bar</importMapping>
</importMappings>
```

and I reference to those objects via `type`

```yaml
  /foo/{bar}:
    get:
      operationId: getBar
      responses:
        200:
          description: desc
          content:
            application/json:
              schema:
                type: Bar
```

**Note:** I've never used/tested this with parameters, only with request/response bodies, but I believe this should work for parameters as well

**Comment by MelleD** [comment]
IMHO there is something broken with the schema-mappings

https://github.com/OpenAPITools/openapi-generator/issues/12885
https://github.com/OpenAPITools/openapi-generator/pull/12600

@wing328 maybe you could answer what i have to change?

**Comment by MelleD** [comment]
@borsch thanks a lot with type it works fine :)
