### ISSUE TITLE
Upgrade the erlang-server dependency from cowboy1.x to cowboy2.x

### ISSUE THREAD

**Issue by feihongmeilian** [OpenAPITools/openapi-generator#1305]
Now we are upgrading the erlang-server code generated by openapi-generator from the dependency on cowboy1.x to cowboy2.x.

Simple case has been verified, but I look forward to more in line with the way cowboy.rest advocates, so I need some time to understand the mode of cowboy.rest .  Of course,I also need to completed the ticket from my company.

So it is estimated that the first PR will be 2018.11.10.

BR/feihongmeilian

**Comment by wing328** [comment]
@feihongmeilian thank you. Look forward to your contributions.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/1364
