### ISSUE TITLE
[BUG] php-symfony model templates using wrong variable for validation annotation (minimum where should be maximum)

### ISSUE THREAD

**Issue by plotbox-io** [OpenAPITools/openapi-generator#13060]
##### Description

Problem found in file: `modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache`. 

```
{{#minimum}}
    {{#exclusiveMinimum}}
     * @Assert\GreaterThan({{minimum}})
    {{/exclusiveMinimum}}
    {{^exclusiveMinimum}}
     * @Assert\GreaterThanOrEqual({{minimum}})
    {{/exclusiveMinimum}}
    {{/minimum}}
    {{#maximum}}
    {{#exclusiveMaximum}}
     * @Assert\LessThan({{minimum}})
    {{/exclusiveMaximum}}
    {{^exclusiveMaximum}}
     * @Assert\LessThanOrEqual({{minimum}})
    {{/exclusiveMaximum}}
    {{/maximum}}
```
Looks like a copy paste error. The two lower instances of `minimum` here should instead be `maximum`. This causes validation to fail in cases where it should not according to the openapi spec.

##### Suggest a fix

Submitting PR to fix the template

**Comment by loicconan** [comment]
@wing328 this issue can be close. Fixed by https://github.com/OpenAPITools/openapi-generator/commit/4fa427c65350f6fc6deaeb1373b739596db5f455
