### ISSUE TITLE
Add support for const

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#13081]
Is this needed?
We could convert const to an enum of length one.

**Comment by NicolasCARPi** [comment]
Hello,

Yes it is needed!

**Comment by hefekranz** [comment]
yes, please!

**Comment by prashant-pant** [comment]
As this issue is mapped to "OpenaApi v3.1.0" project, Can someone point me to the section in [OpenAPI spec 3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md) where it talks about "const"? I don't see any mention of this in the spec. I would be happy to contribute in the implementation if it is in the spec.

**Comment by artificial-paul** [comment]
OpenAPI spec 3.1.0 > Specification > Data Types reads "Data types in the OAS are based on the types supported by the [JSON Schema Specification Draft 2020-12](https://tools.ietf.org/html/draft-bhutton-json-schema-00#section-4.2.1). Note that integer as a type is also supported and is defined as a JSON number without a fraction or exponent part. Models are defined using the [Schema Object](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schemaObject), which is a superset of JSON Schema Specification Draft 2020-12."

The JSON Schema Specification Draft 2020-12 includes this section on `const`: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-00#section-6.1.3

**Comment by artificial-paul** [comment]
(FWIW, this seems to be working when we try to generate from a spec that includes consts)

**Comment by spacether** [comment]
I am no longer a contributor to this repo. Please open a new issue if you plan on adding this feature.
