### ISSUE TITLE
Add support for jsonSchemaDialect

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#13102]

**Comment by thiagofelix** [comment]
Out of curiosity, is this related to [OpenAPIDeserializer.getSchema](https://github.com/swagger-api/swagger-parser/blob/master/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L2658-L2660) returning a `io.swagger.v3.oas.models.media.JsonSchema` instance when parsing a `3.1.*` OpenAPI document?

I believe this causes a issue with [OpenAPINormalizer.isNullTypeSchema](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/OpenAPINormalizer.java#L763) which fails to recognize the `.types` (as array) from the schema. It only checks for the `.type`(singular case).

**Comment by spacether** [comment]
I am no longer a contributor to this repo. Please open a new issue if you plan on adding this feature.
