### ISSUE TITLE
[REQ] support matrix parameters and other parameter styles in typescript-angular

### ISSUE THREAD

**Issue by HonoluluHenk** [OpenAPITools/openapi-generator#13131]
### Is your feature request related to a problem? Please describe.

I need to access a server that is making heavy use of matrix parameters (i.e.: "in": "path", "style": "matrix").
At least the "typescript-angular" generator does not support any other parameter-styles than simple.

The way parameter encoding currently is implemented, modifying the mustache-templates does not work:
AbstractTypeScriptClientCodegen.java generates some hardcoded Typescript code that is broken for other styles than "simple".

Other typescript-* generators are probably "broken" in the same way since they make use of the same Java abstract generator class, see above.

## Describe the solution you'd like

I'd like to have either
a) have correct code generated for all supported parameter styles (at least "style": "matrix")  or
b) have code generated in a way that allows for customization via mustache-templates.

## Describe alternatives you've considered

I tried to customize api.service.mustache but the relevant/wrong code is hardcoded in AbstractTypeScriptClientCodegen.java.

## Additional context

n/a/

**Comment by HonoluluHenk** [comment]
Since supporting all possible combinations of parameter styles is tedious and may never be implemented due to complexity => wasted time at all, I'm working on a prototype for solution "b) have code generated in a way that allows for customization via mustache-templates."

**Comment by HonoluluHenk** [comment]
If anyone lands here by googling: the final fix allows for customization via the `Configuration` object (instead of mustache template).
See the README.md generated by openapi-generator for more details.

**Comment by calebpitan** [comment]
README.md is not generated for typescript-axios
