### ISSUE TITLE
[REQ] Remove GsonFire Dependency

### ISSUE THREAD

**Issue by ChaosMarc** [OpenAPITools/openapi-generator#13169]
### Is your feature request related to a problem? Please describe.

GsonFire has not received commits for nearly two years and has problems running in OSGi contexts in combination with the latest Gson versions as since 2.8.6 the Gson internal packages that GsonFire uses aren't exposed any more. There are workarounds to this problem but none of them are very appealing. See https://github.com/julman99/gson-fire/issues/52 for more information

## Describe the solution you'd like

As far as I can tell the only feature of GsonFire that's used in this project is the GsonFireBuilder in [JSON.mustache](https://github.com/OpenAPITools/openapi-generator/search?l=Mustache&q=GsonFireBuilder). If this could be replaced by a plain GsonBuilder the dependency to GsonFire could be removed alltogether.

## Describe alternatives you've considered

I don't know if there is an unoffical successor for GsonFire but using it would be another solution

## Additional context

https://github.com/julman99/gson-fire/issues/52

**Comment by wing328** [comment]
> If this could be replaced by a plain GsonBuilder the dependency to GsonFire could be removed alltogether.

can you please file a PR with the suggested change? we'll review accordingly.

**Comment by ChaosMarc** [comment]
Sorry this is beyond me. I've tried to extract only the relevant parts of gson-fire and implement them in this project but realized that it's a huge rabit hole to go down into as they use custom classes for **everything**. 

Maybe there is a smarter solution than to completely remove the depenency and only use it when it's really nessessary. maybe a little context will help: I'm coming from a project that uses the gradle plugin org.openapi.generator with the following configuration with various spec.json files:

```
plugins {
    id "org.openapi.generator" version "4.3.1"
}

task generateClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "java"
    inputSpec = "$projectDir/src/main/resources/spec.json"
    outputDir = "$buildDir/generated/openapi"
    invokerPackage = "com.package.name.service"
    apiPackage = "com.package.name.service.api"
    modelPackage = "com.package.name.service.model"
    generateModelDocumentation = false
    generateApiDocumentation = false
    generateModelTests = false
    configOptions = [
            dateLibrary: "java8"
    ]
}

compileJava.dependsOn tasks.generateClient
sourceSets.main.java.srcDir "${buildDir}/generated/openapi/src/main/java"
```

For all generated JSON.java files the only reference to gson-fire looks like this:

```
public static GsonBuilder createGson() {
    GsonFireBuilder fireBuilder = new GsonFireBuilder();
    GsonBuilder builder = fireBuilder.createGsonBuilder();
    return builder;
}
```

My hope was just replace this call with 
```
public static GsonBuilder createGson() {
    return new GsonBuilder();
}
```

As in my case no calls to `fireBuilder.registerTypeSelector()` (like in your examples) were made the only executed code from `fireBuilder.createGsonBuilder()` is 
```
builder.registerTypeAdapterFactory(new SimpleIterableTypeAdapterFactory());
builder.registerTypeAdapterFactory(new WrapTypeAdapterFactory(wrappedClasses)); // `wrappedClasses` being `null`
```

but I'm not sure what it does nor if it's really neccessary...

**Comment by ChaosMarc** [comment]
My issue https://github.com/julman99/gson-fire/issues/52 has been resolved and there is a new release which includes the change: https://github.com/julman99/gson-fire/releases/tag/v1.9.0

So this issue here can be fixed by upgrading to the latest version of gson-fire (not yet available as a maven dependency at the time I'm writing this)

**Comment by wing328** [comment]
@ChaosMarc thanks for the update. we'll update gson-fire to the latest version later.

**Comment by ChaosMarc** [comment]
here you go: https://github.com/OpenAPITools/openapi-generator/pull/17002 😃
