### ISSUE TITLE
[cpp-pistache-server] Enumerations not generated

### ISSUE THREAD

**Issue by brianwaters3** [OpenAPITools/openapi-generator#1317]
##### Description

Currently the enumeration definition below generates a class with no members.  The attached file archive.zip contains a complete definition (with several enumerations) that demonstrate this problem.

[Archive.zip](https://github.com/OpenAPITools/openapi-generator/files/2515830/Archive.zip)

##### openapi-generator version

v 3.3.0

##### OpenAPI declaration file content or url

```yaml
    SupportedGADShapes:
      anyOf:
        - type: string
          enum:
            - POINT
            - POINT_UNCERTAINTY_CIRCLE
            - POINT_UNCERTAINTY_ELLIPSE
            - POLYGON
            - POINT_ALTITUDE
            - POINT_ALTITUDE_UNCERTAINTY
            - ELLIPSOID_ARC
        - type: string
```

##### Command line used for generation

java -jar /home/brian/code/git/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i updated/TS29122_MonitoringEvent.yaml -g cpp-pistache-server --config __config__ -o ./code/MonitoringEvent/server/cpp-pistache-server

##### Steps to reproduce

1. Create a blank working directory
2. Unzip Archive.zip to the newly created directory.
3. Generate the source using the provided command making path adjustments for your system.
4. The class SupportedGADShapes in ./code/MonitoringEvent/server/cpp-pistache-server/model/SupportedGADShapes.h has no members.

##### Suggest a fix/enhancement

The attached file SupportedGADShapes.zip contains the .h and .cpp definitions for the enumeration. 
 Note that an enumeration named "INVALID" has been added in the header and is used when no default is specified.

[SupportedGADShapes.cpp-pistache-server.zip](https://github.com/OpenAPITools/openapi-generator/files/2515849/SupportedGADShapes.cpp-pistache-server.zip)

```
...
    /////////////////////////////////////////////
    /// SupportedGADShapes members
    enum eSupportedGADShapes
    {
       INVALID,
       POINT,
       POINT_UNCERTAINTY_CIRCLE,
       POINT_UNCERTAINTY_ELLIPSE,
       POLYGON,
       POINT_ALTITUDE,
       POINT_ALTITUDE_UNCERTAINTY,
       ELLIPSOID_ARC
    };

    eSupportedGADShapes getValue() const;
    void setValue(eSupportedGADShapes const value);

protected:
    eSupportedGADShapes m_value;
...
```

```
...
nlohmann::json SupportedGADShapes::toJson() const
{
    nlohmann::json val;
    
    switch (m_value)
    {
       case eSupportedGADShapes::POINT:                        val = "POINT";  break;
       case eSupportedGADShapes::POINT_UNCERTAINTY_CIRCLE:     val = "POINT_UNCERTAINTY_CIRCLE";  break;
       case eSupportedGADShapes::POINT_UNCERTAINTY_ELLIPSE:    val = "POINT_UNCERTAINTY_ELLIPSE";  break;
       case eSupportedGADShapes::POLYGON:                      val = "POLYGON";  break;
       case eSupportedGADShapes::POINT_ALTITUDE:               val = "POINT_ALTITUDE";  break;
       case eSupportedGADShapes::POINT_ALTITUDE_UNCERTAINTY:   val = "POINT_ALTITUDE_UNCERTAINTY";  break;
       case eSupportedGADShapes::ELLIPSOID_ARC:                val = "ELLIPSOID_ARC";  break;
       default:                                                val = "INVALID";  break;
    }

    return val;
}

void SupportedGADShapes::fromJson(nlohmann::json& val)
{
    auto s = val.get<std::string>();
    
    m_value =
          (s == "POINT")                        ? eSupportedGADShapes::POINT :
          (s == "POINT_UNCERTAINTY_CIRCLE")     ? eSupportedGADShapes::POINT_UNCERTAINTY_CIRCLE :
          (s == "POINT_UNCERTAINTY_ELLIPSE")    ? eSupportedGADShapes::POINT_UNCERTAINTY_ELLIPSE :
          (s == "POLYGON")                      ? eSupportedGADShapes::POLYGON :
          (s == "POINT_ALTITUDE")               ? eSupportedGADShapes::POINT_ALTITUDE :
          (s == "POINT_ALTITUDE_UNCERTAINTY")   ? eSupportedGADShapes::POINT_ALTITUDE_UNCERTAINTY :
          (s == "ELLIPSOID_ARC")                ? eSupportedGADShapes::ELLIPSOID_ARC :
                eSupportedGADShapes::INVALID;
}

SupportedGADShapes::eSupportedGADShapes SupportedGADShapes::getValue() const
{
   return m_value;
}

void SupportedGADShapes::setValue(SupportedGADShapes::eSupportedGADShapes const value)
{
   m_value = value;
}
...
```

**Comment by federicovalenso** [comment]
Generator still generates enums the same way (a class with no members). Is there any chance that this issue will ever be fixed ?

**Comment by mfyuce** [comment]
Hi,
Thanks for the PR.

What is it that needed to fix and reopen and merge this [PR](https://github.com/OpenAPITools/openapi-generator/pull/1366)? I will help if need.

Thanks a lot.
