### ISSUE TITLE
[REQ] [Swift5] Improve Objective-C interoperability by using @objcMembers instead of @objc at class level

### ISSUE THREAD

**Issue by tsanidas** [OpenAPITools/openapi-generator#13175]
## Describe the issue
When using the `objcCompatible` option, classes are generated with `@objc` at the class level. While using these classes from Objective-C, you will receive a compiler error when trying to access any property:
  `Property 'xyz' not found on object of type 'GeneratedSwiftClass *'`

## Describe the solution you'd like
I'd like to use `@objcMembers` instead of `@objc` in the mustache template file.  I can send in a PR for this if we can get consensus on this change.

**Comment by wing328** [comment]
@tsanidas thanks for the suggestion.

cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @4brunu (2019/11)

**Comment by 4brunu** [comment]
@tsanidas looks good to me 👍

**Comment by tsanidas** [comment]
Hi all.  I've submitted a PR for this.  Please see: https://github.com/OpenAPITools/openapi-generator/pull/15188

**Comment by 4brunu** [comment]
I'm closing this issue, as this should now be fixed, if this is still an issue, please reopen this issue.
Thanks
