### ISSUE TITLE
[BUG][spring] report fix 11886 from java to spring generator - function fromValue for enum model have wrong end if enumUnknownDefaultCase=true

### ISSUE THREAD

**Issue by christophejan** [OpenAPITools/openapi-generator#13241]
[#11886](https://github.com/OpenAPITools/openapi-generator/issues/11886) has fixed function fromValue for enum mode if enumUnknownDefaultCase=true on `java` generator.

Could you please report this fix on `spring` generator ([enumClass.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/enumClass.mustache) and [enumOuterClass.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/enumOuterClass.mustache)).

`spring` generator has `enumUnknownDefaultCase` option like `java` generator ([see spring generator doc](https://openapi-generator.tech/docs/generators/spring/)) and I don't think there is any reason to get an enum behavior different from `java` generator.

**Comment by boroczkigabor** [comment]
What's up with this?

**Comment by s-jepsen** [comment]
What's status on this?

**Comment by michalgazda** [comment]
Also may want to consider taking a look on this topic in openapi specification, where defaulting enum value is proposed as standard extension: https://github.com/OAI/OpenAPI-Specification/issues/1552
