### ISSUE TITLE
[BUG][Python] Client legacy generator asyncio README code example

### ISSUE THREAD

**Issue by jpotyka** [OpenAPITools/openapi-generator#13247]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The python client legacy generator produces a non functional example code in the generated `README.md`.
There are two missing keywords. The code can therefore not be executed.

The `with` context manager has to be replaced with the async one `async with`.
And the API call is now async, so coroutine has to be awaited with the `await` keyword.

Actual code without generated comments:
```python
from __future__ import print_function

import time
import foopy
from foopy.rest import ApiException
from pprint import pprint

configuration = foopy.Configuration(
    host = "http://localhost"
)

with foopy.ApiClient(configuration) as api_client:  # async with
    api_instance = foopy.FooApi(api_client)
    foo_create_schema = foopy.FooCreateSchema()

    try:
        api_response = api_instance.api_v1_foo_create_post(foo_create_schema)  # await
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling FooApi->api_v1_foo_create_post: %s\n" % e)
```

Expected code without generated comments:
```python
from __future__ import print_function

import time
import foopy
from foopy.rest import ApiException
from pprint import pprint

configuration = foopy.Configuration(
    host = "http://localhost"
)

async with foopy.ApiClient(configuration) as api_client:  # async with
    api_instance = foopy.FooApi(api_client)
    foo_create_schema = foopy.FooCreateSchema()

    try:
        api_response = await api_instance.api_v1_foo_create_post(foo_create_schema)  # await
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling FooApi->api_v1_foo_create_post: %s\n" % e)
```

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

`modules/openapi-generator/src/main/resources/python-legacy/common_README.mustache`

```py
# Enter a context with an instance of the API client
with {{{packageName}}}.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = {{{packageName}}}.{{{classname}}}(api_client)
    {{#allParams}}{{paramName}} = {{{example}}} # {{{dataType}}} | {{{description}}}{{^required}} (optional){{/required}}{{#defaultValue}} (default to {{{.}}}){{/defaultValue}}
    {{/allParams}}

    try:
    {{#summary}}    # {{{.}}}
    {{/summary}}    {{#returnType}}api_response = {{/returnType}}api_instance.{{{operationId}}}({{#allParams}}{{#required}}{{paramName}}{{/required}}{{^required}}{{paramName}}={{paramName}}{{/required}}{{^-last}}, {{/-last}}{{/allParams}}){{#returnType}}
        pprint(api_response){{/returnType}}
    except ApiException as e:
        print("Exception when calling {{classname}}->{{operationId}}: %s\n" % e)
    {{/-first}}{{/operation}}{{/operations}}{{/-first}}{{/apis}}{{/apiInfo}}
```

##### Generation Details

 ```
openapi-generator-cli generate \
-g python-legacy \
--library asyncio \
...
```

##### Steps to reproduce

Just generate a python asyncio client with the previously specified command.

##### Related issues/PRs

Just found this https://github.com/OpenAPITools/openapi-generator/issues/763 issue. Not exactly the same, but maybe can be closed too if the generated example works.

##### Suggest a fix

I would add the missing keywords in the template file. If it is desired I can open a PR to fix this bug.

**Comment by spacether** [comment]
Feel free to post a PR fixing this
