### ISSUE TITLE
Syntax error in generated html

### ISSUE THREAD

**Issue by scoldwell** [OpenAPITools/openapi-generator#13272]
https://github.com/OpenAPITools/openapi-generator/blob/c4db27f24dabc5e2e98cf977ad83d3a96ff591c2/modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache#L458 is missing a curly brace, a paren and a semi-colon.  Had to add `});` after the aforementioned line

**Comment by robbieaverill** [comment]
@scoldwell you might consider making a pull request to fix it

**Comment by wing328** [comment]
yes please file a PR: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements

**Comment by scoldwell** [comment]
Will do

**Comment by scoldwell** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/13293

**Comment by wing328** [comment]
Thanks for the PR, which has been merged. 

Have a nice weekend.
