### ISSUE TITLE
[REQ] aspnetcore: readonly properties

### ISSUE THREAD

**Issue by supersupernike** [OpenAPITools/openapi-generator#13290]
### We are using the same class for request and for response. Some of the properties are defined as readonly in the yml-file, but in the code, generated automatically by openapi-generator-cli (with generator = aspnetcore), the properties are created as normal public get/set property. For example, if the yml-file contains the following:
![image](https://user-images.githubusercontent.com/112158532/186907336-53119998-47b5-43fd-a40f-219e67c5a80c.png)
### the following property is generated:
`public string Name { get; set; }`

## If the property is created with a private "setter", introducing also a public method to set it (Set + PropetyName):
```
public string Name { get; private set; }
...
public void SetName(string value) { Name = value; }
```
## the property will be marked as readonly in  the schema and it is possible to set it, if it is used in response. The same mechanism can be used for writeonly property: a private "getter" and a method (Get + PropertyName) to get the value

**Comment by supersupernike** [comment]
I solved the problem changing a  local copy of the model.mustache file

**Comment by wing328** [comment]
@supersupernike thanks for the update. May I know if you can contribute a PR so that we can incorporate the fix into the official repo?

**Comment by supersupernike** [comment]
The correction for me was very simple because I had to implement only the "readonly" flag for a string property. A complete implementation should consider also other types and the "writeonly"  flag.
I changed the model.mustache and instead of a normal  "get; set;" property:
```
{{^isEnum}}
public {{{dataType}}} {{name}} { get; set; }{{#defaultValue}} = {{{.}}};{{/defaultValue}}
{{/isEnum}}
```
I used a private setter and a public set method (public void Set<_PropetyName_>(...)):
```
{{^isEnum}}
{{#isReadOnly}}
public {{{dataType}}} {{name}} { get; private set; }{{#defaultValue}} = {{{.}}};{{/defaultValue}}

/// <summary>
/// ReadOnly  property: set method to use in response
/// </summary>
/// <param name="value">value to set</param>
public void Set{{name}}({{{dataType}}} value) { {{name}} = value; }
{{/isReadOnly}}
{{^isReadOnly}}
public {{{dataType}}} {{name}} { get; set; }{{#defaultValue}} = {{{.}}};{{/defaultValue}}
{{/isReadOnly}}
{{/isEnum}}
```
