### ISSUE TITLE
[BUILD] Add Bazel support

### ISSUE THREAD

**Issue by qzmfranklin** [OpenAPITools/openapi-generator#1330]
I'd like to initiate the discussion of the following topic:
> Add support for Bazel as an officially supported build system (in lieu of Maven, for example)

[Bazel] (http://bazel.io/) is a build tool open sourced by Google. Internally at Google, it is known as `Blaze`. It offers a lot of benefits to developers, with the top few being:
- Fully hermetic build, bit reproducible.
- Expressive python-like [meta-language](https://docs.bazel.build/versions/master/skylark/language.html) that specifies the building process.
- Easy to extend to support *arbitrary* programming languages.

Some other benefits such as massively scalable build and perfect incremental builds are also very nice, but not greatly relevant to this discussion.

For the project of `openapi-generator`, which is a multilingual project in nature, Bazel provides the following additional benefits:
- **Greatly facilitate meaningful developer interactions across different programming languages**. Having the build system *natively* support all programming languages minimizes the barrier between developers working on different problem domains. For example, a TypeScript developer can use the same `bazel build/run` command to develop for Python and Java. The setup time required for running a hello-world is minimized.
- **Greatly improved test coverage**. Tests that are easy to run get run more often. Being able to run tests for all programming languages with a simple `bazel test //...` encourages developers to run tests in the first place. Secondly, `Bazel` correctly tracks dependencies and caches the test results so that only the tests that are affected by your changes are run. If you made a one-line change, chances are, you got only a few tests to run. This sharply constrasts with how Maven runs tests, where all tests are run even with a one-line change.
- **Greatly improve the development speed on new programming languages**. Because it is very easy to extend Bazel to support them. The Bazel community has developed a lot of extensions, many of which have been battle tested by many companies with big names. Most such extensions are available as repos under the URL of `http://bazelbuild.github.io/rules_RULE_NAME` where RULE_NAME could be `typescript`, `nodejs`, `scala`, `docker`, `sass`, `k8s`, `go`, `rust`, `swift` etc..
- **Extend the reach of this project to a fast-growing, high-impact developer community**. Bazel users is a fast-growing community, judging by GitHub stars, issues, and PRs. More and more projects, especially those open sourced by Google such as protobuf, grpc, Tensorflow, Angular, etc. are using Bazel as the default build system. Being able to seamlessly integrate with those high-impact projects could significantly up the impact of this project.

The above said, I fully understand the disruptive nature of this proposal. Looking forward to all the conversations sparking new ideas.

Thanks in advance.

**Comment by mrmeku** [comment]
I'll be adding this over the next week

**Comment by mrmeku** [comment]
@qzmfranklin This is fixed now. There's a new repo which has bazel bindings for the openapi generator at https://github.com/OpenAPITools/openapi-generator-bazel

**Comment by qzmfranklin** [comment]
@mrmeku: Thanks for the nice work!

I was thinking of proposing building the openapi-generator-cli with Bazel.
But a Bazel binding for the pre-built jar file is also useful. Indeed, our team is using openapi internally with a custom Bazel binding. That was pretty ergonomic to us. But I do not think it approrpiate for general uses like the one you did.
