### ISSUE TITLE
Discriminator/mapping is ignored in version 6.0.0 javaSpring

### ISSUE THREAD

**Issue by josef-valo** [OpenAPITools/openapi-generator#13306]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Hi,
I found problem when discriminator/mapping is used for JavaSpring template. 

The problem was introduced in version 6.0.0 with change https://github.com/OpenAPITools/openapi-generator/commit/194b3fda26576c2ed0af38d14321c819c80f67b5 ( @JsonTypeName("{{name}}")  was added).

```
For example SWAGGER:
 components:
  schemas:
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
        mapping:
          DOG_ANIMAL: Dog
          CAT_ANIMAL: cat
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string

```
Serialization in JAVA Spring: The JSON in **pet_type** will have value Cat instead of **CAT_ANIMAL**.
##### openapi-generator version

6.0.0

**Comment by josef-valo** [comment]
Hi,
I found problem when discriminator/mapping is used for JavaSpring template. 

The problem was introduced in version 6.0.0 with change https://github.com/OpenAPITools/openapi-generator/commit/194b3fda26576c2ed0af38d14321c819c80f67b5 ( @JsonTypeName("{{name}}")  was added).

For example SWAGGER:
 components:
  schemas:
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
        **mapping:
          DOG_ANIMAL: Dog
          CAT_ANIMAL: cat**
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Dog`
        properties:
          bark:
            type: string

Serialization in JAVA Spring: The JSON in **pet_type** will have value Cat instead of **CAT_ANIMAL**.

**Comment by wing328** [comment]
the java client generator (jersey2, okhttp-gson) already supports discriminator mapping. can you please give it a try to see if that's what you're looking for?

if that works for you, we can plot it to the java spring generator.

**Comment by josef-valo** [comment]
Thank you after response.

The version v5.4.0 works correctly. The functionality is broken in v6.0.0 ( https://github.com/OpenAPITools/openapi-generator/commit/194b3fda26576c2ed0af38d14321c819c80f67b5 ).

But I understand that discriminator mapping is not supported for the java spring generator. 

So it could be great to support the  discriminator mapping for the  java spring generator. 

Than you 

Regards Josef

**Comment by vgrigoriev** [comment]
@josef-valo I guess it's fixed here https://github.com/OpenAPITools/openapi-generator/issues/14731
