### ISSUE TITLE
[BUG] Resteasy Response object not closed after API call

### ISSUE THREAD

**Issue by MikeEdgar** [OpenAPITools/openapi-generator#13327]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Resteasy client template does not close the `Response` (implements `AutoCloseable`).

https://github.com/OpenAPITools/openapi-generator/blob/225204093fa22b6ff1f78bc7b46f8bb3311e4d65/modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache#L675-L723

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

N/A

##### Generation Details

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix

Handle the `Response` using try-with-resources, such as: https://github.com/MikeEdgar/openapi-generator/blob/06e93fabbfd66cd4f0f26d47bfba32a9ce3992d4/modules/openapi-generator/src/main/resources/Java/libraries/resteasy/ApiClient.mustache#L675-L730

**Comment by wing328** [comment]
@MikeEdgar thanks for reporting the issue. Can you please file a PR with the suggested change?
