### ISSUE TITLE
[REQ] [R] Removal of forced basic authentication

### ISSUE THREAD

**Issue by oganm** [OpenAPITools/openapi-generator#13328]
### Is your feature request related to a problem? Please describe.

It seems that R code generated always forces the user to provide some sort of authentication information. For instance for an API I generated for every method we have this test

https://github.com/oganm/openapi_test/blob/master/R/default_api.R#L6333-L6336
```r
if (is.null(self$api_client$username) || is.null(self$api_client$password)) {
        stop("username, password in `api_client` must be set for authentication in the endpoint `SearchTaxonDatasets`.")
      }
      header_params["Authorization"] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$api_client$username, self$api_client$password, sep = ":"))))
```

even if the API would work fine without any authorisation.

## Describe the solution you'd like

If authentication information is not provided, access should still be attempted without an automatic failure

## Describe alternatives you've considered

Overwriting the check in the generated code allows removal of the authentication requirement

Using this script on the generated code removes the hard requirement
```r
default = readLines('R/default_api.R')
auth_code = grepl("# HTTP basic auth",default)
for (i in which(auth_code)){
    default[i+1] = default[i+1]  %>% 
        gsub('is.null','!is.null',.)
    default[i+2] = paste0("  ",default[i+4])
    default[i+4] = ""
}

writeLines(default,'R/default_api.R')
```

by changing the check to

```r
if (!is.null(self$api_client$username) || !is.null(self$api_client$password)) {
    header_params["Authorization"] <- paste("Basic", base64enc::base64encode(charToRaw(paste(self$api_client$username, self$api_client$password, sep = ":"))))
      }
```

It is possible there is something in the api specification [file I use](https://github.com/swagger-api/swagger-codegen/files/9429783/openapi.txt) that claims authentication is mandatory but I don't believe this is the case

**Comment by wing328** [comment]
According to the spec, it supports multiple authentications (including http basic, cookie, etc).

I'll update the code accordingly to allow multiple security define and won't throw error if these auth is not provided.
