### ISSUE TITLE
[REQ] [Typescript] Support DELETE Payload

### ISSUE THREAD

**Issue by angelaki** [OpenAPITools/openapi-generator#13380]
Like discussed in https://github.com/OpenAPITools/openapi-generator/pull/10976 the possibility to add a payload to the DELETE method was removed. I'd suggest to completely switch to Angular HttpClient's `request` method (instead of get / post / put e.g.). All the other methods are just overloads to the request method.

This way the generator would be less dependent on Angulars API. I hope this is easy to implement for someone here knowing the mustache templates? I've checked it but it pretty much felt like I'd need some more knowledge of the generator's code.

**Comment by cmalard** [comment]
Oh gosh, this reminds me something 🤦 😅 😂
https://github.com/swagger-api/swagger-codegen-generators/pull/568

**Comment by cmalard** [comment]
I guess something was lost with all the forks & merge when OpenApiTools & SwaggerApi were not yet aligned 😅

**Comment by angelaki** [comment]
Hey @cmalard, any chance you could fix this, soon? 🙄 It seams like many issues were caused by just not using the request method (fixed DELETE method forth and back and so on ...) plus I'd really need it these days. And I'm actually **quite** scred I'd need to do this myself ... 😂🙈

**Comment by cmalard** [comment]
Hey @angelaki 🙋 I will also need it in the next weeks (again for another project 😂), if you want it asap, don't wait for me & feel free to do it 😉 🍻
-> https://github.com/swagger-api/swagger-codegen-generators/pull/568/files
-> https://github.com/swagger-api/swagger-codegen-generators/pull/576/files (bugs introduced above fixed ^^")

**Comment by amakhrov** [comment]
I'll take a stab at implementing it (via the "HttpClient#request" method under the hood) over the weekend

**Comment by angelaki** [comment]
Thank you so much! Reading your PR I just noticed that @cmalard initial fix was actually for SwaggerCodGen, not for OpenAPIGenerator 😂. Never the less it's fixed now, great! :)

When while this fix probably make it to the Docker CLI?

**Comment by amakhrov** [comment]
@angelaki you can wait for the 6.1.1 release (planned for Oct 11). Or you can use the `latest` tag of the docker image (looks like it's already updated): https://hub.docker.com/layers/openapitools/openapi-generator-cli/latest/images/sha256-c73d1c3d9612b29d691ca95ee5cf80a7e6ae9cb04033e7b283bb0ed49bfdadc1?context=explore

**Comment by angelaki** [comment]
@amakhrov the latest version
```
$ docker run openapitools/openapi-generator-cli version
6.0.0-SNAPSHOT
```

still seams to generate the cold methods.

**Comment by macjohnny** [comment]
@angelaki I think it should be in the 6.1.1 snapshot: https://github.com/OpenAPITools/openapi-generator#11---compatibility

**Comment by angelaki** [comment]
@amakhrov I was actually running latest, just simplified it. Maybe I shouldn't have. Never the less, latest **is** version `6.0.0-SNAPSHOT` ... for me?

**Comment by amakhrov** [comment]
@angelaki did everything work for you then?

**Comment by angelaki** [comment]
@amakhrov yes, looks pretty good, thank you so much!

**Comment by angelaki** [comment]
Completly off-topic, but maybe you can answer this question: how to retrieve `blob` data via generated client? All the overloads only accept `httpHeaderAccept?: 'text/plain' | 'application/json' | 'text/json'` while the method looks like this:

```
let responseType_: 'text' | 'json' | 'blob' = 'json';
if (localVarHttpHeaderAcceptSelected) {
    if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
    } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
    } else {
        responseType_ = 'blob';
    }
}
```

having this swagger json:

```
 "200": {
    "description": "Success",
    "content": {
        "application/octet-stream": {
        "schema": {
            "$ref": "#/components/schemas/DownloadResult"
        }
        }
    }
},
```

Cannot call it with 'blob' since no overload accepts this. Create a new issue? Guess someone would have noticed yet, if this wasn't possible? 😅

**Comment by amakhrov** [comment]
Not sure what exactly you try to do.
Perhaps the Slack workspace would be a better place to ask: https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
