### ISSUE TITLE
[BUG][typescript] Unbalanced brackets in patterns during parsing

### ISSUE THREAD

**Issue by zodiia** [OpenAPITools/openapi-generator#13390]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

I am trying to generated an OpenAPI client using the `typescript` generator. Unfortunately, I am hitting a bug with the parser, which seemingly forgets the last character of regex patterns.

With the pattern `[A-Z]{3}`, I get the following error message:

```
  Exception: Unbalanced '{' - missing '}' at 
'[A-Z]{3'
      ^

Caused by: com.github.curiousoddman.rgxgen.parsing.dflt.RgxGenParseException: Unbalanced '{' - missing '}' at 
'[A-Z]{3'
      ^
```

(full log using the provided sample OpenAPI in attached files: [output.log](https://github.com/OpenAPITools/openapi-generator/files/9534415/output.log))

Changing the pattern to something else, like `[A-Z][A-Z][A-Z]` doesn't help either, the same error message pops up with the last character seemingly disappearing. Changing it to `[A-Z]{3}}` solves the issue, but is obviously not a fix since it will break up other generators.

Note that, in the schemas section of the error message, the parsed schema does have the last pattern character in it (as seen in the full log: `pattern: [A-Z]{3}`).

##### openapi-generator version

`6.0.1`, `6.1.0`, `6.2.0`

##### OpenAPI declaration file content or url

[test.yml](https://gist.github.com/zodiia/e855527f4d3e5f89cc57d640710998d2)

##### Generation Details

I am simply using the `openapi-generator-cli` command, providing an input OpenAPI file, `typescript` generator and an output directory.

##### Steps to reproduce

Using the provided sample OpenAPI file above and run the following command: `openapi-generator-cli generate -i test.yml -g typescript -o ./out`

##### Related issues/PRs

Not found.

##### Suggest a fix

My theory is that the `typescript` generator is, for some reason, removing the last character of patterns, which it shouldn't do.

**Comment by florianfischer91** [comment]
I can confirm the bug also when using the new python (experimental) generator

**Comment by RemakeTm** [comment]
I also noticed the same bug and haven't found any fix yet ...

**Comment by zodiia** [comment]
Can confirm this issue is still present in both `6.1.0` and `6.2.0`.

**Comment by danihodovic** [comment]
Same when using the python generator at v6.2.0.

```
  Exception: Unbalanced '{' - missing '}' at
'[0-9]{7'
      ^
        at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1187)
        at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1081)
        at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:580)
        at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:915)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:465)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: com.github.curiousoddman.rgxgen.parsing.dflt.RgxGenParseException: Unbalanced '{' - missing '}' at

```
