### ISSUE TITLE
[BUG] Service needs access to http response headers to set Location header 

### ISSUE THREAD

**Issue by blackgold** [OpenAPITools/openapi-generator#13407]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x ] Have you searched for related issues/PRs?
- [x ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Need the ability for service to set location header in case where a new resource is created. Current generated code does not have access to http.ResponseWriter.
Looked at this workaround https://github.com/OpenAPITools/openapi-generator/issues/10837 but it does not help in this use case because the response headers needs to be set after calling service. 

##### openapi-generator version

I am using this jar to generate code openapi-generator-cli-7.0.0-20220719.043604-2.jar

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  description: OAuth API server
  version: 1.0.0
  title: "OAuth API"

servers:
  - url: http://localhost:8080/api/v1
    description: development server
paths:
  /gen/{id}:
    parameters:
      - name: id
        in: path
        description: Identifier of the resource
        required: true
        schema:
          type: string
    post:
      summary: generate resource and respond with location header
      tags:
        - Gen Resource
      requestBody:
        description: request to create new resoruce
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        201:
          description: ceated
          headers:
            Location:
              description: URI of resource
              required: true
              schema:
                type: string
```

##### Generation Details

java -Dhttp.proxyHost=fwdproxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=fwdproxy -Dhttps.proxyPort=8080 -Djava.net.preferIPv6Stack=true -jar ~/openapi-generator-cli-7.0.0-20220719.043604-2.jar generate -i 1.yaml -p packageName=server -g go-server -o server

##### Steps to reproduce

java -Dhttp.proxyHost=fwdproxy -Dhttp.proxyPort=8080 -Dhttps.proxyHost=fwdproxy -Dhttps.proxyPort=8080 -Djava.net.preferIPv6Stack=true -jar ~/openapi-generator-cli-7.0.0-20220719.043604-2.jar generate -i 1.yaml -p packageName=server -g go-server -o server

In the generated service file I would like to set HTTP Location Header in case the resource is successfully created. However http.ResponseWriter is not available

```
// GenIdPost - generate resource and respond with location header
func (s *GenResourceApiService) GenIdPost(ctx context.Context, id string, body string) (ImplResponse, error) {
  // TODO - update GenIdPost with the required logic for this service method.
  // Add api_gen_resource_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

  //TODO: Uncomment the next line to return response Response(201, {}) or use other options such as http.Ok ...
  //return Response(201, nil),nil

  return Response(http.StatusNotImplemented, nil), errors.New("GenIdPost method not implemented")
}
```

Following is the generated code for controller. 
```
// GenIdPost - generate resource and respond with location header
func (c *GenResourceApiController) GenIdPost(w http.ResponseWriter, r *http.Request) {
  params := mux.Vars(r)
  idParam := params["id"]
  
  bodyParam := string{}
  d := json.NewDecoder(r.Body)
  d.DisallowUnknownFields()
  if err := d.Decode(&bodyParam); err != nil {
    c.errorHandler(w, r, &ParsingError{Err: err}, nil)
    return
  }
  result, err := c.service.GenIdPost(r.Context(), idParam, bodyParam)
  // If an error occurred, encode the error with the status code
  if err != nil {
    c.errorHandler(w, r, err, &result)
    return
  }
  // If no error, encode the body and the result code
  EncodeJSONResponse(result.Body, &result.Code, w)

}
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/10837

The workaround I can think of is write a wrapper controller that passes a channel though the request context object to avoid making changes to controller code and controller/service APIs. The service can write the location to channel and the wrapper controller can update the response headers. This workaround is brittle as the information is not passed via APIs.

**Comment by blackgold** [comment]
go-server has an option addResponseHeaders which solves the purpose.
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/go-server.md

**Comment by uri200** [comment]
Thanks @blackgold , just for the record, the command to use is

```
openapi-generator-cli.jar  generate -i 1.yaml -p packageName=server -g go-server -o server --additional-properties=addResponseHeaders=true
```
