### ISSUE TITLE
[BUG] Path names are too long on windows, breaks workflow

### ISSUE THREAD

**Issue by 0xNF** [OpenAPITools/openapi-generator#13458]
Using the current master commit 7e87b5d109193ef764cc5ebe7cc08204333f0344 with PowerShell, the files under python-experimental are too long too be processed. This makes working with the repo difficult.

```powershell
PS ~\projects\experiments\openapi\openapi-generator> git stash

(error: lstat("samples/openapi3/client/3_0_3_unit_test/python-experimental/test/test_paths/test_request_body_post_additionalproperties_allows_a_schema_which_should_validate_request_body/__init__.py"): Filename too long)
```

**Comment by wing328** [comment]
Please run `git config --global core.longpaths true` to fix the issue on Windows.

**Comment by 0xNF** [comment]
I'll be damned, that was it. You're a lifesaver William, thanks.
