### ISSUE TITLE
[BUG] R generator mishandles optional body argument

### ISSUE THREAD

**Issue by jlorince** [OpenAPITools/openapi-generator#13468]
[BUG] R generator mishandles optional body argument

#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When the request body for an endpoint is specified as optional, the R generator produces un-runnable code. 

The generator produces two functions per endpoint in the spec, in this example `RunProject` and `RunProjectWithHttpInfo`. The former invokes the latter, like so:
```
    RunProject = function(project_id, run_project_request_body = NULL, data_file = NULL, ...) {
      local_var_response <- self$RunProjectWithHttpInfo(project_id, run_project_request_body, data_file = data_file, ...)
      ...
```
As you can see, the request body defaults to `NULL` in the `RunProject` function, but this breaks things if the body is not explicitly specified, because in `RunProjectWithHttpInfo` the code checks if the body is present at all, not if it's null:

```
      if (!missing(`run_project_request_body`)) {
        local_var_body <- `run_project_request_body`$toJSONString()
      } else {
        body <- NULL
      }
```
Thus whenever `RunProject` is invoked without a body, it leads to an error because the request defaults to null (rather than being missing), so ``run_project_request_body`$toJSONString()` fails with an error trying to call `toJSONString` on a null object,

##### openapi-generator version

6.1.0
##### OpenAPI declaration file content or url

```
...
 "paths": {
    "/project/{projectId}/run": {
      "post": {
        "operationId": "RunProject",
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProjectRunResponsePayload"
                }
              }
            }
          },
  ...
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RunProjectRequestBody"
              }
            }
          }
        }
      }
    }
...      
```    

##### Generation Details
```yarn run openapi-generator-cli generate -i ./generated/openapi.json -o ../../r-sdk --package-name hexApi -g r```

##### Steps to reproduce

See above.

##### Suggest a fix

I think this should be as simple as updating the generation code to produce code like this:
```
      if (!is.null(`run_project_request_body`)) {
        local_var_body <- `run_project_request_body`$toJSONString()
      } else {
        body <- NULL
      }
```
rather than
```
      if (!missing(`run_project_request_body`)) {
        local_var_body <- `run_project_request_body`$toJSONString()
      } else {
        body <- NULL
      }
```

**Comment by wing328** [comment]
@jlorince thanks for reporting the issue. I'll take a look.
