### ISSUE TITLE
[BUG][REQ][python-experimental] Deserialization is failed when the content-type is `application/json; charset=utf-8`

### ISSUE THREAD

**Issue by EltonChou** [OpenAPITools/openapi-generator#13467]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

@spacether 
When the response's content-type is `application/json; charset=utf-8`,
the library will raise the `ApiValueError`.
(Another bug: The error message wasn't formatted correctly.)

Output:
```
ApiValueError: Invalid content_type=application/json; charset=utf-8 returned for response with status_code={str(response.status)}
```
https://github.com/OpenAPITools/openapi-generator/blob/f773ac7bfeefe0a3f6c41a74770bae4d16ac6c82/samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py#L920-L924

##### openapi-generator version
`v6.1.0`

##### Steps to reproduce

https://github.com/OpenAPITools/openapi-generator/blob/f773ac7bfeefe0a3f6c41a74770bae4d16ac6c82/samples/openapi3/client/petstore/python-experimental/tests_manual/test_deserialization.py#L29

change the code to
```py
json_content_type_headers = {'content-type': json_content_type + "; charset: utf-8"}
```

##### Related issues/PRs

#13465 

##### Suggest a fix

Since the `JSONDetector` treats `application/json; charset=utf-8` as a valid json, 
the code should treat `application/json; charset=utf-8` as `application/json` when check the `self.content`.

https://github.com/OpenAPITools/openapi-generator/blob/f773ac7bfeefe0a3f6c41a74770bae4d16ac6c82/samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py#L802-L816
https://github.com/OpenAPITools/openapi-generator/blob/f773ac7bfeefe0a3f6c41a74770bae4d16ac6c82/samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py#L934-L935
https://github.com/OpenAPITools/openapi-generator/blob/f773ac7bfeefe0a3f6c41a74770bae4d16ac6c82/samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py#L920-L924

##### Further
Should  `application/json-patch+json` and `application/geo+json` be treated as `application/json` when checking content?

**Comment by spacether** [comment]
> Should application/json-patch+json and application/geo+json be treated as application/json when checking content?

Yes it should per the json regex.
Can you please provide your source openapi spec? It sounds like you are trying to deserialized a response content type that does not exist in your spec.

**Comment by spacether** [comment]
@EltonChou can you please provide your openapi source spec file that you are using to generate the client?
Or just the endpoint and schemas that demonstrate this problem.

**Comment by EltonChou** [comment]
Thanks for the explanation.
I found this problem was caused by the mock server I used.
I will open another PR (#13471) to fix the error message .

**Comment by Mainian** [comment]
@spacether
I think this issue should be re-opened.

For interoperability reasons, `application/json` is `application/json; charset=utf-8` 

More information on this topic is in this issue [#12797](https://github.com/OpenAPITools/openapi-generator/issues/12797)

**Comment by spacether** [comment]
Can you please file a new issue for application json with charset handling? So far utf-8 is assumed. If a different charset is needed it must be included in the header and the client must handle it accordingly. Utf-8 works as-is now.

**Comment by ancailliau** [comment]
I'm afraid I hit the same issue. It looks like the charset is not handled as it should. 

```
Invalid content_type returned. Content_type='application/json; charset=utf-8' was returned when only {'application/json', 'text/plain', 'text/json'} are defined for status_code=200
```

**Comment by spacether** [comment]
The spec is an explicit listing of the allowed content types. Anything not in the spec should not be allowed, unless the content-type is `*/*` (anything)
The content type that your server is sending back is not the same as the one in your spec.
If you want this as a feature, please open a PR adding it.
One way to do that would be to add a command line argument, addContentTypesForJsonCharsets which when set to true, will add `application/json; charset=utf-8` and other additional charsets to the output client.

**Comment by spacether** [comment]
If someone wanted to submit a PR that 
- separates the content-type and the charset info
- and deserializes using both
That could allow in the json + charset when given a content type in the spec that lacks charset info.
That would be fine too.
