### ISSUE TITLE
[REQ] [csharp-netcore] Support `targetFramework` `net48` 

### ISSUE THREAD

**Issue by johnthagen** [OpenAPITools/openapi-generator#13476]
### Is your feature request related to a problem? Please describe.

Currently the latest .NET Framework release that is supported by the `csharp-netcore` generator is `net47`:

- https://openapi-generator.tech/docs/generators/csharp-netcore#config-options

For those of us stuck on .NET Framework (for reasons outside our control), it would be great to be able to target the latest .NET Framework 4.8.

## Describe the solution you'd like

Accept:

```
npx @openapitools/openapi-generator-cli generate --generator-name csharp-netcore targetFramework=net48 ...
```

And in the generated `.csproj`:

```xml
<TargetFramework>net48</TargetFramework>
```

I haven't found any issues running the generated code under .NET Framework 4.8 when I change the output manually.

## Additional context

I've found in practice that the legacy `csharp` generator is not as well maintained or quickly updated as `csharp-netcore`, so I've preferred to use `csharp-netcore` even for .NET Framework 4.8 applications.

**Comment by wing328** [comment]
yup, we can support that.

how urgent do you need it? would have time to contribute a PR?

**Comment by johnthagen** [comment]
> how urgent do you need it? 

It's not super urgent as we can pretty easily manually change the `<TargetFramework>` after generation. It was more that .NET Framework 4.8 is the final (and thus super LTS) version of .NET Framework that will be around for years as it continues to hang on, and new users would probably expect to be using that version of .NET Framework if they are still stuck on it.

> would have time to contribute a PR?

I haven't contributed much to `openapi-generator` before, so I'm not sure if I'll have time to make a PR myself.

**Comment by wing328** [comment]
UPDATE: I've filed https://github.com/OpenAPITools/openapi-generator/pull/13504 to add .net framework 4.8.

**Comment by johnthagen** [comment]
@wing328 Thanks! ❤️
