### ISSUE TITLE
[BUG] Looks like a copy paste bug "`1.cs" in file "CSharpNetCoreClientCodegen.java" 

### ISSUE THREAD

**Issue by ikill69** [OpenAPITools/openapi-generator#13479]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I executed the Net Core generator with the Library flag set to "generichost", I noticed several of my file names had "`1.cs" on the end.

I did a search of the repo and it looks like it may be a copy past bug. ["`1.cs"](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/CSharpNetCoreClientCodegen.java#:~:text=%2C%20%22TokenProvider-,%601.cs,-%22))%3B)

![image](https://user-images.githubusercontent.com/49211294/191379350-99772025-a914-42b7-b335-32fff4e5c036.png)

##### openapi-generator version

`docker pull openapitools/openapi-generator-cli:v6.1.0`

##### Steps to reproduce

`docker run --rm -v C:\Dev\OpenAPI_CodeGen:/local openapitools/openapi-generator-cli:v6.1.0 generate -i /local/My_swagger.json -g csharp-netcore -o /local/csharp/OpenApi --skip-validate-spec --additional-properties=netCoreProjectFile=true,targetFramework=net6.0,packageName=MyClient.SDK --library=generichost `

##### Suggest a fix

Remove the "`1" from the affected strings and mustache file names.

**Comment by wing328** [comment]
thanks for reporting the issue

cc @devhl-labs

**Comment by devhl-labs** [comment]
This is intentional. In C#, a class gets it's own file. That means a generic class must have some different file name than it's non-generic counterpart. We use `x where x is the number of generic parameters. This is what Microsoft used to do, but looks like they're now using underscores instead of the grave accent.

**Comment by ikill69** [comment]
Thanks for the Info @devhl-labs
