### ISSUE TITLE
Missing documentation for selective code generation

### ISSUE THREAD

**Issue by tedepstein** [OpenAPITools/openapi-generator#1349]
Swagger-Codegen documents the use of system properties for [selective generation](https://github.com/swagger-api/swagger-codegen#selective-generation). Apparently, OpenAPI-Generator retains this functionality, but I don't see where it's documented. Is it being deprecated, or did it just move to a different documentation page?

**Comment by wing328** [comment]
@tedepstein we've moved customization-related documentations under https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#selective-generation as the project's README contains too much information, which may make it not easy for beginners to go through.

**Comment by tedepstein** [comment]
Got it, thanks @wing328 .
