### ISSUE TITLE
[C++][Pistache-server] POST methods not generated

### ISSUE THREAD

**Issue by bocse** [OpenAPITools/openapi-generator#1354]
##### Description

When compiling the OpenAPI-v3 specification POST methods which have a specified request body don't get generated at all.

Reference:
https://github.com/deepviss/deepviss-server-example/blob/master/src/main/resources/deep-viss-openapi-v3.json

##### openapi-generator version

Pulled from master [https://github.com/OpenAPITools/openapi-generator] just before creating this ticket.

##### OpenAPI declaration file content or url

This is the decription of a POST path from 
https://github.com/deepviss/deepviss-server-example/blob/master/src/main/resources/deep-viss-openapi-v3.json
```
    "/analysis/ProcessingRequest":{
      "post":{
        "tags":[
          "frame"
        ],
        "summary":"Analyze a specific frame",
        "description":"",
        "operationId":"ImageAnalysis",
        "parameters":
        [
          {
            "in": "query",
            "name": "streamId",
            "schema": {
              "type": "string"
            },
            "description": "The identifier of the stream"
          }
        ],
        "requestBody": {
          "description": "Deliver the image to be analyzed *Markdown*",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ProcessingRequest"
              }
            },
            "application/xml": {
              "schema": {
                "$ref": "#/components/schemas/ProcessingRequest"
              }
            }
          }
        },
        "responses":{
          "200": {
            "description": "successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/definitions/Frame"
                  }
                }
              }
            }
          },
          "400":{
            "description":"Invalid status value"
          }
        }
      }
    },


The generate code only contains **FrameApi.cpp , FrameApi.h**, but no **AnalysisApi.cpp**

##### Command line used for generation

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
   -i https://raw.githubusercontent.com/deepviss/deepviss-server-example/master/src/main/resources/deep-viss.json \
   -g cpp-pistache-server \
   -o output_dir
```

##### Steps to reproduce

1. Run the openapi-generator-cli command above.
2. Notice that in the /api or in the /impl folders there isn't any implementation of this end-point /analysis/ProcessingRequest

##### Related issues/PRs

<!-- has a similar issue/PR been reported/opened before? Please do a search in https://github.com/openapitools/openapi-generator/issues?utf8=%E2%9C%93&q=is%3Aissue%20 -->

##### Suggest a fix/enhancement
n.b. The AnalysisApi and AnalysisApiController get generated correctly with the openapi-generator-maven-plugin 3.2.3.

**Comment by etherealjoy** [comment]
I get this when I generate
```
Routes::Post(*router, base + "/analysis/ProcessingRequest", Routes::bind(&FrameApi::image_analysis_handler, this));
```
AnalysisApi.cpp is not generated because there is no tag for it.
The `ProcessingRequest` path is inside the tag `frame`

**Comment by bocse** [comment]
Thank you for the feedback, I made the necessary adjustments and now it works.

However, do consider that in Java or Spring, the specification without the tags creates the end-points, while in the Pistache implementation does not. The two implementation from the same specification should have the same behaviour, for consistency.
