### ISSUE TITLE
[BUG] [typescript-axios] File extensions are not added to export statements in Typescript client

### ISSUE THREAD

**Issue by miniengineer** [OpenAPITools/openapi-generator#13558]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When "consuming" a typescript client generated using `typescript-axios` client generator leads to bunch of ES6 module related errors.

I installed the generated typescript client into a project using the following command (from README)

```
npm install PATH_TO_GENERATED_PACKAGE --save
```

 and imported it into the project like so

```
// index.js

import pkg from 'my-cool-sdk';
const { CoolApi } = pkg;

console.log(CoolApi);
```

And I got the following error

```
export * from "./api";
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:360:18)
```

I was able to fix it by adding the `"type":"module"` into the `package.json`  ( ..I think should be done by default 🤔 )

Then I get bunch of errors from node about not finding the exported module.
Apparently, node doesn't support importing ES6 style modules **without** specifying an extension.

https://nodejs.org/dist/latest-v14.x/docs/api/esm.html#esm_customizing_esm_specifier_resolution_algorithm

And since all generated `.ts` and `.js` files in typescript client don't mention the extension it doesn't work :/ 

```
export * from "./api";

// instead of

export * from "./api.js";
```

Is there a way to make generated files to export modules with specifying the extensions?

##### openapi-generator version

`6.1.1`

##### Generation Details

```
  openapi-generator generate \
    -g typescript-axios
    -o %<dir>s
    -p npmName=my-cool-sdk
    -p npmVersion=1.0.1
    -p apiPackage=api
    -p modelPackage=model
    -p supportsES6=true
    -p withNodeImports=true
    -p withSeparateModelsAndApi=true
```

##### Steps to reproduce

- generate client using `typescript-axios` generator with command from above section ⬆️ 
- import generated `sdk` into a new project in an `index.js` file
-  run `node index.js`

**Comment by miniengineer** [comment]
@nyonson 

Since [Node.js mandates](https://nodejs.org/api/esm.html#esm_mandatory_file_extensions) file extensions for ESM modules (unlike for Common.js modules), ESM style TS clients are not usable at the moment.

Typescript also doesn't have any intention on adding an option which would allow adding file extensions. 🤷‍♀️ 

We found a way to make it work - add `.js` extension to all `import` statements manually in `.ts` files.
TS compiler doesn't remove those `.js` extension and Node.js is happy and can find modules.

There are libraries like [this](https://github.com/Zoltu/typescript-transformer-append-js-extension) for adding the extension,  also found this guide on how to use TS compiler to output both ESM and CommonJs builds.

For now, we only use CommonJs modules as we don't have much time to invest into actually making the ESM modules work.

If are successful in this please don't forget to contribute to upstream 🙂

**Comment by nyonson** [comment]
Thanks @miniengineer !

I think the closest thing I have found to what we want is this PR in another TS codegen: https://github.com/ferdikoomen/openapi-typescript-codegen/pull/1226

**Comment by miniengineer** [comment]
interesting 👀

**Comment by klippx** [comment]
I think https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1182 is the correct issue to solve actually.
