### ISSUE TITLE
[REQ] [Dart] Dart generator contributor discussions

### ISSUE THREAD

**Issue by 0xNF** [OpenAPITools/openapi-generator#13627]
For those of us contributing to the Dart side of things, I'd like to get the principals together in one place to discuss stuff like direction and implementation details.  Wing238 suggested making a #dart channel on the [open api generator slack](https://openapi-generator.slack.com/join/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g) workspace. What do y'all think?

**Comment by 0xNF** [comment]
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

**Comment by ahmednfwela** [comment]
oh I didn't know there was a slack for oas, sure would be great

**Comment by jaumard** [comment]
Sure! I'm on the slack already, a dart channel would be nice :)

**Comment by agilob** [comment]
>Wing238 suggested making a #dart channel on the [open api generator slack](https://openapi-generator.slack.com/join/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g) workspace. What do y'all think?

I was asking for this for months ;)

**Comment by 0xNF** [comment]
Closing this because we got our channel now, and it is nice. Thanks @wing328!
