### ISSUE TITLE
[REQ] [Java] [WebClient] webclient to support application/x-ndjson

### ISSUE THREAD

**Issue by feech** [OpenAPITools/openapi-generator#13673]
### Is your feature request related to a problem?

webflux webclient supports applications/x-ndjson which replaces application/stream+json 
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html#APPLICATION_STREAM_JSON

If openapi specification declares ndjson in the list of possible mediaTypes generated ApiClient ignores it so there is no any chance to select the type from client side, ApiClient selects  another type with lower priority 

## Describe the solution you'd like

proper solution should not ignore ndjson if it present

## Describe alternatives you've considered

the other case is to extend generated ApiClient with proper implementation for `isJsonMime()` as I described in https://github.com/OpenAPITools/openapi-generator/issues/9258#issuecomment-1275384676

## Additional context

it might work only for Java Spring WebFlux Webclient as it supports the MimeType out of box
it definetly will not work for Spring RestTemlate as it does not support streaming

**Comment by Mintas** [comment]
@feech looks like this issue is ready to get closed =)
