### ISSUE TITLE
[BUG] [Python] _headers is not initialized properly for delete functions

### ISSUE THREAD

**Issue by Santobert** [OpenAPITools/openapi-generator#13690]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When deleting objects using the new python generator, an error occurs in `api_client.py update_params_for_auth()`:
```
AttributeError: 'dict' object has no attribute 'add'
```

This error can be traced back to the `paths/{my api}/delete.py` file, where the following line is missing unlike the other files (`get.py`, `put.py`, ...):

```python
        _headers = HTTPHeaderDict()
```

This results in the variable `headers` becoming an empty dict in `api_client.py __call_api()`:
```python
        headers = headers or {}
```

##### openapi-generator version

6.2.0

##### Generation Details

```bash
java -jar openapi-generator-cli-6.2.0.jar generate -i openapi.yaml -g python -o python
```

##### Suggest a fix

Either the missing line needs to be added to `delete.py`:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/endpoint.handlebars#L316

or the headers should be initialized as `HTTPHeaderDict`

**Comment by Santobert** [comment]
Maybe this was fixed by https://github.com/OpenAPITools/openapi-generator/pull/13665
Is there still an underlying issue, that `_headers = HTTPHeaderDict()` is not generated for `delete.py`?

If not, feel free to close this issue.

**Comment by spacether** [comment]
Yes that was fixed in the PR that you linked to. In 6.2.1 or the latest version of the project, this should be fixed.
