### ISSUE TITLE
[BUG][GRADLE PLUGIN] Generate API from a remote URL

### ISSUE THREAD

**Issue by hdani9307** [OpenAPITools/openapi-generator#13726]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If you specify an url for the `inputspec` parameter, the gradle plugin will fail because it is annotated with `@get:InputFile`
##### openapi-generator version

6.2.1

##### Suggest a fix

Remove the `@get:InputFile` and  `@PathSensitive(PathSensitivity.RELATIVE` annotation use a simple `@Input instead`

**Comment by JamesPace-Carta** [comment]
Seems to be in version `5.4.0` as well.
