### ISSUE TITLE
[BUG][GO] Fields in Go client that are required are still marked as references and omitempty

### ISSUE THREAD

**Issue by qshanahan-springhealth** [OpenAPITools/openapi-generator#13735]
```
openapi-generator-cli 6.2.0
  commit : 24f476a
  built  : 2022-09-24T14:07:26Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

For example, fields are generated like this:

```
FieldName *string `json:"FieldName,omitempty"`
```

given a schema like this:

```
properties:
  FieldName:
    type: string
required:
  - FieldName
```

I would expect a type declaration that looks like:

```
FieldName string `json:"FieldName"`
```

The reference makes sense if the field is possibly nil, but if it required by the API, using a pointer type doesn't make sense.

**Comment by qshanahan-springhealth** [comment]
Looking at the source code here:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/model_simple.mustache

it looks like there are checks for `isNullable` and `required` around these two things `*` and `omitempty`. So, it seems this is the expected behavior, at least in the template

**Comment by grokify** [comment]
Agree. Having required and non-nullable properties be pointers seems undesirable.

**Comment by qshanahan-springhealth** [comment]
I'm going to close this, I can no longer reproduce. I'm not sure what changed, I must have missed something in my spec.. maybe I marked the wrong thing as required.. but struct fields are now showing up as pointers, without `omitempty`
