### ISSUE TITLE
html2 generator does not include requestBody

### ISSUE THREAD

**Issue by vishnugr** [OpenAPITools/openapi-generator#1373]
##### Description
I have generated html2 documentation. But index.html does not include requestBody. 
I need to know, how to add the requestBody in the documentation?

##### openapi-generator version
Version 3.3.2

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
info:
  title: service example
  version: 2.0.0
  description: service API's
paths:
  /api/v1/templates:
    post:
      summary: Add a new template
      deprecated: false
      security:
        - Token: []
      tags:
        - Templates
      requestBody:
        description: template to add into the system.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Templates'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Templates'
              example:
                $ref: '#/components/schemas/Templates'
                
components:
  schemas:
    Templates:
      title: Templates
      type: array
      items:
        properties:
          templateName:
            type: string
            description: Template Name
            example: abc
          test:
            type: string
            description: Template Id
            example: test
        required:
          - _id
```

##### Command line used for generation

openapi-generator generate -i swagger/swagger.yaml -g html2 -o docs/

##### Suggest a fix/enhancement
Generator needs to support for the body parameters and response examples to be included in index.html

**Comment by animeshkumar09** [comment]
Adding to the issue specified:-
if the Request body accepts List as a parameter.

Open API shown 
[undefined]

![image](https://user-images.githubusercontent.com/75735646/147088147-fa3c23d2-30c7-4755-92d5-972670b7072e.png)


But if the Request Body accepts an object, it works fine.
