### ISSUE TITLE
[BUG] [java] non-required arrays fail validation

### ISSUE THREAD

**Issue by ashatch** [OpenAPITools/openapi-generator#13774]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Optional array properties in JSON responses fail validation when an optional array property is null:

```java
      // ensure the json data is an array
      if (!jsonObj.get("anotherThing").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `linkedContent` to be an array in the JSON string but got `%s`", jsonObj.get("linkedContent").toString()));
      }
```

A null check is required.

```
java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.isJsonArray()" because the return value of "com.google.gson.JsonObject.get(String)" is null
```

Expected to check null and validate successfully.

##### openapi-generator version

Current `master`  (`0d56ebc`).

##### OpenAPI declaration file content or url

Declaration of an array property:

```yaml
components:
  schemas:
    SomeObject:
      properties:
        something:
          $ref: '#/components/schemas/Something'
        anotherThing:
          items:
            $ref: '#/components/schemas/OtherThingItem'
          type: array
```

##### Suggest a fix

Looks like it was introduced in 3ae37e27a52e349b139f2a581097c781520622f3, `pojo.moustache` line 500. I'll work on a PR.

**Comment by Zomzog** [comment]
@wing328 I think this one can be closed with the merge of #13777
