### ISSUE TITLE
[REQ] Why not split the output file for each API endpoint?

### ISSUE THREAD

**Issue by kerukukku1** [OpenAPITools/openapi-generator#13775]
### Is your feature request related to a problem? Please describe.

Currently, the output is the code generated in the same file (e.g. api.ts).

These have the problem that when the number of API definitions increases, the file becomes tremendously large.
When the file becomes large, other unnecessary code must also be loaded when importing the file, which is very wasteful.

## Describe the solution you'd like

Assign unique identifiers (operationID?) to the yml files to be defined and read them to split the files per endpoint)

**Comment by cyangle** [comment]
I think api operations with the same tag are generated in the same api file.

You should use different tag names for api operations if you want to generate multiple api files.

**Comment by Mintas** [comment]
@kerukukku1 consider using tags, as advised by https://github.com/OpenAPITools/openapi-generator/issues/13775#issuecomment-1287569739
more info:
https://swagger.io/docs/specification/grouping-operations-with-tags/
Example of usage with spring generator flag:
https://openapi-generator.tech/docs/generators/spring/#:~:text=true-,useTags,-use%20tags%20for

**Comment by kerukukku1** [comment]
Thank you all!
I will try to deal with the tag.

**Comment by xtien** [comment]
I use the typescript-axios generator. I found that with the withSeparateModelsAndApi options, I can split the api.ts file in many small files. In vite, I then use the Rollup option 'manualChunks' to chunkify the api into smaller chunks.
