### ISSUE TITLE
[Elm] import 'Data.List_' not used, but causing an error

### ISSUE THREAD

**Issue by Stealthmate** [OpenAPITools/openapi-generator#1378]
##### Description

I'm generating an API from haskell's servant-swagger, where an endpoint returns a type `QueryResponse` which is an object with two array fields.
The output file for this a module `Data.QueryResponse`, which has the import line
```
import Data.List_ as List_ exposing (List_)
```
however, `List_` is not used anywhere in the file. On top of that, Elm doesn't recognize any module like that, and from what I've found there isn't one.

##### openapi-generator version
`3.3.2`, built from source from current `master`

##### OpenAPI declaration file content or url
[gist](https://gist.github.com/Stealthmate/e8756ef17f9cb3267081feff171c467c#file-swagger-json-L341-L365)

##### Command line used for generation
`openapi-generator-cli.sh generate -i "http://localhost:8080/swagger.json" -l elm -o ./api`

##### Steps to reproduce
Just execute the above command on a host that serves the file

##### Related issues/PRs
I tried looking for similar issues, but didn't find anything.

##### Suggest a fix/enhancement
I'm not really sure, but I think just simply not importing List_ would do the trick.

**Comment by Stealthmate** [comment]
I noticed some other problems.

- The API returns `[[string]]`, however the template generated is for `List String` (the `data` field)
- The encoder/decoder functions use `String.encoder` / `String.decoder` respectively, however those don't exist.

Here's a [gist](https://gist.github.com/Stealthmate/afa501109255f4b700930bcdb524255f) of the code as well.

I think nested list generation may not be working properly. I'll try to do some more research during the week if I have time.

**Comment by trenneman** [comment]
Thanks for your report @Stealthmate. `List_` is indeed a bug as nested Lists/Dicts were not yet supported. See the PR for a fix for both.

**Comment by Stealthmate** [comment]
@trenneman Thank you! I'll take a look!
