### ISSUE TITLE
[ruby] Question about Faraday support

### ISSUE THREAD

**Issue by jethrodaniel** [OpenAPITools/openapi-generator#13811]
Hi, in the [docs](https://github.com/OpenAPITools/openapi-generator/blob/227f583a8162d1d2bdfecaecd3c01a4a93c2df34/docs/generators/ruby.md?plain=1#L36), it's mentioned that the `Faraday` library only has beta-support.

What's the current status of the `faraday` library option for Ruby clients - is it still beta? And if so, what things are remaining before it can be considered fully supported?

Thanks!

**Comment by wing328** [comment]
good question. i've filed https://github.com/OpenAPITools/openapi-generator/pull/13823 to remove "Beta" from t.
