### ISSUE TITLE
[REQ] Only create definition classes

### ISSUE THREAD

**Issue by ploef** [OpenAPITools/openapi-generator#13830]
I'm using the generator because I need C# classes created from the definitions. Also creating code for the client is not necessary. It would be great if it would be possible to make this configurable.

**Comment by Zomzog** [comment]
I've created a PR, but as a workaround, you can generate only models by naming the.
For example with the CLI
`openapi-generator-cli generate -i api.yml -g csharp -o pony/csharp --global-property models=",Pony,Color,PonySmall"`

**Comment by ploef** [comment]
Hi, thanks for the quick response!
Using the following the generator (csharp-netcore) is indeed creating only models now:

--global-property=models,modelDocs=false,modelTests=false,apiTests=false

Unfortunately, it looks like the models have a reference to the client because they also contain converter classes that seem to use the client:

``
            Utf8JsonReader guidReader = reader;
            bool guidDeserialized = Client.ClientUtils.TryDeserialize<Guid>(ref guidReader, options, out Guid? guid);
``

Because only the models are generated, the "client" does not exist.

**Comment by ploef** [comment]
That seems to work, thanks for the tip!

**Comment by wing328** [comment]
Another way (or workaround) is to manually delete files that are not needed post-code generation.
