### ISSUE TITLE
add scoped package support in package name

### ISSUE THREAD

**Issue by Ohadbasan** [OpenAPITools/openapi-generator#1386]
##### Description

openapi javascript generator generates a package with the package name as written in the title attribute in the info object.
a javascript package can be scoped.
for example
npm install @organization/my_library
require('my_library').

##### openapi-generator version

3.3.2

##### Command line used for generation

openapi-generator generate -i ./openapi.yaml -g javascript

##### Suggest a fix/enhancement

I suggest adding a scope (or namespace) attribute to the info object that will be used under the "name" attribute in the package.json along with the package title.

**Comment by wing328** [comment]
What about customizing the output with `projectName`?

Ref: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/javascript.md

**Comment by Ohadbasan** [comment]
Exactly what I needed. thank you

there were no generator specific links from the openapi-generator README.md so I could not find them. maybe it's worth considering adding them.
I also don't see where the "config options" feature is documented (how to use that)

thanks!
