### ISSUE TITLE
[REQ][csharp-netcore] Support .NET 6 `DateOnly` type for `date`

### ISSUE THREAD

**Issue by AndreasHae** [OpenAPITools/openapi-generator#13877]
### Is your feature request related to a problem? Please describe.
I'm consuming an API which expects me to provide query parameters of type `date` with the format `yyyy-MM-dd` (without the time portion). Due to the `csharp-netcore` generator generating `DateTime` out of all `date` as well as `datetime` values, it is incorrectly serialized with the time portion included.

The relevant query parameter:
```json
{
    "in": "query",
    "name": "date_to",
    "schema": {
        "type": "string",
        "format": "date"
    },
    "examples": {
        "2022-10-29": {
            "value": "2022-10-29",
            "summary": "2022-10-29",
            "description": "ISO 8601 format date"
        }
    }
}
```

## Describe the solution you'd like
The nicest solution would be to use the new .NET 6 `DateOnly` type when generating values of type `date`. Apart from it being more obvious what the expected value is, one could easily specify it to be generated only as `yyyy-MM-dd` by extending the type pattern match in `ClientUtils.cs`.

## Describe alternatives you've considered
For my serialization problem I'm stuck with adding a custom date format to the relevant API via `GlobalConfiguration` for now, but that's really hacky and only works as long as I only have to use either `date` or `datetime` in the client and not both. Otherwise I have to manually patch the client up but that's something I want to avoid at all cost in case I have to regenerate it due to API updates.

## Additional context
This issue kind of explains 2 problems at once:
1. The generator incorrectly serializing query parameters of type `date` (which is a bug)
2. Generating `date` values as `DateOnly` (which is a feature request)

I figured the former can easily be solved by adding the latter, but older .NET versions would still be affected. Let me know if I should split them up.

**Comment by meigetsu** [comment]
Hello ! I would love to have it in aspnetcore generator too !

**Comment by Anakael** [comment]
I think I can try to implement this.

**Comment by Anakael** [comment]
I've started to work on thin.
