### ISSUE TITLE
[BUG][Python] multipart/form-data Content-Disposition missing

### ISSUE THREAD

**Issue by Santobert** [OpenAPITools/openapi-generator#13887]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When uploading a file with content type `multipart/form-data` the Content-Disposition part is missing.

Expected:

```
-----------------------------31264598498482450412031672804
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: text/plain

Hello World
-----------------------------31264598498482450412031672804--
```

Actual:

```
--3332f21c28498ce486e94b8ec5a48291
Content-Type: application/octet-stream

Hello World
--3332f21c28498ce486e94b8ec5a48291--
```

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

```json
{
    "openapi": "3.0.1",
    "info": {},
    "servers": [],
    "security": [],
    "paths": {
        ...,
        "/files/{fileContainerId}/payload": {
            "post": {
                "tags": [
                    "file"
                ],
                "description": "Upload a new file",
                "operationId": "createFile",
                "parameters": [
                    {
                        "name": "fileContainerId",
                        "in": "path",
                        "required": true,
                        "schema": {
                            "type": "integer",
                            "format": "int64"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "multipart/form-data": {
                            "schema": {
                                "required": [
                                    "file"
                                ],
                                "type": "object",
                                "properties": {
                                    "file": {
                                        "type": "string",
                                        "description": "File which you want to upload",
                                        "format": "binary"
                                    }
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "created"
                    },
                    "404": {
                        "description": "not found"
                    }
                }
            }
        },
        ...
    },
    "components": {...}
}
```

##### Generation Details

```
... generate -i target/openapi/openapi.json -g python -o clients/python
```

**Comment by spacether** [comment]
Is the upload working?
We have a test of this here:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L440

What is your code that you are using to invoke the endpoint? It looks like you are passing bytes (which should also work)

**Comment by Santobert** [comment]
I've used the automatically generated documentation as a reference:

```python
    file = file_api.create_file(
        body={"file": open("./file1.txt", "rb")},
        path_params={"fileContainerId": 123},
    )
```

The upload is not really working, since the backend expects `Content-Disposition` to be set. The old python client (python-legacy) does this and works as expected. 

If you look at the expected and the actual output from above, you can see that the content of the test file is embedded in the message body (both times it is `Hello World`).

**Comment by Santobert** [comment]
It seems, the spec also expects `Content-Disposition` to be set:
> In a multipart/form-data body, the HTTP Content-Disposition general header is a header that must be used on each subpart of a multipart body to give information about the field it applies to. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

**Comment by spacether** [comment]
Heads up, I am working on a fix in https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/67
Once I fix it there I will do a second PR fixing it here, which will be available in the next release here.

**Comment by spacether** [comment]
Fix is merged in https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/67
This repo will get the fix in the future.

**Comment by spacether** [comment]
@Santobert this repo has the fix now
