### ISSUE TITLE
[BUG][JAVA] Bug generating @NotNull when useBeanValidation is set to false

### ISSUE THREAD

**Issue by codarsan** [OpenAPITools/openapi-generator#13885]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We encountered an issue with the spring generator (we use open api gradle plugin)
When we try to upgrade to 6.2.1, the generator seems to generate @NotNull annotations from javax Validation even though we have the config useBeanValidation set to false.

##### openapi-generator version

It is a regression in 6.2.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Management
  version: 1.0.0
paths:
  /service:
    get:
      operationId: save
      responses:
        200:
          description: done
          content:
            application/json;charset=utf-8:
              schema:
                type: string
components:
  schemas:
    Request:
      type: object
      required:
        - 'requiredParam'
        - 'requiredParam2'
      properties:
        requiredParam:
          type: string
        requiredParam2:
          type: string
        optionalParam:
          type: string
```

##### Generation Details

- org.openapi.generator version "6.2.1"
- spring generator
- with configOptions =  [
            openApiNullable  : "false",
            interfaceOnly    : "true",
            useBeanValidation: "false",
            dateLibrary      : "java8"
    ]

##### Steps to reproduce

Create a gradle project with configuration
```
task generateOpenApi(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "spring"
    inputSpec = "$rootDir/src/main/resources/api/server/management.yml"
    outputDir = "$buildDir/generated/openApi"
    apiPackage = "com.application.api"
    modelPackage = "com.application.model"
    typeMappings = [
            OffsetDateTime: 'java.time.LocalDateTime'
    ]
    configOptions = [
            openApiNullable  : "false",
            interfaceOnly    : "true",
            useBeanValidation: "false",
            dateLibrary      : "java8"
    ]
    generateApiTests = false
    generateModelTests = false
}
```
Open the generated file Request.java

##### Related issues/PRs

I did not find any.

##### Observation
Even though the @NotNull annotations are generated, I noticed that the imports are missing so the generated code doesn't compile.

**Comment by rd-henning-ellerweg** [comment]
I am having the same problem. I digged a little and I think it is related to this code change
https://github.com/OpenAPITools/openapi-generator/commit/0060dfd19501e489d892b87e48f29188e62034ed#diff-1b17968383667361ebeac290a077a68241afd8eac3b3a298bce6a9d36cd659d4

**Comment by Mintas** [comment]
> I am having the same problem. I digged a little and I think it is related to this code change [0060dfd#diff-1b17968383667361ebeac290a077a68241afd8eac3b3a298bce6a9d36cd659d4](https://github.com/OpenAPITools/openapi-generator/commit/0060dfd19501e489d892b87e48f29188e62034ed#diff-1b17968383667361ebeac290a077a68241afd8eac3b3a298bce6a9d36cd659d4)

I have submitted PR solving this problem. If you have no time to wait for next release, feel free to fix with templates customization

**Comment by codarsan** [comment]
> I have submitted PR solving this problem. If you have no time to wait for next release, feel free to fix with templates customization
Thanks good to know, i'll wait for the next relase :)
