### ISSUE TITLE
[BUG][Python] Attribute-style access fails for model properties 

### ISSUE THREAD

**Issue by Stealthmate** [OpenAPITools/openapi-generator#13896]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

See the spec below for the model definitions. I was under the impression the following code is legal, but it raises an error:

```python
from openapi_client.models import Foo
f = Foo(bar='bar')
f.bar # this raises an AttributeError
f['bar'] # this works fine
```

##### openapi-generator version

v6.2.1, also tested on master

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: APMS
  version: '0.1'
paths:
  /foo:
    post:
      tags:
        - test
      summary: Test
      operationId: create_foo
      responses:
        '200':
          description: ok
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          type: string
          example: foobar
```

##### Generation Details

```sh
docker run -v $PWD/spec.yaml:/spec.yaml -v $PWD/client:/client -it openapitools/openapi-generator-cli:latest generate -i /spec.yaml -g python -o /client
```

##### Steps to reproduce

Generate the spec above

##### Related issues/PRs

Tried, but couldn't find anything.

##### Suggest a fix

After looking at the generated code for a while, I found a solution. In https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/schemas.handlebars#L1721 , changing

```python
if name not in self.__class__.__annotations__:
```
to
```python
if name not in self.MetaOapg.properties.__annotations__:
```

seems to resolve the problem. However, since there's a lot of `__new__` magic in the generated code, I'm not sure if this is a real fix.

**Comment by spacether** [comment]
This is by design, did you read the migration guide in the readme? Required properties with valid python names are the only ones that are accessible with dot access.

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/README.md#changes

> Property access on AnyType(type unset) or object(dict) schemas

    Only required keys with valid python names are properties like .someProp and have type hints
    All optional keys may not exist, so properties are not defined for them
    One can access optional values with dict_instance['optionalProp'] and KeyError will be raised if it does not exist
    Use get_item_oapg if you need a way to always get a value whether or not the key exists
        If the key does not exist, schemas.unset is returned from calling dict_instance.get_item_oapg('optionalProp')
        All required and optional keys have type hints for this method, and @typing.overload is used
        A type hint is also generated for additionalProperties accessed using this method
    So you will need to update you code to use some_instance['optionalProp'] to access optional property and additionalProperty values

**Comment by Stealthmate** [comment]
Oh I see, I didn't look at that part of the docs, so thanks for linking it. I think you can consider this issue resolved now.

**Comment by ashuk203** [comment]
I am not sure if this is related, but any time I make an API call, the `response.body` field always has the class `DynamicSchema`. Is there any way to make the call return the class corresponding to the OpenAPI schema listed for that response body? 

For example, the below code always prints out a class of the type `DynamicSchema`
```python
    try:
        api_response = api_instance.ping(skip_deserialization=False)
        print(type(api_response.body))     # Outputs '<class 'openapi_client.schemas.DynamicSchema'>'
    except circle.ApiException as e:
        ...
```

However, there is a dedicated class for this endpoint method's response body at `model/ping_response.py` folder. Would there be any way to make it return an instance of that class instead?

**Comment by spacether** [comment]
@ashuk203 this is by design.
Your instance is an instance of type DynamicSchema which is a class that is built on the fly of all validated schemas including the response body schema. Is it is an instance of that class.
You can see examples of this here:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L59

**Comment by ashuk203** [comment]
Oh, okay. Thank you!!

**Comment by robswc** [comment]
> @ashuk203 this is by design. It already does what you are asking for. Your instance is an instance of type DynamicSchema which is a class that is built on the fly of all validated schemas including the response body schema. Is it is an instance of that spec defined response body class. You can see examples of this here: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L59
> 
> This is described in [the migration guide](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/openapi3/client/petstore/python#changes) `All validated data is instantiated in an instance that subclasses all validated Schema classes and Decimal/str/tuple/frozendict/NoneClass/BoolClass/bytes/io.FileIO`

I'm probably misunderstanding something, just a quick question though.

If I have a "Person" model, is there anyway to do:

```
# get person
p = r.body
p.name
```

vs 

`p['name']`

Thanks!

**Comment by spacether** [comment]
Dot referenced properties only exist when:
- the property is required
- the property's key is a valid python variable name

When those two conditions are met, a dot referenced property is defined. Otherwise one must access the value by the key name. Per item 7 in the readme:
https://github.com/OpenAPITools/openapi-generator/tree/v6.6.0/samples/openapi3/client/petstore/python#changes

**Comment by robswc** [comment]
> Dot referenced properties only exist when:
> 
> * the property is required
> * the property's key is a valid python variable name
> 
> When those two conditions are met, a dot referenced property is defined. Otherwise one must access the value by the key name. Per item 7 in the readme: https://github.com/OpenAPITools/openapi-generator/tree/v6.6.0/samples/openapi3/client/petstore/python#changes

Ah, thanks a ton!  I've made them required and it works perfectly!

**Comment by robswc** [comment]
Actually, I may have spoke too soon.  Intellisense picks it up now and it exists for the class, however when I try to reference it I get:

`DynamicSchema({'name': 'test'}) has no attribute 'name'`

`p['name']` works fine though.

**Comment by spacether** [comment]
When you made it required is it also defined in properties?

**Comment by robswc** [comment]
I can paste in a spec tomorrow, as I will have to clean up my example a bit, but here is a snippet of the generated class:

```python
class Signal(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        required = {
            "timestamp",
        }
        
        class properties:
            timestamp = schemas.IntSchema
            __annotations__ = {
                "timestamp": timestamp,
            }
    
    timestamp: MetaOapg.properties.timestamp
```

Doing `s.timestmap` shows in intellisense, but errors when running.  `s['timestamp'] seems to work no problem though.

I'll try to clean up a sample spec though.

When I do `dir(s)` it doesn't show `timestamp` as a property. (not sure if it's supposed to)

Thanks for the help again!

**Comment by spacether** [comment]
timestamp will not show up as a property via dir
DictSchema contains DictBase which has the method `__getattr__` [which is used for instance.name access](https://github.com/OpenAPITools/openapi-generator/blob/v6.6.0/samples/openapi3/client/petstore/python/petstore_api/schemas.py#L1736)
An exception is thrown if the key is not in the class's annotations.
We need to know
- what classes are in instance.__class__.__mro__
- the value of instance.__class__.__annotations__

**Comment by spacether** [comment]
I will fix it in my new repo for the python generator and include it in a release. One needs to update the template files that generate the python code to fix it. Please keep an eye on https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/171 to see the fix land

**Comment by robswc** [comment]
> I will fix it in my new repo for the python generator and include it in a release. One needs to update the template files that generate the python code to fix it. Please keep an eye on [openapi-json-schema-tools/openapi-json-schema-generator#171](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/issues/171) to see the fix land

Ah ok, awesome, thanks!  I wish I was familiar enough with the project to help.  

I can access by key name in the mean time, no problem :+1:

**Comment by spacether** [comment]
[2.0.2 was released with the fix](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/releases/tag/2.0.2)
