### ISSUE TITLE
[BUG][PYTHON] Could not generate model in python but typescript-node suceeds

### ISSUE THREAD

**Issue by kartikye** [OpenAPITools/openapi-generator#13948]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Python generator crashes on a openapi spec while typescript-node does not

##### openapi-generator version

6.2.0

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/Send-Dots/dots-docs-v2/master/docs/v2.yaml

##### Generation Details

Default everything:

openapi-generator-cli generate -g python -i docs/v2.yaml -o python

##### Steps to reproduce

Ran the above command

##### Related issues/PRs

[](https://github.com/OpenAPITools/openapi-generator/issues/11763)

**Comment by spacether** [comment]
Which component schema is causing the problem?
What is the logged result of the generate command?

**Comment by spacether** [comment]
Also, openapi 3.1.0 generation is not yet supported in openapi-generator. Please use v3.0.3 specs until that version of the openapi spec is supported.

**Comment by spacether** [comment]
I am unable to reproduce this issue.
Generation succeeded with v6.2.0 and v6.2.1

`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.1 generate     -i /local/v2.yaml     -g python     -o /local/python_v2/`

`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.2.0 generate     -i /local/v2.yaml     -g python     -o /local/python_v2/`

If you are still experiencing this issue please re-open the issue and provide:
- terminal output of your openapi-generator-cli version
- the failure log of running generation
