### ISSUE TITLE
[BUG][GO] missing imports for "allOf" schemas

### ISSUE THREAD

**Issue by philip-ellis-sp** [OpenAPITools/openapi-generator#13959]
#### Bug Report Checklist

- [X ] Have you provided a full/minimal spec to reproduce the issue?
- [X ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X ] Have you searched for related issues/PRs?
- [X ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When building the Go SDK on the latest version of the generator for GO, schemas that are defined with "allOf" are missing any imports defined in references. I believe that the change here: https://github.com/OpenAPITools/openapi-generator/pull/13143 broke this functionality as versions prior to 6.1.0 work fine

##### openapi-generator version

This occurs on the latest stable version 6.2.1 and was broken in 6.1.0

##### OpenAPI declaration file content or url

Initial definition
```yaml
openapi: 3.0.1
info:
  title: Go bug API
  version: 3.0.0
servers:
  - url: https://tenant.api.test.com
    description: This is the production API server.

tags:
  - name: Test
paths:
  /test:
    get:
      operationId: getLifecycleState
      summary: Retrieves Lifecycle State
      responses:
        '200':
          description: The api that causes missing imports
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './test-inner.yaml'
                  - type: object
                    properties:
                      enabled:
                        type: boolean
                        example: true
                        description: enabled flag
```
All of file:
```yaml
allOf:
  - $ref: './test-inner.yaml'
  - type: object
    properties:
      enabled:
        type: boolean
        example: true
        description: enabled flag
```

##### Generation Details

Generated file will be missing the time import:

```go
package sdk

import (
	"encoding/json"
       // there is a missing time import here!!!!
)

// GetLifecycleState200Response struct for GetLifecycleState200Response
type GetLifecycleState200Response struct {
	// Creation date of the Object
	Created *time.Time `json:"created,omitempty"`
	// enabled flag
	Enabled *bool `json:"enabled,omitempty"`
	AdditionalProperties map[string]interface{}
}
```

##### Steps to reproduce

Generate the SDK using the command:
```java -jar openapi-generator-cli-6-2-1.jar generate -i apis/test.yaml -g go -o sdk-output```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/13143

##### Suggest a fix
I believe the code here: modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java needs to be adjusted to retain the original logic for populating imports.

**Comment by OJFord** [comment]
This does not just affect Go, it's also an issue in python-flask (presumably then any language) when using openapi: 3.1.0 & necessarily generator v6.2

It seems to miss all that use `allOf` rather than having an explicit/top-level `type`. Adding a `type` to the `allOf` array does not help.

**Comment by prochac** [comment]
https://github.com/OpenAPITools/openapi-generator/issues/14121#issuecomment-1370762071
> So suggestion is to add custom template with `type _ = time.Time` present?

@wtrocki only potential downside is bigger binary if the `time` isn't used anywhere in the codebase. While we stick to std lib with this practise, there is low risk. Anyway, it's quite cheap solution, but IMO better than broken output from SDK now.

**Comment by wtrocki** [comment]
Fix have been made in https://github.com/OpenAPITools/openapi-generator/pull/14459
