### ISSUE TITLE
[BUG] [Python] Generated files with syntax errors if spec contains 204 response

### ISSUE THREAD

**Issue by Syuparn** [OpenAPITools/openapi-generator#13971]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated `python` codes have syntax errors when a spec file contains `204 No Content` response.
This is caused by type hint `typing.Union` without any type arguments.

```python
@dataclass
class ApiResponseFor204(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: typing.Union[ # syntax error
    ]
    headers: schemas.Unset = schemas.unset
```

(Note: `typing.Union` requires one or more type arguments https://docs.python.org/3/library/typing.html#typing.Union)

##### openapi-generator version

v6.2.1 (and master branch)

##### OpenAPI declaration file content or url

Gist link: https://gist.githubusercontent.com/Syuparn/0a9d22599b087f61ddfd5beb7bcbc26a/raw/62d003fc54d8df3e97251d6e33103b89a738fd7c/sample.yaml

This is originated from  https://swagger.io/docs/specification/2-0/describing-responses/ `Empty Response Body` sample.

##### Steps to reproduce

```bash
$ docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
     -i https://gist.githubusercontent.com/Syuparn/0a9d22599b087f61ddfd5beb7bcbc26a/raw/62d003fc54d8df3e97251d6e33103b89a738fd7c/sample.yaml \
     -g python \
     -o /local/out/python
```

`out/python/openapi_client/paths/report/delete.py` has the syntax errors written above.

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/12265
- https://github.com/OpenAPITools/openapi-generator/pull/12287

##### Suggest a fix

This type hint should be `schemas.Unset`. Template is intended to render `schemas.Unset` type hint when a body (`content`) is empty.

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/endpoint.handlebars#L164

However, this is unexpectedly treated as non-empty value because `content`, which is `LinkedHashMap`, is always treated as truthy by conditional blocks `{{#if}}`, `{{#or}}`, and, `{{#and}}`.

- definition of `content` key https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenResponse.java#L92
- handlebars function definition (used for `{{#if}}`, `{{#or}}`, `{{#and}}` blocks):  https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java#L200

To fix the issue, we need another way to check whether `content` is empty (adding boolean flag `hasContent` to `CodegenResponse`  class for example).

**Comment by Syuparn** [comment]
@spacether 
When I use v3.0.0 spec, generator works expectedly and generated codes have right type hints.

```python
@dataclass
class ApiResponseFor204(api_client.ApiResponse):
    response: urllib3.HTTPResponse
    body: schemas.Unset = schemas.unset
    headers: schemas.Unset = schemas.unset
```

https://gist.githubusercontent.com/Syuparn/0a9d22599b087f61ddfd5beb7bcbc26a/raw/e74c07e2c76f2b23e482ecb36a7582d91b8e6d70/sample-3.0.yaml

Should we fix this for swagger v2 spec? If so, I will make a PR.

**Comment by spacether** [comment]
You should not be able to generate a python client from a v2 spec per this test:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/python/PythonClientTest.java#L63
Can you please debug how generation is succeeding when the spec version is < 3?
That test throws an error for specs under version 3.

**Comment by Syuparn** [comment]
@spacether
> Can you please debug how generation is succeeding when the spec version is < 3?
> That test throws an error for specs under version 3.

The generator treats swagger 2.0 as OpenAPI 3.0.1 unintendedly.

This test passes but annotation parameter `expectedExceptions` seems to be missing.
If the parameter is specified, the test fails, which means no exceptions are raised.

https://testng.org/doc/documentation-main.html#annotations

```java
    @Test(expectedExceptions = RuntimeException.class) // edited
    public void testSpecWithTooLowVersionThrowsException() throws RuntimeException {
        final OpenAPI openAPI = TestUtils.parseSpec("src/test/resources/2_0/petstore.yaml");
        final PythonClientCodegen codegen = new PythonClientCodegen();
        codegen.preprocessOpenAPI(openAPI);
    }
```

```
org.testng.TestException: 
Method PythonClientTest.testSpecWithTooLowVersionThrowsException()[pri:0, instance:org.openapitools.codegen.python.PythonClientTest@d706f19] should have thrown an exception of type class java.lang.RuntimeException

	at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
	at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:853)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:714)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
```

In the test case, `openAPI` object has  spec vesion `"3.0.1"` in field `openapi`, even though the spec specifies `swagger: '2.0'`.

(:memo: Debug result in [PythonClientCodegen#preprocessOpenAPI](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java#L2759))

![image](https://user-images.githubusercontent.com/36665200/201342658-5882e874-35cf-4f38-abc6-a25143131527.png)

**Comment by spacether** [comment]
Hmm it is possible that the latest parser version is no longer providing the original spec version.

**Comment by spacether** [comment]
@Syuparn all fixed
