### ISSUE TITLE
[REQ][SpringCodegen]: Consider compatible with springdoc-openapi-starter-common-2.0.0

### ISSUE THREAD

**Issue by developerworks** [OpenAPITools/openapi-generator#14077]
https://github.com/OpenAPITools/openapi-generator/blob/903ff0ba47b7ecae6f27fa61e86e33a72b68d8e0/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L488

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/725190/203018146-3b09a5c1-7bfa-46cf-aa1d-5a3584afdbed.png">

The `org.springdoc.api.annotations.ParameterObject class was moved to `org.springdoc.core.annotations.ParameterObject`

**Comment by developerworks** [comment]
#### Fix the issue temporarily in **macOS**

```shell
sed -i '' \
    's/org\.springdoc\.api\.annotations\.ParameterObject/org\.springdoc\.core\.annotations\.ParameterObject/g' \
    ./spring-server/src/main/java/com/demo/api/{UsersApiController,UsersApi}.java
```

You should replace above file path with your local file path

**Comment by gkgeorgiev** [comment]
> https://github.com/OpenAPITools/openapi-generator/blob/903ff0ba47b7ecae6f27fa61e86e33a72b68d8e0/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L488
> 
> <img alt="image" width="1078" src="https://user-images.githubusercontent.com/725190/203018146-3b09a5c1-7bfa-46cf-aa1d-5a3584afdbed.png">
> 
> The `org.springdoc.api.annotations.ParameterObject class was moved to `org.springdoc.core.annotations.ParameterObject`

Thx for the analysis ... saved me some time :)
