### ISSUE TITLE
[PHP] Username checks null  default value is empty string

### ISSUE THREAD

**Issue by phiamo** [OpenAPITools/openapi-generator#1408]
The php generator checks username and password for null, but default values are empty string ''

https://github.com/OpenAPITools/openapi-generator/blob/1522855915f941826879d468be0b65f798f732ca/modules/openapi-generator/src/main/resources/php/api.mustache#L510
https://github.com/OpenAPITools/openapi-generator/blob/1522855915f941826879d468be0b65f798f732ca/modules/openapi-generator/src/main/resources/php/Configuration.mustache#L60

When using e.g. an API which supports Bearer and http auth, the bearer Auth header gets replaced by:
Basic Og==

**Comment by wing328** [comment]
@phiamo thanks for reporting the issue. May I know if you've time to contribute a fix to the issue?

**Comment by phiamo** [comment]
yes, sure, i am just not sure if it would be better to change default values from '' to null, or checking for empty instead would be better? any suggestions?

**Comment by wing328** [comment]
I suggest checking for empty as if I remember correctly, that's the approach taken by other clients (e.g. ruby)

To be clear, both username and password must be empty in that condition. (there're use cases in which an empty password is sent to the server)

**Comment by phiamo** [comment]
Sure, so we leave default values empty strings and check for emptyness as
condition...

Am Di., 13. Nov. 2018, 10:29 hat William Cheng <notifications@github.com>
geschrieben:

**Comment by wing328** [comment]
Right. Ping me in https://gitter.im if you need any help on the PR. Thanks in advance.

**Comment by wing328** [comment]
Closed via #1892 

@phiamo please give the latest a try when you've time.

**Comment by apprme** [comment]
Shouldn't this be also applied to the `accessToken`? 

Its default value is empty string as well; when the endpoint supports both bearer and basic auth, first `Authorization: Basic ...` is added, but then we overwrite it with `Authorization: Bearer ` with empty bearer token.

**Comment by wing328** [comment]
@apprme right, please kindly submit a PR to fix the accessToken as well if you've time. Thank you.
