### ISSUE TITLE
[BUG] php-symfony enum generation generates empty class

### ISSUE THREAD

**Issue by renaud-twd** [OpenAPITools/openapi-generator#14115]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

when declaring an `enum` in OAS specification file, php-symfony generator generates an empty DTO class instead of a usable implementation.

I proposed a fix in the following PR: https://github.com/OpenAPITools/openapi-generator/pull/14105

##### openapi-generator version

Version 6.2.1

##### OpenAPI declaration file content or url

Generate "php-symfony" code with gradle plugin v6.2.1

Here is the generated code for StatusDto:
```php
...
class StatusDto 
{
        /**
     * Constructor
     * @param array|null $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
    }
}
```

##### Steps to reproduce

Generate the code

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/pull/14105

**Comment by paulmyer** [comment]
Please fix.  Enums are useless right now

**Comment by renaud-twd** [comment]
> Please fix. Enums are useless right now

@paulmyer can you please detail your statement (rational, recommended usage, etc...) ?

By the way, I close this issue as the PR has been merge few times ago.

**Comment by renaud-twd** [comment]
@paulmyer thanks for your feedback.
If I understand well, you say that there's no added value using those custom made enums.
But still, even if it is a workaround, the referenced PR make the generated code usable (which wasn't the case before).

Regarding the real fix, I think the generator should use `enum`s introduced in PHP 8.1:
https://php.watch/versions/8.1/enums

This could be some new enhancement request. :)
