### ISSUE TITLE
[BUG][JAVA][KOTLIN] dependency scope of slf4j-simple should be 'runtime'

### ISSUE THREAD

**Issue by harel-biton** [OpenAPITools/openapi-generator#14113]
### Description

From [slf4j site](https://www.slf4j.org/codes.html#multiple_bindings):
> Embedded components such as libraries or frameworks should not declare a dependency on any SLF4J binding but only depend on slf4j-api. When a library declares a compile-time dependency on a SLF4J binding, it imposes that binding on the end-user, thus negating SLF4J's purpose.

The problem is in the following lines from `modules/openapi-generator/pom.xml`:
```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
```
The `scope` of the dependency is not defined and therefore it is `compile` by default. It cause any application that depends on `openapi-generator` to transitively pull `slf4j-simple` also, which is wrong. The purpose of slf4j is that libraries will be depended on `slf4j-api` only (in `compile` scope, and in any slf4j binding in `runtime` scope) and the application developers will choose any logging FW they want to use.
When the application developers choses their own logging FW to their application and `slf4j-simple` is pulled transitively from `openapi-generator`, it causes multiple slf4j bindings to be added to the class path and the following warning is printed:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/**/org.slf4j/slf4j-simple/1.7.36/**/slf4j-simple-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/**/ch.qos.logback/logback-classic/**/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```
And in order to control the actual binding at runtime, the application developer must exclude one of the bindings. In this case `slf4j-simple` should be excluded.

### openapi-generator version
6.2.0 (and probably 6.2.1 also)

### Steps to reproduce
Just open a project and add a dependency on `openapi-generator` and `ch.qos.logback:logback-classic:1.2.11` (an example of logging FW, different from `slf4j-simple`). Initialize an slf4j logger in the main function.

An example of the dependencies definition (gradle):
```
dependencies {
    implementation("ch.qos.logback:logback-classic:1.2.11")
    implementation("org.openapitools:openapi-generator:6.2.0")
}
``` 
An example of the main function (kotlin):
```
fun main() {
  LoggerFactory.getLogger("Logger")
}
```

### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/12375 (same issue, but I hope I described the problem better)

### Suggest a fix
just add `<scope>runtime</scope>` to the dependency definition. I.e:
```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
            <scope>runtime</scope>
        </dependency>
```

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix when you've time? Thank you
