### ISSUE TITLE
[BUG] OAuth dependency added by default

### ISSUE THREAD

**Issue by wtrocki** [OpenAPITools/openapi-generator#14112]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating any OpenAPI with no security scheme openapi generator golang adds OAuth specific dependencies and code

##### openapi-generator version

v6.2.1

##### OpenAPI declaration file content or url

Example for dependency:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/go/go.mod#L11

##### Steps to reproduce

Bug is visible in current example projects in the repository;

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/go/

##### Related issues/PRs

 https://github.com/OpenAPITools/openapi-generator/issues/5018

##### Suggest a fix

I think templates should detect if security scheme is present and add dependencies and other oauth specific code only if security scheme contains it

**Comment by wing328** [comment]
@wtrocki thanks for reporting the issue. I think we can address it using `{{#hasOAuthMethods}} ... {{/hasOAuthMethods}}`.

I wonder if you've time to file a PR for that.

**Comment by wtrocki** [comment]
Happy to add that and create follow up PR.
