### ISSUE TITLE
[BUG][Go] Missing time.Time import when properties are in AllOf relationship 

### ISSUE THREAD

**Issue by wtrocki** [OpenAPITools/openapi-generator#14121]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I have noticed regression between 6.2.0 and 6.2.1 where `time.Time` import is missing when properties are part of allOf
section. For given:

Generated code will miss time.Time import for any DataTime property.

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: test
paths:
  "/api/test":
    get:
      description: "Test"
      operationId: "getTest"
      responses:
        "200":
          description: Test
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TestView"

components:
  schemas:
    TestView:
      type: object
      allOf:
        - type: object
          properties:
            authorizedDate:
              type: string
              format: date-time
```

##### Steps to reproduce

1. `openapi-generator-cli generate -o ./test -i example.yaml -g go
2. Open model_test_view.go 
3. Notice import is missing

**Comment by wtrocki** [comment]
Will work on this!

**Comment by wtrocki** [comment]
it will be good to add this issue to the milestone as it is was regression in the recent changes.

**Comment by prochac** [comment]
Could be static import of `time`. Yes, it will cause error if the time.Time isn't used, but it can be easily fixed with underscore
```
import (
    "time"
)

type _ = time.Time
```
https://go.dev/play/p/ALoU8f53vsn

**Comment by wtrocki** [comment]
So suggestion is to add custom template with `type _ = time.Time` present?

**Comment by wtrocki** [comment]
Duplicate of https://github.com/OpenAPITools/openapi-generator/issues/13959
