### ISSUE TITLE
Disable @Controller generation

### ISSUE THREAD

**Issue by vijayrcse** [OpenAPITools/openapi-generator#14122]
##### Description

I am using openapi-generator-maven-plugin version 5.4.0. I would like to know how to disable @Controller class generation.
I would like to have my own @Controller class instead of autogenerated. please advise

##### openapi-generator version

5.4.0

**Comment by jpfinne** [comment]
There are plenty of options. See https://openapi-generator.tech/docs/generators/spring/

I m not sure which one is relevant for an old version of the generator. I prefer to stick with the latest version, even if you can encounter regressions.

I use interfaceOnly=true and useSpringController=false . I like delegatePattern=true for a cleaner generated code.

Then you create your own controller that implements the generated interface and you @override the methods with the implementation.
Don't forget to add @RestController and optionally @RequestMapping

**Comment by vijayrcse** [comment]
thank you @jpfinne . This worked for me.
