### ISSUE TITLE
[python] Nullable keyword not taken into account when building a client

### ISSUE THREAD

**Issue by volnt** [OpenAPITools/openapi-generator#14181]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm generating a python-client based on the following OpenApi spec:

```
components:
  schemas:
    Pet:
      properties:
        name:
          type: string
          title: Name
        age:
          type: integer
          title: Age
      title: Pet
      type: object
    ListPetsResponse:
      properties:
        oldestPet:
          oneOf:
            - $ref: '#/components/schemas/Pet'
          title: Oldest Pet
          nullable: true
        pets:
          items:
            $ref: '#/components/schemas/Pet'
          nullable: true
          title: Pets
          type: array
      title: ListPetsResponse
      type: object

openapi: 3.0.2
info:
  title: Pet Store
  version: 0.0.1
paths:
  /api/v1/pets:
    get:
      operationId: list_pets
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPetsResponse'
          description: Successful Response
      summary: List Pets
```

This OpenAPI spec defines the response property `oldestPet` like that:

```
 oldestPet:
          oneOf:
            - $ref: '#/components/schemas/Pet'
          nullable: true
```

So `oldestPet` should be either a `Pet` object or `null`.

The issue is that the generated client defines the property like that:

```
            class oldestPet(schemas.ComposedSchema):           
                class MetaOapg:  
                    @classmethod
                    @functools.lru_cache()
                    def one_of(cls):
                        return [
                            Pet,
                        ]
```

Where I would expect this instead:

```
            class oldestPet(schemas.ComposedSchema):           
                class MetaOapg:  
                    @classmethod
                    @functools.lru_cache()
                    def one_of(cls):
                        return [
                            Pet, schemas.NoneBase,             # note the added `NoneBase`
                        ]
```

##### openapi-generator version

I'm using `openapitools/openapi-generator-cli:v6.2.0`.

I don't believe this is a regression but I haven't tested with previous versions.

##### Suggest a fix

I'd first like to confirm with others (especially @spacether) that this is indeed a bug, if that is confirmed I'll see how it can be fixed.

**Comment by spacether** [comment]
Hi there, this is a spec issue and the generator is behaving correctly.
`nullable: true` only adds type null when used adjacent to an explicit type definition.
[Per the openapi spec, the value for nullable is described as](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#schema-object):
```
A true value adds "null" to the allowed type specified by the type keyword, only if type is explicitly defined within the same Schema Object. Other Schema Object constraints retain their defined behavior, and therefore may disallow the use of null as a value. A false value leaves the specified or default type unmodified. The default value is false.
```
Your `oldestPet` schema has no type definition, so any type is allowed in. Adding `nullable: True` has no impact.
To get this to work as you want you can:

1. make the Pet schema nullable in the component
2. Update oldestPet to be:
```
anyOf:
- $ref: '#/components/schemas/Pet'
- type: object
   nullable: true
```

**Comment by spacether** [comment]
Welcome :) Glad to hear tat it is working
