### ISSUE TITLE
[BUG] [JAVA] compile error using Spring StreamingResponseBody after update to 6.0.1

### ISSUE THREAD

**Issue by Simulant87** [OpenAPITools/openapi-generator#14182]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
https://github.com/Simulant87/openApiGeneratorStreamingResponseBodyBug/blob/main/api-doc/file-storage-api.yml
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
Actual: Compile error.
Expected: Working as with version 6.0.0

##### Description
I was using the Java OpenAPI Generator in version 6.0.0 just fine using a StreamingResponseBody with Spring Boot to download a file, generating the Controller API from the API definition. After updating to 6.0.1 the StreamingResponseBody no longer works and creates a compile error.

```
> Task :compileKotlin FAILED
e: /src/main/kotlin/com/example/filestorage/rest/FilesController.kt: (18, 34): 
    Return type of 'downloadFile' is not a subtype of the return type of the overridden member 
    'public open fun downloadFile(): ResponseEntity<JsonNode!>! defined in com.example.filestorage.generated.api.FilesApi'
```
##### openapi-generator version

Version 6.0.1 contains the regression bug compared to version 6.0.0. The error persists in all newer versions.
the Java generator is used in a Gradle based project using the Kotlin DSL for configuring the build. https://github.com/Simulant87/openApiGeneratorStreamingResponseBodyBug/blob/08cac0d720da6e0db78709b705367698d972d22c/build.gradle.kts#L49
The Code is in Kotlin and using Spring Boot, but it does not matter too much, it would also fail in Java as the generator no longer generates the expected response model class requires to define the response of the Controller interface after the version update.

##### OpenAPI declaration file content or url

https://github.com/Simulant87/openApiGeneratorStreamingResponseBodyBug/blob/main/api-doc/file-storage-api.yml

```yaml
openapi: '3.0.2'
info:
  title: 'File Storage API'
  description: |
  version: 'v1.0'

servers:
  - url: '{testTarget}/'
    description: the system to test on
    variables:
      testTarget:
        enum:
          - http://localhost:8080
        default: http://localhost:8080

paths:
  /files:
    get:
      tags:
        - Files
      operationId: downloadFile
      summary: 'download a file as StreamingResponseBody'
      responses:
        200:
          description: 'Retrieves a file'
          headers:
            Content-Disposition:
              schema:
                type: string
              description: the format is `attachment; filename="test.txt"`
          content:
            application/octet-stream:
              schema:
                $ref: '#/components/schemas/StreamingResponseBody'

components:
  schemas:
    StreamingResponseBody:
      type: 'object'
```

##### Generation Details
checkout this repository: https://github.com/Simulant87/openApiGeneratorStreamingResponseBodyBug

run `./gradlew bootRun` 

##### Steps to reproduce
https://github.com/Simulant87/openApiGeneratorStreamingResponseBodyBug/blob/08cac0d720da6e0db78709b705367698d972d22c/build.gradle.kts#L12
switch to version 6.0.0 and the example project works,
use version 6.0.1 or above and a compile error is thrown.

**Comment by borsch** [comment]
@Simulant87 I'm not 100% sure but looks like this has been changed here https://github.com/OpenAPITools/openapi-generator/pull/12600

Inside build.gradle try to change `importMappings.put` to `schemaMappings.put`

**Comment by Simulant87** [comment]
thank you for that hint. So this seems to be not a bug, but actually a late bugfix.
I could fix it by chaging the typeMapping to `typeMappings.put("object", "StreamingResponseBody")`.

From:
```
tasks {
	openApiGenerate {
		typeMappings.put("object", "com.fasterxml.jackson.databind.JsonNode")
		importMappings.put("StreamingResponseBody", "org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody")
	}
}
```

To:

From:
```
tasks {
	openApiGenerate {
		typeMappings.put("object", "StreamingResponseBody")
		importMappings.put("StreamingResponseBody", "org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody")
	}
}
```
