### ISSUE TITLE
[REQ] Extensions for DI

### ISSUE THREAD

**Issue by JakobPriesner** [OpenAPITools/openapi-generator#14192]
### Is your feature request related to a problem? Please describe.

I would like to include all generated clients in .NET7.0 with DI in my code so that a new object does not have to be created each time it is used. 

## Describe the solution you'd like

A Startup.cs like file would be nice with a function like 
```
public static void AddGeneratedClients(this IServiceCollection services)
{
    services.AddSingleton<IPedClient, PedClient>();
    services.AddSingleton<IStoreClient, StoreClient>();
}
```
So i can call in my own Startup-file **services.AddGeneratedClients();** and then inject the Clients in the Constructor of some class Foo with 
```
public Foo(IPedClient pedClient)
{
    _pedClient = pedClient;
}
```

**Comment by devhl-labs** [comment]
If you're using csharp-netcore try the generichost library.

**Comment by devhl-labs** [comment]
That's what the library does, though it may be sitting in a pr still.
