### ISSUE TITLE
[BUG] Application context generation for spring generator can not be disabled

### ISSUE THREAD

**Issue by IvoNet** [OpenAPITools/openapi-generator#14190]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using the generator in maven 

```xml
<plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.2.1</version>
                <executions>
                    <execution>
                        <id>generate-server</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>contract/openapi.yaml</inputSpec>
                            <generatorName>spring</generatorName>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                            <configOptions>
                                <basePackage>com.example</basePackage>
                                <apiPackage>com.example.api</apiPackage>
                                <modelPackage>com.example.model</modelPackage>
                                <dateLibrary>java8</dateLibrary>
                                <apiFirst>false</apiFirst>
                                <delegatePattern>true</delegatePattern>
                                <useTags>true</useTags>
                                <interfaceOnly>false</interfaceOnly>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
</plugin>
```

- with the generate*Tests options set to false it will still generate the `OpenApiGeneratorApplicationTests.java` file

and this one fails when run with the repackaging option of the spring boot maven plugin and in the IDE when it is recognized as a  test.

Why can I disable all kinds of test generation but not not that one?

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

Any correct yaml

##### Steps to reproduce

mvn clean package

##### Related issues/PRs

- possibly https://github.com/OpenAPITools/openapi-generator/issues/3318

##### Suggest a fix

make an option to just disable generation of all tests or an option like `<generateApplicationContextTests>false</generateApplicationContextTests>` or something like it

**Comment by Nathanrown** [comment]
+1

**Comment by wing328** [comment]
one can use `.openapi-generator-ignore` to skip any files during code generation.

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#ignore-file-format has more info.

there's also an option to pre-populate this file as part of the process.
