### ISSUE TITLE
[BUG] issue with java native client handling of response body

### ISSUE THREAD

**Issue by sorin-florea** [OpenAPITools/openapi-generator#14203]
#### Bug Report Checklist

[The native Java client](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache#L264) is using `responseBody.available() < 1` to check if the response is empty, however, `InputStream.available()` [can and will return 0](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#available--) depending on the implementation and should not be used for this. This means that the response will be returned as `null` even though that should not be the case.

- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/14222
