### ISSUE TITLE
[Ruby] Add support for Faraday (HTTP lib) #3270

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#1422]
##### Description

Currently, Ruby API client has a dependency on Typhoeus (HTTP lib).

We want to add support for [Faraday](https://github.com/lostisland/faraday) to provide more flexibility in choosing what HTTP lib to use in the Ruby API client.

(Typhoeus will still be supported)

##### OpenAPI Generator version

Latest master

##### Suggest a solution

Similar to Java, we can use the `-l/--library` option to specify `faraday` and implement the api_client.rb with `faraday` so that users can choose which one they want to use.

cc @meganemura

**Comment by meganemura** [comment]
I'll tackle this issue 💪

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/3405
