### ISSUE TITLE
The generation of SDK takes a long time

### ISSUE THREAD

**Issue by jishupei** [OpenAPITools/openapi-generator#14243]
##### Description

We had 4000+ apis in our files, and when generating the SDK using cli commands, it would have taken several hours.
Is there any good way to generate such large files?

##### openapi-generator version

openapi-generator-cli-6.0.0.jar

##### OpenAPI declaration file content or url
The file is too large to be shown here

##### Command line used for generation

java -jar bin/openapi-generator-cli-6.0.0.jar generate \
    -g java\
    -i src/main/resources/oas_full.json\
    -o gen-java \
    -c src/main/resources/java-sdk.json \
    -t src/main/resources/Java \
    --global-property skipFormModel=false

##### Suggest a fix/enhancement

Is there any good way to generate such large files?

**Comment by wing328** [comment]
> openapi-generator-cli-6.0.0.jar

can you try the latest stable version v6.2.1 instead?

> -g java

Have you tried other generators like C#, Go, etc to see if the issue only happens with the `java` generator taing long time to generate files?

**Comment by jishupei** [comment]
> > openapi-generator-cli-6.0.0.jar
> 
> can you try the latest stable version v6.2.1 instead?
> 
> > -g java
> 
> Have you tried other generators like C#, Go, etc to see if the issue only happens with the `java` generator taing long time to generate files?

I tried c# and it only took a few minutes.
It seems that only java is time-consuming, I tried to add the command "--global-property SkipFormModel = false, modelTests = false, apiTests = false, modelDocs = false, skipOperationExample = true ", is also very time-consuming

**Comment by wing328** [comment]
> I didn't try v6.2.1 

Please try. Lots of changes since v6.0.0

**Comment by jishupei** [comment]
> > I didn't try v6.2.1
> 
> Please try. Lots of changes since v6.0.0

It was quick. It only took a few minutes. thank you
