### ISSUE TITLE
serverUrl is not parsed correctly

### ISSUE THREAD

**Issue by smoebody** [OpenAPITools/openapi-generator#1427]
##### Description

server URL is not parsed correctly, when i try to generate from url. 
```
[main] WARN  o.o.codegen.utils.URLPathUtils - 'scheme' not defined in the spec (2.0). Default to [http] for server URL [http:///v2]
```

The URL is as follows:

    http://api:3000/v2/api-docs

This is the generated `basePath`in the code:

```
protected basePath = 'http://http:/v2';
```

##### openapi-generator version

latest version of docker-image `openapitools/openapi-generator-cli:latest`

##### Command line used for generation

`generate -i http://api:3000/v2/api-docs -g typescript-angular -o /app/api --additional-properties ngVersion=7.0.0`

**Comment by wing328** [comment]
@smoebody can you please share the spec? Hard to troubleshoot without the spec to reproduce the issue.

**Comment by smoebody** [comment]
I dont think the spec is relevant here. In case it is you can take the spec from here and remove the `host` property. Then serve it via http at a non-standard port and use this url to generate the code
