### ISSUE TITLE
[Java][resttemplate] Update spring-web to the latest 6.x

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#14276]
Update spring-web to the latest 6.x, which requires updating ApiClient.java and more to address the compilation errors.

If anyone wants to fix this, please reply to let me know. Thank you.

**Comment by serpentcross** [comment]
This still does not work :(

**Comment by borsch** [comment]
@serpentcross could you please provide plugin/CLI configuration, OpenAPI spec file and generated output that doesn't meet your expectations
