### ISSUE TITLE
[BUG][KOTLIN] Wrong Nullability for required and readOnly properties

### ISSUE THREAD

**Issue by AdRyAniP** [OpenAPITools/openapi-generator#14280]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated properties using `kotlin-spring` generator are not correctly generated when the property is `required` but marked as `readOnly`.

If a property is only `required` the generator generates it with non-nullable type which is correct but if the property is marked as `readOnly` the type changes to the nullable version which is wrong.

##### openapi-generator version

Maven plugin versions tested: 5.4.0, 4.3.1, and **6.1.2 (Latest)**

##### OpenAPI declaration file content or URL

Here is an example. Pay attention to the three different fields:
* `id` -> declared as `required` but without `readOnly` flag
* `name` -> declared as `required` and as  `readOnly`
* `surname` -> not `required` neither `readOnly`

```json
{
  "swagger": "2.0",
  "info": {
    "description": "Service",
    "version": "0.0.1",
    "title": "service"
  },
  "basePath": "/service",
  "tags": [
    {
      "name": "service"
    }
  ],
  "paths": {
  },
  "securityDefinitions": {
    "basicAuth": {
      "type": "basic"
    }
  },
  "definitions": {
    "ExampleDTO" : {
      "type" : "object",
      "required" : [ "id", "name" ],
      "properties" : {
        "id" : {
          "type" : "string"
        },
        "name" : {
          "type" : "string",
          "readOnly" : true
        },
        "surname" : {
          "type" : "string"
        }
      }
    }
  }
}
```

##### Generation Details

Maven configuration:
```xml
                    <execution>
                        <id>testservice</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.build.directory}/swagger/test.json</inputSpec>
                            <generateApis>false</generateApis>
                            <modelPackage>com.test.model</modelPackage>
                            <generatorName>kotlin-spring</generatorName>
                            <skipValidateSpec>true</skipValidateSpec>
                            <configOptions>
                                <enumPropertyNaming>UPPERCASE</enumPropertyNaming>
                                <useTags>true</useTags>
                                <interfaceOnly>true</interfaceOnly>
                                <library>spring-boot</library>
                                <reactive>true</reactive>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                        </configuration>
                    </execution>
```

##### Steps to reproduce

Copy the input file (Swagger definition) into the directory defined in the `inputSpec` and Run `mvn clean compile`

The generated code is:

```kotlin
/**
 * 
 * @param id 
 * @param name 
 * @param surname 
 */
data class ExampleDTO(

    @field:JsonProperty("id", required = true) val id: kotlin.String,

    @field:JsonProperty("name", required = true) val name: kotlin.String? = null,

    @field:JsonProperty("surname") val surname: kotlin.String? = null
) {

}
```

As you can see the field `name` is declared as `nullable` with a default value when it should be `non-nullable`. Expected:
```kotlin
    @field:JsonProperty("name", required = true) val name: kotlin.String,
```

##### Suggest a fix

Don't change a field's nullability behavior just because the `readOnly` flag is activated.

**Comment by saschpe** [comment]
This is obviously wrong but there is more to it. At the moment, all data class fields are either generated as `val` or `var` depending on the configuration option *modelMutable*. 

Thus, one can either have
```kotlin
data class ModelMutableFalse {
  val a: kotlin.String,
  val b: Kotlin.String
}
```
or 
```kotlin
data class ModelMutableTrue {
  var a: kotlin.String,
  var b: Kotlin.String
}
```
but not
```kotlin
data class BothRequiredOrNot {
  var a: kotlin.String,
  val b: Kotlin.String
}
```
Therefore, the *modelMutable* generator option available in the **kotlin-vert**, **kotlin-server** and **kotlin-spring** generators should be deprecated in favor of `readOnly`. The latter is far more granular and and actually part of the OpenAPI 3.x spec. I'll file a separate bug...

**Comment by zaenk** [comment]
This is a tricky one and I don't think the current behaviour of the generator is wrong.

I'd like quote. the OpenAPI spec here: https://swagger.io/docs/specification/data-models/data-types/#readonly-writeonly

> You can use the `readOnly` and `writeOnly` keywords to mark specific properties as read-only or write-only. This is useful, for example, when `GET` returns more properties than used in `POST` – you can use the same schema in both `GET` and `POST` and mark the extra properties as `readOnly`. `readOnly` properties are included in responses but not in requests, and `writeOnly` properties may be sent in requests but not in responses.
> ...
> **If a `readOnly` or `writeOnly` property is included in the `required` list, `required` affects just the relevant scope**

So for OpenAPI, a schema like this one

```yaml
Example:
  required:
    - id
    - name
  properties:
    id:
      type: string
      readOnly: true
    name:
      type: string
```

means two completely different objects.

In request body:

```json
{
  "name": "John"
}
```

In response body:

```json
{
  "id": "foo",
  "name": "John"
}
```

When used in requests, only `name` attribute must be present, as `id` is `readOnly` and must not be sent in requests, but it must be present in responses because it's required.

The generator only generates a single model for a schema, and it must fit all use cases, that's why `readOnly` properties are nullable.

This similar to [TypeScript's readonly properties](https://www.typescriptlang.org/docs/handbook/utility-types.html#readonlytype) - but even this abstraction is not a good fit for the OpenAPI `readonly` property (my team was evaluating this a few years ago, but I can't recall what was the verdict here).

The current implementation matches the intention of the spec. If this distinction is *really* needed in the *generated* code, then I'd use two different schemas. Otherwise, I'd handle this by mapping the *generated DTOs* into some class that specific to the use case / service call.
