### ISSUE TITLE
[BUG][JAVA][SERVER] In release 6.2.1, spring server generator creates wrong annotation on method parameter for multipart request 

### ISSUE THREAD

**Issue by raverone** [OpenAPITools/openapi-generator#14295]
##### Description

Spring server genertor creates wrong annotation on method parameter for multipart request.
The request have 2 parameters:
* SomeObject param1
* MultipartFile param2

In version 5.4.0 both parameters would be annotated with ```@RequestPart```. Which is correct.

But starting from version 6.0.0 (until the 6.2.1 at least) param1 would be annotated with ```@RequestParam``` and param2 with ```@RequestPart```.
In this case, if you make a call to such endpoint, Spring won't be able to convert the request parameters and will throw
```
org.springframework.web.method.annotation.MethodArgumentConversionNotSupportedException:
Failed to convert value of type 'java.lang.String' to required type 'org.example.http.model.SomeObject';
...
no matching editors or conversion strategy found
```

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

[Gist](https://gist.github.com/raverone/bcf34804241bb39e40121ef2704ab040)

##### Generation Details

Generation is done with the gradle plugin by executing ./gradlew :openApiGenerate

##### Steps to reproduce

I created a minimal project on [github](https://github.com/raverone/open-api-multipart-bug)
Steps to reproduce the bug:

* clone the repo
* cd into the repo directory
* execute ```./gradlew :openApiGenerate```
* examine file ```build/generated/src/main/java/org/example/bug/http/api/TestApiApi.java```
  * Expected generated code

```
default ResponseEntity<SomeResponse> uploadFileAndJson(
        @RequestPart(value = "someObject", required = true) SomeObject someObject,
        @RequestPart(value = "image", required = true) MultipartFile image
    )
```
*
  * Actual generated code
```
default ResponseEntity<SomeResponse> uploadFileAndJson(
        @RequestParam(value = "someObject", required = true) SomeObject someObject,
        @RequestPart(value = "image", required = true) MultipartFile image
    )
```
* you can also execute tests with ```./gradlew -i :test```. It should pass, but currently it isn't.

**Comment by borsch** [comment]
Issue was introduced here https://github.com/OpenAPITools/openapi-generator/pull/11449 and released as part of 6.0.0

**Comment by borsch** [comment]
@raverone latest 6.3.0 spanshot should contains this fix. Could you try it?

**Comment by raverone** [comment]
Thanks @borsch !
With [openapi-generator-cli-6.3.0-20230106.034606-64.jar](https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.3.0-SNAPSHOT/openapi-generator-cli-6.3.0-20230106.034606-64.jar) generated code works.
I'm closing then this ticket.
Waiting for the 6.3.0 release :rocket:

**Comment by ssternal** [comment]
Using `@RequestParam` and `@RequestPart` on traditional servlet stack should be fine. If I'm not mistaken, for a reactive stack I guess all parameters of a multipart request should have the `@RequestPart` annotation instead. This is due to the `@RequestParam` annotation on reactive stack only maps to request parameters, but neither to form data, nor parts of multipart requests. This leads to a specification that states you should send parameters as part of your form, but the actual implementation requires you to send simple objects as request parameters. Can anyone confirm this?

**Comment by jorgerod** [comment]
> Using `@RequestParam` and `@RequestPart` on traditional servlet stack should be fine. If I'm not mistaken, for a reactive stack I guess all parameters of a multipart request should have the `@RequestPart` annotation instead. This is due to the `@RequestParam` annotation on reactive stack only maps to request parameters, but neither to form data, nor parts of multipart requests. This leads to a specification that states you should send parameters as part of your form, but the actual implementation requires you to send simple objects as request parameters. Can anyone confirm this?

Your comment is correct. There is a bug for the reactive stack. 
This bug was introduced in this [PR](https://github.com/OpenAPITools/openapi-generator/pull/11449).

@wing328 @cachescrubber @borsch  If you like, I can make a PR so that in the case of reactive the parameter is created as `@RequestPart` instead of `@RequestParam`

**Comment by wing328** [comment]
@jorgerod yes please file a PR to start with and we'll review accordingly.

**Comment by jorgerod** [comment]
> @jorgerod yes please file a PR to start with and we'll review accordingly.

- https://github.com/OpenAPITools/openapi-generator/pull/16535
