### ISSUE TITLE
[BUG] Generating python client code with the --package-name flag generates invalid code

### ISSUE THREAD

**Issue by abeerag** [OpenAPITools/openapi-generator#14324]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generating python client code with the --package-name flag results in some imports using / instead of . which is invalid Python format

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

https://gist.github.com/abeerag/2e433d8554e3bb567437ca2d67696ed1

##### Steps to reproduce

openapi-generator generate -i main.json -g python -o railz  --package-name alpha.generated.railz

Attempt to run Yapf on the code, the generated python in some of the models failes generates imports such as alpha/generated/railz instead of alpha.generated.railz. Running find and replace on that string results in usable code

**Comment by spacether** [comment]
Can you please try the latest commit in master branch? This should have been fixed in https://github.com/OpenAPITools/openapi-generator/pull/14015

**Comment by spacether** [comment]
Duplicates https://github.com/OpenAPITools/openapi-generator/issues/13648

**Comment by spacether** [comment]
This is fixed in our 6.3.0 release
