### ISSUE TITLE
[BUG][csharp-netcore] Duplicate methods in model class

### ISSUE THREAD

**Issue by arvindpdmn** [OpenAPITools/openapi-generator#14350]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When `oneOf` or `anyOf` constructs are used, the generated model file has duplicate constructor and duplicate `getObject()` method. There's no reference to the actual properties (aId, bId, cId, dId) in the generated file. These problems are not seen with `allOf`. The attached example YAML file uses `oneOf`. The same problem will be observed if it's replaced with `anyOf`.

With `aspnetcore`, the model file has no duplicates but shows other problems, such as no constructor. This issue focuses only on `csharp-netcore`.

##### openapi-generator version

Version used is 6.2.1. Did not test against the latest commit on the master branch.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Problem example with OneOf'
paths: {}
components:
  schemas:
    SomeId:
      type: object
      properties:
        aId:
          $ref: '#/components/schemas/AId'
        bId:
          $ref: '#/components/schemas/BId'
        cId:
          $ref: '#/components/schemas/CId'
        dId:
          $ref: '#/components/schemas/DId'
      oneOf:
        - required: [ aId ]
        - required: [ bId ]
        - required: [ cId ]
    AId:
      type: integer
      minimum: 0
      maximum: 10
    BId:
      type: integer
    CId:
      type: integer
    DId:
      type: integer
```
##### Generation Details

```
java -jar C:\openapi-generator-cli.jar generate  -i C:\ModelExample.yaml -g csharp-netcore -o C:\out --additional-properties=targetFramework=net6.0  --additional-properties=packageName=Com.Example
```

##### Steps to reproduce

Just run the command above and check the generated model file. We will see the duplicates.

##### Related issues/PRs

This could be related: https://github.com/OpenAPITools/openapi-generator/issues/8382

##### Suggest a fix

None at the moment

**Comment by davit-asryan-sveasolar** [comment]
Having the same issue

**Comment by wing328** [comment]
The dupilcated methods in this case can be fixed via the `REMOVE_ANYOF_ONEOF_AND_KEEP_PROPERTIES_ONLY` option in the opeanpi normalizer

e.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g csharp-netcore -i /tmp/a.yaml -o /tmp/duplicated2/ --openapi-normalizer REMOVE_ANYOF_ONEOF_AND_KEEP_PROPERTIES_ONLY=true
```

reference: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

**Comment by arvindpdmn** [comment]
Using openapi-generator-cli-6.5.0-20230329.141901-70.jar I tested this. It is fixed though there's no validation code to ensure anyOf or oneOf constraints are met.

In one example, there's still a problem (**code does not compile**): HssAuthenticationVectors in file https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-16/TS29503_Nudm_UEAU.yaml . The generated code has three GetList() methods that differ only by the return type.

**Comment by wing328** [comment]
it's fixed by https://github.com/OpenAPITools/openapi-generator/pull/15007 instead. Please enable the option `skipOneOfAnyOfGetter`

**Comment by arvindpdmn** [comment]
Tried with openapi-generator-cli-6.5.0-20230329.141901-70.jar few weeks back. Was able to compile the generated code.
Today tried with openapi-generator-cli-6.6.0-20230422.085013-33.jar. Compilation fails. I see duplicate methods generated. The offending definition is like this:
```
        subscribedDnnList:
          type: array
          items:
            anyOf:
              - $ref: 'TS29571_CommonData.yaml#/components/schemas/Dnn'
              - $ref: 'TS29571_CommonData.yaml#/components/schemas/WildcardDnn'
```

Generated code is:
```
    public partial class AccessAndMobilitySubscriptionDataSubscribedDnnListInner : AbstractOpenAPISchema, IEquatable<AccessAndMobilitySubscriptionDataSubscribedDnnListInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccessAndMobilitySubscriptionDataSubscribedDnnListInner" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public AccessAndMobilitySubscriptionDataSubscribedDnnListInner(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccessAndMobilitySubscriptionDataSubscribedDnnListInner" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public AccessAndMobilitySubscriptionDataSubscribedDnnListInner(string actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "anyOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

       ...
```

**Comment by wing328** [comment]
@arvindpdmn did you enable the option `skipOneOfAnyOfGetter` (not a normalizer rule) when generating the csharp-netcore client?

**Comment by arvindpdmn** [comment]
Yes. `--additional-properties=targetFramework=net7.0,skipOneOfAnyOfGetter=true` was the option used.

**Comment by arvindpdmn** [comment]
This is the URL: https://forge.3gpp.org/rep/all/5G_APIs/-/blob/REL-16/TS29503_Nudm_SDM.yaml
