### ISSUE TITLE
[REQ] introduce useLegacyJavaxNamespace instead of useJakartaEe and useSpringBoot3 

### ISSUE THREAD

**Issue by parenko** [OpenAPITools/openapi-generator#14362]
### Is your feature request related to a problem? Please describe.

There are several options to enable compatible generations of Java templates for newer libraries of Spring Boot (3.0.1) and jakarta namespace.
Spring generator has `useSpringBoot3`.
Java generator has `useJakartaEe`.

These options might be confusing which option to use.

## Describe the solution you'd like

How about to keep only one option? eg kinda generic `useJakartaEe`?
Or introduce another option which would be needed for legacy reasons? eg `useLegacyJavaxNamespace`?

## Describe alternatives you've considered

Alternatively support both options `useSpringBoot3` `useJakartaEe` interchangeable.
Or use `useJakartaEe` for namespace related generation and `useSpringBoot3` only for SB3 but not namespace related generation.

Java | @bbdouglas (2017/07) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01) @karismann (2019/03) @Zomzog (2019/04) @lwlee2608 (2019/10)
-- | --

cc @borsch @wing328

**Comment by borsch** [comment]
There is no need as such. `useSpringBoot3` is very SB specific and has much more thing do to, not only `javax` or `jakarta` package.

Probably the only thing that can be update is documentation. Like when  you use `useSpringBoot3=true`, then `useJakartaEe` will always be set to `true` regardless of existing value

**Comment by parenko** [comment]
Do you think it would suffice to apply `useJakartaEe=true; additionalProperties.put(USE_JAKARTA_EE, useJakartaEe);` inside of `if (isUseSpringBoot3()) {`?
(And also documenting it)

**Comment by borsch** [comment]
> Do you think it would suffice to apply `useJakartaEe=true; additionalProperties.put(USE_JAKARTA_EE, useJakartaEe);` inside of `if (isUseSpringBoot3()) {`? (And also documenting it)

yep
