### ISSUE TITLE
[BUG][Java Spring OAS3] Deprecated @Schema(required) annotation property is generated

### ISSUE THREAD

**Issue by whydoievenneedthis** [OpenAPITools/openapi-generator#14398]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

When using the spring generator, the fields in the generated POJOs are annotated with `@Schema(required = true | false)`, which is now [deprecated](https://docs.swagger.io/swagger-core/v2.2.7/apidocs/io/swagger/v3/oas/annotations/media/Schema.html#required--). Instead, the `requiredMode` should be used.

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  version: '1.0'
paths: {}
components:
  schemas:
    ResponseEntry:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
```

##### Actual output

Something along the lines of:
```java
  @NotNull @Valid 
  @Schema(name = "id", required = true)
  @JsonProperty("id")
  private UUID id;

  @Schema(name = "name", required = false)
  @JsonProperty("name")
  private String name;
```

##### Expected output

Something along the lines of:
```java
  @NotNull @Valid 
  @Schema(name = "id", requiredMode = Schema.RequiredMode.REQUIRED)
  @JsonProperty("id")
  private UUID id;

  @Schema(name = "name", requiredMode = Schema.RequiredMode.NOT_REQUIRED) // or .AUTO, here I'm not sure which would be better
  @JsonProperty("name")
  private String name;
```

##### Suggest a fix

Update the [pojo.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache#L153) file (plus anything that might be using the same annotation property).

**Comment by plopezgit** [comment]
Thank you for this!
