### ISSUE TITLE
[BUG][java] CustomTypeAdapterFactory incorrectly assumes non-primitives are json objects

### ISSUE THREAD

**Issue by ashatch** [OpenAPITools/openapi-generator#14404]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

`pojo.moustache`'s `CustomTypeAdapterFactory.create` populates properties by testing for e.g. primitive types for values. It's else block makes an assumption that if it isn't a primitive type, it must be an object:

```java
gson.toJsonTree(entry.getValue()).getAsJsonObject()
``` 

This fails when considering arrays.

##### openapi-generator version

`master`

##### Suggest a fix

I'll raise a PR.

**Comment by wing328** [comment]
can you please share a spec to reproduce the issue?

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/17812
