### ISSUE TITLE
[html2] missing body/response schema documentation

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#1441]
##### Description

I'm generating html2 documentation from modules/openapi-generator/src/test/resources/2_0/rust-server/rust-server-test.yaml.

I've noticed that the html2 docs seem to be missing the body and response schemas. These were present when generated in swagger-codegen

New (openapi-generator): https://bgill.eu/openapi-generator/issues/new-html2.html#api-Default-htmlPost
Old (swagger-codegen): https://bgill.eu/openapi-generator/issues/old-html2.html#api-Default-htmlPost

##### OpenAPI declaration file content or url

[modules/openapi-generator/src/test/resources/2_0/rust-server/rust-server-test.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/rust-server/rust-server-test.yaml)

**Comment by Hentioe** [comment]
+1

**Comment by antonio-petricca** [comment]
The issue is still present on 5.1.0.
