### ISSUE TITLE
[Question] How to remove "Inner" suffix from generated class names in version 6.x.x?

### ISSUE THREAD

**Issue by vladimirvlkovic** [OpenAPITools/openapi-generator#14419]
Hello,
we were using version 5.4.0 in our project and now we have upgraded to 6.2.1 and some of the generated java classes have a "Inner" suffix. What would be the correct way of removing this suffix?

**Comment by wing328** [comment]
please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#inline-schema-naming on how to customize the naming of the inline schema.

**Comment by ftagne** [comment]
Hello, 
practically how we do to be remove "Inner" suffix ?
I read the documentation, but it's not clear for me.

Can I have an example ?

Thanks.
