### ISSUE TITLE
[BUG] SpringCodegen doesn't add ParameterIn.HEADER to Parameter annotation (required when implicitHeaders=true)

### ISSUE THREAD

**Issue by EliasZ** [OpenAPITools/openapi-generator#14418]
**Given the following spec file:**
```yaml
openapi: 3.0.1
info:
  title: test
  version: 1.0.0
paths:
  /test:
    get:
      summary: test
      operationId: test
      parameters:
        - name: testHeader
          in: header
          description: 'Test header'
          required: true
          schema:
            type: string
            format: uuid
          example: '523028ac-2e0e-41ab-b6f7-38c1efdbac45'
      tags:
        - test
      responses:
        200:
          description: ok
```
and using the Spring generator with `implicitHeaders=true`, I expect that there should be a `Parameter` annotation on the method stating that the `testHeader` has a property `in` of `ParameterIn.HEADER`:
```
@Parameters({
    @Parameter(in = ParameterIn.HEADER, name = "testHeader", description = "Test header", required = true)
})
```
Currently, the `in` property is missing. Looking at [the relevant moustache template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/paramDoc.mustache), there doesn't seem to be any templating functionality whatsoever to add an `in` property.

I've reproduced this with the following test (`SpringCodegenTest.java`). This test succeeds, but should fail.
```java
    @Test
    public void shouldAddParameterWithInHeaderWhenImplicitHeadersIsTrue() throws IOException {
        File output = Files.createTempDirectory("test").toFile().getCanonicalFile();
        output.deleteOnExit();

        OpenAPI openAPI = new OpenAPIParser()
                .readLocation("src/test/resources/bugs/implicitheader.yaml", null, new ParseOptions()).getOpenAPI();
        SpringCodegen codegen = new SpringCodegen();
        codegen.setLibrary(SPRING_BOOT);
        codegen.setOutputDir(output.getAbsolutePath());
        codegen.additionalProperties().put(SpringCodegen.INTERFACE_ONLY, "true");
        codegen.additionalProperties().put(SpringCodegen.USE_BEANVALIDATION, "true");
        codegen.additionalProperties().put(SpringCodegen.PERFORM_BEANVALIDATION, "true");
        codegen.additionalProperties().put(CodegenConstants.MODEL_PACKAGE, "xyz.model");
        codegen.additionalProperties().put(CodegenConstants.API_PACKAGE, "xyz.controller");
        codegen.additionalProperties().put(SpringCodegen.IMPLICIT_HEADERS, "true");

        ClientOptInput input = new ClientOptInput()
                .openAPI(openAPI)
                .config(codegen);

        DefaultGenerator generator = new DefaultGenerator();
        Map<String, File> files = generator.opts(input).generate().stream()
                .collect(Collectors.toMap(File::getName, Function.identity()));

        JavaFileAssert.assertThat(files.get("TestApi.java"))
                .isInterface()
                .assertMethod("test")
                .assertMethodAnnotations()
                .containsWithNameAndAttributes("Parameters", ImmutableMap.of(
                        "value", "{ @Parameter(name = \"testHeader\", description = \"Test header\", required = true) }"
                        // in = ParameterIn.HEADER is missing?!
                ));
    }
```

(I'm not familiar with the assertion library and this test is used for debugging; could only find a method to check the string-contents of the `@Parameters` annotation instead of checking the attributes of the `@Parameter` inside `@Parameters`)

##### openapi-generator version
6.2.1 (still present in master)

**Comment by borsch** [comment]
@EliasZ could you please try latest 6.3.0-SNAPSHOT build? It should contain fix for this issue

**Comment by ananta-code** [comment]
I am using  openapi-generator-maven-plugin:6.4.0 to generate the project..now it is generating the ParameterIn.HEADER but during compilation it is giving error "error: cannot find symbol:   variable ParameterIn"
`@NotNull @Parameter(name = "X-Request-ID", description = "Request Id to uniquely identify the request received.", required = true, in = **ParameterIn.HEADER**) @RequestHeader(value = "X-Request-ID", required = true) String xRequestID,
        @NotNull @Pattern(regexp = "^[a-z]{2}_[A-Z]{2}") @Parameter(name = "locale", description = "Browser locale language Property.", required = true, **in = ParameterIn.HEADER**) @RequestHeader(value = "locale", required = true) String locale,
     `
