### ISSUE TITLE
[BUG][PYTHON] client throws exception when server response provides `null` for an optional value

### ISSUE THREAD

**Issue by antonysouthworth-halter** [OpenAPITools/openapi-generator#14410]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

e.g you have an OpenAPI spec where some field on a model is not `required`

```yaml
components:
  schemas:
    MyObject:
      required:
        - someMandatoryField
      properties:
        someMandatoryField:
          type: string
        someOptionalField:
          type: string
```

and your server responds with a body like

```json
{"someMandatoryField": "some-value", "someOptionalField": null}
```

the Python client will refuse to deserialise it because it's the same as if you tried this:

```python
my_object = MyObject(some_mandatory_field="some-value", some_optional_field=None)
```

(fails because `None` is not a value value for a field of type `str`)

##### openapi-generator version

any, specifically I have seen it on 5.4.x

##### OpenAPI declaration file content or url

refer my description above

##### Generation Details

inside the docker container

```bash
export GENERATOR_NAME=python
export MODEL_PROPERTY_NAMING=snake_case
export TEMPLATE_NAME=python

/usr/local/bin/docker-entrypoint.sh generate \
  -i "./src/${SPEC}" \
  -g "${GENERATOR_NAME}" \
  -p modelPropertyNaming="${MODEL_PROPERTY_NAMING}" \
  -t "./templates/${TEMPLATE_NAME}" \
  -o "./client" \
  ./src
```

fyi we have nothing inside `templates` folder

##### Steps to reproduce

generate client and try to pass the example JSON in there, it will fail

##### Related issues/PRs

I could not find any but apologies if they already exist 🙏 

##### Suggest a fix

maybe allow `None` in ctor for models?

**Comment by spacether** [comment]
Hi there. Thank you for filing this issue. The generator is actually behaving correctly.
Optional properties may be omitted and does not describe allowed values. Please read all about it here https://json-schema.org/understanding-json-schema/reference/object.html#required-properties

To fix this you need to update your spec to add nullable: true for this property.

**Comment by antonysouthworth-halter** [comment]
Thank you for the clarification @spacether

**Comment by spacether** [comment]
You're welcome 🙂
