### ISSUE TITLE
[BUG] [python-nextgen] circular ImportError on spec that $ref's a spec which $ref's the prior one

### ISSUE THREAD

**Issue by j-wash-BL** [OpenAPITools/openapi-generator#14421]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When attempting the import the generated client, python throws the following stacktrace:
```
Traceback (most recent call last):
  File "[*project root*]\test.py", line 4, in <module>
    import geojson
  File "[*project root*]\geojson-client\geojson\__init__.py", line 21, in <module>
    from geojson.api.geo_json_api import GeoJsonApi
  File "[*project root*]\geojson-client\geojson\api\__init__.py", line 6, in <module>
    from geojson.api.geo_json_api import GeoJsonApi
  File "[*project root*]\geojson-client\geojson\api\geo_json_api.py", line 23, in <module>
    from geojson.models.geo_json_geometry import GeoJsonGeometry
  File "[*project root*]\geojson-client\geojson\models\__init__.py", line 18, in <module>
    from geojson.models.geo_json_geometry import GeoJsonGeometry
  File "[*project root*]\geojson-client\geojson\models\geo_json_geometry.py", line 22, in <module>
    from geojson.models.geometry_collection import GeometryCollection
  File "[*project root*]\geojson-client\geojson\models\geometry_collection.py", line 23, in <module>
    from geojson.models.geo_json_geometry import GeoJsonGeometry
ImportError: cannot import name 'GeoJsonGeometry' from partially initialized module 'geojson.models.geo_json_geometry' (most likely due to a circular import) ([*project root*]\geojson-client\geojson\models\geo_json_geometry.py)
```
A repo that can reproduce the issue can be found [here](https://github.com/j-wash-BL/python-nextgen-issue)

##### openapi-generator version

openapitools/openapi-generator-cli:latest on docker, pulled on 1/5/23

##### OpenAPI declaration file content or url

The spec can be found [here](https://github.com/j-wash-BL/python-nextgen-issue/blob/main/geojson_spec.v1.yml)

##### Generation Details

The client is generated using the following docker command in powershell:
```
docker run --rm -v "${PWD}/:/output" -v "${PWD}:/input" openapitools/openapi-generator-cli:latest generate `
   -g python-nextgen `
   -i /input/geojson_spec.v1.yml `
   -o /output/geojson-client `
   --additional-properties=packageName=geojson `
   --additional-properties=packageVersion=2.4.5
```

##### Steps to reproduce

1. Run the above command to generate client
2. Install the client package to my interpreter (in my case, a venv) using `pip install -e geojson-client`
3. Run any python script that attempts to run `import geojson`

**Comment by spacether** [comment]
@j-wash-BL have you tried the `python` generator?
It should work.
It loads imports at the bottom of modules and stores refs as methods that return $refed classes for this reason, to avoid circular import errors.

**Comment by ninas** [comment]
@spacether I'm running into this too. I have an OpenAPI 2.0 spec, and when trying to use the python generator as a workaround, I get the error:
`Exception in thread "main" java.lang.RuntimeException: Your spec version of 2.0 is too low. python only works with specs with version >= 3.X.X. Please use a tool like Swagger Editor or Swagger Converter to convert your spec to v3`

Are there plans to fix the circular dependency issue in python-flask?

**Comment by spacether** [comment]
@ninas please update your spec per those instructions and generate using the python generator. It will work. If you want to fix a bug in the python-flask generator, please submit a PR with a fix and a verification test.

**Comment by ninas** [comment]
@spacether unfortunately I can't upgrade to OpenAPI 3 - this spec is used by GCP's API Gateway which only supports 2.0.

**Comment by spacether** [comment]
The v2 to v3.0 spec change will not modify what the client is doing, it is just changing how the spec data is represented in json/yaml. What prevents upgrading the spec?

**Comment by ninas** [comment]
I think perhaps I'm not following - do you mean having two versions of the spec (v2 and v3) - one to feed into GCP and one to generate the models?

**Comment by ninas** [comment]
Ah, responded before seeing your edit.
Yes, I can certainly do that. Although, if I'm going through that effort for every change, then it's prob worth me just changing the one import line in the generated models :)

**Comment by spacether** [comment]
Where is the client running? How does gcp use it? I am suggesting making a new version to generate a client

**Comment by ninas** [comment]
GCP uses it to define the API it provides via API Gateway: https://cloud.google.com/api-gateway/docs/openapi-overview
The server (I was using python-flask when I ran into this issue), also runs in GCP (mix of cloud functions and plain instances).
I'll either just manually edit the generated models or go for the 2 versions approach. Thanks for your help on this issue, I appreciate you taking the time to walk through it with me!

**Comment by wing328** [comment]
UPDATE: I've filed https://github.com/OpenAPITools/openapi-generator/pull/15070 to fix it.

Tested locally with your spec to confirm the fix.
