### ISSUE TITLE
[BUG][JAVA][SPRING] Wrong annotation used for array of referenced object in Multipart request

### ISSUE THREAD

**Issue by MetroMarv** [OpenAPITools/openapi-generator#14449]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When we specify the request body as `multipart/form-data` and have one property of type array.

The generated annotation for the `statusArray` property is "@RequestParam". Which leads to following error in Spring when the endpoint is used:
```
org.springframework.web.method.annotation.MethodArgumentConversionNotSupportedException:
Failed to convert value of type 'java.lang.String' to required type 'List.of<MultipartMixedStatus>';
```
Expected would be the annotation "@RequestPart" which fixes the Spring error.

##### openapi-generator version

6.2.1

But the problem was probably introduced in #11449 with version 6.0.0 ([thanks to @borsch to figure this out](https://github.com/OpenAPITools/openapi-generator/issues/14295#issuecomment-1368773203))

##### OpenAPI declaration file content or url

```yaml
[...]
requestBody:
  content:
    multipart/form-data:
      schema:
        type: object
        properties:
          file:
            description: "a file"
            type: string
            format: binary
          statusArray:
            type: array
            items:
              $ref: '#/components/schemas/MultipartMixedStatus'
[...]
```

##### Generation Details

We used the Maven plugin with following config

```xml
        <configuration>
          <templateDirectory>openapi-generator-customization</templateDirectory>
          <generatorName>spring</generatorName>
          <modelNameSuffix>Dto</modelNameSuffix>
          <configOptions>
            <useSpringBoot3>true</useSpringBoot3>
            <documentationProvider>springdoc</documentationProvider>
            <useTags>true</useTags>
            <useBeanValidation>true</useBeanValidation>
            <performBeanValidation>true</performBeanValidation>
            <useSpringController>true</useSpringController>
            <oas3>true</oas3>
            <apiPackage>com.example.api</apiPackage>
            <modelPackage>com.example.model</modelPackage>
            <invokerPackage>com.example.invoker</invokerPackage>
            <interfaceOnly>true</interfaceOnly>
            <skipOverwrite>false</skipOverwrite>
          </configOptions>
        </configuration>
```

##### Steps to reproduce

See test in PR #14450.

##### Related issues/PRs

- #14295 fixed the problem for not wrapped objects
- #11449 might have introduced the problem

##### Suggest a fix

Fixed by: #14450

**Comment by bjansen** [comment]
I believe this change broke our controllers. We map an array of strings to a `List<String>`, and now the list is null instead of containing actual values. It used to be mapped using `@RequestParam` which worked just fine.

**Comment by borsch** [comment]
@bjansen please create a new issue and provide necessary details

**Comment by bjansen** [comment]
Done: #14866 14866
