### ISSUE TITLE
[Python3] Binary decode fails

### ISSUE THREAD

**Issue by POD666** [OpenAPITools/openapi-generator#1445]
##### Description

I'm using openapitools/openapi-generator-cli:v3.3.1 docker image to generate client from my swagger.yml

One of endpoints returns binary data and generated client fails with `UnicodeDecodeError`.

The problem is [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/rest.mustache#L213). I don't need response to be decoded to string as it's binary file.

My workaround is to pass `_preload_content=False` to the api call and handle urllib response object by myself.

I can suggest to simply wrap `.decode("utf-8")` in try-except.

**Comment by wing328** [comment]
@POD666 thanks for reporting the issue. Do you mind filing a PR with the suggested fix so that we can review more easily?

**Comment by POD666** [comment]
Probably we should remove attempt to decode data at all as it's [saved as binary](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/api_client.mustache#L548) any way.

**Comment by spacether** [comment]
Receiving binary data now works in the python client.
See our
- [sample spec endpoint](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L1253)
- [test downloading binary data](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L506)
