### ISSUE TITLE
[BUG] Compilation errors occured if set multipart/type in requestBody

### ISSUE THREAD

**Issue by tbw777** [OpenAPITools/openapi-generator#14461]
#### Bug Report Checklist

- [ v] Have you provided a full/minimal spec to reproduce the issue?
- [ v] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ v] Have you searched for related issues/PRs?
- [ v] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Compilation errors occured if set multipart/type in requestBody:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project drones-openfeign-api: Compilation failure: Compilation failure: 
[ERROR] /opanapicheck/drones-openfeign-api/target/generated-sources/openapi/src/main/java/com/tech/drones/oa/api/FacadeApi.java:[8,32] package com.tech.drones.oa.model does not exist
[ERROR] /opanapicheck/drones-openfeign-api/target/generated-sources/openapi/src/main/java/com/tech/drones/oa/api/FacadeApi.java:[62,25] cannot find symbol
[ERROR]   symbol:   class Medication
[ERROR]   location: interface com.tech.drones.oa.api.FacadeApi
[ERROR] /opanapicheck/drones-openfeign-api/target/generated-sources/openapi/src/main/java/com/tech/drones/oa/api/FacadeApi.java:[51,95] cannot find symbol
[ERROR]   symbol:   class Medication
[ERROR]   location: interface com.tech.drones.oa.api.FacadeApi
[ERROR] -> [Help 1]
```

##### openapi-generator version

6.2.1

##### OpenAPI declaration file content or url

https://gist.github.com/tbw777/d74e13d3da95b2b314c0d338a66dfa46

##### Generation Details

https://gist.github.com/tbw777/18f0077e8c3da0dc3834a2f836fe1006

##### Steps to reproduce

mvn clean compile

##### Related issues/PRs

not found

##### Suggest a fix

dont have

**Comment by martin-mfg** [comment]
Hi @tbw777,
the output of OpenAPI Generator should contain the line
> [INFO] Model Medication not generated since it's marked as unused (due to form parameters) and `skipFormModel` (global property) set to true (default)

You can set `skipFormModel` to `false` like this:
```xml
...
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <globalProperties>
                                <skipFormModel>false</skipFormModel> <!-- this is the important line -->
                            </globalProperties>
                            <generatorName>spring</generatorName>
                            <library>spring-cloud</library>
                            <inputSpec>${project.basedir}/../swagger-common-drones-spec/drones-common.yml</inputSpec>
                            <configOptions>
                                <packageName>com.tech.drones.oa</packageName>
...
```

Then your example should work.
