### ISSUE TITLE
[BUG] allOff to overwrite the description of a string schema results in faulty java code

### ISSUE THREAD

**Issue by icorne** [OpenAPITools/openapi-generator#14473]
##### Description

allOf to overwrite the description of a $ref string does not work in the java generator

##### openapi-generator version

6.2.0

##### OpenAPI declaration file content or url

```yaml
---
swagger: "2.0"
info:
  description: Test API
  version: 1.0.0
  title: Test Api
basePath: /
tags:
- name: test
  description: test
schemes:
- https
paths:
  /test:
    get:
      tags:
      - test
      summary: test
      operationId: getTest
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
            properties:
              one:
                type: array
                items:
                  $ref: '#/definitions/Test'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
definitions:
  BaseTest:
    type: string
    description: 'I am base'
    example: 'an example'
  Test:
    properties:
      base:
        allOf:
          - $ref: '#/definitions/BaseTest'
          - description: 'Overwritten description'
```

##### Generation Details

openapi-generator-cli generate -i allOfStringDescription.yaml -g spring
openapi-generator-cli generate -i allOfStringDescription.yaml -g java

##### Steps to reproduce

compile the resulting code
![image](https://user-images.githubusercontent.com/3259342/212921481-a915cd71-dcf6-41c6-8bbe-b45d4e28e18f.png)

##### Suggest a fix
It used to work in 4.3.0

**Comment by wing328** [comment]
please define as follows instead:
```
    properties:
      base:
        allOf:
          - $ref: '#/definitions/BaseTest'
        description: 'Overwritten description'
```

(description and allOf are in the same level)

**Comment by wing328** [comment]
related PR: https://github.com/OpenAPITools/openapi-generator/pull/21342
