### ISSUE TITLE
Unable to use Swagger CodeGen

### ISSUE THREAD

**Issue by pavan-chakka** [OpenAPITools/openapi-generator#14487]
##### Description

Hello, I am trying to generate 'Address' project code from that service's swagger json, using the swagger-codegen-cli.jar file that generated with 'mvn clean package -Dskiptests', and I am getting error. All I need is Java POJO class of Schemas from Address swagger 

##### openapi-generator version
3.0.1

##### OpenAPI declaration file content or url

`{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"https://abc-address-dev.xyz.com","description":"Generated server url"}],"tags":[{"name":"Actuator","description":"Monitor and interact","externalDocs":{"description":"Spring Boot Actuator Web API Documentation","url":"https://docs.spring.io/spring-boot/docs/current/actuator-api/html/"}}],"paths":{"/api/address/search":{"post":{"tags":["address-controller"],"operationId":"searchAddress","requestBody":{"content":{"application/json":{"schema":{"$ref":"#/components/schemas/Address"}}},"required":true},"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"$ref":"#/components/schemas/Address"}}}}}}},"/api/address/{id}":{"get":{"tags":["address-controller"],"operationId":"getAddressById","parameters":[{"name":"id","in":"path","required":true,"schema":{"type":"string"}}],"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"$ref":"#/components/schemas/Address"}}}}}}},"/actuator":{"get":{"tags":["Actuator"],"summary":"Actuator root web endpoint","operationId":"links_1","responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"type":"object","additionalProperties":{"type":"object","additionalProperties":{"$ref":"#/components/schemas/Link"}}}}}}}}},"/actuator/health":{"get":{"tags":["Actuator"],"summary":"Actuator web endpoint 'health'","operationId":"health_2","responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"type":"object"}}}}}}},"/actuator/health/**":{"get":{"tags":["Actuator"],"summary":"Actuator web endpoint 'health-path'","operationId":"health-path_2","responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"type":"object"}}}}}}}},"components":{"schemas":{"Address":{"required":["address1","city","state","zipCode"],"type":"object","properties":{"id":{"type":"string"},"name":{"type":"string"},"address1":{"type":"string"},"address2":{"type":"string"},"address3":{"type":"string"},"city":{"maxLength":255,"minLength":0,"type":"string"},"state":{"maxLength":255,"minLength":0,"type":"string"},"zipCode":{"maxLength":9,"minLength":5,"type":"string"},"deliveryRoute":{"type":"string"},"country":{"type":"string"},"key":{"type":"string"},"latitude":{"maximum":90,"minimum":-90,"type":"number","format":"double"},"longitude":{"maximum":180,"minimum":-180,"type":"number","format":"double"},"type":{"type":"string"},"createdBy":{"type":"string"},"modifiedBy":{"type":"string"}}},"Link":{"type":"object","properties":{"href":{"type":"string"},"templated":{"type":"boolean"}}}}}}`

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /Users/kiran/Downloads/test/address.json -l java -o /Users/kiran/Downloads/test/Address 

##### Steps to reproduce

1. Download code from https://github.com/swagger-api/swagger-codegen
2. Navigate into swagger-codegen project folder thru terminal in my mac
3. mvn clean package -DskipTests. If I don't skip tests, it was giving some errors.
4. I have access to address service's swagger URL, so I saved the json from that swagger. Above is the swagger json, an I saved as '/Users/kiran/Downloads/test/address.json'
5. Now, I am giving this command thinking it will generate the Java code, and I am getting error specified in below section
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i /Users/kiran/Downloads/test/address.json -l java -o /Users/kiran/Downloads/test/Address 

##### Error I am getting

`[main] INFO io.swagger.parser.Swagger20Parser - reading from /Users/kiran/Downloads/test/address.json
[main] INFO io.swagger.parser.Swagger20Parser - reading from /Users/kiran/Downloads/test/address.json
[main] INFO io.swagger.codegen.ignore.CodegenIgnoreProcessor - No .swagger-codegen-ignore file found.
Exception in thread "main" java.lang.RuntimeException: missing swagger input or config!
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:766)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:307)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)`

##### Related issues/PRs

None

##### Suggest a fix/enhancement

Please advise why it is failing to generate Address service

**Comment by wing328** [comment]
we only support openapi-generator
