### ISSUE TITLE
[REQ] [Python] Documentation is not clear on how to get modeled data from API

### ISSUE THREAD

**Issue by syntaxaire** [OpenAPITools/openapi-generator#14486]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

1. With the Python client generator, the documentation indicates that a model is returned from the index method, but it returns an instance of `ApiResponseFor200`. Expected: one of the generated model list classes. In fact, the model list class that is expected **is** imported in the automatically generated code sample in the documentation, but then it is not used.

In the example documentation included at the end of this comment, the return type of the `activity_index` function is given as `ActivityList activity_index()`, and `ActivityList` is imported but not used.

2. The `ApiResponseFor200` object contains deserialized data in its `body` attribute, but in instances of `DynamicSchema`. This is not addressed in the documentation. Expected: one of the generated model classes.

3. If the actual behaviour of the client is intended, it's not clear how the models can ever be instantiated from an API server.

##### openapi-generator version

Latest master

##### OpenAPI declaration file content or url

Any spec will do, but I am using the spec downloadable from https://app.clio.com/api/v4/documentation

Generated with:
`java -jar openapi-generator-cli.jar generate --global-property skipFormModel=false --enable-post-process-file -i openapi-fixed.json -g python -o openapi-client`

##### Steps to reproduce

Generate any client library and then execute the sample code from the documentation.

# Actual documentation
Below this line is a sample of the generated documentation.

# **activity_index**
<a name="activity_index"></a>
> ActivityList activity_index()

Return the data for all Activities

Outlines the parameters, optional and required, used when requesting the data for all Activities

### Example

```python
import openapi_client
from openapi_client.apis.tags import activities_api
from openapi_client.model.error import Error
from openapi_client.model.activity_list import ActivityList
from pprint import pprint
# Defining the host is optional and defaults to https://app.clio.com/api/v4
# See configuration.py for a list of all supported configuration parameters.
configuration = openapi_client.Configuration(
    host = "https://app.clio.com/api/v4"
)

# Enter a context with an instance of the API client
with openapi_client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = activities_api.ActivitiesApi(api_client)

    # example passing only optional values
    query_params = {
        'activity_description_id': 1,
        'calendar_entry_id': 1,
        'communication_id': 1,
        'contact_note_id': 1,
        'created_since': "1970-01-01T00:00:00.00Z",
        'end_date': "1970-01-01T00:00:00.00Z",
        'expense_category_id': 1,
        'fields': "fields_example",
        'flat_rate': True,
        'grant_transaction_id': 1,
        'ids[]': 1,
        'limit': 1,
        'matter_id': 1,
        'matter_note_id': 1,
        'order': "id(asc)",
        'page_token': "page_token_example",
        'query': "query_example",
        'start_date': "1970-01-01T00:00:00.00Z",
        'status': "billed",
        'task_id': 1,
        'type': "TimeEntry",
        'updated_since': "1970-01-01T00:00:00.00Z",
        'user_id': 1,
    }
    header_params = {
        'X-API-VERSION': "X-API-VERSION_example",
    }
    try:
        # Return the data for all Activities
        api_response = api_instance.activity_index(
            query_params=query_params,
            header_params=header_params,
        )
        pprint(api_response)
    except openapi_client.ApiException as e:
        print("Exception when calling ActivitiesApi->activity_index: %s\n" % e)
```

**Comment by spacether** [comment]
api_response.body DynamicSchema instances subclass the class described in the body of ApiResponse200

**Comment by spacether** [comment]
So I just generated a client from the above spec file.
Looking at the same activity_index route, the docs describe the response as:
```
### Return Types, Responses

Code | Class | Description
------------- | ------------- | -------------
n/a | api_client.ApiResponseWithoutDeserialization | When skip_deserialization is True this response is returned
200 | [ApiResponseFor200](#activity_index.ApiResponseFor200) | Ok
400 | [ApiResponseFor400](#activity_index.ApiResponseFor400) | Bad Request
401 | [ApiResponseFor401](#activity_index.ApiResponseFor401) | Unauthorized
403 | [ApiResponseFor403](#activity_index.ApiResponseFor403) | Forbidden
429 | [ApiResponseFor429](#activity_index.ApiResponseFor429) | Too Many Requests

So for a 200 status response, the return type is ApiResponseFor200, which docs define as

#### activity_index.ApiResponseFor200
Name | Type | Description  | Notes
------------- | ------------- | ------------- | -------------
response | urllib3.HTTPResponse | Raw response |
body | typing.Union[SchemaFor200ResponseBodyApplicationJsonCharsetutf8, ] |  |
headers | Unset | headers were not defined |

# SchemaFor200ResponseBodyApplicationJsonCharsetutf8
Type | Description  | Notes
------------- | ------------- | -------------
[**ActivityList**](../../models/ActivityList.md) |  |

So the api_response.body should be of type ActivityList
```

Let's try it out in code:
```
import unittest
from unittest.mock import patch

import openapi_client
from openapi_client import schemas, api_client, configuration
from openapi_client.apis.tags import activities_api
from openapi_client.model.activity_list import ActivityList
from openapi_client.paths.activities_json import get
from pprint import pprint

import json
import typing

import urllib3
from urllib3._collections import HTTPHeaderDict


class ApiTestMixin(unittest.TestCase):
    json_content_type = 'application/json'
    user_agent = 'OpenAPI-Generator/1.0.0/python'

    @classmethod
    def assert_pool_manager_request_called_with(
        cls,
        mock_request,
        url: str,
        method: str = 'POST',
        body: typing.Optional[bytes] = None,
        content_type: typing.Optional[str] = None,
        accept_content_type: typing.Optional[str] = None,
        stream: bool = False,
    ):
        headers = {
            'User-Agent': cls.user_agent
        }
        if accept_content_type:
            headers['Accept'] = accept_content_type
        if content_type:
            headers['Content-Type'] = content_type
        kwargs = dict(
            headers=HTTPHeaderDict(headers),
            preload_content=not stream,
            timeout=None,
        )
        if content_type and method != 'GET':
            kwargs['body'] = body
        mock_request.assert_called_with(
            method,
            url,
            **kwargs
        )

    @staticmethod
    def headers_for_content_type(content_type: str) -> typing.Dict[str, str]:
        return {'content-type': content_type}

    @classmethod
    def response(
        cls,
        body: typing.Union[str, bytes],
        status: int = 200,
        content_type: str = json_content_type,
        headers: typing.Optional[typing.Dict[str, str]] = None,
        preload_content: bool = True
    ) -> urllib3.HTTPResponse:
        if headers is None:
            headers = {}
        headers.update(cls.headers_for_content_type(content_type))
        return urllib3.HTTPResponse(
            body,
            headers=headers,
            status=status,
            preload_content=preload_content
        )

    @staticmethod
    def json_bytes(in_data: typing.Any) -> bytes:
        return json.dumps(in_data, separators=(",", ":"), ensure_ascii=False).encode('utf-8')

    def test_activity_index(self):

        config_with_auth = configuration.Configuration(
            api_key={'api_key': 'someKey'},
            host = "https://app.clio.com/api/v4"
        )
        used_api_client = api_client.ApiClient(configuration=config_with_auth)
        api_instance = activities_api.ActivitiesApi(api_client=used_api_client)
        with patch.object(urllib3.PoolManager, 'request') as mock_request:
            response_json = {
                "data": [
                    {
                    "id": 0,
                    "etag": "string",
                    "type": "TimeEntry",
                    "date": "2019-08-24",
                    "quantity_in_hours": 0,
                    "rounded_quantity_in_hours": 0,
                    "quantity": 0,
                    "rounded_quantity": 0,
                    "quantity_redacted": True,
                    "price": 0,
                    "note": "string",
                    "flat_rate": True,
                    "billed": True,
                    "on_bill": True,
                    "total": 0,
                    "contingency_fee": True,
                    "created_at": "2019-08-24T14:15:22Z",
                    "updated_at": "2019-08-24T14:15:22Z",
                    "reference": "string",
                    "non_billable": True,
                    "non_billable_total": 0,
                    "activity_description": {},
                    "expense_category": {},
                    "bill": {},
                    "communication": {},
                    "client_portal": {},
                    "matter": {},
                    "matter_note": {},
                    "contact_note": {},
                    "subject": {},
                    "timer": {},
                    "user": {},
                    "utbms_expense": {},
                    "vendor": {},
                    "calendar_entry": {},
                    "task": {},
                    "text_message_conversation": {},
                    "document_version": {}
                    }
                ]
            }
            body = self.json_bytes(response_json)
            mock_request.return_value = self.response(
                body,
                content_type="application/json; charset=utf-8"
            )

            query_params = {
            }
            header_params = {
                'X-API-VERSION': "X-API-VERSION_example",
            }
            api_response = api_instance.activity_index(
                query_params=query_params,
                header_params=header_params,
            )
            assert isinstance(api_response, get.ApiResponseFor200)
            assert isinstance(api_response.response, urllib3.HTTPResponse)
            assert isinstance(api_response.body, ActivityList)
            assert isinstance(api_response.headers, schemas.Unset)
            assert api_response.response.status == 200
            print(api_response.body.__class__.__bases__)


if __name__ == '__main__':
    unittest.main()
```

From running the above example the code works and we get this output:
```
(venv) Justins-MacBook-Air:clio_api justinblack$ python test.py 
/Users/justinblack/Desktop/clio_api/openapi-client/openapi_client/api_client.py:919: DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTPResponse.headers.get(name, default).
  content_type = response.getheader('content-type')
(<class 'openapi_client.model.activity_list.ActivityList'>, <class 'frozendict.frozendict'>)
.
----------------------------------------------------------------------
Ran 1 test in 0.011s

OK
```
So the payload is deserialized, and it is of type ActivityList + frozendict
Per the readme `All validated data is instantiated in an instance that subclasses all validated Schema classes and Decimal/str/tuple/frozendict/NoneClass/BoolClass/bytes/io.FileIO`

**Comment by spacether** [comment]
Changed from bug to request categorization because the code is working and this is a documentation request. @syntaxaire if I don't hear back from you in a week or two I will close this issue as there is no actionable feedback yet on what is missing from the docs

**Comment by spacether** [comment]
Closing this because it has been a week since it was filed and no one provided additional feedback on what was missing/should be added to the docs

**Comment by syntaxaire** [comment]
@spacether As actionable feedback, I think that part of my confusion in reading this doc - as someone unfamiliar with it - is the doc structure. The key part that you point out above is the return types for `activity_index`. In the headers of the doc, they are listed as being the return types for a subsection of `XAPIVERSIONSchema`. I would never have looked here. Screenshot included showing how these sections are logically separated. The return types is at the bottom.
![image](https://user-images.githubusercontent.com/2661404/215804160-b50e94f5-4b0a-4c3e-9e32-4c1d39dd9f79.png)

**Comment by spacether** [comment]
The order of documentation is: endpoint name, inputs, outputs.
Why would you never have looked there? Outputs are after the inputs.

What would help here?
1. Higher level headings like `<h2>` inputs and `<h2>` responses with all the deeper definitions in `<h3>`?
2. Moving the return-types section right after the parameters section?
3. Does [this documentation](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/2_0_0/samples/openapi3/client/petstore/python/docs/apis/tags/fake_api/parameter_collisions.md) read better from my v2.0.0 branch of the generator?

**Comment by syntaxaire** [comment]
I don't think humans read lengthy technical docs by scrolling from the top to the bottom, reading every line - especially when there are dozens of pages of near identical, machine generated sections. In the new example you link, the return types are still at the bottom, under what is, hierarchically, the incorrect section.

![image](https://user-images.githubusercontent.com/2661404/215823443-719e3aff-5705-4ba9-8e1b-97ae05215fe2.png)

I think the actual technical issue is that the schema definitions between the relevant sections are automatically inserted with `#` top level headings. In order for the table of contents to make sense, this material would have to begin at the `####` level.

**Comment by spacether** [comment]
So suggestion 1 that I mentioned is what you want

**Comment by spacether** [comment]
@syntaxaire what do you think of this update?
- https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/v2_documentation_improvements/samples/openapi3/client/petstore/python/docs/apis/tags/fake_api/parameter_collisions.md#responsefor200contentapplication_jsonschema
- A table of contents has been added to the top of the document with links to `Arguments` and `Response Types`
- Indentation is now properly hierarchical

**Comment by syntaxaire** [comment]
That documentation makes sense to me.

**Comment by spacether** [comment]
Hmm one limitation here is that headers only go to 6 levels of depth.
So if one has an inline schema that has more than 6 levels of depth:
- schema docs stop working
- anchors stop working
