### ISSUE TITLE
[BUG][typescript-axios] Type error due to AxiosRequestConfig headers no longer being optional

### ISSUE THREAD

**Issue by Alesion30** [OpenAPITools/openapi-generator#14494]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using typescript-axios, type error because headers in AxiosRequestConfig is no longer optional since axios@1.2.3.

[AxiosRequestConfig(axios@1.2.3)](https://github.com/axios/axios/blob/v1.2.3/index.d.ts#L329)

[AxiosRequestConfig(axios@1.2.2)](https://github.com/axios/axios/blob/v1.2.2/index.d.ts#LL292C5-L292C5)

```ts
Type error: Property 'headers' is missing in type '{}' but required in type 'AxiosRequestConfig<any>'.

  35 |          * @throws {RequiredError}
  36 |          */
> 37 |         usersGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
     |                          ^
  38 |             const localVarPath = `/users`;
  39 |             // use dummy base URL string because the URL constructor only accepts absolute URLs.
  40 |             const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
```

##### openapi-generator version

6.2.1

##### Generation Details

Using [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli).

```sh
openapi-generator generate -g typescript-axios -i path/to/openapi.yml -o path/to
```

**Comment by KanzakiLove** [comment]
I'm facing the same issue right now, waiting for any suggestions

**Comment by sambernard** [comment]
I'm seeing this as well, and have locked my repos to use 1.2.1.

There's a discussion about this on the axios repo here https://github.com/axios/axios/issues/5476

**Comment by bjorgvino** [comment]
I believe this https://github.com/axios/axios/pull/5420 reverts the non-backwards compatible change in axios between 1.2.1 and 1.2.3 and that version 1.2.4 will fix this issue.

**Comment by bjorgvino** [comment]
Axios 1.2.4 is out now and I've verified that it fixes this issue for me at least. 🙏🏼

**Comment by Alesion30** [comment]
I too can confirm that this issue has been resolved and will close this issue. Thanks.
