### ISSUE TITLE
Unable to specify Kotlinx multi-platform datetime library

### ISSUE THREAD

**Issue by AlexTrotsenko** [OpenAPITools/openapi-generator#14490]
As far as I see, there is planned option to use Kotlinx multi-platform _datetime_ library.
https://github.com/OpenAPITools/openapi-generator/pull/7353/files#diff-63deaec8941f638e7aaaeee452ad3d3d823f0d931bec0317e52bb670e6c7547c

However when I specify `dateLibrary=kotlinx` it has no effect and properties with type String are created.

They are still not present in the latest generator description in the dateLibrary section:
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/kotlin.md

What is the best way to have the support for the `kotlinx.datetime` added to the generator? From the 1st look it should not be much different from Java8 DateTime classes.

**Comment by marco-eckstein** [comment]
I have the same problem/question.
