### ISSUE TITLE
[REQ][python-nextgen] make float parsing more lenient

### ISSUE THREAD

**Issue by tnielens** [OpenAPITools/openapi-generator#14499]
If a response json field is an int (`1`), although the target field type is float (`1.0`) , the response parsing fails with an error like 
```
ValidationError: 1 validation error for <ClassName>
<fieldName>
  value is not a valid float (type=type_error.float)
  ```

## Describe the solution you'd like
  Can the parsing be more lenient? Former python generators parsed this more leniently.

## Describe alternatives you've considered
None

## Additional context
I'm trying to use the latest python client code generator. Btw, great job on the source compatibility 👍 .

**Comment by spacether** [comment]
Fyi if you are open to using the `python` generator we have a CI verified test for this use case at:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/3_0_3_unit_test/python/test/test_models/test_integer_type_matches_integers.py#L50
```
    def test_a_float_with_zero_fractional_part_is_an_integer_passes(self):
        # a float with zero fractional part is an integer
        IntegerTypeMatchesIntegers.from_openapi_data_oapg(
            1.0,
            _configuration=self._configuration
        )
```

**Comment by tnielens** [comment]
@spacether thanks. We have many projects based on clients generated by the python-prior generator. The python-nextgen sources look more compatible than the current `python` one. Also the models are based on pydantic which we have experience with and appreciate. `python-nextgen` looks like a better fit for us.

**Comment by nmoreaud** [comment]
It seems legitimate to parse `{"field": 1}` as a valid float value

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/14618 to add an option to make float's strict type configurable.

**Comment by tnielens** [comment]
Tested successfully on 3746a206.
