### ISSUE TITLE
When yml file not found, returns parsing errors

### ISSUE THREAD

**Issue by alexcuesta** [OpenAPITools/openapi-generator#1449]
##### Description

When providing an non existing file to the generator, it returns parsing errors instead of a simple message saying "file not found".

It is confusing.

##### openapi-generator version

0.5.0

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

og unexistingfile.yml markdown

##### Steps to reproduce

Just run the command.

##### Suggest a fix/enhancement

What about a message saying: File not found.

**Comment by ackintosh** [comment]
Thanks for reporting this issue!

Your suggestion looks good. 👍 I'll working on the fix.

**Comment by ackintosh** [comment]
@alexcuesta  The PR which adds the error message has been merged. ✨ Please give it a try with latest master.
