### ISSUE TITLE
[BUG][ELIXIR] Bug generating elixir connection.ex module (Typo in the mustache file)

### ISSUE THREAD

**Issue by MananV-UNI** [OpenAPITools/openapi-generator#14506]
#### Bug Report Checklist

- [YES] Have you provided a full/minimal spec to reproduce the issue?
- [] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [] Have you searched for related issues/PRs?
- [YES] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Generated an elixir specification for Azure SDK. The connection.ex file being generated has typo's. Specifically, "Tesla.Middleware.Headers" is generated as "Tesla.Middlware.Headers". This does not allow us to send requests.

##### openapi-generator version

Version 6.2.1

##### OpenAPI declaration file content or url

File: connection.ex.mustache (https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/elixir/connection.ex.mustache)

##### Generation Details

Language: Elixir
Libraries: Azure REST API Specs (https://github.com/Azure/azure-rest-api-specs)

##### Steps to reproduce

1. Clone the Azure Rest API Specs Repo
2. Run the CLI generator on the following file: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/resources/resource-manager/Microsoft.Resources/stable/2020-01-01/subscriptions.json
3. Write some code to test listing subscriptions.
4. View the error

##### Related issues/PRs

-

##### Suggest a fix

Fix the typo.

**Comment by wing328** [comment]
Can you please file a PR with the fix?
