### ISSUE TITLE
Help: usage queries

### ISSUE THREAD

**Issue by boardtc** [OpenAPITools/openapi-generator#14508]
I can't find a mailing list or alternative place for asking questions for asking usage questions, is there one? Please lt me know any I can delete this quey.

In the absence, I am posting here. I was using the[ issue 13124](https://github.com/OpenAPITools/openapi-generator/issues/13124) but I don't want to spam that issue with questions and also hope there might be more visibility with direct questions here.

I am moving from 5.0.0 to 6.3.0:

1. I generate my API to the resources directory, A copy is done by maven-resources-plugin:3.3.0 to copy the generated files from resources to target, I am not including maven-resources-plugin:3.3.0 in my pom and I don't see it in the plugin pom either so I am confused what calls the goal org.apache.maven.plugins:maven-resources-plugin:3.3.0:resources. If it is related to this plugin or not I would appreciate someone letting me know.
2. With the latest I am getting Gradle artefacts created, whereas this did not happen with v5. I have not had any luck stopping that from happening using .openapi-generator-ignore, is there a way?
3. One user pointed out that no one worries about the Gradle artefacts being created so I am wondering if others do the opposite of what I am doing and generate straight to target and then only copy the java API back to resources?

**Comment by borsch** [comment]
@boardtc there is Slack community https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

Copied link from this page https://openapi-generator.tech/

**Comment by boardtc** [comment]
I didn't know about that, thanks very much.
