### ISSUE TITLE
[REQ] Upgrade typescript-axios to axios@^1

### ISSUE THREAD

**Issue by segevfiner** [OpenAPITools/openapi-generator#14517]
### Is your feature request related to a problem? Please describe.

axios v1 has a few breaking changes, in types, and otherwise, the current generated client is for axios@^0.27 and requires as such in the `package.json`, it would be nice to update it to use `axios@v1`

## Describe the solution you'd like

Upgrade typescript-axios to generate a client for axios@v1

## Describe alternatives you've considered

Keep using outdated axios

**Comment by caioquirino** [comment]
PR on the way: https://github.com/OpenAPITools/openapi-generator/pull/16977
