### ISSUE TITLE
[REQ][jaxrs-spec] Config option to generate StreamingOutput instead of File as response type

### ISSUE THREAD

**Issue by kariem** [OpenAPITools/openapi-generator#14527]
Instead of using `java.io.File` as response type, I would like the generator to use `javax.ws.rs.core.StreamingOutput`. Except for actually serving files, this option would simplify implementation and improve performance by wrapping an `OutputStream`.

## Solution

It would be great to add a configuration option similar to `returnResponse`:

**Name**: `returnStreamingOutput` or `returnStreamingOutputForBinary`

**Description**: Whether the generated API interface should return `javax.ws.rs.core.StreamingOutput` instead of `java.util.File` for a binary response type.

## Alternatives

I currently extend `JavaJAXRSSpecServerCodegen` and override `importMapping` and `typeMapping`. These are actually only two lines of code. See [this response](https://stackoverflow.com/a/75240010/12039) on StackOverflow for the details and more context.

## Additional context

I currently use `jaxrs-spec` generator with the following settings (via maven plugin, formatted for readability):

| Name                    | Value |
|-------------------------|-------|
| hideGenerationTimestamp | true  | 
| interfaceOnly           | true  | 
| useSwaggerAnnotations   | false | 

A schema definition of something like this

``` yml
/{id}:
  get:
    summary: Get the given document as PDF
    operationId: getDocument
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
    responses:
      200:
        description: Get the PDF document
        content:
        application/pdf:
          schema:
          type: string
          format: binary
```

will generate a java interface with this method

``` java
@GET
@Path("/{id}")
@Produces({"application/pdf"})
File getDocument(@PathParam("id") String id)
```

I would prefer this

``` java
@GET
@Path("/{id}")
@Produces({"application/pdf"})
StreamingOutput getDocument(@PathParam("id") String id)
```

**Comment by borsch** [comment]
@kariem You can archive similar result just by using TypeMapping+ImportMapping

```xml
<plugin>
  <groupId>org.openapitools</groupId>
  <artifactId>openapi-generator-maven-plugin</artifactId>
  <version>6.2.1</version>
  <configuration>
    .. rest of configuration ..
    <typeMappings>
      <typeMapping>binary=OutputStream</typeMapping>
      <typeMapping>file=OutputStream</typeMapping>
    </typeMappings>
    <importMappings>
      <importMapping>OutputStream=my.custom.OutputStream</importMapping>
    </importMappings>
  </configuration>
  <executions>
    .. your executions ..       
  </executions>
</plugin>
```

**Comment by kariem** [comment]
@borsch I did not see that. Thank you very much.

Would it be a good idea to file a PR to extend the current documentation with one example?

**Comment by borsch** [comment]
@kariem I think you can do that

**Comment by kariem** [comment]
@borsch Thank you for the help! Closing this.
