### ISSUE TITLE
[BUG] [JAVA] [webclient] `addXYZ` Builder Method in Pojo produces `NullPointerException` for nullable array properties

### ISSUE THREAD

**Issue by kzander91** [OpenAPITools/openapi-generator#14583]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

For nullable arrays, the POJO generated by 6.3.0 no longer initializes the property with an empty list when using the `addXYZ(T item)` builder method to add an item to the property. This produces a `NullPointerException`. With 6.2.1, if the `JsonNullable` didn't contain a value, it was initialized with a new `ArrayList`.

Generated builder method with 6.2.1:
```java
public class TestObject {
  // other stuff

  private JsonNullable<List<String>> nullableArrayProp = JsonNullable.<List<String>>undefined();

  // other stuff

  public TestObject addNullableArrayPropItem(String nullableArrayPropItem) {
    if (this.nullableArrayProp == null || !this.nullableArrayProp.isPresent()) {
      this.nullableArrayProp = JsonNullable.<List<String>>of(new ArrayList<>()); // <-- initialized with empty list
    }
    try {
      this.nullableArrayProp.get().add(nullableArrayPropItem); // <-- no NPE here
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  // other stuff
}
```
Generated builder method with 6.3.0:
```java
public class TestObject {
  // other stuff

  private JsonNullable<List<String>> nullableArrayProp = JsonNullable.<List<String>>undefined();

  // other stuff

  public TestObject addNullableArrayPropItem(String nullableArrayPropItem) {
    if (this.nullableArrayProp == null || !this.nullableArrayProp.isPresent()) {
      this.nullableArrayProp = JsonNullable.<List<String>>of(null); // <-- initialized with null
    }
    try {
      this.nullableArrayProp.get().add(nullableArrayPropItem); // NPE here
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  // other stuff
}
```

##### openapi-generator version

6.3.0 (no errors with 6.2.1)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
    title: Title
    version: "1"
paths:
  /test:
    get:
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestObject'
components:
  schemas:
    TestObject:
      type: object
      properties:
        myNullableArrayProp:
          type: array
          nullable: true
          items:
            type: string
```

##### Generation Details

`java -jar openapi-generator-cli-6.3.0.jar generate -g java --library webclient -i spec.yaml -o out`

##### Steps to reproduce

1. Model with attribute of type `array` and `nullable: true`.
2. Generate with generator `java` and library `webclient`.
3. `TestObject#addMyNullableArrayPropItem` initializes property value with `null`, causing a `NullPointerException` in the next statement.

##### Related issues/PRs

#14130

##### Suggest a fix

Check if the property's type is `array`, initialize it with an empty `ArrayList`, as before.

**Comment by wing328** [comment]
can you set the option `containerDefaultToNull` to true to see if that works?

**Comment by kzander91** [comment]
Both
`java -jar openapi-generator-cli-6.3.0.jar generate -g java --library webclient --additional-properties=containerDefaultToNull=false -i spec.yaml -o out`
and
`java -jar openapi-generator-cli-6.3.0.jar generate -g java --library webclient --additional-properties=containerDefaultToNull=true -i spec.yaml -o out`
produce identical output and don't fix this.

**Comment by wing328** [comment]
what about setting `nullable` to false instead?

**Comment by kzander91** [comment]
With `nullable: false` and `containerDefaultToNull=false`, the NPE is fixed:
```java
  public TestObject addMyNullableArrayPropItem(String myNullableArrayPropItem) {
    if (this.myNullableArrayProp == null) {
      this.myNullableArrayProp = new ArrayList<>();
    }
    this.myNullableArrayProp.add(myNullableArrayPropItem);
    return this;
  }
```
With `nullable: false` and `containerDefaultToNull=true`, it is not:
```java
  public TestObject addMyNullableArrayPropItem(String myNullableArrayPropItem) {
    if (this.myNullableArrayProp == null) {
      this.myNullableArrayProp = null;
    }
    this.myNullableArrayProp.add(myNullableArrayPropItem);
    return this;
  }
```

**Comment by wing328** [comment]
thanks for the info. i'll try to come up with a PR to address it this or next week.

**Comment by tofi86** [comment]
Also happens for the `JavaSpring` generator.

**Comment by MelleD** [comment]
@wing328 do you know why this changes from a empty collection to a null value?

For us the empty collection (List or Set) was fine and works.

**Comment by wing328** [comment]
Hi all,

I've filed https://github.com/OpenAPITools/openapi-generator/pull/14703. Can you please pull it to give it a try and see if it addresses the issues in your use cases?

Thanks.

**Comment by wing328** [comment]
Hi,

I've file a fix: https://github.com/OpenAPITools/openapi-generator/pull/14703. Please test it when you've time to confirm it addresses the issues in your use cases.

Thank you.

**Comment by wing328** [comment]
PR merged. Please give it a try with the SNAPSHOT JAR https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.3.0-SNAPSHOT/openapi-generator-cli-6.3.0-20230201.075320-98.jar and let me know if you still encounter the issue.

**Comment by kzander91** [comment]
@wing328: The SNAPSHOT jar produces identical output and thus doesn't fix the issue.
I tried all four scenarios from [my previous comment](https://github.com/OpenAPITools/openapi-generator/issues/14583#issuecomment-1412430151).

**Comment by wing328** [comment]
Can you try https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.4.0-SNAPSHOT/openapi-generator-cli-6.4.0-20230216.072505-21.jar instead ? (6.4.0-SNAPSHOT JAR)

Sorry that the one I provided earlier was for v6.3.0 (which was released already).

**Comment by kzander91** [comment]
The new snapshot fixed the issue. Give me a bit more time to verify that with my actual application.

**Comment by wing328** [comment]
Please run more tests 🙏

**Comment by kzander91** [comment]
@wing328: I successfully tested the snapshot with my actual application, so this fix works for me.

**Comment by VinceGall** [comment]
Same issue
