### ISSUE TITLE
[REQ] Prevent from casting a "date-time"-format into Date automatically

### ISSUE THREAD

**Issue by sebastian-ludwig** [OpenAPITools/openapi-generator#14595]
I am using the "typescript-fetch" generator and would like to keep ISO-Dates as a string and avoid the automatic casting via `new Date()` and vice versa. It seems to be more flexible when working with strings in input fields.

I would like to have a config flag, to opt-in or out for casting.

If you have got an alternative solution, that is working right now (except of modifying all the relevant templates) I would appreciate it.

**Comment by borsch** [comment]
@sebastian-ludwig try to add `--type-mappings DateTime=string` to your generator configuration. Also you can use `--type-mappings Date=string` for dates

**Comment by sebastian-ludwig** [comment]
@borsch Thank you very much
