### ISSUE TITLE
Discussion: no SNAPSHOT version on master

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#146]
Discussed in #123:

@jimschubert:

> I’d recommend against pushing a -SNAPSHOT dep to master. This will prevent us from being able to run git bisect to detemine when a regression was introduced.

This is a very important rule, and I think that we should enforce this in our build.

----
In #123 there was a lot of discussion about about trying somehow `2.0.1-SNAPSHOT` of swagger-parser, but I think that the discussion is valid for any of our dependencies. Sometimes we want to try something before the release in order to have time to report issue.

Example given by @wing328:

> Definitely a valid point but I would suggest using the SNAPSHOT version of 2.0.1 so as to uncover potential issues before the official release. There were issues (regressions) upgrading to the latest swagger parser before and that's why we are using the latest SNAPSHOT version in the master to avoid running into similar issue.

---
Proposition by @jimschubert:

> Would it be out of the question to commit a local lib of the SNAPSHOT every 1-2 days? we can put the jar (and any transient SNAPSHOT jars) in a lib folder as unmanaged artifacts. They'd be in the class path and compiled into the shadow jar. 
This way we would have repeatable builds, and still be able to evaluate the changes across branches.

My reaction so far:

> I do not think that this is the maven way of handling dependencies.
> 
> It will cause trouble with people using us as dependencies in their maven or gradle build. If they are also managing dependencies their, they will not be aware of our unmanaged artifacts construct.
> One example: if you have the openapi-generator-maven-plugin configured in your build you can override our decision to use swagger-parser 2.0.0 by indicating an other version.
> 
> In addition having jars (binaries) committed in a git repo does not seems right. It is OK for the gradle-wrapper (that is project independent and almost always the same) but not for dependencies.

---

An other idea would be to create an other branch `preview` that works in parallel to `master`. 
From time to time (daily for example) we merge `master` branch into `preview` with a merge commit.

On the `preview` branch we change our version and add a `.preview` or `.p` suffix before `SNAPSHOT` (eg `3.0.0.preview-SNAPSHOT`). This way we can publish this version to a central maven repository (like sonatype oss snapshot)

The code is the same than on master, but we have the flexibility to set some other versions (and snapshot) for our dependencies.

---

This issue is to keep the discussion going on, even when the PR is merged.

Feel free to provide feedback.

**Comment by jimschubert** [comment]
An alternative would be to adopt a gitflow workflow.

https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by jimschubert** [comment]
This has long since been resolved by using a custom build of swagger-parser when we need change that don't exist upstream.

Our repo for swagger-parser intermediate changes is at https://github.com/OpenAPITools/swagger-parser.
