### ISSUE TITLE
[elm-client] Update http operations for elm/http 2.0.0

### ISSUE THREAD

**Issue by andys8** [OpenAPITools/openapi-generator#1461]
[elm/http@2.0.0](https://package.elm-lang.org/packages/elm/http/2.0.0/) was released with a new api. There is a blog post talking about the new api: https://elm-lang.org/blog/working-with-files

The client has to be adapted for the new request type:

#### Current

https://github.com/OpenAPITools/openapi-generator/blob/b24b6df448878cd8eccae234644e5123785295b5/modules/openapi-generator/src/main/resources/elm/api.mustache#L1-L33

#### Api

```elm
request :
    { method : String
    , headers : List Header
    , url : String
    , body : Body
    , expect : Expect msg
    , timeout : Maybe Float
    , tracker : Maybe String
    }
    -> Cmd msg
```

https://package.elm-lang.org/packages/elm/http/2.0.0/Http#request

There is also [expectWhatEver](https://package.elm-lang.org/packages/elm/http/2.0.0/Http#expectWhatever), which could be useful instead of `Http.expectStringResponse (\_ -> Ok ())`

**Comment by trenneman** [comment]
@andys8 can you give the PR a try? I slightly changed the API to prepare it for future additions.
