### ISSUE TITLE
Package name for Configuration Files

### ISSUE THREAD

**Issue by waytoharish** [OpenAPITools/openapi-generator#14613]
Hi Team,
I am trying to generate code with the generator but not able to change the package name for the configuration folder even though I am specifying the package name as below-

java -jar openapi-generator-cli-6.2.1.jar generate -g spring  -i petstore.yaml -o openapicodenew --model-package com.test.model --package-name com.tes.api --api-package com.test.api --artifact-id openapi-spring-boot --group-id com.test

Please can you suggest what wrong I am doing.

**Comment by borsch** [comment]
@waytoharish there is no global property to configure configuration package. Try to add following option `--additional-properties configPackage=you.custom.package`

**Comment by waytoharish** [comment]
Thanks @borsch its worked for me.
