### ISSUE TITLE
Announcement: Upcoming major release 4.0.x

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#1462]
##### Description

The upcoming major release with breaking changes (4.0.x) is scheduled on Jan 31st. There will be no minor release before that and the last patch release 3.3.4 will be on Nov 29th. 4.0.0-beta will be released on Dec 20th.

For a list of breaking changes in 4.0.x, please refer to the [list](https://github.com/OpenAPITools/openapi-generator/pulls?utf8=%E2%9C%93&q=+is%3Apr+milestone%3A4.0.0+)

If you've any question, please reply to let us know.

UPDATE (Jan 31st):
- revised the release date of 4.0.0-beta2 to Jan 31st
- postponed release date of 4.0.0 to Feb 28th instead

**Comment by wing328** [comment]
## Why
As the code base was first created back in 2011, we want to gradually refactor the code base to make it more maintainable as we add more and more features to the project.

## What
We will refactor the base classes (e.g. DefaultCodegen.java, DefaultGenerator.java, CodegenModel, etc) and generators (e.g. GoClientCodegen.java). These changes will not be considered as breaking changes, which are measured with respect to the output (code, documentation, schema, etc) in terms of functionality.

If you heavily customize the generators (e.g. DefaultCodegen.java, GoClientCoidegen.java) to meet your requirements, please contact us via team@openapitools.org so that we can discuss your use case in details and how we can minimize the impact to your usage.

## How
For changes relates to refactoring, we'll label the PRs and issues with "Enhancement: Refactoring" so that users will be able to more easily identify these changes and volunteers can help out with the refactoring as well.

## When
Starting from v4.0.0

**Comment by wing328** [comment]
We're addressing some issues related to how alias to map/array is handled and working on some enhancements related to the parser, and therefore we'll delay the 4.0.0-beta release to the end of this month.

**Comment by jmini** [comment]
`4.0.0-beta2` has been released:
https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.0.0-beta2

Coordinates on maven central:
```xml
<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator</artifactId>
    <version>4.0.0-beta2</version>
</dependency>
```

**Comment by wing328** [comment]
UPDATE: we will need to further postpone the release as we've some ongoing refactoring works (e.g. C# client refactor). We hope to release 4.0.0 by mid-March 2019.

**Comment by weiwunb** [comment]
hi team,

I don't know which should I use, the openapi-generator or swagger-codegen?

quick question, what is the difference between [swagger-codegen](https://github.com/swagger-api/swagger-codegen)?

**Comment by wing328** [comment]
@weiwunb please refer to the [Q&A](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md) for more information.

Let us know if you've further questions.

**Comment by kasimdoctor** [comment]
@wing328 Any ETA/update on when 4.0.0 will be released?

**Comment by wing328** [comment]
We plan to release it in mid-May to better align with the project anniversary.

**Comment by davidwcarlson** [comment]
Any chance of a few more (maybe monthly?) beta releases until then?

**Comment by wing328** [comment]
That sounds reasonable. What about another beta release in the 1st week of April?

**Comment by jmini** [comment]
FYI: [4.0.0-beta3](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.0.0-beta3) was released as scheduled last week.

```xml
<dependency>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator</artifactId>
    <version>4.0.0-beta3</version>
</dependency>
```

**Comment by davidkarlsen** [comment]
@wing328  davidkarlsen :)
Yes - that would ignore the validation errors - but are you aware of the bug (because it is a false positive) - should I create a ticket for it?

**Comment by gpor89** [comment]
Same issue here, did you create a ticket?

**Comment by davidkarlsen** [comment]
@gpor89 nope

**Comment by dnsymphony** [comment]
I just tried the latest because I wanted the change related to OAuth scopes in spring codegen (https://github.com/OpenAPITools/openapi-generator/issues/2603).  The new API interface classes are generated with correct scopes now.  However, I have an attribute on one of my resources called "eTag" and the generated getter for that model class is now geteTag().  Previously, that generated a getter as getETag().  Is that a known breaking change or a bug.  If it's a known change, I will change my code to call the new getter.
