### ISSUE TITLE
[BUG][csharp-netcore] Ignoring EnumMember.Value when converting an list of enums query parameter to string

### ISSUE THREAD

**Issue by JonasSchubert** [OpenAPITools/openapi-generator#14643]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If a query parameter is of type `ICollection` the underlying type will be ignored and it will be cast to an object and then joined using `string.Join`. It might be similar to https://github.com/OpenAPITools/openapi-generator/issues/10107, but now `EnumMember.Value` is considered if standalone - not in a collection.

##### openapi-generator version

6.3.0

##### OpenAPI declaration file content or url

```yaml
UserType:
  type: string
  enum:
    - I
    - X
    - T
  minLength: 1
  maxLength: 1
  description: |
    Contains the user type.
    - `I` - internal
    - `X` - external
    - `T` - team / functional
  example: I
```

```c#
[JsonConverter(typeof(StringEnumConverter))]
public enum UserType
{
    [EnumMember(Value = "I")]
    Internal = 1,

    [EnumMember(Value = "X")]
    External = 2,

    [EnumMember(Value = "T")]
    TeamOrFunctional = 3
}
```

##### Generation Details

- Docker container openapitools/openapi-generator-cli:latest
- for csharp-netcore

`docker run --rm -v ${PWD}/:/local openapitools/openapi-generator-cli generate -i /local/openapi.yaml -g csharp-netcore -o /local/out --additional-properties=aspnetCoreVersion=6.0,buildTarget=program,operationIsAsync=true,packageName=My.Package.Name,swashbuckleVersion=6.5.0 --skip-validate-spec`

##### Steps to reproduce

- Generate a client from above examples and perform a query with an enum as a query parameter.
- The list/collection query parameter will not have the Value from EnumMember but rather their name
  - instead of `"X,T"` it will be `"External,TeamOrFunctional"`

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/10107

##### Suggest a fix

Change [ln 115](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/ClientUtils.mustache#L115) in `ClientUtils` to iterate over every item in a collection and convert them one by one:
```c#
            if (obj is ICollection collection)
            {
                var stringParameterList = new List<string>();
                foreach (var item in collection)
                {
                    stringParameterList.Add(ParameterToString(item, configuration));
                }


                return string.Join(",", stringParameterList);
            }
``` 

`using System.Collections.Generic;` has to be  added additionally.

**Comment by devhl-labs** [comment]
@JonasSchubert Please see if this pr helps. I don't expect it to be completely right for the default RestSharp library, but if you can switch to GenericHost library it should work.
https://github.com/OpenAPITools/openapi-generator/pull/15040
