### ISSUE TITLE
[Java]Generated codes with StringJoiner will cause a compile error for joiner.add() method

### ISSUE THREAD

**Issue by canadazhangsan** [OpenAPITools/openapi-generator#14647]
##### Description

When generating Java codes for enum(Array) parameters, some codes will be generated with two parameters for StringJoiner.add() method which only takes one parameter.

The cause is the mis-placed ")" in the code which makes the 1 parameter to 2.

##### openapi-generator version

The latest version
##### Steps to reproduce

Create an endpoint with parameters with type Array and list of String to make an enum

##### Suggest a fix/enhancement

A sample fixing PR was created here: https://github.com/OpenAPITools/openapi-generator/pull/14646

**Comment by wing328** [comment]
thanks for the PR (#14646). can you please share a spec to reproduce the issue?

**Comment by canadazhangsan** [comment]
> thanks for the PR (#14646). can you please share a spec to reproduce the issue?

We found this issue in our project, I'll try posting some part of the codes here to describe how to reproduce it.
We have an api yaml file with some defined request/response objects like below:
`allowedActions:
  type: array
  uniqueItems: true
  items:
    $ref: "#/components/schemas/allowedActions"
 `
The allowedActions is defined as a type string with enum values like:
`allowedActions:
  type: string
  enum:
    - Value1
    - Value2`
  
With above format, the java code generated for client side has codes like below:
`// add `allowedActions` to the URL query string
if (getAllowedActions() != null) {
  int i = 0;
  for (AllowedActionDTO _item : getAllowedActions()) {
    if (_item != null) {
      try {
        joiner.add(String.format("%sallowedActions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix)),
            URLEncoder.encode(String.valueOf(_item), "UTF-8").replaceAll("\\+", "%20"));
      } catch (UnsupportedEncodingException e) {
        // should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }
  }
}
`
The above code calls StringJoiner.add(CharSequence newElement) which takes one parameter. But the template misplaced a ")" behind `containerSuffix)`, which makes the code to joiner.add(s1, s2) and caused a compile error.

**Comment by wing328** [comment]
so the spec is something like this:

```

    ExampleClass:
      type: object
      properties:
        set_items:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/set_item_ref'

.....

    set_item_ref:
      type: string
      enum:
      - Value1
      - Value2

```

I got a different error instead. In other words, I couldn't repeat the issue.

**Comment by wing328** [comment]
please ignore that. I'm able to repeat the issue and confirm the fix.

thanks for the PR.
