### ISSUE TITLE
[BUG][kotlin-spring] Wildcard imports in generated Kotlin classes

### ISSUE THREAD

**Issue by volsusdev** [OpenAPITools/openapi-generator#14652]
Hi @parenko,

what was the reason for introducing wildcard imports to [kotlin-spring] with one of your last commits (https://github.com/OpenAPITools/openapi-generator/commit/cffe2d0259378373500dbc47609c6c4a97d661ca)? 
We now have the issue that it is not possible anymore to use ktlint for linting the generated code.

![Bildschirmfoto 2023-02-09 um 09 05 19](https://user-images.githubusercontent.com/16232310/217755999-b86352a2-96ea-4dbf-9fac-bcdba3fa7b48.png)

##### openapi-generator version

6.3.0

##### Related issues/PRs

#14369

##### Suggest a fix

If there is no problem with single class imports in this case I would create a PR to change this back for `javax.validation.constraints` imports.

**Comment by parenko** [comment]
As far as I can remember there was a class that was in a different place in Jakarta.  But I don't know which ones right now.  Feel free to change.

**Comment by volsusdev** [comment]
Thanks, then I will make a suggestion with single class imports but with your `{{javaxPackage}}` placeholder.

**Comment by volsusdev** [comment]
I've opened a PR for this: #14899

**Comment by volsusdev** [comment]
fyi: Fix was merged into master.
