### ISSUE TITLE
[Typescript-Angular] modelFileSuffix change dots '.' to slashes '/'

### ISSUE THREAD

**Issue by VincentSurelle** [OpenAPITools/openapi-generator#1467]
##### Description

I'm trying to generate `typescript-angular` api client with pet store sample.
I installed openapi-generator with Homebrew and got version 3.3.3.

When I try to generate with `modelFileSuffix='.model'` with `kebab-case` my dot is changed to a slash.
When I try to generate the same but with `camelCase`, it simply does not appear.

Here is a sample output :

![capture d ecran 2018-11-16 a 12 22 25](https://user-images.githubusercontent.com/1504027/48618925-1406e900-e99b-11e8-9e2a-7ffe9bc6dda0.png)

##### openapi-generator version

3.3.3

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Command line used for generation

`openapi-generator generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -g typescript-angular --additional-properties supportsES6=true,ngVersion='5.2.11',modelSuffix='Model',modelFileSuffix='k.djfgdlmodel' -o ./ts-client-generated-angular`

##### Steps to reproduce

Launch the command above 👼 

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/418

##### Suggest a fix/enhancement

https://github.com/OpenAPITools/openapi-generator/commit/73162cbcca6b1c3c086e2a764dac9c753ed87a0f (Maybe sanitize is responsible for it ?)

**Comment by wing328** [comment]
@VincentSurelle thanks for reporting the issue. My guess is that convertUsingFileNamingConvention is converting dot to slash.

Was it working for you before the commit https://github.com/OpenAPITools/openapi-generator/commit/73162cbcca6b1c3c086e2a764dac9c753ed87a0f ?

cc @smasala

**Comment by tomvangreen** [comment]
I'm having a similar issue. I'm using the model file suffix `.vm` and the generated filename is `model_vm.ts` instead of `model.vm.ts`. I think this might be related.

**Comment by karismann** [comment]
this issue can be closed as i actually tested it with 4.0.0 and it work
