### ISSUE TITLE
[Bug] [Java] [Webclient] Missing models

### ISSUE THREAD

**Issue by fcnjd** [OpenAPITools/openapi-generator#14681]
##### Description
When generating client code for Java and with subtemplate webclient, some important models are left out, making the compilation fail.
Snippet from the Maven output:
```
[ERROR] COMPILATION ERROR :                                                                                             
[INFO] -------------------------------------------------------------                                                    
[ERROR] /C:/dev/openapi-test/src/main/java/org/openapitools/client/api/DraftsApi.java:[7,37] cannot find symbol         
  symbol:   class DraftAPIMultipart                                                                                     
  location: package org.openapitools.client.model                                                                       
[ERROR] /C:/dev/openapi-test/src/main/java/org/openapitools/client/api/DraftsApi.java:[11,37] cannot find symbol        
  symbol:   class DraftProductMultipart                                                                                 
  location: package org.openapitools.client.model                                                                        
etc.
```

##### openapi-generator version
Tested with 6.3.0 and the latest master

##### OpenAPI declaration file content or url
https://gist.github.com/fcnjd/9ab449158cc51d29b1379c80896e062f
I'm sorry for the big file size, but it's the original documentation as provided by IBM.

##### Command line used for generation

openapi-generator-cli generate -g java --library webclient -i IBM_API_Connect_Platform_-_Provider_API-2.0.0.yaml

##### Steps to reproduce
Run the above CLI command, and then do a mvn clean compile and you'll see the errors.

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/14461

##### Suggest a fix/enhancement
A fix is to use SmartBears online tool Swagger Hub, which doesn't have the error, but isn't suitable for my current usecase.

**Comment by martin-mfg** [comment]
Hi @fcnjd,
the same solution as in https://github.com/OpenAPITools/openapi-generator/issues/14461#issuecomment-1505024752 applies here too: If you set `skipFormModel` to `false`, everything should work.
