### ISSUE TITLE
[BUG] default values for references enums are not generated correctly

### ISSUE THREAD

**Issue by robbertvanwaveren** [OpenAPITools/openapi-generator#14689]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

Seen this bug in Java client generation but I think its broken for multiple languages.

##### Description

properties that set a default but references an enum type using allOf results in incompilable java client code.

##### openapi-generator version

regression since 6.3.0 (probably since #14130 was merged)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: Bug
  version: 0.0.1
paths:
  /test:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                test:
                  allOf:
                    - $ref: '#/components/schemas/TestEnum'
                  default: Bar
      responses:
        '200':
          description: Ok
components:
  schemas:
    TestEnum:
      enum:
        - Foo
        - Bar
      type: string
```

##### Generation Details

`openapi-generator-cli generate -i default-for-referenced-enum.yaml -g java -o enum-issue`

results in TestPostRequest.java with line 54 being:
```java
private TestEnum test = Bar;
```
instead of 

```java
private TestEnum test = TestEnum.BAR;
```

##### Steps to reproduce

see Generation Details

##### Related issues/PRs

regression since 6.3.0 (probably since #14130 was merged)

##### Suggest a fix

See linked PR #14692

**Comment by wing328** [comment]
can you pls try the latest master? we've a PR to fix that.

**Comment by robbertvanwaveren** [comment]
@wing328 I started working from a synced master yesterday, its still seems broken without my fix.

**Comment by wing328** [comment]
@robbertvanwaveren I've filed https://github.com/OpenAPITools/openapi-generator/pull/14882 to fix it in the default codegen. I wonder if you can pull it to give it a try when you've time.

(I tested with your spec and the result is good)

**Comment by robbertvanwaveren** [comment]
works like a charm @wing328

**Comment by Midorina** [comment]
Hi. I have this issue in version 7.4.0.

**Comment by mostafazakaria** [comment]
@wing328 I am also facing same issue. My project is kotlin based and I am having size issues with my SDK as because of this issue I am forced to generate enums internally and have alot of duplicates which has a huge impact on final artifact size. Any news on fixing this?

@Midorina any tips on how did you get your problem fixed?
