### ISSUE TITLE
[BUG]  Python Generated client code structure changed, in 6.3.0

### ISSUE THREAD

**Issue by TimothySutton81** [OpenAPITools/openapi-generator#14695]
##### Description

This is more a question on the structural change of the generated client code for python for 6.3.0. Previously we were using 5.3.0, and the resultant code had different structural make up. I could not figure out where in the versioning you documented this change, other than I saw in 6.2.0 you moved to a new generator for python. The crux of my question here is we are going to have to refactor our code for the new generated format, which is fine, but is the new structure to the python generated code stable? Was it expected that rather then importing from an api folder we are now importing apis/tags?
##### openapi-generator version
5.3.0 verse 6.3.0

##### Generation Details
Generated code lay out between 6.3.0 vs 5.3.0

##### Steps to reproduce

Run with latest python generator and run with earlier versions results in a different structure.

##### Suggest a fix
Answer stability question?

**Comment by spacether** [comment]
This new structure is unchanging in minor releases. The 6.2.0 change where python-experimental was swapped in as the main python generator makes its status as stable where breaking changes are no longer allowed outside of major releases. Over 110 repos are successfully using it. How is this ticket a bug?

**Comment by wing328** [comment]
@TimothySutton81 please give `python-nextgen` client generator a try to see if you like the output.
