### ISSUE TITLE
[BUG][Spring][Maven] 6.3.0 generates Schema annotations not compatible with the current dependencies

### ISSUE THREAD

**Issue by okaa-pi** [OpenAPITools/openapi-generator#14693]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Since release 6.3.0, spring generator now generates models using `RequiredMode` parameter, instead of `required`, to fix [deprecation of Schema#required attribute](https://docs.swagger.io/swagger-core/v2.2.7/apidocs/io/swagger/v3/oas/annotations/media/Schema.html#required--)
(See related PR)

But openapi-generator 6.3.0 dependencies still contain version 2.2.4 of swagger-annotations:
```
 \- org.openapitools:openapi-generator:jar:6.3.0:compile
    \- io.swagger.parser.v3:swagger-parser:jar:2.1.6:compile
       \- io.swagger.parser.v3:swagger-parser-v3:jar:2.1.6:compile
          \- io.swagger.core.v3:swagger-core:jar:2.2.4:compile
             \- io.swagger.core.v3:swagger-annotations:jar:2.2.4:compile
```

Which causes the generated classes to import a library that is not included in the project.

##### openapi-generator version

6.3.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Hello API
  version: 1.0.0
servers:
  - url: http://localhost:4200

paths:
  /v1/hello:
    get:
      tags:
        - Hello
      summary: Say Hello
      description: Say Hello
      operationId: sayHello
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessfulOperation'

components:
  schemas:
    SuccessfulOperation:
      type: object
      required:
        - code
      properties:
        code:
          type: string
        message:
          type: string

```

##### Generation Details

Code generated using the Maven plugin:
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator.version}</version>
    <executions>
        <execution>
            <id>generate-v1-api</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/openapi_v1.yaml</inputSpec>
                <generatorName>spring</generatorName>
                <configOptions>
                    <sourceFolder>src/main/java</sourceFolder>
                    <interfaceOnly>true</interfaceOnly>
                    <skipDefaultInterface>true</skipDefaultInterface>
                    <useTags>true</useTags>
                    <useSpringBoot3>true</useSpringBoot3>
                </configOptions>
                <typeMappings>string+time=OffsetTime</typeMappings>
                <importMappings>OffsetTime=java.time.OffsetTime</importMappings>
                <globalProperties>
                    <skipFormModel>false</skipFormModel>
                </globalProperties>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### Steps to reproduce

1. Generate the model classes from provided openapi definition.

##### Related issues/PRs

[PR 14402](https://github.com/OpenAPITools/openapi-generator/pull/14402)

##### Suggest a fix

Update swagger-parser dependency from:
```xml
        <dependency>
            <groupId>io.swagger.parser.v3</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>2.1.6</version>
        </dependency>
```

to:
```xml
        <dependency>
            <groupId>io.swagger.parser.v3</groupId>
            <artifactId>swagger-parser</artifactId>
            <version>2.1.11</version>
        </dependency>
```

**Comment by borsch** [comment]
@okaa-pi could you please provide minimal app example? `swagger-parser@2.1.6` is the dependency of generator itself and doesn't affect generated code. As per you maven plugin setup you should get generated `pom.xml` with 
```xml
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.1.13</version>
        </dependency>
```

**Comment by okaa-pi** [comment]
Okay, so I'm really sorry for the waste of time, I think I just understood now that my project should depend on ``io.swagger.parser.v3:swagger-parser`` and not directly on ``org.openapitools:openapi-generator``.

It used to work with version 5, because it was getting swagger-parser as a transistive dependency.

**Comment by prasannjeet** [comment]
> Okay, so I'm really sorry for the waste of time, I think I just understood now that my project should depend on `io.swagger.parser.v3:swagger-parser` and not directly on `org.openapitools:openapi-generator`.
> 
> It used to work with version 5, because it was getting swagger-parser as a transistive dependency.

I am facing the same issue, and I couldn't really undesrtand how you managed to fix it. Could you let me know how to fix it? Thanks!
