### ISSUE TITLE
[BUG] [Kotlin] Data class must have at least one primary constructor parameter

### ISSUE THREAD

**Issue by alex-hedley** [OpenAPITools/openapi-generator#14710]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm trying to generate a Kotlin class from a Swagger Spec.

Actual Kotlin Class
`class FooList : MutableList<Foo> by ArrayList()`

OpenAPI Generator output
`data class FooList () : kotlin.collections.ArrayList<Foo>()`

Build Error:
> Data class must have at least one primary constructor parameter

##### openapi-generator version

6.3.0

##### Generation Details

```kotlin
import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

plugins {
  id("org.openapi.generator") version "6.3.0"
}

tasks.register<GenerateTask>() { ... }
```

##### Steps to reproduce

...

##### Suggest a fix

Tried adding [No-arg compiler plugin﻿](https://kotlinlang.org/docs/no-arg-plugin.html) but it would prob need to be ran at a certain time in the build?

```kotlin
plugins {
// id("org.jetbrains.kotlin.plugin.noarg") version "1.8.10"
  kotlin("plugin.noarg") version "1.7.21"
}

noArg {
  annotation("com.example.FooList")
}
```

**Comment by sumowrestler** [comment]
Also seeing this in my case there is no annotation to target in the noarg plugin.

**Comment by Perondas** [comment]
I am having the same issue trying to generate a client for [this](https://dataset.api.hub.geosphere.at/v1/openapi-docs) spec.
The data classes: End, EndDate, Start, StartDate and LocationInner are all missing a constructor.
