### ISSUE TITLE
[BUG] [python-nextgen] Generated ApiClient Throws Error With Dict Query Params

### ISSUE THREAD

**Issue by emma-campbell** [OpenAPITools/openapi-generator#14725]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generated `ApiClient` method `parameters_to_url_query` converts `int`, `float`, and `bool` values to strings. It does not do the same for `dict`. As a result passing a `dict` query param to the client results in the following error.

```
TypeError: sequence item 1: expected str instance, dict found
```

Expected output would be to not have this error.

##### openapi-generator version

Tested against `6.3.0` as well as `master`.

##### OpenAPI declaration file content or url

[OpenApi Gist Here](https://gist.github.com/emma-campbell/45bd2194c20e6c601c81a969aafb4107)

##### Generation Details

```sh
./run-in-docker.sh generate -i result_api.json -g python-nextgen -o python-sdk -p disallowAdditionalPropertiesIfNotPresent=false,generateSourceCodeOnly=true,packageName=result_sdk
```
##### Steps to reproduce

1. Generate the client using the CLI options above
2. Use the output client in a python script

```python
from result_sdk.api.runner_api import RunnerApi
from datetime import datetime, timedelta

api = RunnerApi()

end = datetime.utcnow()
start = end - timedelta(days=5)

filter = {
	"$and": [
		{
			"createdOn": {
				"$lte": end.isoformat()
			}
		},
		{
			"createdOn": {
				"$gte": start.isoformat()
			}
		}
	]
}

results = api.get_runner_results(filter=filter)

print(results)
```

Error mentioned before will throw on the `results =` line.

##### Related issues/PRs

Pretty similar to #14334, but here applying to `dict` types.

##### Suggest a fix

I will have a PR shortly for the mustache template.

**Comment by spacether** [comment]
FYI this works in the `python` client per this verification test https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_parameters.py#L143

**Comment by emma-campbell** [comment]
@spacether The spec provided is a minimal reproduction. Truthfully, we tried the `python` first, but ran into issues with recursion errors with specs that worked fine for other languages so decided to give `python-nextgen` a try. This is the only issue we've had with nextgen, so we figured submitting a PR would get us up and running quicker. That, and we prefer the output of `python-nextgen` to `python`.

**Comment by spacether** [comment]
Can you please file a bug for the recursion error that you ran into?

**Comment by emma-campbell** [comment]
@spacether Yep, I can do that later today.

**Comment by spacether** [comment]
@emma-campbell where is the issue? Can you please file it?

**Comment by emma-campbell** [comment]
@spacether Sorry, I ended up getting sick and then now having to play major catchup at work. Creating a minimal reproduction is proving to be a little more challenging than I anticipated. I can try my best to get it up by the end of the weekend.

**Comment by spacether** [comment]
Sorry to hear that. If you want, you can direct message me the spec on slack and I can create the issue. I am there and my name is Justin Black in our slack org.

**Comment by emma-campbell** [comment]
@spacether I've spent some time now trying to reproduce the issue that I previously ran into using the master branch, and for whatever reason I am unable to. If I run into it again, I will be sure to open up a new issue.

As for now, since #14727 was merged in, I will close this issue 😊
