### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by arshadkazmi42** [OpenAPITools/openapi-generator#1474]
##### Description

The link to list of scripts under this cateogry
https://github.com/OpenAPITools/openapi-generator/blob/master/README.md#3---usage
is broken, its redirecting to 404 page.

##### Suggest a fix/enhancement

I think this should be pointed to samples directory here
https://github.com/OpenAPITools/openapi-generator/tree/master/samples

If someone can confirm this, I can create a PR for this.

**Comment by ackintosh** [comment]
@arshadkazmi42 Thanks for reporting this issue!

Correctly, the `"Here is a list of all scripts."` should point to https://github.com/OpenAPITools/openapi-generator/wiki/Samples-folder#scripts . 💡

**Comment by arshadkazmi42** [comment]
Thank you for the correct URL.
I will create a PR for this in some time.
