### ISSUE TITLE
[BUG][Go] Generator results in missing objects when defining inline anyOf, or oneOf

### ISSUE THREAD

**Issue by phegyi81** [OpenAPITools/openapi-generator#14801]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If an inline oneOf or anyOf definition is used below an allOf or oneOf, the generated code will contain the name of the inline defined structure, but the structure itself will not be generated.

If the schema is rearranged to avoid using the inline definition, the missing part is also generated.
One possible way to do this is to define the inline oneOf or anyOf at the top level and reference it from below allOf or oneOf.

##### openapi-generator version

6.4.0

###### oneOf below allOf
[Inline version](https://gist.github.com/phegyi81/425d2bfe756c1bfa72626d3b1d5a3f03)
[Referenced version](https://gist.github.com/phegyi81/df500abad365d21caad4a63873c284d3)

###### anyOf below oneOf
[Inline version](https://gist.github.com/phegyi81/07a086f93efce4d0249ae697883fc463)
[Referenced version](https://gist.github.com/phegyi81/b52a5546116c7b3b49343a6444991672)

##### Generation Details

Nothing special is needed beyond the steps specified in the next section. That is, download the 4 samples and compile them with the linked generator. Two of the samples are the wrongly compilable inline version, while two of them are the properly compilable referenced version.

##### Steps to reproduce

- Download the gists linked above
- Download the [generator script](https://gist.github.com/phegyi81/b18f8b5e5eba67cb62d91f196c5209d0) also
- Run the script `generate.sh`
- Recognise that
  - `AnyOfstringstring` is missing from `go-anyOf-below-oneOf-inline` directory, while it is referenced in `model_b.go`
  - `OneOfDE` and `NullableOneOfDE` are missing from `go-oneOf-below-allOf-inline` directory, while it is referenced in `model_a_all_of_attributes.go`
  - The generated openapi.yaml files are not the same by byte, but they cover practically the same structure

##### Related issues/PRs

#11842
#6161

**Comment by phegyi81** [comment]
A slightly different embedded inline/referenced spec issue is found. If an allOf is embedded in another allOf inline, then the generated type is `*interface{}`. If it is defined on top level and just referenced, the proper type is generated and applied in the go code.

[Inline version](https://gist.github.com/phegyi81/1139d6238a8781f4a5a618b1e5d699b4)
[Referenced version](https://gist.github.com/phegyi81/487abcfd932c4db0292f0e2cb43dd704)

Generator:
```
#!/bin/bash
OPENAPI_GENERATOR_IMG=openapitools/openapi-generator-cli
OPENAPI_GENERATOR_TAG=v6.4.0
GENERATED_DIR=api_generated

rm -rf ${GENERATED_DIR}
for i in A-inline A-referenced; do 
  docker run --user $(id -u):$(id -g) --rm -v "${PWD}:/local" ${OPENAPI_GENERATOR_IMG}:${OPENAPI_GENERATOR_TAG} generate -p enumClassPrefix=true --enable-post-process-file -i /local/${i}.yaml -g go -o /local/${GENERATED_DIR}/go${i}
done
```

**Comment by wing328** [comment]
> If an inline oneOf or anyOf definition is used below an allOf or oneOf, the generated code will contain the name of the inline defined structure, but the structure itself will not be generated.

please give it another try in the latest master as I've just fixed it with https://github.com/OpenAPITools/openapi-generator/pull/17138
