### ISSUE TITLE
[REQ] Feature Request Description

### ISSUE THREAD

**Issue by fjaouen** [OpenAPITools/openapi-generator#14815]
### Is your feature request related to a problem? Please describe.

I'm using the version 6.2.1 of your kotlin-spring openapi-generator.
https://openapi-generator.tech/docs/generators/kotlin-spring/

When we are using a date-time format in our OpenAPI contract, for instance :

createdAt:
  type: string
  format: date-time
  description: Creation date and time
  example: "2021-01-30T08:30:00Z"

the generator maps it to an OffsetDateTime which is correct. But in our case we need to generate a LocalDateTime.

We know that does not respect the OpenAPI standard but we have no really choice.

In the java version https://openapi-generator.tech/docs/generators/java/
it is possible to specify in the option dateLibrary the value java8-localdatetime to accomplish that.

## Describe the solution you'd like

Would it be possible to reproduce in the kotlin-spring the same behaviour that is implemented in the java ?

**Comment by borsch** [comment]
@fjaouen try to specify type mapping like this

Maven plugin:
```xml
<plugin>
	<groupId>org.openapitools</groupId>
	<artifactId>openapi-generator-maven-plugin</artifactId>
	<version>6.4.0</version>
	<configuration>
            <typeMappings>
                <typeMapping>DateTime=java.time.LocalDateTime</typeMapping>
                <typeMapping>date-time=java.time.LocalDateTime</typeMapping>
            </typeMappings>
           .. rest of configuration ..
	</configuration>
</plugin
```

CLI:
```shell
openapi-generator-cli generate  .. rest of configuration .. --type-mappings "DateTime=java.time.LocalDateTime"  --type-mappings "date-time=java.time.LocalDateTime"
```

Gradle:
to be honest I don't use gradle, but there is an property `typeMappings` in `openApiGenerate` so I believe it should be something like this

```groovy
openApiGenerate {
    typeMappings {        // this is of type map<string, string>
         "DateTime": "java.time.LocalDateTime",
         "date-time": "java.time.LocalDateTime"
    }
}
```

**Comment by fjaouen** [comment]
Thank you @borsch for your answer it solved my problem. Here is what I use with grade :

task build(type: GenerateTask) {
               generatorName = "kotlin-spring"
               inputSpec = file.absolutePath
               outputDir = generatedSwaggerSources
               validateSpec = true
               modelPackage = "com.xxx.dto"
               apiPackage = "com.xxx.controller"
               modelNameSuffix = "Dto"
               typeMappings = [
                                            "DateTime": "java.time.LocalDateTime",
                                            "date-time": "java.time.LocalDateTime"
               ]
               configOptions = [
                                            interfaceOnly           : "true",
                                            serializationLibrary    : "jackson",
                                            sortParamsByRequiredFlag: "true",
                                            enumPropertyNaming      : "UPPERCASE",
                                            modelMutable            : "true",
                                            exceptionHandler        : "false"
               ]
}

**Comment by borsch** [comment]
@fjaouen could you please this issue if there is no further questions?
