### ISSUE TITLE
[Java][Resttemplate] Normalize the RestTemplate ApiClient

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#14832]
### Is your feature request related to a problem? Please describe.

Checking all Java clients, the **only** one that defines the ApiClient and XXXApi with the `@Component` annotation is RestTemplate.

With this change, now for RestTemplate (as it is done for the rest of the Java clients) we will have to define one bean as ApliClient and another one as XXXClient.

## Describe the solution you'd like

Remove `@Component` from ApiClient.mustache and api.mustache

- ApiClient.mustache
https://github.com/OpenAPITools/openapi-generator/blob/a4b5b850670ea8b5df193501f9e10e8f308ac51e/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L84

- api.mustache
https://github.com/OpenAPITools/openapi-generator/blob/a4b5b850670ea8b5df193501f9e10e8f308ac51e/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache#L30

**Comment by suntsa** [comment]
Perhaps we should also remove the `@Autowired` annotations? I guess they won't do much good without the `@Component` annotation.
