### ISSUE TITLE
Support for external references in $ref

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#149]
According to the specification ([Reference Object in OAS3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#reference-object)) it is allowed to define references to external files.

For example looking for the `Pet` schema in `other.yaml` in the same repository:

```yaml
$ref: ‘./other.yaml#/components/schemas/Pet'

```

It looks like that the other input file does not need to be a “OpenAPI” yaml/json file at all, it can just be a sub-part of a part:

```yaml
$ref: definitions.yaml#/Pet
```

This is not supported at all by OpenAPI generator.

**Comment by jmini** [comment]
After discussing it with @wing328 :
It is the responsibility of the parser to do it. It works if you parse it like this:

```
        final OpenAPIParser openApiParser = new OpenAPIParser();
        final ParseOptions options = new ParseOptions();
        options.setResolve(true);
        options.setFlatten(true);
        final OpenAPI openAPI = openApiParser.readLocation(inputSpec, null, options).getOpenAPI();
```

---
Test case, in the same folder, put two files:

Main OAS3 file: `main.yaml`

```yaml
openapi: 3.0.1
info:
  title: ping test
  version: '1.0'
servers:
  - url: 'http://localhost:8000/'
paths:
  /some/ping:
    get:
      operationId: pingGet
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: './external.yaml#/SomeObj'
components:
  schemas: {}
```


External file: `other.yaml`

```yaml
SomeObj:
  properties:
    s1:
      type: string
    s3:
      type: string
```

**Comment by jimschubert** [comment]
@jmini Related, swagger-api/swagger-parser#342 covers `$ref` in additional properties. Support was added to the swagger-parser 2.0 branch. When I commented on the linked issue, external refs were only working for JSON docs.
