### ISSUE TITLE
[BUG][JAVA][SERVER][SPRING] Generated java code fails to compile in a special circumstance

### ISSUE THREAD

**Issue by SorenDanielKrum** [OpenAPITools/openapi-generator#14907]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When trying to compile generated java (server) code, the generated code does not compile. 

I drilled a bit in it, the code is generated correctly and compiles when i change one of the following things:
- the header parameter is removed
- the implicitHeaders flag is set to false
- the reactive flag is set to false

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

https://gist.github.com/SorenDanielKrum/2b86bee56a6d6e30f1301035f78d930b
##### Generation Details

See the pom file in the gist provided above. 
##### Steps to reproduce

mvn clean compile
![image](https://user-images.githubusercontent.com/93150632/223688750-04b0b52e-5fa8-4a2e-a9b5-9b02ab535876.png)

**Comment by borsch** [comment]
@SorenDanielKrum could you also share yours `openapi-generator-maven-plugin` configuration?

**Comment by SorenDanielKrum** [comment]
Ay, of course! The pom would be in the gist https://gist.github.com/SorenDanielKrum/2b86bee56a6d6e30f1301035f78d930b, too. I am not aware of any configuration beyond that.
