### ISSUE TITLE
[BUG][JAVA] Fluent setters from inherited from parent return parents type

### ISSUE THREAD

**Issue by leonard84** [OpenAPITools/openapi-generator#14915]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using inheritance via allOf the setters always return the type they are declared on, so using setters declared on the parent type will return `Parent` instead of `Child`.

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: test
  description: >-
    test schema
  version: 1.0.0
servers:
  - url: 'http://test.com'
    description: stage
paths:
  /demo:
    get:
      summary: placeholder summary
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Child'
components:
  schemas:
    Parent:
      type: object
      properties:
        name:
          type: string
    Child:
      x-all-of-name: Child
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
          properties:
            childProperty:
              type: string
```

##### Generation Details

https://github.com/gradle/gradle-enterprise-api-samples/blob/5b9a67556042413337860c47532512046f8765a0/build.gradle.kts#L35-L57

##### Steps to reproduce

Checkout the demo at https://github.com/gradle/gradle-enterprise-api-samples/tree/openapi-generator-issue_inheritance and run build

Will fail with:
```
error: incompatible types: demo.api.model.Parent cannot be converted to demo.api.model.Child
        Child child = new Child().name("bar");
                                      ^
```

##### Suggest a fix
The straight forward [solution](https://stackoverflow.com/a/23895164/16358266) would be to `@Override` all inherited fluent setters on the child types, so that they return the correct type.

So on `Child` add this method

```java
  @Override
  public Child name(String name) {    
    this.name = name;
    return this;
  }
```

**Comment by borsch** [comment]
@leonard84 if you using `lombok` in your project you can fix this by adding `@lombok.SuperBuilder` to `additionalModelTypeAnnotations`

**Comment by leonard84** [comment]
@borsch thanks for the hint, but we don't use lombok.
