### ISSUE TITLE
[BUG][Java] Nullable array creates assignments without value

### ISSUE THREAD

**Issue by bonii-xx** [OpenAPITools/openapi-generator#14948]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When having a nullable array the openapi-generater ceates an assignment statement without value, which doesn't compile (see example below). `openApiNullable` also needs to be false.

It doesn't happen if the field is has a default.

##### openapi-generator version

Started happening with 6.4.0, still happens in latest

##### OpenAPI declaration file content or url

```yaml
nullable_array:
  type: array
  nullable: true
  items:
    type: string
```

[Full specification with more examples](https://gist.github.com/bonii-xx/2786d9850a54a042fb1434b9961d5165#file-openapi-test-yaml)

##### Generation Details

Generate the provided openapi specification with these configurations:

```json
{
  "library": "spring-boot",
  "openApiNullable": false
}
```

To generate it using docker:

```sh
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate \
    -i local/openapi-test.yaml \
    -g spring \
    -o /local/out/java \
    -c /local/config.json
```

Everything is provided in the gist below.

##### Steps to reproduce

https://gist.github.com/bonii-xx/2786d9850a54a042fb1434b9961d5165

Generate this api-spec, either with the maven plugin or the cli generator. The `TestBody` class will contain:

```java
private List<String> nullableRequiredArray = ;
```

and

```java
this.nullableArray = ;
```

which doesn't compile.

**Comment by wing328** [comment]
thanks for reporting the issue. i've filed https://github.com/OpenAPITools/openapi-generator/pull/14959 to fix it.
