### ISSUE TITLE
[BUG][csharp-netcore] Client generated with nullable reference types enabled cannot be built

### ISSUE THREAD

**Issue by davidkaya** [OpenAPITools/openapi-generator#14960]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I generate a C# client, with nullable reference types enabled and target framework set to net7.0, it creates a code that can't be compiled.

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  description: |
    Hello
  version: "1.0.0"
  title: Hello
  termsOfService: 'http://swagger.io/terms/'
servers:
  - url: 'https://hello.io/v2'
paths:
  /hello:
    get:
      summary: Hello
      description: Hello
      operationId: Hello
      responses:
        '200':
          description: UUIDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: uuid
```

##### Generation Details

```
openapi-generator generate -g csharp-netcore -i openapi.yaml --library=generichost --additional-properties=nullableReferenceTypes=true,targetFramework=net7.0
```

##### Steps to reproduce

Run the `openapi-generator` command above and try to build the Solution. 

You will get the following error:

```
/private/tmp/openapi/src/Org.OpenAPITools/Api/DefaultApi.cs(117,35): error CS1061: 'List<Guid>' does not contain a definition for 'Value' and no accessible extension method 'Value' accepting a first argument of type 'List<Guid>' could be found (are you missing a using directive or an assembly reference?) [/private/tmp/openapi/src/Org.OpenAPITools/Org.OpenAPITools.csproj]
```

**Comment by wing328** [comment]
thanks for reporting the issue

cc @devhl-labs
