### ISSUE TITLE
///reference is defined before //tslint:disable which causes linting error

### ISSUE THREAD

**Issue by fuzzzerd** [OpenAPITools/openapi-generator#1498]
##### Description

In generated .ts file; the `///reference` is included above the `//tslint:disable`. Using the latest tslint configuration generates this error:

    <reference> is not allowed, use imports

##### openapi-generator version

3.3.3

##### Command line used for generation

typescript-fetch

##### Steps to reproduce

Run generator for typescript-fetch and view output .ts file:

```
/// <reference path="./custom.d.ts" />
// tslint:disable
...
```

##### Suggest a fix/enhancement

Since tslint is disabled for the rest of the file; might as well disable it for the reference call. Alternatively, rewrite using import as per linting error.

**Comment by fuzzzerd** [comment]
@wing328 I'd love to take a stab at it, and I'm confident I could adjust the template files to work correctly, but I don't work with java or maven so it will take time to get a local environment working to validate the changes.

**Comment by nicokoenig** [comment]
@fuzzzerd Should I provide a fix for the issue or did you already setup your local environment?

**Comment by fuzzzerd** [comment]
@nicokoenig I have not had a chance to work on this, realistically it will be a week or two until I have time to try this out.

**Comment by fuzzzerd** [comment]
Months later I'm finally getting back to this and it seems that this has already been fixed in master. At least the mustache templates start with `//tslint:disable`.  Is this only going to be fixed for v4? or will this change also make it to a 3.x release?
