### ISSUE TITLE
[REQ] [kotlin][jvm-retrofit2] Add handling if responseBody is empty string

### ISSUE THREAD

**Issue by dylan-kwon** [OpenAPITools/openapi-generator#14982]
### Is your feature request related to a problem? Please describe.

JsonParser throws an exception when ResponseBody is an empty string. (In my case I use kotlinx_serialization.)
https://github.com/square/retrofit/issues/1554

## Describe the solution you'd like

this case we need a way to handle empty strings.

## Describe alternatives you've considered

Add `[pre]converterFactory` which can be called first in `retrofitBuilder` inside ApiClient. There is already `converterFactory` but it is not available in this case because it is added last.

```kotlin
private val retrofitBuilder: Retrofit.Builder by lazy {
        Retrofit.Builder()
            .baseUrl(baseUrl)

            ////////////  add  ////////// 
            .apply {
                if (preConverterFactory != null) {
                    addConverterFactory(preConverterFactory)
                }
            }
            ///////////////////////////////

            .addConverterFactory(ScalarsConverterFactory.create())
            .addConverterFactory(kotlinxSerializationJson.asConverterFactory("application/json".toMediaType()))
            .apply {
                if (converterFactory != null) {
                    addConverterFactory(converterFactory)
                }
            }
    }
```

This allows you to add converters to suit your project's needs.
(In my case, adding `NullOnEmptyConverterFactory` can solve the problem.)

```kotlin
class NullOnEmptyConverterFactory : Converter.Factory() {
    override fun responseBodyConverter(
        type: Type,
        annotations: Array<out Annotation>,
        retrofit: Retrofit
    ): Converter<ResponseBody, *> {
        val delegate: Converter<ResponseBody, *> = retrofit.nextResponseBodyConverter<Any?>(
            this, type, annotations
        )
        return Converter<ResponseBody, Any?> { body ->
            when (body.contentLength() == 0L) {
                true -> null
                else -> delegate.convert(body)
            }
        }
    }
}
```

This way, you can handle the response to suit your own requirements.

**Comment by wing328** [comment]
can you please file a PR with the suggested fix when you've time?

**Comment by eriknyk** [comment]
@dylan-kwon dis you test it?
I've tested in retrofit v2.9.0 and contentLegth() is always -1, 
and it makes sense, since it will be set only when the response body is consumed by calling <ResponseBody instance>.bytes() or <ResponseBody instance>.byteString()
