### ISSUE TITLE
[BUG][JAVA] unable to generate gitlab client 

### ISSUE THREAD

**Issue by mischa-n** [OpenAPITools/openapi-generator#14998]
##### Description

Only the `ApiClient` is generated, none of the endpoints or model classes. 

##### openapi-generator version

org.openapitools:openapi-generator-maven-plugin:6.4.0

##### OpenAPI declaration file content or url

https://gitlab.com/gitlab-org/gitlab/-/blob/v15.9.2-ee/doc/api/openapi/openapi.yaml?plain=1

##### Generation Details

```
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.openapitools</groupId>
          <artifactId>openapi-generator-maven-plugin</artifactId>
          <version>6.4.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
    <plugins>
      <plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>create-gitlab-client</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/gitlab-openapi.yaml</inputSpec>
              <generatorName>java</generatorName>
              <apiPackage>com.gitlab.api</apiPackage>
              <modelPackage>com.gitlab.model</modelPackage>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <!-- tons of attribute xyz is unexpected -->
              <skipValidateSpec>true</skipValidateSpec>
              <typeMappings>integer+int64=long,boolean=boolean</typeMappings>
              <!-- generator specific: https://openapi-generator.tech/docs/generators/java/ -->
              <configOptions>
                <!-- okhttp-gson would also match -->
                <library>resttemplate</library>
                <useJakartaEe>true</useJakartaEe>
                <openApiNullable>false</openApiNullable>
                <booleanGetterPrefix>is</booleanGetterPrefix>
              </configOptions>
              <globalProperties>
                <skipFormModel>false</skipFormModel>
              </globalProperties>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

##### Steps to reproduce

Create a single Maven module with the given configuration and run `mvn clean generate-sources`.

##### Suggest a fix

https://gitlab.com/gitlab-org/gitlab/-/blob/v15.9.2-ee/doc/api/openapi/openapi.yaml?plain=1 uses `$ref:` - may be references are not supported by the current generator version.

**Comment by borsch** [comment]
@mischa-n they got pretty strange format for openapi (and seems like not supported by generator) usually we don't refer `path` like that. you can check samples here https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/test/resources/3_0/java

So probably you would need to change structure of that yaml

BTW - I see that v2 looks good https://gitlab.com/gitlab-org/gitlab/-/raw/v15.9.2-ee/doc/api/openapi/openapi_v2.yaml and generator can process it without issues

**Comment by mischa-n** [comment]
@borsch warm thanks for pointing to https://gitlab.com/gitlab-org/gitlab/-/raw/v15.9.2-ee/doc/api/openapi/openapi_v2.yaml!

**Comment by borsch** [comment]
@mischa-n if everything is fine can you close this issue?

**Comment by mischa-n** [comment]
Yes, thanks a lot
(thought I did select "close")
![grafik](https://user-images.githubusercontent.com/54059083/226569513-44c30de6-bc1c-4110-91cd-d8c0f2dddd4b.png)
