### ISSUE TITLE
[BUG][SPRING][latest] Invalid code generated on non-required list object property

### ISSUE THREAD

**Issue by ddeath** [OpenAPITools/openapi-generator#14993]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If there is NON-required array item in object field it will generate invalid code for it:
INVALID:
```java
public Customer addDetailItem(Detail detailItem) {
    if (this.detail == null) {
      this.detail = ;
    }
    this.detail.add(detailItem);
    return this;
  }
```

Expected valid code (v6.4.0):
```java
public Customer addDetailItem(Detail detailItem) {
    if (this.detail == null) {
        this.detail = new ArrayList<>();
    }
    this.detail.add(detailItem);
    return this;
  }
```

##### openapi-generator version

latest docker image, with v6.4.0 generator will produce valid code

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3

info:
  title: Api
  description: Api
  version: 0.1.2

tags:
  - name: Customers
    description: Customers Management and lookup

servers:
  - url: /
    description: Testing env

paths:
  /customers:
    post:
      tags:
        - Customers
      operationId: createCustomer
      description: Creates a customer
      responses:
        '201':
          description: Customer was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'

components:
  schemas:
    Customer:
      type: object
      required:
        - id
      properties:
        id:
          type: string
        detail:
          type: array
          items:
            $ref: '#/components/schemas/Detail'

    Detail:
      type: object
      properties:
        id:
          type: string
```

##### Generation Details
```
docker run --rm --workdir /github/workspace -v $(pwd):/github/workspace openapitools/openapi-generator-cli:latest generate -g spring -o /github/workspace/spring-client -i /github/workspace/openapi/scv/v1.yml --type-mappings string+date=LocalDate,string+date-time=Instant --import-mappings LocalDate=java.time.LocalDate,Instant=java.time.Instant   -p groupId=uk.co.example,basePackage=uk.co.example.scv.v1.server.config,basePackage=uk.co.example.scv.v1.server,apiPackage=uk.co.example.scv.v1.server,invokerPackage=uk.co.example.scv.v1.server.invoker,modelPackage=uk.co.example.scv.v1.server.models,library=spring-boot,artifactId=scv-v1-server,documentationProvider=none,useSwaggerUI=false,interfaceOnly=true,useTags=true,apiPathPrefix=/v1,snapshotVersion=true
```

##### Steps to reproduce

1. put the openapi contract included above to file: './openapi/scv/v1.yml`
2. execute docker command listed above
3. open file `./spring-client/src/main/java/uk/co/gojoko/mosaic/openapi/scv/v1/server/models/Customer.java`
4. check line 59
<img width="878" alt="Screenshot 2023-03-20 at 13 19 35" src="https://user-images.githubusercontent.com/2537379/226253175-0d58e0da-9b76-47f7-a6e5-3c537198dcd1.png">

##### Suggest a fix
- didn't have time to look into it too much so just reporting

**Comment by wing328** [comment]
i tested with the latest master and couldn't repeat the issue (we merged a fix for default value in spring generator last week)

please pull the latest master/docker image to give it another try.

**Comment by ddeath** [comment]
I can confirm that issue appears to be resolved on latest docker tag. However I had to delete images & pull it like 6 times before it started to work for some reason. Probably something somewhere was weirdly cached or something.

Anyway thank you for quick response.
