### ISSUE TITLE
[Go] Response unmarshalling error

### ISSUE THREAD

**Issue by danikarik** [OpenAPITools/openapi-generator#1500]
##### Description

Problem with decoding response body to struct. Decode methods of generated `client.go` expects `interface{}`, but api methods pass string pointer. As as result decode function returns `json: cannot unmarshal object into Go value of type string`.

##### openapi-generator version

3.3.3

##### OpenAPI declaration file content or url

[openapi.yaml](https://raw.githubusercontent.com/danikarik/clicksend-go/master/api/openapi.yaml)

##### Command line used for generation

`openapi-generator generate -i https://raw.githubusercontent.com/ClickSend/clicksend-go/master/api/swagger.yaml -g go -DpackageName=clicksend -o ./`

##### Steps to reproduce

1. Clone [repo](https://github.com/danikarik/clicksend-go).
2. Register [account](https://dashboard.clicksend.com/#/signup/step0).
3. Obtain `API_KEY`.
4. Set env variables: `API_USERNAME` and `API_KEY`.
5. Run `go test -v -run TestAccountGet`

##### Suggest a fix/enhancement

Change api function's return value from `string` to `map[string]interface{}`.

**Comment by danikarik** [comment]
@wing328 Hi! Why the issue was removed from milestone?

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/2414

@danikarik please pull the latest master to give it another try.
