### ISSUE TITLE
[BUG] [JAVA] NullPointerException in add method of DTOs for list if option containerDefaultToNull set to true

### ISSUE THREAD

**Issue by vlavasa** [OpenAPITools/openapi-generator#15013]
Hi, I would like to notify this issue:

in generator for Java version 6.2.1 the _addSomething_ method was like this:
`public RequiredDomainAgreementsAllOf addAgreementsItem(AgreementId agreementsItem) {
    if (this.agreements == null) {
      this.agreements = new ArrayList<>();
    }
    this.agreements.add(agreementsItem);
    return this;
  }`

now in version 6.4.0 it looks like this:
`  public RequiredDomainAgreementsAllOf addAgreementsItem(AgreementId agreementsItem) {
    this.agreements.add(agreementsItem);
    return this;
  }`

without if condition. If somebody use _containerDefaultToNull_ option, it leads to NullPointerException.

With best regards
Vladimír

**Comment by wing328** [comment]
we made some improvements and bug fixes on handling default values. can you give it a try with the latest master?

**Comment by wing328** [comment]
you can use the snapshot version: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-maven-plugin/6.5.0-SNAPSHOT/

**Comment by vlavasa** [comment]
Hi,
it seems to be fixed in version 6.5.0.
The if condition in addXYZ methods is back.
So issue can be closed I think.
Thanks you
Vladimír
