### ISSUE TITLE
[Announcement][JAVA] Decommission of the option `fullJavaUtil`

### ISSUE THREAD

**Issue by martin-mfg** [OpenAPITools/openapi-generator#15012]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
  *I assume OpenAPI Generator's own samples are valid.*
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- What's the actual output vs expected output?
  *Generated code should compile*
- ~~[Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))~~

##### Description

Several Java-based generators have an option called `fullJavaUtil`. When this is set to `true`, OpenAPI Generator in many cases produces output code that can not be compiled.
I created an example commit [**here**](https://github.com/martin-mfg/openapi-generator/commit/e8c64e5886a1445160cc9d873bfdf82ccca2336e). It simply uses the examples that are part of the OpenAPI Generator repository, but with `fullJavaUtil=true`. As you can see in the pipeline status for the commit, many of the samples don't work with that setting.
Also, there's one special case: Using `fullJavaUtil=true` in the java-helidon-client-se sample generates errors already when running OpenAPI Generator, not only when compiling its output.

In a previous PR I had already prepared some fixes for the `fullJavaUtil` problems, but eventually I reverted them. [See here](https://github.com/OpenAPITools/openapi-generator/pull/14929#discussion_r1135947891).
There, I also brought up the idea of deprecating `fullJavaUtil` as it causes problems and apparently is not used much.

##### openapi-generator version

master

##### Generation Details

I enabled `fullJavaUtil` in the Java sample files and then ran `./bin/generate-samples.sh` to create the demo commit which I linked above.

##### Suggest a fix

Either fix the various problems, possibly based on the mentioned work I did already. Or deprecate and eventually remove `fullJavaUtil`.

I would be willing to work on a PR for this. Just let me know how the described problems should be handled.

**Comment by wing328** [comment]
what about removing `fullJavaUtil` in the upcoming 7.0.0 release?

we have much better handling of reserved words so looks like we don't need the `fullJavaUtil` option any more.

**Comment by wing328** [comment]
I've renamed the subject of this issue to announcement and pinned it in the issue tracker so that users will notice the decommission of this option.
