### ISSUE TITLE
Skip maven code generation if source file is unchanged

### ISSUE THREAD

**Issue by rasmusfaber** [OpenAPITools/openapi-generator#1501]
##### Description

When using the Maven task the generator always runs, even if the source file is unchanged.

It would be nice to skip the generation, if there have been no changes.

##### openapi-generator version

3.3.3 / 3.3.4-SNAPSHOT

##### Steps to reproduce

Run maven compile twice in a row, notice that the generator always run, even if there have been no changes.

##### Suggest a fix/enhancement

It might be difficult to track the state, including the maven-options, but if we just compare the timestamp of the source file and the output file, it should be close enough, as long as the skip is not per default

**Comment by Philzen** [comment]
This was implemented a long time ago in 4.x:

```xml
<configuration>
    <skipIfSpecIsUnchanged>true</skipIfSpecIsUnchanged>
</configuration>
```
