### ISSUE TITLE
[BUG] If the model name is `LocalTime`, it will conflict with `java.time.LocalTime`.

### ISSUE THREAD

**Issue by dylan-kwon** [OpenAPITools/openapi-generator#15020]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))
- 
##### Description

If the name of the model is 'LocalTime', the data class is created incorrectly even though 'modelNamePrefix' is set.
```kotlin
data class java.time.LocalTime(
    // ..
)
```
Perhaps `LocalDate` and `LocalDateTime` have the same issue.

##### openapi-generator version
6.4.0

**Comment by daniel-waiguru** [comment]
Any reason why this was closed without any info? Was it fixed
I am facing the same issue on 7.16.0
@dylan-kwon
