### ISSUE TITLE
[REQ] Allow Inheritance from multiple composition

### ISSUE THREAD

**Issue by fraf** [OpenAPITools/openapi-generator#15045]
When you define a component like this : 

```
    IdNomCodeOrdre:
      allOf:
        - $ref: '#/components/schemas/IdNomCode'
        - $ref: '#/components/schemas/IdNomOrdre'
      xml:
        name: IdNomCodeOrdre
```

And then inherit from it like this : 

```
    ProduitSimple:
      allOf:
        - $ref: '#/components/schemas/IdNomCodeOrdre'
        - type: object
          properties:
            typeRisque:
              description: Type risque du produit
              $ref: '#/components/schemas/TypeRisque'
            cible: ...
```

The second $ref ( - $ref: '#/components/schemas/IdNomOrdre') is ignored at code generation (java). Should be nice if it were not !
`IdNomCodeOrdre` should be an entire generated class and then extendable.

**Comment by wing328** [comment]
please give it a try again with the latest stable version as the issue should have been fixed
