### ISSUE TITLE
[BUG][python-nextgen] Client tries to decode image/jpeg response

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#15057]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When calling an API that returns `image/jpeg`, the generated client tries to decode and fails in `api_client.py`:

```
        if response_type not in ["file", "bytes"]:
            match = None
            content_type = response_data.getheader('content-type')
            if content_type is not None:
                match = re.search(r"charset=([a-zA-Z\-\d]+)[\s;]?", content_type)
            encoding = match.group(1) if match else "utf-8"
>           response_data.data = response_data.data.decode(encoding)
E           UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: ""
  version: ""
paths: 
  /getImage:
    get:
      responses:
        200:
          description: OK          
          content:
            image/jpeg:
              schema:
                type: string
                format: binary

```

**Comment by wing328** [comment]
@robertschweizer thanks for reporting the issue. I've filed #15076 to fix the issue.
