### ISSUE TITLE
[rust-server] Using old version of hyper

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#1505]
##### Description

rust-server uses hyper v0.11. We should upgrade to the more recent [v0.12](https://seanmonstar.com/post/174480374517/hyper-v012)

##### Related issues/PRs

See https://github.com/Metaswitch/vault-client/pull/6 for an example of someone manually migrating an autogenerated crate to hyper v0.12 (albeit from an old version that uses hyper v0.10).

**Comment by myk3v** [comment]
Would it be possible to take @colelawrence's [hyper version bump](https://github.com/colelawrence/openapi-generator/commit/649ad73cd226ea3b31c06b0a8499fb73227ce070)?

**Comment by bjgill** [comment]
Unfortunately, that is for `rust`, not `rust-server`.

There are actually two Rust generators, with unhelpful naming:
- `rust` is a client-only generator
- `rust-server` generates a crate that acts as both client and server. It is designed to abstract away the HTTP layer

The two are very different in their internal structure, and use different versions of hyper.

**Comment by myk3v** [comment]
`rust-server` indeed is more elaborate. Thanks for the heads-up. I was not aware of it.

**Comment by richardwhiuk** [comment]
Done in https://github.com/OpenAPITools/openapi-generator/pull/4519
