### ISSUE TITLE
[REQ] Feature Request Description

### ISSUE THREAD

**Issue by shinnokdisengir** [OpenAPITools/openapi-generator#15059]
### Is your feature request related to a problem? Please describe.

Hello everyone. 
I would like to say that I am using php on an exceptional way (the customer requires this technology). 
I am using the **php-slim4** generator and I need to create the OAuth2 token-based authentication/authorization flow.
According to the `README` it would be enough to create `./src/Auth/OAuthAuthenticator.php` and it should work, but nothing seems to happen.
- Should the instance be loaded under middlewares? But it does not have the correct interface
- Should it be loaded as a dependency? If so, can you tell me how/where to handle the loading? (For now I added it to `config.inc.php`

Thanks
G.

**Comment by JulianVennen** [comment]
This does not seem like a feature request
