### ISSUE TITLE
[typescript-angular] outdated zone.js@^0.7.6 peer dependency

### ISSUE THREAD

**Issue by d0x** [OpenAPITools/openapi-generator#1506]
##### Description

Using the generated client for a new angular 6 application will lead into this warning:
```
npm WARN my.lib requires a peer of zone.js@^0.7.6 but none is installed. You must install peer dependencies yourself.
```

##### openapi-generator version

3.3.3

##### Command line used for generation

```
java -jar openapi-generator.jar generate \
                    --skip-validate-spec \
                    --input-spec XXXX  \
                    --generator-name typescript-angular \
                    --output YYY \
                    --invoker-package ZZZ \
                    --additional-properties snapshot=false \
                    --additional-properties supportsES6=true \
                    --additional-properties modelPropertyNaming=camelCase \
                    --additional-properties ngVersion=6.1.1 \
                    --additional-properties withInterfaces=true \
                    --additional-properties providedInRoot=true \
                    --additional-properties useRxJS6=true
```

##### Suggest a fix/enhancement

I tried the generated client using Zone.js 0.8.26 and so far everything works fine. But I don't know the internals of it and when zone.js is really used. So I can't suggest a blind update to 0.8.xx. Furthermore I haven't found any compatibility notes between 0.7.xx and 0.8.xx.

**Comment by wing328** [comment]
> I tried the generated client using Zone.js 0.8.26 and so far everything works fine. But I don't know the internals of it and when zone.js is really used. So I can't suggest a blind update to 0.8.xx. Furthermore I haven't found any compatibility notes between 0.7.xx and 0.8.xx.

Thanks for testing the upgrade locally and checking to see if there's any compatibility notes. I would recommend submitting a PR to see if the CI catches any issue with the upgrade.

**Comment by d0x** [comment]
Ok, i can do that.
