### ISSUE TITLE
[Python] AttributeError: 'UUID' object has no attribute 'openapi_types'

### ISSUE THREAD

**Issue by Amoki** [OpenAPITools/openapi-generator#1507]
##### Description
```
  File "/my_code.py", line 41, in retrieve_full_topic_info
    topic = client.bcf_api.get_full_topic(projects_pk=project_id, guid=topic_guid)
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api/bcf_api.py", line 3195, in get_full_topic
    (data) = self.get_full_topic_with_http_info(guid, projects_pk, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api/bcf_api.py", line 3276, in get_full_topic_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api_client.py", line 322, in call_api
    _preload_content, _request_timeout)
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api_client.py", line 115, in __call_api
    path_params = self.sanitize_for_serialization(path_params)
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api_client.py", line 211, in sanitize_for_serialization
    for key, val in six.iteritems(obj_dict)}
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api_client.py", line 211, in <dictcomp>
    for key, val in six.iteritems(obj_dict)}
  File "/usr/local/lib/python3.7/site-packages/bimdata_api_client/api_client.py", line 207, in sanitize_for_serialization
    for attr, _ in six.iteritems(obj.openapi_types)
AttributeError: 'UUID' object has no attribute 'openapi_types'
```

##### openapi-generator version
3.3.3

##### OpenAPI declaration file content or url
https://api-staging.bimdata.io/doc.json
or
https://api-staging.bimdata.io/doc.yaml

##### Command line used for generation
java -jar /tmp/openapi-generator.jar generate -i /tmp/openapi.json -g python -o /tmp/python-lib

##### Steps to reproduce
When serializing response to https://api-staging.bimdata.io/doc#/bcf/getFullTopic, the UUID serialization produce the stacktrack above.
The code generated can be found here: https://github.com/bimdata/python-api-client/blob/master/bimdata_api_client/api_client.py#L220
The type of `obj` when the exception in thrown is `<class 'uuid.UUID'>`

Does the problem come from my openapi description file?

Thanks for maintaining the awesome tool!

**Comment by wing328** [comment]
@Amoki thanks for reporting the issue. I used https://apidevtools.org/swagger-parser/online/ to valid the spec and got some errors. Not sure if it's related to the exception you got but I think worth fixing these errors.

**Comment by csimmons0** [comment]
@wing328 I'm getting the same error in one of my generated clients. I tested the spec in the validator that you linked, and it passed. The code that's failing looks suspicious. It looks like it's trying to access the openapi_types member of a model object, but openapi_types is a member of the class, not the model instance. That said, I looked at the history of api_client.mustache, and it looks like it's always been that way.

In api_client.py:
```
            obj_dict = {obj.attribute_map[attr]: getattr(obj, attr)
                        for attr, _ in six.iteritems(obj.openapi_types)
                        if getattr(obj, attr) is not None}
```

The model that the code is failing on in my case:
```
class DataAccess(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data_uri': 'str',
        'base_query': 'str',
        'username': 'str',
        'password': 'str'
    }

    attribute_map = {
        'data_uri': 'data_uri',
        'base_query': 'base_query',
        'username': 'username',
        'password': 'password'
    }

    def __init__(self, data_uri=None, base_query=None, username=None, password=None):  # noqa: E501
        """DataAccess - a model defined in OpenAPI"""  # noqa: E501
        ...
```

**Comment by csimmons0** [comment]
@Amoki Did you ever resolve the issue?

**Comment by Amoki** [comment]
I fixed my spec and it works! Even if my spec errors were not related to this field, it was the problems.
Thanks!
