### ISSUE TITLE
[BUG] Inheritance with Typescript using allOf generates code without inheritance

### ISSUE THREAD

**Issue by tbarbugli** [OpenAPITools/openapi-generator#15074]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using `allOf` for inheritance/composition of components, the code generated is not using any kind of inheritance.

Here's the code generated (I removed comments to make it easier to read)

```typescript
export interface BasicErrorModel {
  message: string;
  code: number;
}

export interface ExtendedErrorModel {
  message: string;
  code: number;
  rootCause: string;
}

export interface ExtendedErrorModelAllOf {
  rootCause: string;
}
```

##### openapi-generator version

6.4.0 (tried 6.2.1 and 5.4.0 as well)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
paths:
  /users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
components:
  schemas:
    BasicErrorModel:
      type: object
      required:
        - message
        - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:   
        - $ref: '#/components/schemas/BasicErrorModel'
        - type: object
          required:
            - rootCause
          properties:
            rootCause:
              type: string
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

```

##### Generation Details

```
yarn openapi-generator-cli generate \
  -i "$SCHEMA_FILE" \
  -g typescript-fetch \
  -o "$TEMP_OUTPUT_DIR" \
  --skip-validate-spec \
  --additional-properties=supportsES6=true \
  --additional-properties=modelPropertyNaming=original \
  --additional-properties=enumPropertyNaming=original \
  --additional-properties=withoutRuntimeChecks=true
```

We use this at [Stream](https://getstream.io) and we are happy to sponsor a bugfix is you can provide some guidance on how that works (unfortunately Java is not our forte otherwise we'd bake a patch ourselves :))

**Comment by jbezuk** [comment]
Hi @tbarbugli I am seeing the same thing as you, and I found that using v4.3.1 or anything before the v5.0.0 release (including the v5 beta releases) works as expected. I think this was a planned removal of support for inheritance without the use of discriminators. I couldn't find much information about this change but I found a little debate about it in this thread if you're interested https://github.com/OpenAPITools/openapi-generator/issues/10125

For me my workaround will probably be to use v4.3.1, but I also tested the latest version using discriminators on all inherited types and that does seem to fix the issue too. A little more information about discriminators: https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

**Comment by wing328** [comment]
We've added a rule `REF_AS_PARENT_IN_ALLOF ` in OpenAPI Normalizer to handle such case: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

Please give it a try when you've time.

**Comment by Hiller** [comment]
doesn't work with typescript-angular.
command is java -jar 6.6.0.jar generate -i swagger.json -g typescript-angular -o module --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true --additional-properties=useSingleRequestParameter=true

you can put anything for normalizer options without a single warn from it. Seems like normalizer is not applied at all

**Comment by wing328** [comment]
I did a test with the latest master and looks like it's working as expected:
```diff
diff --git a/.openapi-generator/FILES b/.openapi-generator/FILES
index 2ac0426..9e901f4 100644
--- a/.openapi-generator/FILES
+++ b/.openapi-generator/FILES
@@ -1,5 +1,4 @@
 .gitignore
-.openapi-generator-ignore
 README.md
 api.module.ts
 api/api.ts
diff --git a/model/extendedErrorModel.ts b/model/extendedErrorModel.ts
index 094e69c..0bed623 100644
--- a/model/extendedErrorModel.ts
+++ b/model/extendedErrorModel.ts
@@ -9,11 +9,10 @@
  * https://openapi-generator.tech
  * Do not edit the class manually.
  */
+import { BasicErrorModel } from './basicErrorModel';
 
 
-export interface ExtendedErrorModel { 
-    message: string;
-    code: number;
+export interface ExtendedErrorModel extends BasicErrorModel { 
     rootCause: string;
 }
 
```

**Comment by Hiller** [comment]
According to docs REF_AS_PARENT_IN_ALLOF was implemented before 6.6.0 release. so i can test only latest release. Where can i get nightly build to test master?

**Comment by Hiller** [comment]
related issue BTW #13417

**Comment by wing328** [comment]
7.0.0-beta has been released: https://github.com/OpenAPITools/openapi-generator/pull/new/7.0.0-beta

**Comment by wing328** [comment]
SNAPSHOT builds can be found in the project's readme. Just search for "snapshot"
