### ISSUE TITLE
[BUG][TypeScript - axios] Redundant models - the same type is generated multiple times

### ISSUE THREAD

**Issue by MartinNovak1991** [OpenAPITools/openapi-generator#15077]
#### Bug Report Checklist

- [*] Have you provided a full/minimal spec to reproduce the issue?
- [*] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [*] Have you searched for related issues/PRs?
- [*] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

OpenApi description generated just one model file in 5.4.0. In 6+ (tested with 6.0.0 and 6.4.0) every property (of the same schema) is generating one file per property, and all these files are pointing to the one (same) model/type.

##### openapi-generator version

5.4.0 ok, but generating with 6.0.0 and 6.4.0 causes issue described above.

##### OpenAPI declaration file content or url

There is sample of problematic part (in schemas)
```yaml
    PaginationOffsetType:
      type: object
      properties:
        offset:
          type: integer
          minimum: 0
      required:
        - offset
    OffsetsObjectType:
      type: object
      properties:
        _offsets:
          type: object
          properties:
            self:
              allOf:
                - description: |
                    desc 1
                - $ref: '#/components/schemas/PaginationOffsetType'
            first:
              allOf:
                - description: |
                    desc 2
                - $ref: '#/components/schemas/PaginationOffsetType'
            previous:
              allOf:
                - description: >
                    desc 3
                - $ref: '#/components/schemas/PaginationOffsetType'
            next:
              allOf:
                - description: >
                   desc 4
                - $ref: '#/components/schemas/PaginationOffsetType'
          required:
            - first
            - self
      required:
        - _offsets
```

##### Generation Details

"npx openapi-generator-cli generate --generator-key ${yaml-filename}"
I tried "--openapi-normalizer REF_AS_PARENT_IN_ALLOF=true"   but no effect

##### Steps to reproduce

simply run generate  sample above ... it will create (useless?) four  (suffixed) models:
![image](https://user-images.githubusercontent.com/71878667/228747748-15222e37-730f-4897-9ed5-fc70d5e3ba58.png)

You can see  propertyName suffix ... with contents:

offsets-object-type-offsets.ts:

```
export interface OffsetsObjectTypeOffsets {  
       'self': OffsetsObjectTypeOffsetsSelf;  
       'first': OffsetsObjectTypeOffsetsFirst;  
       'previous'?: OffsetsObjectTypeOffsetsPrevious;   
       'next'?: OffsetsObjectTypeOffsetsNext;
}
```

offsets-object-type-offsets-first.ts:
```
export type OffsetsObjectTypeOffsetsFirst = PaginationOffsetType;
```

offsets-object-type-offsets-next..ts:
```
export type OffsetsObjectTypeOffsetsNext = PaginationOffsetType;
```

offsets-object-type-offsets-previous.ts:
```
export type OffsetsObjectTypeOffsetsPrevious= PaginationOffsetType;
```

offsets-object-type-offsets-self.ts:
```
export type OffsetsObjectTypeOffsetsSelf= PaginationOffsetType;
```

pagination-offset-type.ts:  
```
export interface PaginationOffsetType {
    'offset': number;
}
```

**v5.4.0 was generating:**
![image](https://user-images.githubusercontent.com/71878667/228750286-06c9c559-11e6-43d3-837f-1f32389d59c7.png)

offsets-object-type.ts:
```
export interface OffsetsObjectType {  
   '_offsets': OffsetsObjectTypeOffsets;
}
```

offsets-object-type-offsets.ts:  
```
export interface OffsetsObjectTypeOffsets {  
      'self': PaginationOffsetType ;  
      'first': PaginationOffsetType ;  
      'previous'?: PaginationOffsetType ;  
      'next'?: PaginationOffsetType ;
}
```

pagination-offset-type.ts:  

```
export interface PaginationOffsetType {
    'offset': number;
}
```

I would exepect the same result, optimized, not reduntant files/types (with "equal" content)

##### Related issues/PRs

I have not found any related issue

##### Suggest a fix

No idea

**Comment by ReneZeidler** [comment]
This was partially fixed by #16096, however the issue still persists if `readOnly` and/or `nullable` are used together with any other property (like `description`).
