### ISSUE TITLE
How to add parameters generated by HandlerMethodArgumentResolver?

### ISSUE THREAD

**Issue by agarkoff** [OpenAPITools/openapi-generator#15088]
Can you please tell me if it is possible to add parameters to the generated controllers so that Spring creates them at runtime using implementations of the HandlerMethodArgumentResolver class?

I couldn't find anything relevant on this subject in Google, except for Pageable examples.

**Comment by dabdirb** [comment]
Yes it is useful when i want to access login UserDetail from Principle
i created a PR  https://github.com/OpenAPITools/openapi-generator/pull/16663  to add  vendor extenstion x-spring-provide-args  that can solve this issue.
