### ISSUE TITLE
Generating typescript-node code uses incorrect type

### ISSUE THREAD

**Issue by yperess** [OpenAPITools/openapi-generator#1509]
##### Description

Generating typescript-node code uses `http.ClientResponse` type which was removed in node 10, it should now be `http.IncomingMessage`.

##### openapi-generator version

3.3.3

##### Command line used for generation

java -jar ../openapi-generator-cli.jar generate -i api/openapi.yml -l typescript-node -o build/gen/swagger

##### Suggest a fix/enhancement

Fix the template (I'm sorry, I just don't have the time right now to do it myself).

**Comment by karismann** [comment]
please use the `supportsES6` option set to true to have your issue fixed.
see https://openapi-generator.tech/docs/generators/typescript-node

`java -jar ../openapi-generator-cli.jar generate -i api/openapi.yml -l typescript-node -o build/gen/swagger --additionalproperties supportsES6=true`
