### ISSUE TITLE
[REQ][python-nextgen] Include py.typed file in generated client

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#15097]
### Is your feature request related to a problem? Please describe.

mypy does not import the generated Python client while type checking. According to [PEP 561](https://peps.python.org/pep-0561/), a `py.typed` file needs to be shipped with the package to show mypy that a package has valid type annotations.

## Describe the solution you'd like

Add `py.typed` to the generated package root and add it to the `package_data` in `setup.py`.

**Comment by wing328** [comment]
@robertschweizer I've filed https://github.com/OpenAPITools/openapi-generator/issues/15391. 

Please review when you've time.
