### ISSUE TITLE
[BUG] [csharp-netcore] Double backslash problem in literal string

### ISSUE THREAD

**Issue by arvindpdmn** [OpenAPITools/openapi-generator#15101]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a string in constraint with a regex pattern, the generated code contains extra (redundant) backslash. Pattern is generated in C# as a literal string `@"string-here"` but the string contains double-backslash instead of single-backslash. Single backslash should be present since it's a literal string. See https://learn.microsoft.com/en-us/dotnet/standard/base-types/regular-expressions

Specifically, for the example given below, generated code is 
`new Regex(@"^\\d+(\\.\\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", RegexOptions.CultureInvariant);`
when it should be
`new Regex(@"^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$", RegexOptions.CultureInvariant);`

[Edit]
This problem is also present in the SanitizeFilename() method of ClientUtils class.

##### openapi-generator version

openapi-generator-cli-6.5.0-20230329.141901-70.jar from https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/6.5.0-SNAPSHOT/

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Regex issue'
paths: {}
components:
  schemas:
    Capability:
      properties:
        dlRate:
          $ref: '#/components/schemas/BitRate'
        ulRate:
          $ref: '#/components/schemas/BitRate'
    BitRate:
      type: string
      pattern: '^\d+(\.\d+)? (bps|Kbps|Mbps|Gbps|Tbps)$'
```

##### Generation Details

```
java -jar lib/openapi-generator-cli.jar generate -i RegExp.yaml -g csharp-netcore -o RegExp --additional-properties=targetFramework=net7.0 --additional-properties=packageName=Com.Example --skip-validate-spec --openapi-normalizer SIMPLIFY_BOOLEAN_ENUM=true,SIMPLIFY_ANYOF_STRING_AND_ENUM_STRING=true,REMOVE_ANYOF_ONEOF_AND_KEEP_PROPERTIES_ONLY=true,ADD_UNSIGNED_TO_INTEGER_WITH_INVALID_MAX_VALUE=true,SIMPLIFY_ONEOF_ANYOF=true
```

##### Steps to reproduce

As above

##### Related issues/PRs

None, at least not that's labelled with C#.

##### Suggest a fix

Don't add the extra backslash. Keep string as literal.

**Comment by devhl-labs** [comment]
DefaultCodegen has this

`property.pattern = toRegularExpression(p.getPattern());`

Which eventually calls this

```java
    // override with any special text escaping logic
    @Override
    @SuppressWarnings("static-method")
    public String escapeText(String input) {
        if (input == null) {
            return input;
        }

        // remove \t, \n, \r
        // replace \ with \\
        // replace " with \"
        // outer unescape to retain the original multi-byte characters
        // finally escalate characters avoiding code injection
        return escapeUnsafeCharacters(
                StringEscapeUtils.unescapeJava(
                                StringEscapeUtils.escapeJava(input)
                                        .replace("\\/", "/"))
                        .replaceAll("[\\t\\n\\r]", " ")
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\""));
    }
```

The regex appears to be escaped intentionally due to code injection concerns, so the pr just makes the string not be a literal.

**Comment by arvindpdmn** [comment]
There's one aspect that's not fixed. I have the following:
```
    Ipv4AddrMask:
      type: string
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$'
      example: '198.51.0.0/16'
```

Generated code escapes correctly the first backslash but not the second one:
`Regex regexIpv4Mask = new Regex("^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$", RegexOptions.CultureInvariant);`

Compilation error in Visual Studio:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1009	Unrecognized escape sequence ...
```

Generated with openapi-generator-cli-6.6.0-20230422.085013-33.jar using the same options as earlier.
