### ISSUE TITLE
[BUG] UUID in path parameter is failing in 6.5.0 due to missing .toString()

### ISSUE THREAD

**Issue by holomekc** [OpenAPITools/openapi-generator#15114]
##### Description

In v6.5.0 of the generation fails because UUID is a String in the spec, but not in Java. So without toString() or something similar the generation is not possible:

![image](https://user-images.githubusercontent.com/30546982/229423739-db9cb1b1-64d8-4648-a01a-4faf001a548c.png)

##### openapi-generator version

6.5.0

##### OpenAPI declaration file content or url

I have no spec I could share, but just a path param with schema type string and format "uuid" is enough.

##### Generation Details

java, jersey2

##### Steps to reproduce

Just generate

##### Related issues/PRs

Changes in here created the issue:
https://github.com/OpenAPITools/openapi-generator/commit/564939a4a8eb73f26a5878445c058875e2a1f2a9

##### Suggest a fix

Add toString() again or String.valueOf(). The first one can fail with NullPointerException, the second would send "null". It is hard to say what people prefer here.

**Comment by snago** [comment]
Mea culpa! I'll create a PR with a fix...
