### ISSUE TITLE
[BUG][JAVA][resttemplate] Removal of @Component from ApiClient and <Name>Api classes is a breaking change

### ISSUE THREAD

**Issue by TheCK** [OpenAPITools/openapi-generator#15136]
#### Bug Report Checklist

- [x] The list does not apply

##### Description

[PR](https://github.com/OpenAPITools/openapi-generator/pull/14845) prompted by [Issue](https://github.com/OpenAPITools/openapi-generator/issues/14832) removed `@Component` and `@Autowired` annotations from the ApiClient and <Name>Api classes.

Before this change Spring would automatically find the ApiClient and <Name>Api classes and they could easily be autowired. Since this change they will not be auto-discovered by Spring and previously working builds will now fail.

You now have to manually provide the classes to Spring by e.g.:

```java
@Bean
public DefaultApi defaultApi(RestTemplate restTemplate) {
  return new DefaultApi(new ApiClient(restTemplate));
}
```

Furthermore the PR only removed the annotations but did not remove the imports of the annotation. See:
[@Autowired in ApiClient](https://github.com/OpenAPITools/openapi-generator/blob/b409ceb3a08dba80e07381075bdab5c9475be802/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L9)
[@Component in ApiClient](https://github.com/OpenAPITools/openapi-generator/blob/b409ceb3a08dba80e07381075bdab5c9475be802/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L29)
[@Autowired in Api](https://github.com/OpenAPITools/openapi-generator/blob/b409ceb3a08dba80e07381075bdab5c9475be802/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache#L15)
[@Component in Api](https://github.com/OpenAPITools/openapi-generator/blob/b409ceb3a08dba80e07381075bdab5c9475be802/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache#L16)

##### openapi-generator version

6.5.0

##### Generation Details

Our config is:

```xml
<configuration>
  <generatorName>java</generatorName>
  <inputSpec>somePath</inputSpec>
  <generateApiTests>false</generateApiTests>
  <generateModelTests>false</generateModelTests>
  <configOptions>
    <openApiNullable>false</openApiNullable>
    <useJakartaEe>true</useJakartaEe>
    <library>resttemplate</library>
  </configOptions>
</configuration>
```

##### Steps to reproduce

1. Build any spec with the `java` generator and `resttemplate` lib in version 6.4.0 and generated APIs have an `@Component` annotation
2. Build any spec with the `java` generator and `resttemplate` lib in version 6.5.0 and generated APIs do not have it anymore

##### Related issues/PRs

[PR](https://github.com/OpenAPITools/openapi-generator/pull/14845)
[Issue](https://github.com/OpenAPITools/openapi-generator/issues/14832)

##### Suggest a fix

This should never have been merged in a minor update, since it is a breaking change. But since the damage has already been done now it should at least be documented in the changelog of this version and a migration path should be provided.

**Comment by jorgerod** [comment]
> What about adding an option to allow users revert to the previous behaviour?
> 
> cc @jorgerod

Yes, i will add a property.

**Comment by wing328** [comment]
PR merged. Please give it another try with the latest master.

**Comment by wing328** [comment]
That's right.

Related PR: https://github.com/OpenAPITools/openapi-generator/pull/15419
