### ISSUE TITLE
[BUG][python-nextgen] Model with nested additionalProperties that have fixed properties fails parsing

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#15135]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Similar to #14913, but with one more level of nesting, the below example fails to construct:

```py
import openapi_client
openapi_client.models.Parent.from_dict({"optionalDict": {"a": {"b": {"aProperty": "value"}}}})
```

```
AttributeError: type object 'dict' has no attribute 'from_dict'
```

##### openapi-generator version

6.5.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    InnerDictWithProperty:
      type: object
      properties:
        aProperty:
          type: string

    InnerDictWithAdditionalProperties:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/InnerDictWithProperty"

    DictWithAdditionalProperties:
      type: object
      additionalProperties:
        $ref: "#/components/schemas/InnerDictWithAdditionalProperties"

    Parent:
      type: object
      properties:
        optionalDict:
          $ref: "#/components/schemas/DictWithAdditionalProperties"
```

##### Suggest a fix

The model instantiation code

```py
        _obj = Parent.parse_obj({
            "optional_dict": dict((_k, Dict[str, InnerDictWithProperty].from_dict(_v)) for _k, _v in obj.get("optionalDict").items()) if obj.get("optionalDict") is not None else None
        })
```
has to do dict construction in two levels intead of calling `Dict[str, InnerDictWithProperty].from_dict(_v)`.

**Comment by wing328** [comment]
Fixed via https://github.com/OpenAPITools/openapi-generator/pull/15239.

Please pull the latest master to give it a try.

**Comment by robertschweizer** [comment]
I tried it and the issue is fixed for me on latest master. Thanks a lot!
