### ISSUE TITLE
[BUG][python-nextgen] regex validation fails on optional or nullable string fields

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#15134]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The below example (nullable or "not required" or both string fields with regex pattern) fail to construct with the field value set to `None`:

```py
>> FieldsWithPatterns.from_dict({"nullable_required": None})

ValidationError: 3 validation errors for FieldsWithPatterns
nullableRequired
  expected string or bytes-like object (type=type_error)
nullableNotRequired
  expected string or bytes-like object (type=type_error)
notNullableNotRequired
  expected string or bytes-like object (type=type_error)
```

##### openapi-generator version

6.5.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: ""
  version: ""
paths: {}
components:
  schemas:
    FieldsWithPatterns:
      type: object
      properties:
        nullableRequired:
          type: string
          nullable: true
          pattern: '[a-z]*'
        nullableNotRequired:
          type: string
          nullable: true
          pattern: '[a-z]*'
        notNullableNotRequired:
          type: string
          pattern: '[a-z]*'
      required:
        - nullableRequired
```

##### Suggest a fix

The problem is that the generated validators run

```py
if not re.match(r"[a-z]*", v):
```

which fails on `None` values. It should be combined with an `isinstance(v, str)` check.

**Comment by wing328** [comment]
Fixed via https://github.com/OpenAPITools/openapi-generator/pull/15233. Please pull the latest master to give it a try.

**Comment by robertschweizer** [comment]
I tried it and the issue is fixed for me on latest master. Thanks a lot!
