### ISSUE TITLE
[BUG][Go] Panic when error is JSON array

### ISSUE THREAD

**Issue by thiagoarrais** [OpenAPITools/openapi-generator#15147]
##### Description

It seems like since #13680 openapi-generator's Go template assumes that JSON responses are single objects. But when ran against APIs that returns object _arrays_, it panics when trying to parse error messages. I've chased this down to the use of `formatErrorMessage` as demonstraded on [Go Playground FQ8Js4GaBuv](https://go.dev/play/p/FQ8Js4GaBuv).

##### openapi-generator version

6.2.1 onwards. Reproduced against 6.5.0, which is latest stable as of this writing. 6.2.0 presents no problem.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: OpenAPI Library Demo App
  version: 0.0.1
servers: [
  {
    "url": "http://localhost:8000",
    "description": "local development server",
  },
]
paths:
  /books:
    get:
      responses:
        "422":
          description: error
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    message:
                      type: string
````

##### Suggest a fix

Maybe ensuring that `metaValue`' is a struct (by virtue of it's Kind field) before calling `FieldByName` will do the trick. See the [docs for FieldByName](https://pkg.go.dev/reflect#Value.FieldByName).

**Comment by gcatanese** [comment]
@thiagoarrais Good catch, I have created #15154 to address it. Thank you!
