### ISSUE TITLE
[Ruby][RSpec] RelishApp URL is unavailable, but the content is accessible on rspec.info

### ISSUE THREAD

**Issue by tksmasaki** [OpenAPITools/openapi-generator#15159]
##### Description

When generating a Ruby client, RSpec files are created with reference comments to https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers. However, since RelishApp is currently unavailable, the referenced content cannot be accessed.
The content is accessible on https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/ .

ref: https://rspec.info/documentation/

##### openapi-generator version

`OpenAPI Generator version: 6.5.0`

##### Suggest a fix/enhancement

I suggest that replace the URL https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers with a valid RSpec documentation URL, such as https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/ .

**Comment by wing328** [comment]
can you please file a PR with the suggested change? thank you.

**Comment by tksmasaki** [comment]
I opened PR: https://github.com/OpenAPITools/openapi-generator/pull/15164
