### ISSUE TITLE
[BUG][ASPNETCORE] useSwashBuckle=false still creates swashbuckle attributes in discriminator models

### ISSUE THREAD

**Issue by leonluc-dev** [OpenAPITools/openapi-generator#15156]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Setting the useSwashbuckle property to false generates discriminator models that still utilize SwashBuckle code. Swashbuckle is not included in the resulting project (as expected) so the models are uncompilable.

##### openapi-generator version

6.5.0

##### Generation Details
Example generation CLI command:

`java -jar openapi-generator-cli.jar generate -i ./swagger.json -g aspnetcore -o ./output  --additional-properties=generateBody=false,classModifier=abstract,aspnetCoreVersion=6.0,buildTarget=library,isLibrary=true,packageName=TestGeneratedStubs,useSwashbuckle=false `

##### Steps to reproduce

Generate a simple ASP.NET 6 solution using a swagger.json containing a discriminator model. Set the useSwashbuckle property to false.
Try to build the resulting project using the dotnet build output/TestGeneratedStubs.sln command.

##### Suggest a fix

The best way to make sure this is handled properly is to wrap the attributes in a `useSwashBuckle` condition.

**Comment by wing328** [comment]
@leonluc-dev I've merged it and filed https://github.com/OpenAPITools/openapi-generator/pull/15176 to add a test.

In the branch `useSwashBuckle-test`, I ran
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g aspnetcore -i modules/openapi-generator/src/test/resources/3_0/aspnetcore/petstore.yaml -o /tmp/aspnetcore --additional-properties=generateBody=false,classModifier=abstract,aspnetCoreVersion=6.0,buildTarget=library,isLibrary=true,packageName=TestGeneratedStubs,useSwashbuckle=false
```

but the output contains compilation errors:
![Screen Shot 2023-04-10 at 6 46 30 pm](https://user-images.githubusercontent.com/934260/230887464-a8f480cc-1028-4fa2-b879-ab17ff7e13ef.png)


Looks like more templates need to be updated? Can you please take a look when you've time?

**Comment by leonluc-dev** [comment]
@wing328 
That's odd. Those errors are related to the Filters folder but those files aren't supposed to be generated in the first place if `useSwashBuckle` is set to false.
As can be seen here:

https://github.com/OpenAPITools/openapi-generator/blob/81cafdc196674f38f15a9e617878247a829657b9/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java#L446-L451

I cannot reproduce these errors locally (using the `useSwashBuckle-test` branch and the provided command) since the Filter folder isn't generated (as expected).
Could the filter folder referenced in the screenshot potentially be some leftover files from a previous generation run?

**Comment by wing328** [comment]
thanks for sharing more with me. I purged the folder to clean up unused files, regenerated the samples and now the tests passed 👍
