### ISSUE TITLE
[BUG] java microprofile - microprofileRestClientVersion 3.0 generated client uses javax for base package of bean validators

### ISSUE THREAD

**Issue by barnabycourt** [OpenAPITools/openapi-generator#15180]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When configuring a java microprofile generator 3 & beanvalidation & jakartaEE

Specifically using the gradle generator plugin I am specifying

configOptions = [
            sourceFolder     : "src/gen/java",
            interfaceOnly    : "true",
            library          : "microprofile",
            java8            : "true",
            dateLibrary      : "java8",
            useBeanValidation: "true",
            microprofileRestClientVersion: "3.0",
            useJakartaEE: "true",
    ] 

The problem I am seeing is that if useBeanValidation and useJaktaEE are true then the imports in the generated java classes use "javax." and not "jakarta."

##### openapi-generator version

I am using org.openapitools:openapi-generator-gradle-plugin:6.5.0

##### OpenAPI declaration file content or url

The specific problem appears to be because ```{{javaxPackage}}``` was used instead of  ```{{rootJavaEEPackage}}``` in the api.mustache file at https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/microprofile/api.mustache#L23

##### Related issues/PRs
I created a A PR to patch https://github.com/OpenAPITools/openapi-generator/pull/15179

**Comment by jochenr** [comment]
Hi,
any news here?
I have the same issue.
Thanky you

**Comment by barnabycourt** [comment]
This issue should actually be closed. It was fixed in openapi 6.6.0 when https://github.com/OpenAPITools/openapi-generator/pull/15179 was merged. 

@jochenr if you can identify which template needs updating or a reproducer it would be helpful.
