### ISSUE TITLE
[BUG] [PYTHON] Regression in OpenAPI generator 5.3.1, nullpointerexception when building library

### ISSUE THREAD

**Issue by phoenixy1** [OpenAPITools/openapi-generator#15181]
#### Bug Report Checklist

- [x ] Have you provided a full/minimal spec to reproduce the issue?
- [ x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? -- N/A -- latest master is a breaking change
- [ x] Have you searched for related issues/PRs?
- [ x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We are hitting a build failure when trying to upgrade our OpenAPI generator version. We were successfully able to upgrade to 5.3.0, but the OpenAPI Generator fails to build our python library starting with version 5.3.1 (the same error also occurs with 5.4.0). When building with Docker we get the following error:

```
Exception: null
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1175)
	at org.openapitools.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:1069)
	at org.openapitools.codegen.DefaultGenerator.generateApis(DefaultGenerator.java:566)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:907)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:441)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.PythonClientCodegen.fromProperty(PythonClientCodegen.java:440)
	at org.openapitools.codegen.DefaultCodegen.getContent(DefaultCodegen.java:6728)
	at org.openapitools.codegen.DefaultCodegen.fromRequestBody(DefaultCodegen.java:6756)
	at org.openapitools.codegen.languages.PythonClientCodegen.fromRequestBody(PythonClientCodegen.java:504)
	at org.openapitools.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:4095)
	at org.openapitools.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:1143)
	... 6 more
```

The Java and Node libraries based on the same YML file build successfully and do not experience this error. Given the lack of detail in the error, I'm not sure how to even begin troubleshooting. In case it helps at all, the output right before the error is

``` 
credit_category=class Schema {
        type: null
        format: null
        $ref: #/components/schemas/CreditCategory
        description: null
        title: null
        multipleOf: null
        maximum: null
        exclusiveMaximum: null
        minimum: null
        exclusiveMinimum: null
        maxLength: null
        minLength: null
        pattern: null
        maxItems: null
        minItems: null
        uniqueItems: null
        maxProperties: null
        minProperties: null
        required: null
        not: null
        properties: null
        additionalProperties: null
        nullable: null
        readOnly: null
        writeOnly: null
        example: null
        externalDocs: null
        deprecated: null
        discriminator: null
        xml: null
    }}
    additionalProperties: null
    nullable: null
    readOnly: null
    writeOnly: null
    example: null
    externalDocs: null
    deprecated: null
    discriminator: null
    xml: null
}}
  Exception: null
```

##### openapi-generator version

This is a regression introduced in OpenAPI generator 5.3.1. The build works properly in OpenAPI Generator 5.3.0.

##### OpenAPI declaration file content or url

Our OpenAPI file is here: https://github.com/plaid/plaid-openapi/blob/master/2020-09-14.yml
I ran it against the validator at https://apitools.dev/swagger-parser/online/ and it validated successfully.

##### Generation Details

Template generation files can all be found here: https://github.com/plaid/plaid-python/tree/master/templates/python

##### Steps to reproduce

We are attempting to run the Docker-based generator

**Comment by spacether** [comment]
@phoenixy1 the release that you mention is over a year old. How about using a newer openapi-generator version and changing the generator name to `python-prior`. The older python generator was renamed python-prior in https://github.com/OpenAPITools/openapi-generator/releases/tag/v6.2.0

**Comment by phoenixy1** [comment]
@spacether I was afraid to use 6.x because I know some of my colleagues tried to migrate our openapi generator version to 6.5.x and ran into some really gnarly issues, and I know 6.x is supposed to a breaking change -- but I actually tried it on 6.1 and the issue is fixed there, so I think I'll try to see if we can move at least our python lib to a 6.x-generated version. Thanks!
