### ISSUE TITLE
[BUG] [dart-dio] "name" is not a reserved word but should be. 

### ISSUE THREAD

**Issue by ChristianVaughn** [OpenAPITools/openapi-generator#15207]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

if you have an enum in your spec file with a value "name" then an error is present in the generated code. EnumClass from built_value package has a member variable `final String name;`. The model for the chunk of the schema blow generates a class that extends EnumClass and has `static const RequestSorting name = _$name;` which conflicts with the EnumClass member variable name

##### openapi-generator version

v6.5.0

##### OpenAPI declaration file content or url

```json
"RequestSorting": {
                "type": "string",
                "enum": [
                    "id",
                    "name"
                ]
            },
```

##### Generation Details
This is the config I used for the dart-dio generator using the cli
```json
{
  "pubName": "namehere",
  "modelPackage": "model",
  "apiPackage": "api",
  "withSeparateModelsAndApi": true,
  "generatorName": "dart-dio",
}
```

##### Steps to reproduce

Generate a dart-dio sdk containing a component of type string with enum containing "name" as one of the values. 

##### Suggest a fix

I think name needs to be added as a reserved word for the dart generator, so use of it gets changed to prevent the conflict with the built value package.

**Comment by kuhnroyal** [comment]
You can manually use the `--reserved-words-mappings` parameter or provide a PR that specifically excludes `name` for `EnumClass`.

**Comment by ChristianVaughn** [comment]
Thanks for `--reserved-words-mapping`. I couldn't find that mentioned on the website documentation.

**Comment by kuhnroyal** [comment]
> Thanks for `--reserved-words-mapping`. I couldn't find that mentioned on the website documentation.

You can find it here: https://openapi-generator.tech/docs/usage
