### ISSUE TITLE
[BUG][python-nextgen]Incorrect enum naming: "NUMBER_MINUS_1" is replaced by "NUMBER_-1"

### ISSUE THREAD

**Issue by hujiali0201** [OpenAPITools/openapi-generator#15289]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

"""
My code
"""
NUMBER_MINUS_1(-1)
NUMBER_0(0)
NUMBER_1(1)

But here's what I got

    """
    allowed enum values
    """
    NUMBER_-1 = -1
    NUMBER_0 = 0
    NUMBER_1 = 1

"NUMBER_-1 = -1" has syntax errors. "NUMBER_MINUS_1" is what I really want.

##### openapi-generator version
python-nextgen v6.5.0

**Comment by wing328** [comment]
@hujiali0201 thanks for reporting the issue. I've filed #15291 to fix it.
