### ISSUE TITLE
[Swift] Safer handling of enums

### ISSUE THREAD

**Issue by joeboyscout04** [OpenAPITools/openapi-generator#1529]
##### Description
There are [known issues](https://blog.novatec-gmbh.de/the-problems-with-swagger/) around how Swagger handles enums.  In Swift, if we attempt to parse an enum that doesn't exist, then it will fail.  This is problematic when for example, there is an enum of states, and then more states get added in future versions of the API.  The older Swagger clients will break instead of just ignoring the newer state.  

A workaround is of course to use Strings or Ints instead of Enum, but this is Swift and we like our code strongly-typed...enums are much better for the developer experience.  

Ideally, we could set a default value for the enum (typically "unknown" or similar) and then this value would be used as a fallback when the enum wasn't found in the list. 

##### openapi-generator version
3.3.3

##### Suggest a fix/enhancement

A proposal for a change could be something like this:
Where the "unknown" value could be annotated as the default for the enum in the swagger specification. 

```
public enum PhoneType: String {
    case iPhone7
    case iPhone8
    case iPhoneX
    case iPhoneXS
    case iPhoneXR
    case unknown

}

extension PhoneType: Codable {
    
    public init(from decoder: Decoder) throws {
        self = try PhoneType(rawValue: decoder.singleValueContainer().decode(String.self)) ?? .unknown
    }
}
```
I'm willing to send in a PR for this if anyone else thinks this might be a good idea.

**Comment by macjohnny** [comment]
cc @d-date

**Comment by parachutemind** [comment]
This one seems like an important thing to do. Otherwise, future proofing the clients against API extensions could be a problem.

**Comment by cerupcat** [comment]
@joeboyscout04 @macjohnny was this ever resolved? This is something we're running into. We need to add new enum cases without older clients crashing (which is currently what will happen).

**Comment by joeboyscout04** [comment]
I’m not sure.  I’m no longer working with Swagger/OpenAPI.

**Comment by biovolt** [comment]
This is definitely needed, please add

**Comment by jarrodparkes** [comment]
I was just about to write an issue for this very thing. Here's my implementation idea:

---

### Details

Swift has already discussed this type of idea (called "frozen and non-frozen enums") in [SE-0192](https://github.com/apple/swift-evolution/blob/master/proposals/0192-non-exhaustive-enums.md)

> Currently, adding a new case to an enum is a source-breaking change, something that's at odds with Apple's established process for evolving APIs. This proposal aims to distinguish between enums that are frozen (meaning they will never get any new cases) and those that are non-frozen, and to ensure that clients handle any future cases when dealing with the latter.

Unfortunately, as described in the proposal, non-frozen enums are not currently something third-parties can utilize.

> The features described here may be used by third-party libraries in the future.

### Possible Solution?

#### Old Behavior

Here's an example of how an enum might be defined as part of a `Product` object:

```json
{
  "title": "Product",
  "type": "object",
  "description": "An article or substance manufactured for sale.",
  "properties": {
    "id": {
      "type": "string"
    },
    "payment_status": {
      "type": "string",
      "enum": [
        "PAID",
        "UNPAID"
      ]
    }
  }
}
```

And how `Product` is generated today:

```swift
/// An article or substance manufactured for sale.
struct Product: Codable, Hashable {

    enum PaymentStatus: String, Codable, CaseIterable {
        case paid = "PAID"
        case unpaid = "UNPAID"
    }

    var id: String?
    var paymentStatus: PaymentStatus?

    // …
}
```

#### New Behavior

I'd like to propose defining a protocol like `CaseIterableDefaultsLast` which could result in a `Product` with an enum like this:

```swift
/// An enum where the last case value is "unknown" and can be used as a default catch-all.
protocol CaseIterableDefaultsLast: Decodable & CaseIterable & RawRepresentable 
where RawValue: Decodable, AllCases: BidirectionalCollection {}

extension CaseIterableDefaultsLast {
    /// Initializes an enum such that if a known raw value is found, then it is decoded.
    /// Otherwise the last case ("unknown") is used.
    /// - Parameter decoder: A decoder.
    public init(from decoder: Decoder) throws {
        if let value = try Self(rawValue: decoder.singleValueContainer().decode(RawValue.self)) {
            self = value
        } else if let lastValue = Self.allCases.last {
            self = lastValue
        } else {
            throw DecodingError.valueNotFound(
                Self.Type.self,
                .init(codingPath: decoder.codingPath, debugDescription: "CaseIterableDefaultsLast")
            )
        }
    }
}

/// An article or substance manufactured for sale.
struct Product: Codable, Hashable {

    enum PaymentStatus: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case paid = "PAID"
        case unpaid = "UNPAID"
        case unknown
    }

    var id: String?
    var paymentStatus: PaymentStatus?

    // …
}
```

This could be enabled with a `swift5` generator option. 

@joeboyscout04 Thoughts?

**Comment by jarrodparkes** [comment]
swift maintainers:

@jgavris @ehyche @Edubits @jaz-ah @4brunu

**Comment by 4brunu** [comment]
This is something that is a big issue. Looks good to me, @jarrodparkes could you please open a PR?

**Comment by jarrodparkes** [comment]
@4brunu yes — im planning on opening one today 😄

**Comment by jarrodparkes** [comment]
@4brunu

I've almost got an initial PR done, running into some issues figuring out how to compute the raw value for the `.unknown` case:

Here's the problematic/generated code:

```swift
    public enum EnumString: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
        case unknown
    }
    public enum EnumStringRequired: String, Codable, CaseIterable, CaseIterableDefaultsLast {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
        case unknown
    }
    public enum EnumInteger: Int, Codable, CaseIterable, CaseIterableDefaultsLast {
        case _1 = 1
        case number1 = -1
        case unknown
    }
    public enum EnumNumber: Double, Codable, CaseIterable, CaseIterableDefaultsLast {
        case _11 = 1.1
        case number12 = -1.2
        case unknown
    }
```

Most of those enums can implicitly determine a value for `.unknown`. But `EnumNumber` is an issue. Any suggestions on how to workaround this?

**Comment by jarrodparkes** [comment]
https://docs.swift.org/swift-book/LanguageGuide/Enumerations.html

> When you’re working with enumerations that store integer or string raw values, you don’t have to explicitly assign a raw value for each case. When you don’t, Swift automatically assigns the values for you.

@4brunu I'm trying to see if there is a way that I could only apply `CaseIterableDefaultsLast` if the raw type is int/string (and other conditions hold)

**Comment by jarrodparkes** [comment]
@4brunu ^ I think ive got something 👍

**Comment by 4brunu** [comment]
This should be fixed by https://github.com/OpenAPITools/openapi-generator/pull/11013
