### ISSUE TITLE
[BUG][dart] Dart default dio doesn't work since upgrade to dio 5

### ISSUE THREAD

**Issue by kyrias** [OpenAPITools/openapi-generator#15297]
#### Bug Report Checklist

- [/] Have you provided a full/minimal spec to reproduce the issue?
- [/] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The dart generator defaults to creating a `Dio` insteance with a `baseUrl` that doesn't contain a relative URL without a hostname.  With dio <5.0 this worked, but as of 5.0 this is no longer accepted and triggers an assertion.

##### openapi-generator version

master, 6.5, 6.4.

##### Generation Details

Generate code for dart-dio using any spec.

##### Steps to reproduce

- Generate code for dart-dio using any spec.
- Create an instance of the generated api class without passing in a `Dio` instance.
- Use the api class in any way, including just the serializers.
- The following assertion will be triggered: https://github.com/cfug/dio/issues/1655

##### Related issues/PRs

Broken by https://github.com/OpenAPITools/openapi-generator/pull/14675.

**Comment by ahmednfwela** [comment]
you can override the baseUrl no ?

@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

**Comment by kuhnroyal** [comment]
I don't exactly understand what you mean. We can only generate the base URL that is provided in the spec, if that one is incorrect, you have to manually override it.

Dio 5 now validates that the `baseUrl` is a valid `Uri` - if yours is not, then you need to configure it or adapt your spec.

**Comment by kyrias** [comment]
Oh I was confused by the fact that the template variable that generates the api class is called `basePath` whereas it's actually the full server URL from the spec and not the real base path.

It's a bit unfortunate because our spec apparently just has a URL of `/api/v1` since we host many instances of the service for different customers, and it would be nice if it was possible to just supply the host rather than having to duplicate `/api/v1` everywhere we instantiate a client.

**Comment by kuhnroyal** [comment]
The `basePath` is available as static const on the generated API client, you could use it like this in your case.

```dart
final client = Openapi(basePathOverride: '$host${Openapi.basePath}');
```
