### ISSUE TITLE
[BUG] python-nextgen, ModuleNotFoundError

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#15296]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Unable to import generated lib

##### openapi-generator version

6.5.0

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/917892db7d1dc5a459bdf6d499a491367fc97751/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Generation Details

docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v6.5.0 generate \
    -i /local/petstore.yaml \
    -g python-nextgen \
    -o /local/openapi_generator_python_nextgen

##### Steps to reproduce

- generate the client
- install it into a local venv `python setup.py install`
- enter the venv and import openapi_client

With python 3.9.6 I get:
```
ModuleNotFoundError: No module named 'pydantic_core'
```

**Comment by wing328** [comment]
https://github.com/wing328/python-ci-test/actions/runs/4792778971 shows that python 3.9 (and other versions) seems to work fine with the output.

maybe the issue has to do with the venv? are you using the latest version of venv?

have you tried to repeat the issue in another machine?

**Comment by spacether** [comment]
Must be my machine/venv
