### ISSUE TITLE
[BUG] [python-nextgen]Java Annotation @Deprecated has not taken effect

### ISSUE THREAD

**Issue by hujiali0201** [OpenAPITools/openapi-generator#15308]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
"""
My Java Code
"""
@Override
@Deprecated
public ResponseEntity<ProjectListResponseDTO> getAllProjects(@Valid Integer orgId) {
    // 不维护的接口
    return ResponseEntity.notFound().build();
}

The "getAllProjects" interface should be marked deprecated. But here's what I got

@validate_arguments
def get_all_projects(self, org_id : Optional[StrictInt] = None, **kwargs) -> ProjectListResponseDTO:  # noqa: E501
    kwargs['_return_http_data_only'] = True
    return self.get_all_projects_with_http_info(org_id, **kwargs)  # noqa: E501

##### openapi-generator version
python-nextgen v6.5.0

**Comment by wing328** [comment]
https://peps.python.org/pep-0702/

looks like `deprecated` decorator "will" be supported in python 12 instead.

we can update the docstring/comment to include "deprecated" for the time being.
