### ISSUE TITLE
[BUG][PYTHON-NEXTGEN] I am unable to send empty json 

### ISSUE THREAD

**Issue by murphp15** [OpenAPITools/openapi-generator#15328]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
I want to be able to send an empty json object e.g. {}. 

However when I pass in an empty dict it sends an empty body over the network. 
I realize that more servers probably handle a missing body as an empty json. 
But we have tests which require the empty body. 

The line responsible for it is here: 
https://github.com/OpenAPITools/openapi-generator/blob/e211e1451d8da4300e1fa48d4f7a7169f4d223cc/samples/openapi3/client/petstore/python-nextgen/petstore_api/api/fake_api.py#L161

If we checked that the body was not None instead then we would be able to send empty bodies. 

##### openapi-generator version

6.5.0

##### OpenAPI declaration file content or url
I'm not going to provide a test case as it is reproduced in the examples in your repo. 

##### Generation Details
Generate it the way you generate the samples for your project. 

##### Steps to reproduce
reproduce the sample linked above.

**Comment by wing328** [comment]
thanks for reporting the issue. i'll take a look over the weekend

**Comment by wing328** [comment]
@murphp15 I've filed https://github.com/OpenAPITools/openapi-generator/pull/15336 to fix the issue with some tests.
