### ISSUE TITLE
[REQ][Kotlin] Add spring webclient library

### ISSUE THREAD

**Issue by DSniatecki** [OpenAPITools/openapi-generator#15320]
I suggest adding spring webclient as a library for kotlin generator. 

Webclient is often used with spring boot and if there is kotlin-spring generator, there should be possibility to generate kotlin client  with webclient library.

**Comment by Sekir9** [comment]
> I suggest adding spring webclient as a library for kotlin generator.
> 
> Webclient is often used with spring boot and if there is kotlin-spring generator, there should be possibility to generate kotlin client with webclient library.

Good idea, that would be very helpful

**Comment by stefankoppier** [comment]
This would be good addition. I'd like to give this a shot.
