### ISSUE TITLE
[JAVA] Snake case field name gets converted to camel case with codegen

### ISSUE THREAD

**Issue by riju4git** [OpenAPITools/openapi-generator#15389]
##### Description
Our POJO has some fields which look like this 

```
@Getter 
@Setter
public class Error {
    String errorName;
    String errorCode;
    String error_code;
}
```
Using mvn plugin we generate the openapi document (say api-service.json) and it creates the fields(errorCode and error_code) as expected like this (Adding just a snippet)

```
....
          "errorCode" : {
            "type" : "string"
          },
          "errorName" : {
            "type" : "string"
          },
          "error_code" : {
            "type" : "string"
          },
....
```

Now, when the client uses codegen (command below), the field **error_code** and its corresponding getters and setters are converted to errorCode and _clashes with the already existing field_ , thus creating compilation error. 

**Generated Java file**
```
....
  @SerializedName("errorCode")
  private String errorCode = null;

  @SerializedName("error_code")
  private String errorCode = null; // this line and its getter/setters naturally causes compile issues
....
```

##### openapi codegen version
6.5.0

##### Command line used for generation

```
openapi-generator generate \
  -i /Users/sh/api-service.json \
  --api-package com.company.services \
  --model-package com.company.services.dto \
  --invoker-package com.company.services.app \
  --group-id com.company.services \
  --artifact-id checkout-service-api \
  --artifact-version 0.0.1-SNAPSHOT \
  --skip-validate-spec \
  --generate-api-tests false \
  -g java \
  -o output-april-2023
```

How do I retain the original field name of error_code in the generated code after running openapi-generator ?

**Comment by wing328** [comment]
you can fix it using the name mappnig feature to map error_code to whatever you want: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping
