### ISSUE TITLE
[BUG] [dart] deserialization a double without decimal place will always return null value

### ISSUE THREAD

**Issue by chowwaiming** [OpenAPITools/openapi-generator#15393]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When the json body contain a double/decimal field without decimal place, the deserialization process will throw exception. e.g.
when the json is
{
  "myDouble" : 0.0
} 
the deserialization is ok

however if it is
{
  "myDouble" : 0
} 

the deserialization throw exception

##### openapi-generator version

v6.5.0

**Comment by ahmednfwela** [comment]
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)

**Comment by kuhnroyal** [comment]
What exception?

**Comment by chowwaiming** [comment]
`T? mapValueOfType<T>(dynamic map, String key) {
  final dynamic value = map is Map ? map[key] : null;
  return value is T ? value : null;
}`

in the api_helper.dart, if the value is a double without decimal place, it will return null, suppose we can have some handling in this method. Attached please find a debug screen cap for your reference. Thanks

[https://drive.google.com/file/d/1qmcToZQf7eP4DK9YhOj9dY5HOpnpWFzp/view](url)

**Comment by kuhnroyal** [comment]
This is in the `dart` generator, not `dart-dio`.

**Comment by alexwastl** [comment]
Reproduced the issue as well. 
As long as there is no decimal point in the json body a 'null check operator' exception is thrown. 
-> Using the dart generator to generate the files. As @chowwaiming as written this is causes by the 

T? **mapValueOfType**<T>(dynamic map, String key)

function.

Would be very helpful to have some clarification there.

**Comment by daniele-athome** [comment]
I'm guessing the issue could be addressed in one of the following ways:

* modify native_class.mustache to take `isDouble` into account and treat it like the `#isNumber` case (although that would not handle non-nullable fields, another bug ASAIU)
* modify native_class.mustache to take `isDouble` into account and treat it like the `^isNumber` case, forcing `<num>` as parameter and than doing `toDouble` to the return value - implemented here: https://github.com/daniele-athome/immich/commit/05826c8e5ed80675edd0235592d493027a17e655#diff-b6f7671e5e04f1b69a72f407694c4808fa87585e6bab456fda57d750a8e0c7f0
* modify native_class.mustache `mapValueOfType` method as suggested by @IIIalexmuellerIII - implemented here: https://github.com/immich-app/immich/issues/3935#issuecomment-1701821321
* modify something else (I don't really know what) to make `isNumber` be true also when the number is a double (best solution IMHO, fixes the problem at the source)

But that was just me finding a way to make Immich (a project affected by this bug) work again and studying this project for like 1 hour, so I might not know what I'm saying really.
