### ISSUE TITLE
[python-nextgen] mypy errors when passing dicts to request functions

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#15398]
##### Description

When passing raw dictionaries to generated request functions, the `@pydantic.validate_arguments` decorator automatically converts them to the correct model classes.

However, mypy (and probably other type checkers) doesn't understand this and reports an "incompatible type" error.

##### openapi-generator version

6.5.0

##### Related issues/PRs

#15391

##### Suggest a fix

Ideally, pydantic should fix this upstream by either improving the type annotations of `validate_arguments` or extending their mypy plugin. This won't happen before the v2 release, which might change the behavior here anyway.

Then OpenAPI generator could try to work around this issue by using e.g. a `Union[Mapping, ....]` type annotation for such function arguments. This worked nicely for me in a local test.

**Comment by robertschweizer** [comment]
Thinking about this again:

Pydantic (with or without the mypy plugin) does not let mypy pass on code that only works through type coercion, but wouldn't work in strict mode. Because of that, I don't think this client generator should do that either.

I guess the reason for pydantic's strict typing is this: Even though pydantic allows type coercion, it is inherently unsafe (e.g. floats might be rounded to integers losing information). Someone running a type checker probably wants to avoid such half-safe coercion.

@spacether: If you agree, please close this issue.

**Comment by spacether** [comment]
@wing328 is the python nextgen author, I defer to him

**Comment by multani** [comment]
@robertschweizer Can you check this issue again? With the new Pydantic v2 generator, I think this should not be a problem anymore.

**Comment by robertschweizer** [comment]
I just checked and the behavior does not change between the Pydantic v1 and Pydantic v2 generators: Mypy requires one to pass a model class instance to the request function, it does not allow dictionaries.

I will close this issue though, because I think it is correct that mypy enforces pydantic's "strict" mode.
