### ISSUE TITLE
[BUG][SPRING] x-field-extra-annotation missing in 6.5.0

### ISSUE THREAD

**Issue by tofi86** [OpenAPITools/openapi-generator#15408]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

regression in 6.5.0

##### OpenAPI declaration file content or url

This OA spec snippet

```yaml
    CompanyDto:
      type: object
      description: ....
      properties:
        priceCategory:
          description: The price category
          nullable: true
          x-field-extra-annotation: '@IgnoreForRoles("MEDIA_ADMIN")'
          allOf:
            - $ref: '#/components/schemas/SamplingPriceCategoryEnum'
```

##### Expected Output

... produced the following output in v6.4.0 (using `openApiNullable = true`):

```java
  @JsonProperty("priceCategory")
  @IgnoreForRoles("MEDIA_ADMIN")
  private JsonNullable<SamplingPriceCategoryEnum> priceCategory = JsonNullable.undefined();
```

##### Actual Output

... but produces the following in 6.5.0:

```java
  private JsonNullable<SamplingPriceCategoryEnum> priceCategory = JsonNullable.undefined();
```

**Comment by borsch** [comment]
@tofi86 could you please share plugin configuration/CLI command that you are using

**Comment by jkt628** [comment]
i'm seeing this from gradle plugin `org.openapi.generator` configured with

```groovy
tasks.register('generateEventRouter', GenerateTask) {
	generatorName.set("spring")
	inputSpec.set(eventRouter)
	outputDir.set("$buildDir/generated/openapi")
	apiPackage.set("eventRouter.rest")
	modelPackage.set("eventRouter.model")
	configOptions.set([
		interfaceOnly: "true"
	])
}
```

i tried versions back to `6.2.0` with no joy.

**Comment by borsch** [comment]
@jkt628 can you create minimal reproducible example? I've tried latest master, but it works as expected

**Comment by tofi86** [comment]
@borsch sure, this is my maven configuration:

```xml
<configuration>
    <inputSpec>${project.basedir}/src/main/resources/test-15408.yaml</inputSpec>

    <generatorName>spring</generatorName>
    <library>spring-boot</library>

    <apiPackage>org.example.backend.api.generated</apiPackage>
    <invokerPackage>org.example.backend.api.generated.handler</invokerPackage>
    <modelPackage>org.example.backend.data.generated</modelPackage>

    <globalProperties>
        <!--
            Don't skip form model (multipart/form-data) generation as this has a bug as described in:
            https://github.com/OpenAPITools/openapi-generator/issues/12036
        -->
        <skipFormModel>false</skipFormModel><!-- default: true -->
    </globalProperties>

    <configOptions>
        <basePackage>org.example.backend.api</basePackage>
        <configPackage>org.example.backend.api.v1.config</configPackage>

        <!-- Use interfaceOnly pattern... -->
        <interfaceOnly>true</interfaceOnly><!-- default: false -->

        <!-- Use Java 8 LocalDate/LocalDateTime classes for dates -->
        <dateLibrary>java8-localdatetime</dateLibrary><!-- default: java8 -->

        <!-- Enable OpenAPI Jackson Nullable library for models -->
        <openApiNullable>true</openApiNullable><!-- default: false -->

        <!-- Use Bean Validation Impl. to perform BeanValidation -->
        <useBeanValidation>true</useBeanValidation><!-- default: true -->
        <performBeanValidation>true</performBeanValidation><!-- default: false -->

        <!-- Use Optional<> classes for non-required request params -->
        <useOptional>true</useOptional><!-- default: false -->

        <!-- Hides the generation timestamp when files are generated -->
        <hideGenerationTimestamp>true</hideGenerationTimestamp><!-- default: false -->

        <!-- Do not generate springdoc/springfox docs -->
        <documentationProvider>none</documentationProvider><!-- default: springdoc -->
    </configOptions>
    <typeMappings>
        <typeMapping>time=java.time.LocalTime</typeMapping>
    </typeMappings>
</configuration>
```

And this is the test spec I was using for the example:

```yaml
openapi: 3.0.3

info:
  title: "API"
  description: "REST API"
  version: 0.0.1
  license:
    name: "GNU General Public License v3.0"
    url: "https://choosealicense.com/licenses/gpl-3.0/"
  contact:
    name: "Team"
    email: "test@example.org"
    url: "https://www.example.org.de"


servers:
  - url: http://localhost:8080
    description: Local development server


components:

  securitySchemes:
    BearerAuth:
      description: JWT authorization header using the Bearer scheme.
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    CompanyDto:
      type: object
      properties:
        priceCategory:
          description: The price category
          nullable: true
          x-field-extra-annotation: '@IgnoreForRoles("MEDIA_ADMIN")'
          allOf:
            - $ref: '#/components/schemas/SamplingPriceCategoryEnum'

    SamplingPriceCategoryEnum:
      description: The price category of a sampling action
      type: string
      enum:
        - FREE
        - PRICE_TIER_1
        - PRICE_TIER_2


security:
  - bearerAuth: [ ]


paths:

  /company:
    summary: Represents a Company
```

Generated Java code looks like this:

```java
public class CompanyDto {

  private JsonNullable<SamplingPriceCategoryEnum> priceCategory = JsonNullable.undefined();

  public CompanyDto priceCategory(SamplingPriceCategoryEnum priceCategory) {
    this.priceCategory = JsonNullable.of(priceCategory);
    return this;
  }

  /**
   * Get priceCategory
   * @return priceCategory
  */
  @Valid 
  @JsonProperty("priceCategory")
  public JsonNullable<SamplingPriceCategoryEnum> getPriceCategory() {
    return priceCategory;
  }

  public void setPriceCategory(JsonNullable<SamplingPriceCategoryEnum> priceCategory) {
    this.priceCategory = priceCategory;
  }

 ...
```

**Comment by jkt628** [comment]
minimal(ish) example: https://github.com/jkt628/x-field-extra-annotation

**Comment by borsch** [comment]
> i found an ugly way to at least mark the first field with `@Id` through [jkt628/x-field-extra-annotation@a040d18](https://github.com/jkt628/x-field-extra-annotation/commit/a040d18b2352c1465944d0a7ef63d54f2382fb7b). going through [pojo.mushtache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache#L55-L57) it looks like `vendorExtensions.x-field-extra-annotation` is not set for the field which will bomb a bunch of generators.


Unfortunately you can't use both `$ref` & `x-field-extra-annotation` at same time. This would be the correct approach

```yaml
    EventRouterMessage:
      type: object
      x-class-extra-annotation: |-
        @javax.persistence.Entity
        @javax.persistence.Table(name="event_router_requests")
      properties:
        guid:
          x-field-extra-annotation: |-
            @javax.persistence.Id
            @javax.persistence.Column(name = "id")
          type: string                  <--- this is the change. use direct configuration here instead of $ref
          pattern: '^[0-9A-Fa-f]{8}-(?:[0-9A-Fa-f]{4}-){3}[0-9A-Fa-f]{12}$'
        accounting:
          $ref: '#/components/schemas/Accounting'
        event:
          $ref: '#/components/schemas/Event'
```

**Comment by borsch** [comment]
@tofi86 same issue with yours spec - swagger can't handle both `$ref`/`$allOf`/`$onOff` & extensions or other field. In your case correct schema would be


```yaml
    CompanyDto:
      type: object
      properties:
        priceCategory:
          description: The price category
          nullable: true
          x-field-extra-annotation: '@IgnoreForRoles("MEDIA_ADMIN")'
          type: string     <---- this is the change. Move enum here instead of allOf + $ref
          enum:
          - FREE
          - PRICE_TIER_1
          - PRICE_TIER_2
          title: SamplingPriceCategoryEnum
```

**Comment by tofi86** [comment]
@borsch Sure, this could be a valid solution for this issue.

But on the other hand
* the enum wouldn't be reusable anymore (no enum class is generated).
* it worked just fine in 6.4 🤷‍♂️

**Comment by borsch** [comment]
> @borsch Sure, this could be a valid solution for this issue.
> 
> But on the other hand
> 
>     * the enum wouldn't be reusable anymore (no enum class `SamplingPriceCategoryEnum` is generated).
> 
>     * it worked just fine in 6.4 🤷‍♂️

I'll check 6.4.0 version

**Comment by jkt628** [comment]
unfortunately, i'm coming around to recognize openapi-generator is just not flexible enough for what i want to do without a lot of customization.  in the long run it will be more maintainable to find another way to meet my needs.

**Comment by tofi86** [comment]
@borsch why closed? You wanted to check v6.4.0 where this worked 🤷

**Comment by borsch** [comment]
@tofi86 could you please create minimal project which generate expected code with 6.4.0, but not with 6.5.0.

I've tried this project, but getting same code with both versions
> minimal(ish) example: https://github.com/jkt628/x-field-extra-annotation

Also based on diff https://github.com/OpenAPITools/openapi-generator/compare/v6.4.0...v6.5.0 I also haven't found anything suspicious yet

**Comment by tofi86** [comment]
@borsch cannot speak for the repo you mentioned as it isn't mine. Did you try with my example code from further above? -> https://github.com/OpenAPITools/openapi-generator/issues/15408#issuecomment-1536065966

If this doesn't help or work for you I can try to set up a small project later today or tomorrow...

**Comment by borsch** [comment]
@tofi86 I've finally found what the issue here. This regression was introduced after https://github.com/OpenAPITools/openapi-generator/pull/14882 where special handling was added for `allOf` with single schema. I'll create PR with fix

@jkt628 BTW. This fix should also work for you if use simple change `$ref` to `allOf` + single `$ref`. So in you case it would be

```yaml
EventRouterMessage:
      type: object
      x-class-extra-annotation: |-
        @javax.persistence.Entity
        @javax.persistence.Table(name="event_router_requests")
      properties:
        guid:
          x-field-extra-annotation: |-
            @javax.persistence.Id
          allOf:                        <-- this is the change from $ref to allOf+$ref
            - $ref: '#/components/schemas/GUID'
```

**Comment by borsch** [comment]
@tofi86 @jkt628 please try 7.0.0-SNAPSHOT build once build from 26 of May would be available here

https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.0.0-SNAPSHOT/
