### ISSUE TITLE
[BUG] [JAVA] the non-parametric constructor in DTOs is wrongly marked as deprecated

### ISSUE THREAD

**Issue by vlavasa** [OpenAPITools/openapi-generator#15478]
From openapi-generator version 6.5.0 in Java DTO classes there are all default parameterless constructors now marked as Deprecated, and there are added new parametric constructor with fields defined in OpenAPI as required

It's a very bad idea for the following reasons:

1) if the company uses quality controls, all existing code is now reported as using the deprecated method

2) code using a parametric constructor as opposed to builder methods is less resistant to changes in the OpenAPI definition, such as changing the attribute obligation and **especially changing its order**!

In addition, the parametric constructor must remain in the code forever, because the json parser needs it, so marking it as deprecated is clearly wrong!
Please remove this nonsense.

**Comment by TedGardner** [comment]
The deprecated constructor was actually quite useful in enforcing that required fields always be provided. If someone used the incorrect constructor without arguments, they could return an object that violated the contract that the API specification defined. Technically they could call the constructor with `null` arguments, but they'd have to intentionally do that.

Was there an option to re-enable it, or was that feature just removed entirely?

**Comment by vlavasa** [comment]
@TedGardner I understand your arguments, but deprecating parameterless constructors is not a good way to address this issue. In my opinion, code like this:

`new SomeClass(aaa, bbb, ccc)`

is less resistant to changes in the OpenAPI definition, especially when **changing the order of attributes**, compared to code like this:

`new SomeClass().paramAaa(aaa).paramBbb(bbb).paramCcc(ccc)`

Here, you have **explicitly declared which parameter you are setting**.

I agree that the current DTO classes are not well-designed. The Builder pattern here is poorly implemented.

I would suggest something like an **immutable** class with a builder pattern and with @JsonCreator. If we have a correct builder pattern, for example, **like the one generated by Lombok**, we can do:

`SomeClass.builder().paramAaa(aaa).paramBbb(bbb).paramCcc(ccc).build()`

Here, in the build() method, you can call a constructor with parameters, and inside the constructor, you can have some non-null assertions.

So, in my opinion, the right solution is to fully refactor the generated code in the next major (not backward-compatible) release. Making the current not-so-good code even worse by adding the deprecated annotation is not a good idea!
