### ISSUE TITLE
Missing option `inputSpecRootDirectory` for `openApiGenerate` task (Gradle plugin)

### ISSUE THREAD

**Issue by rocklass** [OpenAPITools/openapi-generator#15483]
##### Description

The option `inputSpecRootDirectory` for `openApiGenerate` task (Gradle plugin) is missing while it is mentioned in the [doc](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin#openapigenerate).

##### openapi-generator version

`6.6.0` (and also `7.0.0`)

**Comment by borsch** [comment]
@rocklass could you please try 7.0.0-SNAPSHOT?

**Comment by mrclrchtr** [comment]
When I try to use `inputSpecRootDirectory`, I get the following error message:
`- Type 'org.openapitools.generator.gradle.plugin.tasks.GenerateTask' property 'inputSpecRootDirectory' file '/Users/xx/xx/specifications' is not a file.`
It's correct, it is not a file, but a directory. Shouldn't this work with a dir?

**Comment by tstphnsn** [comment]
> When I try to use `inputSpecRootDirectory`, I get the following error message: `- Type 'org.openapitools.generator.gradle.plugin.tasks.GenerateTask' property 'inputSpecRootDirectory' file '/Users/xx/xx/specifications' is not a file.` It's correct, it is not a file, but a directory. Shouldn't this work with a dir?

Note that as of 7.1.0 this functionality works.
