### ISSUE TITLE
[BUG][python-nextgen] SyntaxError in from_dict call

### ISSUE THREAD

**Issue by feluelle** [OpenAPITools/openapi-generator#15487]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am running into the following issue in the `from_dict` call:
```
E       for _ik, _iv in _v.items()
E       ^^^
E   SyntaxError: invalid syntax
```

##### openapi-generator version

6.6.0

##### Related issues/PRs

See https://github.com/OpenAPITools/openapi-generator/pull/15239

##### Suggest a fix

See https://github.com/OpenAPITools/openapi-generator/pull/15239#discussion_r1192035455

**Comment by wing328** [comment]
update: filed #15844 to fix it
