### ISSUE TITLE
[BUG] If two api have the same schema, the second type is not generated

### ISSUE THREAD

**Issue by Ryoto-kubo** [OpenAPITools/openapi-generator#15497]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If two api have the same schema, the second type is not generated

##### openapi-generator version

"@openapitools/openapi-generator-cli": "^2.5.2"

##### OpenAPI declaration file content or url

```yaml
/api/hoge/:
  post:
    summary: Api hoge
    operationId: api-hoge
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - token
            properties:
              token:
                type: string
/api/foo/:
    post:
      summary: Api foo
      operationId: api-foo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - token
              properties:
                token:
                  type: string
```

##### Generation Details

It is expected that an axios client will be generated based on the operationId and the following two types will be generated.
- ApiHogeRequest.
- ApiFooRequest

However, only `ApiHogeRequest` will be generated and an `ApiHogeRequest` with the same structure will be used for the Request type in `/api/foo/`

##### Steps to reproduce

config.yml
```yml
enumPropertyNaming: 'camelCase'
supportsES6: true
useSingleRequestParameter: true
```

```bash
$ openapi-generator-cli generate -g typescript-axios -c ./config.yml -i ./schema.yml -o ./api/generated --global-property skipFormModel=false
```

**Comment by Ryoto-kubo** [comment]
I don't know what is fundamentally happening, although setting title in schema is a workaround

**Comment by wing328** [comment]
What about using `SKIP_SCHEMA_REUSE=true` in schema name default option ?

https://openapi-generator.tech/docs/customization/#inline-schema-naming has more details.

**Comment by Ryoto-kubo** [comment]
@wing328 
Thank you! It worked!
