### ISSUE TITLE
[BUG] [Python] DefaultValue does not escape backslash

### ISSUE THREAD

**Issue by HeikoStudt** [OpenAPITools/openapi-generator#15541]
#### Bug Report Checklist

- [~] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
We have got an OpenAPI specification which has a defaultValue for a String of `"\\"` (backslash).

The python-nextgen (nowadays python) generator does not escape the backslash while generating the python model code on two occasions.

##### openapi-generator version
openapi-generator 6.6.0.0 (using the maven plugin)

##### OpenAPI declaration file content or url

```yaml
    TestParam:
      type: object
      properties:
        escape:
          type: string
          minLength: 1
          maxLength: 1
          default: "\\"
```

##### Generation Details
Maven-Plugin using "python-nextgen"

##### Steps to reproduce
Using the above snippet in your OpenAPI spec, generating the python-client and try to import/run it will fail with either of the following errors until you provide an extra backslash (to escape the generated one).

Instead of `'\'` it should output `'\\'` for the `{{defaultValue}}` mustache template.

```
  File "/python/your_api/models/test_param.py", line 34
    escape: Optional[constr(strict=True, max_length=1, min_length=1)] = '\'

SyntaxError: unterminated string literal (detected at line 34)
```

```
  File "/python/your_api/models/test_param.py", line 81
    "escape": obj.get("escape") if obj.get("escape") is not None else '\',

SyntaxError: unterminated string literal (detected at line 81)
```

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/15031

##### Suggest a fix

The following code escapes line breaks and single quotes, but not the escape char (backslash) before doing so.

AbstractPythonCodegen.java::toDefaultValue (135)
```java
        } else if (ModelUtils.isStringSchema(p)) {
            if (p.getDefault() != null) {
                if (Pattern.compile("\r\n|\r|\n").matcher((String) p.getDefault()).find())
                    return "'''" + p.getDefault() + "'''";
                else
                    return "'" + ((String) p.getDefault()).replace("'", "\'") + "'";
            }
```

Probably better (untested):

```java
        } else if (ModelUtils.isStringSchema(p)) {
            String defaultValue = (String)p.getDefault();
            if (defaultValue != null) {
                defaultValue = defaultValue.replace("\\", "\\\\") .replace("'", "\'");
                if (Pattern.compile("\r\n|\r|\n").matcher(defaultValue).find())
                    return "'''" + defaultValue + "'''";
                else
                    return "'" + defaultValue + "'";
            }
```

**Comment by wing328** [comment]
can you please file a PR with the suggested fix when you've time? we can try to add some tests on top of your fix.
