### ISSUE TITLE
[REQ] Updating Rust `reqwest` from `0.9` to `0.11` when using async

### ISSUE THREAD

**Issue by ShayBox** [OpenAPITools/openapi-generator#15549]
### Is your feature request related to a problem? Please describe.

The Rust `reqwest` library currently generates as `~0.9` when using sync, while it generates as `0.11` when using async.
This can cause type-matching problems with libraries generated with `openapi-generator` and packages/crates using them, it also lacks improvements such as cookie stores.

## Describe the solution you'd like

Updating the library version, enabling the `blocking` feature flag when using sync, swapping the types from the old `reqwest::Client` (0.9-sync) to the new `reqwest::blocking::Client` (0.11-sync), and enabling some feature flags such as `json`, `multipart`, `cookies`, etc.

**Comment by KisaragiEffective** [comment]
I will handle this, as this may open potential some known vulns.
