### ISSUE TITLE
[BUG] Python Generator - Incorrect validation for date and datetime query parameters

### ISSUE THREAD

**Issue by thiagofelix** [OpenAPITools/openapi-generator#15554]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The recent addition of support for date and date-time formats in PR #14799 has introduced a validation problem. Currently, the validation process incorrectly utilizes the `isinstance` function to determine if incoming query parameters are valid dates or datetimes. The issue arises when the validation always checks against `datetime`, even when the query parameter is a `date`.

https://github.com/OpenAPITools/openapi-generator/blob/d60b10826c41b617633a582d9f7da0dd0ff247f8/modules/openapi-generator/src/main/resources/python/api.mustache#L201-L206

The code above should be `if isinstance(_params['{{paramName}}'], date):` 

##### openapi-generator version

```7.7.0-SNAPSHOT```

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  description: Demo spec containing query param with format=date
  version: 1.0.0
  title: Demo Spec Query Param format=date
paths:
  /date-query-params:
    get:
      parameters:
        - name: date_query
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Success
```

##### Steps to reproduce

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i  openapi.yaml -o test -g python
```

##### Related issues/PRs
#14799 

##### Suggest a fix

Update the [code mentioned](https://github.com/OpenAPITools/openapi-generator/blob/d60b10826c41b617633a582d9f7da0dd0ff247f8/modules/openapi-generator/src/main/resources/python/api.mustache#L201-L206) in the description by the following:
```
            {{#isDate}}
            if isinstance(_params['{{paramName}}'], date):
                _query_parame.append(('{{baseName}}', _params['{{paramName}}'].strftime(self.api_client.configuration.date_format)))
            else:
                _query_params.append(('{{baseName}}', _params['{{paramName}}']))
            {{/isDate}}
```

**Comment by wing328** [comment]
Thanks for reporting the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/15675 to fix it.

**Comment by thiagofelix** [comment]
> Thanks for reporting the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/15675 to fix it.
> 
> 

Thank you! Any chance I could become a member to help fixing this sort of issues? I am investing some time in the generators currently at my job :)

**Comment by wing328** [comment]
Feel free to file a PR to enhance the Python generator (or other parts of this project). We definitely welcome more contributions: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements

I hope you find this project useful in your work.
