### ISSUE TITLE
ArgumentNullException when operation is null in GetOperationServerUrl

### ISSUE THREAD

**Issue by racsus** [OpenAPITools/openapi-generator#15576]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

For the Yapily openapi definition [https://api.yapily.com/docs/v3/openapi.json](https://api.yapily.com/docs/v3/openapi.json), the `Operation` and `OperationIndex` properties are not defined for each endpoint(i.e.: `AddUserUsingPOSTWithHttpInfoAsync`) and because of that, the method `GetOperationServerUrl` in the class `Configuration` raise an `ArgumentNullException`:

```
        /// <summary>
        /// Returns URL based on operation server settings.
        /// </summary>
        /// <param name="operation">Operation associated with the request path.</param>
        /// <param name="index">Array index of the server settings.</param>
        /// <param name="inputVariables">Dictionary of the variables and the corresponding values.</param>
        /// <return>The operation server URL.</return>
        public string GetOperationServerUrl(string operation, int index, Dictionary<string, string> inputVariables)
        {
            if (OperationServers.TryGetValue(operation, out var operationServer))
            {
                return GetServerUrl(operationServer, index, inputVariables);
            }

            return null;
        }
```
It seems a null validation is missing.

##### openapi-generator version

openapi-generator-cli 6.6.0
  commit : 7f8b853
  built  : -999999999-01-01T00:00:00+18:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/

##### Generation Details

	openapi-generator generate -i \
		https://api.yapily.com/docs/v3/openapi.json \
		-g csharp-netcore \
		--package-name Vestiver.Yapily \
		--model-package Models \
		--api-package Services \
		--api-name-suffix Service \
		--inline-schema-name-defaults arrayItemSuffix= \
		--global-property apiDocs=false,apiTests=false,modelDocs=false,modelTests=false

##### Suggest a fix

Add a null check before executing the `TryGetValue`

        public string GetOperationServerUrl(string operation, int index, Dictionary<string, string> inputVariables)
        {
            if (operation is null)
                 return null;

            if (OperationServers.TryGetValue(operation, out var operationServer))
            {
                return GetServerUrl(operationServer, index, inputVariables);
            }

            return null;
        }

**Comment by wing328** [comment]
Can you please submit a PR with the suggested fix? Let me know if you need any help.

**Comment by racsus** [comment]
> Can you please submit a PR with the suggested fix? Let me know if you need any help.

Done. https://github.com/OpenAPITools/openapi-generator/pull/15599
