### ISSUE TITLE
[BUG] Build runner Logger Error

### ISSUE THREAD

**Issue by kaj777** [OpenAPITools/openapi-generator#15628]
##### Description

Generate was working fine all the time until today, no code change but this sudden issue occur at build_runner.
Does anyone encounter the issue ?

Possible Reason :https://pub.dev/packages/logging/changelog a new release here 

Gradle Setting:
openApiGenerate {
    generatorName = 'dart-dio'
}
openApiGenerate successful but when build runner build, encounter the following error.
command : flutter pub run build_runner build

> Task :runBuildRunner
Failed to build build_runner:build_runner:
../../../../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.7/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
pub finished with exit code 1

> Task :runBuildRunner FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':runBuildRunner'.
> Process 'command 'flutter'' finished with non-zero exit value 1

##### OpenAPI declaration file content or url 
https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml

##### Steps to reproduce

 flutter pub run build_runner build

**Comment by ahmednfwela** [comment]
@jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12) @ahmednfwela (2021/08)
