### ISSUE TITLE
[JAVA][gradle-plugin] The option generateClientAsBean is not available in gradle plugin

### ISSUE THREAD

**Issue by fserafin** [OpenAPITools/openapi-generator#15639]
##### Description

In the latest release (v6.6.0) the option `generateClientAsBean` has been introduced, as in those PRs:
#15419 
#15416

But it seems it's still not available in the org.openapi.generator gradle plugin v6.6.0.
In fact if I add that option like this:

```groovy
task customGenerateTask(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generateClientAsBean.set true
    // other options...
}
```

i obtain the following error:
`groovy.lang.MissingPropertyException: Could not get unknown property 'generateClientAsBean' for task ':customGenerateTask' of type org.openapitools.generator.gradle.plugin.tasks.GenerateTask`

##### openapi-generator version

v6.6.0

##### Steps to reproduce

Adding option `generateClientAsBean` in the GenerateTask task.

##### Related issues/PRs

#15419 
#15416 

##### Suggest a fix/enhancement

Make the option available for gradle and maven plugins.

**Comment by wing328** [comment]
generateClientAsBean is not a global option

it's an option for the Java generator only so you can set via "additionalProperties"  instead

**Comment by fserafin** [comment]
> generateClientAsBean is not a global option
> 
> it's an option for the Java generator only so you can set via "additionalProperties" instead

Thank you so much @wing328 for your prompt response and for providing the solution! 👍 
I can close the issue
