### ISSUE TITLE
[BUG][spring-http-interface]Missing Import when using spring-http-interface

### ISSUE THREAD

**Issue by zelaskoa** [OpenAPITools/openapi-generator#15631]
##### Description

Generated Code has no Imports for
- @Parameter
- @Valid
- ParameterIn.PATH
- @Min

But these Annotations/Enumvalues 

##### openapi-generator version

6.6.0

##### Generation Details

Using 'spring-http-interface'

**Comment by Quad-Plex** [comment]
I've just come across this issue myself even with current version 7.5.0, imports for @Parameter and @ParameterIn.HEADER are missing in the generated interface when using spring-http-interface

**Comment by alex-shamshurin** [comment]
Unfortunately this bug still exists!
