### ISSUE TITLE
[BUG][Java][Spring][Bounty] allOf with nullable produces build method not expecting JsonNullable, Java cannot compile

### ISSUE THREAD

**Issue by jspetrak** [OpenAPITools/openapi-generator#15640]
OpenAPI Generator: 7.0.0 beta, template "spring"

OpenAPI Specification: 3.0.3

Given test file reproduces the issue.

```yaml
openapi: 3.0.3

info:
  title: Test API specification
  version: 0.0.1

paths:
  /tests/{testId}:
    parameters:
      - name: testId
        in: path
        required: true
        schema:
          type: string
    patch:
      operationId: modifyTest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifyTestRequest'
      responses:
        '200':
          description: Modifies a test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModifyTestResponse'

components:
  schemas:
    ModifyTestRequest:
      type: object
      additionalProperties: false
      discriminator:
        propertyName: objectType
      required:
        - oneRequired
      properties:
        oneRequired:
          type: string
          nullable: false
        twoOptional:
          type: string
          nullable: true
        threeOptionalBinaryContent:
          type: string
          format: byte
          nullable: true

    ModifyNamedTestRequest:
      allOf:
        - $ref: '#/components/schemas/ModifyTestRequest'
        - type: object
          additionalProperties: false
          properties:
            name:
              type: string
              nullable: true
    
    ModifyOrderedTestRequest:
      allOf:
        - $ref: '#/components/schemas/ModifyTestRequest'
        - type: object
          additionalProperties: false
          properties:
            ordinal:
              type: integer
              nullable: true

    ModifyTestResponse:
      type: object
      additionalProperties: false
      required:
        - oneRequired
      properties:
        oneRequired:
          type: string
          nullable: false
        twoOptional:
          type: string
          nullable: true
        threeOptionalBinaryContent:
          type: string
          format: byte
          nullable: true
```

The parent ModifyTestObject has following setter generated

```java
public void setTwoOptional(JsonNullable<String> twoOptional) {
    this.twoOptional = twoOptional;
}
```

but the child object takes List instead and passes it to the super method.

```java
public ModifyNamedTestRequest twoOptional(String twoOptional) {
    super.setTwoOptional(twoOptional);
    return this;
}
```

**Expected solutions**

Either `ModifyNamedTestRequest::twoOptional` should not be generated at all, or twoOptional should take `JsonNullable<String>` as its parameter.

**Related Issues**

_Originally posted by @jspetrak in https://github.com/OpenAPITools/openapi-generator/issues/4128#issuecomment-1560978293_

#14765 [BUG][Java][Spring] openapiNullable - JsonNullable usage is based on nullable property instead of required property

#14766 is potential fix

**Bounty**

This is a blocker for [OSDM](https://github.com/UnionInternationalCheminsdeFer/OSDM) code generation into Java Spring Boot. [Bileto](https://github.com/bileto) is willing to sponsor the resolution of the issue by €500 bounty, other currency equivalent, or extra donation to Open API Collective.

**Comment by jspetrak** [comment]
Yet present in 7.0.0 beta.

**Comment by martin-mfg** [comment]
Hi @jspetrak,
this issue should be fixed in the latest release, version 7.0.1. The fix was contributed by @robinjhector via https://github.com/OpenAPITools/openapi-generator/pull/16497 .

-----------

As an aside, you might want to fix the below lines of your input spec:
```yaml
      discriminator:
        propertyName: objectType
```
According to https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/ 
>  The `discriminator` is used with `anyOf` or `oneOf` keywords only.

and

> It is important that all the models mentioned [...] contain the property that the discriminator specifies.

**Comment by robinjhector** [comment]
Does my fix solve the problem @jspetrak? Otherwise let me know!

**Comment by jspetrak** [comment]
@martin-mfg @robinjhector I tested the 7.0.1 version against the openapi files and I agree, it now produces compilable code.

**Comment by robinjhector** [comment]
I had no idea this had a bounty on it, and I'm not sure it was still active, otherwise feel free to sponsor my github profile or paypal, or buy me a coffee 😄
