### ISSUE TITLE
[BUG][JAVA] additionalModelTypeAnnotations adds lombok annotation to abstract class AbstractOpenApiSchema

### ISSUE THREAD

**Issue by abu7waij** [OpenAPITools/openapi-generator#15684]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

```
     <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.6.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <configOptions>
                                <additionalModelTypeAnnotations>@lombok.AllArgsConstructor;@lombok.Builder(toBuilder = true,builderClassName = "Builder")</additionalModelTypeAnnotations>
                            </configOptions>
                            <inputSpec>${spec-temp-dir}/api.yaml</inputSpec>
                            <generatorName>java</generatorName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
The generated abstract class AbstractOpenApiSchema also has the lombok annotation, which causes a compiler failure, "AbstractOpenApiSchema is abstract; cannot be instantiated". Is there a way to tell the plugin to ignore this class?

##### openapi-generator version

openapi-generator-maven-plugin:6.6.0

**Comment by borsch** [comment]
@abu7waij I would fix this in v7.0.0, but as for now you can try a workaround with custom template https://openapi-generator.tech/docs/templating

you would need to override this template https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/native/AbstractOpenApiSchema.mustache and simply remove `{{>additionalModelTypeAnnotations}}` from it
