### ISSUE TITLE
[BUG] [JAVA-SPRING] x-extra-annotation along with $ref not working

### ISSUE THREAD

**Issue by BaluVyamajala** [OpenAPITools/openapi-generator#15707]
##### Description  
vendor extensions along side $ref not working as expected.
For example x-extra-annotation, which is supposed to add annotation on getter method, is not added.
```
OrderHeader:
  function:
     x-extra-annotation: '@software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbIgnoreNulls'
     $ref: '#/components/schemas/OrderFunction'
```

Generates Java Code as without @DynamoDbIgnoreNulls annotation.

```
  @Valid 
  @Schema(name = "function", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("function")
  public OrderFunction getFunction() {
    return function;
  }
```
However it works fine with allOf , i can see the annotation above getter method.
```
OrderHeader:
  function:
     x-extra-annotation: '@software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbIgnoreNulls'
     allOf:
          - $ref: '#/components/schemas/OrderFunction'
```

Java class
```
  @software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbIgnoreNulls
  @Valid 
  @Schema(name = "function", requiredMode = Schema.RequiredMode.NOT_REQUIRED)
  @JsonProperty("function")
  public OrderHeaderFunction getFunction() {
    return function;
  }

```

This solution with allOf generates a new class with attributes of OrderFunction with name OrderHeaderFunction. If I use OrderFunction ref in 10 different spots, i end up with 10 different classes.

Either I need a way to not create new class when there is just one value in allOf OR apply x-extra-annotation on getter function of $ref

##### openapi-generator version

tried with 6.0, 6.3, 6.6 and 7.0 snapshot

**Comment by wing328** [comment]
> However it works fine with allOf 

I think that's the right way to do it
