### ISSUE TITLE
[Typescript] [Angular] api client method call not receiving the intended response header

### ISSUE THREAD

**Issue by 666Ben** [OpenAPITools/openapi-generator#1570]
##### Description

I am working on an Angular 6 project using an api client library. When calling a create method in this api library I don't receive the intended response header. My code:

```
import { NewProject, ProjectsService } from '@xxxx/xxxxxx-client';
.....
@Component({
.....
})
export class .... {
...
  constructor(
    private readonly prjService: ProjectsService
  ) {}
...
createNewProject(event: NewProject) {
    console.log('start create new project', event);
    // calling open api method
    this.prjService.createProject(event, 'response').subscribe(
      res => console.log('create success', res),
      err => {
        this.logService.error('create error', err);
      }
    );
    console.log('end create new project');
  } 
.....
}
```
The intended project is successfully created and on the console I get the following output through
`res => console.log('create success', res),`
See at: [response in angular](https://i.stack.imgur.com/pqieN.png)

However: when looking at the result of the corresponding POST call in the browser networkanalysis I see the following response header
[POST response header in browser](https://i.stack.imgur.com/Sumrp.png)

There is some vital information (location) in that POST response that is not passed to my method call in Angular.

##### openapi-generator version 
3.3.3

**Comment by macjohnny** [comment]
@666Ben this does not seem to be an issue of the angular codegen, but of the ussage of the angular http client itself. The `Location` response header indicates that the request should continue to the url given, so your response is just an intermediate result and thus not considered the final response.
you could try
```typescript
this.prjService.createProject(event, 'event').subscribe(
```
See https://angular.io/api/common/http/HttpHeaderResponse
