### ISSUE TITLE
[SWIFT4] Objective C compatibility

### ISSUE THREAD

**Issue by Sal0g** [OpenAPITools/openapi-generator#1571]
Currently the generator (**v3.3.3**) produces Swift 4.2 code that is not directly useable in Mixed **Swift/Objective C** projects even though the config files contains:

`"objcCompatible":"true",`

- Currently the generator produces `Struct` objects which are not accessible in **Objective C**. It would instead produces `@objc public class CLASSNAME: NSObject, Codable { ... }`
- everywhere where `public` is produced, it would be necessary to have `@objc public` as in Swift 4, such automatic @objc inference is deprecated and disabled by default

**Comment by wing328** [comment]
@Sal0g thanks for reporting the issue. May I know if you've time to contribute the fix? We can work with you on the PR.

cc @jgavris (2017/07) @ehyche (2017/08) @Edubits (2017/09) @jaz-ah (2017/09) @d-date (2018/03)

**Comment by Sal0g** [comment]
I do have a little bit of time that I can offer, but I don't have deep knowledge about the inner workings of the generator. Is it only adapting a few mustaches? If you point me into the right direction I can maybe patch it.

**Comment by wing328** [comment]
To add `@objc` in the output when the option `objcCompatible` is set, you can do the following:
```
{{#objcCompatible}}@objc {{/objcCompatible}} public
``` 


Ref: https://github.com/OpenAPITools/openapi-generator/blob/0eb385c0d6497c38c09b42158b2d66109b78b15b/modules/openapi-generator/src/main/resources/swift4/modelObject.mustache#L16

The templates for Swift 4 can be found in the folder `modules/openapi-generator/src/main/resources/swift4/`

**Comment by Sal0g** [comment]
@wing328 As this PR is now open for quite some time: Do you still need anything from my side? 

The changes are rather trivial, but important for me. So I would love to see them make their way into the project.

**Comment by wing328** [comment]
Please try the latest `swift5` generator and report back if there's still an issue. Thanks.

**Comment by Pe-te** [comment]
Just fyi: When included as a Pod, subclassing does not work because the classes are public but need to be open.
