### ISSUE TITLE
[python] bearerAuth always type basic

### ISSUE THREAD

**Issue by vmorris** [OpenAPITools/openapi-generator#1577]
##### Description

Defining security component like
```
"components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ]
```

When I generate a python client, the API configuration code only allows for `type: basic`.

In configuration.py:
```
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'bearerAuth':
                {
                    'type': 'basic',
                    'in': 'header',
                    'key': 'Authorization',
                    'value': self.get_basic_auth_token()
                },

        }
```

##### openapi-generator version
3.3.3

**Comment by vmorris** [comment]
Does #1207 address this?

**Comment by ybelenko** [comment]
> Does #1207 address this?

As you may already notice. Nope, referenced PR adds token authentication feature to PHP Slim Server generator only.

@tomplus As new Python committee, can you answer this?

**Comment by tomplus** [comment]
As we can find here [/resources/python/configuration.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/configuration.mustache#L234) the bearer token will work only if the type equals `oauth2`.

**Comment by vmorris** [comment]
I'm not real familiar with mustache.. Shouldn't we be able to add another block for type `http`? Perhaps a default if `oauth2` is not set?

**Comment by waza-ari** [comment]
In my opinion that should be changed, as the OpenApi allows Bearer authentication without OAuth.

**Comment by wing328** [comment]
#1999 merged into master. Please try the latest master (snapshot, docker image, etc).

Closing this for the time being.

**Comment by waza-ari** [comment]
@wing328 sorry it took some time for me to come back to that project. I was testing it today using the current master snapshot docker image and it works perfectly. Thanks for your work!

**Comment by esseti** [comment]
is this fix released in 3.X version? in my generated code there's no `bearerAuth` in the `auth_setting(self)` it should have something like this (note: what should be the `identifier` ?)

```
    'bearerAuth':
                {
                    'type': 'http',
                    'in': 'header',
                    'key': 'Authorization',
                    'value': self.get_api_key_with_prefix('<THEPREFIX>')
                },
```

**Comment by vmorris** [comment]
@esseti this went into the 4.0.0 milestone

**Comment by 4c74356b41** [comment]
hey, i'm looking at a code generated for python and i see this:
```
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
        }
```
openapi spec has bearer token auth on all requests pretty much
should I raise a new issue @vmorris ?

**Comment by vmorris** [comment]
>  should I raise a new issue @vmorris ?

@4c74356b41 I am not an expert on this group's preferred way to handle this, but I think you should open a new issue and reference this one.
