### ISSUE TITLE
[BUG] [scala-sttp] API functions return Unit when a default response is present

### ISSUE THREAD

**Issue by michaelmcguirk** [OpenAPITools/openapi-generator#15785]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using the scala-sttp generator, any paths in the spec which have a `default` response result in generated API functions that always return `Unit` for a successful response(`Unit` in Scala is the equivalent of `void` in Java). 

This is not an issue when the default response does not have a schema, but is incorrect when a default response schema is present, as it hides the response.

The problem is the use of `asEither(asString, ignore)` here when a spec has a default response on a path with a schema as the `ignore` portion on the right has the effect of ignoring whatever is on the Right of the Either (the success response).

##### openapi-generator version

6.4.0

##### OpenAPI declaration file content or url

https://gist.github.com/michaelmcguirk/0862f22cad0c8fafea9269cbe12ad3dc

##### Generation Details

```
openapi-generator-cli generate -i ~/petstore.yaml -g scala-sttp

```
##### Steps to reproduce

1. Run openapi-generator-cli generate on the attached spec using the scala-sttp generator.
2. Check the showPetsById function in PetsApi.scala in the generated code. 
3. Response type signature should be `Request[Either[ResponseException[String, Exception], Pet], Any]` as it returns a Pet response, but in fact it is `Request[Either[Either[String, String], Unit], Any]`

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/11949

##### Suggest a fix

I believe I have a fix, and I'm happy to create a PR, but the contribution guidelines mention opening an Issue first. 

Currently api.mustache checks for `#defaultReturnType` when it could check for `^returnType` so that we're only returning unit when a return type is absent here: https://github.com/OpenAPITools/openapi-generator/blob/fbe768bb9c57aefc64fd5946a3b647b6773b9dac/modules/openapi-generator/src/main/resources/scala-sttp/api.mustache#L39

Updated api function response would be:

```Scala
.response({{^returnType}}asEither(asString, ignore){{/returnType}}{{#returnType}}{{#separateErrorChannel}}asJson{{/separateErrorChannel}}{{^separateErrorChannel}}asJsonAlwaysUnsafe{{/separateErrorChannel}}[{{>operationReturnType}}]{{/returnType}})
```
with the function signature being:
```scala
Request[{{^returnType}}Either[Either[String, String], Unit]{{/returnType}}{{#returnType}}{{#separateErrorChannel}}Either[ResponseException[String, Exception], {{>operationReturnType}}]{{/separateErrorChannel}}{{^separateErrorChannel}}{{>operationReturnType}}{{/separateErrorChannel}}{{/returnType}}, Any] 
```

**Comment by dwischolek-modulon** [comment]
This is still an issue. If it helps, I could try to create a PR sometime next week.

**Comment by dwischolek-modulon** [comment]
@wing328 I think this might be closed with the two PRs merged.

**Comment by wing328** [comment]
Thanks for the PR by @dwischolek-modulon 

@michaelmcguirk please give it a try with the latest master (snapshot version can be found in project's readme)
