### ISSUE TITLE
[BUG] [JAVA-SPRING] version 6.5.0 is creating allof models

### ISSUE THREAD

**Issue by Rob-1966** [OpenAPITools/openapi-generator#15791]
#### Bug Report Checklist

- [yes] Have you provided a full/minimal spec to reproduce the issue?
- [yes ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [yes] Have you searched for related issues/PRs?
- [yes] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

openapi-generator-maven-plugin version 6.4.0 is creating models without AllOf for:

     "allOf": [
          {
            "$ref": "#/components/schemas/AmortizationVersion"
          },

for this: AmortizationVersionAllOfDetail

version 6.5.0 is creating AmortizationVersionAllOfDetail

and this is causing compilation errors:

incompatible types: io.swagger.client.model.AmortizationVersionAllOfDetail cannot be converted to io.swagger.client.model.AmortizationVersionDetail

##### openapi-generator version

6.5.0 and 6.6.0

##### Steps to reproduce
`
<plugin>
   <groupId>org.openapitools</groupId>
   <artifactId>openapi-generator-maven-plugin</artifactId>
   <version>6.5.0</version>
   <executions>
      <execution>
         <?m2e execute onConfiguration?>
         <goals>
            <goal>generate</goal>
         </goals>
         <configuration>
            <inputSpec>${basedir}/src/main/resources/closeDefinition/close-swagger.json</inputSpec>
            <modelPackage>io.swagger.client.model</modelPackage>
            <apiPackage>io.swagger.client.api</apiPackage>
            <configOptions>
               <modelNamePrefix>Close</modelNamePrefix>
               <localVariablePrefix>dv</localVariablePrefix>
               <dateLibrary>java8-localdatetime</dateLibrary>
            </configOptions>
         </configuration>
      </execution>
   </executions>
</plugin>
`

**Comment by wing328** [comment]
can you please try v6.6.0 or the latest master (snapshot can be found in the readme)? I remember merging a PR to better handle allOf.

**Comment by Rob-1966** [comment]
v6.6.0 is giving the same issue, because I'm using Maven I cannot use the snapshot. For now I'm reverting to v6.4.0

**Comment by wing328** [comment]
should be fixed in the latest stable version

happy to reopen the issue if needed.
