### ISSUE TITLE
Easy one: Dart Generator - Flutter 3.10 compatibility

### ISSUE THREAD

**Issue by wiesnery** [OpenAPITools/openapi-generator#15845]
Hi there,

I just wanted to upgrade my project to flutter 3.10.4 
It seems like there is an issue with the `intl` version in the code that the dart generator produces. It references version `^0.17.0` however `intl: 0.18.0` is required for the new flutter version.

I searched through the code and could not find any usages of the intl package anyway, so I would suggest to just remove the following line from the mustache template:

https://github.com/OpenAPITools/openapi-generator/blob/afca85acf577c4117e6eda650d2e228726b57f5c/modules/openapi-generator/src/main/resources/dart2/pubspec.mustache#L19

If anyone sees a reason why this is important, we could also change it to `>=0.17.0`

I can provide a PR, just let me know which of the two versions you would prefer.

Cheers!

**Comment by ahmednfwela** [comment]
Is this related ? https://github.com/OpenAPITools/openapi-generator/pull/15510

**Comment by ahmednfwela** [comment]
also https://github.com/OpenAPITools/openapi-generator/pull/15516

**Comment by wiesnery** [comment]
Yes, they would both fix it. Thanks!
Just not sure if it is smart to use ^0.17.0 but instead go with >0.17.0

Happy to see this fixed soon!

**Comment by wiesnery** [comment]
Has been fixed with this PR https://github.com/OpenAPITools/openapi-generator/pull/17862 and is available in 7.4.0
