### ISSUE TITLE
[BUG][spring-cloud] multipart/form-data model not generated

### ISSUE THREAD

**Issue by zhanghaozjk** [OpenAPITools/openapi-generator#15843]
##### Description

multipart/form-data model ref by api properties not generated

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: TestApi
  version: 1.0.0
paths:
  /api/v1/report:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - files
                - data
              properties:
                data:
                  $ref: '#/components/schemas/ReportExportRequest'
                files:
                  type: array
                  items:
                    format: binary
                    type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
          description: success
      operationId: createReport
components:
  schemas:
    ReportExportRequest:
      type: object
      properties:
        reportId:
          format: int64
          type: integer
```

##### Generation Details

following is my generate script
$ openapi-generator-cli generate -g spring  --library spring-cloud  -i test.yml  -o test
and model ReportExportRequest not generated.

**Comment by borsch** [comment]
@zhanghaozjk add parameter `--global-property skipFormModel=false` to your CLI command

**Comment by zhanghaozjk** [comment]
Thanks for your reply and it works! @borsch 
By the way, I searched the logs with level "warn" since model ReportExportRequest not generated. should this log change level to warn?

**Comment by borsch** [comment]
> should this log change level to warn?

probably yes
