### ISSUE TITLE
[REQ][csharp-netcore] Add reference to library when generating project

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#15888]
### Is your feature request related to a problem? Please describe.

When generating a client we add our own `TokenProvider`. This `TokenProvider` need a reference to a nuget package.

## Describe the solution you'd like

Possibility in the config file to specify some additional package reference.

## Describe alternatives you've considered

None

## Additional context

We create a TokenProvider that refresh the Token when expired based on a credentials.

**Comment by devhl-labs** [comment]
@kYann I think you can already handle this. You can add to your csproj file by providing a template called netcore_project.additions Just add templateDir: <your template directory> to the root of your config. Then create a file called netcore_project.additions.mustache and put whatever extra things you need.

**Comment by kYann** [comment]
Thanks it works !
