### ISSUE TITLE
[REQ][csharp-netcore] Use 6.x reference to .Net SDK when using target net6.0

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#15887]
### Is your feature request related to a problem? Please describe.

When targeting .net6.0 `targetFramework: net6.0` the csproj contains reference to 7.0 library which are not compatible with 6.0.

## Describe the solution you'd like

Either when targeting 6.0 we use 6.0 SDK, or it's a new parameter to define the version of the SDK.

## Additional context

When in a .net6.0 project we use 6.0 SDK and so it creates build error to use 7.0 sdk

**Comment by devhl-labs** [comment]
@kYann What library is getting the wrong version? When I change the sample to 6.0 I get `<TargetFramework>net6.0</TargetFramework>` with no errors or warnings.

**Comment by kYann** [comment]
The library are the microsoft ones

```xml
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="7.0.5" />
```

When adding the client to an asp .net 6 project with other .net 6 dependencies we end up with conflict between versions
