### ISSUE TITLE
[REQ] Zapier Integration Generation

### ISSUE THREAD

**Issue by valmoz** [OpenAPITools/openapi-generator#15883]
I'm currently part of the Fatture in Cloud API Team.

To make it easier for third-party developers to consume our APIs, we are actively using the OpenAPI Generator to generate client libraries for different programming languages.
Following our customer's requests, we plan to develop a [Zapier](https://zapier.com/) Integration that would enable them to use our API from their no-code software. Of course, we don't want to build it manually, so we're planning to create a new Generator to generate it from our OpenAPI file.

Do you think it could be useful to make this generator available to the community? Or is there some policy that excludes this possibility (since Zapier is not Open Source)?

Right now we're exploring the possibility to obtain a working Zapier Integration by modifying the templates of one of the existing generators (to be used locally in our build process), but we could try to implement it as a proper standalone generator if we plan to make it available in the official generator.

The same thing could be done with other similar services. For example, we are currently trying to implement an example [n8n](https://n8n.io/) integration, and if it works properly we could try to implement a generator for that service as well.

Thanks
Mauro

@emajo

**Comment by valmoz** [comment]
@wing328 let us know if it could be interesting for the community. Of course, we're willing to prepare a PR for that

**Comment by wing328** [comment]
@valmoz thanks for offering a generator to better integrate with Zapier.

We definitely welcome such contribution assuming you and your team will help maintain the generator moving forward.

Please file a PR to start with and we will start from there.

**Comment by emajo** [comment]
Hi @wing328 I almost finished the [first version of the generator](https://github.com/valmoz/openapi-generator/pull/3/files) but I have some doubts about how to manage some situations.

For example Zapier search actions want an array to be returned, but depending on the api structure the array can either be returned in the first level of the response, or nested in some fields, actually [this is the solution](https://github.com/valmoz/openapi-generator/pull/3/files#diff-717d8cd70ed9992398de73b3756512f4184f65af04ed2303ec639e27bcb630b0R11-R14) I adopted (leaves the logic to the generator user), for example our api returns always a 'data' field that wraps the response, so this method in our case becomes:

```
const searchMiddleware = (action) => {
  let oldFunc = action.operation.perform
  action.operation.perform = async(z, bundle) => oldFunc(z, bundle).then((response) => response.data)
  return action
}
```

I wanted to know if there is a better way to implement this.

Thanks,
Emanuele.

**Comment by emajo** [comment]
HI @wing328 the generator is complete, I opened a [PR](https://github.com/OpenAPITools/openapi-generator/pull/15997/), let us know if it's alright.
