### ISSUE TITLE
[REQ] Nightly/Preview releases

### ISSUE THREAD

**Issue by stephan-strate** [OpenAPITools/openapi-generator#15919]
### Is your feature request related to a problem? Please describe.

Stable releases take time to release. When fixing bugs, the time it takes to a final stable release can be long. To compensate for that, an automated nightly/weekly release to maven repository would be amazing.

Side effect: Early feedback on features, fixes before stable release.

## Describe the solution you'd like

Nightly release from master to maven repository.

**Comment by wing328** [comment]
you can use the snapshot version. search for 'snapshot' in the readme and you will find it
