### ISSUE TITLE
[REQ] Support scala-pekko-http-server instead scala-akka-http-server

### ISSUE THREAD

**Issue by krrrr38** [OpenAPITools/openapi-generator#15924]
### Is your feature request related to a problem? Please describe.

https://pekko.apache.org/

apache pekko is fork of akka. Someone want to migrate into pekko-http from akka-http because of a license issue.

## Describe the solution you'd like

Support scala-pekko-http-server generator instead scala-akka-http-server.

## Additional context

- https://github.com/apache/incubator-pekko/issues/334
- https://pekko.apache.org/docs/pekko/current/project/migration-guides.html
- https://pekko.apache.org/docs/pekko-http/current/migration-guide/index.html

**Comment by wing328** [comment]
Thanks for letting us know.

In scala-akka-http-server generator, what about adding an option (e.g. useApachePekko, default to false) to let the user chooses?
