### ISSUE TITLE
[BUG] No module named 'openapi_server: cannot start FastAPI code generated by OpenAPI generator

### ISSUE THREAD

**Issue by AJNOURI** [OpenAPITools/openapi-generator#15962]
#### Description

I have this server code generated by this openapi-generator from a swagger.yaml specification listed below.

When trying to start the server  from the directory where main is, it gives an error:

```
Y\git\openapi-fastapi-example\src\openapi_server> uvicorn main:app --reload
INFO:     Will watch for changes in these directories: ['X\\git\\openapi-fastapi-example\\src\\openapi_server']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [30316] using StatReload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "Z\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "Z\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "Y\git\venv1\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "Y\git\venv1\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "Z\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "Z\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "Y\git\venv1\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "Y\git\venv1\lib\site-packages\uvicorn\config.py", line 474, in load
    self.loaded_app = import_from_string(self.app)
  File "Y\git\venv1\lib\site-packages\uvicorn\importer.py", line 24, in import_from_string
    raise exc from None
  File "Y\git\venv1\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "Z\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "Y\git\openapi-fastapi-example\src\openapi_server\.\main.py", line 15, in <module>
    from openapi_server.apis.device_api import router as DeviceApiRouter
ModuleNotFoundError: No module named 'openapi_server'

```
**All generated librararies imports** refer to "**openapi_server**"  from within "openapi_server" directory itself.

This happens where ever the directory I am in (uvicorn adjusted accordingly to target the **main**.

#### openapi-generator version
7.0.0-SNAPSHOT

#### OpenAPI declaration file content or url
https://gist.github.com/AJNOURI/34f3302b223985cd068fab10a9dbf2a8

#### Steps to reproduce & Generation Details
- copy the swagger.yaml to a directory "X"
- cd X
- docker run --rm   -v ${PWD}:/local openapitools/openapi-generator-cli generate --skip-validate-spec   -i /local/swagger.yaml   -g python-fastapi   -o /local
- cd python-fastapi
- tree
```
$ tree
.
├── docker-compose.yaml
├── Dockerfile
├── openapi.yaml
├── pyproject.toml
├── README.md
├── requirements.txt
├── setup.cfg
├── src
│   └── openapi_server
│       ├── apis
│       │   ├── device_api_base.py
│       │   ├── device_api.py
│       │   ├── __init__.py
│       │   ├── orange_api_status_api_base.py
│       │   └── orange_api_status_api.py
│       ├── main.py
│       ├── models
│       │   ├── brand.py
│       │   ├── capabilities.py
│       │   ├── category_type.py
│       │   ├── device.py
│       │   ├── extra_models.py
│       │   ├── __init__.py
│       │   ├── orange_api_component.py
│       │   ├── orange_api_error.py
│       │   ├── orange_api_status.py
│       │   ├── orange_api_status_value.py
│       │   ├── screen.py
│       │   └── type.py
│       └── security_api.py
├── swagger.yaml
└── tests
    ├── conftest.py
    ├── test_device_api.py
    └── test_orange_api_status_api.py

5 directories, 30 files

```
- cd src\openapi_server
- uvicorn main:app --reload

#### Related issues/PRs
No related issues

**Comment by lvijnck** [comment]
Use 

```
uvicorn openapi_server.main:app --reload
```

To ensure the right path is captured.

**Comment by leopaul36** [comment]
I am also facing the same issue, the `docker-compose up --build` commands also fails with:

```
 => ERROR [service test_runner 6/6] RUN pytest tests                                                                                    1.0s
------
 > [service test_runner 6/6] RUN pytest tests:
#0 0.916 ImportError while loading conftest '/tmp/tests/conftest.py'.
#0 0.916 tests/conftest.py:5: in <module>
#0 0.916     from openapi_server.main import app as application
#0 0.916 /venv/lib/python3.7/site-packages/openapi_server/main.py:15: in <module>
#0 0.916     from openapi_server.apis.default_api import router as DefaultApiRouter
#0 0.916 /venv/lib/python3.7/site-packages/openapi_server/apis/default_api.py:8: in <module>
#0 0.916     import openapi_server.impl
#0 0.916 E   ModuleNotFoundError: No module named 'openapi_server.impl'
```

**Comment by AJNOURI** [comment]
Same here:

```
git\python-fastapi\src> uvicorn main:app --reload
...
git\python-fastapi\src\.\openapi_server\apis\manifacturer_api.py", line 8, in <module>
    import openapi_server.impl
ModuleNotFoundError: No module named 'openapi_server.impl'
```

The imp module is nowhere ??
![image](https://github.com/OpenAPITools/openapi-generator/assets/1716020/831d8fcd-680f-42b2-8460-22bdf1a83b95)

**Comment by AJNOURI** [comment]
Had to replace "openapi_server.impl" by "impl" everywhere in the project and make sure "impl" library is installed.
Now it looks ok.

Is this a bug?

**Comment by lvijnck** [comment]
The `impl` module is the one you have to implement. 

The idea is that you create subclasses of the provided classes and override the functions. 

Does that make sense?

**Comment by AJNOURI** [comment]
I am not sure to get the idea.
@lvijnck do you have a basic example of such implementation.

**Comment by wing328** [comment]
@lvijnck when you've time, I wonder if you can file a PR by creating subclasses of the provided classes in samples/server/petstore/python-fastapi so that running pytest in that folder will pass. Thank you.

**Comment by deng232** [comment]
have you installed requirements

**Comment by AJNOURI** [comment]
Hey guys!
I would love to help with this beta version of the FastAPI generator.
But you have to be more reactive than that or have some documentation or guidance.

Is there any additional documentation or examples on how to use "impl" ?

**Comment by iamsolid** [comment]
create a folder called "impl" and in that folder create a file called "__init__.py". That will create a "sub-module" that is scanned for additional implementation functions or override functions. It would be good that this is created by default since the generator is supposed to support final build with docker/etc.

**Comment by wing328** [comment]
Hi all, I've filed https://github.com/OpenAPITools/openapi-generator/pull/17852 to auto-generate init.py under `impl'` folder and now can start the server without issue.

However when I run `pytest`, I got the following errors:
```
ImportError while loading conftest '/mnt/c/Users/wing3/Code/openapi-generator/samples/server/petstore/python-fastapi/tests/conftest.py'.
tests/conftest.py:5: in <module>
    from openapi_server.main import app as application
E   ModuleNotFoundError: No module named 'openapi_server'
```

Did you get similar error when running pytest? Can you share how you resolve it? Thanks

**Comment by wing328** [comment]
UPDATE: ran ` PYTHONPATH=src pytest tests` and now I got the following errors instead:

```
/home/wing328/.local/lib/python3.10/site-packages/fastapi/routing.py:163: in run_endpoint_function
    return await dependant.call(**values)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

username = 'username_example', user = User(id=0, username='username', first_name=None, last_name=None, email='email', password='password', phone='phone', user_status=None), token_api_key = None

    @router.put(
        "/user/{username}",
        responses={
            400: {"description": "Invalid user supplied"},
            404: {"description": "User not found"},
        },
        tags=["user"],
        summary="Updated user",
        response_model_by_alias=True,
    )
    async def update_user(
        username: str = Path(..., description="name that need to be deleted"),
        user: User = Body(None, description="Updated user object"),
        token_api_key: TokenModel = Security(
            get_token_api_key
        ),
    ) -> None:
        """This can only be done by the logged in user."""
>       return BaseUserApi.subclasses[0]().update_user(username, user)
E       IndexError: tuple index out of range

src/openapi_server/apis/user_api.py:184: IndexError
============================================================================================ short test summary info ============================================================================================
FAILED tests/test_fake_api.py::test_fake_query_param_default - IndexError: tuple index out of range
FAILED tests/test_pet_api.py::test_delete_pet - IndexError: tuple index out of range
FAILED tests/test_pet_api.py::test_find_pets_by_status - IndexError: tuple index out of range
FAILED tests/test_pet_api.py::test_find_pets_by_tags - IndexError: tuple index out of range
FAILED tests/test_pet_api.py::test_get_pet_by_id - IndexError: tuple index out of range
FAILED tests/test_pet_api.py::test_update_pet_with_form - IndexError: tuple index out of range
FAILED tests/test_pet_api.py::test_upload_file - IndexError: tuple index out of range
FAILED tests/test_store_api.py::test_delete_order - IndexError: tuple index out of range
FAILED tests/test_store_api.py::test_get_inventory - IndexError: tuple index out of range
FAILED tests/test_store_api.py::test_place_order - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_create_user - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_create_users_with_array_input - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_create_users_with_list_input - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_delete_user - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_get_user_by_name - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_login_user - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_logout_user - IndexError: tuple index out of range
FAILED tests/test_user_api.py::test_update_user - IndexError: tuple index out of range
```

**Comment by wing328** [comment]
I think I've fixed it by commenting out the part to make the http request. (users need to uncomment these as well as the assert statement when writing their tests)

**Comment by francisrafal** [comment]
> create a folder called "impl" and in that folder create a file called "**init**.py" in the "openapi_server" folder. That will create a "sub-module" that is scanned for additional implementation functions or override functions. It would be good that this is created by default since the generator is supposed to support final build with docker/etc.

@iamsolid 
@wing328
Thanks for your answers and the fixes! Could you maybe help me with understanding how to use the `impl` package correctly:
Is it actually possible to override a function in the generated `src/openapi_server/apis/default_api.py` without modifying `default_api.py`?
My generated code for the python-fastapi-server inserts `import openapi_server.impl` at the top of `default_api.py`. If I understand correctly, Python executes the very last definition of a function so it would actually execute the function definitions of `default_api.py` instead of the function definitions in the `impl` package because the import statement is at the top of `default_api.py`.
So I would also need to modify `default_api.py`?

Or do you have an example for how to override a function by redefining in `src/openapi_server/impl/__init__.py` without modifying `default_api.py`?

**Comment by ridwan-salau** [comment]
Hi @francisrafal 
> Python executes the very last definition of a function so it would actually execute the function definitions of default_api.py instead of the function definitions in the impl package because the import statement is at the top of default_api.py.

From my understanding, I believe that the `__init_subclass__` method in `default_api_base.py` will override the methods defined in the class if those same methods are implemented in a subclass that is defined in `openapi_server/impl/...`.

However, that is as far as I know. I have not been able to get it to successfully get the response I defined in the `openapi_server/impl/...` package following the convention above.
