### ISSUE TITLE
[BUG] [Kotlin] Generated api client doesn't work for plain text response body types

### ISSUE THREAD

**Issue by Yonggo** [OpenAPITools/openapi-generator#15973]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Suggest a fix

accept content type is not set in the generated client code unless application/json is used as response tpye:
![image](https://github.com/OpenAPITools/openapi-generator/assets/108994903/d8456443-a972-469b-aea6-caa61b1b1d64)
therefore it come always error "HttpMediaTypeNotAcceptableException" during integrationtest

**Comment by ffffionn** [comment]
This is a big deal I think, the "text/plain" media type should be supported

**Comment by 0sten** [comment]
Issue is still present when client is ktor.
