### ISSUE TITLE
[BUG] `python-nextgen` circular refs lead to no imports

### ISSUE THREAD

**Issue by indietyp** [OpenAPITools/openapi-generator#16010]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generation is successful, but for recursive models the imports are missing, when trying to generate from https://github.com/hashintel/hash/blob/main/apps/hash-graph/openapi/openapi.json you can see how in `models/filter.py` the import for `AnyFilter` is missing and how in `models/any_filter.py` the import is missing for `Filter.`

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or URL

https://github.com/hashintel/hash/blob/main/apps/hash-graph/openapi/openapi.json

##### Generation Details

        "generatorName": "python-nextgen",
        "packageName": "hash_openapi",

##### Steps to reproduce

Simply generate with the aforementioned schema

**Comment by wing328** [comment]
can you please try the latest master (snapshot version can be found in the readme)?

I remember merging a fix for that.

**Comment by wing328** [comment]
in the latest master, python-nextgen has been renamed to python

**Comment by indietyp** [comment]
I just tested with [openapi-generator-cli-7.0.0-20230705.091805-173.jar](https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.0.0-SNAPSHOT/openapi-generator-cli-7.0.0-20230705.091805-173.jar) using `java -jar ~/Downloads/openapi-generator-cli-7.0.0-20230705.091805-173.jar generate -g python -i input/apps/hash-graph/openapi/openapi.json` with the same result.

The imports are still absent.

**Comment by spacether** [comment]
FYI this was working in the deprecated python client v6.5.0 release
- [Player model contains a property enemyPlayer also of type player](https://github.com/OpenAPITools/openapi-generator/blob/v6.5.0/samples/openapi3/client/petstore/python/petstore_api/model/player.py#L45)
That generator has moved to a different repo where it has test of self referencing object and array models:
- [array model test](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_self_referencing_array_model.py#L22)
- [object model test](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_self_referencing_object_model.py#L22)

**Comment by wing328** [comment]
I tested it with the latest master and `pytest` runs fine without issues with a test as follows in `test/test_filter.py`:
```
    def testFilter(self):
        """Test Filter"""
        model = openapi_client.models.filter.Filter()
```

what error did you get when using the auto-generated client/sdk?

**Comment by fa0311** [comment]
Here is how to reproduce this
- Build /bin/configs/python.yaml
`java -jar openapi-generator-cli.jar generate -g python -c . /bin/configs/python.yaml`
- Execute the following
```python
from petstore_api.models.first_ref import FirstRef
FirstRef.from_dict({})
```

This is the output
```log
Traceback (most recent call last):

  ....

  File "/home/yuki/openapi-generator/test,py", line 3, in <module>
    FirstRef.from_dict({})
  File "/home/yuki/openapi-generator/.venv/lib/site-packages/petstore_api/models/first_ref.py", line 70, in from_dict
    _obj = FirstRef.parse_obj({
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 339, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 860, in pydantic.fields.ModelField.validate
pydantic.errors.ConfigError: field "self_ref" not yet prepared so type is still a ForwardRef, you might need to call FirstRef.update_forward_refs().
```

**Comment by wing328** [comment]
@fa0311 thanks for the details. Will look into it with your PR this weekend.

**Comment by wing328** [comment]
Thanks for the PR from @fa0311 

@indietyp please pull the latest master to give it a try.
