### ISSUE TITLE
[BUG] Wrong image has been pushed to dockerImage tag latest-release

### ISSUE THREAD

**Issue by venuselite** [OpenAPITools/openapi-generator#16022]
#### Bug Report Checklist
 
Hello,
it seems like the the image tag "latest-release" is running the same version as v7.0.0-beta.
This can be seen on [docker hub](https://hub.docker.com/r/openapitools/openapi-generator-cli/tags) as well.
Both tags share the same DIGEST:
**DIGEST:sha256:69a1f1cb3ed4ad4f6bf644855c7906e605d875c88272424cb0c7110ca0b49bcc**

![image](https://github.com/OpenAPITools/openapi-generator/assets/11396294/a26c2a9d-7bb2-498b-a744-caeb8e75bcd7)

There are breaking changes in version 7 which should not be in latest-release yet:

`Can't load config class with name 'csharp-netcore'

Available:

ada

ada-server

android

apache2

apex

asciidoc

aspnetcore

avro-schema

bash

crystal

c

clojure

cwiki

cpp-qt-client

cpp-qt-qhttpengine-server

cpp-pistache-server

cpp-restbed-server

cpp-restbed-server-deprecated

cpp-restsdk

cpp-tiny

cpp-tizen

cpp-ue4

csharp

csharp-functions

dart

dart-dio

eiffel

elixir

elm

erlang-client

erlang-proper

erlang-server

fsharp-functions

fsharp-giraffe-server

go

go-echo-server

go-server

go-gin-server

graphql-schema

graphql-nodejs-express-server

groovy

kotlin

kotlin-server

kotlin-spring

kotlin-vertx

ktorm-schema

haskell-http-client

haskell

haskell-yesod

java

jaxrs-cxf-client

java-helidon-client

java-helidon-server

java-inflector

java-micronaut-client

java-micronaut-server

java-msf4j

java-pkmst

java-play-framework

java-undertow-server

java-vertx

java-vertx-web

java-camel

jaxrs-cxf

jaxrs-cxf-extended

jaxrs-cxf-cdi

jaxrs-jersey

jaxrs-resteasy

jaxrs-resteasy-eap

jaxrs-spec

javascript

javascript-apollo-deprecated

javascript-flowtyped

javascript-closure-angular

jetbrains-http-client

jmeter

julia-client

julia-server

k6

lua

markdown

mysql-schema

n4js

nim

nodejs-express-server

objc

ocaml

openapi

openapi-yaml

plantuml

perl

php

php-laravel

php-lumen

php-slim-deprecated

php-slim4

php-symfony

php-mezzio-ph

php-dt

postman-collection

powershell

protobuf-schema

python

python-fastapi

python-flask

python-aiohttp

python-blueplanet

r

ruby

ruby-on-rails

ruby-sinatra

rust

rust-server

scalatra

scala-akka

scala-akka-http-server

scala-finch

scala-gatling

scala-lagom-server

scala-play-server

scala-sttp

scala-sttp4

scalaz

spring

dynamic-html

html

html2

swift5

swift-combine

typescript

typescript-angular

typescript-aurelia

typescript-axios

typescript-fetch

typescript-inversify

typescript-jquery

typescript-nestjs

typescript-node

typescript-redux-query

typescript-rxjs

wsdl-schema

xojo-client

[error] Check the spelling of the generator's name and try again.`

**Comment by wing328** [comment]
> `Can't load config class with name 'csharp-netcore'

csharp-netcore has been renamed to csharp.

you can roll back to previous 6.x version using v6.6.0 tag.

**Comment by venuselite** [comment]
Thank you @wing328 for the answer.
Is it expected behaviour that the docker tag latest-release is also using version [v7.0.0-beta](https://hub.docker.com/layers/openapitools/openapi-generator-cli/v7.0.0-beta/images/sha256-69a1f1cb3ed4ad4f6bf644855c7906e605d875c88272424cb0c7110ca0b49bcc?context=explore)?

**Comment by wing328** [comment]
> Is it expected behaviour that the docker tag latest-release is also using version [v7.0.0-beta](https://hub.docker.com/layers/openapitools/openapi-generator-cli/v7.0.0-beta/images/sha256-69a1f1cb3ed4ad4f6bf644855c7906e605d875c88272424cb0c7110ca0b49bcc?context=explore)?

it's debatable.

I want more users to try out v7.0.0-beta if possible.
