### ISSUE TITLE
[Java] Generate model for component with allOf has not attributes

### ISSUE THREAD

**Issue by ravthiru** [OpenAPITools/openapi-generator#1602]
##### openapi-generator version

3.3.4

**Comment by wing328** [comment]
@ravthiru can you please test https://github.com/OpenAPITools/openapi-generator/pull/1360 to see if it fixes the issues for you?

**Comment by ravthiru** [comment]
@wing328  which snapshot version i should use for testing

**Comment by wing328** [comment]
@ravthiru you will need to build the JAR from the branch locally as the PR has not yet been merged into master.

**Comment by ravthiru** [comment]
No the said branch has not fixed the issue, for below spec **Pet** model class should have **id**, **name** and **tag** attributes, but with generated **Pet** Model class only extends **Address** 

```
Pet:
      allOf:
        - $ref: "#/components/schemas/address"
        - type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    address:
      type: object
      properties:
        location:
          type: string
        city:
          type: string
```

**Comment by ravthiru** [comment]
I used the branch oas3-spec-support1

**Comment by jmini** [comment]
@ravthiru: I did not look in detail at the change made in the PR, but I think that the correct way of expressing what you want is:

```yaml
components:
  schemas:
    Pet:
        allOf:
          - $ref: "#/components/schemas/address"
          - type: object
            required:
              - id
              - name
            properties:
              id:
                type: integer
                format: int64
              name:
                type: string
              tag:
                type: string
    address:
        type: object
        properties:
          location:
            type: string
          city:
            type: string
```
=> Please notice the indentation difference.

And as far as I know this is already working with version `3.x.x`. It produces a child class.

@wing328 : swagger-editor https://editor.swagger.io/ seems to support this as well:

```yaml
components:
  schemas:
    Pet:
        allOf:
          - $ref: "#/components/schemas/address"
        type: object
        required:
          - id
          - name
        properties:
          id:
            type: integer
            format: int64
          name:
            type: string
          tag:
            type: string
    address:
        type: object
        properties:
          location:
            type: string
          city:
            type: string
```

I am not sure if this is correct or not from an OpenAPI Spec perspective or not and I also did not look at how the Swagger-Parser is parsing this.

**Comment by ravthiru** [comment]
Thanks it was because of indentation issue , it is working now
