### ISSUE TITLE
[REQ] [go-gin-server] Generated code overwrites code

### ISSUE THREAD

**Issue by chenyunda218** [OpenAPITools/openapi-generator#16107]
### Is your feature request related to a problem? Please describe.
The go-gin-server generator always overwrite my code. There is not options to generate `interfaceOnly` or `modelOnly` code.
## Describe the solution you'd like

Add some options to control output.
| Option |  Description | Values | Default|
|---|---|---|---|
|dockerfile| Do you need to generate Dockerfile?  |  |true|
|  modelOnly| Only generate model  | | true|
|modelPath| Path of output model  | | . |
|goMod|Do you need to generate go.mod? | |false|
|main| Do you need to generate main.go?||  false|

**Comment by wing328** [comment]
what about using .openapi-generator-ignore to skip files from being generated?

https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#ignore-file-format

**Comment by chenyunda218** [comment]
Thank you for answering my question. sorry for my ignorance.
