### ISSUE TITLE
[BUG] [Go-server] Do not import ioutil deprecated packages

### ISSUE THREAD

**Issue by vsur06** [OpenAPITools/openapi-generator#16113]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a server stub, we see the issues below:
1. deprecated io/ioutil pacjages are being installed [Issue 1](https://github.com/OpenAPITools/openapi-generator/blob/067b17252ecdb61dfec1c808fc906e2b256da059/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L156) [Issues 2](https://github.com/OpenAPITools/openapi-generator/blob/067b17252ecdb61dfec1c808fc906e2b256da059/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L161)
2. Method not getting resolved in routers file [Link to Code](https://github.com/OpenAPITools/openapi-generator/blob/067b17252ecdb61dfec1c808fc906e2b256da059/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L166)
3. Missing error handling for method [Link to Code](https://github.com/OpenAPITools/openapi-generator/blob/067b17252ecdb61dfec1c808fc906e2b256da059/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L168)
4. In submodule, the go version is 1.13
##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url
[https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml)

##### Generation Details

`openapi-generator generate -g go-server -i petstore.yaml -o <output dir> --package-name server --additional-properties=sourceFolder=server`

##### Steps to reproduce

Generate a go-server using the petstore.yaml to observe the aforementioned issues

##### Related issues/PRs

Yes, but the change was for the client, and not the server: [https://github.com/OpenAPITools/openapi-generator/pull/14476](https://github.com/OpenAPITools/openapi-generator/pull/14476)

##### Suggest a fix

  Changes required as in the the PR mentioned above,  but for the server.

**Comment by wing328** [comment]
Thanks for the suggestion. I wonder if you've time to file a PR similar to https://github.com/OpenAPITools/openapi-generator/pull/14476

**Comment by gcatanese** [comment]
FIxed by PR #16822

**Comment by lwj5** [comment]
@wing328 would you mind closing this
