### ISSUE TITLE
wrong ngPackagr version for angular6

### ISSUE THREAD

**Issue by dominikg** [OpenAPITools/openapi-generator#1615]
The pr (https://github.com/OpenAPITools/openapi-generator/pull/1613) that added angular7 support (thank you for this, came here to report an issue about it!)
added the following code:
https://github.com/OpenAPITools/openapi-generator/blob/10ea00066a51df8613488318747bd31dcb92a736/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L264-L275

The check in line 265 should test for angular version 7.0.0, right? (otherwise the block starting at line  270 is unreachable)

**Comment by wing328** [comment]
@dominikg I've filed https://github.com/OpenAPITools/openapi-generator/pull/1616. Can you check to see if it looks good to you?

**Comment by dominikg** [comment]
looks good to me. @pkainz what do you think?

**Comment by wing328** [comment]
@dominikg @pkainz the fix has been merged into master. Please pull the latest to give it another try.

**Comment by pkainz** [comment]
Yes, that's a typo and should read 7.0.0 - thanks for fixing!
