### ISSUE TITLE
[BUG] [PHP] [Symfony] Issues for parameters of type date-time not completely fixed

### ISSUE THREAD

**Issue by gaea44** [OpenAPITools/openapi-generator#16155]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I declare a parameter of with `type: string` and `format: date-time` and generate a symfony bundle with it, then I observe that queries on that endpoint get a `400` response with message `This value should be of type string`.

##### openapi-generator version

Behavior oberved in 6.6.0 and 7.0.0-beta

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Test
  version: 0.0.1
paths:
  /my-route:
    get:
      summary: Get stuff
      parameters:
        - name: myparam
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        "200":
          description: OK
```

##### Generation Details

```bash
openapi-generator-cli generate \
    -i openapi.yamll \
    -g php-symfony \
    -o .
```

##### Steps to reproduce

Plug the symfony bundle generated into a symfony app (following the steps in the auto-generated README). Then launch the symfony server and perform a query against this route, for instance:

```bash
  curl -i http://localhost:8000/my-route # this should be ok because the parameter is marked as non required
  # or also
  curl -i 'http://localhost:8000/my-route?myparam=2017-07-21T17:32:28Z'
```

##### Related issues/PRs

Its the same issue explained [here](https://github.com/OpenAPITools/openapi-generator/issues/14930)
and partially fixed [in this PR](https://github.com/OpenAPITools/openapi-generator/pull/14933)

##### Suggest a fix

The error occurs because the generated Models in symfony still contains the wrong Datetime Constraints `Assert\DateTime()` instead of `Assert\Type("DateTime")`

```php
// Model/MyModel.php

    /**
     * @var \DateTime|null
     * @SerializedName("myparam")
     * @Assert\DateTime()
     * @Type("DateTime")
     */
    protected ?\DateTime $myparam = null;
```
The PR only fixed the template `modules/openapi-generator/src/main/resources/php-symfony/api_input_validation.mustache` but it missed changes in the model template `modules/openapi-generator/src/main/resources/php-symfony/model_variables.mustache`

```diff
    {{#isDateTime}}
-    * @Assert\DateTime()
+    * @Assert\Type("DateTime")
     * @Type("DateTime")
    {{/isDateTime}}
```

**Comment by loicconan** [comment]
@wing328 this issue can be close, resolved by https://github.com/OpenAPITools/openapi-generator/commit/cb85358aa55412c4d9409ba5c10b6b879afd5eba
