### ISSUE TITLE
[BUG] DefaultCodegen.specialCharReplacements comment about  prefixing with the quotation mark

### ISSUE THREAD

**Issue by msakai** [OpenAPITools/openapi-generator#16161]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The comment of `DefaultCodegen.specialCharReplacements` says that it uses the quotation mark (`'`) as a prefix.

https://github.com/OpenAPITools/openapi-generator/blob/fb2c866dfc39d0de25f86bab6025e63130bf39ff/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L242-L245

But, neither the initializer of the table

https://github.com/OpenAPITools/openapi-generator/blob/fb2c866dfc39d0de25f86bab6025e63130bf39ff/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L1836-L1839

nor its use-site `DefaultCodegen.toVarName` and its subroutine `StringUtils.encode` insert the quotation mark .

https://github.com/OpenAPITools/openapi-generator/blob/fb2c866dfc39d0de25f86bab6025e63130bf39ff/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L1612-L1619

https://github.com/OpenAPITools/openapi-generator/blob/fb2c866dfc39d0de25f86bab6025e63130bf39ff/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/StringUtils.java#L267-L285

Background: I noticed the problem when I was debugging `HaskellServantCodegen`. `HaskellServantCodegen` generates code that assumes the quotation mark prefixes, but the generated field names do not have the quotation mark prefixes.

##### Suggest a fix

I guess that the comment is outdated and the current behavior (not prefixed with the quotation mark) is intended behavior.

If so, I suggest simply removing ` and prefixed with ' ` from the comment.

**Comment by wing328** [comment]
> If so, I suggest simply removing and prefixed with ' from the comment.

Yes please file a PR. Thank you.

**Comment by msakai** [comment]
Sure!
