### ISSUE TITLE
[BUG][Python-experimental]  _response_types_map = { '200': "List[List]"} is created

### ISSUE THREAD

**Issue by MalteEbner** [OpenAPITools/openapi-generator#16239]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?

##### Description

With these full openapi specs:

```yml
openapi: 3.0.0
info:
  title: Sample API
  description: Description
  version: 0.1.9
servers:
  - url: http://api.example.com/v1/
    description: Optional server description, e.g. Main (production) server
paths:
  /users:
    get:
      tags:
        - Objects
      operationId: getObjects
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200":
            description: Get successful
            content:
                application/json:
                  schema:
                    type: array
                    items:
                      $ref: "#/components/schemas/ListOfObjects"

components:
  schemas:
    ListOfObjects:
      type: array
      title: ListOfObjects
      items:
        $ref: "#/components/schemas/Object"
    Object:
      type: object
      title: Object
      properties:
        property1:
          type: string
        property2:
          type: integer

```
the generator from version 6.6.0 generates an `objects_api.py` with the method `get_objects_with_http_info`, which contains

```python
_response_types_map = {
    '200': "List[List]",
}
```

When using that object with an API, it errors with
```
AttributeError: module 'generated_code.models' has no attribute 'List'
```

#### Fix by manually changing generated code

When changing the generated code in `objects_api.py: get_objects_with_http_info` to the correct response type, it works fine:
```python
_response_types_map = {
    '200': "List[List[Object]]",
}
```

##### openapi-generator version

6.6.0

**Comment by MalteEbner** [comment]
@spacether Can you add the Client:python tag?

**Comment by japrescott** [comment]
Most likely related: https://github.com/OpenAPITools/openapi-generator/issues/15816

**Comment by wing328** [comment]
I could repeat the issue. Will try to come up with a fix this weekend.

**Comment by wing328** [comment]
UPDATE: I've filed #16291 to fix the issue and add a test.
