### ISSUE TITLE
[BUG][JAVA] generated class tries to extend instead of implement Serializable interface

### ISSUE THREAD

**Issue by PhraseTomasVich** [OpenAPITools/openapi-generator#16240]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Following OpenAPI v3 YAML schema definition generates non-compilable code.

Generated class extends abstract class AbstractOpenApiSchema but then it also tries to extend (instead of implement) Serializable interface.
```
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-02T14:31:16.003353100")
public class ReferencesCondition extends AbstractOpenApiSchema, Serializable {
...
}
```

##### openapi-generator version

org.openapitools:openapi-generator-gradle-plugin:6.6.0
with Java 1.8

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: Test
  version: 0.0.1
paths:
  /api/some_api:
    get:
      operationId: someApi
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ReferencesCondition'
components:
  schemas:
    ReferencesCondition:
      type: object
      oneOf:
        - $ref: '#/components/schemas/JobCondition'
        - $ref: '#/components/schemas/TaskCondition'
    JobCondition:
      type: object
      properties:
        jobId:
          type: string
    TaskCondition:
      type: object
      properties:
        taskId:
          type: string
x-build-time: 2023-08-02T11:35:52.647Z
```

##### Generation Details

```
task buildSomeJavaClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "java"
    inputSpec = "$projectDir/src/main/resources/some.yaml".toString()
    outputDir = "$buildDir/generated/sources/some-client".toString()
    templateDir = "$projectDir/codegen/Java".toString()

    groupId = project.group
    id = "$project.name-some-client"
    version = project.version
    apiPackage = 'com.some.api'
    invokerPackage = 'com.some.api.invoker'
    modelPackage = 'com.some.api.model'
    skipOverwrite = false

    configOptions = [
            dateLibrary                             : 'java8',
            disallowAdditionalPropertiesIfNotPresent: 'false',
            serializableModel                       : 'true'
    ]
}
compileJava.dependsOn tasks.buildSomeJavaClient
sourceSets.main.java.srcDirs += "$buildDir/generated/sources/some-client/src/main/java"
```

##### Steps to reproduce
Generate the client, try to build with it.

**Comment by wing328** [comment]
thanks for reporting the issue. I've just filed https://github.com/OpenAPITools/openapi-generator/pull/16241 to fix it.

you can use/test the fix using customized templates (e.g. -t via CL) for the time being.

**Comment by wing328** [comment]
PR merged. Please give it a try with the latest master.
