### ISSUE TITLE
[BUG] C# Aspnetcore Generator. Fix header missing (Name = ) Property

### ISSUE THREAD

**Issue by lance-yuan-igt** [OpenAPITools/openapi-generator#16275]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by wing328** [comment]
can you please file a PR similar to #8826 to fix the issue?

**Comment by lance-yuan-igt** [comment]
I don't have write access to the repo

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements
