### ISSUE TITLE
[Question][Dart] How to Write Yaml about json Map struct to build Dart? 

### ISSUE THREAD

**Issue by huafsud** [OpenAPITools/openapi-generator#16285]
hi : 

I have a JSON file that I want to use to write a YAML file in order to build Dart, but I don't know how to do it.
I searched for issues, but still couldn't find a solution.
 
```
{
    "users": {
        "1": {
            "id": 1,
            "name": "Jon"
        },
        "2": {
            "id": 2,
            "name": "Jonx"
        }
    }
}
```

 need help~  Thanks,

**Comment by Nexushunter** [comment]
https://converter.swagger.io/ Allows you to convert OAS online to and from json and yaml but it needs to be a valid oas spec which isn't what you've provided. What you've provided is what appears to be a response payload that you are expecting.
