### ISSUE TITLE
[BUG][JAVA][Spring] Setting "additionalProperties" generates Spring endpoint with wrong RequestBody type

### ISSUE THREAD

**Issue by CG-Patrick** [OpenAPITools/openapi-generator#16294]
##### Description

When using a model that has "additionalProperties" set to true, the generated Spring API expects a Map<String, Object> as request body instead of the generated model type.

The model for the request body is generated correctly (https://gist.github.com/CG-Patrick/44c7523dcca738390833bc971785ba67#file-exampleoperationrequest-java) but it is not used in the generated API (https://gist.github.com/CG-Patrick/44c7523dcca738390833bc971785ba67#file-myendpointapi-java).

##### openapi-generator version

7.0.0 (latest master)

##### OpenAPI declaration file content or url

https://gist.github.com/CG-Patrick/44c7523dcca738390833bc971785ba67#file-example-api-yml

##### Generation Details

Generated using the latest master CLI with no special config.

##### Steps to reproduce

java -jar openapi-generator-cli-7.0.0-20230810.025436-258.jar generate -i example-api.yml -g spring

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/1466

**Comment by Kavan72** [comment]
getting same problem

**Comment by martin-mfg** [comment]
As a workaround until the above fix is released, you can set [`generateAliasAsModel`](https://openapi-generator.tech/docs/globals/) to `true` to get the expected behaviour.

**Comment by weijiequ** [comment]
Having the same issue, any chance we prioritize the fix?
