### ISSUE TITLE
[swift] to support application/octet-stream for file upload (alamofire)

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#16300]
##### Description

Update `alamofire` to support application/octet-stream for file upload

ref: https://github.com/OpenAPITools/openapi-generator/pull/15140#discussion_r1177418158

**Comment by 4brunu** [comment]
I think that https://github.com/OpenAPITools/openapi-generator/pull/17422 fixes this issue.

**Comment by 4brunu** [comment]
I'm closing this issue, as this should now be fixes, if this is still an issue, please reopen this issue.
Thanks
