### ISSUE TITLE
[BUG] [csharp] Using the generic type List<T> requires 1 type argument

### ISSUE THREAD

**Issue by prajon84** [OpenAPITools/openapi-generator#16307]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

master 

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: C# Object with oneof array of string
  version: v1
paths:
  '/roles/report':
    get:
      responses:
        '200':
          description: returns report
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RolesReport'

components:
  schemas:
    RolesReport:
      description: Roles report
      type: array
      items:
        $ref: '#/components/schemas/RolesReportsHash'
    RolesReportsHash:
      description: Role report Hash
      type: object
      properties:
        role_uuid:
          type: string
          format: uuid
        role:
          type: object
          properties:
            name:
              type: string
          
```

##### Steps to reproduce
```
>openapi-generator generate -g csharp  -i openapi.yaml --library httpclient -o out/csharp_array_of_object_issue --model-package Model --api-package Api

>cd out/csharp_array_of_object_issue
>dotnet build
```

produces:

![image](https://github.com/OpenAPITools/openapi-generator/assets/43785517/ee08269a-f2d5-4e83-9197-9e6a1b94c93d)

In VS:

![image](https://github.com/OpenAPITools/openapi-generator/assets/43785517/df4805f3-9201-494c-9c17-4af187f8a35a)

`List<List>` should be `List<List<RolesReportHash>>`

##### Related issues/PRs

None that I could find.

##### Suggest a fix

@wing328 @lucamazzanti @Blackclaws @shibayan @devhl-labs

**Comment by devhl-labs** [comment]
It's known that nested lists are not supported right now.
