### ISSUE TITLE
When use discriminator plus allOf to create a java inheritance relationship, duplicated class generated

### ISSUE THREAD

**Issue by haiyunhzhang** [OpenAPITools/openapi-generator#16338]
#### Bug Report Checklist

- [Y] Have you provided a full/minimal spec to reproduce the issue?
- [Y] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [N] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [Y] Have you searched for related issues/PRs?
- [Y] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I am using "discriminator" in parent schema plus allOf in child schema inside the openapi input file describing the open api models without validation errors when using https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/6.6.0/openapi-generator-cli-6.6.0.jar to generate spring server java classes. The java classes are all generated correctly with child class Child.java extending the parent class. But a duplicated ChildAllOf.java class is also generated with the same child's fields and does not extend the parent class.

I tried the same input file with the online editor https://editor-next.swagger.io/ and it successfully generated all the java classes without generating the duplicated class.

The issue is always reproducible and I even tried release 5.4.0 and have the same problem.
 

 
##### openapi-generator version
6.6.0 & 5.4.0

No
##### OpenAPI declaration file content or url
{
  "openapi": "3.0.1",
  "info": {
    "title": "Table for school children",
    "description": "## Students' information",
    "version": "4.0.0"
  },
  "paths": {
  },
  "components": {
    "schemas": {
      "Child": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Parent"
          },
          {
            "required": [
              "name"
            ],
            "type": "object",
            "properties": {
              "description": {
                "type": "string",
                "description": "Child information"
              },
              "name": {
                "type": "string",
                "description": "Name of the child"
              }
            },
            "description": "Child class"
          }
        ]
      },
      "Parent": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string",
            "description": "Family address"
          }
        },
        "discriminator": {
          "propertyName": "address"
        },
        "description": "Parent information"
      }
    }
  }
}

**Comment by wing328** [comment]
>  But a duplicated ChildAllOf.java class is also generated with the same child's fields and does not extend the parent class.

can you please try the latest master? I think we addressed it already.

i did a test and no longer found the *AllOf java files.

**Comment by haiyunhzhang** [comment]
> > But a duplicated ChildAllOf.java class is also generated with the same child's fields and does not extend the parent class.
> 
> can you please try the latest master? I think we addressed it already.
> 
> i did a test and no longer found the *AllOf java files.

Could you please let me know how to download the jar file built from the master branch?

I tried,

 wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/master/openapi-generator-cli-master.jar -O openapi-generator-cli.jar

And it returns errors.

Thanks

**Comment by haiyunhzhang** [comment]
I have verified the fix with 7.0.0-beta. I saw it has been fixed and will close this issue.
