### ISSUE TITLE
Generator for Spring Java17 Still imports from javax instead of jakarta

### ISSUE THREAD

**Issue by haiyunhzhang** [OpenAPITools/openapi-generator#16349]
#### Bug Report Checklist

- [Y] Have you provided a full/minimal spec to reproduce the issue?
- [Y] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [Y] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [] Have you searched for related issues/PRs?
- [Y] What's the actual output vs expected output?
For Spring boot 3 and Springframework 6, java17 and jakarta should be used to replace javax,
Still has the lines in the generated model files:

import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;

- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Spring boot 3 and newer has updated to java17 and use jakarta libraries to replace javax, but the latest OpenApi 3 still generate those imports from javax.

import javax.validation.Valid;
import javax.validation.constraints.*;
import javax.annotation.Generated;

etc.

##### openapi-generator version
7.0.0-beta

##### OpenAPI declaration file content or url
{
  "openapi": "3.0.1",
  "info": {
    "title": "Table for school children",
    "description": "## Students' information",
    "version": "4.0.0"
  },
  "paths": {
  },
  "components": {
    "schemas": {
      "Child": {
        "allOf": [
          {
            "$ref": "#/components/schemas/Parent"
          },
          {
            "required": [
              "name"
            ],
            "type": "object",
            "properties": {
              "description": {
                "type": "string",
                "description": "Child information"
              },
              "name": {
                "type": "string",
                "description": "Name of the child"
              }
            },
            "description": "Child class"
          }
        ]
      },
      "Parent": {
        "type": "object",
        "properties": {
          "address": {
            "type": "string",
            "description": "Family address"
          }
        },
        "discriminator": {
          "propertyName": "address"
        },
        "description": "Parent information"
      }
    }
  }
}

##### Generation Details
java -jar openapi-generator-cli.jar generate -g spring -c ../bug-report/springOptions.json -v -i "../bug-report/inheritance.json" -o "../bug-report/school_src"

##### Steps to reproduce
Just one step to run the above command

##### Suggest a fix

Produce jakarta import by default or make it configurable.

**Comment by ahavriluk** [comment]
useSpringBoot3 config param.

**Comment by haiyunhzhang** [comment]
@ahavriluk
Set useSpringBoot3 and it generates the right imports now.

Thank you very much!

**Comment by waynemorphic** [comment]
### Problem

`javax.validation.*` does not exist

### Solution

In the plugin set-up with maven, use:

```
<configOptions>

    <useSpringBoot3>true</useSpringBoot3>

</configOptions>
```

[Check out these configuration options](https://openapi-generator.tech/docs/generators/spring/)

**Comment by fahrican** [comment]
If you use `build.gradle.kts` you would do something like this:

```
openApiGenerate {
    generatorName.set("kotlin-spring")
    // rest of your config then...
    configOptions.set(mapOf("useSpringBoot3" to "true"))
}
```

**Comment by cfurst** [comment]
HOw do we get around this if we are using a java generator.. I'm trying to use the plugin, but javax.annotations package doens't exist.. any plans to migrate for later java versions?

**Comment by wing328** [comment]
for `java` client generator, did you try enabling the option `useJakartaEe` ?

https://openapi-generator.tech/docs/generators/java/
