### ISSUE TITLE
[BUG] Jersey 2 and 3 clientBuilder gets overwritten after call to `customizeClientBuilder`

### ISSUE THREAD

**Issue by datengraben** [OpenAPITools/openapi-generator#16353]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

To customize a generated Jersey 2 or 3 ApiClient, it's advised via javadocs to extend the type and overwrite `customizeClientBuilder(...)`. See: 
https://github.com/OpenAPITools/openapi-generator/blob/778a53a4069cf522cfbe8c045b8bf65671a394e8/modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache#L1399-L1409

But the code generated for the ApiClients classes, where `customizeClientBuilder(...)` (line 1368) gets called, overwrites the `apiClient` Configuration directly, after the invoke `customizeClientBuilder(...)`, see 1369.

https://github.com/OpenAPITools/openapi-generator/blob/778a53a4069cf522cfbe8c045b8bf65671a394e8/modules/openapi-generator/src/main/resources/Java/libraries/jersey3/ApiClient.mustache#L1363-L1371

##### openapi-generator version
7.0.0-SNAPSHOT

##### Steps to reproduce

* Generate jersey 2 or 3 client code
* Extend ApiClient class and overwrite `customizeClientBuilder` to further configurate your client.
* Inspect via debugger that in the type ApiClient the member `clientBuilder` Configuration is overwritten by the line `clientBuilder = clientBuilder.withConfig(clientConfig);`

##### Suggest a fix

To prevent that from happending, I suggest to switch line 1369 with 1368, so first the default config gets loaded and after that the customize method is invoked and doesn't get overwritten.

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix?

**Comment by datengraben** [comment]
@wing328 gladly. done
