### ISSUE TITLE
[BUG] Generated Kotlin code doesn't compile

### ISSUE THREAD

**Issue by bodiam** [OpenAPITools/openapi-generator#16363]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I've reported https://github.com/OpenAPITools/openapi-generator/issues/16362. To validate the issue, I've also generated a Kotlin client. However, the generated Kotlin client doesn't compile. 

The generation generates this in the `ApiClient`:

```
    protected fun <T> updateAuthParams(requestConfig: RequestConfig<T>) {
        if (requestConfig.query["apikey"].isNullOrEmpty()) {
            if (apiKey["apikey"] != null) {
                if (apiKeyPrefix["apikey"] != null) {
                    requestConfig.query["apikey"] = apiKeyPrefix["apikey"]!! + " " + apiKey["apikey"]!!
                } else {
                    requestConfig.query["apikey"] = apiKey["apikey"]!!
                }
            }
        }
    }
```

However, the `requestConfig.query` map doesn't take a `<String, String>`, but takes a `<String, List<String>>`:

<img width="864" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/46468/f56eb1b6-cd22-4440-adde-611913437003">

As a result, the code doesn't compile. I've worked around it by wrapping the code in a `listOf`, but I'm not 100% sure if that's correct.

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

https://gist.github.com/bodiam/d770c451e5a67629135c46261b291eac

##### Generation Details

`java -jar openapi-generator-cli-6.6.0.jar  generate -i http://localhost:8080/v3/api-docs  -g kotlin -o /tmp/test/kotlin`

##### Steps to reproduce

1. Download the OpenAPI spec
2. Generate the code using the generation step and the OpenAPI file
3. Compile

Expected is that this will compile without issues, but the code doesn't compile.

##### Related issues/PRs

I searched, but haven't found one.

##### Suggest a fix

Maybe wrap the code with `listOf`?

**Comment by wing328** [comment]
> Maybe wrap the code with listOf?

can you please file a PR with the suggested fix?
