### ISSUE TITLE
[BUG] APIkey as query parameter is not passed in Java client

### ISSUE THREAD

**Issue by bodiam** [OpenAPITools/openapi-generator#16362]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178)) <-- I will donate if this turns out to be a user error or a bug!

##### Description

I have a OpenAPI spec which uses a request parameter `apikey`. This is defined as follows:

```
    "securitySchemes": {
      "apikey": {
        "type": "apiKey",
        "name": "apikey",
        "in": "query"
      }
    }
```

(The full schema can be found here: https://gist.github.com/bodiam/d770c451e5a67629135c46261b291eac)

I have generated a Java client (and Kotlin client), and the Java client doesn't pass the query auth parameter to the endpoint. The Kotlin client, while having other issues, does send the apikey.

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

The problem is most likely in this piece of code:

```java
        // update parameters with authentication settings
        updateParamsForAuth(authNames, allQueryParams, headerParams, cookieParams, requestBodyToString(reqBody), method, URI.create(url));

        final Request.Builder reqBuilder = new Request.Builder().url(url);
        processHeaderParams(headerParams, reqBuilder);
        processCookieParams(cookieParams, reqBuilder);
```

It seems the request params (`allQueryParams`) are updated in the `updateParamsForAuth` method, and while they are, they aren't used in the request, causing the call to fail. 

This simple testcases reproduces it:

```
    @Test
    public void demoTest() throws ApiException {
        String color = "red";
        api.getApiClient().setApiKey("abcdef");
        api.demo(color);
    }
```

##### Generation Details

`java -jar openapi-generator-cli-6.6.0.jar  generate -i http://localhost:8080/v3/api-docs  -g java -o /tmp/test/java`

##### Steps to reproduce

1. Use the attached schema
2. Use the generation step above
3. Run the mailbox controller test with the above code

Expected: the apikey is sent.
Actual: it's not sent.

##### Suggest a fix

I think the requestbuilder needs to be updated with the correct request parameters.

**Comment by wing328** [comment]
> java -jar openapi-generator-cli-6.6.0.jar  generate -i http://localhost:8080/v3/api-docs  -g java -o /tmp/test/java

can you also please try `--library jersey2` or `--library native` to see if these libraries work better with api key authentication in the query?

**Comment by spraot** [comment]
I see this issue too
