### ISSUE TITLE
[BUG] REF_AS_PARENT_IN_ALLOF=true no longer works for allOf combined with properties

### ISSUE THREAD

**Issue by jpraet** [OpenAPITools/openapi-generator#16389]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?

##### Description

For test.yaml openapi example below, I expect the generated code to use inheritance for all 3 cases.

But, from 6.5.0 onwards, Y no longer extends B in the generated code.

Y is combination of an allOf and object properties.

```yaml
    Y:
      description: allOf without embedded properties
      allOf:
        - $ref: '#/components/schemas/B'
      type: object
      properties:
        y:
          type: string
```

When the object properties are embedded inside the allOf (example X) it works.
Or when adding x-parent: true (example Z) it also works.

##### openapi-generator version

Works in 6.4.0, fails in 6.5.0, 6.6.0 and 7.0.0-beta

##### OpenAPI declaration file content or url

test.yaml:
```yaml
openapi: 3.0.3
info:
  version: 1.0.0
  title: test
paths: {}
components:
  schemas:
    A:
      type: object
      properties:
        a:
          type: string
    B:
      type: object
      properties:
        b:
          type: string
    C:
      type: object
      properties:
        c:
          type: string
      x-parent: true
    X:
      description: allOf with embedded properties
      allOf:
        - $ref: '#/components/schemas/A'
        - type: object
          properties:
            x:
              type: string
    Y:
      description: allOf without embedded properties
      allOf:
        - $ref: '#/components/schemas/B'
      type: object
      properties:
        y:
          type: string
    Z:
      description: allOf without embedded properties (x-parent)
      allOf:
        - $ref: '#/components/schemas/C'
      type: object
      properties:
        z:
          type: string
```

##### Steps to reproduce

```
java -jar openapi-generator-cli-6.5.0.jar generate -g jaxrs-spec -i test.yaml -o output/ --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true
```

**Comment by wing328** [comment]
can you please try enabling `REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true` as well in openapi-normalizer?

ref: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

**Comment by wing328** [comment]
can you try the latest master as well? snapshot version can be found in the project's readme.

**Comment by jpraet** [comment]
openapi-generator-cli-7.0.0-20230824.100806-306 behaves same as 7.0.0-beta in this regard.

To clarify: the behavior of 7.0.0 not generating these *AllOf.java that are not used anyway seems fine to me,
I'm just asking if there is an easy way to get rid of them in 6.6.0.

**Comment by wing328** [comment]
> I'm just asking if there is an easy way to get rid of them in 6.6.0.

Nope. You can delete those files manually post code generation.

v7.0.0 has been released. Please consider using the latest stable version instead.

**Comment by mikepictor** [comment]
Just a note that I am experiencing this bug in 7.7.0. For context, I am generating kotlin classes, maybe that has an impact. 

```
    Question:
      type: object
      required:
        - mandatory
      abstract: true
      properties:
        mandatory:
          type: boolean
          example: true
          default: true
    SingleAnswerQuestion:
      allOf:
        - $ref: '#/components/schemas/Question'
        - type: object
.... other properties
```

I get a `Question` object and a `SingleAnswerQuestion` object, but one does not extend the other.

**Comment by wing328** [comment]
@mikepictor did you enable the rule in the normalizer?
