### ISSUE TITLE
[PYTHON] update to pydantic v2

### ISSUE THREAD

**Issue by oshmoun** [OpenAPITools/openapi-generator#16468]
##### Description

Recently, pydantic v2 was released, with changes that deprecate/remove some configs and functions.
In order to keep the generator up-to-date, and avoid generating deprecated code, a template update is in order to produce pydantic v2 models.

##### openapi-generator version

latest master

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/16176

##### Suggest a fix/enhancement

N/A

**Comment by TroyTae** [comment]
@oshmoun @wing328 
Sorry for question at here
Our server is migrated to pydentic v2.3 so I get errors now when I use generator
Is there a way to resolve this situation before release this PR(#16549)?
Thank you for your hard work 👍

**Comment by oshmoun** [comment]
> Our server is migrated to pydentic v2.3 so I get errors now when I use generator

What kind of errors? Afaik one should be only getting deprecation warnings 🙂

**Comment by oshmoun** [comment]
> @oshmoun This is the part of error log what I get:
> 
> ```
> [[main] ./api] [main] ERROR i.s.v.p.reference.ReferenceVisitor - Error resolving schema #/components/schemas/OrderBulkResultSchema
> [[main] ./api] java.lang.IllegalArgumentException: Cannot deserialize value of type `java.lang.Boolean` from Object value (token `JsonToken.START_OBJECT`)
> [[main] ./api]  at [Source: UNKNOWN; byte offset: #UNKNOWN]
> [[main] ./api]  at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4393)
> [[main] ./api]  at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4324)
> [[main] ./api]  at io.swagger.v3.core.util.ModelDeserializer.deserializeJsonSchema(ModelDeserializer.java:157)
> ```
> 
> ```
> [[main] ./api] Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `java.lang.Boolean` from Object value (token `JsonToken.START_OBJECT`)
> [[main] ./api]  at [Source: UNKNOWN; byte offset: #UNKNOWN]
> [[main] ./api]  at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
> [[main] ./api]  at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1741)
> ```

Not sure i see a relation to pydantic. Appears to be an issue with parsing openapi spec 😅

**Comment by TroyTae** [comment]
@oshmoun Thank you for your research!
Then... maybe openapi version can be cause of this error
I'll try again after downgrade version. Thank you so much :)

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/16549 to add an option to support pydantic v2.

Still need more work as some integration tests failed

**Comment by wing328** [comment]
Agreed with @oshmoun the issue seems related to spec (input file).

You may want to try other generators (e.g. java, ruby, etc) to see if you get the same errors.

**Comment by robertschweizer** [comment]
The "python" generator switched to pydantic v2 in https://github.com/OpenAPITools/openapi-generator/pull/16624

**Comment by timo-reymann** [comment]
@robertschweizer that does not seem to be the case.

https://github.com/pydantic/pydantic/issues/7495

> the code you generated doesn't utilize v2 of Pydantic

**Comment by oshmoun** [comment]
> The "python" generator switched to pydantic v2 in #16624

Oh wasn't aware it was merged, thanks for the hint!


> @robertschweizer that does not seem to be the case.

Are you sure your version of the generator included this change. I'm not actually sure if it's included in a release yet 😅

**Comment by timo-reymann** [comment]
> Are you sure your version of the generator included this change. I'm not actually sure if it's included in a release yet 😅
I find it really hard to find any change in a release, as there is only the "look in the PRs", which is a nightmare.

But that should be with 7.0.1

**Comment by robertschweizer** [comment]
You can see "milestone 7.1.0" in https://github.com/OpenAPITools/openapi-generator/pull/16624. This version has not been released yet, but it's due on October 18: https://github.com/OpenAPITools/openapi-generator#11---compatibility

**Comment by wing328** [comment]
please use the SNAPSHOT version for the time being: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.1.0-SNAPSHOT/

**Comment by robertschweizer** [comment]
Can this issue be closed now?
