### ISSUE TITLE
[BUG] [SWIFT] Stored properties cannot be marked potentially unavailable with '@available' with 7.0.0

### ISSUE THREAD

**Issue by barcister** [OpenAPITools/openapi-generator#16479]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Upon updating our projects to 7.0.0 we've noticed a build error in Xcode in URLSessionImplementations.swift on line 55:
`@available(*, unavailable, message: "Please override execute() method to intercept and handle errors like authorization or retry the request. Check the Wiki for more info. https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-do-i-implement-bearer-token-authentication-with-urlsession-on-the-swift-api-client")`

##### openapi-generator version

7.0.0 (works fine on 6.6.0)

##### Steps to reproduce

Generate a base client to Swift using 7.0.0 version and try to run the project.

Xcode version: 14.3.1 and 15.0

##### Suggest a fix

As an interim fix, we created our own moustache file without the available check and that resolved our build issues.

**Comment by wing328** [comment]
can you please submit a PR with the patched mustache template and we'll start from there? thanks.

**Comment by barcister** [comment]
just opened the PR:
[Link](https://github.com/OpenAPITools/openapi-generator/pull/16504)
