### ISSUE TITLE
[REQ] [Go] Response middleware

### ISSUE THREAD

**Issue by AlanCitrix** [OpenAPITools/openapi-generator#16471]
### Is your feature request related to a problem? Please describe.

In our service we would like to add some operations during the response. Particularly logging and some custom error handling. It is cumbersome to have to copy/paste this logic after every request we make.

## Describe the solution you'd like

The `#withCustomMiddlewareFunction` accomplishes this for the `*http.Request`. Could we have another hook for the `*http.Response`?

## Describe alternatives you've considered

We are working on using a custom template to workaround this, but would prefer to see this added to the default template.

**Comment by wing328** [comment]
>We are working on using a custom template to workaround this, but would prefer to see this added to the default template.

Do you mind contribute a PR with the enhancement to start with?

**Comment by AlanCitrix** [comment]
Sorry for the delay, PR opened!
