### ISSUE TITLE
[REQ] Add support to AnyType for cpp-restsdk 

### ISSUE THREAD

**Issue by gpetrussa** [OpenAPITools/openapi-generator#16476]
Good day!

I am facing the following issue with the `cpp-restsdk` generator: it does not support `AnyType` (when I build the solution, the compiler complains that the header file `AnyType.h` is missing). 

The API I'd want to interface to supports the `Any` type, so I was wondering if there is a way to use this type in C++ (like `boost::variant`).
By doing a code research the only clients that support it are `Qt` and `UE4`:

![types](https://github.com/OpenAPITools/openapi-generator/assets/19194078/9f69dd38-7675-480a-b704-01f3370684df)

I've seen that cpp-restsdk has entered in maintenance mode (#10040) , but do you think you could support this type anyway?

Thank you for your work.
Best regards.

**Comment by wing328** [comment]
the cpp-restsdk client genenrator is still pretty active.

we welcome PRs to add AnyType support to cpp-restsdk

let me know if you need help with starting point.s

have a nice weekend

**Comment by aminya** [comment]
I made a pull request that fixes this issue. #18463
