### ISSUE TITLE
[BUG] v7.0.0 typescript-axios generator generates export interface ProtobufAny different from v6.6.0

### ISSUE THREAD

**Issue by tonytony2020** [OpenAPITools/openapi-generator#16494]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

v6.6.0 generates what we and tsc expected, v7.0.0 doesn't.

##### openapi-generator version

v7.0.0

##### OpenAPI declaration file content or url

swagger spec file t.json

```json
{
  "swagger": "2.0",
  "info": {
    "title": "foo APIs",
    "version": "0.0.1"
  },
  "host": "foo.com",
  "paths": {
    "/hello": {}
  },
  "definitions": {
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    }
  }
}

```

openapi tool configuration file foo.openapitools.json
```json
{
  "npmName": "foo",
  "npmVersion": "0.0.1",
  "snapshot": false,
  "supportsES6": true,
  "modelPropertyNaming": "original"
}
```

##### Steps to reproduce

generate code from spec

```shell
openapi-generator-cli version-manager set 7.0.0
openapi-generator-cli generate -i t.json --generator-name typescript-axios -o src/gen/foo -c foo.openapitools.json
```

tsc build failed with v7.0.0

```shell
npm run --prefix src/gen/foo build                                                                                

> foo@0.0.1 build
> tsc && tsc -p tsconfig.esm.json

api.ts:39:5 - error TS2411: Property ''@type'' of type 'string' is not assignable to 'string' index type 'object'.

39     '@type'?: string;
       ~~~~~~~


Found 1 error in api.ts:39
```

##### Suggest a fix

If we switch back to 6.6.0 everything works as expected:

```shell
openapi-generator-cli version-manager set 6.6.0

openapi-generator-cli generate -i t.json --generator-name typescript-axios -o src/gen/foo -c foo.openapitools.json
npm run --prefix src/gen/foo build
```

we diff v6.6.0 and v7.0.0 

```diff
 diff -Nuar  src/gen/foo/api.ts /tmp/app/src/gen/foo/api.ts
--- src/gen/foo/api.ts	2023-09-04 13:39:42
+++ /tmp/app/src/gen/foo/api.ts	2023-09-04 13:39:57
@@ -29,7 +29,7 @@
  * @interface ProtobufAny
  */
 export interface ProtobufAny {
-    [key: string]: object | any;
+    [key: string]: object;
 
     /**
      * 
```

**Comment by wing328** [comment]
thanks for reporting the issue. Do you mind doing a git bisect to identify the commit causing the change?

**Comment by wing328** [comment]
```
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
```

ProtobufAny has one property `@type`. It looks to me the followings (both) are incorrect:
```diff
-    [key: string]: object | any;
+    [key: string]: object;
```

I tested with `typescript` client generator and got the following instead:
```
import { HttpFile } from '../http/http';

export class ProtobufAny {
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "@type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProtobufAny.attributeTypeMap;
    }

    public constructor() {
    }
}
```

Should this be the correct output instead?

**Comment by luisaugusto** [comment]
I'm running into the same issue, with v7, the index signature for one of my generated interfaces is being changed from `[key: string]: string | any;` to `[key: string]: string;` with this schema:

```
{
    type: 'object',
    example: 'ok',
    additionalProperties: {
        type: 'object',
        properties: {
            status: {
                type: 'string',
            },
        },
        additionalProperties: {
            type: 'string',
        },
    },
}
```

Generated interface:

```
export interface HealthCheckControllerCheck200ResponseInfoValue {
    [key: string]: string;

    /**
     * 
     * @type {string}
     * @memberof HealthCheckControllerCheck200ResponseInfoValue
     */
    'status'?: string;
}
```

Causing the error `TS2411: Property  'status'  of type  string | undefined  is not assignable to  string  index type  string `

I downgraded to v6.6 and everything works fine.

**Comment by vikramparth** [comment]
Any updates on when this bug might be fixed? It's preventing us from upgrading to v7.
