### ISSUE TITLE
[REQ] [Kotlin] Specifying visibility modifiers

### ISSUE THREAD

**Issue by skydoves** [OpenAPITools/openapi-generator#16506]
Hello Team,

I'm curious if there's a way to specify visibility modifiers for the generated code, particularly for classes, methods, and properties.

We've been making use of the [Explicit API mode](https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md) feature in Kotlin to enforce clear visibility modifiers, and it would be fantastic if we could ensure compatibility with this feature.

**Comment by hamorillo** [comment]
Another one here with the same case. It would be a great feature!

**Comment by arcadii-meister** [comment]
Apparently, this feature has been available for some time, thanks to this [PR](https://github.com/OpenAPITools/openapi-generator/pull/4089). However, it supports only setting the `internal` visibility modifier by using this configuration:
```kotlin
openApiGenerate {
    generatorName = "kotlin"
    ...
    additionalProperties = mapOf("nonPublicApi" to "true")
}
```
On the other hand, it should solve the explicit API mode compatibility.
