### ISSUE TITLE
[BUG][Python] Unresolved imports in generated code

### ISSUE THREAD

**Issue by Ivan-Kurochenko** [OpenAPITools/openapi-generator#16538]
@spacether 
##### Description
I am generating the Open API using openapi-generator for Python. 
```shell
openapi-generator generate -i /path/to/spec.yaml -g python -o /path/to/output/dir
```

I have checked my `.yml` spec and everything is ok. 
However, when I am generating the code, I am getting problems with imports inside the generated module

<img width="557" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/75803414/c14f1679-9a51-4e9d-9a81-31f5ab301366">

It's just throwing compilation errors and deny the project building. 

##### openapi-generator version

```shell
% openapi-generator --version
openapi-generator-cli 7.0.0
  commit : c37fa8a
  built  : -999999999-01-01T00:00:00+18:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/

```
I have no clue why it doesn't work.

**Comment by wing328** [comment]
can you please share the spec so that we can reproduce the issue more easily?

**Comment by Ivan-Kurochenko** [comment]
@wing328 

```yml
openapi: 3.0.0
info:
  title: My project name
  version: 0.0.1
paths:
  /dump/analyze:
    post:
      operationId: server.dump.analyze
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DumpFiles'
      responses:
        "200":
          description: "Extraction started"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DumpFileIdMap'
        default:
          description: "Unexpected error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
```

**Comment by wing328** [comment]
it works fine for me:
```
➜  pyaaa pytest
============================================================================================= test session starts ==============================================================================================
platform darwin -- Python 3.7.13, pytest-7.1.3, pluggy-1.0.0
rootdir: /private/tmp/pyaaa
plugins: anyio-3.6.2
collected 3 items                                                                                                                                                                                              

test/test_default_api.py .                                                                                                                                                                               [ 33%]
test/test_dump_file_id_map_inner.py .                                                                                                                                                                    [ 66%]
test/test_error_response.py .                                                                                                                                                                            [100%]

============================================================================================== 3 passed in 1.23s ===============================================================================================
```

**Comment by Ivan-Kurochenko** [comment]
@wing328 
Check the generated code for unresolved imports, is everything ok ? 

I also can generate successfully open API, but imports ...

**Comment by wing328** [comment]
Can you do a test with the petstore spec: https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml to see if it works in your environment?

**Comment by Ivan-Kurochenko** [comment]
@wing328 
I will do it later, can you please give me the command you have used for generating?

**Comment by wing328** [comment]
e.g. java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g python -i /tmp/a.yaml -o /tmp/py/

**Comment by Ivan-Kurochenko** [comment]
ok.... 
I have used 
```shell
openapi-generator generate -i /path/to/spec.yaml -g python -o /path/to/output/dir
```

and I haven't generated the cli jar, how can I do this ?

**Comment by wing328** [comment]
please run `./mvnw clean package -DskipTests -Dmaven.javadoc.skip=true` to compile the JAR

(please use git bash if you're using Windows)

**Comment by Ivan-Kurochenko** [comment]
@wing328 

I have generated the Open API for PetStore, running this command
```shell
openapi-generator generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -g python -o ./openapi
```

and the problem is still, imports are unresolved. what can you suggest now ?

**Comment by Ivan-Kurochenko** [comment]
@wing328 
I have an update. 
I have generated the Open API using JAR and unresolved imports only in `__init__.py` files instead of the whole project. 

<img width="709" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/75803414/74f67a1a-801a-4049-801e-e2707200f5ce">

**Comment by wing328** [comment]
Maybe an issue with how python is set up in your machine.

Can you try with another machine?

**Comment by Ivan-Kurochenko** [comment]
@wing328 
Sorry, but it is a single machine. 
Can you give me a tutorial you have used for installing Python

**Comment by Ivan-Kurochenko** [comment]
@wing328
```shell 
>>> python3 --version
Python 3.10.11
```

**Comment by robertschweizer** [comment]
I believe the output you are getting also matches the samples, e.g. in https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/echo_api/python/openapi_client/__init__.py

Your interpreter cannot find the generated Python package `openapi_client` (the name can be configured in the generator).  Try installing it with `pip install /path/to/output/dir` in the Python interpreter that your IDE is using.

**Comment by isarang** [comment]
@Ivan-Kurochenko  were you able to resolve it? it was fixed for some time after package install but its recurring again
