### ISSUE TITLE
[BUG][FLASK] enum name issue

### ISSUE THREAD

**Issue by fleutot** [OpenAPITools/openapi-generator#16557]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? 
-> Nope, but tested with the docker image, which I think is [at most 17 days old](https://hub.docker.com/r/openapitools/openapi-generator-cli/tags).
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Generated flask server code has bad Python syntax for `enum`.

##### openapi-generator version

7.0.1-SNAPSHOT (got it from Docker)

##### OpenAPI declaration file content or url
https://github.com/TALQ-consortium/TALQ_specification/tree/main/oas

##### Steps to reproduce

I'm trying to generate a TALQ gateway in flask, from [their OpenAPI specs](https://github.com/TALQ-consortium/TALQ_specification/tree/main/oas).

I've download these OpenAPI specs into my local folder, and tried to generate a server as per the [Docker instructions](https://openapi-generator.tech/).

```
docker run --rm -v $PWD:/local openapitools/openapi-generator-cli generate -i /local/talq-api-gateway-2-5-1.json -g python-flask -o /local/out/flask
```
Generation gave a wall of text, a lot of `INFO`, some `WARN`, but the code was generated. I couldn't find anything special about the offending identifiers in this text. Return value in CLI is OK.

Then I followed the instructions in `out/flask/README.md`:
```
# building the image
docker build -t openapi_server .

# starting up a container
docker run -p 8080:8080 openapi_server
```
This results in an error in `openapi_server/models/event_type.py`, the generated python code is invalid:
```
class EventType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUMBER_&#39;abnormalNoiseDetected&#39; = 'abnormalNoiseDetected'
    NUMBER_&#39;absoluteLampPowerTooHigh&#39; = 'absoluteLampPowerTooHigh'
    NUMBER_&#39;absoluteLampPowerTooLow&#39; = 'absoluteLampPowerTooLow'
...
```
`NUMBER_&#39;` is probably wrong, &#39 is an apostrophe that did not translate correctly. But I'm not sure what the expected result should be.

##### Related issues/PRs

Related issue: https://github.com/OpenAPITools/openapi-generator/issues/13689

**Comment by wing328** [comment]
Thanks for reporting the issue.

To fix it, one needs to use `{{{...}}}` mustache tag (original value) instead of `{{...}}` mustache tag (escaped value).

Is that something you can help file a PR with?

**Comment by wing328** [comment]
@fleutot did you update this line: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python-flask/model.mustache#L32 ?

**Comment by wing328** [comment]
I got the following after updating the template:
```
class EnumModel(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    NUMBER_'available>' = 'available>'
    NUMBER_'pending<' = 'pending<'
    NUMBER_'sold' = 'sold'
    NUMBER_'1' = '1'
    NUMBER_'2' = '2'

```

Looks like we need to fix the issue in the python flask generator (java class) as well.

**Comment by wing328** [comment]
UPDATE: filed https://github.com/OpenAPITools/openapi-generator/pull/16576 to fix the issue.

**Comment by fleutot** [comment]
Result after the PR:
```
class EventType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ABNORMALNOISEDETECTED = 'abnormalNoiseDetected'
    ABSOLUTELAMPPOWERTOOHIGH = 'absoluteLampPowerTooHigh'
    ABSOLUTELAMPPOWERTOOLOW = 'absoluteLampPowerTooLow'
```
, which seems correct, thank you!

I had to manually move the previously generated `event_type.py` to see the change, maybe I missed a required clean command, or there is something broken in build dependencies.

Very grateful, thanks!
