### ISSUE TITLE
[BUG] Version 7.0.1 of openapi-generator-cli not published on Maven2 repository

### ISSUE THREAD

**Issue by Mobiletainment** [OpenAPITools/openapi-generator#16609]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I get a 404 file not found when I try to use the newly released patch version `7.0.1` of the generator-cli:

```
Download failed, because of: "Request failed with status code 404"
x-amz-error-code NoSuchKey
x-amz-error-message The specified key does not exist.
x-amz-error-detail-key maven2/org/openapitools/openapi-generator-cli/7.0.1/openapi-generator-cli-7.0.1.jar
```

It appears to be missing from the Maven 2 repository: https://repo.maven.apache.org/maven2/org/openapitools/openapi-generator-cli/

<img width="536" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/1514111/4369106b-a6a8-40c2-8c2e-3964b5d3b167">

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

My `openapitools.json`:
```json
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "7.0.1"
  }
}

```

##### Generation Details

```
npx @openapitools/openapi-generator-cli generate -i "./schemas/API.openapi.yaml" -g typescript-axios -o "libs/rest/src/lib/api" --additional-properties=supportsES6=true,disallowAdditionalPropertiesIfNotPresent=true,withoutPrefixEnums=true
```

**Comment by wing328** [comment]
we're working on the release. will be published soon.

**Comment by wing328** [comment]
v7.0.1 CLI: https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.0.1/openapi-generator-cli-7.0.1.jar
