### ISSUE TITLE
[BUG][C] C compiler fails because model includes "set.h" which does not exist.

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [OpenAPITools/openapi-generator#16611]
##### Description

The C Client uses set.h which does not exist.
This causes the compiler to fail because set.h does not exist.
The issue occurs when a model object has a array of enums property that is also unique.

![grafik](https://github.com/OpenAPITools/openapi-generator/assets/66277940/d9b36f5a-3b79-4ce9-bde9-f4f3fe747467)

I suppose set.h/set.c should also be next to list.c/list.h so I guess even if the files are simply missing, the include would also be wrong.

##### openapi-generator version

I have tested with 6.2.1 and 7.0.0. This issue exists with both versions.

##### OpenAPI declaration file content or url
https://pastebin.com/raw/WvAZ1Rwc

##### Generation Details

Generation using gradle
Gradlefile (build.gradle.kts):

import org.openapitools.generator.gradle.plugin.tasks.GenerateTask

//Using version 7.0.0 also did not fix anything
plugins {
    id("org.openapi.generator") version "6.2.1"
}

tasks.register<GenerateTask>("genV2C") {
    validateSpec.set(false)
    generatorName.set("c")
    inputSpec.set("$rootDir/schema.json")
    outputDir.set("$rootDir/generated/")
}

Then on console run:

./gradlew genV2C

##### Steps to reproduce

See  Generation Details

##### Related issues/PRs

None to my knowledge

##### Suggest a fix

Perhaps set.c and set.h is just simply missing by mistake?
I could only guess as to what the actual contents of those files would be.

**Comment by wing328** [comment]
as a workaround, please type mappings to map set to list

e.g. `--type-mappings set=list` in the CLI

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/16730 to map set to list by default in the c client generator.
