### ISSUE TITLE
Kotlin generator is not generating all the fields.

### ISSUE THREAD

**Issue by umar-id** [OpenAPITools/openapi-generator#16612]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
 I am generating schemas in my android application using kotlin plugin. but when I see the generated schema, it ignores all the fields which are coming under properties in image 1 (It does not generate variables from addresses and visitors). And when I change the schema like shown in image 2, it works fine.

this issue is only happening when I use kotlin generator, using android generator does not produce the issue

##### openapi-generator version
7.0.0

image 1
![image](https://github.com/OpenAPITools/openapi-generator/assets/86039607/2003b4e5-5be9-4c4c-b5b9-b3a3ac38d210)

image 2
![image](https://github.com/OpenAPITools/openapi-generator/assets/86039607/a4425355-1823-4c25-9ab9-73547ef6f1f5)

**Comment by wing328** [comment]
use https://openapi-generator.tech/docs/customization/#openapi-normalizer

and enable `REFACTOR_ALLOF_WITH_PROPERTIES_ONLY`
