### ISSUE TITLE
[BUG] Gradle openapigenerator plugin (spring) - parameterNameMappings not working

### ISSUE THREAD

**Issue by vasanth0989** [OpenAPITools/openapi-generator#16615]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

- The ```openApiGenerate``` task parameterNameMappings is not working as expected.

> spec.yaml
```yaml
/accounts:
  get:
    operationId: getAccounts
    tags:
      - Step 1
    description: Get Eligible accounts
    parameters:
      - in: header
        name: X-USER-BANK-ID
        description: Bank user ID
        required: true
        schema:
          type: string
   responses:
     200:
       description: Get eligible accounts
```

````groovy
openApiGenerate {
   parameterNameMappings.set(['X-USER-BANK-ID': 'bankId'])
   generatorName.set("spring")
   inputSpec.set("$rootDir/specs/openapi-spec.yml"
   outputDir.set("$buildDir/generated")
   apiPackage.set("com.example.openapidemo.api")
   modelPackage.set("com.example/openapidemo.model")
}
configOptions.set([
  dateLibrary: "java8",
  useSpringBoot3: "true",
  interfaceOnly: "true",
  hideGenerationTimestamp: "true",
  skipDefaultInterface: "true",
  sourceFolder: "src/api/java"
])
}
````

- If you look into the above spec and the gradle task configuration I am trying to change the generated method param name of header to set as **bankId**.
- But this is not working as expected there is no effect with ```parameterNameMappings``` option.

##### openapi-generator version
**Version: 7.0.0**
```
dependencies {
  classpath "org.openapitools:openapi-generator-gradle-plugin:7.0.0"
}
```

##### OpenAPI declaration file content or url

- YAML file spec and the task configuration has been specified above.

##### Generation Details

* I am using Gradle plugin to generate the spring API interface code, where I am running the configured ```openApiGenerate``` task to generate my source code.

##### Steps to reproduce

* Run the ```openApiGenerate``` task of the gradle plugin with ```parameterNameMappings``` options configured.
* You will not see that configuration values are getting acknowledged instead it is gonna use the same **baseName** as the header parameter name in the spec.

##### Related issues/PRs

- I dint find any existing issues/PRs specifically talking about this Bug.

##### Suggest a fix

* Probably we need to fix the [OpenApiGeneratorPlugin.kt](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt#L96) file where we are not setting the ```parameterNameMappings``` and ```nameMappings``` while registering the ```openApiGenerate``` task.
* Adding a setter for ```parameterNameMappings``` and ```nameMappings``` should get this  bug addressed.

**Comment by wing328** [comment]
thanks for reporting the issue.

- please try v7.0.1 to see if the issue still persists
- please try the CLI as well to see if it's an issue with the Gradle plugin only.

**Comment by vasanth0989** [comment]
I haven't tried with 7.0.1 will give it a try, it worked fine with cli though.

**Comment by vasanth0989** [comment]
Just validated with 7.0.1 the issue still exists for the gradle plugin, as I don't see [OpenApiGeneratorPlugin.kt](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/OpenApiGeneratorPlugin.kt#L96) file was modified, this has to be addressed.

**Comment by wing328** [comment]
Just filed #16616 to fix the issue. Can you please help review and test it when you've time? Thanks.

**Comment by wing328** [comment]
Merged the fix. A SNAPSHOT version of the gradle plugin will be published soon. Please test that later to see if that issue is resolved for you.
