### ISSUE TITLE
[BUG][python] Path parameter with value `0` leads to error

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#16621]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The request function generated from below OpenAPI has the argument `index : StrictInt`.

It later handles path parameters like this:

```py
        # process the path parameters
        _path_params = {}
        if _params['index']:
            _path_params['index'] = _params['index']
```

If `index` is `0`, the if-block is skipped and the server is called with `/get/{index}` instead of `/get/0`.

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: ""
  version: ""
paths: 
  /get/{index}:
    get:
      parameters:
        - name: index
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: OK
```

##### Generation Details

```
openapi-generator generate -g python -i swagger.yaml
```

**Comment by wing328** [comment]
Filed https://github.com/OpenAPITools/openapi-generator/pull/16628 to fix it.
