### ISSUE TITLE
[REQ] Axios Version Bump

### ISSUE THREAD

**Issue by coler-j** [OpenAPITools/openapi-generator#16642]
### Is your feature request related to a problem? Please describe.

Axios `0.27.2` and Node versions > 18 have some stability issues. Can we update the axios generator version?

## Describe the solution you'd like

Upgrade the axios version, controllable via an argugment.

## Describe alternatives you've considered

Ditching axios generator for fetch.

**Comment by wing328** [comment]
may I know if you've time to contribute a PR with the suggested change?
