### ISSUE TITLE
[BUG] Java produces wrong class with array and enum, kotlin is successfull

### ISSUE THREAD

**Issue by vongohren** [OpenAPITools/openapi-generator#16648]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Im loading this spec: https://api.entur.io/products/api-docs/swagger.json
And everything is great until i compile det java produced code since there is a broken type.
Adding images for clarity. Two images with the error, and two iamges for kotlin that has understood this properly.
<img width="513" alt="Screenshot 2023-09-22 at 12 06 53" src="https://github.com/OpenAPITools/openapi-generator/assets/1012055/53e0417e-acd5-4717-8d7c-e9c547992cea">
<img width="1146" alt="Screenshot 2023-09-22 at 12 07 21" src="https://github.com/OpenAPITools/openapi-generator/assets/1012055/b8889865-b21b-4448-b291-9dc9c0fa6881">
<img width="945" alt="Screenshot 2023-09-22 at 12 07 29" src="https://github.com/OpenAPITools/openapi-generator/assets/1012055/7d88ed65-cc5e-4e4c-9060-0ffb9e4eb6b5">
<img width="884" alt="Screenshot 2023-09-22 at 12 07 36" src="https://github.com/OpenAPITools/openapi-generator/assets/1012055/f757ee74-8b55-403f-9882-018a09ee4195">

How can I bypass this, or is it anything that has to be done to make this work?

##### openapi-generator version

6.6.0

##### OpenAPI declaration file content or url

https://api.entur.io/products/api-docs/swagger.json

##### Generation Details

Gradle

```
tasks.register("downloadFile", Download::class) {
    src("https://api.entur.io/products/api-docs/swagger.json")
    dest("$projectDir/generated/product-swagger.json")
}

openApiGenerate {
    generatorName.set("java")
    inputSpec.set("$projectDir/generated/product-swagger.json")
    outputDir.set("$projectDir/generated")
    apiPackage.set("no.entur.product.client.api")
    modelPackage.set("no.entur.product.client.model")
    configOptions.set(mapOf(
        "library" to "feign",
        "dateLibrary" to "java8"
    ))
}
```

##### Steps to reproduce

Just compile with the following gradle setup and see things not kompiling

##### Suggest a fix

I dont know, but make sure the code that is generated is compilable?

**Comment by wing328** [comment]
> 6.6.0

can you try openapi-generator v7.0.1 instead?

**Comment by vongohren** [comment]
@wing328 thanks for the reply. It was acctually part of the swagger spec and we could fix it by specifying better. So will close it for now
