### ISSUE TITLE
[BUG][php-client] `x-codegen-request-body-name` seems to be ignored

### ISSUE THREAD

**Issue by etshy** [OpenAPITools/openapi-generator#16647]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? 
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The `x-codegen-request-body-name` paremeter seems to be ignored while generating php-client. I use client a lot with named parameters so this will break everywhere I'm calling the client.

The `body` parameter name is always the name of the class referenced while it should be the name I set up in `x-codegen-request-body-name` ("command" in my example below)

##### openapi-generator version

tested on 7.0.0 and 7.1.0 (`openapi-generator-cli-7.1.0-20230922.055434-15.jar`)

##### OpenAPI declaration file content or url

[json schema](https://gist.github.com/etshy/2a97c7a968936036b86b64910c548d6e)

##### Generation Details

`java -jar openapi-generator-cli-7.1.0-20230922.055434-15.jar generate -i ./minimalcodegenbodyname.json -g php -o ./generated/php/ -c phpconfig.json`

phpconfig.json
```json
{
   "gitUserId":"user",
   "gitRepoId":"project",
   "variableNamingConvention":"camelCase",
   "invokerPackage":"My\\Client",
   "artifactVersion":"0.0.0"
}
```

##### Steps to reproduce

generate code for php client with given json and parameters and check generated Api file

##### Related issues/PRs

found #9123 but it seems to concern php server generation

##### Suggest a fix

`x-codegen-request-body-name` should change the parameter name.

##### More Info

In case That's important (I doubt it but still), I use `zircote/swagger-php`'s Attributes and `nelmio/NelmioApiDocBundle` to generate the json file.
`swagger-php` can handle the `x` parameter just fine as it appears correctly in the json schema, but codegen seems to ignore it

**Comment by wing328** [comment]
what about using the parameterNameMappings option instead?

e.g. 
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i modules/openapi-generator/src/test/resources/3_0/java/petstore-with-fake-endpoints-models-for-testing-okhttp-gson.yaml  -o /tmp/java2/ --parameter-name-mappings _type=paramType,type_=typeParam
```

ref: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#name-mapping

**Comment by etshy** [comment]
It worked with this command

`java -jar openapi-generator-cli-7.1.0-20230922.055434-15.jar generate -i ./minimalcodegenbdyname.json -g php -o ./generated/php/ -c phpconfig.json --parameter-name-mappings CreateUserCommand=command`

But it means I have to add param with all my requestBody.

In some Api i'm working on there is tons a them, so having the `x-codegen-request-body-name` does that automatically (as it's auto generated with swagger-php's attribute) would really be great.

**Comment by wing328** [comment]
@etshy I've filed https://github.com/OpenAPITools/openapi-generator/pull/17850 to support the extension in the request body (before it was only supported in the operation level/object)
