### ISSUE TITLE
[REQ][python] Allow streaming large response bodies

### ISSUE THREAD

**Issue by robertschweizer** [OpenAPITools/openapi-generator#16640]
When downloading a large response body, e.g. a file, it is useful to only load a chunk of the file into memory at once.

The generated client (pydantic-based, v7.0.1) does not allow streaming responses in this way: When specifying `_preload_content=False`, this option is passed through to urllib3. But later, `urllib3.HTTPResponse.data` is accessed to fill `ApiResponse.raw_data`. This loads the entire response body into memory.

## Describe the solution you'd like

1. Expose the `urllib3.HTTPResponse` instance to callers of the `_with_http_info` request functions for maximum flexibility. Maybe add this as an extra property `urllib3_response` to `ApiResponse`.
2. Do not access `urllib3.HTTPResponse.data` when constructing the `ApiResponse` instance. Instead, `ApiResponse.raw_data` could become a `@property` that returns `self.urllib3_response.data`. The decoding done if `_preload_content=True` can also be moved to the property method.

## Describe alternatives you've considered

My workaround is using plain `requests` to stream large files.

**Comment by robertschweizer** [comment]
Closed in https://github.com/OpenAPITools/openapi-generator/pull/16802

**Comment by jleaniz** [comment]
@robertschweizer have you been able to stream files after this was merged? I'm curious because I haven't been able to get this to work properly using the python-pydantic-v1 generator

**Comment by dtzeng** [comment]
Same as @jleaniz .

What's the right way to stream now? I'm also using the `python-pydantic-v1` generator, and I'm calling my `..._with_http_info` function with `_preload_content=False`. I see that the returned `ApiResponse` object has the `raw_data` field, but we don't have access to the original `urllib3.HTTPResponse`.

I get nothing when I do `str(raw_data)`. Wrapping `io.BufferedReader(raw_data)` also doesn't work (`AttributeError: 'bytes' object has no attribute 'readable'`)

How do we read from ApiResponse.raw_data?

**Comment by jleaniz** [comment]
You can read ```raw_data``` directly from the ApiResponse object, the problem is that it's not a stream, so the entire response is transferred and there's no read() like method to read in chunks, even if you set ```preload_content=False```

**Comment by dtzeng** [comment]
Right, I think ApiResponse only provides the `raw_data`. From the original description: `Maybe add this as an extra property urllib3_response to ApiResponse`

The pydantic v2 generator (`-g python`) produces a separate `without_preload_content` function that returns the `urllib3.HTTPResponse` directly (aliased as `RESTResponseType`)

@robertschweizer was the urllib3 response supposed to be added to ApiResponse as well and was missed? Or should the `without_preload_content` be backported to the v1 generator? (`-g python-pydantic-v1`)

**Comment by robertschweizer** [comment]
Sorry, but this feature was only implemented for the pydantic v2 Python client generators. The `python-pydantic-v1` generator does not allow streaming large response objects.

**Comment by robertschweizer** [comment]
Yes, the `without_preload_content` method would need to be backported. Adding the urllib3 response to `ApiResponse` would not be useful, because all the response data is loaded into memory to fill the `data` and `raw_data` attributes.

**Comment by JJtheJJpro** [comment]
I'm aware this is an older issue and this comment is not python related, but I'm wondering if allowing streaming large response bodies should be spread to other languages, like Go for example, I ran into this issue in Go, and this is the closest thing I've seen related.
