### ISSUE TITLE
[BUG][Python-Flask] Missing required argument on PUT, POST, PATCH

### ISSUE THREAD

**Issue by tomghyselinck** [OpenAPITools/openapi-generator#1666]
##### Description

`PUT /data` fails to provide positional argument when `Data` is an `object` type.

```
Calling function: <function data_put at 0x7fd26bd3b1e0> with args: {}
[2018-12-12 09:58:56,228] ERROR in app: Exception on /data [PUT]
Traceback (most recent call last):
  File "/home/tom/.local/lib/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tom/.local/lib/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tom/.local/lib/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tom/.local/lib/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/tom/.local/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tom/.local/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/uri_parsing.py", line 132, in wrapper
    response = function(request)
  File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/validation.py", line 165, in wrapper
    response = function(request)
  File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/home/tom/.local/lib/python3.5/site-packages/connexion/decorators/parameter.py", line 131, in wrapper
    return function(**kwargs)
TypeError: data_put() missing 1 required positional argument: 'data'
127.0.0.1 - - [12/Dec/2018 09:58:56] "PUT /data HTTP/1.1" 500 -
```

I've seen this also fails with `POST` and `PATCH`.

Please note that this does work fine when the `Data` is not an `object` type. For example when using:
```
components:
  schemas:
    Data:
      type: string
```

##### openapi-generator version

I used OpenAPI generator CLI version `4.0.0-SNAPSHOT`:
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20181210.103357-85.jar

##### OpenAPI declaration file content or url

See `python-flask-required-body.yaml` in the attached zip-file:
[python-flask-required-body.zip](https://github.com/OpenAPITools/openapi-generator/files/2671184/python-flask-required-body.zip)

##### Command line used for generation

    java -jar openapi-generator-cli-4.x.jar generate -i ./python-flask-required-body.yaml -g python-flask -o ./python-flask-required-body/

##### Steps to reproduce

1. Generate the server code

       ./python-flask-required-body.sh

2. Start the server

       (cd python-flask-required-body && python3 -m openapi_server)

3. Perform a client request

       curl -X PUT "http://localhost:8080/data" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"myItem\":\"myItem\"}"

   Returns:
   ```
   {
     "detail": "The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.",
     "status": 500,
     "title": "Internal Server Error",
     "type": "about:blank"
   }
   ```

##### Related issues/PRs

Related issues/PRs for `openapi-generator`:
* #1758

I found a similar issue in [connexion](https://github.com/zalando/connexion):
* [#548 - Incorrect validation of required body properties](https://github.com/zalando/connexion/issues/548)
* [#579 - Incorrect validation of required body parameters](https://github.com/zalando/connexion/issues/579)

##### Suggest a fix

Either:
1. Workaround as used in #1758 (commit https://github.com/OpenAPITools/openapi-generator/pull/1758/commits/39e4441a6e7498f432321adef2930f0298ea5526#diff-23008aab5bc1adc4749f4fa8e9ebb94c):

   Set the `x-codegen-request-body-name: body` in the `requestBody`'s `schema`.
1. You need to provide the `x-body-name` in the `requestBody`'s `schema` so it matches the (positional) function argument name.
   
   See also [Automatic Parameter Handling](https://github.com/zalando/connexion#automatic-parameter-handling) at [connexion](https://github.com/zalando/connexion):
   
   > In the OpenAPI 3.x.x spec, the requestBody does not have a name. By default it will be passed in as 'body'. You can optionally provide the x-body-name parameter in your requestBody schema to override the name of the parameter that will be passed to your handler function.
1. Keep name `body` for the (**_single_**?) (_positional_) argument.

**Comment by nathan5280** [comment]
On the suggested fixes in the petstore example.
2. Updated the default_controller.py
```python
def add_pet(body):  # noqa: E501
```
which worked fine.
1. If I add the x-body-name to the requestBody/schema
```yaml
    post:
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: addPet
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPet'
              x-body-name: new_pet
```
or the components/schemas/NewPet
```yaml
    NewPet:
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
      x-body-name: new_pet
```
the x-body-name isn't copied through to the generated spec in openapi_server/openapi/openaip.yaml.  If I manually add it to this file here
```yaml
            schema:
              x-body-name: new_pet
              $ref: '#/components/schemas/NewPet'
```
everything works fine.

Thanks for the information above.  It helped me get past a sticky spot on my project.

**Comment by jdeyton** [comment]
If you look at the source code for connexion, it tries to send the requestBody content to the operation as a named argument. The argument's name is defaulted to "body" in the absence of "x-body-name" in the `openapi.yaml`. Unfortunately, the openapi-generator's Python/Flask/Connexion Java simply doesn't add the extension for requestBody parameters.

I've discovered the **third** workaround below works if you want to be able to re-generate your code without manually editing either the `openapi.yaml` file or your controller modules.

1. Copy the `controller.mustache` template to your templates dir and edit it.

2. Leave the parameter as is if `isBodyParam` is false, otherwise rename it to `body`:

`def {{operationId}}({{#allParams}}{{^isBodyParam}}{{paramName}}{{/isBodyParam}}{{#isBodyParam}}body{{/isBodyParam}}{{^required}}=None{{/required}}{{#hasMore}}, {{/hasMore}}{{/allParams}}):`

3. Then way down after the docstring ends, add in these middle three lines to assign the value of `body` to the desired parameter name:
```
    {{#allParams}}
{{#isBodyParam}}
    {{paramName}} = body
{{/isBodyParam}}
    {{^isContainer}}
```

4. If you're not already using templates, run the code gen with the `-t templates/dir` flag. In recent openapi-generator versions, this should pick up just the mustache templates you've provided.

**Comment by SteveHespelt** [comment]
following up on the [earlier comment](https://github.com/OpenAPITools/openapi-generator/issues/1666#issuecomment-451684201) by @nathan5280,
I've found that the OpenAPI-tech 5.0.1 code generator will preserve the x-body-name property if it is NOT a sibling of a $ref usage as mentioned in [using-ref](https://swagger.io/docs/specification/using-ref/#sibling). So I have x-body-name as a top-level property for a requestBody type. The generated openapi.yaml has this preserved & the run-time code makes use of this. What's interesting is that the Swagger codegen generated code has 'body' as the formal parameter name while OpenAPI-tech uses the type name to base the parameter name while the Connexion's OpenAPIOperation._get_body_argument() assumes a default of 'body' (overridden by the value of x-body-name in the body's schema, if present).

And this is related to issue 3345 which refers back to this issue.

**Comment by Tohnmeister** [comment]
The workarounds mentioned only seem to work when using `application/json`. When using `multipart/form-data` (for example when uploading files), it has no effect and the error remains.

**Comment by srl295** [comment]
so maybe this is a **fourth** workaround, but what I see is that the calling code in `parameter.py` is:

```python
        return function(**kwargs)
```

… where `kwargs={}` (for example)

but in my controller there's:

```python
def myfunc(myobj):
   #…
    if connexion.request.is_json:
        myobj = MyObj.from_dict(connexion.request.get_json())  # noqa: E501
```

so a workaround is to change the signature to `def myfunc(myobj=None):` - this could be in the template.  Should be some way to fix the template so this works by default.

**Comment by Johnlon** [comment]
The problem is that the existing placement of x-body-name is not compliant with OAS3 and to tools will reject it or drop it on the floor like Openapi Generator.
See https://github.com/zalando/connexion/issues/1452 which provides support for a valid OAS3 location for this flag.
