### ISSUE TITLE
[BUG][KOTLIN] Headers declaration results in compilation error

### ISSUE THREAD

**Issue by ivanvasheka-intellias** [OpenAPITools/openapi-generator#16678]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating api using retrofit 2 library, in the api.mustache there is an entry of a headers annotation, that looks like this:

```
    {{#prioritizedContentTypes}}
    {{#-first}}
    @Headers({
        "Content-Type:{{{mediaType}}}"
    })
    {{/-first}}
    {{/prioritizedContentTypes}}
```

##### openapi-generator version

7.0.1

##### Generation Details

Generate any API adding `prioritizedContentTypes` to the POST or PUT operation. 

##### Suggest a fix

Update template to have correct headers declaration (without { } ):

```
    {{#prioritizedContentTypes}}
    {{#-first}}
    @Headers("Content-Type:{{{mediaType}}}")
    {{/-first}}
    {{/prioritizedContentTypes}}
```

**Comment by wing328** [comment]
Can you please submit a PR with the suggested fix?
