### ISSUE TITLE
[BUG][Python] Stringified Enum variable used in request path instead of underlying string

### ISSUE THREAD

**Issue by john-odonnell** [OpenAPITools/openapi-generator#16688]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When an `Enum` of strings is used as a path parameter, the request path contains a stringified constant variable name instead of the underlying string.

##### openapi-generator version

`openapitools/openapi-generator-cli:latest`

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: ""
  version: ""
paths:
  /items/{enumParam}:
    get:
      parameters:
      - name: enumParam
        in: path
        required: true
        schema:
          $ref: "#/components/schemas/EnumValue"
      responses:
        200:
            description: "Responds with the requested path"
            content:
              text/plain:
                schema:
                  type: string
components:
  schemas:
    EnumValue:
      type: string
      enum:
        - a
        - b
```

##### Generation Details

Generating using the Python client generator with default settings.

```yaml
# ${PWD}/config.yml
generatorName: python
outputDir: /spec/python
inputSpec: /spec/openapi.yml
```

```
docker run --rm \
  -v "${PWD}":/spec \
  openapitools/openpai-generator-cli:latest \
    generate -c /spec/config.yml
```

##### Steps to reproduce

1. Start a local web server that responds to requests with the requested resource path.

   ```python
   # ${PWD}/echo_server.py
   import http.server
   import socketserver

   port = 80

   # Create a custom request handler that responds to all requests
   class CustomHandler(http.server.SimpleHTTPRequestHandler):
       def do_GET(self):
           # Extract the requested API path
           api_path = self.path
           self.send_response(200)
           self.send_header('Content-type', 'text/html')
           self.end_headers()
           self.wfile.write(api_path.encode('utf-8'))

   # Create a socket server with the custom request handler
   with socketserver.TCPServer(('', port), CustomHandler) as httpd:
       print(f"Server running on port {port}")
       # Start the server
       httpd.serve_forever()
   ```

   ```
   $ python3 echo_server.py
   Server running on port 80
   ```

3. Install the generated client:

   ```
   $ cd python
   $ python3 setup.py install --user
   ```

   This creates an `EnumValue` model:

   ```python
   class EnumValue(str, Enum):
       """
       EnumValue
       """

       """
       allowed enum values
       """
       A = 'a'
       B = 'b'

       @classmethod
       def from_json(cls, json_str: str) -> EnumValue:
           """Create an instance of EnumValue from a JSON string"""
           return EnumValue(json.loads(json_str))
   ```

2. Make requests to an endpoint that uses an Enum type as a path parameter:

   ```python
   # #{PWD}/example.py
   import openapi_client
   from openapi_client.models import EnumValue

   configuration = openapi_client.Configuration(host = "http://localhost")

   with openapi_client.ApiClient(configuration) as api_client:
       api_instance = openapi_client.DefaultApi(api_client)

       print(api_instance.items_enum_param_get(EnumValue.A))
       print(api_instance.items_enum_param_get(EnumValue.A.value))
       print(api_instance.items_enum_param_get('a'))
   ```

   This code outputs the following:

   ```
   $ python3 example.py
   /items/EnumValue.A
   /items/EnumValue.A
   /items/EnumValue.A
   ```

   I expect it to output:

   ```
   $ python3 example.py
   /items/a
   /items/a
   /items/a
   ```

##### Related issues/PRs

I don't think there is an open issue that matches this one.

##### Suggest a fix

As a workaround in my own project, I updated [`api_client.mustache`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/api_client.mustache#L184-L189) to check if path parameters are instances of `aenum.Enum` and dereference them:
```diff
for k, v in path_params:
+   # dereference Enums
+   if isinstance(v, Enum)
+       v = v.value
+
    # specified safe chars, encode everything
    resource_path = resource_path.replace(
        '{%s}' % k,
        quote(str(v), safe=config.safe_chars_for_path_param)
    )
```

Would probably need to do the same for query parameters, too.

**Comment by wing328** [comment]
@john-odonnell thanks for reporting the issue. What about applying a fix similar to https://github.com/OpenAPITools/openapi-generator/pull/15278/files#diff-18c932643600d7fe7b3ae94dcf8f006187cdae3e1714269eba37fe5b7c523ffdR202 to the path parameters?
