### ISSUE TITLE
Improve messages of "validate" result

### ISSUE THREAD

**Issue by ackintosh** [OpenAPITools/openapi-generator#167]
##### Description

```
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar validate -i test-petstore.yaml

Validating spec file (test-petstore.yaml)
attribute paths.'/pet/findByStatus'(get).responses is missing
attribute paths.'/pet/{petId}'(get).parameter is unexpected
attribute paths.'/pet'.pu is unexpected
attribute paths.'/pet'(post).responses is missing
Exception in thread "main" org.openapitools.codegen.cmd.ValidateException
        at org.openapitools.codegen.cmd.Validate.run(Validate.java:50)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:56)

```

`Exception in thread "main"....`  seems like something wrong in validation command, but this is the correct behavior in the case of validation errors. It is confusing. 😕 
ref: [Validate.java#L50](https://github.com/ackintosh/openapi-generator-1/blob/18031e3492ae8391802b09ca3209f45ab4ed1a5c/modules/openapi-generator-cli/src/main/java/org/openapitools/codegen/cmd/Validate.java#L50)

##### openapi-generator version

current master

##### Suggest a fix/enhancement

- validation error (with exit code 1)

```
$ cli validate -i https......
Validating spec file (test-petstore.yaml)

- attribute paths.'/pet/findByStatus'(get).responses is missing
- attribute paths.'/pet/{petId}'(get).parameter is unexpected
- attribute paths.'/pet'.pu is unexpected
- attribute paths.'/pet'(post).responses is missing
$ 
```

- no errors (with exit code 0)

```
$ cli validate -i https......
Validating spec file (test-petstore.yaml)

No validate errors detected.
$ 
```

**Comment by jmini** [comment]
+1, this is a good idea.

**Comment by wing328** [comment]
Agreed CLI throwing the exception is a bad idea.

**Comment by wing328** [comment]
Same for "generate":
```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Exception in thread "main" java.lang.RuntimeException: Can't load config class with name 'php2'
Available:
ada
ada-server
android
apache2
apex
......
typescript-node
        at org.openapitools.codegen.CodegenConfigLoader.forName(CodegenConfigLoader.java:50)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:473)
        at org.openapitools.codegen.cmd.Generate.run(Generate.java:312)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:56)
```
Ideally it should not show the exception either.

**Comment by jimschubert** [comment]
@wing328 your exception is thrown via `CodegenConfigLoader`, which is different from the Validate command throwing an exception. We could verify input generator names in the Generate command, but then we're duplicating logic/messages/etc.  If we validate the input generator name, then we'll have to start validating all options passed to the Generate command, and I think that's a slippery slope of deciding where generator argument validations occur and can lead to lots of duplicated messages and whatnot.

I'd be happy to take up both of these and open a PR for feedback on the approach.

**Comment by jimschubert** [comment]
I've opened a PR to address both concerns reported in this issue, as well as a few other cases I encountered to make things consistent.

There are still numerous areas for improvement, namely that we throw `RuntimeException` everywhere, and there isn't always a user-friendly (from a CLI perspective) message attached to the exception. I think we can fix these as we encounter them.

**Comment by jimschubert** [comment]
@ackintosh my PRb with a fix was merged. Do you want to keep this open to track any other messages we may find before release, or were you specifically interested in the validate command?

**Comment by ackintosh** [comment]
I was interested in the validate command, so will close this issue. 💡 Thanks for the PR!
