### ISSUE TITLE
[BUG] [kotlin] [okhttp4] Generated Client Code does not Compile

### ISSUE THREAD

**Issue by sauterl** [OpenAPITools/openapi-generator#16714]
##### Description

There are several compilation errors for using the openapi generator gradle plugin (version 7.0.1) in combination with the okhttp4 library.
Specifically the following:

* ApiClient.kt: Modifier 'protected' is not applicable to 'top level function' (for method `request` on line 161)
* ApiClient.kt Unresolved reference: baseUrl (in method `request` on line 162)
* and following
* Generated Apis: Unresolved reference: request (as a consequence of the first item in this list)

##### openapi-generator version

Version 7.0.1

##### OpenAPI declaration file content or url

See the [OpenApi Sepcification](https://raw.githubusercontent.com/dres-dev/Client-Examples/dev/oas-client.json) or try to compile the [kotlin example project](https://github.com/dres-dev/Client-Examples/blob/dev/kotlin/README.md)

##### Generation Details

The gradle plugin is in use with the following `openApiGenerate` setup:

```groovy
openApiGenerate {
    generatorName = "kotlin"
    library = "jvm-okhttp4"
    inputSpec = "$rootDir/../oas-client.json".toString()
    outputDir = "$buildDir/generated".toString()
    apiPackage = "dev.dres.client"
}
```

##### Steps to reproduce

1. Execute gradle task `openApiGenerate`
2. Execute gradle task `compileKotlin`

##### Related issues/PRs

No related issues have been found so far

##### Suggest a fix

The following steps have lead to compilable and working code for our project:

1. Remove the rogue `}` at `ApiClient.kt:159:5`
2. Remove all `protected` modifiers in file `ApiClient.kt`

See the [corresponding gist](https://gist.github.com/sauterl/25e7ce2a68d943422a4307a26c05d02f)

**Comment by wing328** [comment]
@sauterl can you please file a PR with the suggested fixes? Thank you.

**Comment by sauterl** [comment]
@wing328 thanks, I will try to do so, however I am currently on a very tight budget with regards to time. If at all, I might be able to tackle it be the end of the month.

**Comment by wing328** [comment]
looks like this has been fixed. please pull the latest master to give it a try again
