### ISSUE TITLE
[BUG][KOTLIN-SPRING] Missing Bean Validation annotations on RequestBody

### ISSUE THREAD

**Issue by Fabii547** [OpenAPITools/openapi-generator#16738]
##### Description

The kotlin-spring generator does not add beanValidation annotations (e.g. `@Max`) for RequestBody params.

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

```yaml
paths:
  /add:
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              title: quantity
              minimum: 2
        required: true
      responses:
        '204':
          description: OK
```

generates 

```kotlin
@RequestMapping(
           method = [RequestMethod.PUT],
            value = ["/add"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun add(@Valid @RequestBody body: kotlin.Int): ResponseEntity<Unit>
```

but should have `@Min(2)` included:

```kotlin
fun add(@Valid @Min(2) @RequestBody body: kotlin.Int): ResponseEntity<Unit>
```

##### Generation Details

Plugin configuration: (beanValidation is enabled by default)

generatorName = 'kotlin-spring'
configOptions = [
interfaceOnly: 'true',
skipDefaultInterface: 'true',
useSpringBoot3: 'true'
]

##### Steps to reproduce

`./gradlew openApiGenerate`

##### Related issues/PRs

The same issue occurred and has been fixed in the java spring generator: https://github.com/OpenAPITools/openapi-generator/issues/13932

##### Suggest a fix

Applying the same fix as done in https://github.com/OpenAPITools/openapi-generator/issues/13932 for the java spring version.

**Comment by lukbaran** [comment]
Hi, I try to fix it in https://github.com/OpenAPITools/openapi-generator/pull/16859
