### ISSUE TITLE
[BUG] Python generator doesn't handle lists of nullable primitives

### ISSUE THREAD

**Issue by jamestrousdale** [OpenAPITools/openapi-generator#16740]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I have an OpenAPI spec where one field consists of a list of nullable floats (e.g., type hint `list[float | None]` in my Python server code - FastAPI to be specific).

It results in setting the nullable flag to true for the `items` field in the spec, but then the type generator doesn't acknowledge this nullability and so the field ends up of type `List[float]` in the client side - which obviously causes validation issues when some of those `None` values actually show up in payloads.

##### openapi-generator version

`7.1.0-SNAPSHOT` from October 4

##### OpenAPI declaration file content or url

Relevant addition

```yaml
        nullable_floats:
          type: array
          items:
            type: number
            format: float
            nullable: true
```

Full gist [here](https://gist.github.com/jamestrousdale/7944a1fd46e4694c8264ca046c984247)

##### Generation Details

Here's the full command

```bash
java -jar /opt/aa/openapi/openapi-generator-cli.jar generate \
  --input-spec ./pet.yml \
  --generator-name python \
  --output /tmp/pet \
  --additional-properties packageName="petstore" \
  --additional-properties packageVersion="1.2.3" \
  --additional-properties projectName="petstore" \
  --additional-properties library=asyncio
```

##### Steps to reproduce

Generate the python (`pydantic` v2) client from the given spec

##### Related issues/PRs

I couldn't find anything that was a close or even similar match other than generic issues with `anyOf` that don't seem directly relevant.

##### Suggest a fix

I'm not familiar with Java or the templating engine, but it appears that the Python generator does not do enough introspection on array elements - I see it checks if the type is primitive, but doesn't seem to acknowledge the nullability.

Technically, the issue can sort of be bypassed by forcing an `anyOf` into the picture, by for example setting the type to `list[float | int | None]` in the Python code that generates the openAPI spec. The `anyOf` template handler seems to handle the nullability of array elements, I think.

**Comment by changhc** [comment]
Hello @wing328 and @multani, I would like to work on this issue. Can I assign this issue to myself? I have done some investigations and got a working solution at hand, but I need to understand a bit more why the code was written like that at the beginning as some refactoring might be needed.
