### ISSUE TITLE
[BUG][PYTHON] OpenAPI schema fields without nullable attribute lead to Optional type hints

### ISSUE THREAD

**Issue by BobMcFry** [OpenAPITools/openapi-generator#16747]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated Python clients use `Optional[...]` types even though there is not `nullable=true` constraint in the openapi schema.

This openapi extract
```json
[...]
  "Address": {
    "type": "object",
    "properties": {
      "street": {
        "type": "string",
        "example": "437 Lytton"
      },
      "city": {
        "type": "string",
        "example": "Palo Alto"
      },
      "state": {
        "type": "string",
        "example": "CA"
      },
      "zip": {
        "type": "string",
        "example": "94301"
      }
    },
    "xml": {
      "name": "address"
    }
  }
[...]
```
leads to this Python model
```python
class Address(BaseModel):
    """
    Address
    """
    street: Optional[StrictStr] = None
    city: Optional[StrictStr] = None
    state: Optional[StrictStr] = None
    zip: Optional[StrictStr] = None
```
which uses `Optional[StrictStr]` types instead of only `StrictStr`

##### openapi-generator version

[Docker v7.0.1](https://hub.docker.com/layers/openapitools/openapi-generator-cli/v7.0.1/images/sha256-1894bae95de139bd81b6fc2ba8d2e423a2bf1b0266518d175bd26218fe42a89b?context=explore) but also tested with `latest` and got the same results.

##### OpenAPI declaration file content or url
See extract in description or for a full file see the [petstore example](https://petstore3.swagger.io/api/v3/openapi.json).

##### Generation Details

See below.

##### Steps to reproduce

```bash
docker run --rm -v .:/local openapitools/openapi-generator-cli:v7.0.1 generate \
		-i https://petstore3.swagger.io/api/v3/openapi.json \
		-g python \
		-o /local \
		--additional-properties="generateSourceCodeOnly=true"
```

##### Related issues/PRs

Could not find any related issues or PRs.

##### Suggest a fix

I would expect the generator to not produce `Optional[...]` types if the nullable field is either not defined or set to false explicitly. Following the example from above, I would expect this to be generated:

```python
class Address(BaseModel):
    """
    Address
    """
    street: StrictStr
    city: StrictStr
    state: StrictStr
    zip: StrictStr
```

**Comment by jamestrousdale** [comment]
Try adding them to the `required` list inside the `Address` schema, i.e.

```json
[...]
  "Address": {
    "type": "object",
    "required": ["street", "city", "state", "zip"],
    "properties": {
      "street": {
        "type": "string",
        "example": "437 Lytton"
      },
      "city": {
        "type": "string",
        "example": "Palo Alto"
      },
      "state": {
        "type": "string",
        "example": "CA"
      },
      "zip": {
        "type": "string",
        "example": "94301"
      }
    },
    "xml": {
      "name": "address"
    }
  }
[...]
```

**Comment by BobMcFry** [comment]
Hi @jamestrousdale,

thanks for your quick response. I have altered the spec like you did and in fact it removes the Optional part of the type hint:

```python
class Address(BaseModel):
    """
    Address
    """
    street: StrictStr = Field(...)
    city: StrictStr = Field(...)
    state: StrictStr = Field(...)
    zip: StrictStr = Field(...)
    __properties = ["street", "city", "state", "zip"]
...
```

I totally missed the fact that a field is optional if the key is not specified as `required`.

I will close this issue then, thanks for your help!
