### ISSUE TITLE
[Swift][Question] What is the timeout of api requests and can you set it in Swift?

### ISSUE THREAD

**Issue by waterdrake** [OpenAPITools/openapi-generator#16755]
I use this generated code for Swift (with urlsession as library):

```
openAPI.myMethod() { (response, error) in
    guard error == nil else {
        print(error)
        return
    }

    if (response) {
        dump(response)
    }
}
```

It works but I think the timeout may be too low and I am getting a timeout error. 

I tried looking through the generated Swift code for anywhere that a timeout might be set but I can't find anything.

Does anyone know what the default timeout is of requests in Swift? And is it possible to set it to something higher?

**Comment by AMA-at-WD** [comment]
```Swift
let urlSessionConfiguration = URLSessionConfiguration.default
urlSessionConfiguration.timeoutIntervalForRequest = Self.timeoutIntervalForRequest
let urlSession = URLSession(configuration: urlSessionConfiguration)
let urlSessionTransportConfiguration = URLSessionTransport.Configuration(session: urlSession)
let urlSessionTransport = URLSessionTransport(configuration: urlSessionTransportConfiguration)
let client = Client(serverURL: yourServerURL, transport: urlSessionTransport, middlewares: yourMiddleWares)
```

**Comment by 4brunu** [comment]
To change the timeout you need to override the `URLSession` created here https://github.com/OpenAPITools/openapi-generator/blob/9147e998ff6244702185026a5bb86566de355e7d/samples/client/petstore/swift5/urlsessionLibrary/Sources/PetstoreClient/URLSessionImplementations.swift#L82
Here is an example of how to override URLSessionRequestBuilder
https://github.com/OpenAPITools/openapi-generator/blob/9147e998ff6244702185026a5bb86566de355e7d/samples/client/petstore/swift5/urlsessionLibrary/SwaggerClientTests/SwaggerClient/BearerDecodableRequestBuilder.swift#L12

https://github.com/OpenAPITools/openapi-generator/blob/9147e998ff6244702185026a5bb86566de355e7d/samples/client/petstore/swift5/urlsessionLibrary/SwaggerClientTests/SwaggerClient/BearerDecodableRequestBuilder.swift#L22

**Comment by 4brunu** [comment]
I'm closing this issue, as this was already answered, if this is still an issue, please reopen this issue.
Thanks
