### ISSUE TITLE
[BUG][csharp-netcore] Unkown base type

### ISSUE THREAD

**Issue by kYann** [OpenAPITools/openapi-generator#16795]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When generating client from schema, some type are "UNKOWN_BASE_TYPE" leading to compilation error.

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

https://gist.github.com/kYann/17c85748ea8e092e451228db040d1fc9

##### Generation Details

openapi-generator-cli generate -i http://localhost:5127/swagger/v1/swagger.json

##### Steps to reproduce

Generate client and try to compile

**Comment by wing328** [comment]
just merged a fix. please give it a try with the latest master (snapshot version available in the readme)
