### ISSUE TITLE
[BUG][CSHARP][GENERICHOST] Not support for multiple auth token

### ISSUE THREAD

**Issue by KRSogaard** [OpenAPITools/openapi-generator#16803]
The current implementation of the generic-host library for C# does not support authorization methods that require multiple auth tokens. I discovered this limitation while working on PR https://github.com/OpenAPITools/openapi-generator/pull/16801. In its current state, the library fails to compile if authorization involves more than one header containing a auth token. (That was was my PR was to fix). For instance, the Plaid OpenAPI specification uses both "PLAID-CLIENT-ID" and "PLAID-SECRET" headers. (https://raw.githubusercontent.com/plaid/plaid-openapi/master/2020-09-14.yml)

The code generated from this specification looks like:
```
apiKeyTokenLocalVar = (ApiKeyToken) await ApiKeyProvider.GetAsync("PLAID-CLIENT-ID", cancellationToken).ConfigureAwait(false);
tokenBaseLocalVars.Add(apiKeyTokenLocalVar);
apiKeyTokenLocalVar.UseInHeader(httpRequestMessageLocalVar, "PLAID-CLIENT-ID");

apiKeyTokenLocalVar = (ApiKeyToken) await ApiKeyProvider.GetAsync("PLAID-SECRET", cancellationToken).ConfigureAwait(false);
tokenBaseLocalVars.Add(apiKeyTokenLocalVar);
apiKeyTokenLocalVar.UseInHeader(httpRequestMessageLocalVar, "PLAID-SECRET");
```
In this setup, `ApiKeyProvider.GetAsync` merely reads from the list of available tokens by using `AvailableTokens.Reader.ReadAsync(cancellation).ConfigureAwait(false)`, but it fails to fetch the correct token value for the corresponding header.

There needs to be a mechanism to accurately retrieve the token associated with the requested header. Upon initial review, it appears that implementing this feature would necessitate a redesign of both the rate limiter and the storage mechanism for authentication tokens.

#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [X] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by wing328** [comment]
@KRSogaard thanks for reporting the issue.

cc @devhl-labs
