### ISSUE TITLE
[BUG][JAVA] java.util.Scanner used in ApiClient.java does not have character encoding set and thus uses JVM default encoding

### ISSUE THREAD

**Issue by wojciechkl** [OpenAPITools/openapi-generator#16818]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Scanner used for response stream reading uses JVM default encoding (does not have second parameter "charsetName" provided - https://docs.oracle.com/javase/8/docs/api/java/util/Scanner.html#Scanner-java.nio.file.Path-java.lang.String-).

https://github.com/OpenAPITools/openapi-generator/blob/ba367e60e85392a7fd58cdb374c35c3aaaece872/modules/openapi-generator/src/main/resources/Java/libraries/apache-httpclient/ApiClient.mustache#L840

In my case this makes generated code unusable because API provider (who controls yaml with spec) uses diaciritics in some params. And those params are changed by OpenApi into enums. And when data, with those params, is actually returned from REST end point the encoding does not match and I get java.lang.IllegalArgumentException Exception - Unexpected value '...' in fromValue method.

##### openapi-generator version

7.0.1

##### Suggest a fix

I can provide a patch here, but first I would like to discuss which should be preffered way of solving this - forcing "UTF-8" encoding (which works for me) or providing new parameter that would allow to choose encoding.

**Comment by youngInnovator** [comment]
I will suggest to use parameter and if parameter is null use default as UTF-8

**Comment by wing328** [comment]
> or providing new parameter that would allow to choose encoding.

What about adding a property in ApiClient.java (default to current behaviour) to let users choose?

**Comment by AB-xdev** [comment]
I think a way easier fix would be to use [``EntityUtils#toString``](https://javadoc.io/doc/org.apache.httpcomponents.core5/httpcore5/5.2.4/org/apache/hc/core5/http/io/entity/EntityUtils.html#toString-org.apache.hc.core5.http.HttpEntity-) as it automatically derives the charset from the content type.

**Comment by AB-xdev** [comment]
I quickly created a PR that should fix this: #17998
