### ISSUE TITLE
[BUG][GO] Generated client does not treat all media types with the suffix `+json` as JSON or `+xml` as XML

### ISSUE THREAD

**Issue by joshraker** [OpenAPITools/openapi-generator#16811]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm creating a spec for an `application/hal+json` API but the resulting Go client raises an "undefined response type" error for every operation because it only treats responses with a `Content-Type` that conforms to `application/vnd.*+json` as JSON. Hence, `application/hal+json` is considered an "unknown" content type.

My understanding of [RFC 6838](https://datatracker.ietf.org/doc/html/rfc6838#section-4.2.8), which the [OpenAPI docs](https://swagger.io/docs/specification/media-types/#names) say is the source of truth for supported media types, is that any media type with a `+suffix` should conform to the suffix type. By that logic, I expect the client to treat any media type with the suffix `+json` as JSON and `+xml` as XML. I'm not using XML but it only supports `application/xml` so may as well update it while touching the JSON regular expression.

Assuming my understanding isn't flawed the fix is a fairly simple change to two regular expressions that I'll open a PR for but starting with an issue per the contribution guidelines. Happy to provide additional details upon request but given the simplicity of the issue they seem unnecessary.

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/blob/2cfce7cd2d54f42f0d64bc96c87829a2f99f58ce/modules/openapi-generator/src/main/resources/go/client.mustache#L36-L37

Would be updated to

```golang
jsonCheck = regexp.MustCompile(`(?i:(?:application|text)/(?:[^;]+\+)?json)`) 
xmlCheck  = regexp.MustCompile(`(?i:(?:application|text)/(?:[^;]+\+)?xml)`) 
```

**Comment by wing328** [comment]
@joshraker thanks for reporting the issue. Can you please file a PR with the suggested fix?
