### ISSUE TITLE
[BUG] [CSHARP] GenericHost Generator does not generate BearerToken class

### ISSUE THREAD

**Issue by sqz269** [OpenAPITools/openapi-generator#16825]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I tried to generate a GenericHost client with specs provided below the resulting client does not contain a class called `BearerToken` but generated code references `TokenProvider<BearerToken>` making the generated code fail to compile.

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

https://api-music.marisad.me/swagger/playlist/v1/swagger.json

##### Generation Details

```openapi-generator-cli.cmd generate -i https://api-music.marisad.me/swagger/playlist/v1/swagger.json -g csharp --additional-properties=library=generichost```

##### Steps to reproduce

1. Run the generator command with arguments ` -g csharp --additional-properties=library=generichost`
2. Observe that the generated client does not contain the filed `BearerToken` but is referenced in api calls and the schema have a security definition for HTTP Bearer and code does not compile due to missing class.

**Comment by devhl-labs** [comment]
I'll check it out.

**Comment by sqz269** [comment]
@devhl-labs Any updates on this?

**Comment by devhl-labs** [comment]
Sorry, no. Focus is currently on the pr for better null/required support. I'll get to this shortly after.
