### ISSUE TITLE
[BUG][Rust] Array with unique enum items causes mismatched types error

### ISSUE THREAD

**Issue by SAIA-Basseldonk** [OpenAPITools/openapi-generator#16849]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Components containing arrays of unique enum items are converted to models where the property is typed as a `std::collections::HashSet<T>` in the struct, but typed as a `Vec<T>` in the constructor arguments, resulting in `error[E0308]: mismatched types` during the build process.

###### Current output

```Rust
pub struct Foo {
    #[serde(rename = "bar")]
    pub bar: std::collections::HashSet<Bar>,
}

impl Foo {
    pub fn new(bar: Vec<Bar>) -> Foo {
        Foo {
            bar,
        }
    }
}
```

###### Expected output
Arguments should be typed as `std::collections::HashSet<T>` as well to match the generated struct.

```Rust
pub struct Foo {
    #[serde(rename = "bar")]
    pub bar: std::collections::HashSet<Bar>,
}

impl Foo {
    pub fn new(bar: std::collections::HashSet<Bar>) -> Foo {
        Foo {
            bar,
        }
    }
}
```

##### openapi-generator version

7.0.1

##### OpenAPI declaration file content or url

```yaml
# minimal_example.yaml

openapi: 3.0.3

info: 
  version: 1.0.0
  title: Unique Items Array

paths:
  /foo:
    get:
      description: Returns an array with unique items
      responses: 
        '200':
          description: Array with unique items
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/foo'

components:
  schemas:
    foo:
      type: object
      required:
        - bar
      properties: 
        bar:
          type: array
          description: An array containing unique items
          uniqueItems: true
          example: 
            - 1
            - 2
            - 3
          items:
            type: integer
            enum:
              - 1
              - 2
              - 3
            example: 1
```

##### Generation Details

```yaml
generatorName: rust
outputDir: generated/rust
library: reqwest
inputSpec: minimal_example.yaml
templateDir: modules/openapi-generator/src/main/resources/rust
additionalProperties:
  supportAsync: false
  packageName: openapi
```

##### Steps to reproduce
```sh
openapi-generator-cli generate -g rust -i minimal_example.yaml -o generated/rust

cd generated/rust
cargo build
```

##### Related issues/PRs
Possibly introduced in https://github.com/OpenAPITools/openapi-generator/pull/8693

##### Suggest a fix
Template file for rust models, modules/openapi-generator/src/main/resources/rust/model.mustache, should be updated so not only struct vars are checked for `{{#uniqueItems}}`, but also arguments in `pub fn new`.

```
pub fn new({{#requiredVars}}{{{name}}}: {{#isNullable}}Option<{{/isNullable}}{{#isEnum}}{{{enumName}}}{{/isEnum}}{{^isEnum}}{{{dataType}}}{{/isEnum}}{{#isNullable}}>{{/isNullable}}{{^-last}}, {{/-last}}{{/requiredVars}}) ->
```
Should become

```
pub fn new({{#requiredVars}}{{{name}}}: {{#isNullable}}Option<{{/isNullable}}{{#isEnum}}{{#isArray}}{{#uniqueItems}}std::collections::HashSet<{{/uniqueItems}}{{^uniqueItems}}Vec<{{/uniqueItems}}{{/isArray}}{{{enumName}}}{{#isArray}}>{{/isArray}}{{/isEnum}}{{^isEnum}}{{{dataType}}}{{/isEnum}}{{#isNullable}}>{{/isNullable}}{{^-last}}, {{/-last}}{{/requiredVars}}) -> {{{classname}}} {
```

**Comment by wing328** [comment]
can you please file a PR with the suggested fix when you've time?
