### ISSUE TITLE
Passwords should be excluded from `toString`

### ISSUE THREAD

**Issue by mgrafl** [OpenAPITools/openapi-generator#16851]
For the Java Spring generator (and potentially others), the generated `toString` method includes all properties: https://github.com/OpenAPITools/openapi-generator/blob/d6421411c91af2dd3820b4a85cbfc1c4eb2c84ce/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache#L289

The properties may include sensitive information, such as passwords. 
Since the `toString` method is primarily used for logging purposes, sensitive information should be redacted (see also [CWE-532](https://cwe.mitre.org/data/definitions/532.html)). 

The OpenAPI specification already has the modifier property called `format`, that can be set to `password` as a hint that a field contains sensitive information (see https://spec.openapis.org/oas/v3.1.0#data-types). 

### Proposed mitigation: 
* The generator(s) should honor this hint in the generated `toString` method and skip (or redact) fields that are marked as `format: password`. 

### Compatibility considerations: 
* Since the `toString` method includes the class name before the opening curly brackets, there is no risk that developers might mistakenly use the `toString` method for JSON serialization. 

### Related issues:
* #14156 requests an enhancement feature for customizing and/or skipping `toString` method generation. 
Even though such a more flexible vendor extension could achieve the same goal, the secure default should be to always exclude sensitive information from the `toString` method.

**Comment by dabdirb** [comment]
the better solution is not exclude password field from toString() method, replace password as another string, such as "***" or "[MASKED]".

**Comment by wing328** [comment]
closed via #16942
