### ISSUE TITLE
[REQ] Request to Update ktor-client Version to 2.3.5 for Custom Plugin Support

### ISSUE THREAD

**Issue by mtriston** [OpenAPITools/openapi-generator#16867]
### Is your feature request related to a problem? Please describe.

The current version (2.1.2) of `ktor-client` lacks support for custom plugins. This limitation hinders the flexibility and functionality of the generated clients. Ktor has introduced custom plugin support from version `2.2.x` onwards.
https://ktor.io/docs/client-custom-plugins.html

## Describe the solution you'd like

I propose updating the `ktor-client` version to at least `2.2.0`, or ideally to the latest version `2.3.5`. This update would enable custom plugin support, aligning with the latest enhancements offered by Ktor, and potentially bringing various optimizations and bug fixes from the newer versions of `ktor-client`.

**Comment by wing328** [comment]
can you please submit a PR to update ktor-client to newer version?

**Comment by mtriston** [comment]
> can you please submit a PR to update ktor-client to newer version?

https://github.com/OpenAPITools/openapi-generator/pull/16869
