### ISSUE TITLE
[BUG] python client using deprecated allow_population_by_field_name

### ISSUE THREAD

**Issue by PaulSut** [OpenAPITools/openapi-generator#16878]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

According to this Migration Guide allow_population_by_field_name is deprecated and should be replaced by populate_by_name.

This caused the generated api to have some unexpected behavior, which could be fixed by adjusting this in my client.

##### Steps to reproduce

create a python client

##### Suggest a fix

Unfortunately I won't be free for quite a while to have a look into how openapi-generator is actually working. But maybe just [replacing this everywhere](https://github.com/OpenAPITools/openapi-generator/pull/16877) is already enough?

**Comment by fa0311** [comment]
Already fixed in #16685.
