### ISSUE TITLE
[BUG]  Python-pydantic-v1 is in the generator list, but python-pydantic-v1 is not in openapi-generator-cli 7.0.1

### ISSUE THREAD

**Issue by jintao-ng** [OpenAPITools/openapi-generator#16888]
#### Bug Report Checklist

![image](https://github.com/OpenAPITools/openapi-generator/assets/107451877/56e089b6-bcfa-48d9-b5dd-47e7d0a79720)

![image](https://github.com/OpenAPITools/openapi-generator/assets/107451877/5cf6a9e6-02fb-43f2-b649-03405a08de75)

![290a8681-4fa5-438c-83a2-d56e19488a5c](https://github.com/OpenAPITools/openapi-generator/assets/107451877/bafdd2a1-b24a-4043-b173-973ab1487a8e)

**Comment by wing328** [comment]
the website doc refers to the latest master

you can use the `python` generator in v7.0.1 for the time being as that one generates code with pydantic v1

in the upcoming v7.1.0 release, the python client generator will leverage pydantic v2 instead.
