### ISSUE TITLE
[BUG] Java Resttemplate with jakartaEE generates deprecated Code

### ISSUE THREAD

**Issue by limdul79** [OpenAPITools/openapi-generator#16889]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
If you generate a Java Client with Resttemplate als library, the following two files generated:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/pom.mustache

In the pom, if you activate JakartaEE, the spring web version is set (as of today, 23.10.2023) to 6.0.3
In the ApiClient.java, in logResponse the following Code is generated - regardless of the jarkataEE Option:

`        private void logResponse(ClientHttpResponse response) throws IOException {
            log.info("HTTP Status Code: " + response.getRawStatusCode());
            log.info("Status Text: " + response.getStatusText());
            log.info("HTTP Headers: " + headersToString(response.getHeaders()));
            log.info("Response Body: " + bodyToString(response.getBody()));
        }
`
The problem is, that response.getRawStatusCode() is deprecated since Spring 6. Instead response.getStatusCode().value() should be used.

**Comment by dabdirb** [comment]
This is not a bug, please refer doc https://openapi-generator.tech/docs/generators/java
```
resttemplate
    HTTP client: Spring RestTemplate 4.x. JSON processing: Jackson 2.9.x
```
openapi generator did not formally announce it support spring boot 3 client, it should be a new feature request.

**Comment by maxl2287** [comment]
Hello @dabdirb,

I guess that @limdul79 is more referencing into updating the ApiClient.mustache file to just use 

```
response.getStatusCode().value() 
```
here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L907

I mean yes, it's not a bug, but it can be fixed for next version, if @limdul79 provides a PR-fix?

**Comment by dabdirb** [comment]
simple change, created a PR #17405 to fix it
