### ISSUE TITLE
[REQ] Support new RestClient for spring 6.1 clients

### ISSUE THREAD

**Issue by jbkervyn** [OpenAPITools/openapi-generator#16902]
The upcoming spring framework 6.1 (planned release date on November 15th, 2023) comes with a new RestClient (next to other 2 spring alternatives : RestTemplates & webclient).

It would make sense to support it as well.

Details can be found here :https://spring.io/blog/2023/07/13/new-in-spring-6-1-restclient

**Comment by straurob** [comment]
Here is the JavaDoc for Spring's new `RestClient` interface:
https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestClient.html

**Comment by rfelgent** [comment]
I try to provide an MR

**Comment by twonky4** [comment]
Docu says RestClient support is in the java generator with library RestClient.

**Comment by ppa-fyayc** [comment]
Was merged as part of https://github.com/OpenAPITools/openapi-generator/issues/17571
