### ISSUE TITLE
[REQ] [Rust] set default edition to 2021

### ISSUE THREAD

**Issue by KisaragiEffective** [OpenAPITools/openapi-generator#16925]
### Is your feature request related to a problem? Please describe.

The current edition seems to be 2018, but today's (1.56.0 or later) compiler supports edition 2021:

https://github.com/OpenAPITools/openapi-generator/blob/fbd02554f5aca52b5a9ed83d63ef5230aebb51f5/modules/openapi-generator/src/main/resources/rust/Cargo.mustache#L20

## Describe the solution you'd like

```diff
- edition = "2018"
+ edition = "2021"
```

## Describe alternatives you've considered

N/A

## Additional context
N/A

**Comment by wing328** [comment]
can you please file a PR with the suggested change?

**Comment by ross-paypay** [comment]
this was handled in https://github.com/OpenAPITools/openapi-generator/pull/18608

**Comment by KisaragiEffective** [comment]
I'm going to close this.
