### ISSUE TITLE
[BUG][Java] generator creates inconsistent class name and class file name

### ISSUE THREAD

**Issue by hebra** [OpenAPITools/openapi-generator#1692]
##### Description
Trying to generate a Java client from the [Vimeo OpenAPI spec](https://github.com/vimeo/openapi).
Using the openapi gradle plugin 3.3.4 with the generator 'java with any of it libraries (jersey1, jersey2, feign etc.) generates a class where the file name and the class name are inconsistent in regards to letter cases, leading to java compilation errors.

##### openapi-generator version
3.3.4

##### OpenAPI declaration file content or url
config.json
```
{
	"generatorName": "java",
	"library": "feign",
	"groupId": "com.vimeo",
	"modelPackage": "com.vimeo.model",
	"apiPackage": "com.vimeo.api",
	"invokerPackage": "com.vimeo",
	"basePackage": "com.vimeo",
	"dateLibrary": "java8",
	"java8": true,
	"async": true,
	"responseWrapper": "ListenableFuture",
	"useBeanValidation": true
}
```

build.gradle snippet
```
buildscript {
  repositories {
    mavenCentral()
  }
  dependencies {
    classpath "org.openapitools:openapi-generator-gradle-plugin:3.3.4"
  }
}

apply plugin: 'org.openapi.generator'

openApiGenerate {
	validateSpec = true
    configFile = "$rootDir/vimeo/config.json".toString()
    inputSpec = "$rootDir/vimeo/openapi/api.yaml".toString()
    outputDir = "$buildDir/generated".toString()
}
```

##### Command line used for generation

As the OpenAPI generator Gradle plugin is used the command line looks lile
```
./gradlew clean openApiGenerate
```

##### Steps to reproduce
- create a new Spring Boot project (e.g. by using https://start.spring.io/)
- download the api.yaml from above mentioned Vimeo GitHub repo
- adjust the build.gradle to include above additions for the OpenAPI plugin
- run via ```./gradlew clean openApiGenerate```

#### Results to check
- after generating open the file ```build/generated/src/main/java/com/vimeo/model/MeVideosPrivacy.java```
- as you can see from the file name it is ```MeVideosPrivacy``` with a capital V and P, but inside the file the class name is 'MevideoPrivacy', with a lower-case v but again an uppercase P
- some other class files are referencing the class as ```MeVideosPrivacy``` (like ```model/MeVideos.java```) where others use ```MevideosPrivacy``` (like ```model/InlineObject53.java```

##### Related issues/PRs
Kind of related is #1691

##### Suggest a fix
I am actually not sure if this is an issue with the Vimeo spec or the OpenAPI generator, as even the naming inconsistency is inconsistent across different files

**Comment by hebra** [comment]
After fixing #1691 I was able to verify that the issue is also present for the Spring-flavours of generated Java code, making this a basic issue across all the Java generators.

**Comment by hebra** [comment]
It looks like the issue is fixed on the latest code on master.

**Comment by wing328** [comment]
@hebra thanks for confirming the issue has been addressed in the latest master.

**Comment by manjulapasala** [comment]
[Spring] generator creates inconsistent class name and class file name and not escaping backslashes in paths
we are getting below error while running ./gradlew clean openApiGenerate(openapi-generator-gradle-plugin version : 4.3.1)
#/components/schemas/~1a~1{b} is not defined
#/components/schemas/~1a~1{b} is not defined
#/components/schemas/~1a~1{b} is not defined
~1a~1{b} (model name starts with number) cannot be used as model name. Renamed to Model1a1b
