### ISSUE TITLE
Multiple AdditionalProperties dont work with CLI v2.7.0

### ISSUE THREAD

**Issue by DanTurco** [OpenAPITools/openapi-generator#16938]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When running command

```
openapi-generator-cli generate -i C:\dev\cbx-client\projects\temp\swagger.json -g typescript-angular -o C:\dev\client\projects\clientapi-swagger-client\src --skip-validate-spec --additional-properties=withInterfaces=true,apiModulePrefix=Client
```

Get error
[error] Found unexpected parameters: [apiModulePrefix=Client]

Seems it only allows 1 additional parameters to be provided, what ever the next set of values are after the first comma show up in the error. This command was based on the help files https://openapi-generator.tech/docs/usage#examples

##### openapi-generator version

2.7.0

**Comment by wing328** [comment]
what about using git bash instead?

the following works fine for me:

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g typescript-angular -i https://gist.githubusercontent.com/aeneasr/c201992378c87943dfdbe559adc32bae/raw/bdd23b17707b67c55b0ca7a3e128b198f5bbf0f3/openapi.json --skip-validate-spec --additional-properties=withInterfaces=true,apiModulePrefix=Client
```
