### ISSUE TITLE
[BUG] [Go] MarshalJSON is extremely slow. (Performance Issue)

### ISSUE THREAD

**Issue by kokoichi206** [OpenAPITools/openapi-generator#16948]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

It might not be appropriate to raise this as a bug report.

json.Marshal of the generated struct was extremely slow (5-10x).

I guess that the cause lies in the part of the MarshalJSON method for the struct generation, where it's converting to a map of string and interface.
I couldn't understand the reason for processing every field in this manner.

I'd appreciate it if you could explain the reason for this kind of generation and, if possible, let me know how to avoid it during the generation process.

##### openapi-generator version

openapi-generator-cli:v7.0.0
(v5.1.1 also reproduced)

##### OpenAPI declaration file content or url

I used the [petstore example from OpenAPI-Specification](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/examples/v3.0/petstore.yaml)

##### Generation Details

I used docker of the cli.

``` sh
docker run --rm -v $(shell pwd):/project openapitools/openapi-generator-cli:v7.0.0 \
	generate -i /project/openapi.yaml -g go \
	--additional-properties=packageName=component -o /project/gen/component -p enumClassPrefix=true
```

`.openapi-generator-ignore`

``` 
api_*
client.go
configuration.go
.travis.yml

README.md
git_push.sh

go.mod
go.sum

api/
docs/
```

##### Steps to reproduce

1. Generate code for 2 packages using the "Generation Details" docker and [petstore example](https://github.com/OAI/OpenAPI-Specification/blob/78170608af208da8165ab095715e5cb9ff715f47/examples/v3.0/petstore.yaml).
2. Leave one generated as is, with the package name "component_method".
3. Rename the other one to the package name "component" and remove MarshalJSON and UnmarshalJSON from the generated code.
4. Do Benchmark tests for `json.Marshal` and `json.Unmarshal`.
5. `json.Marshal` of "component_method" is 6x slower than "component"

test results

``` sh
$ go test -bench .
goos: darwin
goarch: arm64
pkg: benchmark
BenchmarkJsonUnMarshal-8                 1225986               987.5 ns/op
BenchmarkJsonUnMarshalMethod-8           1229346               977.5 ns/op
BenchmarkJsonMarshal-8                   7769258               153.6 ns/op
BenchmarkJsonMarshalMethod-8             1256686               956.0 ns/op
PASS
ok      benchmark       8.116s
```

The benchmark test code

``` go
package main

import (
	"benchmark/gen/component"
	"benchmark/gen/component_method"
	"encoding/json"
	"os"
	"testing"
)

func BenchmarkJsonUnMarshal(b *testing.B) {
	bytes, _ := os.ReadFile("res.json")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var res component.Pet
		json.Unmarshal(bytes, &res)
	}
}

func BenchmarkJsonUnMarshalMethod(b *testing.B) {
	bytes, _ := os.ReadFile("res.json")

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		var res component_method.Pet
		json.Unmarshal(bytes, &res)
	}
}

func BenchmarkJsonMarshal(b *testing.B) {
	bytes, _ := os.ReadFile("res.json")
	var res component.Pet
	json.Unmarshal(bytes, &res)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = json.Marshal(res)
	}
}

func BenchmarkJsonMarshalMethod(b *testing.B) {
	bytes, _ := os.ReadFile("res.json")
	var res component_method.Pet
	json.Unmarshal(bytes, &res)

	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_, _ = json.Marshal(res)
	}
}
```

`res.json`

``` json
{
    "id": 111,
    "name": "Test name 111",
    "tag": [
        "test tag",
        "kawaii"
    ]
}
```

supplement

- This behavior also reproduced for larger json, struct
- json.Unmarshal is not slow

**Comment by wing328** [comment]
@kokoichi206 thanks for brining it up and the benchmark result.

If I remember correctly, the customized MarshalJSON method was added to meet the requirement of different use cases (e.g. oneOf/anyOf schema in properties, additional properties, nullable properties, etc)

For your use cases, if these are not needed, what about adding an option to skip generating the MarshalJSON method? Would that help?

**Comment by wing328** [comment]
FYI @antihax (2017/11) @grokify (2018/07) @kemokemo (2018/09) @jirikuncar (2021/01) @ph4r5h4d (2021/04) @lwj5 (2023/04)

**Comment by kokoichi206** [comment]
@wing328 
Thank you for your reply.

Having an option to skip generating the MarshalJSON method would be a welcome addition for our use case.
If it's acceptable, I would also be interested in trying to implement this feature myself.

**Comment by wing328** [comment]
> If it's acceptable, I would also be interested in trying to implement this feature myself.

yes please. let me know if you need help with the PR.

**Comment by wing328** [comment]
closing this as the PR has been merged.

happy to reopen if needed.
