### ISSUE TITLE
[BUG] `parameters_to_url_query` returns booleans with upper letter

### ISSUE THREAD

**Issue by mhaley-tignis** [OpenAPITools/openapi-generator#16941]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The `parameters_to_url_query` function incorrectly produces `True` and `False` for boolean values. This piece of code in the api_client template is responsible:
https://github.com/OpenAPITools/openapi-generator/blob/08d518319ee722f4b5874be7516acd293008fbe3/modules/openapi-generator/src/main/resources/python/api_client.mustache#L484-L487

In python `isinstance(True, int) == True` :) 

##### openapi-generator version

v7.0.1

##### OpenAPI declaration file content or url

N/A

##### Generation Details

N/A

##### Steps to reproduce

N/A

##### Suggest a fix

Swap the order of the checks to first check for booleans:
```
            if isinstance(v, bool):
                v = str(v).lower()
            if isinstance(v, (int, float)):
                v = str(v)
```

**Comment by robertschweizer** [comment]
This can be closed since https://github.com/OpenAPITools/openapi-generator/pull/16947 was merged.
