### ISSUE TITLE
[BUG][RUST][CLIENT] Generated enum type used with `format!` but it doesn't impl `Display`

### ISSUE THREAD

**Issue by eliaperantoni** [OpenAPITools/openapi-generator#16975]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If an endpoint uses an enum as the path parameter, and the enum is defined in `components` rather than inline, then the generated `default_api.rs` creates the URL with the `format!` macro but the generated Rust enum doesn't implement `Display` (it does implement `ToString` instead).

```
error[E0277]: `Color` doesn't implement `std::fmt::Display`
  --> src/apis/default_api.rs:31:97
   |
31 |     let local_var_uri_str = format!("{}/demo/{color}", local_var_configuration.base_path, color=color);
   |                                                                                                 ^^^^^ `Color` cannot be formatted with the default formatter
   |
   = help: the trait `std::fmt::Display` is not implemented for `Color`
   = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
   = note: this error originates in the macro `$crate::__export::format_args` which comes from the expansion of the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
```

NOTE: You need to reference the enum like:

```
schema:
  allOf:
    - $ref: "#/components/schemas/Color"
```

otherwise you're going to run into issue #16974 first.

##### openapi-generator version

I'm using the Docker `openapitools/openapi-generator-cli:latest` image. `openapi-generator-cli version` prints `7.1.0-SNAPSHOT`.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Demo
  version: 0.0.0
paths:
  /demo/{color}:
    get:
      parameters:
        - name: color
          required: true
          in: path
          schema:
            $ref: "#/components/schemas/Color"
      responses:
        200:
          description: OK
components:
  schemas:
    Color:
      type: string
      enum:
        - RED
        - GREEN
        - BLUE
```

##### Generation Details

```shell
$ openapi-generator generate -i openapi.yaml -g rust -o demo
```

**Comment by wing328** [comment]
> NOTE: You need to reference the enum like:

I've filed https://github.com/OpenAPITools/openapi-generator/pull/17694 to fix the issue
