### ISSUE TITLE
Update base image of Dockerfile

### ISSUE THREAD

**Issue by litetex** [OpenAPITools/openapi-generator#17000]
##### Description

The [Dockerfile](https://github.com/OpenAPITools/openapi-generator/blob/master/Dockerfile) currently uses ``maven:3.6.3-jdk-11-openj9``.
This version is highly outdated (released ~4 years ago) and should be updated.

##### Suggest a fix/enhancement

Update to a newer version.

I would recommend [``3-eclipse-temurin-21``](https://hub.docker.com/_/maven/tags?name=3-eclipse-temurin-21):
* ``3`` will ensure that it's always the latest Maven 3 version
* ``eclipse-temurin`` is likely the most umodified jdk with the largest support available
* ``21`` is the latest LTS java version

**Comment by wing328** [comment]
can you please file a PR to start with?

**Comment by litetex** [comment]
Okay so I updated the Dockerfile (see linked PR) but apparently there are some problems and I have some questions:
1. Why is maven running in interactive mode inside the container? (No ``-B`` flag set) This spams the log full with download progress... Not sure how anyone is currently able reading logs e.g. [on GitHub actions](https://github.com/OpenAPITools/openapi-generator/actions/runs/6780298788/job/18428751284)... 
![grafik](https://github.com/OpenAPITools/openapi-generator/assets/40789489/5e6a4ad0-c859-4826-b39d-e0f8b021f866)
Is there any reasoning behind this?
2. I also updated the Dockerimage inside ``run-in-docker.sh``
   a. TLS communication is somehow downgraded to TLSv1.2 inside [``run-in-docker.sh``](https://github.com/OpenAPITools/openapi-generator/blob/ced96601234cdff535e37d1ac508e7890d69ed43/run-in-docker.sh#L18)?
  b. Currently I can't compile anything as Gradle Enterprise [throws on initialization of maven ``java.nio.file.AccessDeniedException: /.m2``](https://github.com/litetex/openapi-generator/actions/workflows/docker.yaml?query=branch%3Aupdate-docker-image). Is it somehow possible to change this directory (it looks like it's currently trying to use the user directory which is not present so it defaults ``/`` and the permission therefore are wrong)? The source code is not available so I have no idea what's happening there...
3. While inspecting ``docker-entrypoint.sh`` I found this line:
https://github.com/OpenAPITools/openapi-generator/blob/ced96601234cdff535e37d1ac508e7890d69ed43/docker-entrypoint.sh#L7 Why is the memory capped to 1GB inside a container? You can and should control the container memory and not the one of the JVM. Some guides [here](https://www.baeldung.com/ops/docker-jvm-heap-size) and [here](https://dzone.com/articles/best-practices-java-memory-arguments-for-container). Is there any reason behind this?

I will have a look at this again tomorrow or in a few days

**Comment by wing328** [comment]
Thanks for the PR.

For 1, please feel free to add the -B flag

For 2a, no idea

For 2b, need to check

For 3, no idea. Don't recall why `-Xmx1024M` was added to the options.

(I'm not the one who created this file)

I saw [another issue](https://github.com/OpenAPITools/openapi-generator/issues/16951#issuecomment-1798234783) related to JDK21. Maybe we should use JDK17 for the time being.

**Comment by litetex** [comment]
Java 17 seems to works so I'm moving to that. 

Still seeing lots of problems like unviewable logs but I wont address these here as they are unrelated.

PR can be reviewed now :)
