### ISSUE TITLE
Powershell client has wrong apikey header name

### ISSUE THREAD

**Issue by elonmallin** [OpenAPITools/openapi-generator#17005]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The Powershell client gets the wrong name for the apikey when generated with the below spec.

##### openapi-generator version

7.1.0-SNAPSHOT (running it with latest docker image)

##### OpenAPI declaration file content or url

```yaml
swagger: '2.0'
info:
  title: Test API
  version: 1.0.0
host: test.com
paths:
  "/accounts":
    get:
      summary: Get a list of AccountResources
      produces:
      - application/json
      responses:
        '200':
          description: Success
securityDefinitions:
  APIKeyHeader:
    type: apiKey
    name: X-ApiKey
    in: header
security:
- APIKeyHeader: []
```

##### Generation Details

`docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/swagger.yaml -g powershell -o /local --package-name Bug`

##### Steps to reproduce

1. `docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/swagger.yaml -g powershell -o /local --package-name Bug`
2. Remove `'Model', ` from `$FunctionPath = 'Api', 'Client' | ForEach-Object {Join-Path "$ScriptDir\src\Bug\" $_}` in `Build.ps1` since ther is no models and will fail to build (this is another bug it seems)
3. Remove `'Model', ` from `'Api', 'Client', 'Private' | Get-ChildItem -Path {` in `Bug.psm1` since there is no models and will fail to import module otherwise (this is related to the bug in the previous step)
4. `Import-Module -Name ".\src\Bug" -Prefix Bug`
5. `Set-BugConfigurationApiKey -Id "X-ApiKey" -ApiKey "mykey"`
6. `Set-BugConfigurationApiKey -Id "APIKeyHeader" -ApiKey "mykey"`
7. `Invoke-BugAccountsGet -Debug`
8. See debug message for header parameters is wrong `DEBUG: HeaderParameters {[APIKeyHeader, mykey]}`

So `X-ApiKey` was never added to our request setting the config like we did. And setting the config with id `APIKeyHeader` added a header but but with the wrong name.

###### Expected outcome

Setting either the api key config for `APIKeyHeader` or `X-ApiKey` should add a header with name `X-ApiKey` and value `mykey`.

##### Related issues/PRs

Could only find 3 issues with label powershell and none of them were mentioning this.

##### Suggest a fix

The problem seems to be that this code `$LocalVarHeaderParameters['APIKeyHeader'] = $Configuration["ApiKey"]["APIKeyHeader"]` in `src/Bug/Api/DefaultApi.ps1` has `$LocalVarHeaderParameters['APIKeyHeader']` but should have `$LocalVarHeaderParameters['X-ApiKey']`.

The solution I think might be to update [this line](https://github.com/OpenAPITools/openapi-generator/blob/d9454990739121af81dccb14e5136089356b47e5/modules/openapi-generator/src/main/resources/powershell/api.mustache#L182C1-L182C1) to `$LocalVarHeaderParameters['{{{keyParamName}}}'] = $Configuration["ApiKey"]["{{{name}}}"]` instead of `$LocalVarHeaderParameters['{{{name}}}'] = $Configuration["ApiKey"]["{{{name}}}"]`.

I'm not too sure how the generation works but I saw in the docs generation that it used the `keyParamName` which ends up being `X-ApiKey` so if it works there it might work in the api generation as well.

**Comment by wing328** [comment]
can you please file a PR with the suggestion fix?
