### ISSUE TITLE
[BUG] python-aiohttp broken by a new dependency release

### ISSUE THREAD

**Issue by ajoga** [OpenAPITools/openapi-generator#17013]
##### Description

python-aiohttp's `requirements.txt` has `connexion[aiohttp,swagger-ui] >= 2.6.0` as dependency ; 

The recent major release 3 dropped aiohttp support:

> Aiohttp support has been dropped due to lack of ASGI support

-- https://connexion.readthedocs.io/en/3.0.1/v3.html

Current generated examples can't be installed/ran.

##### Suggest a fix

I suggest modifying this line to limit the `connexion` version used to the 2.x branch:

https://github.com/OpenAPITools/openapi-generator/blob/f35b13206832b59caee93835e5e101b76abfda88/modules/openapi-generator/src/main/resources/python-aiohttp/requirements.mustache#L1

Something like:

```
connexion[aiohttp,swagger-ui] >= 2.6.0, <3; python_version>="3.6"
```

**Comment by wing328** [comment]
can you please file a PR with the suggested fix? thanks
