### ISSUE TITLE
[BUG] `allOf` with single `$ref` element implementation doesn't respect sibling properties like `deprecated` etc.

### ISSUE THREAD

**Issue by pinalbaldha** [OpenAPITools/openapi-generator#17048]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
`allOf` can have sibling json properties like `deprecated`, `readOnly`, `nuallable` etc.
`allOf` with single`$ref` is treated differently: https://github.com/OpenAPITools/openapi-generator/pull/16096
`allOf` with single `$ref` doesn't respect sibling property behaviour. 
Whereas `allOf` with more than one `$ref` respects sibling properties.

OpenAPI spec with `allOf` & single `$ref`:
```
"components":{
  "schemas": {
    "AssetFrame": {
      "type": "object",
      "properties": {
        "test": {
          "type": "string",
          "deprecated": true
        },
        "machineDetails": {
          "deprecated": true,
          "allOf": [
            {
              "$ref": "#/components/schemas/MachineDetails"
            }
          ]
        }
      }
    }
  }
}
```

Generates below java code:
Snippet of AssetFrame.java

```
  @SerializedName(SERIALIZED_NAME_MACHINE_DETAILS)
  private AssetFrameMachineDetails machineDetails;
```

OpenAPI spec with `allOf` & more man one `$ref`
```
"components":{
  "schemas": {
    "AssetFrame": {
      "type": "object",
      "properties": {
        "test": {
          "type": "string",
          "deprecated": true
        },
        "machineDetails": {
          "deprecated": true,
          "allOf": [
            {
              "$ref": "#/components/schemas/MachineDetails"
            },
            {
              "$ref": "#/components/schemas/Shelf"
            }
          ]
        }
      }
    }
  }
}
```

Snippet of AssetFrame.java

```
  @Deprecated
  @SerializedName(SERIALIZED_NAME_MACHINE_DETAILS)
  private AssetFrameMachineDetails machineDetails;
```

##### openapi-generator version

3.0.0

##### Expectation

`allOf` with single `$ref` should respect `deprecated` property and should have `@Deprecated` annotation. 

##### Steps to reproduce
java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i ./library_openapi.json -g java -o ~/Documents/library/

##### Related issues/PRs

None found

##### Suggest a fix

Probably fix will be in [modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java#L235](https://github.com/OpenAPITools/openapi-generator/blob/c9f7af752fe12df3d3a96ff7ba290a90f3ccb0d5/modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java#L235 block.
Need to set properties before/after execution. 
need go through the code to find the code fix location.

**Comment by wing328** [comment]
thanks for reporting the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/17056 to fix it.
