### ISSUE TITLE
[BUG][PHP] incorrect mapping generated in FedEx OpenAPI schema

### ISSUE THREAD

**Issue by mehgcap** [OpenAPITools/openapi-generator#17061]
##### Description

FedEx has a new API, which they offer in OpenAPI format. I'm using this generator to make PHP libraries from the FedEx schemas. So far, I've found one problem, but I'd be willing to bet that similar issues await elsewhere in the schemas.

Once generated, Model/RateReplyDetail.php contains an array called $openAPITypes. In this array, on line 65, is this text:

`'rated_shipment_details' => '\CompanyName\FedExAPI\Rate\Model\RatedShipmentDetail',`

When I use the library with this line, it fails. The PHP object created from a rate request lacks most of the values it should have, values in RatedShipmentDetails, for instance.

To fix this problem, I changed line 65 to tell it to map to an array of these objects:

`'rated_shipment_details' => '\CompanyName\FedExAPI\Rate\Model\RatedShipmentDetail[]',`

Once I made this change, all the charges and other information missing from the PHP object were present. I don't know enough about OpenAPI to explain why this worked or where the generator might be getting confused, but I do know that this change fixed the problem, since ObjectSerializer::deserialize() recursed over these objects correctly. I think this method was treating the array like one of the objects before.

##### openapi-generator version

The latest as of November 13, 2023, v7.1.0. Also tested in what I believe is 7.0.2 with identical results.

##### OpenAPI declaration file content or url

I can't link to this directly because of some JS on the page. Go to https://developer.fedex.com/api/en-us/catalog/rate/v1/docs.html#operation/Rate%20and%20Transit%20times and choose the link near the top to download the full schema. It's big.

##### Generation Details

```bash
namespace="MyCompany\FedExAPI\Rate"
docker run --rm \
-v $(pwd):/local \
openapitools/openapi-generator-cli generate \
-i rate.json \
-o lib/Rate \
-g php \
--invoker-package "$namespace" \
--package-name "rate" \
--git-user-id "$namespace" \
--git-repo-id "rate"
```

##### Steps to reproduce

1. Run the above command in a bash script to generate the library.
2. Open lib/Model/RateReplyDetail.php and check line 65. You should see no brackets, which will cause ObjectSerializer::deserialize() to not treat this object correctly.

##### Related issues/PRs

None I know of. I searched for "fedex rate" and found no open issues.

##### Suggest a fix

I'm no OpenAPI expert. All I was able to work out was that the rated_shipment_details property should map to an array, not an individual object. Once it's an array in the map, deserialize() handles it properly by recursively calling itself on the RatedShipmentDetails objects, and everything appears to work correctly. Why this mapping is incorrect is far beyond me.

**Comment by baileysp** [comment]
I believe this is an issue with the Fedex api spec file. The spec, defines `LTLRateReplyDetail.ratedShipmentDetails` as 
```json
"ratedShipmentDetails": {
    "$ref": "#/components/schemas/RatedShipmentDetail"
},
```
I would change it to the following, and regenerate.
```json
"ratedShipmentDetails": {
    "type": "array",
    "items": {
        "$ref": "#/components/schemas/RatedShipmentDetail"
    }
},
```

**Comment by mehgcap** [comment]
Thank you, @baileysp. I think you solved it. I'm not surprised that FedEx has a bug in their schema, given the other problems we've had implementing/testing this API. I'll close this issue since it's not a problem with the generator.
