### ISSUE TITLE
[BUG][JAVA] jaxrs-resteasy Generator and useJakartaEe still imports packages from javax instead of jakarta

### ISSUE THREAD

**Issue by jakwarrior** [OpenAPITools/openapi-generator#17069]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

With jaxrs-resteasy Generator, and the option **useJakartaEe** enabled, the generated code still imports javax instead of jakarta for some packages:

```
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import jakarta.validation.constraints.*;
import io.swagger.annotations.*;
import javax.validation.Valid;
```

The `javax.validation.Valid` option is linked to the option **useBeanValidation**. This option is true by default. If I set this option to false, the import disappears, and the code can compile.

##### openapi-generator version

7.1.0

##### Suggest a fix

If `useJakartaEe` and `useBeanValidation` options are enabled at the same time, the import should be `import jakarta.validation.Valid`

**Comment by jakwarrior** [comment]
Done

> > If useJakartaEe and useBeanValidation are enabled at the same time, the import should be import jakarta.validation.Valid
> 
> thanks for reporting the issue. do you mind filing a fix for this issue?

Done 👍

**Comment by Eagle94T** [comment]
I didn't find any PR for this, so I assume it's still open.

There is another dependency that is still using `javax.validation.Valid` or better say, that imports it twice, once from jakarta and once from javax.

This line seems to be redundant and should probably be removed:

https://github.com/OpenAPITools/openapi-generator/blob/1024c7733eb9ec3f5acd3482593a9f3ff25fb61d/modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/pojo.mustache#L2

**Comment by hamburml** [comment]
Just opened a PR. Please check @Eagle94T @wing328
