### ISSUE TITLE
[BUG]  MAP in open API specification is generating code with compilation error

### ISSUE THREAD

**Issue by pragya-animod** [OpenAPITools/openapi-generator#17078]
#### Bug Report Checklist

- [x]   Have you provided a full/minimal spec to reproduce the issue?

- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

i am using kotlin-server generator latest version 7.0.1 and this is my OAS 3.0 spec
testProperty:
  type: object
  additionalProperties:
    type: string
but this is generating a kotlin code with compilation error
@Serializable
@JvmInline
value class TestProperty(v**al value: kotlin.collections.Map&lt;kotlin.String, kotlin.String&gt;){**
}

generating the HTML-encoded entities (&lt; and &gt;),

##### openapi-generator version

 latest version 7.0.1

##### OpenAPI declaration file content or url

if it is a bug, a json or yaml that produces it.
If you post the code inline, please wrap it with

```
testProperty:
  type: object
  additionalProperties:
    type: string
```

(for YAML code) or
```json
(here your code)
```
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->

##### Generation Details

```

 @Serializable
@JvmInline
value class TestProperty(val value: kotlin.collections.Map**&lt;**kotlin.String, kotlin.String**&gt;**){
}

```

####Expected Output

```
@Serializable
@JvmInline
value class TestProperty(val value: kotlin.collections.Map<kotlin.String, kotlin.String>){
}

```

**Comment by wing328** [comment]
I couldn't repeat the issue. can you please share the full spec and exact commands/options used to generate the incorrect output mentioned in the issue.
