### ISSUE TITLE
[REQ] Required fields in Zapier generator

### ISSUE THREAD

**Issue by chenjr0719** [OpenAPITools/openapi-generator#17093]
### Is your feature request related to a problem? Please describe.

The current Zapier generator does not include the required field when generate models. All the fields will be optional now.

## Describe the solution you'd like

Including the required field based on the document.

## Describe alternatives you've considered

Nope

## Additional context

The schema of Pet includes two required fields:
https://github.com/OpenAPITools/openapi-generator/blob/69fcfeff38b878a1c617e796efbe1daf4daf0944/samples/yaml/pet.yml#L148-L150

The current zapier model does not follow it:
https://github.com/OpenAPITools/openapi-generator/blob/d9920a5b819c8350d2051a5a066b234398b7db76/samples/client/petstore/zapier/models/Pet.js#L10-L19

The field schema of zaiper models:
https://zapier.github.io/zapier-platform-schema/build/schema.html#fieldschema

**Comment by wing328** [comment]
thanks for reporting the issue.

cc @valmoz, @emajo

**Comment by emajo** [comment]
Thanks, I filed a pr with the fix
[PR-17115](https://github.com/OpenAPITools/openapi-generator/pull/17115)
