### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by OlafFlebbeBosch** [OpenAPITools/openapi-generator#17105]
This commit breaks the Docker image on Dockerhub
https://github.com/OpenAPITools/openapi-generator/commit/bae20c1887456b1954e08f48081a70f8a8bf5b3d

docker run openapitools/openapi-generator-cli 
env: can't execute 'bash': No such file or directory

Reason: The base image amazoncorretto:17.0.8-alpine3.18 does not contain /bin/bash but the docker entrypoint
https://github.com/OpenAPITools/openapi-generator/blob/dcccd06a9a79a3fef9bd899782321f4443251447/docker-entrypoint.sh#L1 needs `bash`

**Comment by wing328** [comment]
just reverted the change. please give it a try with the latest.

will file another PR to add a test moving forward.

**Comment by OlafFlebbeBosch** [comment]
You may consider to use eclipse-temurine:17-jre (or jdk if needed) .
