### ISSUE TITLE
[BUG] Array keyword minItems not in serde validator

### ISSUE THREAD

**Issue by vances** [OpenAPITools/openapi-generator#17136]
##### Description

Array keyword `minItems` results with empty validation in Rust model.

##### openapi-generator version

7.1.0

##### OpenAPI declaration file content or url

```yaml
---
swagger: '2.0'
info:
  title: Bug in Array Validation
  version: 0.1.0
paths:
  "/foo":
    get:
      responses:
        '200':
          description: Success
          schema:
            "$ref": "#/definitions/Foo"
definitions:
  Foo:
    type: object
    properties:
      bar:
        type: array
        items:
          "$ref": "#/definitions/Bar"
        minItems: 1
  Bar:
    type: string
```

##### Generation Details

```bash
$ uname -a
Darwin box.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64
$ cargo version
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
```

##### Steps to reproduce

```bash
$ openapi-generator generate --generator-name rust-server -i bug.yaml
$ cargo build
error: Invalid attribute #[validate] on field `bar`: it needs at least one validator
  --> src/models.rs:56:5
   |
56 |     #[validate(
   |     ^

error: could not compile `openapi_client` (lib) due to previous error
```

The generated `src/models.rs`:
```rust
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize, validator::Validate)]
#[cfg_attr(feature = "conversion", derive(frunk::LabelledGeneric))]
pub struct Foo {
    #[serde(rename = "bar")]
    #[validate(
        )]
    #[serde(skip_serializing_if="Option::is_none")]
    pub bar: Option<Vec<models::Bar>>,

}
```

##### Suggest a fix

The validation in the generated model should be:
 ```rust
     #[validate(
         length(min = 1)
        )]
```

**Comment by wing328** [comment]
@vances thanks for reporting the issue. Would you have time to contribute a PR with a fix?

**Comment by wing328** [comment]
I could be wrong but looks like the bug can be fixed by simply updating the mustache templates in https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/rust-server

and here is how another template (python-flask) is using `minItems`: https://github.com/OpenAPITools/openapi-generator/blob/6d93b0ec83ad812bf01d27eedd26a4523406fa40/modules/openapi-generator/src/main/resources/python-flask/model.mustache#L156

**Comment by vances** [comment]
@wing328 Heh, I had just reached that conclusion by fumbling my way around.  :)

I'll try to make it work.  Thanks.

**Comment by wing328** [comment]
👍 

let me know if you need any help (PM me via Slack)

**Comment by vances** [comment]
Completed in PR #17201
