### ISSUE TITLE
[REQ] [Java][Spring] Generate a Controller per operation

### ISSUE THREAD

**Issue by pcuriel** [OpenAPITools/openapi-generator#17145]
Having controllers split by tags is nice, but patterns like Vertical Slicing suggest going a step further and having one Controller per endpoint.

In a similar fashion to `useTags`, a `useOperationIds` config option could be added to use the operationId to generate the interface/controller classnames.

An alternative/complementary option could be adding a `x-controller-name` vendor extension applicable to Operation object.

**Comment by wing328** [comment]
I've filed #17161 to meet this requirement. To give it a try, here is an example:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g spring -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml  -o  /tmp/spring5 --openapi-normalizer SET_TAGS_TO_OPERATIONID=true --additional-properties useTags=true
```
