### ISSUE TITLE
[BUG] Model Name Mapping is not functional in Java codegen. 

### ISSUE THREAD

**Issue by krisnik** [OpenAPITools/openapi-generator#17189]
#### Bug Report Checklist

Hi, I have attempted to use the modelNameMapping configuration. But the generated SDK does not seem to render it. 

Went through few reference PRs. https://github.com/OpenAPITools/openapi-generator/pull/16209 

The configuration was passed via pom.xml

```xml
           <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>6.3.0</version>
                <executions>
                    <execution>
                        <id>generate-java-sdk2</id>
                        <phase>install</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <skip>${sdk.codegen.skip}</skip>
                            <inputSpec>${project.build.directory}/openapi.json</inputSpec>
                            <generatorName>java</generatorName>
                            <groupId>${sdk2.java.groupId}</groupId>
                            <artifactId>${sdk2.java.artifactId}</artifactId>
                            <artifactVersion>${sdk2.java.version}</artifactVersion>
                            <packageName>${sdk2.java.packageName}</packageName>
                            <apiPackage>${sdk2.java.packageName}.api</apiPackage>
                            <modelPackage>${sdk2.java.packageName}.models</modelPackage>
                            <invokerPackage>${sdk2.java.packageName}.invoker</invokerPackage>
                            <generateModelTests>false</generateModelTests>
                            <output>${sdk2.java.outputDirectory}</output>
                            <library>webclient</library>
                            <verbose>true</verbose>
                            <importMappings>
                                <importMapping>User=com.foo.sdk.common.models.User</importMapping>
                                <importMapping>Link=com.foo.sdk.common.models.Link</importMapping>
                            </importMappings>
                            <schemaMappings>
                                <schemaMapping>EntityModelUserAccount=com.foo.sdk.models.UserAccount</schemaMapping>
                            </schemaMappings>
                            <!-- <modelNameMappings>
                                <modelNameMapping>EntityModelUserAccount=com.foo.sdk.models.UserAccount</modelNameMapping>
                            </modelNameMappings> -->
                            <configOptions>
                                <hateoas>true</hateoas>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

Seems like the support is available only for select generators. 

Could you please suggest how to proceed and enable support for java. 

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by wing328** [comment]
which  openapi generator are you using? can you share the full pom.xml to repeat the issue more easily?

**Comment by krisnik** [comment]
> which openapi generator are you using? can you share the full pom.xml to repeat the issue more easily?

@wing328 Sure, have updated the entire plugin. Please do note that the same thing didn't work even with plugin version 7.1.0. As a workaround what I have done is create a class and use it via schemaMapping. 

My usecase is that if I have `List<EntityModel<UserAccount>>` to enable Spring Hateoas links, The generated class name is `EntityModelUserAccount` instead of `UserAccount` causing the SDK consumers to break. Hence, trying to make sure that the generated SDK will continue with the same name.

**Comment by meltsufin** [comment]
I have the same problem. The `--model-name-mappings` options seems to have no effect for `-g java --library okhttp-gson`.
