### ISSUE TITLE
DeprecationWarning: ssl_context is deprecated, use ssl=context instead

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#1719]
##### Description
Deprecation warning found in the Travis CI for the Python client:

```
test/test_fake_api.py::TestFakeApi::test_test_enum_parameters
  /home/travis/build/OpenAPITools/openapi-generator/samples/client/petstore/python-asyncio/petstore_api/rest.py:69: DeprecationWarning: ssl_context is deprecated, use ssl=context instead
    ssl_context=ssl_context
```

##### openapi-generator version

Latest master

##### Suggest a fix

Follow the suggestion to use `ssl=context ` instead

cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10)

**Comment by tomplus** [comment]
@wing328 thanks for merging fix :+1:
