### ISSUE TITLE
[BUG] "==" enum value generates "_" in Java which is invalid since Java 9

### ISSUE THREAD

**Issue by motofix** [OpenAPITools/openapi-generator#17276]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

"==" enum value geneates "_" in Java which is invalid since Java 9

##### openapi-generator version

7.2.0-SNAPSHOT

##### OpenAPI declaration file content or url

It's part of the Apache Superset OpenAPI definition

```json
                    "op": {
                        "description": "The comparison operator.",
                        "enum": [
                            "==",
                            "!=",
                            ">",
                            "<",
                            ">=",
                            "<=",
                            "LIKE",
                            "ILIKE",
                            "IS NULL",
                            "IS NOT NULL",
                            "IN",
                            "NOT IN",
                            "IS TRUE",
                            "IS FALSE",
                            "TEMPORAL_RANGE"
                        ],
                        "example": "IN",
                        "type": "string"
                    },
```

##### Suggest a fix

PR is comming

**Comment by hkawa608** [comment]
Hi @wing328 , would you review @motofix 's PR?
We use v4.3.1 and have to migrate to Java17, and this issue is the blocker, so we want his PR merged.

**Comment by wing328** [comment]
let me review the PR

for the time being, what about using enum name mapping: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping, to mape "==" to whatever value you want?

**Comment by wing328** [comment]
@motofix can you pleas also try the enum name mapping option?

**Comment by hkawa608** [comment]
Actually. it is hard for us to update the plugin version, and v4.3.1 doesn't have enum name mapping feature...

**Comment by wing328** [comment]
If we merge thet PR, you still need to update openapi Generator to newer version, right?

**Comment by hkawa608** [comment]
We want the fix to be backport to v4.

**Comment by hkawa608** [comment]
I got it. We use our original codegen class which extends JavaJerseyServerCodegen, so we will merge the fix to our class.

**Comment by hkawa608** [comment]
How is the review going?

**Comment by hkawa608** [comment]
@wing328 
How is the review going?

**Comment by wing328** [comment]
merged via https://github.com/OpenAPITools/openapi-generator/pull/18338 with updated docs instead
