### ISSUE TITLE
[BUG] hideGenerationTimestamp doesn't seem to work for openapi-generator-maven-plugin

### ISSUE THREAD

**Issue by jduan-highnote** [OpenAPITools/openapi-generator#17308]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using the `openapi-generator-maven-plugin`, does the `hideGenerationTimestamp` configuration work? I tried it on a project and it still generated code with timestamps:

```
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-04T11:26:38.758850-08:00[America/Los_Angeles]")
public class ApiException extends Exception {
```

The timestamps are not good when it comes to build caches because every time the code is generated, it has a new timestamp and the cache key would change, meaning we can't use the remote cache. 

##### openapi-generator version

The latest 7.1.0

**Comment by tvartom** [comment]
Version 7.20 seems to have the same issue.

```
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <!-- RELEASE_VERSION -->
    <version>7.2.0</version>
    <!-- /RELEASE_VERSION -->
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>java</generatorName>
                <!-- This should hide the timestamps: -->
                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                <configOptions>
                   <sourceFolder>src/gen/java/main</sourceFolder>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by jduan-highnote** [comment]
@tvartom I assume you meant version 7.2.0. Thanks for testing out the latest version!

**Comment by wing328** [comment]
i think hide generation time stamp option is a generator option (not global option) so you need something like

```
                <configOptions>
                   <sourceFolder>src/gen/java/main</sourceFolder>
                   <hideGenerationTimestamp>true</hideGenerationTimestamp>
                </configOptions>
```

**Comment by tvartom** [comment]
Yes, this works in 7.2.0
Thanks @wing328!

```
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <!-- RELEASE_VERSION -->
    <version>7.2.0</version>
    <!-- /RELEASE_VERSION -->
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>java</generatorName>
                <!-- This should hide the timestamps: -->
                <configOptions>
                   <sourceFolder>src/gen/java/main</sourceFolder>
                   <hideGenerationTimestamp>true</hideGenerationTimestamp>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by jduan-highnote** [comment]
I confirmed this worked for me as well. Thanks @wing328 !
