### ISSUE TITLE
[REQ] "dateLibrary" option for Kotlin

### ISSUE THREAD

**Issue by ackintosh** [OpenAPITools/openapi-generator#1731]
### Is your feature request related to a problem? Please describe.

Even though [KotlinSpringServer](https://github.com/OpenAPITools/openapi-generator/blob/9e1cce2e7b2fefa742c4992215c59998fb9fb311/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java) generates a java.time.OffsetDateTime property from `date-time`, I often need LocalDateTime instead.

https://github.com/OpenAPITools/openapi-generator/blob/9e1cce2e7b2fefa742c4992215c59998fb9fb311/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java#L247

## Describe the solution you'd like

How about that add `dateLibrary` option to KotlinSpringServer?

e.g. AbstractJavaCodegen

JavaCodegen allows `dateLibrary=java8-localdatetime` to generate java.time.LocalDateTime property.

https://github.com/OpenAPITools/openapi-generator/blob/9e1cce2e7b2fefa742c4992215c59998fb9fb311/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L496-L497

```
$ openapi-generator config-help -g java
        dateLibrary
            Option. Date library to use
                joda - Joda (for legacy app only)
                legacy - Legacy java.util.Date (if you really have a good reason not to use threetenbp
                java8-localdatetime - Java 8 using LocalDateTime (for legacy app only)
                java8 - Java 8 native JSR310 (preferred for jdk 1.8+) - note: this also sets "java8" to true
                threetenbp - Backport of JSR310 (preferred for jdk < 1.8)
```

**Comment by ackintosh** [comment]
If my suggestion makes sense, I'll working on the issue. 💨 

cc: @jimschubert (2017/09) @dr4ke616 (2018/08)

**Comment by jimschubert** [comment]
@ackintosh I don't like using `dateLibrary` to mix both library and library options. For example, how would you extend this to change default date formats from YYYY-MM-DD to MM-DD-YYYY or something other?

Are you unable to generate code as expected by defining these import and type mappings options at the command line?

Would it make sense to evaluate some way to provide user-preferences for type and import mappings? I think this would be ideal as a way to share JVM defaults across generators.

That said, I'm not opposed to the suggestion. My concern is that `library-variant` formats don't scale well, and become difficult to change as more and more users consume the new option.

**Comment by ackintosh** [comment]
> Are you unable to generate code as expected by defining these import and type mappings options at the command line?

Yes, it will be better solution than adding `dateLibrary` if that exists. 💡

**Comment by ackintosh** [comment]
Oh, I've noticed `--type-mappings` and `--import-mappings` options just now. 👀 I'm trying the options.

**Comment by ackintosh** [comment]
I've tried `--type-mappings date-time=java.time.LocalDateTime` and `--type-mappings DateTime=java.time.LocalDateTime` but the option seems be overwritten by following 👀 :

- [KotlinSpringServerCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/314b4cc54f68c32552901ad872615b56119ce9a9/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java#L246-L249)
- [AbstractKotlinCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/314b4cc54f68c32552901ad872615b56119ce9a9/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java#L160-L178)

Is there a generator which supports the option? I would like to enhance Kotlin generator to support the option.

**Comment by jimschubert** [comment]
@ackintosh I've opened #1740 for your evaluation.

If the change resolves your immediate needs, I'd like to open another issue to track the possibility of having default configs which can get merged into external user configs.

For instance, if you passed `-c myconfig.json` where `myconfig.json` defined your command line options… I think it would be nice to read in `~/.openapi-generator/default.json` which could be applied across generators. Something like:

```json
{
  "options": [
      {
        "name": "type-mappings",
        "value": [ "DateTime=java.time.OffsetDateTime" ],
        "exclude": [ "kotlin" ],
        "include": [ "java" ]
      }
   ],
  "settings": [
    …
  ]
}
```

**Comment by ackintosh** [comment]
@jimschubert Thanks! I'll have a look soon. ✨

**Comment by ackintosh** [comment]
Thanks for the PR. I've checked that the options works well. 😌
