### ISSUE TITLE
[BUG] [SPRING] openapi-generator should not generate model files if import-mapping is used

### ISSUE THREAD

**Issue by arandth** [OpenAPITools/openapi-generator#17330]
##### Description

we are using import-mapping directives to use manually written versions of some (very few) models. In earlier versions of the code-generator (at least 5.X) this lead to NOT generating these model files, which is exactly what we need.
With version 7.X (at least, for 6.X I'm not sure) these unnecessary files are generated, which has two problems:
1) users (developers) are confused as they have two similar files for the same model object (while the generated file must not be used)
2) we sometimes use this feature to define the mapping to point to a class with the same name and package (!!). This now even breaks compilation as two identical classes exist.

However, there is a workaround: I can write a white-list of model files that should be generated, but this is very inconvenient as I must manually mention very many names in that whitelist.

##### openapi-generator version

7.0.0, 7.1.0 (this is the maven-plugin version)

##### Suggest a fix

Two possible solutions:
1) bring back the behavior of 5.X
2) add an option for model files that should not be generated.

**Comment by wing328** [comment]
please try schema mapping instead: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#schema-mapping

**Comment by arandth** [comment]
Very good hint, thank you very much! This seems to work
