### ISSUE TITLE
[REQ] Disable Creation of Tests

### ISSUE THREAD

**Issue by maxl2287** [OpenAPITools/openapi-generator#17341]
### Is your feature request related to a problem? Please describe.

When I want to generate the code, I always have the problem, that there are generated Tests as well.
They are empty, but they are there.

![image](https://github.com/OpenAPITools/openapi-generator/assets/112983658/73af81c6-01d4-4151-9bda-ca9ce5c271f9)

I have explicitly marked to disable tests and I expected that they won't be generated at all.

 <generateApiTests>false</generateApiTests>
 <generateModelTests>false</generateModelTests>

```yaml
<plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>7.1.0</version>
        <executions>
          <execution>
            <id>client</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
              <generatorName>java</generatorName>
              <library>resttemplate</library>
              <templateDirectory>../templates/openapi-generator/Java</templateDirectory>
              <apiPackage>com.network.api</apiPackage>
              <invokerPackage>com.network.api</invokerPackage>
              <modelPackage>com.network.api.model</modelPackage>
              <configOptions>
                <additionalModelTypeAnnotations>
                  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                </additionalModelTypeAnnotations>
                <useJakartaEe>true</useJakartaEe>
                <generateClientAsBean>true</generateClientAsBean>
              </configOptions>
            </configuration>
          </execution>
          <execution>
            <id>server</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>com.network.api.notifications</apiPackage>
              <modelPackage>com.network.api.model</modelPackage>
              <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
              <configOptions>
                <useSpringBoot3>true</useSpringBoot3>
                <delegatePattern>true</delegatePattern>
                <useJakartaEe>true</useJakartaEe>
              </configOptions>
              <environmentVariables>
                <apis>notifications</apis>
              </environmentVariables>
              <openapiNormalizer>
                SIMPLIFY_ANYOF_STRING_AND_ENUM_STRING=true
              </openapiNormalizer>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
## Describe the solution you'd like

Do not generate the tests when the configuration is explicitly disabling test-generation.

**Comment by jpfinne** [comment]
@maxl2287 
in the client execution there is no 
<configuration>
             <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
</configuration>
So the tests are generated.

Side note:
You generate the client and server code in the same module.    I think it is better to split the generation in 2 modules.

The second execution overwrites the result of the first execution.

For example the models are generated in the same package com.network.api.model.  The generated code is slightly different between generators, especially if you add configOptions like additionalModelTypeAnnotations.

If you want to share the generated model, you can generated it separately with a third execution:
<generateApis>false</generateApis>

and in the client and server execution:
<generateModels>false</generateModels>
