### ISSUE TITLE
[python] delete path response type ignored

### ISSUE THREAD

**Issue by vmorris** [OpenAPITools/openapi-generator#1734]
##### Description

`DELETE` paths ignore any specified return type. The RFC indicates that if a DELETE request returns 200, the body should contain status information.

> 9.7 DELETE
>
> The DELETE method requests that the origin server delete the resource identified by the Request-URI. This method MAY be overridden by human intervention (or other means) on the origin server. The client cannot be guaranteed that the operation has been carried out, even if the status code returned from the origin server indicates that the action has been completed successfully. However, the server SHOULD NOT indicate success unless, at the time the response is given, it intends to delete the resource or move it to an inaccessible location.
>
>  A successful response SHOULD be 200 (OK) if the response includes an entity describing the status, 202 (Accepted) if the action has not yet been enacted, or 204 (No Content) if the action has been enacted but the response does not include an entity.
>
> If the request passes through a cache and the Request-URI identifies one or more currently cached entities, those entries SHOULD be treated as stale. Responses to this method are not cacheable.

##### openapi-generator version
3.3.4

##### OpenAPI declaration file content or url

```json
  "delete": {
    "summary": "Delete repository",
    "description": "Use this operation to delete a specific repository.",
    "tags": [
      "repositories"
    ],
    "operationId": "delete_repository",
    "parameters": [
      {
        "name": "repository_id",
        "in": "path",
        "description": "Repository ID",
        "required": true,
        "schema": {
          "type": "string"
        }
      }
    ],
    "responses": {
      "200": {
        "description": "OK",
        "content": {
          "application/json": {
            "$ref": "../repositories-by_id/components/schemas/RepositoryDeleteResponse.json"
          }
        }
      }
    }
  }
```

##### Command line used for generation
`openapi-generator-cli generate -i index.json -g python -o myapi_client/ -DpackageName=myapi_client`

##### Steps to reproduce
1. Specify a `delete` path and include a response object
2. Generate a python client

##### Suggest a fix
Allow, at least for 200 status responses on a delete action to have a response body.

**Comment by spacether** [comment]
This should be fixed in v6.2.0 where the python client returns the response from the delete call
https://github.com/OpenAPITools/openapi-generator/blob/8b10dc3830f21961c4ae3c9ad7b3831a2d78f8ee/samples/openapi3/client/petstore/python/petstore_api/rest.py#L137
If a response content type is defined for a certain status code, it should be used when deserilizing.
