### ISSUE TITLE
Java RESTEasy client does not provide the "filename" directive when creating "multipart/form-data" requests

### ISSUE THREAD

**Issue by miladhub** [OpenAPITools/openapi-generator#17367]
##### Description

When generating a Java RESTEasy client for an API that creates "multipart/form-data" requests, the HTTP request lacks the "filename" [directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition). The generated code seems to simply omit the parameter - i.e., instead of calling [this API](https://docs.jboss.org/resteasy/docs/6.2.5.Final/javadocs/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutput.html#addFormData(java.lang.String,java.lang.Object,jakarta.ws.rs.core.MediaType,java.lang.String)), it calls [this one](https://docs.jboss.org/resteasy/docs/6.2.5.Final/javadocs/org/jboss/resteasy/plugins/providers/multipart/MultipartFormDataOutput.html#addFormData(java.lang.String,java.lang.Object,jakarta.ws.rs.core.MediaType)). Note that the generated code has the `file` at hand, so it is entirely within its reach to provide it.

##### openapi-generator version

7.2.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Foo API
servers:
  - url: http://127.0.0.1:8080/{basePath}
    variables:
      basePath:
        default: v1
paths:
  /foo:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                bar:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
```

##### Command line used for generation

```shell
java -jar openapi-generator-cli.jar generate -i api.yaml -g java --library resteasy
```

##### Steps to reproduce

1. Generate the client with the command above
2. Add a `Main` class with the following contents
```java
package org.openapitools.client;
import org.openapitools.client.api.DefaultApi;
import java.io.File;
public class Main {
    public static void main(String[] args) throws ApiException {
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        defaultClient.setBasePath("http://localhost:8080/v1");
        DefaultApi apiInstance = new DefaultApi(defaultClient);
        File bar = new File("pom.xml");
        apiInstance.fooPost(bar);
    }
}
```
3. Build with `mvn clean install`
4. On another tab, listen for incoming connections with `nc localhost -l 8080 | grep "Content-Disposition"`
5. Run the client project with `mvn exec:java -Dexec.mainClass="org.openapitools.client.Main"`

The tab open at point 4 should display the following:
```shell
$ nc localhost -l 8080 | grep "Content-Disposition"
Content-Disposition: form-data; name="bar"
```

showing that the "filename" directive is missing. The output should have been

```
Content-Disposition: form-data; name="bar"; filename="pom.xml"
```

Note - The last command needs to be eventually killed.

##### Related issues/PRs

Found none.

##### Suggest a fix/enhancement

The fix should be a matter of adding `, file.getName()` on this line of generated code:

```java
File file = (File) param.getValue();
try {
  multipart.addFormData(param.getKey(),new FileInputStream(file),MediaType.APPLICATION_OCTET_STREAM_TYPE); // Here
} catch (FileNotFoundException e) {
  throw new ApiException("Could not serialize multipart/form-data "+e.getMessage());
}
```

**Comment by wing328** [comment]
@miladhub thanks for reporting the issue. Can you please file a PR with the suggested fix?

**Comment by miladhub** [comment]
Yes I can look into that.

**Comment by miladhub** [comment]
I tried to push the fix on a branch to then create a PR, but the push is getting refused:
```shell
$ git push --set-upstream origin pr_17367_multipart_filenames
remote: Permission to OpenAPITools/openapi-generator.git denied to miladhub.
fatal: unable to access 'https://github.com/OpenAPITools/openapi-generator.git/': The requested URL returned error: 403
```

**Comment by miladhub** [comment]
I've also tried with SSH and signed commits, but I still get an unauthorized error. Attaching patch.
[added_filename_directive_for_Java_RESTEasy_file_uploads_#17367.patch](https://github.com/OpenAPITools/openapi-generator/files/13692385/added_filename_directive_for_Java_RESTEasy_file_uploads_.17367.patch)

**Comment by miladhub** [comment]
For the record, I've tried this exact process on a repo of my own and it works, so it must really be a matter of permissions. Let me know if I can do anything, but feel free to use my patch, thanks.

**Comment by wing328** [comment]
please refer to https://github.com/OpenAPITools/openapi-generator/wiki/faq#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements on how to file a PR

**Comment by miladhub** [comment]
Thanks! Created PR: https://github.com/OpenAPITools/openapi-generator/pull/17435

**Comment by miladhub** [comment]
Verified end-to-end against version 7.2.0.
