### ISSUE TITLE
[REQ] Release 7.2.0

### ISSUE THREAD

**Issue by geemanjs** [OpenAPITools/openapi-generator#17371]
Hey,

Wasn't sure the best way to request this so apologies if this is incorrect. 

### Is your feature request related to a problem? Please describe.
Axios 0.27 has a [high CVE associated with it](https://security.snyk.io/package/npm/axios/0.27.2). Version `openapi-generator@7.1.0` uses that version of Axios. 

I noticed that the day after the `7.1.0` release the Typescript projects Axios upgrade was merged in (to `1.6.1` which has no CVE associated with it):
https://github.com/OpenAPITools/openapi-generator/issues/14517
https://github.com/OpenAPITools/openapi-generator/pull/14518
https://github.com/OpenAPITools/openapi-generator/commit/a460b7ea8783dce3b86ca8e1f8212204f856ae19

I also noticed that there have been a couple of PRs to do the upgrade and a couple of previous requests to release this version in various comments across the issues / PRs - which suggest this might be wanted by multiple people/projects. 

## Describe the solution you'd like
Release the current `master` version as 7.2.0 with the already merged `axios` upgrade in it.

## Describe alternatives you've considered
The library we pull in to our project is `@ory/client` which is an authentication based library. 

I assume they are reluctant to use a `SNAPSHOT` version of the generator for a public facing library

## Additional context
Happy to help resolve any issues blocking the `7.2.0` release currently.

**Comment by wing328** [comment]
we should be able to cut a release (last release of 2023) this week.

**Comment by geemanjs** [comment]
Thanks @beanow-at-crabnebula and @wing328 - I didn't realise there was a target milestone! Looking forwards to getting this resolved in the new year! 

I'll close this ticket now as it looks as if the ball is rolling 👍 

Happy holidays and new year!
