### ISSUE TITLE
[BUG] Python generated client give `name 'AnyOf' is not defined`

### ISSUE THREAD

**Issue by ArnaudPalgen** [OpenAPITools/openapi-generator#17415]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Python generated client give `NameError: name 'AnyOf' is not defined`:

```
_____________________________________________________________ ERROR collecting test/test_default_api.py ______________________________________________________________
test/test_default_api.py:17: in <module>
    from openapi_client.api.default_api import DefaultApi
openapi_client/__init__.py:20: in <module>
    from openapi_client.api.default_api import DefaultApi
openapi_client/api/__init__.py:4: in <module>
    from openapi_client.api.default_api import DefaultApi
openapi_client/api/default_api.py:36: in <module>
    class DefaultApi:
openapi_client/api/default_api.py:66: in DefaultApi
    ) -> AnyOf:
E   NameError: name 'AnyOf' is not defined
====================================================================== short test summary info =======================================================================
ERROR test/test_default_api.py - NameError: name 'AnyOf' is not defined
```

##### openapi-generator version

Docker image: `openapitools/openapi-generator-cli:v7.1.0`

##### OpenAPI declaration file content or url

Gist URL: https://gist.githubusercontent.com/ArnaudPalgen/811236b902e9ab1c6d225f4c5d2d0d36/raw/3d3ec30f988e491aa95c6d0fbd66c08c1e3d2f8e/open_api_spec.json

##### Generation Details

- Generation from a Python FastAPI application
- The target language is Python.
- CLI command: `docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v7.1.0 generate -i /local/openapi.json -g python -o /local/out/python`
- Python version: 3.10.4
- OS infos: macOS 14.1.1 (23B81)

##### Steps to reproduce

All code used in the followings steps is available at: https://gist.github.com/ArnaudPalgen/811236b902e9ab1c6d225f4c5d2d0d36

1. `mkdir bug_example && cd bug_example`
2. `wget https://gist.githubusercontent.com/ArnaudPalgen/811236b902e9ab1c6d225f4c5d2d0d36/raw/de6059a6581c170ed665d6997d59c55e3bdb6aa7/main.py`
3. `python3 -m venv venv`
4. `source venv/bin/activate`
5. `wget https://gist.githubusercontent.com/ArnaudPalgen/811236b902e9ab1c6d225f4c5d2d0d36/raw/42de99d10fdc234484fd38fe03ebae069da54901/requirements.txt && pip install -r requirements.txt`
6.  `uvicorn main:app --reload`
7. In an other session: `wget http://127.0.0.1:8000/openapi.json`
8. `docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v7.1.0 generate -i /local/openapi.json -g python -o /local/out/python`
9. `cd out`
10. `python3 -m venv venv`
11. `source venv/bin/activate`
12. `cd python`
13. `pip install -r requirements.txt`
14. `pip install -r test-requirements.txt`
15. `pytest`

##### Related issues/PRs

Stackoverflow question without answer
https://stackoverflow.com/questions/77528788/openapi-generator-python-name-anyof-is-not-defined

**Comment by ArnaudPalgen** [comment]
This issue still persists with the latest master docker image (openapitools/openapi-generator-cli:latest)

**Comment by changhc** [comment]
I think this is a fundamental issue in the base code generator. I generated some go code with your schema and it has the same problem. I'm trying to figure out where the bug is.

**Comment by changhc** [comment]
After some experiments, I think this problem only exists with openapi 3.1.0. You can lower the version to 3.0.0 and it should work.

**Comment by ArnaudPalgen** [comment]
Yes, it's works, thanks !

**Comment by wing328** [comment]
Just merged a fix. Please give it another try with the latest master (snapshot version can be found in the readme)
