### ISSUE TITLE
[BUG] Infinite loop with REF_AS_PARENT_IN_ALLOF normalizer

### ISSUE THREAD

**Issue by amakhrov** [OpenAPITools/openapi-generator#17425]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

7.1.0, latest

##### OpenAPI declaration file content or URL

```yaml
info:
  description: Normalizer issue repro
  title: Normalizer issue repro
  version: 1.0.0
openapi: 3.0.0
paths:
  /item:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
                
components:
  schemas:
    Item:
      properties:
        hashes:
          allOf:
            - $ref: '#/components/schemas/ItemHashes'
          description: Map of all hashes
          nullable: true
      type: object

    ItemHashes:
      properties:
        data:
          description: Data hash
          type: string
      type: object
```

The crucial part is `nullable: true` in the `Item.hashes` property. Without it, the `allOf` is simplified to a flat model. However, `nullable` bails it out of this flattening, resulting in a separate composite schema.

##### Generation Details

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i normalizer.yaml -o /tmp/java/ --openapi-normalizer REF_AS_PARENT_IN_ALLOF=true
```

##### Steps to reproduce

Run the command above. It will get stuck with no output, and eventually crash with OutOfMemory.

When debugging,I can see that it gets into an infinite `while` loop in `DefaultCodegen#updateAllModels`.

The reason is name conflict with two schemas:
- `ItemHashes` - the one explicitly defined in the spec above
- `Item_hashes` - the autogenerated schema describing the `hashes` property of the `Item` schema. This property is defined as `allOf`. It has `parent: ItemHashes`

So far so good and matches the spec.

Now, the both schemas produce the identical model name (via `toModelName()`): `ItemHashes`. Model name is used as the key, hence one overwrites the other.

So, the `Item_hashes` model with `parent: `ItemHashes` results in `ItemHashes` with `parent: ItemHashes` - self-reference. This circular references makes the while loop in the normalizer infinite.

The example spec seems totally legit otherwise. And it's not even manually crafted - it's generated by https://github.com/marshmallow-code/apispec from the source python code.

##### Suggest a fix

I don't have a fix in mind.
As a local workaround I can try using model name mapping to avoid the naming conflict. Also after upgrading the spec from 3.0.0  to 3.1.0, the nullability is represented differently, and this allows to flatten the allOf schema.

**Comment by wing328** [comment]
just merged a fix. can you please give it a try with the latest master?

**Comment by amakhrov** [comment]
Wow, that was fast. Thanks @wing328  - works like a charm!
