### ISSUE TITLE
[BUG] Python-Client Tests, 13 tests fail

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#1747]
##### Description

When running the client tests for the sample petstore python client, 13 of the tests fail on the master branch.

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

petstore sample used by the client tests in the openapi-generator repo

##### Command line used for generation

`mvn integration-test`

##### Steps to reproduce

1. cd to `samples/client/petstore/python`
2 run `mvn integration-test`

Note: regenerating the python client library by running `./bin/python-petstore.sh` does not fix these tests.

The below tests fail:
```python
test_update_pet (tests.test_pet_api.PetApiTests) ... ERROR
test_async_with_http_info (tests.test_pet_api.PetApiTests) ... ERROR
test_delete_pet (tests.test_pet_api.PetApiTests) ... ERROR
test_upload_file (tests.test_pet_api.PetApiTests) ... ERROR
test_separate_default_config_instances (tests.test_pet_api.PetApiTests) ... ok
test_async_request (tests.test_pet_api.PetApiTests) ... ERROR
test_find_pets_by_status (tests.test_pet_api.PetApiTests) ... ERROR
test_separate_default_client_instances (tests.test_pet_api.PetApiTests) ... ok
test_update_pet_with_form (tests.test_pet_api.PetApiTests) ... ERROR
test_find_pets_by_tags (tests.test_pet_api.PetApiTests) ... ERROR
test_async_with_result (tests.test_pet_api.PetApiTests) ... ERROR
test_add_pet_and_get_pet_by_id_with_http_info (tests.test_pet_api.PetApiTests) ... ERROR
test_add_pet_and_get_pet_by_id (tests.test_pet_api.PetApiTests) ... ERROR
test_timeout (tests.test_pet_api.PetApiTests) ... ok
test_async_exception (tests.test_pet_api.PetApiTests) ... ERROR
test_preload_content_flag (tests.test_pet_api.PetApiTests) ... ERROR
```

##### Suggest a fix

Please edit the tests/feature code so that the tests pass.
Do the tests pass in another branch?

**Comment by wing328** [comment]
Likely due to bad data in the public petstore server. In Travis (and other CIs), we're running a local petstore server to avoid such issues when running the Python petstore tests: https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1039-L1041

**Comment by spacether** [comment]
I will ignore these tests locally

**Comment by spacether** [comment]
@wing328 is there a shell script that I can invoke to run the server locally and get these tests to pass?
Which one do we use when testing the samples? I can't tell from the pom.xml file.

**Comment by spacether** [comment]
Inspection of travis-ci testing has shown that the test server is run locally on port 80.
It is run with docker.
This line downloads the docker image:
`docker pull swaggerapi/petstore`
This line runs the server:
`docker run -d -e SWAGGER_HOST=http://petstore.swagger.io -e SWAGGER_BASE_PATH=/v2 -p 80:8080 swaggerapi/petstore`
