### ISSUE TITLE
[BUG][aspnetcore] optional query parameters with enum types not nullable

### ISSUE THREAD

**Issue by fujieda** [OpenAPITools/openapi-generator#17518]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The latest aspnetcore generator doesn't set nullable for an optional query parameter in the following definition.

```yaml
openapi: 3.0.0
info:
  title: optional query test
  version: 1.0.0
paths:
  /test:
    get:
      summary: Test API
      parameters:
        - in: query
          name: testQuery
          schema:
            $ref: '#/components/schemas/TestEnum'
          required: false
      responses:
        '200':
          description: OK

components:

  schemas:
    TestEnum:
      type: string
      enum:
        - A
        - B
```

Expected output:

```csharp
public virtual IActionResult TestGet([FromQuery (Name = "testQuery")]TestEnum? testQuery)
```

Actual output:
```csharp
public virtual IActionResult TestGet([FromQuery (Name = "testQuery")]TestEnum testQuery)
```

##### openapi-generator version

From the commit 6299af176d3720 to 7.2.0 and the latest master

##### Steps to reproduce

Just run the following command. `simple.yml' contains the above declarations.
```
 java -jar openapi-generator-cli-7.2.0.jar generate -g aspnetcore -i simple.yaml
```

##### Suggest a fix

This issue can be fixed by reverting the commit 6299af176d3720.

**Comment by kipusoep** [comment]
We ran into this issue as well, pretty annoying as we have to revert all the removed question marks manually every time we generate a new client.

**Comment by wing328** [comment]
cc @devhl-labs who's the author of the commit https://github.com/OpenAPITools/openapi-generator/commit/6299af176d3720bd4d58580b1a4090ce8c750483

**Comment by devhl-labs** [comment]
I don't think that commit is the problem. In the DefaultCodegen, property.isModel should be returning true. You can see both of my debugging variables b and c are false. If I make isModel return true here, then it works.

![image](https://github.com/OpenAPITools/openapi-generator/assets/29644329/1e611caa-6778-420c-9469-0313db140f66)

**Comment by troutkilroy** [comment]
I'm observing same issue with csharp generator in any 7.X

**Comment by fujieda** [comment]
> I don't think that commit is the problem. In the DefaultCodegen, property.isModel should be returning true. You can see both of my debugging variables b and c are false. If I set isModel to true here, then it works.

The commit introduced a fatal incompatibility in the generated code. Please check out commit 598c27d, the parent of the commit. Build it, and then generate the code for the above YAML using the aspnetcore generator. You will see the code we expect.

**Comment by devhl-labs** [comment]
The commit is correct, but it highlights another bug yet to be addressed. I explained exactly what the bug is [here](https://github.com/OpenAPITools/openapi-generator/issues/17518#issuecomment-1962797968)

**Comment by wing328** [comment]
> In the DefaultCodegen, property.isModel should be returning true

If I remember correctly, `isModel` means its `properties` is non empty.

What about using `isEnumRef` instead?

**Comment by devhl-labs** [comment]
Should I also use isEnum?

**Comment by wing328** [comment]
`isEnum` is true when the schema is an inline enum.

isEnumOrRef is true when both `isEnum` and `isEnumRef` are true.

using which one really on the use cases.

**Comment by wing328** [comment]
thanks for the fix by @devhl-labs which has been merged.

please pull the latest master to give it a try
