### ISSUE TITLE
[BUG] [Python] anyOf array of string is handled incorrectly in 3.1.0 regression

### ISSUE THREAD

**Issue by daniellowtw** [OpenAPITools/openapi-generator#17523]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))
##### Description

This appears to be a regression from handling 3.0 specs. If I switch the openapi version from 3.1.0 to 3.0.0 then the correct output is produced.

When a field is of type 

```
anyOf:
  - type: string
  - type: array
    items:
      type: string
```

The generated code ignores the array and produces

```
    field: Optional[StrictStr] = Field(...)
```

It does the right thing when it's 

```
anyOf:
  - type: string
  - type: number
```

Producing

```
    field: Field = Field(...)
```

##### openapi-generator version

latest/7.2.0

```
docker pull openapitools/openapi-generator-cli:latest
latest: Pulling from openapitools/openapi-generator-cli
Digest: sha256:7bfcb402ec4fef3af86c5ff38cec26c772db138120f931755da4a63a3cec5189
```

##### OpenAPI declaration file content or url

```yaml
openapi: 3.1.0
paths: {}
info:
  version: 1.0.0
  title: Swagger Petstore
components:
  schemas:
    Cat:
      type: object
      title: Cat
      description: a cat
      required: [field]
      properties:
        field:
          title: field
          anyOf:
          - type: string
          - items:
              type: string
```

##### Generation Details

```
$ pip install openapi-spec-validator
$ openapi-spec-validator openapi.yaml
openapi.yaml: OK

$ docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate -g python --additional-properties=generateSourceCodeOnly=true,packageName=client -o /local/ -i /local/openapi.yaml 
```

Output has no warnings/errors.

##### Steps to reproduce

1. Create openapi.yaml and generate code
2. Look in client/model/cat.py and observe list[str] is missing in the type of field
3. Switch to 3.0.0 in yaml
4. Regenerate code and observe the field now points to a new type which correctly expresses the union type

##### Related issues/PRs

None that I could find.

##### Suggest a fix

It seems like the array handling logic is incorrect.

**Comment by razzeee** [comment]
This doesn't seem to be python specific I think?

While I have a python backend, we're generating typescript-axios code.

```
# Clean slate
export TS_POST_PROCESS_FILE="prettier --write --ignore-path .gitignore"

npx @openapitools/openapi-generator-cli generate \
  -i http://localhost:8000/openapi.json -o src/codegen \
  --enable-post-process-file \
  -g typescript-axios --additional-properties=supportsES6=true,withSeparateModelsAndApi=true,modelPackage=model,apiPackage=apis

```

And I'm also seeing missing arrays (of objects)

**Comment by mtw75** [comment]
we've been also running into this problem as well - we'd be willing to sponsor the resolution, is anybody interested to help out on this ?

**Comment by wing328** [comment]
@mtw75 can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by mtw75** [comment]
Awesome, thanks for your quick reaction, have PMed you 😊

Von: William Cheng ***@***.***>
Gesendet: Freitag, 26. Januar 2024 10:22
An: OpenAPITools/openapi-generator ***@***.***>
Cc: Michael Wagner | ipolog GmbH ***@***.***>; Mention ***@***.***>
Betreff: Re: [OpenAPITools/openapi-generator] [BUG] [Python] anyOf array of string is handled incorrectly in 3.1.0 regression (Issue #17523)


@mtw75<https://github.com/mtw75> can you please PM me via Slack when you've time?

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g

**Comment by wing328** [comment]
A workaround is to fallback to 3.0.1 spec for the time being

**Comment by carsten-grimm-at-ipolog** [comment]
> A workaround is to fallback to 3.0.1 spec for the time being

My understanding is that one of our libraries (pydandtic2) forces us to use 3.1.0, unfortunately.

**Comment by wing328** [comment]
Understood. We will definitely get it fixed. For those who can use the workaround, please use it for the time being.

**Comment by wing328** [comment]
@mtw75 as discussed I'll try to fix the bug over the weekend and see how that goes.

**Comment by wing328** [comment]
Filed https://github.com/OpenAPITools/openapi-generator/pull/17728 to fix the issue with some tests.

**Comment by mtw75** [comment]
Awesome, thank you so much 😄

Gesendet von Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: William Cheng ***@***.***>
Gesendet: Sunday, January 28, 2024 5:03:12 PM
An: OpenAPITools/openapi-generator ***@***.***>
Cc: Michael Wagner | ipolog GmbH ***@***.***>; Mention ***@***.***>
Betreff: Re: [OpenAPITools/openapi-generator] [BUG] [Python] anyOf array of string is handled incorrectly in 3.1.0 regression (Issue #17523)


Filed #17728<https://github.com/OpenAPITools/openapi-generator/pull/17728> to fix the issue with some tests.

**Comment by wing328** [comment]
PR merged. Please give it a try with the latest master or snapshot version.
