### ISSUE TITLE
[BUG][csharp] Loss of description in generated code for enum property using allOf

### ISSUE THREAD

**Issue by fujieda** [OpenAPITools/openapi-generator#17545]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In the following definition, the `mode` property in `TestResponse`  uses `allOf` for a single enum type. 

```yaml
TestResponse:
  type: object
  properties:
    mode:
      description: Test mode
      type: object
      allOf:
        - $ref: '#/components/schemas/TestEnum'
TestEnum:
  description:  Specify the test mode
  type: string
  enum:
    - A
    - B
```

This technique, while peculiar, has been effective in preserving the description in the generated property until version 6.4.0, resulting in the following C# code:

```csharp
/// <summary>
/// Test mode
/// </summary>
/// <value>Test mode</value>
[DataMember(Name="mode", EmitDefaultValue=false)]
public TestEnum? Mode { get; set; }
```

However, starting with version 6.5.0 and later, the description is no longer included in the generated code, resulting in a loss of compatibility. The change in behavior can be observed in the following code snippet:

```csharp
/// <summary>
/// Gets or Sets Mode
/// </summary>
[DataMember(Name="mode", EmitDefaultValue=false)]
public TestEnum? Mode { get; set; }
```

This compatibility issue has been present since the commit a4dd90c01d3.

##### openapi-generator version

6.5.0 and later, including the latest master

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: allOf enum test
  version: 1.0.0
paths: {}

components:

  schemas:
    TestResponse:
      type: object
      properties:
        mode:
          description: Test mode
          type: object
          allOf:
            - $ref: '#/components/schemas/TestEnum'

    TestEnum:
      description:  Specify the test mode
      type: string
      enum:
        - A
        - B
```

##### Generation Details

java -jar openapi-generator-cli-7.2.0.jar generate -g csharp -i simple.yaml

##### Related issues/PRs

#15035

**Comment by wing328** [comment]
thanks for reporting the issue. i've filed https://github.com/OpenAPITools/openapi-generator/pull/17560 to fix it
