### ISSUE TITLE
[BUG][python-flask] Generator fails to create required imports for models

### ISSUE THREAD

**Issue by ericraymond** [OpenAPITools/openapi-generator#1755]
##### Description

Model are created the lack the required imports to run correctly.  This fails for petstore example!

##### openapi-generator version

Failed for 3.3.4 and lastest from master branch

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/OpenAPITools/openapi-petstore/master/src/main/resources/openapi.yaml

##### Command line used for generation

Options for gradle used for 4.4.3 test:
``` generatorName = "python-flask"
    inputSpec = "${rootDir}/openapi.yaml".toString()
    outputDir = swaggerOutputDir
    templateDir= "${rootDir}/templates/flaskConnexion".toString()
    apiPackage = "swagger_server"
    invokerPackage = "swagger_server"
    modelPackage = "models"
    additionalProperties = [
        packageName: "swagger_server",
        controllerPackage:  "controllers"
    ]
```

Pretty sure that only generatorName = "python-flask" is relevant.

For head of master, used a local docker build:
```
docker build .  

Get image ID from above command

docker run --rm -v ${PWD}:/local <ID> generate -i https://raw.githubusercontent.com/OpenAPITools/openapi-petstore/master/src/main/resources/openapi.yaml     -g python-flask     -o /local/out/py

```

##### Steps to reproduce

1) Generate code for python-flask using petstore yaml (https://raw.githubusercontent.com/OpenAPITools/openapi-petstore/master/src/main/resources/openapi.yaml)

2) Look at generated model for models/pet.py

There are no imports for Category or Tag

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/1665
- https://github.com/OpenAPITools/openapi-generator/issues/1668
- https://github.com/OpenAPITools/openapi-generator/pull/1256

**Comment by ericraymond** [comment]
Thanks @wing328 !

**Comment by wing328** [comment]
@ericraymond no problem (and thanks for opening an issue for tracking). Can you try the latest snapshot version to see if it resolves the problem for you?

**Comment by ericraymond** [comment]
It did seem to address the issue.

I'm now stuck on: https://github.com/OpenAPITools/openapi-generator/issues/1714

**Comment by wing328** [comment]
@ericraymond to me, that one looks like a regression in swagger parser. Please use the workaround you've mentioned for the time being.

**Comment by wing328** [comment]
@ericraymond please also try the `--skip-validate-spec` option to see if it helps.
