### ISSUE TITLE
[BUG] openapitools/openapi-generator-cli:v7.1.0 docker image generate broken openapi flask server image because of connexion3 release

### ISSUE THREAD

**Issue by cherusk** [OpenAPITools/openapi-generator#17565]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The latest release of the openapitools/openapi-generator-cli docker image produce broken python openapi-server docker image source code. The requirements.txt of the generated image is broken because of the constraints not catching the release of connexion3.

##### openapi-generator version

openapitools/openapi-generator-cli:v7.1.0 docker image

##### OpenAPI declaration file content or url

[config](https://github.com/cherusk/godon-images/blob/main/godon-api/openapi.yml)

##### Generation Details

[cli-invocation](https://github.com/cherusk/godon-images/blob/main/godon-api/maskfile.md?plain=1#L42)

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/17303

##### Suggest a fix

I could patch it myself as interim by amending the python flask/requirements connexion constraints:
https://github.com/cherusk/godon-images/blob/main/godon-api/maskfile.md?plain=1#L58

**Comment by wing328** [comment]
do you mind opening a PR with the patch? let us know if you need help with the PR.

**Comment by cherusk** [comment]
PR openend https://github.com/OpenAPITools/openapi-generator/pull/17611

**Comment by wing328** [comment]
merged
