### ISSUE TITLE
[BUG][JAVA][SPRING] 7.1.0 generates broken APIs for models consisting only of typing additionalProperties

### ISSUE THREAD

**Issue by jorgerod** [OpenAPITools/openapi-generator#17580]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

This [PR ](https://github.com/OpenAPITools/openapi-generator/pull/17490) fixed this [bug ](https://github.com/OpenAPITools/openapi-generator/issues/17258) caused by this [PR](https://github.com/OpenAPITools/openapi-generator/pull/16613).

Additionally, when **additionalProperties is typed**, the error is maintained.
##### openapi-generator version

7.1.0 and higher

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 1.7.0
  title: my api
servers:
  - url: http://localhost:8080
    description: Localhost
tags:
  - name: queries
    description: Generic query api
paths:
  /rest/v1/queries:
    post:
      tags:
        - queries
      summary: generic queries
      operationId: postQuery
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/QueryParameters"
      responses:
        '200':
          description: The table data
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    QueryParameters:
      type: object
      additionalProperties: 
        type: string //don't work
```

##### Generation Details

`java -jar openapi-generator-cli.jar generate -g java -i openapi-rest.yml -o openapi --library resttemplate`

##### Steps to reproduce

Generate the provided api-specification using the provided configuration.

The generator logs:
```java
[ERROR] /api/QueriesApi.java:[70,68] cannot find symbol
[ERROR]   symbol:   class QueryParameters
[ERROR]   location: class api.QueriesApi
```

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/17258
- https://github.com/OpenAPITools/openapi-generator/issues/16294
- https://github.com/OpenAPITools/openapi-generator/pull/16613

cc/ @martin-mfg @wing328

**Comment by martin-mfg** [comment]
I will have a look. 👍

Until a fix is merged, you can set `generateAliasAsModel` to `true` as a workaround.
