### ISSUE TITLE
[BUG] PHP/Dart/Python Generator does not escape single quotes in enum values

### ISSUE THREAD

**Issue by JulianVennen** [OpenAPITools/openapi-generator#17582]
##### Description

When an enum value contains a single quote, the character is placed directly into the string, causing invalid code in the PHP, Dart, and Python generators.

##### openapi-generator version
7.2.0

##### OpenAPI declaration file content or url
https://gist.github.com/JulianVennen/d291ae93f80f48a687131418aee7da40

##### Generation Details
The command used is
```sh
openapi-generator-cli generate -g php -i openapi.yaml
openapi-generator-cli generate -g dart -i openapi.yaml
openapi-generator-cli generate -g python -i openapi.yaml
```

##### Steps to reproduce
1. Run the PHP generator with the linked spec
2. Open lib/Model/IssueStatus.php in an editor
3. See that the string is not escaped correctly.

##### Suggest a fix
The single quotes should be escaped using backslashes.
This should be done in the escapeText method of the Codegen classes, like it is already done in the AbstractTypeScriptClientCodegen class.

**Comment by tonybathgate-wk** [comment]
Default values with single quotation marks are also not escaped in generated Dart clients.
