### ISSUE TITLE
[BUG][JAVA] Generator and useJakartaEe still imports package from javax instead of jakarta

### ISSUE THREAD

**Issue by dmbakker** [OpenAPITools/openapi-generator#17590]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

With java Generator, and the option useJakartaEe enabled, the generated pom includes the dependency com.fasterxml.jackson.jakarta.rs:jackson-jaxrs-json-provider and this should have been com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider. The used dependency includes imports from javax instead of jakarta.

##### openapi-generator version

7.2.0

##### Suggest a fix

If useJakartaEe option is enabled for the java generator, the dependency in the pom should be com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider instead of com.fasterxml.jackson.jakarta.rs:jackson-jaxrs-json-provider.

**Comment by wing328** [comment]
> If useJakartaEe option is enabled for the java generator, the dependency in the pom should be com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider instead of com.fasterxml.jackson.jakarta.rs:jackson-jaxrs-json-provider.

Can you please file a PR with the suggested fix?
