### ISSUE TITLE
[BUG][JAVA][JAXRS-Spec] Config option interfaceOnly should generated class RestApplication as well

### ISSUE THREAD

**Issue by verhagen** [OpenAPITools/openapi-generator#17645]
### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

#### Description

When a given OpenAPI specification contains an `info` block, this gets generated as `OpenAPIDefinition` annotation on top 
of the class `RestApplication`. But that class is not generated when the configuration option `interfaceOnly` is set to `true`.

* **Correct:** When using the configuration option `interfaceOnly` is `false` (default), the class `RestApplication` is generated.
* **Incorrect:** When using the configuration option `interfaceOnly` is `true`, the class `RestApplication` is not generated.
  This is **not correct**, the class `RestApplication` should still be generated, especially when the given OpenAPI specification contains an `info` block.

#### openapi-generator version

`7.2.0`

#### OpenAPI declaration file content or url

Any yaml with some `info` block will have this issue.
```yaml
openapi: 3.0.3
info:
  contact:
    name: The API Team
    url: https://organisation.org/the-api-team
    email: the-api-team@organisation.org
```

#### Generation Details

Requires configOptions:

* useMicroProfileOpenAPIAnnotations = true
* interfaceOnly = true

```xml
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.2.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/openapi.yaml</inputSpec>
                            <generatorName>jaxrs-spec</generatorName>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <useMicroProfileOpenAPIAnnotations>true</useMicroProfileOpenAPIAnnotations>

                                <groupId>org.organisation</groupId>
                                <artifactId>some-api</artifactId>
                                <packageName>org.organisation</packageName>
                                <library>quarkus</library>
                                <supportAsync>true</supportAsync>
                                <useJakartaEe>true</useJakartaEe>
                                <dateLibrary>java8</dateLibrary>
                                <sourceFolder>src/main/java</sourceFolder>
                                <useTags>true</useTags>
                                <disallowAdditionalPropertiesIfNotPresent>true</disallowAdditionalPropertiesIfNotPresent>
                                <legacyDiscriminatorBehavior>false</legacyDiscriminatorBehavior>
                                <serializableModel>true</serializableModel>

                                <apiPackage>${default.package}.handler</apiPackage>
                                <modelPackage>${default.package}.model</modelPackage>
                                <invokerPackage>${default.package}.handler</invokerPackage>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

#### Steps to reproduce

Just run the maven plugin

`./mvnw clean generate-sources`

##### Actual Output

_No Java class was generated_

##### Expected Output

_The generated Java class with MicroProfile OpenAPI Annotations_

```java
@org.eclipse.microprofile.openapi.annotations.OpenAPIDefinition(
    info = @org.eclipse.microprofile.openapi.annotations.info.Info(
        version="0.1.0"
        ,title = "Some title"
        ,description = "Some description"
        ,contact = @org.eclipse.microprofile.openapi.annotations.info.Contact(name = "API Team", email = "api-team@organisation.org")
))
@ApplicationPath(RestResourceRoot.APPLICATION_PATH)
public class RestApplication extends Application {

}
```

**Comment by CENGOiSM** [comment]
The generation of RestApplication when interfaceOnly is true seems counterintuitive, especially since the @ApplicationPath annotation is wrong, in my opinion. Right now, we are helping ourselves by deleting RestApplication, but we don't think this behavior is correct...

@verhagen, do you really need ApplicationPath, or do you only need the info annotation?

**Comment by IvoNet** [comment]
is it not possible to just add a  config-option to generate it or not and let that one be active when interfaceOnly is true. Right now I get errors like `Caused by: java.lang.RuntimeException: More than one Application class:` as I already have my own Application class with some security annotations on it. Now I have to remove the RestApplication that was generated after it was generated?! Does not sound good to me.

**Comment by WhiskasChaton** [comment]
> is it not possible to just add a config-option to generate it or not and let that one be active when interfaceOnly is true. Right now I get errors like `Caused by: java.lang.RuntimeException: More than one Application class:` as I already have my own Application class with some security annotations on it. Now I have to remove the RestApplication that was generated after it was generated?! Does not sound good to me.

I have the same issue. Is it possible to have another configOption to generate those RestApplication and RestResourceRoot, independently from  interfaceOnly ?
