### ISSUE TITLE
[BUG] [Perl] Can't locate WWW/OpenAPIClient/Object/AnyType.pm in @INC

### ISSUE THREAD

**Issue by bmodotdev** [OpenAPITools/openapi-generator#17650]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Running `prove -l` on the Perl's petstore sample, the following error is seen:
```
$ cd samples/client/petstore/perl
$ prove -l
[... etc ...]

#   Failed test 'use WWW::OpenAPIClient::Object::TestInlineFreeformAdditionalPropertiesRequest;'
#   at t/TestInlineFreeformAdditionalPropertiesRequestTest.t line 28.
#     Tried to use 'WWW::OpenAPIClient::Object::TestInlineFreeformAdditionalPropertiesRequest'.
#     Error:  Can't locate WWW/OpenAPIClient/Object/AnyType.pm in @INC (you may need to install the WWW::OpenAPIClient::Object::AnyType module) (@INC contains: lib /home/user/git/openapi-generator/samples/client/petstore/perl/lib /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.3/x86_64-linux-thread-multi /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.3 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/5.36.3/x86_64-linux-thread-multi /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/5.36.3 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.1/x86_64-linux-thread-multi /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.1 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl/5.36.0 /home/user/perl5/perlbrew/perls/perl-5.36.0/lib/site_perl) at lib/WWW/OpenAPIClient/Object/TestInlineFreeformAdditionalPropertiesRequest.pm line 33.
# BEGIN failed--compilation aborted at lib/WWW/OpenAPIClient/Object/TestInlineFreeformAdditionalPropertiesRequest.pm line 33.
# Compilation failed in require at t/TestInlineFreeformAdditionalPropertiesRequestTest.t line 28.
# BEGIN failed--compilation aborted at t/TestInlineFreeformAdditionalPropertiesRequestTest.t line 28.
# Looks like you failed 1 test of 1.
t/TestInlineFreeformAdditionalPropertiesRequestTest.t ..
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
t/UserApiTest.t ........................................ ok
t/UserTest.t ........................................... ok

Test Summary Report
-------------------
t/TestInlineFreeformAdditionalPropertiesRequestTest.t (Wstat: 256 (exited 1) Tests: 1 Failed: 1)
Failed test:  1
Non-zero exit status: 1
Files=57, Tests=64,  7 wallclock secs ( 0.07 usr  0.04 sys +  6.02 cusr  0.83 csys =  6.96 CPU)
Result: FAIL
```

The full output is available in my gist [prove1.txt](https://gist.github.com/bmodotdev/6b1500655b3271ad3489b262ab6c3b1f#file-prove1-txt) with master and  [prove2.txt](https://gist.github.com/bmodotdev/6b1500655b3271ad3489b262ab6c3b1f#file-prove2-txt) with pr #17649.

I noticed [docs/generators/perl.md](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/perl.md) has a table of "Data Type Feature" which "AnyType" is marked as :x:. Maybe there is some config option to disable this unimplemented type?

##### openapi-generator version

current master 3756c3b65da18903f66449edcf8631c2ff307e57

##### Steps to reproduce
```
$ perlbrew use perl-5.36.0
$ perlbrew upgrade-perl
$ perlbrew clean
$ perl -E'say $]'
5.036003

$ sudo apt install openjdk-17-jre maven
$ ./mvnw clean package
$ /bin/rm samples/client/petstore/perl/t/*Test.t
$ ./bin/generate-samples.sh ./bin/configs/perl.yaml
$ cpanm Class::Accessor Test::Exception Test::More Log::Any LWP::UserAgent URI::Query Module::Runtime DateTime Module::Find Moose::Role JSON
$ cd samples/client/petstore/perl/
$ prove -l
```

##### Related issues/PRs

PR: #17649 

Around the same domain, PR: #14923 Issue: #14921 

##### Suggest a fix

I am not familiar enough with the project to know the answer here. I am open to being pointed to documentation and doing some follow up work. Thank you

**Comment by wing328** [comment]
filed https://github.com/OpenAPITools/openapi-generator/pull/17651 to fix it
