### ISSUE TITLE
[BUG][JAVA] Nested object not created when setting 'modelsToGenerate'

### ISSUE THREAD

**Issue by luchovl2** [OpenAPITools/openapi-generator#17707]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Model generation ignores nested objects when the property "modelsToGenerate" is used.
When the property is not set, nested objects are created normally.

##### openapi-generator version
7.0.2

##### OpenAPI declaration file content or url

https://gist.github.com/luchovl2/4312b9e51a341599b1567f28d9ecc0d8

##### Generation Details

            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>7.2.0</version>
                <executions>
                    <execution>
                        <id>api-spec</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/swagger/sample-spec.json</inputSpec>
                            <generatorName>java</generatorName>
                            <generateSupportingFiles>true</generateSupportingFiles>
                            <generateApis>false</generateApis>
				<modelsToGenerate>DefinedType</modelsToGenerate>
                            <configOptions>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
##### Steps to reproduce

mvn clean generate-sources

**Comment by jpfinne** [comment]
I don't think there is a bug.

The verbose option is good to know what happens.
It shows this when modelsToGenerate is not specified:

```
      "schemas" : {
        "DefinedType" : {
          "type" : "object",
          "properties" : {
            "nestedObject" : {
              "$ref" : "#/components/schemas/DefinedType_nestedObject"
            },
            "someInteger" : {
              "type" : "integer"
            }
          }
        },
        "DefinedType_nestedObject" : {
          "type" : "object",
          "properties" : {
            "val1" : {
              "type" : "string"
            }
          }
        }
      }
    }

```
So you need to specify 
```
<modelsToGenerate>DefinedType,DefinedType_nestedObject</modelsToGenerate>
```

**Comment by luchovl2** [comment]
Ooh, I see.
It worked, even with more than one layer of nesting.
Thanks a lot. I didn't find any references to this particular situation (using modelsToGenerate with nested).
