### ISSUE TITLE
[BUG][PowerShell] client - Double $MultiPartBoundary generated by Invoke-ApiClient

### ISSUE THREAD

**Issue by condorcorde** [OpenAPITools/openapi-generator#17740]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ x] Have you searched for related issues/PRs?
- [ x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The request generated by Invoke-ApiClient for a multipart/form-data request contains the boundary text twice for all parts except the first and the last:

~~~
Content-Type: multipart/form-data; boundary=---------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Length: 161872
Connection: close

-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Disposition: form-data; name="title"

XXXX_SA.014834.v1.2.pdf
-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Disposition: form-data; name="recordId"

14581
-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Disposition: form-data; name="file"; filename="XXXX_SA.014834.v1.2.pdf"
Content-Type: application/octet-stream
[...]
-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5--
~~~

The expected body is:

~~~
Content-Type: multipart/form-data; boundary=---------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Length: 161677
Connection: close

-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Disposition: form-data; name="title"

XXXX_SA.014834.v1.2.pdf
-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Disposition: form-data; name="recordId"

14581
-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5
Content-Disposition: form-data; name="file"; filename="XXXX_SA.014834.v1.2.pdf"
Content-Type: application/octet-stream
[...]
-----------------------------2b6cc4c8-872c-47ca-9ecf-ab7cd06986c5--
~~~

##### openapi-generator version

The code of the client module in this example was generated by version 7.0.0, but there haven't been changes in the relevant code since.

##### OpenAPI declaration file content or url

The issue is not related to a particular declaration file, it affects all multipart POST requests.

##### Generation Details

NA

##### Steps to reproduce

Generate a multipart POST request and dump the $RequestBody variable in Invoke-ApiClient

##### Related issues/PRs

The code was introduced in #8347

##### Suggest a fix

The following patch generates a multipart request which is accepted by the server I tested.

~~~
*** ApiClient.ps1	Mon Sep  4 18:42:04 2023
--- ~/powershell/Modules/CWPSA/Private/ApiClient.ps1	Mon Jan 29 18:26:49 2024
***************
*** 116,124 ****
                      $RequestBody += "$LF$LF"
                      $RequestBody += ([string]$value)
                  }
!                 $RequestBody += "$LF--$MultiPartBoundary"
              }
!             $RequestBody += "--"
          } else {
              $RequestBody = $FormParameters
          }
--- 116,124 ----
                      $RequestBody += "$LF$LF"
                      $RequestBody += ([string]$value)
                  }
!                 $RequestBody += "$LF"
              }
!             $RequestBody += "--$MultiPartBoundary--"
          } else {
              $RequestBody = $FormParameters
          }
~~~

**Comment by wing328** [comment]
thanks for reporting the issue. Do you mind filing a PR with the suggested fix to start with?

**Comment by condorcorde** [comment]
Hi, I realise that there is a bigger issue with this code. 
$RequestBody is a string, and there is no way that it can accommodate something with MIME type application/octet-stream and binary content. I will have to think about it a little bit longer.

But I have another proposal for improvement. In the same file there is the function Select-Header, which returns the first entry for both "Accept" and "Content-Type". If the API is badly thought, sometimes you may expect a PDF and have instead an error message in JSON, so it would be better that "Accept" supports multiple choices. May I include this change in same PR?

**Comment by wing328** [comment]
> so it would be better that "Accept" supports multiple choices. May I include this change in same PR?

yes please file a PR for this enhancement to start with.

**Comment by wing328** [comment]
Thanks for the PR.

If I remember correctly, we did evaluate Invoke-RestMethod but didn't use it due to some limitations uncovered by our use cases and I can't recall the exact details at the moment.

**Comment by wing328** [comment]
UPDATE: https://www.reddit.com/r/PowerShell/comments/4smvtk/invokerestmethod_response_headers/ looks like the reason.

if it's easy to submit multiipart/form-data via Invoke-RestMethod, then we can selectively use it when the payload is a multipart MIME and users won't get the HTTP headers, response code, etc (documented as a known limitation)

**Comment by condorcorde** [comment]
Interesting, since ConnectWise PSA is one of the application where I extensively use the PowerShell client.
The handling of the response headers and status is what I wanted to investigate next, but for CW in particular there is an alternative solution that does not make use of the Link header altogether. Every GET object method has a GET objectCount counterpart, and by calling it beforehand it is possible to loop the correct number of times. So I just built a helper module on top of the PS client to retrieve all instances of any CW PSA class.

Is openapi-generator supposed to support any version of PowerShell before 7?



[https://www.kyos.ch/wp-content/uploads/2021/07/01.kyos_.logo_.noir300px-1.png]

Alessandro Miotto
[https://www.kyos.ch/wp-content/uploads/2021/06/Arrow_small_2.png] Security Architect


[https://www.kyos.ch/wp-content/uploads/2021/06/line.gif]
41 22 577 65 37
+41 78 647 22 59
***@***.***       Ch. Frank-Thomas 32
CH-1208 Geneva
Rue de l'Avenir 28 CH-1020 Renens
 [cid:icon-kyos-apps-20px_99676364-2eff-4a8d-9cb0-4407fa145510.png] <https://www.kyos.ch>     [cid:linkedin_20_6701f2a8-5961-41d7-b778-7ce26f100dda.png] <https://www.linkedin.com/company/kyos/>     [cid:github-mark_20_088212c5-510d-44b9-a36d-4aaffcd29802.png] <https://github.com/swisskyos>
[https://www.kyos.ch/wp-content/uploads/2021/06/line.gif]
[https://kyoswebpublic.blob.core.windows.net/public/banniere_signature_newyear_kyos.png]
[https://www.kyos.ch/wp-content/uploads/2021/06/line.gif]
“The information contained in this message is intended for the addressee only and may contain classified information. If you are not the addressee, please delete this message and notify the sender; you should not copy or distribute this message or disclose its contents to anyone. Any views or opinions expressed in this message are those of the individual(s) and not necessarily of the organization. No reliance may be placed on this message without written confirmation from an authorised representative of its contents. No guarantee is implied that this message or any attachment is virus free or has not been intercepted and amended.”


<https://www.linkedin.com/company/1672641>
On 2 Feb 2024, at 05:26, William Cheng ***@***.***> wrote:



UPDATE: https://www.reddit.com/r/PowerShell/comments/4smvtk/invokerestmethod_response_headers/ looks like the reason.

if it's easy to submit multiipart/form-data via Invoke-RestMethod, then we can selectively use it when the payload is a multipart MIME and users won't get the HTTP headers, response code, etc (documented as a known limitation)

**Comment by condorcorde** [comment]
With PS 7 it would be enough to remove the old form parameters code and end the ApiClient with:

~~~
    # Use splatting to pass optional parameters
    $Params = @{}
    if ($SkipCertificateCheck -eq $true) {
        $Params.SkipCertificateCheck = $true
    }
    if ($null -ne $Configuration["Proxy"]) {
        $Params.Proxy = $Configuration["Proxy"].GetProxy($UriBuilder.Uri)
        $Params.ProxyUseDefaultCredentials = $true
    }
    if ($MultiPart) {
        $Params.Form = $FormParameters
    } else {
        $Params.Body = $RequestBody
    }

    $Response = Invoke-RestMethod -Uri $UriBuilder.Uri `
                            -Method $Method `
                            -Headers $HeaderParameters `
                            -ErrorAction Stop `
                            -ResponseHeadersVariable "ResponseHeaders" `
                            -StatusCodeVariable "ResponseStatusCode" `
                            @Params

    return @{
        Response = DeserializeResponse -Response $Response -ReturnType $ReturnType -ContentTypes $ResponseHeaders["Content-Type"]
        StatusCode = $ResponseStatusCode
        Headers = $ResponseHeaders
    }
}
~~~

Of course in PS 5 the two last parameters of Invoke-RestMethod do not exist and there should be an extra if statement to use Invoke-WebRequest if $Multipart is false (and change the DeserializeResponse parameters as well).

Is there a way to use different mustache files depending on the version of the client?

**Comment by condorcorde** [comment]
I have a couple of unrelated questions, if you can help without having to open separate threads.
The first is  a bug in the file Client/Configuration.ps1
~~~
  If ($Proxy.GetType().FullName -ne "System.Net.SystemWebProxy" -and $Proxy.GetType().FullName -ne "System.Net.WebRequest+WebProxyWrapperOpaque") {
~~~
Now if I create a proxy directly I can do it via [System.Net.WebProxy]::new() while  [System.Net.SystemWebProxy]::new() returns "Unable to find type".
Furthermore, calling  [System.Net.WebRequest]::GetSystemWebProxy() returns  
* System.Net.WebRequest+WebProxyWrapperOpaque on PS 5, 
* System.Net.Http.HttpWindowsProxy on PS 7/Windows and 
* System.Net.Http.MacProxy on PS 7/MacOS
* System.Net.Http.HttpNoProxy on PS 7/Linux

So the line above is clearly wrong, but it's not clear to me how to rewrite it in a simple way.

---

The second is about authentication. I added this code at the end of a spec file expecting to find some extra client code but found nothing. What did I do wrong?
~~~
    "securitySchemes": {
      "APIkey": {
        "type": "apiKey",
        "name": "Y-API-KEY",
        "in": "header"
      }
    }
  },
  "security": [ {
    "ApiKey": []
    }
  ]
}
~~~

**Comment by wing328** [comment]
> The second is about authentication. I added this code at the end of a spec file expecting to find some extra client code but found nothing. What did I do wrong?

APIkey vs ApiKey ?

**Comment by wing328** [comment]
> So the line above is clearly wrong, but it's not clear to me how to rewrite it in a simple way.

Sorry I don't recall anything about this line.

If I remember correctly, it was contributed by others.

For your use cases, you need to use a proxy, right?

**Comment by condorcorde** [comment]
I need a proxy only for testing issues, but with several client libraries.
However I may have found a suitable solution from the command
~~~
PS > [System.Net.WebRequest] | Get-Member -Static -Name GetSystemWebProxy
~~~

https://github.com/condorcorde/openapi-generator/commit/5120fc739dc789032f092693dbf16b13929dabcc
