### ISSUE TITLE
[BUG] Usage of ref and description on a field does not work

### ISSUE THREAD

**Issue by oszust002** [OpenAPITools/openapi-generator#17760]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I was trying to generate object with property (openapi 3.0, kotlin-spring), which had ref, and wanted to add description to the property itself, it was not possible in any way. I was trying both usage of `allOf` + `description` or putting `description` inside referenced object, there was no way to somehow get property containing description.

Additionally generator created some strange duplicate of a class instead of putting actual class.

What I got from generator:
```kotlin
package com.example

import java.util.Objects
import com.example.ExampleDTOReffedProperty
import com.fasterxml.jackson.annotation.JsonProperty
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 * 
 * @param reffedProperty 
 */
data class ExampleDTO(

    @field:Valid
    @Schema(example = "null", description = "")
    @field:JsonProperty("reffedProperty") val reffedProperty: ExampleDTOReffedProperty? = null
) {

}
```

What I expected:
```kotlin
package com.example

import java.util.Objects
import com.example.ExampleSubDTO
import com.fasterxml.jackson.annotation.JsonProperty
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Email
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size
import javax.validation.Valid
import io.swagger.v3.oas.annotations.media.Schema

/**
 * 
 * @param reffedProperty 
 */
data class ExampleDTO(

    @field:Valid
    @Schema(example = "null", description = "Some fancy description")
    @field:JsonProperty("reffedProperty") val reffedProperty: ExampleSubDTO? = null
) {

}
```

##### openapi-generator version

6.0.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Example
  version: 1.0.0
  contact:
    name: user
    email: user@user.com
paths:
  /example-api:
    get:
      tags:
        - example
      operationId: exampleApi
      summary: Not important
      responses:
        200:
          description: example description in responses
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    ExampleDTO:
      type: object
      properties:
        reffedProperty:
          allOf:
            - $ref: '#/components/schemas/ExampleSubDTO'
          description: Some fancy description
    ExampleSubDTO:
      type: object
      properties:
        examplePropertyInSub:
          type: string
          description: Property description
          example: property
```
##### Generation Details
language - kotlin spring
config file used:
```json
{
  "library": "spring-boot",
  "modelPackage": "com.example",
  "apiPackage": "com.example",
  "packageName": "com.example",
  "skipDefaultInterface": true,
  "interfaceOnly": true,
  "implicitHeaders": true,
  "java8": true,
  "swaggerAnnotations": true,
  "enable-post-process-file": "true"
}
```
\+ useTags was used. I was using generator through https://github.com/int128/gradle-swagger-generator-plugin so not sure what properties are important or how to run it through the CLI

##### Steps to reproduce

Generate model with openapi-generator

**Comment by wing328** [comment]
i think we've this issue fixed in the latest master. can you please give it a try?
