### ISSUE TITLE
[BUG][PYTHON] Python client can't deserialize string enum response

### ISSUE THREAD

**Issue by joeka** [OpenAPITools/openapi-generator#17789]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated python clients can't deserialize a response that was defined as string with possible values specified as an enum.

It ends up calling a non-existing from_dict method on the enum class.

- Template for the enum: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_enum.mustache
- from_dict called here: [https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cf[…]openapi-generator/src/main/resources/python/api_client.mustache](https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cfedaa14709a56a/modules/openapi-generator/src/main/resources/python/api_client.mustache#L754)
- coming from __deserialize here: [https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cf[…]openapi-generator/src/main/resources/python/api_client.mustache](https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cfedaa14709a56a/modules/openapi-generator/src/main/resources/python/api_client.mustache#L440)

So basically: if there is a response for an api endpoint defined as string enum, the client assumes it has to be a dict or similar after json decoding, because it is defined as a model class and then tries to call a non-existing from_dict method. From dict doesn't make any sense anyway, as the response value in JSON is a string. For other enums it could be other basic types.

##### openapi-generator version

7.1.0, 7.2.0 and 7.3.0-SNAPSHOT

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  title: test api
  version: 1.0.0-SNAPSHOT
paths:
  /status:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Status:
      enum:
        - NEW
        - SCHEDULED
        - RUNNING
      type: string
```

##### Generation Details

I used openapi-generator-maven-plugin, only setting the generateSourceCodeOnly option, but should be the same with the cli.

##### Steps to reproduce

1. Create a rest endpoint returning an string enum value as json (probably the same with other enums)
2. Create a python client with the openapi generator for the specs of (1.) (or the provided example)
3. Call the endpoint using the client -> crashes with
```
[undefined]AttributeError: from_dict
.venv\Lib\site-packages\pydantic\_internal\_validate_call.py:113: in __call__
    res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
src\test_client\api\test_internal_api.py:4389: in restore_status_specific_storage
    return self.api_client.response_deserialize(
src\test_client\api_client.py:314: in response_deserialize
    return_data = self.deserialize(response_text, response_type)
src\test_client\api_client.py:390: in deserialize
    return self.__deserialize(data, response_type)
src\test_client\api_client.py:429: in __deserialize
    return self.__deserialize_model(data, klass)
src\test_client\api_client.py:731: in __deserialize_model
    return klass.from_dict(data)
```

##### Suggest a fix

Should Enums be handled in [api_client.mustache](https://github.com/OpenAPITools/openapi-generator/blob/334ddca0217cfcb8c2b5791c3cfedaa14709a56a/modules/openapi-generator/src/main/resources/python/api_client.mustache#L754)?

**Comment by wing328** [comment]
```
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
```

Just so we're on the same page, the response body is something like the following right?

```
"SCHEDULED"
```

(note that it's double-quoted)

**Comment by joeka** [comment]
Yes, exactly.
