### ISSUE TITLE
[BUG] [JAVA] 7.3.0 adds @lombok.NonNull on all required fields when any lombok annotation is included

### ISSUE THREAD

**Issue by Squeeeez** [OpenAPITools/openapi-generator#17831]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

https://github.com/OpenAPITools/openapi-generator/pull/17622 adds more lombok support, which is great!
As soon as any lombok annotation is included, every required field on the models now gets annotated with @lombok.NonNull
which adds a null check where none was present before (i.e. with 7.2.0) when using for example a lombok constructor or builder.

As such a breaking change which suddenly starts throwing NullPointerExceptions where none were thrown before it would be nice to have a way to configure such behaviour.

##### openapi-generator version

7.3.0-SNAPSHOT

##### OpenAPI declaration file content or url

The [yaml configuration](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/configs/spring-boot-lombok-tostring.yaml)
The [generated sample](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/springboot-lombok-tostring) 

##### Generation Details

bin/config-generate-samples.sh bin/configs/spring-boot-lombok-tostring.yaml

##### Steps to reproduce

Include any lombok class in `additionalModelTypeAnnotation`, mark a model attribute as required

##### Suggest a fix

I would suggest the use of a configuration possibility similar to `useBeanValidation`, either to disable `@lombok.NonNull`, or to choose which library is used for such Nullable/NonNull annotations. What are your thoughts?

**Comment by jpfinne** [comment]
@Squeeeez

The lombok generation has many issues:  see #17793

What is your use case of `@lombok` annotations in generated code?
What do you miss from the non `@lombok` code?
Just AllArgArguments constructor and builder or something else?

I ask because pojo.mustache becomes too complex.  I would like to delombok it.

**Comment by vzorge** [comment]
@jpfinne Most people I know use it for the Builder. It makes writing tests a lot better to read when the POJO's have a Builder. Altough personally I think having the setters, or extra fluent setter names that return _this_ work fine as well.

In tests this is better to understand:
```
val someFoo = Foo.builder()
        .somefield("something")
        .bar(Bar.builder()
               .someBarField("barField")
        .build()
```

Then

```
val someBar = new someBar();
someBar.setSomeBarField("barField");
val someFoo = new Foo();
foo.setBar(someBar);
foo.setSomeField("someField");
```

Especially when the objects are quite large with lots of nesting
