### ISSUE TITLE
[BUG][golang][7.3.0] Generated model accessor functions have incorrect boolean logic for array types

### ISSUE THREAD

**Issue by jduplaid** [OpenAPITools/openapi-generator#17835]
Given a schema with a field that has type `array` like this:

```
"Foo": {
   "type": "object",
   "properties": {
        "data": {
           "type": "array",
           "items": {
              "$ref": "#/components/schemas/Bar"
           },
           "nullable": true
        },
        ...
    } 
}
```

our generated models have functions like:
```
// HasData returns a boolean if a field has been set.
func (o *Foo) HasData() bool {
	if o != nil && IsNil(o.Data) {
		return true
	}

	return false
}
```

shouldn't the boolean to check if the Foo model has data be `o != nil && !IsNil(o.Data)`, rather than `o != nil && IsNil(o.Data)`?

another accessor function also gets generated:
```
func (o *Foo) GetDataOk() ([]Bar, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}
```
`GetDataOk` seems correct, and applying DeMorgan's law, that indicates `HasData` should use `o != nil && !IsNil(o.Data)`

We are using v7.3 openapi-generator, but we believe the issue is present in 7.2 as well

**Comment by wing328** [comment]
> shouldn't the boolean to check if the Foo model has data be o != nil && !IsNil(o.Data), rather than o != nil && IsNil(o.Data)?

I think so

can you please file a PR when you've time?

**Comment by jduplaid** [comment]
@wing328 looks like @sagarkhot3 already created a fix here: https://github.com/OpenAPITools/openapi-generator/pull/17840, if you can help take a look at that - thanks!
