### ISSUE TITLE
[BUG][JAVA] Feign : Reference to RetryableException is ambiguous

### ISSUE THREAD

**Issue by jijins1** [OpenAPITools/openapi-generator#17842]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm trying generate a feign client with Authentification.
The code is well generated but not compile with an error "reference to RetryableException is ambiguous"

##### openapi-generator version

7.3.0

##### Generation Details

Feign Version : 7.3.1

##### Steps to reproduce

Generate a client with oauth authentification. 
Use Feign 7.3.1

##### Suggest a fix
I think the ambiguity is added from this commit 
https://github.com/OpenFeign/feign/commit/be25759e93d2b94408b44270013d8379ec9b47bd
I think adding a cast of the null value in date  (For compatibiliy with older feign version) should be valid
I will propose a pr

**Comment by arnogeismar** [comment]
Hi can we already use this fix? Regards,

**Comment by clemensul** [comment]
@arnogeismar Version 7.4.0 fixed it for me.
