### ISSUE TITLE
[BUG][JAVA] Multiple generated Feign clients are not working

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#17847]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

Description
If different Feign clients are generated, then multiple ClientConfigurations will be created with the same beans. This means that the clients cannot be initialized.

In my opinion, the `@Configuration` should be removed and the configuration should be specified in @EnableFeignClient or is currently also directly in the `FeignClient`. So it works without `@Configuration`.

The bigger issue is the ClientPropertiesConfiguration which loads, the properties. Maybe there should be a flag if the ClientPropertiesConfiguration should be generated or not. And also can be imported with @Import from spring
https://www.baeldung.com/spring-import-annotation

`Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'clientConfiguration' for bean class [test.client2.config.ClientConfiguration] conflicts with existing, non-compatible bean definition of same name and class [test.client1.config.ClientConfiguration]
`
openapi-generator version
7.3.0

Steps to reproduce
See example here:
https://github.com/MelleD/open-api-feign-client-example

**Comment by MelleD** [comment]
@borsch and @welshm 

I need your help and opinion here. I think the main issue is clear. We have issues with Spring Configuration, because the class names are hardcoded and always the same. When we have multiples clients, then this crash the bean creation, because of duplicated bean and config names.

The first issue is easy. We have just to remove the @Configuration here
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientConfiguration.mustache#L38 

But for the second file it's a little more complex:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/clientPropertiesConfiguration.mustache

Options:
- We could add the package name into the @Configuration like the proposal here, BUT this not very typically for spring applications https://github.com/OpenAPITools/openapi-generator/pull/17738
- We could remove the @Configuration and the users have to be import the configuration with @Import(ClientPropertiesConfiguration.class)
- Maybe it's possible to remove the ClientPropertiesConfiguration and add the @PropertySource into the ClientConfiguration.mustache 
- Or we just remove this funcionality, because it's just a shortcut to reduce some configs, but not sure if this function is really valueable. 

Second issue is that currently the https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/libraries/spring-cloud/oauth2ClientProperties.mustache will always overwritten, because the name is always the same.
Here my question, can we use the name for the security scheme for the name. How can I use this {{{name}}} into the code generator?
https://github.com/OpenAPITools/openapi-generator/blob/ec42f88c6a27a0d422390ecdf5adb5785b2be5e7/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L597

What do you think? Do you have any other ideas?
Thank you for your help :)

**Comment by welshm** [comment]
I actually like the first option. I agree it's not typical for Spring applications, but otherwise I think that removing the `@Configuration` just moves the problem somewhere else. If you still need those beans configured, it's just more boilerplate for users of the generator to setup (and understand).

Using the full package name for the bean name avoids the collisions, and would hopefully allow generating N number of clients and having the configurations just work. Although having a generator option would be nice (`standardConfiguration`, `fullPackageNameConfiguration`, `noConfiguration`) so that people could customize it for how they prefer to setup their spring projects.

Having to use the `@Import()` works for strong users of Spring, but probably a bit harder for anyone not that experienced with Spring to know that they need to add it. Personally for my Spring projects I don't like autoconfiguration so I use `@Import` a lot - but I don't think that's a common practice.


For the second question - I haven't worked much with the security schema generation but the name property must be derived from somewhere. I can take a look this weekend hopefully if you haven't done it by then

**Comment by MelleD** [comment]
@welshm thanks for the answer.

There are multiple issues:
First issue, for the feign client we have to remove the global `@Configuration`, because it's already declared in the `@FeignClient`. Thats easy just remove the `@Configuration`. I think there is no discussion, because it have to be scoped. Therefore spring feign have this config.

The second issue is more "our" issue. Iam not sure if we really need a  `@Configuration` to load a properties file and also how valuable is this properties files. Look it just load this properties

```
spring.security.oauth2.client.registration.xxx.enabled=false
spring.security.oauth2.client.registration.xxx.client-id=set-xxx-client-id
spring.security.oauth2.client.registration.xxx.scope=openid
spring.security.oauth2.client.registration.xxx.authorization-grant-type=client_credentials
spring.security.oauth2.client.provider.macmaApplication.token-uri=https:xxx
```

But if we really need Configuration to load this :). Also we need then multiple files not always the same one

**Comment by MelleD** [comment]
Ok one idea is:

We use the ClientPropertiesConfiguration with package name and add a PropertySourcesPlaceholderConfigurer with all properties. Then I can remove the property file and the naming issue is gone

**Comment by MelleD** [comment]
@welshm here what I would do :)
https://github.com/OpenAPITools/openapi-generator/pull/17860
