### ISSUE TITLE
[BUG] @Valid TYPE_USE is not compatible with Schema mapping 

### ISSUE THREAD

**Issue by vietk** [OpenAPITools/openapi-generator#17888]
#### Bug Report Checklist
- [x] Have you searched for related issues/PRs?

##### Description

I am migrating from openapigenerator version 7.1.0 to 7.3.0, I am encountering a regression on the schema mapping functionality combined with the schema validation.

I am using schema mapping to provide external packaged class to be used instead of part of the generated grammar 

```xml
<schemaMappings>
  <schemaMapping>
     TypeToMap=com.my.company.TheRealClass
  </schemaMapping>
<schemaMappings>
```

Now using that last version of the generator code I have

```java
private @Valid List<@Valid com.my.company.TheRealClass> list;
```

And I get a compilation error : 

```shell
error: cannot find symbol
 symbol:   class com
```

The usage of annotation is prohibited here because the generation uses the fully qualified name of the supplied type mapping ([9.7.4](https://docs.oracle.com/javase/specs/jls/se17/html/jls-9.html#jls-9.7.4))

> A type annotation is admissible if both of the following are true:
> - The simple name to which the annotation is closest is classified as a TypeName, not a PackageName.
> - If the simple name to which the annotation is closest is followed by "." and another TypeName - that is, the annotation appears as @Foo T.U - then U denotes an inner class of T.

##### openapi-generator version

regression in  7.3.0

##### Steps to reproduce

1. Define a schema mapping to bind a grammar external to the defined schemas
2. Disable bean validation with `<useBeanValidation>false</useBeanValidation>` (is has no impact on the failure of the generation) 

##### Related issues/PRs

#17874

##### Suggest a fix

A solution to consider is to import the mapped class and use the type name in the usage of the annotation.
Or simply use #17874 to disable validation and workaround

**Comment by jpfinne** [comment]
There is a fix in https://github.com/OpenAPITools/openapi-generator/pull/17730
