### ISSUE TITLE
[BUG] serializableModel generates "extends" instead of "implements"

### ISSUE THREAD

**Issue by thorstenhirsch** [OpenAPITools/openapi-generator#17895]
##### Description

When generating Java code with `serializableModel=true` the result is faulty.

expected result:
```java
public class MyClass implements Serializable {
}
```

current result (simplified):
```java
public class MyClass extends Serializable {
}
```

In my case there was already an class from which to extend, so Serializable was just added:
current result:
```java
public class MyClass extends Something, Serializable {
}
```

##### openapi-generator version

7.3.0 with Java 17 and Java 21

##### OpenAPI declaration file content or url & Generation Details

Just use any OpenAPI JSON with the following command to generate the Java code:
```sh
java -jar libs/openapi-generator-cli-7.3.0.jar generate \
      -i ./my.json -g java -o genc \
      --additional-properties library=native,serializableModel=true
```

##### Steps to reproduce

1. Generate code
2. Check classes for "Serializable"

**Comment by martin-mfg** [comment]
Hi,
in my tests with your described settings, it worked fine. Here's an example of the output I get: `public class MyObject extends HashMap<String, Object> implements Serializable {`.
If the problem persists for you, please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by thorstenhirsch** [comment]
Just reproduced the issue with version 7.4.0. You can use the attached Test-OpenAPI.json to reproduce the issue. With the following call you will get a class `de.my.client.mode.CoreBar` with a faulty `Serializable` declaration.
```sh
$ java -jar openapi-generator-cli-7.4.0.jar generate -i ./Test-OpenAPI.json -g java -o genc --additional-properties library=native,serializableModel=true --invoker-package=de.my.client --model-package=de.my.client.model --api-package=de.my.client.api
```

```java
public class CoreBar extends AbstractOpenApiSchema, Serializable { ... }
```

[Test-OpenAPI.json](https://github.com/OpenAPITools/openapi-generator/files/14775299/Test-OpenAPI.json)

**Comment by thorstenhirsch** [comment]
I could break down the problem to this parameter:
```sh
library=native
```
Without this parameter the generator works correctly.

**Comment by martin-mfg** [comment]
Thanks for the clarification. I could reproduce the issue now and created a fix for it.
