### ISSUE TITLE
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined

### ISSUE THREAD

**Issue by wqvv** [OpenAPITools/openapi-generator#17903]
##### Description

when i use openapi-generator to generate go client code, i got some warns said "#/components/schemas/Exchange/properties/id is not defined", but i have already defined the component

##### openapi-generator version

v7.3.0

##### OpenAPI declaration file content or url
[openapi.yaml.zip](https://github.com/OpenAPITools/openapi-generator/files/14340968/openapi.yaml.zip)

##### Generation Details

[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Exchange/properties/id is not defined

[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/to_type is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined
[main] WARN  o.o.codegen.utils.ModelUtils - #/components/schemas/Transaction/properties/status is not defined

##### Steps to reproduce

openapi-generator generate --additional-properties=packageName=CoboPortal -i openapi.yaml -g go -o portal_go_sdk --git-repo-id cobo-portal-go-api --git-user-id CoboGlobal --global-property debugOpenAPI>> output.txt

**Comment by jpfinne** [comment]
You use references to inner properties:
```
components:
  schemas:
    Exchange:
      type: object
      properties:
        id:
          type: string
          enum:
            - Binance
    CreateExchangeWallet:
       type: object
       properties:
          exchange:
             $ref: '#/components/schemas/Exchange/properties/id'
```

The issue is that Models.unaliasSchema does not support it.  It only finds references to "top" level schemas (ie directly under component.schemas)

You can get rid of the warning by declaring a dedicated type
```
components:
  schemas:
    ExchangeId:
      type: string
      enum:
         - Binance
    Exchange:
      type: object
      properties:
        id:  
          $ref: '#/components/schemas/ExchangeId'
    CreateExchangeWallet:
      type: object
      properties:
        exchange:
          $ref: '#/components/schemas/ExchangeId'          
```
