### ISSUE TITLE
[REQ] Support for JSON Schema Additional Properties 

### ISSUE THREAD

**Issue by jeffreywstevens** [OpenAPITools/openapi-generator#17917]
Maybe this already exists by another convention. A command line property settings?

I have used other C# code generators. What I liked about OpenAPI-Generator was the creation of the entire C# project and the bonus: unit tests.

I created a Github actions pipeline to:
1. download the open API contract.
2. Generate C# projects
3. Publish Nuget Package

Once I tried to swap the models, I discovered the lack of Additional Properties.  Others support JSON Schema Additional Properties by default, allowing for a dictionary of extra properties at every level.

Usually, this is manifested by the following:

<img width="793" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/637945/b487d1b3-aed4-400c-a4e8-4759cc7f33d0">

Does this already exist by some other convention?

**Comment by wing328** [comment]
did you set `disallowAdditionalPropertiesIfNotPresent` to false in the generator's option?

https://openapi-generator.tech/docs/generators/csharp/

**Comment by jeffreywstevens** [comment]
I don't use the config. I saw that and the default is what I want. This is my CLI in my pipeline.

<img width="764" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/637945/047b4711-da92-469e-8891-a45f03a54bc4">

**Comment by wing328** [comment]
can you try setting the option to false, which will have the models support additional properties in C#?

**Comment by jeffreywstevens** [comment]
Can I set it via a command line switch or do I have to create a config file?

**Comment by wing328** [comment]
please add `--additional-properties disallowAdditionalPropertiesIfNotPresent =false` to your CLI

**Comment by jeffreywstevens** [comment]
That did it! I should have just RTFM. Thanks for your help!

**Comment by jeffreywstevens** [comment]
It seems there is a problem with additional properties regarding inheritance after I got inheritance working with other command line properties.  It is adding in the code for the JsonExtensionData even thought it is already there from the inherited base class.
<img width="750" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/637945/d2aff31c-5496-4823-87fc-33826070253f">
