### ISSUE TITLE
[REQ][CppUE4] modelName, modelFilename non camelize

### ISSUE THREAD

**Issue by powerumc** [OpenAPITools/openapi-generator#17981]
### Is your feature request related to a problem? Please describe.

Our unreal projects have a naming convention.
We redefined the Schema name in Swagger on our server to follow the client naming rules.

Use the class name `FT1Model_` for the model class and `FT1Protocol_` for the request object.
Also, in C++, '_' naming is very natural in some cases.

However, the CppUE4 generator always uses camelcase, so `_` characters are removed from file names and class names.
I expected a class name, file name with the name `FT1Model_HelloWorldRequest`, but it always returns the camelcase name `FT1ModelHelloWorldRequest`.

## Describe the solution you'd like

I added additionalProperties of `modelNameCamelize` and `modelFilenameCamelize` to solve this.
Made CppUE4ClientCodegen.toModelFilename, toModelName methods return camelcase or non camelcase depending on options.

## Describe alternatives you've considered

I tried to solve this in the mustache template, but it wasn't possible.

## Additional context

If my suggestion is appropriate, I would like to make a Pull Request for the added features.

**Comment by wing328** [comment]
if it's not a lot of work, can you please file a PR to start with and we'll review accordingly

**Comment by powerumc** [comment]
Thank you in advance for the review.
I will make a Pull Request soon.
