### ISSUE TITLE
[BUG] Can't serialize objects when `Enum` are defined within an `Object` 

### ISSUE THREAD

**Issue by rvalim** [OpenAPITools/openapi-generator#17999]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version 

7.3.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
components:
  schemas:
    TransportLocation:
      example:
        iataCode: ZRH
        locationType: AIRPORT
      properties:
        iataCode:
          description: IATA code for the location
          example: ZRH
          type: string
        locationType:
          description: Type of the transport location
          enum:
          - UNKNOWN
          - AIRPORT
          - TRAIN_STATION
          - BUS_STATION
          - AREA
          example: AIRPORT
          type: string
      required:
      - iataCode
      - locationType
      type: object
```

##### Generation Details
 
When generating code based on the provided yaml, there is no  for the any enumeration property defined within an object. 
Taking `locationType` as an example, I could solve it by first declaring an `Enum` object and then adding its reference to the `TransportLocation`, solution below:

```
    TransportLocationType:
      description: Type of the transport location
      enum:
        - UNKNOWN
        - AIRPORT
        - TRAIN_STATION
        - BUS_STATION
        - AREA
      type: string
      example: AIRPORT

    TransportLocation:
      example:
        iataCode: ZRH
        locationType: AIRPORT
      properties:
        iataCode:
          description: IATA code for the location
          example: ZRH
          type: string
        locationType:
          $ref: '#/components/schemas/TransportLocationType'
      required:
      - iataCode
      - locationType
      type: object
```

Only after that the properly `EnumNameSerializer`/`Converted` were created:

Scala version:
<img width="616" alt="Screenshot 2024-02-29 at 08 07 23" src="https://github.com/OpenAPITools/openapi-generator/assets/1134063/010ad8ae-442d-4800-a269-98fa74b56d7b">

Java version:
<img width="773" alt="Screenshot 2024-02-29 at 07 58 26" src="https://github.com/OpenAPITools/openapi-generator/assets/1134063/67b6a28f-86a8-42dc-9134-ebbd200b3e46">

##### Steps to reproduce

`openapi-generator generate -c <yaml file path>`

##### Related issues/PRs

Didn't found any one.

**Comment by martin-mfg** [comment]
Hi, I just created a fix for this problem. After the fix is released, you need to set `RESOLVE_INLINE_ENUMS` to `true` ([documented here](https://openapi-generator.tech/docs/customization/#inline-schema-naming)) for the Converters to be generated.
