### ISSUE TITLE
[BUG][JAVA - SPRING] Generates different annotations for List elements

### ISSUE THREAD

**Issue by DatApplePy** [OpenAPITools/openapi-generator#18008]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Based on what I found in the AbstractJavaCodegen, it generates different annotations for E in List<E>.
Using $ref in items -> only @ Valid
Defining schema in items -> eg. @ Pattern and @ Size

##### openapi-generator version
7.3

##### OpenAPI declaration file content or url
```yaml
category:
  type: array
  maxItems: 20
  items:
    #$ref: "#/components/schemas/string50"
    type: string
    pattern: "^[a-zA-Z0-9 .:!()-]$"
    maxLength: 50

string50:
  type: string
  pattern: "^[a-zA-Z0-9 .:!()-]$"
  maxLength: 50
```

##### Generation Details
Gradle config
```gradle
openApiGenerate {
    generatorName.set('spring')
    inputSpec.set("$layout.projectDirectory/api/api.yaml")
    outputDir.set("$layout.projectDirectory/build/api")
    templateDir.set("$layout.projectDirectory/templates")
    apiPackage.set('<my-package>.web-api')
    modelPackage.set('<my-package>.web-model')
    globalProperties.set([
            generateSupportingFiles: 'false',
            skipFormModel: 'false',
            models: '',
            apis: '',
    ])
    configOptions.set([
            delegatePattern: 'true',
            openApiNullable: 'false',
            skipDefaultInterface: 'true',
            useSpringBoot3: 'true',
    ])
}
```
---
Generated with $ref
```java
private List<@Valid String> category;
```
---
Generated without $ref
```java
private @Valid List<@Pattern(regexp = "^[a-zA-Z0-9 .:!()-]$") @Size(max = 50) String> category;
```

##### Suggest a fix
[Possible source of issue - AbstractJavaCodegen](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L969)

**Comment by wing328** [comment]
can you try the latest master which should have better support for this use case?

snapshot version can be found in the project's readme

**Comment by DatApplePy** [comment]
@wing328 as you suggested, I tried the latest (openapi-generator-cli-7.4.0-20240229.081737-58.jar | Thu Feb 29 08:20:59 UTC) but unfortunately the issue still exists.

**Comment by wing328** [comment]
thanks for testing the snapshot version. My fix was for fixing validation attributes along side a $ref (so not the exact same use case as yours)

@Aliaksie can you please take a look at this issue when you've time?

**Comment by Aliaksie** [comment]
> thanks for testing the snapshot version. My fix was for fixing validation attributes along side a $ref (so not the exact same use case as yours)
> 
> @Aliaksie can you please take a look at this issue when you've time?

Hey @wing328 ! Thanks for letting me know. here is a [PR](https://github.com/OpenAPITools/openapi-generator/pull/18014) that should solve this problem, please have a look when you've time!
