### ISSUE TITLE
[BUG / Question] [Java] [Spring]: "format: ipv4" no validation added

### ISSUE THREAD

**Issue by maxl2287** [OpenAPITools/openapi-generator#18007]
##### Description
I have a component for an IPv4-Address.
This has the "format: ipv4".

Is there a possibility to have here a validation?

##### openapi-generator version

7.3.0

##### OpenAPI declaration file content or url

```yaml
    SingleIpv4Addr:
      description: A single IPv4 address with no subnet mask
      type: string
      format: ipv4
      example: "84.125.93.10"
```

##### Generation Details

<plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>7.3.0</version>
        <executions>
          <execution>
            <id>server</id>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/src/main/resources/static/api.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <apiPackage>com.api</apiPackage>
              <modelPackage>com.api.model</modelPackage>
              <supportingFilesToGenerate>ApiUtil.java</supportingFilesToGenerate>
              <configOptions>
                <additionalModelTypeAnnotations>
                  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                </additionalModelTypeAnnotations>
                <useSpringBoot3>true</useSpringBoot3>
                <delegatePattern>true</delegatePattern>
                <useJakartaEe>true</useJakartaEe>
                <openApiNullable>false</openApiNullable>
                <generatedConstructorWithRequiredArgs>false</generatedConstructorWithRequiredArgs>
              </configOptions>
              <generateApiTests>false</generateApiTests>
              <generateModelTests>false</generateModelTests>
              <globalProperties>
                <apis>roaming,connectivity,subscriptions</apis>
              </globalProperties>
              <openapiNormalizer>
                REFACTOR_ALLOF_WITH_PROPERTIES_ONLY=true
                SIMPLIFY_ANYOF_STRING_AND_ENUM_STRING=true
              </openapiNormalizer>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by maxl2287** [comment]
@wing328 do you have a suggestion for that?

**Comment by martin-mfg** [comment]
Hi @maxl2287,
OpenAPI Generator doesn't generate validation for "ipv4" out of the box. You could define a regex [pattern](https://swagger.io/docs/specification/data-models/data-types/#pattern) for `SingleIpv4Addr` to add appropriate validation.
And the OpenAPI Generator project happily welcomes PRs to add the missing ipv4 validation functionality. As a starting point, [here](https://github.com/OpenAPITools/openapi-generator/blob/81f576c9dac4e3dca58a54d76f2039aff0181f03/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L1066C1-L1068C10) is where email validation is implemented.

**Comment by maxl2287** [comment]
I will close this issue, as it is no bug yet.
