### ISSUE TITLE
[BUG] cshar .net6 DateOnly not nullable

### ISSUE THREAD

**Issue by Noudicus** [OpenAPITools/openapi-generator#18017]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a client for csharp .net6 the nullable parameter is not applied to the DateOnly property

##### openapi-generator version

v7.3.0

##### OpenAPI declaration file content or url
```json
{
    "openapi": "3.0.1",
    "info": {
        "title": "Test API",
        "description": "Test",
        "contact": {
            "name": "Test",
            "email": "api@test.com"
        },
        "version": "1.0"
    },
    "servers": [
        {
            "url": "https://api.test.net"
        }
    ],
    "security": [
        {
            "oAuth2": []
        }
    ],
    "tags": [        
        {
            "name": "Reservation",
            "description": "test"
        }
    ],
    "paths": {
        "/v1/Reservation": {
            "get": {
                "tags": [
                    "Reservation"
                ],
                "summary": "Test",
                "description": "Test",
                "operationId": "getReservation",
                "responses": {
                    "200": {
                        "description": "The request is completed successfully without any errors",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Reservation"
                                }
                            }
                        }
                    },
                    "404": {
                        "description": "No resorts found for given criteria."
                    },
                    "500": {
                        "description": "Error occurred while fetching Reservation."
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {            
            "Reservation": {
                "type": "object",
                "properties": {
                    "tncSignedDate": {
                        "type": "string",
                        "format": "date",
                        "nullable": true
                    }
                }
            }
        }
    }
}
```
##### Generation Details

Config:
```json
{
    "packageName": "Test.PublicApi",
    "packageVersion": "2024.3.1.1",
    "targetFramework": "net6.0"
}
```
java -jar ../Generator/openapi-generator-cli-7.3.0.jar generate -g csharp -i openapi.json -o output --config config/GeneratorConfig.json

##### Steps to reproduce

Generate above

**Comment by 0x326** [comment]
Can confirm. It generates code like this, even though it is marked as `nullable: true`:

```csharp
    [DataContract(Name = "cargoReadyDate")]
    public partial class CargoReadyDate : IEquatable<CargoReadyDate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CargoReadyDate" /> class.
        /// </summary>
        /// <param name="currentValue">currentValue.</param>
        /// <param name="previousValue">previousValue.</param>
        public CargoReadyDate(DateOnly currentValue = default(DateOnly), DateOnly previousValue = default(DateOnly))
        {
            this.CurrentValue = currentValue;
            this.PreviousValue = previousValue;
        }

        /// <summary>
        /// Gets or Sets CurrentValue
        /// </summary>
        [DataMember(Name = "currentValue", EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateOnly CurrentValue { get; set; }

        /// <summary>
        /// Gets or Sets PreviousValue
        /// </summary>
        [DataMember(Name = "previousValue", EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateOnly PreviousValue { get; set; }
```

```csharp
    /// <summary>
    /// Formatter for 'date' openapi formats ss defined by full-date - RFC3339
    /// see https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#data-types
    /// </summary>
    public class OpenAPIDateConverter : IsoDateTimeConverter
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OpenAPIDateConverter" /> class.
        /// </summary>
        public OpenAPIDateConverter()
        {
            // full-date   = date-fullyear "-" date-month "-" date-mday
            DateTimeFormat = "yyyy-MM-dd";
        }
    }
```

**Comment by MichaelMay81** [comment]
Made a TestProject to collect errors regarding DateOnly, which includes this error: https://github.com/MichaelMay81/OpenApiGeneratorTest

**Comment by jpduchon** [comment]
I recognized that DateOnly will only be handled as a nullable value type when using the library GENERICHOST.
When using the library HTTPCLIENT I experience the same problem as described in this issue.
Adding DateOnly to the getNullableTypes and getValueTypes method in CSharpClientCodegen fixes the error for me.

What is the reason why some types are not present in the overrrides of getNullableTypes (e.g. Dateonly) and getValueTypes (e.g. DateTime, DateOnly, DateTimeOffset, Guid) when the library isn't GENERICHOST?

**Comment by devhl-labs** [comment]
> I recognized that DateOnly will only be handled as a nullable value type when using the library GENERICHOST. When using the library HTTPCLIENT I experience the same problem as described in this issue. Adding DateOnly to the getNullableTypes and getValueTypes method in CSharpClientCodegen fixes the error for me.
> 
> What is the reason why some types are not present in the overrrides of getNullableTypes (e.g. Dateonly) and getValueTypes (e.g. DateTime, DateOnly, DateTimeOffset, Guid) when the library isn't GENERICHOST?

There are only reference types or value types. Nullable types was a misnomer and there were some other issues of which I don't really recall now. Generichost does not use getNullableTypes at all, the abstract C# codegen throws an exception if it is used. Other C# implementations were excluded from the change to narrow the scope of my pr.

**Comment by Noudicus** [comment]
For me the working workaround is to not yet use the DateOnly objects by setting the additionalProperty:
`--additional-properties=useDateTimeForDate=true`

[https://openapi-generator.tech/docs/generators/aspnetcore/]

I have tried to add the extensions in the spec but that did not make the DateOnly property nullable for me
`
                            "active_till": {
                                "type": "string",
                                "format": "date",
                                "readOnly": true,
                                "nullable": true,
                                "x-is-value-type": true
                            },
`
resulted in
`        /// <summary>
        /// Gets or Sets ActiveTill
        /// </summary>
        [DataMember(Name = "active_till", EmitDefaultValue = true)]
        public DateOnly ActiveTill { get; private set; }
`

**Comment by MichaelMay81** [comment]
I don´t understand the problem. Can we not just accept the Pullrequest as a Workaround and if there is a deeper problem with the getNullableTypes concept, open a new ticket to fix that in the future!?

I don't understand what makes DateOnly so special. getNullableTypes already includes DateTime and DateTimeOffset. All of them are structs and therefore ValueTypes.
