### ISSUE TITLE
Add enum name mapping feature to typescript generators

### ISSUE THREAD

**Issue by linxin1019** [OpenAPITools/openapi-generator#18029]
### Is your feature request related to a problem? Please describe.

Please add enum name mapping feature to typescript generators.

**Comment by wing328** [comment]
may I know if you've time to contribute a PR for that? thanks

**Comment by linxin1019** [comment]
yes, i can do that.

**Comment by linxin1019** [comment]
> may I know if you've time to contribute a PR for that? thanks

yes, i can do that.

**Comment by linxin1019** [comment]
#18064
