### ISSUE TITLE
[BUG] [PYTHON] Multipart mixed post fails when passing objects

### ISSUE THREAD

**Issue by Poolmann** [OpenAPITools/openapi-generator#18076]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The multipart mixed post fails when trying to send objects.

##### openapi-generator version

7.4.0

##### OpenAPI declaration file content or url

[form-multipart-binary-array.yaml](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/form-multipart-binary-array.yaml)

##### Generation Details
`java -jar openapi-generator-cli.jar generate -i form-multipart-binary-array.yaml -g python -o test-client`

##### Steps to reproduce

Generate client with mentioned YAML spec and try to run the client like:
```python
with openapi_client.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = openapi_client.MultipartApi(api_client)
    marker = MultipartMixedRequestMarker(name="Test")

    try:
        api_instance.multipart_mixed(
            status=MultipartMixedStatus.ALLOWED, file="<file>", marker=marker
        )
    except Exception as e:
        print("Exception when calling MultipartApi->multipart_array: %s\n" % e)
```

##### Suggest a fix

The exception actually occurs in `urllib3` when, it tries to write the object into a byte stream and can't interpret the `dict` as bytes (`body.write(data)`):
``` python
def encode_multipart_formdata(
    fields: _TYPE_FIELDS, boundary: str | None = None
) -> tuple[bytes, str]:
    """
    Encode a dictionary of ``fields`` using the multipart/form-data MIME format.

    :param fields:
        Dictionary of fields or list of (key, :class:`~urllib3.fields.RequestField`).
        Values are processed by :func:`urllib3.fields.RequestField.from_tuples`.

    :param boundary:
        If not specified, then a random boundary will be generated using
        :func:`urllib3.filepost.choose_boundary`.
    """
    body = BytesIO()
    if boundary is None:
        boundary = choose_boundary()

    for field in iter_field_objects(fields):
        body.write(f"--{boundary}\r\n".encode("latin-1"))

        writer(body).write(field.render_headers())
        data = field.data

        if isinstance(data, int):
            data = str(data)  # Backwards compatibility

        if isinstance(data, str):
            writer(body).write(data)
        else:
            body.write(data)

        body.write(b"\r\n")
```
Error message: `a bytes-like object is required, not 'dict'`

**Comment by fa0311** [comment]
I was able to reproduce this error.
But what is the expected behavior of this?
Should the dict be converted to json?

**Comment by Poolmann** [comment]
Yes somewhere along the way to urllib the dict should be dumped as a json. For a regular request body this happens at https://github.com/OpenAPITools/openapi-generator/blob/5975e6c5b0c27844a77fbbf406a020fd6dff75c7/modules/openapi-generator/src/main/resources/python/rest.mustache#L170-L171
But I'm not sure where this should happen for the `post_params`. I think ideally it should happen before, since I wouldn't want to iterate over the list of `post_params` here.

**Comment by Poolmann** [comment]
Otherwise, this should do it no?
```python
post_params = [(a, json.dumps(b)) if isinstance(b, dict) else (a,b) for a, b in post_params]
```

**Comment by fa0311** [comment]
> Otherwise, this should do it no?

Yes, I think this is a good idea.
Can you send me a Pull Request?

**Comment by Poolmann** [comment]
> Can you send me a Pull Request?

https://github.com/OpenAPITools/openapi-generator/pull/18140
