### ISSUE TITLE
[BUG][PYTHON] Fail to do model_validate in the deserialization if the object inherited via AllOf

### ISSUE THREAD

**Issue by zishunwei** [OpenAPITools/openapi-generator#18089]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
    Expected output:
    Calling for the DefaultApi.get_user_info() passes
    Acutal output:
```
Exception when calling DefaultApi->get_user_info: 2 validation errors for Info
nameA
  Field required [type=missing, input_value={'_typeName': 'Info'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
nameB
  Field required [type=missing, input_value={'_typeName': 'Info'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
```
When calling the API, the obj is not regrade as the dict and will go to cls.model_validate({"_typeName": obj.get("_typeName")}) ,
but actually the Info obj requires fields: NameA and NameB, which are missed and the exception is thrown by the validator.

```python
class Info(BaseModel):
    """
    Info
    """ # noqa: E501
    name_a: StrictStr = Field(alias="nameA")
    name_b: StrictStr = Field(alias="nameB")
    type_name: StrictStr = Field(alias="_typeName")
    __properties: ClassVar[List[str]] = ["_typeName"]

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Info from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_typeName": obj.get("_typeName")
        })
        return _obj
```

Check the models/info.py, looks __properties and from_dict() are defined with mistakes, it should be:
```python
__properties: ClassVar[List[str]] = ["_typeName", "name_a", "name_b"]

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        _obj = cls.model_validate({
            "_typeName": obj.get("_typeName"),
            "nameA": obj.get("name_a"),
            "nameB": obj.get("name_b")
        })


```
instead of:
```python
__properties: ClassVar[List[str]] = ["_typeName"] # only includes _typeName inherited from Base

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        _obj = cls.model_validate({
            "_typeName": obj.get("_typeName") # only includes _typeName inherited from Base
        })
```

##### openapi-generator version

7.4.0 (Latest Master code until 2024/03/12)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: ""
  version: ""
paths:
  /user/{id}/getInfo:
    get:
      operationId: getUserInfo
      parameters:
      - description: user time
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
          description: |
            OK
      security:
      - Session: []
      x-accepts: application/json
components:
  parameters:
    id:
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
  schemas:
    Info:
      allOf:
      - $ref: '#/components/schemas/Base'
      example:
        nameA: nameA
        nameB: nameB
      properties:
        nameA:
          type: string
        nameB:
          type: string
      required:
      - nameA
      - nameB
      type: object
    Base:
      description: |
        The base of all data types
      example:
        _typeName: _typeName
      properties:
        _typeName:
          type: string
      required:
      - _typeName
      type: object
```

##### Generation Details
`java -jar openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i validate.yaml -g python -o ~/validate-issue-demo  `

##### Steps to reproduce

1. Run `openapi-generator generate -i <the above yaml file> -g python -o <output directory>`
2. Try to call the DefaultApi.get_user_info, will throw the exception as shown before

##### Related issues/PRs

No

##### Suggest a fix
We can consider making changes in  model_generic.mustache  in openapi-generator to re-define the logic of __properties and from_dict method for deserialization

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_generic.mustache#L267

**Comment by zishunwei** [comment]
Hi @fa0311 , I am trying to fix and file a PR for this issue but having some concerns now.

I am targeting to change the generated model models/info.py as shown below. It will not throw the validation errors if the model was generated like this. But I am not sure if it is a suitable change for the python generator to generate the models like this. Could you please take a look if you have time? And maybe you can also give some advice to me for which files in generator need to be modified. Thank you!

```python
class Info(BaseModel):
    __properties: ClassVar[List[str]] = ["_typeName", "name_a", "name_b"]
    
    ...
    
    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:

       ...

        _obj = cls.model_validate({
            "_typeName": obj.get("_typeName"),
            "nameA": obj.get("name_a"),
            "nameB": obj.get("name_b")
        })
```

instead of:

```python
class Info(BaseModel):
    __properties: ClassVar[List[str]] = ["_typeName"] #only includes _typeName inherited from Base
   
    ...

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
       
       ...

        _obj = cls.model_validate({
            "_typeName": obj.get("_typeName") #only includes _typeName inherited from Base
        })
```

**Comment by fa0311** [comment]
There are several things about the current AllOf that are puzzling and I don't know what to do about them either.

https://github.com/OpenAPITools/openapi-generator/blob/e78aeb6bc7610a763e17e3d53614a1ef1990f311/modules/openapi-generator/src/main/resources/python/model_generic.mustache#L26

I don't know what `{{#parent}}{{.}}{{/parent}}` stands for.

---

Inheritance may be used to write a concise
In any case, AllOf is broken and it will be a big job to fix 

```
class Info(Base):
    name_a: StrictStr = Field(alias="nameA")
    name_b: StrictStr = Field(alias="nameB")
    __properties: ClassVar[List[str]] = ["_typeName", "nameA", "nameB"]
    ...
    
    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:

       ...

        _obj = cls.model_validate({
            "_typeName": obj.get("_typeName"),
            "nameA": obj.get("nameA"),
            "nameB": obj.get("nameB")
        })
```

**Comment by wing328** [comment]
```
  schemas:
    Info:
      allOf:
      - $ref: '#/components/schemas/Base'
      example:
        nameA: nameA
        nameB: nameB
      properties:
        nameA:
          type: string
        nameB:
          type: string
      required:
      - nameA
      - nameB
      type: object
```

if you want allOf to be treated as inheritance in this case without using discriminator, please enable the rule `REF_AS_PARENT_IN_ALLOF` in the normalizer.

since allOf and properties are in the same level, you will need to enable `REFACTOR_ALLOF_WITH_PROPERTIES_ONLY` as well

ref: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

**Comment by wing328** [comment]
> I don't know what {{#parent}}{{.}}{{/parent}} stands for.

that's for parent model. if Dog inherits/extends Pet, then `{{parent}}` is the Pet in this case.

**Comment by fa0311** [comment]
> if you want allOf to be treated as inheritance in this case without using discriminator, please enable the rule `REF_AS_PARENT_IN_ALLOF` in the normalizer.
> 
> since allOf and properties are in the same level, you will need to enable `REFACTOR_ALLOF_WITH_PROPERTIES_ONLY` as well

This and `{{parent}}` also worked.

From these, it appears that this Issues is not a bug.

**Comment by zishunwei** [comment]
Thanks @wing328 for your suggestion, it worked when enabling the rules.

However, I also tried the case using allOf with discriminator (attach my spec below), it will still kick the same issue if I do not enable `REFACTOR_ALLOF_WITH_PROPERTIES_ONLY`. 

Based on my findings described in PR https://github.com/OpenAPITools/openapi-generator/pull/18255 , in the cases using allOf (whatever we use discriminator or not), `allVars` in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model_generic.mustache#L285 will only have the properties of the parent model but lacks these itself. 

Does it make sense? I am curious if using allOf with discriminator is also regard as a user defined case and we must need to enable the customization rule. If we also need the PR https://github.com/OpenAPITools/openapi-generator/pull/18255 to make it can be generated well directly without enabling the customization rule? 

```
openapi: 3.0.0
info:
  title: ""
  version: ""
paths:
  /user/{id}/getInfo:
    get:
      operationId: getUserInfo
      parameters:
        - description: user time
          explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Info'
          description: |
            OK
      security:
        - Session: []
      x-accepts: application/json
components:
  parameters:
    id:
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
  schemas:
    Info:
      allOf:
        - $ref: '#/components/schemas/Base'
      example:
        nameA: nameA
        nameB: nameB
      properties:
        nameA:
          type: string
        nameB:
          type: string
      required:
        - nameA
        - nameB
      type: object
    Base:
      description: |
        The base of all data types
      discriminator:
        mapping:
          string: '#/components/schemas/PrimitiveString'
        propertyName: _typeName
      example:
        _typeName: _typeName
      properties:
        _typeName:
          type: string
      required:
        - _typeName
      type: object
    PrimitiveString:
      allOf:
        - $ref: '#/components/schemas/Base'
      description: |
        A boxed String primitive.
      properties:
        _value:
          type: string
      required:
        - _value
      type: object
```

**Comment by wing328** [comment]
REFACTOR_ALLOF_WITH_PROPERTIES_ONLY will be enabled by default in v8.0.0 release
