### ISSUE TITLE
[REQ][JAVA] - [QA] How not to generate @Pattern and @Size for UUID

### ISSUE THREAD

**Issue by DatApplePy** [OpenAPITools/openapi-generator#18095]
### Is your feature request related to a problem? Please describe.

This is more of a question, than a possible feature. So in our project we use 42Crunch to test our APIs, which requires us to define pattern (and maxLength) in our contract for a schema like this:
```yaml
components:
  schemas:
    uuid:
      type: string
      format: uuid
```
For a single UUID object (as a member of a class), using vendorExtensions and with some mustache template magic I can make the generator not to annotate UUID members.
But if our class has a list of UUIDs, than the type of elements in our List will look something like this:
```java
List<@Pattern(regexp = "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$") @Size(max = 36) UUID>
```

Thanks to 7.4.0, many of our issues with list element type annotations have been resolved. Unfortunately the current case is different because of the 'format: uuid'. In Java, UUID cannot be validated with these annotations.

Please prove me wrong, but as I remember, the annotations for list element types are injected directly into the 'dataType' using AbstractJavaCodegen, and not based on mustache templates.
https://github.com/OpenAPITools/openapi-generator/blob/v7.4.0/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L963
https://github.com/OpenAPITools/openapi-generator/blob/v7.4.0/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L1039

## Describe the solution you'd like

Is there any workaround to solve this? Our project is huge as hell, so getting rid of 'format: uuid' is not possible.

EDIT: After doing some research I found a possible solution. In the code (link below) we can simply exclude each format, which is not allowed to have any validation in the generated code (eg. UUID).
https://github.com/OpenAPITools/openapi-generator/blob/v7.4.0/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L1041

**Comment by DatApplePy** [comment]
Fix is on the way

**Comment by MelleD** [comment]
This not completely fixed, just for container types. Have the issue also on single types e.g. query and path params

**Comment by MelleD** [comment]
@wing328  see here: https://github.com/OpenAPITools/openapi-generator/pull/18900
