### ISSUE TITLE
Not valid URL: localhost:9000/api. Default to http://localhost.

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#181]
##### Description

I got the following warning in a test spec:
```
[main] WARN org.openapitools.codegen.utils.URLPathUtils - Not valid URL: localhost:9000/api. Default to http://localhost.
```

I think we may be able to better handle this by automatically appending http:// if it's not found at the beginning of the URL

##### openapi-generator version

Latest master

##### Steps to reproduce

Craft a spec with `localhost:9000/api` and run with any generator

##### Suggest a fix/enhancement

Update URLPathUtils class to better handle this case for the user.

**Comment by grokify** [comment]
There are a couple of places where a default protocol / scheme is used as shown below in `URLPathUtils.java`.

Should we default to `http` for both this issue and and line 64.

Default to `http`

https://github.com/OpenAPITools/openapi-generator/blob/d43801a9b72e9ecee760b9ede031aa355f1f8e9e/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L120

Default to `https`

https://github.com/OpenAPITools/openapi-generator/blob/d43801a9b72e9ecee760b9ede031aa355f1f8e9e/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L59-L65

**Comment by jmini** [comment]
See also #320. If you do not specify a scheme in an OAS2 schema, it should take the one from the server.

But this issue can be implemented independently. #320 must be solved in swagger parser.
