### ISSUE TITLE
[BUG][JAVA] Usage of allOf results in code incompatible with Gson: no suitable method found for value(java.lang.Object)

### ISSUE THREAD

**Issue by parfentjev** [OpenAPITools/openapi-generator#18203]
#### Bug Report Checklist

- [ X ] Have you provided a full/minimal spec to reproduce the issue?
- [ X ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ X ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ X ] Have you searched for related issues/PRs?
- [ X ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

My specification defines a response schema that leverages the `allOf` construct to reference the response object, which includes a string enumeration. The generated code includes a custom adapter for the enum that uses methods not present in the Gson library, resulting in compilation errors.

##### openapi-generator version

I used the latest docker image to verify the issue using the generator directly, unfortunately it doesn't support the `--version` flag. In my project, I'm using a maven plugin. I tried the following versions of the plugin: 6.2.0, 7.1.0, and 7.4.0.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.1.0
info:
  title: Account API
  version: 1.0.0
paths:
  /account/{id}:
    get:
      summary: Get account by ID
      operationId: getAccountById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Account found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
components:
  schemas:
    Account:
      allOf:
        - $ref: "#/components/schemas/AccountResponse"
    AccountResponse:
      type: object
      properties:
        locale:
          type: string
          enum:
            - locale1
            - locale2
```

##### Generation Details

```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
-i /local/spec.yaml \
-g java \
-o /local/temp
```

##### Steps to reproduce

1. Save the spec above to a `spec.yaml` file.
2. Go to the directory with the spec file.
3. Run the command above.

The broken code is located in: `./temp/src/main/java/org/openapitools/client/model/Account.java`, lines 91, 96, and 102.

```java
    public static class Adapter extends TypeAdapter<LocaleEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LocaleEnum enumeration) throws IOException {
        // JsonWriter doesn't implement a value(Object) method
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LocaleEnum read(final JsonReader jsonReader) throws IOException {
        // JsonReader doesn't implement a nextObject() method
        Object value =  jsonReader.nextObject();
        return LocaleEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // JsonElement doesn't implement a getAsObject() method
      Object value = jsonElement.getAsObject();
      LocaleEnum.fromValue(value);
    }
```

##### Related issues/PRs

I couldn't find similar PRs in this project.

##### Suggest a fix

In general, if we manually replace Object with String in the generated code, that solves the problem with this specification. However, I don't know if this solution would apply everywhere. After all, there probably is some logic behind dynamic data types in templates.

There was a similar issue in swagger-codegen-generator, somehow your projects look related.

https://github.com/swagger-api/swagger-codegen-generators/commit/8f23a89ce4c75597b8deb82e010fa1e8037168d8#diff-050bf3598e1b6bc7cf3f99c6008daeb360dfc57bd394e070bfa9fb19cbe79a7f

However, this particular commit doesn't solve all mentioned problems.

**Comment by wing328** [comment]
as a workaround, please switch back to openapi 3.0.1 spec for the time being while we work on a fix.

**Comment by wing328** [comment]
UPDATE: I fixed it via https://github.com/OpenAPITools/openapi-generator/commit/6746be9a507e68075f2bbeef148fef235efabc66

Please give it a try with the latest master (snapshot version can be found in the README)

(sorry that I should have created a PR instead but I forgot to create a branch to start with while working on the fix)
