### ISSUE TITLE
[BUG] 3.1.0 Missing type for array when multiple arrays with same ref

### ISSUE THREAD

**Issue by am-on** [OpenAPITools/openapi-generator#18290]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When a `Schema` has multiple `array` properties with same `$ref`, only the first array property gets correct type. The example file works correctly using `openapi: 3.0.0`

Relevant part from `Schema`:
```yaml
properties:
  arrayFooOne:
    type: array
    items:
      $ref: '#/components/schemas/Foo'
  arrayFooTwo:
    type: array
    items:
      $ref: '#/components/schemas/Foo'
  arrayFooThree:
    type: array
    items:
      $ref: '#/components/schemas/Foo'
```

Elm
```Elm
type alias BarAndFoos =
    { arrayFooOne : List Foo
    , arrayFooTwo : Maybe AnyType -- Should be `Maybe (List Foo)`
    , arrayFooThree : Maybe AnyType -- Should be `List Foo`
    }
```

Golang
```Go
type BarAndFoos struct {
	ArrayFooOne []Foo `json:"arrayFooOne"`
	ArrayFooTwo interface{} `json:"arrayFooTwo,omitempty"` // Should be ArrayFooTwo []Foo
	ArrayFooThree interface{} `json:"arrayFooThree"` // Should be ArrayFooThree []Foo 
}
```

Java
```java
  public List<Foo> getArrayFooOne() {
    return arrayFooOne;
  }

  public Object getArrayFooTwo() { // Should be public List<Foo>
    return arrayFooTwo;
  }

  public Object getArrayFooThree() { // Should be public List<Foo>
    return arrayFooThree;
  }
```

##### openapi-generator version

openapi-generator-cli 7.5.0-SNAPSHOT
  commit : f357be4

##### OpenAPI declaration file content or url

```yaml
openapi: 3.1.0
info:
  title: ""
  version: ""

paths:
  /user/getInfo:
    get:
      operationId: getUserInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BarAndFoos'
          description: |
            OK
      security:
        - Session: []
      x-accepts: application/json

components:
  schemas:
    Foo:
      type: object
      required:
        - fooData
      properties:
        fooData:
          type: string

    BarAndFoos:
      type: object
      required:
        - arrayFooOne
        - arrayFooThree
      properties:
        arrayFooOne:
          type: array
          items:
            $ref: '#/components/schemas/Foo'
        arrayFooTwo:
          type: array
          items:
            $ref: '#/components/schemas/Foo'
        arrayFooThree:
          type: array
          items:
            $ref: '#/components/schemas/Foo'
```

##### Generation Details

Elm:
```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \ 
      --input-spec openapi.yaml \
      --generator-name elm \
      --output "foo"
```

Golang:
```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \ 
      --input-spec openapi.yaml \
      --generator-name go \
      --output "foo"
```

Java:
```bash
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \ 
      --input-spec openapi.yaml \
      --generator-name java \
      --output "foo"
```

##### Steps to reproduce

Use the provided OpenAPI declaration file and generate code.

**Comment by wing328** [comment]
thanks for reporting the issue. i've filed https://github.com/OpenAPITools/openapi-generator/pull/18297 to fix it

**Comment by wing328** [comment]
PR merged. please pull the latest master to give it a try to use the snapshot version mentioned in the project's readme

**Comment by am-on** [comment]
Thank you so much for the speedy bug fix! Greatly appreciated! 

I've tested the latest master on the example from this issue and our code where I noticed the bug, and in both cases, the bug is fixed.
