### ISSUE TITLE
Please upgrade jmustache to 1.16 

### ISSUE THREAD

**Issue by evgeny-myasishchev** [OpenAPITools/openapi-generator#18311]
Would be good to have jmustache updated to the 1.16. The 1.16 version supports parents which may make some templates more reusable.

**Comment by wing328** [comment]
i wonder if you can time to file a PR to do so: https://github.com/OpenAPITools/openapi-generator/blob/master/pom.xml#L1233

**Comment by evgeny-myasishchev** [comment]
Sure, here it goes https://github.com/OpenAPITools/openapi-generator/pull/18314

**Comment by evgeny-myasishchev** [comment]
Closing it for now as per #18314 comments.
