### ISSUE TITLE
org.springframework.core.io.Resource cannot be converted to org.springframework.web.multipart.MultipartFile

### ISSUE THREAD

**Issue by siddhsql** [OpenAPITools/openapi-generator#18345]
I get above error when trying to generate Java stub using the sample OpenAPI spec found at https://editor.swagger.io/ 

[mre.zip](https://github.com/OpenAPITools/openapi-generator/files/14923739/mre.zip)

# Steps to Repro

1. unzip the MRE
2. mvn clean install

# Expected

no errors

# Observed

```
[ERROR] /Users/xxx/code/openapi-mre/target/generated-sources/openapi/src/main/java/com/baeldung/openapi/api/PetApi.java:[340,68] incompatible types: org.springframework.core.io.Resource cannot be converted to org.springframework.web.multipart.MultipartFile
```

how can I fix this? is this a bug or something that i am doing wrong?

**Comment by palatam** [comment]
bug still persists, does nobody test their changes/bugfixes?
