### ISSUE TITLE
[BUG] invalid allVars for allOf and properties at the same level

### ISSUE THREAD

**Issue by jpfinne** [OpenAPITools/openapi-generator#18340]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

allVars does not contain the properties when the properties are on the same level as the allOf
Simlar to Object3 in issue_16797.yaml

##### openapi-generator version

7.4

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: '1.0'
paths:
  /pets:
    get:
      summary: Get all pets
      operationId: getAllPets
      responses:
        default:
          description: ok
components:
  schemas:
    Pet:
      type: object
      properties:
        petType:
          type: string    
      discriminator:
        propertyName: petType
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
      type: object
      properties:
        name:
          type: string
```

Ps:  the issue also exists if there is no discriminator

##### Generation Details

Spring generator  (probably all generators that support inheritance)

##### Steps to reproduce
use this templates/pojo.mustache for demonstration
```
/**
allVars
=======
{{#allVars}}{{name}} {{/allVars}}

vars
=======
{{#vars}}{{name}} {{/vars}}

parentVars
========
{{#parentVars}}{{name}} {{/parentVars}}
*/
```

openapi-generator-cli generate -g spring -i allvarSample.yaml -o out -t templates

Cat.java has an invalid allVars.  It should contain name.
```
/**
allVars
========
petType 

vars
========
name 

parentVars
========
 petType
*/
```
##### Suggest a fix

Add a normalizer that transforms the model into
```yaml
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            name:
               type: string
```

**Comment by wing328** [comment]
there's already a normalizer rule for that: REFACTOR_ALLOF_WITH_PROPERTIES_ONLY

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

**Comment by jpfinne** [comment]
> there's already a normalizer rule for that: REFACTOR_ALLOF_WITH_PROPERTIES_ONLY
> 
> https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

I don't think it works if REF_AS_PARENT_IN_ALLOF is enabled.

I meant a new normalizer that runs ** before ** REFACTOR_ALLOF_WITH_PROPERTIES_ONLY

**Comment by wing328** [comment]
why not simply run `REFACTOR_ALLOF_WITH_PROPERTIES_ONLY` before `REF_AS_PARENT_IN_ALLOF` if possible?

**Comment by jpfinne** [comment]
It seems the code on master has not the issue anymore.
I'll do more tests later today

**Comment by jpfinne** [comment]
I reproduce on master using this test in DefaultCodegenTest using the same contract:

```
    @Test
    public void testAllVars_issue_18340() {
        final OpenAPI openAPI = TestUtils.parseFlattenSpec("src/test/resources/3_0/spring/issue_18340.yaml");
        // the bug happens with or without this normalization
        new OpenAPINormalizer(openAPI, Map.of("REFACTOR_ALLOF_WITH_PROPERTIES_ONLY", " true"))..normalize();
        
        Schema catModel = ModelUtils.getSchema(openAPI, "Cat");
        DefaultCodegen defaultCodegen = new DefaultCodegen();
        defaultCodegen.setOpenAPI(openAPI);
        CodegenModel defaultCat = defaultCodegen.fromModel("Cat", catModel);
        assertThat(getNames(defaultCat.allVars)).isEqualTo(List.of("name", "petType"));  // correct

        // same model gives an invalid var when using SpringCodegen.  name is missing
        SpringCodegen springCodegen = new SpringCodegen();
        springCodegen.setOpenAPI(openAPI);
        CodegenModel springCat = springCodegen.fromModel("Cat", catModel);
        assertThat(getNames(springCat.allVars)).isEqualTo(List.of("petType"));  // should be name,petType

        // Prove that supportsInheritance is the culprit
        SpringCodegen springCodegenNoSupportInheritance = new SpringCodegen() {
            {
                this.supportsInheritance = false;
            }
        };
        springCodegenNoSupportInheritance.setOpenAPI(openAPI);
        CodegenModel springCatNoSupportInheritance = springCodegenNoSupportInheritance.fromModel("Cat", catModel);
        assertThat(getNames(springCatNoSupportInheritance.allVars)).isEqualTo(List.of("name", "petType"));  // correct again
    }
```

**Comment by jpfinne** [comment]
Additional info.  Moving the properties to the list of allOf fixes the issue:

```
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            name:
              type: string
```
allvars = petType,name  (IMHO a much better order)

Using this contract and the DefaultCodegen (ie without supportInheriance)
```
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
      type: object
      properties:
        name:
          type: string
```
allVars = name,petType (IMHO not a good order.  See #17542)

So I would "fix"  REFACTOR_ALLOF_WITH_PROPERTIES_ONLY (or create another normalizer) to migrate to first version to the second version

**Comment by jpfinne** [comment]
@wing328  Sorry my mistake, in testAllVars_issue_18340() I made a stupid typo with an extra space for " true".
```
Map.of("REFACTOR_ALLOF_WITH_PROPERTIES_ONLY", " true")
```
Sorry that the typo is now on master

**Comment by wing328** [comment]
@jpfinne that's ok. please fix it later in another PR
