### ISSUE TITLE
[REQ] Mutiny-Support for Jax-RS Quarkus Generator

### ISSUE THREAD

**Issue by lizzyTheLizard** [OpenAPITools/openapi-generator#18388]
### Is your feature request related to a problem? Please describe.

Quarkus usually uses [Mutiny](https://smallrye.io/smallrye-mutiny/) as Async framework. OpenAPI-Generator can already generate Mutiny-Files, but only in the kotlin-server generator. I would like to add Mutiny support in the Jax-RS-Generator for Library Quarkus as well.

## Describe the solution you'd like

I would therefore want to port the useMutiny-Flag from the kotlin-server generator to the Jax-RS generator. The flag will only have effect when using library "quarkus" and having "supportAsync" set. If not set, the flag will be false so that this change will be fully backwards compatible.

## Describe alternatives you've considered
None

## Additional context
None

**Comment by wing328** [comment]
your suggestion sounds good. may I know if you've time to contribute a PR?

**Comment by lizzyTheLizard** [comment]
@wing328 just added it!
