### ISSUE TITLE
[REQ] Delete orphaned models and tests from 2.0 samples

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#1840]
### Is your feature request related to a problem? Please describe.

This is a general cleanup task

## Describe the solution you'd like

When working on a python PR I noticed that the models animal_farm and string_boolean_map
no longer exist in the 2.0 sample spec.
Let's delete them from the the samples folder in the repo as they are no longer functional.
https://github.com/OpenAPITools/openapi-generator/search?q=animalfarm&unscoped_q=animalfarm
https://github.com/OpenAPITools/openapi-generator/search?q=stringbooleanmap&unscoped_q=stringbooleanmap

## Describe alternatives you've considered

N/A

## Additional context

This is just a nice to have update.
Note: if we removed the models directories before writing the sample clients, we would have seen test errors and would have removed this outdated content.

**Comment by jimschubert** [comment]
One approach to this, I think, would be to update all samples scripts to delete the apis/models/docs folders explicitly.
