### ISSUE TITLE
[BUG] openapi-generator 7.5.0 is no longer able to resolve local $refs

### ISSUE THREAD

**Issue by ctreatma** [OpenAPITools/openapi-generator#18429]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In openapi-generator 7.5.0, swagger-parser was upgraded to 2.1.19.  The same upgrade was done previously in openapi-generator 7.2.0 where it broke the generator's ability to resolve relative refs: https://github.com/OpenAPITools/openapi-generator/issues/17554.

The behavior described in the linked issue for 7.2.0 has been reintroduced in 7.5.0.  At some point, tests were added in an attempt to protect against breaking changes in parser upgrades, but those tests either didn't run or they didn't fail.

##### Suggest a fix

Previously the swagger-parser upgrade was reverted.  There are now a couple swagger-parser releases after 2.1.19 (the latest release is 2.1.22) and it's possible one of those releases includes a fix for the ref resolution issue, but if the tests that cover parser upgrades aren't working, it's harder to tell if the upstream issue was fixed.

**Comment by wing328** [comment]
sorry for the regression. not sure why the test didn't catch it

can you please build the project locally (mvn clean pacakge) with swagger parser 2.1.22 and see if it works for you locally?
