### ISSUE TITLE
[BUG] Model property treated as discriminator incorrectly

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#18450]
According to [this](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/#:~:text=The%20discriminator%20is%20used%20with%20anyOf%20or%20oneOf%20keywords%20only.), the discriminator is only valid when oneOf or anyOf are present. The generator will mark properties as discriminators even without oneOf or anyOf. This creates a problem during serialization in the csharp generichost library. We don't create properties for discriminators because the value can be inferred, but this is not a discriminator, so it just results in a missing property due to it being incorrectly marked as a discriminator.

![image](https://github.com/OpenAPITools/openapi-generator/assets/29644329/e22efc7e-5015-40df-8558-a9a7265cd925)
![image](https://github.com/OpenAPITools/openapi-generator/assets/29644329/ed99e781-18e8-4adc-890a-db00793684ed)

**Comment by wing328** [comment]
>  the discriminator is only valid when oneOf or anyOf are present

what about allOf?

**Comment by devhl-labs** [comment]
The openapi docs say only oneOf and anyOf. If it us allOf then there is nothing to discriminate.

**Comment by wing328** [comment]
in https://redocly.com/docs/resources/discriminator/

```
The discriminator must apply to the same level of the schema it is declared in (common mistake when using nested objects).

Also, it must be used in combination with anyOf, oneOf, or allOf.
```

**Comment by devhl-labs** [comment]
I think that quote agrees with what im saying except for allOf. allOf has nothing to discriminate so it shouldnt be needed. The animal model doesnt have any composed schemas at this level.

**Comment by wing328** [comment]
>allOf has nothing to discriminate so it shouldnt be needed

please have a look at https://github.com/OpenAPITools/openapi-generator/issues/14917

**Comment by devhl-labs** [comment]
Okay thanks for the link. Makes sense.
