### ISSUE TITLE
[BUG] [Java] Invalid code generation for oneof types.

### ISSUE THREAD

**Issue by Bethibande** [OpenAPITools/openapi-generator#18517]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
The generator generated an invalid java class when generating a client for the github api definition.

##### openapi-generator version
v7.5.0 (docker image: [openapitools/openapi-generator-cli:v7.5.0](https://hub.docker.com/layers/openapitools/openapi-generator-cli/v7.5.0/images/sha256-55ff6454b7e169a2de206539ab4c9ac480770f373480a9e5e5891319e5f81491?context=explore))
Note the docker image "latest" was also tested and has the same issue.

##### OpenAPI declaration file content or url
https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json
line **35245** seems to be the issue:
```json
"payload": {
    "oneOf": [
        {
            "type": "object",
            "additionalProperties": true
        },
        {
            "type": "string",
            "description": "JSON payload with extra information about the deployment.",
            "default": ""
        }
    ]
}
```
This generated a class that doesn't compile (ReposCreateDeploymentRequestPayload.java).
Compiling the generated project using "gradle build" causes 6 compiler errors, all within this one class.
For example the following method is generated:
```java
/**
 * Get the actual instance of `Map<String, Object>`. If the actual instance is not `Map<String, Object>`,
 * the ClassCastException will be thrown.
 *
 * @return The actual instance of `Map<String, Object>`
 * @throws ClassCastException if the instance is not `Map<String, Object>`
 */
public Map<String, Object> getMap<String, Object>() throws ClassCastException {
    return (Map<String, Object>)super.getActualInstance();
}
```
Other errors include invalid field names (containing ``Map<String, Object>``) or calls like ``Map<String, Object>.class``
```java
final TypeAdapter<Map<String, Object>> adapterMap<String, Object> = gson.getDelegateAdapter(this, TypeToken.get(Map<String, Object>.class));
```
See gradle error logs:
https://gist.github.com/Bethibande/4d0c2e925daff40572bcb3cee44d6ed7

##### Generation Details / Steps to reproduce
This can be reproduced on Windows with Docker (WSL) using the following two commands:
```shell
docker run --rm -v "%CD%:/local" openapitools/openapi-generator-cli:v7.5.0 generate -i https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json -g java -o /local/out/java
docker run --rm -v "%CD%:/local" -w /local/out/java gradle:8.7.0-jdk17 gradle build
```

##### Suggest a fix

1. Remove ``<``, ``,, `` and ``>`` from field and method names resulting in names like ``getMapStringObject`` or ``adapterMapStringObject``
2. Change TypeToken creation for Map types from ``TypeToken.get(Map<String, Object>.class)`` to ``TypeToken.getParameterized(Map.class, String.class, Object.class)`` or ``new TypeToken<Map<String, Object>>() {}``, see Gson documentation for [TypeToken](https://www.javadoc.io/doc/com.google.code.gson/gson/latest/com.google.gson/com/google/gson/reflect/TypeToken.html)

**Comment by wing328** [comment]
thanks for reporting the issue and suggesting a fix.

can you please PM me via Slack in the coming week when you've time to further discuss the fix? thanks

https://join.slack.com/t/openapi-generator/shared_invite/zt-12jxxd7p2-XUeQM~4pzsU9x~eGLQqX2g
