### ISSUE TITLE
[BUG] openapi-yaml translates "NO" to false

### ISSUE THREAD

**Issue by detached** [OpenAPITools/openapi-generator#18510]
##### Description

If a enum  contains  the value "NO" the output yaml will contain "false".

##### openapi-generator version

v7.5.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: sample
  version: 1.0.0
servers:
  - url: https://localhost
    description: test
paths:
  /items:
     get:
       responses:
         200:
           description: ""
       parameters:
         - in: query
           name: sort
           description: Sort order
           schema:
             type: string
             enum: 
               - NO
```

##### Generation Details
```
java -jar openapi-generator-cli.jar generate -i ./api.yaml -g openapi-yaml -o ./
```
Output:

```yaml
[...]
schema:
  enum:
    - "false"
  type: string
[...]
```
##### Steps to reproduce

* Define a enum with "NO" as value in your spec
* Generate yaml with "openapi-yaml" generator
* Output contains enum value "false"

**Comment by stefan521** [comment]
That might be a YAML thing:

> YAML indicates boolean values with the keywords True, On and Yes for true. False is indicated with False, Off, or No.

https://www.cloudbees.com/blog/yaml-tutorial-everything-you-need-get-started#booleans

Try with quotes?
```
schema:
   type: string
   enum: 
      - "NO"
```

**Comment by stefan521** [comment]
I did a bit of googling and this is is called the "YAML Norway problem". In YAML 1.2 this does not happen and only `true` and `false` are treated as boolean values. You could try to explicitly set the version of your document to 1.2

**Comment by detached** [comment]
Alright, thank you for the detailed answer! I will close the issue.
