### ISSUE TITLE
[BUG][Python] invoker-package does not work for python generator

### ISSUE THREAD

**Issue by iddqd1** [OpenAPITools/openapi-generator#1853]
##### Description

invoker-package is completly ignored for -g python

##### openapi-generator version

4.0.0-beta

##### OpenAPI declaration file content or url
https://api-staging.sallysalary.dk/swagger.json

##### Command line used for generation

openapi-generator  generate --invoker-package salarydk   -i swagger.json -g python  -o salarydk-python
##### Steps to reproduce

Try to generate any python client.Root package is always openapi_client.

**Comment by iddqd1** [comment]
Workaround is to create config file config.json with content: 
{
    "packageName": "yourInvokerPackagename"
}

**Comment by spacether** [comment]
packageName is the correct parameter to use to set the python package name for your client or server
