### ISSUE TITLE
[BUG][CSharp] DateOnly deserialized as DateTime and fails

### ISSUE THREAD

**Issue by MichaelMay81** [OpenAPITools/openapi-generator#18541]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

My Api uses DateOnly. The CSharp code cretead by OpenApi-Generator decorates DateOnly fields with [JsonConverter(typeof(OpenAPIDateConverter))]. This results in an Exception, when Json derserializes the string as DateTime and than tries to give that to a DateOnly.

##### openapi-generator version

Testetd with 7.5 and 7.3

##### Steps to reproduce

Create an API with 'dotnet new webapi' and update Swashbuckle.AspNetCore to 6.5 (earlier versions create a DateOnly schema instead of a Date type)

Created the client with 'docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v7.5.0 generate -i /local/${swagger_file} -g csharp -o /local/${output_dir} --additional-properties=packageName=${package_name} --additional-properties=targetFramework="net8.0" --additional-properties=useDateTimeOffset=true'

Initi Api: 'var webApi = new WebApiApi("http://localhost:5188")'
Calling 'webApi.GetWeatherForecast();' returns null. In debug I can see that there is an Exception being swallowed: "Unable to cast object of type 'System.DateTime' to type 'System.DateOnly'"

##### Suggest a fix

Removing the DateOnly decorators [JsonConverter(typeof(OpenAPIDateConverter))] seem to fix this issue.

**Comment by MichaelMay81** [comment]
Uploaded code to verify: https://github.com/MichaelMay81/OpenApiGeneratorTest

**Comment by BrettMillerDealX** [comment]
Also experienced, removing  `[JsonConverter(typeof(OpenAPIDateConverter))]` in the models resolved the issue for me too.

**Comment by jpduchon** [comment]
I also tested it with a build that only adds the Attribute when "supportsDateOnly" is false and it fixed the issue for me.
