### ISSUE TITLE
[BUG][cpp-qt5] template has extraneous characters

### ISSUE THREAD

**Issue by dtucker61** [OpenAPITools/openapi-generator#1855]
##### Description

Typo in mustache file (apirequest.cpp.mustache) for cpp-qt5-qhttpengine-server. 
Line 80 is currently:
```
 ::{{cppNamespace}}::fromStringValue((QString(socket->readAll()), {{paramName}});
```
Note the extra `(` following `fromStringValue`.

The line should be:
```
 ::{{cppNamespace}}::fromStringValue(QString(socket->readAll()), {{paramName}});
```

##### openapi-generator version

Current version (4.0.0) and at least on prior (3.3.4)

##### Steps to reproduce

Generate code from the following spec:
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: StringBugDemo
servers:
  - url: 'http://localhost:8080'
paths:
  /demo:
    post:
      summary: Test for typo in generated code
      requestBody:
        description: to show bug
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: success
```
##### Suggest a fix

Remove the extraneous character.

**Comment by etherealjoy** [comment]
Fixed with #1859
