### ISSUE TITLE
[BUG][JAVA] Exception in thread "main" java.lang.OutOfMemoryError: UTF16 String size is 1171739252, should be less than 1073741823

### ISSUE THREAD

**Issue by mthomas-github** [OpenAPITools/openapi-generator#18584]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm just trying to run Open Spec from docusign (https://github.com/docusign/OpenAPI-Specifications/raw/master/esignature.rest.swagger-v2.1.json) getting the following error

![image](https://github.com/OpenAPITools/openapi-generator/assets/51845049/7fde67f4-89c4-4f19-9c5a-0bbd3db3edf1)

##### openapi-generator version

![image](https://github.com/OpenAPITools/openapi-generator/assets/51845049/cd7a34ae-2f24-45a2-8fdc-8addcb7051bf)

##### OpenAPI declaration file content or url
DocuSign Swwagger Generated
d
##### Generation Details

I have a server with 160GB of Ram, it doesn't make a difference get same error each time, I tried with bash and java jar same approach

```
openapi-generator-cli generate -i https://github.com/docusign/OpenAPI-Specifications/raw/master/esignature.rest.swagger-v2.1.json -g csharp -o out
```
##### Steps to reproduce

Run command above

**Comment by wing328** [comment]
please use `skipOperationExample` (global option). the below works for me.

e.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -i https://raw.githubusercontent.com/docusign/OpenAPI-Specifications/master/esignature.rest.swagger-v2.1.json -o /tmp/docusign/ --skip-operation-example
```

**Comment by mthomas-github** [comment]
Thanks,i tested and it worked
