### ISSUE TITLE
[BUG] C# allof inheritance ok, but local properties mssing

### ISSUE THREAD

**Issue by ericbl** [OpenAPITools/openapi-generator#1858]
##### Description
As already mentioned in few bugs, the allof still has issues.

I want to generate C# code from a swagger file in which I use allOf to create inheritance.
The generated child class should inherits the parent class and has its own properties.

The generated code (see below) received only the inheritance, without the local properties: the properties defined for the child class were not generated.

##### openapi-generator version

Lastest pull of docker image / SwaggerEditor UI, thus using generator version 3.2 ?

##### OpenAPI declaration file content or url
I defined the following in my swagger file:

```yaml
  Result:
    type: object
    required:
      - value
    properties:
      value:
        type: object
 AugmentedResult:
    allOf: 
      - $ref: '#/definitions/Result'
    properties:
      recommendations:
        type: object
        properties:
          intents:
            type: array
            items:
              type: string
```

##### Steps to reproduce
I tried both generate server/aspnetcore and generate client/csharp from SwaggerEditor

I get the 2 classes in the models, where AugmentedResult inherits from Result.
But the properties defined in AugmentedResult are NOT generated.

And the rest of the class is also useless, starting with (GetHashCode, Equals, ToString()) where the local properties are also missing.

```[DataContract]
    public partial class AugmentedResult : Result,  IEquatable<AugmentedResult>, IValidatableObject
    {
        [JsonConstructorAttribute]
        protected AugmentedResult() { }
        public AugmentedResult(string type = default(string), Object value = default(Object)) : base(type, value)
        {
        }       
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AugmentedResult {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                return hashCode;
            }
        }
```

##### Related issues/PRs
Maybe 704
#1842

**Comment by wing328** [comment]
@ericbl please try the latest snapshot: https://github.com/OpenAPITools/openapi-generator#11---compatibility (JAR or docker images)

**Comment by nolanlocke** [comment]
This is also an issue in the typescript-fetch client

Using latest snapshot this is still an occurring issue

**Comment by InfoSec812** [comment]
@ericbl and @nolanlocke This appears to be working as expected in the latest 5.0.0-beta, could you test and confirm?
