### ISSUE TITLE
[BUG] [JAVA] [Client] Using different Content Types results in Accept Header [Ljava.lang.String;@XXXXXXXX

### ISSUE THREAD

**Issue by manuelnagler** [OpenAPITools/openapi-generator#18590]
##### Description

Regression in 7.5.0: Using different Content Types results in Accept Header generated as [Ljava.lang.String;@XXXXXXXX

##### openapi-generator version

Broken since 7.5.0. 
7.4.0 works as expected

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.2
info:
  title: Demo
  version: "1"
paths:
  /demo:
    post:
      requestBody:
        content:
          application/text:
            schema:
              type: string
      responses:
        '200':
          description: demo
          content:
            application/pdf:
              schema:
                type: string
                format: byte
        '500':
          description: demo
          content:
            application/text:
              schema:
                type: string
```

##### Steps to reproduce

Generate e.g. a feign client from the spec. 

Result:
```java
@RequestLine("POST /demo")
@Headers({
    "Content-Type: application/text",
    "Accept: [Ljava.lang.String;@7d0332e1",
})
byte[] demoPost(String body);
```

Expected:
```java
@RequestLine("POST /demo")
@Headers({
    "Content-Type: application/text",
    "Accept: application/pdf,application/text",
})
byte[] demoPost(String body);
```

The Accept Header is not serialized properly into the generated interface.

**Comment by wing328** [comment]
looks like it's related to https://github.com/OpenAPITools/openapi-generator/pull/18092

@larsenf-els can you please take a look when you've time?

**Comment by larsenf-els** [comment]
@manuelnagler @wing328 @yasstec:
I will have a look.

**Comment by larsenf-els** [comment]
@manuelnagler @yasstec 

I created a small project here at GitHub that uses Gradle to call the OpenAPI Generator 7.5.0 on the provided OpenAPI specification file used for producing the error:

https://github.com/larsenf-els/feign-openapi-generator-test

It generates this file:
`/feign-openapi-generator-test/build/generated/src/main/java/com/example/api/DefaultApi.java`

```java

**Comment by manuelnagler** [comment]
I noticed, that your initial pullrequest includes this change: https://github.com/OpenAPITools/openapi-generator/pull/18092/files#diff-d50fdea014963dc2aad9184a546a9005256203dce025f8b43255dd35aa3197ee

We were using a local copy of the api.mustache which we forgot to update. This issue is resolved.

**Comment by larsenf-els** [comment]
> I noticed, that your initial pullrequest includes this change: https://github.com/OpenAPITools/openapi-generator/pull/18092/files#diff-d50fdea014963dc2aad9184a546a9005256203dce025f8b43255dd35aa3197ee
> 
> We were using a local copy of the api.mustache which we forgot to update. This issue is resolved.

@manuelnagler 
Thank you for the follow-up. :smile::+1:
