### ISSUE TITLE
[REQ] Switch deprecated retrofit2-kotlinx-serialization-converter for first party kotlinx-serialization

### ISSUE THREAD

**Issue by larst-ingka** [OpenAPITools/openapi-generator#18593]
### Is your feature request related to a problem? Please describe.

Back in the middle of march 2024 [jakewharton retrofit2-kotlinx-serialization-converter](https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter) was deprecated as it was moved to a [first party converter](https://github.com/square/retrofit/tree/trunk/retrofit-converters/kotlinx-serialization). This means that any further improvements to the converter will happen in the retrofit repository.

## Describe the solution you'd like

Switch out the retrofit converter factory used for kotlinx_serialization with the new first party converter.

## Describe alternatives you've considered

Given that no further development is to be expected on the deprecated repository, and the fact that the repo was moved to a first party converter with no code changes between, I don't see any other clear options.

**Comment by wing328** [comment]
thanks for opening an issue (ticket) to track this.

the switch sounds good

may I know if you've time to contribute a PR for that?

let me know if you need some good starting points.

**Comment by larst-ingka** [comment]
Yeah, that would not be a problem. 

A preliminary timeline when I'd be available to contribute it would be early-mid next week. 

Sure, I've had a look at blame for earlier similar contributions, as well as the [CONTRIBUTING guidelines](https://github.com/OpenAPITools/openapi-generator/blob/master/CONTRIBUTING.md), but if theres some other goodies that would be helpful to me, please don't hesitate.

**Comment by wing328** [comment]
yup, previous PRs would be a good starting point too.

look forward to your PR.

thanks in advance for your contributions

**Comment by larst-ingka** [comment]
The pr was merged, so ill close this REQ now
