### ISSUE TITLE
[BUG][Go] UnmarshalJSON() does not allow unknown fields even when they are not forbidden in schema

### ISSUE THREAD

**Issue by dyurovskykh-tivo** [OpenAPITools/openapi-generator#18613]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
JSON schema allows additional properties by default, see https://json-schema.org/understanding-json-schema/reference/object#additionalproperties

>The additionalProperties keyword is used to control the handling of extra stuff, that is, properties whose names are not listed in the properties keyword or match any of the regular expressions in the patternProperties keyword. By default any additional properties are allowed.
>
>The value of the additionalProperties keyword is a schema that will be used to validate any properties in the [instance](https://json-schema.org/learn/glossary#instance) that are not matched by properties or patternProperties. Setting the additionalProperties schema to false means no additional properties will be allowed.

But Go generator produces `UnmarshalJSON()` with `decoder.DisallowUnknownFields()` regardless of the `additionalProperties` flag.

##### openapi-generator version
- latest

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
info:
  title: Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Object:
      required:
        - field1
      properties:
        field1:
          description: Something
          type: string
```

##### Generation Details
`$ docker run --rm -u 1001:1001 -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i /local/test.yaml -g go -o /local/out/go`

##### Steps to reproduce
Run generator and check the generated code. `UnmarshalJSON()` must not contain `decoder.DisallowUnknownFields()` because additional properties are not forbidden.

##### Related issues/PRs
Introduced by https://github.com/OpenAPITools/openapi-generator/issues/17575

##### Suggest a fix
Place the following LOC under the condition to be added only when `additionalProperties = false` for a given structure:
`decoder.DisallowUnknownFields()`

**Comment by dyurovskykh-tivo** [comment]
@wing328 @ctreatma
Please, check this bug.

**Comment by ctreatma** [comment]
The model template only generates the `decoder.DisallowUnknownFields()` code if the generator thinks that additional properties are not allowed: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/go/model_simple.mustache#L493-L511

What config are you passing in when running the generator?  There is a `disallowAdditionalPropertiesIfNotPresent` config option that controls the behavior of generated code for all languages: https://openapi-generator.tech/docs/generators/go/#config-options

For legacy reasons, the `disallowAdditionalPropertiesIfNotPresent` defaults to `true`.  This means that by default, the generator will produce models that assume additional properties _are not allowed_ if the `additionalProperties` key is not explicitly specified.

To configure the generator to produce code that complies with the `additionalProperties` behavior documented in OAS, you have to set `disallowAdditionalPropertiesIfNotPresent` to `false`.

**Comment by dyurovskykh-tivo** [comment]
@ctreatma
Thank you! I did not know about `disallowAdditionalPropertiesIfNotPresent` config.
When I run the generator like `docker run --rm -u 1001:1001 -v "${PWD}:/local" openapitools/openapi-generator-cli generate --additional-properties=disallowAdditionalPropertiesIfNotPresent=false -i /local/test.yaml -g go -o /local/out/go`, `decoder.DisallowUnknownFields()` is not generated
