### ISSUE TITLE
[BUG] [Typescript] [Axios] Header does not support complex-objects

### ISSUE THREAD

**Issue by sruehl** [OpenAPITools/openapi-generator#1865]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When using a header that is a complex object like defined here https://swagger.io/specification/#headerObject the serialization is missing here:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/api.mustache#L175
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/api.mustache#L180
this should be done like here:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/api.mustache#L226  

##### openapi-generator version

master

##### OpenAPI declaration file content or url

https://gist.github.com/sruehl/9919a4f8aab6ef9bb1ca47cf90b3c6e5

##### Related issues/PRs

#1874

##### Suggest a fix

implement serialization like here https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/api.mustache#L226

**Comment by sruehl** [comment]
same applies to java btw where toString on the object will then be called which produces something like `CustomHeader@132213`

**Comment by wing328** [comment]
@sruehl thanks for reporting the issue. I think no generator has yet added the support for the complex object in the header parameters.

For the suggested fix, I wonder if you can open a PR so that we can review the change more easily.

**Comment by sruehl** [comment]
sure I can try

**Comment by sruehl** [comment]
@wing328 I added a proposal with #1874. 
(At least for typescript, java should be done similar then)
