### ISSUE TITLE
 [BUG] [JAVA] [JAXRS-SPEC] Outer enum is given @Valid in jaxrs-spec

### ISSUE THREAD

**Issue by CREKD127** [OpenAPITools/openapi-generator#18681]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
https://github.com/OpenAPITools/openapi-generator/issues/18430
In this Issue, we have added support for not performing validation on enums that are not inline.
But, when I generate it using jaxrs-spec, it still has the `@Valid` annotation.

##### OpenAPI declaration file content or url
The test added in this PR is still given `@Valid`.
https://github.com/OpenAPITools/openapi-generator/pull/18664/files#diff-b84cef880717fd1f86abd47136c71acaa9c93ce0f3b4cc0093274a3ccfcefd78R143
https://github.com/OpenAPITools/openapi-generator/pull/18664/files#diff-b84cef880717fd1f86abd47136c71acaa9c93ce0f3b4cc0093274a3ccfcefd78R162

Perhaps `@Valid` is no longer given in jaxrs modules other than jaxrs-spec.
https://github.com/OpenAPITools/openapi-generator/pull/18451/files#diff-0193b51e2ebc7a334d29a9aa3f277cea846352f7ae2b168a3cf08af1fa939508R281

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/18697
