### ISSUE TITLE
Document x-enum-varnames and x-enum-descriptions as vendor extensions

### ISSUE THREAD

**Issue by jimschubert** [OpenAPITools/openapi-generator#1871]
##### Description

Add `x-enum-varnames` and `x-enum-descriptions` to documentation.

##### Related issues/PRs

Introduced via #1752, `x-enum-descriptions` should be added to the new doc site which will be introduced by #1770.

While reviewing #1752, I also noticed `x-enum-varnames` which is not accounted for in the existing docs that I had migrated to the docusaurus site. Once #1770 is merged, these should be documented in `docs/templating.md`.

**Comment by jmini** [comment]
On gitter @wing328 pointed to:
https://github.com/OpenAPITools/openapi-generator/wiki/Vendor-Extensions

Should I update this page or wait for #1770 to be merged?

**Comment by jimschubert** [comment]
@jmini please wait for #1770, as I've already migrated the docs and will edit them to link to the new locations after the site is up and running.

**Comment by jmini** [comment]
I will update https://github.com/OpenAPITools/openapi-generator/blob/master/docs/templating.md#extensions

**Comment by jmini** [comment]
PR: #2010
