### ISSUE TITLE
[BUG] Error in URLSessionImplementations 'UTType' is only available in watchOS 7.0 or newer 

### ISSUE THREAD

**Issue by noemier** [OpenAPITools/openapi-generator#18723]
Hi, 

I'm using openapi-generator with the option "useSPMFileStructure=true"
This is the command line use 
`openapi-generator generate -i swagger.yaml -o OpenAPI/generated -g swift5 --model-name-suffix Remote --additional-properties=generateModelAdditionalProperties=false,hashableModels=true,objcCompatible=false,responseAs=Combine,useCustomDateWithoutTime=true,useSPMFileStructure=true`

Since version 7.5.0, when I generate the source code I've got this error in the URLSessionImplementations.swift file :

URLSessionImplementations.swift:590:29: 'UTType' is only available in watchOS 7.0 or newer
            if let utType = UTType(filenameExtension: pathExtension) { 
            
Can you check on your side ?

Thank you

**Comment by 4brunu** [comment]
This should now be fixed.
If you still have this issue with the new version, please reopen this issue.
