### ISSUE TITLE
[BUG][typescript-fetch] 7.6.0 regression: TS7053 errors in generated instanceOf* methods

### ISSUE THREAD

**Issue by cascornelissen** [OpenAPITools/openapi-generator#18746]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
The changes introduced in [OpenAPITools/openapi-generator#18418](https://github.com/OpenAPITools/openapi-generator/pull/18418) result in `TS7053` errors in the generated `instanceOf*` methods on our side.

```
TS7053: Element implicitly has an any type because expression of type string can't be used to index type typeof Criticality
No index signature with a parameter of type string was found on type typeof Criticality
```

<img width="1054" alt="image" src="https://github.com/OpenAPITools/openapi-generator/assets/1304939/08140560-89d8-4b1e-aada-620ec884a779">

##### openapi-generator version
7.6.0 fails, 7.5.0 has no issue

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
components:
  schemas:
    # -- Snipped 300 lines of other schemas --
    Criticality:
      type: string
      enum:
        - error
        - warning
        - malfunction
```

##### Generation Details
We execute the following command and depend on [@openapitools/openapi-generator-cli](https://www.npmjs.com/package/@openapitools/openapi-generator-cli) for the generation.

While we use the `stringEnums` option, removing that doesn't solve the issue so that option seems unrelated.

```
openapi-generator-cli --openapitools 'path/to/openapitools.json' generate --generator-key some-service
```

The `openapitools.json` then looks like this:

```json
{
    "$schema": "./node_modules/@openapitools/openapi-generator-cli/config.schema.json",
    "spaces": 4,
    "generator-cli": {
        "version": "7.6.0",
        "generators": {
            "some-service": {
                "additionalProperties": {
                    "inputSpec": "path/to/some-service.yaml",
                    "output": "path/to/some-app/src/js/types/openapi/some-service",
                    "generatorName": "typescript-fetch",
                    "stringEnums": true
                }
            }
        }
    }
}
```

##### Steps to reproduce

1. Create an OpenAPI YAML specification containing a schema as shown above
2. Use `openapi-generator` to generate TypeScript types, it does so succesfully
3. Try to import/use the generated enum, TypeScript will throw a TS7053 error

Alternatively:

##### Related issues/PRs
None found so far.

##### Suggest a fix
Either revert the PR or adjust the the TypeScript, the following cast seems to solve the issue but is less than ideal;

```ts
if ((Criticality as Record<string, Criticality>)[key] === value) {
```

We have also noticed that setting `strict` to `false` in `tsconfig.json` resolves the issue which makes sense because TS7053 refers to an implicit any. Setting `strict` to `true` and `noImplicitAny` to `false` also seems to work.

**Comment by joshmenden** [comment]
+1 I am also encountering this issue. Thanks for the writeup @cascornelissen

**Comment by hhvrc** [comment]
+1 Also encountering the issue

**Comment by hhvrc** [comment]
@cascornelissen this can be closed as solved 😄

**Comment by celluj34** [comment]
When will this be released?

**Comment by devbydixon** [comment]
Also encountering this
