### ISSUE TITLE
[BUG][PYTHON] Deserialize on basic str fails since new version

### ISSUE THREAD

**Issue by oricho123** [OpenAPITools/openapi-generator#18774]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Hey. I've been using your openapi-generator for my app and It is great!

Since PR [#18039](https://github.com/OpenAPITools/openapi-generator/pull/18069) I've found a bug in the Python deserialization of a basic str.
The return value of each api_call that should return a basic `str` (`'example'`) returns instead an `str` wrapped with quotes (`'"example"'`), as it misses the normally called `json.loads`.

I know where the problem is, please keep reading :)

##### openapi-generator version

v7.6.0

##### OpenAPI declaration file content or URL

Ran a basic generated GET function that called the api_clent. the response should be a str

This is the generated code
```python
response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data
```

##### Generation Details

Generate a basic get in a service. For a Python library

##### Steps to reproduce

Generate a Python code from a service that returns a string, 
Run a basic generated GET function that calls the api_clent. the response should be a str

##### Related issues/PRs

The specific line was introduced in PR [#18039](https://github.com/OpenAPITools/openapi-generator/pull/18069)

More specifically- on file `modules/openapi-generator/src/main/resources/python/api_client.mustache`

##### Suggest a fix

Firstly, The function `__deserialize_primitive(response_text, response_type)`
on the file mentioned above, is getting a string representation of response_type, and not the type class as it must expect.
As of now, a TypeError is ALWAYS being thrown and caught when providing a string, and no deserialization happens.
So I guess it's needed to run before -

```python
            # convert str to class
            if klass in self.NATIVE_TYPES_MAPPING:
                klass = self.NATIVE_TYPES_MAPPING[klass]
            else:
                klass = getattr(monday_code.models, klass)
```

In any case, I still don't think it will solve the problem, as the code will now run-

```python
str('"example_value"')
```
And no `json.loads` will happen to remove the double quotes.

**Comment by wing328** [comment]
thanks for reporting the issue

@fa0311 can you please take a look when you've time? thanks

**Comment by oricho123** [comment]
@fa0311 Thanks for the quick resolution, king!

Will update if I find any problem :)

**Comment by markthiessen** [comment]
This change is overly specific and broke loading content with vendor extension content types. https://github.com/OpenAPITools/openapi-generator/issues/19285
