### ISSUE TITLE
[BUG][kotlin-spring] Gradle build fails when generated with `interfaceOnly=true`

### ISSUE THREAD

**Issue by Philzen** [OpenAPITools/openapi-generator#18803]
```shell
$ gradle build -x test
> Task :bootJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bootJar'.
> Error while evaluating property 'mainClass' of task ':bootJar'.
   > Failed to calculate the value of task ':bootJar' property 'mainClass'.
      > Main class name has not been configured and it could not be resolved

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

This happens when building locally and also on the CI pipeline: https://github.com/OpenAPITools/openapi-generator/actions/runs/9314727937/job/25639472824 – blocking any kotlin-related PRs from succeeding.

@stefankoppier @Rugal any ideas?

Strangely enough, i also tried building against the very first version locally (1e0e8fe0eb), same result.

#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

[ci] [kotlin]

**Comment by stefankoppier** [comment]
@Philzen it doet not fail for me locally when I run `build -x test`. The task `bootJar` is also not defined for me, locally. Can you link me the failing CI build?

**Comment by stefankoppier** [comment]
@Philzen, I can reproduce it locally. I'm unsure why this is happening. The error message is correct, as only interfaces are generated and no mainClass exists. Investigating further atm

**Comment by stefankoppier** [comment]
bootJar creates an executable JAR. This is not applicable, as there is no executable. A library is generated, and thus only jar should be used. A fix would be to add
```kotlin
tasks.bootJar {
    enabled = false
}
```
to build.gradle.kts when the additional property interfaceOnly is set to true. But unsure what the implications are, this should be tested. 

I don't have the time to create a PR with a tested fix. Are you able to do it, @Philzen?

**Comment by Philzen** [comment]
@stefankoppier Thanks heaps for the timely response – that fix works like a charm! :rocket: 
This really made my day as i was working on another PR that had some kotlin samples regenerated, which triggered a test execution for all Kotlin samples and thus was blocked … although this particular sample was unchanged.

> I don't have the time to create a PR with a tested fix. Are you able to do it, @Philzen?

See #18809

**Comment by stefankoppier** [comment]
cc @wing328
