### ISSUE TITLE
[BUG] TypeScript-Fetch: Headers passed in configurations are dropped in API calls

### ISSUE THREAD

**Issue by emadelwany** [OpenAPITools/openapi-generator#1882]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

headers passed as part of a Configuration's BaseOptions property (Configuuration::BaseOptions::Headers) in calls to Api Factories are dropped. 

The logic is in *FetchParamCreator doesn't copy them over to the final headers as part of param creation.  This is obvious in the code below, the line
```TypeScript
            const localVarHeaderParameter = {} as any;
```
Should copy them over

```TypeScript
            const localVarPath = `/api/Users`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
```

##### openapi-generator version

Discovered in 3.2.3, still occurring in 3.3.4

##### OpenAPI declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "API"
  },
  "paths": {
    "/api/Users": {
      "get": {
        "tags": [
          "Users"
        ],
        "operationId": "Get",
        "consumes": [
          
        ],
        "produces": [
          "text/plain",
          "application/json",
          "text/json"
        ],
        "parameters": [
          
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/User"
            }
          }
        }
      }
    }
  },
  "definitions": 
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "format": "uuid",
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "created": {
          "format": "date-time",
          "type": "string",
          "example": "2019-01-11T06:02:07.4817678Z"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "roles": {
          "uniqueItems": false,
          "type": "array",
          "items": {
            "$ref": "#/definitions/Role"
          }
        }
      }
    }
  }
}
```
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->

##### Command line used for generation

docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v3.3.4 generate \
    -i "http://host.docker.internal/swagger/v1/swagger.json" \
    -g typescript-fetch \
    --type-mappings Date=string \
    -o /local/src/swagger

##### Suggest a fix

One simple fix is to update the code under:
https://github.com/OpenAPITools/openapi-generator/blob/0eb385c0d6497c38c09b42158b2d66109b78b15b/modules/openapi-generator/src/main/resources/Javascript-Flowtyped/api.mustache

to properly assign Confiugration:BaseOptions:Headers to localVarHeaderParameter

This bug affects most TypeScript implementations and a similar fixed is needed in all of them.

I can create a PR if needed.

**Comment by keesvanlierop** [comment]
This is maybe because of the generated configuration class constructor does not extend baseOptions? From configuration.ts:

`constructor(param: ConfigurationParameters = {}) {
        this.apiKey = param.apiKey;
        this.username = param.username;
        this.password = param.password;
        this.accessToken = param.accessToken;
        this.basePath = param.basePath;
 }`

**Comment by jmike11** [comment]
Anyone have any luck with this one or do we have to create a local fix for now?

**Comment by macjohnny** [comment]
might be refactored in https://github.com/OpenAPITools/openapi-generator/issues/3402
