### ISSUE TITLE
[BUG][Kotlin] Enum type name starts lowecased and causes a build-error

### ISSUE THREAD

**Issue by hrach** [OpenAPITools/openapi-generator#18836]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

After updating to 7.6.0 (from 7.4.0) there is a regression. The produced code does not compile:

```kotlin
data class FavoritesEndpointItemsDto constructor (
    @Json(name = "user_gender")
    val userGender: FavoritesEndpointItemsDto.UserGender? = null,
) {
    /**
     * 
     *
     * Values: MALE,FEMALE
     */
    enum class userGender(val value: kotlin.String) {
        @Json(name = "male") MALE("male"),
        @Json(name = "female") FEMALE("female");
    }
}
```

##### openapi-generator version

`7.6.0`, yes, a regression

##### OpenAPI declaration file content or url

```json
            "FavoritesEndpoint_Items": {
                "type": "object",
                "properties": {
                    "user_gender": {
                        "type": "string",
                        "enum": [
                            "male",
                            "female"
                        ]
                    }
                },
                "required": [
                ]
            },
```

**Comment by hrach** [comment]
Tested 7.5.0, it is broken as well, so it is in its changes.

**Comment by piotrantosik** [comment]
Error still occurs in 7.7.0

**Comment by egrimstad** [comment]
I also had this problem, and finally found out it was due to me having overridden the `data_class.mustache` template. There seems to have been quite a few changes to the template since 7.4.0 (https://github.com/OpenAPITools/openapi-generator/commits/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache), so when I updated my local override the issue was fixed.

**Comment by hrach** [comment]
Oh, same on my side. Thanks!
