### ISSUE TITLE
[REQ] request middleware for Zapier generator.

### ISSUE THREAD

**Issue by a-wallen** [OpenAPITools/openapi-generator#18847]
### Is your feature request related to a problem? Please describe.

APIs that use some form of session auth, whether it be API keys or basic auth that requires parameters other than a Bearer token do not have support with the current generator. 

In order to support this, there needs to be middleware that can include these request options. 

## Describe the solution you'd like

utils.js should include a request middlware

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/18907
