### ISSUE TITLE
[BUG][KOTLIN] Kotlin client generation with generateOneOfAnyOfWrappers=true produces Java code in .kt file that does not compile in a Kotlin project

### ISSUE THREAD

**Issue by martinLeht** [OpenAPITools/openapi-generator#18890]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I tested the latest openapi-generator latest (7.7.0-SNAPSHOT) that contains a fix related to better oneOf support for generated Kotlin client code generation. The latest Kotlin client generator generates code that does not compile in a Kotlin project when using new config-option **generateOneOfAnyOfWrappers**=true. Kotlin generator produces Java code among the Kotlin code which results in a .kt file that does not compile. This problem persists when generation is performed against an OpenAPI schema that uses oneOf and discriminator for polymorphism. 

By simply looking at the mustache template files, one can see that there are variables declared in Java syntax and that some exceptions are thrown with "new" keyword that does not exist in Kotlin and thus does not compile. Below are some snippets and references to the templates: 

* Both [kotlin-client/oneof_class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/oneof_class.mustache), [kotlin-client/anyof_class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/anyof_class.mustache) contains some List variables are declared with Java style on [row 117](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/oneof_class.mustache#L117):
```code
...
 {{#isArray}}
                List<?> list = (List<?>) value.actualInstance // Java specific syntax
                if (list.get(0) is {{{items.dataType}}}) {
                     ...
                }
{{/isArray}}
...
```

* The template for data classes [kotlin-client/data_class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache) contains the "new" keyword when exceptions are thrown, in addition to having JsonArray variable declarations that are written with Java syntax:
* * IllegalArgumentException thrown with "new" keyword on [row 249](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache#L249)
```code
...
throw new IllegalArgumentException(String.format("Expected the field `{{{baseName}}}` to be an array in the JSON string but got `%s`", jsonObj["{{{baseName}}}"].toString()))
...
```
* * JsonArray declaration on [row 252](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache#L252)
```code
...
JsonArray jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}")
...
```

##### openapi-generator version

This issue currently on latest 7.7.0-SNAPSHOT version.

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  title: test
  version: 1.0.0
  description: test
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://petstore.swagger.io/v2
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: pet_type
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:     # "Dog" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Dog`-specific properties
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Dog`
          required:
            - names
          properties:
            names:
              type: array
              items:
                type: object
                properties:
                  firstname:
                    type: string
                  lastname:
                    type: string
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:     # "Cat" is a value for the pet_type property (the discriminator value)
      allOf: # Combines the main `Pet` schema with `Cat`-specific properties
        - $ref: '#/components/schemas/Pet'
        - type: object
          # all other properties specific to a `Cat`
          properties:
            hunts:
              type: boolean
            age:
              type: integer
```

##### Generation Details

Use latest generator CLI via docker: [openapitools/openapi-generator-cli:latest](https://hub.docker.com/layers/openapitools/openapi-generator-cli/latest/images/sha256-f24f8a3c7d172615b40eb49ceaaa348c1d76630210b5ad57a8dd847595c03245?context=explore)

Use above provided OpenAPI YAML to reproduce (see detailed below).

Configuration options (additional-properties) for Kotlin client generation:
* generateOneOfAnyOfWrappers=true
* enumPropertyNaming=original
* serializationLibrary=gson

##### Steps to reproduce

Run kotlin client generation command with latest openapi-generator-cli image against the OpenAPI YAML provided above with above additional properties described above:
`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate -i /local/pets.yaml -g kotlin -o /local/generated/kotlin --additional-properties=generateOneOfAnyOfWrappers=true,enumPropertyNaming=original,serializationLibrary=gson`

##### Related issues/PRs

Bug was a result of PR: https://github.com/OpenAPITools/openapi-generator/commit/353320cb04fdf84187e20ddfb0a3a8fe4de7da7a

##### Suggest a fix

Kotlin mustache templates should be fixed, so that there is only Kotlin syntax and no Java specific syntax. The above listed variable declarations and exception throwing should probably be fixed to Kotlin equivalent as follows:
* Before (Java) -> After (Kotlin):
```code
List<?> list = (List<?>) value.actualInstance // Java
-> val list = value.actualInstance as List<Any> // Kotlin


JsonArray jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}") // Java
-> val jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}") // Kotlin


throw new IllegalArgumentException(...) // Java
-> throw IllegalArgumentException(...) // Kotlin

```

**Comment by wing328** [comment]
@martinLeht thank for reporting the issue.

```
List<?> list = (List<?>) value.actualInstance // Java
-> val list = value.actualInstance as List<Any> // Kotlin
```

I've filed https://github.com/OpenAPITools/openapi-generator/pull/18891 to fix it

For the 2nd and 3rd issues, I couldn't repeat it with the latest master.

**Comment by martinLeht** [comment]
> @martinLeht thank for reporting the issue.
> 
> I've filed #18891 to fix it

Thanks! How about the other Java syntax problems mentioned above in [kotlin-client/data_class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache) ? Your fix does not seem to include them:
```
JsonArray jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}") // Java
-> val jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}") // Kotlin


throw new IllegalArgumentException(...) // Java
-> throw IllegalArgumentException(...) // Kotlin
```

**Comment by wing328** [comment]
PR merged. Please give it a try with the latest master. (snapshot version available in the project's readme)

**Comment by martinLeht** [comment]
@wing328 Nice, it seems to be working regarding the problems I mentioned earlier, thanks!

 I noticed tho another problem (possibly related to encoding on generation?). In the template [kotlin-client/data_class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache) we have the following jsonArray variable declaration and for-loop:
```
val jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}")
// validate the required field `{{{baseName}}}` (array)
for (i in 0 until jsonArray{{name}}.size()) {
              {{{items.dataType}}}.validateJsonElement(jsonArray{{name}}.get(i))
}
```
 
The above template produces uncompilable code, when the variable {{name}} = "data" in the OpenAPI spec. The generated code would look like this (uncompilable):
```
val jsonArray&#x60;data&#x60; = jsonObj.getAsJsonArray("data")
// validate the required field `data` (array) 
for (i in 0 until jsonArray&#x60;data&#x60;.size()) {
             <SOME_MODEL>.validateJsonElement(jsonArray&#x60;data&#x60;.get(i))
}
```
But when the {{name}} = "entities" or something else than "data", it generates code that is compilable and good:
```
val jsonArrayentities = jsonObj.getAsJsonArray("entities")
// validate the required field `entities` (array)
for (i in 0 until jsonArrayentities.size()) {
              <SOME_MODEL>.validateJsonElement(jsonArrayentities.get(i))
}
```

Should I make a separate issue with more details or is this enough?

**Comment by martinLeht** [comment]
@wing328 made new issue related to the problem above: https://github.com/OpenAPITools/openapi-generator/issues/18908
