### ISSUE TITLE
Extra package prefix created for Typescript AngularJS

### ISSUE THREAD

**Issue by achew22** [OpenAPITools/openapi-generator#189]
##### Description

When OpenAPI generated [PetApi.ts](https://github.com/OpenAPITools/openapi-generator/blob/0373b74a758e722fa553898523aab4402138bb6e/samples/client/petstore/typescript-angularjs/api/PetApi.ts#L34) at 0373b74a758e722fa553898523aab4402138bb6e, the output correctly had the signature:

`    public addPet (pet: models.Pet, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {`

When the file was regenerated at 059a3efe467d52345f9215d79399588cbe1d5693, it now has the signature of

`    public addPet (pet: models.models.Pet, extraHttpRequestParams?: any ) : ng.IHttpPromise<{}> {`

as you can see in [PetApi.ts](https://github.com/OpenAPITools/openapi-generator/blob/059a3efe467d52345f9215d79399588cbe1d5693/samples/client/petstore/typescript-angularjs/api/PetApi.ts#L34)

##### openapi-generator version

https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/3.0.0-SNAPSHOT/openapi-generator-cli-3.0.0-20180529.071922-102.jar

##### OpenAPI declaration file content or url

This is from the OpenAPI sample declaration.

##### Command line used for generation

The ones in the .pom file.

##### Steps to reproduce

1. Build OpenAPI
2. Build the samples
3. Notice that the path is incorrect and that it doesn't compile through the TS compiler.

##### Related issues/PRs

I looked but didn't see one. If I'm incorrect, please feel free to close this issue.

##### Suggest a fix/enhancement

I think this could be found by doing a bisection from the two provided commits and then mvn build'ing them and grepping for `\.models\.models` which would find it.

Additionally you might consider adding a test that regenerates the sample files and does a diff against what is checked in failing if there is a diff. This would ensure that the checked in files reflect the new reality of the generated code. Additionally, this would give you a nice diff every time someone did something that changed the generated code. Just a thought.

PS: Congrats on your progress post fork :fireworks: :champagne:. Things seem to really be coming along! I can't wait for a V3 release!

**Comment by jimschubert** [comment]
Thanks. That's an excellent issue report.

Here's the last script I used for a git bisect on this project: https://gist.github.com/jimschubert/38fe5491aa0c25df9d2c8c13d327a1b6. It should be a simple modification if someone wants to run a bisection to investigate this issue. This outputs UI notifications in Mac, in case the bisect range is large. The test condition is on the last `if` condition.

**Comment by jordan-nicholas** [comment]
It appears that this started happening at 80c8b92cb544bc08a18e7e15bca1d1b0487c4095, which made [DefaultCodegen.java](https://github.com/OpenAPITools/openapi-generator/commit/80c8b92cb544bc08a18e7e15bca1d1b0487c4095#diff-7cb46fa53f89a458a7b7cb201d2214a8) run postProcessParameter() more often.  If I remove either the postProcessParameter() or getTypeDeclaration() function from [TypeScriptAngularJsClientCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/69a3852ef77767c2dc8b3d63bb3c896b08af981d/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularJsClientCodegen.java#L70) the problem stops happening.  I don't know if it's safe to remove either of those overrides though.

**Comment by cbermudez97** [comment]
I have been generating a client for `typescript-angularjs` and the result is lacking of the `tsconfig.json`, `package.json` and so on. Is this the expected result?
