### ISSUE TITLE
[BUG][KOTLIN] Kotlin client generation with generateOneOfAnyOfWrappers=true produces uncompilable code when array field name is "data" in OpenAPI spec

### ISSUE THREAD

**Issue by martinLeht** [OpenAPITools/openapi-generator#18908]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I noticed some problems in generated code when testing latest fixes regarding the kotlin client generation with generateOneOfAnyOfWrappers. In the template [kotlin-client/data_class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/data_class.mustache) on line 252-256 we have the following jsonArray variable declaration and for-loop:
```
val jsonArray{{name}} = jsonObj.getAsJsonArray("{{{baseName}}}")
// validate the required field `{{{baseName}}}` (array)
for (i in 0 until jsonArray{{name}}.size()) {
              {{{items.dataType}}}.validateJsonElement(jsonArray{{name}}.get(i))
}
```
 
The above template produces uncompilable code, when the variable {{name}} = "data" in the OpenAPI spec. The generated code would look like this (uncompilable):
```
val jsonArray&#x60;data&#x60; = jsonObj.getAsJsonArray("data")
// validate the required field `data` (array) 
for (i in 0 until jsonArray&#x60;data&#x60;.size()) {
             <SOME_MODEL>.validateJsonElement(jsonArray&#x60;data&#x60;.get(i))
}
```
As seen above, {{name}} is converted after generation to #x60;data&#x60; (not compilable).
But when the {{name}} = "entities" or something else than "data", it generates code that is compilable and wokring as expected:
```
val jsonArrayentities = jsonObj.getAsJsonArray("entities")
// validate the required field `entities` (array)
for (i in 0 until jsonArrayentities.size()) {
              <SOME_MODEL>.validateJsonElement(jsonArrayentities.get(i))
}
```

##### openapi-generator version

This issue currently on latest 7.7.0-SNAPSHOT version.

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.3
info:
  title: test
  version: 1.0.0
  description: test
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://petstore.swagger.io/v2
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pet:
      type: object
      required:
        - data
        - size
      properties:
        data:
          type: array
          items:
            type: object
            properties:
              firstname:
                type: string
              lastname:
                type: string
        size:
          type: integer
```

##### Generation Details

Use latest generator CLI via docker: [openapitools/openapi-generator-cli:latest](https://hub.docker.com/layers/openapitools/openapi-generator-cli/latest/images/sha256-f24f8a3c7d172615b40eb49ceaaa348c1d76630210b5ad57a8dd847595c03245?context=explore)

Use above provided OpenAPI YAML to reproduce (see detailed below).

Configuration options (additional-properties) for Kotlin client generation:
* generateOneOfAnyOfWrappers=true
* enumPropertyNaming=original
* serializationLibrary=gson

##### Steps to reproduce

Run kotlin client generation command with latest openapi-generator-cli image against the OpenAPI YAML provided above with above additional properties described above:
`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:latest generate -i /local/pets.yaml -g kotlin -o /local/generated/kotlin --additional-properties=generateOneOfAnyOfWrappers=true,enumPropertyNaming=original,serializationLibrary=gson`

##### Related issues/PRs

Bug was noticed after fix: https://github.com/OpenAPITools/openapi-generator/pull/18891 

##### Suggest a fix

Kotlin mustache templates should be fixed, so that one can assign any name for an array field in OpenAPI spec. At this moment "data" as field name would not produce usable Kotlin client code.

**Comment by wing328** [comment]
thank for reporting the issue

filed https://github.com/OpenAPITools/openapi-generator/pull/18965 to fix it
