### ISSUE TITLE
[REQ] allow to pass a `str` to the Python aiohttp client

### ISSUE THREAD

**Issue by ziodave** [OpenAPITools/openapi-generator#18972]
### Is your feature request related to a problem? Please describe.

At the moment, it is not possible but to use `bytes` to pass raw data to the client

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/asyncio/rest.mustache#L183

This conflicts with definitions that are `string` and represented as `StrictStr` in model.

## Describe the solution you'd like

Same solution as in the sample here:
https://github.com/OpenAPITools/openapi-generator/blob/a4d43a83769fd71c0a2db79e8dc04af9699bd1fc/samples/client/echo_api/python/openapi_client/rest.py#L220

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/18985
