### ISSUE TITLE
[BUG] generated java client fails 'mvn install' due to undefined version of maven-dependency-plugin

### ISSUE THREAD

**Issue by smaarster** [OpenAPITools/openapi-generator#18977]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating a java client the plugin configuration of the maven-dependency-plugin is not defined. That leads to a failing build with standard target 'mvn install' because of the maven-enforcer-plugin: `Rule 1: org.apache.maven.enforcer.rules.RequirePluginVersions`

Skipping the enforcer plugin is possible but not desirable.
##### openapi-generator version
7.2.0, 7.6.0, 7.7.0-SNAPSHOT 

##### OpenAPI declaration file content or url

reproducable with the example pet store project.

##### Generation Details

generate -g java --skip-validate-spec --additional-properties=library=resttemplate

##### Steps to reproduce
1. Generate java client
2. 'mvn install' in generated client project

##### Suggest a fix

It seems that all the mustache templates for pom.xml files do not contain a version for the dependency plugin. Setting a value there would most probably fix the issue.

**Comment by wing328** [comment]
i tested with `java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java --library resttemplate -i modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/resttemplate/` 

and both `mvn clean package`, `gradle build` run without issues

**Comment by smaarster** [comment]
Thanks for your test wing238, could you tell me which maven version you are using and/or show the <plugin> config for the maven-dependency plugin?

**Comment by smaarster** [comment]
Thank you for your effort. The at my side was introduced through the enforcer-plugin on the parent pom I generated into the pom.xml. Still the question to me is, do you know why (in opposite to the other <plugin> definitions) the version of the maven-dependency-plugin is not defined explicitely?
