### ISSUE TITLE
Can we get the most recent snapshots from the master branch?

### ISSUE THREAD

**Issue by NikDevPHP** [OpenAPITools/openapi-generator#19035]
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.7.0-SNAPSHOT/

Many critical bugs have been fixed, it would be nice to get them ASAP.

For example
https://github.com/OpenAPITools/openapi-generator/pull/18945

**Comment by shiftgeist** [comment]
Is version 7.7.0 ([planned for 2024-06-20](https://github.com/OpenAPITools/openapi-generator?tab=readme-ov-file#11---compatibility)) uphold by any other issues?

We are waiting for the release of the [null fix](https://github.com/OpenAPITools/openapi-generator/pull/18887) of the typescript client.

**Comment by wing328** [comment]
I will do a release tomorrow or later this week

**Comment by shiftgeist** [comment]
@NikDevPHP version 7.7.0 is released
