### ISSUE TITLE
[BUG] Doesn't generate a getter if response example is the same

### ISSUE THREAD

**Issue by VelorumS** [OpenAPITools/openapi-generator#19031]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If the example response to GET is the same for two different paths then the second one isn't generated.

I expect to have both `GetOrderProductionFiles()` and `GetOrderTestFiles()`, but I get only `GetOrderProductionFiles()`.

##### openapi-generator version

7.6.0

##### OpenAPI declaration file content or url

```yaml
swagger: '2.0'
info:
  title: mytitle
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /orders/{orderNumber}/production-files:
    get:
      summary: Get zip file containing all production files by order number.
      operationId: getOrderProductionFiles
      parameters:
        - in: path
          name: orderNumber
          required: true
          type: string
          description: The expected order number
      responses:
        '200':
          description: Download URL.
          schema:
            type: object
            properties:
              downloadUrl:
                type: string
                description: The download URL
            example:
              downloadUrl: https://example.com/files/orderNumber/fileName.zip
  /orders/{orderNumber}/test-files:
    get:
      summary: Get zip file containing all test files by order number.
      operationId: getOrderTestFiles
      parameters:
        - in: path
          name: orderNumber
          required: true
          type: string
          description: The expected order number
      responses:
        '200':
          description: Download URL.
          schema:
            type: object
            properties:
              downloadUrl:
                type: string
                description: The download URL
            example:
              downloadUrl: https://example.com/files/orderNumber/fileName.zip
```

##### Generation Details

`openapi-generator generate -i api.yml  -g python`

Same problem with python-pydantic-v1, python-fastapi, possibly others.

##### Steps to reproduce

Save the yaml into `api.yml` and run:

```
openapi-generator generate -i api.yml  -g python
grep -i GetOrderProductionFiles
grep -i GetOrderTestFiles
```

Python code is not found for GetOrderTestFiles.

**Comment by wing328** [comment]
thanks for reporting the issue

if you remove the example, the output is generated as expected, right?

**Comment by VelorumS** [comment]
No, if I remove both examples then the second one still doesn't generate.

It's even more severe: I can vary parameter type and responses - it still won't generate the second one.

```yaml
swagger: '2.0'
info:
  title: mytitle
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /orders/{orderNumber}/production-files:
    get:
      summary: Get zip file containing all production files by order number.
      operationId: getOrderProductionFiles
      parameters:
        - in: path
          name: orderNumber
          required: true
          type: string
          description: The expected order number
      responses:
        '200':
          description: Download URL.
          schema:
            type: object
            properties:
              downloadUrl:
                type: string
                description: The download URL
  /orders/{orderNumber}/test-files:
    get:
      summary: Get zip file containing all test files by order number.
      operationId: getOrderTestFiles
      parameters:
        - in: path
          name: orderNumber
          required: true
          type: string
          description: The expected order number
      responses:
        '200':
          description: Download URL.
          schema:
            type: object
            properties:
              downloadUrl:
                type: string
                description: The download URL
```

**Comment by wing328** [comment]
that's weird. i'll try to take a look this weekend.

have a nice weekend

**Comment by wing328** [comment]
i can find both functions in `openapi_client/api/default_api.py`

```
grep -i GetOrderProductionFiles
grep -i GetOrderTestFiles
```
methods are renamed with snake to follow python method naming convention.

**Comment by wing328** [comment]
the responses are inline models/schemas and that's why they are generated as models

**Comment by VelorumS** [comment]
And if you want to have two different response models instead of one model then put a different example into the "response example" field in the API definition.
