### ISSUE TITLE
[BUG] Incorrect enum generation for Chinese / Korean characters

### ISSUE THREAD

**Issue by flue89** [OpenAPITools/openapi-generator#19057]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating the client, everything works fine except generating the enum where the values ​​are Chinese characters. I generated clients from a very large file and the problem is only with Chinese / Korean characters.

##### openapi-generator version

`"@openapitools/openapi-generator-cli": "2.13.4"`

##### Generation Details

Generated enum:

```ts
/**
 * 카테고리 이름.
 * @export
 * @enum {string}
 */

export enum SomeEnum {
     = '회원',
    2 = '구매',
    3 = '예약'
}
```

Expected enum:

```ts
/**
 * 카테고리 이름.
 * @export
 * @enum {string}
 */

export enum SomeEnum {
    '회원' = '회원',
    '구매' = '구매',
    '예약' = '예약'
}
```

##### Steps to reproduce

Java Version:
```
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

Command:
```
openapi-generator-cli generate -i src/file.yaml -g typescript-axios -o dist/client --additional-properties=apiPackage=clients,modelPackage=models,withSeparateModelsAndApi=true,withoutPrefixEnums=true,enumPropertyNaming=original,enumPropertyNamingReplaceSpecialChar=true,stringEnums=true,legacyDiscriminatorBehavior=true,paramNaming=original
```

**Comment by wing328** [comment]
please try the `enumNameMappings` option

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping

**Comment by flue89** [comment]
> please try the `enumNameMappings` option
> 
> https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping

Thank you. It's working.
