### ISSUE TITLE
[BUG] [Go] Golang generated client breaks for regular expression containing `

### ISSUE THREAD

**Issue by mohamuni** [OpenAPITools/openapi-generator#19102]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In Openapi specification if there is any regular expression consisting of  `` ` `` (Backtick character) breaks the generated client as regex expression after `` ` `` is ignored in struct tag

##### openapi-generator version

7.7.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: TestPattern
  version: 1.0.0
paths: {}
components:
  schemas:
    email_login:
      required:
        - email
      properties:
        email:
          type: string
          pattern: "^$|^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
    mobile_login:
      required:
        - mobile
      properties:
        mobile:
          type: string
          description: this pattern is more complicated and requires escaping
          pattern: "/^([+]\\d{2})?\\d{10}$/"
    login_source:
      oneOf:
        - $ref: '#/components/schemas/email_login'
        - $ref: '#/components/schemas/mobile_login'
```

##### Generation Details

```
mvn clean install
java -jar openapi-generator-cli.jar generate -i example.yaml -g go-o gosdk
```

##### Steps to reproduce

1. Generate SDK with the above specified declaration file
2. Open any generated model file with regex validation in struct tag  containing `` ` ``(Backtick character) in the regular expression and observe that struct tag is terminated in the middle of regex due to presence of `` ` `` character.

In the model file model_email_login.go for the above specified declaration, we can observe that struct tag content after `` ` `` in regex is ignored as highlighted in below picture causing breakage of SDK
![image](https://github.com/OpenAPITools/openapi-generator/assets/167277545/c9ee66bc-c535-4ab4-b862-02febe856d6c)

##### Related issues/PRs

The issue has started from the following PR
https://github.com/OpenAPITools/openapi-generator/pull/18760

##### Suggest a fix

The suggestion is to use `github.com/go-playground/validator/v10` package instead of `gopkg.in/validator.v2`
  
`github.com/go-playground/validator/v10` provides support for validation of struct from function which eliminates problem of struct tag breakage due to presence of `` ` ``(Backtick character) in regex

**Comment by vvb** [comment]
@wing328 the change added with https://github.com/OpenAPITools/openapi-generator/pull/18760 should ideally be made conditional based on a config flag. Currently it breaks `go build` itself if the regex pattern has a backtick in it. I think we need to rethink this change in context of nested struct validations as well. 

Please guide on how to proceed with this.

**Comment by wing328** [comment]
> itself if the regex pattern has a backtick in it

I will try to come up with a PR to fix it later this week as I think we need to better support regex pattern of any possible values instead of ignoring regex via an option.

**Comment by wing328** [comment]
update: filed https://github.com/OpenAPITools/openapi-generator/pull/19358 with a test to fix it

**Comment by wing328** [comment]
please help test the snapshot version when you've time: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.8.0-SNAPSHOT/

**Comment by mohamuni** [comment]
@wing328 we still see regex breaking in UnmarshalJSON function where we have struct without embedded structs as pointed below.

https://github.com/OpenAPITools/openapi-generator/blob/b3f74c7c4f516bcbe61c111c710489f3cb8182bd/modules/openapi-generator/src/main/resources/go/model_simple.mustache#L440


The above line require changes as you have done previously as shown below
https://github.com/OpenAPITools/openapi-generator/blob/b3f74c7c4f516bcbe61c111c710489f3cb8182bd/modules/openapi-generator/src/main/resources/go/model_simple.mustache#L23

Please find the PR for the above suggested changes
https://github.com/OpenAPITools/openapi-generator/pull/19410
