### ISSUE TITLE
[BUG][Java][Client][RestClient] Missing imports when using withXml

### ISSUE THREAD

**Issue by Nicklas2751** [OpenAPITools/openapi-generator#19137]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version
 
7.7.0

##### Steps to reproduce

1. Set `withXml` to `true`
2. The generated ApiClient misses the Imports for: XmlMapper and ToXmlGenerator

##### Suggest a fix

Add the missing imports

**Comment by wing328** [comment]
@Nicklas2751 thanks for reporting the issue

can you please file a PR with the suggested fix?

**Comment by Nicklas2751** [comment]
> @Nicklas2751 thanks for reporting the issue
> 
> 
> 
> can you please file a PR with the suggested fix?
> 
> 

Yes, probably not today, but tomorrow.

**Comment by Nicklas2751** [comment]
@wing328 Done 😎
