### ISSUE TITLE
[C#] CodeGen-CLI: Polymorphic Discriminator Mapping does not work

### ISSUE THREAD

**Issue by StenzelRichard** [OpenAPITools/openapi-generator#1914]
Using the discriminator object by propertyName works fine.
Using the discriminator object in conjunction with "mapping" does not work. I.e. when extending the propertyName - value mapping with values other than class names, it does not work. 

This type of mapping is needed, whenever the derived class-names do not match with the content of a certain attribute value.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#discriminatorObject
... see last example before "XML Object", starting 

components:
  schemas:
    Pet:
      type: object
      required:
      - petType
      properties:
        petType:
          type: string
      discriminator:
        propertyName: petType
        mapping:
          dog: Dog
....

this should deserialize a "Dog" class, when petType contains "dog" (lowercase). 
But this does not work, since Pet.cs has
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "PetType")]
    [JsonSubtypes.KnownSubType(typeof(Lizard), "Lizard")]
    [JsonSubtypes.KnownSubType(typeof(Cat), "Cat")]
    [JsonSubtypes.KnownSubType(typeof(Dog), "Dog")]
    public partial class Pet :  IEquatable<Pet>, IValidatableObject
      ...
and the mapping from "dog" to "Dog" is missing
missing: 
   [JsonSubtypes.KnownSubType(typeof(Dog), "dog")] 

#### Steps to reproduce

in my reproduction file polymorph-mini.json I replaced "dog" with "cachorro" to make it more plain (not a problem of case-sensitivity, but a challange to put additional mappings in place)
[polymorph-mini.json.txt](https://github.com/OpenAPITools/openapi-generator/files/2759413/polymorph-mini.json.txt)
i.e. when using the exanple polymorph-mini.json, then I miss 
 [JsonSubtypes.KnownSubType(typeof(Dog), "cachorro")] 
in .\csharp-mini\src\Org.OpenAPITools\Model\Pet.cs

reproduce with (either 3.3.4 or 4.0.0-snapshot)
java -jar openapi-generator-cli-4.0.0-20190114.050440-189.jar generate -i polymorph-mini.json -o csharp-mini -g csharp

This type of mapping is needed, whenever the derived class-names do not match with the content of a certain attribute value.

**Comment by wing328** [comment]
@StenzelRichard thanks for reporting the issue. Can you please ping me via https://gitter.im (ID: wing328)? I can work with you to get it fixed.

(we also have the `csharp-refactor` generator but likely it has the same issue)

**Comment by StenzelRichard** [comment]
I checked the generator "csharp-refactor" => it had the same issue, as you expected

**Comment by StenzelRichard** [comment]
@wing328: you are faster than the speed of light 👍 

when using:
"discriminator": {
          "propertyName": "pet_type"
}

then 
[JsonConverter(typeof(JsonSubtypes), "PetType")]
[JsonSubtypes.KnownSubType(typeof(Lizard), "Lizard")]
[JsonSubtypes.KnownSubType(typeof(Cat), "Cat")]
[JsonSubtypes.KnownSubType(typeof(Dog), "Dog")]
public partial class Pet : IEquatable, IValidatableObject....

should be emitted (we need a mapping from the string "Lizard" to the type Lizard (typeof(Lizard)))

when using:

"discriminator": {
          "propertyName": "pet_type",
          "mapping": {
            "cachorro": "#/components/schemas/Dog"
          }

then
[JsonConverter(typeof(JsonSubtypes), "PetType")]
[JsonSubtypes.KnownSubType(typeof(Lizard), "Lizard")]
[JsonSubtypes.KnownSubType(typeof(Cat), "Cat")]
[JsonSubtypes.KnownSubType(typeof(Dog), "Dog")]
[JsonSubtypes.KnownSubType(typeof(Dog), "cachorro")]
public partial class Pet : IEquatable, IValidatableObject....

should appear. I.e. the standard mappings stay in place, just an additional mapping of the string "cachorro" to the type/class dog was added.

by the way: 
Is there a standard way, how to write an integration test in c#, which uses your build pipeline? 
I mean: yes, I can test your code (super fast provided ... big thanks!!!!... don't know what to say...) in my project (will use about 100 classes with >10 mappings each), and say: yes it works (or not..). But it would be nice to have integration tests for future developments...

**Comment by wing328** [comment]
> should be emitted (we need a mapping from the string "Lizard" to the type Lizard (typeof(Lizard)))

Done. Please have another look.

> Is there a standard way, how to write an integration test in c#, which uses your build pipeline?

Yup, I'll share more details with you next week (too tired today...)

Have a nice weekend.
