### ISSUE TITLE
[REQ][PHP] Generate a high-level object to put all the APIs together

### ISSUE THREAD

**Issue by maidmaid** [OpenAPITools/openapi-generator#19140]
### Is your feature request related to a problem? Please describe.

The generator php (psr18) should have a high-level object that collects all the APIs because It's a bit boring to inject the specific API class every time.

## Describe the solution you'd like

If the generator writes an `Api\ProductApi` and an `Api\OrderApi`, such object could be like :

```php
class Client
  public function ProductApi(): ProductApi
  public function OrderApi(): OrderApi
```

## Describe alternatives you've considered

/

## Additional context

/

**Comment by wing328** [comment]
if you want to group all operations in a single class, there's a rule called `SET_TAGS_FOR_ALL_OPERATIONS` in openapi normalizer to do that:


https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer

**Comment by maidmaid** [comment]
Nice, thank your @wing328
