### ISSUE TITLE
[BUG][Kotlin][Spring] When using interfaceOnly, Spring Boot 3 needs @RestController annotation at api interface

### ISSUE THREAD

**Issue by pstorch** [OpenAPITools/openapi-generator#19156]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using interfaceOnly generation, Spring Boot 3 needs `@RestController` annotation at api interface. 

Sometimes it works without, but Spring wraps your Controller class in certain situations within a dynamic Proxy (e.g. when using security). Then your controller is not found resulting in a 404 error.

To fix this,  the API Interface needs the `@RestController` annotation.

##### openapi-generator version

7.7.0

##### Generation Details

```
openApiGenerate {
    generatorName = "kotlin-spring"
    inputSpec = "$projectDir/src/main/resources/static/openapi.yaml"
    apiPackage = "com.example.adapter.web.api"
    modelPackage = "com.example.adapter.web.model"
    modelNameSuffix = "Dto"
    cleanupOutput = true
    configOptions.set(
        mapOf(
            "sourceFolder" to "",
            "useTags" to "true",
            "interfaceOnly" to "false",
            "delegatePattern" to "false",
            "documentationProvider" to "none",
            "useBeanValidation" to "true",
            "useSpringBoot3" to "true",
            "enumPropertyNaming" to "UPPERCASE",
            "requestMappingMode" to "none",
            "skipDefaultInterface" to "true",
        )
    )
}

```
##### Steps to reproduce

Generate an API with Kotlin Spring with `interfaceOnly` set to `true`, then the interfaces only have the `@Validated` annotation, but missing the `@RestController` annotation.

##### Related issues/PRs

There is a similar issue for the Java Spring generator: https://github.com/OpenAPITools/openapi-generator/issues/18403

##### Suggest a fix

Add `@RestController` annotation at api interface.

I'll send a PR soon.

**Comment by proggler23** [comment]
This fix created a bug for us: We are using the generated api clients (feign) which implement the api interface here. Unfortunatelly, the RequestMappings for the client and an own RestController within our application have the same RequestMapping. Therefore, we got an ambiguous request mapping error. IMO, this should not happen per default, as we do not want a controller, but just a client stub.

Please, @pstorch , @4brunu consider your solution or please give me hints on where I might have fucked up on my side :)

**Comment by 4brunu** [comment]
@proggler23 do you suggest any fix to this?

**Comment by proggler23** [comment]
@4brunu I'm not sure yet, but having ClientStubs and Server-Controllers generated seems wrong to me.

For my personal case, I would be fine with a switchToggle to enable/disable the @RestController annotation. If you are fine with that, I could create a PR, if you wish so

**Comment by 4brunu** [comment]
@pstorch what do you think of this?

**Comment by pstorch** [comment]
Why using the kotlin-spring generator when you only need the client? Would the kotlin generator work for you?

**Comment by proggler23** [comment]
it fits within our currently library stack (with the spring cloud and feign clients). I haven't found any fitting library in the kotlin generator.

I know, kotlin-spring is mainly server (the generator type even says that). But that was minimum extra-libraries and a good fit in our ecosystem.

**Comment by pstorch** [comment]
@proggler23 I see maybe a feign client would be a good addition to the kotlin generator.

Would it help to set `interfaceOnly` to true, to generate the API interface stubs without the server files?

**Comment by proggler23** [comment]
@pstorch Do you mean currently, or as a new feature?

If you mean as a new feature --> so setting interfaceOnly to true in order to remove the RestController annotation. I would be perfectly fine with that and it would resolve my problem!

**Comment by pstorch** [comment]
No. the `interfaceOnly` option is available in the current version.

**Comment by pstorch** [comment]
You can also set the `requestMappingMode` to `none`

**Comment by proggler23** [comment]
it is, but it has no effect. If it helps, this is my current config and to generated output. 
![{55F47B59-38E4-408B-9D29-A98D9CE54F85}](https://github.com/user-attachments/assets/2bd3af41-1593-4c72-ac6e-39d0a57d9f2b)
![{DC18A72A-5F4D-4B90-94F7-E27CF1BB1A44}](https://github.com/user-attachments/assets/5c4e92e1-f420-4818-9fb2-07033cb03914)

I actually do not get any server files already. Also requestMappingMode has no effect for me.

**Comment by pstorch** [comment]
Haven't used `sping-cloud` myself, but as I understand it's a client generator only, right?
Maybe it would be enough to remove the `@RestController` annotation if the `spring-cloud` library is used (or if the `useFeignClient` variable) is set to true.

**Comment by pstorch** [comment]
ìnterfaceOnly` and `useFeignClient` are set to `true` if the spring-cloud library is used:

https://github.com/OpenAPITools/openapi-generator/blob/4ddfb6fc41232ccbacd1b8c0b94d42e9bf2891c1/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/KotlinSpringServerCodegen.java#L544C1-L548C10

**Comment by pstorch** [comment]
This should fix it: https://github.com/OpenAPITools/openapi-generator/pull/19877

**Comment by 4brunu** [comment]
Merged, thanks for the PR 👍
