### ISSUE TITLE
[BUG][GO] Query parameters that are not required should be generated as pointers in go-server

### ISSUE THREAD

**Issue by phil-bugdahn-hs** [OpenAPITools/openapi-generator#19169]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using the `go-server` generator, query parameters with `required: false` are being generated as value types. Using the example spec below, this generates a method signature like the following:
```
type DefaultAPIServicer interface { 
	RootGet(context.Context, bool) (ImplResponse, error)
}
```
Since the default value of `bool` is false, it is not possible to tell whether the client passed `false` to the parameter or simply did not provide it at all. By using a pointer instead, the parameter could be `nil` when not passed by the client. The method signature should look like the following:
```
type DefaultAPIServicer interface { 
	RootGet(context.Context, *bool) (ImplResponse, error)
}
```

##### openapi-generator version

7.7.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
security: []
info:
  description: >-
    This is a sample spec to demonstrate handling non-required boolean query parameters in the go-server generator
  version: 1.0.0
  title: Boolean sample
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /:
    get:
      summary: Sample endpoint
      description: Demonstrate handling of non-required boolean query parameters
      parameters:
        - in: query
          name: someParam
          description: a test parameter
          schema:
            type: boolean
          required: false
      responses:
        '200':
          description: Demo
          content:
            application/json:
              schema:
                type: string
```

##### Generation Details

This bug can be reproduced using the `go-server` generator with no additional settings.

##### Steps to reproduce

- Copy the above spec into a file and save at `./openapi/openapi.yaml`
- Run the generator with the command: `java -jar openapi-generator-cli.jar generate -i ./openapi/openapi.yaml -o ./server-gen -g go-server`
- Observe the generated server code in the `server-gen` directory, eg. `./server-gen/go/api.go`, note that the `RootGet` method signature takes a `bool`  rather than a `*bool` parameter.

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/pull/19149

Would appreciate the Go technical committee reviewing this issue and my suggested fix (@antihax, @grokify, @kemokemo, @jirikuncar, @ph4r5h4d, @lwj5)

**Comment by lwj5** [comment]
Have you tried?

```
openapi: 3.0.0
security: []
info:
  description: >-
    This is a sample spec to demonstrate handling non-required boolean query parameters in the go-server generator
  version: 1.0.0
  title: Boolean sample
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /:
    get:
      summary: Sample endpoint
      description: Demonstrate handling of non-required boolean query parameters
      parameters:
        - in: query
          name: someParam
          description: a test parameter
          schema:
            type: boolean
            nullable: true
          required: false
      responses:
        '200':
          description: Demo
          content:
            application/json:
              schema:
                type: string
```

**Comment by phil-bugdahn-hs** [comment]
@lwj5 Thanks for this sample, I had tried something similar but didn't realize the `nullable` property had to be under `schema`. This does indeed address the problem so I will close this issue/PR. Thanks for your time.
