### ISSUE TITLE
[BUG] Use of Task.Result directly blocks thread

### ISSUE THREAD

**Issue by rfriend-zilo** [OpenAPITools/openapi-generator#19176]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The direct call here to Task.Result is blocking the thread, and when used in a blazor application prevents UI from rendering : 

https://github.com/OpenAPITools/openapi-generator/blob/9ae877598713eff7c6b1bbb53c5b3b8ed22fa1f2/modules/openapi-generator/src/main/resources/csharp/ApiClient.mustache#L628

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/18915/files/0639c25fe8affd4c6ad8ea3d26711cc0f83a7bf1

##### Suggest a fix

Rather than calling async code from sync code using .Result, inside ExecAsync just await action() then construct Func<RestClient, RestResponse<T>> getResponse using the result from that awaited call.

**Comment by wing328** [comment]
> Rather than calling async code from sync code using .Result, inside ExecAsync just await action() then construct Func<RestClient, RestResponse> getResponse using the result from that awaited call.

can you please file a PR with the suggested fix when you've time?

**Comment by rfriend-zilo** [comment]
My solution was not correct, my suggestion is to revert the changes in the PR.

**Comment by wing328** [comment]
@filipe-silva can you please review this issue reported by @rfriend-zilo when you've time?

**Comment by filipe-silva** [comment]
> @filipe-silva can you please review this issue reported by @rfriend-zilo when you've time?

This concern makes sense, I did a fix to resolve this issue.
How do I merge it?

**Comment by wing328** [comment]
@filipe-silva can you please file a new PR?

**Comment by wing328** [comment]
@rfriend-zilo can you please review the fix when you've time?

https://github.com/OpenAPITools/openapi-generator/pull/19231
