### ISSUE TITLE
Endpoint not generated with the right body parameter

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-generator#192]
##### Description

I really don't understand this one.

I have an endpoint declared like this:

```
  /message-calendars/{message-calendar-id}/message-events:
    post:
      tags:
        - Messaging
      summary: Add a message event to the given message calendar
      operationId: addMessageEventToMessageCalendar
      parameters:
        - $ref: "#/parameters/message-calendar-id"
        - in: body
          name: new-message-event
          required: true
          schema:
            $ref: "./definitions.yaml#/definitions/MessageEventCoreWithTimeListEntries"
      responses:
        200:
          description: OK
          schema:
            $ref: "./definitions.yaml#/definitions/GetMessageEventResponse"
```

The `MessageEventCoreWithTimeListEntries` is declared like this:

```
  MessageEventCoreWithTimeListEntries:
    type: object
    description: "Base of a message event with Time List entries"
    allOf:
      - $ref: "#/definitions/MessageEventCore"
      - type: object
        required:
          - timeListEntries
        properties:
          timeListEntries:
            type: array
            items:
              $ref: "#/definitions/TimeListEntry"
```

Strangely, the endpoint is generated like this:

`GetMessageEventResponse addMessageEventToMessageCalendar(Long messageCalendarId, MessageEventCore body) throws Exception;`

Instead of:

`public GetMessageEventResponse addMessageEventToMessageCalendar(Long messageCalendarId, MessageEventCoreWithTimeListEntries newMessageEvent) throws Exception;`

Please note that the `MessageEventCoreWithTimeListEntries` model is generated, but not used in the declaration of the endpoint...

##### openapi-generator version

Latest master

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i swagger.yaml --generator-name java-play-framework -o generatedServer -DhideGenerationTimestamp=true`

##### Steps to reproduce

Just run the above command

##### Related issues/PRs

No idea

##### Suggest a fix/enhancement

No idea!

**Comment by JFCote** [comment]
I have tagged this in 3.0.2 because I think this is very blocking and we should not release anything without this fix but feel free to move it to 3.0.3 or later if needed. I just don't want it to be forgotten.

**Comment by jmini** [comment]
Thank you for the bug report and the investigation.

This is of course a big issue for you (and for other users using the same pattern). The release `3.0.2` is due next monday. If nobodies provide a PR to fix this, it will move to the next release...

**Comment by jmini** [comment]
Here a standalone spec to reproduce the problem:

```yaml
swagger: "2.0"
info:
  version: "2"
  title: "Test API"
basePath: "/xx2"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /ping:
    post:
      tags:
        - Messaging
      summary: Add a message event to the given message calendar
      operationId: addMessageEventToMessageCalendar
      parameters:
        - in: body
          name: new-message-event
          required: true
          schema:
            $ref: "#/definitions/MessageEventCoreWithTimeListEntries"
      responses:
        200:
          description: OK
definitions:
  MessageEventCoreWithTimeListEntries:
    type: object
    description: "Base of a message event with Time List entries"
    allOf:
      - $ref: "#/definitions/MessageEventCore"
      - type: object
        required:
          - timeListEntries
        properties:
          timeListEntries:
            type: array
            items:
              $ref: "#/definitions/TimeListEntry"
  MessageEventCore:
    type: object
    properties:
      id:
        type: integer
      message:
        type: string
  TimeListEntry:
    type: object
    properties:
      p1:
        type: string
      p2:
        type: string
```

The wrong generated code can be seen in:
`<generated project>/app/controllers/MessagingApiControllerImp.java`

```java
public class MessagingApiControllerImp implements MessagingApiControllerImpInterface {
    @Override
    public void addMessageEventToMessageCalendar(MessageEventCore body) throws Exception {
        //Do your magic!!!
    }

}
```

**Comment by JFCote** [comment]
@jmini Thanks. I understand. I would provide a PR myself my I didn't play a lot with the core, mostly worked on multiple generators.

**Comment by jmini** [comment]
Have you the possibility to try the version in my PR: #358
I think it solves your problem.

**Comment by JFCote** [comment]
@jmini Will try this today and let you know!

**Comment by JFCote** [comment]
@jmini  Will try in the upcoming days, not sure when. A lot going on right now. Sorry for the delay

**Comment by JFCote** [comment]
@jmini I confirm that the changes work! Do you need any other confirmation? I could merge this right now if you want.

**Comment by jmini** [comment]
I have merged the change. Please test `3.0.3-SNAPSHOT` and mark this issue as closed.

**Comment by JFCote** [comment]
Confirmer fixed in `3.0.3-SNAPSHOT`, closing this issue! Thanks a lot!

**Comment by softarts** [comment]
I still sae this in 3.4.0 with python generated code:
RetrieveCustomWordsResponse:
      allOf:
      - $ref: '#/components/schemas/CommonResponse'
      - type: object
        properties:
          name:
            type: string
            description: the name
          words:
            type: array
            items:
              type: string
            description:  the desc
the generated class 'RetrieveCustomWordsResponse' doesn't have the property in 'CommonResponse'

**Comment by softarts** [comment]
just tried 4.0.0 snapshot, it is fixed.@wing328

**Comment by wing328** [comment]
@softarts Thanks for the confirmation. Happy holidays!
