### ISSUE TITLE
[BUG] Error decoding enum on Swift when there is a new enum.

### ISSUE THREAD

**Issue by waterdrake** [OpenAPITools/openapi-generator#19243]
##### Description

The generated Swift API produces this runtime error when there is a new enum value being returned from the backend:

dataCorrupted(Swift.DecodingError.Context(codingPath: []], debugDescription: "Cannot initialize Enum from invalid String value", underlyingError: nil))

This crashes the whole app. Is there a way around this?

##### openapi-generator version

7.0.1

##### Suggest a fix

Is there a way to generate the swift client to not crash during runtime when there is an enum it doesn't know?

**Comment by 4brunu** [comment]
Yes, you should check the enumUnknownDefaultCase configuration in https://openapi-generator.tech/docs/generators/swift5.
