### ISSUE TITLE
[BUG][PYTHON] Deserialize json vendor extensions broken since 7.7.0

### ISSUE THREAD

**Issue by kevinferrare** [OpenAPITools/openapi-generator#19285]
#### Bug Report Checklist
- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Since this commit, generated python api_client cannot handle deserializing json with a content type that does not start with application/json. 
For example vendor extensions like application/vnd.amadeus+json

https://www.iana.org/assignments/media-types/application/vnd.amadeus+json

https://github.com/OpenAPITools/openapi-generator/commit/6ae8a8f4c7b00ed15bbb3cfdc49a7b99dbb56c4b

##### openapi-generator version

7.7.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Test
  version: '1.0'
paths:
  '/test':
    get:
      requestBody:
        content:
          application/vnd.amadeus+json:
            schema:
              type: object
              title: TestObject
              properties:
                id:
                  type: string
      responses:
        '200':
          description: OK
```

##### Generation Details

java -jar openapi-generator-cli-7.8.0-SNAPSHOT.jar generate -o ./generated -i ./test-api.yaml -g python

##### Steps to reproduce

Save the API declaration in a file and generate it.

When calling test_get() method, it fails with an exception because it doesnt understand application/vnd.amadeus+json is json:
```
ApiException: (0) Reason: Unsupported content type: application/vnd.amadeus+json;charset=UTF-8
```

##### Related issues/PRs

None I could find

##### Suggest a fix

In the api_client files updated by the commit I mention, Replace:
```python
elif content_type.startswith("application/json"):
```
With:
```python
elif content_type.startswith("application/json") or content_type.endswith("+json"):
```

**Comment by fa0311** [comment]
related: #18800
