### ISSUE TITLE
[BUG][PHP] `accept` header is sometimes erased  

### ISSUE THREAD

**Issue by maidmaid** [OpenAPITools/openapi-generator#19286]
In the next example, the endpoint accept to configure `accept` header.

![image](https://github.com/user-attachments/assets/44d141b2-1350-4431-a323-4ae6a10ca679)

But the next lines of code erase the value given to `accept` header.

https://github.com/OpenAPITools/openapi-generator/blob/484b87f22a79779ec75f04a672175b702cad7fea/modules/openapi-generator/src/main/resources/php/libraries/psr-18/api.mustache#L684-L688

A fixe should be to change parameters order to give the priority to headers params :

```php
$headers = array_merge(
    $defaultHeaders,
    $headers,
    $headerParams,
);
```

**Comment by wing328** [comment]
@maidmaid i think default headers should have the highest priority to allow users to override everything defined in the spec.

`Accept` (not parameter) defined in the spec should have the lowest priority.

**Comment by ybelenko** [comment]
> Wdyt @ybelenko ?

As far as I remember `Accept` shouldn't be a header parameter. Since current OpenApi spec allows to describe any response type, then in a perfect world generated client library should provide a way to choose response type and build `Accept` header accordingly.
Maybe it should be tree different methods like `getUsersJson`, `getUsersXml`, `getUsersBinary` or maybe it should be methods argument `getUsers($responseType = "json")`.
I wouldn't add `Accept` to spec header parameters and agree with @wing328

**Comment by maidmaid** [comment]
Thanks for your answers sirs :+1: 

> it should be methods argument getUsers($responseType = "json")

The generated result for the example given in the description is:

```php
public function getTicket($accept, $bookingId, $ticketId, $xConversationId = null, $xContractId = null)
```

So, it is already an argument but it is erased by the others headers.

In my opinion, the generated client should follow the best design as you explained. But it should also allow to be configurated in a way to fit real situations where OpenAPI specs aren't always compliant with the best practices like in my case. Furthermore, in that kind of endpoints (ticket/invoice generation), it's very common to handle types (pdf, png, text...) with the `accept` header. In any cases, I don't have any control of this 3rd tier OpenAPI spec where I'm just a external consumer and I have right now to edit the generated code as a workaround.

**Comment by ybelenko** [comment]
> have right now to edit the generated code as a workaround.
You're absolutely right, just change your template the way you need. We can't merge that code, because it modifies default template.
