### ISSUE TITLE
[csharp] Update restsharp to the latest stable version

### ISSUE THREAD

**Issue by ondrej-krc-jediny** [OpenAPITools/openapi-generator#19387]
Update RestSharp to the latest stable version (111.4.1). The version 110.2.0 used currently has a dependency on System.Text.Json 7.0.2, which is [vulnerable](https://www.nuget.org/packages/System.Text.Json/7.0.2) with high severity. The latest stable version 111.4.1 depends on System.Text.Json 8.0.4, that is not vulnerable.

**Comment by wing328** [comment]
thanks for opening a ticket/issue on this

would you like to contribute a PR to update the version to the latest?

a good reference PR is https://github.com/OpenAPITools/openapi-generator/pull/16122

**Comment by jacobilsoe** [comment]
I think it should be upgraded to 1.112.0 since older versions are vulnerable: https://security.snyk.io/vuln/SNYK-DOTNET-RESTSHARP-7853196

**Comment by jacobilsoe** [comment]
Thank you @wing328
