### ISSUE TITLE
[BUG] Latest Docker image is v7.9.0 instead of v7.8.0

### ISSUE THREAD

**Issue by florentausha** [OpenAPITools/openapi-generator#19389]
##### Description

On the Docker hub:  
https://hub.docker.com/r/openapitools/openapi-generator-cli/tags

The latest version is v7.9.0 instead of v7.8.0 ;)

**Comment by wing328** [comment]
let me take a look

**Comment by wing328** [comment]
v7.8.0 should be published shortly

thanks again for reporting the issue

**Comment by florentausha** [comment]
Thanks @wing328 ! :)

**Comment by wing328** [comment]
published

please check again when you've time

(v7.9.0 images were deleted)

**Comment by florentausha** [comment]
OK for me, thanks for the fix!
