### ISSUE TITLE
[REQ] Kotlin clients add a new additional  property to change the generated Jackson's ObjectMapper's FAIL_ON_UNKNOWN_PROPERTIES's value

### ISSUE THREAD

**Issue by ashirman** [OpenAPITools/openapi-generator#19408]
### Is your feature request related to a problem? Please describe.

adds a new additional and non mandatory property to change the generated Jackson's ObjectMapper's FAIL_ON_UNKNOWN_PROPERTIES's value

## Describe the solution you'd like

need to make changes similar to what was done in [this PR](https://github.com/OpenAPITools/openapi-generator/pull/19271) to cover Kotlin generated sources.

## Additional context

was asked open a ticket in this PR https://github.com/OpenAPITools/openapi-generator/pull/19271#discussion_r1711407941 to align Java and Kotlin behaviour.

**Comment by fistons** [comment]
I will work on a PR to address this as soon as I can
