### ISSUE TITLE
[BUG] [GO] [go-server] Incorrect data type for routes definition

### ISSUE THREAD

**Issue by Kashugoyal** [OpenAPITools/openapi-generator#19445]
##### Description

For routes defined as the following
```
getPost/latest
getPost/{postId}
```
and stored in a type defined as:
```
// Routes is a map of defined api endpoints
type Routes map[string]Route
```
Refer code [here](https://github.com/OpenAPITools/openapi-generator/blob/2b40a2c05887e77b81ab872c976a00005e97ceaf/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L39).

The api routes are registered with the router by [iterating over the map](https://github.com/OpenAPITools/openapi-generator/blob/2b40a2c05887e77b81ab872c976a00005e97ceaf/modules/openapi-generator/src/main/resources/go-server/routers.mustache#L66) and since native maps are unordered in golang, this leads to unexpected route ordering and breaks the above two routes (as they depend on route precedence for path matching).

##### openapi-generator version

Latest 7.9.0

##### OpenAPI declaration file content or url

Test [api.yaml can be downloaded here](https://gist.github.com/Kashugoyal/29d9a57d9e04dfb76d816ddd3c6401ce)

##### Generation Details

You can use any method of generation but I used the following:
```
npx @openapitools/openapi-generator-cli generate -i api.yaml -g go-server -o ./server
```

##### Steps to reproduce

Based on the Golang language spec [here](https://go.dev/ref/spec#For_range), 
`The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.`

So reruns of the server may lead to different paths being matched if one was registered with the router first. 

##### Related issues/PRs
Sounds similar but  is **not**:
https://github.com/OpenAPITools/openapi-generator/issues/14660 

##### Suggest a fix
Use an ordered data type to store the routes such as a list.

**Comment by gcatanese** [comment]
The problem is in the generator code when sorting the OpenAPI operations. Re-ordering the operations (routes) doesn't work for the Go Server generator, see #19550
