### ISSUE TITLE
[BUG] default basePath is different than in swagger-codegen

### ISSUE THREAD

**Issue by tomplus** [OpenAPITools/openapi-generator#1946]
##### Description

The openapi-generator has default basePath defined here:

https://github.com/OpenAPITools/openapi-generator/blob/c51f333f6c9d0a58366879e85dafb4c0b0afdc2d/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L40

but the swagger-codegen has `https://localhost`  - the schema is different:

https://github.com/swagger-api/swagger-codegen/blob/c4c5c062cd25db43cd0aa93882560f278e6cd4f7/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L103

##### Suggest a fix

Use default `https://localhost` as swagger-codegen - or update the migration guide.

**Comment by wing328** [comment]
@tomplus thanks for reporting this. I'll update the migration guide accordingly.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/1957
