### ISSUE TITLE
[BUG][PYTHON-FASTAPI] Generator README.md uses hard-coded default packageName

### ISSUE THREAD

**Issue by DavidRV00** [OpenAPITools/openapi-generator#19480]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When I run the python-fastapi generator, with the python-fastapi templates provided in this repo, and specify `packageName`, the generated README.md doesn't pick it up for the example uvicorn command: `PYTHONPATH=src uvicorn openapi_server.main:app --host 0.0.0.0 --port {{serverPort}}`

##### openapi-generator version

Latest master branch as of Aug 28 2024.

##### OpenAPI declaration file content or url

I'm using the provided petstore.yaml, but it shouldn't matter.

##### Generation Details

```
openapi-generator generate \
    -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
    -g python-fastapi \
    -t modules/openapi-generator/src/main/resources/python-fastapi \
    --additional-properties packageName=my_custom_name,fastapiImplementationPackage=my_custom_name.impl \
    -o ~/myprojects/api
```

##### Steps to reproduce

Run the above generator command and open the README.md. You will see that the uvicorn command specifies `openapi_server.main:app` even though packageName was used to specify something other than `openapi_server` (should be `my_custom_name.main:app`)

##### Suggest a fix

Change the line in the provided template README.mustache from:

```
PYTHONPATH=src uvicorn openapi_server.main:app --host 0.0.0.0 --port {{serverPort}}
```

to:

```
PYTHONPATH=src uvicorn {{packageName}}.main:app --host 0.0.0.0 --port {{serverPort}}
```

**Comment by wing328** [comment]
can you please file a PR with the suggested fix?
