### ISSUE TITLE
[REQ] Option to remove keywords

### ISSUE THREAD

**Issue by SebastianStehle** [OpenAPITools/openapi-generator#19503]
### Is your feature request related to a problem? Please describe.

I am working on a client for Java and I have a parameter called "file". Unfortunately this parameter is in the list of reserved words and I have actually no idea why. 

## Describe the solution you'd like

Option to remove parameters from the reserved words would be great. The result is generated code, if you have a strongly typed language it should be easy to determinate whether the code works or not.

## Describe alternatives you've considered

I have tested a mapping and it works great, but I want consistend naming across my SDKs. I have considered to just fork the repo and build my own container.

**Comment by jpfinne** [comment]
You can achieve this with the reservedWordMapping option.

For example with the maven plugin:
```
<reservedWordsMappings>
    <reservedWordsMapping>file=file</reservedWordsMapping>
</reservedWordsMappings>
```

This is more flexible than just removing keywords

**Comment by wing328** [comment]
> I have a parameter called "file"

what about using parameter naming mapping instead?

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping

see `parameterNameMapping`

**Comment by wing328** [comment]
are you using the latest stable version of openapi genrator v7.8.0 ?
