### ISSUE TITLE
[BUG] [Javascript] Setting a property as default doesn't work

### ISSUE THREAD

**Issue by Poolmann** [OpenAPITools/openapi-generator#19604]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### openapi-generator version

7.8.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Title
  description: Title
  version: 1.0.0
paths:
  '/user':
    get:
      responses:
        200:
          description: "success"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequiredProperties'

components:
  schemas:
    RequiredProperties:
      type: object
      required:
        - requiredWithDefault
        - requiredWithoutDefault
      properties:
        requiredWithDefault:
          type: string
          default: "4.5.0"
        requiredWithoutDefault:
          type: string
        notRequiredWithDefault:
          type: string
          default: "4.5.0"
        notRequiredWithoutDefault:
          type: string
```

##### Generation Details

`java -jar openapi-generator-cli.jar generate -i required.yaml -g javascript -o req_test`

##### Steps to reproduce

Generate client, run:
```js
var Title = require("title");

var test = new Title.RequiredProperties();
console.log(test)
```
Output:
```
RequiredProperties {
  requiredWithDefault: '4.5.0',
  requiredWithoutDefault: undefined
}
```

I would expect properties with a default to be initialized as well (with the DEFAULT). Especially since this is the case with all the other generators that I'm using (Java, Python, C#, PHP).

**Comment by wing328** [comment]
> I would expect properties with a default to be initialized as well (with the DEFAULT).

thanks for reporting the issue.

May I know if you've time to contribute a PR to add the default value support in the JS client? We can work with you on that.

**Comment by Poolmann** [comment]
> May I know if you've time to contribute a PR to add the default value support in the JS client?

Not right now, but I will probably have to look into the issue in the near future.

**Comment by Poolmann** [comment]
I actually got sooner to it than I thought. It would be nice if someone looked into it. The changes are minimal.
