### ISSUE TITLE
[REQ][JAVA] Add @Nullable/@Nonnull annotations to POJO attributes and setters

### ISSUE THREAD

**Issue by nvervelle** [OpenAPITools/openapi-generator#19600]
I'm using java generator for webclient, and the generated [POJO classes only contain `@Nullable`/`@Nonnull` annotations for the getters](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/pojo.mustache#L214), but not for the attributes themselves or the setters.

When using tools like [NullAway](https://github.com/uber/NullAway), it causes some issues because you cannot easily use the fluent setters when setting a nullable attribute, because the setter is not annotated with `@Nullable`.

I'd like to add the annotations to the attributes and the setters, so that it's easier to enable tools like NullAway on code using the generated clients.

I will submit a PR for this feature request.

**Comment by c99SRS** [comment]
Hi @nvervelle pls assign this to me. Want to work on this

**Comment by nvervelle** [comment]
@c99SRS : the PR is submitted, what is the work you were thinking of ?
