### ISSUE TITLE
[BUG] Python client generator doesn't handle schema clashes

### ISSUE THREAD

**Issue by brendanator** [OpenAPITools/openapi-generator#19612]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The [GitHub openapi spec](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.json) contains a `commit` object which contains an inner `commit` object.

When I generate a client using the Python generator only the inner `commit` object is generated

##### openapi-generator version

```
$ docker run --rm openapitools/openapi-generator-cli:latest --version
openapi-generator-cli 7.9.0-SNAPSHOT
  commit : ca378b4
  built  : -999999999-01-01T00:00:00+18:00
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
```

##### OpenAPI declaration file content or url

Here's the full [GitHub openapi spec](https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.json) and here's the relevant snippet

```json
      "commit": {
        "title": "Commit",
        "description": "Commit",
        "type": "object",
        "properties": {
          ...
          "commit": {
            "type": "object",
            "properties": {
              "url": {
                "type": "string",
                "format": "uri",
                "example": "https://api.github.com/repos/octocat/Hello-World/commits/6dcb09b5b57875f334f61aebed695e2e4193db5e"
              },
              "author": {
                "$ref": "#/components/schemas/nullable-git-user"
              },
              "committer": {
                "$ref": "#/components/schemas/nullable-git-user"
              },
              "message": {
                "type": "string",
                "example": "Fix all the bugs"
              },
              "comment_count": {
                "type": "integer",
                "example": 0
              },
              "tree": {
                "type": "object",
                "properties": {
                  "sha": {
                    "type": "string",
                    "example": "827efc6d56897b048c772eb4087f854f46256132"
                  },
                  "url": {
                    "type": "string",
                    "format": "uri",
                    "example": "https://api.github.com/repos/octocat/Hello-World/tree/827efc6d56897b048c772eb4087f854f46256132"
                  }
                },
                "required": [
                  "sha",
                  "url"
                ]
              },
              "verification": {
                "$ref": "#/components/schemas/verification"
              }
            },
            "required": [
              "author",
              "committer",
              "comment_count",
              "message",
              "tree",
              "url"
            ]
          },
          ...
```

##### Generation Details

```
docker run --rm -v /tmp:/local openapitools/openapi-generator-cli:latest generate \
  --input-spec https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.2022-11-28.json \
  --generator-name python \
  --output /local
```

##### Steps to reproduce

1. Run the docker generation command above
2. `cat /tmp/openapi_client/models/commit.py`
3. See that it is the inner commit object and the outer one does not exist

##### Suggest a fix

I suggest including the outer name in the name of nested objects - in this case the inner class would be named `CommitCommit`

**Comment by wing328** [comment]
to have completed control of inline schema naming, please refer to https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#inline-schema-naming
