### ISSUE TITLE
[BUG] Using `model-name-prefix` with `rust-axum` results in uncompilable code due to adding the prefix twice in `server/mod.rs`

### ISSUE THREAD

**Issue by jdanton-believer** [OpenAPITools/openapi-generator#19632]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Using `-g rust-axum` in conjunction with `--model-name-prefix=Foo` results in `models::FooFoo{Object}` in generated `server/mod.rd` and uncompilable code.

##### openapi-generator version

openapi-generator-cli 7.9.0-SNAPSHOT
  commit : eebecc8

##### OpenAPI declaration file content or url

You can use the provided test `petstore` spec (https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml)

##### Generation Details

```
openapitools/openapi-generator-cli help generate \
    -i petstore.yaml \
    -g rust-axum \
    -o /local/out \
    --model-name-prefix=Foo
```

##### Steps to reproduce

* Run the provided generation command.
* Try to compile.
* Look at line 73 in `server/mod.rs`

##### Suggest a fix

I am guessing it is connected to https://github.com/OpenAPITools/openapi-generator/blob/eebecc864660805fb2ef99b1976ec9b6a0446f45/modules/openapi-generator/src/main/resources/rust-axum/server-operation-validate.mustache#L65 which means `dataType` is getting the prefix added twice.

**Comment by linxGnu** [comment]
Hello @jdanton-believer 

Thank you for reporting the issue. 

There is a bug in `AbstractRustCodegen` which is shared between RustAxumServer, RustClient, RustServer: [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractRustCodegen.java#L248-L249)

```java
datatype = toModelName(ModelUtils.getSimpleRef(p.get$ref()));
datatype = "models::" + toModelName(datatype);
```

Should change to:
```java
datatype = "models::" + toModelName(ModelUtils.getSimpleRef(p.get$ref()));
```

How do you think @wing328 I can make a PR to fix the issue. Calling `toModelName` twice is a bug imho!

**Comment by linxGnu** [comment]
Noted: tried to fix that at my local, generated code worked perfectly (ran integration test as well)

**Comment by GeorgeFkd** [comment]
Trying to create the echo_api(more advanced api integration test) sample i also came across this and can confirm(i reached the same conclusion that something is happening there), this is also happening for the rust-reqwest generator, even without the model-name-prefix parameter. 

@linxGnu when you submit your PR ping me so i can take a look at it.

**Comment by linxGnu** [comment]
@GeorgeFkd 
PTAL: https://github.com/OpenAPITools/openapi-generator/pull/19922
