### ISSUE TITLE
[BUG] Calls off multiple threads cannot run concurrently in Swift 4

### ISSUE THREAD

**Issue by DavePilks** [OpenAPITools/openapi-generator#1966]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?

##### Description

When creating the `ResponseData` object in `AlamofireImplementations.swift`, no dispatch queue is passed into the `init`. This means that `Alamofire` defaults to `DispatchQueue.main`.

If you then have multiple threads trying to make service calls, they are all placed on the main queue and cannot run concurrently as there is only a single thread.

We noticed this as we were trying to break out of the callback pattern using a semaphore. This is when we noticed the blocking.

##### openapi-generator version

3.3.4

##### Steps to reproduce

Call Setup
* Use semaphore to block until call back is fire
* Return result from callback

Queuing
* Have multiple call running in the background queue 

Expected Result
The calls return once the call has been completed

Actual Result
The calls block

##### Suggest a fix

The `init` for the `Alamofire` response takes in a queue parameter that is defaulted to `nil`. Suggested fix is to provide `DispatchQueue.global(qos: .background)` as the parameter to allow concurrency

**Comment by wing328** [comment]
@DavePilks thanks for reporting the issue. Do you mind filing a PR with the suggested fix so that we can review it more easily?

**Comment by DavePilks** [comment]
It is in the works, just a bit busy at the moment but I should get something out by the end of the week.

**Comment by wing328** [comment]
@DavePilks thanks. Let us know if you need any help.

**Comment by joeboyscout04** [comment]
Related to https://github.com/OpenAPITools/openapi-generator/issues/230? Is there a way we can pass the queue so caller can control which queue it's on?

**Comment by wing328** [comment]
The fix is available in the newly-added swift5 generator so closing this one instead.
