### ISSUE TITLE
Windows 11 org/openapitools/codegen/OpenAPIGenerator has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by orbx-ruslan** [OpenAPITools/openapi-generator#19700]
Installed the latest Java for Windows:
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 1.8.0_421-b09)
Java HotSpot(TM) Client VM (build 25.421-b09, mixed mode, sharing)

there is no version 11 for Windows, if I miss it, please tell me where to get it

**Comment by wing328** [comment]
you can download JDK 11 installer from https://adoptium.net/

or use docker instead if you don't want to install JDK: https://hub.docker.com/r/openapitools/openapi-generator-cli

**Comment by orbx-ruslan** [comment]
this helps: https://www.oracle.com/java/technologies/downloads/#jdk23-windows

**Comment by orbx-ruslan** [comment]
> you can download JDK 11 installer from https://adoptium.net/
> 
> or use docker instead if you don't want to install JDK: https://hub.docker.com/r/openapitools/openapi-generator-cli

thank you
