### ISSUE TITLE
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

### ISSUE THREAD

**Issue by mustafacco7** [OpenAPITools/openapi-generator#19705]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/OpenAPITools/openapi-generator/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

_Originally posted by @wing328 in https://github.com/OpenAPITools/openapi-generator/issues/16735#issuecomment-1754302093_

**Comment by wing328** [comment]
PR already merged: https://github.com/OpenAPITools/openapi-generator/pull/16735
