### ISSUE TITLE
[BUG][JAX-RS Jersey 2] Generating @DefaultValue for query parameter Arrays causing server startup failure

### ISSUE THREAD

**Issue by calebmiller010** [OpenAPITools/openapi-generator#1970]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
When generating with OpenAPI Generator version 3.3.0 (and before), this is the generated code:
```java
    public Response getPetByTagIds(
@ApiParam(value = "The tag id(s) to search with",required=true) @QueryParam("tagIds") List<Long> tagIds
...
```

This works fine, and I do not run into any issues with this code.

After bumping the OpenAPI Generator version to 3.3.1 (and beyond), the code generation made a non-passive change that causes the server to fail when starting up.

When generating an API definition that has a query parameter that accepts multiple Long values, the generated code in the *Api.java files defines a `@DefaultValue` that causes Jersey to throw a [NumberFormatException](https://gist.github.com/calebmiller010/057577f358420b331d1a4248cf62f585) and fail to start up. 

The generated code looks like:
```java
    public Response getPetByTagIds(
@ApiParam(value = "The tag id(s) to search with",required=true, defaultValue="new ArrayList<Long>()") @DefaultValue("new ArrayList<Long>()") @QueryParam("tagIds") List<Long> tagIds
...
```
OR if generated with java8 option TRUE:
```java
    public Response getPetByTagIds(
@ApiParam(value = "The tag id(s) to search with",required=true, defaultValue="new ArrayList<>()") @DefaultValue("new ArrayList<>()") @QueryParam("tagIds") List<Long> tagIds
...
```
either way, failure occurs when the server attempts to start.

##### openapi-generator version

3.3.1 (and beyond). This is not an issue with 3.3.0 (and below).

##### OpenAPI declaration file content

```yaml
  /pet/findByTags:
    get:
      description: Service for retrieving pets by searching with multiple tags
      parameters:
        - name: tagIds
          in: query
          description: The tag id(s) to search with
          required: true
          explode: true
          schema:
            type: array
            items:
              type: integer
              format: int64
```

##### Command line used for generation

Using the openapi-generator-maven-plugin with:
* jaxrs-jersey generator
* jersey2 library

##### Steps to reproduce

Generate the code with openapi-generator 3.3.1, with the OpenAPI definition resembling what is shown in the code snippet above (i.e. any query parameter that is a list/array). 

With the generated PetApi.java file in the server classpath, attempt to start a Jersey 2 server. It should fail upon server startup with a [NumberFormatException](https://gist.github.com/calebmiller010/057577f358420b331d1a4248cf62f585).

##### Related issues/PRs

Unable to find any related issues; this was a pretty recent change that caused this issue. I've traced it to [this commit](https://github.com/OpenAPITools/openapi-generator/commit/999f472e4bfe091c02b2bdc8813d7e9c7a534614#diff-7cb46fa53f89a458a7b7cb201d2214a8R2743) where `@DefaultValue` is now always defined in the generated code.

##### Suggest a fix

I am not too familiar with OpenAPI Generator's internal workings, but I believe this would require a change either to:
* DefaultCodeGen, but I would be concerned about passivity
* the JAX-RS Api.mustache file; some way to avoid generating the `@DefaultValue` in this scenario

This could also be an issue on Jersey's side of things, I am not really sure. And with the OpenAPI definition, I am able to get around this issue if the "tagId" format is changed from an integer to string, as this is not an issue with Jersey 2 when `List<String> tagIds` has `@DefaultValue("new ArrayList<String>()")`. But, I still felt like an issue should be logged for this, as it was a breaking change and blocks an upgrade to using a version of OpenAPI Generator greater than 3.3.0 without making changes to the OpenAPI definition.

**Comment by MiltosKoutsokeras** [comment]
The above is not the only case where this error rises:
```
org.glassfish.jersey.internal.inject.ExtractorException: java.lang.NumberFormatException
```

It happened on my setup also, so I created the minimal case to showcase the problem.
I use the Maven generator version **3.3.4**, jaxrs-jersey server stubs:
```
<plugin>
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>3.3.4</version>
<executions><execution><goals><goal>generate</goal></goals>
<configuration>
	<inputSpec>${project.basedir}/src/main/resources/openapiv3.yaml</inputSpec>
	<validateSpec>true</validateSpec>
	<generatorName>jaxrs-jersey</generatorName>
	<configOptions>
		<sourceFolder>src/gen/java/main</sourceFolder>
		<dateLibrary>java8</dateLibrary>
		<java8>true</java8>
		<library>jersey2</library>
	</configOptions>
</configuration>
</execution>
</executions>
</plugin>
```
This is a small spec that triggers it:
```
components:
  responses:
    Error:
      description: Error message.
      content:
        '*/*':
          schema:
            type: string
  schemas:
    Foobar:
      type: integer
      format: int32
      minimum: 1
    Item:
      type: object
      required:
        - name
      properties:
        name:
          type: string
    Result:
      type: array
      items:
        $ref: "#/components/schemas/Item"
paths:
  /bug:
    get:
      operationId: bugQueryGET
      parameters:
        - in: query
          name: foobar
          required: true
          schema:
            $ref: "#/components/schemas/Foobar"
      responses:
        '200':
          description: The HTTP/200 response.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Result"
        # Any response that is not HTTP/200 OK is considered an error.
        default:
          $ref: "#/components/responses/Error"
```
The `Result` component is added due to another bug I will open shortly. This spec produces this API class:
```
package org.openapitools.api;

import org.openapitools.api.*;
import org.openapitools.model.*;

import org.glassfish.jersey.media.multipart.FormDataContentDisposition;

import org.openapitools.model.Item;

import java.util.List;
import org.openapitools.api.NotFoundException;

import java.io.InputStream;

import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;
import javax.validation.constraints.*;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaJerseyServerCodegen", date = "<TIMESTAMP here>")
public abstract class BugApiService {
    public abstract Response bugQueryGET( @NotNull Integer foobar,SecurityContext securityContext) throws NotFoundException;
}
```
and this is the generated resource:
```
@GET
@Produces({ "application/json", "*/*" })
@io.swagger.annotations.ApiOperation(value = "", notes = "", response = Item.class, responseContainer = "List", tags={  })
@io.swagger.annotations.ApiResponses(value = { 
@io.swagger.annotations.ApiResponse(code = 200, message = "The HTTP/200 response.", response = Item.class, responseContainer = "List"),
@io.swagger.annotations.ApiResponse(code = 200, message = "Error message.", response = String.class) })
public Response bugQueryGET(
	@ApiParam(value = "",required=true, defaultValue="null") @DefaultValue("null") @QueryParam("foobar") Integer foobar, 
	@Context SecurityContext securityContext) throws NotFoundException {
	return delegate.bugQueryGET(foobar,securityContext);
}
```

**Comment by selliera** [comment]
This issue is there for all jax-rs generators too:

In the generated java jax-rs api, there are some defaultValue="new ArrayList<>()".
They do cause problems, since for a query parameter specified as a String array, possibly empty, we have for instance:

    samples\server\petstore\jaxrs-jersey\src\gen\java\org\openapitools\api\FakeApi.java
    203:    public Response testEnumParameters(@ApiParam(value = "Header parameter enum test (string array)" , allowableValues=">, $", defaultValue="new ArrayList<String>()")@HeaderParam("enum_header_string_array") List<String> enumHeaderStringArray
If the caller do not specify a value, the default is used, and it is incorrect, since the specification did call for an empty list if the caller omit the parameter.

**Comment by calebmiller010** [comment]
Hi @selliera it's been awhile since I've checked on this, but it appears based on [this comment of yours](https://github.com/OpenAPITools/openapi-generator/pull/2883#issuecomment-498137294) that this is no longer an issue? Should I go ahead and close this out?

**Comment by selliera** [comment]
Hello,

Yes, you can close the issue, indeed, this is no longer a problem.

Thanks !

antoine
