### ISSUE TITLE
[BUG] [Python] Generator deletes `STATE_` prefix for default value of enums

### ISSUE THREAD

**Issue by MelvinKl** [OpenAPITools/openapi-generator#19751]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
If the default value of an enum has the prefix `STATE_` the generator will delete this prefix for the default value, which results in a wrong value. This only happens if the value has the prefix `STATE_`. If the prefix is different the generator will produce correct code.

Actual output of definition of `aggregated` in `openapi_client/models/status.py`:
`aggregated: Optional[StatusState] = StatusState.UNSPECIFIED`
expected output:
`aggregated: Optional[StatusState] = StatusState.STATE_UNSPECIFIED`

##### openapi-generator version
7.7.0, 7.8.0, latest

##### OpenAPI declaration file content or url
[Example yaml to reproduce the issue](https://gist.github.com/MelvinKl/61fc4f0ae935c0641e7848458780d773)

##### Steps to reproduce
Download the provided `example.yaml` and run the following command:
`docker run --rm -v $PWD:/local openapitools/openapi-generator-cli:latest generate -i /local/example.yaml -g python -o /local/out/python`

**Comment by wing328** [comment]
can you please try setting `removeEnumValuePrefix` (generator option) to false?

e.g.
```
 java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g python -i https://gist.githubusercontent.com/MelvinKl/61fc4f0ae935c0641e7848458780d773/raw/85afa13d2ea2e4d7268fd589700a3fe95ea53f55/example.yaml -o /tmp/pythonenum/ --additional-properties removeEnumValuePrefix=false
```

**Comment by MelvinKl** [comment]
Thanks for the response. That fixes the issue
