### ISSUE TITLE
[BUG][Elixir] Generated API modules do not conform to the suggested programming style

### ISSUE THREAD

**Issue by efcasado** [OpenAPITools/openapi-generator#19779]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The [guidelines for contributing to the project](https://github.com/OpenAPITools/openapi-generator/blob/cfe6520283b6b03c28a7b1704d9d56d1e6cb67ee/CONTRIBUTING.md#L56) suggest that generated Elixir code should conform to [Christopher Adams' style guide](https://github.com/christopheradams/elixir_style_guide), which states that acronyms such as `HTTP`, `XML`, ... and `API` should be [kept uppercase](https://github.com/christopheradams/elixir_style_guide?tab=readme-ov-file#camel-case). However, the current implementation does not honor this principle.

Using [this toy project](https://github.com/efcasado/opsgeniex/tree/e9bae4c5ce71af7f5199d7355e5283d8d8bc7b34) as an example, the generated API modules are named `Opsgeniex.Api.{Account, Alert, ...}` but I would have expected the output to be `Opsgeniex.API.{Account, Alert, ...}`.

##### openapi-generator version

`v7.8.0`

##### OpenAPI declaration file content or url

`N/A`

The issue is not specific to a particular OAS.

##### Generation Details

[Here](https://github.com/efcasado/opsgeniex/blob/e9bae4c5ce71af7f5199d7355e5283d8d8bc7b34/Makefile#L34-L40) is an example, but all code generated with `-g elixir` should manifest the same "issue".

##### Steps to reproduce

```
openapi-generator generate \
  -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
  -g elixir \
  -o /tmp/test/
```

##### Related issues/PRs

`N/A`

**Comment by goyalyash340** [comment]
I would like to work on this.

**Comment by mrmstn** [comment]
Hi @efcasado

Thank you for raising this point and for participating in the related discussion at [#19778](https://github.com/OpenAPITools/openapi-generator/pull/19778).

Based on the insights shared in that discussion, I believe it would be best not to adopt Christopher Adams' style guide for acronym casing. Doing so could lead to further debates on where to draw the line and introduce breaking changes to the project, which we should aim to avoid.

Thanks again for bringing up the topic, submitting a PR and contributing to the conversation.
