### ISSUE TITLE
legal issues of editing the generated stub code and opensource that generated code

### ISSUE THREAD

**Issue by ranjitkumar2k10** [OpenAPITools/openapi-generator#1977]
##### Description
We are working for an organization and as an orgnanization we are planning to opensource a project which is using openAPI2.0 and 3.0 specifications.

we are planning to generate the stub server and client code using openapi-generator
on top of generated code we may need edit the generated code like example model files, router file (or) main file (or) api_default files etc.. according to our business need/logic .

if we edit any of those files we need to change the file header to our organization property and will opensource those files also.

will there be any legal issue from OpenAPITools/openapi-generator (or) swagger code-gen?

 

##### openapi-generator version

any latest version

##### OpenAPI declaration file content or url

<
  -->

##### Command line used for generation

mainly go language, can be python also in future

**Comment by ranjitkumar2k10** [comment]
thanks for clarification.

is it ok to keep for modified mustach templates in our repo according to our requirement.

**Comment by wing328** [comment]
Yes, Apache v2 license doesn't mandate making the modified source code or template files public but we definitely recommend contributing back to the official repo as it will make upgrading to the latest version easier in the future.

Like any other questions on licensing, you are recommended to check with the legal department in your company.

**Comment by ranjitkumar2k10** [comment]
sure.. thanks for the clarifications, if there is any changes will definitely do the contributors back.
