### ISSUE TITLE
[BUG][Python] Incorrect command in python-aiohttp server README

### ISSUE THREAD

**Issue by kent-williams** [OpenAPITools/openapi-generator#1979]
##### Description

There is an incorrect command to launch tests in the python-aiohttp server README.

The following:
`
sudo pip install -r test-requirements.txt
`
Should be:
`
sudo pip3 install -r test-requirements.txt
`

This particular python-aiohttp generator and test dependencies requires Python 3.5.2+, as stated previously in the README.
##### openapi-generator version

Latest Master
##### OpenAPI declaration file content or url

`
openapi-generator/modules/openapi-generator/src/main/resources/python-aiohttp/README.mustache
`

**Comment by wing328** [comment]
@kent-williams thanks for reporting the issue. May I know if you've time to contribute a PR to update the readme accordingly?

**Comment by kent-williams** [comment]
@wing328 Yes, I'd be happy to.
