### ISSUE TITLE
Bug in pushing SNAPSHOT JAR

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#198]
##### Description

We found that when the core team opens a PR with a new branch. Travis will deploy the snapshot JAR if the job succeeds, which is not the correct behavior as only the job targeting master should deploy the SNAPSHOT JAR:
```
[INFO] openapi-generator-project .......................... SUCCESS [  4.929 s]
[INFO] openapi-generator (core library) ................... SUCCESS [ 52.295 s]
[INFO] openapi-generator (executable) ..................... SUCCESS [ 15.301 s]
[INFO] openapi-generator (maven-plugin) ................... SUCCESS [ 11.260 s]
[INFO] openapi-generator-gradle-plugin (gradle-plugin) .... SUCCESS [01:07 min]
[INFO] openapi-generator-online ........................... SUCCESS [ 16.057 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:49 min
[INFO] Finished at: 2018-06-01T08:56:39Z
[INFO] Final Memory: 67M/660M
[INFO] ------------------------------------------------------------------------
Finished mvn clean deploy for master
```

##### openapi-generator version

Latest master

##### Steps to reproduce

Create a branch and open a PR

##### Suggest a fix/enhancement

https://github.com/OpenAPITools/openapi-generator/blob/master/.travis.yml#L97 is a good starting point.

**Comment by jimschubert** [comment]
@wing328 this sould be fixed after my release management changes this weekend. I added:

```
[ "$TRAVIS_PULL_REQUEST" == "false" ]; then
```

**Comment by jmini** [comment]
Nice we will check this when we create the `3.1.0` branch
