### ISSUE TITLE
[BUG][typescript-fetch] nullable arrays with a default null throws an error.

### ISSUE THREAD

**Issue by yannickl88** [OpenAPITools/openapi-generator#19825]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

We have a schema which can either be null or a list of object. This is mainly to allow the parameter to be optionally passed and to detect if the property was set to do case distinction on. So passing `null` vs `[]` behaves differently. (Similarly, as passing and empty string vs `null`)

However, when encoding this in a spec and trying to generate an typescript-fetch client for this, it results in an error.

##### openapi-generator version

`7.9.0`

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.3'

info:
  title: Test
  version: 0.1.0

paths: {}

components:
  schemas:
    Test:
      type: array
      items:
        type: string
      default: null
      nullable: true

```

##### Generation Details

```
$ java -jar "/node_modules/@openapitools/openapi-generator-cli/versions/7.9.0.jar" generate --input-spec="/test_schema.yaml" --generator-name="typescript-fetch" --output="/tmp/" --additional-properties="withInterfaces=true"
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 3
Errors: 
     -attribute components.schemas.PaymentConfigurationResponse.default is not of type `array`
Warnings: 
     -attribute components.schemas.PaymentConfigurationResponse.default is not of type `array`

     at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
     at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
     at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
     at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
     at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
```

##### Steps to reproduce

Run the command with the given schema

##### Related issues/PRs

None

##### Suggest a fix

`null` defaults are allowed when nullable, regardless of the type (`array` in this case).

**Comment by wing328** [comment]
please report the issue to https://github.com/swagger-api/swagger-parser which performs the validation

for the time being, please skip the validation (e.g. --skip-validate-spec in CLI) as mentioned in the error message

**Comment by yannickl88** [comment]
alrighty, thanks for pointing me to the correct project. I will close this issue then.
