### ISSUE TITLE
[BUG] [typescript-fetch] oneOf models are generated without `...ToJSONTyped` functions but models referencing still try to import

### ISSUE THREAD

**Issue by joshasharpe** [OpenAPITools/openapi-generator#19858]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output? _below_
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
When an object includes a field that is a oneOf type, the generation of the oneOf does not include `...ToTypedJson` method but the parent object attempts to import it still.

##### openapi-generator version
7.9.0

##### OpenAPI declaration file content or url
Small yaml that can produce
https://gist.github.com/joshasharpe/33ae2391c163f3db78f56e57ccf6d8dd

##### Generation Details
typescript-fetch with docker main

##### Steps to reproduce
1. Create a small openapi yaml that includes one model as the parent object.
2. Create models that will be unioned for the field
3. Mark them as oneOf for that field
4. Use `typescript-fetch` generator to create typescript code.

##### Related issues/PRs
Simliar to:
- https://github.com/OpenAPITools/openapi-generator/issues/15736
- https://github.com/OpenAPITools/openapi-generator/pull/19524
- https://github.com/OpenAPITools/openapi-generator/issues/14763 (This is still open so I almost posted here but it does not directly mention this particular function missing)

##### Suggest a fix

Adding to [this file](https://github.com/hagis/openapi-generator/blob/c36df78cff1142615f478b06d1274ccf565586cd/modules/openapi-generator/src/main/resources/typescript-fetch/modelOneOf.mustache#L44),

https://github.com/hagis/openapi-generator/blob/c36df78cff1142615f478b06d1274ccf565586cd/modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache#L105

I am not sure if it is 1:1 or whether there are other functions missing. I did not see documentation explaining that this was intentional. If so, we would have to make the import conditional on whether the "child" model is oneOf.

**Comment by tobq** [comment]
@macjohnny got this same error with 7.10.0:

```json
{
  "$schema": "./node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "7.10.0"
  }
}
```
```sh
$ openapi-generator-cli version
7.10.0
```

```ts
export function myEntityToJSONTyped(value?: ProjectTrackLoopEvery | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}
```

> TS2304: Cannot find name instanceOfnumber
