### ISSUE TITLE
[BUG] [typescript-angular] bearer auth is handled like basic auth

### ISSUE THREAD

**Issue by MBcom** [OpenAPITools/openapi-generator#1985]
#### Bug Report Checklist

- [x ] Have you provided a full/minimal spec to reproduce the issue?
- [x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x] What's the version of OpenAPI Generator used?
- [x ] Have you search for related issues/PRs?
- [x ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

* generate a typescript angular package with configured bearer auth like  
```yaml
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
```
* and the result in the generated package is that it trys to use basic authentication with username and password
* the expected behaviour is too send the bearer token in the header of the api request  
-> look at my suggestions in the related pull request

##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

look above

##### Command line used for generation

-

##### Steps to reproduce

generate a typescript-angular package with the open aip generator cli

##### Related issues/PRs
#1446, #1577, #457, #1930

##### Suggest a fix
look at the linked pull request

**Comment by maxfriedmann** [comment]
@MBcom, is this issue solved for you? I use the same securityScheme as you, and as expected by looking at your PR's content, my auth header gets prefixed with "Bearer ", and not "JWT ". I assume, the "bearerFormat" is ignored?

**Comment by MBcom** [comment]
@maxfriedmann sry for late answer  
you are right bearerFormat is not asumed to be the header prefix. We use `Bearer <token>` for JWT. I'm not sure was the standard says, but i thought the JWT is only the token format and Bearer the scheme.

**Comment by maxfriedmann** [comment]
@MBcom, yes, you're absolutely right, shame on me. After reading the official spec (https://jwt.io/introduction) I totally agree with you. `bearerFormat` relates to the format of the `<token>` of course.
