### ISSUE TITLE
[BUG] CSharp generator does not correctly recognize nullabilities

### ISSUE THREAD

**Issue by gfx** [OpenAPITools/openapi-generator#19879]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
  - source of schema: https://github.com/gfx/openapi-tools-csharp-nullability-bug/blob/main/main.py
  - generated model: https://github.com/gfx/openapi-tools-csharp-nullability-bug/blob/main/client/src/Org.OpenAPITools/Model/HelloWorldResponse.cs
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
  - expected: `anyOf(string, null)` generates nullable fields
  - actual: it's not recognized as nullable
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I use `{"anyOf":[{"type":"string"},{"type":"null"}]` for a response field, but CSharp generator does not generate nullable fields (i.e. `public T field? { get; set; }`. Instead, it generates non-null fields (i.e. `public T field { get; set; }`.  It seems to be a bug in the `csharp` generator. 

Note: because I use FastAPI@Python to generate OpenAPI schema, my minimum reproducable project does so (but it's not related to the bug in this issue):

* https://github.com/gfx/openapi-tools-csharp-nullability-bug

##### openapi-generator version

7.9.0

##### OpenAPI declaration file content or URL

https://github.com/gfx/openapi-tools-csharp-nullability-bug/blob/main/openapi.json

##### Generation Details

As the Makefile of the repo does, I did `java -jar openapi-generator.jar generate -i http://localhost:8001/openapi.json -g csharp -o client` to generate source files.

##### Suggest a fix

Add `?` after nullable field names.

**Comment by wing328** [comment]
> {"anyOf":[{"type":"string"},{"type":"null"}]

string is nullable by default in C#: https://stackoverflow.com/a/32853595/677735

you can test with "integer" type and openapi geneator should add the `?` to the auto-generated code to make it nullable

**Comment by gfx** [comment]
Ah, I reviewed my (private) project, and saw a real type is `DateTime` (python's `datetime.datetime`) and FastAPI is a bit old (0.97.0).

The latest FastAPI 0.115.2 + OpenAPI generator 7.9.0 does work as expected. So the bug was in FastAPI. 

Closing. Sorry for bothering this project.
