### ISSUE TITLE
[BUG] [typescript-angular] local package installation fails because of link issue

### ISSUE THREAD

**Issue by MBcom** [OpenAPITools/openapi-generator#1988]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x ] What's the version of OpenAPI Generator used?
- [ x] Have you search for related issues/PRs?
- [x ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

* if you install the generated typescript angular package locally like described in the README.md then you ran in trouble on windows if the version of the api packages changes
* so installing the build tgz bundle instead induced npm to copy the generated files to the node_modules folder instead of symlinking them
  
the bug bevaviour is actually described in the README.md  
  
the linked pull request solves this issue

##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

-

##### Command line used for generation

-

##### Steps to reproduce

run  
```bash
npm install --save <Path to api package>
```
change something on the api package, do some git commits on an other machine like an unix based system, pull the changes and install the new api package again - the new changes are not adopted  
see https://github.com/angular/angular-cli/issues/8284

##### Related issues/PRs
-
look at the linked pr

##### Suggest a fix

look at the linked pr

**Comment by karismann** [comment]
this can be closed cause it has been fixed with 4.0.0 (linked PR)

**Comment by wing328** [comment]
@karismann thanks for going through issues and make sure their status is up-to-date.
