### ISSUE TITLE
[BUG] [Python-Flask] invalid code generated when spec contains parameter with ref to array

### ISSUE THREAD

**Issue by mskoh52** [OpenAPITools/openapi-generator#1990]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? 3.3.4
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generating a python-flask stub. The `default_controller.py` file contains invalid Python code if the route contains a query parameter with a ref to an array in its schema (see example). If the same schema is "expanded" inline in the parameter, then the generated code is fine.

The generated code is below. Notice how it is trying to assign the query param from the request body.

```python
import connexion
import six

from openapi_server import util


def failing(fail=None):  # noqa: E501
    """get

     # noqa: E501

    :param fail: 
    :type fail: dict | bytes

    :rtype: None
    """
    if connexion.request.is_json:
        fail = .from_dict(connexion.request.get_json())  # noqa: E501
    return 'do some magic!'


def working(works=None):  # noqa: E501
    """get

     # noqa: E501

    :param works: 
    :type works: List[str]

    :rtype: None
    """
    return 'do some magic!'

```

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: example
  description: minimal example for $ref to array in parameter schema bug
  version: 0.0.0

paths:
  /fail:
    get:
      summary: get
      operationId: failing
      parameters:
        - in: query
          name: fail
          schema:
            $ref: "#/components/schemas/Fail"
      responses:
        "200":
          description: "asdf"
          content:
            text/plain: {}

  /works:
    get:
      summary: get
      operationId: working
      parameters:
        - in: query
          name: works
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: "asdf"
          content:
            text/plain: {}

components:
  schemas:
    Fail:
      type: array
      items:
        type: string
```

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i minimal.yml -o minimal -g python-flask`

##### Steps to reproduce

1) Run the above command to generate a python-flask server using the above spec.
2) Look at `minimal/openapi_server/controllers/default_controller.py`. The code for `failing` contains invalid Python code.

**Comment by wing328** [comment]
@mskoh52 I would suggest try the latest master and use the option `generateAliasAsModel` to not generate the "Fail" as model.

**Comment by mskoh52** [comment]
Confirming that it things work properly in latest master. Thanks!
