### ISSUE TITLE
[BUG] [Python] $ref references to non-object types not working correctly

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#1991]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When looking at the swagger2.0 sample spec, the #/definitions/OuterEnum
defines a string with enum examples. When it is used in other models, the parameters that refer to OuterEnum with $ref incorrectly list themselves as model parameters and do not include the correct enum options.

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

```yaml
definitions:
  OuterEnum:
    type: string
    enum:
    - "placed"
    - "approved"
    - "delivered"
  Enum_Test:
    type: object
    required:
      - enum_string_required
    properties:
      enum_string:
        type: string
        enum:
          - UPPER
          - lower
          - ''
      enum_string_required:
        type: string
        enum:
          - UPPER
          - lower
          - ''
      enum_integer:
        type: integer
        format: int32
        enum:
          - 1
          - -1
      enum_number:
        type: number
        format: double
        enum:
          - 1.1
          - -1.2
      outerEnum:
        $ref: '#/definitions/OuterEnum'
```

##### Command line used for generation

java -DdebugModels -jar /Users/justin/programming/openapi/fork_mine/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -t modules/openapi-generator/src/main/resources/python -i modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -g python -o samples/client/petstore/python -DpackageName=petstore_api

##### Steps to reproduce

1. Run the above debugging for the models
2. Inspect the OuterEnum model result, its dataType='str'
3. Inspect the  Enum_Test OuterEnum parameter, isModel is true and none of the enum values have been connected in

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/issues/1627
- https://github.com/OpenAPITools/openapi-generator/issues/1990 
- https://github.com/OpenAPITools/openapi-generator/issues/1981
- https://github.com/OpenAPITools/openapi-generator/issues/1927

##### Suggest a fix

For models where datatype is not object, we should:
- Convert them to codegen parameters
- Put them where they belong
- Remove the source models from the final models list

**Comment by wing328** [comment]
> When it is used in other models, the parameters that refer to OuterEnum with $ref incorrectly list themselves as model parameters and do not include the correct enum options.

OuterEnum is an enum model, which is allowed in some languages (e.g. Java).

For Python, `OuterEnum`is generated as https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/models/outer_enum.py

Does currently implementation of outer_enum.py make sense to you?

cc @taxpon (2017/07) @frol (2017/07) @mbohlool (2017/07) @cbornet (2017/09) @kenjones-cisco (2017/11) @tomplus (2018/10) @Jyhess (2019/01)

**Comment by spacether** [comment]
It does not make sense to me for the following reasons.
Given the example:
```
swagger: "2.0"
info:
  title: "some title"
  description: "some description"
  version: "1.0.0"
host: "example.com"
basePath: "/api"
schemes:
- "https"
paths:
  /tracking:
    post:
      summary: "creates a RefModel"
      description: "creates a RefModel"
      operationId: "createRefModel"
      parameters:
        - in: body
          name: ref_model
          description: "RefModel Body"
          required: true
          schema:
            $ref: "#/definitions/RefModel"
      responses:
        200:
          description: "Valid input"

definitions:
  IntegerRef:
    type: integer
    nullable: true
    enum:
      - 0
      - -12
      - 41
  NumberRef:
    type: number
    nullable: true
    enum:
      - 3.1415
      - 1.618
      - -2.718
  BooleanRef:
    type: boolean
    nullable: true
  ArrayRef:
    type: array
    nullable: true
    items:
      type: integer
  StringRef:
    type: string
    nullable: true
    enum:
      - some
      - options
      - here
  RefModel:
    type: object
    required:
      - integer_ref
      - number_ref
      - boolean_ref
      - array_ref
      - string_ref
    properties:
      integer_ref:
        $ref: '#/definitions/IntegerRef'
      number_ref:
        $ref: '#/definitions/NumberRef'
      boolean_ref:
        $ref: '#/definitions/BooleanRef'
      array_ref:
        $ref: '#/definitions/ArrayRef'
      string_ref:
        $ref: '#/definitions/StringRef'
```
When instantiating RefModel we have the following issues:
- Parameters that use $ref references are all set as non-nullable even though we defined them as nullable (openapi 3.0 spec feature)
- Values assigned in parameters are not checked against the possible enum values in their models
- When instantiating non-object models, there is no way to store a value in the model in an __init__ argument, or to see the values in the to_dict() representation
- Serialization of RefModel may not work, types are undefined in in the parameters
- Deserialization of RefModel instances with typed values for integer_ref etc will not work

**Comment by dojeda** [comment]
I think I encountered this bug on an API that has the following structure:

```
paths:
  /data/workspaces/:
    get:
      summary: Get all workspaces
      tags:
        - data
      operationId: app.api.data.workspace.fetch
      parameters:
      - $ref: '#/components/parameters/pageOffset'
      - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          description: Paginated list of workspaces.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Workspace'
                  page:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/page'
                  pages:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/pages'
                  total:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/total'
        default:
          $ref: '#/components/responses/ErrorResponse'

components:
  parameters:
    pageOffset:
      name: page
      in: query
      description: The page of a collection to return.
      required: false
      schema:
        type: integer
        minimum: 1
        default: 1
    pageSize:
      name: per_page
      in: query
      description: Number of items to return per page.
      schema:
        type: integer
        minimum: 1
        maximum: 100000
        default: 100

  schemas:
    PaginationEnvelope:
      type: object
      title: Paginated response template type
      description: >
        An envelope for responses that need to be paginated. When a collection
        is accessed through a GET request, the results are sent in an object
        that informs on the pagination status (page, number of pages, number
        of results) and the data itself. This type is heavily inspired from
        linode's PaginationEnvelope.
      required:
        - pages
        - page
        - total
        - data
      properties:
        pages:
          type: integer
          description: Number of pages available in the collection
          readOnly: true
        page:
          type: integer
          description: Current page number
          readOnly: true
        total:
          type: integer
          description: Total number of items in the collection
          readOnly: true
        data:
          type: array
          description: Array of objects with the results of the current page
          readOnly: true
          items:
            type: object
    Workspace:
      title: Workspace details type
      description: Workspace details
      required:
        - name
      type: object
      properties:
        id:
          description: Workspace ID
          type: integer
          readOnly: true
        status:
          description: Workspace status
          enum:
            - INITIALIZING
            - READY
            - SCANNING
            - UPDATING
            - COMMITTING
            - DELETING
            - INVALID
            - CONFLICT
            - DELETED
          readOnly: true
        name:
          description: Name of the workspace
          type: string
```

I tried to trim as much as possible in order to keep only the elements related to this issue. I left the enum just to show that enums are handled correctly.

The problem here is the `$ref` to a property in a schema. This generates a model with the following map:
```
class InlineResponse200Results(object):
    openapi_types = {
        'data': 'list[WorkspaceDetailsType]',
        'page': 'Page',
        'pages': 'Pages',
        'total': 'Total'
    }
   ...
```
which then fails when deserializing the response because there is no `package.models.Page` class.

I have a workaround, which is to resolve all `$ref`s... I am using something like:
```
import json

import yaml
import jsonref


with open('input.yaml', 'r') as f:
    api = yaml.safe_load(f)

api_noref = jsonref.JsonRef.replace_refs(api)
with open('output.json', 'w') as f:
    json.dump(api_noref, f)
``` 

and then use this new json to generate the Python client code. Then, I find that the model map uses the correct types for page, pages, total:
```
    openapi_types = {
        'data': 'list[WorkspaceDetailsType]',
        'page': 'int',
        'pages': 'int',
        'total': 'int'
    }
```

**Comment by spacether** [comment]
@dojeda
When using $ref linkings, I have never seen them refer to the inner properties of a model.
So your inline definition here:
```
                  page:
                    $ref: '#/components/schemas/PaginationEnvelope/properties/page'
```
Your spec would be easier to understand if you defined the Page, Pages, and Total models at:
```
#/components/schemas/Page
#/components/schemas/Pages
#/components/schemas/Total
```
Each of those models would demonstrate from the same issue that I am describing above
where they are non-object models.
From your error it looks like the codegen inline model resolver makes the non-object models Page/Pages/Total but they don't do what you need them to do.

**Comment by dojeda** [comment]
Thanks for the response @spacether,

I had never seen `$ref` to the inner properties of a model before either, until I read linode's specification, which is what I used as inspiration for my paginated responses: https://developers.linode.com/api/v4/openapi.yaml 
I know I can refactor this out into a schema, but I liked the way linode solved this problem. I don't think this is more or less readable (subjective?) and I checked that there is actually no discouragement or violation to the OpenAPI specification. I'll probe this with my colleagues; if I find that they agree with you, I'll probably change it since it's not a major modification.

I agree that moving these elements to schemas as suggested would indeed present the same issue.

Concerning the error, the problem is that the wrapping class (the pagination envelope) creates a map to a non-existing type (Page/Pages/Total), but there is no model generated for these types. It is not that they don't do what I need them to do: there are no Page/Pages/Total models at all.

**Comment by spacether** [comment]
Making them base level models may make them generated. I know that an array model is generated but per this issue, even if it is generated it will not store data like you need it to. Can you file a separate ticket on the inline models not being generated?

**Comment by dojeda** [comment]
Just to be sure, when you say making them base level models, you mean changing to something like:
`$ref:  '#/components/schemas/Page'` ?

**Comment by spacether** [comment]
Yes, that's what I meant.

**Comment by dojeda** [comment]
OK I'll create an issue this week; I'm a bit under the water but I will have some time before friday.

**Comment by spacether** [comment]
Further work into this issue has revealed that models with type not equal to object are needed.
There are 3 possible model types
1. composed schema models (allOf/anyOf/oneOf)
2. object models (models with properties, similar to dict/map)
3. non-object models which contain validation and enums (str/int/float)

For type 3, We could have a string/float etc model to store and validate values.
The reason that we need these models in addition to object models is that operations (endpoints) only return primitives (str/float/int) or models. 

If we need a primitive to be validated against a list of possible enums we need to make that primitive into a model. If we need a primitive like a float to be validated agains a max and minimum value, we need that primitive to be converted into a model so the model can contain the max and min validations.

We can convert models with non-object type that have no validations and enums into simple parameters and use those primitives in any models/operations that reference them.

If we did not support type3 models, then we would be losing the enum and validation info when deserializing str/float/int response values.

**Comment by spacether** [comment]
This is now supported in the python-experimental generator
Non object models with validations and enums are generated in python inheriting from the class ModelSimple
