### ISSUE TITLE
[BUG][Swift6] OpenAPIInterceptor shoud retry 401 errors even if thre is no let response urlSession

### ISSUE THREAD

**Issue by biovolt** [OpenAPITools/openapi-generator#19939]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When you call a service with Bearer auth like JWT and the token was revoked or something made the token no longer valid, e.g., a user password change, the service can return a 401, and no Body / no error with the response. This scenario will not call the retry because "if let response, let error" will fail. The reason is that error is nil and skip over the interceptor.retry call.

```
                case let .success(modifiedRequest):
                    let dataTask = urlSession.dataTaskFromProtocol(with: modifiedRequest) { data, response, error in
                        self.cleanupRequest()
                        if let response, let error {
                            self.openAPIClient.interceptor.retry(urlRequest: modifiedRequest, urlSession: urlSession, requestBuilder: self, data: data, response: response, error: error) { retry in
                                switch retry {
                                case .retry:
                                    self.execute(completion: completion)

                                case .dontRetry:
                                    self.openAPIClient.apiResponseQueue.async {
                                        self.processRequestResponse(urlRequest: request, data: data, response: response, error: error, completion: completion)
                                    }
                                }
                            }
                        } else {
                            self.openAPIClient.apiResponseQueue.async {
                                self.processRequestResponse(urlRequest: request, data: data, response: response, error: error, completion: completion)
                            }
                        }
                    }
```

##### openapi-generator version

7.10.0-SNAPSHOT 
Commit SHA 266193f95fb5eb92179139782316251454d19517

##### OpenAPI declaration file content or url

I am not allowed to share this: Sorry
  -->

##### Generation Details

java -jar openapi-generator-cli.jar generate -i swagger.json -g swift6 -o . -p projectName=******OpenApiClient -p podVersion=$3 \
-p sortModelPropertiesByRequiredFlag=true \
-p hashableModels=false \
-p removeMigrationProjectNameClass=true \
-p enumUnknownDefaultCase=true \
-p podSource=************openapiclient.git \
-p podHomepage=*************openapiclient \
-p podDocumentationURL=*************openapiclient/-/blob/master/README.md \
-p podSwiftVersion=6.0

##### Steps to reproduce

Generate the openapi code and add it to a project authenticate with Bearer auth like JWT. Once the app has a valid JWT invalidate the token server side. so that the server returns a 401 with no error / no body and it won't call the interceptor.retry 

The raw response from the service is with no Body

```
HTTP/1.1 401 Unauthorized
Date: Tue, 22 Oct 2024 06:35:04 GMT
Transfer-Encoding: chunked
WWW-Authenticate: Basic
Request-Context: appId=cid-v1:5461468-2fa1-4e29-ad9b-4178841351987
Strict-Transport-Security: max-age=2592000
X-Platform: Core
Content-Security-Policy: object-src none
Content-Security-Policy: frame-ancestors 'self'
X-Frame-Options: SAMEORIGIN
```

##### Related issues/PRs

I could not find any

##### Suggest a fix

Inside URLSessionImplementations.swift  " if let response, let error {" remove the requirement for error to have a value. 
Error is not required it is the HTTP status code that determines what action should be taken. However, I am not sure why a 401 with no body does not return an error from urlSession.dataTaskFromProtocol

**Comment by 4brunu** [comment]
Hi @biovolt, I thought a 401 status code would have an error.
Can ou please check if this PR fixes your issue?
https://github.com/OpenAPITools/openapi-generator/pull/19988

**Comment by JohanP24** [comment]
Hi @4brunu 
Yes, it works thank you!
