### ISSUE TITLE
[BUG] Kotlin generator: generateOneOfAnyOfWrappers=true leads to broken code

### ISSUE THREAD

**Issue by andreas-umbricht** [OpenAPITools/openapi-generator#19942]
##### Description

While using the Kotlin generator in a Android Project with "generateOneOfAnyOfWrappers=true", the generator generates code with the Gson Library even tough it should be Moshi by default(?). After including the Gson Library to the project, it still failed. Partly because of invalid naming of variables. As you can see in the picture below, on line 37 and 38, the generates variables are interpreted by kotlin as extension functions. So this won't compile.

![Bildschirmfoto 2024-10-22 um 12 02 06](https://github.com/user-attachments/assets/55062733-63cc-492c-a89a-4e75562737ac)

To start from the beginning: We received a new OpenAPI Spec from our server team. The spec contains some "OneOf" relations. The file itself should be valid, since our iOS team was able to generate the desired code with `openapi-generator generate -i Common/MeteoMapsAPI/meteomapsapi.json -g swift5 -o Common/MeteoMapsAPI --model-name-prefix SRF --additional-properties=projectName=MeteoMapsAPI,generateAliasAsModel=true`. 
If we (Android team) run the generator without "generateOneOfAnyOfWrappers=true", an error get's thrown `@JsonClass can't be applied to ch.srf.meteo.data.meteomap.model.MeteoMapLayer: must be a Kotlin class`. This makes sense looking into the generated code:

![Bildschirmfoto 2024-10-22 um 11 59 23](https://github.com/user-attachments/assets/6fde3437-ea16-4d96-a246-a9af91fa8856)

So I guess, the approach of using "generateOneOfAnyOfWrappers=true" should be correct?

The full OpenAPI declaration file can be found below.

##### openapi-generator version

7.9.0, 7.8.0

##### OpenAPI declaration file content or url

[meteomap-api.json](https://github.com/user-attachments/files/17473660/meteomap-api.json)

##### Generation Details

```
    val generateMeteoMap by registering(GenerateTask::class) {
        generatorName.set("kotlin")
        .....
        configOptions.set(apiConfigOptions)
        additionalProperties.set(
            mapOf(
                "enumPropertyNaming" to "UPPERCASE",
                "useCoroutines" to "true",
                "moshiCodeGen" to "true",
                "generateOneOfAnyOfWrappers" to "true",
            )
        )
        library.set("jvm-retrofit2")
    }
```

##### Steps to reproduce

If you run the generator either with Gradle or via CLI with the attached OpenAPI declaration file (which should be valid in my opinion), the error occures.

**Comment by andybdahl** [comment]
I am experiencing this exact same issue as well.

We are using version 7.9.0 of the generator.

This is our configOptions configured on the generateApi task

```kotlin
openApiGenerate {
    generatorName.set("kotlin")
    validateSpec.set(true)
    inputSpec.set("$rootDir/api-specs/ntvb-api-spec.yaml")
    outputDir.set("$buildDir/generated")
    cleanupOutput.set(true)
    apiPackage.set("com.norlysplay.kmm.data.datasource.api")
    modelPackage.set("com.norlysplay.kmm.data.model.generated")
    modelNameSuffix.set("NetworkModel")
    typeMappings.set(mapOf(
        "string+uuid" to "kotlin.String",
        "string+uri" to "kotlin.String",
        "number" to "kotlin.Float"
    ))
    configOptions.set(mapOf(
        "dateLibrary" to "kotlinx-datetime",
        "library" to "multiplatform",
//        "serializationLibrary" to "kotlinx_serialization",
        "enumPropertyNaming" to "UPPERCASE",
        "generateOneOfAnyOfWrappers" to "true",
        "useOneOfInterfaces" to "true",
    ))
}
```

I am getting the same generated code that is using the Gson library even when we add the uncommented option to use kotlinx_serialization. We are using the generator in a KMP project as well, as Gson is not available to use there at all.

So it seems the codegen does not produce compilable code with the oneOf/anyOf options in an api spec.


Any help on how to solve these problems would be greatly appreciated 🤞

**Comment by andreas-umbricht** [comment]
I would like to reopen this issue. The variables' names are now compatible with kotlin. Thank you ver much for that!
The other error is still happening. Code gets generates with the Gson Library instead of the Moshi Library (which should be the default according to your documentation). I then tried adding the Gson dependency to the project, but then I noticed, that the generated classes do not import any Gson Classes itself and I must override the generated files to add the correct import statements.

<img width="1002" alt="Bildschirmfoto 2024-11-27 um 11 59 39" src="https://github.com/user-attachments/assets/061fe7df-e697-4521-9a67-4916ea314147">

In theory that would work, but still should be handled by the openapi-generator, since it's not suitable to do that everytime you build.

In addition to the above mentioned issue, the auto-generated code tries to call static methods of data classes, that do not exist.

<img width="986" alt="Bildschirmfoto 2024-11-27 um 16 03 08" src="https://github.com/user-attachments/assets/1cff960a-4545-47df-96ba-5b5af3153244">

In my scenario MeteoMapLayer is the superclass (oneOf/anyOf) with SubTypes MeteoMapImageLayer, MeteoMapTileLayer and MeteoMapGeoJsonLayer.
The `validateJsonElement(..)` function is only generated for MeteoMapLayer class and not it's subclasses. So this makes also sense that this does not work.

```
data class MeteoMapLayer(var actualInstance: Any? = null) {

    class CustomTypeAdapterFactory : TypeAdapterFactory {
        .....
    }

    companion object {
        /**
        * Validates the JSON Element and throws an exception if issues found
        *
        * @param jsonElement JSON Element
        * @throws IOException if the JSON Element is invalid with respect to MeteoMapLayer
        */
        @Throws(IOException::class)
        fun validateJsonElement(jsonElement: JsonElement?) {
            requireNotNull(jsonElement) {
                "Provided json element must not be null"
            }
            var match = 0
            val errorMessages = ArrayList<String>()
            // validate the json string with MeteoMapTileLayer
            try {
                // validate the JSON object to see if any exception is thrown
                MeteoMapTileLayer.validateJsonElement(jsonElement)
                match++
            } catch (e: Exception) {
                // Validation failed, continue
                errorMessages.add(String.format("Validation for MeteoMapTileLayer failed with `%s`.", e.message))
            }
            // validate the json string with MeteoMapImageLayer
            try {
                // validate the JSON object to see if any exception is thrown
                MeteoMapImageLayer.validateJsonElement(jsonElement)
                match++
            } catch (e: Exception) {
                // Validation failed, continue
                errorMessages.add(String.format("Validation for MeteoMapImageLayer failed with `%s`.", e.message))
            }
            // validate the json string with MeteoMapGeoJsonLayer
            try {
                // validate the JSON object to see if any exception is thrown
                MeteoMapGeoJsonLayer.validateJsonElement(jsonElement)
                match++
            } catch (e: Exception) {
                // Validation failed, continue
                errorMessages.add(String.format("Validation for MeteoMapGeoJsonLayer failed with `%s`.", e.message))
            }

            if (match != 1) {
                throw IOException(String.format("Failed validation for MeteoMapLayer: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()))
            }
        }
    }
}
```
```
data class MeteoMapTileLayer (

    @Json(name = "data")
    val `data`: kotlin.collections.List<MeteoMapRasterizableLayerDataItem>,

    @Json(name = "disableSmoothing")
    val disableSmoothing: kotlin.Boolean? = null,

    @Json(name = "opacity")
    val opacity: kotlin.Float? = 0.8f,

    @Json(name = "insertBelowId")
    val insertBelowId: kotlin.String? = null,

    @Json(name = "insertAboveId")
    val insertAboveId: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: TILES
     */
    @JsonClass(generateAdapter = false)
    enum class Type(val value: kotlin.String) {
        @Json(name = "tiles") TILES("tiles");
    }

}
```

I will be glad to provide you with our spec.json file if that helps you any further.
