### ISSUE TITLE
[BUG] `FILTER` customization stops generation of `impl` folder for the selected endpoints (only interfaces generated)

### ISSUE THREAD

**Issue by julienteisseire** [OpenAPITools/openapi-generator#19945]
#### Bug Report Checklist

- [ x] Have you provided a full/minimal spec to reproduce the issue?
- [x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ x] Have you searched for related issues/PRs?
- [x ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Hi, I am using the feature allowing to only select few endpoints to be processed by open api generator.
That's definitely the feature I was looking for when using a large open api spec file.

My problem is when I generate my cpp server, using FILTER option stops the generation of the `impl` files.
I only have interfaces generated, but not the POST functions for the selected endpoints.

##### openapi-generator version

I am using the version 7.9.0, and I guess it is not a regression.
Either I don't use FILTER option correctly or it is the expected behavior.
But even if I select few endpoints to be generated I still need my server implementation for these endpoints to be called.

##### OpenAPI declaration file content or url
```
openapi: 3.1.0
info:
  title: New test api
  description: |-
    Open API test
  contact:
    email: blabla@blibli.net
  version: 1.0.0
tags:
  - name: test
    description: test api
paths:
  /myfirstendpoint:
    post:
      tags:
        - test
      summary: test endpoint
      description: test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                requeststring:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  responsestring:
                    type: string
        '400':
          description: Invalid status value
  /mysecondendpoint:
    post:
      tags:
        - test
      summary: test endpoint
      description: test
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                requeststring:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  responsestring:
                    type: string
        '400':
          description: Invalid status value
```

##### Generation Details
```
docker run --user "$(id -u):$(id -g)" --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v7.9.0 generate \
    -i /local/models/test.yaml \
    -g cpp-pistache-server \
    -o /local/generated/ \
    --openapi-normalizer FILTER="operationId:myfirstendpoint"
```
##### Steps to reproduce

generate and check `impl` folder not present in generated files.
When removing `--openapi-normalizer FILTER="operationId:myfirstendpoint"` from command-line, I have all endpoints generated (ok) and I get back the `impl` folder generated (as I would expect when generating with only selected endpoints).

**Comment by wing328** [comment]
> FILTER="operationId:myfirstendpoint"

that's for the `operationId` (another field which is the same level as description, summary), not path (e.g. `/myfirstendpoint`)

**Comment by julienteisseire** [comment]
Thank you for your answer, but I don't understand.

- Do you mean it is simply **impossible** today to bu**ild a CPP server with implementation** (in my case) with only s**ome of the endpoints** described in my yaml file ?
- Or do you mean I have to use **path** instead of **operationId** ?

Thank you

**Comment by julienteisseire** [comment]
I did new test.
My case was in error when operationID: has been set with path of endpoint (even if openapi generator was managing only one endpoint at that time, which was confusing in my understanding of FILTER behavior).

Now I added operationId field to my endpoints and configured accordingly the generate command (`operationId: postMyFirstEndpoint`).

In that case, it works like a charm.

Example of API configuration :
```
openapi: 3.1.0
info:
  title: New test api
  description: |-
    Open API test
  contact:
    email: blabla@blibli.net
  version: 1.0.0
tags:
  - name: test
    description: test api
paths:
  /myfirstendpoint:
    post:
      tags:
        - test
      summary: test endpoint
      description: test
      operationId: postMyFirstEndpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                requeststring:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  responsestring:
                    type: string
        '400':
          description: Invalid status value
  /mysecondendpoint:
    post:
      tags:
        - test
      summary: test endpoint
      description: test
      operationId: postMySecondEndpoint
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                requeststring:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  responsestring:
                    type: string
        '400':
          description: Invalid status value

```

And generate command line :
```
docker run --user "$(id -u):$(id -g)" --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v7.9.0 generate \
    -i /local/models/test.yaml \
    -g cpp-pistache-server \
    -o /local/generated/ \
    --openapi-normalizer FILTER="operationId:postMyFirstEndpoint"
```

So I understand when operationId parameter is based on endpoint path, there is a particular behaviour where only interfaces with no implementation is generated for the specified endpoints.

But when configuring properly using operationId optional fields, it works perfectly.

Thank you again.
