### ISSUE TITLE
[BUG] Symfony4 StrictJsonDeserializationVisitor::visitString declaration incompatible

### ISSUE THREAD

**Issue by BenjaminHae** [OpenAPITools/openapi-generator#1996]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating the code for `php-symfony` it does not work as intended with symfony 4.2.2.
Running 
```
php bin/console server:start 0.0.0.0:8000
```
and visiting an registered endpoint leads to the following fatal error:
```
(1/1) FatalErrorException
Compile Error: Declaration of OpenAPI\Server\Service\StrictJsonDeserializationVisitor::visitString($data, array $type, JMS\Serializer\Context $context) must be compatible with JMS\Serializer\JsonDeserializationVisitor::visitString($data, array $type): string
--
in StrictJsonDeserializationVisitor.php line 23
```

##### openapi-generator version

`master, v4.0.0-beta, latest`

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local test/openapi-generator-cli generate -i /local/swagger.yaml     -g php-symfony -o /local/4Symfony
```

##### Steps to reproduce

Implement a symfony4 application by doing step 1 through 5 of the README. Then apply the fix for private controllers: https://github.com/OpenAPITools/openapi-generator/pull/1003
Start the server 
```
php bin/console server:start 0.0.0.0:8000
```
and visit an endpoint.

**Comment by BenjaminHae** [comment]
I've tried to fix it by myself: https://github.com/BenjaminHae/openapi-generator/tree/symfony4-fixes
But now I'm on a different type of error:
```
Argument 1 passed to JMS\Serializer\JsonDeserializationVisitor::__construct() must be of the type int, object given, called in Service/JmsSerializer.php on line 18
```

**Comment by ossinkine** [comment]
JsonDeserializationVisitor became final since 2.0.0-RC1 https://github.com/schmittjoh/serializer/commit/2340794e3a5bf75a5da7f199c5970ab4b48793c4.
So it seems we can't use inheritance anymore and should use composition.
