### ISSUE TITLE
[BUG] nullable enum property

### ISSUE THREAD

**Issue by rienafairefr** [OpenAPITools/openapi-generator#1997]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?   3.3.0
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

If encountered this using the python but I feel like this is the case in a lot of cases
I encountered an API that was publishing a 2.0 spec, but I'm getting resultst from the API that are out-of-spec and not possible to be parsed by a generate openapi-generator client, mostly sending null on non-nullable properties. But the issue is for enum values, I'm not sure how a client should validate:

a small spec that is apparently valid according to 3.0.2 
```
openapi: 3.0.1
paths:
  /test:
    summary: test
info:
  description: test
  version: 1.0.0
  title: test
components:
  schemas:
    Type:
      properties:
        prop:
          nullable: true
          enum: [A, B, C]
          type: string
```
if the enum is nullable, then getting a `null` as a result data from an API call should be valid and we should get a property typed like `Enum? in C#, or a `None` value in Python, and that should be valid. But the code in the case of an enum lists the allowable values excluding null, even if the enum property is specified nullable

##### Suggest a fix

- explicitely adding None in the `allowed_values` list in Python seems to at least make the client accept what the API sends, not sure if that's the full extent that a fix would take

**Comment by wing328** [comment]
> explicitely adding None in the allowed_values list in Python seems to at least make the client accept what the API sends, not sure if that's the full extent that a fix would take

@rienafairefr thanks for reporting the issue and suggesting the fix. What about doing that in the template with {{#isNullable}} ... {{/isNulalble}} instead of updating the allowed_values?

**Comment by Deitsch** [comment]
I'm having the same issue described by @rienafairefr.
```
"reason": {
    "type": "string",
        "enum": [
            "one",
            "two",
            null
        ],
    "nullable": true
}, 
```

is getting turned into 
```
export type ReasonEnum = 'one' | 'two' | 'null';
export const ReasonEnum = {
        Pending: 'one' as ReasonEnum,
        InProgress: 'two' as ReasonEnum,
        Null: 'null' as ReasonEnum
    };
```

Imo null should be converted to `null` not `'null`

**Comment by aaronabf** [comment]
I am also having issues even when following the examples as outlined in https://github.com/OpenAPITools/openapi-generator/pull/7754
