### ISSUE TITLE
[BUG][python-fastapi] fieldNames with reserved words are turned into private attributes in pydantic models

### ISSUE THREAD

**Issue by andlien** [OpenAPITools/openapi-generator#20030]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating pydantic models with the python-fastapi generator, reserved words are escaped by prepending an underscore. This results in pydantic treating the fields as a private attribute which is ignored in validation and (de)serialization. Furthermore, as of Pydantic v2.1.0, you receive a NameError if trying to use the Field function with a private attribute.

##### openapi-generator version

latest master

##### OpenAPI declaration file content or url

[Sample OpenApi spec](https://gist.github.com/andlien/0d2c01e873d9ba454ee2ab4744772a32)

Generating models for this spec results in the following model

```python
class TestDTO(BaseModel):
    _self: StrictStr = Field(alias="self")
    foo: StrictStr
    bar: StrictStr
    __properties: ClassVar[List[str]] = ["self", "foo", "bar"]
```

##### Generation Details

No special config

##### Steps to reproduce

openapi-generator generate -i sample.json -g python-fastapi -o /tmp/test/

##### Related issues/PRs

I have not found anything related

##### Suggest a fix

The escaping is currently performed in AbstractPythonCodegen.escapeReservedWord(). The `python` client generator also generates pydantic models, but it's overriding the method prepending "var_" istead. I assume copying this implementation in PythonFastAPIServerCodegen.java would fix the issue.

**Comment by wing328** [comment]
as a workaround, please use the name mapping option: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping
