### ISSUE TITLE
[BUG] Operations with multiple Tags triggers "unique" operation id generator which appends _0 to operation names.

### ISSUE THREAD

**Issue by AlexanderSchuetz97** [OpenAPITools/openapi-generator#20066]
I use the Java Native client generator.

I have a operation with 2 tags.
This did work as expected with the method being generated in both "client" files for openapi generator version 7.8.0

When using openapi generator 7.9.0 with the exact same schema file this adds _0 to the code which causes it to no longer compile.
The operation id is actually unique in the file.

My analysis of the Bug:

The Bug appears to occur in:
org.openapitools.codegen.DefaultCodegen#addOperationToGroup

There is a 
in line 5713 there is this: seenOperationIds.put(co.operationId, counter);

which gets called from DefaultGenerator#processOperations line 1586.
This line is in a for loop over all tags.

This can be fixed if the seenOperationsIds prepend the "tag" to the seen operation ids.

**Comment by devhl-labs** [comment]
Fixed by https://github.com/OpenAPITools/openapi-generator/pull/19913

**Comment by wing328** [comment]
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/7.10.0-SNAPSHOT/

please give it a try with the latest snapshot version

happy to reopen if it's still an issue

**Comment by AlexanderSchuetz97** [comment]
Snapshot did work. Could you cut a release soon?
