### ISSUE TITLE
[REQ] Do not use RestSharp for C# clients

### ISSUE THREAD

**Issue by the-avant-it** [OpenAPITools/openapi-generator#20074]
### Is your feature request related to a problem? Please describe.
Currently when creating csharp client RestSharp is added to dependencies. Since RestSharp has a lot of breaking changes from version to version, if generated client is added to project that already has a reference to different RestSharp version, you have to update that dependency, which might be hard.

## Describe the solution you'd like
Use built in HttpClient instead

**Comment by wing328** [comment]
did you try the library option (e.g. --library httpclient) ?

https://openapi-generator.tech/docs/generators/csharp/

**Comment by the-avant-it** [comment]
Thanks a lot! Will try it
