### ISSUE TITLE
[BUG][php-nextgen] ObjectSerializer methods fail with enums as parameters

### ISSUE THREAD

**Issue by DisasterCoding** [OpenAPITools/openapi-generator#20086]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When using `ObjectSerializer` methods, an exception occurs because parameters passed are enums instead of strings. This error arises in several methods, which require checking if parameters are enums and using their values directly.

##### openapi-generator version

7.9.0

##### OpenAPI declaration file content or URL

The issue can be observed in the `api.mustache` file at:
`OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-nextgen/api.mustache`

Lines 714, 731, and other relevant sections have been modified to check if parameters are enums and to use their values, like this:

```mustache
$queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
    ${{paramName}} instanceof \BackedEnum ? ${{paramName}}->value : ${{paramName}},
    '{{baseName}}', // param base name
    '{{#schema}}{{openApiType}}{{/schema}}', // openApiType
    '{{style}}', // style
    {{#isExplode}}true{{/isExplode}}{{^isExplode}}false{{/isExplode}}, // explode
    {{required}} // required
) ?? []);
```

##### Generation Details

- my config.json
```json
   {
   "invokerPackage": "Project",
   "disallowAdditionalPropertiesIfNotPresent": false,
   "legacyDiscriminatorBehavior": false,
   "prependFormOrBodyParameters": true,
   "variableNamingConvention": "camelCase",
   "phpLegacySupport": false,
   "booleanGetterPrefix": "is"
   }
```

- then I made changes to the api.mustache template
- cli
```bash 
 openapi-generator generate -i project.yaml -g php-nextgen -o project -c config.json -t templates
 ```

##### Steps to reproduce

1. Use the above command with the OpenAPI spec and the modified template.
2. Attempt to generate code and note the instances where enums cause exceptions due to improper handling by `ObjectSerializer` methods.

##### Related issues/PRs

- No related issues/PRs found.

##### Suggest a fix

Update relevant `ObjectSerializer` method calls to check if `paramName` is an enum, and if so, use `paramName->value`. 

For instance:

```mustache
$headerParams['{{baseName}}'] = ObjectSerializer::toHeaderValue(
    ${{paramName}} instanceof \BackedEnum ? ${{paramName}}->value : ${{paramName}}
);
```

**Comment by JulianVennen** [comment]
This is fixed by #20294
