### ISSUE TITLE
Question - Is it possible to remove the Api suffix

### ISSUE THREAD

**Issue by carlosmmatos** [OpenAPITools/openapi-generator#20113]
I could just be doing something wrong, but I don't see how you can tell the generator (Ruby in my case) to NOT add the `Api` suffix. I know there is this:
```
        --api-name-suffix <api name suffix>
            Suffix that will be appended to all API names ('tags'). Default:
            Api. e.g. Pet => PetApi. Note: Only ruby, python, jaxrs generators
            support this feature at the moment.
```

But I can't pass an empty string in there to remove it. Any guidance is much appreciated!

**Comment by wing328** [comment]
likely that will result in name collision, .e.g renaming PetApi to just Pet will result in compilation errors with the model `Pet`.

**Comment by carlosmmatos** [comment]
Okay - I will continue doing this post-processing then, thanks.
