### ISSUE TITLE
[BUG] Version 7.10.0 Release Notes miss Kotlin Explicit API support

### ISSUE THREAD

**Issue by xsveda** [OpenAPITools/openapi-generator#20136]
Version 7.10.0 Release Notes

https://github.com/OpenAPITools/openapi-generator/releases/tag/v7.10.0

does not mention #19999 feature. The feature is actually included and working, I've just tested it on out project.

**Comment by wing328** [comment]
the release note only highlights some of the changes (not all)

if you feel it's essential to include this one, i can update the release note

**Comment by xsveda** [comment]
I would be thankful for that. 

I know few teams are waiting for this feature. 

Much appreciated.


______________________________________________________________
> Od: "William Cheng" ***@***.***>
> Komu: "OpenAPITools/openapi-generator" ***@***.***>
> Datum: 20.11.2024 04:26
> Předmět: Re: [OpenAPITools/openapi-generator] [BUG] Version 7.10.0 Release Notes miss Kotlin Explicit API support (Issue #20136)
>

the release note only highlights some of the changes (not all)
if you feel it's essential to include this one, i can update the release note

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/OpenAPITools/openapi-generator/issues/20136#issuecomment-2487270458",
"url": "https://github.com/OpenAPITools/openapi-generator/issues/20136#issuecomment-2487270458",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wing328** [comment]
updated.

thanks for the feedback and the PR
