### ISSUE TITLE
How to add a new option to a generator

### ISSUE THREAD

**Issue by Urganot** [OpenAPITools/openapi-generator#20183]
##### Description

I want to add a new option to the aspnetcore generator.  For this I added the option to the AspNetServerCodegen.java file and added it to the template.

As far as I can tell, the codegen does read the argument correctly but it is always false when the template is being processed.

Here is the link to a first commit: https://github.com/Urganot/openapi-generator/commit/953d869d7e3239d186d6ba1232c1ddeb0d962b49

Am I missing something?

**Comment by Urganot** [comment]
Please ignore the .net9 stuff for now. Ill remove it from this branch and add it as its own PR later

**Comment by DielN** [comment]
from a quick look - you are using different names: In the generator you call it `useCentralizedPackageVersionManagement`, in the template you are using `useCentralPackageVersionManagement`.

**Comment by Urganot** [comment]
Oh ffs 🤦‍♂️ thank you so much :)
