### ISSUE TITLE
[BUG] [C++][Pistache-server] Object defined inside the body content does not compile

### ISSUE THREAD

**Issue by CyrilleBenard** [OpenAPITools/openapi-generator#2024]
##### Description
When the YAML file describes the use of an object inside the body content (without any content type like application/json), the generator produces a model file called InlineObject.h (and cpp) but to use it, the generator set the wrong include file name :

```
#include "Inline_object.h"
```
instead of

```
#include "InlineObject.h"
```

It seems that there is a confusion between the file name and the class name

```
class  Inline_object
    : public ModelBase
{
    ...
} ;
```

##### openapi-generator version

Current master 4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Check generation of pistache
  description: Internal ref filename is check_object_immediately_in_the_content.yaml

servers:
  - url: http://localhost:8080

paths:
  /sm-contexts:
    post:
      summary:  Create SM Context
      tags:
        - SM contexts collection
      operationId: PostSmContexts
      requestBody:
        description: representation of the SM context to be created in the SMF
        required: true
        content:
          multipart/related:
            schema:
              type: object
              properties: # Request parts
                dataMessage:
                  type: string

      responses:
        '200':
          description: Everythings gonna be alright
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Content"
        default:
          description: unexpected error


components:
  schemas:
    Content:
      type: string

```

##### Command line used for generation

Generate :
```
openapi-generator-cli.sh generate -i ./openapi.yaml -g cpp-pistache-server -c ./config.json -o .
```

Compile :
```
g++ -c  -I./api -I./model -I./impl  -Wall -g -std=c++11 -o obj/api/SMContextsCollectionApi.o api/SMContextsCollectionApi.cpp
```

##### Steps to reproduce

Generate & compile

##### Related issues/PRs

N/A

**Comment by CyrilleBenard** [comment]
Agree that it is fixed with #2781 even if I expected a renamed model file name (?)

Up to now, all models files names were named in CamelCase without 'underscore' character except the Inline_object ? 
In other words, I expected a file name like InlineObject.xxx (and also a class named InlineObject) instead of  Inline_object.xxx and class Inline_object.

Anyway, may be it's not so easy to modify the java code in this way
Thanks for the fix

**Comment by etherealjoy** [comment]
Issue is that we are trying to unify the naming across all `C++` generators so that fixing bugs is easier.

**Comment by etherealjoy** [comment]
If we camelize it we might get a case where the model name is `my_model`, and we turn it into `MyModel` and then user might not be happy.
