### ISSUE TITLE
[REQ] String binary generate MultipartFile

### ISSUE THREAD

**Issue by caroffan** [OpenAPITools/openapi-generator#20281]
Why a string binary which represent a file generate a `Resource` type in kotlin, in java this generate a `MultipartFile`.
MultipartFile is simpler to use and deserialize.

**Comment by jpfinne** [comment]
@caroffan I think you can achieve this with a type-mappings

See https://openapi-generator.tech/docs/customization

in maven:
```
<typeMappings>
       <typeMapping>File=org.springframework.web.multipart.MultipartFile</typeMapping>
</typeMappings>
```   
I'not tested with the kotlin generator but it works with the java generator
