### ISSUE TITLE
[BUG] [swift] URLSession library does not percent encode HTTP body for application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by Jonas1893** [OpenAPITools/openapi-generator#20357]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178)) -> silver sponsor

##### Description

HTTP body for application/x-www-form-urlencoded requests does not get percent encoded using URLSession template. We detected this when migrating from Alamofire to URLSession template, in Alamofire this worked as described below

##### openapi-generator version

7.10.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Minimal spec
  description: |-
    Minimal spec for bug ticket
  version: 1.0.0
servers:
  - url: https://oauth2.basepath.com
paths:
  /any/oauth2.path:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded; charset=utf-8:
            schema:
              oneOf:
                - $ref: '#/components/schemas/LoginRequestModel'
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    LoginRequestModel:
      type: object
      properties:
        client_id:
          type: string
        grant_type:
          type: string
          enum: ["refresh_token", "password", "urn:ietf:params:oauth:grant-type:device_code", "authorization_code"]
        password:
          type: string
        scope:
          type: string
        username:
          type: string
      required:
        [client_id, grant_type, password, scope, username]
```

##### Generation Details

config:
```yaml
generatorName: swift6
library: urlsession
generateModelAdditionalProperties: false
additionalProperties:
  responseAs: AsyncAwait
  readonlyProperties: true
  nonPublicApi: false
  modelNamePrefix: API
  removeMigrationProjectNameClass: true
```

Since the code is the same I guess the same issue should happen with swift5

##### Steps to reproduce

Use the minimal spec with the provided config. The HTTP body of the request sent will be similar to:
`client_id=7cfaf41e-aa18-40fd-a871-a21140d8e403&grant_type=password&password=foobarbaz&scope=openid email phone profile offline_access some-uid&username=+511287237674`

Note that the spaces between the scopes and the `+` sign in the username are not percent encoded.

Expected output should be similar to:
`client_id=7cfaf41e-aa18-40fd-a871-a21140d8e403&grant_type=password&password=foobarbaz&scope=phone%20some-uid%20openid%20profile%20email%20offline_access&username=%2B511287237674`

##### Suggest a fix

The problem is that in `private class FormURLEncoding`  -> `func encode` adds the non-escaped query to the httpBody:
`urlRequest.httpBody = requestBodyComponents.query?.data(using: .utf8)`
This means that any percent encoding needs to be done manually for the parameters. Changing this to 
`urlRequest.httpBody = requestBodyComponents.percentEncodedQuery?.data(using: .utf8)` does not solve the issue entirely since the `+` sign will not be percent encoded.

I suggest to fix this by manually percent encoding each query item using `.addingPercentEncoding(withAllowedCharacters: .alphanumerics)` before adding them to `requestBodyComponents.queryItems`

If this is accepted as a bug I could contribute a fix for it.

**Comment by 4brunu** [comment]
Hi, could you please open a PR with the fix? Thanks
