### ISSUE TITLE
[Java][okhttp-gson] Bug building generated client with localVariablePrefix set

### ISSUE THREAD

**Issue by lwoerdeman** [OpenAPITools/openapi-generator#2043]
##### Description
The open api generator for the default client (ok http) fails to compile after generating client with

##### openapi-generator version
3.3.4

##### OpenAPI declaration file content or url
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/api.mustache

##### Command line used for generation
java -jar openapi-generator-cli-3.3.4.jar generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g java -D localVariablePrefix=local -o test

##### Steps to reproduce
The command shown above will reproduce this issue and it can be found in any of the apis PetApi, StoreApi, etc.

##### Suggest a fix/enhancement
apiClient in the progessListener block (currently line 117) of okhttp-gson/api.mustache needs prefixed with {{localVariablePrefix}}

callback in the callback block (currently lines 245 & 249) of okhttp-gson/api.mustache needs prefixed with {{localVariablePrefix}}

**Comment by wing328** [comment]
@lwoerdeman thanks for reporting the issue. i think what I'll do it to completely remove the option and prefix all local varaible wiith `localVar` similar to what we've done in other languages.

**Comment by wing328** [comment]
@lwoerdeman I've filed https://github.com/OpenAPITools/openapi-generator/pull/2045. Please have a look when you've time.

**Comment by wing328** [comment]
@lwoerdeman we want to reduce the number of options as we got feedback from users the generators contain too many options.

The original goal of the option is to avoid parameter naming conflicts and we can still do that without the option (just like what we've done in other generators)

If you feel strongly to keep that option, can you elaborate on the reasons/your use cases?
