### ISSUE TITLE
[BUG] [Bash] Exception when generating bash for slack web api spec

### ISSUE THREAD

**Issue by Hellspam** [OpenAPITools/openapi-generator#2051]
##### Description

When using the latest openapi-generator with the spec for slack - https://api.slack.com/specs/openapi/v2/slack_web.json - I get an exception:
```
Exception in thread "main" java.lang.RuntimeException: Could not process model 'team_prefs_prefs'.Please make sure that your schema is correct!
    at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:457)
    at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:888)
    at org.openapitools.codegen.cmd.Generate.run(Generate.java:355)
    at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:62)
```

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

https://api.slack.com/specs/openapi/v2/slack_web.json

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -g bash -i https://api.slack.com/specs/openapi/v2/slack_web.json --additional-properties scriptName=slack-web-api,generateBashCompletion=true,generateZshCompletion=true,hostEnvironmentVariable=SLACK_HOST --skip-validate-spec`

##### Steps to reproduce

Try generating bash client for the slack web api.
I also tried generating groovy - groovy seemed to work, but there were some invalid fields as well there.

**Comment by wing328** [comment]
@Hellspam I've filed #2247 to fix the NPE.

Some parts of the spec do not seem to be valid, e.g.:
```
                "enterprise_mandatory_channels": {
                    "type": "array"
                },
```
which does not contain the `item` (e.g. array of string, array of model, etc)

**Comment by wing328** [comment]
@Hellspam PR merged into master. Please give it another try.

**Comment by Hellspam** [comment]
Thanks, I will check it out.
