### ISSUE TITLE
[BUG] Spring Boot fails to parse LocalDate query parameter

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#2053]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When defining a query parameter of  `type: string` and `format: date`

```yaml

  /bla:
    get:
      parameters:
        - $ref: '#/parameters/analysisDate'
      produces:
        - application/json
      responses:
          200:
            description: 'Successful operation'

parameters:
  analysisDate:
    name: analysisDate
    in: query
    required: true
    type: string
    format: date
```
the server fails to parse a url like `/bla?analysisDate=2017-11-30`

The generated code looks like
```java
 blaGet(@NotNull @ApiParam(value = "Analysis Date", required = true) @Valid @RequestParam(value = "analysisDate", required = true) LocalDate analysisDate) 
```

##### openapi-generator version

3.3.4

##### Related issues/PRs

https://blog.codecentric.de/en/2017/08/parsing-of-localdate-query-parameters-in-spring-boot/
https://github.com/spring-projects/spring-boot/pull/9930

##### Suggest a fix

adding `@DateTimeFormat(iso = DateTimeFormat.ISO.DATE)` resolves the issue:
```java
blaGet(@NotNull @ApiParam(value = "Analysis Date", required = true) @Valid @RequestParam(value = "analysisDate", required = true) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate analysisDate)
```

**Comment by macjohnny** [comment]
relevant code:

https://github.com/OpenAPITools/openapi-generator/blob/63e1e0451c61d7eb5f191c54d5e68f5fb02f5994/modules/openapi-generator/src/main/resources/JavaSpring/queryParams.mustache#L1

**Comment by macjohnny** [comment]
See also https://github.com/OpenAPITools/openapi-generator/issues/2053

**Comment by melissapalmer** [comment]
> See also #2053

@macjohnny  which issue did you mean to link this too #2053 is this issue? 

I am having the same issue that Spring server generated code is not parsing LocalDate correctly, reason I found is because the code being generated for these request parameters is as: 
```
@ApiParam(value = "Filter on KYC applications since a date")  LocalDate filterDateFrom
```
where as it should (include @RequestParam)
```
 @RequestParam(value = "filterDateFrom", required = false) @ApiParam(value = "Filter on KYC applications since a date")  LocalDate filterDateFrom
```

And this seems to be caused by the change you pointed out at: 
https://github.com/OpenAPITools/openapi-generator/issues/2053#issuecomment-495561796

What did you mean with these last comments you added please.

**Comment by macjohnny** [comment]
I updated my comment to link the correct issue

**Comment by peyerroger** [comment]
Hi guys

Even with the RequestParam annotation spring is not able to parse date/datetime into localdate/localdatetime. 

The suggested fix of @macjohnny to add @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) is the correct way from my point of view. At the moment we add this on the implementation. But it would be nice to have it in the generated code. I will create a PR if you agree.

@macjohnny The line needs an import statement. Is it ok to add the full class name in the queryParam.mustache file?

If 'isDate' (found in CodegenParameter.java)
```
@org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE)
```

If 'isDateTime' (found in CodegenParameter.java)
```
@org.springframework.format.annotation.DateTimeFormat(iso = org.springframework.format.annotation.DateTimeFormat.ISO.DATE_TIME)
```

**Comment by peyerroger** [comment]
@macjohnny Had some time and created the PR right away. #3860 Could you take a look? Do you know who can add the technical committee? Could you do that? 

Please note this only works correctly when issue #3248 is resolved as well.

**Comment by melissapalmer** [comment]
@diyfr are you possibly the correct person to include as the technical person for Java Spring server related work?

**Comment by melissapalmer** [comment]
@peyerroger looks like there are a few people on the tech committee see here: 
https://github.com/OpenAPITools/openapi-generator#62---openapi-generator-technical-committee

**Comment by baurchanu** [comment]
4Googlers:
You can disable this OOTB validation by using custom formats for date / time.
yaml
```
- name: dateFrom
  in: query
  schema:
    type: string
    format: my-custom-date-format
```
pom.xml
```
<plugin>
  ...
  <executions>
    <execution>
      ...
      <configuration>
        ...
        <typeMappings>my-custom-date-format=java.time.LocalDate</typeMappings>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by zalito12** [comment]
Hi! Note this is not working when you have your query parameters definied inside an object, for example:

```
paths:
  /elephants:
    get:
      operationId: getElephants
      parameters:
        - in: query
          name: count
          schema:
            type: integer
	- $ref: '#/components/parameters/SearchParams'
components:
  parameters:
    SearchParams:
      name: searchParams
      description: Possible search params to filter case search
      in: query
      style: form
      explode: true
      schema:
        type: object
        properties:
          prop1:
            type: integer
            example: 1
          start:
            type: string
            format: date
            example: '2019-12-31'
          end:
            type: string
            format: date
            example: '2019-12-31'
```

If I'm correct the `@DateTimeFormat` annotation also works in class fields. Has anyone face this problem too?

**Comment by prateek2007** [comment]
in case of "dateLibrary": "java8", DateFormatter is =DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)
which accepts date of format 12/6/19

**Comment by qbixsd** [comment]
> in case of "dateLibrary": "java8", DateFormatter is =DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)
> which accepts date of format 12/6/19

according to documentation, string with date format should be formatted with ISO format (yyyy-MM-dd): https://swagger.io/docs/specification/data-models/data-types/
So this default approach is in contradiction to openapi specification.

Also, is there a way to override this setting?

**Comment by fditolla** [comment]
In my case in the implemntation method I added @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) to the field and it seems to work.
