### ISSUE TITLE
[BUG] [Java][RESTEASY] Multipart requests in generated client doesn't work

### ISSUE THREAD

**Issue by mrzeszotarski** [OpenAPITools/openapi-generator#2054]
##### Description

Generated Resteasy Java client throws Exception `javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type multipart/form-data type: java.util.LinkedHashMap` when sending multipart request.

##### openapi-generator version
4.0.0-SNAPSHOT
##### OpenAPI declaration file content or url
https://petstore.swagger.io/v2/swagger.json

##### Command line used for generation
```
java -jar openapi-generator-cli.jar generate -i modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g java --library resteasy -o generated/resteasy
```
##### Steps to reproduce

We can reproduce error by running little modified test from generated class `PetApiTest`.

```
@Test
public void uploadFileTest() throws ApiException, IOException {
        Long petId = 1L;
        String additionalMetadata = null;
        File file = new File("test.txt");
        if(!file.exists()){
            file.createNewFile();
        }
        file.deleteOnExit();

        ModelApiResponse response = api.uploadFile(petId, additionalMetadata, file);
        
        Assert.assertEquals((long)response.getCode(), 200L);
}
```

##### Suggest a fix
To fix this problem I suggest modification of `serialize` method in `ApiClient.mustache` template file for resteasy.

**Comment by beneeng** [comment]
Hey, any chance @mrzeszotarski 's solution will make it into the main repo?

**Comment by anastouda12** [comment]
I have the same problem with version 4.3.0. Has anyone found a solution?

**Comment by jokl12** [comment]
Still around in 6.5.0.

**Comment by wing328** [comment]
@peter-seitz I wonder if you can file a PR with the suggested fix.
