### ISSUE TITLE
[PHP] "-l slim" in CLI suggested in wiki flagged as deprecated. Update docs to "-l php-slim"

### ISSUE THREAD

**Issue by decet** [OpenAPITools/openapi-generator#2055]
##### Description

Referencing wiki at wiki/Server-stub-generator-HOWTO, -l slim is suggested for generating server stubs. That'll get you a warning that it's deprecated, and to use -l php-slim, like so:

[main] WARN  o.o.c.config.CodegenConfigurator - The name 'slim' is a deprecated. Please update to the new name of 'php-slim'.

Update the wiki to reflect non-deprecated flag.

##### openapi-generator version

Current wiki at github.com/OpenAPITools/openapi-generator/wiki

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/wiki/Server-stub-generator-HOWTO

##### Command line used for generation

command line referenced in wiki:
https://github.com/OpenAPITools/openapi-generator/wiki/Server-stub-generator-HOWTO#php-slim

##### Steps to reproduce

https://github.com/OpenAPITools/openapi-generator/wiki/Server-stub-generator-HOWTO#php-slim

##### Suggest a fix/enhancement

Update the wiki at
https://github.com/OpenAPITools/openapi-generator/wiki/Server-stub-generator-HOWTO#php-slim
to show "-l php-slim"

**Comment by wing328** [comment]
@decet thanks for reporting the issue. Please feel free to update the wiki page directly as the wiki documentation is meant to be maintained by the community.

**Comment by decet** [comment]
I believe I have to be a "repository collaborator" to edit that wiki, and I am not.
Perhaps move the wiki material into the code repository, and change it with pull requests?
That would reduce the level of trust required for a change, and increase the scutiny.

**Comment by wing328** [comment]
You're right. The wiki page is now "admin" only so I've updated it myself.

I'll look into the setting later (again) to see if we can allow the users to edit the wiki directly.
