### ISSUE TITLE
[Python] Skip utf8 decoding for specific Content-Types in py3

### ISSUE THREAD

**Issue by g-bon** [OpenAPITools/openapi-generator#206]
In rest.py if PY3 is used and _preload_content is True, the response content is always decoded as utf8. This doesn't make sense for non-text files, e.g. an api that returns a file.
 
```
if six.PY3:
    r.data = r.data.decode('utf8')
```

https://github.com/OpenAPITools/openapi-generator/blob/b5942624d6714f38c0bde9ae9c7400df1d48b1ed/modules/openapi-generator/src/main/resources/python/rest.mustache#L213

I welcome any suggestion on how to tackle this but the two solution that come to mind are:
- Check on the content_type and make a whitelist/blacklist of content types that should be decoded to utf8.

A simple example would be something like 

```
if six.PY3 and headers.get('Content-Type') not in ['application/octet-stream']:
    r.data = r.data.decode('utf8')
```

Where obviously the list of Content-Types to "skip" would be a meaningful one and not only octet-stream.

- Another, harder approach would be to infer the content type from the actual data but feels fragile and overkill to me. Positive side would be that it would likely do the right thing even if the wrong or no content-type is specified in the response headers.

Happy to work on this when I have some confirmation the problem is here / feedback on the right approach.

**Comment by gierschv** [comment]
Same issue here (FlatIO/api-client-python#1), I believe a whitelist of mime-types could be helpful here.

**Comment by gierschv** [comment]
No, I didn't have time to work on this, I found this issue by looking into another bug.

Another idea for the whitelist: we could have `application/octet-stream` whitelisted by default and add a vendor param in the spec to add additional mime types (e.g. `x-disable-decoding-content-types: [...]`). In my use case, I have at least MIDI/MP3/WAV content types that can be returned by some endpoints.

**Comment by rienafairefr** [comment]
I've pushed a PR that I think addresses this issue, #2134

**Comment by spacether** [comment]
Another solution would be to pass the spec required response_type through and if it is of type file, skip the decoding. 

My preference is for a whitelist or blacklist of Content-Types though.

Just a heads up, we should also handle the Content-Disposition header as that indicates a file to be downloaded. per: https://github.com/OpenAPITools/openapi-generator/blob/b5942624d6714f38c0bde9ae9c7400df1d48b1ed/modules/openapi-generator/src/main/resources/python/api_client.mustache#L528 in api_client.mustache def __deserialize_file it is used to extract the filename to save.

**Comment by spacether** [comment]
This issue has been resolved by https://github.com/OpenAPITools/openapi-generator/pull/5679
Thank. you for your hard work @CrshOverride!

**Comment by g-bon** [comment]
Thanks @CrshOverride
