### ISSUE TITLE
[bug][Kotlin] Default typeMapping for 'date' should be LocalDate

### ISSUE THREAD

**Issue by legzo** [OpenAPITools/openapi-generator#2063]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When a spec specifies a property as : 

```
"type": "string",
"format": "date",
```

the Kotlin generator generates the corresponding field as a `LocalDateTime` and later, the parsing fails when Jackson is used (Gson too) saying it cannot find a converter for this type.

As I understand the spec, `"format":"date"` should result in a `LocalDate` and `"format":"date-time"` in a `LocalDateTime`

##### openapi-generator version

I tried version 3.3.4, but I read the code of [master](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java) and the problem is still present.

##### Steps to reproduce

Use as an input any spec that has a property configured as : 

```
"type": "string",
"format": "date",
```

##### Suggest a fix/enhancement

I think there is only one line to change at https://github.com/OpenAPITools/openapi-generator/blob/0b66fa5c8214e2907a326fa8684cb2adcfa438a6/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractKotlinCodegen.java#L175

it should be

```
 typeMapping.put("Date", "java.time.LocalDate");
```

I can provide a PR if you think it is really a bug.

Cheers.

**Comment by legzo** [comment]
@jimschubert , @dr4ke616 : what's your take on that ?

**Comment by jimschubert** [comment]
@legzo I do think this would be considered a bug. There's always a workaround with type mappings in that you can specify them on the command line. Some generators may set certain mappings in such a way that user overrides aren't supported (as with Kotlin client json types).

If you're able to open a PR, that would be awesome. I'm in a crunch at work and it's been taking away from my open source contrib time.

**Comment by jimschubert** [comment]
I've tagged this as client/server related, since this is in the base class. Will evaluate the full impact later.

**Comment by legzo** [comment]
Hi @jimschubert, thanks for your feedback.

As a matter of fact I overrid the mapping in the config of the generator, so there is a work around. However I find it deceptive that out of the box Jackson is not able to deserialize a model that is propertly typed and formatted in the json. 

I'll make a PR and you'll decide what to do with it :)

Thank you for your open-source contrib by the way. Much appreciated.
