### ISSUE TITLE
[BUG] [PYTHON] generateSourceCodeOnly value is not checked properly

### ISSUE THREAD

**Issue by timbedard** [OpenAPITools/openapi-generator#2066]
##### Description

This is the code from PythonClientCodegen.java that checks the config property for `generateSourceCodeOnly`:
```java
Boolean generateSourceCodeOnly = false;
if (additionalProperties.containsKey(CodegenConstants.SOURCECODEONLY_GENERATION)) {
    generateSourceCodeOnly = true;
}
```
It's pretty obvious that when the config json includes:
```json
{
    "generateSourceCodeOnly": false
}
```
...the above code will incorrectly set `generateSourceCodeOnly` to `true`.

##### openapi-generator version

4.0.0

##### OpenAPI declaration file content or url

< any valid declaration file >

##### Command line used for generation

`openapi-generator generate -i openapi.yaml -g python -c config.json`

##### Steps to reproduce

Run the above command on a valid declaration file with `generateSourceCodeOnly` set to `false` in the config.json.

##### Suggest a fix

Actually set the value to what's in the config.
```java
Boolean generateSourceCodeOnly = false;
if (additionalProperties.containsKey(CodegenConstants.SOURCECODEONLY_GENERATION)) {
    generateSourceCodeOnly = convertPropertyToBoolean(CodegenConstants.SOURCECODEONLY_GENERATION);
}
```

**Comment by wing328** [comment]
I think it should be fixed by https://github.com/OpenAPITools/openapi-generator/pull/2015. Please give the latest master a try.

Closing this for the time being. We'll reopen if it's still an issue.

**Comment by timbedard** [comment]
Searched but still missed it. Thanks.

**Comment by wing328** [comment]
> if (additionalProperties.containsKey(CodegenConstants.SOURCECODEONLY_GENERATION)) {
    generateSourceCodeOnly = convertPropertyToBoolean(CodegenConstants.SOURCECODEONLY_GENERATION);
}

Do you mind filing a PR with your suggested fix if it's still an issue?

**Comment by timbedard** [comment]
Nah, #2015 fixed it.
