### ISSUE TITLE
[BUG][Python] Bug in Cookie authentication

### ISSUE THREAD

**Issue by tomghyselinck** [OpenAPITools/openapi-generator#2075]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix

##### Description

We use `apiKey` authentication via `cookie` in an OpenAPI 3.0 spec file.

We generate Python client code.

The generated `openapi_client/configuration.py` contains invalid code: The `'in'` key in the `auth_settings()` map misses a value.

```python
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'FullAccessAuth':
                {
                    'type': 'api_key',
                    'in': ,
                    'key': 'FULL_ACCESS_TOKEN',
                    'value': self.get_api_key_with_prefix('FULL_ACCESS_TOKEN')
                },
        }
```

We expect it to be either:
```python
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
            'FullAccessAuth':
                {
                    'type': 'api_key',
                    'in': 'cookie',
                    'key': 'FULL_ACCESS_TOKEN',
                    'value': self.get_api_key_with_prefix('FULL_ACCESS_TOKEN')
                },
        }
```
or
```python
    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {}
```

##### openapi-generator version

`4.0.0-SNAPSHOT`:
https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20190206.074014-271.jar

##### OpenAPI declaration file content or url

`python-cookie-auth.yaml`:
```yaml
openapi: '3.0.1'
info:
        title: Test REST API
        version: "1.0"
servers:
- url: http://localhost:8080/
paths:
        /data:
                get:
                        summary: Get the Data
                        responses:
                                200:
                                        description: The Data
                                        content:
                                                application/json:
                                                        schema:
                                                                type: string
                        security:
                        - FullAccessAuth: []
components:
        securitySchemes:
                FullAccessAuth:
                        type: apiKey
                        in: cookie
                        name: FULL_ACCESS_TOKEN
```

##### Command line used for generation

    java -jar openapi-generator-cli-4.x.jar generate -i ./python-cookie-auth.yaml -g python -o ./python-cookie-auth/

##### Steps to reproduce

    wget \
        'https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/4.0.0-SNAPSHOT/openapi-generator-cli-4.0.0-20190206.074014-271.jar' \
        -O 'openapi-generator-cli-4.x.jar'
    rm -rf python-cookie-auth/
    java -jar openapi-generator-cli-4.x.jar generate -i ./python-cookie-auth.yaml -g python -o ./python-cookie-auth/

You can also use the files in attachment:
[python-cookie-auth.zip](https://github.com/OpenAPITools/openapi-generator/files/2836546/python-cookie-auth.zip)

##### Related issues/PRs

* #2077

##### Suggest a fix

When cookie authentication is used, we actually don't need the item (i.e. `'FullAccessAuth'`) in the dict.
The cookie should be set to the `ApiClient.cookie` object when the `Set-Cookie` HTTP header is received by the `ApiClient` object (see also #2077).

**Comment by spacether** [comment]
Our auth pattern is to keep all info in the configuration auth dict and then load it in when requests are made.

How about using the in cookie solution and load the configuration value into the cookie if it is not already there. If cookie auth is used, and the login route is hit, set the value of the cookie key in the auth configuration. That keeps this auth type following our current patterns.

**Comment by spacether** [comment]
Two useful test cases could be:
in one host will have two cookie authentication types:
cookieAuthA
cookieAuthB
Have route loginA use cookieAuthA
Have route loginB use cookieAuthB
Have route /cookieNeededA use cookieAuthA
Have route /cookieNeededB use cookieAuthB

**Comment by tomghyselinck** [comment]
Hi @spacether,

Thank you for your reply.

I also support you suggestion.

Please note that this implementation will also need support at `def update_params_for_auth(self, headers, querys, auth_settings)` in `modules/openapi-generator/src/main/resources/python/api_client.mustache`:

```python
    def update_params_for_auth(self, headers, querys, auth_settings):
        """Updates header and query params based on authentication setting.

        :param headers: Header parameters dict to be updated.
        :param querys: Query parameters tuple list to be updated.
        :param auth_settings: Authentication setting identifiers list.
        """
        if not auth_settings:
            return

        for auth in auth_settings:
            auth_setting = self.configuration.auth_settings().get(auth)
            if auth_setting:
                if not auth_setting['value']:
                    continue
                elif auth_setting['in'] == 'header':
                    headers[auth_setting['key']] = auth_setting['value']
                elif auth_setting['in'] == 'query':
                    querys.append((auth_setting['key'], auth_setting['value']))
                elif auth_setting['in'] == 'cookie':
                    # TODO - Implement this...
                else:
                    raise ValueError(
                        'Authentication token must be in `query` or `header`'
                    )
```

Furthermore, there may also be the need to define the priority of the `self.cookie` vs `self.configuration.auth_settings()` regarding the final value of a given cookie. I mean: can `self.cookie` override the value set by the definitions in the auth settings or the other way round.

Another thing there might to be taken care of: How to delete a cookie?
* Unset `self.cookie`.
* Unset the `value` field in the `auth_setting`.
Any conflict in usage here?

If possible, all of this should be handled transparently (see also my feature request #2077) since IMHO cookie assignment is server-managed while (_standard_ header or query) API key can rather be seen as a "_shared key_".

Thank you in advance!

**Comment by tomghyselinck** [comment]
Maybe a more extended useful test case (using two authentication tokens) could be:
1. cookieAuthA
1. cookieAuthB
1. Have route /cookieNeededA use cookieAuthA (_should fail_)
1. Have route /cookieNeededB use cookieAuthB (_should fail_)
1. Have route loginA use cookieAuthA
1. Have route /cookieNeededA use cookieAuthA
1. Have route /cookieNeededB use cookieAuthB (_should fail_)
1. Have route loginB use cookieAuthB
1. Have route /cookieNeededA use cookieAuthA
1. Have route /cookieNeededB use cookieAuthB
1. Have route logoutA use cookieAuthA
1. Have route /cookieNeededA use cookieAuthA (_should fail_)
1. Have route /cookieNeededB use cookieAuthB
1. Have route logoutB use cookieAuthB
1. Have route /cookieNeededA use cookieAuthA (_should fail_)
1. Have route /cookieNeededB use cookieAuthB (_should fail_)
