### ISSUE TITLE
[REQ][Python] Python client Cookie authentication should be transparent

### ISSUE THREAD

**Issue by tomghyselinck** [OpenAPITools/openapi-generator#2077]
### Is your feature request related to a problem? Please describe.

In summary:
Cookie authentication is currently not "_transparent_" to the API user.
We need to set the cookie ourselves once authenticated to the server.

1. We use cookie authentication in an OpenApi 3.0 spec.
1. We generate a Python client
1. Perform a "_login_" operation on the REST API (using the `openapi_client.DefaultApi.login_post()` call).
1. The REST server responds with a `Set-Cookie` HTTP header.
1. For successful authentication, the API user must now set the value of `openapi_client.ApiClient.cookie` with the value obtained from the "_HTTP headers_" returned by `openapi_client.DefaultApi.login_post_with_http_info()` call.

See also an example in #2075 or in attachment:
[python-cookie-auth.zip](https://github.com/OpenAPITools/openapi-generator/files/2836815/python-cookie-auth.zip)

Generate Python client code using:

    ./python-cookie-auth.sh

## Describe the solution you'd like

When the REST API server returns a `Set-Cookie` HTTP header, the `ApiClient` should handle it properly:
1. E.g. `'Set-Cookie': 'FULL_ACCESS_TOKEN=123; HttpOnly; Path=/; SameSite=Strict'` should _set_ the `FULL_ACCESS_TOKEN` cookie
1. E.g. `'Set-Cookie': 'FULL_ACCESS_TOKEN=; Expires=Thu, 01-Jan-1970 00:00:00 GMT; Max-Age=0; Path=/'` should _unset_ the `FULL_ACCESS_TOKEN` cookie

I suppose the `openapi_client.ApiClient.__call_api` (or any function it calls) should handle incoming `Set-Cookie` headers and update `openapi_client.ApiClient.cookie` value accordingly.

### Considerations

When multiple `cookie` authentications are defined in the OpenAPI (3.0) description file, you should considered to extend the support to multiple cookies.
For example make `openapi_client.ApiClient.cookie` a `dict` of cookie names to values.

Secondly, the API server can also send cookies which are not used for authentication.
Those can either be filtered out if not useful or also added to the `cookie` dict and used just as is.

## Describe alternatives you've considered

At this moment we set the `openapi_client.ApiClient.cookie` value once we received it.

**Comment by spacether** [comment]
I think that this was resolved with:
https://github.com/OpenAPITools/openapi-generator/pull/2367/files
