### ISSUE TITLE
[BUG] [Python] library .travis.yaml omits python 3.6 and 3.7

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#2093]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating a python library from a 2.0 spec file, .travis.yml only lists python versions:
```
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  #- "3.5-dev" # 3.5 development branch
  #- "nightly" # points to the latest development branch e.g. 3.6-dev
```

Per here: https://docs.travis-ci.com/user/languages/python/
Travis supports:
```
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
```

##### openapi-generator version

3.3.4
this issue exists in the latest master branch though

##### OpenAPI declaration file content or url

Any spec

##### Command line used for generation

Any python library generated

##### Steps to reproduce

Generate a python library
open up the .travis.yml file and check the listed python versions

##### Related issues/PRs

None

##### Suggest a fix

Update the mustache file here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/travis.mustache

**Comment by wing328** [comment]
@spacether yup, the file likely is outdated as it has not been updated for a long time. Please submit a PR when you've time.

When I've time, I'll also take a look at the Travis files in other libs (e.g. Ruby, PHP, etc) to ensure it contains the latest supported versions.

**Comment by spacether** [comment]
This has been resolved by the above pr
