### ISSUE TITLE
[BUG] [angular-typescript] Wrong Typescript Version for Angular 6 with Npm

### ISSUE THREAD

**Issue by karismann** [OpenAPITools/openapi-generator#2096]
##### Description

Unable to `npm run build` the sample typescript-angular-v6-provided-in-root\builds\with-npm because the typescript version is not correct :  
> Error: The Angular Compiler requires TypeScript >=2.7.2 and <2.10.0 but 2.6.2 was found instead.

##### openapi-generator version

4.0.0-SNAPSHOT

##### Related issues/PRs

https://github.com/angular/angular/blob/master/CHANGELOG.md#600-2018-05-03

##### Suggest a fix

`tsVersion`  ">=2.1.5 <2.7.0"  value should be replaced by ">=2.7.2 and <2.10.0"

I will send a PR

**Comment by macjohnny** [comment]
@karismann @wing328 can you close this issue? it was merged with https://github.com/OpenAPITools/openapi-generator/pull/2097
