### ISSUE TITLE
[BUG] OpenApi 2 client generator refparameters not separated by slash

### ISSUE THREAD

**Issue by karismann** [OpenAPITools/openapi-generator#2098]
##### Description

In an openAPI 2.0 declaration, if you have two ref parameters not separated by "/" , the client generator send the error : 

> -attribute paths.'/v1/utilisateurs/{codesociete}-{matricule}'. Declared path parameter codesociete}-{matricule needs to be defined as a path parameter in path or operation level

##### openapi-generator version

4.0.0-SNAPSHOT
worked before with swagger codegen 2.2.3

##### OpenAPI declaration file content or url

```json
    "/v1/utilisateurs/{codesociete}-{matricule}" : {
      "get" : {
        "description" : "",
        "operationId" : "getUserBySocieteMatricule",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "codesociete",
          "in" : "path",
          "required" : true,
          "type" : "string"
        }, {
          "name" : "matricule",
          "in" : "path",
          "required" : true,
          "type" : "string"
        } ],
```

**Comment by wing328** [comment]
@karismann what about skipping the validation for the time being as a workaround?

**Comment by karismann** [comment]
You're right, when we use the `--skip-validate-spec` to generate the client, all works.
But this error message is not supposed to appear.

**Comment by wing328** [comment]
I agree the validation is not perfect and may sometimes output false alarms. Maybe we should change to --skip-validate-spec by default and output the validation errors as FYI.

**Comment by wing328** [comment]
Please try the latest master with the upgrade parser to see if it's still an issue.
