### ISSUE TITLE
[BUG][Python] file upload seems broken

### ISSUE THREAD

**Issue by rienafairefr** [OpenAPITools/openapi-generator#2118]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?   latest master
- [X] Have you search for related issues/PRs?

##### Description

When using a `multipart/form-data` request body like the example in the spec
```
requestBody:
  content:
    multipart/form-data:
      schema:
        properties:
                # The property name 'file' will be used for all files.
          file:
            type: array
            items:
              type: string
              format: binary
```
the `ApiClient` tries to 'sanitize_for_serialization` the `(fileName, fileContent, fileMIME)` tuple that is describing the file data, so we get a string with that tuple, instead of the actual tuple, being sent to urllib3, and the API doesn't identify the content of the file correctly (it believes the serialized tuple is the content of the file...)

##### Suggest a fix

I seem to be able to upload a file or multiple files by adding the files tuples after the 'sanitization', but I need more testing before a PR can be sent

**Comment by shahargl** [comment]
any workaround on this? (cc @rienafairefr)

**Comment by shahargl** [comment]
> I seem to be able to upload a file or multiple files by adding the files tuples after the 'sanitization', but I need more testing before a PR can be sent

can you describe how you did this? @rienafairefr

**Comment by spacether** [comment]
This is working in the python client.
See the spec [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L1203)
See the test [here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L379)

Plural files work too:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L410
