### ISSUE TITLE
[BUG][ANGULAR] Typescript compiler error when using formData

### ISSUE THREAD

**Issue by rolandbaettig** [OpenAPITools/openapi-generator#2147]
##### Description
Following api-definition leads to a typscript compiler error
```yaml
  /document/upload:
    post:
      tags:
        - document
      summary: 'uploads a pdf as a document'
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: 'The file to upload.'
      responses:
        200:
          description: 'Successful operation'
```
this generates in the angular service following code (snippet):
```
        if (file !== undefined) {
            formParams = formParams.append('file', <any>file) || formParams;
        }
```
which leads to following typscript error:

ERROR in src/app/core/services/backend-api/generated/api/document.service.ts(447,26): error TS1345: An expression of type 'void' cannot be tested for truthiness

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

```yaml
  /document/upload:
    post:
      tags:
        - document
      summary: 'uploads a pdf as a document'
      consumes:
        - multipart/form-data
      parameters:
        - in: formData
          name: file
          type: file
          description: 'The file to upload.'
      responses:
        200:
          description: 'Successful operation'
        405:
          description: 'Invalid input'
```
##### Command line used for generation

maven-plugin

##### Suggest a fix
```
        if (file !== undefined) {
            formParams = formParams.append('file', <any>file) as any || formParams;
        }
```

**Comment by macjohnny** [comment]
this is due to https://github.com/Microsoft/TypeScript/issues/26262, a breaking change in typescript 3.1
I can't find a way to tell the compiler to ignore this error
