### ISSUE TITLE
[Python-Flask] How to generate a Python-Flask server with OpenAPI Generator that refers to my own implementation of *_controller.py?

### ISSUE THREAD

**Issue by pseres** [OpenAPITools/openapi-generator#2148]
##### Description
If I want to generate a Python-Flask server providing a certain OpenAPI spec as input - let's say _foo.yaml_ - by running the following command:
`java -jar openapi-generator-cli.jar generate -i foo.yaml -g python-flask -o python-flask_api_server`

...it will generate a server stub containing a file called _foo_controller.py_ under _\python-flask_api_server\openapi_server\controllers_ and each method defined in this file returns the same template string:

> 'do some magic!'

**foo_controller.py**
```
def foo_post(inline_object=None):  # noqa: E501
"""Create a foo

 # noqa: E501

:param inline_object: 
:type inline_object: dict | bytes

:rtype: str
"""
if connexion.request.is_json:
    inline_object = InlineObject.from_dict(connexion.request.get_json())  # noqa: E501
return 'do some magic!'
```

What I'm trying to do with OpenAPI Generator is to generate a server stub whose foo_controller.py references my own implementation of this file, like this for example:

**foo_controller.py** (generated file)
```
import foo_controller_impl

def foo_post(inline_object=None):  # noqa: E501
"""Create a foo

 # noqa: E501

:param inline_object: 
:type inline_object: dict | bytes

:rtype: str
"""
foo_controller_impl.foo_post_impl(inline_object)
```

**foo_controller_impl.py** (my implementation to which foo_controller.py refers to)
```
def foo_post_impl(inline_object=None):  # noqa: E501
if connexion.request.is_json:
    inline_object = InlineObject.from_dict(connexion.request.get_json())  # noqa: E501
print("Request body is:\n" + str(inline_object))
response = "/foo/1"
return response
```

I ran the following command to generate a new template set:
`java -jar openapi-generator-cli.jar meta -o my-codegen -n myCodegen -p org.openapitools.codegen`

But after reading the generated _README.md_ and inspecting _MycodegenGenerator.java_ it still isn't very clear to me how I could achieve this. Is this even possible?

Any help would be greatly appreciated.
##### openapi-generator version
3.3.4
##### Command line used for generation
`java -jar openapi-generator-cli.jar meta -o my-codegen -n myCodegen -p org.openapitools.codegen`

**Comment by tomghyselinck** [comment]
Hi @pseres,

I like your proposal, but I would rather suggest to call the implementation _after_ parsing the (`json`) input.

Something like (_adjusting your example_):

**`foo_controller.py`** (generated file)

```py
import foo_controller_impl

def foo_post(inline_object=None):  # noqa: E501
"""Create a foo

 # noqa: E501

:param inline_object: 
:type inline_object: dict | bytes

:rtype: str
"""
if connexion.request.is_json:
    inline_object = InlineObject.from_dict(connexion.request.get_json())  # noqa: E501
foo_controller_impl.foo_post_impl(inline_object)
```

**`foo_controller_impl.py`** (my implementation to which `foo_controller.py` refers to)

```py
def foo_post_impl(inline_object=None):  # noqa: E501
    print("Request body is:\n" + str(inline_object))
    response = "/foo/1"
    return response
```

**Comment by pseres** [comment]
Hello @tomghyselinck,

Thanks for the proposal! By the way, I finally figured out how to edit the template for the controller file in order to refer to my implementation.  The solution is mostly based on this stackoverflow answer: https://stackoverflow.com/a/47554626/8044725.
