### ISSUE TITLE
[BUG] openapi-generator-cli detects wrong version

### ISSUE THREAD

**Issue by kokorin** [OpenAPITools/openapi-generator#2180]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

openapi-generator-cli.sh detects version as `v3.3.4` not `3.3.4`

##### openapi-generator version

3.3.4

##### Steps to reproduce

Download launch [script](https://github.com/OpenAPITools/openapi-generator/blob/master/bin/utils/openapi-generator-cli.sh) and run it
##### Suggest a fix

```ver=${OPENAPI_GENERATOR_VERSION:-$(latest.tag $ghrepo)}

if [[ $ver == v* ]]
then
ver=${ver:1}
fi```

**Comment by ackintosh** [comment]
@kokorin Thanks for this issue! 👍  #2223 has been merged into master.
