### ISSUE TITLE
[BUG][Java][Spring] error: constant string too long

### ISSUE THREAD

**Issue by TruthNZ** [OpenAPITools/openapi-generator#2186]
With a large enough data model the Java-Spring server generator produces example responses with a string that is too long for the Java compiler.
It's not exceeding the size of a string allowed by the JVM, but the size of a string constant the compiler handles.

```java
 default ResponseEntity<ResponseObject> restMethod(@ApiParam(value = "A Parameter",required=true) @PathVariable("parameter") String parameter) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    ApiUtil.setExampleResponse(request, "application/json", "{ [A large example json string response that breaks the Java compiler] }");
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
    }
```

Was generated using openapi-generator-maven-plugin 3.3.4.
Settings:
```xml
<configOptions>
	<sourceFolder>${generated-sources-java-path}</sourceFolder>
	<interfaceOnly>true</interfaceOnly>
	<java8>true</java8>
	<dateLibrary>java8</dateLibrary>
	<useBeanValidation>true</useBeanValidation>
	<performBeanValidation>true</performBeanValidation>
</configOptions>
<generatorName>spring</generatorName>
```

Potentially similar to the swagger codegen issue: https://github.com/swagger-api/swagger-codegen/issues/9055

Is an example response needed?
Failing that: Could it be broken into a StringBuilder (or at worst just string concatenation)? Or maybe loaded from a resource file?

**Comment by wing328** [comment]
@TruthNZ does setting the "example" in the spec give you control on the example response?

**Comment by TruthNZ** [comment]
We have examples set in the spec. We've set them at the individual field level (large document structure with various reused elements) - and we definitely want them for our api consumers to have a good idea of formatting requirements, etc.
In the codegen it looks like it's concatenating them all (+ standard examples for fields we haven't explicitly specified) into an overall example response document - hence the massive example string.

But even if we modify it on our specific project, I believe the overall bug still needs to be dealt with.

**Comment by wing328** [comment]
OK. Can you share the exact error message thrown by JVM?

**Comment by TruthNZ** [comment]
```java
[ERROR] /C:/Development/AProject/src/main/java/com/company/project/api/RestInterfaceApi.java:[53,77] constant string too long
```

**Comment by wing328** [comment]
What about looping through all examples via `postProcessOperationsWithModels` and set the example to null or empty string if the string exceeds a certain size (and output a warning as well) ?

**Comment by inthegarage** [comment]
Is it possible tor remove this line altogether or trim it, currently some of the sample values are using the full extent of the value, IE a number is 5.6373766566333287642009963747113943099975585937

Is there any option to remove this at all? I don't really need this example response in the interface.

**Comment by wing328** [comment]
@inthegarage maybe removing it from the spec as a workaround for the time being?

**Comment by inthegarage** [comment]
@wing328 How do you mean "spec"? Is this the yaml file used to created the API or something else?
