### ISSUE TITLE
[REQ] Use cookie-cutter approach for templates

### ISSUE THREAD

**Issue by jgroom33** [OpenAPITools/openapi-generator#2194]
### Is your feature request related to a problem? Please describe.

The process of writing a language was not intuitive to me. 

## Describe the solution you'd like

A directory for all static files should be used.  This would operate similarly to this project: https://github.com/audreyr/cookiecutter

Files and folders within the well-known directory (cookiecutter) will automatically be parsed by the template engine.  This approach would remove the requirement to code addSupportingFile.

Additionally, the model and api template files could be placed within the nested directory structure.  Those files could be added to an ignoreFile HashMap.

An example of the approach is [here](https://github.com/OpenAPITools/openapi-generator/tree/ead71fe439b6854dafa3faad8a5d56e93dcd777b/modules/openapi-generator/src/main/resources/python-blueplanet/app)

**Comment by rienafairefr** [comment]
I've proposed something to solve that kind of problem in #619,
