### ISSUE TITLE
[REQ] Functional requirements

### ISSUE THREAD

**Issue by windymindy** [OpenAPITools/openapi-generator#2216]
### Is your feature request related to a problem? Please describe.

Hi.
I get quite confused trying to implement a custom code generator.
Looking through the existing templates and java classes, I find them very diverse.
And even though it is relatively easy to get started, I start to worry about my custom generator compliance.
How do I make sure, that the code it produces is correct and that it conforms to the Specification?

## Describe the solution you'd like

First of all, I thought, that it would be nice to state functional requirements for a generator implementation.
Then, there are tests for samples, but what about tests for generators? Maybe that would be nice to have an API description, which covers most of OpenAPI Specification features. So that an automatic test can confirm, that a specific implementation supports authentication, header parameter routing, schema validation and so on.

What do you think?

## Additional context

Functional requirements reflections:
1. Networking.
   An implementation should support encryption.
2. Routing.
   It definitely should handle all the paths/queries/headers/methods/media types routing variants.
3. Serialization/deserialization.
   Should an implementation express parameters, headers, etc. in parsed structural datatypes?
   Should an implementation serialize/deserialize request/response bodies?
4. Validation.
   An implementation definitely should validate request/response against specification.
5. Security schemes.
   Is authentication handled by generated code or by hand-written one?
6. Errors.
7. Logging.
8. ???

**Comment by wing328** [comment]
@windymindy thanks for your feedback. I wonder if you can contact me via https://gitter.im (ID: wing328) or other IM channels you prefer for a quick chat about your requirement for a custom generator.

**Comment by windymindy** [comment]
We have discussed, that at first it would be nice to create a readme file with functional requirements for all generators. Please, feel free to comment on what you expect from an implementation.

**Comment by windymindy** [comment]
Looks like none is interested.
