### ISSUE TITLE
[BUG][R]Some Model classes are not generating in R-generator like "Date"

### ISSUE THREAD

**Issue by Ramanth** [OpenAPITools/openapi-generator#2217]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Model is not getting generated when the name of the model is "Date" in r codegeneration.

**Details of what causing the issue:**
Date is being mapped to "java.util.Date" in DefaultCodegen file which is being extended in the RClientCodegen as a result the Date is mapped to the Date class of java and is being skipped from being generated.

I guess the importMapping list needs to be cleared in the RClientCodegen constructor as it makes no sense of converting them to java types.

##### openapi-generator version

4.0.0

##### Steps to reproduce
use openapi-codegen-cli to generate the models in r language, with any model name matching "Date"
The model will not be generated.

##### Related issues/PRs
Not Yet
##### Suggest a fix
Clear the **importMappping** list inside the constructor of **RClientCodegen**

**Comment by wing328** [comment]
Already fixed via https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/RClientCodegen.java#L179

**Comment by wing328** [comment]
FYI. Added a test via https://github.com/OpenAPITools/openapi-generator/pull/13345
