### ISSUE TITLE
[REQ] Feature Request Description

### ISSUE THREAD

**Issue by jason-henriksen** [OpenAPITools/openapi-generator#2222]
### Is your feature request related to a problem? Please describe.

I am working on a new generator that is specific to my company.   I found it very difficult to debug the java code that sets up the data sent to the mustache files.   The existing documentation suggests a complex method of running the jar in suspend and then attaching an IDE debugger on a debug port.

## Describe the solution you'd like

A much simpler way to get the generator to run in the debugger was to simply create a JUnit test that calls the CLI library programmatically.  When I debug the JUnit test, it calls the CLI, the CLI calls my code and then I've easily got my code running in debug mode without any mucking around with debug ports.

## Describe alternatives you've considered

I proved this worked on my own project, then I made a PR to alter the openapi **codgen meta** command to create that JUnit test automatically.   The technique makes it much easier to debug generators and also makes it easier for new generators to get started.

## Additional context

I've already forked the project with the code changes needed, the updated mustache files and an update to the documentation.  I appreciate you taking the time to review and consider this PR.

https://github.com/OpenAPITools/openapi-generator/pull/2221

**Comment by jason-henriksen** [comment]
My PR missed a CircleCI item.  I'll fix that this evening.

**Comment by jason-henriksen** [comment]
It looks like I happened to fork the code on a day that those tests weren't running successfully.  I'm updated my branch to match the code as it is today and the tests seem ok.   I've created a new PR and I'm waiting for the tests to run now. 

https://github.com/OpenAPITools/openapi-generator/pull/2388

**Comment by jason-henriksen** [comment]
The updated PR for this issue is passing the CI tests.

**Comment by ackintosh** [comment]
@jason-henriksen Thanks for your contribution! The enhancement will be released as v4.0.0. ✨
