### ISSUE TITLE
[BUG][JAVA] Bug generating spring server: codegenModel is null. Default to UNKNOWN_BASE_TYPE

### ISSUE THREAD

**Issue by fjs018** [OpenAPITools/openapi-generator#2236]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I am trying to generate a java spring server using 4.0.0-beta2, however generation fails with:
```
[main] WARN  o.o.codegen.DefaultCodegen - codegenModel is null. Default to UNKNOWN_BASE_TYPE
[main] WARN  o.o.codegen.DefaultCodegen - The following schema has undefined (null) baseType. It could be due to form parameter defined in OpenAPI v2 spec with incorrect consumes. A correct 'consumes' for form parameters should be 'application/x-www-form-urlencoded' or 'multipart/form-data'
[main] WARN  o.o.codegen.DefaultCodegen - schema: class ComposedSchema {
    class Schema {
        title: null
        multipleOf: null

The .java with the generated APIs has the following:
  import org.openapitools.model.UNKNOWN_BASE_TYPE;
  The default ResponseEntity has:
ApiParam(value = "Click on the **Model** below to view the available parameters for this endpoint." ,required=true )  @Valid @RequestBody UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE) {
```
##### openapi-generator version

4.0.0-beta2 and previous versions.

##### OpenAPI declaration file content or url

```requestBody:
        description: >-
          Click on the **Model** below to view the available parameters for this
          endpoint.
        required: true
        content:
          application/json:
            schema:
              allOf:
                - type: object
                  properties:
                    key:
                      type: string
                      example: S1111...111111
                    alg:
                      type: string
                      example: abc
                    params:
                      type: object
                      oneOf:
                        - $ref: '#/components/schemas/abc_params'
                        - $ref: '#/components/schemas/abb_params'
                        - $ref: '#/components/schemas/aaa_params'
                      example:
                        num: '5521204534320004'
                        expiryDate: 0519
                        sCode: '123'
                      discriminator:
                        propertyName: alg
                        mapping:
                          abc: '#/components/schemas/abc_params'
                          abb: '#/components/schemas/abb_params'
                          aaa: '#/components/schemas/aaa_params'```




##### Command line used for generation

java -jar openapi-generator-cli.jar generate  -i myAPI.yaml -g spring -o spring_server -c  config.json


##### Steps to reproduce

<!-- unambiguous set of steps to reproduce the bug.-->

##### Related issues/PRs

<!-- has a similar issue/PR been reported/opened before? Please do a search in https://github.com/openapitools/openapi-generator/issues?utf8=%E2%9C%93&q=is%3Aissue%20 -->

##### Suggest a fix

<!-- if you can't fix the bug yourself, perhaps you can point to what might be
  causing the problem (line of code or commit), or simply make a suggestion -->

**Comment by fjs018** [comment]
I believe that this is all related to the discussion in: https://github.com/OpenAPITools/openapi-generator/issues/15
@jmini , can you confirm?

**Comment by hugotavares** [comment]
Hi,
I'm facing this issue as well. Still, I'd like to know whether it exists a workaround or not for it, even though it is by manually setting any configuration parameter on the `pom.xml` which generates the API.
Thanks in advance.

**Comment by Emdee89** [comment]
Facing the same issue. Can confirm that the issues does occur once you use `oneOf` like so:
```
  /demonstrations:
    post:
      summary: Create Demonstration
      tags: 
        - Demonstrations
      operationId: createDemonstration
      requestBody:
        description: Demonstration details.
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/demonstrationPayload2'
                - $ref: '#/components/schemas/demonstrationPayload1'
      responses:
        '201':
          description:  created
```

When we comment `oneOf` and only mention one entry of `$ref`, then it works.

**Comment by wing328** [comment]
As a workaround, what about defining the schema separately (instead of inline)? e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/allOf.yaml#L43-L52

**Comment by Emdee89** [comment]
@wing328: I tried that, then it parses the yaml correctly and the source code compiles. However, when you look at the generated code, it does not do what the semantics would imply.

In my experiments, the code generator generates a Java class that looks exactly (of course, except its name) like the Java class that corresponds to the schema mentioned at last under the `oneOf` declaration. What I'd like to have instead is a Java class that is a super-type of the two mentioned schemas.

**Comment by wing328** [comment]
I remember the oneOf implementation in Java is still being discussed/worked on.

>  What I'd like to have instead is a Java class that is a super-type of the two mentioned schemas.

If it's a super-type, what about using `allOf` instead?

**Comment by alfirin** [comment]
Same issue here and I don't wat to use the allOf instead.

**Comment by dkirrane** [comment]
related to
https://github.com/OpenAPITools/openapi-generator/issues/2845

**Comment by jandriescher** [comment]
Hey everyone. Was there ever a solution found for this? Facing the same issue with `oneOf` currently.

**Comment by tejarao25** [comment]
Facing the same issue with oneOf. Any solution for this issue?

**Comment by iekdosha** [comment]
I still have this issue with Spring generator. Anything new?

**Comment by russ-shmus** [comment]
did anyone ever get to the bottom if it? I still see that even latest maven plugin 5.0.0-beta2 fails to generate inheritance code, whereas online generator processes exactly the same yaml correctly. Tried all workarounds found, no luck..

**Comment by skchande** [comment]
Have you tried using Version 3.0?

**Comment by Bubo-DBM** [comment]
@wing328 Hi, same as @frochi42 I'm getting UNKNOWN_BASE_TYPE with version 5.1.1 with openapi-generator-cli for angular-typescript. Using https://editor.swagger.io/ I'm getting the correct client code.

**Comment by trackq** [comment]
fyi. this also happens for python-fastapi server generation

```
@router.post(
    "/callthrough",
    responses={
        201: {"model": Call, "description": "Example response"},
    },
    tags=["default"],
    summary="Create a callthrough",
)
async def post_callthrough(
    unknown_base_type: UNKNOWN_BASE_TYPE = Body(None, description=""),
) -> Call:
    """Createa a new callthrough Call"""
    ...
```

**Comment by sebastian-hatala-leanix** [comment]
Tried the following in FastApi, but changing to `allOf` still fails with OpenApi Generator 😢:

```
def custom_openapi() -> dict[str, dict]:
    openapi_schema = get_openapi(
        title=constants.PROJECT_NAME,
        description=constants.DESCRIPTION,
        version=constants.VERSION,
        routes=app.routes,
    )

    paths = openapi_schema["paths"]
    for path in paths.values():
        for method in path.values():
            if (body := "requestBody") in method:
                schema = method[body]["content"]["application/json"]["schema"]
                if "anyOf" in schema.keys():
                    schema["allOf"] = schema.pop("anyOf")

    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi
```

**Comment by dbcall2** [comment]
This issue was opened three years ago!! The spring code generator is STILL completely broken on polymorphic request/respond bodies. What's causing the delay? Do you guys need people to work on this? Is it internal squabbling about how to "fix" it? I'll gladly volunteer some time to get this fixed as this tech holds promise.

**Comment by CoenWarmer** [comment]
Any update @dbcall2?

**Comment by wing328** [comment]
I've merged https://github.com/OpenAPITools/openapi-generator/pull/12353 to the master which seems to address the inline schema issues in the request bodies. Please pull the latest master to give it a try.
