### ISSUE TITLE
[BUG] [JAXRS-CXF] allOf generates duplicate code instead of using inheritance (regression)

### ISSUE THREAD

**Issue by markus-wa** [OpenAPITools/openapi-generator#2238]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Since `4.0.0`, instead of using inheritance for `allOf`, code is duplicated in JaxRs-CXF. This makes it harder to maintain mappings.

I'm not sure if this is intended or not since, in Java, inheritance won't be possible for more than two `$ref`s. I've asked via Gitter yesterday and it's been suggested to open an issue. If you find that this is intended behavior for the reason I mentioned or any other please let me know.

If it's not intended I can attempt a PR.

##### openapi-generator version

`4.0.0-beta2`

##### OpenAPI declaration file content or url

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: 'http://petstore.swagger.io/v1'
paths:
  '/pets/{petId}':
    get:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The id of the pet to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  '/dogs/{dogId}':
    get:
      summary: Info for a specific dog
      operationId: showDogById
      tags:
        - pets
      parameters:
        - name: dogId
          in: path
          required: true
          description: The id of the dog to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dog'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Dog:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        properties:
          breed:
            type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
```

##### Command line used for generation

`java -jar ~/Downloads/openapi-generator-cli-4.0.0-beta2.jar generate -i ~/Documents/petstore-allOf.yaml -g jaxrs-cxf -o /tmp/petstore-allOf`

##### Steps to reproduce

1. Generate code
2. Look at `/tmp/petstore-allOf/src/gen/java/org/openapitools/model/{Pet,Dog}.yaml`

```java
public class Dog  {
  
  @ApiModelProperty(required = true, value = "")
  private Long id;

  @ApiModelProperty(required = true, value = "")
  private String name;

  @ApiModelProperty(value = "")
  private String tag;

  @ApiModelProperty(value = "")
  private String breed;
```

```java
public class Pet  {
  
  @ApiModelProperty(required = true, value = "")
  private Long id;

  @ApiModelProperty(required = true, value = "")
  private String name;

  @ApiModelProperty(value = "")
  private String tag;
```

##### Related issues/PRs

-

##### Suggest a fix

Switch back to inheritance.

**Comment by ryanwalker** [comment]
This appears to be a bug to me. I am not sure why this would be an intentional change. I can't upgrade to v4 of the gradle plugin because of this.

**Comment by markus-wa** [comment]
> I am not sure why this would be an intentional change.

I was thinking maybe since Java doesn't support inheritance from multiple super-classes. But I agree, it should at least use inheritance where possible.

**Comment by markus-wa** [comment]
Any news on this?

**Comment by wing328** [comment]
Please use the discriminator object if you want inheritance instead of model composition: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#discriminator-object

**Comment by markus-wa** [comment]
Thanks for clearing this up @wing328  🙂
