### ISSUE TITLE
[TypeScript][Angular] Upgrade to ng-packagr 3.0.0

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#224]
##### Description

See original issue https://github.com/swagger-api/swagger-codegen/issues/8251

**Comment by macjohnny** [comment]
@BastiOfBerlin would you like to implement your changes here in openapi-generator? I think this would be very useful!

**Comment by BastiOfBerlin** [comment]
It's really just changing the dependency from 2.4.1 to 3.0.0. See https://github.com/BastiOfBerlin/swagger-codegen/commit/558209cc1bdfba9f85d7e053a961fcb4021b5078

**Comment by macjohnny** [comment]
closed with #1613
