### ISSUE TITLE
[BUG] A lot of license proprietary in mustaches

### ISSUE THREAD

**Issue by SzymonKlimuk** [OpenAPITools/openapi-generator#2255]
#### Bug Report Checklist
Licenses found in source code
OpenAPI generator 4.0.0-beta
No similar issues found on github
"license": "proprietary"

##### Description

there is a lot of "license": "proprietary" in the source code. Especially in the mustaches:

$ grep -r proprietary * |grep mustache
modules/openapi-generator/src/main/resources/lumen/composer.mustache:    "license": "proprietary",
modules/openapi-generator/src/main/resources/php/composer.mustache:    "license": "proprietary",
modules/openapi-generator/src/main/resources/php-symfony/composer.mustache:    "license": "proprietary",
modules/openapi-generator/src/main/resources/ze-ph/composer.json.mustache:    "license": "proprietary",

The questions are:

Why they are there?
Is this going to the generated code?
Shall they be removed if openapi-generator is the Open Source project?

Thanks for your answers.

Szymon Klimuk

**Comment by wing328** [comment]
@SzymonKlimuk that's the default value. The auto-generated code is unlicensed so you can apply whatever license to the auto-generated code: https://github.com/OpenAPITools/openapi-generator#34---license-information-on-generated-code

**Comment by SzymonKlimuk** [comment]
@wing328 Thanks for your explanation.

**Comment by jarekchr** [comment]
Hi,

Thanks for the link and explanation you've provided to Szymon.
However I think that in such case the defaults in the templates should be "free" (or similar) indicating that you can do whatever you want with the generated code. At the moment it's inconsistent in all templates so if it's possible then please change it in the same way.

Thanks and regards,
Jarek

**Comment by wing328** [comment]
@jarekchr thanks for the feedback but "free" is not a valid identifier in https://spdx.org/licenses/.

That's why we went with "unlicense" instead.

Would you have time to help us clean up the license field in various templates to ensure it's "unlicense" by default?

**Comment by jarekchr** [comment]
If not me then I think that my colleagues will help you with this.

**Comment by kacbuk001** [comment]
Based on above discussion, I have created a PR associated to default value of license fields in mustache templates.
https://github.com/OpenAPITools/openapi-generator/pull/2627
