### ISSUE TITLE
[BUG][PHP] Serialize exploded query params array of type string-array of style form

### ISSUE THREAD

**Issue by githubERIK** [OpenAPITools/openapi-generator#2292]
##### Description

_Given_ a get request with optional, exploded, form-style, schema-type-array query parameters of type string (see OpenAPI declaration and steps-to-reproduce below).
_When_ the generated php client code processes the array of query parameters.
_Then_ it does not create the same result of ampersand-connected query as <http://editor.swagger.io/> shows

Actual `?someParamName=0%3DoneValue%261%3DotherValue%262%3DanotherValue`
Expected `?someParamName=oneValue&someParamName=otherValue&someParamName=anotherValue`

![ampersand_query_param](https://user-images.githubusercontent.com/8700908/53734687-59d5b780-3e8d-11e9-9b80-fe455ff94df9.gif)

##### openapi-generator version

master branch (version 3.3.4)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Example API
  version: 0.0.1
servers:
  - url: 'https://some.example.api.com/v1'
paths:
  /notes:
    get:
      summary: Returns all notes.
      operationId: fetchNotes
      parameters:
        - in: query
          name: labelIds
          required: false
          schema:
            type: array
            items:
              type: string
          style: form
          explode: true
      responses:
        '204':
          description: An object containing a list of group objects.
```

from [example repo](https://github.com/githubERIK/openapi-php-multiparam-bug-example/blob/master/example.yaml).

Eventually expect this `?labelIds=LabelOne&labelIds=LabelTwo&labelIds=LabelThree` but the result is `?labelIds=0%3DLabelOne%261%3DLabelTwo%262%3DLabelThree`.

##### Command line used for generation

openapi-generator generate -g php

##### Steps to reproduce

From https://github.com/githubERIK/openapi-php-multiparam-bug-example/commits/master

- Generate PHP client based on [example.yaml](https://github.com/githubERIK/openapi-php-multiparam-bug-example/blob/master/example.yaml)
- Set name in composer.json
- Print failed query

... which is done in <https://github.com/githubERIK/openapi-php-multiparam-bug-example>.

After that clone try it out like in https://github.com/githubERIK/openapi-php-multiparam-bug-tryout with steps described in the [README](https://github.com/githubERIK/openapi-php-multiparam-bug-tryout/blob/master/README.md).

##### Related issues/PRs

Similar, but different: https://github.com/OpenAPITools/openapi-generator/issues/1763.

##### Suggest a fix

Workaround: in the generated file under the comment `// query params`: [lib/Api/DefaultApi.php#L234](https://github.com/githubERIK/openapi-php-multiparam-bug-example/blob/master/lib/Api/DefaultApi.php#L234) replace 

this

```php
        if (is_array($label_ids)) {
            $label_ids = ObjectSerializer::serializeCollection($label_ids, 'multi', true);
        }
        if ($label_ids !== null) {
            $queryParams['labelIds'] = ObjectSerializer::toQueryValue($label_ids);
        }
```

by this

```php
$queryParams['labelIds'] = $label_ids;
```

**Comment by soundstripe** [comment]
Yes! Guzzle build_query already handles this form of array serialization in the query string, and is already being called.

**Comment by copypasta-g** [comment]
I'm working on this issue and will send a PR soon.

**Comment by spawn-guy** [comment]
@copypasta-g i have a remark to the implementation.
the proposed method is correct _Only_ if the `explode: true` (equals `true`). - guzzle serializes parameters correctly. 
However, if `explode: false` i'd suggest to leave the current implementation IN. i'm referring to https://swagger.io/docs/specification/serialization/#query webpage. notice the difference of `expolde true/false`. 
- `true` will produce multiple query parameters,
- `false` actually serializes into one parameter (and then Guzzle will correctly url-encode the resulting query parameters)

**Comment by copypasta-g** [comment]
@spawn-guy that's a good point, I will fix this tomorrow. Thank you!

**Comment by copypasta-g** [comment]
@spawn-guy let's take this discussion to the pull-request since it's more relevant there.
