### ISSUE TITLE
[REQ][Golang][client] interface definitions for api functions

### ISSUE THREAD

**Issue by partkyle** [OpenAPITools/openapi-generator#2294]
### Is your feature request related to a problem? Please describe.

When using an external api in testing it is common to use a golang interface to introduce a mock or fake implementation. 

## Describe the solution you'd like

Automatically generating these interfaces along side the api definitions would make a consistent place for referencing these interfaces to facilitate unit testing for applications that would use this client.

## Describe alternatives you've considered

I could create my own package that has this implementation, but the openapi spec already includes all the information I need. Furthermore, the generated client code includes the request input and output types, so it makes the most sense for the interface to be included in the same package.
 
## Additional context

A quick-and-dirty stab at implementation would look something like this, though I would be up to discuss alternatives:

```
diff --git a/modules/openapi-generator/src/main/resources/go/api.mustache b/modules/openapi-generator/src/main/resources/go/api.mustache
index fe72ace87e..c8a374575e 100644
--- a/modules/openapi-generator/src/main/resources/go/api.mustache
+++ b/modules/openapi-generator/src/main/resources/go/api.mustache
@@ -17,6 +17,35 @@ var (
        _ context.Context
 )

+type {{classname}} interface {
+{{#operation}}
+    /*
+    {{{classname}}}Service{{#summary}} {{{.}}}{{/summary}}
+    {{#notes}}
+    {{notes}}
+    {{/notes}}
+    * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
+    {{#allParams}}
+    {{#required}}
+    * @param {{paramName}}{{#description}} {{{.}}}{{/description}}
+    {{/required}}
+    {{/allParams}}
+    {{#hasOptionalParams}}
+    * @param optional nil or *{{{nickname}}}Opts - Optional Parameters:
+    {{#allParams}}
+    {{^required}}
+    * @param "{{vendorExtensions.x-exportParamName}}" ({{#isPrimitiveType}}{{^isBinary}}optional.{{vendorExtensions.x-optionalDataType}}{{/isBinary}}{{#isBinary}}optional.Interface of {{dataType}}{{/isBinary}}{{/isPrimitiveType}}{{^isPrimitiveType}}optional.Interface of {{dataType}}{{/isPrimitiveType}}) - {{#description}} {{{.}}}{{/description}}
+    {{/required}}
+    {{/allParams}}
+    {{/hasOptionalParams}}
+    {{#returnType}}
+    @return {{{returnType}}}
+    {{/returnType}}
+    */
+    {{{nickname}}}(ctx context.Context{{#hasParams}}, {{/hasParams}}{{#allParams}}{{#required}}{{paramName}} {{{dataType}}}{{#hasMore}}, {{/hasMore}}{{/required}}{{/allParams}}{{#hasOptionalParams}}localVarOptionals *{{{nickname}}}Opts{{/hasOptionalParams}}) ({{#returnType}}{{{returnType}}}, {{/returnType}}*http.Response, error)
+{{/operation}}
+}
+
 type {{classname}}Service service
 {{#operation}}
```

**Comment by DABH** [comment]
Agreed this would be very useful.  I ended up needing to do this (in order to generate mocks) but it took a bit more work than @partkyle 's diff above (though that was a good starting point).  You can peek at https://github.com/DABH/openapi-generator/commits/master if interested.  Some of the changes I made were tailored to how my mocking library etc. is setup so probably not necessary, but some of the diffs there might be helpful; it did end up working for me.
