### ISSUE TITLE
[BUG][Golang] client generations creates unreachable code

### ISSUE THREAD

**Issue by partkyle** [OpenAPITools/openapi-generator#2296]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

The Go client generator creates code that cannot be reached. In the error handler all response codes are iterated over. It's not possible to have 200 level responses in this block, but they are all listed out. You can see the example [here](https://github.com/OpenAPITools/openapi-generator/blob/cc1fe6eebf1c09051185e08407c770246b0003c6/samples/client/petstore/go/go-petstore/api_store.go#L350) to show the issue I'm referring to. It's impossible for the status code to be >= 300 and then == 201.

##### openapi-generator version

4.0.0

This doesn't appear to be a regression because the problem can be seen in the sample code.

##### Suggest a fix

I'm not sure what's possible here, since mustache templates are logic-less. The solution may be just to leave it the way it is.

**Comment by wing328** [comment]
@partkyle would creating the mustache tags `is2xx`, `is3xx`, `is4xx` help?

**Comment by partkyle** [comment]
I could see that being helpful, since this is just to add an error handling case. I'm trying to work out if there's a way to structure the code differently to not need that.
