### ISSUE TITLE
[Swift4] Update Alamofire dependency

### ISSUE THREAD

**Issue by thecivillain** [OpenAPITools/openapi-generator#2300]
The current Alamofire dependency for Swift is **4.7.0** and the current stable version is **4.8.1** with **5.0** in **BETA**. The major issue with the current dependency is the use of deprecated synax in the `Request` extension located in `ResponseSerilization.swift` along with use of `'let' properties that are implicitly 'final'` and should `use 'public' instead of 'open'`, in a multitude of components, causing compiler warnings (see attached screenshot).

**Suggested fix**
The Alamofire dependency should be updated to the latest stable version, optionally monitoring updates to avoid similar problems in the future.

![screenshot 2019-03-05 at 10 19 08](https://user-images.githubusercontent.com/10880165/53794493-665f1c00-3f30-11e9-88e0-a816b33623d5.png)

**Comment by wing328** [comment]
@thecivillain thanks for reporting the issue. May I know if you've time to contribute a PR to update the Alamofire dependency to the latest version? I can show you some good starting points.
