### ISSUE TITLE
[BUG] PHP generates bad links in Model docs

### ISSUE THREAD

**Issue by jacobweber** [OpenAPITools/openapi-generator#2309]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Using the PHP generator, it creates files like `docs/Model/*.md`. They have links at the bottom like "Back to README", which point to "..", but they should point to "../..". The links in `docs/Api` are correct.

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

Any

##### Command line used for generation

Anything with `-g php`.

##### Steps to reproduce

View sample client:
https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/samples/client/petstore/php/OpenAPIClient-php/docs/Model/Dog.md

##### Related issues/PRs

N/A

##### Suggest a fix

Change .. to ../.. in template

**Comment by karismann** [comment]
i will send a PR

**Comment by jacobweber** [comment]
Thanks!
