### ISSUE TITLE
csharp client: OneOfstringarray could not be found

### ISSUE THREAD

**Issue by jathanaselos** [OpenAPITools/openapi-generator#2311]
##### Description

 
Hi there, the C# client (.NET Framework 4.5) is generating class/object names such as:  OneOfstringarray, OneOfValuearray and ObjectInfo, resulting in compile errors.

##### openapi-generator version

1.0.0.0

##### OpenAPI declaration file content or url

https://api.conexsys.com/lead-app/openapi/openapi.xml

##### Command line used for generation

openapi-generator generate -i C:\src\MyProject\openapi.yaml -g csharp --additional-properties=targetFramework=v4.5,packageName=MyProject.APIClient -o out

##### Steps to reproduce

Step 1:
Download the openAPI declaration file

Step 2:
Generate the csharp client (openapi-generator generate -i C:\YOUR_DOWNLOAD_LOCATION\openapi.yaml -g csharp --additional-properties=targetFramework=v4.5,packageName=MyProject.APIClient -o out)

Step 3:
Open the csharp client solution and compile.   

Any help would be GREATLY APPRECIATED!!!   Thank you.

**Comment by markus-wa** [comment]
Same in JAXRS-CXF: 

```
> Task :outbound:rest:common:server:compileJava FAILED
C:\Users\walthema\wsg\master\Java\workspace\zInt\outbound\rest\common\server\build\openapi2java\src\gen\java\com\hp\wsg\outbound\rest\common\server\model\Config.java:3: error: cannot find symbol
import com.hp.wsg.outbound.rest.common.server.model.OneOfintegerstring;
                                                   ^
  symbol:   class OneOfintegerstring
  location: package com.hp.wsg.outbound.rest.common.server.model
```

**Comment by wing328** [comment]
The spec (https://api.conexsys.com/lead-app/openapi/openapi.yaml) contains `oneOf`, which is not fully supported yet but I agree the code should be at least compilble without issue.

**Comment by RichardBruskiewich** [comment]
@wing328 has there been any  progress on implementing this OpenAPI tag in your code generator?  I have just attempted an OpenAPI  tool code generation  just  now on a 3rd party  specification which liberally uses the OneOf tag.

**Comment by gbrown-ce** [comment]
@wing328 Running into the same problem here. Is there any solution to this problem?
