### ISSUE TITLE
[BUG] haskell-http-client: Arbitrary instance for recursive data structures runs forever

### ISSUE THREAD

**Issue by guoshimin** [OpenAPITools/openapi-generator#2312]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

@jonschoning  haskell-http-client generates QuickCheck-based JSON roundtrip tests. For recursive data structures, the Arbitrary instance runs forever.

##### openapi-generator version

master

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.9/api/openapi-spec/swagger.json

##### Steps to reproduce

Run `stack test` on the generated code. The test will be stuck at `V1beta1CustomResourceDefinition`. The cause is `V1beta1JSONSchemaProps` which is a recursive structure.

**Comment by jonschoning** [comment]
recursive datatypes typically require writing a custom Arbitrary instances to control the size of the tree.
some initial thoughts: 
 1. provide a list of datatypes to the generator for which it should not automatically create arbitrary instances for.  These datatypes can then be prepared in a different non-generated file with the custom logic.
 2. provide a list of datatypes to the generator for which MimeJson tests should be excluded entirely
 3. find a way to automatically generate shrinking trees for recursive types; given the limits of codegen, i'm not sure off the top of my head how to achieve it, but am open to ideas.

**Comment by guoshimin** [comment]
Taking the suggestion from http://www.cse.chalmers.se/~rjmh/QuickCheck/manual_body.html#16, how about:
- generate a `{{typeName}}_sizedGen :: Int -> Gen {{typeName}}` for every record type
- In the implementation, if n is 0, generate `None` for all optional fields. Otherwise, for each optional record field, generate `None` with 50% probability and call sizedGen with `n-1` (or some other decreasing function on `n`) with 50% probability.
- The `Arbitrary` instance for `{{typeName}}` would be `sized {{typeName}}_sizedGen`

**Comment by jonschoning** [comment]
test results with this fix: https://gist.github.com/jonschoning/16e732c17870a9dab831ef4562db079a
test no longer hangs on infinite recursion

**Comment by jonschoning** [comment]
Perhaps we should decrease the size even for non-maybe datatypes as well, to prevent recursion in other cases?

**Comment by guoshimin** [comment]
Yeah, makes sense.

**Comment by jonschoning** [comment]
done https://gist.github.com/jonschoning/16e732c17870a9dab831ef4562db079a/6c5272dcf0deb887623ec4cf420b9d8403ec78ea

**Comment by guoshimin** [comment]
Thanks for the quick fix!
