### ISSUE TITLE
[BUG][jaxrs-jersey] Alias models are initialized with ArrayList

### ISSUE THREAD

**Issue by timkrueger** [OpenAPITools/openapi-generator#2317]
First of all many thanks for your great work. 🙏🏻

##### Description

**Current:**

For the schema `geoJsonFeature` (see section _OpenAPI declaration file content or url_)  the class `GeoJsonFeature` with the following property will generated:

```java
@JsonProperty("bbox")
private GeoJsonBbox bbox = new ArrayList<>();
```

**Expected:**

Because of the parameter `<generateAliasAsModel>true</generateAliasAsModel>` the following is expected:

```java
@JsonProperty("bbox")
private GeoJsonBbox bbox = null;
```

##### openapi-generator version

4.0.0-beta2

##### OpenAPI declaration file content or url

```yaml
schemas:
  geoJsonBbox:
    type: array
    minItems: 4
    maxItems: 4
    items:
      type: number
      format: double

  geoJsonFeature:
    type: object
    properties:
      bbox:
          $ref: "#/schemas/geoJsonBbox"
```

##### Command line used for generation

The following openapi-generator-maven-plugin configuration was used:

```xml
<configuration>
  <generatorName>jaxrs-jersey</generatorName>
  <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
  <generateAliasAsModel>true</generateAliasAsModel>

  <configOptions>
    <modelPackage>${project.groupId}.model</modelPackage>
    <apiPackage>${project.groupId}.api</apiPackage>
    <invokerPackage>${project.groupId}.invoker</invokerPackage>
    <java8>true</java8>
  </configOptions>
</configuration>
```
##### Steps to reproduce

Execute `mvn install` with the previous configuration.

##### Suggest a fix

🙁

**Comment by wing328** [comment]
A similar issue has been reported before. I think we'll leverage `nullable` to indicate whether we should use null or empty list to initialize the property.

**Comment by timkrueger** [comment]
Has someone a workaround for that issue?

**Comment by wing328** [comment]
@timkrueger we'll use https://github.com/OpenAPITools/openapi-generator/issues/1861 to track the issue instead.
