### ISSUE TITLE
[BUG] Gradle plugin, value of validateSpec is overridden by skipValidateSpec

### ISSUE THREAD

**Issue by iura1981** [OpenAPITools/openapi-generator#2319]
##### Description
Please see:
https://github.com/OpenAPITools/openapi-generator/blob/b302c16f74fdbf8d6034b924e0906ad60b4d5d29/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt#L528

```kotlin
            skipValidateSpec.ifNotEmpty { value ->
                configurator.setValidateSpec(value)
            }
```
as a result validateSpec is set as value of skipValidateSpec, as by default skipValidateSpec == false it means that validateSpec will be assigned false, and build will not fail even in case of errors in provided swagger / openApi specification.

##### openapi-generator version
4.0.0-beta2

##### Command line used for generation
./gradlew openApiGenerate

##### Steps to reproduce
Run openApiGenerate for invalid swagger/openAPI specification, it should continue even after reporting that errors where found:
There were issues with the specification, but validation has been explicitly disabled.

##### Suggest a fix
Please rewrite it as:
```kotlin
            skipValidateSpec.ifNotEmpty { value ->
                configurator.setSkipValidateSpec(value)
            }
```

**Comment by jimschubert** [comment]
Fixed via #2583.

There is no option on configurator for `skipValidateSpec`. The intention of that property is to match the option to constraints on the CLI which only allow truthy booleans.  Fix here is just to negate the value of skipValidateSpec:

```
            skipValidateSpec.ifNotEmpty { value ->
                configurator.setValidateSpec(!value)
            }
```
