### ISSUE TITLE
[BUG] [Spring] Async missing import

### ISSUE THREAD

**Issue by TruthNZ** [OpenAPITools/openapi-generator#2327]
When specifying
```html
<configOptions>
	<java8>true</java8>
	<dateLibrary>java8</dateLibrary>
	<library>spring-cloud</library>
	<async>true</async>
</configOptions>
<generatorName>spring</generatorName>
```
the generated API Interface file is missing the import for `CompletableFuture`
(assumably `import java.util.concurrent.CompletableFuture;`)

**Comment by TruthNZ** [comment]
It appears using the library spring-cloud disables the java 8 options from being generated.
However enabling async, still puts in a CompletableFuture.

**Comment by Zomzog** [comment]
Non-blocking looks to be not supported by feign: https://github.com/OpenFeign/feign/issues/361.

I propose to disable async for the spring-cloud library.

**Comment by TruthNZ** [comment]
It is supported by Hystrix.
Just needs the Hystrix module on the path, then add CompletableFuture to the method call.
Source: https://github.com/OpenFeign/feign/tree/master/hystrix

**Comment by Zomzog** [comment]
Good point.
I try it locally and it won't need more dependency. It's confirmed by https://cloud.spring.io/spring-cloud-openfeign/spring-cloud-openfeign.html#spring-cloud-feign-hystrix.

I change the PR to enable it.

**Comment by cbornet** [comment]
You must not set the jdk8 flag as it generates default methods for the interfaces which is not supported by Feign. There's currently no support for the `async` option in Spring-Cloud. You can however specify a CompletableFuture return type by providing the `responseWrapper=CompletableFuture` option
