### ISSUE TITLE
typescript-fetch: type with name "list" is translated to Array

### ISSUE THREAD

**Issue by velohomme** [OpenAPITools/openapi-generator#2336]
#### Description

Using homebrew install.  When generating typescript from swagger type references which are named "list" are translated to Array instead of the actual type.

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url

```json
  
  "tabs": {
    "type": "array",
    "items": {
      "$ref": "#/definitions/list"
    }
  },


  "definitions": {
    "list": {
      "type": "object",
      "properties": {
 
       },
```

yields:

```javascript
  tabs?: Array<Array>;
```

should yield:

```javascript
  tabs?: Array<List>;
```
If I switch the type name to "Choices" the generator works correctly.

##### Command line used for generation

openapi-generator generate -i SWAGGER_FILE_PATH -g typescript-fetch -o TYPESCRIPT_OUTPUT_FOLDER

##### Steps to reproduce

See above

##### Suggest a fix

It appears the generator has some hard-coded relationship such that "list" is an array?

**Comment by macjohnny** [comment]
this is due to https://github.com/OpenAPITools/openapi-generator/blob/d2576f411e0222c3f4fe998037a76b08b472db12/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java#L106

**Comment by eseliger** [comment]
since List ist not a keyword or anything reserved in TS, is it safe to remove it from the list @macjohnny ?

**Comment by macjohnny** [comment]
we can't remove it from the type mapping, as `List` might be used internally when types are determined, so it needs to be mapped correctly to `Array`.
The problem, however, arises from the inability of the code generator to distinguish the type by the fully qualified class name, rather the class name alone. Therefore the class `List` is just converted to `Array`.
Therefore, I believe there is no easy way to solve that.
As a workaround, you could use the `modelPrefix` configuration option. Or simply choose a different name for your model.
