### ISSUE TITLE
[BUG][Rust] Fields that should be nullable aren't `Option`

### ISSUE THREAD

**Issue by tecywiz121** [OpenAPITools/openapi-generator#2337]
##### Description

The Rust generator output `String` when I think it should have output `Option<String>` in the model.

##### openapi-generator version

`4.0.0-beta2`

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 0.0.0
  title: Bug Report
paths:
  /:
    get:
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pages"
components:
  schemas:
    Pages:
      required:
        - next
      properties:
        next:
          type: string
          nullable: true
```

##### Command line used for generation

`openapi-generator generate -i bug-report.yml -g rust -o bug-report`

##### Steps to reproduce

Generate the client library.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/2269
https://github.com/OpenAPITools/openapi-generator/issues/1766

**Comment by wing328** [comment]
What about using the `{{#isNullable}}...{{/isNullable}}` mustache tag to to include `Option<...>`??

**Comment by tecywiz121** [comment]
Something like that?

**Comment by wing328** [comment]
Yup, that should work as we've implemented it in other generators. Let us know if you need help filing a PR. Thanks for your contribution.
