### ISSUE TITLE
[BUG] Master branch is failing to build

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#2340]
#### Bug Report Checklist

The master branch is failing to build on my machine, is anyone else having this issue?
Git commit: 3739584a1a74d8cb124c38d3b03923161e01a4fe
Steps to repoduce:
- `git clone git@github.com:OpenAPITools/openapi-generator.git`
- `cd openapi-generator/`
- `mvn clean install`
Errors are printed in the terminal:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[ERROR] Tests run: 615, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 22.008 s <<< FAILURE! - in TestSuite
[ERROR] testGenerateOperationBodyWithCodedTestData(org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest)  Time elapsed: 0.358 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest.checkFile(JavaJAXRSCXFExtServerCodegenTest.java:393)
	at org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest.testGenerateOperationBodyWithCodedTestData(JavaJAXRSCXFExtServerCodegenTest.java:664)

[ERROR] testGenerateOperationBodyWithJsonTestData(org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest)  Time elapsed: 0.377 s  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
	at org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest.checkFile(JavaJAXRSCXFExtServerCodegenTest.java:393)
	at org.openapitools.codegen.java.jaxrs.JavaJAXRSCXFExtServerCodegenTest.testGenerateOperationBodyWithJsonTestData(JavaJAXRSCXFExtServerCodegenTest.java:711)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   JavaJAXRSCXFExtServerCodegenTest.testGenerateOperationBodyWithCodedTestData:664->checkFile:393 expected object to not be null
[ERROR]   JavaJAXRSCXFExtServerCodegenTest.testGenerateOperationBodyWithJsonTestData:711->checkFile:393 expected object to not be null
[INFO] 
[ERROR] Tests run: 615, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for openapi-generator-project 4.0.0-SNAPSHOT:
[INFO] 
[INFO] openapi-generator-project .......................... SUCCESS [  3.126 s]
[INFO] openapi-generator (core library) ................... FAILURE [ 51.314 s]
[INFO] openapi-generator (executable) ..................... SKIPPED
[INFO] openapi-generator (maven-plugin) ................... SKIPPED
[INFO] openapi-generator-gradle-plugin (maven wrapper) .... SKIPPED
[INFO] openapi-generator-online ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.289 s
[INFO] Finished at: 2019-03-08T22:56:09-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (test-testng) on project openapi-generator: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/justin/programming/open_source/openapi-generator/modules/openapi-generator/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
```

Environment:
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /usr/local/Cellar/maven/3.6.0/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by wing328** [comment]
@spacether the CI builds (circleci, appveyor) are green.

Can you try cloning the repo into a new directory to see if the build runs fine?

**Comment by spacether** [comment]
@wing328 I did that, that's why my instructions include git clone and cd-ing into the just made directory.

**Comment by spacether** [comment]
The commit that caused this issue is: 2985c0f0b804a8b8d8cd944f2f668d5af4abec56
The commit right before it builds with no issues: 37c890f755650c8a281d93fdab9b7fec8472558c
@wing328 can you confirm?

**Comment by wing328** [comment]
@spacether I'm able to repeat the issue locally. Let me look into this.

Please use "-DskipTests" for the time being.

**Comment by wing328** [comment]
UPDATE: I've temporarily disabled 2 tests via cdb447d187 while we work on a fix for the test failures.

**Comment by demonfiddler** [comment]
I will look into this on Monday. Needless to say, all tests were passing before the PR merge.

**Comment by demonfiddler** [comment]
I have been unable to reproduce the test failures on any of Windows 10, CentOS-7 or Ubuntu-18.04. On all three platforms all six tests in JavaJAXRSCXFExtServerCodegenTest pass. The latter two were conducted on brand new OS installations and freshly cloned codebases.

**Comment by spacether** [comment]
@demonfiddler can you confirm that you are running `mvn clean install` to check if this is working?
What version of java are you using?

**Comment by demonfiddler** [comment]
@spacether I used ./mvnw clean install, running on OpenJDK 1.8.

**Comment by spacether** [comment]
@demonfiddler thank you for that confirmation.
It looks like we will need to do more investigation on our systems where the tests are failing.
I do have one last question though.
When you ran `./mvnw clean install` which openapi-generator git commit was it on?
The commits that have this issue are between:
- Earliest: 2985c0f0b804a8b8d8cd944f2f668d5af4abec56
- Latest: 3739584a1a74d8cb124c38d3b03923161e01a4fe
Note: any master branch pulls after this one will pass locally because @wing328 disabled the JavaJAXRSCXFExtServerCodegenTest tests in cdb447d1877fe13be8db8e0bf8b2e6e850c55f7f
so the last 6 commits in the master branch will pass because our failing tests turned off right now.

@wing328 on your machine where the tests failed locally can you let us know your java version and environment info (os, architecture)?

**Comment by demonfiddler** [comment]
@spacether I re-enabled the two failing tests before running the build. There are six tests in total in that test unit and all six passed.

**Comment by wing328** [comment]
Seems like the issue is Mac only:

> Debugging, it looks like my temp file is created in /private/var, but the test is checking /var

That's the finding by @jimschubert

**Comment by demonfiddler** [comment]
I was able to reproduce the problem on a Mac. looks like File.getCanonicalPath() and File.getAbsolutePath() return different things under MacOS. The first is prefixed with '/private', the second isn't. Working on a fix - should be straightforward enough.

**Comment by jimschubert** [comment]
@demonfiddler thanks for investigating. I had briefly debugged a couple of times, and didn't notice the two different File api calls. I didn't see that this issue was reported, and thought it was local to my machine (I assumed it was my adoptopenjdk).
