### ISSUE TITLE
jaxrs-spec: openapi.yaml file is empty

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#235]
When generating a project with the `jaxrs-spec` generator (`JavaJAXRSSpecServerCodegen` class) a file `src/main/openapi/openapi.yaml` is created. This file is empty.

See the `samples/server/petstore/jaxrs-spec` sample (created with `bin/jaxrs-spec-petstore-server.sh`): [openapi.yaml](https://github.com/OpenAPITools/openapi-generator/blob/6983dcffa2ca65931488f5dbb0bf6d537a107628/samples/server/petstore/jaxrs-spec/src/main/openapi/openapi.yaml)

**Comment by wing328** [comment]
Thanks for reporting the issues with the details. I found a fix and will submit a PR soon.
