### ISSUE TITLE
[REQ] New ASP.NET Core 3.0 server generator

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#2350]
To start with, we'll need to create the following:

- new AspNetCore3ServerCodegen.java based on AspNetCoreServerCodegen.java
- new resource folder `modules/openapi-generator/src/main/resources/aspnetcore3` based on `modules/openapi-generator/src/main/resources/aspnetcore` (2.0 or 2.1)
- add batch file to generate Petstore samples under `samples/server/petstore/aspnetcore3`

cc @SeanFarrow

**Comment by SeanFarrow** [comment]
Let me get a vm with .net core 3 on sorted in the next few days.
I’ll then take a look at this, so if you could assign it to me that would be appreciated.

**Comment by A-Joshi** [comment]
@SeanFarrow 
Have been slowly adding in library and other support for the aspnetcore generator particularly for 2.2 and happy to collaborate for 3.0.

**Comment by etherealjoy** [comment]
I am interested in ASP.NET Core 3.0 and I have lots of manual things that I do with the 2.1 generator and I would really like a clean sheet .NET Core 3 including clients and using Microsoft's new high performance json parser

**Comment by A-Joshi** [comment]
Sure - no objections about that - just curious what do you have to do
manually? Moving to 3.0 would be a good idea - though I suspect it will
take a little time after it is releaseed before one can move to it.

**Comment by wing328** [comment]
Discussions related to authentication support: https://github.com/OpenAPITools/openapi-generator/issues/2352

**Comment by A-Joshi** [comment]
Based on what I seen so far [Migrate from ASP.NET Core 2.2 to 3.0 Preview 2](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio)  it might not be that difficult to simply extend the current current generator for one more version.

**Comment by etherealjoy** [comment]
I did these
- update TFM
- Change The Configure services
- Add Json.NET manually
- Adapt Configure services and Configure due to change in hosting environment and Json.NET
- Update package versions

Additionally I was wondering if we use Json.NET or use MS internal Json package
Nice to have would be the DI mechanism to inject the API handlers instead of manually editing the HomeController. This is tedious everytime we generate code due to API update

**Comment by A-Joshi** [comment]
@etherealjoy it might be simpler to adopt the approach of using the generator to generate an abstract class and have the server implement it. I am waiting for #2629 to be merged and will be able to provide more concrete examples.

**Comment by etherealjoy** [comment]
Additionally using current aspnetcore generator I had to rearrange the layout of the folders and update the base images to point to mcr

**Comment by A-Joshi** [comment]
@etherealjoy   might be helpful if you can create a simple example with the generated original code and the modified to work with 3.0 code.

**Comment by SeanFarrow** [comment]
I'm now starting to look at Asp.Net core 3.0 and I would not recommend just upgrading the current generator as is as things like routing have changed. Also, for backwarrd compatibility, we will need to support Json.Net which has been removed in 3.0, but is still opt-in.

I'm currently working on the Asp.net Core 2.x authorization/authentication support to ensure we support all security schemes in OAS v3, but can then look at this in more detail.

Finally, asp.net core is still in preview, so to my thinking there really isn't any rush.

**Comment by etherealjoy** [comment]
The most important thing for me why I am working with .NET Core 3.0 already is official support for Linux arm64. 
Upcoming feature in .NET Core 3.0, single file bundle makes it easier for deployment and deploying in Linux containers is a breeze. Pretty much like Go

But lets wait for MS Build and see

I believe the ASP.NET Core 3.0 would be better off being a new generator. 
Regarding JSON.NET I think we can discuss if we start using MS JSON Parser instead or continue with it.

**Comment by A-Joshi** [comment]
@etherealjoy @SeanFarrow I have it creating properly with 3.0 preview4: routing is still old and uses newtonsoft. Will put in the PR for it in a day or two (need to clean up the generator so the 2.2 break introduced is fixed).

For the new features I suspect it will not be too difficult to extend.

**Comment by SeanFarrow** [comment]
Do you have a branch I can take a look at?

**Comment by A-Joshi** [comment]
@SeanFarrow  - you can look at https://github.com/ihsmarkitoss/openapi-generator/tree/feature/version3 - still missing a little cleanup. but generally works if you set aspnetCoreVersion = 3.0 in thepom.xml

**Comment by A-Joshi** [comment]
I have submitted the preliminary support changes in the PR #2824

**Comment by wing328** [comment]
Closed via #2824
