### ISSUE TITLE
[REQ][haskell-http-client] Support type-mapping and import-mappings

### ISSUE THREAD

**Issue by guoshimin** [OpenAPITools/openapi-generator#2362]
## Describe the solution you'd like

Support type-mapping and import-mappings so we can provide custom implementation for selected model, for example, as is done in https://github.com/kubernetes-client/gen/blob/master/openapi/java.xml.

## Additional context

In the OpenAPI spec for Kubernetes, there is an `IntOrString` type that's currently mapped to `object` if there is no custom mapping for it: https://github.com/kubernetes-client/gen/blob/c07ee54dcb0ae70c6ef587dded93b6ea75f354ea/openapi/preprocess_spec.py#L275. It would be more type safe to create (by hand) a Sum type for it.

@jonschoning

**Comment by jonschoning** [comment]
type-mappings:
  - the behavior of type-mappings changed in openapi-generator in the case that the spec defines a primitive model ref for the type according to https://github.com/kubernetes-client/gen/issues/93#issuecomment-457844107 , so if we can to supply a custom `IntOrString`, but we'll need to remove the `intstr.IntOrString` model definition from the spec.

import-mappings:
 - i will look into adding support

**Comment by jonschoning** [comment]
modify preprocessor to remove models:
https://github.com/jonschoning/kubernetes-client-gen/commit/b876d778d5f9190b6e08f305bd82a9e1219cf459

regen with import-mappings and type-mappings: 
https://github.com/jonschoning/kubernetes-client-haskell/commit/063587bdf4e0f841d41bbaea4d928b6b6579c2e2

add CustomTypes and CustomInstances: 
https://github.com/jonschoning/kubernetes-client-haskell/commit/a268948aca9bdc4259d712e5df27058ca99350d0

tests passed:
https://gist.github.com/jonschoning/df46961e0c999902eec07a3f7785822e

**Comment by guoshimin** [comment]
Thanks for the quick fix! I also did the same test and it worked.
