### ISSUE TITLE
[BUG][typescript-fetch] Parse plain text reponse as json

### ISSUE THREAD

**Issue by frankyjuang** [OpenAPITools/openapi-generator#2372]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Parsing reponse of type string into json breaks. Should just `return response` if return type is string instead of `return response.json()`. The same issue happens with both swagger 2.0 and openapi 3.0

```javascript
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        testPost(options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<string> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).testPost(options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};
```

##### openapi-generator version

3.3.4

##### OpenAPI declaration file content or url
```json
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Test API"
  },
  "paths": {
    "/test": {
      "post": {
        "produces": [
          "text/plain"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "type": "string"
            }
          }
        }
      }
    }
  }
}
```
```json
{
  "openapi": "3.0",
  "info": {
    "version": "1.0",
    "title": "Test API"
  },
  "paths": {
    "/test": {
      "post": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

##### Command line used for generation

```
java -jar openapi-generator-cli.jar generate -i openapi3.json -o test -g typescript-fetch
```

##### Suggest a fix

There's a template variable `{{returnType}}` controls whether we want to `.json()` or not. If `returnType` is `string`, then we probably shouldn't do that.

**Comment by wing328** [comment]
@frankyjuang thanks for reporting the issue. I remember there's something like {{#isString}} that can be used to handle this situation.

**Comment by wing328** [comment]
@frankyjuang can you please try the latest master (which seems to have the TS fetch code refactor/update a little bit) to see if it's an issue?

SNAPSHOT version (JAR) of the latest master can be found in the project's readme.

**Comment by frankyjuang** [comment]
it's fixed in 4.0. thanks!

**Comment by fuzzzerd** [comment]
Is the only solution here to migrate to v4? Will v3.x be patched?

**Comment by wing328** [comment]
We won't patch 3.x. For upcoming versions, please refer to https://github.com/OpenAPITools/openapi-generator#11---compatibility.
