### ISSUE TITLE
[BUG] @JacksonXmlProperty and  xmlAnnotation.mustache seem not to be rendered

### ISSUE THREAD

**Issue by tom-mayer** [OpenAPITools/openapi-generator#2376]
Hey,

I am trying to create an api endpoint that consumes a XML file. This is my openapi yaml file: 
```yaml
openapi: 3.0.1
info:
  version: "1.1"
  title: xml test
  description: some xml test

servers:
  - url: 'http://localhost/'

paths:
  '/test':
    put:
      operationId: testMethodNaming
      requestBody: 
        content:
          'application/xml':
            schema:
              $ref: '#/components/schemas/MyRequest'
      responses:
        '200':
          description: 'OK'

components:
  schemas:
    MyRequest:
      type: object
      properties: 
        name:
          type: string
          xml: 
            attribute: true
```
In the generated model I would have expected a `@JacksonXmlProperty(isAttribute = true)`  (Line 24 of pojo.mustache) annotation to be present on the name property of the model. As well as the xmlAnnotation.mustache template to be rendered on top of the class, so I can use this class in Spring Boot to parse the input XML. 

The generated model is this: 

```java
/**
 * MyRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-03-12T16:53:03.534640+01:00[Europe/Berlin]")

public class MyRequest   {
  @JsonProperty("name")
  private String name;

  public MyRequest name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
  */
  @ApiModelProperty(value = "")


  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MyRequest myRequest = (MyRequest) o;
    return Objects.equals(this.name, myRequest.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MyRequest {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

```
I used the following command to generate everything:
```
java -jar openapi-generator-cli.jar generate \
  -i test.yaml \
  -l spring \
  -o build
```
Did I miss something or do I need to do something additionally to have the XML annotations present in my model?

Cheers
Tom

**Comment by ghilainm** [comment]
I have exactly the same issue. Why was it closed? The attribute part is not generated on my side. The following two annotations are generated but not the attribute part:
   @JsonProperty("MyAttribute")
  @JacksonXmlProperty(localName = "MyAttribute")

**Comment by nsatishkumar81** [comment]
I do have the same issue, as openapi codegen is not generating  @JacksonXmlProperty(isAttribute = true), although the swagger.json has the following tags present of the element.
  "xml": {
              "attribute": true
            }

Note: Tried including withXml as true in ConfigOptions of maven open api codegen plugin.

Can you please provide the fix, which you have followed?

Thanks 
Satish
