### ISSUE TITLE
[BUG] Date and DateTime enums do not work in many languages

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#2404]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generators in python, java, csharp and others fail to generate valid datetime and date enum values. The expected behavior is that valid libraries are generated that cast date and datetime enums as the correct datatypes in the chosen languages.

##### Which version of openapi-generator are you using?
- master branch latest commit

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK
definitions:
  TypeHolderExample:
    type: object
    description: a model to test required properties with an example and length one enum
    required:
      - date_item
      - datetime_item
    properties:
      date_item:
        type: string
        format: date
        example: 2017-07-21
        enum: [2017-07-21]
      datetime_item:
        type: string
        format: date-time
        example: 2017-07-21T17:32:28Z
        enum:
          - 2017-07-21T17:32:28Z
```

##### Command line used for generation

generate -i modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -g java -c bin/java-petstore-jersey2.json -o samples/client/petstore/java/jersey2 -DhideGenerationTimestamp=true

##### Steps to reproduce

- Add the TypeHolderExample mode to the sample spec and run all generators
- Or generate the csharp or java jersey2 or python client and attempt to use them

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/1312
https://github.com/OpenAPITools/openapi-generator/issues/1299
https://github.com/OpenAPITools/openapi-generator/issues/926

##### Suggest a fix

We should add the ability to these generators to handle date and datetime enums

**Comment by spacether** [comment]
I am working on this in https://github.com/OpenAPITools/openapi-generator/pull/2297

**Comment by chikki1982** [comment]
This one is still open, do we have any update on resolution?

**Comment by spacether** [comment]
So this will having to be fixed on a generator by generator basis. Doyou wantto fix the generator thatyou need this in? Ican point youto where to start.

**Comment by chikki1982** [comment]
@spacether yes please let me know.

**Comment by spacether** [comment]
Which generator do you need it working in?

**Comment by SCSreekanth** [comment]
Hi @spacether ,
Apologies for the delayed reply. Could you please let me know specifically, what are you requesting? I didn't quite get it when you said, which generator.
Thanks,
Sree

**Comment by spacether** [comment]
We support generating code in many languages and frameworks.
Each context of generating code for x language is called a generator. Sometimes we have multiple generators for the same language for old or new versions or different frameworks.
We have docs on each of our generators here:
https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/README.md
So which generator are you interested in improving?

**Comment by SCSreekanth** [comment]
Ok. Thanks. I would be needing the fix for the Java-based generator. Thanks. HTH

**Comment by spacether** [comment]
Great; if you want to work on fixing that generator:
- its templates are located here: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/Java
- the generator functionality is in this file https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java

And some of the code that handles enums are here:
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java#L791
- https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/JavaClientCodegen.java#L763
This project is run by and build by volunteers and fixes and contributions are welcome
