### ISSUE TITLE
[BUG] using xml:wrapped:false does not generate the correct annotation

### ISSUE THREAD

**Issue by tom-mayer** [OpenAPITools/openapi-generator#2417]
Hey,

in the documentation https://swagger.io/docs/specification/data-models/representing-xml/ here it says that you can represent unwrapped lists in xml with using the xml:wrapped:false in the openapi yaml. I am using the JavaSpring generator. The xml:atttribute:[true|false] and xml:name seem to work fine, generating the correct `@JacksonXmlProperty` values. 

However using  xml:wrapped:false does not change the generated model. Jackson-Xml uses wrapping by default, so if this is set, a `@JacksonXmlElementWrapper(useWrapping = false)` should be rendered over the property to make xmls like that parsable.

Looking at the pojo.mustache `@JacksonXmlElementWrapper` is also not in there. Should be around line 27.

My question is, is this really a bug / not yet done or do I just miss something.

**Comment by thiko** [comment]
Any news here? :-/
@tom-mayer could you find a workaround (beside adding the annotation manually)?

Thanks!

**Comment by tom-mayer** [comment]
Hey @thiko . No couldn't find a good workaround here. We were in the lucky spot that we could change the API to return wrapped lists,... but that was not a very satisfying solution and for sure not applicable if you don't own the API,.. even then it's not really a preferable solution.

Cheers

**Comment by thiko** [comment]
hi @tom-mayer, thanks for your response!
great that you were able/allowed to change the API. Unfortunately, thats not possible for us. The "calling system" is fix and we really need to serve the expected output.
Our current _workaround_ is: generating the model, copy the files to another place, add the custom annotations, deactivate the model creation, delete the generated files and work with the customized "copies". Sounds stupid and.. well.. it is! ;-)

**Comment by siimp** [comment]
Same here, it seems that one of my deserialization does not work properly because of this bug. Looking forward to this fix also.

A little googeling shows that swagger codegen has JacksonXmlElementWrapper annotation generation https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaSpring/pojo.mustache#L50
but openapi tools does not https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaSpring/pojo.mustache#L48

**Comment by UnleashSpirit** [comment]
> If you're interested, I can provide a Pull Request that generates the wrapper annotations for the `JavaSpring` generator and fixes some other issues in the same area.

Hi, this topic is a bit old but i'm very interested

**Comment by Philzen** [comment]
> If you're interested, I can provide a Pull Request that generates the wrapper annotations for the `JavaSpring` generator and fixes some other issues in the same area.

@chschu that'd be dope and highly appreciated :pray: 

That would probably solve #5078 and #5764 as well.

**Comment by chschu** [comment]
There are a couple of mustache templates that generate Jackson XML annotations in generators other than `JavaSpring`. These should probably be fixed as well.

Both #5078 and #5764 would require a similar fix in `src/main/resources/Java/jackson_annotations.mustache`.
