### ISSUE TITLE
[REQ] Provide yaml support for config.json by being able to read config.yml

### ISSUE THREAD

**Issue by dragosnutu** [OpenAPITools/openapi-generator#2425]
### Is your feature request related to a problem? Please describe.

It would be great to have support to pass in config.yml file instead of config.json to generate command.

## Described solution

Instead of passing to generate, a `config.json` file using the `-c` parameter, we could pass in `config.yml`. This has multiple advantages, one of them, which is pretty important, is that we can have comments in yaml format and not in json.
Using comments would be easier to know how to configure the generate.

Also maybe a great idea would be to have also a third parameter value maybe to `config-help` for the `--format` something like `yamltemplate` generating the default config.yml file with description as comments.

## Described alternative

The alternative would be to use the old format config.json and each time we need to print the help for that/each specific language.

**Comment by wing328** [comment]
> Instead of passing to generate, a config.json file using the -c parameter, we could pass in config.yml

We definitely welcome the enhancement. Would you have time to contribute with a PR?

**Comment by dragosnutu** [comment]
Yes, I can try. I had a look on the code and it should't be that hard. The first one and the setup might be a bit harder (for me at least).

**Comment by dragosnutu** [comment]
@wing328 - please review, and guide me If something is not according to flow/contributions etc. Thank you.

**Comment by wing328** [comment]
Closed via #2434 

Thanks for the contribution by @dragosnutu

**Comment by wing328** [comment]
@dragosnutu when you've time, I wonder if you're free for a quick chat (IM) via https://gitter.im (ID: wing328). Thanks.
