### ISSUE TITLE
[BUG] packageName ignored by maven plugin

### ISSUE THREAD

**Issue by Zomzog** [OpenAPITools/openapi-generator#2428]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

packageName not used by maven plugin, infrastructure is genereted in default package.

##### openapi-generator version

3.2.2 and 4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url
Maven config
```
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<executions>
    <execution>
        <goals>
            <goal>generate</goal>
        </goals>
        <configuration>
            <inputSpec>${project.basedir}/src/main/resources/swagger.json</inputSpec>
            <generatorName>kotlin</generatorName>
            <configOptions>
                <sourceFolder>src/gen/kotlin/main</sourceFolder>
            </configOptions>
            <packageName>bzh.zomzog.utils</packageName>
            <generateSupportingFiles>true</generateSupportingFiles>
        </configuration>
    </execution>
</executions>
```

##### Command line used for generation

mvn clean install

##### Steps to reproduce

Generate a kotlin client with custom packageName

##### Suggest a fix

Add support of packageName to maven plugin

**Comment by wing328** [comment]
Have you tried putting `packageName` inside `<configOptions> ... </configOptions>`?

**Comment by Zomzog** [comment]
It works but I think it's a strange behavior because all other configurations are in the `<configuration>` level.

**Comment by wing328** [comment]
There are 2 types of options: global options vs generator-specifed options.

packageName is a generator's option (as Ruby, Perl, etc use "moduleName" instead) so it should be inside the `configOptions` block.

**Comment by q3769-patientpoint** [comment]
I just tried 7.8.0. The pacakgeName has no effect in or outside <configOptions>. Only way to change the base package is using <apiPackage>/<modelPackage>/<invokerPackage> inside the <configOptions>.
