### ISSUE TITLE
[REQ] Provide support to config-help to output sample yaml config file

### ISSUE THREAD

**Issue by dragosnutu** [OpenAPITools/openapi-generator#2442]
### Is your feature request related to a problem? Please describe.

It would be great to have support to generate `config.yml` file with default values and documentation about available options for each language.

Together with this https://github.com/OpenAPITools/openapi-generator/issues/2425 we could than easily have a template config file.

## Describe the solution you'd like

When using `config-help` cli option we now have `--format` two options. `text` and `markdown`. We could have a third option like `yamlsample` that will basically will generate yaml like format to output. Also in combination with `--output` there will be the possibility to save it and the modify it according.

## Describe alternatives you've considered

The alternative is to read documentation and manually add documentation and values to a yaml file.

## Additional context

This would easily help users to see/change available options, and also if any other options might appear or the documentation will change they can regenerate the configurations, see the differences and adjust the config easily (using git diff, or any other diff tool).

**Comment by ackintosh** [comment]
@dragosnutu Thanks for this issue. That sounds great!

**Comment by dragosnutu** [comment]
Hi @ackintosh can someone have a look on this ?

**Comment by wing328** [comment]
@dragosnutu Let me review shortly ...

**Comment by wing328** [comment]
Thanks for #2443, which has been merged into master
