### ISSUE TITLE
[REQ] Add RuboCop to Gemfile

### ISSUE THREAD

**Issue by ackintosh** [OpenAPITools/openapi-generator#2444]
## Describe the solution you'd like

I would suggest to add [Rubocop](https://github.com/rubocop-hq/rubocop) to Gemfile so that users won't need to install that globally.

```diff
group :development, :test do
   gem 'rake', '~> 12.0.0'
   gem 'pry-byebug'
+  gem 'rubocop', '~> 0.66.0'
end
```

cc Technical Committee: @cliffano (2017/07) @zlx (2017/09) @autopp (2019/02)

**Comment by wing328** [comment]
Sounds good to me


在 2019年3月19日週二 下午6:56，Akihito Nakano <notifications@github.com> 寫道：

**Comment by autopp** [comment]
@ackintosh Sounds good to me!

**Comment by ackintosh** [comment]
Thanks for the feedback @wing328 @autopp ! I'll file a PR to close this issue later today. 💪
