### ISSUE TITLE
[BUG] [Javascript] Module not found

### ISSUE THREAD

**Issue by jdorel** [OpenAPITools/openapi-generator#2450]
##### Description

When trying to build some frontend using webpack, I get the following:

```
ERROR in /home/user/api_javascript/src/index.js
Module not found: Error: Can't resolve 'ApiClient' in '/home/user/api_javascript/src'
 @ /home/juser/api_javascript/src/index.js 19:4-114
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/components/home.vue
 @ ./src/components/home.vue
 @ ./src/components lazy ^\.\/.*\.vue$
 @ ./src/router/index.js
 @ ./src/main.js
```
I also have the same error for 'api/DefaultApi' and for all my models.

I tried using the following, as written in the README.md, but nothing changes :

```javascript
module: {
  rules: [
    {
      parser: {
        amd: false
      }
    }
  ]
}
```
I also tried this: https://github.com/webpack/webpack/issues/981#issuecomment-225364774

##### openapi-generator version

4.0.0-beta2

##### OpenAPI declaration file content or url

I am not at liberty to disclose it, but I do not believe it comes from the declaration file. However, here is the generated package.json:

```json
{
  "name": "device_api",
  "version": "0.0.1",
  "description": "API_to_access_the_device",
  "license": "Unlicense",
  "main": "src/index.js",
  "scripts": {
    "test": "./node_modules/mocha/bin/mocha --recursive"
  },
  "browser": {
    "fs": false
  },
  "dependencies": {
    "superagent": "3.7.0"
  },
  "devDependencies": {
    "expect.js": "~0.3.1",
    "mocha": "^5.2.0",
    "sinon": "1.17.3"
  }
}

```

##### Command line used for generation

I'm using webpack
```shell
npm run build
```

##### Complementary informations
I know this might not be enough informations to resolve this issue, but I do not know how to get more informations (I tried using https://github.com/webpack-contrib/grunt-webpack/issues/49 without success)

**Comment by wing328** [comment]
@jdorel thanks for reporting the issue. Would the following PR help?

https://github.com/OpenAPITools/openapi-generator/pull/2439

**Comment by jdorel** [comment]
Upon updating, my webpack project wouldn't find my dependency in `node_modules`. But I don't think it comes from `openapi-generator`. I'll be sure to let you know how this evolves.
