### ISSUE TITLE
[BUG][typescript-fetch] implicit any in runtime.ts

### ISSUE THREAD

**Issue by Teyras** [OpenAPITools/openapi-generator#2461]
##### Description
The `querystring` function defined in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L186 has an implicit return type of `any`. This is a problem when using the generated client with create-react-app.

##### openapi-generator version

4.0.0-SNAPSHOT from dockerhub

**Comment by macjohnny** [comment]
would you like to file a PR for this?
