### ISSUE TITLE
[BUG][Python] Inline enums not generated

### ISSUE THREAD

**Issue by fantavlik** [OpenAPITools/openapi-generator#2495]
Related Go issue: #2360 

I've kept these issues separate because the fix appears to be at the template-level and a PR for the Go fix is up: https://github.com/OpenAPITools/openapi-generator/pull/2494

#### Bug Report Checklist

- [ x ] Have you provided a full/minimal spec to reproduce the issue?
- [ x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ x ] What's the version of OpenAPI Generator used?
- [ x ] Have you search for related issues/PRs?
- [ x ] What's the actual output vs expected output?

##### Description

Enums that are declared inline are simply being declared as strings, while the same enum defined as a separate schema is properly captured with all legal values.

##### openapi-generator version

`4.0.0-SNAPSHOT` built from this commit: https://github.com/OpenAPITools/openapi-generator/commit/b128d1470709c44c6c7b6a906e1993d1c2758b52

##### OpenAPI declaration file content or url

sample.yaml:
```yaml
openapi: "3.0.0"
info:
  version: v1
  title: Fake Service
servers:
- url: https://fake.net
paths:
  /status/details:
    get:
      summary: Get status details
      operationId: getStatus
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StatusDetails"

components:
  schemas:
    State:
      type: string
      enum:
      - "IN_PROGRESS"
      - "READY"
      - "FAILED"
    StatusDetails:
      properties:
        id:
          type: string
        stateInline: # enum not captured, just declared as "string"
          type: string
          enum:
          - "IN_PROGRESS"
          - "READY"
          - "FAILED"
        state: # works as expected
          $ref: "#/components/schemas/State"
```

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i sample.yaml -g python -o ./sample-python`

##### Steps to reproduce

1. `git clone https://github.com/OpenAPITools/openapi-generator.git`
2. `cd openapi-generator`
3. `git checkout b128d1470709c44c6c7b6a906e1993d1c2758b52`
4. `mvn clean install`
5. `ln -s modules/openapi-generator-cli/target/openapi-generator-cli.jar .`
6. `java -jar openapi-generator-cli.jar generate -i sample.yaml -g python -o ./sample-python`

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/2200
https://github.com/OpenAPITools/openapi-generator/issues/1702
https://github.com/OpenAPITools/openapi-generator/issues/1706

##### Actual vs Expected output
Python:
openapiclient/models/status_details.py (actual, abbreviated):
```python
...
class StatusDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'state_inline': 'str',
        'state': 'State'
    }
```

openapiclient/models/status_details.py (expected, abbreviated):
```python
...
class StatusDetails(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'state_inline': 'StateInlineEnum',
        'state': 'State'
    }
```

##### Suggest a fix

The fix needs to be adding enum definitions to the templates similar to the `typescript-fetch` templates which implement this correctly: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache#L92-L109

**Comment by spacether** [comment]
Inline enums value are defined in the generators
- python see the [Order.status values](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/order.py#L59)
- python-experimental see the [Order.status class definition](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/model/order.py#L98)
