### ISSUE TITLE
Add CodegenProperty.nameInSnakeCase

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#25]
Raised in #22, it would be nice to have `CodegenProperty.nameInSnakeCase`similar to `CodegenProperty.nameInCamelCase`.

Example:

| baseName | nameInSnakeCase |
|---|---|
| `petId` | `PET_ID` |
| `name` | `NAME` |
| `some_value` | `SOME_VALUE` |

When this feature is implemented, #21 can be changed to be conform to the java naming convention.

**Comment by jimschubert** [comment]
@jmini It may be good to also include a snake case mustache lambda for usage in templates as well. See https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/mustache

There are sometimes differences between assumptions made in base language classes that don't apply to all frameworks (or even all versions of the same framework), and we can work around these differences using the above lambdas. This allows better extension by users with custom templates.

**Comment by jmini** [comment]
First step: #42
I will look at the mustache lambda in a separated PR.

**Comment by jmini** [comment]
Second step (mustache lambda): #91 contributed by @viclovsky. Thank you a lot!
