### ISSUE TITLE
[gradle] Prior to 4.0 release, document gradle plugin portal

### ISSUE THREAD

**Issue by jimschubert** [OpenAPITools/openapi-generator#2505]
##### Description

To avoid confusion for the remainder of 4.0.0-SNAPSHOT, we won't add documentation about the upcoming publish to Gradle's Plugin Portal. Only release artifacts will be published here. Snapshot artifacts can still be consumed from Sonatype.

We'll want to update docs and the gradle plugin's README with details.

##### openapi-generator version

4.0.0-SNAPSHOT

Below is a rough draft of additional details:
---

The Gradle Plugin, `org.openapi.generator`, will be available from the Gradle Plugin Portal beginning with version 4.0.0.

This allows for simplified usage via the [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block).

## Groovy (build.gradle)

```groovy
plugins {
  id "org.openapi.generator" version "4.0.0"
}
```

## Kotlin (build.gradle.kts)

```kotlin
plugins {
  id("org.openapi.generator") version "4.0.0"
}
```

## Legacy

```groovy
buildscript {
  repositories {
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  dependencies {
    classpath("gradle.plugin.org.openapitools:openapi-generator-gradle-plugin:4.0.0")
  }
}

apply(plugin = "org.openapi.generator")
```

## Snapshots

```groovy
buildscript {
  repositories {
        maven {
            url "https://oss.sonatype.org/content/repositories/releases/"
        }
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots/"
        }
  }
  dependencies {
    classpath("gradle.plugin.org.openapitools:openapi-generator-gradle-plugin:4.0.0-SNAPSHOT")
  }
}

apply(plugin = "org.openapi.generator")
```

**Comment by wing328** [comment]
I believe this is done: https://plugins.gradle.org/plugin/org.openapi.generator

**Comment by jimschubert** [comment]
@wing328 I've added to the docs in linked PR. I don't think we need to document SNAPSHOT usage.
