### ISSUE TITLE
[BUG] Generating Java Client produces NULLUNIQUENAME.java classes

### ISSUE THREAD

**Issue by ncroma** [OpenAPITools/openapi-generator#2516]
##### Description

By generating a Java Client using the yaml file posted below, I get a NULLUNIQUENAME.java as the model class for the LoginApi.java method's request-body parameter - `login(List<NULLUNIQUENAME> NULLUNIQUENAME)` - instead of a InlineObject.class.

##### openapi-generator version

I'm using the docker command posted bellow, I would assume it is using the last generator version.

##### OpenAPI declaration file content or url

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: My Api
tags:
  - name: login
paths:
  /api/login:
    post:
      operationId: login
      summary: Logs in
      tags:
        - login
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  prop:
                    type: string
servers:
  - url: http://localhost:3000/
```

##### Command line used for generation

I'm using this docker command:
`docker run --rm -v %cd%/api:/output -v %cd%:/local openapitools/openapi-generator-cli generate -i /local/oas-doc.yaml -g java -o /output`

**Comment by Zomzog** [comment]
@wing328 can we close this issue?
