### ISSUE TITLE
ModelUtils.getUnusedSchemas reports simple model from array types as unused

### ISSUE THREAD

**Issue by jimschubert** [OpenAPITools/openapi-generator#252]
##### Description

Found in #251

##### openapi-generator version

3.0.0

##### OpenAPI declaration file content or url

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Command line used for generation

n/a (not a generation bug)

##### Steps to reproduce

Discovered while testing #251.

On that branch:

```
mvn clean install
cd modules/openapi-generator-gradle-plugin/
./gradlew assemble publishToMavenLocal
./gradlew --build-file=samples/local-spec/build.gradle generateGoWithInvalidSpec
```

##### Related issues/PRs

* #251

##### Suggest a fix/enhancement

ModelUtils.getUnusedSchemas calls into visitOpenAPI, and `visitOpenAPI` needs to account for multiple levels of nested arrays, enums, map structures, and polymorphic types.

**Comment by jmini** [comment]
Thank you a lot!

> ModelUtils.getUnusedSchemas calls into visitOpenAPI, and visitOpenAPI needs to account for multiple levels of nested arrays, enums, map structures, and polymorphic types.

This is absolutely correct.

**Comment by jmini** [comment]
I have started something to fix it: #253

**Comment by jmini** [comment]
> ModelUtils.getUnusedSchemas calls into visitOpenAPI, and visitOpenAPI needs to account for multiple levels of nested arrays, enums, map structures, and polymorphic types.

@jimschubert : what have you in mind with "enums"? I have looked at the spec, but I did not find where you can use/reference a Schema.

**Comment by jimschubert** [comment]
@jmini here's an example of an OpenAPI 2.0 spec with a top-level enum of weekdays. https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/integrationtests/csharp/general/enum-support-spec.json#L35

I only skimmed ModelUtils.getUnusedSchemas for a few seconds to present the list of what I felt might be missing. I noticed it was inspecting items, but it didn't look like it was evaluating nested children which might refer to top-level enums. Similar to logic that is there, I think it would have to be done for inputs, outputs, and other response models (like errors).

**Comment by jmini** [comment]
@jimschubert thank you a lot for your reply.

Enum models are exactly like other models in the `definitions` section (or schema and `components/schema` section in the OAS3 terminology), I have already an example in the Unit test:

https://github.com/OpenAPITools/openapi-generator/blob/ebaa7021a413497442dda0897ee961331ca98814/modules/openapi-generator/src/test/resources/3_0/unusedSchemas.yaml#L251-L256

I am glad you gave this precision, because I was afraid to miss something.

Let me finish #253 and I hope I will have all cases.
