### ISSUE TITLE
[BUG][Javascript] JS Generator Fails with NullPointerException if info.version is empty

### ISSUE THREAD

**Issue by sarod** [OpenAPITools/openapi-generator#2523]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Javascript Generator fails with NullPointerException if info.version is empty string

##### openapi-generator version

4.0.0-beta2

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: ""
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A paged array of pets
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pets"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"    
components:
  schemas:
    Pet:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Pets:
      type: array
      items:
        $ref: "#/components/schemas/Pet"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

```

##### Command line used for generation

Using petstore.yaml as defined above run
`openapi-generator generate -i ./petstore.yaml -g javascript`

##### Steps to reproduce

Using petstore.yaml as defined above run
`openapi-generator generate -i ./petstore.yaml -g javascript`

The execution faisl with
```java
Exception in thread "main" java.lang.NullPointerException
	at org.openapitools.codegen.languages.JavascriptClientCodegen.escapeQuotationMark(JavascriptClientCodegen.java:1164)
	at org.openapitools.codegen.languages.JavascriptClientCodegen.preprocessOpenAPI(JavascriptClientCodegen.java:283)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:181)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:890)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:354)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

##### Related issues/PRs
No similar issue found

**Comment by wing328** [comment]
@sarod thanks for reporting the issue. The problem has been fixed via https://github.com/OpenAPITools/openapi-generator/pull/2553

Please give it a try with the latest master.
