### ISSUE TITLE
[BUG] Validation reports error with $ref parameters

### ISSUE THREAD

**Issue by raubel** [OpenAPITools/openapi-generator#2525]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Validation seems to report false errors about path parameters using $ref.

##### openapi-generator version

4.0.0-beta2

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
servers:
- url: http://localhost:10080/semarchy/api/rest
info:
  version: ""
  title: Data Management
  description: This API allows to programmatically consume data...
security:
- basicAuth: []
paths:
  /query/ProductRetail/Family/GD/{record-id}:
    get:
      parameters:
      - $ref: '#/components/parameters/record-id'
      responses:
        200:
          description: Record content
components:
  parameters:
    record-id:
      name: record-id
      description: ID of the record to query
      required: true
      schema:
        type: string
      in: path
```

##### Command line used for generation

```
openapi-generator validate -i data.yaml
```
##### Steps to reproduce

See output below:
```
$ npm install @openapitools/openapi-generator-cli@cli-3.3.4 -g
/home/me/.nvm/versions/node/v8.10.0/bin/openapi-generator -> /home/me/.nvm/versions/node/v8.10.0/lib/node_modules/@openapitools/openapi-generator-cli/bin/openapi-generator
+ @openapitools/openapi-generator-cli@0.0.8-3.3.4
updated 1 package in 0.365s
$ openapi-generator validate -i data.yaml 
Validating spec (data.yaml)
No validation issues detected.
$ npm install @openapitools/openapi-generator-cli -g
/home/me/.nvm/versions/node/v8.10.0/bin/openapi-generator -> /home/me/.nvm/versions/node/v8.10.0/lib/node_modules/@openapitools/openapi-generator-cli/bin/openapi-generator
+ @openapitools/openapi-generator-cli@0.0.8-4.0.0-beta2
updated 1 package in 0.393s
$ openapi-generator validate -i data.yaml 
Validating spec (data.yaml)
Errors:
	-attribute paths.'/query/ProductRetail/Family/GD/{record-id}'. Declared path parameter record-id needs to be defined as a path parameter in path or operation level

[error] Spec has 1 errors.
```

##### Related issues/PRs

(maybe) https://github.com/OpenAPITools/openapi-generator/issues/2030

**Comment by wing328** [comment]
Please use `--skip-validate-spec` for the time being before we update project to use a newer version of the parser, which may better handle this particular case.

**Comment by raubel** [comment]
OK, thanks.
But in my case, I do want to validate my specification (to check my specification keeps valid upon changes).
I will wait for the next version.

**Comment by wing328** [comment]
I tested with the latest master (using the upgraded parser) and no longer see the issue. Please give it a try.

**Comment by project-ang** [comment]
Note - I was using yaml file defined in OAS 3.0.0, using 7.4.0 open apo generator cli for Java facing issue when we pointing definition using ref parameter

**Comment by project-ang** [comment]
> I tested with the latest master (using the upgraded parser) and no longer see the issue. Please give it a try.

I tested using latest open api cli generator 7.4.0 for Java, still the ref not works it says undefined
