### ISSUE TITLE
[REQ] Kotlin Spring Server Generator: adopt the pattern used by Java Spring Server generator

### ISSUE THREAD

**Issue by mikezx6r** [OpenAPITools/openapi-generator#2526]
Currently, the Kotlin Spring Server generator produces a Controller that calls a 'delegate' service. The controller code assumes that the delegate service will either return successfully, OR throw an exception. 

This means no custom validation of input or pre-processing can be performed in the Controller class, AND that the service MUST use exception handling for all error situations.

The Java Spring server generator creates a Controller interface that has an `_` prefixed method for the RequestMapping and parameter annotations and then calls a method that has a default implementation. This method makes no assumptions about the result as it returns a ResponseEntity.

The server code then inherits the interface, and overrides the method. This allows the Controller to do request data validation and formatting as well as not be forced to use Exceptions for error handling.

@dr4ke616 Would you be open to an update to the Kotlin spring Server generator that utilizes this pattern rather than the existing one?

It obviously would be a breaking change for anyone using the generator now.

If not, then I'll have to decide if I submit a new one, or merely create a custom one, or continue using the Java one. Don't like the latter option as it means I don't get the benefit of nullability being properly generated in model objects and Controller functions.

**Comment by fj-roman** [comment]
Releated to https://github.com/OpenAPITools/openapi-generator/pull/3050

**Comment by massimosiani** [comment]
Hi, I was opening the exact same issue.
I did some work in this branch https://github.com/massimosiani/openapi-generator/tree/feature/kotlin-spring-delegate-pattern, but something is still missing (reactive for instance).
Would you like to give me some feedback?
I'd like to submit a PR in a few days.
Thanks!

**Comment by mikezx6r** [comment]
I've begun looking at your PR, and provided a couple minor comments on it, but it doesn't close this ticket. I'm not 100% sure what you are adding as I haven't dug in real deep, but it is a different approach to what I desire.

My scenario would only have the interface for the Controller. This interface would have 2 methods defined for each operation.

The first method, `fun _getContact(id: Int): ResponseEntity<Any> = getContact(id)` would have the appropriate Api annotations on the function AND the parameters. It also has to return `ResponseEntity<Any>` to allow for multiple return types from the controller. In my services, I leverage Arrow, and Either so that the Controller returns for all successes, where that includes warnings/errors back to the client. 

The only time I use exceptions are for unexpected, exceptional situations.

The interface would also have a `fun getContact(id: Int):ResponseEntity<Any> = throw IllegalStateException("Not implemented yet")`

The code then just has to extend the Controller, and override the `getContact` function to process the request, and return the reply.

And just in case you don't already know, we need the `_getContact` function as annotation on method/function parameters are not inherited in Java/Kotlin, so those would not be visible to Spring.

**Comment by fj-roman** [comment]
@mikezx6r can you please provide an example for the spec. How do you want to define the ResponseEntity **Any** ?

**Comment by mikezx6r** [comment]
My services either have a SuccessResponse, which has a `data` and a ` notifications` property, where `data` is mandatory. 
For ErrorResponse, `data` is nullable, and `notifications` can't be empty. In other words, the Controller function can return 2 different objects, hence the actual requirement that the ResponseEntity be an `Any`, and not a specific type.

For the custom generator I created, I put the responseType value as a comment on the function so that at least it appeared somewhere for defining the implementation, and knowing what type should be created for the 'success' path.

It's not ideal, and I haven't had much feedback on my approach internally, hence me not formalizing it yet as a PR. But appreciate thoughts if this seems like something you'd also like to have.

**Comment by fj-roman** [comment]
I think about the drawbacks. You are losing type safety! Spring handles Error Responses with ControllerAdvices and ExceptionHandler. Sorry, but I don't understand any advantage to avoid expected Exceptions.

**Comment by mikezx6r** [comment]
I prefer explicit error/validation handling from business logic, and return values that reflect this over the 'goto like' approach of using Exceptions for error/validations AND Exceptional situations.

Yes, I give up a bit of type safety in the Controller, but strictly speaking, ResponseEntity<Any> is the truest representation as Java/Kotlin don't support some form of `OR` typing so that I could be more explicit.

It's a design/architecture choice, more FP like, and not for everyone. That is part of the reason I have not bothered trying to contribute my plugin, but instead have kept it locally.

Regardless, I still prefer the generator to create an interface that encapsulates the 'delegate' internally, so I only have to code a Controller that implements the interface. The interface has the function with all the Spring annotations for parameters and the request. I prefix it with `_` to indicate it should really be referenced/called.
The `_` function calls a function of the same name that indicates it is not implemented yet (I have it throw an exception). 

The dev then creates a Controller that extends the interface, and overrides the function to provide the functionality. Less code, and less confusing than the Delegate interface injection approach currently used.

And I wonder if the interface should be a class instead? Then the `_` function could be made private. Unless of course that breaks Spring's analysis, and ability to find, the function. Haven't tested that thought.

**Comment by mikezx6r** [comment]
Sorry I'm late to the party, but the PR does not close this ticket. It provides a delegate interface that must be implemented by code, which is not what I was hoping for. I did mention it in my comment above, but I think it got lost in the discussion around typing.

What I'm looking for is something like this for a CustomerApi.

```
interface CustomerApi {
     @Mapping("/customers/{id}")
     @JvmDefault
     internal fun _getCustomer(@PathParam("id") val id:Int): ResponseEntity<Customer> {
               return getCustomer(id)
     }

     fun getCustomer(val id: Int): ResponseEntity<Customer> {
              return ResponseEntity.notFound(null)
     }
```

The idea is that one would create a CustomerController that extends CustomerApi, and overrides the functions that don't start with `_`. 

The indirection/'delegate' is required as function/method parameter annotations are not inherited in Java.

Please re-open this ticket, and I'll try to find some time to implement what I'm after.

Also in the accepted PR, there were a couple comments I added that weren't addressed, and therefore I believe the generated Kotlin code will be using the Java Optional class.
