### ISSUE TITLE
[BUG][typescript-angular] Incorrect import path when using prefix/suffix for model names

### ISSUE THREAD

**Issue by jahow** [OpenAPITools/openapi-generator#2560]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating code for the `typescript-angular` language and specifying either `--model-name-prefix` or `--model-name-suffix`, the paths used for importing models are wrong (missing said prefix/suffix).

Using the spec & command given below, a model file called `model/testSchema.ts` is generated,:
```typescript

/**
 * blah
 */
export interface TestSchemaModel { 
    description?: string;
    creationDate?: Date;
    code?: string;
}
```

The import for this model in  `api/default.service.ts` is as follow:
```typescript
...

import { TestSchemaModel } from '../model/testSchemaModel';

...
```

The path is wrong and should be `../model/testSchema` (or alternatively the name of the model file is wrong).

##### openapi-generator version

`master` and `4.0.0-beta2`.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: Sample API
  version: "1.0.0"
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

paths:
  /TestSchema/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
    get:
      operationId: find
      responses:
        200:
          description: returns something
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestSchema'

components:
  schemas:

    TestSchema:
      description: blah
      allOf:
        - type: object
          properties:
            description:
              type: string
            creation_date:
                type: string
                format: 'date-time'
            code:
              type: string
```

##### Command line used for generation

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i schema.yaml -g typescript-angular -o testoutput --model-name-suffix=model
```

##### Related issues/PRs

* https://github.com/OpenAPITools/openapi-generator/issues/234 and https://github.com/OpenAPITools/openapi-generator/pull/418
* https://github.com/OpenAPITools/openapi-generator/issues/957

##### Suggest a fix

I've looked into the source code but have not yet found what would be the cause of this behaviour. Will create a PR if I ever find a fix for this on my own (if that's okay?).

Thanks a lot for this great project!

**Comment by macjohnny** [comment]
@jahow a PR with a fix is highly appreciated. 
I guess the starting point is here:
https://github.com/OpenAPITools/openapi-generator/blob/5a34f8428c01fd8b9fad51c00418421e5d47aedb/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L503-L504
which is then imported here
https://github.com/OpenAPITools/openapi-generator/blob/5a34f8428c01fd8b9fad51c00418421e5d47aedb/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L27-L29

Moreover, the `removeModelSuffixIfNecessary()`  should also handle prefixes.
