### ISSUE TITLE
Query String parameter named 'configuration' conflicts with the api configuration in the generated typescript-fetch client.

### ISSUE THREAD

**Issue by fuzzzerd** [OpenAPITools/openapi-generator#2564]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Query String parameter named 'configuration' conflicts with the api configuration in the generated typescript-fetch client. Here is a sample of the problem:

```ts
/**
 *  - fetch parameter creator
 * @export
 */
export const ControllerApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         */
        getControllers(skip?: number, take?: number, controllerId?: string, configuration?: string, options: any = {}): FetchArgs {
            const localVarPath = `/api/Controller`;
            const localVarUrlObj = url.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions; // note this conflicts with line 5 parameter
            }
            const localVarRequestOptions = Object.assign({ method: 'GET' }, baseOptions, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication oauth2-clientCred required
            // oauth required
            if (configuration && configuration.accessToken) { // note this conflicts with line 5 parameter
				const localVarAccessTokenValue = typeof configuration.accessToken === 'function' 
					? configuration.accessToken("oauth2-clientCred", ["scope1", "scope2", "scope3"])
					: configuration.accessToken; // note this conflicts with line 5 parameter
                localVarHeaderParameter["Authorization"] = "Bearer " + localVarAccessTokenValue;
            }

```

##### openapi-generator version

v3.3.4

##### OpenAPI declaration file content or url

I don't have one available that I can share; however, it occurs anytime a any parameter is named 'configuration' since that conflicts with the internal client configuration object.

##### Command line used for generation

java -jar openapi-generator-cli.jar generate -i "https://example.com/swagger/v1/swagger.json" -o "C:\Source\Project\src\api" -g typescript-fetch -D withInterfaces=true

##### Steps to reproduce

Linting/Transpile error when trying to build generated api.ts file (even with //tslint:disable)

##### Suggest a fix

Rename internal 'configuration' parameter to something a bit more specific and less likely to conflict with other api parameter names. Ex: `tsFetchClientConfiguration` or similar.

**Comment by macjohnny** [comment]
you could add this to the reserved keywords:

https://github.com/OpenAPITools/openapi-generator/blob/0889b8ec1349d6f912ad7dfa221d3980f1801dba/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptFetchClientCodegen.java#L251-L255

**Comment by fuzzzerd** [comment]
@macjohnny I don't know if thats the problem, I think the issue is that the variable defined in the BaseAPI conflicts with the parameter of the action.

https://github.com/OpenAPITools/openapi-generator/blob/2353d71d4b02be6dbabe25aac1a9e56eb3b812a2/modules/openapi-generator/src/main/resources/typescript-fetch/api.mustache#L47 

I think its an issue in the template?

**Comment by macjohnny** [comment]
the issue in the template arises due to local variables with the same name. this can be prevented by adding `configuration` to the reserved words, leading to an automatic rewrite of the parameter variable name.

**Comment by fuzzzerd** [comment]
Would you like me to open a pull request with that add? What branch should I start with?

**Comment by macjohnny** [comment]
You can open a branch from master, make the changes, compile and check this actually resolves the issue.
