### ISSUE TITLE
[BUG][typescript-angular] Cannot redeclare block-scoped 

### ISSUE THREAD

**Issue by BenjaminHae** [OpenAPITools/openapi-generator#2581]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When trying petstore with the generator for typescript-angular, actually using the generated code leads to compiler errors.

##### openapi-generator version

openapitools/openapi-generator-cli:latest 

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml

##### Command line used for generation
```
docker run --user 1000:1000 --rm -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g typescript-angular -o /local/OpenAPIAngularClient --additional-properties npmName=@test/test
```

##### Steps to reproduce

Run `npm install && npm run build` in directory of code generated.
Create a new angular project `ng new testAngular`.
Run `npm install /tmp/OpenAPIAngular` to add the module.
Configuring app.module.ts as described in the README:
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { HttpClientModule } from '@angular/common/http';
import { ApiModule, BASE_PATH } from '@test/test';

import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    HttpClientModule,
    ApiModule,
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```
Then **building fails**:
```
$ ng build
[...]
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/@test/test/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
```

Angular version is
```
$ ng --version
[...]
Angular CLI: 7.1.4
Node: 11.12.0
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

**Comment by macjohnny** [comment]
This seems to be due to different angular installations, see https://github.com/angular/angular/issues/21670#issuecomment-359752703

When installing the generated api npm package, maybe you accidentally installed the devdependencies?
Delete the „node_modules“ folder and re-install again, without devdependencies

**Comment by BenjaminHae** [comment]
Which one? The one in the generated code?

**Comment by macjohnny** [comment]
@BenjaminHae 
Please check the content of `node_modules/@test/test/node_modules` first. there should not be `@angular/core`
I would first try deleting `node_modules/@test/test/node_modules`.
However, ensure that your `package-lock.json` will produce the same state, s delete `node_modules` and run `npm-install` and see what happens

**Comment by BenjaminHae** [comment]
Thank you! That pointed me in the right direction. The problem was that I ran `npm install` in the directory of the generated code.
Now I get the error
```
Error: /tmp/OpenAPIAngularClient/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

I guess some instruction in the generated README is not completely right.

**Comment by macjohnny** [comment]
What are the files in your „node_modules/@test/test“?

**Comment by BenjaminHae** [comment]
```
user@debian:/tmp/test2/node_modules/@test/test$ ls -la
insgesamt 72
drwxr-xr-x  5 user user 4096 Apr  3 17:47 .
drwxrwxrwt 18 root      root      4096 Apr  3 18:16 ..
drwxr-xr-x  2 user user 4096 Apr  3 17:47 api
-rw-r--r--  1 user user 1207 Apr  3 17:47 api.module.ts
-rw-r--r--  1 user user 3089 Apr  3 17:47 configuration.ts
-rw-r--r--  1 user user  543 Apr  3 17:47 encoder.ts
-rw-r--r--  1 user user   39 Apr  3 17:47 .gitignore
-rw-r--r--  1 user user 1662 Apr  3 17:47 git_push.sh
-rw-r--r--  1 user user  150 Apr  3 17:47 index.ts
drwxr-xr-x  2 user user 4096 Apr  3 17:47 model
-rw-r--r--  1 user user  112 Apr  3 17:47 ng-package.json
drwxr-xr-x  2 user user 4096 Apr  3 17:47 .openapi-generator
-rw-r--r--  1 user user 1040 Apr  3 17:47 .openapi-generator-ignore
-rw-r--r--  1 user user  953 Apr  3 17:47 package.json
-rw-r--r--  1 user user 4003 Apr  3 17:47 README.md
-rw-r--r--  1 user user  659 Apr  3 17:47 tsconfig.json
-rw-r--r--  1 user user   92 Apr  3 17:47 typings.json
-rw-r--r--  1 user user  219 Apr  3 17:47 variables.ts
```

**Comment by macjohnny** [comment]
then I don't understand which part of your code references `/tmp/OpenAPIAngularClient/index.ts`

**Comment by macjohnny** [comment]
you should have `import { ... } from "@test/test"`

**Comment by BenjaminHae** [comment]
`/tmp/test2/node_modules/@test` is a symlink to `/tmp/OpenAPIAngularClient/` as I've installed the package locally.
You can see in my first post, that it's indeed 
```
import { ApiModule, BASE_PATH } from '@test/test';
```

**Comment by macjohnny** [comment]
`/tmp/test2/node_modules/@test/test` should be a symlink to `/tmp/OpenAPIAngularClient/`

**Comment by BenjaminHae** [comment]
sorry - my mistake. it is like you said.

**Comment by macjohnny** [comment]
Can you try without symlink, i.e. copy the content of api package directly to the `/tmp/test2/node_modules/@test/test` path? Angular cli had some issues with symlinks

**Comment by BenjaminHae** [comment]
Still the same :/

**Comment by BenjaminHae** [comment]
Would you mind trying to reproduce it?
I want to make sure it's not something weird on my side.

**Comment by BenjaminHae** [comment]
I finally got it working by copying the generated build into the node_modules folder. It only worked now although I tried it earlier... but maybe I just used the folder with the generated code, not the result of the build...
