### ISSUE TITLE
[REQ] Using black as an auto-formatter for the Python generated code

### ISSUE THREAD

**Issue by timonbimon** [OpenAPITools/openapi-generator#2584]
I think black is well on its way to become the default Python code formatter.
It would be awesome to have the client generated code in Python auto-formatted by black. :)
https://github.com/ambv/black

**Comment by wing328** [comment]
@timonbimon thanks for the suggestion.

I think it's already doable using the file post-processing hook when generating Python client/server code. Have you tried that?

**Comment by timonbimon** [comment]
oh awesome, no i was not aware of that, i'll have a look right away!

**Comment by wing328** [comment]
👌  Let us know if you need help on that.

**Comment by Anurag-Pola** [comment]
Hey there, I was trying to understand how to use the post processing hook, but got stuck, is there any place where I can see an example of the post processing for python-flask using gradle

Thank you in advance!
