### ISSUE TITLE
[REQ] [Swift] Property naming policy

### ISSUE THREAD

**Issue by SergeyPetrachkov** [OpenAPITools/openapi-generator#2589]
### Problem description

The current generator changes `id` and `description` properties to `_id` and `_description`.
But why `_id` for simple structs? Neither `id` nor `description` are reserved words for Swift. I mean some might say that these particular models can be reused as an Entity layer of the app and there might be a conflict with other frameworks, but others will say (me too) that it's wrong and server layer must use it's own entities, app layers must use it's own. So there's no big point in using `_id` here. 

As far as I can see [from here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/Swift4Codegen.java) you use underscore for Objective-C compatibility. But is there any real point in it? There's objc generator for it. 

## Possible way to resolve this

Is it possible to maybe make objc compatibility an optional parameter for generator? If one wants to keep compatibility one will have to pass something like -objcCompatible.

**Comment by SergeyPetrachkov** [comment]
P.S. while swift3 is deprecated and swift4 generator produces valid code for swift5, would it not be better to just rename it to `swift` and remove redundant codes?

**Comment by wing328** [comment]
> P.S. while swift3 is deprecated and swift4 generator produces valid code for swift5, would it not be better to just rename it to swift and remove redundant codes?

I think we'll keep the current strategy to name the swift generator with the version as I think such strategy works pretty well for Swift, which releases a major new version regularly.

**Comment by wing328** [comment]
> As far as I can see from here you use underscore for Objective-C compatibility. But is there any real point in it? There's objc generator for it.

My guess is that maybe the developers want to use the same Swift SDK in both ObjC and Swift App for easier maintenance.

**Comment by wing328** [comment]
> Is it possible to maybe make objc compatibility an optional parameter for generator? If one wants to keep compatibility one will have to pass something like -objcCompatible.

There's already an option for Objective-C compatibility:
```
	objcCompatible
	    Add additional properties and methods for Objective-C compatibility (default: false)
```

Have you tried it?

**Comment by SergeyPetrachkov** [comment]
objc compatibility is disabled by default, yet `_id` and `_description` are there

**Comment by wing328** [comment]
@SergeyPetrachkov I've filed https://github.com/OpenAPITools/openapi-generator/pull/2632 to fix the issue. Please have a look at the fix when you've time.
