### ISSUE TITLE
3.0.1 patch release postponed to Jun 11th (Monday)

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#259]
##### Description

We would like to postpone 3.0.1 patch release to coming Monday (Jun 11th) as Sonatype has better support on weekday (faster response time) so we can reach out to them in case we need help as we try to automate the release process.

Sorry for the short notice.

(the original release date is Jun 9th, Sat)

##### openapi-generator version

3.0.1

**Comment by jmini** [comment]
Released: https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.0.1
