### ISSUE TITLE
[BUG] Typo in Wiki FAQ

### ISSUE THREAD

**Issue by arnolde** [OpenAPITools/openapi-generator#2620]
In https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#android the last parameter for listing the available http clients should be "-g java", not "-l java"

Full line:
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar config-help -g java
```

**Comment by wing328** [comment]
@arnolde just fixed it by replacing all "-l " with "-g ". Thanks for reporting the issue
