### ISSUE TITLE
[REQ] Option to disable stripping of common enum prefix

### ISSUE THREAD

**Issue by jvs64893** [OpenAPITools/openapi-generator#2624]
### Is your feature request related to a problem? Please describe.

This is related to the following issue:
swagger-api/swagger-codegen-generators#246

If you have Enums with a common prefix this is currently stripped and there is no way to stop the generator from doing so.

## Describe the solution you'd like

There should be an option to disable this behavior.

**Comment by jkuipers** [comment]
I'm amazed that this hasn't been fixed yet: this "feature" is completely unwanted, and should at the least be optional (it should be disabled by default). 
It would be nice to get an update here on a) whether this will be addressed and b) if so, when a release containing the fix will be available.

**Comment by johnflanigan** [comment]
I encountered this also and am going to try to address it.

**Comment by spyro2000** [comment]
Lead also to major trouble for us and broke deserialization. Seriously, WHY?
