### ISSUE TITLE
Investigate Java 9+ support

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#263]
This issue tracks effort around Java 9+ (current java version is Java 10).

---

OpenAPI generator should run on Java 9+ on the classpath (modulepath could also be investigated, but It probably requires more work).

Keeping Java 8 minimal java version seems to be a good idea for the moment.

**CI:** Some CI Jobs should run on Java 9+.

For generated java code (jaxrs, spring, java clients, ...) we should ensure that the generated code also run on Java 9+. Generated code is probably impacted by java ee modules removal from Java SE in java 9+ (see [Dependencies on JavaEE modules](https://blog.codefx.org/java/java-9-migration-guide/#Dependencies-On-Java-EE-Modules)).

**Comment by wing328** [comment]
The project is now buildable with JDK9 via https://github.com/OpenAPITools/openapi-generator/pull/1188

**Comment by wing328** [comment]
I think this can be closed.
