### ISSUE TITLE
[BUG][WIKI] deprecated option `-l` is used in sample code in wiki page

### ISSUE THREAD

**Issue by yuji38kwmt** [OpenAPITools/openapi-generator#2659]
# Description
There is following sample code in wiki page. 
https://github.com/OpenAPITools/openapi-generator/wiki/Mustache-Template-Variables

```
java -DdebugModels -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l csharp \
```

The `-l` option is deprecated in v3.3.4, so I want to modify `-l` to `-g`.

```
java -DdebugModels -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -g csharp \
```

# openapi-generator version
 openapi-generator-cli v3.3.4

**Comment by wing328** [comment]
@yuji38kwmt thanks for reporting the issue. I've updated the wiki page accordingly.

**Comment by yuji38kwmt** [comment]
Thanks!
