### ISSUE TITLE
[BUG] go-server generating issue

### ISSUE THREAD

**Issue by unipark00** [OpenAPITools/openapi-generator#2661]
When I tried to generate go-server stubs w/ openapi3.0 yaml, I found that package name was missing at the source codes.

```
# ~/open-api/openapi-generator/samples/openapi3/server/petstore/go-server$ (master) grep -rn package
main.go:10:package main
go/model_tag.go:10:package
go/model_order.go:10:package
go/routers.go:10:package 
go/model_inline_object_1.go:10:package
go/api_pet.go:10:package
go/api_store.go:10:package
go/logger.go:10:package
go/model_inline_object.go:10:package
go/api_user.go:10:package
go/model_category.go:10:package
go/model_pet.go:10:package
go/model_api_response.go:10:package
go/model_user.go:10:package
```

When I exeucted server, some error occurred.

main.go:23:2: 
go/api_pet.go:12:1: expected 'IDENT', found 'import'

      1 /*
      2  * OpenAPI Petstore
      3  *
      4  * This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.
      5  *
      6  * API version: 1.0.0
      7  * Generated by: OpenAPI Generator (https://openapi-generator.tech)
      8  */
      9 
     10 package
     11 
     12 import (
     13         "net/http"
     14 )

**Can you tell me how to specifiy the package name on the generation?**

I used the usage, and changed into newer version (swagger-codegen-cli -> swagger-codegen-cli).

[ New Version ]
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
  -i petstore.yaml \
  -g go-server \
  -o samples/server/petstore/go-server
```

[ Old Version ]
```
https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#go-server
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i http://petstore.swagger.io/v2/swagger.json \
  -l go-server \
  -o samples/server/petstore/go-server
```

**Comment by wing328** [comment]
Please add `-DpackageName=petstoreserver` to specify the package name as a workaround for the time being.

**Comment by wing328** [comment]
@unipark00 I've filed #2662 to fix it. Thanks for reporting the issue.

**Comment by wing328** [comment]
The fix has been merged into master. Please give it another try when you've time.
