### ISSUE TITLE
[C++] Addition of a server for Qt5

### ISSUE THREAD

**Issue by etherealjoy** [OpenAPITools/openapi-generator#268]
I have been using the generated models from the Qt5 Client for integration with this [qhttp server](https://github.com/azadkuh/qhttp) 

With Qt6 on the radar coming with integrated server functionality does it makes sense to have a server at this moment?

@MartinDelille @stkrwork @ravinikam

**Comment by stkrwork** [comment]
There is the option to do both, one with QT6 and one with QHttp. Then a developer can choose between the two. Another C++ Server could be useful, so Users can have another option besides Restbed and Pistache.

**Comment by MartinDelille** [comment]
Personally I use Qt only for the client.

**Comment by etherealjoy** [comment]
@stkrwork 
I think [qhttp server](https://github.com/azadkuh/qhttp) would be a good candidate 


We can reuse all client templates from cpp-qt5 for the models
Main thing is to wire the request via a router to the model and handling the callback to how pistache is doing.
But from what I see Qt5 with qhttp can do it more eloquently.
what do you think?

**Comment by etherealjoy** [comment]
Another option would be [qhttpengine](https://github.com/nitroshare/qhttpengine)

**Comment by etherealjoy** [comment]
I just read on phoronix that Qt6 is far away, I think we could just give one of these http engines a try.

**Comment by etherealjoy** [comment]
Integrated with #322
