### ISSUE TITLE
[BUG] Dart code generator does not support date format for string

### ISSUE THREAD

**Issue by dalewking** [OpenAPITools/openapi-generator#2696]
##### Description

The dart code generator does support date-time format for strings, making the parameter type DateTime and formatting it correctly. However if the format for a string is "date" it also uses DateTime for the parameter, but it does not format it correctly as it includes the time in the formatted version.

##### openapi-generator version

4.0.0-beta3

**Comment by wing328** [comment]
> DateTime for the parameter, but it does not format it correctly as it includes the time in the formatted version.

So the correct solution is still using DateTime but with a different datetime format, right?

**Comment by dalewking** [comment]
Yes, as you can see here: https://swagger.io/specification/#dataTypes, there are date and date-time formats, where date is only the date. Since dart only provides DateTime type, the internal type is the same, but for date format only the date is sent or parsed (e.g. 2019-05-02)

**Comment by wing328** [comment]
so we should update this line: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart2/class.mustache#L26 to do something like:

```dart
var formatter = new DateFormat('yyyy-MM-dd');
{{name}} = formatter.format(DateTime.parse(json['{{baseName}}']));
```
Disclaimer: I never code in Dart

**Comment by dalewking** [comment]
That should handle the case of formatting to send to an API (though with Dart 2 the new keyword is not necessary). There would probably need to be a corresponding change for parsing a string value  into a DateTime.

**Comment by dalewking** [comment]
Wait, no that code does not make sense. Let me look into it a bit more

**Comment by dalewking** [comment]
So for the line you referenced no change is actually *required* as DateTime.parse will accept any valid input. If you wanted to make it so that it will only accept things in the yyyy-MM-dd format you would do something like this:

```
var formatter = new DateFormat('yyyy-MM-dd');
{{name}} = formatter.parseStrict(json['{{baseName}}']);
```

The important place to change is https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart2/class.mustache#L72

There you would want to do something like:

     var formatter = DateFormat('yyyy-MM-dd');
      json['{{baseName}}'] = {{name}} == null ? null :formatter.format( {{name}});

But there would also need to be a change somewhere else as well as this only handles model classes. The place I ran into it was passing the date as a parameter on the URL path.

**Comment by wing328** [comment]
@dalewking  Do you mind filing a PR with the suggested change?
```dart
 var formatter = DateFormat('yyyy-MM-dd');
  json['{{baseName}}'] = {{name}} == null ? null :formatter.format( {{name}});
```

**Comment by dalewking** [comment]
May be a while before I can get to it.

**Comment by sbu-WBT** [comment]
Is there any progress? I stumbled on this problem, too.

If there's no PR in progress, I don't mind to make one.
