### ISSUE TITLE
[REQ] Mojo shall not generate _all_ supporting files and folders

### ISSUE THREAD

**Issue by Emdee89** [OpenAPITools/openapi-generator#2716]
### Is your feature request related to a problem? Please describe.
I run the Maven Plugin to generate Java abstractions for my API.
When I parameterize it to not generate supporting files like so:
  ```
  <plugin>
      <groupId>org.openapitools</groupId>
      <artifactId>openapi-generator-maven-plugin</artifactId>
      <version>4.0.0-beta3</version>
       <executions>
         <execution>
            <goals>
                  <goal>generate</goal>
             </goals>
             <configuration>
                  <inputSpec>TRUNCATED</inputSpec>
                  <generatorName>java</generatorName>
                   <configurationFile>${project.basedir}/src/main/resources/api-options.json</configurationFile>
                    <generateSupportingFiles>false</generateSupportingFiles>
                </configuration>
            </execution>
        </executions>
    </plugin>
```
then it does not compile, because the classes around `ApiClient` are missing (i.e., not generated).
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project xyz: Compilation failure: Compilation failure:
[ERROR] /xyz/openapi/src/main/java/xyz.java :[3,34] package xyz.invoker does not exist
[ERROR] /xyz/openapi/src/main/java/xyz.java : [30,13] cannot find symbol
[ERROR]   symbol:   class ApiClient
```
When I run the same with `generateSupportingFiles` = `true`, then it compiles, because the package `invoker` containing the `ApiClient` class gets generated.

However, in this case the Maven Plugin generates numerous files ("supporting files") which I do not need for my case.
Examples:

- AndroidManifest.xml
- folder "gradle"
- an own pom.xml 
- ...

## Describe the solution you'd like
I would like to instruct the Maven Plugin that it should generate the `invoker` package and its content even if `generateSupportingFiles` == `false`. 

## Describe alternatives you've considered
I experimented with the parameter `supportingFilesToGenerate` which allows to name explicitly which file (not folder) you want to have generated. As a result, the plugin only generates supporting files that I named explicitly. However, this approach is not the holy grail, because:
- I do not really want to mention all files explicitly by hand. This is error-prone.
- The plugin still creates directories for files I have not mentioned.

## Additional context
To me this appears to be a bigger aspect that requires thorough analysis of what the user wants to have generated.

**Comment by wing328** [comment]
> However, in this case the Maven Plugin generates numerous files ("supporting files") which I do not need for my case.

Please use .openapi-generator-ignore to skip those files instead.
