### ISSUE TITLE
[REQ] Support for custom types based on format field

### ISSUE THREAD

**Issue by steco** [OpenAPITools/openapi-generator#2730]
**Description**

OpenApi-Gen currently supports the following hard-coded "format"s for a string parameter
 - uuid
 - binary
 - email
 - date
 - date-time
 - byte-array
 - binary

I'd like to make this more generic, ie support additional values for the "format" field and use a type-mapping parameter to map them to a specific type in the generated code.  As per https://swagger.io/specification/#dataTypes:

_the format property is an open string-valued property, and can have any value. Formats such as "email", "uuid", and so on, MAY be used even though undefined by this specification_

This [commit](https://github.com/finbourne/openapi-generator/commit/ab99bed7b38112de7306cf862240f8b67b09d841) is the change to support this.  Is this an appropriate change to make ?

**Comment by wing328** [comment]
@steco thanks for the suggestion. Yes, we definitely want to support more `format`.

I would suggest opening a PR to start with and see if the CIs catch any issue as a result of the suggested change.

**Comment by steco** [comment]
Thanks William. I've done it here - https://github.com/OpenAPITools/openapi-generator/pull/2799, and it looks like all the CI tests pass.  What's the next step ?

Thanks

**Comment by chrylis** [comment]
Would this change make it possible for me to use a format `myformat` and provide a custom mapping to `com.company.project.MyFormat`?

**Comment by steco** [comment]
Yes.  I've only used this for a C# client but I believe that the change should work for all languages.  You would just need to pass --type-mappings myformat=com.company.project.MyFormat to swagger-codegen-cli.jar

**Comment by sigpwned** [comment]
I have a similar requirement and independently generated what is (essentially) the same PR as linked above. It worked for my Java application as well. I would love to see this get merged and released soon! My team will likely have to maintain a patched version until then. Thanks to @steco for the issue and PR, and to the broader team for a hopefully quick review and merge!

**Comment by ShoeBoom** [comment]
Is it possible to extend this feature to other types. For example my spec uses something similar to

```
"foo": {
    "enum": [
        "0",
        "1",
        "2"
    ],
    "type": "integer",
    "format": "byte"
}
```

the codgen maps this to Int

**Comment by crtomirmajer** [comment]
Any progress on this?

**Comment by ShoeBoom** [comment]
> Any progress on this?

I made a related change in #4931. But it hasn't been active for a while so idk

**Comment by marcelstoer** [comment]
Since both #2799 and #9285 were merged I suggest you close this.

**Comment by wing328** [comment]
Closed. 

Please give it a try with the latest master or SNAPSHOT version or the upcoming v5.1.1 release

**Comment by wh81752** [comment]
Hi there, is this feature now in place?

In my use-case, I have two date-time formats, one being:

```
      type: string
      format: date-time-with-fixed-precision
      example: '2017-07-21T17:32:28.000000000Z'
```

Now, within my moustache (mess) I would like to be able to write -- as an example -- something like this:
```
{{#isDateTimeWithFixedPrecision}}@JsonSerialize(using = IssInstantSerializer.class){{/isDateTimeWithFixedPrecision}}
```

Or is something like this already doable?
