### ISSUE TITLE
[BUG] [typescript-angular] Base Path can't be set to '<empty string>'

### ISSUE THREAD

**Issue by DanielHabenicht** [OpenAPITools/openapi-generator#2731]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

If the `basePath` in the config is set to `''` (empty string). The configuration is ignored and `'http://localhost'` is used instead. That is unexpected behaviour. 

###### Background
The basePath of the typescript-angular generated Files are currently set to `'http://localhost'` (as a Fallback). When trying to setup the basePath to `''` (empty String) the config is not used as the generated line of code `configuration.basePath || basePath || this.basePath;` is evaluated to false, because empty string in javascript is false. 

```typescript
  protected basePath = 'http://localhost';
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (configuration) {
      this.configuration = configuration;
      this.configuration.basePath = configuration.basePath || basePath || this.basePath;
    } else {
      this.configuration.basePath = basePath || this.basePath;
    }
  }
```

##### openapi-generator version

4.0.0-beta2

##### Command line used for generation

```bash
npm install @openapitools/openapi-generator-cli@0.0.8-4.0.0-beta2
openapi-generator generate -i swagger.json -g typescript-angular -o projects/client-api/src/lib/ --additional-properties="ngVersion=6.1.7" --additional-properties="supportsES6=true"
```

##### Steps to reproduce

1. Generate typescript-angular package from openapi.config
2. Configure the `ApiModule` in app.module.ts
3. Use a service from the generated typescript-angular package. 

##### Related issues/PRs

Nothing found.

##### Suggest a fix
Two ways:
1. Remove the fallback basePath by setting it to `''` (empty string)
2. Fix the evalutation `basePath` property.

**Comment by macjohnny** [comment]
@DanielHabenicht would you like to implement a fix for this?

**Comment by DanielHabenicht** [comment]
If you can tell me where the `basePath` is set I would be more than happy to provide a PR. :)
I've ready searched for it but could not find the code.

**Comment by macjohnny** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/baf0e8521634ecb759c7e00ab65f12373aa2d546/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L59-L71

**Comment by macjohnny** [comment]
But you can set the basepath in your .yaml file

**Comment by nyszilard** [comment]
It doesn't work for me...

```java
@Bean
    public OpenAPI openAPI() {
        OpenAPI openAPI = new OpenAPI().info(
            new Info()
                .title("API")
                .description("API description")
                .version("1.0.0")
        );
        Server server = new Server();
        server.setUrl("/");
        openAPI.setServers(List.of(server));
        return openAPI;
    }
```

Output:
```typescript
protected basePath = 'http://localhost';
```

**Comment by NetzwergX** [comment]
Neither the empty string nor a relative URL like `/` currently work. This makes it extremely hard to use the generator for portable code. We have at least two different projects where we'd like to set the base path to `/`. It appears that way in our YAML file, and the generator *should not* simply ignore that.

Please redirect effort towards this issue, it has been open long enough. We are currently patching the generated source files, which is a really, really dirty practice.

**Comment by macjohnny** [comment]
@NetzwergX happy to accept your PR

**Comment by martinnovak** [comment]
@NetzwergX what do you mean by having the base path as relative url, but setting it as `/`?

I use OpenAPI this way - I define API endpoint as `/api/users` and then I set the base url as empty string.

**Comment by hieucd04** [comment]
I'm running into this issue today too.
- I tried to set `basePath` to both '' (empty string) and `/` and none of them work.
- I also tried to set `server` to both '' (empty string) and `/` and none of them work.

My use case is simple: I just want to send HTTP requests to whatever appears in browser address bar without using `window.location.href` (`window` is not even available in my case as I'm doing React SSR)

My current workaround is to modify the `typescript-axios` template files which is OK for now but will become an overhead in the long run as I will have to keep updating the template to keep it in sync with its online version.

Can this issue be reopened so that I can subscribe to it and be notified when it's closed?

**Comment by macjohnny** [comment]
@hieucd04 you can open a new issue and provide a fix for it

**Comment by Kerren-Entrostat** [comment]
For anyone that's arriving here from search, I've been able to set the `basePath` variable in Angular using `basePath=<YOUR_PATH>` in the `additional-properties` flag in the CLI generate command. An example would be:

```bash
npx --yes @openapitools/openapi-generator-cli \
	generate -i ./src/openapi.yaml \
	-g typescript-angular \
	-o ./src/generated-client \
	--additional-properties=fileNaming=kebab-case,basePath=/
```

You'll now see in your Angular classes the following:

```typescript
	protected basePath = '/';
```
