### ISSUE TITLE
[BUG][C++][Pistache-server] (Regression) Server rejects the input request

### ISSUE THREAD

**Issue by CyrilleBenard** [OpenAPITools/openapi-generator#2734]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The issue is almost new and seems to be related to the use of the new nlohmann::json API (?)

When a request has been described in YAML with a body content owning 2 fields (only one required), if the client sends the request with only one field, the pistache-server rejects and answer with a HTTP 500 - "[json.exception.out_of_range.403] key 'field2' not found"

I must add that the 'field2' was defined as a 'anyOf' string, see below.

##### openapi-generator version

Current master 4.0.0-SNAPSHOT

This is a regression. It has worked, at least, up to the commit `84b99fea546ec116e399625239a6991ebabd3a94`

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Check anyOf in request content
servers:
  - url: '{apiRoot}/'
    variables:
      apiRoot:
        default: https://example.com
        description: Internal ref filename is check_anyOf_in_req_content.yaml
paths:
  /CheckAnyOf:
    post:
      summary: Check AnyOf generation
      operationId: list
      tags:
        - Check
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Content"

      responses:
        '200':
          description: Everythings gonna be alright
          headers:
            x-next:
              description: Everythings gonna be alright
              schema:
                type: string
          content:
            application/json:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string

components:
  schemas:

    PresenceState:
      anyOf:
      - type: string
        enum:
          - "IN"
          - "OUT"
          - "UNKNOWN"
      - type: string

    Content:
      type: object
      required:
        - field1
      properties:
        field1:
          type: string
        field2:
          $ref: "#/components/schemas/PresenceState"
                                                                        
```
##### Command line used for generation

Generate :
```
openapi-generator-cli.sh generate -i ./openapi.yaml -g cpp-pistache-server -c ./config.json -o .
```

Compile all files and link:
```
(cd impl && ln -s ../main-api-server.cpp ./main.cpp)

g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/api/CheckApi.o api/CheckApi.cpp
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/impl/CheckApiImpl.o impl/CheckApiImpl.cpp
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/impl/main.o impl/main.cpp
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/model/Content.o model/Content.cpp
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/model/PresenceState.o model/PresenceState.cpp
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/model/Helpers.o model/Helpers.cpp

ar -rc obj/model/libmodel.a obj/model/Content.o obj/model/PresenceState.o obj/model/Helpers.o

g++ -g   -o server-MsUnderTest obj/api/CheckApi.o obj/impl/CheckApiImpl.o obj/impl/main.o obj/model/libmodel.a -lpistache -lpthread
```

##### Steps to reproduce

Launch the generated server listening on the TCP port 8080

Send the request with only 1 field content, with curl (for example) :
```
curl -X POST "http://localhost:8080/CheckAnyson" -H  "Content-Type: application/json" -d "{\"field1\":\"string\"}"
```

The result will be :
```
[json.exception.out_of_range.403] key 'field2' not found
```

Send the request with the 2 fields :
```
curl -X POST "http://localhost:8080/CheckAnyOf" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{\"field1\":\"string\",\"field2\":\"string\"}"
```

The result will be :
```
"Everythings gonna be alright"
```

##### Related issues/PRs
N/A
##### Suggest a fix
One suggested fix in the comment below
EDIT: One patch delivered to fix the appropriated code. See below

**Comment by CyrilleBenard** [comment]
I worked on this regression and I have identified the generated code that throw an json exception :

```
void from_json(const nlohmann::json& j, Content& o)
{
    j.at("field1").get_to(o.m_Field1);

    /*
     * The call to j.at("field2") will throw a JSON exception out_of_range - 403 - key not found
     * before calling the is_null() method
     */
    if(!j.at("field2").is_null())
    {
        j.at("field2").get_to(o.m_Field2);
        o.m_Field2IsSet = true;
    } 
}
```

**Comment by CyrilleBenard** [comment]
Fix should be this kind generated code :

```
void from_json(const nlohmann::json& j, Content& o)
{
    j.at("field1").get_to(o.m_Field1);

#ifdef BEFORE_FIX
    if(!j.at("field2").is_null())
    {
        j.at("field2").get_to(o.m_Field2);
        o.m_Field2IsSet = true;
    } 
#else
    {
        auto it=j.find("field2") ;
        if( it != j.cend() )
        {
            it->get_to(o.m_Field2) ;
            o.m_Field2IsSet = true;
        }
    }
#endif
}
```

**Comment by CyrilleBenard** [comment]
Below the patch to apply to the mustache file :

```
cd ./modules/openapi-generator/src/main/resources/cpp-pistache-server
patch -N -t -p0 < file.patch.txt
```
[file.patch.txt](https://github.com/OpenAPITools/openapi-generator/files/3117742/file.patch.txt)

It will generate some kind of code as described above for each required field.
I hope the next time I will be able to submit a PR ... as soon as I would have understood how to ^^

**Comment by etherealjoy** [comment]
Thanks for the patch. I can help you create the PR.

**Comment by etherealjoy** [comment]
Lets fix this first before we work on the other Pistache issues

**Comment by CyrilleBenard** [comment]
Agree and the fix is better than mine :+1:
