### ISSUE TITLE
[BUG] Dart code generator does not support num types

### ISSUE THREAD

**Issue by lucamerolla** [OpenAPITools/openapi-generator#2736]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The dart code generator does not recognize the parameter type number with format int32. The resulted output is a parameter of type Object.

I have tried with swagger-codegen and instead it return a parameter of type num, which is perhaps more correct

##### openapi-generator version

4.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

Here is the input
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
paths:
  /positions:
    get:
      description: ..
      operationId: getPortfolioOverviewImpact
      responses:
        "200":
          description: ...
          content:
            application/json:
              schema:
                 $ref: "#/components/schemas/Position"
servers:
  - url: http://test.io/mobile-api
components:
  schemas:
    Position:
      type: object
      required:
        - asset_id
      properties:
        asset_id:
          type: number
          format: int32
        asset_class:
          type: string
        market_value:
          type: number
          format: float
          multipleOf: 0.01
        current_balance:
          type: number
          format: float
          multipleOf: 0.01
      xml:
        name: Position
```

##### Command line used for generation

```
# Generate non-browserClient and put it to the flutter sample app
ags="generate -t ${home_swagger}/modules/openapi-generator/src/main/resources/dart -i ${project}/mobile-api/api/test.yaml -g dart -o ${output}/flutter -DhideGenerationTimestamp=true -DbrowserClient=false $@"
java $JAVA_OPTS -jar $executable $ags
```

##### Steps to reproduce

1. generate the code from the provided API definitino
2. check the file position.dart created
3. the output is the following...

```
class Position {
  
  Object assetId = null;

  String assetClass = null;
  
  double marketValue = null;
  
  double currentBalance = null;
...
```

##### Suggest a fix

The exact type that should be created in the data model should be an "int", however, it seems that it would be a good practice in Dart to use "num" instead.

**Comment by karismann** [comment]
format int32 is only available for type integer, not for number

i think you should have this warning in the generation :
`Unknown format detected for null: int32`

you could also check this here : https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#dataTypes

**Comment by lucamerolla** [comment]
Thanks, indeed that was the problem
