### ISSUE TITLE
[typescript-axios] toIsoString() with type string

### ISSUE THREAD

**Issue by duckytutu** [OpenAPITools/openapi-generator#2745]
Im using Docker to generate my OpenAPI
https://openapi-generator.tech/docs/installation#docker

This is one of my generate
![image](https://user-images.githubusercontent.com/14825696/56782006-751ace80-680f-11e9-9e08-7f2b7f9214b8.png)

Any idea why `startDate` for example, input as `string` but still has the line 
```localVarQueryParameter['startDate'] = (startDate as any).toISOString();```

It cause an error: `toIsoString() is not a function`

**Comment by macjohnny** [comment]
maybe you have a type mapping in your configuration? e.g.
```xml

                                    <typeMappings>
                                        <typeMapping>DateTime=string</typeMapping>
                                    </typeMappings>
```
the generated code should be improved to something like
```typescript
if (startDate !== undefined && startDate instanceof Date) {...}
```
would you like to open a PR to fix this?

**Comment by tsiq-jeremy** [comment]
Hey, I see the same issue occurring with typescript/fetch using

```JSON
{
   ...
   "type": "string",
   "format": "date",
}
```
Since the parameter getting passed in is ALWAYS going to be a string, it should never be calling `toIsoString()` on it. Can we just update it to not worry about calling that function?

```Javascript
localVarQueryParameter['{{baseName}}'] = {{paramName}};
```

**Comment by macjohnny** [comment]
in order not to break existing code, it would be simpler to check for both `Date` and `string`:
```typescript
if (startDate !== undefined && startDate instanceof Date) {...}
```

**Comment by tsiq-jeremy** [comment]
@macjohnny works for me! Im going to open up a PR with an update to do this. So I also did a bit more digging into the issue on why this is occurring. If the format is "date", then the parameter type is a `string`, while if the format is "DateTime", the the parameter it is looking for is a `Date`. 

In `AbstractTypeScriptClientCodegen.java:
```java
typeMapping.put("date", "string");
typeMapping.put("DateTime", "Date");
```

While in `typescript-fetch/api.mustache` I found:
```mustache
                {{#isDate}}
                localVarQueryParameter['{{baseName}}'] = ({{paramName}} as any).toISOString();
                {{/isDate}}
```

Which is causing the type mismatch.

**Comment by tsiq-jeremy** [comment]
@macjohnny works for me! Im going to open up a PR with an update to do this. So I also did a bit more digging into the issue on why this is occurring. If the format is "date", then the parameter type is a `string`, while if the format is "DateTime", the the parameter it is looking for is a `Date`. 

In `AbstractTypeScriptClientCodegen.java:
```java
typeMapping.put("date", "string");
typeMapping.put("DateTime", "Date");
```

While in `typescript-fetch/api.mustache` I found:
```mustache
                {{#isDate}}
                localVarQueryParameter['{{baseName}}'] = ({{paramName}} as any).toISOString();
                {{/isDate}}
```

Which is causing the type mismatch.

**Comment by macjohnny** [comment]
@tsiq-jeremy could you please open the PR here in openapi generator?

**Comment by fuzzzerd** [comment]
This seems to be affecting the typescript fetch client too. Looks like there was a pull against the swagger-gen fetch client, but not the openapi generator fetch client.

**Comment by macjohnny** [comment]
@fuzzerd would you like to port https://github.com/OpenAPITools/openapi-generator/issues/3423 to the typrscript fetch client?
