### ISSUE TITLE
[BUG] [Elm] elmPrefixCustomTypeVariants

### ISSUE THREAD

**Issue by andys8** [OpenAPITools/openapi-generator#2759]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

```json
    "Answers": {
      "type": "object",
      "required": [
        "houseLiving",
        "liabilityLegalProtection",
        "pets"
      ],
      "properties": {
        "houseLiving": {
          "type": "string",
          "enum": [
            "RENTED",
            "OWN_HOUSE",
            "OWN_FLAT",
            "PARENTS_HOUSE",
            "SHARED_FLAT",
            "RENT_FREE"
          ]
        },
        "liabilityLegalProtection": {
          "type": "array",
          "items": { "type": "string", "enum": ["BUILDER", "LANDLORD"] }
        },
        "pets": {
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["DOG", "CAT", "HORSE", "AQUARIUM"]
          }
        }
      },
      "title": "Answers"
    }
```

```elm
type HouseLiving
    = HouseLivingRENTED
    | HouseLivingOWNHOUSE
    | HouseLivingOWNFLAT
    | HouseLivingPARENTSHOUSE
    | HouseLivingSHAREDFLAT
    | HouseLivingRENTFREE


type LiabilityLegalProtection
    = LiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionBUILDER
    | LiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionLiabilityLegalProtectionLANDLORD

type Pets
    = PetsPetsPetsPetsDOG
    | PetsPetsPetsPetsCAT
    | PetsPetsPetsPetsHORSE
    | PetsPetsPetsPetsAQUARIUM
```

The actual output for `LiabilityLegalProtection` and `Pets` should only add the prefix a single time.

##### openapi-generator version

v4.0.0-beta3

##### Command line used for generation

```shell
    docker run --rm \
                -v "$PWD:/local" \
                openapitools/openapi-generator-cli:${OPEN_API_VERSION} generate \
                    -i /local/swagger.json \
                    -o "/local/$SDK_DIR/$generator" \
                    -g "$generator" \
                    --invoker-package "crm" \
                    --additional-properties elmEnableCustomBasePaths=true \
                    --additional-properties elmPrefixCustomTypeVariants=true
```

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/blob/69ad9a9957fc0dca9dbd792cb9a6a3b6f5bf197c/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElmClientCodegen.java#L696-L698

A fix would be to check if the prefix is already part of the value. This will work, but will not remove the root cause. It seems that certain cases leed to concatenating the prefix 4 times. In other cases it's working fine.

@eriktim What do you think?

**Comment by eriktim** [comment]
Thanks for reporting this @andys8 !
I something miss some FP here, so I am not particularity proud of my fix...
