### ISSUE TITLE
Creating templates is confusingly documented

### ISSUE THREAD

**Issue by philsturgeon** [OpenAPITools/openapi-generator#276]
There are a lot of ways to get started with openapi-generator, and none of them seem to make it particularly easy to make your own template. I wouldn't consider creating a template to be advanced usage, I'd expect most people want to build their own, as generated code by somebody else usually fits like a borrowed suit. 

As such it should be super duper clear how to go about making one, and after going thorugh the docs and trying things for almost two hours I'm not there.

##### Description

The customization docs say its easy, but dont really say what to do.

<img width="1009" alt="screen shot 2018-06-10 at 2 06 22 pm" src="https://user-images.githubusercontent.com/67381/41205383-009faa38-6cb8-11e8-98d4-067c79e2ca71.png">

I've cloned openapu-generator and im using this command: 

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
	-i ./specs/API.yml \
	-t ./templates/ \
	-g foo \
	-o ./out/foo

```

Inside `./templates/` is `foo` which is copied from `ruby`, but that doesn't seem to exist:

```
Can't load config class with name 'foo'
Available:
ada
ada-server
```

I tried putting the repo next to all the other templates in `modules/openapi-generator/src/main/resources/` too and no dice. 

Maybe the instructions here could be a little more explict, as I think whoever wrote it is very familiar with how things work already.

##### openapi-generator version

3.0.0

##### Command line used for generation

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
	-i ./specs/API.yml \
	-t ./templates/ \
	-g foo \
	-o ./out/foo
```

**Comment by jmini** [comment]
Thank you a lot for this feedback. Please continue the discussion to help to improve this documentation.

Page is: [`docs/customization.md`](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md).

I agree that it could be improved.

---

The first section **Modifying the client library format** is about using an existing generator but with modified templates.

In this case, this does not define an new generator `-g`.

If you want to create a new generator check the second section **Making your own codegen modules**

---

Maybe you can tell here what you are trying to do, I can indicate how you should use it.

**Comment by philsturgeon** [comment]
Thank you @jmini , that's something I figured out on a plane through enough trial an error after about an hour (there was no movie!)

I have a modified version of the docs that this clear you can only "override" existing generators, so your templates directory can contain `ruby` but it cannot contain `foo`. Hopefuly https://github.com/OpenAPITools/openapi-generator/pull/283  will help.
