### ISSUE TITLE
[REQ] [kotlin-spring] Reactive Kotlin Spring Server Generator

### ISSUE THREAD

**Issue by botcoder** [OpenAPITools/openapi-generator#2765]
## Describe the solution you'd like

Support webflux in the same way as the [Spring](https://github.com/OpenAPITools/openapi-generator/blob/v4.0.0-beta3/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L57) server generator, when using kotlin-spring with spring-boot library.

## Describe alternatives you've considered

Wrap ResponseEntity with Mono/Flux.

## Additional context

Java support was added at PR [#571](https://github.com/OpenAPITools/openapi-generator/pull/571), but Kotlin support is missing.

**Comment by wing328** [comment]
@botcoder that's a reasonable suggestion. May I know if you've time to contribute the enhancement? We can show you some good starting points.

**Comment by sylvainmoindron** [comment]
since spring 5.2 support kotlin coroutines, i'm interesed to add reactive behavior with coroutines for kotlin-spring generator. should i start from @botcoder work ?

**Comment by botcoder** [comment]
> since spring 5.2 support kotlin coroutines, i'm interesed to add reactive behavior with coroutines for kotlin-spring generator. should i start from @botcoder work ?

You can ignore my change as I just added a "Mono/Flux" wrapper, but it's incomplete as it doesn't allow the user to change the response headers, and adding a reference to ServerWebExchange doesn't work on webflux, so I closed the pull request.

Coroutine would be a much better solution, I'll be looking forward to it. Thank you.

**Comment by sylvainmoindron** [comment]
I will add a reactive support via coroutines then. should I also remove any reference to mono/flux that are already in the master ? (in the template there a reference to reactive but they cannot be triggered because there is no reactive option in the kotlin-spring at the moment)

**Comment by botcoder** [comment]
It seems those references were added by mistake (ie, copy+paste from spring-mvc, perhaps).

**Comment by sylvainmoindron** [comment]
since the PR #2934 is merged, shouldn't this request be closed?
