### ISSUE TITLE
[JAVA] Option "--template-dir" seems not work

### ISSUE THREAD

**Issue by osier** [OpenAPITools/openapi-generator#2766]
##### Description

How to reproduce:

1) Copy the mustache templates of generator `java` with:

```Bash
# mkdir /tmp/templates
# cp -r openapi-generator/modules/openapi-generator/src/main/resources/Java/* /tmp/templates
```
                     
2) Change the README.mustache with removing the following line:

```
{{#appDescription}}{{{appDescription}}}{{/appDescription}}
```

3) Generate with `--template-dir`, the script used is:

```Bash
#!/bin/bash

export JAVA_POST_PROCESS_FILE="/usr/bin/clang-format -i"
java -DdebugModels=true -jar $PWD/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
-i openapi.yaml \
-g java \
-o ks-sdk-java/ \
--skip-overwrite \
-t /tmp/templates \
--enable-post-process-file 
```

4) Check the generated README.md in "ks-sdk-java",  will see it still has the {{#appDescription}} included.

##### openapi-generator version
```Bash
# java -jar $PWD/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar version
4.0.0-SNAPSHOT
```

**Comment by wing328** [comment]
@osier thanks for reporting the issue. Can you please also test with another generator (e.g. php) to see if the issue is Java-specified?

**Comment by osier** [comment]
@wing328 Hi, Thanks for the quick response. 

Just tested with generator `php`,  it works fine, so yes, the issue may only exist for generator `java`.

**Comment by wing328** [comment]
It works for me. The Java client generator is using `okhttp-gson` as the default library so you will need to customize https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/README.mustache

**Comment by wing328** [comment]
Let us know if you still need help.

**Comment by osier** [comment]
@wing328 Sorry, was out of the internet for a while.  It works indeed, thanks.  This issue can be closed now.

**Comment by wing328** [comment]
No problem. Ping us if you need further help. Have a nice weekend.

**Comment by osier** [comment]
👍，nice weekend.
