### ISSUE TITLE
Move to Circle CI 2.0

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#278]
Since Circle CI 1.0 sunset in august.

**Comment by philsturgeon** [comment]
The most important aspect of CircleCI 2.0 is [workflows](https://circleci.com/docs/2.0/workflows/), but their basing everything around docker images is also going to be very relevant here. 

Workflows will allow you to run [your various different test suites](https://github.com/OpenAPITools/openapi-generator/wiki/Integration-Tests) simultaniously, without needing multiple different CI services involved.

![image](https://user-images.githubusercontent.com/67381/41232037-129eca16-6d53-11e8-9595-656b7dd16dda.png)

There are [pre-built images](https://circleci.com/docs/2.0/circleci-images/) for all sorts of things, so hopefully many of your needs will be satisfied with those, and you wont need to go building custom images.

Here is a very boring CicleCI config with only the one workflow, but it might help: 

  https://github.com/wework/speccy/blob/master/.circleci/config.yml

**Comment by wing328** [comment]
@MartinDelille thanks for creating an issue for tracking

@philsturgeon thanks for sharing more about new features in CircleCI 2.0. We'll explore CircleCI 2.0 new features (e.g. custom build images) after the migration.

**Comment by wing328** [comment]
UPDATE: https://discuss.circleci.com/t/issue-with-migration-from-1-0-to-2-0/22915
