### ISSUE TITLE
[REQ][Golang][client] Add go.mod to go client templates

### ISSUE THREAD

**Issue by bkabrda** [OpenAPITools/openapi-generator#2796]
### Is your feature request related to a problem? Please describe.

I need to use the autogenerated go client as a dependency of another go module, which is much easier when it's a module as well.

## Describe the solution you'd like

I'd like the go client templates to also contain go.mod/go.sum files that would be rendered (not sure if this should be by default, but it probably wouldn't hurt). To do that, the go config file would also need to contain the full module name, e.g. "github.com/user/mymodule".

## Describe alternatives you've considered

I could maintain these files by hand outside of openapi-generator functionality.

## Additional context

This seems to be a simple enough modification that I would probably be able to send a PR myself, but first I'd like to hear if it's wanted/acceptable.

**Comment by wing328** [comment]
The suggestion makes sense to me and I don't mind it's turning on by default.

Let us know if you need help with the PR.
