### ISSUE TITLE
[BUG] Dart code (seems to) need dartson 

### ISSUE THREAD

**Issue by ExplicitlyImplicit** [OpenAPITools/openapi-generator#2830]
When using enums it seems that the generated dart code references stuff in the dartson package:

https://github.com/OpenAPITools/openapi-generator/blob/b186883217577a2db87789d3efe8f18f4e712023/modules/openapi-generator/src/main/resources/dart2/api_client.mustache#L50

https://github.com/OpenAPITools/openapi-generator/blob/b186883217577a2db87789d3efe8f18f4e712023/modules/openapi-generator/src/main/resources/dart2/enum.mustache#L1

https://github.com/OpenAPITools/openapi-generator/blob/b186883217577a2db87789d3efe8f18f4e712023/modules/openapi-generator/src/main/resources/dart2/enum.mustache#L18

But it does not include it in the pubspec.

Is this by design and how can I fix it?

Thank you for your help!

**Comment by wing328** [comment]
@ExplicitlyImplicit thanks for reporting the issue.

cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09)

**Comment by rvowles** [comment]
this would be relatively easy to fix

**Comment by rvowles** [comment]
Given the sluggish nature of release @ExplicitlyImplicit - I put my stuff in a dependency you can use in Maven if you use Maven. https://github.com/ClearPointNZ/connect-java/tree/master/maven-plugins/openapi-dart-plugin
