### ISSUE TITLE
[REQ] Support Server Variable Object and relative URL (javascript client)

### ISSUE THREAD

**Issue by jdorel** [OpenAPITools/openapi-generator#2832]
### Is your feature request related to a problem? Please describe.

I want to deploy the same API on several hosts (I am working with some embedded systems). But it appears to me that the current javascript client module generated has a static URL. 

## Describe the solution you'd like

I would like to have to be able to use a variable to set the URL of the server. A better alternative would be to support [Server Variable Object](https://swagger.io/specification/#serverVariableObject) and a default variable when only specifying a relative path

## Describe alternatives you've considered

As I am using webpack to generate the files to be distributed, I considered using a regex in the backend to modify the sttic files. I still need to do that, but having a single variable where it is set appears cleaner to me.

## Additionnal context

I am willing to do the PR myself, but it might take some time. This issue is also to gather some feedbacks.

**Comment by wing328** [comment]
Which version did you try? I added the server variable support in 4.0.0-beta releases.

Can you try the latest master to see if it works for you? SNAPSHOT version can be found in the project's README

**Comment by jdorel** [comment]
From `openapi-generator version`, I am using version `4.0.0-beta3`.So it appears to be implemented, sorry for not seeing this. I just don't understand how to use it yet.

From what I understand, I need to redefine an `ApiClient` object, using the `getBasePathFromSettings` function (for exemple `getBasePathFromSettings(0, {'port': "8443"}). And then create my API object (the one returned by `new PxcApi.DefaultApi()`).

I don't understand how to correctly link those bricks together at the moment, I'll get back to you once I have (and will try to document it in the README). Or should the issue be closed ?

In the meantime, would you have any advice / exemple ?

Thanks

**Comment by jdorel** [comment]
I got it to work using
```
const serverSettings = {
  server_hostname: window.location.hostname,
  port: '8443',
};

const localApi = new PxcApi.ApiClient();
localApi.basePath = localApi.getBasePathFromSettings(0, serverSettings);
const api = new PxcApi.DefaultApi(localApi);
```
