### ISSUE TITLE
[BUG][typescript-axios] Cannot find name 'Response'

### ISSUE THREAD

**Issue by mushketyk** [OpenAPITools/openapi-generator#2850]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix

##### Description

`openapi-generator` for `typescript-axios` does not generate a response type for a method with the following definition:

It generates a method like this:

```ts
healthz(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
```

But the `Response` type is not defined.

##### openapi-generator version

@openapitools/openapi-generator-cli@0.0.9-4.0.0-beta3

##### OpenAPI declaration file content or url

https://gist.github.com/mushketyk/7456792aeb35b2f9118d91b4cd2243d1

##### Command line used for generation

```
npx openapi-generator generate -i swagger.json -g typescript-axios
```

##### Steps to reproduce

Create a Swagger.json file with the specified endpoint
Generate a client using the provided command.
In the result output in the `api.ts` file the `Response` type is missing

##### Suggest a fix

Either define the `Response` type or return `AxiosPromise<void>`.

**Comment by macjohnny** [comment]
cc @nicokoenig

**Comment by macjohnny** [comment]
`Response` should be defined by the browser: https://developer.mozilla.org/de/docs/Web/API/Response

**Comment by mushketyk** [comment]
@macjohnny Unfortunately I am using this library in a Node.js environment, and I get a TypeScript compilation error when I import a package that was generated by the `typescript-axios` generator.

**Comment by macjohnny** [comment]
@mushketyk this could help you: https://github.com/Microsoft/TypeScript/issues/4948
I think you just need to import the typings

**Comment by macjohnny** [comment]
see also https://github.com/prisma/graphql-request/issues/15#issuecomment-326551575

**Comment by macjohnny** [comment]
Here you go: https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L12300

So you just need https://stackoverflow.com/a/42604094

**Comment by mushketyk** [comment]
@macjohnny Thank you for suggestions! Let me try it.

**Comment by mushketyk** [comment]
@macjohnny I don't think this is a correct solution. If you look at other methods generated with this method, they look like this:

```ts
status(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<IStatusResponse> {
}
```

Where the generic parameter of the `AxiosPromise` interface defines **data returned by a server**, e.g.:

```ts
export interface IStatusResponse {
    status: string;
}
```

Here is the definition of the `AxiosPromise` used by the generator:

```ts
export interface AxiosPromise<T = any> extends Promise<AxiosResponse<T>> {
}

export interface AxiosResponse<T = any>  {
  data: T;
  status: number;
  statusText: string;
  headers: any;
  config: AxiosRequestConfig;
  request?: any;
}
```

As you can see the `T` parameter defines data **returned by a server** to a client.

In this light the generated code makes no sense:

```ts
healthz(options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<Response> {
...
}
```

Since it assumes that a server is returning a JSON object that has the following structure: 

```ts
interface Response extends Body {
    readonly headers: Headers;
    readonly ok: boolean;
    readonly redirected: boolean;
    readonly status: number;
    readonly statusText: string;
    readonly trailer: Promise<Headers>;
    readonly type: ResponseType;
    readonly url: string;
    clone(): Response;
}
```

I still think that for the Swagger JSON that I've posted above the code generator should generate `void` type or something similar.

**Comment by macjohnny** [comment]
@nicokoenig could you have a look at this?

**Comment by vellengs** [comment]
'Response' just a type, we can define ourself, or directly use 'AxiosResponse'; 
But the difficult one is 'FormData is not defined'. 
I have to do like below:
```
(global as any).FormData = FormData; // hack for nodejs;
```

**Comment by macjohnny** [comment]
this could also be useful:https://www.npmjs.com/package/formdata-node

**Comment by HoaBo** [comment]
@mushketyk @macjohnny This is because of https://github.com/OpenAPITools/openapi-generator/blob/7f36f2642209c6d7070e1d76209ba1928d816922/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L226

When return type is empty, it's defaulted to `Response` while it should be `void`.

Should I fork and submit a pull request for this? In that case, who should be the reviewer? @nicokoenig seems to not actively maintain this anymore.

**Comment by macjohnny** [comment]
@HoaBo a PR is very welcome

**Comment by HoaBo** [comment]
@macjohnny I submitted the PR but cannot add any reviewers. Could you help please?
