### ISSUE TITLE
[REQ] Update PHP Slim generator to 4.0.0-alpha

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#2851]
### Is your feature request related to a problem? Please describe.

Slim Framework announced 4.0.0-alpha release in previous month.
https://www.slimframework.com/2019/04/25/slim-4.0.0-alpha-release.html
Current Slim server generator based on 3 version.

## Describe the solution you'd like

I think it's perfect time to migrate to Slim 4 while openapi-generator is in prestable status.

**Comment by wing328** [comment]
We'll release 4.0.0 soon. What about upgrading to 4.0.0-alpha (slim) after the release instead?

**Comment by ybelenko** [comment]
@wing328 
Thought about that, don't you think that developers will be frustrated about breaking changes right after they just upgraded to 4.0.0 generator?

**Comment by wing328** [comment]
We can create a new php-slim-v4 generator instead.

That's the approach we used for Swift (e.g. swift3, swift4, etc)

**Comment by ybelenko** [comment]
@wing328 
Easier to me ) Don't need to hurry.
I agree if you think it's the best way. Slim3 will be kinda abandoned, I won't add new features to outdated version.
