### ISSUE TITLE
[BUG] Version 4 no longer supports additionalProperties with boolean value

### ISSUE THREAD

**Issue by bopm** [OpenAPITools/openapi-generator#2854]
##### Description

Generator no longer supports `additonalProperties` with boolean value. Error `-attribute components.schemas.<...>.additionalProperties is not of type 'object'` being returned for such.

##### openapi-generator version

It's regression for 4.0.0

##### OpenAPI declaration file content or url

```json
{
  "type": "object",
  "additionalProperties": true
}
```

**Comment by macjohnny** [comment]
see also https://github.com/OAI/OpenAPI-Specification/issues/668

**Comment by lemoinem** [comment]
The link provided by @macjohnny is somewhat misleading. At first glance, it seems to imply that boolean `additionalProperties` are forbidden by the Spec.

Linked from there is https://github.com/OAI/OpenAPI-Specification/pull/894 which clearly states that boolean `additionalProperties` are allowed.

And the final text of the spec is very clear about it: https://swagger.io/specification/#properties
> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema. Consistent with JSON Schema, additionalProperties defaults to true.

**Comment by sabba** [comment]
This bug has also broken our development pipeline, where we use the `latest ` `openapi-generator-cli` docker image to validate and generate a python-flask server.
Actually we have to skip the validation with` --skip-validate-spec`.

Bug is still present on image `v4.0.0`, while it's not present on `v4.0.0-beta3`.

Thank you.

**Comment by macjohnny** [comment]
cc @wing328

**Comment by lemoinem** [comment]
As mentioned by sabba, disabling the validation can be used as a workaround in the meantime.

**Comment by bopm** [comment]
@wing328 by any chance is there a way to escalate it? It's really nasty to disable validation because of that.

**Comment by wing328** [comment]
@bopm yes, it's a regression in the [Swagger Parser](https://github.com/swagger-api/swagger-parser). Please open an issue in that repo instead.

**Comment by bopm** [comment]
@wing328 According to [this](https://github.com/swagger-api/swagger-parser/pull/1082) and [this](https://github.com/OpenAPITools/openapi-generator/commit/16f94e7e6295af89599743954bd16dd6c5c0ae6f) it may no longer be a problem. Testing on my example right now.

**Comment by bopm** [comment]
Well, it should be fixing that, but for some reason it's not. I am pulling 4.0.1 from Docker and it keeps telling me `additionalProperties is not of type 'object'`.

**Comment by bopm** [comment]
Can that be connected to missing release 2.0.13 [here](https://github.com/swagger-api/swagger-parser/releases)?

**Comment by wing328** [comment]
I don't think so ...

cc @jmini who works on the parser we maintain

**Comment by bopm** [comment]
Seems like stalled issue. And yet it forces me to not use validation in production code. Can something be done about it?

cc @wing328 @jmini

**Comment by ricellis** [comment]
This appears fixed for me with the [parser v2.0.13-OpenAPITools.org-2](https://github.com/OpenAPITools/swagger-parser/releases/tag/v2.0.13-OpenAPITools.org-2) which is included in recent 4.0.3 snapshots (I tried `openapi-generator-cli-4.0.3-20190708.092710-73`). So hopefully this will be resolved in the 4.0.3 release.

**Comment by wing328** [comment]
@ricellis thanks for confirming the issue has been addressed. Issue closed.

**Comment by jmini** [comment]
@ricellis I really appreciate your feedback on this. It helps to close issue.
