### ISSUE TITLE
[REQ] How to adjust the file name of a generated java class?

### ISSUE THREAD

**Issue by Emdee89** [OpenAPITools/openapi-generator#2864]
I played around with creating by own custom template for Java Resttemplate. This works quite nice!

My aim is to alter the class name of the generated API classes. I did so by changing `api.mustache`:
```
...
public class {{classVarName}} {
  private ApiClient apiClient;
...
```
I replaced ``{{className}}`` by ``{{classVarName}}`` and the output is as expected.

However, Java requires that the class name and the file name are the same. 

It appears that the generated Java file name is built with the variable `{{className}}`.

Suppose my API is named `My Service`, then the file would be named `MyServiceApi.java`, and the code would be `public class MyService`. 

How can I alter the file name of the Java class?

**Comment by wing328** [comment]
Given that the class name is based on the tag, What about renaming the tag in your spec instead?

**Comment by Emdee89** [comment]
Well I noticed that the filename consists of the tag plus Api. I would prefer that Api is omitted. I am afraid this is currently not possible.

**Comment by wing328** [comment]
You can customize the Java client generator to name it in whatever way you want.

PM me via [Slack](https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM) if you need help on that.

**Comment by danparisi** [comment]
Is there some documentation about how to do that? I'd need to replace the **ApiClient** class name

**Comment by qiaoruntao** [comment]
> Is there some documentation about how to do that? I'd need to replace the **ApiClient** class name

**ApiClient** seems to get hardcoded in template, i think you have to make custom templates to change it

**Comment by SaverioFrancesco** [comment]
Hello, 
I'm having the same problem but with the Csharp template.

My schemas are formatted like this:
#/components/schemas/A.B.DTO.C.ClassDTO
it is defined as A.B.DTO.C.ClassDTO

The problem is that the A.B.DTO.C. part should be compiled as the package and instead is sanitized like ABDTOCClassDTO as className.

Can you point to a tutorial on how to customize the template and extract the A.B.DTO.C.ClassDTO into 2 different variables?

**Comment by arderyp** [comment]
I'm also interested in this. Given these are API Clients, I'd like *ApiClient instead of *Api
