### ISSUE TITLE
[BUG] Ruby and node.js generators overwriting .travis.yml

### ISSUE THREAD

**Issue by tweirtx** [OpenAPITools/openapi-generator#2887]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

When I run the generators for the Ruby and node.js client libraries, they overwrite the custom .travis.yml files I have for them. This is not the case with any of the other generators. I have put .travis.yml in the .openapi-generator-ignore file.

##### openapi-generator version

0.0.9-4.0.0-beta3
##### OpenAPI declaration file content or url
https://www.thebluealliance.com/swagger/api_v3.json

I am aware that the spec has issues, however that does not have any bearing on the bug as far as I can tell. The same spec does not produce the same errors with other generators (such as the Python client)

##### Command line used for generation

openapi-generator generate -i https://www.thebluealliance.com/swagger/api_v3.json -g ruby -o tba-api-client-ruby -c configs/ruby-config.json --skip-validate-spec --additional-properties packageVersion=3.04.1
##### Steps to reproduce
* Create a custom .travis.yml file
* Add .travis.yml to your .openapi-generator-ignore
* Generate a Ruby or node.js client library
* Observe that your custom .travis.yml file has been overwritten by the generator

##### Related issues/PRs
None as far as I can see

##### Suggest a fix
Take a look at those generators and compare them with working ones

**Comment by wing328** [comment]
As a workaround, please add the file to .openapi-generator-ignore for the time being.

**Comment by tweirtx** [comment]
I have added it, sorry. I was not entirely clear about that

**Comment by ackintosh** [comment]
@tweirtx  Could you provide your `.openapi-generator-ignore` file?

I've tested with the .openapi-generator-ignore below, the file was not overwritten. 👀 
(with openapi-generator `v4.0.1-SNAPSHOT`)

- `ls -la`

```
$ ls -la
...
...
.openapi-generator-ignore
.rspec
.rubocop.yml
.travis.yml
...
...
...
```

- .openapi-generator-ignore 

```diff
# OpenAPI Generator Ignore
# Generated by openapi-generator https://github.com/openapitools/openapi-generator

+ .travis.yml
```

**Comment by tweirtx** [comment]
🤦‍♂ apparently I had it in there as travis.yml, not .travis.yml.
