### ISSUE TITLE
[Question | C#] How can I change the generated project name and namespace

### ISSUE THREAD

**Issue by nehme-bilal-ah** [OpenAPITools/openapi-generator#2931]
Hi,

When I use the C# generator I get a project named `Org.OpenAPITools.csproj` and the namespace is something like `Org.OpenAPITools.Model`. Are there parameters I can pass to changes these values?

Thanks.

**Comment by etherealjoy** [comment]
Run this command and you will see what options you can pass to the generator
```shell
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar config-help -g aspnetcore
```
For your case above you have to set the property  `packageName`
while generating pass additionally these parameters
```shell
--additional-properties packageName=YourPackageName
```
