### ISSUE TITLE
ReferenceError: FormData is not defined, if run at nodejs without browser.

### ISSUE THREAD

**Issue by vellengs** [OpenAPITools/openapi-generator#2939]
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache
code line 55 
```
const localVarFormParams = new {{^multipartFormData}}URLSearchParams(){{/multipartFormData}}{{#multipartFormData}}FormData(){{/multipartFormData}};{{/hasFormParams}}{{/vendorExtensions}}

```
will compiled with 
```
const localVarFormParams = new FormData();
```
 but FormData is unavailable at nodejs runtime.

**Comment by macjohnny** [comment]
see also https://github.com/OpenAPITools/openapi-generator/issues/2850#issuecomment-491208240

**Comment by syndic8myles** [comment]
The referenced issue above does not fix this bug. It is not a misconfigured `tsconfig.ts` issue.

**Comment by macjohnny** [comment]
You could add it to the globals, see e.g. https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-fetch/tests/default/mocks.ts

Would this solve your issue?

**Comment by syndic8myles** [comment]
This is the error with 'form-data' imported to the global scope.

```
runtime.js:83
                body: requestOpts.body instanceof FormData ? requestOpts.body : JSON.stringify(requestOpts.body),
                                       ^

TypeError: Right-hand side of 'instanceof' is not callable
```

This is the error with an import directly in the `runtime.ts` file.

```
runtime.ts:111:47 - error TS2359: The right-hand side of an 'instanceof' expression must be of type 'any' or of a type assignable to the 'Function' interface type.

111             body: requestOpts.body instanceof FormData ? requestOpts.body : JSON.stringify(requestOpts.body),
```

I'm not sure where to go from here to make `typescript-rxjs` node compatible.

**Comment by macjohnny** [comment]
Any contribution here is appreciated.
Any could be added to the instanceof expression

**Comment by DanielRuf** [comment]
Everything in the generated file is for a browser environment as it seems (uses `window`and much more).

**Comment by elierotenberg** [comment]
I'm personally using the generated openapi client for server-side testing only.
In my case, simply defining a dummy `global.FormData` property was enough to avoid `instanceof FormData` throwing (and always returning false).
```ts
// Mock for open API tests
((global as unknown) as { FormData: unknown }).FormData = class FormData {}; // or jest.fn()
```

If you actually need to use FormData, I'd suggest using something like [this](https://github.com/form-data/form-data) instead of an empty class.

**Comment by petermetz** [comment]
Polluting the global object should definitely work, but I wanted something where I don't have to rely on it so came up with this:
https://github.com/OpenAPITools/openapi-generator/pull/7455
Feedback would be most welcome.

**Comment by macjohnny** [comment]
fixed by https://github.com/OpenAPITools/openapi-generator/pull/7455

**Comment by Bessonov** [comment]
What's about typescript-fetch?

**Comment by macjohnny** [comment]
@Bessonov you are invited to apply to fix to the typescript-fetch generator as well.
