### ISSUE TITLE
[DefaultCodegen]Identifying Primitive types in response of Maps and Array types

### ISSUE THREAD

**Issue by etherealjoy** [OpenAPITools/openapi-generator#294]
##### Description

In the DefaultCodegen.java 
```java
public CodegenResponse fromResponse(String responseCode, ApiResponse response)
```
the map or array type is set when the response is indeed an array or a map.
Under **operations** are only **isListContainer** and **isMapContainer** available.
This is insufficient when for certain langs the instantiation of primitive variables is different from objects.
So inside the **response** are several variables available for use, but it is unclear if for example below

```c++
    {{#responses}}
    {{#-first}}
    foreach(QJsonValue obj, jsonArray) {
        {{^isString}}
        {{/isString}}
    }
    {{/-first}}
    {{/responses}}
```
isContainer is set, but should the isString for example be set as well?
This will allow treatment of array or map members differently from complex types which are generic Object instantiation types
How to approach? 

```yaml
paths:
  /example:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                    type: string
```
##### openapi-generator version

**master**

**Comment by etherealjoy** [comment]
The type of the items could string, boolean or something,
But in the mustache, I want to know how to check which is the baseType.
for models and so on, I could just use {{#isString}} or {{#isInteger}}
How could I do this for responses
By knowing this I could instantiate the items differently in the mustache, because some langs like C++ needs memory allocation for non primitive types but does not need for int or boolean for example.

I changed the default codegen to set the isString or isInteger even though the type is array, but the baseType is some primitive type, but I am not sure this is a good approach.

**Comment by etherealjoy** [comment]
Copy of #329

**Comment by jmini** [comment]
See also #20. My take is that with `4.0.0` we need to refactor a lot those `Codegen`-Objects to remove redundancy, to provide similar features where it make sense.

This is a lot of work...

OAS3 did a lot of work in this direction (Schema are now used everywhere).

**Comment by etherealjoy** [comment]
I see. But we have to do something eventually, because for languages which don't have type inspection and reflection it is harder to detect return types from the API call.
C++ being one prime example.

**Comment by etherealjoy** [comment]
Indeed it is for response. Little difficult to do this for C++ for example.
The generators we have for C++ cannot handle responses which are arrays of primitive types.
