### ISSUE TITLE
[BUG] [Ruby] UNKNOWN_BASE_TYPE and object recognition

### ISSUE THREAD

**Issue by rhuanbarreto** [OpenAPITools/openapi-generator#2955]
##### Description

If I have a RequestBody:

```yaml
components:
  requestBodies:
    LoginBody:
      description: A JSON object for user authenticate
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              username:
                type: string
                example: rune
                description: username of microsoft's active directory
              password:
                type: string
                example: abc123
                description: password of microsoft's active directory
```

I get an UNKNOWN_BASE_TYPE object that breaks the API client.

I don't want to use a model because the User model is not defined on the backend but on the Active Directory.

In order to fix this I must create an user model and declare a $ref:

```yaml
    LoginBody:
      description: A JSON object for user authenticate
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
```

Then it works.

##### openapi-generator version

4.0.1-SNAPSHOT

##### Suggest a fix

The Ruby generator should recognize the objects without schema as a common class with properties and not try to put an inline class name on it. Responses and request bodies not always are fixed classes like this 401 unauthorized response:

```yaml
paths:
  /test:
    get:
      responses:
        '401':
          $ref: "#/components/responses/Unauthorized"
components:
  responses:
    Unauthorized:
      description: Unauthorized. You must add the token on the header.
      content:
        application/json:
          schema:
            type: string
            example: { message: 'Unauthorized' }
```

```json
{
  "message": "Unauthorized"
}
```

This response is just a simple informative object. There is no schema into it. Instead it's being generated as inline_response401.rb

**Comment by IvoMerchiers** [comment]
The same issue also occurs when generating code for `python-flask`.
@rhuanbarreto his solution works in that case as well.

**Comment by rhuanbarreto** [comment]
@cliffano @zlx @autopp Any thoughts?

**Comment by autopp** [comment]
@rhuanbarreto Thank you for report this issue and I'm sorry for late reply.
Your suggestion is looks good. I'll try to fix in the near future. (And of course we also welcome PR)

**Comment by rhuanbarreto** [comment]
I would love to have the knowledge to change it, but Java is not my main language. But if someone stumbles upon this issue and has the knowledge, I would appreciate a fix!

**Comment by toonsevrin** [comment]
Microsoft dynamics Business Central API also has tons of unknown types that should not be unknown:
https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/dynamics-open-api

[Download spec](https://docs.microsoft.com/en-us/dynamics-nav/api-reference/v1.0/contracts/bcoas1.0.yaml)

An example is the postSalesInvoice operation, the body is mapped to an unknown_base_type, while it is properly specified.

**Comment by wing328** [comment]
Hi all, please give it another try with the latest master as the issue should have been addressed.

Happy to reopen the issue if it's not the case.
