### ISSUE TITLE
[BUG][Typescript axios] Generated call to accessToken doesn't match type definition

### ISSUE THREAD

**Issue by bebsworthy** [OpenAPITools/openapi-generator#2956]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?   4.0.1#master
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

The code generated for accessToken is :

```
// http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }
```
(As per https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache)

`configuration.accessToken()` is called without parameters

Type definition for accessToken is
```
accessToken?: string | ((name: string, scopes?: string[]) => string);
```

`name` is a mandatory parameter
Typescript outputs the following error `semantic error TS2554 Expected 1-2 arguments, but got 0.`

Type definition for accessToken should probably be:
```
accessToken?: string | ((name?: string, scopes?: string[]) => string);
```

or, if the parameters are never used:
```
accessToken?: string | (() => string);
```

- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

**Comment by mAAdhaTTah** [comment]
Ran into this same issue. Trying to generate a TS client that works between React Native & Web and having no luck. Axios is the closest but this is blocking. I could PR this, but should the `accessToken` type change based on if it's `BasicBearer` or should the call site change to include those values?

**Comment by macjohnny** [comment]
@mAAdhaTTah a PR is very welcome

**Comment by macjohnny** [comment]
cc @nicokoenig
