### ISSUE TITLE
[BUG] Kotlin with snake case parsing from JSON

### ISSUE THREAD

**Issue by catluc** [OpenAPITools/openapi-generator#2961]
#### Bug  
A simple json as this one {cod_state_region: "whatever"}, moshi is not able to parse this String to the property in my class. i just read out on moshi, and the correct way to implement the mapping for snake_case and camel case in kotlin is to use the KotlinJsonAdapterFactory class.

At the moment of writing this i am on openapi-generator-maven-plugin V4.0.0 beta 3 and I tested the last release v4.0.0 and the problem is still the same

##### Description

My suggestion is to change the ApiClient mustache.
This method 

 ```
protected inline fun <reified T: Any?> responseBody(body: ResponseBody?, mediaType: String? = JsonMediaType): T? {
        if(body == null) {
            return null
        }
        val bodyContent = body.string()
        if (bodyContent.length == 0) {
            return null
        }
        return when(mediaType) {
            JsonMediaType -> Moshi.Builder().add(object {
                    @ToJson
                    fun toJson(uuid: UUID) = uuid.toString()
                    @FromJson
                    fun fromJson(s: String) = UUID.fromString(s)
                })
                //.add(ByteArrayAdapter())
                .build().adapter(T::class.java).fromJson(bodyContent)
            else ->  TODO("responseBody currently only supports JSON body.")
        }
    }
```

Into this method:
```
protected inline fun <reified T: Any?> responseBody(body: ResponseBody?, mediaType: String = JsonMediaType): T? {
        if(body == null) return null
        return when(mediaType) {
            JsonMediaType -> Moshi.Builder()
                    .add(KotlinJsonAdapterFactory())
                .build().adapter(T::class.java).fromJson(body.source())
            else -> TODO("responseBody currently only supports JSON body.")
        }
    }

**Comment by karismann** [comment]
hello @catluc, could you please retry with latest snapshot version ? that should be fixed. Thanks.

**Comment by catluc** [comment]
just checked this commit: [[Kotlin] Fix parse error when using custom field names with @JSON ](https://github.com/OpenAPITools/openapi-generator/commit/1e06d7fe88dc8e61c2d2cf234daf1f1330d5333c) and it looks ok to me
