### ISSUE TITLE
[REQ] Expose all top-level config options as properties

### ISSUE THREAD

**Issue by InfoSec812** [OpenAPITools/openapi-generator#2962]
### Is your feature request related to a problem? Please describe.

Some of the options in the CodeGenMojo are exposed such that you can pass the property on the Maven command-line using `-Dopenapi.generator.maven.plugin.<property>`, but not all. I propose that ALL of those properties should be exposed and that the documentation should be updated to reflect the property name as well.

## Describe the solution you'd like

Modify the CodeGenMojo to include property exposure in all @Parameter annotations

## Describe alternatives you've considered

None that I can think of

## Additional context

I can submit a PR for this if it is helpful.

**Comment by wing328** [comment]
@InfoSec812 thanks for the suggestion. 

@jimschubert has been performing some works to enhance/refactor the options: https://github.com/OpenAPITools/openapi-generator/pull/2946

Please review and let us know if you've any feedback

**Comment by InfoSec812** [comment]
> @InfoSec812 thanks for the suggestion.
> 
> @jimschubert has been performing some works to enhance/refactor the options: #2946
> 
> Please review and let us know if you've any feedback

@wing328 The CodeGenMojo is not addressed in that change, but I have just submitted a PR which addresses exposing the CodeGenMojo configuration settings as properties where appropriate and updated the README to make it clear how it works.

**Comment by jimschubert** [comment]
The changes in #2946 shouldn't have an effect on the public api usage of CodegenConfigurator (which I'm assuming was the concern).

Glancing over the PR, it looks like a maven specific way of defining settings as `properties` rather than `configuration`. I agree there shouldn't be any overlap between the two
