### ISSUE TITLE
Review test results

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#297]
##### Description

There are some tests, which throw errors but doesn't affect the test result: 
```
[ERROR] Error fetching link: /home/ubuntu/OpenAPITools/openapi-generator/modules/openapi-generator/home/ubuntu/OpenAPITools/openapi-generator/modules/openapi-generator-cli/target/apidocs/package-list. Ignored it.
```

We should either fix these or remove these if the tests are no longer relevant.

##### openapi-generator version

Latest master

##### Steps to reproduce

Check CI test results (log)

##### Suggest a fix/enhancement

If anyone wants to work on this, please reply to let us know.

**Comment by jimschubert** [comment]
This has been resolved since #2399. The error wasn't tests, but javadoc trying to find a link to the repository. See http://maven.40175.n5.nabble.com/quot-Error-fetching-link-quot-when-running-Javadoc-Report-but-can-t-find-link-td5149790.html
