### ISSUE TITLE
[BUG] Unnecessary Parenthesis on Python Client Code

### ISSUE THREAD

**Issue by wy193777** [OpenAPITools/openapi-generator#2977]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The parenthesis around `data` is unnecessary. Can causing mypy linter give `undefined variable 
https://github.com/OpenAPITools/openapi-generator/blob/0eb385c0d6497c38c09b42158b2d66109b78b15b/modules/openapi-generator/src/main/resources/python/api.mustache#L57

##### openapi-generator version

Current code on master.

##### Suggest a fix

Delete the unnecessary parenthesis.

**Comment by wing328** [comment]
@wy193777 thanks for reporting the issue. Can you please file a PR so that we can review the fix more easily?

**Comment by wy193777** [comment]
Sure, will do.

**Comment by wy193777** [comment]
Has been fixed by merging #2985 .
