### ISSUE TITLE
[REQ][Java-okhttpgson] Include API's Http response codes and their corresponding description and response headers in the documentation

### ISSUE THREAD

**Issue by saigiridhar21** [OpenAPITools/openapi-generator#2994]
### Is your feature request related to a problem? Please describe.

The possible HTTP response codes of each API method are not specified on javadocs. It is also better to include description of each response code and corresponding response headers in the documentation.
This will help the clients of library to easily go through the documentation of each API method on Eclipse's intellisense.

## Describe the solution you'd like

Use javadocs custom tag and define HTTP response codes along with their corresponding description and response headers on each API method.

**Comment by jmini** [comment]
@saigiridhar21: this `@http.response.details` you have introduced is causing me trouble when I try to generate the javadoc:
https://github.com/OpenAPITools/openapi-generator/issues/3299

Can you give me some input?
