### ISSUE TITLE
[REQ][csharp] Make API response's headers case insensitive

### ISSUE THREAD

**Issue by saigiridhar21** [OpenAPITools/openapi-generator#2997]
### Is your feature request related to a problem? Please describe.

As HTTP headers are case insensitive, it is better to make API response's header dictionary as case insensitive. This is a good to have feature.

## Describe the solution you'd like

Use comparer in the API response's headers dictionary

**Comment by wing328** [comment]
@saigiridhar21 thanks for the PR, which has been merged into master.

For your upcoming PRs, you can use keywords to close the corresponding issue: https://help.github.com/en/articles/closing-issues-using-keywords
