### ISSUE TITLE
Use Liberapay for funding

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#300]
I am codirector of the foundation https://liberapay.com/ and it would be very interesting to use it for funding `openapi-generator`.

Liberapay is community driven, fully open source and funded on Liberapay. For those who know, it is a fork of http://gratipay.com/ (old gittip) which closed recently.

**Comment by MartinDelille** [comment]
I created a team: https://liberapay.com/OpenAPITools/

**Comment by jimschubert** [comment]
Closing this as we've gone with Open Collective.

**Comment by MartinDelille** [comment]
I don't see why there should be only one funding option. A store accept cash or credit card to let the customer choose the best way to pay. I think we can apply that to funding too.

**Comment by MartinDelille** [comment]
I just wanted to add that Open Collective collect fees additionnaly to stripe (the same payement processor than Liberapay): https://opencollective.com/pricing

Liberapay is self sufficient since its early start so it is here to stay.

I'm currently part of [the team](https://liberapay.com/OpenAPITools/) with @wing328  but I can either leave it as I am not a funding member of openapi-generator or take only a very small amount since my contribution are not so big.
