### ISSUE TITLE
[Go][Client] Multipart array elements gets rendered as struct.String()

### ISSUE THREAD

**Issue by Miroku87** [OpenAPITools/openapi-generator#3043]
##### Description

When generating a Go client that has a 'requestBody' of the 'multipart/form-data' type, properties which are arrays of **objects** gets rendered in the HTTP request body as plain struct.String() values and not with JSON formatted text.
This happens only when the content of the `requestBody` is stated under the `paths:` property of the YAML.
If the contents are state inside `components/requestBodies` the issue does not occur (a different issue occurs but I will make a different issue about that #3045 ).

In the case a property of the `form-data` contains an object this object will become an interface and this interface will have to be rendered as a string to be inserted in the `localVarFormParams` struct, so the `parameterToString` function will be used. Nothing unusual here.
The unusual thing is that, when calling the `parameterToString` function, the `collectionFormat` parameter is set to `csv` causing the program to render the object as if printing it with `fmt.Printf('%v',userpayload)`.

##### openapi-generator version

4.0.1-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
servers:
- url: http://petstore.swagger.io/v2
info:
  description: 'This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For
    this sample, you can use the api key `special-key` to test the authorization filters.'
  version: 1.0.0
  title: Swagger Petstore
paths:
  "/user/createWithArray":
    post:
      tags:
      - user
      summary: Creates list of users with given input array
      description: ''
      operationId: createUsersWithArrayInput
      responses:
        default:
          description: successful operation
      requestBody:
        content:
          multipart/form-data:
            schema:
              "$ref": "#/components/schemas/UserPayload"
  
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      xml:
        name: User
        
    UserPayload:
      type: object
      properties:
        foo:
          type: string
        bar:
          type: array
          items:
            "$ref": "#/components/schemas/User"
```
##### Command line used for generation

I'm using the docker generator:

```
sudo docker run --rm -v \
    ${PWD}:/local \
    openapitools/openapi-generator-cli generate \
    --package-name foo \
    -i /local/openapi.yaml \
    -g go \
    -o /local
```

##### Steps to reproduce

Use the above command to generate a client passing the above YAML as input.

##### Related issues/PRs

#2964 
#3045 

##### Suggest a fix/enhancement

Instead of passing `"csv"` as a `collectionFormat` parameter to the `parameterToString` function the normal thing to do would be to print the object as a JSON string (which the `parameterToString` does not yet support as said in this issue: #2964 )

I think the line in the template is this one: 
https://github.com/OpenAPITools/openapi-generator/blob/e5a0d183744c3a7d331b77af4d451ff36cc3da16/modules/openapi-generator/src/main/resources/go/api.mustache#L140

**Comment by thiagoarrais** [comment]
@Miroku87: is it feasible to test your case against #2965? The approach for this PR was very similar to you suggested fix. It may fix your issue.

**Comment by Miroku87** [comment]
@thiagoarrais sorry for the late reply! Yes we can try and test it but I don't think that #2965 will fix the issue because the `createUsersWithArrayInput` function calls the `parameterToString` function by passing `csv` implicitly. If it passed an empty string then #2965 would have fixed it but it's not the case.

Also, by looking at the java code that fills the moustache templates I think that the real issue is to be found around here:
https://github.com/OpenAPITools/openapi-generator/blob/314f18a2c142e20b3d3d33a3d5b63318d765465d/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L2986

I'm sorry if I'm not very specific but I'm new to the project so I still have to learn how to move inside the code.
Also I'm having issue building the jar. Can I ask you a hand by private message?

**Comment by thiagoarrais** [comment]
Sure. You can find my email address in my profile.

**Comment by thiagoarrais** [comment]
Finally got around to doing my own testing and it seems that #2965 does indeed fix this.

**Comment by Miroku87** [comment]
Great!
