### ISSUE TITLE
[BUG] Link of `.openapi-generator-ignore` in FAQ wiki is not found.

### ISSUE THREAD

**Issue by yuji38kwmt** [OpenAPITools/openapi-generator#3057]
##### Description
https://github.com/openapitools/openapi-generator/wiki/FAQ#how-to-skip-certain-files-during-code-generation

Following link of `.openapi-generator-ignore` is not found.
>.openapi-generator-ignore is auto-generated by default.

https://github.com/openapitools/openapi-generator/blob/master/samples/client/petstore/php/.openapi-generator-ignore

**Comment by wing328** [comment]
Fixed :)
