### ISSUE TITLE
[REQ] Add Api key auth to aspnet core server package

### ISSUE THREAD

**Issue by MBcom** [OpenAPITools/openapi-generator#3088]
### Is your feature request related to a problem? Please describe.
* on generating the aspnetcore server package - (bearer) authentication are ignored and roles/scopes specfied for each operation are ignored too
* it would be time saving if the generator would generate the missing annotations

## Describe the solution you'd like

* if there is an api key authentication specified  then annotate with `[Authorize(Rules= "...")]`
* add an `IAuthorizationRequirement` handler class
* and add the needed handler to `Startup.cs` file

## Describe alternatives you've considered

-

## Additional context

see the linked pull request for my suggestions

**Comment by InfoSec812** [comment]
@MBcom Looks like your PR was merged, does that mean this issue is resolved? If so, could you please close?
