### ISSUE TITLE
[typescript-fetch][4.0.X] Migration guide from 3.X.X to 4.X.X

### ISSUE THREAD

**Issue by dalinarkholin** [OpenAPITools/openapi-generator#3102]
### Is your feature request related to a problem? Please describe.

[typescript-fetch][4.0.X] `Cannot read property 'middleware' of undefined`

After upgrading from 3.3.3 to 4.0.1 and resolving file pathing(api.ts was no longer a thing) I get the above error. There is something up with `this.configuration` not existing in the Configuration Class even though I pass it during instance creation of an api. I modified the constructor to include this.configuration = configuration(param that comes into the class constructor) and that gets past that specific issue. But then there are additional errors around not sending the body of the request, basePath is undefined etc.

This was all working pre 4.X.X and I have not found any documentation on what breaking changes were introduced in terms of the configuration, middleware, etc.

I am frustrated because I am using homebrew and can't seem to go back to using 3.3.3 easily since there are no versions published other than the latest.

## Describe the solution you'd like

Some sort of guide would be nice when breaking changes are introduced(this could live in the openapi generator docs on a per generator basis. Here [https://openapi-generator.tech/docs/generators/typescript-fetch](https://openapi-generator.tech/docs/generators/typescript-fetch) for example.

1. homebrew versioning so I can switch between openapi-generator versions
2. migration guide so I have some idea where I need to start. 
3. additional documentation around breaking changes.

If this isn't enough information let me know, I can try to provide more, but I need to go back to using 3.3.X for now. Thanks for all the hard work here.

**Comment by dalinarkholin** [comment]
If anyone else comes across this:

My workaround to switch openapi-generator versions with homebrew was to:

- copy the contents of [https://raw.githubusercontent.com/Homebrew/homebrew-core/27b6ca79a00a857f0d395642b9b1db42ba91f7c1/Formula/openapi-generator.rb](https://raw.githubusercontent.com/Homebrew/homebrew-core/27b6ca79a00a857f0d395642b9b1db42ba91f7c1/Formula/openapi-generator.rb) and place them in a local file(anywhere) with the same name as the brew package so: `openapi-generator.rb`
- Then edit the url in the file. replace version with the one you want.
- Then `brew unlink openapi-generator`
- Then `brew install --build-from-source ./openapi-generator.rb`
- You will get a error about a shaw mismatch. something like:
```
Expected: 3e542fefa969975c6174c52f669ccccd7801d27572cabc34036bb3988dddf4b9
  Actual: 456ef6f15808e9fa8573ec04f6e6506a25047f6243a61ab8ea5aecd70305c21b
```
- Replace the sha256 line with the actual sha in the openapi-generator.rb file we made. Its right below the url line.
- Then `brew install --build-from-source ./openapi-generator.rb` again

and you should be good to go. If not...good luck. :)

**Comment by macjohnny** [comment]
@wing328 is there no possibility to install a specific version with homebrew?

**Comment by wing328** [comment]
I tried but seems like there's no easy way.

`npm` provides an easier way to switch back to an old version: https://www.npmjs.com/package/@openapitools/openapi-generator-cli

**Comment by wing328** [comment]
>  I modified the constructor to include this.configuration = configuration(param that comes into the class constructor) and that gets past that specific issue. But then there are additional errors around not sending the body of the request, basePath is undefined etc.

Can you please share the details of the errors? We definitely want to make the migration easier for everyone.

Here is a list of TS fetch PRs: https://github.com/OpenAPITools/openapi-generator/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22Client%3A+TypeScript%22+is%3Amerged+fetch

We will need to determine which one breaks your use case and how to remediate (e.g. roll back the change)

**Comment by dalinarkholin** [comment]
@wing328 I dug into this a bit more and found it was due to a transpiling issue with babel 7. I needed to add `["@babel/plugin-transform-typescript"],` to my list of plugins in babelrc so that the class constructor params would get set properly on instance creation. So I guess specific to my setup. My bad. At least this is issue documents the problem. Im good if you guys are.

**Comment by macjohnny** [comment]
@dalinarkholin thanks for the feedback. so I close this issue as is not a general problem of the generated code or at least it can be solved with an appropriate setup.
