### ISSUE TITLE
[Announcement][Kotlin][Retrofit][Coroutines] New generator: kotlin-retrofit

### ISSUE THREAD

**Issue by kroegerama** [OpenAPITools/openapi-generator#3135]
👋 Hello OpenAPI-Team!

I created a new generator called "kotlin-retrofit". Are you guys interested in integrating it into your repository and helping me complete/improve it?

**Generator branch: [kroegerama/kotlin-retrofit](https://github.com/kroegerama/openapi-generator/tree/kotlin-retrofit)**

Example project: [Generated petstore](https://github.com/kroegerama/kotlin-retrofit-generated)

## The main features are:
* generates a ready to use module for Android Studio
* only model classes, api classes and two helper classes are generated
* supports per-route authentication (for now: ApiKey, Basic, Bearer)
* uses kotlin data classes
* uses [moshi-codegen](https://github.com/square/moshi#codegen) to parse/serialize json
* uses [retrofit 2.6](https://square.github.io/retrofit/) with support for suspend functions

The petstore.yaml works just fine right now. Also a few other apis that I tested.

## Todos: <sub><sup>(also see README.mustache)</sup></sub>
* **done (allOf)** ~~add better support for json schema inheritance (allOf, anyOf, etc.)~~
* support for `collectionFormat` (e.g. csv)
* add OAuth functionality
* update proguard/p8 rules for okhttp/moshi
* option to switch coroutine generation off
* add documentation
* add tests

@jimschubert @wing328 @karismann @Zomzog

**Comment by wing328** [comment]
> I created a new generator called "kotlin-retrofit". Are you guys interested in integrating it into your repository and helping me complete/improve it?

Yes, we are definitely interested in adding more generators to benefit the community.

I wonder if you can open a PR to start with and we'll review based on what you've created so far.

**Comment by NicolaeGP** [comment]
@kroegerama check out #5076  Perhaps it would be something simple for you to add since you already have support for coroutines in your generator.

**Comment by kroegerama** [comment]
You may want to try my new project:
https://github.com/kroegerama/openapi-kgen

It's a new generator, written entirely from scratch. A generated example can be found here:
https://github.com/kroegerama/openapi-kgen-generated

**Comment by djensen47** [comment]
First, just wanted to say that this is a wonderful, useful project and I appreciate all the hard work put into it.

Second, my querstion is why did this get closed? Is there any possibility of getting kroegerama/openapi-kgen merged into this project?
