### ISSUE TITLE
[BUG] [Spring] Generated API interface treats multipart arrays as a single file

### ISSUE THREAD

**Issue by galleog** [OpenAPITools/openapi-generator#3139]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generated API interface for multipart arrays contains a single MultipartFile instead of a list. Besides any MultipartFile argument should have @RequestPart annotation instead of @RequestParam.

##### openapi-generator version

Tested with 4.0.0 version of https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.0'
info:
  version: 1.0.0
  title: MultipartFile test
paths:
  /multipart-array:
    post:
      tags:
        - multipart
      description: MultipartFile array test
      operationId: multipartArray
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '204':
          description: Successful operation
  /multipart-single:
    post:
      tags:
        - multipart
      description: Single MultipartFile test
      operationId: multipartSingle
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '204':
          description: Successful operation
```

##### Command line used for generation

Maven plugin was used:
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>${openapi-generator-maven-plugin.version}</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${basedir}/src/main/resources/multipart.yaml</inputSpec>
                <generatorName>spring</generatorName>
                <modelPackage>org.openapi.test.model</modelPackage>
                <apiPackage>org.openapi.test.api</apiPackage>
                <library>spring-cloud</library>
                <generateSupportingFiles>false</generateSupportingFiles>
                <generateApiTests>false</generateApiTests>
                <configOptions>
                    <interfaceOnly>true</interfaceOnly>
                    <dateLibrary>java8</dateLibrary>
                    <java8>true</java8>
                    <booleanGetterPrefix>is</booleanGetterPrefix>
                    <useBeanValidation>true</useBeanValidation>
                    <useTags>true</useTags>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### Steps to reproduce

Generate MultipartApi interface using the plugin configuration listed above. Both multipartArray and multipartSingle methods contains a single MultipartFile parameter with @RequestParam annotation.

##### Suggest a fix

Looks like the mustache template formParams.mustache ignores arrays.

**Comment by ips219** [comment]
I am not sure if it is the best solution.... But for me this worked....

1-Download templates for JavaSpring to local project folder from [](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/JavaSpring)

2-Include the templateDirectory parameter in the plugin configuration
```
                            <templateDirectory>${project.basedir}/templates/JavaSpring</templateDirectory>
                            <configOptions>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <dateLibrary>java8</dateLibrary>
                                <sourceFolder>api</sourceFolder>
                                <library>spring-boot</library>
                                <delegatePattern>true</delegatePattern>
                            </configOptions>
                            <output>target/generated-sources</output>
```
3-Fix the related templates: api.mustache, apiDelegate.mustache, exampleReturnTypes.mustache, formParams.mustache, formParams.mustache by replacing all **MultipartFile** entries by **{{#isListContainer}}List<{{/isListContainer}}MultipartFile{{#isListContainer}}>{{/isListContainer}}**
