### ISSUE TITLE
[rust-server] unable to handle >32 regexes

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#314]
##### Description

See https://github.com/swagger-api/swagger-codegen/issues/8201#issuecomment-390270329 - if the swagger spec has more than 32 regexes, we generate invalid Rust. This is because we generate a tuple/fixed length slice(?), and the Rust standard library only copes with tuples/fixed length slices(?) up to size 32.

We should fix this and then add a test.

(Note: this part of a set of issues from swagger-codegen. I didn't fix this as part of the move to openapi-generator. Thus I strongly suspect rust-server in openapi-generator also suffers the same problem. I'm not planning on working on this at the moment - contributions gratefully welcomed)

##### Suggest a fix/enhancement

I suspect the fix will be to stop using tuples/fixed length slices. Instead, maybe a `Vec` might work? It'll be a bit less efficient, but I don't think that will have a significant effect.

Testing this may be _fun_. I'd recommend starting to split up the test samples for `rust-server`. That way, we can have a spec that just tests for this issue, without ending up with a single test spec of absurd length.

**Comment by richardwhiuk** [comment]
Fixed by https://github.com/OpenAPITools/openapi-generator/pull/3494
