### ISSUE TITLE
[BUG][CSHARP] generator defines AccessToken but never includes it in the request if present?

### ISSUE THREAD

**Issue by jamesrusso** [OpenAPITools/openapi-generator#3143]
The csharp generator includes reference to an AccessToken Property for use with OAuth2 authentication, however nothing is done with the value in the APIClient. I would expect if this value is set, the required Authorization header would be included (ex: Authorization: Bearer {token}). 

```csharp
/// <summary>
/// Gets or sets the access token for OAuth2 authentication.
/// </summary>
/// <value>The access token.</value>
public virtual string AccessToken { get; set; } 
```
Unless I am misunderstanding the intended usage?

**Comment by jimschubert** [comment]
@jamesrusso can you provide details about which C# generator you're using (there are a few)?

In the newer C# generator, the `AccessToken` is applied automatically in generated API code. see:  

https://github.com/OpenAPITools/openapi-generator/blob/314f18a2c142e20b3d3d33a3d5b63318d765465d/samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Api/PetApi.cs#L602

You ask specifically about ApiClient… we don't set this automatically in ApiClient for a few reasons. First, OpenAPI Specification allows for different authorization schemes for different endpoints. Reusing a client which automatically sets the token could lead to programmatic and/or multi-threading errors, and I've designed the new ApiClient in an attempt to minimize potential for user error.

It's also possible for multiple OAuth2 strategies and flows to be used throughout the generated code, which means we need to set the token at the endpoint call. Currently, the C# ApiClient only supports setting the AccessToken and applying it as a bearer token, so it doesn't automate any OAuth 2.0 flows… this is intended to be done by the consumer.

**Comment by jamesrusso** [comment]
@jimschubert Thanks Jim. 

I agree, I guess I was just confused as to why it was there but never referenced in the code. 

I suppose it does make sense to include it in the configuration so it's available if you implement the partial method InterceptRequest to add the header (as I have done). 

I am using the generator provided by "csharp". (ex -g csharp) with default options (except package name). How can I make use of the updated client which would generate the API code to include the access token on each method? I am using openapi-generator via npx.

```
npx openapi-generator version
4.0.0
```

**Comment by jimschubert** [comment]
I apologize for not expanding on my previous comment, I was writing out on mobile.  By "newer C# generator", I was referring to the rewrite I had preformed on all generators except the C# 2.0 client. The generator you're using should support this flow directly.

I haven't used node for quite a while (before npx was available), so to avoid any snafu on my part, here's what I've done:

```
npm install @openapitools/openapi-generator-cli@cli-4.0.0 -g

openapi-generator generate -g csharp -o generated \
    -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml

grep -B 4 -A 5 AccessToken  generated/src/Org.OpenAPITools/Api/PetApi.cs | head -20
            }

            // authentication (petstore_auth) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
--
            {
                localVarHeaderParams["Authorization"] = "Bearer " + this.Configuration.AccessToken;
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
--
--
            }

            // authentication (petstore_auth) required
            // oauth required
```

You should see something similar to the code above in your API implementations in both the synchronous and asynchronous implemetnations. If you don't, please check that security is setup correctly. A subset of the OpenAPI 2.0 example spec document used above:

```
swagger: '2.0'
info:
  description: "This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\"
  version: 1.0.0
  title: OpenAPI Petstore
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: petstore.swagger.io:80
basePath: /v2
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
schemes:
  - http
paths:
  /pet:
    post:
      tags:
        - pet
      summary: Add a new pet to the store
      description: ''
      operationId: addPet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet object that needs to be added to the store
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        '200':
          description: successful operation
        '405':
          description: Invalid input
      security:
        - petstore_auth:
            - 'write:pets'
            - 'read:pets'
securityDefinitions:
  petstore_auth:
    type: oauth2
    authorizationUrl: 'http://petstore.swagger.io/api/oauth/dialog'
    flow: implicit
    scopes:
      'write:pets': modify pets in your account
      'read:pets': read your pets
```

To have the `AccessToken` assignment applied to the generated code, you'd need both the `securityDefinitions.petstore_auth` type of structure as well as the `paths['/pet'].security[0]['petstore_auth']`. Note that `security` is an array rather than an object (I'm not too sure if swagger-parser supports Array | Object here).

If you're using OpenAPI 3.0+, could you provide a minimal example of your spec? We can take a look to see if there's something wonky with the auth support in 3.0.

**Comment by jamesrusso** [comment]
I am using OpenAPI 3.0, I'll see what I can come up with.

**Comment by jamesrusso** [comment]
This is generating the correct code on 4.0.1 with the AccessToken being included. Thanks for your help. @jimschubert 

Here is what I came up with for openapi-3.0. I'm still not sure all the details, but still working through it.. But it is generating the code correctly.


```
components:
  securitySchemes:
   OAuth2Scheme:
      type: oauth2
      flows:
       clientCredentials:
        tokenUrl: https://example.com/api/oauth/dialog
        scopes:
          sync:begin: begin a sync cycle
          sync:end: finalize a sync cycle
          encounters:put: add encounters
          encounters:get: obtain encounters
          metadata:put: set metadata
          metadata:get: obtain metadata
```
