### ISSUE TITLE
[BUG] Import Mapping seems to not work with typescript-angular

### ISSUE THREAD

**Issue by filipvh** [OpenAPITools/openapi-generator#3149]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))
##### Description

I used importMapping in combination with the typescript-angular generator.
Here is a redacted config file:
```json
{
  "npmName": "the-package-name",
  "npmVersion": "1.8.0",
  "ngVersion": "1.7.0",
  "modelFileSuffix": ".type",
  "npmRepository" : "http://domain/is/redacted",
  "snapshot" : false,
  "importMappings": {
        "EnumValue":"some-other-package"
  }
}
```

##### openapi-generator version

4.0.1

##### What happens?

 - The 'EnumValue' is not generated (is missing from model folder) => OK
 - In an other type/interface EnumValue is still refferenced locally => NOK

```js
import { EnumValue } from './enumValue.type';
```

##### What was expected?

 - The 'EnumValue' is not generated (is missing from model folder)
 - In an other type/interface EnumValue refferences the external package

```js
import { EnumValue } from 'some-other-package';
```

##### Command line used for generation

```
generate -i model.yaml -g typescript-angular -c config.json -o out
```

**Comment by macjohnny** [comment]
@filipvh would you like to try and fix this issue?

**Comment by filipvh** [comment]
@macjohnny  I can try. Wanted to make sure that it is an issue and that there isn't a duplicate i couldn't identify. If one would expect it to do what I expect... :-)

**Comment by scottydawg** [comment]
@filipvh - I'm up against this issue as well for the `TypeScriptNodeClientCodegen`. I'm going to look into a fix unless you've already got something going here that might address both.

In the case of the Node client generator, [these mappings seem to be intentionally obliterated in the constructor](https://github.com/OpenAPITools/openapi-generator/blame/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptNodeClientCodegen.java#L48). The Angular generators don't clear the importMappings like that.

**Comment by scottydawg** [comment]
I was mistaken about the Angular generators; the abstract class that these TypeScript generators all specialize also [clears the initMappings in the constructor.](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java#L62)

**Comment by scottydawg** [comment]
@macjohnny @filipvh - I've [created a PR](https://github.com/OpenAPITools/openapi-generator/pull/3469) that addresses this issue for the Node client generator. It should be a similar fix for the Angular (and other TypeScript) generators. It might be worth putting this change in the abstract class so that all the TS generators can pick it up, but I wanted a small impact crater for now.

**Comment by macjohnny** [comment]
anyone interested in porting https://github.com/OpenAPITools/openapi-generator/pull/3469 to the abstract typescript generator?
