### ISSUE TITLE
[BUG][RUST-SERVER] Can't generate multiple responses options with both content and headers

### ISSUE THREAD

**Issue by Herrera93** [OpenAPITools/openapi-generator#3158]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

There is a problem generating the the responses options when other than the first response have both `content` and `headers`.
For example: 

```yaml
  /xml_other:
    post:
      requestBody:
        content:
          application/xml:
            schema:
              $ref: "#/components/schemas/anotherXmlObject"
      responses:
        "201":
          description: "OK"
          headers:
            X-Random-Header:
              description: Random header
              schema:
                type: string
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
```

This generates the correct output:

```rust
#[derive(Debug, PartialEq)]
pub enum XmlOtherPostResponse {
    /// OK
    OK { body: String, x_random_header: String } ,
    /// Bad Request
    BadRequest ,
}
```

but if we add both `content` and `headers` to the `400` response like this:

```yaml
/xml_other:
    post:
      requestBody:
        content:
          application/xml:
            schema:
              $ref: "#/components/schemas/anotherXmlObject"
      responses:
        "201":
          description: "OK"
          headers:
            X-Random-Header:
              description: Random header
              schema:
                type: string
          content:
            application/json:
              schema:
                type: string
        "400":
          description: Bad Request
          headers:
            X-Random-Header:
              description: Random header
              schema:
                type: string
          content:
            application/json:
              schema:
                type: string
```

it generates this incorrect output:

```rust
#[derive(Debug, PartialEq)]
pub enum XmlOtherPostResponse {
    /// OK
    OK { body: String, x_random_header: String } ,
    /// Bad Request
    BadRequest , x_random_header: String } ,
}
```
##### openapi-generator version

4.0.2-SNAPSHOT

##### Command line used for generation

`./bin/rust-server-petstore.sh`

##### Steps to reproduce

Add two or more responses with both `content` and `headers`.

##### Related issues/PRs

None

##### Suggest a fix

I fixed this by removing the `{{#-first}{{/-first}}` section on [here](https://github.com/OpenAPITools/openapi-generator/blob/32b8d7fee7886c13a8ccd9523dd31791cdf6371b/modules/openapi-generator/src/main/resources/rust-server/lib.mustache#L46) but I don't know if there is another purpose of this.

**Comment by richardwhiuk** [comment]
Fixed by https://github.com/OpenAPITools/openapi-generator/pull/3669
