### ISSUE TITLE
[BUG] maven compile error: cannot find strictSpec

### ISSUE THREAD

**Issue by forest-yang** [OpenAPITools/openapi-generator#3166]
I've used 4.0.0-beta2 plugin before, now I want to upgrade plugin to 4.0.2.
When I try compile use mvn compile, error happened: 
```
Cannot find 'strictSpec' in class org.openapitools.codegen.plugin.CodeGenMojo
```

Can any one tell me what's wrong happened?

**Comment by wing328** [comment]
Please use 4.0.0 for the time being. We've fixed the issue in the latest master and will release a patch version soon.
