### ISSUE TITLE
[Java] "allOf" does not support inheritance

### ISSUE THREAD

**Issue by vincent-ch** [OpenAPITools/openapi-generator#3172]
**Description**
I just attempted to use allOf in my project to use inheritance in our data model.

**openapi-generator version**
I am using the Maven plugin: openapi-generator-maven-plugin:4.0.0-beta2

**OpenAPI declaration file**

    UserSpecificService:
      type: object
      required:
        - typ
        - aktiviert
      properties:
        id:
          type: string
          format: int64
        typ:
          $ref: '#/components/schemas/ServiceTyp'
        aktiv:
          type: boolean

    PushServiceETA:
      allOf:
        - $ref: '#/components/schemas/UserSpecificService'
        - type: object
          properties:
            verteilerListe:
              type: array
              items:
                $ref: '#/components/schemas/PushVerteilerETA'
            ort:
              $ref: '#/components/schemas/Ort'

**Result**
```
public class UserSpecificService {
  private String id;
  private ServiceTyp typ;
  private Boolean aktiv;
}

public class PushServiceETA {
  private String id;
  private ServiceTyp typ;
  private Boolean aktiv;
  private List<PushVerteilerETA> verteilerListe = new ArrayList<>();
  private Ort ort = null;
}
```

**Suggest a fix/enhancement**
The Java generator should support single inheritance. It would give us way more flexibilty in the usage of the generated classes in our code.

```
public class PushServiceETA extends UserSpecificService {
  private List<PushVerteilerETA> verteilerListe = new ArrayList<>();
  private Ort ort = null;
}
```

**Comment by mikhail-putilov** [comment]
Technically it is not a bug https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#does-openapi-generator-support-all-new-features-in-openapi-specification-v3

**Comment by wing328** [comment]
@vincent-ch for inheritance, please use `discriminator` as per OpenAPI spec v3.

Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaComposition

**Comment by vincent-ch** [comment]
Thanks for your answer @wing328 , I did a quick test and it looks good. I just have to test how I can configure it with my complexes cases. This is not a bug in this case.

**Comment by wing328** [comment]
@vincent-ch glad to hear the issue has been resolved for you.

If you like what OpenAPI Generator offers, please consider supporting our voluntary work via https://opencollective.com/openapi_generator

**Comment by epabst** [comment]
After I got the Pet model working that @marcdejonge provided in https://github.com/OpenAPITools/openapi-generator/issues/9615#issuecomment-861304768, I figured out a workaround for my own issue. I had separate yaml files for my schema model classes, and by moving them into the same file as the endpoints under this, it worked for me!!!
```
components:
  schemas:
```
