### ISSUE TITLE
Deno typescript OpenAPI generators

### ISSUE THREAD

**Issue by anxiousmodernman** [OpenAPITools/openapi-generator#3174]
##### Description

Deno is a new [TypeScript runtime built with V8 and Rust](https://github.com/denoland/deno). Generating clients and servers from OpenAPI specifications would be a great feature.

The existing TypeScript _fetch_ implementation should work for generating clients, with some modifications. I have done some research to this effect with the spec for Kubernetes. Some of the changes required to get the Deno code to build.

- [change imports to be ".ts"](https://github.com/anxiousmodernman/deno-kube/commit/241bedb23ddbbb129c66d10bcd129143fedbea17) instead of no file extension
- when importing directory "modules", [point the import at "blah/index.ts"](https://github.com/anxiousmodernman/deno-kube/commit/5444c6f9281162b7ceb2dcda4dcdfab7d3175481) instead of just "blah" (the directory)
- [alias the standard DOM types](https://github.com/anxiousmodernman/deno-kube/blob/master/src/runtime.ts#L14-L18) to the Deno dom types.
- [Add the HEAD http method](https://github.com/anxiousmodernman/deno-kube/commit/64617c85610a90cb87c8223bd76b0fb5118ef5bc) to the generated code (missing for some reason, perhaps a bug in the generator)

Deno strives for browser compatibility, so the fetch implementation is built in. But there are other networking capabilities being developed for Deno, such as `dialTLS` builtins. The fetch api is probably where authors of OpenAPI generators should focus first, however, as that API is well defined and is unlikely to change in big ways, I imagine.

Generating server-side Deno is something that is feasible, but that API is more likely to change.

**Comment by anxiousmodernman** [comment]
Some issues re: fetch in Deno to watch
https://github.com/denoland/deno/issues/2520
https://github.com/denoland/deno/issues/2513
https://github.com/denoland/deno/issues/2150

**Comment by macjohnny** [comment]
cc @TiFu 
keep in mind https://github.com/OpenAPITools/openapi-generator/issues/802

**Comment by TiFu** [comment]
Thanks, will do, although I'm progressing very slowly - currently writing my master's thesis.

**Comment by macjohnny** [comment]
@TiFu wish you all the best for your thesis!

**Comment by chibat** [comment]
I want to add `deno` to `platforms` of typescript(experimental).
May I create a Pull Request ?

**Comment by TiFu** [comment]
@chibat Of course! :) Do you already have an idea how you want to add deno?

**Comment by chibat** [comment]
@TiFu
Thanks!
I created the PR(#6732). I think you already know it.
