### ISSUE TITLE
Can I use openapi-generator to generate documentation from my OpenAPI file I already have ?

### ISSUE THREAD

**Issue by AleksandrovM** [OpenAPITools/openapi-generator#3190]
Documentation generation is only I want

**Comment by jmini** [comment]
Have a look at one of this generator:

* [dynamic-html](https://openapi-generator.tech/docs/generators/dynamic-html)
* [html](https://openapi-generator.tech/docs/generators/html)
* [html2](https://openapi-generator.tech/docs/generators/html2)
