### ISSUE TITLE
[BUG] php-symfony generator bug, integer->maximum property

### ISSUE THREAD

**Issue by reznikartem** [OpenAPITools/openapi-generator#3209]
#### Bug Report Checklist

- [+] Have you provided a full/minimal spec to reproduce the issue?
- [+] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [4.0.0-beta3] What's the version of OpenAPI Generator used?
- [+] Have you search for related issues/PRs?

Hello. You have a bug in openapi-generator/modules/openapi-generator/src/main/resources/php-symfony/api_input_validation.mustache

In line 68 - 75 you have this code:

` {{#maximum}}
    {{#exclusiveMaximum}}
        $asserts[] = new Assert\LessThan({{minimum}});
    {{/exclusiveMaximum}}
    {{^exclusiveMaximum}}
        $asserts[] = new Assert\LessThanOrEqual({{minimum}});
    {{/exclusiveMaximum}}
    {{/maximum}}`

Variable **minimum** used here instead of **maximum**

**Comment by wing328** [comment]
@reznikartem thanks for reporting the issue. I wonder if you can file a PR so that we can review the suggested fix more easily. 

Let us know if you need help with the PR.

**Comment by reznikartem** [comment]
Made pull request https://github.com/OpenAPITools/openapi-generator/pull/3971
