### ISSUE TITLE
[REQ] Elixir v1.9 support

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#3211]
### Is your feature request related to a problem? Please describe.

Elixir v1.9 has been released: https://elixir-lang.org/blog/2019/06/24/elixir-v1-9-0-released/

We will need to test the auto-generated Elixir client to ensure it works with v1.9.0

## Describe the solution you'd like

N/A

## Describe alternatives you've considered

N/A

## Additional context

N/A

**Comment by mrmstn** [comment]
We use some auto-generated clients in our elixir 1.9 application and they look to work fine

**Comment by wing328** [comment]
@mrmstn thanks for the confirmation.
