### ISSUE TITLE
[BUG] OpenAPI 3.0: Generated nodejs server stub from editor.swagger.io can not start.

### ISSUE THREAD

**Issue by nanw1103** [OpenAPITools/openapi-generator#3216]
Steps to reproduce:

1. Use editor.swagger.io, fill-in the example config in this ticket
2. Generate server stub for nodejs
3. Start the server locally
4. Expect the server to start. However, the server can not be started.

Note: A workaround to start the server is to change "openapi: 3.0.0" to "openapi: 3.0.1"

-------------------------------------
Example config:
-------------------------------------

openapi: 3.0.0
info:
  title: Demo error
  version: 1.0.0
servers:
- url: /demo
paths:
  /test:
    post:
      operationId: testPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/my_req_body'
        required: true
      responses:
        200:
          description: Success
      x-swagger-router-controller: Default
components:
  schemas:
    my_req_body:
      properties:
        code:
          type: string
        message:
          type: string

**Comment by DanielHabenicht** [comment]
What error is thrown on the console?

**Comment by duqcyxwd** [comment]
I am having the same issue. There is no error thrown on the console. The workaround works. Thanks

**Comment by wing328** [comment]
We've included a new `nodejs-express-server` in 4.1.0 release. Please check it out.
