### ISSUE TITLE
[BUG] [git] Perl client sample files collide on case-insensitive file system

### ISSUE THREAD

**Issue by kendoyle** [OpenAPITools/openapi-generator#3228]
##### Description

Checking out latest master on Windows (case-insensitive file system) yields the following warning about file name conflicts:

```
$ git clone https://github.com/OpenAPITools/openapi-generator.git
Cloning into 'openapi-generator'...
remote: Enumerating objects: 285, done.
remote: Counting objects: 100% (285/285), done.
remote: Compressing objects: 100% (146/146), done.
remote: Total 338795 (delta 127), reused 143 (delta 2), pack-reused 338510
Receiving objects: 100% (338795/338795), 81.53 MiB | 17.52 MiB/s, done.
Resolving deltas: 100% (206139/206139), done.
Checking out files: 100% (21690/21690), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'samples/client/petstore/perl/docs/AnotherFakeApi.md'
  'samples/client/petstore/perl/docs/AnotherfakeApi.md'
  'samples/client/petstore/perl/t/AnotherFakeApiTest.t'
  'samples/client/petstore/perl/t/AnotherfakeApiTest.t'
```

##### openapi-generator version

master

##### Command line used for generation

```
git clone https://github.com/OpenAPITools/openapi-generator.git
```

* git version: git version 2.22.0.windows.1
* Windows version: Windows 10 version 1703

##### Steps to reproduce

1. Clone the repo using the above command on windows
2. Warning messages appear about path collisions

##### Related issues/PRs

The files cause the case-insensitive path conflict were added in this PR:
https://github.com/OpenAPITools/openapi-generator/pull/3207

##### Suggest a fix/enhancement

Can't fix myself at the moment, seems like these files are duplicates, just need to remove each of the conflicting files.

**Comment by wing328** [comment]
Can you try again with the latest master? I think we've addressed the issue.

We'll open this issue if that's not the case.

**Comment by kendoyle** [comment]
Confirmed with e46bd7dd that this issue is no longer occurring. Thanks for the fix!
