### ISSUE TITLE
[REQ] apisToGenerate option

### ISSUE THREAD

**Issue by hellboy81** [OpenAPITools/openapi-generator#3235]
### Is your feature request related to a problem? Please describe.

The code generated for all api definitions can  contain too much unused code.

## Describe the solution you'd like

Is there possible to generate only code for chosen api definitions? The models list to be generated should be detected automatically. 

## Describe alternatives you've considered

Is there 3rd party tools which can determine models list are used by rest api?

**Comment by wing328** [comment]
What about trimming down the OpenAPI document into smaller one to meet your requirement?

**Comment by hellboy81** [comment]
Is there supporting editors/tools which can help to split?

**Comment by hellboy81** [comment]
Got it!
[Open api supports customization](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md)

Also `openapi-generator-ignore` can be used
