### ISSUE TITLE
[REQ] [Java] add @Nullable annotation to generated model fields that aren't "required"

### ISSUE THREAD

**Issue by kassim** [OpenAPITools/openapi-generator#3264]
### Is your feature request related to a problem? Please describe.

In IDEs such as IntelliJ, in compilers, and in Kotlin's Java-interop - you can assist the developer by annotating fields that are nullable, with the `@Nullable` annotation. 
At the moment the generated models do indicate what fields are optional via `@ApiModelProperty(required = true` however this doesn't hook in with the very helpful existing features as mentioned before.

This is particularly annoying when using Kotlin for development because it is a language that leads you to expect it won't compile when you make an action on a nullable variable that hasn't had a null check.

## Describe the solution you'd like

for any field (and its accessor methods) please annotate with `@Nullable` (javax.annotation.Nullable) if it is not stated as "required" in the API schema

## Describe alternatives you've considered

Alternative: use the Kotlin generator - it's not a well featured as the Java generator (doesn't include a Retrofit library), requires a switch to a different JSON parsing library (Gson to Moshi) + it's also not compiling with the use of lists/arrays
Alternative: check every field's description when developing - not fun
Alternative: null check everything - ...

## Additional context

https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html
https://kotlinlang.org/docs/reference/java-interop.html#nullability-annotations

**Comment by wing328** [comment]
@kassim may I know if you've time to contribute a PR for such enhancement? I can show you some good starting points such as using {{#isNullable}} ... {{/isNullable}}

**Comment by kassim** [comment]
I think in 2 weeks time I will :)
