### ISSUE TITLE
[BUG] generator for graphql-nodejs-express-server SIGSEGV in openapi-generator-online docker

### ISSUE THREAD

**Issue by tx0h** [OpenAPITools/openapi-generator#3291]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

can't generate server code for 'graphql-nodejs-express-server' using the pet example in the openapi-generator-online environment. maybe it's related to a SIGSEGV which occurs during the code generation. maybe it's releated to

```
115   stat("graphql-nodejs-express-server/.gitignore", 0x7f43aa3e1eb0) = -1 ENOENT (No such file or directory)
115   open("graphql-nodejs-express-server/.gitignore", O_RDONLY) = -1 ENOENT (No such file or directory)
```

##### openapi-generator version

i tried the latest docker image from docker hub, which got tagged as latest (July 7, 2019 04:51 PM).
i also tried the public online version, can't tell what version is on it. -> http://api.openapi-generator.tech/

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml

##### Command line used for generation

`curl -X POST -H "content-type:application/json" -d '{"openAPIUrl":"https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml"}' http://api.openapi-generator.tech/api/gen/servers/graphql-nodejs-express-server`

##### Steps to reproduce

take the command line as stated above on a system with curl installed and fire the command.

##### Related issues/PRs

-/-

##### Suggest a fix

it works in the openapi-generator-cli version. it must be server related, maybe this .gitignore file i mentioned above. have a look at the console output and the strace SIGSEGV event in the text file i've attached to this report.

[br.txt](https://github.com/OpenAPITools/openapi-generator/files/3365895/br.txt)

**Comment by wing328** [comment]
Looked into it but really no clue why this fails. Please use the CLI as a workaround for the time being.
