### ISSUE TITLE
Integrating with a project generator to generate for openApi

### ISSUE THREAD

**Issue by abhishek-anand13** [OpenAPITools/openapi-generator#3294]
Hi there, I have a spring boot project wherein a user creates a microservice code according to his needs. The new requirement for the project demands someone can upload a .yml file in compliance with openApi and that we should be able to generate the project from .yml in our code and return back the generated code. Is there any support for such integrations? If yes, what do I do?

**Comment by macjohnny** [comment]
if I correctly understand your requirement, this is exactly what OpenAPI-Generator is supposed to do

**Comment by abhishek-anand13** [comment]
openapi generator generates the structure of code from command line as I understood. I want to generate it via already running java backend application and return it back

**Comment by macjohnny** [comment]
you could simply create a tiny REST Controller e.g. in Spring boot and call the codegen e.g. like this

https://github.com/OpenAPITools/openapi-generator/blob/51e7005373fdb55daa1c253f36fb6267a64a7bf7/modules/openapi-generator/src/test/java/org/openapitools/codegen/typescript/typescriptangular/TypeScriptAngularClientCodegenTest.java#L18-L22

**Comment by abhishek-anand13** [comment]
sure. let me try this and get back in case of any issues
