### ISSUE TITLE
[BUG] OAuth security schema is used  but OAuth related files are not generated 

### ISSUE THREAD

**Issue by eyals24** [OpenAPITools/openapi-generator#3305]
Related buggy fix  has been performed on Java Client at 28.01.2019
-- Generate OAuth related files only if OAuth security schema is used #1907
-- related commit - 887b688014e3c1b1c3e4c95d07d86dbcc2da220e

The fix lead to bug when OAuth security schema is used  but OAuth related files are not generated. After generating process files : OAuth and OAuthFlow classes 
imported in ApiClient class but not exists in the source path. 

properties : 

openApiGenerate {
    generatorName = "java"
    library = "resttemplate"
    inputSpec = "$rootDir/src/main/resources/swagger/swagger.yaml".toString()
    outputDir = "$buildDir/openapi".toString()
    apiPackage = "com.test.client.api"
    modelPackage = "com.test.client.api.model"
    configOptions = [
            dateLibrary: "java8"
    ]
    systemProperties = [
            modelDocs: "false",
            apiDocs: "false"
    ]
}

**Comment by damc-dev** [comment]
I am running into this same issue when trying to generate a feign client with OAuth2.0.
I see that the fix has been merged to master, but are there any plans to include this on a release?
Also are there any workarounds I could use in the meantime?

**Comment by damc-dev** [comment]
> I am running into this same issue when trying to generate a feign client with OAuth2.0.
> I see that the fix has been merged to master, but are there any plans to include this on a release?
> Also are there any workarounds I could use in the meantime?

I was able to work around this by just defining my endpoint security as oauth (even with an empty array of scopes) it will then correctly generate the OAuth files.
e.g.
```
"paths": {
    "/pets/{petId}": {
        "get": {
            "security": [
                {
                    "oauth2": []
               }
            ]
        --omitted--
```

**Comment by wing328** [comment]
Please share a minimal spec to help reproduce the issue.

**Comment by helgadeville** [comment]
I run into same issue.
Piece of YAML file says:

  securitySchemes:
    oAuth:
      type: oauth2
      description: This API uses OAuth 2 with the clientCredentials grant flow. [More info](https://api.example.com/docs/auth)
      flows:
        clientCredentials:
          authorizationUrl: https://some-server...

During generation, 2 spec errors exist:

org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors: 
	-attribute components.securitySchemes.oAuth.scopes is missing
	-attribute components.securitySchemes.oAuth.tokenUrl is missing

Since I cannot change the YAML file (it is external file), I override it with "skip validation spec", then the OAuth, OAuthFlow and RetryingOAuth are NOT generated, although ApiClient imports them.

Then, the whole generated code does not compile and is unusable.

There is nothing mysterious about the plugin config also in pom.xml:

                        <configuration>
                            <inputSpec>${project.basedir}/api/some_file.yaml</inputSpec>
                            <skipValidateSpec>true</skipValidateSpec>
                            <generatorName>java</generatorName>
                            <output>${project.build.directory}/generated-sources/openapi</output>
                            <generateApiDocumentation>false</generateApiDocumentation>
                            <generateModelDocumentation>false</generateModelDocumentation>
                            <withXml>false</withXml>
                            <modelPackage>com.model</modelPackage>
                            <apiPackage>com.api</apiPackage>
                            <invokerPackage>com.invoker</invokerPackage>
                            <configOptions>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                            </configOptions>
                        </configuration>
