### ISSUE TITLE
[BUG][Python] Incorrect Python package name for 4.0.3

### ISSUE THREAD

**Issue by daviddavis** [OpenAPITools/openapi-generator#3335]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Python package name is wrong for openapi-cli v4.0.3.

##### openapi-generator version

4.0.3

##### Command line used for generation

```
    docker run -u $(id -u) --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
        -i /local/api.json \
        -g python \
        -o /local/pulp_file-client \
        -DpackageName=pulpcore.client.pulp_file \
        -DprojectName=pulp_file-client \
        -DpackageVersion=0.1.0b1 \
        --skip-validate-spec \
        --strict-spec=false
```

##### Steps to reproduce

Use the above command to generate a client. 

With 4.0.2:

```
cat pulp_file-client/setup.py | grep NAME
NAME = "pulp_file-client"
    name=NAME,
```

With 4.0.3:

```
cat pulp_file-client/setup.py | grep NAME
NAME = "openapi-client"
    name=NAME,
```

**Comment by dkliban** [comment]
This is not a language specific bug. I am seeing the same behavior for Ruby clients.

**Comment by wing328** [comment]
Please use `--additional-properties` instead of `-D`.
