### ISSUE TITLE
[BUG][spring] Enum query parameter parsing fails due to enum constants being generated in uppercase

### ISSUE THREAD

**Issue by tkalliom** [OpenAPITools/openapi-generator#3337]
##### Description

Even when enum values are lower-case in the specification, openapi-generator produces uppercased enum constants in Java, apparently due to the convention. However, this means that lowercased values in enum query parameters are not parsed correctly, resulting in 400 Bad requests for valid requests.

##### openapi-generator version

4.0.3, was present in 3.2 as well

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  title: Catalog
  version: '1.0'
servers:
  - url: 'http://localhost:8080'

components:
  schemas:
    ProductType:
      type: string
      enum:
        - hardware
        - SOFTWARE
paths:
  /products:
    get:
      operationId: getProducts
      parameters:
        - in: query
          name: type
          schema:
            $ref: '#/components/schemas/ProductType'
      responses:
        '200':
          description: Ok
```

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i catalog.yaml -g spring`

##### Steps to reproduce

1. `mvn spring-boot:run`
2. `curl -i "http://localhost:8080/products?type=hardware"`

Expected outcome: `HTTP/1.1 501` due to missing implementation, and no warnings output by Spring. (This is the case for the uppercase `type=SOFTWARE`)
Actual outcome: `HTTP/1.1 400` and the following warning:
```
2019-07-11 12:29:39.186  WARN 12951 --- [nio-8080-exec-4] .w.s.m.s.DefaultHandlerExceptionResolver : Failed to bind request element:
  org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'org.openapitools.model.ProductType'; nested exception is
    org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@io.swagger.annotations.ApiParam @javax.validation.Valid org.openapitools.model.ProductType] for value 'hardware'; nested exception is
      java.lang.IllegalArgumentException: No enum constant org.openapitools.model.ProductType.hardware
```

Spring is trying to do `Enum.valueOf(ProductType.class, "hardware")` which fails, since openapi-generator produces the constant as `ProductType.HARDWARE`.

##### Related issues/PRs

Issue #1927 is related: producing enum in MACRO_CASE also results in non-working `@DefaultValue` annotations.

##### Suggest a fix

I would consider just reverting to producing enum constants matching the API specification. If this is considered unacceptable, then probably the way to fix this bug would be to:
1. Produce a `model.FooConverter extends java.Beans.PropertyEditorSupport` for each enum schema Foo, implementing `setAsText` utilizing `model.Foo::fromValue`
1. For each controller where an enum is used as a parameter, add `@InitBinder public void initBinder(WebDataBinder dataBinder) { dataBinder.registerCustomEditor(Foo.class, new FooConverter()) }`

**Comment by jmini** [comment]
> I would consider just reverting to producing enum constants matching the API specification.

I do not think that this is an option…

Having uppercase follow the java recommendation:
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

---
When the name of the enum is computed, other aspect are also taken into consideration:

* Illegal chars (valid OpenAPI spec) in Java enum names are replaced.
* Illegal names are fixed (Java does not allow the name of enum to start with number, ...)
* Extension like `x-enum-varnames` is supported.
* ...

---

If I remember well my problem to solve the remaining issue described in https://github.com/OpenAPITools/openapi-generator/issues/1927#issuecomment-462640059 was that the upper-case name of the enum is not really available in the templates yet.

**Comment by davidjlynn** [comment]
I have just run into this issue also.
For me the temporary solution was to switch all of our enums over to be uppercase in our schema definition, however would have been nice not to have this restriction.

Strangely the OpenAPI seems to only use lowercase for it's enums however: https://swagger.io/docs/specification/data-models/enums/

**Comment by Maurice-Betzel** [comment]
Same issue with the EU open data portal and Open API generator maven plugin with jarxrs-cxf-client. I think of converting it to a plain string.

**Comment by Maurice-Betzel** [comment]
I resolved the issue by using a custom mustache template for enumClass:

	{{#withXml}}
	@XmlType(name="{{datatypeWithEnum}}")
	@XmlEnum({{dataType}}.class)
	{{/withXml}}
	public enum {{datatypeWithEnum}} {

		{{#allowableValues}}
	{{#enumVars}}
		{{#withXml}}
			@XmlEnumValue({{#isInteger}}"{{/isInteger}}{{#isDouble}}"{{/isDouble}}{{#isLong}}"{{/isLong}}{{#isFloat}}"{{/isFloat}}{{{value}}}{{#isInteger}}"{{/isInteger}}{{#isDouble}}"{{/isDouble}}{{#isLong}}"{{/isLong}}{{#isFloat}}"{{/isFloat}})
		{{/withXml}}
		{{name}}({{dataType}}.valueOf({{{value}}})){{^-last}},
		{{/-last}}{{#-last}};
		{{/-last}}{{/enumVars}}
		{{/allowableValues}}


		private {{dataType}} value;

		{{datatypeWithEnum}} ({{dataType}} v) {
			value = v;
		}

		@JsonValue
		public {{dataType}} getValue() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}

		@JsonCreator
		public static {{datatypeWithEnum}} fromValue({{dataType}} value) {
			for ({{#datatypeWithEnum}}{{{.}}}{{/datatypeWithEnum}}{{^datatypeWithEnum}}{{{classname}}}{{/datatypeWithEnum}} b : {{#datatypeWithEnum}}{{{.}}}{{/datatypeWithEnum}}{{^datatypeWithEnum}}{{{classname}}}{{/datatypeWithEnum}}.values()) {
				if (b.value.equals(value)) {
					return b;
				}
			}
			{{#isNullable}}return null;{{/isNullable}}{{^isNullable}}throw new IllegalArgumentException("Unexpected value '" + value + "'");{{/isNullable}}
		}
	}

**Comment by Heidschnucke** [comment]
Any news regarding this issue?

**Comment by lelvisl** [comment]
same situation

schema

```yaml
    imgFormat:
      type: string
      enum:
        - "lol"
        - "image/gif"
        - "image/jpeg"
        - "image/png"
        - "image/png8"
        - "image/vnd.jpeg-png"
        - "image/vnd.jpeg-png8"
```

generated enum

```java
public enum ImgFormat {
  
  LOL("lol"),
  
  IMAGE_GIF("image/gif"),
  
  IMAGE_JPEG("image/jpeg"),
  
  IMAGE_PNG("image/png"),
  
  IMAGE_PNG8("image/png8"),
  
  IMAGE_VND_JPEG_PNG("image/vnd.jpeg-png"),
  
  IMAGE_VND_JPEG_PNG8("image/vnd.jpeg-png8");

  private String value;

  ImgFormat(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static ImgFormat fromValue(String value) {
    for (ImgFormat b : ImgFormat.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}


```


```
Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'com.myapp.model.ImgFormat'; nested exception is org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [@javax.validation.constraints.NotNull @io.swagger.annotations.ApiParam @javax.validation.Valid @org.springframework.web.bind.annotation.RequestParam com.myapp.model.ImgFormat] for value 'image/png'; nested exception is java.lang.IllegalArgumentException: No enum constant com.myapp.model.ImgFormat.image/png]
```

**Comment by lelvisl** [comment]
it's on 5.0.1

**Comment by mishka3097** [comment]
@lelvisl have you solved this isuue in your project?

**Comment by lelvisl** [comment]
No, i dropped using this tool.

**Comment by vandanagoyal-ak** [comment]
> it's on 5.0.1

Do you mean its solved in this version, this issue is still open ?

**Comment by Parawata** [comment]
Not clear from the above if this is solved (I'm using 5.1.1 and still happening), but I found a simple enough way to get around it without needing to customise the enum templates.

Instead of defining the enum values only, add coressponding values under the x-enum-varnames as in the example below. This will overwrite the uppercase constant with the values you specify with no uppercase conversion. 
i.e.
```yaml
DistributionType:
      type: string
      enum:
        - All
        - List
      x-enum-varnames:
        - All
        - List
```

Generates
```java
public enum DistributionType {
  
  All("All"),
  
  List("List");

  private String value;

  DistributionType(String value) {
    this.value = value;
  }
...
```
Repetitive I know but preferable (for me anyway) to forcing everything to uppercase. Project I'm working on has a lot of configuration and properties identifiers in enums so retaining case sensitivity is essential.

**Comment by tobq** [comment]
This bug is sitll an issue

**Comment by Hollerweger** [comment]
Something seems to be wrong in Spring validation as the ENUMs are generated with correct lowercase value:

```
public enum SortByEnum {
  
  NAME("name"),
  
  ID("id"),
  
  LASTUPDATEDTS("lastUpdatedTs");

  private String value;

  SortByEnum(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static SortByEnum fromValue(String value) {
    for (SortByEnum b : SortByEnum.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }
}
```

**Comment by osimosu** [comment]
Ran into this issue today. What worked for is creating a custom Converter in Spring boot to convert the Enum to String

```
@Component
public class MyCustomEnumConverter implements Converter<String, SortEnum> {
    @Override
    public SortEnum convert(String source) {
       try {
          return SortEnum.valueOf(source);
       } catch(Exception e) {
          return null; // or SortEnum.asc
       }
    }
}
```

**Comment by Hollerweger** [comment]
Stumbled again on this annoying issue.
Adding ApplicationConversionService formatter in Spring WebMvcConfigurer helps to circumvent this issue as it registers a LenientObjectToEnumConverterFactory which can mapper lower case values.

```
  @Override
  public void addFormatters(final FormatterRegistry registry) {
    ApplicationConversionService.configure(registry);
  }
```

Still would be great if Spring and OpenAPI Team can align here.

**Comment by frochi42** [comment]
Any updates here? A solution would be greatly appreciated.

**Comment by jkt628** [comment]
@Parawata 
for https://github.com/OpenAPITools/openapi-generator/issues/3337#issuecomment-930273802 YAML anchors cut down the repetition:
```YAML
DistributionType:
  type: string
  enum: &DistributionType
    - All
    - List
  x-enum-varnames: *DistributionType
```

**Comment by tkalliom** [comment]
This issue appears to have been fixed in v6.2.1 with #13349. Code generated by the current openapi-generator now produces 501 for `/products?type=hardware`.

**Comment by h3adache** [comment]
> This issue appears to have been fixed in v6.2.1 with #13349. Code generated by the current openapi-generator now produces 501 for `/products?type=hardware`.

I am not sure how that MR fixed anything @tkalliom. It doesn't generate a converter to register to spring, it just shows what a converter would look like in the samples 🤔

**Comment by tpat4856** [comment]
isn't the issue is still there with 7.1.0

**Comment by tpat4856** [comment]
isn't the issue still there with 7.1.0

**Comment by frochi42** [comment]
Did you try
<legacyDiscriminatorBehavior>true</legacyDiscriminatorBehavior>
in <configOptions>?
(if you are using maven. Else you must lookup where to apply this option)

**Comment by angelmerino** [comment]
Issue still there in 7.2.0.
The only way to get around it is with a mustache template or to define all enum values in uppercase.

**Comment by mg-okteo** [comment]
Hey there, the issue is still there using open-api 3.0.1, open-api-generator 6.6.0, and spring boot 3.1.2

Any fix or workaround to make Spring stop using the valueOf ?

**Comment by andreas-voigt-csw** [comment]
Issue still there in 7.6.0

**Comment by WIStudent** [comment]
I am using 7.9.0 and the `EnumConverterConfiguration.java` is being generated and collected by Spring Boot. If you configured `<supportingFilesToGenerate>` in your openapi-generator-maven-plugin configuration, make sure you include `EnumConverterConfiguration.java`, otherwise it will not be generated.

**Comment by bahuma20** [comment]
How to generate this EnumConverterConfiguration.java file, when we use "interfaceOnly"?

**Comment by jorgerod** [comment]
> generate this EnumConverterConfiguration.java file, when we use "interfaceOnly"

Hi

I've created this issue for fix this problem
