### ISSUE TITLE
[BUG][aspnetcore][csharp][csharp-dotnet2] allOf generates source code for *AllOf model

### ISSUE THREAD

**Issue by oleksabor** [OpenAPITools/openapi-generator#3338]
##### Description

I've tried to use allOf to check inherited classes case. But the problem is that it generates surplus model class `ExtendedErrorModelAllOf.cs` among with `ErrorModel.cs` `ExtendedErrorModel.cs`
I expect that `ExtendedErrorModelAllOf.cs` should not be generated.

##### openapi-generator version

v4.0.3

##### OpenAPI declaration file content or url

[classInherit.yml.zip](https://github.com/OpenAPITools/openapi-generator/files/3381725/classInherit.yml.zip)

##### Command line used for generation

java -jar D:/os/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i classInherit.yml -g aspnetcore -o d:\temp\ErrorMessage

java -jar D:/os/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i classInherit.yml -g csharp -o d:\temp\ErrorMessage

java -jar D:/os/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i classInherit.yml -g csharp-dotnet2 -o d:\temp\ErrorMessage

##### Steps to reproduce

clone openapi-generator
checkout v4.0.3
build mvnw package
get classInherit.yml
run commands

##### Suggest a fix

I suppose the reason is in the AbstractCSharpCodegen since all three  c# is affected.

probably it happens because of ExtendedErrorModel has `-ref$` and `-type`

````yml
  ExtendedErrorModel:
    allOf:
    - $ref: '#/definitions/ErrorModel'
    - type: object
````

**Comment by thilux** [comment]
This is affecting other clients as well. I see the same problem for Java and Typescript at least.
I am using the same generator version as the reporter (v4.0.3).

**Comment by wing328** [comment]
Thanks for reporting the issue. Can you please check the latest master? if it's still an issue, I'll take a look in the next 2 weeks after I'm back from my trip.

**Comment by oleksabor** [comment]
I've just checked with latest master but it generates three files 

> ErrorModel.cs
> ExtendedErrorModel.cs
> ExtendedErrorModelAllOf.cs - it should not be generated

and ExtendedErrorModel does not inherit from the ErrorModel:
`public partial class ExtendedErrorModel : IEquatable<ExtendedErrorModel>`

**Comment by edag94** [comment]
Any updates on this? Seems like inheritance isn't supported by these generators.

**Comment by slemrmartin** [comment]
There is the same problem in Ruby client. Tried in version 4.1.1 and 4.2.0

**Comment by wing328** [comment]
I've filed a PR (https://github.com/OpenAPITools/openapi-generator/pull/13498) related to this. 

Please refer to https://github.com/OpenAPITools/openapi-generator/issues/3100#issuecomment-1255043072 for the instruction to try it out.

closing this one as we'll use https://github.com/OpenAPITools/openapi-generator/issues/3100 to track

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/15682

Please pull the latest master to give it a try.
