### ISSUE TITLE
[BUG][typescript-rxjs] Generator imports some conditional imports unnecessarily

### ISSUE THREAD

**Issue by evantrimboli** [OpenAPITools/openapi-generator#3339]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

`throwIfRequired` and `COLLECTION_FORMATS` are imported unconditionally at the top of the `apis.mustache` file. However, depending on the contents of the spec, they may not be used and are marked as unused imports.

`throwIfRequired` only needs importing if there are required params.
`COLLECTION_FORMATS` only needs importing if `isListContainer` or `isCollectionFormatMulti` is set.

This can be problematic if compiler options are set to not allow unused vars.

##### openapi-generator version

4.0.3. No regression.

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

`java -jar openapi-generator-cli.jar generate -i spec.yaml -g typescript-rxjs -o ./out`

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

**Comment by macjohnny** [comment]
@evantrimboli would you like to fix this issue?

**Comment by evantrimboli** [comment]
At this point I don't have the time/expertise to dig into it. Perhaps in the future.

**Comment by macjohnny** [comment]
cc @denyo maybe you can implement this as part of your code cleanup

**Comment by denyo** [comment]
Should be taken care of with some more improvements here in #3316.

**Comment by denyo** [comment]
Can be closed since #3316 is merged?

**Comment by macjohnny** [comment]
fixed with #3316.
