### ISSUE TITLE
[QUESTION] Modify Openapi spec yml and regenerate server stub without changing business logic?

### ISSUE THREAD

**Issue by parrotcar00** [OpenAPITools/openapi-generator#3360]
##### Description

Is it possible to iteratively modify the spec of some endpoints in the yml file and then regenerate the server stub without having to modify your business logic each time you do that?

To give an example, consider the endpoint:
GET /api/v1/{petID}/details

Suppose we modify this to look like, adding another parameter to the endpoint:

GET /api/v1/{petstoreRegionCode}/{petID}/details

As an example, let's say we're using spring boot backend generator, would it be possible to regnerate the code, if I wanted to preserve my business logic that I wrote in spring-boot?

##### openapi-generator version

Latest openapi-generator version: 4.1

**Comment by richardwhiuk** [comment]
I think #426 is related to this - where there's a desire for the generators to cleanly separate implementation and interface logic.

**Comment by parrotcar00** [comment]
I was able to solve my issue by using the openapi generator maven plugin which does the re-generation of the API interface while preserving your business logic.

**Comment by amorozov** [comment]
I would like to ask what generator did you use for that?
