### ISSUE TITLE
[BUG] Option template directory ignored in 4.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by MichalFoksa** [OpenAPITools/openapi-generator#3364]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Looks like template directory option (-t <template directory> | --template-dir <template directory>) is ignored in 4.1.0-SNAPSHOT. Template directory always defaults to embeded dir.

Following condition from DefaultCodegen.processOpts() evaluates to false even when `-t` option is provided, e.g: `-t swagger/my-template `.

`if (additionalProperties.containsKey(CodegenConstants.TEMPLATE_DIR))`

I have added a log message right at the end of DefaultCodegen.processOpts() method:
`LOGGER.info("Template directory [templateDir={}]", this.templateDir());`

Result message:
`[main] INFO  o.o.codegen.DefaultCodegen - [Template directory [templateDir=openapi-yaml]`

BTW: Same issue is with Spring generator.

##### openapi-generator version

4.1.0-SNAPSHOT as of 14/July/2019.

##### Steps to reproduce

java -jar "./modules/openapi-generator-cli/target/openapi-generator-cli.jar" generate -i swagger/openapi.yml -g openapi-yaml -t swagger/my-template --additional-properties outputFile=swagger/swagger.yml

##### Suggest a fix

It looks like there is a quite difference in code gen configuration (e.g.: CodegenConfigurator.java) between 4.0.x and 4.1.0.

I do not know what is a direction in 4.1.x.

**Comment by jimschubert** [comment]
Thanks for reporting this. It looks like this may affect versions 4.0.2+.

GeneratorSettings and WorkflowSettings may need to push all properties with a corresponding CODEGEN_CONSTANTS into the additionalProperties map. I'll try to get a fix for this into master later today.

**Comment by MichalFoksa** [comment]
You are welcome.
BTW: This particular issue (with template directory) is not in 4.0.3.

**Comment by jimschubert** [comment]
I've filed #3385 to resolve the issue. Looks like `templateDir` was the only property I'd missed setting on `additionalProperties`.

**Comment by MichalFoksa** [comment]
Great, when merged, I will test it.

**Comment by jimschubert** [comment]
@MichalFoksa this has been merged into master. Feel free to reopen the ticket if there are other kinks that I've missed.

**Comment by MichalFoksa** [comment]
I believe it won't be necessary.  :smiley:

**Comment by MichalFoksa** [comment]
@jimschubert it works. Thank you!
