### ISSUE TITLE
[BUG][C++-rest-sdk] Issue when default value is nullptr

### ISSUE THREAD

**Issue by dan-drl** [OpenAPITools/openapi-generator#3374]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
Run time error occurs because default type is set to nullptr. This breaks the fromJSON and toJSON methods in model-source.mustache.

##### openapi-generator version
4.1.0-SNAPSHOT

##### OpenAPI declaration file content or url
See test.json: https://gist.github.com/dan-drl/147e962298d1f1467638c00786cd9b6f
See resulting c++: https://gist.github.com/dan-drl/0ec11853c939d5d05ab3c2699238d324

##### Command line used for generation
java -jar openapi-generator-cli.jar generate -i test.json -g cpp-restsdk -o \src\test

##### Steps to reproduce
If a JSON containing a "value":null is provided to the AdditionalField model for deserialization, a runtime error occurs because of this:
```
std::shared_ptr<Object> newValue(nullptr);
newValue->fromJson(val.at(utility::conversions::to_string_t(L"value")));
```

##### Related issues/PRs
I didn't find anything.

##### Suggest a fix
Planning on making a pull request. See this commit, https://github.com/dan-drl/openapi-generator/commit/7b42948498ab0a82ee25c875a9787cdc685c9890

**Comment by wing328** [comment]
please provide more details. otherwise, it would be hard for others to help you out.

**Comment by dan-drl** [comment]
Sorry, I didn't realize that submitted : / ...  Please see revised issue above. 

Since the proposed fix, although small, could have a large impact, feedback about the change would be good. I am simply not familiar enough with the code to full understand the the ramifications of a change to the toDefaultValue method.

I am currently waiting to see if anything else comes up as other folks use my patched build. So far, things seem okay though.
