### ISSUE TITLE
[BUG][typescript-fetch] 4.0 returns void instead of raw Response type for controllers with blob responses

### ISSUE THREAD

**Issue by skrawn** [OpenAPITools/openapi-generator#3377]
##### Description

After upgrading openapi-generator from 3.3.4 to 4.0.3 we lost the ability to download files. I looked at the difference in the code generated by openapi and I noticed that instead of returning ```Promise<Response>```, it now returns ```Promise<void>``` for this API path. Here's the C# code for controller path:

```csharp
        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> GetDocument([FromRoute] Guid id)
        {
            var doc = await _apiService.GetDocument(id);
            return File(await doc.Content.ReadAsByteArrayAsync(), doc.Content.Headers.ContentType.ToString(),
                doc.Content.Headers.ContentDisposition.FileName);
        }
```

In openapi-generator 3.3.4, this code was:

```typescript
        getDocument(id: string, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DocumentsApiFetchParamCreator(configuration).getDocument(id, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
```

In openapi-generator 4.0.3, this code becomes:

```typescript
    async getDocument(requestParameters: GetDocumentRequest): Promise<void> {
        await this.getDocumentRaw(requestParameters);
    }
```

The openapi declaration file, posted below, is exactly the same between the two versions.

##### openapi-generator version

4.0.3

##### OpenAPI declaration file content or url

```json
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Super API 1.0",
    "version" : "1.0"
  },
  "servers" : [ {
    "url" : "/"
  } ],
  "paths" : {
    "/api/v1/Documents/{id}" : {
      "get" : {
        "tags" : [ "Documents" ],
        "operationId" : "GetDocument",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "required" : true,
          "schema" : {
            "type" : "string",
            "format" : "uuid"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Success",
            "content" : { }
          }
        },
        "security" : [ {
          "Bearer" : [ ]
        } ]
      }
    },
  }
}
```

##### Command line used for generation

openapi-generator generate -i http://localhost:8000/swagger/v1/swagger.json --skip-validate-spec --generator-name typescript-fetch --type-mappings DateTimeOffset=string -o .

##### Suggest a fix

Restore old behavior or have a flag to use raw responses?

Did I miss this in the 4.0 changes notes? I didn't see a fix for this in there and though it might be a bug.

**Comment by macjohnny** [comment]
in your OpenAPI declaration file, there is no response defined. See https://swagger.io/docs/specification/describing-responses/

**Comment by skrawn** [comment]
Our declaration file is generated by Swashbuckle.AspNetCore.SwaggerGen. I know there is an issue with the response not being defined and that's a separate thing. But I want to know why openapi-generator 3.3.4 was giving me Response as a return value and now 4.0.3 is giving me void as a return value.

**Comment by macjohnny** [comment]
I can't really tell, maybe this was a bug before, but I think the current behavior is correct.

**Comment by macjohnny** [comment]
@TiFu do you think we can close this issue?

**Comment by TiFu** [comment]
As far as I can tell, in the case of a non void response type, it returned Promise<{ResponseType}> in both 3.3.4 and 4.0.0, corrrect? In this case I'd argue that it was a bug in 3.3.4 and we can close this.
