### ISSUE TITLE
[BUG] [SPRING-CLOUD] Invalid generated ConfigurationProperties annotation

### ISSUE THREAD

**Issue by SirWayne** [OpenAPITools/openapi-generator#3381]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The generated Client Configurations class generates invalid properties annotation, when you use a title with uppercase characters. Camel case is not allowed for this annotation.

The yml
```
info:
  version: v1
  title: My Default API
```

Output is:
```
  @Bean
  @ConditionalOnProperty("myTestApi.security.macma.client-id")
  @ConfigurationProperties("myDefaultApi.security.x")
  public ClientCredentialsResourceDetails macmaResourceDetails() {
    ClientCredentialsResourceDetails details = new ClientCredentialsResourceDetails();
    details.setAccessTokenUri("test");
    return details;
  }
```

`@ConfigurationProperties("myDefaultApi.security.x")` is not allowed

see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
```
The prefix value for the annotation must be in kebab case (lowercase and separated by -, such as acme.my-project.person).

```

##### openapi-generator version

4.0.3

##### Suggest a fix

Camel case title should be seperated by a dot with just lower case characters or should be completely lower case.
```my.default.api.security.x```

or
```mydefaultapi.security.x```

**Comment by wing328** [comment]
@SirWayne thanks for reporting the issue, which can be fixed with mustache lambda.

Is that something you can help us with by filing a PR with the fix? Thanks in advance.
