### ISSUE TITLE
[REQ] [Kotlin] Switch between Moshi and Jackson depending on import library

### ISSUE THREAD

**Issue by herveDarritchon** [OpenAPITools/openapi-generator#3414]
### Is your feature request related to a problem? Please describe.

Currently with the Kotlin generator, there is no choice in the library used for marshalling/unmarshalling. Kotling codegen uses Moshi (may be because of the android history).

But when you use Jersey, Ktor ou Spring, you use more often Jackson than Moshi or at least Gson.

Because of this automatic import, you have to had Moshi in your build if you use codegen even if it is not really used. Moreover with Enum not respecting code convention you have runtime issue because Jackson is used to unmarshall you json string and the moshi annotation is not used.
One solution is to change the template to use Jackson instead of moshi but what's happening if you use moshi in your project ?

The good thing should be to work as in Java codegen, depending on the library imported, you use Moshi annotation or Jackson or Gson.

see issue swagger-codegen 7811 (https://github.com/swagger-api/swagger-codegen/issues/7811) for more details.

## Describe the solution you'd like

I'd like to be able to choose the lib for marshalling/unmarshalling imported and used by the code generated by openapi codegen

## Describe alternatives you've considered

I have thought about using a specific template using Jackson but it's not a good solution for me because you're duplicating efforts.

## Additional context

I'd like to make the pull request but before doing it I'd like to know if you think it is valuable for the community ;) and it can be integrated later if it works, it has the good quality :)

**Comment by wing328** [comment]
> I'd like to make the pull request but before doing it I'd like to know if you think it is valuable for the community ;) and it can be integrated later if it works, it has the good quality :)

I think it's definitely valuable.

For the Java client, it supports Jackson and GSON so I would foresee when the Kotlin gains more popularly, someone will ask for this feature.

Let us know if you need help with the PR to add an option to support Jackson in addition to Moshi.

**Comment by prisoneroftech** [comment]
I started a somewhat related change in swagger-codegen that I want to bring over to openapi-codegen. It only applies to kotlin-cli so far, though.
Here is the related PR in swagger-codegen. The code for openapi is very very similar. 

https://github.com/swagger-api/swagger-codegen/pull/9656

What do you think about bringing this part over? It is just for the client but at least it brings some gson support now.

**Comment by wing328** [comment]
Sure, we definitely welcome that. Let us know if you need help with the PR.

**Comment by prisoneroftech** [comment]
Sounds good. Should I create a separate issue to make it Kotlin client specific or associate the PR with fix_issue3414

**Comment by wing328** [comment]
Referencing the PR to this issue is fine.

**Comment by prisoneroftech** [comment]
I've created a pull request. #3734 https://github.com/OpenAPITools/openapi-generator/pull/3734

**Comment by prisoneroftech** [comment]
Any ideas what is going on here? https://travis-ci.org/OpenAPITools/openapi-generator/builds/576564797?utm_source=github_status&utm_medium=notification 

Running the same command on my machine works for me.
```
mvn --quiet --batch-mode --show-version clean install
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T15:00:29-04:00)
Maven home: /usr/local/Cellar/maven/3.6.1/libexec
Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[firstName, name, email, id]
[firstName, name, email]
[]
[name]
> Task :clean
The `kotlin-dsl` plugin applied to root project 'openapi-generator-gradle-plugin' enables experimental Kotlin compiler features. For more information see https://docs.gradle.org/4.10.2/userguide/kotlin_dsl.html#sec:kotlin-dsl_plugin
w: /Users/prisoneroftech/code/prisoneroftech/openapi-generator/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt: (602, 47): 'getter for config: CodegenConfig!' is deprecated. Deprecated in Java
w: /Users/prisoneroftech/code/prisoneroftech/openapi-generator/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt: (608, 40): 'getter for config: CodegenConfig!' is deprecated. Deprecated in Java
> Task :compileKotlin
> Task :compileJava NO-SOURCE
> Task :pluginDescriptors
> Task :processResources
> Task :classes
> Task :inspectClassesForKotlinIC
> Task :jar
> Task :javadoc NO-SOURCE
> Task :javadocJar
> Task :sourcesJar
> Task :assemble
> Task :generatePomFileForMavenJavaPublication
> Task :signMavenJavaPublication SKIPPED
> Task :publishMavenJavaPublicationToMavenLocal
> Task :generatePomFileForOpenApiGeneratorPluginMarkerMavenPublication
> Task :publishOpenApiGeneratorPluginMarkerMavenPublicationToMavenLocal
> Task :generatePomFileForPluginMavenPublication
> Task :publishPluginMavenPublicationToMavenLocal
> Task :publishToMavenLocal

BUILD SUCCESSFUL in 27s
14 actionable tasks: 14 executed

**Comment by gmariotti** [comment]
Is Jackson support still planned for Kotlin?

**Comment by herveDarritchon** [comment]
hi,

No answer since my last post so I have planned to add support for Jackson following the issue #3734

Are you ok with that ? No one is doing it ?

**Comment by parachutemind** [comment]
I'm cool with that! - I think it will be great to have Jackson support.
