### ISSUE TITLE
[BUG] Python generator incorrectly renames non-reserved model objects

### ISSUE THREAD

**Issue by rizwansaeed** [OpenAPITools/openapi-generator#3427]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

**Comment by spacether** [comment]
Hi there. Can you provide a sample spec that demonstrates this issue?
Without an input spec that shows the issue, we won't be able to fix it.

**Comment by rizwansaeed** [comment]
Apologies, this was raised in error and duplicates https://github.com/OpenAPITools/openapi-generator/issues/3428
