### ISSUE TITLE
[REQ] [JAVA] Java 11 Native HTTP client library

### ISSUE THREAD

**Issue by bbdouglas** [OpenAPITools/openapi-generator#3433]
##### Description

Support Java 11 Native HTTP client library.

New in the standard library of Java 11 is an [HTTPClient](https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpClient.html) class that simplifies much of the low-level details of making HTTP calls. Using this native client as opposed to a third party client such as Jersey or Feign comes with a few key benefits:

- Reduced set of dependencies for the caller
- Strong commitment to continuous support and backwards compatibility by the Java maintainers
- Up-to-date features such as HTTP2 support

##### openapi-generator version

4.1.0

##### OpenAPI declaration file content or url

Petstore

##### Command line used for generation

Standard

##### Steps to reproduce

There is no Java library that uses the native HTTPClient introduced in Java 11.

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

We at Yelp have developed a set of mustache templates for use with openapi-generator that produces native Java 11 HTTPClient-based client libraries. We actively use these clients in our production microservices infrastructure and find them robust and performant. We would like to propose integrating these with the main openapi-generator project to open up their use to the wider community.

**Comment by macjohnny** [comment]
@bbdouglas a contribution would be very welcome!

**Comment by bbdouglas** [comment]
CC @cbornet  @karismann  @Zomzog for other members of the Java technical committee.
