### ISSUE TITLE
[REQ][typescript-*] String Enums

### ISSUE THREAD

**Issue by eseliger** [OpenAPITools/openapi-generator#3451]
### Is your feature request related to a problem? Please describe.

Since TS version 2.4 string enums are supported, which are the preferred way of defining enums that can have string values (over the legacy object-type-dualism). https://www.typescriptlang.org/docs/handbook/enums.html#string-enums

## Describe the solution you'd like

I implemented it already on a branch for internal use at my company, which is using an additional property called "stringEnums" for now. No breaking change since it needs to be enabled, off by default

## Describe alternatives you've considered

Other solutions that would be possible are:
- Default to string enums, which would be incompatible with TS<2.4 and be a breaking change
- Add a proprietary flag to the openapi spec. I think this is not really desirable because most problems that are solved this way are rather specific to the operation, whereas this is more of a global flag IMO.

## Comparison of outputs

before:

```ts
export interface User {
    title: User.TitleEnum
    name: string
}
export namespace User {
	export type TitleEnum = 'Mr' | 'Mrs' | 'Ms'
	export const TitleEnum = {
	    Mr: 'Mr' as Title,
	    Mrs: 'Mrs' as Title,
	    Ms: 'Ms' as Title,
	}
}
```

with string enums enabled:

```ts
export interface User {
    title: UserTitle
    name: string
}
export enum UserTitle {
    Mr = 'Mr',
    Mrs = 'Mrs',
    Ms = 'Ms',
}
```

**Comment by macjohnny** [comment]
@eseliger a contribution would be welcome!

**Comment by eseliger** [comment]
@macjohnny I just realized when I wanted to port the changes to the other typescript clients, that most of them use string enums already, but typescript-angular doesn't.

What would you prefer?
- Align it and make it a breaking change
- Only implement it with the flag for typescript-angular and might remove it in v5

this one I meant 🤦‍♂

**Comment by macjohnny** [comment]
I would prefer to go with the flag, and decide later whether to default to true and introduce a breaking change. The typescript-generators are subject to refactoring, see https://github.com/OpenAPITools/openapi-generator/issues/802

**Comment by bodograumann** [comment]
This is not implemented for typescript-inversify.

Out of interest: What is your use case of enums in contrast to union types? I have found that the latter are sufficient.

**Comment by macjohnny** [comment]
Enum values can be re-used elsewhere

**Comment by ffMathy** [comment]
An exported type can also be used anywhere, no?

**Comment by Morriz** [comment]
this would be nice to see...has there been any activity on this request?

**Comment by bodograumann** [comment]
Which generator are you using, @Morriz ?

**Comment by Morriz** [comment]
Thanks for asking! Just upgraded `express-openapi` from `8.0.0` to `9.0.3` and that solved it ;)

**Comment by Morriz** [comment]
Grrr. Too quick. The typescript that gets generated is fine, but the `dist/*js` are not using the strings.

**Comment by bodograumann** [comment]
Could you please create a new issue, @Morriz ?

**Comment by Morriz** [comment]
not needed...the stuff shown in the debugger is not what is used I deduce. TS that generates enum NOT using strings is shown, but the JS is using strings.
