### ISSUE TITLE
[BUG] [typescript-angular] Angular 8: generated package.json includes `@angular/http` dependency

### ISSUE THREAD

**Issue by daniel-sc** [OpenAPITools/openapi-generator#3460]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating for `angular-typescript` and setting the Angular version to 8.x (e.g. 8.1.1) the generated package.json is invalid, as the included `@angular/http` is not available in version 8.1.1. 

##### openapi-generator version

4.0.3

##### Steps to reproduce

Generate with `<ngVersion>8.1.1</ngVersion>`

##### Suggest a fix

The dependency `@angular/http` should be removed from the generated `package.json` as it is now included in `@angular/common` - see e.g.: https://blog.angularindepth.com/embrace-yourself-angular-8-is-coming-1bf187c8f0bf

**Comment by macjohnny** [comment]
@daniel-sc would you like to file a PR to fix that?

**Comment by macjohnny** [comment]
you could use the `{{#useHttpClient}}` variable, see e.g. https://github.com/OpenAPITools/openapi-generator/blob/a3cf964ce929504e3906bad8a8f246bd77009f44/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L5-L15

**Comment by eseliger** [comment]
@macjohnny I have a fix for that ready, I can submit a pr in a few

**Comment by macjohnny** [comment]
@eseliger that would be great!

**Comment by eseliger** [comment]
@macjohnny I just realized when I wanted to port the changes to the other typescript clients, that most of them use string enums already, but typescript-angular doesn't. 

What would you prefer?
- Align it and make it a breaking change
- Only implement it with the flag for typescript-angular and might remove it in v5

**Comment by macjohnny** [comment]
wrong issue?

**Comment by eseliger** [comment]
the heck, sorry
