### ISSUE TITLE
[BUG] openapi-generator-gradle-plugin: systemProperties option :settings.gradle gets generated if apis and/or supportingFiles required to be generated

### ISSUE THREAD

**Issue by vmisra2018** [OpenAPITools/openapi-generator#3467]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ 4.0.3] What's the version of OpenAPI Generator used?
- [ YES] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### openapi-generator version
4.0.3

##### Steps to reproduce
1)I have a client  stub project which is a subfolder with a parent folder. The parent is having setting.gradle
rootProject.name = 'x-y-service'

include 'x-y-service-core'
include 'x-y-service-rest-api'
include 'x-y-service-rest-client'
include 'x-y-service-server'

Here the subfolder is 'x-y-service-rest-client' where I am generating client stubs. In this,I have
 build.gradle and I am trying o generate java reactive  webclient client stubs using gradle plugin and have defined  following task
```json
task generateItemApi(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask){
    generatorName = "java"
    inputSpec = "$rootDir/some.yaml".toString()
    outputDir = "$projectDir".toString()
    
    modelPackage = "<some name>"
    configOptions = [
            dateLibrary: "java8"
    ]
    systemProperties = [
            modelDocs: "false",
            models: ""
    ]
    skipValidateSpec = true
    logToStderr = true
    generateAliasAsModel = false
    additionalProperties = [
            reactive: true
    ]
    
    library = "webclient"
}

```
2) when I run this task, I get the models generated as expected.  Since this is a client stub, i have dependency from server api so dont need models as I am generating them in server stub.
But I need apis and supportingFiles. So I make changes as below  :  
```json
task generateItemApi(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask){
//
 systemProperties = [
            modelDocs: "false",
            apis: "",
            supportingFiles:""
    ]
//
}
```
3) The change in 2 ) results in a file "settings.gradle" being generated in this client stub folder after first run which has with an entry in it. Note that this was not generated in step2 . This only happens with apis and/or supportingFiles . The new settings.gradle has entry:
rootProject.name = "openapi-java-client"

This causes issues as I cant generate in next run as it keeps complaining about folders and I see message:

* What went wrong:
A problem occurred evaluating root project 'openapi-java-client'.
> Project with path ':x-y-service-core' could not be found in root project 'openapi-java-client'.

**Comment by jimschubert** [comment]
Can you provide an example of the working tree structure in these cases (expected vs actual)?

I'm a little confused by the expected output. When you define `supportingFiles`, this means that you want the extra files that the template defines.  In your first task, you're saying to only generate models.

It seems to me like you might expect a structure that's not achievable by the selective generation properties. You might want to consider specifying an ignore file (see https://openapi-generator.tech/docs/customization#ignore-file-format). The file syntax is just like gitignore, and gives greater control over what the generator is allowed to generate.

**Comment by vmisra2018** [comment]
Hi Jim,
 I no longer have this issue. (May be my gradle config issue) .
Not able to replicate.  By supportingFiles, I want to to genenrates files like ApiClient.java and Auth package. (which it did). 
Thanks for looking into it.
Vivek
