### ISSUE TITLE
[BUG][typescript-fetch] withInterfaces option does not generate interfaces

### ISSUE THREAD

**Issue by fuzzzerd** [OpenAPITools/openapi-generator#3478]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Compare these files in the samples directory:

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-fetch/builds/default/apis/PetApi.ts

vs 

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-fetch/builds/with-interfaces/apis/PetApi.ts

##### openapi-generator version

Master branch

##### Suggest a fix

Could not find reference to `withInterfaces` parameter in the mustache templates, and no difference in the generated api. 

Option should be removed from documentation or re-implemented for `typescript-fetch` 

https://openapi-generator.tech/docs/generators/typescript-fetch

**Comment by macjohnny** [comment]
cc @TiFu are the interfaces necessary? classes can also be used as interfaces...

**Comment by fuzzzerd** [comment]
> classes can also be used as interfaces...

Is that the recommended guidance outside the Angular style guide? I've found at least one dissenter: https://www.stevefenton.co.uk/2017/11/typescript-using-classes-interfaces/

> are the interfaces necessary? 

Even if not, the tooling not providing them when it used to should be a breaking change at least.

**Comment by macjohnny** [comment]
I agree that a class which contains logic either in the constructor or in some methods should not be used as an interface. However, for generated model-interfaces I think this is not a problem.

Yes, the refactoring caused some breaking changes, this should have been avoided.

**Comment by fuzzzerd** [comment]
I was not concerned with the models; but with the api clients themselves. They used to have interfaces too and are arguably the more valuable piece that was lost.

**Comment by Prior99** [comment]
We're also kind of stuck with the missing interfaces. We were using them to mock the Api's for testing purposes.
