### ISSUE TITLE
Rename local variable with prefix "local_var_" in Python client

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#348]
##### Description

We will need to rename the local variables in Python client with the prefix "local_var_" to avoid conflicts with the endpiont parameters or reserved keywords

e.g. renaming `params` to `local_var_params` in https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/api/pet_api.py

##### Swagger-codegen version

Latest master

##### Suggest a fix/enhancement

If anyone wants to work on this, please reply to let us know.

A good starting point it the mustache templates: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/python

**Comment by tomplus** [comment]
Hi @wing328 I don't know which `params `you want to rename. For sure we have a problem with `async` which has became keywords in recently released Python 3.7.

**Comment by wing328** [comment]
`params` is a good starting point: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/petstore_api/api/pet_api.py#L172 ([template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/api.mustache#L91))

`collection_formats` is another good candidate: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/api.mustache#L147

For `async`, we can whitelist it for the time being.
