### ISSUE TITLE
[REQ][Kotlin-client] Support for authentication

### ISSUE THREAD

**Issue by armandmgt** [OpenAPITools/openapi-generator#3482]
### Is your feature request related to a problem? Please describe.

The `securitySchemes` or `securityDefinitions` are not taken into account in the generated client.

## Describe the solution you'd like

The code generator should support them as they are already supported in other languages (e.g. ruby-client)

## Describe alternatives you've considered

I can workaround this by using a custom template but I feel like this should be supported in the generator

**Comment by armandmgt** [comment]
I managed to support it but I have no idea if I did it the right way, would you guys be interested in a PR ?

**Comment by wing328** [comment]
@armandmgt yes please submit a PR so that we can review your fix.
