### ISSUE TITLE
[REQ] [Java][Spring] Add support for custom validation messages in Beanvalidation annotations

### ISSUE THREAD

**Issue by vijjayy81** [OpenAPITools/openapi-generator#3519]
The feature specified in https://github.com/swagger-api/swagger-codegen/issues/5643 not available with openapi-generator.

**Comment by cpandya231** [comment]
@vijjayy81 Have you found any updates or workaround? I am not able add custom message for validation errors

**Comment by cpandya231** [comment]
@HugoMario Since you have worked on this issue [5643](https://github.com/swagger-api/swagger-codegen/issues/5643), can you please help on how to provide message on validation failure in swagger-codegen?

**Comment by vijjayy81** [comment]
@cpandya231  I have not found any workaround for this.

@HugoMario Could you please help us to add this feature in to openapi generator?

**Comment by vijjayy81** [comment]
@cpandya231  I have not found any workaround for this.

@HugoMario Could you please help us to add this feature in to openapi generator?

**Comment by cpandya231** [comment]
I tried to replicate changes done by @HugoMario  in   [swagger-api/swagger-codegen#5643](https://github.com/swagger-api/swagger-codegen/issues/5643). 

But getting failed unit tests, @vijjayy81 would like to collaborate with me?
