### ISSUE TITLE
[REQ] [KOTLIN] Don't use TODO() function provided by Kotlin

### ISSUE THREAD

**Issue by toXel** [OpenAPITools/openapi-generator#3529]
The use of the Kotlin function TODO() can IMO be dangerous sometimes. For example here:
https://github.com/OpenAPITools/openapi-generator/blob/4d285939a662312b99b238dc5385fea548253ba2/modules/openapi-generator/src/main/resources/kotlin-client/infrastructure/ApiClient.kt.mustache#L60-L63

When `mediaType` is not `application/json` the app or program, in which the client is used, just crashes. AFAIK there is no way to catch these exceptions without modifying the `ApiClient` class.

## Describe the solution you'd like

Replace `TODO()` calls with catchable exceptions or return null and add an `// TODO` comment. I've tested both attempts and they worked without crashing the app.

**Comment by jimschubert** [comment]
👍  I think the custom exception option would be the better approach than an implementer comment and returning null.

**Comment by jimschubert** [comment]
I opened #3611 to change `TODO()` to `throw UnsupportedOperationException`. What are your thoughts on this exception type rather than some custom exception?

**Comment by toXel** [comment]
I think that's a great solution. Thank you for the PR! I hope it'll be merged soon.

**Comment by jimschubert** [comment]
I've merged the PR. Please keep an eye out for the change in the latest snapshot.

Feel free to reopen the issue if the fix needs any adjustments.
