### ISSUE TITLE
Add ignore-models to generators

### ISSUE THREAD

**Issue by kjq** [OpenAPITools/openapi-generator#3563]
### Is your feature request related to a problem? Please describe.

We have the need to "exclude" models before the generation using the Maven plugin to cleanup the final generated code.  We have only a handful of models that this needs to happen (less than if we use the whitelist approach of models to be included).

I am filing this per a comment from Jim Schubert:
>If you'd like, you could open an issue explaining the use case... I think an ignore-models (and APIs equivalent) option would be easy enough to add for more advanced usage (although, I'd consider it highly experimental).

## Describe the solution you'd like

The generated outputs work for the most part but a lot of "transitive" dependencies are generated which sometimes cause issue.  One example that seems to crop up is when dealing with Multipart files, the Angular generator for example renders improper models (with generics) and this could be alleviated by "excluding" the models pre-generation.  Also, transitive models, such as Flux or Mono from the Java side are not needed or used (the Spring WebClient correctly generates them already).

## Describe alternatives you've considered

We tried using the .ignore file which does ignore them from the generated outputs but in cases like Node or Angular they were still defined in the files.

**Comment by richardwhiuk** [comment]
Do you have a sample API you can share which demonstrates the problem?

Normally I'd expect all models generated to be used by the API in some form?

**Comment by kjq** [comment]
Sure, i will update the ticket tonight with some samples.  Real quick, we have resources/endpoints annotated with JAX-RS using Project Reactor (but not Webflux from SpringBoot - we use CXF).

The generated outputs for non-reactor projects (or outside of java) are correct - List<XXX> or XXX (in the case of Mono).  The generated output for Spring WebClient is also correct using Flux or Mono form.  BUT, what does get generated in addition to the regular outputs are FluxXXX and MonoXXX models as well.  They are not used/referenced anywhere and in the case of the JS generators included in the models.ts.

In this example below there is a `FluxFileResult` and `FileResult` model - i can safely ignore the FluxFileResult, and actually the Flux itself because most of the clients do not support/need it.

If there is another way to do this or I am doing the mapping wrong I can work with that.  It also pollutes the generated code when they are not used too.

```
    @POST
    @Path("/uploads")
    @Produces(APPLICATION_JSON)
    @Consumes(MULTIPART_FORM_DATA)
    @Operation(
        operationId = "uploadFilesExample",
        summary = "Upload files",
        description = "Upload files",
        parameters = {
            @Parameter(name = "client", description = "Client name", required = true),
            @Parameter(name = "project", description = "Project name", required = true),
            @Parameter(name = "unique", description = "Use unique names")},
        requestBody = @RequestBody(
            content = @Content(
                schema = @Schema(implementation = MultipartRequest.class))),
        responses = {
            @ApiResponse(
                responseCode = "200",
                description = "The uploaded files",
                content = @Content(
                    array = @ArraySchema(
                        schema = @Schema(implementation = FileResult.class)))),
            @ApiResponse(responseCode = "400", description = "Bad request"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "409", description = "Version Conflict"),
            @ApiResponse(responseCode = "500", description = "Backend Error")})
    @PreAuthorize("isSecured(#client, 'projects', 'write')")
    public Flux<FileResult> uploadFiles(@PathParam("client") String client,
                                        @PathParam("project") String project,
                                        @QueryParam("unique") @DefaultValue("false") boolean unique,
                                        @Parameter(hidden = true) @Context HttpServletRequest request)
```

**Comment by richardwhiuk** [comment]
Ah right, these aren't really models, but auxiliary types which one generator is creating.

**Comment by Paul-Etienne** [comment]
I'm working on a project where this exact need arose. We would need to generate everything but an API and one model class. With the whitelist approach we have to specify all 9 classes that we want to keep and would have to update it every time there's an evolution to the interface. While we only need to exclude one model. Long story short, sometimes specifying a blacklist is more convenient than a whitelist, I'd be glad if this feature was added in an upcoming update.

**Comment by dominik-seichter** [comment]
Currently, there is a modelsToGenerate flag - I would also agree that a modelsToExclude option would be very convinient in many cases.

**Comment by joheb-mohemian** [comment]
@kjq was this really completed? I don't see a modelsToExclude flag in version 6.4.0 of the maven plugin.

**Comment by kjq** [comment]
This was a long time ago when we were using SpringBoot with Project Reactor.  We have shifted to a different stack and I have not heard any grumblings about it since.

**Comment by wing328** [comment]
Another way is to use .openapi-generator-ignore file to skip certain files from being generated: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#ignore-file-format

**Comment by amakhrov** [comment]
Looks like `.openapi-generator-ignore` applies to files, while a model (or an API) can surface in other places, too. E.g. for the `java` generator, all models are enumerated in `README.md` - even if I exclude one of the generated model file via `.openapi-generator-ignore`
