### ISSUE TITLE
[REQ][Elm] Remove `DateTime` in favour of `Posix`

### ISSUE THREAD

**Issue by andys8** [OpenAPITools/openapi-generator#3578]
### Is your feature request related to a problem? Please describe.

Generated code is obfuscating `Posix` with a new name `DateTime`.

## Describe the solution you'd like

[`DateTime`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/elm/DateTime.mustache) is an alias for [`Time.Posix`](https://package.elm-lang.org/packages/elm/time/1.0.0/Time#Posix). Since `Time.Posix` is now being used everywhere in Elm applications, it could make sense to remove the `type alias` for clarification. I think this is a left-over from the code base before `Time.Posix` was introduced.

**Comment by wing328** [comment]
@andys8 thanks for the suggestion.

cc @eriktim

**Comment by wing328** [comment]
What about using `--type-mapping` with `Time.Posix` for the time being?

**Comment by andys8** [comment]
@wing328 Could work, but isn't really necessary. Because it's a `type alias` it can be used the same way without the need to convert it.

The suggestion is mainly targetted towards avoiding confusion and using the type people know.

**Comment by eriktim** [comment]
I could rename the alias to `Posix`. That indeed makes sense. We can still use the decoder/encoder then. Any suggestions what to do with the `DateOnly` version then? Alias it as `PosixDate`? I do like the fact the type (alias) keeps them distinct.

**Comment by andys8** [comment]
I was thinking of dropping the name. Is anything wrong with it or would you subject doing it like this?

```elm
module DateTime exposing (decoder, encode, toString)

import Iso8601
import Json.Decode as Decode exposing (Decoder)
import Json.Encode as Encode
import Result
import Time exposing (Posix)


decoder : Decoder Posix
decoder =
    Decode.string
        |> Decode.andThen decodeIsoString


encode : Posix -> Encode.Value
encode =
    Encode.string << toString


decodeIsoString : String -> Decoder Posix
decodeIsoString str =
    case Iso8601.toTime str of
        Result.Ok posix ->
            Decode.succeed posix

        Result.Err _ ->
            Decode.fail <| "Invalid date: " ++ str


toString : Posix -> String
toString =
    Iso8601.fromTime
```

**Comment by eriktim** [comment]
There are two issues here:
* To be honest I do not know how easy it would be to have the type (`Posix`) come from a different module than the de/encoders (`DateTime`) in the generator;
* There is also `DateOnly`. I would like the record to have distinct types for dates with time and dates without time.

**Comment by eriktim** [comment]
In the upcoming 5.0.0 release both `date` and `date-time` are now `Posix` values. Be aware that in case of `date` not the exact `Posix` value gets transmitted as the time is stripped off.
