### ISSUE TITLE
[java][model] Collection initialized to empty collection even if not required

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#3585]
We are trying to use the same model between our client (using a model serialized with Jackson) and server (JaxRS jersey2).

If a collection is not required, the server model set its value to `null`.

https://github.com/OpenAPITools/openapi-generator/blob/7f36f2642209c6d7070e1d76209ba1928d816922/modules/openapi-generator/src/main/resources/JavaJaxRS/pojo.mustache#L24-L29

This is not the case on client side.

https://github.com/OpenAPITools/openapi-generator/blob/7f36f2642209c6d7070e1d76209ba1928d816922/modules/openapi-generator/src/main/resources/Java/pojo.mustache#L61

In my opinion this should be aligned.

**Comment by bkabrda** [comment]
👍 from my side. It also leads to problems like always sending empty `{}` when you don't touch a value of that attribute, which can be problematic when doing `PATCH` requests that are only expected to change certain parts of the resource, but with this issue they actually reset some attributes to empty.

**Comment by viclovsky** [comment]
I use rest-assured client for testing. 
The issue leads to inability to check that a field is definitely absent (by comparing by null), because collections are always empty.

**Comment by jmini** [comment]
@bkabrda thank you for your feedback, you wrote exactly what I wanted to add. This is a valid argument for people who are interested only in the java-client (and do not care about client and server being aligned).

---
I have proposed the change in PR #3615
