### ISSUE TITLE
Modernize samples yaml files

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#359]
##### Description

Samples located here are still using an old specification version: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/yaml/

Could we give it a fresh look?

Old specification files should be kept in a subfolder for backward compatibility test if needed.

##### openapi-generator version

HEAD

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/yaml/

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

Not that I know

##### Suggest a fix/enhancement

Inspire from the one found here: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/test/resources

ping @wing328 @jmini

**Comment by jmini** [comment]
Thank you for this issue.

The `/samples` folder contains the output of generators triggered by `bin/*.sh` scripts.
I think this should be the case for `/samples/yaml`.

We need a script `bin/petstore-openapi-yaml.sh` that triggers the `openapi-yaml` generator for our petstore input spec and that outputs it results to `/samples/yaml`.
