### ISSUE TITLE
[BUG][kotlin-spring] "SwaggerAnnotations=true"  leads into compile error when using inheritance

### ISSUE THREAD

**Issue by d0x** [OpenAPITools/openapi-generator#3596]
##### Description

When using inheritance, the generated code won't compile. It fails with this error:

> This annotation is not applicable to target 'member property without backing field or delegate'

You can see it in this example:

```kotlin
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "animalType", visible = true)
@JsonSubTypes(
      JsonSubTypes.Type(value = Pet::class, name = "Pet")
)
interface Animal{
                @ApiModelProperty(example = "null", value = "")
                // ^^^^^^^^^^^^^^^^^^^ This annotation is not applicable to target 'member property without backing field or delegate'
        val weight: java.math.BigDecimal? 
}
```

##### openapi-generator version

Generator Version 4.0.3
Spec Version 3.0.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  title: example
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: successful operation
components:
  schemas:
    Animal:
      type: object
      properties:
        weight:
          type: number
      discriminator:
        propertyName: animalType
      required:
        - animalType
    Pet:
      allOf:
        - $ref: "#/components/schemas/Animal"
        - type: object
          properties:
            name:
              type: string
```

##### Command line used for generation

```bash
openapi-generator generate -i myspec.yml -g kotlin-spring \
        -Dmodels \
        -Dapis \
        --additional-properties=interfaceOnly=true \
        --additional-properties=gradleBuildFile=false \
        --additional-properties=exceptionHandler=false \
        --additional-properties swaggerAnnotations=true \
        --additional-properties=sourceFolder=src/gen/kotlin
```

##### Steps to reproduce

Generate the spec above and check the Animal class.

##### Related issues/PRs

There is another issue related to inheritance:
- https://github.com/OpenAPITools/openapi-generator/issues/1205
- https://github.com/OpenAPITools/openapi-generator/issues/3587

**Comment by mdoh** [comment]
If the property would loo like this on the  Animal interface`@get:ApiModelProperty` the compile error is gone

**Comment by ralfstuckert** [comment]
Any news here?

**Comment by jrsall92** [comment]
bump

**Comment by superbob** [comment]
I am also facing this issue using the gradle plugin (org.openapi.generator) in version 6.6.0.  
I can provide an example project if needed, but I think the initial example is still relevant.

**Comment by superbob** [comment]
I've just submitted an MR to fix this. Hope this will be merged soon 🙏

**Comment by superbob** [comment]
Hello, I just found a workaround to this problem by reading to the [Using Templates - Modifying Templates official doc](https://openapi-generator.tech/docs/templating/#modifying-templates).

Depending on the tool you use, you may need to adapt but the main idea is this:

1. Create a folder near your source files (I used src/template)
2. Put the two following files in this folder (they are the fixed files that I put in [my PR](https://github.com/OpenAPITools/openapi-generator/pull/15488)):
    * [interfaceOptVar.mustache](https://raw.githubusercontent.com/superbob/openapi-generator/master/modules/openapi-generator/src/main/resources/kotlin-spring/interfaceOptVar.mustache)
    * [interfaceReqVar.mustache](https://raw.githubusercontent.com/superbob/openapi-generator/master/modules/openapi-generator/src/main/resources/kotlin-spring/interfaceReqVar.mustache)
    In the end it should look like this: 
    ![Capture d’écran 2023-05-12 à 17 45 30](https://github.com/OpenAPITools/openapi-generator/assets/1587431/749a7c57-c3ff-4f5e-99e7-359a659c551e)
3. Add the relevant [user-defined template](https://openapi-generator.tech/docs/templating/#modifying-templates) configuration depending on how you run the generator.
    * In my case, I'm using the Gradle plugin generator so I added the following config to my `build.gradle.kts` file:
    ```kotlin
    openApiGenerate {
        [...]
        templateDir.set("$projectDir/src/template")
    }
    ```

And that's it!

**Comment by dimrad-RB** [comment]
> Hello, I just found a workaround to this problem by reading to the [Using Templates - Modifying Templates official doc](https://openapi-generator.tech/docs/templating/#modifying-templates).
> 
> Depending on the tool you use, you may need to adapt but the main idea is this:
> 
> 1. Create a folder near your source files (I used src/template)
> 2. Put the two following files in this folder (they are the fixed files that I put in [my PR](https://github.com/OpenAPITools/openapi-generator/pull/15488)):
>    
>    * [interfaceOptVar.mustache](https://raw.githubusercontent.com/superbob/openapi-generator/master/modules/openapi-generator/src/main/resources/kotlin-spring/interfaceOptVar.mustache)
>    * [interfaceReqVar.mustache](https://raw.githubusercontent.com/superbob/openapi-generator/master/modules/openapi-generator/src/main/resources/kotlin-spring/interfaceReqVar.mustache)
>      In the end it should look like this:
>      ![Capture d’écran 2023-05-12 à 17 45 30](https://user-images.githubusercontent.com/1587431/238019191-749a7c57-c3ff-4f5e-99e7-359a659c551e.png)
> 3. Add the relevant [user-defined template](https://openapi-generator.tech/docs/templating/#modifying-templates) configuration depending on how you run the generator.
>    
>    * In my case, I'm using the Gradle plugin generator so I added the following config to my `build.gradle.kts` file:
>    
>    ```kotlin
>    openApiGenerate {
>        [...]
>        templateDir.set("$projectDir/src/template")
>    }
>    ```
> 
> And that's it!

Thanks, man. This is great!

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/15488 has been merged. Thanks again for the PR.

Closing this issue.
