### ISSUE TITLE
[BUG][resttemplate] Object with additionalProperties (HashMap) does not generate a model

### ISSUE THREAD

**Issue by Na3blis** [OpenAPITools/openapi-generator#3602]
##### Description

I am trying to generate a HashMap class, but no class is generated and a plain Java Map is used where the class `ContextHeaders` should be used. 

```
  @JsonProperty("contextHeaders")

  private Map contextHeaders = null;
```

##### openapi-generator version

4.0.3

##### OpenAPI declaration file content or url

[swagger.json](https://gist.github.com/Na3blis/93dbca819faf2598fdae5f595dbf66e9)
[swagger-client-config.json](https://gist.github.com/Na3blis/b175b9db83fde16f3229708416c102a1)
##### Command line used for generation

`curl -s -o ./codegen.jar http://central.maven.org/maven2/org/openapitools/openapi-generator-cli/4.0.3/openapi-generator-cli-4.0.3.jar`
`java -jar ./codegen.jar generate -c ./swagger-client-config.json -i ./swagger.json -g java -o generated-client/`

##### Steps to reproduce

Run the codegen 4.0.3 against the swagger.json file with the config swagger-client-config.json. Notice there is no `com.example.authrules.v1.client.model.ContextHeaders` class, and `com.example.authrules.v1.client.model.RulesUser` references a plain Java Map instead of a class

**Comment by jmini** [comment]
Can you please switch to a newer version of OpenAPI generator?

Can you provide a small OpenAPI-Spec that show what is not working for you?

**Comment by Na3blis** [comment]
@jmini I just tried with 4.1.0 same results, as well as with the 4.2 snapshot.

[Here](https://swagger.io/docs/specification/data-models/dictionaries/) is what I'm referring to. Currently I'm using a 2.0 spec, and swagger-codegen 2.3.1 and it generates [ContextHeaders.java](https://gist.github.com/Na3blis/2d0d2d73d3960b776884ebf0ba94889e).
And in the model that references that, it has: 
```
  @JsonProperty("contextHeaders")
  private ContextHeaders contextHeaders = null;
```
However, when using the 3.0 spec, it still creates a `HashMap<String, List>`, the problem is that it's not it's own Model Object as before, where it's referenced it shows up now as 
```
  public static final String JSON_PROPERTY_CONTEXT_HEADERS = "contextHeaders";
  @JsonProperty(JSON_PROPERTY_CONTEXT_HEADERS)
  private Map<String, List<String>> contextHeaders = new HashMap<String, List<String>>();
```

**Comment by jmini** [comment]
I think that with `generateAliasAsModel` you get the Swagger-Codegen behavior where models (`ContextHeaders extends Map<String, List<String>>`) are created .

See: https://github.com/OpenAPITools/openapi-generator/issues/472

**Comment by Na3blis** [comment]
Thanks, that does look like the solution! However it does not create the object correctly when referenced,
`[ERROR] /Users/tim/dev/authorization-rules-service/generated-client/src/main/java/com/example/authrules/v1/client/model/RulesUser.java:[146,43] incompatible types: java.util.HashMap<java.lang.String,java.util.List<java.lang.String>> cannot be converted to com.example.authrules.v1.client.model.ContextHeaders`

And in the RulesUser class it has:
```
public static final String JSON_PROPERTY_CONTEXT_HEADERS = "contextHeaders";
  @JsonProperty(JSON_PROPERTY_CONTEXT_HEADERS)
  private ContextHeaders contextHeaders = new HashMap<String, List<String>>();
```
So it's trying to instantiate it as a `HashMap` instead of as a new `ContextHeaders` object.

**Comment by bodograumann** [comment]
We have just encountered the same behaviour as @Na3blis. The problem is that, while `DefaultGenerator` does generate the model definition file in the `generateModels` method, `DefaultCodegen` does not reference them in the `fromRequestBody` method.

I'll try to fix it.

**Comment by Praveen2518** [comment]
@Na3blis   did you get the answer why ContextHeaders object created with HashMap and how can we fix this

**Comment by Na3blis** [comment]
> @Na3blis did you get the answer why ContextHeaders object created with HashMap and how can we fix this

Unfortunately not. I think I ended up having to change the api to work around this
