### ISSUE TITLE
[REQ] [Dart] Don't initialize variables to null

### ISSUE THREAD

**Issue by nickmeinhold** [OpenAPITools/openapi-generator#3633]
### Is your feature request related to a problem? Please describe.

Models have their members initialized to null which is against the Effective Dart guidelines. 

## Describe the solution you'd like

When the default value is null, just declare the variable as in Dart, "a variable or field that is not explicitly initialized automatically gets initialized to null" and "Adding = null is redundant and unneeded."

## Describe alternatives you've considered

I tried using an inverted section based on the defaultValue but it didn't work, I don't know mustache well enough yet but I'll come back to it.

## Additional context

https://dart.dev/guides/language/effective-dart/usage#dont-explicitly-initialize-variables-to-null

**Comment by wing328** [comment]
OK. I can take a look as I'm familiar with the default value.
