### ISSUE TITLE
DockerHub: consume a specific version ("3.0.x" or "3.1.x")

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#364]
I am not a DockerHub user myself, now that we have introduced branches to work on different version of the project:

(current state 21.06.2018)
* `master` for version `3.0.3-SNAPSHOT`
* `3.1.x` for version `3.1.0-SNAPSHOT`
* `4.0.x` for version `4.0.0-SNAPSHOT`

See also: https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches

I am wondering how this works in DockerHub:
https://hub.docker.com/r/openapitools/openapi-generator-cli/tags/

"latest" tag seems to be the last built, regardless of the branch.

What would make sense?

* "latest" for latest from the `master` branch
* "latest_<branch name>" in the other cases (for our protected branches like `3.1.x` and `4.0.x` - not for the working branches)

**Comment by etherealjoy** [comment]
`latest` would be `master` 
`3.1.x` would be `3.1.0-SNAPSHOT`
This is usually the norm but is not binding

**Comment by jmini** [comment]
According to those lines:

https://github.com/OpenAPITools/openapi-generator/blob/12ab7e27521dce18b7fb27e40ce2eb636f4fac29/.travis.yml#L125-L128

We are not pushing the Docker images for the `3.1.x` and `4.0.x` branches.

On the Docker-Hub `latest` Tag, you can the continuously built artifact from the `master` branch.

---

I am not sure if there is an interest to have other GitHub-tags for the other branches.

**Comment by wing328** [comment]
What about using tags like "SNAPSHOT" (e.g. 3.1.1-SNAPSHOT) as @etherealjoy suggested? (I don't think in general SNAPSHOT is exclusively used for Java JAR and developers should be able to understand what SNAPSHOT mean for a docker image release)

**Comment by etherealjoy** [comment]
> latest would be master
3.1.x would be 3.1.0-SNAPSHOT
This is usually the norm but is not binding

This is like @jimschubert  mentioned is the norm. But of course not every docker repo follows this.
tag `latest` --> `master` branch
tag `3.0.x` --> `3.0.x` branch if it exists
tag `3.0` --> last released `3.0.x` branch if it exists, or 3.0.0 for the particular version.
tags has to reference a persistent branch not something which will be merged and deleted.
Multiple tags can be applied to an image.

**Comment by jmini** [comment]
@etherealjoy 

I think it would make sense to create `3.1.x` tag on DockerHub.

"Tag `3.1.x` --> `3.1.x` branch if it exists" as you have proposed. It will contains the latest `3.1.0-SNAPSHOT` versions until the `3.0.x-SNAPSHOT` versions are dropped. Because then, we will merge back `3.1.x` branch on `master` see ([merging back on master](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches#merging-back-on-master) section) and `latest` will contains the latest `3.1.0-SNAPSHOT` versions.

Does this make sense to you? Or not at all?

**Comment by etherealjoy** [comment]
Ok. It makes sense.
Do you plan long term tags like `3.1` for example? it is not normal for a tag to disappear. Users  can get a specific tag `3.1.1` or `3.1.2` but `3.1` tag for example need to point to one of these stable versions. And `latest` simply points to whichever is on `master`.
When you merge the branch the image remains. Do you want to remove the image tag as well?

**Comment by jmini** [comment]
@etherealjoy thank you so much for your inputs on this topic.

The point with the tags was bother me and you are right, tags should not disappear... I am not a DockerHub user, but if I compare it with maven central, it makes sense to me.

I think that having DockerHub tags entirely coupled to our git branches makes no sense from an DockerHub user perspective.

This is my last proposition:

* Released version **[already implemented, no changes]**: DockerHub tag match the Tag in the git repository. Examples:
   - `v3.0.0` Tag: `3.0.0` released version.
   - `v3.0.1` Tag
   - `v3.0.2` Tag
* Continuously built version (after each commit) **[NEW]**:
   - `3.0.x` Tag: this should contain first `3.0.2-SNAPSHOT` and after the `3.0.2` release it switches to `3.0.3-SNAPSHOT`.
   - `3.1.x` Tag: contains `3.1.0-SNAPSHOT` regardless of the branch (working branch `3.1.x` or `master` when we have merged back). After the `3.1.0` release it will contains `3.1.1-SNAPSHOT` and so on.
   - And similars `3.2.x`, `4.0.x`, …
* `lastest` Tag: **[current implementation, with some clarification]**
   - this contains the version built from our `master` branch. Right now it is `3.0.3-SNAPSHOT` but then it will be `3.1.0-SNAPSHOT`, `3.1.1-SNAPSHOT`, … , `3.2.0-SNAPSHOT`, …, `4.0.0-SNAPSHOT`.
   - what is new: we will not tag each build with `latest` docker tag, because otherwise you would get a random version depending if the last build was made from our `master` branch or from one of our working git branches (currently `3.1.x` and `4.0.x`)

This way as a DockerHub user you can follow the stream you are really interested in.

Of course with this new system the same Docker image build gets potentially tagged multiple times. Examples: 

* A continuous build of the master branch, gets tagged as `lastest` and as `3.0.x`. 
* A tag build gets tagged as `v3.0.3` and as `3.0.x` this is also OK.

This is fine and [possible](https://stackoverflow.com/a/35565384).

I will propose a PR in this direction. Feel free to give your feedback.

**Comment by jimschubert** [comment]
Also, I've mentioned this before but it would be much better if we created an automated build in DockerHub to handle these building and tagging rules.

Would anyone object if I created a single automated repo for demonstration of settings? A DockerHub automated build allows you to build based on regex criteria on branch/tag, and other settings that would allow us to offload that build. We may need to modify our Dockerfile (or create a secondary Dockerfile) to perform the build, but that's a very minor change to reduce our build complexity in my opinion.

**Comment by jimschubert** [comment]
@jmini

> 3.1.x Tag: contains 3.1.0-SNAPSHOT regardless of the branch (working branch 3.1.x or master when we have merged back). After the 3.1.0 release it will contains 3.1.1-SNAPSHOT and so on.

This doesn't make sense to include `master` here. After we merge a 3.1.0 branch, if following a steady feature branch format then we would have a 3.1.1 branch which would become the latest on this major-minor tag. Having these "snapshot" branches moving from feature to master and back would quickly become confusing, especially when the likelihood is that users are only pulling latest or trying a feature branch upon our suggestion to evaluate a change.

Tags of 3.0.x or similar should really only occur from a single place (be it a feature branch or tracking master), as once integrated into master for release, it would no longer be a snapshot.

I couldn't tell from your comment if this is what you meant, so I wanted to add clarity/clarification about it.

**Comment by jmini** [comment]
@jimschubert : I think we speak from the same... but I am confused by your comment.

I did not decide at all how the branching model works. @wing328 designed it and I wrote it down in this wiki page: [Git Branches](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches).

There is one short period of time where the `3.1.0-SNAPSHOT` is built from master. Right after the `3.0.3` release the `3.1.x` git branch is merged back to master and is removed.
The next release few days later is `3.1.0` built from `master` (we always built from `master`)

In some of your comment you have proposed to use Git-Flow. This project is not using Git-Flow for the moment. It is similar, but a little bit easier is my opinion.

A lot of user are just used to file PRs against `master`.
If we would use Git-Flow we would always have to change the PR to an other Branch.
Because in a Git-Flow model, you never develop against `master`. You merge to `master` to build and deploy to production (in our case: build the release).

---

This discussion about branches goes way out the scope of this issue, which is about improving the way the Docker-Tags works... For the moment we do not have any way for our DockerHub users to test `4.0.0-SNAPSHOT`. This is the important point.

**Comment by jmini** [comment]
I have proposed PR #390 to introduce new DockerHub tags: `3.0.x`, `3.1.x` and `4.0.x`.

**Comment by jmini** [comment]
> I've mentioned this before but it would be much better if we created an automated build in DockerHub to handle these building and tagging rules.
> 
> Would anyone object if I created a single automated repo for demonstration of settings? A DockerHub automated build allows you to build based on regex criteria on branch/tag, and other settings that would allow us to offload that build. We may need to modify our Dockerfile (or create a secondary Dockerfile) to perform the build, but that's a very minor change to reduce our build complexity in my opinion.

@jimschubert: you have a lot of release engineering knowlege and I think I can learn a lot from you. There are a lot of stuff that can be improved in this project. I am not against it.

For the moment I like to solve the problems in a way I know, without having to learn too much new stuff.

I think that the DockerHub tags are much more maven/gradle version driven than git-branch driven (see previous discussion).

**Comment by jmini** [comment]
See #836

**Comment by jimschubert** [comment]
This has been done for a while via automated builds in DockerHub.

See https://hub.docker.com/repository/docker/openapitools/openapi-generator/tags?page=1

![image](https://user-images.githubusercontent.com/109659/83955293-5747d780-a81f-11ea-8167-6d9d0a766c06.png)

I've opened #6573 to add a stable tracking latest tag. I don't think there's anything else to be done from a docker image release management perspective.
