### ISSUE TITLE
[REQ] [Dart] instructions in generated README are problematic

### ISSUE THREAD

**Issue by nickmeinhold** [OpenAPITools/openapi-generator#3641]
### Is your feature request related to a problem? Please describe.

I spoke to someone today who was having issues trying to use a generated client as the README instructions are a bit confusing and incorrectly use a mapping value.

The generated README includes instructions like this:

If this Dart package is published to Github, please include the following in pubspec.yaml
```Dart
name: api_client
version: 0.0.1
description: OpenAPI API client
dependencies:
  api_client:
    git: https://github.com/username/api_client.git
      version: 'any'
```

## Describe the solution you'd like
 
Get rid of the first 3 three lines and the last line and change the wording a little so the instructions are: 

If this Dart package is published to Github, add the following dependency to your pubspec.yaml
```Dart
dependencies:
  api_client:
    git: https://github.com/username/api_client.git
```

**Comment by nickmeinhold** [comment]
Also the Requirements in the generated README are 
```
Dart 1.20.0 or later OR Flutter 0.0.20 or later
```
and I believe should be 
```
Dart 2.0 or later
```

I might rename this issue to something more general like "generated README needs updating" and go through more thoroughly and see if there is anything else I think should be changed. Is it preferred to group together small changes like this?

**Comment by wing328** [comment]
Agreed if `supportDart2` is set to true, the requirement should be Dart 2.0 or later.
