### ISSUE TITLE
Qt5 client code fail to be compiled for https://github.com/jdegre/5GC_APIs/raw/master/TS29502_Nsmf_PDUSession.yaml 

### ISSUE THREAD

**Issue by dongfangxunlei** [OpenAPITools/openapi-generator#3651]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

There are quite some errors in the generated Qt5 client code and fail to compile

##### openapi-generator version

4.1.0 and 5.0.x

##### Command line used for generation

java -jar /home/pqy/Downloads/openapi-generator-cli-5.0.0-20190811.165202-11.jar  generate -g c -i https://github.com/jdegre/5GC_APIs/raw/master/TS29502_Nsmf_PDUSession.yaml -o TS29502_Nsmf_PDUSession

**Comment by wing328** [comment]
> There are quite some errors in the generated Qt5 client code and fail to compile

It would help to show the error message here or via https://gist.github.com

**Comment by etherealjoy** [comment]
Looking at this issue now, I see the client is C but the expectation is Qt5.
@dongfangxunlei 
Could you please comment which one is the needed one?

**Comment by dongfangxunlei** [comment]
@etherealjoy  It is Qt5. Sorry for  the mistake

**Comment by dongfangxunlei** [comment]
The main problem is in OAIInline_object.h
OAIHttpRequestInputFileElement* binary_data_n1_sm_message;
OAIHttpRequestInputFileElement* binary_data_n2_sm_information;

**Comment by etherealjoy** [comment]
I see, thanks for the clarification, Binary input is not supported yet in the Qt5 client.
See also this one
#3421

But I think we can think of it because it is requested often.

**Comment by etherealjoy** [comment]
I think this mapping is wrong it should be QByteArray, it is not an input file.
We will have to update this mapping then.

**Comment by etherealjoy** [comment]
Added support for binary data in #3853

**Comment by etherealjoy** [comment]
@dongfangxunlei 
Could you please check current master if your issue is solved.

**Comment by dongfangxunlei** [comment]
@etherealjoy Should I build the source of generator myself?

**Comment by wing328** [comment]
You can use the snapshot jar as mentioned in the readme.

在 2019年9月18日週三 上午8:33，dongfangxunlei <notifications@github.com> 寫道：

**Comment by dongfangxunlei** [comment]
Yeah. It works now. Thanks for your great work!
One more suggestion: Qt5 client put all source files in the same folder, it is better to seperate they into different folder by Models/Apis/Others

**Comment by etherealjoy** [comment]
@dongfangxunlei 
Many thanks for the feedback.
We will consider this improvement in the future for the source files.
