### ISSUE TITLE
[BUG] [typescript-inversify] rxjs imports are wrong for newest version

### ISSUE THREAD

**Issue by deluksic** [OpenAPITools/openapi-generator#3705]
Newest rxjs version has changed imports:

```js
import { Observable } from "rxjs/Observable";
```
to
```js
import { Observable } from "rxjs";
```

and 

```js
return Observable.fromPromise(promise);
```

to 

```js
import { from } from 'rxjs';
return from(promise);
```

**Comment by macjohnny** [comment]
@deluksic would you like to implement an option similar to the typescript-angular client?
see

https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L89
https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L180
https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L16-L21

cc @gualtierim

**Comment by siada** [comment]
This is already handled in typescript-inversify if you specify `UseRxJS6: true` in a config.yml, and add `-c config.yaml` to your `openapi-generator generate` call it will generate correctly

**Comment by macjohnny** [comment]
@siada great, so we can close this.

**Comment by deluksic** [comment]
Great thank you for explaining! :+1:
