### ISSUE TITLE
[BUG] [typescript-fetch] Configuration class fails on strict mode

### ISSUE THREAD

**Issue by deluksic** [OpenAPITools/openapi-generator#3708]
`Configuration` class from `runtime.ts` doesn't transpile if `tsconfig.ts` set to `strict: true`.

Specifically, `| undefined` should be added to these methods:
```js
...
    get headers():  HTTPHeaders | undefined {
        return this.configuration.headers;
    }

    get credentials(): RequestCredentials | undefined {
        return this.configuration.credentials;
    }
...
```

**Comment by macjohnny** [comment]
this has been fixed with https://github.com/OpenAPITools/openapi-generator/pull/3605
