### ISSUE TITLE
[BUG] Values of instantiationTypes not considered

### ISSUE THREAD

**Issue by Marvin1912** [OpenAPITools/openapi-generator#3718]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
```
openApiGenerate {
    generatorName = 'spring'
    outputDir = "${buildDir}/..."
    inputSpec = "${projectDir}/..."
    apiPackage = "com..."
    invokerPackage = "com..."
    modelPackage = "com..."
    instantiationTypes = [array: "java.util.HashSet"]    
    configOptions = [
            dateLibrary  : "java8",
            interfaceOnly: "true"
    ]
}
```
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
4.0.1 (`org.openapitools:openapi-generator-gradle-plugin:4.0.1`)
- [ ] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
Given `instantiationTypes = [array: "java.util.HashSet"]`
Actual: ArrayLists are generated
Expected: Generated HashSets

##### Description

Wanted to generate HashSets instead of ArrayLists for arrays and set value for `instantiationTypes ` to `[array: "java.util.HashSet"]`. According to answer of Slack:

> Jeremie Bresson  vor 16 Stunden
@Marvin please create an issue for that, it seems to me that the default value is hard-coded and not using this instantiationTypes parameter.
See:
https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L718-L727

##### openapi-generator version

4.0.1, not a regression

##### OpenAPI declaration file content or url

```
openApiGenerate {
    generatorName = 'spring'
    outputDir = "${buildDir}/..."
    inputSpec = "${projectDir}/..."
    apiPackage = "com..."
    invokerPackage = "com..."
    modelPackage = "com..."
    instantiationTypes = [array: "java.util.HashSet"]    
    configOptions = [
            dateLibrary  : "java8",
            interfaceOnly: "true"
    ]
}
```

##### Command line used for generation

gradle clean openApiGenerate

##### Steps to reproduce

Just set instantiationTypes according to example above.

**Comment by jmini** [comment]
I am not sure if the `instantiationTypes` were ever used for default value, but this would be a great addition (more a feature than a bug).

---
I think it is safe to replace:

https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L722-L727

With:
`final String pattern = "new " + instantiationTypes().get("array") + "<%s>()";`

---
And:

https://github.com/OpenAPITools/openapi-generator/blob/4575b3074ab6f2628837ca84ed5c287f2afaceee/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L746-L751

With:
`final String pattern = "new " + instantiationTypes().get("map") + "<%s>()";`

---
Optional: A unit test for this could also be added in `AbstractJavaCodegenTest`

---
@Marvin1912: Can you file a pull request for that?

**Comment by Marvin1912** [comment]
Hi @jmini,
seems like I'm not able to push to created feature branch from my current workstation. I'll try it once more when I've switched places.

**Comment by ala85** [comment]
Hi, any update on the above? instantiationTypes field is not really helpful at current state for collections other than plain ArrayList.

**Comment by Marvin1912** [comment]
Hi @ala85 
unfortunately I'm not able to push any changes on a feature branch. Unless someone grant me the rights, there's nothing I can do.

**Comment by AlexanderUldall** [comment]
Hello @wing328 is this something you or another core contributor could assist with?

**Comment by wing328** [comment]
@Marvin1912 please have a look at https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements on how to submit a PR with your enhancement.

**Comment by Marvin1912** [comment]
PR created.

**Comment by rgavriel** [comment]
Can you please share a link to the PR.
Was it merge? if so, from which version is it available?

**Comment by Marvin1912** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/4982

**Comment by tiffmaelite** [comment]
@Marvin1912 https://github.com/OpenAPITools/openapi-generator/pull/4982 was merged. This issue can be closed.

**Comment by Marvin1912** [comment]
@tiffmaelite Yes, can be closed.
