### ISSUE TITLE
[REQ][typescript-inversify] Add option to specify namespaces

### ISSUE THREAD

**Issue by siada** [OpenAPITools/openapi-generator#3721]
### Is your feature request related to a problem? Please describe.

I've used the openapi-generator to produce two separate typescript-inversify client's on a single project, however I can't find a way to specify different instances of the IAPIConfiguration per-project.

## Describe the solution you'd like

I'm suggesting the ability to add namespaces in the config/parameters for typescript-inversify so I can create two distinctly different types

## Describe alternatives you've considered

Alternatively the ability to add prefixes or even completely rename the parameters used for the `@inject("")` decorators

**Comment by macjohnny** [comment]
@siada feel free to file a PR.
cc @gualtierim

**Comment by macjohnny** [comment]
@siada you could also write a script that replaces the string `@inject("IApiHttpClient")` in the generated output with `@inject("OtherIApiHttpClient")`

**Comment by gualtierim** [comment]
We can use tags to group the services. In the apiConfiguration we can introduce a dictionary to override the basePath for every tag if there is a entry for the tag.

**Comment by gualtierim** [comment]
@macjohnny Siada maybe wants a prefix for every service registered in the container. So during binding every services is registered with: container.bind(“${prefix}${serviceName}”).

**Comment by siada** [comment]
@macjohnny When you say 'write a script' is this a feature of openapi-generator, ie: there's a post-execute hook, or do you just mean a shell script that 'just does it' as an extra step? I'm looking to make it feel as seamless as possible so if there's a hook then great, but having to manually do it isn't ideal

@gualtierim perhaps not every service though, the HttpClient for example will (to the best of my knowledge) be identical for each generated client, it's the service that has it's own IAPIConfiguration that needs to be unique per-api. So some deps _could_ be re-used.

But yes, a prefix would I guess half solve the problem, aside from having multiple of the same HttpClient

**Comment by gualtierim** [comment]
@siada When you want to inject a different `IApiConfiguration` for service maybe you want only override the basePath. To solve this problem we can use tags and the interface of ApiConfiguration should be changed in:
`
    apiKeys?: {[ key: string ]: string};
    username?: string;
    password?: string;
    accessToken?: string | (() => string);
    basePath?: string;
    withCredentials?: boolean;
    tagPath?: {[ key: string ]: string}; 
`
Every services will be override the basePath if there is a tagPath for its.

If you want to inject a different ApiConfiguration (the case described above is not soddisfated) for every service you can use:
> whenInjectedInto(parent: (Function|string)): interfaces.BindingOnSyntax<T>;

Anyway a custom prefix for every binding is useful for a lot of use cases. I will introduce it in the config.yml.

**Comment by siada** [comment]
I didn't realise `whenInjectedInto` was a thing - that will solve my issue completely so thanks for that.

Do you want me to close this issue? Or leave it open while you introduce the prefixer code

**Comment by macjohnny** [comment]
if the issue can be resolved with `whenInjectedInto`, I think it should be closed. @gualtierim what do you think?

**Comment by gualtierim** [comment]
Yes, I will create a PR adding the prefixer

**Comment by bodograumann** [comment]
@gualtierim Are you still intending to implement some kind of discriminator?
We are using `@named("{{classname}}")` for that. I could include it in a PR.
