### ISSUE TITLE
[BUG][C#] Model properties are generated as non-nullable after 4.1.0 release

### ISSUE THREAD

**Issue by 414004738** [OpenAPITools/openapi-generator#3725]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

In version 4.0.3, when using an OpenAPI 2.0 input, model properties were generated as nullable. For example, see that the date-time property in the FormatTest class was generated as a DateTime? type in 4.0.3:
https://github.com/OpenAPITools/openapi-generator/blob/v4.0.3/samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/FormatTest.cs#L172

But in 4.1.0, the same property is generated as a non-nullable DateTime type:
https://github.com/OpenAPITools/openapi-generator/blob/v4.1.0/samples/client/petstore/csharp/OpenAPIClient/src/Org.OpenAPITools/Model/FormatTest.cs#L172

This is a problem because if a service returns null for these properties in a response, the JSON deserialization fails.

Is there a way to generate nullable properties using an OpenAPI 2.0 input?

##### openapi-generator version

4.1.0

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/v4.1.0/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L1301

##### Command line used for generation

See https://github.com/OpenAPITools/openapi-generator/blob/v4.1.0/bin/csharp-petstore-netcore-project.sh#L30

##### Steps to reproduce

Look at the generated samples in Github for version 4.0.3 and 4.1.0 and compare the types of the properties in the generated models.

##### Related issues/PRs

I believe this may have been introduced by these pull requests:
https://github.com/OpenAPITools/openapi-generator/pull/3530
https://github.com/OpenAPITools/openapi-generator/pull/3537

##### Suggest a fix

I think the changes made in the above pull requests should only affect OpenAPI 3.0 generation.

**Comment by 414004738** [comment]
Note that this seems to be an issue for both the csharp and csharp-netcore generators

**Comment by wing328** [comment]
> Is there a way to generate nullable properties using an OpenAPI 2.0 input?

@414004738 please try `x-nullable: true` in OAS 2.0

**Comment by 414004738** [comment]
Hi @wing328. Thanks for the response.

Manually adding `x-nullable: true` did seem to work. However, we are using swashbuckle to generate the OAS 2.0 JSON files for our C# .net core services and springfox to do the same for our spring boot java services, which don't seem to include the `x-nullable: true` property in the generated JSON. Do we have to customize the output of these libraries somehow to continue using the latest version of openapi-generator?

**Comment by wing328** [comment]
PM me via [Slack](https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM) when you've time.

**Comment by kevinoid** [comment]
Shouldn't the property also be `Nullable<T>` if it is not required?  For example:

```yaml
DateRange:
  type: object
  properties:
    start:
      type: string
      format: date-time
    end:
      type: string
      format: date-time
  required:
  - start
```

If the generated `End` property is `DateTime` instead of `DateTime?` and an open-ended range is represented by omitting the `end` property (rather than sending/receiving `null`), how would the client represent that?

**Comment by kevinoid** [comment]
For reference, [Autorest](https://github.com/Azure/autorest) uses `Nullable<T>` for properties which are either not `required` or `x-nullable: true`, whereas openapi-generator appears to only consider `x-nullable`.

**Comment by rizwansaeed** [comment]
Is the change in behaviour a feature or bug? We're planning to move to the `csharp-netcore` implementation but this is currently blocking us. Will adding `x-nullable: true` be required going forward in order to get the behaviour from 4.0.3?

Thanks

**Comment by wing328** [comment]
@rizwansaeed `nullable` property will determine the behavior moving forward.

The previous implementation was based on OAS v2, which does not support nullable (later it's supported via x-nullable)

**Comment by kevinoid** [comment]
@wing328 Are you saying [`required`](https://tools.ietf.org/html/draft-wright-json-schema-validation-00#section-5.15) should have no effect in OAS3?

**Comment by wing328** [comment]
@kevinoid no, I didn't say that.

Please open a new issue with minimal spec to reproduce the issue as this issue refers to the change in the type: nullable by default to nullable depending on the `nullable` attribute (or x-nullable in OAS2)
