### ISSUE TITLE
[BUG] Https protocol schema is not handled correctly in java 11 native code

### ISSUE THREAD

**Issue by thecrazzymouse** [OpenAPITools/openapi-generator#3729]
##### Description

The schema in the ApiClient is hard wired to http and there is no way to change this like the other parameters like host.

##### openapi-generator version

4.1.0

##### Suggest a fix

Add a setter method for schema:

`
public ApiClient setScheme(String scheme){
    this.scheme = scheme;
    return this;
}
`

**Comment by macjohnny** [comment]
@thecrazzymouse would you like to file a PR for this?

**Comment by thecrazzymouse** [comment]
I have created the PR

**Comment by bbdouglas** [comment]
Hi @thecrazzymouse, thanks for bringing this up and creating the PR.

I believe that the scheme is taken from the spec, for example the [server url](https://swagger.io/specification/#serverObject) in OpenAPI v3.0 or the [schemes](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#schema) in OpenAPI v2.0. The scheme is calculated by parsing that URL as seen in the code below. So, if you have access to the spec, the simplest thing is to change it there.

https://github.com/OpenAPITools/openapi-generator/blob/14a39349d5658646c39d8388a69d9fdd83eb88f3/modules/openapi-generator/src/main/resources/Java/libraries/native/ApiClient.mustache#L157-L158

I can imagine one scenario where changing the scheme would be useful, and that is when the the spec lists multiple URL's/schemes. There is a known limitation of openapi-generator, where it only looks at the first of multiple urls/schemes, and ignores the rest. To get around this limitation, you would need to manually override the scheme as you suggest.

Is this the situation that you are in? Are you connecting to a server with multiple urls/schemes?

**Comment by macjohnny** [comment]
the spec could also contain a default url, like `http://localhost`, while it might be useful to define different urls for different environments, at runtime. I think this PR aims at this scenario

**Comment by bbdouglas** [comment]
> default url

That's definitely reasonable. The PR looks good to me, with the one comment I left that I think it would follow the existing pattern better if there were only a setter and no getter.
