### ISSUE TITLE
[BUG][CSHARP-NETCORE] Spelling error in Multimap

### ISSUE THREAD

**Issue by jaboc83** [OpenAPITools/openapi-generator#3745]
##### Description

There is a simple spelling error in one of the comments. 'Dictioary' should be 'Dictionary'

##### openapi-generator version

4.1.0

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/Multimap.mustache

Lines 280 and 302

##### Command line used for generation

csharp-netcore

##### Steps to reproduce

It's right in the source code on the lines listed above.

##### Suggest a fix

The PR process was pretty complicated for a minor spelling error. I'll have to leave it as an issue for someone else unless I get some time later to go through the whole PR checklist.

**Comment by wing328** [comment]
@jaboc83 thanks for reporting the typo. Please edit the file directly to submit a PR when you've time. We will then help you to complete the checklist.
