### ISSUE TITLE
[REQ] Support git repositories other than github.com

### ISSUE THREAD

**Issue by qmuntal** [OpenAPITools/openapi-generator#3755]
I'm hosting an auto generated go client in an private instance of github enterprise and the generated `mod.go` file points to `github.com` instead of my own host. 

I would like to be able to configure the host of my git repository using a cli parameter, for example `--git-host`, in the same way as it is done for `--git-user-id` and `--git-repo-id`.

Without this parameter, the only alternatives I have are:
- Manually update the auto generated code, which creates a maintenance problem when regenerating the code.
- Create an custom extension with the hard-coded host, which seem to be an overkill to just modify an url

**Comment by wing328** [comment]
That sounds reasonable. Would you have time to contribute the enhancement?

**Comment by qmuntal** [comment]
Yes I do. 
@wing328 do you know if this parameter could be used in more places other than `git_push.sh` and `go.mod`? My initial focus will be this two files.

**Comment by wing328** [comment]
We can start with these 2 files first.

Later we can roll it out to other files like PHP composer config file, Ruby client's README, etc
