### ISSUE TITLE
[REQ] [Kotlin][client] Allow use of Double instead of BigDecimal for number type

### ISSUE THREAD

**Issue by prisoneroftech** [OpenAPITools/openapi-generator#3773]
### Problem

In the context of Kotlin multiplatform, BigDecimal is not portable.  
There are efforts to create a kotlin multiplatform library for BigDecimals (e.g., https://discuss.kotlinlang.org/t/multiplatform-bigdecimal-implementation/5631/6). However, even if such library was available, I think it would still be overkill for those situations where a "Double" should suffice.

## Proposal
New Kotlin client generation option: "numberLibrary" with 2 options available: "BigDecimal" or "Double" (follows the dateLibrary pattern)
This could be extended to include a Kotlin native library in the future.
For existing list see https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/kotlin.md

## Additional Kotlin generation improvements
As part of this I would also like to propose we remove`kotlin.`, `kotlin.collection.` package names for Kotlin's basic types. The package names prefixing basic types result in "Redundant qualifier name..." warnings in Android Studio and IntelliJ IDEs at least.

Let me know what you think. I'd be happy to code it.

FYI 
@jimschubert
@dr4ke616
@karismann
@Zomzog

**Comment by wing328** [comment]
What about using --type-mapping instead ?

**Comment by prisoneroftech** [comment]
@wing328 - I think you are right. This feature does not add a lot of value since you can do what I want with --type-mapping. The only thing that is a bit annoying because of the "redundant" warning is that I have to set the --type-mapping to "kotlin.Double" not just "Double"

I guess the feature request now boils down to just removing "kotlin." and "kotlin.collection." package name from basic types.

**Comment by prisoneroftech** [comment]
Ok. I think I found a way to do what I want without making any code changes to the generator.
The answer is --type-mappings and --language-specific-primitives

--type-mappings number=Double,string=String,array=List,boolean=Bool,integer=Int --language-specific-primitives=Double,String,List,Int,Map,Int,Bool

**Comment by jakoss** [comment]
On version 5.0.0 the problem with redundant qualifier returned for lists. All primitives besides the List are just fine. My setup:
```
task generateKotlinModels(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "kotlin"
    inputSpec = "$buildDir/swagger.json"
    outputDir = "$projectDir/models".toString()
    apiPackage = "com.ku.mobile.apimodels"
    packageName = "com.ku.mobile.apimodels"
    modelPackage = "com.ku.mobile.apimodels"
    configOptions = [
            dateLibrary       : "java8",
            enumPropertyNaming: 'UPPERCASE',
    ]
    additionalProperties = [
            moshiCodeGen: "true"
    ]
    globalProperties = [
            modelDocs: "false",
            apis     : "false",
            models   : ""
    ]
    typeMappings = [
            double : "Double",
            number : "Double",
            string : "String",
            array  : "List",
            boolean: "Boolean",
            integer: "Int",
            long   : "Long",
            map    : "Map"
    ]
    languageSpecificPrimitives = ["String", "Double", "Array", "List", "Int", "Boolean", "Long", "Map"]
    generateApiTests = false
    generateApiDocumentation = false
    generateModelDocumentation = false
    generateModelTests = false
    skipValidateSpec = true
}
```
