### ISSUE TITLE
inline model title

### ISSUE THREAD

**Issue by rienafairefr** [OpenAPITools/openapi-generator#378]
Hey guys,

This might be linked and direct consequence of #8, if that's the case you can close this one.

I thought that after that commit https://github.com/OpenAPITools/openapi-generator/commit/ea15b859b7460789138b25f4f42f97346a900375, we could define inline models with a title property, then have that title property be used for the model name in the codegen, it's apparently not the case anymore, because even with title property on the schema object I still have models appearing with the name inline_response_*** 
It's solvable by moving them to /components/schemas or elsewhere, of course. Looks like that functionality regressed with the openapi 3.0 support. 

Using openapi-generator v 3.0.2 and a 3.0.0 [spec](http://api.iot-lab.info/swagger.yaml), generating a basic python client (`generate -g python -i /local/swagger.yaml`)

**Comment by aljacob** [comment]
same issue in 3.3.4 using a java generator.

**Comment by wing328** [comment]
@aljacob can you try the latest master? There are some enhancement to the inline model resolver and hopefully those issues have been addressed.

**Comment by aljacob** [comment]
@wing328 just tried to run on 4.0.0-SNAPSHOT, but then I cannot generate because I am hitting issue no.  [https://github.com/OpenAPITools/openapi-generator/issues/1714 ](1714)

**Comment by wing328** [comment]
Did you try using `--skip-validate-spec` to skip the validation error (false alarm)?

**Comment by aljacob** [comment]
@wing328 when adding a title I can confirm that it works with 4.0.0 now. An object without title just is named InlineObjectXXX but if a title is set it get the correct name now. Still the validation issue is annoying as I can't be sure that the rest of the api is specified correctly this way.

**Comment by wing328** [comment]
@aljacob thanks for the confirmation. Likely we'll set the default of 
`--skip-validate-spec` to true and show the errors as FYI only.

@rienafairefr please give the latest master another try and let us know if you still encounter te issue
