### ISSUE TITLE
[BUG] [typescript-fetch] TypeScript 3.6 breaks generated code

### ISSUE THREAD

**Issue by someone1** [OpenAPITools/openapi-generator#3798]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
The 3.6 release of typescript has some [breaking changes](https://devblogs.microsoft.com/typescript/announcing-typescript-3-6/#breaking-changes) that break the generated code. Now the generated code ships with TypeScript 2.4, but some (or at least I) like to update this to the latest for any free optimizations that may come with it.

##### openapi-generator version

4.1.0

##### Suggest a fix

`GlobalFetch` was removed, so use it's namespaced version under `WindowOrWorkerGlobalScope`

**Comment by someone1** [comment]
cc @macjohnny

**Comment by macjohnny** [comment]
@someone1 are you willing to fix this?

**Comment by someone1** [comment]
Working on it now - should I bump the typescript version to 3.6 the packages.json ships with?

**Comment by someone1** [comment]
FYI - I think 3.0 would be the minimum version required for this change.
