### ISSUE TITLE
[BUG] [Kotlin] Class fields are generated with immutable 'val' instead of 'var'

### ISSUE THREAD

**Issue by vitaliysapounov** [OpenAPITools/openapi-generator#3803]
### Description
Kotlin generator generates Kotlin classes with 'val' fields, not 'var'. Thus, the fields are constant and cannot be changed by a programmer -- you cannot even an instance programmatically.

##### openapi-generator version

Generator Version 4.1.1
Spec Version 3.0.2

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.2"

info:
  version: "1.0.0"
  title: Testing Kotlin generation

# We only care about schemas, but this prevents codegen error: "attribute paths is missing"
paths:
  /dummy:
    get:
      responses:
        '200':
          description: OK

components:
  schemas:

    TestRec:
      properties:
        id:
          type: integer
          description: >
            Unique id.
          minLength: 1
          example: 1
        label:
          type: string
          description: >
            User-friendly name.
          example: "North"
        userId:
          type: string
          description: >
            User Id.
          minLength: 38
          example: "Test1234"
```

##### Command line used for generation

`openapi-generator generate -i my-models.yml -g kotlin`

NOTE: we actually use the Gradle plugin for code generation (`org.openapi.generator` version `4.1.1`), but the above command-line tool gives the same result. However, we would like the fix to propagate to the Gradle plugin as well, so we can use in our build.

##### Steps to reproduce

Run the command above and inspect the generated `TestRec.kt`. It will look like below:

```
package org.openapitools.client.models


import com.squareup.moshi.Json

data class TestRec (
    /* Unique id.  */
    @Json(name = "id")
    val id: kotlin.Int? = null,
    /* User-friendly name.  */
    @Json(name = "label")
    val label: kotlin.String? = null,
    /* User Id.  */
    @Json(name = "userId")
    val userId: kotlin.String? = null
) {

}
```

Note `val` is used, not `var`.

##### Related issues/PRs

Not found.

##### Suggest a fix

Generate Kotlin fields with 'var' instead of 'val'.

**Comment by Zomzog** [comment]
This creates an immutable object, you can create instance of it `val a = TestRec(1, "label", "userId")`

Maybe we can add an option for generating mutable models. But I'm not sure if it's a good idea.

**Comment by vitaliysapounov** [comment]
Thanks, but what's the purpose of generating immutable models? Mutation is necessary in certain cases -- the simplest is getting an object from remote API, changing certain fields, and posting it back to update.

There is no reason to make models immutable, as I can see it. It will only complicate programmer's life. Also, this is not consistent with other languages (e.g. Java) where models are essentially mutable (and this is a good thing).

**Comment by clintfoster** [comment]
We have request/response data classes that we generate for interacting with our cloud APIs. In many cases the request classes contain quite a few fields, some of which are optional, and some of which might be built up individually through different logic paths before the request is sent, making a single constructor unwieldy.

**Comment by kiwisincebirth** [comment]
While this is a very old issue. Thought I would comment for anyone else investigating, 

> Thanks, but what's the purpose of generating immutable models? Mutation is necessary in certain cases -- the simplest is getting an object from remote API, changing certain fields, and posting it back to update.

Kotlin supports this scenario out of the box using immutable objects, and the copy() function thus

```
fun processRecord( inputRecord: TestRec ) {
    // this constructs a new immutable object with the modified property
    val mutatedRecord = inputRecord.copy() {
        label = "New Value"
    }
}
```

There is a point of immutability (TLDR), and Kotlin does support the use case, in the required way.

**Comment by tarukhan19** [comment]
Is there any to make variable as var instead of val.

**Comment by Arumugam-R** [comment]
Please update if there is any solution for the above.

**Comment by vishaldhardubey** [comment]
Is there any update on above request

**Comment by urmichm** [comment]
Could we choose a middle ground and generate 'required' fields as 'val' and others as 'var'?
