### ISSUE TITLE
[REQ] Protobuf v3 schemas and gRPC service definitions 

### ISSUE THREAD

**Issue by keithtian** [OpenAPITools/openapi-generator#3806]
## Describe the solution you'd like

Is there any plan to provide a converter to transform OpenAPI specification v3 to Protobuf v3 schemas and gRPC service definitions?

I'd a look at https://github.com/nytimes/openapi2proto but it only supports OpenAPI specification v2.

Thank you

## Describe alternatives you've considered

https://github.com/nytimes/openapi2proto

**Comment by wing328** [comment]
@keithtian Very good suggestion.

There's no plan at the moment and we definitely welcome contribution for that. Would you have time to make the contribution? We can show you some good starting points.

**Comment by keithtian** [comment]
@keithtian Sorry that I'm not familiar with Java/mustache plus I'm busy with a new project so I won't be able to help out :(

**Comment by wing328** [comment]
I've come up with a prototype (beta) generator for gPRC/ProtoBuf over the weekend: https://github.com/OpenAPITools/openapi-generator/pull/3818

Please check it out and let us know what you think.

**Comment by keithtian** [comment]
@wing328 That's awesome. Thanks so much. I'm on vacation for 2 weeks and will review your PR after that.

**Comment by wing328** [comment]
I've merged the PR into master to release a beta generator for gPRC, Protobuf for the time being so that we can start collecting feedback from the developers.

**Comment by keithtian** [comment]
I notice that the new generator is included in the v4.1.2 release. Thanks a lot.

My teammate has taken over the task so I'll let him know and ask him to reply here if he has any question.

**Comment by gattytto** [comment]
should this be closed since the requested feature was implemented? I'd like to add a thread for client and server libs generation from the grpc schemas
