### ISSUE TITLE
Invert model and path in the definition files

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#381]
##### Description

Almot all examples start to describe the path, then the model. I think it is not right and that model should come first.

##### openapi-generator version

HEAD

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

Not that I know

##### Suggest a fix/enhancement

Simply invert order on all example.

**Comment by jmini** [comment]
This is a matter of taste, we are using the order, as specified here:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#fixed-fields

* `paths` is a required section
* `components` is not

Because the spec is Yaml/Json the order does not matter.

**Comment by MartinDelille** [comment]
Ok I close this issue.
