### ISSUE TITLE
[Question][Python] Is posible to change to cammel case naming convention?

### ISSUE THREAD

**Issue by jpascualsana** [OpenAPITools/openapi-generator#3813]
##### Description

Our project is wrote on camelCase convention. Is possible to generate python client following camelCase instead of the pythonic snake_case? 

I looked at mustache templates on:

https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/python

And the instructions under `openapi-generator config-help -g python`. 

Also I looked at [PythonClientCodegen.java](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java) but I didn't find the answer. 

##### openapi-generator version

```
➜ openapi-generator version
4.0.3
```

##### OpenAPI declaration file content or url

https://gitlab.com/snippets/1882068/raw

Note: this YAML is auto generated from a Doxygen documentation for RetroShare project using [this](https://gitlab.com/jpascualsana/retroshare-api-wrapper-generator)

##### Command line used for generation

```
openapi-generator generate -i wrapper_openapi.yml -g python -o ../openapi-python-retroshare-api-wrapper
```

**Comment by wing328** [comment]
Is pythonic snake_case causing issues (e.g. JSON payload serialization/deserialization)?

**Comment by jpascualsana** [comment]
For the moment it don't seems so, but we would like to use only CamelCase on our project, also in python wrappers, breaking with the pythonic rules. 

Is there a way to modify the template to disable snake_case and use CamelCase for variable names an others?

**Comment by rmadisonhaynie** [comment]
We have a similar issue at the moment, a resolution would be great thanks

**Comment by spacether** [comment]
This is partially implemented in python-experimental when instantiating models.
See this [example](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/test/test_drawing.py#L48)
Where we make a model like:
```
inst = petstore_api.Shape(_spec_property_naming=True, shapeType="Triangle", triangleType="IsoscelesTriangle")
```
A solution like this is could be added to endpoints also. To do that we would need to add a dict which goes from python variable names to spec veraible names, and we could decorate the endpoint function with `@convert_js_args_to_python_args` like we do in the model `__init__` method

**Comment by thebhushanp** [comment]
> in Java add a CLI option to a python generator which uses the spec naming for all endpoint variable names and object variable names. This will probably involve editing functions to use this CLI option and change the property names that are use in Java.

@spacether Can you guide me little on where should I look in the code for this above approach ?

**Comment by spacether** [comment]
Sure thing :)
So I think that [this](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PythonClientCodegen.java#L487) is where the parameter names are set in the python client
And here is an example of a PR that adds a CLI parameter in a python generator:
https://github.com/OpenAPITools/openapi-generator/pull/4765

**Comment by spacether** [comment]
@jpascualsana can you try the python-experimental generator?
It uses spec naming for all model properties and endpoint parametersIt was added in: https://github.com/OpenAPITools/openapi-generator/pull/8325

**Comment by spacether** [comment]
Can this issue be closed now that we have a python generator which uses only spec case?

**Comment by spacether** [comment]
Closing this issue because the [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata) generator uses spec (camel case) naming
