### ISSUE TITLE
[REQ] add /* eslint-disable */ to JS/TypeScript files

### ISSUE THREAD

**Issue by AshSuzuki** [OpenAPITools/openapi-generator#3814]
### Is your feature request related to a problem? Please describe.

I'm using open-api-generator with create-react-app / typescript.

I generated dead simple API by below command:
`openapi-generator generate -i openapi.yml -g typescript-axios -o ./src/api-client`

Then, executed `yarn start` command, It shows warning:

```
Compiled with warnings.

./src/api-client/base.ts
  Line 17:  'AxiosPromise' is defined but never used  @typescript-eslint/no-unused-vars

./src/api-client/api.ts
  Line 19:  'COLLECTION_FORMATS' is defined but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```

I feel these generated codes shouldn't be lint-ed.

## Describe the solution you'd like

Just add `/* eslint-disable */` to top of the generated `.js/.ts` files.

## Additional context

Currently, Create React App(CRA) doesn't follow .eslintignore.
https://github.com/facebook/create-react-app/issues/2339

CRA & eslint is one of the most popular tools to develop JS/TS frontend.
I feel this feature is reasonable.

**Comment by bodograumann** [comment]
I don’t think this is necessary or helpful. You are responsible for the linting you are doing, @AshSuzuki. If you feel that the linting done on the generated code is to much, just add your own `.eslintrc.js` in the `src/api-client` directory and disable the respective rules.

**Comment by AshSuzuki** [comment]
I think it's *helpful*, but unnecessary.

@bodograumann, As I mentioned in `Additional context`, CRA doesn't follow `.eslintrc.js`.

**Comment by bodograumann** [comment]
@AshSuzuki You talked about `.eslintignore`, which is something different.

Another solution would be to put the generated api client into a separate npm package. Then it would be included in `node_modules` of your main application and you can setup your own linting for the api. This will also make the api client code more easily reusable.

**Comment by mihai-dinculescu** [comment]
I would really like this to be added as well for the very same reason mentioned by @AshSuzuki .

The files in question already have a `// tslint:disable` as the top. But `tslint` is no longer the preferred tool for linting TypeScript, `eslint` is.

**Comment by AshSuzuki** [comment]
@bodograumann 

Yeah, I know there's several options to prevent from linting.
But I feel linting should be disabled by **default**.

(Sorry about late reply)

@mihai-dinculescu 

Thanks. I didn't realized these files already has `// tslint:disable`.
As current implementation produces it, this request would be reasonable.

**Comment by mikewheaton** [comment]
It looks like #4110 made this change, so now we're just waiting for the next release to include it.

**Comment by macjohnny** [comment]
Fixed in #4110

**Comment by bodograumann** [comment]
You are correct, @tocosastalo: https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments

**Comment by mikewheaton** [comment]
Can I help with this? I'm new to the project but I'm happy to make a PR if someone points me in the right direction. I'm guessing I just change the same `.mustache` files that #4110 did and then run some command to generate all of the rest?

**Comment by macjohnny** [comment]
@mikeewheaton yes, you need to change the mustache files and run „mvn clean package“, then run bin/typescript-axios-petstore-all.sh and
commit the mustache files plus the files changed in /samples.

**Comment by mikewheaton** [comment]
@bodograumann's [comment on 802](https://github.com/OpenAPITools/openapi-generator/issues/802#issuecomment-542044205) makes a good point about how adding `/* eslint-disable */` would prevent linting for everyone, even those who want it.

To me, this is really a problem with Create React App's configuration making it difficult to ignore folders. I'm going to try the solution in [#2339](https://github.com/facebook/create-react-app/issues/2339) again. 🤞

**Comment by rubeonline** [comment]
@macjohnny it is only fixed for typescript-fetch and not for typescript-axios. Why only for fetch?

**Comment by macjohnny** [comment]
> it is only fixed for typescript-fetch and not for typescript-axios. Why only for fetch?

@rubeonline feel free to file a PR, contributions are welcome.

**Comment by jakub-astrahit** [comment]
@macjohnny What do I need to change to add this for typescript-axios as well?
