### ISSUE TITLE
[REQ] [Dart] Add testing of generated client to CI

### ISSUE THREAD

**Issue by nickmeinhold** [OpenAPITools/openapi-generator#3816]
### Is your feature request related to a problem? Please describe.

Currently CI runs the generated tests that are part of the petstore client library, but these are all empty passing tests.

## Describe the solution you'd like

It would be helpful to have a reasonable set of tests that are run by the CI in order to have confidence that any fixes/enhancements to the dart generator haven't broken things.

## Describe alternatives you've considered

It would be great to get input on how to proceed, we could:

- edit the dart generator to include tests in the output client libs (probably limit to tests everyone would want in the lib, eg. no platform specific tests)
- run separate tests (potentially in a staging environment) by test apps that import the client lib
- a combination of the above

## Additional context

- there is a set of tests at `samples/client/petstore/dart2/petstore` that are not currently run in CI
  - several fail when run in my local environment 
  - seems that stubbed server responses would solve most of the problems though
- currently all dart testing is done on Drone, see `CI/.drone.yml`
- EDIT: just found this too, not sure how it fits in yet:
  - https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/dart

**Comment by wing328** [comment]
> https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/test/java/org/openapitools/codegen/dart

That's the unit testing the Dart generators (Java classes)

**Comment by nickmeinhold** [comment]
Thanks @wing328!

So am I right in saying:  
1. the java produces a set of maps for use with the templates 
2. the java uses jmustache to apply the templates to the maps, which produces the client lib 

- currently we have unit testing of step 1 but no testing of step 2

So I'm thinking I might get the tests that are at `samples/client/petstore/dart2/petstore` working and add to CI, what do you think? 

Btw am I using the right language in saying maps?  what do you call the data that jmustache uses with the templates?

**Comment by nickmeinhold** [comment]
I've also been wondering about having a step in the CI that runs the analyzer (after adding a standard `analysis_options.yaml`, I would think using the `pedantic` lints).  

Maybe this needs a separate issue?
