### ISSUE TITLE
[REQ][typescript-fetch] Allow module selection via command line argument for npm package 

### ISSUE THREAD

**Issue by fuzzzerd** [OpenAPITools/openapi-generator#3833]
### Is your feature request related to a problem? Please describe.

The generated typescript package uses `commonjs` which is not suitable for client side applications.

## Describe the solution you'd like

Additional command line arguments to tailor the generated `package.json` file for npm packages.

## Additional context

Discussion here: https://github.com/OpenAPITools/openapi-generator/issues/3694#issuecomment-523180558

**Comment by macjohnny** [comment]
Would you like to implement this?

**Comment by fuzzzerd** [comment]
Updating the templates is within my capability. I don't have the java tooling or expertise to go beyond that.

**Comment by fuzzzerd** [comment]
For what its worth, per some discussions on the slack channel, I ended up doing some tweaks to my main package.json, where I run the generator.

I installed the replace package:

```
npm install replace --save-dev
```
I have a few tasks defined:

```
npx openapi-generator generate -i swagger.json -o c:\temp\oag ... ...
npx replace \"commonjs\" \"esnext\" c:/temp/tsconfig.json
```
Which isn't the best work around, but for anyone else looking for a work around this might be useful.

**Comment by bodograumann** [comment]
@fuzzzerd, could you please explain how exactly you want to use the library?

**Comment by fuzzzerd** [comment]
@bodograumann I'm using the generated library from a vue cli SPA.

**Comment by bodograumann** [comment]
Then I don’t understand what problem you have, because vue-cli uses webpack and can use commonjs libraries just fine.

**Comment by fuzzzerd** [comment]
Perhaps its lack of understanding or configuration on my part; but whatever cocktail configuration I have doesn't allow me to use the generated package when its set to commonjs and it works with esnext. I am not a webpack expert, so perhaps there is something I need to do to mix and match?

The goal here was to have the ability to make it configurable at generate time.
