### ISSUE TITLE
[Slim] General enhancement discussion

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#384]
##### Description

Hey, PHP guys! :handshake: 
I'm going to upgrade PhpSlimCodegen to meet community and my personal requirements.
I'm not familiar with spec 3.0, so all text below related to 2.0 version.

1. Automated UnitTests generation for every model and every endpoint(checks at least response status code and response data types)
2. Mock API server generation (`example` properties from responses will be used as mock data). It should covers autogenerated UnitTests automatically, I think.

Few updates that I would do later:

* Move all generated API Route controllers from `index.php` into separated PHP classes for more modular testing and easy maintain #438
* Add generation of Authentication middleware stubs (Basic #606 and apiKey at least)

##### PHP Technical Committee

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh 

##### Questions to PHP Committee

I will try to create basic template which any developer can modify by edit mustache markdown, but we need to decide how advanced it should be by default:

1. What PHP version should we target? Is it too soon to use type annotation with PHP7 and modern syntax shortcuts? ( `[]` instead of `array()`, `$_GET['user'] ?? 'nobody'` instead of `isset($_GET['user']) ? $_GET['user'] : 'nobody'`)
2. What PHPUnit version should we target?
3. Should we use [Faker](https://packagist.org/packages/fzaninotto/faker) library for mock data or it's too much?
4. I would like to use .ENV config file with [phpdotenv](https://packagist.org/packages/vlucas/phpdotenv) library. I've met a problem vlucas/phpdotenv#266 few times, but I don't see any decent alternatives beside builtin `parse_ini_file` function with external .INI file as a config.

**Comment by ackintosh** [comment]
Thanks for opening this discussion! 🐘 

My thoughts:

1. The enhancements would be expected to work with PHP >=5.5.0, as Slim framework on which our stub server depends supports the version.
On the other hand, updating supported version is good idea as PHP5.5 is EOL. To avoid making users/contributors confused and make our work as simple as possible, I think updating support version should be proceed in another process.

2. The latest PHPUnit which works with the PHP 5.5.0.

3. I think it is too much for current step as stub server should return the value defined at `exmaple`. (It is a good idea implementing the feature that returns random values)

4. I want to understand the necessity of .ENV config file on the enhancement. What configs are you going to manage with .ENV config file?

**Comment by ybelenko** [comment]
@ackintosh 
1. Accordingly to that ref [PHP supported versions](http://php.net/supported-versions.php) 5.6 is minimum version which is not abondoned right now.
2. This ref [PHPUnit supported versions](https://phpunit.de/index.html) says that minimum supported version PHPUnit6 requires PHP7. Maybe we should warn users somehow that PHPUnit5 is not officially supported and need to use it with caution.
3. I've meant cases when spec doesn't contain `example` values. Let's say primitive type `string` without example, in that situation Faker can provide more precise data than `"foobar"` or `"Lorem ipsum dolor"`. But from another point it's just template mustache upgrade, so anybody can add Faker if needed without recompiling project.
4. Usually I keep sensitive configs in .ENV file to keep them separated from code and avoid pushing into SVN. Database credentials, API keys. Different ENV for develop and production.
