### ISSUE TITLE
No docker tag corresponding to 'latest' release

### ISSUE THREAD

**Issue by onionhammer** [OpenAPITools/openapi-generator#3840]
If I go to docker hub, I can see the 'latest' tag has been updated 45 minutes ago, but there is no corresponding version bump, so if a user already has 'latest' tag they would have to forcibly re-fetch the image to get the latest

![image](https://user-images.githubusercontent.com/969938/64361513-505f1080-cfd2-11e9-9469-6942faaff7be.png)

**Comment by wing328** [comment]
The `latest` refers to the latest master (which is updated pretty frequently).

**Comment by onionhammer** [comment]
@wing328 Makes sense.. so if there is a fix you want to use (like the one that lets you use Typescript 3.6), you just have to wait for it to come out with a tag in order to truly use it because the next person to download :latest may get an awful breaking change?

**Comment by wing328** [comment]
What about using SNAPSHOT JAR instead? The SNAPSHOT is published whenever there's a change to master, next minor/major release branches.

Ref: https://github.com/OpenAPITools/openapi-generator#11---compatibility

**Comment by onionhammer** [comment]
@wing328 we're using docker as part of our build system so every developer doesnt have to give their computer cancer (i.e. java)

**Comment by jimschubert** [comment]
Each image now has a `latest-release` version. This will build every two days and point to the last version tag at the time of the job running.

![image](https://user-images.githubusercontent.com/109659/85967083-9c2edc00-b98f-11ea-99fb-c2f1245dc5e2.png)
