### ISSUE TITLE
[JAVA] [SPRING] - Error Compiling When generateSupportingFiles=false and configOptions.java8 = true

### ISSUE THREAD

**Issue by brion-fuller** [OpenAPITools/openapi-generator#386]
##### Description

Currently, seeing an issue running `mvn clean compile` when generateSupportingFiles=false and configOptions.java8 is set to true I will get a ApiUtil not found error.

##### openapi-generator version

3.0.2

##### OpenAPI declaration file content or url

```yaml
<plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>3.0.2</version>
        <executions>
          <execution>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputSpec>${project.basedir}/api-v1.yaml</inputSpec>
              <generatorName>spring</generatorName>
              <generateSupportingFiles>false</generateSupportingFiles>

              <apiPackage>true</apiPackage>
              <modelPackage>true</modelPackage>
              <apiPackage>com.test.hello.api.v1</apiPackage>
              <modelPackage>com.test.hello.api.v1.model</modelPackage>

              <configOptions>
                <interfaceOnly>true</interfaceOnly>
                <java8>true</java8>
                <sourceFolder>src/gen/java</sourceFolder>
                <dateLibrary>java8</dateLibrary>
                <library>spring-boot</library>
              </configOptions>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

##### Command line used for generation

`mvn clean compile`

##### Steps to reproduce

Use example app and OpenApi3 pets example 
Set generateSupportingFiles=false
Set configOptions.java8=true
run `mvn clean compile'
Should see an ApiUtil Not Found Error

**Comment by jmini** [comment]
Do you know what is the idea behind `generateSupportingFiles=false`? 
Is there some documentation to explain what a "generateSupportingFile" is/should be somewhere?

**Comment by brion-fuller** [comment]
I haven't seen a lot of documentation around it for OpenApiTool-Generator but looking in the code.   "generateSupportingFile" creates files around an application (pom.xml, README.md, etc...) depending on the "generatorName" and "libary" chosen.  
Running with Java8 enabled and generateSupportingFile still creates the dependency for ApiUtil.java which is a support file used to return a mocked response (based on swagger example) if you do not override.

**Comment by jimschubert** [comment]
I hope you don't mind, but I'm going to close this in favor of #746. Although that one is a duplicate, it has more details and more discussion than this issue.
