### ISSUE TITLE
[REQ] Upgrade to tokio 0.2 and related async/await features

### ISSUE THREAD

**Issue by dbcfd** [OpenAPITools/openapi-generator#3865]
### Is your feature request related to a problem? Please describe.

The tokio ecosystem is currently migrating to std::future::Future and async/await support. This should land in rust 1.39 (currently stable in nightly)

## Describe the solution you'd like

Upgrade to appropriate versions for tokio and hyper that make use of std::future::Future and async/await

## Describe alternatives you've considered

Tokio 0.2 is not compatible with older hyper versions (pre hyper 0.13). One possibility is to try and use runtime and tide, but that is significantly more of a change.

**Comment by dbcfd** [comment]
Not seeing how to add label `client:rust` or `server:rust`

**Comment by richardwhiuk** [comment]
For Rust Server, my plan is to upgrade to tokio 0.2 and hyper 0.13 when Rust 1.39 stabilises in November, which adds non-nightly support for async/await.

**Comment by kanekv** [comment]
@richardwhiuk 1.39 is released! What is your plan with upgrade? Do you need help?

**Comment by dbcfd** [comment]
@kanekv See #4210 The client was was fairly far along, but if someone wants to revisit it again with latest hyper/reqwest, that would be helpful. Focusing on server right now. Make sure to use github master for hyper, since there are significant changes from the released alpha version.

**Comment by richardwhiuk** [comment]
@kanekv There's an MR open at https://github.com/OpenAPITools/openapi-generator/pull/4210#issuecomment-553113934

Ideally, we'd like tokio 0.2 and hyper 0.13 to stabilise.

In the short term, you can use `Compat::new()` and `.compat()` (from futures 0.3 with the compat feature) in the business logic to allow use of async/await.
