### ISSUE TITLE
[BUG] Java Open-API-Generator Version > 4.0.0.0 - Broken Import-Mappings

### ISSUE THREAD

**Issue by flaxoiu** [OpenAPITools/openapi-generator#3868]
Since Version 4.0.0 of openapi-generator-maven-plugin for Java, the import-mappings not working anymore.

I tried the following with the Maven "openapi-generator-maven-plugin" plugin with version 4.0.0 until 4.1.1

![image](https://user-images.githubusercontent.com/36970409/64594955-4b72d600-d3b1-11e9-8774-dc87c0a6fea4.png)

![image](https://user-images.githubusercontent.com/36970409/64594990-5c234c00-d3b1-11e9-8615-b29372cac8f0.png)

![image](https://user-images.githubusercontent.com/36970409/64595016-647b8700-d3b1-11e9-8982-0160456e302d.png)

But the result was always the same that the  enum class was not used in generated class

![image](https://user-images.githubusercontent.com/36970409/64595064-7e1cce80-d3b1-11e9-8c29-4204d873b25c.png)

Best regards

**Comment by flaxoiu** [comment]
With version 3.3.4 it works but not with newer version

**Comment by macjohnny** [comment]
@flaxoiu would you like to help us and fix it?

**Comment by flaxoiu** [comment]
Import-Mappings is now direct part of configuration node and not inside configOptions node anymore
