### ISSUE TITLE
[BUG] Cpprestsdk - ModelBase.cpp fails to compile on Kubuntu 14

### ISSUE THREAD

**Issue by TomerJLevy** [OpenAPITools/openapi-generator#3877]
Hi,

The sample of cpp-restsdk/client/ModelBase.cpp fails to compile on Linux.
The same Cpprestsdk version compiled fine using v4.0.2 generator.

**Because of line 299:**
![image](https://user-images.githubusercontent.com/22237259/64709179-80b91a00-d4be-11e9-9422-0d1565bd0103.png)

"No matching function for call to 'utility::datetime::from_string(const wchar_t....).."
"Candindate is: utility::datetime::from_string(const string_t....).."

In which 'string_t' is defined in 'cpprestsdk/Release/include/cpprest/details/basic_types.h' as std::wstring for Windows or std::string for POSIX:
link here: https://github.com/microsoft/cpprestsdk/blob/master/Release/include/cpprest/details/basic_types.h#L52

![image](https://user-images.githubusercontent.com/22237259/64709490-0b017e00-d4bf-11e9-8f10-745680db1e63.png)

For me, removing the 'U' before the "NULL" does the trick but it's not a bug fix.

**Comment by TomerJLevy** [comment]
The bug was created in the last pull request:
https://github.com/OpenAPITools/openapi-generator/pull/3572/files

**Comment by TomerJLevy** [comment]
Fix - Commit 2c95d10

**Comment by etherealjoy** [comment]
solved in #3892
