### ISSUE TITLE
[C++][cpp-restsdk][BUG] Templating variable x-codegen-response-ishttpcontent not being set correctly

### ISSUE THREAD

**Issue by dan-drl** [OpenAPITools/openapi-generator#3886]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When it code gens runs on this [spec](https://gist.github.com/dan-drl/11e55dfc8602cb9a45b1f64a50f71ba7) the result is does not compile because HttpContent has no fromJson method. 

```
    .then([=](utility::string_t localVarResponse)
    {

        // 

        std::shared_ptr<HttpContent> localVarResult(nullptr);

        if(localVarResponseHttpContentType == utility::conversions::to_string_t("application/json"))
        {
            web::json::value localVarJson = web::json::value::parse(localVarResponse);

            localVarResult->fromJson(localVarJson);
        }
        // else if(localVarResponseHttpContentType == utility::conversions::to_string_t("multipart/form-data"))
        // {
        // TODO multipart response parsing
        // }
        else
        {
            throw ApiException(500
                , utility::conversions::to_string_t("error calling getAccountingDocumentFile: unsupported response type"));
        }

        return localVarResult;
        
    });
```

##### openapi-generator version

Fails in 4.1.3-SNAPSHOT and also validated it fails in 4.1.0.

##### OpenAPI declaration file content or url

https://gist.github.com/dan-drl/11e55dfc8602cb9a45b1f64a50f71ba7

##### Command line used for generation

java -jar openapi-generator-cli.jar generate -i openapi.json -g cpp-restsdk -o src\Test --model-package Test

##### Steps to reproduce

Download gist, and run command above. 

##### Related issues/PRs

I didn't notice any, however, I wasn't quite sure what to search for. I wouldn't be suprised if there are other issues caused by x-codegen-response-ishttpcontent not being set correctly.

##### Suggest a fix
I'll be issuing a PR shorlty.

**Comment by etherealjoy** [comment]
Fixed with #3888
