### ISSUE TITLE
Springboot codegen : Compilation error in generated controllers if the skipDefaultInterface tag is set to true

### ISSUE THREAD

**Issue by devdream02** [OpenAPITools/openapi-generator#3894]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Springboot codegen : Compilation error in generated controllers if the skipDefaultInterface tag is set to true

##### openapi-generator version

3.0.2
##### OpenAPI declaration file content or url

petstore.yaml
##### Command line used for generation

spring boot
maven plugin config
`                             <configOptions>
                                <java8>true</java8>
                                <library>spring-boot</library>
                                <dateLibrary>java8</dateLibrary>
                                <sourceFolder>src/main/java</sourceFolder>
                                <useBeanValidation>true</useBeanValidation>
                                <configPackage>com.solvezy.sample.config</configPackage>
                                <swaggerDocketConfig>true</swaggerDocketConfig>
                                <skipDefaultInterface>true</skipDefaultInterface>
                            </configOptions>`

##### Steps to reproduce

Set skipdefaultInterface flag as true

###### Error message
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project openapi-spring: Compilation failure: Compilation failure:
[ERROR] /C:/Users/1984/Downloads/Codebase/openapipoc/src/main/java/com/solvezy/sample/api/UserApiController.java:[11,8] com.solvezy.sample.api.UserApiController is not abstract and does not override abstract me
thod updateUser(java.lang.String,@javax.validation.Valid com.solvezy.sample.model.User) in com.solvezy.sample.api.UserApi
[ERROR] /C:/Users/1984/Downloads/Codebase/openapipoc/src/main/java/com/solvezy/sample/api/UserApiController.java:[20,5] method does not override or implement a method from a supertype
[ERROR] /C:/Users/1984/Downloads/Codebase/openapipoc/src/main/java/com/solvezy/sample/api/PetApiController.java:[11,8] com.solvezy.sample.api.PetApiController is not abstract and does not override abstract meth
od uploadFile(java.lang.Long,java.lang.String,@javax.validation.Valid org.springframework.web.multipart.MultipartFile) in com.solvezy.sample.api.PetApi
[ERROR] /C:/Users/1984/Downloads/Codebase/openapipoc/src/main/java/com/solvezy/sample/api/PetApiController.java:[20,5] method does not override or implement a method from a supertype
[ERROR] /C:/Users/1984/Downloads/Codebase/openapipoc/src/main/java/com/solvezy/sample/api/StoreApiController.java:[11,8] com.solvezy.sample.api.StoreApiController is not abstract and does not override abstract
method placeOrder(@javax.validation.Valid com.solvezy.sample.model.Order) in com.solvezy.sample.api.StoreApi
[ERROR] /C:/Users/1984/Downloads/Codebase/openapipoc/src/main/java/com/solvezy/sample/api/StoreApiController.java:[20,5] method does not override or implement a method from a supertype
`

**Comment by macjohnny** [comment]
you need to override the interface methods, as the error message indicates:
```
com.solvezy.sample.api.UserApiController is not abstract and does not override abstract me thod updateUser(java.lang.String,@javax.validation.Valid com.solvezy.sample.model.User) in com.solvezy.sample.api.UserApi
```

**Comment by devdream02** [comment]
Hi @macjohnny , well that's the point, every time i generate/build my project it will override the existing controllers and again i need to override the methods. If the skipDefaultInterface is generating the API interfaces with default methods then the generated controllers should also automatically override the methods without default implementation. Please correct me if i am wrong.

**Comment by macjohnny** [comment]
You can add the controllers to the .openapi-generator-ignore file

**Comment by devdream02** [comment]
But again that's just a workaround, i need my controllers to be generated but with proper methods overridden.

**Comment by macjohnny** [comment]
As far as I know the openapi generator only generates on a per-file basis, it does not modify l existing code

**Comment by devdream02** [comment]
okay well that's partially true, lets say i have written a spec with 3 endpoints, and it has generated the api interface as well as controllers with errors to override the methods. And i have fixed that issue manually for the first time. Now i add one more endpoint in my spec and i want to generate the api interface and controller for it too, but the issue that will come now is the existing file will be overwritten and i will have do all the changes again to fix the overriding methods issue that's quite a rework.

**Comment by macjohnny** [comment]
Here is what I usually do: I generate interfaces, and in a separate location I write the controllers that implement those interfaces. You have to write the controllers anyway as you need to implement the endpoint

**Comment by devdream02** [comment]
Well i am doing the same, just thought that it would be good if the issue is fixed and the generated code will work out of the box without any errors.

Thanks for the suggestion though.

**Comment by devdream02** [comment]
> you need to override the interface methods, as the error message indicates:
> 
> ```
> com.sample.api.UserApiController is not abstract and does not override abstract me thod updateUser(java.lang.String,@javax.validation.Valid com.sample.model.User) in com.sample.api.UserApi
> ```

Hi @macjohnny ,

Could you please delete or edit the comment of yours, as by mistake my company name is there in the package name and my compliance team is chasing me to get it removed.
Thanks!

**Comment by macjohnny** [comment]
@devdream02 done

**Comment by developer79433** [comment]
Please can we re-open this issue? I think there are better fixes available than the ideas mentioned here so far.

- The suggestion to over-ride the interface methods requires editing generated code. This works around the problem, but it's better to keep code generated code and hand-written code separate. If developers have to edit generated code, their changes could get accidentally over-written, losing work. Also, it's not clear what the provenance of a given source code file is. Consequently, it's not clear whether the source should go into 'src/blah' or 'target/generated-source/blah'.
- The suggestion to add the controllers to the .openapi-generator-ignore file also works around the problem, but it has to be done manually by the user. If this is the approach we're going to take, then it would be better to do this automatically. At the moment, the 'skipdefaultInterface' option causes the generated code to not compile. It would be better to not generate the offending code at all. Code that doesn't compile is not very useful.

I believe a better fix for this issue would be to cause the 'skipdefaultInterface' option to add an 'abstract' keyword on the controllers it generates, and (optional, nice-to-have) append 'Base' to each controller class's name, yielding something like "public abstract class BlahBlahControllerBase".

This would have the following benefits:
- All generated code will compile again
- There is no need for the programmer to edit any generated files
- If some kind of boilerplate controller code is necessary, it can be generated into BlahBlahControllerBase.java, instead of the programmer needing to manually write it
- The programmer simply needs to implement a class 'BlahBlahController', which inherits from 'BlahBlahControllerBase' and implements the inherited abstract methods. They have to do this anyway, to implement the actual application functionality, so this means the developer only has to do the minimum amount of work.

**Comment by macjohnny** [comment]
@developer79433 thanks for suggesting a solution. do you want to contribute this feature?

**Comment by developer79433** [comment]
Sure thing! It turns out to be a trivial change - see #7959 .
This is my first contribution, so this probably needs some polishing still. I'm learning the ropes, please go easy on me :-)

**Comment by developer79433** [comment]
Can we re-add the label 'bug', please?

In the scenario described in this issue, the code that OpenAPI Generator generates does not compile.
I'm assuming that OpenAPI Codegen is intended to generate Java code that compiles - there's not much use of Java code that doesn't compile.

So this is unintended unfortunate behaviour, ie a bug.

**Comment by macjohnny** [comment]
@developer79433 I just wanted to point out the `interfaceOnly` that prevents a controller class from being generated. would that help your project?

**Comment by mg-okteo** [comment]
> @developer79433 I just wanted to point out the `interfaceOnly` that prevents a controller class from being generated. would that help your project?

Yes but then it prevents you from generating configs and the likes.

Is there a way to only exclude the `xxxApiController.java` class files from the generation ?

**Comment by mathisgauthey** [comment]
> @developer79433 I just wanted to point out the `interfaceOnly` that prevents a controller class from being generated. would that help your project?

Yes but then it prevents you from generating configs and the likes.

Is there a way to only exclude the xxxApiController.java class files from the generation ?

**Comment by wing328** [comment]
One can use the option `openapiGeneatorIgnoreList` (e.g. --openapi-generator-ignore-list in CLI) to pre-populate `.openapi-generator-ignore`

Ref: https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#ignore-file-format
