### ISSUE TITLE
[BUG][C++][Pistache] Serialized object path parameters missing operator>>

### ISSUE THREAD

**Issue by julesdent** [OpenAPITools/openapi-generator#3916]
#### Bug Report Checklist

- [ x ] Have you provided a full/minimal spec to reproduce the issue?
- [ x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ 4.1.2 ] What's the version of OpenAPI Generator used?
- [ x ] Have you search for related issues/PRs?
- [ x ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

If you declare a path parameter as a serialized object, the generated code for that parameter fails to compile due to a missing operator>>().

##### openapi-generator version
4.1.2 

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
servers:
  - description: SwaggerHub API Auto Mocking
    url: 'https://virtserver.swaggerhub.com/'
info:
  description: Object parameter test
  version: 1.0.2
  title: Object parameter test
paths:
  '/alternates/{id}':
    parameters:
      - name: id
        in: path
        description: Id of the station
        required: true
        explode: true
        schema:
          $ref: '#/components/schemas/AlternateAirportsKey'
    get:
      operationId: get-alternate-airports-by-key
      responses:
        '200':
          description: Get Alternate Airports Successful Operation
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    Icao:
      type: string
      description: Airport Code
      minLength: 1
      maxLength: 4
      example: CYHZ
    Alc:
      description: Airline Code
      type: string
      minLength: 0
      maxLength: 3
      example: NAV
    AircraftEquip:
      description: Aircraft Equipment
      type: string
      minLength: 0
      maxLength: 5
      example: A330
    AircraftSeries:
       description: Aircraft Series
       type: string
       minLength: 1
       maxLength: 5
       example: 200
    AlternateAirportsKey:
      properties:
        DestinationIcao:
          $ref: '#/components/schemas/Icao'
        AircraftEquip:
          $ref: '#/components/schemas/AircraftEquip'
        AircraftSeries:
          $ref: '#/components/schemas/AircraftSeries'
        Alc:
          $ref: '#/components/schemas/Alc'
```

##### Command line used for generation

java -jar ./openapi-generator/openapi-generator-cli-4.1.2.jar generate -g cpp-pistache-server --additional-properties=helpersPackage=Navblue::RestServer,modelPackage=Navblue::RestServer,apiPackage=Navblue::RestServer -i ./ObjectParam.yaml -o generated

##### Steps to reproduce

1. Generate C++ code as shown
2. Generate makefiles 
3. make

Compilation fails with the following error:

In file included from /home/vagrant/ex/ObjectParam/generated/api/DefaultApi.h:23,
                 from /home/vagrant/ex/ObjectParam/generated/api/DefaultApi.cpp:13:
/home/vagrant/ex/ObjectParam/generated/external/include/pistache/router.h: In instantiation of ‘static T Pistache::Rest::details::LexicalCast<T>::cast(const string&) [with T = Navblue::RestServer::AlternateAirportsKey; std::string = std::basic_string<char>]’:
/home/vagrant/ex/ObjectParam/generated/external/include/pistache/router.h:56:45:   required from ‘T Pistache::Rest::TypedParam::as() const [with T = Navblue::RestServer::AlternateAirportsKey]’
/home/vagrant/ex/ObjectParam/generated/api/DefaultApi.cpp:40:61:   required from here
/home/vagrant/ex/ObjectParam/generated/external/include/pistache/router.h:33:19: error: no match for ‘operator>>’ (operand types are ‘std::istringstream’ {aka  std::basic_istringstream<char>’} and ‘Navblue::RestServer::AlternateAirportsKey’)
         if (!(iss >> out))

 [ dozens of lines of error messages trimmed ]

**Comment by etherealjoy** [comment]
This specification seems to be incorrect.

*AlternateAirportsKey*
```yaml
    AlternateAirportsKey:
      properties:
        DestinationIcao:
          $ref: '#/components/schemas/Icao'
        AircraftEquip:
          $ref: '#/components/schemas/AircraftEquip'
        AircraftSeries:
          $ref: '#/components/schemas/AircraftSeries'
        Alc:
          $ref: '#/components/schemas/Alc'
```
*path* param used *AlternateAirportsKey*
```yaml
paths:
  '/alternates/{id}':
    parameters:
      - name: id
        in: path
        description: Id of the station
        required: true
        explode: true
        schema:
          $ref: '#/components/schemas/AlternateAirportsKey'
```

Closing it for now, because an object cannot be used in the path, also it does not makes sense to have encoded buffer in the URL.
Please use multiple string/integer params in the path instead.
