### ISSUE TITLE
[BUG][typescript-fetch] cannot handle with application/x-www-form-urlencoded content

### ISSUE THREAD

**Issue by namaozi** [OpenAPITools/openapi-generator#3920]
##### Description

In OpenAPI Specification [Media Type Object](https://swagger.io/specification/#mediaTypeObject), it says `requestBody->content` 's key is media type (it includes `'application/x-www-form-urlencoded'` ) or media type range. 

like this:
```.yml
paths:
  /memo/{memoId}:
    put:
      summary: update Memo
      tags: 
        - Memos
      operationId: updateMemo
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
              - title 
              properties:
                title:
                ...
```

It seems that the request body made through by the generated code however always make `multipart/form-data` request.

like this (in src/apis/Memos.ts):

```.ts
export class MemosApi extends runtime.BaseAPI {
  async updateMemoRaw(requestParameters: UpdateMemoRequest) {

    // ...
    
    const headerParameters: runtime.HTTPHeaders = {};

    // ...
    
    const formData = new FormData();
    if (requestParameters.title !== undefined) {
        formData.append('title', requestParameters.title as any);
    }

    // and formData is set as body (`body: formData`)
  }
}
```

It would be appreciated like this:

```.ts
    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/x-www-form-urlencoded'; 

    const bodyParams = new URLSearchParams();
    if (requestParameters.title !== undefined) {
        bodyParams.append('title', requestParameters.title as any);
    }

    // and bodyParams is set as body (`body: bodyParams`)

```

##### openapi-generator version

`v4.1.1`

##### Command line used for generation

`openapi-generator generate -i bundle.yml -o ./lib --generator-name typescript-fetch`

**Comment by macjohnny** [comment]
@namaozi would you like to implement a fix for this?

**Comment by namaozi** [comment]
I'm not quite familiar with openapi-generator implementation now, it seems that mustache template has no conditional branch for seeing content type... 

https://github.com/OpenAPITools/openapi-generator/blob/f15f814d9b4d6f43c541cf4f837a912a75e5621d/modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache#L153

**Comment by macjohnny** [comment]
you could look at the typescript-angular client, it is handled correctly there:
https://github.com/OpenAPITools/openapi-generator/blob/b793a95765501caf120aac8538177c89c8df65f1/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L298-L307

**Comment by namaozi** [comment]
Nice! So [typescript-fetch/apis.mustache#L153](https://github.com/OpenAPITools/openapi-generator/blob/f15f814d9b4d6f43c541cf4f837a912a75e5621d/modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache#L153) could handle FormParams like this?
It was just inferred from the typescript-angular client, so I not so sure,,,

```apis.mustache
        {{#hasFormParams}}
        let formParams = new FormData();
        {{^useHttpClient}}
        headerParameters['Content-Type'] = 'application/x-www-form-urlencoded;charset=UTF-8');
        formParams = new URLSearchParams();
        {{/useHttpClient}}
        {{/hasFormParams}}
```

**Comment by macjohnny** [comment]
`useHttpClient` is not part of the `typescript-fetch`.
Moreover, it should be decided similar to `this.canConsumeForm(consumes);`

**Comment by rainmanhhh** [comment]
1. runtime.mustache
`        const body = (context.body instanceof FormData || isBlob(context.body))
	    ? context.body
	    : JSON.stringify(context.body);`
should be replaced to
```
let body: any;
        if (context.body instanceof URLSearchParams) {
            body = context.body.toString()
        } else if (context.body instanceof FormData || isBlob(context.body)) {
            body = context.body
        } else {
            body = JSON.stringify(context.body)
        }
```
2. apis.mustache
```
if (useForm) {
            formParams = new FormData();
        } else {
            headerParameters['Content-Type'] = 'application/x-www-form-urlencoded'; // add this line 
            formParams = new URLSearchParams();
        }
```

**Comment by macjohnny** [comment]
@rainmanhhh does the current solution https://github.com/OpenAPITools/openapi-generator/pull/4103/files fix the problem for you?
If not, please open a new issue
