### ISSUE TITLE
[BUG][DART]: DateTime class conflict issue in Dart? No method found (toUtc, parse)

### ISSUE THREAD

**Issue by Morkos** [OpenAPITools/openapi-generator#3955]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
https://otr-backend-service-us-devo.offtherecord.com/v2/api-docs

- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?

Getting an error, but is unrelated to compilations errors I'm getting from Flutter.

_Error resolving $ref pointer "https://apitools.dev/swagger-parser/online/#/definitions/List". 
Token "List" does not exist._

- [x] What's the version of OpenAPI Generator used?
V4.1.2

- [x] Have you search for related issues/PRs?
Yes.

- [x] What's the actual output vs expected output?
Compilation errors here:
https://gist.github.com/Morkos/65f89d8bbaa5b7ba139522365eb6b107

Expected: Compile success

##### Description

Hi,

I'm getting a slew of compilation errors relating to the DateTime class. The generated dart client libraries that I'm trying to incorporate in my Flutter app is failing to compile with NoMethod errors on DateTime.toUtc and DateTime.parse. 

##### openapi-generator version

V4.1.2

##### OpenAPI declaration file content or url

https://gist.github.com/Morkos/65f89d8bbaa5b7ba139522365eb6b107

##### Command line used for generation

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate \
 -i /tmp/otr.json \
-g dart \
-o /tmp/libs

##### Steps to reproduce
Run the command above. Declare it in pubspec.yml as a dependency and import a *Api type and build.

##### Related issues/PRs
None that I could see.

##### Suggest a fix

There's two DateTime classes here. Not sure if you can leverage some of sort "namespace" feature in dart. Perhaps the "library" feature to separate the dart.core DateTime and the OpenAPI generated one.

**Comment by wing328** [comment]
What about whilelisting DateTime as a reserved keyword so that DateTime model becomes `ModelDateTime` instead?

**Comment by Morkos** [comment]
@wing328 How do I get about doing that exactly? I looked through the swagger docs, but wasn't sure how to use the "--reserved-words-mappings" ...
