### ISSUE TITLE
[ANNOUNCEMENT] 3.0.3 release postponed to coming Wednesday (Jun 27th)

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#396]
##### Description

We'll postpone the patch release 3.0.3 from today (Monday) to coming Wednesday (Jun 27th) since we would like to include a few PRs (enhancements, bug fixes) in the release.

Should you have any question, please reply to let us know

**Comment by jmini** [comment]
I have closed [milestone 3.0.3](https://github.com/OpenAPITools/openapi-generator/milestone/6)

Still pending for the 3.0.3 release:

* Homebrew formula (I guess)
* Gradle Plugin publication
* Merge of #408

**Comment by ackintosh** [comment]
oops... I missed updating homebrew formula. 💦  will file PR to homebrew ASAP.

**Comment by jmini** [comment]
Gradle plugin was published to maven central.

**Comment by ackintosh** [comment]
Pull request is already exists 👀 
https://github.com/Homebrew/homebrew-core/pull/29504

**Comment by ackintosh** [comment]
🍺🍺🍺

```
[10:27:27] nakano:~ $ brew upgrade openapi-generator
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, homebrew/cask).
==> Updated Formulae
openapi-generator ✔

==> Upgrading 1 outdated package, with result:
openapi-generator 3.0.2 -> 3.0.3
==> Upgrading openapi-generator
==> Downloading https://search.maven.org/remotecontent?filepath=org/openapitools/openapi-generator-cli/3.0.3/openapi-generator-cli-3.0.3.jar
######################################################################## 100.0%
🍺  /usr/local/Cellar/openapi-generator/3.0.3: 4 files, 15.3MB, built in 21 seconds
[10:28:45] nakano:~ $ openapi-generator version
3.0.3
```
