### ISSUE TITLE
[BUG] Multiple samples not regenerated after 4.1.2 release

### ISSUE THREAD

**Issue by jimschubert** [OpenAPITools/openapi-generator#3974]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Go sample (and others) wasn't regenerated after the 4.1.2 release. Seems there's something missing in automation. See https://openapi-generator.slack.com/archives/CLSB0U0R5/p1569625581055100

##### openapi-generator version

4.1.3-SNAPSHOT

##### Suggest a fix

Investigate build scripts and update accordingly.

**Comment by wing328** [comment]
Go samples (OAS3) added to ensure-up-to-date script via https://github.com/OpenAPITools/openapi-generator/pull/3979

If there are more, I'm happy to look into it.
