### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by MickStanciu** [OpenAPITools/openapi-generator#3980]
Hi, I am using Gradle with Kotlin DSL

This is the important part of the code:
`
plugins {
    java
    id ("org.openapi.generator") version "4.1.2"
}

configure<org.openapitools.generator.gradle.plugin.extensions.OpenApiGeneratorGenerateExtension> {
    this.generatorName = "spring" as Property<String>
}
`

This is the error:
> * What went wrong:
> Script compilation error:
> 
>   Line 72:     this.generatorName = "spring" as Property<String>
>                ^ Val cannot be reassigned
> 

I have to mention that I tried in a separate project with Groovy and it works (although Gradle 5 warn me about the same issue). Is it any 'magic' way to make it work with Kotlin DSL?

Thank you

**Comment by Zomzog** [comment]
Hi,

Can you try this syntax?
```
openApiGenerate {
  generatorName.set("spring")
}
```

**Comment by MickStanciu** [comment]
> Hi,
> 
> Can you try this syntax?
> 
> ```
> openApiGenerate {
>   generatorName.set("spring")
> }
> ```

Hi, it works :) Thank you
