### ISSUE TITLE
[BUG] [AVRO] MR 3728 broke the package handling of the avro generator

### ISSUE THREAD

**Issue by Choobz** [OpenAPITools/openapi-generator#3987]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
Package handling was broken for the avro generator during [MR 3728](https://github.com/OpenAPITools/openapi-generator/pull/3728).  
```java
cliOptions.add(new CliOption(CodegenConstants.INVOKER_PACKAGE, CodegenConstants.INVOKER_PACKAGE_DESC));
cliOptions.add(new CliOption(CodegenConstants.API_PACKAGE, CodegenConstants.API_PACKAGE_DESC));
cliOptions.add(new CliOption(CodegenConstants.MODEL_PACKAGE, CodegenConstants.MODEL_PACKAGE_DESC));
```

That part was removed so now all ref type point toward the model package no matter the namespace of the targeted object.
 

##### openapi-generator version
4.1.1

##### OpenAPI declaration file content or url
```yaml
components:
  schemas:
    Pet:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
        friend:
          $ref: '#/components/schemas/Friend'
    Friend:
      type: object
      properties:
        id:
          type: string
```

**Result**
```json
{
  "namespace": "fr.test",
  "type": "record",
  "doc": "",
  "name": "Pet",
  "fields": [
 ...
    {
      "name": "friend",
      "type": ["null", "model.Friend"],
      "doc": ""
    }
  ]
}
````

**Expected**
```json
{
  "namespace": "fr.test",
  "type": "record",
  "doc": "",
  "name": "Pet",
  "fields": [
 ...
    {
      "name": "friend",
      "type": ["null", "fr.test.Friend"],
      "doc": ""
    }
  ]
}
````

##### Command line used for generation
```xml
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <!-- RELEASE_VERSION -->
    <version>4.1.1</version>
    <!-- /RELEASE_VERSION -->
    <executions>
        <execution>
            <id>avro-schema</id>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>avro-schema</generatorName>
                <configOptions>
                    <packageName>fr.test</packageName>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

##### Steps to reproduce
mvn compile

##### Suggest a fix
Not entirely sure about the fix, I don't think the original proposition for package handling was really standard and/or accepted by the maintaining team. 
Could do the MR if pointed toward the right way to handle packages and namespaces for imported avsc files.

**Comment by wing328** [comment]
@Choobz I removed those options since those options didn't seem to be used in the templates.

If I understand the fix correctly, the model needs to be prefixed with the namespace, right?

cc @sgadouar

**Comment by Choobz** [comment]
Yep exactly, the current implementation default to model.object ignoring the namespace of the referenced object.

**Comment by sgadouar** [comment]
Yes correct ! I agree

**Comment by Choobz** [comment]
Thanks a lot for your work and help 👍
