### ISSUE TITLE
[BUG][Kotlin] Kotlin client  variable name

### ISSUE THREAD

**Issue by andrewemery** [OpenAPITools/openapi-generator#3992]
##### Description

Kotlin client generates invalid variable names for reserved words.

##### openapi-generator version

Working in: 4.1.2
Broken in: 4.1.3-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
responses:
  '200':
    schema:
      properties:
        data: # kotlin reserved word
          type: string
```

Expected:
```kotlin
val `data`: String
```

Actual:
```kotlin
val ``data`` String
```

##### Command line used for generation

```bash
openapi-generator generate -g kotlin
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/3899

**Comment by wing328** [comment]
Closed via #3993
