### ISSUE TITLE
[BUG][Scala-AKKA] The custom package name is being overwritten in reference.conf file

### ISSUE THREAD

**Issue by aneksamun** [OpenAPITools/openapi-generator#4004]
Hi,

I been settings custom `mainPackage` name in the `pom` file.
```
      <plugin>
        <groupId>org.openapitools</groupId>
         ...
            <configuration>
              <inputSpec>${project.basedir}/target/licenseplate-api-contract.json</inputSpec>
              <generatorName>scala-akka</generatorName>
              <configOptions>
                <mainPackage>com.some.package</mainPackage>
                <configKeyPath>com.some.package</configKeyPath>
              </configOptions>
              <output>${project.basedir}</output>
            </configuration>
      ...
      </plugin>
``` 
When code generation complete the `reference.conf` file contains hardcoded package name `org.openapitools.client` which is causing runtime error making HTTP request:
```
.../reference.conf: 1: No configuration setting found for key 'com'
```
I need the same namespace as `mainPackage`.   

At the first glance looking at`ScalaAkkaClientCodegen` it look like the `configKeyPath` is not being set from configuration.
Please can you fix this issue?
Can we have custom api, model & invoker package - it been ignored now?

Regards,
Sergey

**Comment by wing328** [comment]
> Can we have custom api, model & invoker package - it been ignored now?

Sure we can. If you have time I can probably show you where to fix it.

**Comment by aneksamun** [comment]
Sure, I reckon it is in 
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ScalaAkkaClientCodegen.java
within `processOpts` function.
