### ISSUE TITLE
[haskell-http-client] Bug in generated file when `dateTimeFormat` parameter set

### ISSUE THREAD

**Issue by frincon** [OpenAPITools/openapi-generator#4012]
##### Description
When specified `dateTimeFormat` the module generated does not compile. The problem is in the this line: https://github.com/OpenAPITools/openapi-generator/blob/31827f5f35a049ec70697d642ce966c3b4499aac/modules/openapi-generator/src/main/resources/haskell-http-client/Core.mustache#L429

Wrong trailing comma!

##### openapi-generator version
Master

##### OpenAPI declaration file content or url

Any API

**Comment by jonschoning** [comment]
merged - thanks!
