### ISSUE TITLE
[REQ] Some Questions on Converting C# flags Enumeration to Python

### ISSUE THREAD

**Issue by grapevictory** [OpenAPITools/openapi-generator#4044]
Can you provide an interface for converting the C_ flags enumeration into a user-defined Python data structure, not just a list? And an interface to customize the corresponding enumeration matching mechanism for users. Thank you.

**Comment by spacether** [comment]
This description is not very clear. It looks like the author is asking that `Indicates that an enumeration can be treated as a bit field; that is, a set of flags.`
per https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-6.0

**Comment by spacether** [comment]
Closing this as stale and because the requested info was never provided
