### ISSUE TITLE
[Announcement] add an entry for this project in Vert.x Awesome

### ISSUE THREAD

**Issue by vietj** [OpenAPITools/openapi-generator#4060]
It would be great to make a PR to https://github.com/vert-x3/vertx-awesome and advertise this generator.

**Comment by wing328** [comment]
@vietj thanks for the suggestion. Do you mind submitting the PR for us?

**Comment by wing328** [comment]
Filed https://github.com/vert-x3/vertx-awesome/pull/157 by @slash-arun

**Comment by wing328** [comment]
We'll use https://github.com/vert-x3/vertx-awesome/pull/157 to track instead. Closing this one.
