### ISSUE TITLE
[BUG] [cwiki] Confluence wiki poorly formatted

### ISSUE THREAD

**Issue by deviantlycan** [OpenAPITools/openapi-generator#4061]
##### Description

The output of the Confluence wiki (cwiki) results in a poorly formatted confluence page.
* rows in the model table are split
* anchor to the models does not work
* several other small offending issues.

##### openapi-generator version
4.1.2

##### Command line used for generation

```
openapi-generator generate -i openapi.yaml -o ./generated -g cwiki 
```
##### Steps to reproduce

1. generate the wiki document
2. add to Confluence Cloud
3. Look at the Models section

### Solution
Template improvements, I have a fix and will make a PR.

**Comment by ackintosh** [comment]
@deviantlycan Thanks for your contribution! The PR has been merged to master. ✨
