### ISSUE TITLE
[BUG][Rust] Enums are not accessible outside the crate

### ISSUE THREAD

**Issue by borsboom** [OpenAPITools/openapi-generator#4079]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When an `enum` is defined along with a `struct`, that enum is not exported from the crate and so external code using the model cannot access its values.

In the Pet Store example, [models/pet.rs](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/rust/reqwest/petstore/src/models/pet.rs) defines `pub enum Status`.  However, [models/mod.rs](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/rust/reqwest/petstore/src/models/mod.rs) only exports the `Pet` struct, but not the `Status` enum:
```
pub use self::pet::Pet;
```
The `pet` module is also not exported, so it can't be accessed that way:
```
mod pet;
```

##### openapi-generator version

```
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar version
4.1.3-SNAPSHOT
```

##### OpenAPI declaration file content or url

[Pet store example](https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml)

##### Command line used for generation

```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml -g rust -o /tmp/petstore
```

##### Steps to reproduce

Run the above command line.

##### Related issues/PRs

#2244 added support for enums.

##### Suggest a fix

There are two approaches I can think of:

1. Have `models/mod.rs` export the whole module where the struct and enums are defined.  For example, [models/mod.rs](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/rust/reqwest/petstore/src/models/mod.rs) would have
   ```
   pub mod pet;
   ```
   instead of 
   ```
   mod pet;
   ```
   This way the enum could be accessed as `[crate]::models::pet::Status`.

2. Have `models/mod.rs` export the enum directly.  For example, [models/mod.rs](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/rust/reqwest/petstore/src/models/mod.rs) would have
   ```
   pub use self::pet::{Pet, Status};
   ```
   instead of 
   ```
   pub use self::pet::Pet;
   ```
   This would allow the enum to be accessed as `[crate]::models::Status`.

   However, there is a problem with this approach: the enum names are not necessarily unique (another struct could also have an enum named `Status`), so for this to work the enum name would have to be disambiguated, for example by prepending the struct name (so `Status` would become `PetStatus`).

/cc @bjgill (submitter of PR that added enum support)

**Comment by borsboom** [comment]
I have a local patch that fixes this using approach (1), which I'd be happy to submit as a PR if that approach sounds good.

**Comment by bjgill** [comment]
Good catch. I think https://github.com/OpenAPITools/openapi-generator/pull/3895/files#diff-6c10c5027ae03bc37f3ef221b5e37bf8L3 contains the fix for this (also using option 1). I'll try to get that in quickly to fix this issue.

**Comment by bjgill** [comment]
OK. That should now be done. Can you confirm that this is now fixed?

**Comment by borsboom** [comment]
Awesome, looks good!

Since we're talking enums, what do you think about deriving a few more traits for them?  In particular, `Clone` and `Copy` would be great because there's no reason we should have to deal with move/borrow semantics for simple enums like this (`Clone` would be nice for structs as well).  I think `Eq` would be make sense, since `PartialEq` is already derived and any enum is going to be reflexive.  `Hash` could be helpful too in some cases, but not sure if this one would always make sense.  `PartialOrd` and `Ord` could be nice, although not every enum is really going to have a natural ordering so I can see and argument for not deriving them.
