### ISSUE TITLE
Kotlin SerializableModel is missleading

### ISSUE THREAD

**Issue by darktanker89** [OpenAPITools/openapi-generator#4096]
##### Description

serializableModel introduced in #4006 relate to

> java.io.Serializable

as a kotlin user you might expect the @Serializable to be tied to

> kotlinx.serialization.Serializable

 (https://github.com/Kotlin/kotlinx.serialization)

naming/doc is lacking precision and can be missleading

##### OpenAPI declaration file content or url

docs/generators/kotlin-server.md
docs/generators/kotlin.md

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/4006 @janweinschenker

**Comment by janweinschenker** [comment]
Will be fixed with #4021 and commit 973392f

**Comment by janweinschenker** [comment]
@wing328 I really think #4021 fixed this. This issue will be resolved with milestone 4.2.0
