### ISSUE TITLE
[BUG] spaces in schema.title causes spaces in interface

### ISSUE THREAD

**Issue by snebjorn** [OpenAPITools/openapi-generator#4097]
##### Description

When a response title is set and have spaces then the resulting model will also have spaces. Which is not allowed.

```ts
export interface Collection of Foo { 
    value?: Array<NAMESPACEFoo>;
}
```

The [definition for `schema.title` ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#schemaObject)
> are taken directly from the JSON Schema definition and follow the same specifications

[which is](https://tools.ietf.org/html/draft-wright-json-schema-00#section-4.5)

> 4.5.  Root schema and subschemas
> 
>    The root schema is the schema that comprises the entire JSON document
>    in question.
> 
>    Some keywords take schemas themselves, allowing JSON Schemas to be
>    nested:
> 
>    ```json
> {
>        "title": "root",
>        "items": {
>            "title": "array item"
>        }
>    }
> ```
> 
>    In this example document, the schema titled "array item" is a
>    subschema, and the schema titled "root" is the root schema.

So spaces in title is valid.

##### openapi-generator version

`"@openapitools/openapi-generator-cli": "^1.0.1-4.1.3"`... yes the version is `1.0.1-4.1.3` it's not a range - it's a bit weird.
Check https://www.npmjs.com/package/@openapitools/openapi-generator-cli

##### OpenAPI declaration file content or url

```json
{
  "openapi": "3.0.0",
  "info": {
    "title": "Foo",
    "version": "0001",
    "description": "The description"
  },
  "paths": {
    "/FooSet": {
      "get": {
        "summary": "Get entities from FooSet",
        "responses": {
          "200": {
            "description": "Retrieved entities",
            "content": {
              "application/json": {
                "schema": {
                  "title": "Collection of Foo",
                  "type": "object",
                  "properties": {
                    "value": {
                      "type": "array",
                      "items": { "$ref": "#/components/schemas/NAMESPACE.Foo" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "NAMESPACE.Foo": {
        "type": "object",
        "properties": {
          "id": { "type": "string", "maxLength": 12 }
        },
        "title": "Foo"
      }
    }
  }
}
```

##### Command line used for generation

> npx openapi-generator generate -g typescript-angular -i openapi.json -o out/test

##### Steps to reproduce

Generate a client that have a space in `paths["/endpoint"].get.responses.200.content.application/json.schema.title`

**Comment by snebjorn** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/7e8c7db79884d2812215a7168a61466a744c745d/modules/openapi-generator/src/main/java/org/openapitools/codegen/InlineModelResolver.java#L439

I believe that also need to have the regex replace.

```java
return uniqueName(title).replaceAll("[^A-Za-z0-9]", "_");
```

**Comment by macjohnny** [comment]
@snebjorn would you like to file a PR to fix this?

**Comment by snebjorn** [comment]
Sure thing

**Comment by snebjorn** [comment]
@macjohnny not sure what to do from here. The PR notes said something about tagging the correct people, but the change ended up not being language specific.

**Comment by macjohnny** [comment]
I think the core team should have a look
