### ISSUE TITLE
[REQ][typescript-angular] Option to rename ApiModule and Configuration

### ISSUE THREAD

**Issue by snebjorn** [OpenAPITools/openapi-generator#4101]
### Is your feature request related to a problem? Please describe.

Generated angular client module will always be called `ApiModule`. 
The module also exposes a `Configuration` object which also cannot be renamed.

This isn't great when multiple generated clients are needed in a single project.

## Describe the solution you'd like

I'd like an Config Option for typescript-angular that can configure the `Module` and `Configuration` prefix. 

Option | Description | Values | Default
-- | -- | -- | --
modulePrefix | The prefix of the file and class of the generated module (\<prefix>.module.ts and `class <prefix>Module`). |   | Api
configuraionPrefix | The prefix of the file and class of the generated configuration object (\<prefix>Configuration.ts and `class <prefix>Configuration`). |   | null

**Note** _the names are in the default fileNaming: camelCase format, but kebab-case should also be supported_

**Comment by macjohnny** [comment]
I agree on `configurationPrefix`, but why would `modulePrefix` be necessary?
It isn't useful to import the module anywhere if you use the `providedInRoot` option (https://openapi-generator.tech/docs/generators/typescript-angular)

**Comment by denyo** [comment]
As an alternative you can easily post process whatever gets generated, e.g. do renaming or replacements, transpile it to js, bundle it, etc.

**Comment by snebjorn** [comment]
> I agree on `configurationPrefix`, but why would `modulePrefix` be necessary?
> It isn't useful to import the module anywhere if you use the `providedInRoot` option (https://openapi-generator.tech/docs/generators/typescript-angular)

You only import the module in the root module. But if you have multiple clients it'll look like this.

```ts
import {
  ApiModule as FooApiModule,
  Configuration as FooApiConfiguration
} from "src/generated-clients/foo";
import {
  ApiModule as BarApiModule,
  Configuration as BarApiConfiguration
} from "src/generated-clients/bar";

@NgModule({
  imports: [
    FooApiModule.forRoot(
      () =>
        new FooApiConfiguration({
          basePath: environment.fooUrl
        })
    ),
    BarApiModule.forRoot(
      () =>
        new BarApiConfiguration({
          basePath: environment.barUrl
        })
    )
  ]
})
export class AppModule {}
```

**Comment by macjohnny** [comment]
No need to import the modules if the services are providedInRoot. The configuration can be set via dependency injection

**Comment by snebjorn** [comment]
Oh yeah that's right. That make things a lot simpler. Or well in a way.

```ts
import {
  ApiModule as FooApiModule,
  Configuration as FooApiConfiguration
} from "src/generated-clients/foo";
import {
  ApiModule as BarApiModule,
  Configuration as BarApiConfiguration
} from "src/generated-clients/bar";

@NgModule({
  imports: [
    FooApiModule.forRoot(
      () =>
        new FooApiConfiguration({
          basePath: environment.fooUrl
        })
    ),
    BarApiModule.forRoot(
      () =>
        new BarApiConfiguration({
          basePath: environment.barUrl
        })
    )
  ]
})
export class AppModule {}
```

vs

```ts
import { Configuration as FooApiConfiguration } from "src/generated-clients/foo";
import { Configuration as BarApiConfiguration } from "src/generated-clients/bar";

@NgModule({
  providers: [
    {
      provide: FooApiConfiguration,
      useValue: new FooApiConfiguration({
        basePath: environment.fooUrl
      })
    },
    {
      provide: BarApiConfiguration,
      useValue: new BarApiConfiguration({
        basePath: environment.barUrl
      })
    }
  ]
})
export class AppModule {}
```

It's not much different. So I still think that people should have the option to name their module and configuration then they can use the "style" they want.

BTW the `BASE_PATH` token should probably also be affected by `configurationPrefix` option.

```ts
export const BASE_PATH = new InjectionToken<string>('basePath');
```

Wont the `'basePath'` have to be unique? So 
```ts
export const PREFIX_BASE_PATH = new InjectionToken<string>('<prefix>BasePath');
````

Maybe a single option that affects all of the above would be the best approach.

**Comment by macjohnny** [comment]
`basePath` is just a description, it is the very reference to `BASE_PATH` which is unique, even if the expression
```typescript
export const BASE_PATH = new InjectionToken<string>('basePath');
```
appears several times in the code

**Comment by macjohnny** [comment]
so I think we should close this issue, as there is little to no gain at the expense of more configuration options.

**Comment by snebjorn** [comment]
fair enough

**Comment by macjohnny** [comment]
@snebjorn there is a PR that allows configuration of the ApiModule name: https://github.com/OpenAPITools/openapi-generator/pull/4209

**Comment by snebjorn** [comment]
That's fantastic :)

**Comment by sorohan** [comment]
Would you be open to a pull request for this one for `configurationPrefix` too?
