### ISSUE TITLE
[BUG] [Powershell] nullable used for arrays and complex types

### ISSUE THREAD

**Issue by martinweu** [OpenAPITools/openapi-generator#4107]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
the pet store example includes that bug in the Pet-Model. The Problem is the tags parameter
array:
```
[Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[IO.Swagger.Model.Tag[]]]
        ${tags},

```
complex type:

```
[Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [System.Nullable[Org.OpenAPITools.Model.Category]]
        ${category},
```

So `System.Nullable[array[]]` is not working because arrays in Powershell / .Net ... are anyhow nullable, so the language does not allow this. Same for complex types like `category`

Reference to generated code:
[https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/powershell/src/Org.OpenAPITools/Model/New-Pet.ps1](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/powershell/src/Org.OpenAPITools/Model/New-Pet.ps1)

- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? current
- [x] Have you search for related issues/PRs? nothing found
- [x ] What's the actual output vs expected output?

actual:
      `[System.Nullable[IO.Swagger.Model.Tag[]]]`
      `[System.Nullable[Org.OpenAPITools.Model.Category]]`
expected:
       `[IO.Swagger.Model.Tag[]]`
       `[Org.OpenAPITools.Model.Category]`

##### openapi-generator version

current master

##### OpenAPI declaration file content or url

petstore example

##### Command line used for generation

whatever is used to generate the examples in the repository itself

##### Suggest a fix

https://github.com/OpenAPITools/openapi-generator/pull/4106

**Comment by wing328** [comment]
@martinweu We've added a new `powersehll-experimental` client generator. Please give it at try and let us know if you've any feedback. Thanks.
