### ISSUE TITLE
[REQ] Update python test dependencies

### ISSUE THREAD

**Issue by yurinnick** [OpenAPITools/openapi-generator#4114]
### Is your feature request related to a problem? Please describe.

Python clients get generated with old and unsupported testing dependencies:
- [randomize](https://pypi.org/project/randomize) Last released: Oct 16, 2016
- [nose](https://pypi.org/project/nose) Last released: Jun 2, 2015

Consider that this dependencies may not be compatible with Python 3 while Python 2 will be officially unsupported 01.2020

## Describe the solution you'd like

Update to a modern libraries with similar functionality:
- [nose2](https://pypi.org/project/nose2)
- [nose-randomly](https://pypi.org/project/nose-randomly)
- [randomly](https://pypi.org/project/randomly)

**Comment by wing328** [comment]
@yurinnick I wonder if you can file a PR to help update the libraries to the latest stable version.

**Comment by spacether** [comment]
Another solution here would be to switch from nose to pytest.
It is actively maintained per pypi: https://pypi.org/project/pytest/#history

More people/projects may prefer it per the number of github stars.
Pytest: https://github.com/pytest-dev/pytest 5.2k stars
Nose: https://github.com/nose-devs/nose 1.3k stars
