### ISSUE TITLE
[BUG] [typescript-rxjs] Typescript error in generated files for query parameters

### ISSUE THREAD

**Issue by balazs-zsoldos** [OpenAPITools/openapi-generator#4159]
##### Description

In case Typescript strict mode is on, there is typescript error in the generated code if a function has one or more query parameters.

##### openapi-generator version

4.0.3 - 4.1.3

##### OpenAPI declaration file content or url

The standard petstore yaml file that is used to generate the samples.

##### Command line used for generation

See the samples directory for the generated files.

##### Steps to reproduce

* Download the typescript-rxjs/default (or any other) sample from the github master branch
* Copy it into a project where typescript strict mode is on, or
* Just open it in Visual Code to see the error in UserApi.ts loginUser function.

Generated code:

`   const query: HttpQuery = {
            ...(requestParameters.username && { 'username': requestParameters.username }),
            ...(requestParameters.password && { 'password': requestParameters.password }),
        };`

Error message:

`Type '{} | { 'username': string; } | { 'password': string; } | { 'password': string; 'username': string; }' is not assignable to type 'HttpQuery'.
  Type '{}' is not assignable to type 'HttpQuery'.
    Index signature is missing in type '{}'.`

##### Related issues/PRs

none

##### Suggest a fix

The generated code was ok until 4.0.2. It would be good to check why the mustache files were changed to the new code.

**Comment by macjohnny** [comment]
changing the generated code to
```typescript
const query: HttpQuery = <HttpQuery>{ ...(requestParameters.username && { 'username': requestParameters.username }), ...(requestParameters.password && { 'password': requestParameters.password }), };
```
instead of
```typescript
const query: HttpQuery = { ...(requestParameters.username && { 'username': requestParameters.username }), ...(requestParameters.password && { 'password': requestParameters.password }), };
```
seems to fix the issue.
See http://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAEsxgIoFcICcRQLxQN5QG0BrCEALigGdg0BLAOwHMBdC6upqAHynuQFsARum69kAG3GjBAexniIAQ3qiAgmjSKQAHnYNGovkJE8+k6XIXKAfFAC+AbgCwAKFcBjGfWpQ0EAI6o1AAKipr8EMDolNh4rlAJUMiU6PSKERQA5JkANPGJYIqUlADuMmgAJlmZrnauHl4+-hRwCCjomDi4jg3ewFCBHS3wSKgYsfgAdNMAFH6DIWHpkdGTyanLUABkW3hQmetoaRGZFPNBwKHhK2iUaylHm3YAlDlQ05NzARdXy1G3k0KxTKlW2u3wmSBpXKFVOvm+EEW13+dyhIIq9le9mcLk8fQGYxAACZhm1CbFtK1Rh1rFNZudEZclhEUfcNhEwXsDg9jhA4QykX9VodeZi3h8vgsmcjVmiYZyIXLKvyEYKWbKitDQS83j03Pq8T5BOJFKTqeMcJSRu0MLSoMbTXg7M6cUA

**Comment by balazs-zsoldos** [comment]
I am wondering, why this is better/faster than the code that was generated in 4.0.2. With 5+ query parameters there would be lots of unnecessary cloning (if I understand ... operator well, I have never really used it in this way).

The code that is generated by 4.0.2:

    const queryParameters: HttpQuery = {};
    
    if (requestParameters.username !== undefined && requestParameters.username !== null) {
        queryParameters['username'] = requestParameters.username;
    }

    if (requestParameters.password !== undefined && requestParameters.password !== null) {
        queryParameters['password'] = requestParameters.password;
    }

I also think that the code that 4.0.2 generates could be simplified to

    requestParameters.password != null

This does an automatic casting from undefined to null and does not give a positive result for the number 0 (as no cast from number 0 is done to null).

**Comment by macjohnny** [comment]
performance impacts should not play an important role in this case.
I agree sometimes the code could be simplified, but since it was changed for some reasons, one would need to carefully ensure to re-test all issues that were meant to be fixed.
