### ISSUE TITLE
[BUG][Java] isBasicBearer not used in default template

### ISSUE THREAD

**Issue by tpeyrard** [OpenAPITools/openapi-generator#4178]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generating the code with the default Java template, it seems the new added `isBasicBearer` is not used:
https://github.com/OpenAPITools/openapi-generator/blob/7ab73ff587a4c112307f9b646d4af744bb17d152/modules/openapi-generator/src/main/resources/Java/ApiClient.mustache#L106-L108

The Bearer part is defined inside the `isBasicBasic`. I thought it would be within the `isBasicBearer`.

##### openapi-generator version

4.1.3

##### OpenAPI declaration file content or url

Although the problem is at the template level, not the code generation I think, here is the link to the OpenAPI spec:
https://api.criteo.com/marketing/swagger/docs/v.1.0

##### Command line used for generation
https://github.com/criteo/criteo-marketing-sdk-generator/blob/master/build-java/build.gradle#L66-L93

Thanks :)

**Comment by macjohnny** [comment]
@tpeyrard would you like to file a PR to fix this?

**Comment by tpeyrard** [comment]
If that's really a "bug" / "missing feature", then yes I'd be happy to file
a PR.

Are you ok to say it should use the `isBasicBearer` for the Bearer
authentication?

Le ven. 18 oct. 2019 à 12:30, Esteban Gehring <notifications@github.com> a
écrit :

**Comment by macjohnny** [comment]
looking at other templates like e.g.
https://github.com/OpenAPITools/openapi-generator/blob/c2ad14ea02f47dcca2acd8458428777b38e752fa/modules/openapi-generator/src/main/resources/typescript-fetch/apis.mustache#L109-L126
it seems `{{#isBasicBearer}}` is correct

**Comment by macjohnny** [comment]
however, looking at the code
https://github.com/OpenAPITools/openapi-generator/blob/7ab73ff587a4c112307f9b646d4af744bb17d152/modules/openapi-generator/src/main/resources/Java/ApiClient.mustache#L106-L108
the line
```java
{{^isBasicBasic}} 
 authentications.put("{{name}}", new HttpBearerAuth("{{scheme}}"));{{/isBasicBasic}}
```
should be added if basic-bearer authentication is enabled, since
`{{^isBasicBasic}}` is the negation of `{{#isBasicBasic}}`

**Comment by tpeyrard** [comment]
Ok, thanks.
I'll see how to build and add tests to the templates.

**Comment by tpeyrard** [comment]
So I tried to "fix" it but there is nothing to fix in fact.
I learnt the "inverted selection" in Mustache, so the current code is not using `isBasicBearer`, but since there is only one possible choice other than isBasicBasic, it works.

So either I leave the code as-is, or I change it to use the `isBasicBearer` instead of `^isBasicBasic` (pay attention to the `^`).

wdyt?

**Comment by macjohnny** [comment]
i think isBasicBearer is more future-proof

**Comment by addynaik** [comment]
Sorry i hadnt seen the defect. I fixed it since we needed for for our purpose. I created a PR with the fix.

**Comment by tpeyrard** [comment]
Thanks I didn't have time this week to work on it.
