### ISSUE TITLE
[REQ] Deserialisation very slow in python client

### ISSUE THREAD

**Issue by ghost** [OpenAPITools/openapi-generator#4181]
### Is your feature request related to a problem? Please describe.

Deserialization of large json is very slow

## Describe the solution you'd like

The current code uses setattr which might be contributing to this majorly

**Comment by wing328** [comment]
What about using a  Python serializer?

https://voidfiles.github.io/python-serialization-benchmark/

**Comment by spacether** [comment]
@slash-arun can you provide a sample spec and data response that demonstrates this issue?
Then we can use it to debug and solve this problem.

**Comment by spacether** [comment]
Closing this issue because it did not include a reproducible sample, and this issue is investigated in the newer issue:
https://github.com/OpenAPITools/openapi-generator/issues/11496
