### ISSUE TITLE
[BUG] [csharp] client always generated under targetFramework net45

### ISSUE THREAD

**Issue by PeterTriebe** [OpenAPITools/openapi-generator#4202]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator
- [x] What's the version of OpenAPI Generator used? - 4.1.3
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output? actual: `<TargetFramework>net45</TargetFramework>` expected: `<TargetFramework>netstandard2.0</TargetFramework>`

##### Description

open-api generates the client always as `<TargetFramework>net45</TargetFramework>`
Its a bug inside the generator. We always set targetFramework=netstandard2.0 but its not working.

##### openapi-generator version

4.1.3

##### Command line used for generation

example usage: java -jar "openapi-generator-cli-4.1.3.jar" generate -i api.yaml -g csharp -o Example.Client -p targetFramework=netstandard2.0 -p netCoreProjectFile=true -p packageName=Example.Client

##### Steps to reproduce

use the command line and generate the client. After generating check the csproj file. Inside there is a tag "TargetFramework" 

##### Related issues/PRs

I think old fixed bugs like https://github.com/OpenAPITools/openapi-generator/issues/3691 produces this new bug

##### Suggest a fix

I think targetFramework=netstandard2.0 is ignored if netCoreProjectFile=true.
If netCoreProjectFile=false the project is set to netstandard2.0. But netstandard2.0 needs the new netCore Project Format to work.

**Comment by wing328** [comment]
Have you tried the new `csharp-netcore` client generator? Would that meet your need?

**Comment by PeterTriebe** [comment]
Ahh. That is working. Thanks! But i think with "csharp" must also work?

**Comment by wing328** [comment]
We found it challenging to support .net framework 3.x, 4.x and netcore in the same generator so we create a new one `csharp-netcore` just focusing on that.

I'll update `csharp` to mark netcore/netstandand support as deprecated and advise the users to use `csharp-netcore` instead.

**Comment by PeterTriebe** [comment]
ok great. Thanks!
