### ISSUE TITLE
[BUG] Program comments generated from a discription containing multibyte characters described in the OpenAPI spec are garbled.

### ISSUE THREAD

**Issue by Yuutakasan** [OpenAPITools/openapi-generator#4215]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Bounty to sponsor the fix ([The program comment is garbled.](https://www.bountysource.com/issues/82418380-bug-the-program-comment-is-garbled))

##### Description

The description described in multibyte characters in OpenAPI Spec is garbled.

##### openapi-generator version

4.1.2

##### OpenAPI declaration file content or url

```
summary: 法人番号システム Web-API
description: 取得期間を指定して情報を取得するAPIです。
get:
    tags:
        - company
    responses:
        '200':
            $ref: '#/components/responses/csv_unicode'
    operationId: getCorporationByDiff
    summary: 法人期間検索
    description: 法人情報取得期間を元に登記法人の情報を検索することができます。
```

##### Command line used for generation

client
go
java

server 
php-laravel
php-symfony
go
java

html
html2
.
.
etc

##### Steps to reproduce

generate php-laravel program

```
/**
 * ???????? Web-API
 * # ???????? Web-API # ???????? Web-API???? Web-API??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: houjinbangou-webapi@nta.go.jp
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */
```
https://fd1.dev/test/api/openapispecification.yaml

##### Related issues/PRs

non

##### Suggest a fix

Fix garbled characters in multibyte characters

**Comment by Yuutakasan** [comment]
I think it occurs in all languages that have been output via the open api generator
go lang,html,html2

**Comment by Yuutakasan** [comment]
I became a spawner today. I'm looking for someone to deal with.

**Comment by kilves** [comment]
Can't reproduce. Everything looks right for me, both for 4.1.2 and 4.1.3. I used `./openapi-generator-cli generate -i openapispecification.yaml -g php-laravel` and all files were generated with no garbled 
chinese characters.

**Comment by wing328** [comment]
@Yuutakasan is your spec/doc encoded in UTF-8? 

We do have tests in place for double byte characters: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L698

Thanks for becoming a sponsor. We'll try to assist you as usual but there's no SLA.

**Comment by wing328** [comment]
@kilves thanks for performing more tests to troubleshoot the issue.

**Comment by Yuutakasan** [comment]
@wing328 @wing328 
Perhaps there was a problem with the setting method here, so I would like to try the reproduction test again.

**Comment by Yuutakasan** [comment]
When I tried it in another environment, I confirmed that it was not garbled. I started thinking that it might be an environment variable or locale issue.

**Comment by Yuutakasan** [comment]
@wing328 @kilves 
I made my own docker image and ran the openapigenerator, but only en_US.UTF-8 was registered in the CentOS image of Docker. Therefore, garbled characters were generated.

Japanese language file name is garbled when LANG environment variable is set when running Java program on Docker container
https://qiita.com/Targityen/items/f921c95e684810d7087f?fbclid=IwAR1rroPqXbXLfJYkEMkxDuUBjF8Wellulpwp82llvSK0D9ut9FIdnotkFbA

There was no problem with OpenAPIGenerator.
I apologize to you for a fuss over.

**Comment by wing328** [comment]
No problem. Glad to hear the issue has been resolved for you.
