### ISSUE TITLE
[BUG][JAVA][RestTemplate] Specified Accept header values generates uncompilable code

### ISSUE THREAD

**Issue by crosbyb** [OpenAPITools/openapi-generator#4222]
##### openapi-generator version

4.1.0, 4.1.3

##### OpenAPI declaration file content or url
See the attached swagger contract for the full example.

```json
        "parameters": [
          {
            "in": "header",
            "name": "Accept",
            "schema": {
              "enum": [
                "application/vnd.geo+json",
                "text/csv"
              ]
            },
            "required": true
          }
        ],
```

##### Command line used for generation

swagger-client-config.json:
```json
{
  "modelPackage": "sc.v0.client.model",
  "apiPackage": "svc.v0.client",
  "library": "resttemplate",
  "groupId": "api.clients",
  "artifactId": "svc-client",
  "artifactVersion": "0.0.1"
}
```

java -jar ./codegen.jar generate -c ./swagger-client-config.json  -i ./swagger.json -g java -o client/

##### Steps to reproduce

```
mkdir client
java -jar ./codegen.jar generate -c ./swagger-client-config.json  -i ./swagger.json -g java -o client/
cd client/ && mvn install  -q -Dmaven.test.skip=true -Dmaven.javadoc.skip=true && cd ..
```
You'll see the following error when Maven tries to compile:
```
[ERROR] /Users/brad/tmp/openapi-accept/client/src/main/java/svc/v0/client/ServiceApi.java:[77,31] variable accept is already defined in method getAllThings(java.lang.String)
```

There is already a local variable in the method named `accept`, so adding the accept header as an argument to the method creates the conflict.

**Comment by wing328** [comment]
> [ERROR] /Users/brad/tmp/openapi-accept/client/src/main/java/svc/v0/client/ServiceApi.java:[77,31] variable accept is already defined in method getAllThings(java.lang.String)

Looks like this can be fixed by prefixing the variable name with `localVar` (e.g. `localVarAccept`) like we've done in other generators.

I wonder if you've time to file a PR with the suggested fix.

**Comment by fermartel** [comment]
Any update on this issue?

**Comment by ogerardin** [comment]
I just ran into the same problem.
@crosbyb did you use a workaround ?

**Comment by mikesaurus** [comment]
@fermartel @ogerardin 
You can workaround this issue by creating a local copy of the Java/resttemplate/api.mustache template and using the templateDirectory or templateResourcePath config properties to override the default.  I just submitted a PR to update the template in the main codebase, so hopefully they will merge this in for the next release.  In the meantime, you can copy the api.mustache template from my PR and use it with the version you are currently running.

@wing328 https://github.com/OpenAPITools/openapi-generator/pull/7101

**Comment by wing328** [comment]
Thanks for the fix by @mikesaurus 

Please pull the latest master or snapshot to give it a try.
