### ISSUE TITLE
[REQ] [csharp-netcore] Custom JsonSerializer needed

### ISSUE THREAD

**Issue by PeterTriebe** [OpenAPITools/openapi-generator#4241]
### Is your feature request related to a problem? Please describe.

Lib: csharp-netcore

I want to do a "Patch" request to update some entries.
For this reason its needed that "null" values are not serialized. If a property is not serialized it will be ignored from the service.

## Describe the solution you'd like

To solve this i want to add a custom Json serializer. Inside this I'm able to say that null values will be ignored.

example how it worket after i changed the generated code:

```
        private RestRequest newRequest(
            HttpMethod method,
            String path,
            RequestOptions options,
            IReadableConfiguration configuration)
        {

....
            RestRequest request = new RestRequest(Method(method))
            {
                Resource = path,
                JsonSerializer = new CustomJsonCodec(new JsonSerializerSettings
                {
                  NullValueHandling = NullValueHandling.Ignore
                },configuration)
            };
```
But we want to make it more generic :-)
The creation of this request is wrapped by the generated client. And there is actual no way to pass a custom Json serializer. I think its a good idea to pass a custon serializer together wirh the configuration. With this the client can configure what he want.

## Describe alternatives you've considered

Its also possible to add some configurations like `NullValueHandling = NullValueHandling.Ignore` directly to the config. But i think thats not so suitable.

**Comment by jimschubert** [comment]
Are you specifically looking for something that can be manually set by the user?

I'd like to keep RestSharp and JSON.net types out of the Configuration object, because the design allows users to replace the underlying accessor completely. If we begin adding these types back to the Configuration object, the decision to support these types moves from runtime to codegen time.

For your use case, would it make sense to move the RestSharp client construction to it's own template, which you could override as you see fit? The tooling allows you to override only the templates you care to modify, falling back to built-in templates.

I'm hesitant as well to introduce a new option for this patch use case because it would be "global", meaning the client wouldn't allow you to explicitly null out a property in non-PATCH endpoints.

**Comment by jimschubert** [comment]
On second thought, we could also add an option to use the ignore nulls for patch only. Is this the intended suggestion? I may have originally misunderstood.

**Comment by PeterTriebe** [comment]
Ok I understand.
Default it was also set a JsonSerializer from type CustomJaonCodec :

```
        private readonly JsonSerializerSettings _serializerSettings = new JsonSerializerSettings
        {
            // OpenAPI generated types generally hide default constructors.
            ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor,
                ContractResolver = new DefaultContractResolver
                {
                    NamingStrategy = new CamelCaseNamingStrategy()
                    {
                        OverrideSpecifiedNames = true
                    }
                }
        };

        public CustomJsonCodec(IReadableConfiguration configuration)
        {
            _configuration = configuration;
            _serializer = JsonSerializer.Create(_serializerSettings);
        }

        public CustomJsonCodec(JsonSerializerSettings serializerSettings, IReadableConfiguration configuration)
        {
            _serializerSettings = serializerSettings;
            _serializer = JsonSerializer.Create(_serializerSettings);
            _configuration = configuration;
        }

```
I think here we need to pass custom "JsonSerializerSettings".
But how we can solve this without add the type JsonSerializerSettings to the configuration? I dont know :-/

In my case its enough to add `NullValueHandling = NullValueHandling.Ignore`. 

I always create the whole client automatically on the build server from the yaml file. So its not suitable for me to customize the code.

**Comment by PeterTriebe** [comment]
I also habe a similar problem. I want to pass a proxy. https://github.com/OpenAPITools/openapi-generator/issues/4236

I think that was also removed for the same reason.
