### ISSUE TITLE
[BUG] [dart][dart-dio] generated code does not compile if swagger doc paramName is called data

### ISSUE THREAD

**Issue by lingster** [OpenAPITools/openapi-generator#4267]
@athornz 
 I have submitted PR   #4266 which resolves issue with dart-dio library. a bit sort of time to fill out a complete bug report. Will try to do this later in the week if required.
Also thanks for your work on issue #4018 !

#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

**Comment by kuhnroyal** [comment]
@lingster Can you please close the issue, your PR has been merged for a while :)

**Comment by wing328** [comment]
closed
