### ISSUE TITLE
[BUG] rust - lazy_static crate version is out of date

### ISSUE THREAD

**Issue by AsadMGradex** [OpenAPITools/openapi-generator#4271]
Generated a server using 'rust-server' generator.

I got this error:

error: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
    lazy_static! {
        //-snip-    
    }
    ^
----

cargo.toml:
lazy_static = "0.2"

Changing this to:
lazy_static = "1.4.0" (most recent version of this crate) will solve this issue

**Comment by wing328** [comment]
Can you please open a PR with the suggested fix?

**Comment by AsadMGradex** [comment]
Hi @wing328, my experience with the openapigenerator rust-server. The code generated is outdated and several of the dependencies are also outdated (not just lazy_static). Bumping lazy_static won't really have much affect but bumping other crates will cause several errors, like methods/structs/etc no longer existing in the newer version.

Unless a full overhaul of the Rust generation is decided, I think fixing this bug in specific is pointless.

**Comment by richardwhiuk** [comment]
@AsadMGradex I'm disappointed you've had a bad experience with the Rust Server generator.

I've raised a PR to fix the compatibility issues with Rust 1.39 - keeping up with the Rust ecosystem is a fair effort at the moment.

I'm assuming that the rest of your comment is a reference to the generator currently producing code which targets OpenSSL 0.9 / Hyper 0.11?

Sadly, these are all breaking changes, and maintaining fallback in the generator isn't a particularly appetising proposition. I expect that we'll update all of these in time for the 5.x release - and hopefully we'll have snapshot releases available soon with this merged.
