### ISSUE TITLE
[BUG] jws not found, thus mvn install does not work

### ISSUE THREAD

**Issue by michelealbano** [OpenAPITools/openapi-generator#4279]
#### Bug Report Checklist

- [ X ] Have you provided a full/minimal spec to reproduce the issue?

Download current gitlab code
Do mvn clean install

- [ X ] What's the version of OpenAPI Generator used?

commit 55f26d31d3ded1163f37725d00fdcb2b840e4b57 (grafted, HEAD -> master, origin/master, origin/HEAD)
Date:   Wed Oct 3 23:53:50 2018 +0800

- [ X ] Have you search for related issues/PRs?

Yes. Nothing on it.

- [ X ] What's the actual output vs expected output?

Instead of the correct compilation of the source code, I received a:

ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /mnt/hgfs/shared/openapi-generator/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/ElixirClientCodegen.java:[33,17] package javax.jws does not exist

##### Description

openapi-generator does not compile.

##### openapi-generator version

commit 55f26d31d3ded1163f37725d00fdcb2b840e4b57 (grafted, HEAD -> master, origin/master, origin/HEAD)
Date:   Wed Oct 3 23:53:50 2018 +0800

##### OpenAPI declaration file content or url

I just did a mvn clean install

##### Command line used for generation

mvn clean install

##### Steps to reproduce

git clone https://gitlab.com/OpenAPITools/openapi-generator.git
cd openapi-generator
mvn clean install

##### Related issues/PRs

N/A

##### Suggest a fix

Substitute jws in the pom with a different support for jws.

**Comment by wing328** [comment]
@michelealbano are you using Java 7 somehow?

**Comment by michelealbano** [comment]
@wing328 I am using OpenJDK 13:

```
$ java --version
openjdk 13 2019-09-17
OpenJDK Runtime Environment (build 13+13-Ubuntu-0ubunt1)
OpenJDK 64-Bit Server VM (build 13+13-Ubuntu-0ubunt1, mixed mode, sharing)

```

**Comment by michelealbano** [comment]
I was using the code I downloaded on October the 4th. I tried with the current commit, and it works fine.
Please close the bug.
