### ISSUE TITLE
Next release (3.1.0) postponed to Jul 6th (Fri)

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#428]
##### Description

Minor release 3.1.0 has been postponed to coming Friday (Jul 6th) from Monday (Jul 2nd) as the core team would like to include a few more enhacements, bug fixes to the 3.1.0 release.

##### openapi-generator version

3.1.0

**Comment by jmini** [comment]
Maybe we might need to work on our wording... When you read "Minor Release" in this context:

* Patch release (we have no more patch release planned for the `3.0.x` stream)
* Minor release => version `3.1.0` planned. Release containing breaking changes with fallback.
* Major release => version `4.0.0` planned. Release with breaking changes, some of them without fallback

It is clear what "minor" means: Second digit in the version scheme. The release is important.

---

But without all this context, you might understand "minor release" as "small" or "not important".

---

I am not sure how to solve this...

**Comment by jmini** [comment]
Release Tag: https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.1.0

Docker image are present:
* https://hub.docker.com/r/openapitools/openapi-generator-cli/tags/
* https://hub.docker.com/r/openapitools/openapi-generator-online/tags/

Waiting for Maven central sync

**Comment by jmini** [comment]
PR for brew formula: Homebrew/homebrew-core#29806

**Comment by jmini** [comment]
Maven central is also good.
I will work on the Gradle Plugin later this evening.

**Comment by jmini** [comment]
Gradle plugin is published to Maven-Central

**Comment by jmini** [comment]
I just closed milestone [3.1.0](https://github.com/OpenAPITools/openapi-generator/milestone/3).
