### ISSUE TITLE
[BUG] NotNull annotation is not set for requiered body in jaxrs-cxf

### ISSUE THREAD

**Issue by acommuni** [OpenAPITools/openapi-generator#4280]
#### Bug Report Checklist

- [X ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X ] What's the version of OpenAPI Generator used?
- [X ] Have you search for related issues/PRs?
- [X ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When validation is activated with jaxrs-cxf and a body is requiered the annotation @NotNull is not set

##### openapi-generator version

4.1.3

##### OpenAPI declaration file content or url

<configuration>

              <language>jaxrs-cxf</language>
              <generateApis>true</generateApis>
              <generateApiTests>false</generateApiTests>
              <generateModels>true</generateModels>
              <generateSupportingFiles>false</generateSupportingFiles>
              <addCompileSourceRoot>true</addCompileSourceRoot>
              <configOptions>
                <serializableModel>true</serializableModel>
                <sourceFolder>src/main/java</sourceFolder>
                <dateLibrary>java8</dateLibrary><java8>true</java8>
                <invokerPackage>${package-path}.invoker</invokerPackage>
                <modelPackage>${package-path}.model</modelPackage>
                <apiPackage>${package-path}.api</apiPackage>
                <serializableModel>true</serializableModel>
                <useBeanValidation>true</useBeanValidation>
                <useReflectionEqualsHashCode>true</useReflectionEqualsHashCode>
                <useGenericResponse>true</useGenericResponse>
                <booleanGetterPrefix>get</booleanGetterPrefix>
                <addConsumesProducesJson>false</addConsumesProducesJson> 
                <useAnnotatedBasePath>true</useAnnotatedBasePath>               
              </configOptions>
            </configuration>

##### Suggest a fix

You will find the new mustasche for bodyParams

[bodyParams.zip](https://github.com/OpenAPITools/openapi-generator/files/3774553/bodyParams.zip)

**Comment by wing328** [comment]
I wonder if you can open a PR with the suggested fix.
