### ISSUE TITLE
[REQ] [Kotlin Multiplatform] Support authentication

### ISSUE THREAD

**Issue by andrewemery** [OpenAPITools/openapi-generator#4283]
Include support for authentication schemes:
- api key
- http basic
- http bearer
- oauth

**Comment by andrewemery** [comment]
@wing328 Thanks William. What's the process for closing issues? Can I close this after merge or is it waiting on something else?

**Comment by wing328** [comment]
Usually, we close the issue as part of the PR merge using https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords
