### ISSUE TITLE
[BUG] Python client can not use Python-Keyword as parameter

### ISSUE THREAD

**Issue by SimonZgx** [OpenAPITools/openapi-generator#4291]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When I try to use SwaggerClient to generate python rest-api client, I found that if a endpoint has a parameter which is python keyword, it can't be called. The following is my code and part of `swagger.json`:

```python
from bravado.client import SwaggerClient

host = 'https://api-testnet.bybit.com'
spec_uri = host + "/doc/swagger.txt"
...
...
client = SwaggerClient.from_url(spec_uri, config=config, http_client=request_client)

client.Kline.Kline_get(symbol='BTCUSD', interval='1m', from='1572231328')
```

Because `from` is a keyword in python, so there is a syntax error.

```json
        "/v2/public/kline/list": {
            "get": {
                "tags": [
                    "Kline"
                ],
                "summary": "Query historical kline.",
                "operationId": "Kline.get",
                "parameters": [{
                    "name": "symbol",
                    "in": "query",
                    "description": "Contract type.",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "interval",
                    "in": "query",
                    "description": "Kline interval.",
                    "required": true,
                    "type": "string"
                }, {
                    "name": "from",
                    "in": "query",
                    "description": "from timestamp.",
                    "required": true,
                    "type": "number",
                    "format": "int64"
                }, {
                    "name": "limit",
                    "in": "query",
                    "description": "Contract type.",
                    "required": false,
                    "type": "string"
                }],
                "responses": {
                    "200": {
                        "description": "Request was successful",
                        "schema": {
                            "items": {
                                "$ref": "#/definitions/KlineBase"
                            }
                        }
                    }
                },
                "deprecated": false,
                "security": []
            }
        }
    }
```

##### openapi-generator version
2.x

##### OpenAPI declaration file content or url
url

**Comment by wing328** [comment]
> 2.x

Are you using the latest version (v4.1.3) of OpenAPI Generator?

**Comment by SimonZgx** [comment]
No code is generated, I just want to use `SwaggerClient` lib to generate client from url. All endpoints work well except Kline,  just because this endpoint has a parameter `from` which is a python keyword.

**Comment by wing328** [comment]
```
from bravado.client import SwaggerClient
```
That's not supported by us so nothing we can help you with.
