### ISSUE TITLE
[BUG][JavaScript]Timeout unhandled causes crash after PR #1814 

### ISSUE THREAD

**Issue by fabik111** [OpenAPITools/openapi-generator#4296]
##### Description
With [PR #1814 ](https://github.com/OpenAPITools/openapi-generator/pull/1814) was added in the `callApi`  function an object `err ` to better handle errors. `err` has four attributes taken from the `response ` obj>
```
 request.end((error, response) => {
                if (error) {
                    var err = {};
                    err.status = response.status;
                    err.statusText = response.statusText;
                    err.body = response.body;
                    err.response = response;
                    err.error = error;

                    reject(err);
```
If the call ends with a timeout error, the `response` obj will be `undefined` and so I've this problem:
`TypeError: Cannot read property 'status' of undefined`

##### openapi-generator version

v4.1.3

##### Related issues/PRs
[PR #1814 ](https://github.com/OpenAPITools/openapi-generator/pull/1814)
[Line code with bug](https://github.com/OpenAPITools/openapi-generator/blob/d92d84bb12c33e15f27ef5206aa22eacbeeb42cb/modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache#L472)

##### Suggest a fix/enhancement
Add a check if `response` is `undefined`

**Comment by wing328** [comment]
@fabik111 thanks for reporting the issue. Do you mind filing a PR with the suggested fix?
