### ISSUE TITLE
[BUG][C++] special characters and case sensitivity and key "operator" in properties not respected

### ISSUE THREAD

**Issue by AIexG** [OpenAPITools/openapi-generator#4320]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating a server stub, cpp-restbed-server in my case, all functions reading the values through the keys of a JSON request will automatically stripe certain special characters from the keys set the first letter to uppercase and add an underscore to certain keywords (e.g. `operator`). This causes the `pt.put()`, `pt.get()` etc, which apparently are case sensitive to fail aquiring and passing data to and from a JSON file/array.

The [OAS](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#format) also states that keys are case sensitive

> All field names in the specification are **case sensitive**. This includes all fields that are used as keys in a map, except where explicitly noted that keys are **case insensitive**.

I haven't confirmed if any other languages/generators are affected by this problem, but it might be possible!

##### openapi-generator version

- 4.1.3
- 4.2.0-SNAPSHOT

##### OpenAPI declaration file content or url

caseSensitive.yaml

```yaml
openapi: 3.0.1
info:
  title: Case Sensitivity Demo
  contact:
    email: mail@example.com
  version: 1.0.0

paths:
  /demo:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/demoSchema'
        required: true
      responses:
        '405':
          description: 'Validation error'
          content: {}

components:
  schemas:      
    demoSchema:
      type: object
      properties:
        $dollarsign:
          type: string
        §paragraph:
          type: string
        operator:
          type: string
        Firstupper:
          type: string
        noupper: 
          type: string
        midUpper: 
          type: string
        ALLUPPER:
          type: string
```

Generates the following function `toJsonString()`:

```c++
std::string DemoSchema::toJsonString()
{
	std::stringstream ss;
	ptree pt;
	pt.put("dollarsign", m_dollarsign); // should be "$dollarsign"
	pt.put("paragraph", m_paragraph); // should be "§paragraph"
	pt.put("_operator", m__operator); // should be "operator"
	pt.put("Firstupper", m_Firstupper); // alright
	pt.put("Noupper", m_Noupper); // should be "noupper"
	pt.put("MidUpper", m_MidUpper); // should be "midUpper"
	pt.put("ALLUPPER", m_ALLUPPER); // alright
	write_json(ss, pt, false);
	return ss.str();
}
```

_comments indicate the expected output_

##### Command line used for generation

java -jar openapi-generator-cli.jar generate -i .\caseSensitive.yaml -g cpp-restbed-server -o .\openapi-server\

##### Steps to reproduce

Simply don't use an uppercase letter as first character for a property key.

**Comment by wing328** [comment]
Closed via  #4323. Thanks for the PR by @lwlee2608
