### ISSUE TITLE
[BUG][typescript-angular] Type mapping from DateTime to string causes build error

### ISSUE THREAD

**Issue by malymato** [OpenAPITools/openapi-generator#4330]
I encountered the same issue on v 4.1.3 as described here:
https://github.com/OpenAPITools/openapi-generator/issues/2745

When using a type mapping from DateTime to string, generated code contains lines such as `queryParameters = queryParameters.set('dateFrom', <any>dateFrom.toISOString());`, which causes build failure.

This was fixed for typescript-axios generator, but the issue is still present in typescript-angular. I'd like to open a PR with a fix.

**Comment by malymato** [comment]
#2745

**Comment by malymato** [comment]
I'm not familiar with the codebase, would it be ok to override `DefaultCodegen.fromProperty` in AbstractTypeScriptClientCodegen.java? Or is it better to perform a runtime type check in the template as in #3423?

```
@Override
public CodegenProperty fromProperty(String name, Schema p) {
    CodegenProperty property = super.fromProperty(name, p);
    if (property.isDateTime && property.dataType == "string" || property.dataType == "String") {
        property.isString = true;
        property.isDateTime = false;
    }
    return property;
}
```

**Comment by macjohnny** [comment]
I think a runtime check is better
