### ISSUE TITLE
Add support for Spring 5 WebClient and projectreactor

### ISSUE THREAD

**Issue by 0v1se** [OpenAPITools/openapi-generator#434]
##### Description

Support new Spring 5 WebClient and reactive / webflux

##### Suggest a fix/enhancement

Will submit new PR with Spring 5 WebClient support

**Comment by wing328** [comment]
@0v1se please open a PR to start with given that you have the change ready in your branch.

**Comment by 0v1se** [comment]
@wing328 
Opened: https://github.com/OpenAPITools/openapi-generator/pull/435

**Comment by 0v1se** [comment]
This one is fixed now I think

**Comment by KumarManoj-S** [comment]
@0v1se Is there a doc or readme that explains how to use this?
