### ISSUE TITLE
[BUG][Ruby] Set NULL is not possible

### ISSUE THREAD

**Issue by slemrmartin** [OpenAPITools/openapi-generator#4363]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used? 
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

In **Ruby client**, it's not possible to set NULL on any value (I suppose it should be "nullable": true in yaml definition)

##### openapi-generator version

3.3.4, 4.0.0, 4.1.1, 4.2.0

##### OpenAPI declaration file content or url

https://github.com/ManageIQ/topological_inventory-ingress_api/blob/12b92fbdb9485d01b7840318dc42a384f557286a/public/doc/openapi-3-v0.0.2.json#L4243
https://github.com/ManageIQ/topological_inventory-ingress_api/blob/12b92fbdb9485d01b7840318dc42a384f557286a/public/doc/openapi-3-v0.0.2.json#L4252
(2nd case: Is it possible to set nullable to `ref`?)

##### Command line used for generation

```
java -jar openapi-generator-cli-3.4.4.jar generate -i public/doc/opeanpi-3-v0.0.2.json.generator.yaml -c .openapi_generator_config.json -g ruby -o topological_inventory-ingress_api-client-ruby
```
https://github.com/ManageIQ/topological_inventory-ingress_api/blob/master/.openapi_generator_config.json

with version 4.0.0 validator generates 100+ errors, version 4.1+ must be run with `--skip-validate-spec`

##### Steps to reproduce

`TopologicalInventoryIngressApiClient::ServiceOffering.new(:source_ref => '123', :name => 'Sample',...).to_hash`
`TopologicalInventoryIngressApiClient::ServiceOffering.new(:source_ref => '123', :name => nil,...).to_hash`

##### Suggest a fix

Following line causes that keys with `nil` values are deleted, so it's not possible to recognize by server if they're not set or set to nil.

https://github.com/ManageIQ/topological_inventory-ingress_api-client-ruby/blob/8e685e8ae6b50afa69d6aa67284eea64e6da9c9b/lib/topological_inventory-ingress_api-client/models/inventory_collection_service_offering.rb#L199

This client is generated by version 4.2.0

**Comment by wing328** [comment]
Right, I think it's a limitation at the moment.

May I know if you've time to contribute the enhancement? I can show you some good starting points to start with.

**Comment by slemrmartin** [comment]
@wing328 I have time to work on it, we need to fix it, but I'm not java programmer - so I'll be able to fix the client, not generator.

**Comment by wing328** [comment]
@slemrmartin I don't think you need to know Java in this case. You can simply update the mustache template to meet your requirements.

Please PM me via Slack to discuss this further: https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by autopp** [comment]
#4391 fixes this.
@slemrmartin Thanks for report and fix.
