### ISSUE TITLE
[KOTLIN] Feature: Use linter to verify coding style

### ISSUE THREAD

**Issue by guenhter** [OpenAPITools/openapi-generator#439]
##### Description

Use a linter (like klint) to verify the style of the generated Kotlin code as suggested by
https://github.com/OpenAPITools/openapi-generator/pull/427#issuecomment-401612067

##### openapi-generator version

Next minor release

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/427#issuecomment-401612067

**Comment by wing328** [comment]
@guenhter I've filed https://github.com/OpenAPITools/openapi-generator/pull/1400 to add post-processing to Kotlin files and I'm able to use `ktlint` to format the code.

Please review and let us know if you've any question.

**Comment by wing328** [comment]
Closed via #1400
