### ISSUE TITLE
[BUG][SPRING] unhandledException not working in combination with skipDefaultInterface

### ISSUE THREAD

**Issue by JPQuirmbach** [OpenAPITools/openapi-generator#4393]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When I use the optional configuration unhandledException=true in combination with skipDefaultInterface=true the exception is not thrown in the interface.

##### openapi-generator version

4.2.0

###### Actual
```java
Mono<ResponseEntity<TransactionModel>> updateTransaction(@ApiParam(value = "",required=true) @PathVariable("transactionId") Long transactionId,@ApiParam(value = "the transaction to be updated"  )  @Valid @RequestBody Mono<TransactionModel> transactionModel, ServerWebExchange exchange);
```

###### Expected
```java
Mono<ResponseEntity<TransactionModel>> updateTransaction(@ApiParam(value = "",required=true) @PathVariable("transactionId") Long transactionId,@ApiParam(value = "the transaction to be updated"  )  @Valid @RequestBody Mono<TransactionModel> transactionModel, ServerWebExchange exchange) throws Exception;
```

##### Command line used for generation

```xml
<generatorName>spring</generatorName>
<modelNameSuffix>Model</modelNameSuffix>
<configOptions>
  <sourceFolder>src/gen/java/main</sourceFolder>
  <unhandledException>true</unhandledException>
  <interfaceOnly>true</interfaceOnly>
  <skipDefaultInterface>true</skipDefaultInterface>
  <java8>true</java8>
  <dateLibrary>java8</dateLibrary>
  <booleanGetterPrefix>is</booleanGetterPrefix>
  <reactive>true</reactive>
</configOptions>
```

**Comment by ex0b1t** [comment]
+1

**Comment by ex0b1t** [comment]
The issue is in modules/openapi-generator/src/main/resources/JavaSpring/api.mustache. If jdk8-default-interface is false then unhandledException is not rendered.

**Comment by shyamkondisetty** [comment]
how to make jdk80default0interface true

**Comment by ex0b1t** [comment]
> how to make jdk80default0interface true

Hey @shyamkondisetty, not sure if this is documented somewhere but you can have a look at this piece of code https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L436-L463

**Comment by wing328** [comment]
The fix has been fixed. Please pull the latest master to give it a try.

**Comment by guptaavijit** [comment]
Is this really fixed? I still see the issue and cannot get it to work with version 5.4.0 (Maven plugin). When using unhandledException=true in combination with skipDefaultInterface=true the exception is not thrown in the interface.
