### ISSUE TITLE
[BUG][PHP] Model name suffix incorrectly added to inline enum names

### ISSUE THREAD

**Issue by hinrik** [OpenAPITools/openapi-generator#4403]
Consider this definition:

```yaml
components:
  schemas:
    Foo:
      type: object
      properties:
        inline_enum:
          type: string
          enum: [one, two, three]
        referenced_enum:
            $ref: '#/components/schemas/ReferencedEnum'
    ReferencedEnum:
      type: string
      enum: [one, two, three]
```

If you generate PHP from this defintion using a `modelNameSuffix=DTO` option on the generator, the values of `inline_enum` will now change from being e.g. `INLINE_ENUM_ONE` to `INLINE_ENUM_DTO_ONE`, which doesn't make sense.

Values of `ReferencedEnum` are untouched, still `ReferencedEnum::ONE` (though they are unusable regardless [for another reason](https://github.com/OpenAPITools/openapi-generator/issues/4328)).

**Comment by ackintosh** [comment]
@hinrik Thanks for the PR! It has been merged into master. 🎉
