### ISSUE TITLE
[BUG] [AsciiDoc] Names of the parameters are not preserved

### ISSUE THREAD

**Issue by mgwoj** [OpenAPITools/openapi-generator#4408]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example]

##### Description

Documentation generated in AsciiDoc format has invalid parameter names.
If the parameter name is like `X-Some-Param`, in the generated `index.adoc` file it looks like `xSomeParam`, which is wrong. Original name should be preserved.

##### openapi-generator version

2.4.1-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Some API
  version: 0.0.1
paths:
  /v1/api/view/:
    get:
      responses:
        '200':
          description: OK
      parameters:
        - name: X-Some-Param
          in: header
          required: true
          schema:
            type: integer
```

##### Command line used for generation

generated via gradle plugin

##### Steps to reproduce

Generated, wrong content

```asciidoc
====== Header Parameters

[cols="2,3,1,1,1"]
|===         
|Name| Description| Required| Default| Pattern

| xSomeParam 
|   
| X 
| null 
|  

|===         
```

##### Related issues/PRs

None

##### Suggest a fix

Change file `openapi-generator\modules\openapi-generator\src\main\resources\asciidoc-documentation\param.mustache` and replace `paramName` with `baseName`

/CC: @man-at-home

**Comment by man-at-home** [comment]
oh, I see, our own projects are java based, never used -. seems easy to fix.

**Comment by mgwoj** [comment]
The same problem is in the model section, in file `modules/openapi-generator/src/main/resources/asciidoc-documentation/model.mustache` `name` should be replaced with `baseName`

**Comment by mgwoj** [comment]
Thank you for the fast fix
