### ISSUE TITLE
Publish a documentation of options available with each generator

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#441]
We should publish all the option for each generator to our documentation somewhere on GitHub Pages.

**Comment by jmini** [comment]
As workaround the easiest way to get this information is with the CLI:

```
java -jar openapi-generator-cli.jar config-help -l <generator name>
```

**Comment by jmini** [comment]
I understand that users would like to have a page online (especially for maven and gradle users), but this needs to be generated otherwise it will be outdated.

**Comment by wing328** [comment]
We can try to automate that with a script and leverage the CI to perform a check to ensure the config options are up-to-date.
