### ISSUE TITLE
[REQ] [JAVA] [HATEOAS] Replace old depcreated ResourceSupport

### ISSUE THREAD

**Issue by MelleD** [OpenAPITools/openapi-generator#4425]
### Is your feature request related to a problem? Please describe.

The spring hateoas `ResourceSupport` is renamed and depcreated. The new name is now `RepresentationModel`

see https://docs.spring.io/spring-hateoas/docs/current/reference/html/

## Describe the solution you'd like

We have to adapt the mustache template for the name

**Comment by OLibutzki** [comment]
This issue is fixed with #4426. You can close this one.
