### ISSUE TITLE
[BUG][R] model.mustache incorrect links to R help pages

### ISSUE THREAD

**Issue by LiNk-NY** [OpenAPITools/openapi-generator#4428]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The mustache template does too much and it would help to remove the `:{{complexType}}` insert and leave the the spaces out of the curly brace after the square bracket so that you have:
<pre>
#' @field {{baseName}} {{title}} {{^isPrimitiveType}} \link[{{packageName}}]{{{/isPrimitiveType}} {{#isContainer}} {{#isListContainer}}list({{#items}}{{dataType}}{{/items}}){{/isListContainer}}{{#isMapContainer}}named list({{#items}}{{dataType}}{{/items}}){{/isMapContainer}} {{/isContainer}}{{^isContainer}}{{dataType}}{{/isContainer}} {{^isPrimitiveType}}} {{/isPrimitiveType}} {{^required}}[optional]{{/required}}
</pre>
In this block of code:
https://github.com/OpenAPITools/openapi-generator/blob/de162f7f34e6ac2bf91b289fd7c6ae9f82e03f4b/modules/openapi-generator/src/main/resources/r/model.mustache#L8-L11

##### openapi-generator version

4.2.1-SNAPSHOT

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/HumanCellAtlas/matrix-service/master/config/matrix-api.yml

##### Command line used for generation

See this gist: 
https://gist.github.com/LiNk-NY/3a35d4a693e87e5c84ba430680752b96

##### Steps to reproduce

See gist above. 

##### Related issues/PRs

Tangential issue: 
https://github.com/openapitools/openapi-generator/issues/3367

##### Suggest a fix

I have not tested this as I was unable to run it locally. I kept getting errors when using the
`openapi-generator-cli-4.2.0.jar` file. 

```diff
-#' @field op   \link[hcamatrixapi:v1_ComparisonFilterOperator]{  V1ComparisonFilterOperator  }  [optional]
+#' @field op   \link[hcamatrixapi]{V1ComparisonFilterOperator}  [optional]
```

**Comment by Ramanth** [comment]
i doubt the below line will link properly to the "v1_ComparisonFilterOperator" Rd file properly in the help pages with the below change change
#' @field op   \link[hcamatrixapi]{V1ComparisonFilterOperator}  [optional]

If we dont have the :{{complexType}}, its not going to link it to that respective help page in that package.

**Comment by LiNk-NY** [comment]
@Ramanth 
I meant I didn't test the change by using the `.jar` file. 
I did test it in R and it works. 

Have you tried it in R? 

You should only need the package name and function name to link to
the documentation of an exported function. 

Best,
Marcel
