### ISSUE TITLE
[BUG] [typescript-rxjs] Dates become strings?

### ISSUE THREAD

**Issue by SaschaAusUlm** [OpenAPITools/openapi-generator#4451]
Hi!

We're using the version 4.1.3 of the generator and we're trying to move from Swaggerhub's typescript-node to OpenApi's typescript-rxjs.

We did a conversion, but now I am seeing that Dates are not handled correctly, or we're not converting properly?

In the JSON:
```javascript
licenseStartDate | string($date-time)
```
with the call:

openapi-generator generate -g typescript-rxjs --enable-post-process-file --additional-properties=supportsES6=true,withInterfaces=false -o src/api/ -i http://localhost:8081/ui/v2/api-docs

is generated into:

```javascript
  /**
   * @type {Date}
   * @memberof Appliance
   */
  licenseStartDate?: Date;
```
and that looks fine, but when I check:

```javascript
if (typeof appliance.licenseStartDate === 'string') {
   console.log('Date is a string');
}

console.log(Object.prototype.toString.call(appliance.licenseStartDate));
```

then it's a string. And a call like:

```javascript
this.appliance.licenseStartDate.toISOString().substr(0, 10)
```

fails. What am I doing wrong? If the generator generates the field as a "Date", shouldn't it then be a date? What do I need to do to fix it?

Thanks in advance!

Sascha

**Comment by macjohnny** [comment]
is this issue about deserializing the backend response or about the request parameters?

**Comment by SaschaAusUlm** [comment]
It's about de-serializing the backend response.
The serialization of the request parameters is generated perfectly as far as I can tell:
```javascript
    const query: HttpQuery = {
      ...(requestParameters.end && { end: (requestParameters.end as any).toISOString() }),
      ...(requestParameters.historyGranularity && { historyGranularity: requestParameters.historyGranularity }),
      ...(requestParameters.start && { start: (requestParameters.start as any).toISOString() }),
      ...(requestParameters.virtualFridgeId && { virtualFridgeId: requestParameters.virtualFridgeId })
    };
```

I put in a method into runtime.ts that goes recursively through the response. If the type of the field is string, it tries to parse into a date and then sets a date into the response.

But I am not sure if that's the correct way? It works as a workaround.

Regards,

Sascha

**Comment by macjohnny** [comment]
there is no deserialization logic in the `typescript-rxjs` generator, therefore the `string` date (e.g. `2019-11-18`) is not converted to `Date`, so the generated model property should be of type `string` instead of `Date`. However, you can override it with a type-mapping.

**Comment by SaschaAusUlm** [comment]
Well, the generated model **is** Date. But there are no Dates in there, just Strings. That's the issue. The discrepancy between what is generated and what happens at runtime ... that's the issue.

**Comment by macjohnny** [comment]
yes, the model is not generated correctly, however, you can override this behavior with a type-mapping.

**Comment by SaschaAusUlm** [comment]
But ... how ...? 
I can change it so that the generator generates string as data type in case of Date. Then it would be "correct" again, but no improvement for me.  Is that what you are talking about?
Or something else?
Do you have a link that explains generating type-mappings, maybe an example?

**Comment by SaschaAusUlm** [comment]
Because when I look at the mustache from runtime ... it gets the response "as it is" and just casts.
But the type-mapping would then need to change how Dates are transported by RXJS, no? Or at least how Dates are returned by RXJS.

**Comment by macjohnny** [comment]
the type-mapping would not do any conversion for you, it would just help you to align the models with the actual object content, see https://openapi-generator.tech/docs/usage#type-mappings-and-import-mappings

however, you could fix this in openapi generator, see https://github.com/OpenAPITools/openapi-generator/issues/4170#issuecomment-543061422

**Comment by macjohnny** [comment]
if you want to have deserialization logic, this could be implemented similar to the `tyepscript-fetch` generator.

**Comment by SaschaAusUlm** [comment]
Thanks, I will take a look.
