### ISSUE TITLE
[BUG] [AsciiDoc] No security section in the generated documentation

### ISSUE THREAD

**Issue by mgwoj** [OpenAPITools/openapi-generator#4460]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example]

##### Description

Documentation generated in AsciiDoc format has no section describing security information.

##### openapi-generator version

2.4.1-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Some API
  version: 0.0.1
paths:
  /v1/api/view/:
    get:
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
```

##### Command line used for generation

generated via gradle plugin

##### Steps to reproduce

No chapter like 

```asciidoc
== Security
```

in the generated `index.adoc`

##### Related issues/PRs

None

##### Suggest a fix

See other mustache templates how `{{authMethods}}` is used.

/CC: @man-at-home

**Comment by wing328** [comment]
@mgwoj thanks for reporting the issue. Do you have to file a PR with better security definitions in the AsciiDoc?

**Comment by mgwoj** [comment]
I think it can be closed as it is included in https://github.com/OpenAPITools/openapi-generator/pull/4505
