### ISSUE TITLE
[Feature][typescript-angular] useSingleRequestParameter missing on typescript-angular generator

### ISSUE THREAD

**Issue by djairhogeuens** [OpenAPITools/openapi-generator#4465]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Compare
https://openapi-generator.tech/docs/generators/typescript-fetch
and
https://openapi-generator.tech/docs/generators/typescript-angular

The Angular generator does not contain the useSingleRequestParameter

##### openapi-generator version

master

##### Suggest a fix

I can try to implement this myself but I will probably need some hints to get started as I am new to this project

**Comment by macjohnny** [comment]
some starting points:
https://github.com/OpenAPITools/openapi-generator/blob/99204ecd66b61df9d97d5b456a8f82d35febc0e1/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L146

https://github.com/OpenAPITools/openapi-generator/blob/99204ecd66b61df9d97d5b456a8f82d35febc0e1/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L84-L85

see also https://github.com/OpenAPITools/openapi-generator/issues/865

**Comment by djairhogeuens** [comment]
@macjohnny I already found the files you mentioned and think I have a complete implementation. I would like to push my branch. Can you make me a contributor please?

**Comment by macjohnny** [comment]
@djairhogeuens you can simply fork the repository and then create a pull-request

**Comment by CaLxCyMru** [comment]
Hi @djairhogeuens, thanks for opening the issue!

I was actually going to be open one myself but regarding the `typescript-axios` generator. 

As part of the work that you aim to do as part of the `typescript-angular` project, are you able to look at the `typescript-axios` project, or perhaps all other `typescript` generators to ensure that they all have support for `useSingleRequestParameter`.

It is also worth noting that there are on-going discussions in #802 to re-write the existing generators.

I am happy to provide assistance on this if needed, let me know what you think! :)

**Comment by djairhogeuens** [comment]
I created a pull request https://github.com/OpenAPITools/openapi-generator/pull/4479

@CaLxCyMru I will not immediately have time. I just came across this at work as we want to start using the generator for our Angular clients and therefore quickly tried to fix it to be able to get started. Furthermore, my knowledge of front-end frameworks is rather limited (I barely know enough about Angular as I'm more specialized in architecture and back-end development :))

**Comment by filipvh** [comment]
Would be great news if this could be merged. It's the only reason i'm not using auto generated APIs... 👍
