### ISSUE TITLE
[REQ] Support incremental builds in gradle plugin

### ISSUE THREAD

**Issue by donaldswartz** [OpenAPITools/openapi-generator#4492]
### Problem

Every time the gradle build runs, it runs the `openApiGenerate` task because it does not know when it is up-to-date. Gradle supports incremental builds via various methods.

## Desired solution

Mark the correct Task Parameters in https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GeneratorsTask.kt using the `@Input`, `@InputFile`, `@OutputDirectory` and other annotations as necessary, so that Gradle knows when all outputs are up-to-date.

More information can be found here: https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:up_to_date_checks #

**Comment by sesamzoo** [comment]
@donaldswartz, `GenerateTask`'s parameters would need to be annotated, so the link should be https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt

**Comment by jimschubert** [comment]
This has been contributed via #6716 and will be included in our 5.0 release.

It required bumping up from our previous minimum Gradle version to support everything fully.
