### ISSUE TITLE
[Core] oneOf schema properties

### ISSUE THREAD

**Issue by lwlee2608** [OpenAPITools/openapi-generator#4515]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
`vars` missing from `model` if they are given `oneOf` rule

##### openapi-generator version
`4.2.2-SNAPSHOT`

##### OpenAPI declaration file content or url

```yaml
    Area:
      type: object
      oneOf:
        - required:
          - tacs
        - required:
          - areaCode
      properties:
        tacs:
          type: array
          items:
            $ref: '#/components/schemas/Tac'
          minItems: 1
        areaCode:
            $ref: '#/components/schemas/AreaCode'
```

##### Steps to reproduce
checkout from [here](https://github.com/lwlee2608/openapi-generator-testbed/tree/oneOf-%234515)
`./run.sh`

The generated code won't compile because `Area` is missing properties `tacs` and `areaCode`

##### Suggest a fix
call `addVars` from `schema.properties` here
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L1939

**Comment by spacether** [comment]
This other pr also attempts to fix this issue

**Comment by lwlee2608** [comment]
@spacether I see, the fix is also identical. And it comes with tests, nice.

**Comment by jimschubert** [comment]
@lwlee2608 can you run your spec through an online validator? `oneOf` should be an array of Schemas, but what you've presented as an example shouldn't be valid. Additionally, `oneOf` technically shouldn't have any additional properties besides `discriminator`, although I've seen this numerous times.

For example, using this spec:

```
openapi: "3.0.1"
info:
   title: title
   version: 0.0.1
paths:
   /:
      get:
         responses:
            '200':
               description: none
               content:
                  application/json:
                     schema:
                        $ref: '#/components/schemas/Area'
components:
   schemas:
      AreaCode:
         title: AreaCode
         type: object
         properties:
            value:
               type: string
      Tac:
         type: object
         properties:
            count:
               type: number
            type:
               type: string
      Area:
         type: object
         oneOf:
         - required:
            - tacs
         - required:
            - areaCode
         properties:
         tacs:
            type: array
            items:
               $ref: '#/components/schemas/Tac'
            minItems: 1
         areaCode:
               $ref: '#/components/schemas/AreaCode'
```

You should see multiple errors in OpenAPI Generator's validation:

```
openapi-generator validate -i ~/Documents/sam.yml --recommend
Validating spec (/Users/jim/Documents/sam.yml)
Errors:
	-attribute components.schemas.Area.properties is not of type `object`
	-attribute components.schemas.Area.areaCode is unexpected
	-attribute components.schemas.Area.tacs is unexpected
Warnings:
	-Unused model: Tac
	-Unused model: AreaCode

[error] Spec has 3 errors.
```

You've ticked the validation TODO item in the description, but my above minimal spec fails validation in the linked validator:

![image](https://user-images.githubusercontent.com/109659/70377685-35f44600-18e5-11ea-8025-3b30edabda95.png)

**Comment by lwlee2608** [comment]
@jimschubert 
I have run the validator before it is valid. The schema file I was using can be found [here](https://raw.githubusercontent.com/lwlee2608/openapi-generator-testbed/oneOf-%234515/api.yaml)

**Comment by lwlee2608** [comment]
full-blown original 3gpp schema file can be found [here](https://www.3gpp.org/ftp/Specs/latest/Rel-15/OpenAPI/TS29571_CommonData.yaml)

**Comment by spacether** [comment]
Should be fixed by https://github.com/OpenAPITools/openapi-generator/pull/4482
