### ISSUE TITLE
[Typescript][Angular] Enhancement: allow filename to be transmitted by using File instead of Blob

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#454]
##### Description

allow filename to be transmitted by using `File` instead of `Blob`
See https://github.com/swagger-api/swagger-codegen/issues/8386

**Comment by macjohnny** [comment]
@albertotn would you like to implement this feature in OpenAPI Generator (a community fork of Swagger Codegen)?

**Comment by albertotn** [comment]
I can but I need some guidance on how and where contribuite exactly

**Comment by albertotn** [comment]
@macjohnny you are right, File extends Blob, but method signature are misleading: a developer could see Blob, and pass the blob, that is without filename.
A method signature with File are more clear, because always carry the filename

**Comment by macjohnny** [comment]
@albertotn I think a developer can easily figure out to pass a `File` object if he wants to pass the filename with it. Since `Blob` is more general and suits all cases, including those that don't need a filename. So since there is no technical necessity to change the signature, I would close this issue.
