### ISSUE TITLE
[BUG] [PHP] no data in container due to `$responseBody->getContents()`

### ISSUE THREAD

**Issue by cjprinse** [OpenAPITools/openapi-generator#4541]
## Bug Report Checklist ##

- :ballot_box_with_check: Have you provided a full/minimal spec to reproduce the issue?
- :ballot_box_with_check: Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- :ballot_box_with_check: What's the version of OpenAPI Generator used?
- :ballot_box_with_check: Have you search for related issues/PRs?
- :ballot_box_with_check: What's the actual output vs expected output?

##### Description #####

The method `GuzzleHttp\Psr7\Stream::getContents` will not reset the stream to position 0.
So, when u are using middleware to intercept the response (eg guzzle profiler), getContents will return a empty value. As a consequence the data in the model container will be empty.pty.

##### openapi-generator version

 v4.2.1

##### OpenAPI declaration file content or url

https://gist.github.com/cjprinse/4c5b5e2f5065fc3c24f0829c7448e640

##### Command line used for generation

```bash
npx openapi-generator generate -g php -o bundles/src/Etrias/Bundles/WarehouseBundle/Connector -i ~/swagger.json --skip-validate-spec --invoker-package=Etrias\\\\Bundles\\\\WarehouseBundle\\\\Connector\\\\lib
```

##### Suggest a fix

Use `GuzzleHttp\Psr7\Stream::__toString` instead of `GuzzleHttp\Psr7\Stream::getContents()`

**Comment by ackintosh** [comment]
@cjprinse Thanks for reporting this issue! I think your suggestion is good. ✨ 

If you want to address this issue, please let me know. I could help you. 😃
