### ISSUE TITLE
[codegen] external $ref in parameters not supported

### ISSUE THREAD

**Issue by tnmtechnologies** [OpenAPITools/openapi-generator#455]
##### Description

When a parameter schema $ref references an external yaml file, code generation fails.

##### openapi-generator version

openapi-generator-cli-3.0.3.jar 

##### OpenAPI declaration file content or url

here is a yaml definition fragment relating to the code generation failure: 
```
  /nf-instances/{nfInstanceID}:
    get:
      summary: Read the profile of a given NF Instance
      operationId: GetNFInstance
      tags:
        - NF Instance ID (Document)
      parameters:
        - name: nfInstanceID
          in: path
          description: Unique ID of the NF Instance
          required: true
          schema:
            $ref: './TS29571_CommonData.yaml#/components/schemas/NfInstanceId'
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NFProfile'
```

##### Command line used for generation

 java  -jar ./openapi-generator-cli-3.0.3.jar generate -i TS29510_Nnrf_NFManagement.yaml -g jaxrs-resteasy -o samples.openapi 

##### Steps to reproduce

Output is as follows when code generation fails:

```
 java  -jar ./openapi-generator-cli-3.0.3.jar generate -i TS29510_Nnrf_NFManagement.yaml -g jaxrs-resteasy -o samples.openapi 
[main] WARN  o.o.c.ignore.CodegenIgnoreProcessor - Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to http://localhost
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to http://localhost
[main] WARN  o.o.codegen.utils.URLPathUtils - 'host' not defined in the spec (2.0). Default to http://localhost
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./TS29571_CommonData.yaml#/components/schemas/NfInstanceId
[main] WARN  o.o.codegen.utils.ModelUtils - Failed to get the schema name: ./TS29571_CommonData.yaml#/components/schemas/NfInstanceId
[main] INFO  o.o.codegen.AbstractGenerator - writing file .....\samples.openapi\src\gen\java\org\openapitools\model\AmfInfo.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file .....\samples.openapi\src\gen\java\org\openapitools\model\AusfInfo.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file .....\samples.openapi\src\gen\java\org\openapitools\model\BsfInfo.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file .....\samples.openapi\src\gen\java\org\openapitools\model\DataSetId.java
[main] INFO  o.o.codegen.AbstractGenerator - writing file .....\samples.openapi\src\gen\java\org\openapitools\model\DefaultNotificationSubscription.java

```

##### Related issues/PRs

#149

**Comment by jmini** [comment]
This should be supported as indicated in #80, can you please publish the content of your `TS29571_CommonData.yaml` file (the necessary extract) so that we have a chance to reproduce this?

**Comment by tnmtechnologies** [comment]
Please find in attachment the yaml files 
[#455-yaml-files.ZIP](https://github.com/OpenAPITools/openapi-generator/files/2163170/455-yaml-files.ZIP)

**Comment by jmini** [comment]
The problem is to be solved in Swagger-Parser. See issue: https://github.com/swagger-api/swagger-parser/issues/749

**Comment by tnmtechnologies** [comment]
Thank you for your analysis.

**Comment by markus-wa** [comment]
My workaround for now:

```
paths:
  /example:
    get:
      operationId: myOp
      parameters:
        - in: query
          name: myParam
          schema:
            $ref: '#/components/schemas/MyParamSchema'

components:
  schemas:
    MyParamSchema:
      allOf:
       - ref: './other.yaml#/MyParamSchema'
```

**Comment by jmini** [comment]
The issue in Swagger-Parser was fixed, and with PR #696 OpenAPI-Generator was updated to use a version containing the fix. 

This issue reported here, should no longer appear with the newest `3.2.0-SNAPSHOT` version.
@markus-wa, @tnmtechnologies, can you check it?

**Comment by markus-wa** [comment]
I think it's fixed for me @jmini.

But unfortunately `2.0.2-OpenAPITools.org-1` breaks the workaround for https://github.com/swagger-api/swagger-parser/issues/764.

**Comment by tnmtechnologies** [comment]
It is fixed for me too (tested with 3.2.0).

**Comment by LBoraz** [comment]
version 4.2.0 of the generator still produces the warning (with no external $ref)

**Comment by markus-wa** [comment]
Might be best to open a new issue @LBoraz - afaik closed ones usually aren't being monitored

**Comment by xvilo** [comment]
@LBoraz did you create a new issue?

**Comment by LBoraz** [comment]
No, i didn't
