### ISSUE TITLE
Is this a bug?

### ISSUE THREAD

**Issue by EFanZh** [OpenAPITools/openapi-generator#4551]
https://github.com/OpenAPITools/openapi-generator/blob/2838db20529de13bb48e73ef58e9c48c9ee9316d/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenModel.java#L120-L122

Is line 121 supposed to be `.append("isNullable", isNullable)`?

**Comment by wing328** [comment]
Yes, I think so. I wonder if you can file a PR with the suggested fix. Thanks.
