### ISSUE TITLE
[BUG] Dart mustache model toJson doesn't handle the situation which the property is object or array

### ISSUE THREAD

**Issue by winterbesos** [OpenAPITools/openapi-generator#4562]
https://github.com/OpenAPITools/openapi-generator/blob/96bbab98a47c702c9b05f7f2bf06f485071dbd23/modules/openapi-generator/src/main/resources/dart2/class.mustache#L86

If there is a property is an object or an array, it dose not handle this situation.

**Comment by mortifactor** [comment]
I ran into this problem too. It seems that it has been fixed in dart-dio part of generator: https://github.com/OpenAPITools/openapi-generator/pull/4401
