### ISSUE TITLE
Unalias schema in getTypeDeclaration when not generating model for alias 

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#4563]
##### Description

Defining a schema for an array type, and referencing it as the items type in another array doesn't generate valid code. It happened for me in Java and go-experimental that I'm using, but might be the case for other languages as well.

https://github.com/OpenAPITools/openapi-generator/pull/4527 fixes the issue for Go and Java. We will need to do it for all other generators.

If anyone wants to help out, please reply to let us know.

##### openapi-generator version

Latest master

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/issues/4362#issue-517130622

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/4527

**Comment by amakhrov** [comment]
@wing328 Looks like there is an attempt to address that - https://github.com/OpenAPITools/openapi-generator/pull/4981

**Comment by wing328** [comment]
Fixed via #4981
