### ISSUE TITLE
[BUG] DefaultCodegen#writeOptional should honor options such as skipOverwrite/codegen ignore

### ISSUE THREAD

**Issue by jimschubert** [OpenAPITools/openapi-generator#4582]
##### Description

Rules for skipping 50-100 files across a handful of generators is not intuitive.

##### openapi-generator version

all

##### Steps to reproduce

* Add any text to `samples/openapi3/client/petstore/ruby/spec/spec_helper.rb`
* Commit a WIP commit
* Run `openapi-generator batch --verbose bin/ci/openapi3-ruby-client-petstore.json`
* Notice no diff because the file is silently skipped due to `writeOptional`
* Run `./bin/openapi3/ruby-client-petstore.sh`
* Notice diff because file is deleted in the bash script via:

```bash
find samples/openapi3/client/petstore/ruby/spec -type d -not -name spec -not -name custom | xargs rm -Rf
find samples/openapi3/client/petstore/ruby/spec -type f -not -name petstore_helper.rb -not -iwholename '*/spec/custom/*' | xargs rm -Rf
```

##### Suggest a fix

Remove support for `writeOptional` in favor of newer methods for controlling writes. If outputs under `samples` require these to be unmodified, they should be added to respective `.openapi-generator-ignore` files.

**Comment by wing328** [comment]
> Remove support for writeOptional in favor of newer methods for controlling writes.

I think we discussed this before. .openapi-generator-ignore can not be used to replace writeOptional since the former won't generate the file at all while the later will generate the file if it's not present.

**Comment by jimschubert** [comment]
@wing328 I think at the very least, we should have an option to modify this behavior. Currently, it doesn't honor skipOverwrite or anything similar. I would personally find it surprising behavior, because we have no way to communicate it to users.

**Comment by jimschubert** [comment]
To expand on my concerns…

Currently the method `writeOptional` will write a file if it doesn't exist, and skip if it does exist.

If I'm a user and I define my ignore file as:

```
*
!**/models/**
```

I'm saying to ignore all files, except anything with a `models` in the package. With `writeOptional`, any generator deciding that a supporting file doesn't exist on the filesystem will write it out even though the user has explicitly requested only a subset of files.

I think the proper usage of `writeOptional` would be "Write if it doesn't exist, and hasn't been excluded for writes by the user".

The `writeOptional` method is somewhat concerning because it puts file writes, which are mostly done in `DefaultGenerator` into codegen types. I don't think we should allow Codegen implementations to write files as that's a slippery slope of confusion, and there are already 82 instances of this usage in Codegen types. I've seen a few comments from users about not being able to block supporting files, and I assume this is the root cause.

My proposal for the fix is to add a "writeOptional" boolean to the SupportingFile, and move the `writeOptional` logic into DefaultGenerator where we can evaluate the ignore processor for those patterns.  If others are cool with this approach, I'll look at getting it one by the 5.0 release.

cc @OpenAPITools/generator-core-team @OpenAPITools/openapi-generator-collaborators

**Comment by jimschubert** [comment]
I noticed that working on #5036 that my previous comments centered around "file writes" when it's actually only conditionally registering in `supportingFiles` (but someone could easily modify DefaultCodegen to delete/write if they wanted). My previous comment about honoring the ignore file isn't relevant because supportingFiles would be processed all in the same way. Since the method is very confusing, I still think it's best to remove it and move any file-related logic into the DefaultGenerator.
