### ISSUE TITLE
[REQ] [Elm] generate list of enum values

### ISSUE THREAD

**Issue by andys8** [OpenAPITools/openapi-generator#4583]
There enum generation results in a tagged union like this:

```elm
type PaymentsPerYear
    = Monthly
    | Quarterly
    | Halfyearly
    | Yearly
```

It would be super nice if there would also be an enumeration in form of a `List` or `Set`. This way it's made sure that the list of values is complete.

```elm
paymentsPerYear = [ Monthly, Quarterly, Halfyearly, Yearly ]
```

This is basically solving a feature the language `Elm` is currently missing and maybe a bit more than what to expect from the generator but it would be super nice :)

**Comment by eriktim** [comment]
Thanks for the suggestion @andys8. I've added this to the major refactoring that's on its way.

**Comment by eriktim** [comment]
This is now part of the upcoming 5.0.0 release.
