### ISSUE TITLE
[BUG][Python] "SyntaxError: more than 255 arguments" when a data type has 255 or more properties

### ISSUE THREAD

**Issue by sebastien-rosset** [OpenAPITools/openapi-generator#4600]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The Python model.mustache template generates a \_\_init\_\_ function. The function arguments are the properties defined in the data type. However, because the OpenAPI spec does not set a max limit for the number of properties in a data type, this means a data type could have a list of 300 properties. But until version 3.7, python functions cannot have more than 255 arguments. 
The generated python code will fail with a syntax error:
```
SyntaxError: more than 255 arguments
```
Note that as a comparison point, Java also has a limit of 255 function arguments, but the generated Java class does not exhibit a similar problem. The Java constructor is not generated with a long list of arguments.

##### openapi-generator version

4.2.1

##### OpenAPI declaration file content or url

I don't think a OAS content sample is needed. It's obvious from the mustache template that the generated __init__ function could have more than 255 arguments:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/model.mustache#L60

##### Steps to reproduce

1) Create a OpenAPI spec with a data type that has 255 or more properties (possibly from "inherited" classes using allOf
2) Run the Python code generator. In the generated model file, the \_\_init\_\_ method will have more than 255 arguments.
3) Try to execute the SDK using Python 3.6 or earlier. The python interpreter will report a syntax err. With python 3.7 and above, the python interpreter will execute without error.

##### Suggest a fix

One workaround is to use Python 3.7 or above. However, several Linux distributions do not support 3.7 yet, so it may be operationally complex to require SDK users to install Python 3.7.
Another workaround is to ensure that OAS data types should not have more than 254 arguments, which is a good idea anyway. The first argument of \_\_init\_\_ is "self", hence 254. This could be documented in the wiki. Having caveats in the wiki would be helpful.
A fix would be to remove the arguments from the \_\_init\_\_ function, but this will break backward compatibility.

**Comment by sebastien-rosset** [comment]
@spacether , do you have a recommendation to address this issue for Python?  I see several OAS code generators (Java, cpp, go, swift, dart...) don't have this limitation because they don't create functions with a long list of arguments. One exception is the Erlang code generator does create a list of arguments, and Erlang has a max limit of 256 arguments per function.
Of course, I would argue an OAS data type should not have 256 properties in the first place, but sometimes you have to work with an existing OAS spec.

Since mustache is logic-less, it's not possible to have "if len({{vars}}) > 254" in the template.

Options:
1) Remove all arguments from the generated constructor. This will break any existing client that sets properties through the constructor.
2) Create {{isVarsCountGt250}} and {{isAllVarsCountGt250}} tags (or something equivalent). 
  In the mustache template, when isVarsCountGt250 is false, generate the constructor as before. If isVarsCountGt250 is true, then generate a constructor without arguments, and the client must set the variables after creating the object.
3) Any other option?

**Comment by spacether** [comment]
@sebastien-rosset 
Sorry, I didn't see this before I am first seeing it now.
The most robust way to handle this in python is to switch our inputs to models to use:
- positional arguments *args
- named arguments **kwargs
The python-experimental generator already uses named arguments to pass in optional parameters here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_init_properties.mustache#L1
If we also use positional arguments we can collapse down the required arguments.

Some pseudocode:
```
# old style
def __init__(required_one, required_two, optional_one, optional_two):
     self.required_one = required_one
     self.required_two = required_two
     self.optional_one = optional_one
     self.optional_two = optional_two

# new style
def __init__(*args, **kwargs):
     # it may be difficult to assign indices using  mustache info, maybe it already exists in our vars data
     self.required_one = args[0]
     self.required_two = args[1]
     for key, value in kwargsi.tems():
          setattr(self, key, value)
```
Important note:
Python lets us pass positional arguments in named argments so we can still use:
a = Instance(required_one=1, required_two=2, optional_one=3, optional_two=4)
Also, this solution is general and would work if we have a big or small model.

**Comment by sebastien-rosset** [comment]
> The python-experimental generator already uses named arguments to pass in optional parameters here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/model_templates/methods_init_properties.mustache#L1

Sounds good. How about if we apply the same "python-experimental" technique to the \_\_init\_\_ function in the "python" mustache template? This will make it backward compatible and support more than 255 arguments. I can do that.

**Comment by spacether** [comment]
@sebastien-rosset that sounds great!
So this would be for kwargs only right?
It probably makes sense for an *args update to be left as future work.

**Comment by spacether** [comment]
@sebastien-rosset can I close this issue because it is working in python-experimental
Or do you want this to apply only to the python generator?
