### ISSUE TITLE
[BUG][PHP] Unable to generate working client based on API-Platform OAS3 definition

### ISSUE THREAD

**Issue by pascal-splotches** [OpenAPITools/openapi-generator#4636]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

With an API generated with [API-Platform](https://api-platform.com/) I am unable to generate a working API client. Based on the API you build within API platform it automatically generates a JSON-LD API with an OpenAPI definition file.

The API endpoints do not seem to be able to parse, load and handle the JSON-LD fields in the response, as fields like `@id`, `@context` and `@type` remain empty on individual items. On collections fields like `hydra:member`, `hydra:totalItems` etc. also do not seem to be parsed and I end up with an empty collection.

I don't expect my use-case to be a rare one. Perhaps I'm doing something wrong, but so far have been unable to determine what? Any advice would be welcomed.

##### openapi-generator version

`4.2.1` - _not a regression_

##### OpenAPI declaration file content or url

https://gist.github.com/pascal-splotches/60efb27ff3946dfffd0ac745d4203a27

##### Command line used for generation

```bash
export PHP_POST_PROCESS_FILE="prettier --parser php --write"
openapi-generator generate \
    --input-spec "https://gist.githubusercontent.com/pascal-splotches/60efb27ff3946dfffd0ac745d4203a27/raw/7e0a85028d49a1076548f8b6dc5ee3dce2801493/openapi.definition.json" \
    --generator-name php \
    --api-package Api \
    --model-package Model \
    --invoker-package "Example\Api"
    --additional-properties "sortParamsByRequiredFlag=true,ensureUniqueParams=true,allowUnicodeIdentifiers=true,variableNamingConvention=camelCase" \
    --enable-post-process-file
```
##### Steps to reproduce

When generating the API, the following error gets thrown when not using the `--skip-validate-spec` flag:
```bash
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors:
	-attribute components.schemas.Schema name Example:jsonld-Read doesn't adhere to regular expression ^[a-zA-Z0-9\.\-_]+$

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:470)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:497)
	at org.openapitools.codegen.cmd.Generate.run(Generate.java:415)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

When using the `--skip-validate-spec` flag the client does generate, but it does not work completely.

When setting up the endpoint and calling the collection method:
```php
print_r($exampleApi->getExampleCollection());
```

it outputs the following empty object:
```
(
    [container:protected] => Array
        (
            [hydramember] =>
            [hydratotalItems] =>
            [hydraview] =>
            [hydrasearch] =>
        )

)
```

Whereas I would expect the `hydramember` to be filled with the `Example` models and the `hydratotalItems` to be filled with the total amount of items in the collection.

When setting up the endpoint and calling the item method:
```php
print_r($exampleApi->getExampleItem(4));
```

it outputs the following object:
```
(
    [container:protected] => Array
        (
            [context] =>
            [id] =>
            [type] =>
            [name] => Example
        )

)
```

This leads me to conclude that the generated API client for some reason does not know how to handle the JSON-LD related fields.

##### Related issues/PRs

Not that I have found

**Comment by jorissteyn** [comment]
If your models are hydrated without JSON-LD specific fields, this means your API did not send a JSON-LD response.

Digging into the issue I found the culprit in `HeaderSelector`. The client objects use `HeaderSelector` to format the `Accept` header:

```php
$headers = $this->headerSelector->selectHeaders(
    ['application/ld+json', 'application/json', 'text/html'],
    []
);
```

But the selector simply ignores `application/ld+json` if a `application/json` is present:

```php
} elseif (preg_grep("/application\/json/i", $accept)) {
    return 'application/json';
} else {
```

This behaviour is wrong, I believe the `Accept` header should contain all content types as listed in the client object, in that specific order of preference. I can't think of any use case solved by having that `preg_grep` clause there.
