### ISSUE TITLE
[BUG] typescript-node mixes require and import

### ISSUE THREAD

**Issue by DanielRuf** [OpenAPITools/openapi-generator#4656]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When running `openapi-generator generate -i https://petstore3.swagger.io/api/v3/openapi.json -g typescript-node -o out -c config.json`

with the config.json file:
```json
{
    "npmName": "@swagger/typescript-fetch-petstore",
    "npmVersion": "1.0.0",
    "npmRepository": "https://skimdb.npmjs.com/registry",
    "snapshot": false,
    "supportsES6": true
}
```

it generates the following code which is not valid esm code:

```js
import localVarRequest = require('request');
import http = require('http');
```

##### openapi-generator version

`4.2.0`

**Comment by macjohnny** [comment]
@DanielRuf would you like to implement a fix?

**Comment by laubfall** [comment]
Just for your information: i ran into the same problem and fixed this issue in https://github.com/laubfall/openapi-generator/tree/typescript-node_mixes_require_and_import_4656 . PR is on its way.

**Comment by laubfall** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/6947
