### ISSUE TITLE
[BUG] malformed inline yaml string for nodejs-express-server with petstore3

### ISSUE THREAD

**Issue by DanielRuf** [OpenAPITools/openapi-generator#4657]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When generating a server using the `nodejs-express-server`generator and the petstore v3 we get `error: Malformed inline YAML string ("This is a sample Pet Store Server based on the OpenAPI 3.0 specification.\`

`openapi-generator generate -i https://petstore3.swagger.io/api/v3/openapi.json -g nodejs-express-server -o server -c config.json`

##### openapi-generator version

4.0.2

##### Command line used for generation

`openapi-generator generate -i https://petstore3.swagger.io/api/v3/openapi.json -g nodejs-express-server -o server -c config.json`

**Comment by DanielRuf** [comment]
Removing a few lines of the multiline string fixes this.

**Comment by DanielRuf** [comment]
Changing the multiline string to a singleline string fixes this.

**Comment by markphilipp** [comment]
+1 for this
