### ISSUE TITLE
[BUG][Java] Generated code fails compilation; using wrong object for generated model

### ISSUE THREAD

**Issue by tobymurray** [OpenAPITools/openapi-generator#4673]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] Bounty to sponsor the fix ([$50.00 USD](https://www.bountysource.com/issues/84779902-bug-java-generated-code-fails-compilation-using-wrong-object-for-generated-model))

##### Description
The generated code does not compile because the model's field is declared as the expected type but initialized to be a `HashMap`

Example stacktrace (lightly massaged, so not totally verbatim with e.g. file paths): https://gist.github.com/tobymurray/2986f1d98419e47e7067c44710ea9158

##### openapi-generator version
Have tried with 4.2.1 and 4.2.2, 4.2.3, 4.3.0, 4.3.1, and 5.0.0-beta; all fail similarly. This appears to be a regression from 3.3.3, I believe it was introduced in the 4.0 release.

##### OpenAPI declaration file content or url
https://gist.github.com/tobymurray/c9733c7e1ca3bac292eb906838949d2c

##### Command line used for generation

`java -jar openapi-generator-cli-4.2.2.jar generate -g java -o test-dir -i bug-reproduction.yaml`

##### Steps to reproduce

1. Execute the above command line against the linked YAML
2. invoke `gradlew assemble` (note you may have to `chmod a+x` the gradle wrapper)

Expected:
The code will be valid and compile successfully

Actual:
The code fails to compile:
Example stacktrace (lightly massaged, so not totally verbatim with e.g. file paths): https://gist.github.com/tobymurray/2986f1d98419e47e7067c44710ea9158

##### Suggest a fix

I'm not sure why the OpenAPI Generator is considering this specific model to be a `HashMap` when it knows the declaration is a (in this case) `ObjectMap`, I imagine the fix would be to find where that assignment is taking place and ensure it respects the type. Interestingly, both the `data` builder method and the `setData` method use the correct type.

**Comment by tobymurray** [comment]
It looks like I'm having exactly the same problems with the server (specifically `jaxrs-cxf-extended`) models, e.g.:
`private StringMap customProperties = new HashMap<>();' <= these two types are not compatible

**Comment by toby-murray-snow-software** [comment]
I've just posted a 50$ CAD bounty on this: https://www.bountysource.com/issues/84779902-bug-java-generated-code-fails-compilation-using-wrong-object-for-generated-model

**Comment by wing328** [comment]
I tested with the latest master but couldn't repeat the issue with https://gist.githubusercontent.com/tobymurray/c9733c7e1ca3bac292eb906838949d2c/raw/4d61a8fbb23c9637493c09259285fe329501991b/api.yaml

Can you please test with the latest master to see if it works for you?

**Comment by tobymurray** [comment]
I just tried this out on `master` () and was unable to reproduce this issue. The current head of `master` produces an `org.openapitools.client.model.ObjectMap` with no corresponding HashMap (which is where it broke previously) e.g.:
```
  private ObjectMap data;


  public GetResponse data(ObjectMap data) {
    
    this.data = data;
    return this;
  }
```

**Comment by wing328** [comment]
```
definitions:
  ObjectMap:
    type: object
    required:
      - default
    properties:
      default:
        type: string
    additionalProperties:
      type: object
```
For `ObjectMap` defined above, openapi-generator generates a Java class `ObjectMap`, which extends `HashMap<String, Object>`:
```java
/**
 * ObjectMap
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-09-02T23:55:15.475+08:00[Asia/Hong_Kong]")
public class ObjectMap extends HashMap<String, Object> {
  public static final String SERIALIZED_NAME_DEFAULT = "default";
  @SerializedName(SERIALIZED_NAME_DEFAULT)
  private String _default;
```

It seems to me openapi-genreator is doing the right thing. 

What's your expected output?

**Comment by toby-murray-snow-software** [comment]
I agree with you, maybe poorly worded on my part. I was unable to reproduce this issue on the head of `master`, meaning this bug has been fixed and I did not encounter it in my test.

I mentioned the `ObjectMap` and `HashMap` as that's the functional change I observed. The broken behavior that existed previously tried to do `ObjectMap whatever = new HashMap()`, the current (non-broken) behavior avoids using `HashMap`.

**Comment by wing328** [comment]
Ah ok :)

**Comment by wing328** [comment]
Please donate the bounty to https://opencollective.com/openapi_generator when you've time. Thank you.

**Comment by toby-murray-snow-software** [comment]
@wing328 - do you have any advice on how to practically do that? Its my first time using Bountysource, how do I direct the funds from that bounty to the Opencollective?

**Comment by toby-murray-snow-software** [comment]
@wing328 - so far as I can tell, once a bounty is created on Bountysource it may not be modified. Are you able to claim the bounty? Otherwise it seems likes it in limbo (can't be claimed, as the bug is fixed, can't be cancelled).

**Comment by wing328** [comment]
>  so far as I can tell, once a bounty is created on Bountysource it may not be modified

@toby-murray-snow-software I think there should be a way you can cancel it. You may need to contact their CS to do it for you.
