### ISSUE TITLE
[BUG][NODEJS-EXPRESS-SERVER] Body data will not be processed.

### ISSUE THREAD

**Issue by cjuenger** [OpenAPITools/openapi-generator#4679]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
The generated server stub does not handle data (defined as schema in OpenAPI 3.0) transferred in the body HTTP.
The generated code uses the name of the schema (here: bodyData) as the name of the input parameter of the generated service method (here: static addDataPerBody({bodyData}).

That is the issue, the controller parses all data in the body of a HTTP request into 'requestParams.body' which won't work for destructuring the assignment to '{bodyData}'.
 
See 'Suggest a fix' below for a possible fix.

##### openapi-generator version
Version 4.2.2

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Titel
  description: Some description 
  version: 0.0.0.0
servers:
  - url: /some/uri
paths:
  
  /groups:
    post:
      operationId: addDataPerBody
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BodyData'
        required: true
      responses:
        '200':
          description: Id of added data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataId'
    
components:
  schemas:    
    BodyData:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        info:
          type: string
        created:
          type: string
        changed:
          type: string
      required:
        - name
    DataId:
      type: object
      properties:
        id:
          type: integer
          description: ID of the group.

```

##### Command line used for generation

openapi-generator generate -g nodejs-express-server -i .\FILE.yaml -o .\TARGET\DIR 

##### Suggest a fix

Every service function parameter simply needs to be identified by 'body' and aliased by the schema name.

For example: Change '**_static addDataPerBody({bodyData})_**' to  '**_static addDataPerBody({'body': bodyData})_**'

**Comment by wing328** [comment]
cc @YishTish

**Comment by Armageddonas** [comment]
Hey guys, any progress with this?

**Comment by rdecarreau** [comment]
version: openapi generator 4.3.1

I believe this is related to my issue, I am trying to use Reusable Request Bodies as in the example here: https://swagger.io/docs/specification/describing-request-body/
(copied here for specificity)
```paths:
  /pets:
    post:
      summary: Add a new pet
      requestBody:
        $ref: '#/components/requestBodies/PetBody'
  /pets/{petId}
    put:
      summary: Update a pet
      parameters: [ ... ]
      requestBody:
        $ref: '#/components/requestBodies/PetBody'
components:
  requestBodies:
    PetBody:
      description: A JSON object containing pet information
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Pet'
```

My request gets a 500 server error in response. Some debugging puts the problem in the Controller.js's collectRequestParams() function. The code is destructuring a 'content' element which is not present.
https://github.com/OpenAPITools/openapi-generator/blob/4e352cb28261b68fe87adbd64db77565a4ffcd90/modules/openapi-generator/src/main/resources/nodejs-express-server/controllers/Controller.mustache#L88

**Comment by Armageddonas** [comment]
@rdecarreau Yes the bug is in the controller. You can bypass it by not using destructuring in the for the arguments in the controller. This doesn't work for the post requests.

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/6041 has been merged. Please give it another try with the latest master.
