### ISSUE TITLE
[BUG] Ruby models order in inheritance case

### ISSUE THREAD

**Issue by gigaga** [OpenAPITools/openapi-generator#4690]
##### Description

By generating a ruby client, the models order defined in `openapi_client.rb` is incorrect in case where there is some inheritance.

##### openapi-generator version

```bash
$ openapi-generator version
4.2.2
```

##### OpenAPI declaration file content or url

petstore.yaml

```yaml
openapi: 3.0.0
info:
  version: 1.0.0-SNAPSHOT
  title: petstore
  description: |
    This is the specification of Petstore with the following resources:

    - Pet
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      tags:
        - pets
      responses:
        "200":
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: object
                description: 1.0.0
                required:
                  - pet_type
                properties:
                  pet_type:
                    type: string
                discriminator:
                  propertyName: pet_type
                  mapping:
                    dog: "#/components/schemas/Dog"
                    cat: "#/components/schemas/Cat"
                    lizard: "#/components/schemas/Lizard"
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
        startDate:
          type: string
          example: "2019-11-08"
        num:
          type: integer
          example: 1
      discriminator:
        propertyName: pet_type
        mapping:
          dog: "#/components/schemas/Dog"
          cat: "#/components/schemas/Cat"
          lizard: "#/components/schemas/Lizard"
    Dog:
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            bark:
              type: string
    Cat:
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            name:
              type: string
    Lizard:
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            lovesRocks:
              type: boolean

```

##### Command line used for generation

```bash
openapi-generator generate --generator-name ruby -i petstore.yaml
```

##### Steps to reproduce

1. After generating, build gem `gem build openapi_client.gemspec`
1. Install it `gem install openapi_client-1.0.0.gem`
1. Use it in your ruby code in `test.py` file for example: `require 'openapi_client'
1. Execute it `ruby test.py`

The following error has occured: `uninitialized constant OpenapiClient::Pet (NameError)`

The problem is due to `openapi_client.rb` file where `Cat`, `Dogs` and `Lizard` modules are loaded before `Pet`.

##### Suggest a fix

Rather to generate the model list from alphabetic order, generate it in the same order of OpenAPI specs file.

**Comment by EranAvidor** [comment]
👍 experiencing the same issue.

**Comment by EranAvidor** [comment]
Update:
I patched the generated code with a script and turns out that the generated ruby classes are broken as well.
Downgraded to plugin version [v4.1.1](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.1.1) and the generated client is working. It also required me to downgrade `gradle`.
The bug was introduced in [v4.1.2](https://github.com/OpenAPITools/openapi-generator/releases/tag/v4.1.2).

**Comment by davinchia** [comment]
@EranAvidor I'm still seeing this incorrect import order with v4.1.1 in the generated Ruby client. Cat is a child class of Pet. We are using the `allOf` swagger annotation.
```
require 'test_api_client/models/Cat'
require 'test_api_client/models/Pet'
```

We had to downgrade to `3.3.4` to fix this. In `3.3.4` the generated classes did not inherit from any base class, all fields are directly attached on the class itself. Got it working temporarily. We might try to implement your suggestion as a patch.

**Comment by ColeMurray** [comment]
Bumping as this is still an issue in 5.1.0

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/9103 to fix it. Please review when you guys have time.
