### ISSUE TITLE
openapi-generator batch could not find api.yaml

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#4717]
##### Description

I have to folder:
- `/Users/martin/dev/test/src` containing:
  - `petstore.yaml`
  - `config.yaml`
  - a `generated` folder where the code should be generated
- `/Users/martin/dev/test/build` where the code is generated from (`pwd`)

When generating the client from the `build` folder with the `batch` command, the `petstore.yaml` file is not found.

##### openapi-generator version

4.2.2

##### OpenAPI declaration file content or url

The `petstore.yaml` from [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore_oas3_test.yaml).

```yaml
# config.yaml
inputSpec: petstore.yaml
generatorName: cpp-qt5-client
outputDir: generated
```

##### Command line used for generation

```
cd /Users/martin/dev/test/build
$ openapi-generator batch /Users/martin/dev/test/src/config.yaml --root-dir /Users/martin/dev/test/src
```

##### Steps to reproduce

Just run the command line and see the error:

```
[main] INFO  o.o.codegen.cmd.GenerateBatch - Batch generation using up to 16 threads.
Includes: /Users/martin/dev/test/src
Root: /Users/martin/dev/test/src
[pool-1-thread-1] ERROR i.s.parser.SwaggerCompatConverter - failed to read resource listing
java.lang.RuntimeException: Could not find petstore.yaml on the classpath
	at io.swagger.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:207)
```

##### Related issues/PRs

Not that I know.

##### Suggest a fix/enhancement

ping @jimschubert

**Comment by jimschubert** [comment]
@MartinDelille where does `api.yaml` exist in your structure? I only see `petstore.yaml`.

**Comment by MartinDelille** [comment]
@jimschubert Sorry my example was not very clear because I did it with my own `api.yaml` file. I rewrote the issue with `petstore.yaml` file.

Hope it make more sense now!
