### ISSUE TITLE
[jaxrs-jersey] Generated method doesn't use model

### ISSUE THREAD

**Issue by PowerOfCreation** [OpenAPITools/openapi-generator#472]
##### Description

I have generated a jaxrs-jersey server with two models:
```yaml
components:
  schemas:
    TimeseriesEntry:
      type: object
      properties:
        ts:
          type: integer
          format: int64
        value:
          type: number
          format: double
        tagList:
          type: array
          items:
            type: string
      xml:
        name: TimeseriesEntry
    TimeseriesData:
      type: array
      items:
        $ref: '#/components/schemas/TimeseriesEntry'
      xml:
        name: TimeseriesData
```
When I use the TimeseriesData model as a parameter, then the generated code has a `List<TimeseriesEntry>` instead of a TimeseriesData in it. This is problematic, because our code works with TimeseriesData and not with `List<TimeseriesEntry>`.

##### openapi-generator version

3.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  description: Timeseries API
  version: 1.0.0
  title: Timeseries REST-API
  termsOfService: ''
  contact:
    email: unassigned@scads.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://localhost:8080/v1.0
paths:
  '/timeseries/{id}/data':
    parameters:
        - name: id
          in: path
          description: ID of the timeseries whose data should be retrieved
          required: true
          schema:
            type: string
    put:
      tags:
        - timeseries
      summary: Sets data of timeseries identified by ID
      operationId: setDataByID
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/TimeseriesData'
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid status value
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
  schemas:
    TimeseriesEntry:
      type: object
      properties:
        ts:
          type: integer
          format: int64
        value:
          type: number
          format: double
        tagList:
          type: array
          items:
            type: string
      xml:
        name: TimeseriesEntry
    TimeseriesData:
      type: array
      items:
        $ref: '#/components/schemas/TimeseriesEntry'
      xml:
        name: TimeseriesData
```
##### Command line used for generation

CMake:
COMMAND ${Java_JAVA_EXECUTABLE} -jar ${SWAGGER_CODEGEN_JAR} generate -i ${SWAGGER_API_DEF} -g jaxrs-jersey -o "${SERVER_API_FOLDER}" -c "${SWAGGER_GENERATOR_CONFIG}"
And the online editor.

##### Steps to reproduce

Generate a server using the provided .yaml file. Then open TimeseriesApiService and check what parameter the method setDataByID uses. It should be TimeseriesData, but is `List<TimeseriesEntry>`.

##### Related issues/PRs

Didn't found anything related.

##### Suggest a fix/enhancement

When this is how it is supposed to be, then I couldn't find any note in https://swagger.io/docs/specification/components/ and because of that I suppose it is a bug and needs to be fixed -> the TimeseriesData model gets used instead of `List<TimeseriesEntry>`.

**Comment by jmini** [comment]
I do not remember exactly why and I could not find any direct discussion of this topic, but I think that it was decided for now to not create a type for "array of items". If I remember it correctly Swagger-Codegen `2.x` generate a class like this:

```java
public class TimeseriesData extends ArrayList<TimeseriesEntry> {
   //...
}
```

Maybe someone else will remember why this decision was taken.

**Comment by PowerOfCreation** [comment]
I need to verify when I'm back at work, but I'm pretty sure this model got created exactly like that in Open API 3.0 as well, but it won't be used by the operations.

**Comment by PowerOfCreation** [comment]
Can confirm OpenAPI 3.0.0 generates a model MetaData, but it doesn't get used.
```Java
public class MetaData extends ArrayList<MetaEntry>  {

}
```

**Comment by jmini** [comment]
Quick update :

The way it is now is preferred: `List<TimeseriesEntry>`

If you use the aliased form (`TimeseriesData`), you can not other java constructs like `Arrays.asList(..)`:
```java
List<TimeseriesEntry> list = Arrays.asList(new TimeseriesEntry("abc", 18, 30), new TimeseriesEntry("yxz", 64, 54));
```
Or streams + collectors:
```
input.stream().map(Item::toTimeseriesEntry).collect(Collectors.toList());
```

But in order for you to have a smooth transition, we will introduce an option to use the aliased form (`TimeseriesData` in you example).

What do you think?

**Comment by wing328** [comment]
UPDATE: we've added the option `generateAliasAsModel` (default: false) to cater differente use cases.
