### ISSUE TITLE
[REQ] outputs field causing the error when parsing fails

### ISSUE THREAD

**Issue by jbtrystram** [OpenAPITools/openapi-generator#4736]
### Is your feature request related to a problem? Please describe.

I am trying your tool to generates documentation from an apenAPI spec YAML file. I have given a go to the tools, and it fails with : 
`xception in thread "main" java.lang.NullPointerException: element cannot be mapped to a null key` which appears to be an error in my spec file. 
However my spec file is fine with the swaggerUI visualisation tool, and I don't know what I need to adjust.

## Describe the solution you'd like

I would like to know what line in my openAPI file causes this error, that would help me in the debugging process.. Because right now I have no idea what is causing the issue. It could be #4681 as I have AllOf fields, but i am not sure.

**Comment by AIexG** [comment]
If you have an inline object inside an `allOf`, try to break the object into its own schema and use a `$ref` instead. You can also provide a minimal example specification, which should help narrowing the issue down.

**Comment by jbtrystram** [comment]
I solved the issue of allOf  by using the branch of @rasmusfaber  (https://github.com/rasmusfaber/openapi-generator/commit/ad64c9d28e67e3264de1ca4953c68d0e22c645d1 ) . But my point was that it was not easy to find that my issue was the inline object. 
But I  had other instances where the parser does output the line it is not happy with, so I suppose what i want is already implemented :) 
I'll close this
