### ISSUE TITLE
[BUG][Maven] importMappings not working

### ISSUE THREAD

**Issue by luStopai** [OpenAPITools/openapi-generator#4745]
Hi

maven plugin is not working as expected when trying to use an already existing class.

Here (https://openapi-generator.tech/docs/usage#target-external-models) are the instructions to generate code using a existing class.

It works when using openapi-generator client. When I execute this
```
openapi-generator generate \
    -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml \
    -g java \
    -o out \
    --language-specific-primitives=Pet \
    --import-mappings=Pet=com.yourpackage.models.Pet
```
Then Pet.java, as expected, does not exist in src/main/java/org/openapitools/client/model/

But when doing the same with maven plugin   
```
<plugin>
        <groupId>org.openapitools</groupId>
        <artifactId>openapi-generator-maven-plugin</artifactId>
        <version>4.2.2</version>
        <executions>
                <execution>
                        <goals>
                                <goal>generate</goal>
                        </goals>
                        <configuration>
                                <inputSpec>https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml</inputSpec>
                                <generatorName>java</generatorName>
                                <configOptions>
                                    <languageSpecificPrimitives>Pet</languageSpecificPrimitives>
                                    <importMappings>Pet=com.yourpackage.models.Pet</importMappings>
                                </configOptions>
                        </configuration>
                </execution>
        </executions>
</plugin>
```

Then Pet.java does exist in src/main/java/org/openapitools/client/model/ but it shouldn't

openapi-generator-maven-plugin 4.2.2
openapi-generator-cli 4.2.1

**Comment by daniilmatafonov** [comment]
Helllo, guys! When you will be able to fix it?

**Comment by uortiz** [comment]
This is working fine for me. 
openapi-generator-maven-plugin plugin version: 4.2.3
<generatorName>java</generatorName>

Try adding the mapping as a child of <configuration> 

e.g.,
```
<configuration>
   <importMappings>Pet=com.yourpackage.models.Pet</importMappings>
</configuration>
```

As stated in https://github.com/OpenAPITools/openapi-generator/issues/3868

```Import-Mappings is now direct part of configuration node and not inside configOptions node anymore```

Looking at org.openapitools.codegen.plugin.CodeGenMojo, it does have code to support "import-mappings" (as opposed to importMappings) inside configOptions

Line 622
```
// Retained for backwards-compataibility with configOptions -> import-mappings
                if (importMappings == null && configOptions.containsKey("import-mappings")) {
                    applyImportMappingsKvp(configOptions.get("import-mappings").toString(),
                            configurator);
                }
```

But importMappings is being initialized to an empty list, therefore the above backwards-compataibility code will not work.

**Comment by luStopai** [comment]
Many thanks @uortiz, that was pretty hidden

I wonder if it's possible to make this change clear in the documentation or to show some kind of warning when generating sources.

Also, I don't really get this "backwards-compatibility" if it won't work. I think it's preferable to show an error instead of not complaining at all but also do nothing, it's confusing.

Anyways, thanks again

**Comment by JuanMorenoDeveloper** [comment]
Hi guys! 
I have the same problem with the 5.0.0 version, I wrote the details here. https://stackoverflow.com/questions/65954112/openapi-generator-maven-plugin-generated-bigdecimal-properties-without-the-prope

**Comment by JuanMorenoDeveloper** [comment]
Related issue https://github.com/OpenAPITools/openapi-generator/issues/8803
