### ISSUE TITLE
[BUG][kotlin][client] missing implementation of allowRequiredAsNullable

### ISSUE THREAD

**Issue by 4brunu** [OpenAPITools/openapi-generator#4746]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

In https://github.com/OpenAPITools/openapi-generator/pull/4696 was introduced support for OpenApi 3.0 nullable required fields.
There is a flag `allowRequiredAsNullable` that was introduced to control this feature, but it's not working.
https://github.com/OpenAPITools/openapi-generator/blob/42f685f59c2f3803865c0c0c1680a5f57a774327/bin/openapi3/kotlin-client-petstore-nullable-required.sh#L29

##### openapi-generator version

4.2.2

##### Suggest a fix

Implement the flag to enable or disable this feature.

**Comment by Mordag** [comment]
@4brunu I implemented this feature for the kotlin client. Did I miss something? I am happy to fix any bugs related to this feature.

**Comment by 4brunu** [comment]
@Mordag No It works ok, the problem was that this change changed a lot of things in my project, but after a better look at it, I think the previous generated code was wrong.
Thanks for the contribution by the way 👍
