### ISSUE TITLE
[BUG] "petstore" hardcoded in tox.ini template

### ISSUE THREAD

**Issue by lk-jeffpeck** [OpenAPITools/openapi-generator#4766]
See here:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/tox.mustache#L19

**Comment by wing328** [comment]
Thanks for reporting the issue. I've filed #4776 to fix it.

**Comment by wing328** [comment]
PR merged. Please try again with the latest master.
