### ISSUE TITLE
[BUG] The Kotlin client with basic authentication doesn't compile

### ISSUE THREAD

**Issue by coder82** [OpenAPITools/openapi-generator#4771]
##### Description

I simply generate the kotlin client with basic authentication specified in the yaml file and what is generated does not compile due to a missing import.

##### openapi-generator version

4.2.2

##### OpenAPI declaration file content or url
This is an extract of the yaml:
```yaml
security:
  - basicAuth: []

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
```
(for YAML code) or
```json
<all default>
```

##### Command line used for generation

I am using the gradle generator:
```
task buildKotlinClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "kotlin"
    inputSpec = "$resourceDir/test.yaml"
    configFile = "$rootDir/kotlin-client-api-config.json"
    outputDir = "$srcDir/test/kotlin"
    generateModelTests = false
    generateModelDocumentation = false
    generateApiTests = false
    generateApiDocumentation = false
}
```

##### Steps to reproduce

Generate the kotlin client from petstore default yaml, just change the authentication to basic, and you will find this error during compilation:

``` Unresolved reference: Credentials ```

##### Suggest a fix

This change has been added recently so I think it was not tested.
I think this is just a combination which was not tried, you need to add the import:

`import okhttp3.Credentials`

**Comment by facundomedica** [comment]
+1
