### ISSUE TITLE
[REQ] Option to not generate go.mod and go.sum

### ISSUE THREAD

**Issue by iddan** [OpenAPITools/openapi-generator#4773]
### Is your feature request related to a problem? Please describe.

Currently, the generated go client library always includes go.mod and go.sum files.

## Describe the solution you'd like

I would like to have an option in the configuration file to not generate go.mod and go.sum files.

## Describe alternatives you've considered

Currently, to overcome the issue I remove the generated files after the code generation ends

## Additional context

I am working on [adding a code-generated client package to Cayley](https://github.com/cayleygraph/cayley/pull/896). For it to work correctly the generated client directory must not include go.mod and go.sum

**Comment by wing328** [comment]
What about using .openapi-generator-ignore to skip files you don't want in the code generation process?

**Comment by iddan** [comment]
That would do, even though I'm not sure how to do that. But I think there should be an explicit option for this as it has semantic meaning.
