### ISSUE TITLE
[REQ] Add a markdown generator

### ISSUE THREAD

**Issue by alexander-matthiesen** [OpenAPITools/openapi-generator#4778]
### Is your feature request related to a problem? Please describe.

Currently we are trying to convert our OpenAPI-Specification into a markdown format that we can use this generated markdown in mkdocs.

## Describe the solution you'd like

I would like to have a generator that converts oas2 and oas3 files to .md files

## Describe alternatives you've considered

I tried swagger2md or even converting the oas2 file to a wiki book and from that to markdown, but nothing was satisfying.

## Additional context

I've seen that there is a html-markdown script in this repository, but I couldn't get it running. Some help would be nice.

**Comment by jimschubert** [comment]
The `html-markdown` generator outputs HTML with the CommonMark documentation support required by OpenAPI Specification. In other words, your description text can contain Markdown, and that sample script demonstrates that it will result in valid HTML.

That said, most of our generators output Markdown docs. I think it makes a lot of sense to have something standalone.

We do have an asciidoc generator. As a temporary workaround, I believe you could also pass that output through pandoc for Markdown.

**Comment by alexander-matthiesen** [comment]
Hey Jim, thanks for the fast reply and the additional information. Unfortunately the asciidoc didn't work for me as I tried. 
Currently I'm trying to implement the example from here https://openapi-generator.tech/docs/new-generator because that is a markdown-generator but we didn't have one implemented. 
Would be nice if someone who already has implemented a generator could take a look at that.

**Comment by jimschubert** [comment]
@alexander-matthiesen I wrote the document you've linked. What exactly did you need looked at? I'd be happy to look into it.

When I'd created the document, I think there was a comment that we didn't need a standalone generator because our generators all support markdown. I think rather than require users to figure out exclusions and customization, that it makes sense to have a standalone to complement HTML and Asciidoc.

**Comment by alexander-matthiesen** [comment]
Ah great! First let me say that is is very well written and it has brought me to my goal. 
For now I have implemented my own oas to markdown generator with that "tutorial". It would be a little easier when a markdown-generator is already there. The customization could still be done over the template_dir but the whole pull and build process if something changes isn't that great for a software-development-team. 
Based on that I would suggest to add a very minimal implementation of your tutorial to the openapi-generator so guys like me didn't have to implement it themselves.

**Comment by jimschubert** [comment]
Thanks for the clarification. This is how I understood the original request, but I was confused by the question to review. I thought maybe there was a missing pull request or something.

**Comment by jimschubert** [comment]
Added a new generator via #4811.
