### ISSUE TITLE
[BUG] [Golang] Bug make the http Body readable again

### ISSUE THREAD

**Issue by Tsovak** [OpenAPITools/openapi-generator#4799]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
For Golang need to make HTTPResponse.Body readable again 

Now after generating code, the generator read the Http Body one and closed it. After that user cannot read the Body again out the generated client. I suggest making the Body readable again. 

##### openapi-generator version
4.2.3

##### Suggest a fix
Need to change in the templates `localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)`
to 
```
	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
```

**Comment by nmische** [comment]
I just ran into this issue yesterday and was planning to submit a similar bug report. Is there a PR open to address this issue?

**Comment by Tsovak** [comment]
@nmische  I searched the existed PR but could not find it. I tried to open PR but I didn't have access. So we need to wait for the OpenAPI Team.

**Comment by wing328** [comment]
Thanks for the fix by @nmische 

@Tsovak please pull the latest master or snapshot version to give it a try.
