### ISSUE TITLE
[BUG][Java][Spring] multiple files upload

### ISSUE THREAD

**Issue by purple-dragon** [OpenAPITools/openapi-generator#4803]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
use open api spec 3 to define api to upload multiple files, but openapi generator 
generate incorrect, following openapi spec

https://swagger.io/specification/#mediaTypeObject
section: "To upload multiple files, a multipart media type MUST be used:"
![image](https://user-images.githubusercontent.com/3256085/70910887-9dc83080-204b-11ea-90d5-81e42139ac6b.png)

```
default ResponseEntity<Document> createDocument(@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile file,@ApiParam(value = "") @RequestParam(value="metadata", required=false)  Object metadata)
```

```
should be array: MultipartFile[] file

default ResponseEntity<Document> createDocument(@ApiParam(value = "file detail") @Valid @RequestPart("file") MultipartFile[] file,@ApiParam(value = "") @RequestParam(value="metadata", required=false)  Object metadata)
```

##### openapi-generator version
        <dependency>
            <groupId>org.openapitools</groupId>
            <artifactId>openapi-generator</artifactId>
            <version>4.2.2</version>
        </dependency>

##### OpenAPI declaration file content or url
```
openapi: "3.0.2"
info:
  version: "1.0.0"
  title: "File Management API"
  description: >-
    File Management

paths:
  /api/v1/documents:
    post:
      tags:
        - Manage Files
      summary: "Upload new file"
      operationId: "createDocument"
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                metadata:
                  type: object
      responses:
        201:
          description: "Document created, return generated document information"
        404:
          description: "Not Found"
        409:
          description: "Conflict"
        500:
          description: "Internal Server Error"
```

##### Related issues/PRs
looks like there are similar issues, not sure if it fixed or not.

https://github.com/OpenAPITools/openapi-generator/issues/2210
https://github.com/ga4gh/workflow-execution-service-schemas/issues/43

**Comment by surajgautam** [comment]
How did you fix it? I am also facing the same issue. :(

**Comment by purple-dragon** [comment]
@surajgautam  no solution for now :(

**Comment by surajgautam** [comment]
Hi there,

I managed to generate MultipartFile[] files by using:

content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files[]:
                  type: array
                  items:
                    type: string
                    format: binary

**Comment by ericdariel** [comment]
Hello,

I have the same problem, impossible to generate a MultipartFile[] in Spring Boot with openapi-generator 4.2.2

Anyone knows how to do in Open API v3 ?

**Comment by purple-dragon** [comment]
@ericdariel  pls check @surajgautam commets

**Comment by jorgerod** [comment]
Hello,

I have the same problem. Java client not work for me.

[I used the previously defined file](https://github.com/OpenAPITools/openapi-generator/issues/4803#issue-538424793)

```java
    public ResponseEntity<Void> createDocumentWithHttpInfo(List<File> file, Object metadata) throws RestClientException {
        Object postBody = null;
        
        String path = apiClient.expandPath("/api/v1/documents", Collections.<String, Object>emptyMap());

        final MultiValueMap<String, String> queryParams = new LinkedMultiValueMap<String, String>();
        final HttpHeaders headerParams = new HttpHeaders();
        final MultiValueMap<String, String> cookieParams = new LinkedMultiValueMap<String, String>();
        final MultiValueMap formParams = new LinkedMultiValueMap();

        if (file != null)
             //Not compile. FileSystemResource constructor wait a File, not a List<File>
            formParams.put("file", new FileSystemResource(file));
        if (metadata != null)
            formParams.add("metadata", metadata);

        final String[] accepts = { };
        final List<MediaType> accept = apiClient.selectHeaderAccept(accepts);
        final String[] contentTypes = { 
            "multipart/form-data"
        };
        final MediaType contentType = apiClient.selectHeaderContentType(contentTypes);

        String[] authNames = new String[] {  };

        ParameterizedTypeReference<Void> returnType = new ParameterizedTypeReference<Void>() {};
        return apiClient.invokeAPI(path, HttpMethod.POST, queryParams, postBody, headerParams, cookieParams, formParams, accept, contentType, authNames, returnType);
    }

```

**Comment by jorgerod** [comment]
@wing328 I want to try to do a PR to solve the problem. Which version would I go for? 4.3.x? 5.x?

**Comment by dvdvdmt** [comment]
How can I solve the same problem with multiple files upload for `typescript-axios` generator?
I tried `@openapitools/openapi-generator-cli@cli-5.0.0-beta` on this scheme:
```yml
...
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              required:
                - files
              properties:
                files:
                  type: array
                  items: { type: string, format: binary }
              type: object
...
```
It don't take into account the array of files and generates this code:
```ts
     const localVarFormParams = new FormData();

      if (files) {
        localVarFormParams.append('files', files.join(COLLECTION_FORMATS.csv));
      }
```
It would be great if it produce something like:
```ts
     const localVarFormParams = new FormData();

      if (files) {
        files.forEach((file) => {
          localVarFormParams.append('files[]', file)
        });
      }
```

Or maybe I'm doing something wrong?

**Comment by tobiashochguertel** [comment]
This issue isn't yet solved @wing328 it's still not working for the Spring generator.

```yaml
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
```

![grafik](https://github.com/OpenAPITools/openapi-generator/assets/3332669/70128e46-dac3-4a90-8c96-22a83434f73c)

**Comment by afjord** [comment]
@tobiashochguertel In my case this problem disappeared when I removed `delegatePattern` option.
