### ISSUE TITLE
[REQ] [donet-core] Support for dotnet core 3.1

### ISSUE THREAD

**Issue by hpollak** [OpenAPITools/openapi-generator#4818]
It leads not in a unresolveable Problem to use csharp-netcore to generate client-code for .netcore 2.x but Dotnet-core 3.1 has LTS. You can port the generated code to 3.1 but 3.1 should supported by the generator.
I generated the Code from kubernetes.json - Swagger-File. 

It works after a view corrections, but there are a lot of warnings (CS0472) caused by the null-checks, the functions use types i.e. bool and not bool? so its per definition not possible to be null ( this checks can be removed )

the project files contains allso the targetframework in the PropertyGroup of the SDK. Can be changed to <TargetFramework>netcoreapp3.1</TargetFramework>

So it would be nice to have a generation-option for netcoreapp3.1.

**Comment by wing328** [comment]
@hpollak we definitely welcome contributions to support dotnet core 3.1. May I know if you've time to contribute the enhancement?

cc @mandrean (2017/08), @jimschubert (2017/09), @frankyjuang (2019/09)

**Comment by hpollak** [comment]
@wing328 I will try to find time for contribution
