### ISSUE TITLE
[BUG] Python Generated Code is always parsing responses as json even if the response type is string

### ISSUE THREAD

**Issue by tkinz27** [OpenAPITools/openapi-generator#4822]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

In the generated kubernetes client, responses that are strings are being loaded as json and then stringified resulting in a return value that is not correct. 

See https://github.com/kubernetes-client/python/issues/1032#issuecomment-566746272 for full details.

**Comment by tkinz27** [comment]
Sorry i know this is not the most complete bug rep

**Comment by spacether** [comment]
Multiple response content types are deserializable in the `python-experimental` generator
One can see them here: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/api_client.py#L936
And they include:
- 'application/octet-stream'
- json
- 'multipart/form-data'
