### ISSUE TITLE
[BUG][aspnetcore] Documentation : operationModifier can't be partial

### ISSUE THREAD

**Issue by tmakin** [OpenAPITools/openapi-generator#4829]
##### Description
Very minor issue.

The help text for `aspnetcore` generator suggests that the `operationModifier` option can be partial. This is not possible in c# and is not implemented in the generator (it's just the help text that is wrong)
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AspNetCoreServerCodegen.java#L73

##### openapi-generator version
4.2.2

##### Steps to reproduce
Using CLI:
```
> openapi-generator config-help -g aspnetcore

...
 operationModifier
            Operation Modifier can be virtual, abstract or partial (Default: virtual)
...
```

##### Suggest a fix
Update help text as follows:
```private CliOption operationModifier = new CliOption(OPERATION_MODIFIER, "Operation Modifier can be virtual or abstract");```

**Comment by wing328** [comment]
Thanks for the fix by @Sshnyari 

@tmakin please pull the latest master or snapshot version to give it a try.
