### ISSUE TITLE
[REQ] Allow JavaJaxRsSpec Generator to generate asynchronous APIs

### ISSUE THREAD

**Issue by prodanov** [OpenAPITools/openapi-generator#4832]
### Is your feature request related to a problem? Please describe.

I'm using the model generation and API generation of the JaxRsSpec generator and I like it a lot as it gives me a lot of freedom in implementing the server. Quite Specific I'm using it with Quarkus and in order to have asynchronous routes in quarkus you API has to return CompletionStage<SomeResponseType>. CompletionStage is a class from the JDK. A simplified example could look like:

`import java.util.concurrent.CompletionStage;

interface FruitApi {
  CompletionStage<Fruit> getFruit();
}`

It would be ok to have an "async" flag in the config that will generate those types of APIs. Maybe with some other options like in the spring generator.

**Comment by prodanov** [comment]
Actually I have a fix locally that is pretty simple. With a bit more effort I can prepare a PR.

**Comment by rquinio** [comment]
+1 

JAX-RS 2.1 introduced async returned types for server-side.
These same return types could also be leveraged client-side via microprofile-rest-client (cf https://github.com/quarkusio/quarkus/issues/6540)

A dedicated flag would avoid polluting people not interested by asynchronous APIs.

**Comment by hermes85pl** [comment]
Can this eventually happen? So much time has passed, and we're still where we were. The issue wasn't event tagged with the referred language or anything.

@prodanov, are you still willing to prepare a PR to make this issue more likely to proceed?

**Comment by prodanov** [comment]
There were some more corner cases that I encountered back in the days and that's why I did not submit the PR. Currently is out of my focus to be honest.

**Comment by prodanov** [comment]
We can close the issue if you like

**Comment by tbredzin** [comment]
Hey @prodanov, I had the same need so I created PR https://github.com/OpenAPITools/openapi-generator/pull/10919, do you think it covers the corner cases that you mentioned ?
