### ISSUE TITLE
[BUG][Go] respect initialisms or acronyms in names

### ISSUE THREAD

**Issue by jirikuncar** [OpenAPITools/openapi-generator#4833]
#### Description

Names in generated Go clients do not respect recommended [style](https://github.com/golang/go/wiki/CodeReviewComments#initialisms).

```
Url -> URL
Id -> ID
Http -> HTTP
```

##### openapi-generator version

all

##### Related issues/PRs

https://github.com/golang/go/wiki/CodeReviewComments#initialisms

##### Suggest a fix

Override `GoExperimentalCodegen.toParamName` method.

**Comment by wing328** [comment]
There were discussions on this before. I think the best way is to provide an option allowing users to provide a mapping (e.g. HTTP => Http) on special words that need to be handled differently.
