### ISSUE TITLE
[REQ] Possible to generate a client directly from server resource endpoint?

### ISSUE THREAD

**Issue by ktalebian** [OpenAPITools/openapi-generator#4836]
I'm adding a SwaggerBundle to my dropwizard application and it adds a `/openapi.{json|yaml}` endpoint and generates the OpenAPI spec from using the `io.swagger.v3.oas.annotation` annotations that I have.

Is it possible to use this endpoint as the input spec path instead of a file? Alternatively, is there a maven generator to generate the OpenAPI spec file from the resource endpoint that I can then pipe into this generator?

**Comment by wing328** [comment]
Nope, it's not possible. OpenAPI Generator only takes a JSON/YAML file (OpenAPI spec/doc) as the input
