### ISSUE TITLE
[BUG] [AsciiDoc] Add option to not generate metadata

### ISSUE THREAD

**Issue by mgwoj** [OpenAPITools/openapi-generator#4848]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example]

##### Description

Documentation generated in AsciiDoc has metadata information at the begining of the file. This is causing problems if the generated file is included into some bigger documentation, as those metadata are copied "as-is", which pollutes the final documentation.
It would be great to add the option if we want this metadata to be generated or not (default is true).

##### openapi-generator version

2.4.1-SNAPSHOT

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Command line used for generation

generated via gradle plugin

##### Steps to reproduce

Currently generated file looks like 
```
= My App API 
team@example.com
1.0.0
:toc: left
:numbered:
:toclevels: 3
:source-highlighter: highlightjs
:keywords: openapi, rest, My App API 
:specDir: 
:snippetDir: 
:generator-template: v1 2019-11-19
:info-url: https://openapi-generator.tech
:app-name: My App API

[abstract]
...
```
It would be good to not generate lines starting with `:`, like this

```
= My App API 

[abstract]
...
```

##### Related issues/PRs

None

##### Suggest a fix

Not known at this moment.

/CC: @man-at-home

**Comment by man-at-home** [comment]
I think this could be useful. At the moment I integrate the output into an orchid site, but including into other markup would be another option.

In the meantime, you could reach the same effect with a customized template (/openapi-generator/src/main/resources/asciidoc-documentation/index.mustache), removing unwanted markup there, but I will look into it.

**Comment by mgwoj** [comment]
Thank you @man-at-home for super fast fix. It works very well.
