### ISSUE TITLE
[BUG][kotlin][client] Request date converter wrong default behaviour

### ISSUE THREAD

**Issue by 4brunu** [OpenAPITools/openapi-generator#4867]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Until recently the Kotlin client generator until recently was using the LocalDate or LocalDateTime `toString` method.
This works ok in some cases but it's inconsistent, let me explain why.
The Kotlin client has a serialiser (Moshi or Gson) and that serialiser is responsible for parsing the data received from the server to objects and convert the objects to data to send to the server.
The serialiser is configurable, and let's the user decide which format should be used.
The problem is that when the method toString is used, the format configured in the serialiser is ignored.

This is even worst, because, if you send a post object to the server that has dates, the dates will use the format defined in the serialiser.
If you send a get request, the dates will use the toString, ignoring the format.
So depending on how the request is made, the date format changes.

Recently, the PR https://github.com/OpenAPITools/openapi-generator/pull/4750 was merged, which improved the situation.
Now the user can specify that the format defined in the serializer should always be used.
The problem is that this option it's not on by default.
By default the toString method will be used.

##### openapi-generator version

4.2.2

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/4750

##### Suggest a fix

I have two different solution to fix this issue:
- make the toJson option the default one, and keep the toString option;
- make the toJson option the only option, since the toString option is wrong.

I'm not sure which of the following options is better, because I think that the option toString is wrong, misleading and I can't find a good use case to it, only for backward compatible/legacy reasons, but I think it's a bug.

**Comment by Mordag** [comment]
@4brunu I've worked on this PR. The reason for keeping "toString" was to avoid breaking code. Before the toString method was always used. It is true that the toString is indeed the incorrect behaviour, but I would say offering the choice between the old and new way is much better.

**Comment by 4brunu** [comment]
@Mordag First of all thanks for your PR 😃 
I think you are right, we should keep the toString option to give a choice to the users.
But I think the toJson should be the default option, because it's the correct behaviour, and if someone needs the old behaviour they can enable it.
What do you think?

**Comment by Mordag** [comment]
Yeah that sounds good. :+1:

**Comment by Mordag** [comment]
@4brunu I think this issue can be closed, or?

**Comment by 4brunu** [comment]
@Mordag you are right, thanks for reminding me 🙂
