### ISSUE TITLE
[Dart][BUG] Dart Generation does not work correctly unless all files are generated

### ISSUE THREAD

**Issue by dalewking** [OpenAPITools/openapi-generator#4878]
### Is your feature request related to a problem? Please describe.

Related to #3828. Due to the way "part" is used in apilib.moustache you cannot filter out generated apis, models, or support files because each is referred to with a part statement even if they are not generated.

## Describe the solution you'd like

That part statements are not generated if the particular file is excluded from generation.

**Comment by kuhnroyal** [comment]
I assume you used the `.openapi-ignore` file.
You can use https://openapi-generator.tech/docs/customization/#selective-generation to achieve this.

There are recent PRs which also address the selective generation.
https://github.com/OpenAPITools/openapi-generator/pull/8339
https://github.com/OpenAPITools/openapi-generator/pull/8388
