### ISSUE TITLE
[BUG][DART] Method listFromJson isn't defined on array of enums 

### ISSUE THREAD

**Issue by selankon** [OpenAPITools/openapi-generator#4887]
### Description

When I define inside an object a property that is an array of enums, the generated code call a method `listFromJson` that is not defined inside the enum model causing build problems.

##### openapi-generator version

```bash
➜ openapi-generator version
4.2.2
```
##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
    title: RetroShare OpenApi wrapper
    version: 0.0.1
    description: RetroShare OpenApi wrapper generated using Doxygen documentation
    license:
        name: AGPLv3
servers:
    - url: http://127.0.0.1:9092/
    
paths:
    /jsonApiServer/version:
        post:
            summary: blahblah             
            responses:
                '200':
                    description: >
                            return: 
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/FileChunksInfo'

components:      
    schemas:
        FileChunksInfo:
            type: object
            properties:
                chunks:
                    type: array
                    items:
                        $ref: '#/components/schemas/ChunkState'
        ChunkState:
            type: integer
            enum:
                
                    - 0
                    - 1
                    - 2
                    - 3
            x-enum-varnames:
                
                    - CHUNK_OUTSTANDING
                    - CHUNK_ACTIVE
                    - CHUNK_DONE
                    - CHUNK_CHECKING
```

##### Command line used for generation

```bash
➜ openapi-generator generate -i definition.yml -g dart -o openapi-dart-retroshare-api-wrapper
```

##### Steps to reproduce

Just copy the .yml definition and run the command. 

After the code is generated be sure that all the dependencies are installed. I us VSCodium with Dart extension for that. 

Once all installed you will see a build error on lib/model/file_chunks_info.dart.

```dart
  FileChunksInfo.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    chunks = (json['chunks'] == null) ?
      null :
      ChunkState.listFromJson(json['chunks']);
  }
```

Where `listFromJson` is not defined on `ChunkState` model.

##### Related issues/PRs

Maybe related to https://github.com/OpenAPITools/openapi-generator/issues/2567

##### Suggest a fix

Should the nums have the method `listFromJson`?

**Comment by kuhnroyal** [comment]
Also running into this.

**Comment by selankon** [comment]
The method that is not implemented and is implemented on other models should be like:

```dart
static List<ChunkState> listFromJson(List<dynamic> json) {
    return json == null ? List<ChunkState>() : json.map((value) => ChunkState.fromJson(value)).toList();
  }
```

I'm not sure why this is not implemented, but looking at the mustache files [dart/class.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/class.mustache) I found: 

```dart
  static List<{{classname}}> listFromJson(List<dynamic> json) {
    return json == null ? new List<{{classname}}>() : json.map((value) => new {{classname}}.fromJson(value)).toList();
  }
```

So maybe we need only to add this code on [dart/enum.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/enum.mustache) ? Something like [that](https://github.com/selankon/openapi-generator/commit/a4efeef20bf0fb13260b273c1e0b8a65d399b5c0?diff=unified) (i'm not able to do the checklist to make a PR right now...)

**Comment by selankon** [comment]
I created the PR but modifying the template inside `dart2` folder.

**Comment by tuomohopia** [comment]
I keep hitting this myself too. Any good ways to solve this?

**Comment by selankon** [comment]
Please merge my PR (is not merged on master yet)
https://github.com/OpenAPITools/openapi-generator/pull/5355

**Comment by wing328** [comment]
@selankon thanks for the fix, which has been merged into the master.

Have a nice weekend.

**Comment by ollyde** [comment]
Also have this issue, seems it's still not updated from 2020? Anyway to fix it? 😢
