### ISSUE TITLE
[typescript-node][BUG] create getter/setter for `defaultHeaders` property

### ISSUE THREAD

**Issue by AProts** [OpenAPITools/openapi-generator#4894]
**Steps to reproduce**
1. generate apiclient for typescript-node
2. check `defaultHeaders` property in apiclient class: it's not possible to get or set it

 version of OpenAPI Generator used: Master (4.2.3-SNAPSHOT)

**Actual output**
protected defaultHeaders : any = {};
let localVarHeaderParams: any = (<any>Object).assign({}, this.defaultHeaders);

**Expected output**
protected _defaultHeaders : any = {};
set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }
get defaultHeaders() {
        return this._defaultHeaders;
    }
let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);

#### Bug Report Checklist

- [+] Have you provided a full/minimal spec to reproduce the issue?
- [+] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [+] What's the version of OpenAPI Generator used?
- [+] Have you search for related issues/PRs?
- [+] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

**Comment by macjohnny** [comment]
fixed by https://github.com/OpenAPITools/openapi-generator/pull/4896
