### ISSUE TITLE
[Go] Generate XML struct annotations

### ISSUE THREAD

**Issue by siddharthist** [OpenAPITools/openapi-generator#490]
##### Description

When generating Go code, one gets types tagged with JSON: 
```go
type Foo struct {
	Str string `json:"Str,omitempty"`
}
```
This is awesome for JSON APIs. However, OpenAPI also allows for `application/xml` content-types! I am writing an XML API and currently have to manually go in and tag these types.

##### openapi-generator version

The Docker CLI generator.

##### Command line used for generation
```
sudo docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
       -i /local/swagger.yml \
       -g go \
       -o /local/generated/client
```

##### Steps to reproduce
Write any `swagger.yml` and generate Go code

##### Suggest a fix/enhancement
Automatically annotate all structs with both XML and JSON names, to start. [The tags are space separated](https://golang.org/pkg/reflect/#StructTag).

**Comment by siddharthist** [comment]
Is this done with ` -D withXml=true`? It's hard to figure out the command line options when the software crashes when called with `--help`.

**Comment by grokify** [comment]
Yes, `-D withXml=true` will produced the XML struct tags. You can use it with other flags like `-D packageName=petstore,withXml=true`.

**Comment by grokify** [comment]
> It's hard to figure out the command line options when the software crashes when called with `--help`.

Well noted. I updated the error message here: https://github.com/OpenAPITools/openapi-generator/pull/494

**Comment by siddharthist** [comment]
@grokify Thanks for the quick response! I must be putting this option in the wrong place, because I'm still not seeing any XML tags. Does this look right?
```
sudo docker run --rm -v ${PWD}:/local \
     openapitools/openapi-generator-cli generate \
     -i /local/swagger.yml \
     -g go \
     -D withXML=true \
     -o /local/generated/client

sudo docker run --rm -v ${PWD}:/local \
     openapitools/openapi-generator-cli generate \
     -i /local/swagger.yml \
     -g go \
     -D withXML=true \
     -o /local/generated/server
```

**Comment by siddharthist** [comment]
Ah, I see that I was writing `withXML` instead of `withXml`. Perhaps an error should be thrown on unknown key-value arguments as well.
