### ISSUE TITLE
[REQ] [C#] Add a CancellationToken to overloads

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#4905]
When generating C# from an API's specifications, can we have overloads added that will allow us to pass in a cancellation token?  This way the caller can cancel the request if needed without waiting for whatever the timeout value is.

Below looks like a similar request for a different generator:

https://github.com/OpenAPITools/openapi-generator/issues/3383

**Comment by Lomkex1** [comment]
This would be very useful
