### ISSUE TITLE
[BUG][JAVA] Unable to compile newly added generator code

### ISSUE THREAD

**Issue by godrose** [OpenAPITools/openapi-generator#4909]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### openapi-generator version

Version: 4.2.3

##### Steps to repro
Follow the steps outlined at https://openapi-generator.tech/docs/customization.html

Run 'Use the new generator' step with the following command
java -cp out/generators/my-codegen/target/my-codegen-openapi-generator-1.0.0.jar:modules/openapi-generator-cli/target/openapi-generator-cli.jar org.openapitools.codegen.OpenAPIGenerator

Expected: It works
Actual: It doesn't. The error is the following: 
Error: Could not find or load main class org.openapitools.codegen.OpenAPIGenerator

**Comment by ElRochito** [comment]
I've got same problem following steps at https://openapi-generator.tech/docs/customization

**Comment by ElRochito** [comment]
Founded the problem!!!
@godrose you have to swap paths of jar

`java -cp out/generators/my-codegen/target/my-codegen-openapi-generator-1.0.0.jar:modules/openapi-generator-cli/target/openapi-generator-cli.jar org.openapitools.codegen.OpenAPIGenerator`

becomes
`java -cp modules/openapi-generator-cli/target/openapi-generator-cli.jar:out/generators/my-codegen/target/my-codegen-openapi-generator-1.0.0.jar org.openapitools.codegen.OpenAPIGenerator`

**Comment by krishtekula** [comment]
@ElRochito 
I got the same prblem, but swapping paths doesn't resolve it. How did it work for you ?

**Comment by krishtekula** [comment]
Don't swap the paths, but quotes around and jars separated by semicolon worked for me.

java -cp "out/generators/my-codegen/target/my-codegen-openapi-generator-1.0.0.jar;modules/openapi-generator-cli/target/openapi-generator-cli.jar" org.openapitools.codegen.OpenAPIGenerator

**Comment by jimschubert** [comment]
Thanks for bumping this issue.

Sorry for the delay in clarifying the docs more. I hadn't seen the original report or the first two comments.
