### ISSUE TITLE
[REQ] Remove support for unsupported Python versions

### ISSUE THREAD

**Issue by rafmagns-skepa-dreag** [OpenAPITools/openapi-generator#4933]
## Request
This is unrelated to any issues I've encountered. 

As Python 2.7 hit EOL last week, are there plans to remove support for Python 2.7 (as well as any lingering support for Python 3.x < 3.5) since it is no longer maintained?

[Handy chart of which Python versions are being supported](https://python-release-cycle.glitch.me)

It would help clean up a bit of the code and remove `six` as a dependency.

Unrelated question - is there a style guide for the Python templates?

## Ideal Solution
Support for Python < 3.5 is dropped (at least for the main Python generator) by updating the Python templates. I'm happy to help with this.

**Comment by spacether** [comment]
I am open to keeping or removing older python versions.
It is unclear to me what % of our users are suing older or unsupported versions of python.
Core Team:
@wing328 (2015/07) 
@jimschubert (2016/05) 
@cbornet (2016/05)
@ackintosh (2018/02) 
@jmini (2018/04) 
@etherealjoy (2019/06)
Do we have any records of this?
Do the companies/projects using openapi generator tell us which generator they are using and what version of the language they are using?
Can our users comment in this thread on what version of Python they use?

**Comment by spacether** [comment]
It doesn't look like we have a specific python style guide that we use.
For reference we run flake8 as part of our test suite in py27 and python3:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/python/test_python2.sh#L26

**Comment by wing328** [comment]
> Do we have any records of this?

Nope generally we don't but as you probably aware there's a PR to add support for Python 2.6.

> Do the companies/projects using openapi generator tell us which generator they are using and what version of the language they are using?

We've not received any private feedback from companies to support a particular EOL programming language (e.g. PHP 4.x)

> It doesn't look like we have a specific python style guide that we use.

https://github.com/OpenAPITools/openapi-generator/blob/master/CONTRIBUTING.md#style-guide

We can make an announcement to set a particular date/version to remove Python 2.x support from all Python client/server generators and see if there's any objection from the community.

To me, 2019 June/July (6 months from now) is a reasonable time to make the breaking changes and users can alays use old stable releases if they need Python 2.x support.

**Comment by bukowa** [comment]
Any updates?

**Comment by spacether** [comment]
Python-experimental has been updated to support python >= 3 only in https://github.com/OpenAPITools/openapi-generator/pull/7061

**Comment by johnthagen** [comment]
I just wanted to comment that having type hints in the generated Python code would be a huge productivity boost.

**Comment by spacether** [comment]
This was resolved by https://github.com/OpenAPITools/openapi-generator/pull/8042
