### ISSUE TITLE
[BUG] [TYPESCRIPT] Array model of alias to array model is missing inner type argument

### ISSUE THREAD

**Issue by bodograumann** [OpenAPITools/openapi-generator#4968]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When defining a data scheme, which has a property that contains an array of another data scheme, which is an alias of an array, the resulting property definition is `Array<Array>`, i.e. the inner generic has no type parameter.

##### openapi-generator version

I have tested this with master.

##### OpenAPI declaration file content or url

Example declaration gist: https://gist.github.com/bodograumann/0ec60e9b2b6d8824fba49fa74c2f88a9

##### Command line used for generation

```sh
java -jar ~/Programme/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i array-of-array-alias.openapi.yaml -g typescript-node -o src
```

##### Steps to reproduce

Generate the code with the `typescript-node`, `typescript-inversify` or `typescript-axios` template.
Then run `tsc --noEmit` to typecheck the generated code. The following error will be produced:
```
src/models/Zoo.ts:15:26 - error TS2314: Generic type 'Array<T>' requires 1 type argument(s).

15     'enclosures'?: Array<Array>;
```
Instead of `Array<Array>`, the type should be `Array<Array<string>>`. Indeed, if instead of the reference to `Enclosure`, the inner array is included directly in the outer array's items-definition, the correct type is generated. The linked gist contains a second api definition, which demonstrates that fact.

It also does not work with the new typescript template from https://github.com/OpenAPITools/openapi-generator/issues/802

##### Related issues/PRs

I have not found any related issues.

In https://github.com/OpenAPITools/openapi-generator/pull/4569 there was some talk about removing `isAlias`. If that would be done, I guess that would probably impact this issue as well.

##### Suggest a fix

Seems like the whole alias handling seems to be volatile and complicated. Maybe defaulting to using the literal name and then optionally inlining would improve the situation? Not sure what the plans for aliases are.

**Comment by bodograumann** [comment]
The code generation seems to also work properly with the java `spring` template.

I have traced the source of the wrong type declaration to the codegen's `getTypeDeclaration` method, specifically the `ModelUtils.isArrayScheme` case.
Compare typescript and java:
https://github.com/OpenAPITools/openapi-generator/blob/4627c7d5343e97635ce5cfaffb1f8140348b0adc/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java#L316-L319
https://github.com/OpenAPITools/openapi-generator/blob/4627c7d5343e97635ce5cfaffb1f8140348b0adc/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L713-L715

The differences are the calls to `getSchemaItems` and `ModelUtils.unaliasSchema` in java. The former only adds some error catching, but the latter is the crux of the problem.
A quick check confirms that adding the call to `ModelUtils.unaliasSchema` fixes the problem in the typescript templates. Note that there are several subclasses for the various typescript variants which reimplement the `getTypeDeclaration` method and contain the same error.

I think I should be able to cook up a pull request. Guess for #802 a separate one needs to be created as it only exist in its own branch.

**Comment by amakhrov** [comment]
@bodograumann this looks related to https://github.com/OpenAPITools/openapi-generator/issues/4563 . Is it so, or is it a separate issue that only manifests itself in Typescript generators?

**Comment by bodograumann** [comment]
@amakhrov You are correct, that this seems to be the same issue. Not sure which other languages are affected though. php maybe, but there the types are only annotations in comments.
The issue should not affect languages without types, like javascript.
