### ISSUE TITLE
[BUG] php-slim4-server tests are failing in CI

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#4994]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

php-slim4-server tests are failing in CI
An example of it is here: https://travis-ci.org/OpenAPITools/openapi-generator/builds/636572707?utm_source=github_status&utm_medium=notification

##### Suggest a fix

It looks like we need to change the version of the slim-token-authentication library that we are using

**Comment by ybelenko** [comment]
Fixed via #4995
