### ISSUE TITLE
[Spring-java] required readonly attribute generate not null field

### ISSUE THREAD

**Issue by esoni88** [OpenAPITools/openapi-generator#5026]
Hi All,
regard required, readOnly and writeOnly open api specification report:

If a readOnly or writeOnly property is included in the required list, required affects just the relevant scope – responses only or requests only. That is, read-only required properties apply to responses only, and write-only required properties – to requests only.

so if i declare a field required and read-only means that in the request that field should be empty.

example with this yam:

    Poll:
      title: Poll
      type: object
      description: A poll is an election, or a survey of people's opinions to ask inside the platform
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
          description: Unique Identifier of a Poll
-------
openapigenerator generate the class with id not null

  @JsonProperty("id")
  private Long id;

  @NotNull
    public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

What happen if i run my code and  i perform a post with an empty id ? Spring raise bad request but it is not correct.  For openapi specification  read-only required properties apply to responses only and not for the request.
I think that openapi generator should generate @NotNull only for writeOnly property

**Comment by tty0482** [comment]
Hi,

I've encountered this same problem. The fix is simple, just change the beanValidation.mustache template slightly - I will attach a pull request in a minute. However, it seems to me that it is likely not only the Spring generator that suffers from this problem, but every Java generator that uses bean validation:

```
$ find modules/openapi-generator/src/ -name "beanValidation.mustache" -exec grep -l @NotNull {} \;
modules/openapi-generator/src/main/resources/Java/beanValidation.mustache
modules/openapi-generator/src/main/resources/Java/libraries/microprofile/beanValidation.mustache
modules/openapi-generator/src/main/resources/java-pkmst/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-cdi/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/cxf-ext/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/eap/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaJaxRS/spec/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaPlayFramework/beanValidation.mustache
modules/openapi-generator/src/main/resources/JavaSpring/beanValidation.mustache
```

I didn't look at these files in detail, but it seems likely that all or at least many of these files should receive the same or a similiar fix.

**Comment by laDanz** [comment]
Pretty similar to #9654
