### ISSUE TITLE
[REQ] Put the enum values in multiple lines to avoid using E501

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#5030]
### Is your feature request related to a problem? Please describe.

For https://github.com/OpenAPITools/openapi-generator/pull/5019#discussion_r368043780

> We are tying to minimize the usage of flake8 E501 and other flake8 opt out lines.

**Comment by spacether** [comment]
It would also be nice to remove any other E501s that we can

**Comment by spacether** [comment]
Enum values with newlines now use \n so this has been fixed
