### ISSUE TITLE
[Question] Handle custom code.

### ISSUE THREAD

**Issue by Sebastiencreoff** [OpenAPITools/openapi-generator#5053]
##### Description

Hello, I found this package which looks awesome to generate API easily and be able to do mapping between documentation and code. 
I just do not find a tutorial to include this tool inside a project. 
For what I understood at the moment is:
1 - Create your yaml file folliwing the OpenApi specification (ok)
2 - Generate my API with your tool. (ok)
3 - Implement my own code ?
4 - Add a new feature and then update my yaml file
5 - go back to 2.

Can someone knows where I can find a tutorial about the 3, 4 and 5 part to avoid losing my personal code added the next time I generate my API ? 

For example:

Inside my API, I have this function:
```
async def find_pets_by_status(request: web.Request, status) -> web.Response:
    """Finds Pets by status

    Multiple status values can be provided with comma separated strings

    :param status: Status values that need to be considered for filter
    :type status: List[str]

    """
    return web.Response(status=200)
```

For my personal purpose, I need to do something like that inside:

```
async def find_pets_by_status(request: web.Request, status) -> web.Response:
    """Finds Pets by status

    Multiple status values can be provided with comma separated strings

    :param status: Status values that need to be considered for filter
    :type status: List[str]

    """
    # Call my personal module to do it.
   result = mymodule.find_my_pet(user)
   return web.Response(body=result, status=200)
```

Thanks for your help.

**Comment by AIexG** [comment]
You could edit/copy the template files for your language located at `/modules/openapi-generator/src/main/resources`. To avoid compiling the whole generator again you can append a custom template directory in the CLI with the flag `-t <path-to-dir>`. When adding your changes to the templates instead of the generated source files you wont loose anything!

**Comment by Sebastiencreoff** [comment]
@AIexG 
Thanks for your answer, I will check it and close this issue if it is fine for me.
