### ISSUE TITLE
Bearer token not supported for scala-akka client.

### ISSUE THREAD

**Issue by jaroslawZawila** [OpenAPITools/openapi-generator#5067]
Current implementation does not generate bearer token basic authentication from OpenApi 3.x. Instead if specified in the spec file, it generates basic auth with username and password instead of bearer token.

**Comment by wing328** [comment]
Right. I wonder if you have time to file a PR for the enhancement.

I can show you some good starting points.

**Comment by jaroslawZawila** [comment]
I already have one but I have problem to create PR from my fork as github gives me unicorn :(

**Comment by jimschubert** [comment]
Thanks for reporting the issue and for fixing it via #5069!
