### ISSUE TITLE
[go] map type object *interface{} convert problem

### ISSUE THREAD

**Issue by ilk** [OpenAPITools/openapi-generator#51]
##### Description

Definition property "type": "object" gets converted to *interface{} which returns an error when set to a struct or pointer pointer.

##### openapi-generator version

3.0.0
##### Suggest a fix/enhancement

Instead of an *interface{} map the object to map[string]interface{}

**Comment by wing328** [comment]
@ilk thanks for creating the issue. May I know if you can also share a spec to more easily reproduce the issue?

When using `type: object`, are you referring to an arbitrary JSON payload?

**Comment by ilk** [comment]
**For example:**
```json
...
"Provider" : {
  "type" : "object",
  "properties" : {
    "Foobar" : {
      "type" : "object",
      "description" : "Foobar-specific configuration object"
    },
...
```

**Results to:**
```go
type Provider struct {
  Foobar *interface{}
  ...
}
```

**Better would be:**
```go
type Provider struct {
  Foobar map[string]interface{}
  ...
}
```

**Comment by louis77** [comment]
@antihax Which works properly if definitions are used in the OpenAPI Spec. 

However, arbitrary inline objects are currently represented as *interface{}'s. To use @ilk 's example, `Foobar` is an arbitrary inline object, most likely there will be no corresponding struct definition in the Go code that will use the go-client.

**Comment by wing328** [comment]
Is it correct to say that the proposed change will also work with XML payload (since Go client supports the "withXML" option) ?
```
	withXml
	    whether to include support for application/xml content type and include XML annotations in the model (works with libraries that provide support for JSON and XML) (Default: false)
```
