### ISSUE TITLE
[BUG][Typescript] Duplicate key in enum when value (string) has characters that are not valid in variable name 

### ISSUE THREAD

**Issue by Warchant** [OpenAPITools/openapi-generator#5110]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Characters that can not be used in variable names should be translated into words, and yet still used in enum keys. Removing them (current behavior), leads to duplicate keys.

This enum is generated with `typescript-node` and `typescript-axios` (and I am sure, other generators will work the same, but I did not test them):
```
export enum GradeEnum {
        A = <any> 'A+',
        A = <any> 'A',
        B = <any> 'B',
        C = <any> 'C',
        D = <any> 'D',
        E = <any> 'E'
    }
```

##### openapi-generator version

The one installed from npm, 4.2.2

##### OpenAPI declaration file content or url

Spec: https://lgtm.com/api/v1.0/openapi

Bug is related to this part of the spec:
```json
{
  "type": "string",
  "description": "The grade of the code for this language.",
  "example": "A+",
  "enum": [
    "A+",
    "A",
    "B",
    "C",
    "D",
    "E"
  ]
}
```

##### Command line used for generation

https://github.com/Warchant/lgtm-api-ts/blob/f7fbd5e587b7b49d7aa2ee405cf8be5423c01059/Makefile#L8

```
npx openapi-generator generate --git-user-id=$(GIT_USER) --git-repo-id=$(GIT_REPO) -i $(API) -g typescript-axios -c config.json

```

##### Steps to reproduce

1. Use `typescript-axios` generator on lgtm spec
2. Find `GradeEnum` in generated fles. 
3. See duplicate keys.

##### Related issues/PRs

None. 

##### Suggest a fix

Characters that can not be used in variable names, should be replaced with special words, or so:
```
const replacement = {
  "+": "plus",
  "-": "minus"
}
```

Then, enum keys will become:
```
export enum GradeEnum {
        Aplus = <any> 'A+',
        A = <any> 'A',
        B = <any> 'B',
        C = <any> 'C',
        D = <any> 'D',
        E = <any> 'E'
    }
```

**Comment by macjohnny** [comment]
@Warchant would you like to contribute a fix?

**Comment by alsofr** [comment]
Could it be that the fix needs to be done in this file?

https://github.com/OpenAPITools/openapi-generator/blob/ebc98ec848fb53ca28e07a20d83b7cad72d8aea6/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractTypeScriptClientCodegen.java#L629

However I'm not very confident about the side effects and implications of changing this code. Any change in that code won't be backward compatible.

Maybe an additional configuration parameter for enums would work best?

**Comment by racsus** [comment]
Hi there, any update about this bug?
