### ISSUE TITLE
[BUG][typescript-angular] Incorrect import path for inline models 

### ISSUE THREAD

**Issue by amakhrov** [OpenAPITools/openapi-generator#5127]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Inline models (if there are more than one) together with fileNaming="kebab-case" result in incorrect import paths.
E.g. `InlineObject1` is created in `models/inline-object-1.ts`. But generated api file tries to import it as
```
import {InlineObject1} from '../models/inline-object1'
```

##### openapi-generator version

Master and stable

##### OpenAPI declaration file content or url

[inline-models.yml (gist)](https://gist.github.com/amakhrov/7967679d2945ba1daf30a2313afd69df)

Important part is that there are 2 POST endpoints with inline models in body.

##### Command line used for generation

```
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate \
    -i /local/inline-models.yml \
    -g typescript-angular \
    --config /local/config.json \
    -o /local/generated
```
and `config.json`:
```
{
  "fileNaming": "kebab-case",
}
```

##### Steps to reproduce

- Generate the files using the spec.
- Compare the name of the file containing InlineObject1 model with the import path used in `api/default.service.ts`
- **Expectation**: they should match
- **Actual**: file name is `inline-object-1`; import path is `inline-object1`

##### Suggest a fix

PR: https://github.com/OpenAPITools/openapi-generator/pull/5128

**Comment by macjohnny** [comment]
@amakhrov

> E.g. `InlineObject1` is created in `models/inline-object-1.ts`. But generated api file tries to import it as
> 
> ```
> import {InlineObject1} from '../models/inline-object-1'
> ```

this seems correct, or am I missing something?

**Comment by amakhrov** [comment]
My bad. The actual import looks like
```
import {InlineObject1} from '../models/inline-object1'
```
see the missed dashed before `1`
