### ISSUE TITLE
[javascript-flowtyped] Enum (uniontype) not excaped properly

### ISSUE THREAD

**Issue by shfx** [OpenAPITools/openapi-generator#514]
##### Description

When openapi contains a enum type for any of the attributes and this enum contains `'`, enum union type is not escaped properly.

e.g.
```js
export type CountriesHumanNameEnum = 'Andorra' | 'United Arab Emirates' | 'Afghanistan' | 'Antigua and Barbuda' | 'Anguilla' | 'Albania' | 'Armenia' | 
'Cote d'Ivoire' | // <- Here
'Mayotte' | 'South Africa' | 'Zambia' | 'Zimbabwe';
```

##### openapi-generator version

3.1.1-SNAPSHOT

##### Command line used for generation

```sh
openapi-generator generate -i https://example.com/api.json -g javascript-flowtyped -o openapi/client
```

##### Steps to reproduce

1. Generate client code
2. `yarn`
3. `yarn run build`

##### Suggest a fix/enhancement

Escape string union types generated by `openapi-generator`

**Comment by macjohnny** [comment]
related: https://github.com/swagger-api/swagger-codegen/issues/7369

this should be fixed for all typescript / javascript generators
