### ISSUE TITLE
[BUG] [kotlin-spring] interfaceOnly doesn't work as expected

### ISSUE THREAD

**Issue by mariusstokseth** [OpenAPITools/openapi-generator#5165]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Using the openapi-gradle plugin i setup a task to generate code for the Petstore example [YAML] (https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml). I have created the following task: 
```
task buildKotlinClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask){
    generatorName = "kotlin-spring"
    inputSpec = "$rootDir/pet.yaml".toString()
    outputDir = "$rootDir/generated-sources/".toString()
    apiPackage = "sandbox.api"
    modelPackage = "sandbox.model"
    configOptions = [
            dateLibrary: "java8",
            swaggerAnnotations: "true",
            interfaceOnly: "true",
    ]
    systemProperties = [
            modelDocs: "false",
            generateSupportingFiles: "false",
    ]
}
```

From what I understand only the PetAPI and the objects Error and Pet should be generated. Instead the task also generates Application.kt, build.gradle.kts, pom.xml, README.m, settings.gradle and application.yaml

##### OpenAPI declaration file content or url
URL: https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Steps to reproduce
1. Download Petstore Example YAML
2. Run code generation task using the Gradle Plugin
3. Navigate to the genearted-sources folder

**Comment by raphael-jungers** [comment]
You can set the "generateSupportingFiles" option to false. It's not specifically related to the kotlin-spring generator. See [this answer](https://stackoverflow.com/a/48774368/5695522)

**Comment by kleinph** [comment]
I also run over this issue. `generateSupportingFiles` is AFAIK specific to the maven plugin.

For the gradle plugin use this:
```gradle
systemProperties = [
            apis: "",
            models: "",
            supportingFiles: "false"
]
```

**Comment by mariusstokseth** [comment]
Thank you very much for this @kleinph
