### ISSUE TITLE
[BUG][JAVA][webclient] queryParams get encoded twice

### ISSUE THREAD

**Issue by dwlabcube** [OpenAPITools/openapi-generator#5224]
In ApiClient.mustache of the webclient (Spring) the Query Params get encoded after this Comment at Line: 559
 //encode the query parameters in case they contain unsafe characters

But will get encoded AGAIN in Line 574:
final WebClient.RequestBodySpec requestBuilder = webClient.method(method).uri(**builder.encode().toUriString()**, pathParams)

that is leading to a double-encoding.
suddenly a Queryparam which should be:
www.api.com/get?filter=id=4
is going to be:
www.api.com/get?filter=id%25253D4

instead of only:
www.api.com/get?filter=id%3D4

**Comment by dwlabcube** [comment]
The following Code makes it work for my case:

`if (queryParams != null) {
            //encode the query parameters in case they contain unsafe characters
            /*for (List<String> values : queryParams.values()) {
                if (values != null) {
                    for (int i = 0; i < values.size(); i++) {
                        try {
                            values.set(i, URLEncoder.encode(values.get(i), "utf8"));
                        } catch (UnsupportedEncodingException e) {

                        }
                    }
                }
            }*/
            builder.queryParams(queryParams);
        }

        final WebClient.RequestBodySpec requestBuilder = webClient.method(method).uri(**builder.build(false).toUriString(),** pathParams);`

**Comment by wing328** [comment]
Thanks for reporting the issue. I wonder if you can file a PR with the suggested fix and we'll review accordingly.

**Comment by dwlabcube** [comment]
Unfortunately i am not smart enough to create pull request, because i can not create a branch on this repo. i only get 403 back.

So, this file would be the fix:
openapi-generator\modules\openapi-generator\src\main\resources\Java\libraries\webclient
[ApiClient.mustache.zip](https://github.com/OpenAPITools/openapi-generator/files/4179506/ApiClient.mustache.zip)

**Comment by wing328** [comment]
Please refer to https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements on how to submit a PR.

**Comment by grzegorz-moto** [comment]
what is the status of this? when can we expect it released?

**Comment by dwlabcube** [comment]
i have done a pull request to it, but obviously i did not link it correctly to this bug.
https://github.com/OpenAPITools/openapi-generator/pull/5255#

it seems to be merged, but since i am not a github-specialist i don't know how to proceed

**Comment by wing328** [comment]
We'll include it in the upcoming 4.3.0 release. For the time being, please use the SNAPSHOT version as mentioned in the project's README.
