### ISSUE TITLE
[BUG][JAVA][Feign]: erroneous Param-mapping causes "Body parameters cannot be used with form parameters"

### ISSUE THREAD

**Issue by Chr1st0ph** [OpenAPITools/openapi-generator#5249]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generating a Feign-client with header-param, e.g. Authorization, causes a validation-error:

Caused by: java.lang.IllegalStateException: Body parameters cannot be used with form parameters.
        at feign.Util.checkState(Util.java:130) ~[feign-core-10.4.0.jar:na]

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

https://gist.github.com/Chr1st0ph/bb10430c703f79dd938201c19c92fbc1

Generated code:

```yaml
  @RequestLine("POST /examples")
  @Headers({
    "Content-Type: application/json",
    "Accept: application/json",
    "Authorization: {authorization}"
  })
  void postExample(@Param("Authorization") String authorization, String body);
```
Mapping in Headers-annotation for Authorization does not fit to mapping in Param-annotation.

##### Command line used for generation

mvn spring-boot:run -Dspring-boot

##### Steps to reproduce

Create files ( see linked GIST ), and run the Maven-command.

##### Related issues/PRs

I did a swift search, but did not find an open issue for it.

##### Suggest a fix

I will provide a merge-request for using paramName instead of baseName in openapi-generator/modules/openapi-generator/src/main/resources/Java/libraries/feign/api.mustache

**Comment by joshdcollins** [comment]
@Chr1st0ph  I'm interacting with a system which has underscores in the param names.  After this change, these are now moved to camel-case.  Is there a good way to avoid this?

**Comment by Chr1st0ph** [comment]
@joshdcollins I can reproduce your issue, and have to apologize since there is no workaround for this. Maybe you can stick with 2.3.0 for the moment. Anyway, thank you for notifying me about it.

@wing328 this issue introduced a bug: can it be reverted for the next release ?

**Comment by Chr1st0ph** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/6234

@wing328 @joshdcollins  fyi
