### ISSUE TITLE
[Rust] client codegen ignores all fields that are of type "formData"

### ISSUE THREAD

**Issue by euank** [OpenAPITools/openapi-generator#525]
##### Description

I think the title for this one is fairly self-descriptive.

I intend to fix this one myself fairly soon.

**Comment by myk3v** [comment]
Unfortunately, it seems that this issue persists with generator option `"library": "reqwest"` #1258 
@bcourtine

**Comment by bcourtine** [comment]
@myk3v Thanks for the ping. I will look at this.
