### ISSUE TITLE
[BUG] C++ Server (Qt5) does not implement "fromStringValue(const QString &, OAIObject &)"

### ISSUE THREAD

**Issue by redturtlepower** [OpenAPITools/openapi-generator#5252]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Sending a Post request with a json payload (application/json mime type) the generator generates the code 

```
void OAIUserApiRequest::loginUserRequest(){
    qDebug() << "/v1/user/login";
    connect(this, &OAIUserApiRequest::loginUser, handler.data(), &OAIUserApiHandler::loginUser);
    OAIObject body;
    ::OpenAPI::fromStringValue(QString(socket->readAll()), body);
    emit loginUser(body);
}
```
The function `::OpenAPI::fromStringValue(QString(socket->readAll()), body);` is only declared in file `helpers-header.mustache` but not defined in file `helpers-body.mustache`.

##### openapi-generator version

cli: 4.2.3

##### OpenAPI declaration file content or url
[spec.yaml](https://gist.github.com/redturtlepower/b70a103bfce99f1248a65d52da083ac9)

##### Command line used for generation

rmdir /s /q .\myapp-api-v1-server
java -jar openapi-generator-cli.jar generate -i spec.yaml -g cpp-qt5-qhttpengine-server -o myapp-api-v1-server

##### Steps to reproduce

Generate the source from the linked spec file.
Open the generated file 'OAIUserApiRequest.cpp' at line 53.
The code won't link because the function is not defined.

##### Suggest a fix

Add the following code to file `helpers-body.mustache`

```
#include <QJsonParseError>

bool
fromStringValue(const QString &inStr, {{prefix}}Object &value)
{
    QJsonParseError err;
    QJsonDocument::fromJson(inStr.toUtf8(),&err);
    if ( err.error == QJsonParseError::NoError ){
        value.fromJson(inStr);
        return true;
    }
    return false;
}

```

**Comment by etherealjoy** [comment]
Fixed with #5253
