### ISSUE TITLE
[BUG] [typescript-fetch] Base Path can't be set to '<empty string>'

### ISSUE THREAD

**Issue by duxiaofeng-github** [OpenAPITools/openapi-generator#5282]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

the same issue with [https://github.com/OpenAPITools/openapi-generator/issues/2731](https://github.com/OpenAPITools/openapi-generator/issues/2731)

##### openapi-generator version

latest version

##### Steps to reproduce
```
new DefaultApi(
  new Configuration({
    basePath: "",
  }),
)
```

the basePath will replaced by "localhost/xxxx", but i expect it as /xxxx

##### Related issues/PRs

[https://github.com/OpenAPITools/openapi-generator/issues/2731](https://github.com/OpenAPITools/openapi-generator/issues/2731)

##### Suggest a fix

it caused by this line:

https://github.com/OpenAPITools/openapi-generator/blob/baf0e8521634ecb759c7e00ab65f12373aa2d546/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L125

the code above assume that this.configuration.basePath not a empty string, otherwise it will be replaced by BASE_PATH.

use the below code to fix it:

```
return this.configuration.basePath != null ? this.configuration.basePath : BASE_PATH;
```

it means if this.configuration.basePath **NOT A NULL OR UNDEFINED**, then use it, otherwise use the BASE_PATH

**Comment by macjohnny** [comment]
@duxiaofeng-github would you like to fix this with a PR?

**Comment by duxiaofeng-github** [comment]
@macjohnny i don't know how to generate those examples in https://github.com/OpenAPITools/openapi-generator/pull/3489/files

**Comment by macjohnny** [comment]
```
mvn clean package
./bin/typescript-fetch-petstore-all.sh
```

**Comment by duxiaofeng-github** [comment]
ok, @macjohnny , i send a pr already, please review it when you're free.
