### ISSUE TITLE
Consolidate web presence names for better discovery

### ISSUE THREAD

**Issue by grokify** [OpenAPITools/openapi-generator#530]
##### Description

Right now, OpenAPI Tools and Generator have a number of different names for various web presences. If we can consolidate the names, it would make for better discovery and a more consistency for users. Some examples include:

* https://github.com/OpenAPITools/openapi-generator
* https://twitter.com/oas_generator
* https://openapi-generator.tech
* https://openapitools.org

Some questions include:

* What is the top level entity we want to promote: OpenAPI Tools, or OpenAPI Generator? We have a GitHub org for Tools and a Twitter handle for Generator. We have web domains for both Generator and Tools.
* Can we consolidate names and have a single name for the Tools and Generator entities, e.g. `openapi-generator` vs. `oas_generator`.
* Can we consolidate the name styles. For example `openapi-generator.tech` and `openapitools.org` have different TLDs.

If we want to promote OpenAPI Tools, then we could have:

* GitHub: https://github.com/OpenAPITools
* GitHub: https://github.com/OpenAPITools/openapi-generator
* Twitter: https://twitter.com/OpenAPITools
* Web: https://openapitools.org
* Web: https://openapitools.org/openapi-generator

If we wanted to promote the OpenAPI Generator, we could have:

* GitHub: https://github.com/OpenAPITools/openapi-generator
* Twitter: https://twitter.com/openapi-generator
* Web: https://openapi-generator.tech

Either way, it would be nice to be consistent between the GitHub, Twitter and web presences.

**Comment by jmini** [comment]
Thank you a lot for this summary! It helps to start a discussion.

**Comment by jmini** [comment]
The OAI group (The "OpenAPI Initiative" group, responsible for the OpenAPI project) has raised some concerns about the name of our project and about the name of our organization. After our public launch, they have updated their guideline. 
We are trying to understand the implications and have opened OAI/OpenAPI-Style-Guide#14 to discuss it.

Right now we are waiting for feedback.

Until we know more, we might need to put the consolidation action proposed in this issue on hold.

**Comment by jimschubert** [comment]
Regarding the options…

> GitHub: `@OpenAPITools`
> GitHub: `OpenAPITools/openapi-generator`

We have these.

> Twitter: twitter.com/OpenAPITools

Twitter apparently no longer lets you choose the twitter name?

> Web: openapitools.org

We have this, it redirects to this repo currently but could/should redirect to organization details in the future.

> Web: openapitools.org/openapi-generator

This isn't necessary. Most tools/framework have a dedicated site which is not resourced under a TLD. See, for example delta.io (DataBricks), swagger.io (SmartBear), 

If we wanted to promote the OpenAPI Generator, we could have:

> GitHub: OpenAPITools/openapi-generator

We have this

> Twitter: twitter.com/openapi-generator

Again, we can't choose the name, apparently.

> Web: openapi-generator.tech

We have this as a documentation site specific to the generator.

---

So, aside from Twitter being screwy, the openapitools.org/openapi-generator recommendation is debatable.

I hope you don't mind if I close this as I work on cleaning up outstanding issues?  If you feel strongly that openapitools.org/openapi-generator should be an alias for openapi-generator.tech, please reach out on Slack and we can see how that might work.
