### ISSUE TITLE
[REQ] Add `--enable-post-process-file` example for `nodejs-express-server`

### ISSUE THREAD

**Issue by mattnorris** [OpenAPITools/openapi-generator#5323]
### Is your feature request related to a problem? Please describe.

Most generators give you an environment variable and example command in the log output for 
`--enable-post-process-file`. Generating `nodejs-express-server` does not. 

## Describe the solution you'd like

Add `--enable-post-process-file` example for `nodejs-express-server`. 

## Additional context

Discussed with @jimschubert and @wing328 on Slack.

**Comment by wing328** [comment]
#5369 merged into master.

Please give the latest master/snapshot version a try.
