### ISSUE TITLE
[REQ] Python .gitlab-ci.yml

### ISSUE THREAD

**Issue by LoveIsGrief** [OpenAPITools/openapi-generator#5340]
### Is your feature request related to a problem? Please describe.

It would be great to have a `.gitlab-ci.yml` for the python package. It would support Gitlab CI and not only TravisCI.

## Describe the solution you'd like

A simple `.gitlab-ci.yml` for python that does the same as `.travis.yml`.

## Describe alternatives you've considered

A simpler way to include files in templates? I'm not sure one exists and if it does, it has to be documented.

## Additional context

I'm talking about adding `.gitlab-ci.mustache` to https://github.com/OpenAPITools/openapi-generator/tree/ea55968737fa80a3e306d1b08032ff4d911774c9/modules/openapi-generator/src/main/resources/python

**Comment by wing328** [comment]
PR merged. Thanks for the contribution.

**Comment by LoveIsGrief** [comment]
Thanks for merging and the quick response!
