### ISSUE TITLE
[Python][Validation] Knob to control whether to ignore additional attribute in the HTTP response

### ISSUE THREAD

**Issue by sebastien-rosset** [OpenAPITools/openapi-generator#5351]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I've noticed SDKs are inconsistent in how they handle additional, undeclared attributes in HTTP response. What do you think about having a language-independent parameter that controls the leniency?

Some clients (such as python-experimental) do strict validation of the response. If the response includes undeclared properties that the client does not know about, the client raises an exception. Other clients (such as go and Java) are lenient and ignore additional attributes from the server JSON response.

Use case: The client has been generated and keeps running for weeks without problem. Then the server is upgraded to a newer version, adding one more declared property in the schema, in a way which is backward compatible. I.e. the OAS spec has a new property to an existing API. The new server sends the new property when the existing API is requested.
The problem is as soon as the server is upgraded, the clients will start failing. If there are thousands of clients, this is bad because as soon as the server is upgraded, all clients fail and must be upgraded.

A user of the client SDK may have the intent to run the same version of the SDK for a while, even if the server is upgraded. They may be perfectly fine doing this because the server provides backward compatibility guarantees and new attributes can be safely ignored. Other users may want to make sure the client fails when a new attribute in sent by the server, because they really want the client and server to be always at the same version.

As a workaround, it's possible to set "additionalproperties" in the spec everywhere, to prepare for additions to the spec. I don't find this solution very appealing because it can't address the above use cases.

##### openapi-generator version

master February 17th 2020

**Comment by sebastien-rosset** [comment]
@spacether

**Comment by spacether** [comment]
Also, I am not sure if additionalProperties is widely supported across our generators yet.
This CLI option sounds useful when people want to allow new properties without raising validation errors.

**Comment by sebastien-rosset** [comment]
Yes, I can confirm support for additional properties is lacking in Java and go

**Comment by sebastien-rosset** [comment]
Also, I think my preference would be to make it a configuration parameter of the generated SDK, not a build time option. That way, the same SDK can be used in both modes, rather than publishing two SDKs

**Comment by spacether** [comment]
That sounds like a good plan.
Some options would be to:
- add it as a module level constant
- add it as a configuration instance property
A configuration instance property would allow separate our users to have multiple clients in memory and use different deserialization behavior for them which gives them good control.
If a class has that flag flipped in configuration, then it could set additionalpropeties for that class to store any type (None, int, dict, float, file_type...) which would allow free form key-value pairs to be ingested.

-Should those new key value pairs be included when instances of that model are sent back to the server?

**Comment by sebastien-rosset** [comment]
> That sounds like a good plan.
> Some options to do this in python-experimental are:
> 
> * add it as a module level constant
> * add it as a configuration instance property
>   
>   * For reference, we are already passing in the Configuration instance to the model `__init__` method
> * add it as an input argument to deserialize() or to the model's `__init__`method
> 
> A configuration instance property would allow separate our users to have multiple clients in memory and use different deserialization behavior for them which gives them good control.
> If a class has that flag flipped in configuration, then it could set additionalpropeties for that class to store any type (None, int, dict, float, file_type...) which would allow free form key-value pairs to be ingested.

Yes, that would be great.

> 
> Should those unexpected key value pairs be included when instances of that model are sent back to the server?

Good question. In our specific case, it would make sense NOT to send the unknown attributes back to the server, but at this point I don't have a strong opinion either way. If the client has been built using an older version of the OAS document, my rationale is it shouldn't send stuff that it does not know about. And it will not send the unknown attribute in a POST operation anyway, that is unless first the client performs a GET to obtain the current value, but that is not required.
In our case, the server is doing a JSON merge of the incoming POST body with the existing content which is already present on the server side. That makes it possible for a client to send just a small HTTP body, instead of being required to send the entire payload. That also means our server is friendly to older clients. If an attribute does not exist in the payload, it will be merged. It has the benefit of allowing somewhat concurrent clients who each want to modify a subset, non-disjoint set of attributes.

As a side note, we also support json+patch content-type.

**Comment by spacether** [comment]
My suggestion is to add a parameter discard_unknown_keys to the configuration instance then. If false we keep our current strict behavior. If true then we discard the extra key info.

**Comment by sebastien-rosset** [comment]
> discard_unknown_keys

ok. What should be the default value?

**Comment by sebastien-rosset** [comment]
> My suggestion is to add a parameter discard_unknown_keys to the configuration instance then. If false we keep our current strict behavior. If true then we discard the extra key info.

Something like #5362?

**Comment by spacether** [comment]
This feature was added in https://github.com/OpenAPITools/openapi-generator/pull/5362
