### ISSUE TITLE
[BUG] [Java Spring] Cookie in parameter is not correctly generated

### ISSUE THREAD

**Issue by zalito12** [OpenAPITools/openapi-generator#5374]
##### Description

Like the other Java generators, Spring api generator is writting and ``, `` when there is a cookie param on the endpoint definition.

##### openapi-generator version

openapi-generator-maven-plugin 4.2.2

##### Steps to reproduce

It's detailed on #2908 

##### Related issues/PRs

#2908 
#2689

##### Suggest a fix

For spring we could add ``@CookiValue`` annotation to cookie params.

**Comment by wing328** [comment]
@zalito12 do you mind filing a PR with the suggested fix?

**Comment by zalito12** [comment]
@wing328 Yes, I'm working on it. I haven't contribute before so I'm catching up the on the working of the generator.

**Comment by zalito12** [comment]
I close it as it was duplicated in #5386
