### ISSUE TITLE
Revamp of a generator (csharp-netcore)

### ISSUE THREAD

**Issue by prajon84** [OpenAPITools/openapi-generator#5375]
We are evaluating the code generated by several of the C# templates and be quite dissatisfied with it.
The closest to what we need is the csharp-netcore template but it uses RestSharp internally and we need to pass our own middlewares which does not seem possible.

We are willing to work on improving these templates but the nature of our changes are very backwards incompatible, for instance, we want to allow passing the http client and remove the dependency on RestSharp, we also want to remove all the synchronous methods , etc.

Should we modify csharp-netcore, for instance creating multiple folders one per client like Java does or should we create a new higher level directory csharp-netcore-new ? with all the changes to not break compatibility with current users of csharp-netcore ?

@wing328  @SeanFarrow

**Comment by wing328** [comment]
@prajon84 thanks for the feedback.

cc @jimschubert the author of `csharp-netcore`

**Comment by wing328** [comment]
cc C# technical committee as well: @mandrean @jimschubert @frankyjuang @shibayan

**Comment by jimschubert** [comment]
The client is designed in such a way that you can implement the required interfaces and inject your own ApiClient implementation without introducing code into the built-in templates. ApiClient is also a partial class, allowing users to extend without touching the generated code itself.

Is there an issue with the interfaces, or are you more looking for an option which would create ApiClient without RestSharp imports and/or method implementations?

**Comment by shibayan** [comment]
Hello

I also aim to add a completely new designed C# client generator.
The current generator is based on C# 2.0, so the latest language features are not fully utilized.

I have been writing the so-called `csharp-latest` generator this year. The following branch is it.
https://github.com/shibayan/openapi-generator/tree/csharp-latest

**Comment by jcarres-mdsol** [comment]
@jimschubert 
There are multiple changes we would like to make:
- We need middlewares (We use Zipkin, also our own auth schema implemented in middleware), AFAIK there is no support to do this with RestSharp so we need other client.
- Our solution to the above would be to allow the user of the library to create an httpClient outside the library, with whatever middlewares, and passing the client to api client. Then we can always change details without breaking compatibility. If we do this, then the dependency on RestSharp is painful as we will never use it.

- We do all things Async, having sync methods can confuse people or make then think it is ok to use them when we don't want that. Also probably we would add more async methods if/where missing
 
- We'd like to produce data types where possible (date time, etc) instead of strings, this will be backwards incompatible change. We also would like to do all strings as `string`, there is a mix of `String` and `string` now.

**Comment by gabbsmo** [comment]
I am also in the process of reviewing different swagger client generators. The AngularJS/TypeScript generators are the best in the business. I do not need to repeat what has been said about the C# generator in the thread already.

I would like to add that I wish it was possible to exclude the test project generation. First in introduces a dependency on a testing framework that may not be the preferred choice for all developers. Secondly I think the value of test stubs for generated code is not that valuable if you do not intend to change the generated code.

**Comment by wing328** [comment]
> I have been writing the so-called csharp-latest generator this year. The following branch is it.
https://github.com/shibayan/openapi-generator/tree/csharp-latest

What about adding a `csharp-experimental` generator to collect feedback based on what you've built in the `csharp-latest` branch so far?

We've been adding experimental generators for PowerShell, Python, Go to collect feedback so far and the best part is that we don't need to worry about breaking changes as all experimental generators are subject to breaking changes without further notices.

**Comment by shibayan** [comment]
I wrote about it in #6800 and I'll write about it here as well. I am currently working on adding a `csharp-experimental` generator.

https://github.com/OpenAPITools/openapi-generator/compare/master...shibayan:csharp-experimental

The quality of the generated code is much improved. I will be replacing RestSharp with HttpClient in the future. The caveat is that the target is limited to modern C# / .NET Core support.

**Comment by jcarres-mdsol** [comment]
@shibayan did you ever commit your code?

**Comment by devhl-labs** [comment]
At this point he'd have to rewrite again.

**Comment by wing328** [comment]
We've added a new library option `httpclient` (e.g. in CLI `--library httpclient`) to the csharp-netcore client generator. Please pull the latest master or using the SNAPSHOT version to give it a try and let us know if you've any feedback
