### ISSUE TITLE
[Java] Default values for string-type query parameters are generated with two sets of quotes

### ISSUE THREAD

**Issue by OmriHarary** [OpenAPITools/openapi-generator#540]
##### Description
In annotations on parameters for generated api methods, default values for request query parameters are surrounded in two sets of double quotes. Completely prevents compilation.

Example of problem code, generated using information below:
```java
@ApiOperation(value = "", nickname = "fooGet", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation") })
    @RequestMapping(value = "/foo",
        method = RequestMethod.GET)
    default ResponseEntity<Void> fooGet(@ApiParam(value = "", defaultValue = ""foobar"") @Valid @RequestParam(value = "bar", required = false, defaultValue=""foobar"") String bar) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }
```
Example partial result from running `mvn package` on generated project:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project openapi-spring: Compilation failure: Compilation failure:
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,80] ')' expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,86] <identifier> expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,88] ';' expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,159] ')' expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,165] <identifier> expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,167] ';' expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,179] = expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,181] illegal start of type
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[43,182] <identifier> expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,16] = expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,19] ';' expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,35] <identifier> expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,36] illegal start of type
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,37] '(' expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,47] illegal start of type
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[44,63] = expected
[ERROR] /path/to/src/main/java/org/openapitools/api/FooApi.java:[48,1] class, interface, or enum expected
```
##### openapi-generator version

latest master

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
info:
  title: Issue example
  version: 1.0.0
paths:
  /foo:
    get:
      parameters:
        - name: bar
          in: query
          required: false
          schema:
            type: string
            default: foobar
      responses:
        default:
          description: successful operation

```
##### Command line used for generation
```
java -jar openapi-generator-cli.jar generate -g spring -i openapi.yaml
```

**Comment by wing328** [comment]
@OmriHarary thanks for reporting the issue. I'll take a look tomorrow.

**Comment by OmriHarary** [comment]
@wing328 I found the source of the problem and will file a PR for a fix soon.

**Comment by OmriHarary** [comment]
Issue is not limited to the `spring` generator, also found in: `jaxrs-cxf`, `jaxrs-spec`, `jaxrs-cxf-cdi`, `jaxrs-cxf-client`, `jaxrs-jersey`, `java-msf4j`, `jaxrs-resteasy`, `java-play-framework`, and `java-pkmst`.

**Comment by wing328** [comment]
Thanks for offering help to fix it.

For the following:
```
        - name: bar
          in: query
          required: false
          schema:
            type: string
            default: foobar
```

Should it be using `type` directly instead?
```
        - name: bar
          in: query
          required: false
          type: string
          default: foobar
```

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L203-L207

**Comment by OmriHarary** [comment]
The former is required for OAS3. ex: https://github.com/swagger-api/swagger-samples/blob/4750a960128953f77c5428b669b8a75689329b1a/java/swagger-petstore/src/main/swagger/openapi.yaml#L234-L238

Issue occurs in either case anyways.

**Comment by wing328** [comment]
OK. I'll give it another try tomorrow and hopefully file a PR to fix all Java-related generators regarding this issue.

**Comment by jmini** [comment]
Fixed with #708. 

Can you verify with version `3.2.2-SNAPSHOT`?

**Comment by wing328** [comment]
@OmriHarary if it's still an issue, please let me know and we'll reopen this issue for tracking.

**Comment by staaouat** [comment]
I'm facing the same problem with the versions cli-3.3.4 and cli-4.0.0-SANPSHOT

**Comment by halucki** [comment]
I have the same problem.  When I set the default value to header parameters like below,

```
openapi: 3.0.0
info:
  title: Issue example
  version: 1.0.0
paths:
  /foo:
    get:
      parameters:
        - name: bar
          in: header
          required: false
          schema:
            type: string
            default: foobar
      responses:
        default:
          description: successful operation
```

Generated parameters are with two sets of quotes. How can I solve this?

**Comment by jacekkruger** [comment]
It still fails for something like this:
`      parameters:
        - name: param_name
          in: path
          description: param_description
          required: true
          schema:
            type: string
            default: param_default`

**Comment by m-idler** [comment]
@jacekkruger actually a required value can't also have a default value. see also in the docs:
> Common Mistakes
> There are two common mistakes when using the default keyword:
> Using default with required parameters or properties, for example, with path parameters. This does not make sense – if a value is required, the client must always send it, and the default value is never used.
> ...

https://swagger.io/docs/specification/describing-parameters/
