### ISSUE TITLE
[Typescript][jQuery] fix return type

### ISSUE THREAD

**Issue by macjohnny** [OpenAPITools/openapi-generator#541]
##### Description

see https://github.com/swagger-api/swagger-codegen/issues/8383

**Comment by macjohnny** [comment]
@baol @grollinger would you like to incorporate the changes of https://github.com/swagger-api/swagger-codegen/pull/8385 here, too? openapi-generator is a community-fork of swagger codegen, and it is released frequently. migration is easy, just change the dependency in your `pom.xml`

**Comment by grollinger** [comment]
@macjohnny Sure, why not.

**Comment by macjohnny** [comment]
closed with https://github.com/OpenAPITools/openapi-generator/pull/581
