### ISSUE TITLE
[BUG][dart][dart-dio] required fields are nullable in generated files

### ISSUE THREAD

**Issue by valentinbercot** [OpenAPITools/openapi-generator#5411]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When trying to generate dart-dio api client with open api specification with required fields, they are ignored by default.

I know that a nullableFields option is available for generation but there is only 2 possibles output:
- all fields are nullable
- all fields are non nullable

Why there is no way to have only required fields non nullable?

##### openapi-generator version

os: macOS
os version: 10.15.2
openapi-generator version: 4.2.3
node version: 10.15.2
npm version: 6.13.4

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

##### Command line used for generation

```
npm install
npm run client:generate
```

with the following package.json
```
{
  "name": "dart-dio-gen",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "client:generate": "rm -rf client/ && openapi-generator generate --generator-name dart-dio --input-spec petstore.yaml --output client/"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@openapitools/openapi-generator-cli": "^1.0.10-4.2.3"
  }
}
```

##### Steps to reproduce

After generation, just have a look at `client/model/pet.dart` for example

Obtained generate file:

```
            import 'package:openapi/model/tag.dart';
            import 'package:built_collection/built_collection.dart';
            import 'package:openapi/model/category.dart';
        import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'pet.g.dart';

abstract class Pet implements Built<Pet, PetBuilder> {

    
        @nullable
    @BuiltValueField(wireName: r'id')
    int get id;
    
        @nullable
    @BuiltValueField(wireName: r'category')
    Category get category;
    
        @nullable
    @BuiltValueField(wireName: r'name')
    String get name;
    
        @nullable
    @BuiltValueField(wireName: r'photoUrls')
    BuiltList<String> get photoUrls;
    
        @nullable
    @BuiltValueField(wireName: r'tags')
    BuiltList<Tag> get tags;
    /* pet status in the store */
        @nullable
    @BuiltValueField(wireName: r'status')
    String get status;
        //enum statusEnum {  available,  pending,  sold,  };

    // Boilerplate code needed to wire-up generated code
    Pet._();

    factory Pet([updates(PetBuilder b)]) = _$Pet;
    static Serializer<Pet> get serializer => _$petSerializer;

}
```

Expected generated file:

```
            import 'package:openapi/model/tag.dart';
            import 'package:built_collection/built_collection.dart';
            import 'package:openapi/model/category.dart';
        import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'pet.g.dart';

abstract class Pet implements Built<Pet, PetBuilder> {

    
        @nullable
    @BuiltValueField(wireName: r'id')
    int get id;
    
        @nullable
    @BuiltValueField(wireName: r'category')
    Category get category;
    
    @BuiltValueField(wireName: r'name')
    String get name;
    
    @BuiltValueField(wireName: r'photoUrls')
    BuiltList<String> get photoUrls;
    
        @nullable
    @BuiltValueField(wireName: r'tags')
    BuiltList<Tag> get tags;
    /* pet status in the store */
        @nullable
    @BuiltValueField(wireName: r'status')
    String get status;
        //enum statusEnum {  available,  pending,  sold,  };

    // Boilerplate code needed to wire-up generated code
    Pet._();

    factory Pet([updates(PetBuilder b)]) = _$Pet;
    static Serializer<Pet> get serializer => _$petSerializer;

}
```

**Comment by athornz** [comment]
@valentinbercot I'm not sure about the expected behaviour here.

As I understand it, nullable and required are different things. 

A field that is required will be returned in the response, but it may still be null.

**Comment by valentinbercot** [comment]
Hi @athornz,

The expected behaviour is shown here https://pub.dev/packages/built_value#common-usage

It could be great if, by default, only non required fields in the OAS file aren't annote with `@nullable`.

**Comment by kuhnroyal** [comment]
In most cases required and non-nullable mean the same thing. There are probably edge cases where this is not the case.

In regard to built_value usage, only fields that are nullable/non-required in OAS should be annotated with `@nullable`.

From my current tests this works as expected with an OAS 3.0 file when `nullableFields: false` is set. This does not work with an OAS 2.0 file.

**Comment by kuhnroyal** [comment]
Looking at this: https://stackoverflow.com/questions/45575493/what-does-required-in-openapi-really-mean there is a real difference between `nullable` (which OAS 2 does not support) and `required`. The problem is that built_value does not have this concept.

non-nullable in built_value is required+non-nullable in OAS.
nullable in built_value is !required in OAS.

The combination of required+nullable can no be represented in built_value.

**Comment by kuhnroyal** [comment]
@josh-burton I have been thinking about this issue for a while. I would suggest to default `nullableFields` to false in the future. Use the OAS `required` property to add `@nullable` (`{{^required}}@nullable{{/required}}`) and figure out some default value if the property is not nullable, possibly using the built_value `_initializeBuilder`.
This whole change would also be a requirement for future NNBD support without having all properties being `Type?`.

**Comment by kuhnroyal** [comment]
I have added https://github.com/OpenAPITools/openapi-generator/pull/8235 as a draft for this.
After more thought on this, properties should be `@nullable` when they are `nullable || !required` in OAS.
Additionally the new changes generate a customer serializer which serializes `null` for fields that are `required && nullable` in OAS.

**Comment by isaac-merkos** [comment]
Was this resolved? I am having the complete opposite issue, required but nullable fields are marked as required with dart generator and fail if the value is null
