### ISSUE TITLE
[BUG][csharp-netcore] : 'BaseValidate' does not exist in the current context 

### ISSUE THREAD

**Issue by xygon** [OpenAPITools/openapi-generator#5416]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
When generating a csharp client with the swagger file below I am getting a compilation error `Model\Pet.cs(127,30): error CS0103: The name 'BaseValidate' does not exist in the current context`.  I am aware of #1126 which I thought addressed this issue, but I'm still getting it with the specified swagger file.

##### openapi-generator version
I am using version 4.3.0-SNAPSHOT
* using latest docker image
* docker run --rm openapitools/openapi-generator-cli

##### OpenAPI declaration file content or url

[petstore-with-inheritance.json](https://gist.github.com/xygon/82cd827dd8979167bc6287bafc9eaf84)

##### Command line used for generation

docker run --rm -v c:\work\code\OpenApi3-Example:/local openapitools/openapi-generator-cli generate -i /local/petstore.json -g csharp-netcore -o /local/GeneratedClient

##### Steps to reproduce

Run the above command line.
cd src
cd Org.OpenAPITools
dotnet build
=> does not comile
=> `Model\Pet.cs(127,30): error CS0103: The name 'BaseValidate' does not exist in the current context`

##### Related issues/PRs

#1126

**Comment by wing328** [comment]
I couldn't reproduce the issue with the latest master. Please pull the latest master or snapshot version to give it another try.

**Comment by wing328** [comment]
Btw, the following is model composition (not inheritance) according to OpenAPI spec:
```
        "schemas": {
            "NewPet": {
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "tag": {
                        "type": "string"
                    }
                }
            },
            "Pet": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/NewPet"
                    },
                    {
                        "required": [
                            "id"
                        ],
                        "properties": {
                            "id": {
                                "format": "int64",
                                "type": "integer"
                            }
                        }
                    }
                ]
            },
```

You will need `discriminator` for inheritance.

**Comment by grimurjonsson** [comment]
You can reproduce it if you have no other properties. 

`            "Pet": {
                "allOf": [
                    {
                        "$ref": "#/components/schemas/NewPet"
                    }
                ]
            },`

In my case I have
`
allOf:
 - "$ref": "#/components/schemas/NewPet"
 - "$ref": "#/components/schemas/NewPet2"
`
and that also fails.

**Comment by wing328** [comment]
> You will need discriminator for inheritance.

since v6.6.0, one can use openapi normalizer to have inheritance in models without discriminator, please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#openapi-normalizer (rule: REF_AS_PARENT_IN_ALLOF)
