### ISSUE TITLE
How to set a token for typescript-angular?

### ISSUE THREAD

**Issue by dbanty** [OpenAPITools/openapi-generator#5441]
I feel like I'm missing something super obvious, but I can't figure out how to set an accessToken at runtime in my generated Angular client.

I can see in the source code that it's properly trying to get the accessToken from the Configuration and set the header, but I'm not sure how to set that token on the Configuration in the first place.

If I follow the instructions in the README and set up my app module like below, I can only set Configuration at initialization.  This doesn't help with the token because my user won't be logged in yet!

Is there a recommended way to set the Authorization header in the outgoing request?  Currently we're using an HttpInterceptor, but that can't be what you intended or the api functions wouldn't be trying to set the header for me.

It would be super nice to have whatever the answer is added to documentation somewhere or even the generated README.md.

Thanks!

```typescript
// configuring providers
import { ApiModule, Configuration, ConfigurationParameters } from 'inventory-client';

export function apiConfigFactory (): Configuration => {
  const params: ConfigurationParameters = {
    // set configuration parameters here.
  }
  return new Configuration(params);
}

@NgModule({
    imports: [ ApiModule.forRoot(apiConfigFactory) ],
    declarations: [ AppComponent ],
    providers: [],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
```

**Comment by amakhrov** [comment]
@dbanty Right, a Configuration instance is injected statically. But it doesn't mean it's properties cannot change dynamically at run time.

Simplified example
```
@Injectable({providedIn: "root"})
export class SessionService {
  // here we inject the very same configuration instance that is injected into api service
  constructor(private apiConfiguration: Configuration) {}

  async login() {
     const sessionData = await doSomeAsyncLoginStuff();
     this.apiConfiguration.accessToken = sessionData.accessToken;
  }
}
```

Does this help?

**Comment by dbanty** [comment]
I'll give that a shot, thanks!

**Comment by sertal70** [comment]
I definitely add a vote to have this added to the documentation!

**Comment by janishorsts** [comment]
alternative, to keep it simple - set it directly in the API client as DefaultService is DI:

```typescript
construct(private api: DefaultService) {}

// ....

// when token changed
this.api.configuration.accessToken = accessToken
```
