### ISSUE TITLE
[BUG] [csharp-netcore] Invalid expressions are generated using ??

### ISSUE THREAD

**Issue by vaindil** [OpenAPITools/openapi-generator#5442]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
The csharp-netcore generator generates invalid C# if an enum is set as required in a definition. With the enum property name present in the "required" object inside the definition of `ObjectCreateArgs`, the C# below is generated as a constructor for `ObjectCreateArgs`:

```csharp
public ObjectCreateArgs(ObjectType objectType = default(ObjectType))
{
    // to ensure "objectType" is required (not null)
    this.ObjectType = objectType ?? throw new ArgumentNullException("snip");;
}
```

This is invalid C# because `objectType` is not nullable, therefore the null coalescing operator can't be used with it.

##### openapi-generator version
4.2.3

##### OpenAPI declaration file content or url
[Click here](https://github.com/OpenAPITools/openapi-generator/files/4252477/swagger.txt) (rename extension to .json)

##### Command line used for generation
```
java -jar openapi-generator-cli.jar generate -i swagger.json -g csharp-netcore -o test-csharp
```

##### Steps to reproduce
Run the above command.

##### Suggest a fix
Enums are not nullable unless declared with `?` like other types, so they should be treated as such.

**Comment by BottlecapDave** [comment]
I have also just encountered this bug

**Comment by donatwork** [comment]
I'm also seeing the issue with openapi-codegen 4.3.0. The JSON looks like this:
```
    "my_class": {
      "type": "object",
      "required": [
        "my_type"
      ],
      "properties": {
        "my_type": {
          "$ref": "#/definitions/MyEnum"
        }
      }
    }
```

The csharp generator produced this:

```
        public MyClass(MyEnum myType = default(MyEnum))
        {
            // to ensure "myType" is required (not null)
            if (myType == null)
            {
                throw new InvalidDataException("myType is a required property for MyClass and cannot be null");
            }
            else
            {
                this.myType = myType;
            }
        }
```

When I switched to the csharp-netcore generator (validatable=true, false  both generated the same):

```
        public MyClass(MyEnum myType = default(MyEnum))
        {
            // to ensure "myType" is required (not null)
            this.myType = myType ?? throw new ArgumentNullException("myType is a required property for MyClass and cannot be null");;
        }
```

Here are my configOptions:

```
                            <configOptions>
                                <packageGuid>UUID</packageGuid>
                                <packageName>hidden</packageName>
                                <modelPackage>hidden</modelPackage>
                                <apiPackage>hidden</apiPackage>
                                <invokerPackage>hidden</invokerPackage>
                                <hideGenerationTimestamp>true</hideGenerationTimestamp>
                                <netCoreProjectFile>true</netCoreProjectFile>
                                <optionalMethodArgument>false</optionalMethodArgument>
                                <sortParamsByRequiredFlag>false</sortParamsByRequiredFlag>
                                <enablePostProcessFile>true</enablePostProcessFile>
                                <validatable>false</validatable>
                            </configOptions>

```

**Comment by donatwork** [comment]
This change (against master) could probably fix.

`diff --git a/modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache b/modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
index eb69cfc3eb..88a18998e1 100644
--- a/modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
+++ b/modules/openapi-generator/src/main/resources/csharp-netcore/modelGeneric.mustache
@@ -63,7 +63,14 @@
             {{#required}}
             {{^vendorExtensions.x-csharp-value-type}}
             // to ensure "{{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}}" is required (not null)
-            this.{{name}} = {{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}} ?? throw new ArgumentNullException("{{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}} is a required property for {{classname}} and cannot be null");
+            if ({{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}} == null)
+            {
+                throw new InvalidDataException("{{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}} is a required property for {{classname}} and cannot be null");
+            }
+            else
+            {
+                this.{{name}} = {{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}};
+            }
             {{/vendorExtensions.x-csharp-value-type}}
             {{#vendorExtensions.x-csharp-value-type}}
             this.{{name}} = {{#lambda.camelcase_param}}{{name}}{{/lambda.camelcase_param}};
`

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix?

https://github.com/OpenAPITools/openapi-generator/wiki/FAQ

**Comment by donatwork** [comment]
PR https://github.com/OpenAPITools/openapi-generator/pull/6110

**Comment by vaindil** [comment]
@donatwork Looks like you closed that PR, are you still planning on doing this?

**Comment by donatwork** [comment]
I saw another PR https://github.com/OpenAPITools/openapi-generator/pull/6112 which seems to be the big picture fix for this so I ended up closing my PR.

**Comment by wing328** [comment]
The fix by @shibayan has been merged into master. Please give it a try with the latest master or snapshot version and see if the issue has been fixed for you.

**Comment by donatwork** [comment]
This works well. Also the latest generated code does not even generate warnings, excellent.

**Comment by ByronMayne** [comment]
Yeah I have currently having this exact issue which cause a compile error 
![image](https://user-images.githubusercontent.com/6024487/113331516-10672900-92ee-11eb-9421-e8ef7e15b8db.png)
Owner is an enum type 

The object is 
```yaml
schemas:
    processInfo:
      required:
        - "owner"
      properties:
        owner:
          $ref: "#/components/schemas/processOwnerType"
components:
 schemas:
    processOwnerType:
      title: "ProcessOwnerType"
      type: string
      enum: 
       - "one"
       - "two"
       - "tree"
```

````

**Comment by donatwork** [comment]
Are you using the object initialization syntax when you create your instance? I've been using VS 2019 and target of 4.7.2 and no issues with compilation. At runtime it is possible that with object initialization syntax the object may be created first then fields set which I have seen.

**Comment by ByronMayne** [comment]
this is all auto generated I am not doing anything.  This is just in the constructor it fails to compile. 

![image](https://user-images.githubusercontent.com/6024487/113369917-868c7f80-9330-11eb-87d8-a40e5abbd885.png)

**Comment by moikot** [comment]
@ByronMayne You can try to add x-csharp-value-type to the type. e.g.
```c-sharp
Foo:
  type: string
  x-csharp-value-type: true
  enum:
     - A
     - B
```

**Comment by aeneasr** [comment]
Yes, I am also encountering this option. I have tried several options to work around it but could not find a resolution for it. See also #9442

**Comment by aeneasr** [comment]
Looks like there was a PR for this but it got closed: https://github.com/OpenAPITools/openapi-generator/pull/6110/files

**Comment by donatwork** [comment]
> Looks like there was a PR for this but it got closed: #6110

Yeah I closed the PR because the maintainers made a more thorough fix.

**Comment by aeneasr** [comment]
I see! Unfortunately it appears the issue still persist. I have no dotnet / c# experience but we are publishing SDKs for dotnet and „dotnet pack“ fails due to this.

I would love to help if anyone has an idea? It appears as if the syntax is only invalid in some scenarios? For example when a struct/object or boolean is involved?

**Comment by aeneasr** [comment]
@donatwork took your original PR and updated it to the latest methodologies of openapi generator. Tried it out against our spec, it resolves all the build issues: https://github.com/OpenAPITools/openapi-generator/pull/10333

:)

**Comment by leus** [comment]
I'm generating csharp code using the git version and it still generates invalid null checks (also generates duplicated enum values but those are less troubling, I just delete them). I'm using the following Blend.com spec: https://github.com/blend/blend-api-specs/blob/master/version_4/v4.2.0_stable.openapi_spec.yaml
