### ISSUE TITLE
[REQ] [Java] use a builder pattern for parameters?

### ISSUE THREAD

**Issue by bgong-mdsol** [OpenAPITools/openapi-generator#5451]
### Is your feature request related to a problem? Please describe.
Not an issue per se, just a better way to achieve the same result.

## Describe the solution you'd like
Currently parameters of an endpoint become parameters on a method.

Some endpoints have many parameters and as a result, the method will have 10s of parameters.
Something like:
```java
search(uuid, uuid2, uuid3, name, some_bool, other_bool, this_int, this_other_uuuid, other_bool, name2, name3)
```

The problems are:
- Usually you only need a couple of params so you call this with 2 params and 9 null
- It is very difficult to review and very error prone
- If the openapi spec changes the order in which they write the params or if they add a param in the first position, all the params will shift position. If types match, the code will compile but the outgoing call would be totally different.

To mitigate that, we used a builder pattern in our own templates to handle parameters, usage roughly looks like that:

```java
String operation = "unlock";
String operatorUuid = "596ad8ad-40f3-4fcd-b8af-7e7be5d8337c";
ServiceClient myApi = createServiceClient();

APIpermissionsIndexParams params = APIpermissionsIndexParams.builder()
  .operation(operation)
  .operatorUuid(operatorUuid)
  .build();

List<Permission> response = myApi.permissionsIndex(params);
```

## Describe alternatives you've considered
Using `Map<String, Object>`.

## Additional context
N/A

---

We would like to contribute the code back upstream but before opening a PR we'd like to hear the thoughts of the java tech committee.

Thanks!

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

**Comment by jeff9finger** [comment]
I would definitely like to see this. We have implemented our own builders for this purpose and to have them generated would be excellent.

I'd like to see the methods on server generated controller methods be able to not need to declare all the possible query parameters as well. I know that is a separate item, but very similar in concept.

**Comment by jfeltesse-mdsol** [comment]
As you recognize, I think the server-side of this should be implemented at a different time, through a separate PR.

As for the client side, should we keep the existing code in place (that generates methods with _n_ arguments) for backwards-compatibility or should we replace entirely and target 5.x?

**Comment by cbornet** [comment]
:+1 very good idea !

**Comment by jfeltesse-mdsol** [comment]
Heads up, we're going to tackle that soon for the native JDK 11 httpclient variant of the client templates.

One question still left unanswered though is:

> As for the client side, should we keep the existing code in place (that generates methods with n arguments) for backwards-compatibility or should we replace entirely and target 5.x?

**Comment by wing328** [comment]
@jfeltesse-mdsol better have backward-compatibility via an option in this case.

**Comment by bgong-mdsol** [comment]
[PR](https://github.com/OpenAPITools/openapi-generator/pull/5961) is ready for review.

**Comment by puneetgoyal08** [comment]
Hi, I tried using this but I was only able to generate it by selecting library as native, which made me use java version 11. Is there any way i can keep using java 8 and still use the builder pattern?

Thanks!

**Comment by wing328** [comment]
@puneetgoyal08  please try the `jersey2` library option.

**Comment by monktastic** [comment]
I must be missing something. How do I enable this feature? Simply using `jersey2` or `native` as the library apparently isn't enough (in 5.0.0).

**Comment by jfeltesse-mdsol** [comment]
your OpenAPI file needs to feature `x-group-parameters: true` at the top level.

**Comment by monktastic** [comment]
Thanks @jfeltesse-mdsol. There's no way to do this without modifying the OpenAPI spec? I'm surprised -- I would have thought it could be done purely client-side.

**Comment by monktastic** [comment]
Also, what other effects does `x-group-parameters: true` have? I don't want to break other clients.

**Comment by bgong-mdsol** [comment]
As my understand, `x-group-parameters` is one of vendor Extensions for grouping parameters into a single object. `x-group-parameters `can be put at the top level of the spec or in each endpoint definition. 
It won't break other clients if the client doesn't support `x-group-parameters`.

Since there are a few Jave Clients supporting `x-group-parameters` in their templates, I think it is better to add a cli option `USE_SINGLE_REQUEST_PARAMETER` for Java client generator.

**Comment by monktastic** [comment]
@bgong-mdsol Thank you! Just to make sure I'm understanding: `USE_SINGLE_REQUEST_PARAMETER` doesn't yet exist as an option yet, and you're suggesting that it get added, right? Or are you saying that I can set it somehow today?

As it stands today, it seems like I'm going to have to find a way to shoehorn `x-group-parameters` into the fetched spec on the client side before running the generator. I don't really understand why a setting that controls purely the client-side behavior should exist on the server side at all.

**Comment by bgong-mdsol** [comment]
@monktastic 
Currently there are no such option USE_SINGLE_REQUEST_PARAMETER for JavaClientCodegen yet. 

The client templates of` jersey2` or `native` supports `x-group-parameters`, and the generator will enable this feature if OpenAPI file  set `x-group-parameters: true`.

**Comment by monktastic** [comment]
Thanks @bgong-mdsol. That's unfortunate. It doesn't seem to make any sense for a flag on the _server_ side to dictate how a client can generate its own internal code (if it has no visible effect for the service, which it seems not to). It can also break other users of the service who are using openapi-generator. I've filed a FR for this. In the mean time, I've written a script to preprocess the spec and stuff `x-group-parameters: true` in before I run openapi-generator.

**Comment by majo32** [comment]
Hi. I solved this using lombok anotation: `<additionalModelTypeAnnotations>@lombok.AllArgsConstructor @lombok.Builder @lombok.NoArgsConstructor</additionalModelTypeAnnotations>
                            ` in `<configOptions>`
