### ISSUE TITLE
[BUG][typescript-angular] generator generates invalid TypeScript for polymorphic types

### ISSUE THREAD

**Issue by t03apt** [OpenAPITools/openapi-generator#5467]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

[typescript-angular] generator generates invalid TypeScript for polymorphic types.
For example:
```[TypeScript]
import { Circle } from '../model/models';
import { Rectangle } from '../model/models';
import { Rectangle | Circle } from '../model/models';
```

Expected:
```[TypeScript]
import { Rectangle, Circle } from '../model/models';
```

##### openapi-generator version

4.2.3

##### How to reproduce
> openapi-generator generate -i https://gist.githubusercontent.com/t03apt/71391e24045ef08dcad11bfae12037ae/raw/9c83bd41be70063d1436f84c842253018a6c8c46/Swashbuckle.AspNetCore.Test.WebSites.Basic.swagger.json -o ./generated -g typescript-angular --skip-validate-spec

**Comment by macjohnny** [comment]
related: https://github.com/OpenAPITools/openapi-generator/issues/4130#issuecomment-591458888

**Comment by szilagyinorbi** [comment]
any update on this?

**AbstractTypeScriptClientCodegen.java**
```
private Set<String> parseImports(CodegenModel cm) {
   Set<String> newImports = new HashSet<String>();
   if (cm.imports.size() > 0) {
      for (String name : cm.imports) {
         if (name.indexOf(" | ") >= 0) {
            String[] parts = name.split(" \\| ");
            for (String s : parts) {
               newImports.add(s);
            }
         } else {
               newImports.add(name);
         }
      }
   }
   return newImports;
}

private List<Map<String, String>> toTsImports(CodegenModel cm, Set<String> imports) {
   List<Map<String, String>> tsImports = new ArrayList<>();
   for (String im : imports) {
      if (!im.equals(cm.classname)) {
         HashMap<String, String> tsImport = new HashMap<>();
         // TVG: This is used as class name in the import statements of the model file
         tsImport.put("classname", im);
         tsImport.put("filename", toModelFilename(removeModelPrefixSuffix(im)));
         tsImports.add(tsImport);
      }
   }
   return tsImports;
}
```

I saw you have this splitting logic for the imports, but I still get the same error for oneOf types.

I am using openapi-gen **4.3.0**

**Swagger schema**
```
"schema": {
   "type": "array",
   "items": {
      "oneOf": [
         { "$ref": "#/components/schemas/Circle" },
         { "$ref": "#/components/schemas/Rectangle" }
       ]
    }
}
```

The return type for the endpoints are valid, but the imports are still
```
import { Circle } from '../model/models';
import { Rectangle } from '../model/models';
import { Rectangle | Circle } from '../model/models';
```

**Comment by tomghyselinck** [comment]
Can this be an issue in the mustache file(s)?

**Comment by macjohnny** [comment]
> Can this be an issue in the mustache file(s)?

I guess it is rather a problem in the type-generation in the java code

**Comment by FelschR** [comment]
This is also an issue with the `typescript-fetch` generator.

**Comment by macjohnny** [comment]
fixed in https://github.com/OpenAPITools/openapi-generator/pull/6789
