### ISSUE TITLE
[C++][Pistache-server] Help - How to write one server application that handles the full API ?

### ISSUE THREAD

**Issue by CyrilleBenard** [OpenAPITools/openapi-generator#548]
##### Description

I wonder how we are supposed to write one cpp-pistache server application that will handle the full API ? When I have a look to the [petstore sample ](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/cpp-pistache), I can find 3 "main example", so 3 different applications.

I mean _PetApiMainServer.cpp_, StoreApiMainServer.cpp and UserApiMainServer.cpp will each listen to the port 8080. How are we supposed to write ONE main application that will listen to the port 8080 and handle all the 3 API ?
What would be the server instantiation ?

Many thanks in advance

##### openapi-generator version
N/A
##### OpenAPI declaration file content or url
N/A
##### Command line used for generation
N/A
##### Steps to reproduce
N/A
##### Related issues/PRs
N/A
##### Suggest a fix/enhancement
N/A

**Comment by etherealjoy** [comment]
Have you found a solution?
If not I could check this weekend.

**Comment by CyrilleBenard** [comment]
I was a little wrong : 
The "HTTP End point" (ie listened port) is not defined by the _operationId_ keyword but by the keyword _tags_  that will produce a one to one relationship between class and tags. 

A workaround to embed all the API inside the same application would be to define every path/operationId with the same tags list, so that the generator will produce only ONE api class and so, only one "HTTP End point" but that also means "bye bye" the split class architecture like Pet, Store and User.

This is a workaround, not a nice solution I think. We should be able to define several API, so several classes but one HTTP End point.
If I am not wrong, there not the same issue in, at least, Java ?

**Comment by etherealjoy** [comment]
The issue is there only for pistache. Others don't have this problem. This is due to the inheritance pattern used. But it can be solved.

**Comment by etherealjoy** [comment]
@CyrilleBenard 
To solve this;
In the Api class the following members should be `std::shared_ptr` 
```C++
    Pistache::Http::Endpoint httpEndpoint;
    Pistache::Rest::Router router;
```
The Api class has to accept these members in the constuctor
They need to be constructed outside in a single file hosting the main function. 
Pass the same router and endpoint to all Api classes from the same spec.

**Comment by etherealjoy** [comment]
@stkrwork @wing328 
Is this something we should do, I have some idea to do this? I mean the Pistache server is probably the only server with three separate binary to run the PetStore sample.

**Comment by CyrilleBenard** [comment]
@etherealjoy could you expose or better, modify the Pistache integration to got a uniform behavior between all languages ? I mean, avoid the specific Pistache mapping "One Tag list" => "One End point" as explained previously. It would be nice to have this feature and obviously, more usable.

**Comment by etherealjoy** [comment]
@CyrilleBenard 
Please try out #1230 to see this feature
