### ISSUE TITLE
[REQ] [Python] improve additional_properties_type

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#5489]
### Is your feature request related to a problem? Please describe.

@sebastien-rosset did work that uncovered that additionalProperties: {}
should set additional property value data types to:
{str: (bool, date, datetime, dict, float, int, list, str)}
whereas python-experimental currently sets it to:
(bool, date, datetime, dict, float, int, list, str)

## Describe the solution you'd like
For additionalProperties: {} or additionalProperties: True
change the type definition to:
`additional_properties_type = ({str: (bool, date, datetime, dict, float, int, list, str)}, )`

Also per spec version https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md and higher
additionalProperties accepts a boolean value and defaults to True if omitted.

For additionalProperties: False or null use
`additional_properties_type = None`

For an object with no definition except a description:
`additional_properties_type = (bool, date, datetime, dict, float, int, list, str)`

For an object with no definition except a description + nullable: True:
`additional_properties_type = (bool, date, datetime, dict, float, int, list, str, none_type)`

## Related Issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/5317 generation of composedSchemas with additionalProperties: True
https://github.com/OpenAPITools/openapi-generator/issues/5387 describes how to handle nullable:True
https://github.com/OpenAPITools/openapi-generator/pull/5316 comments added describing what booleans util functions return when additionalProperties is False/True/Schema
https://github.com/OpenAPITools/openapi-generator/pull/5391 adds util function isAnyType adds sample spec example models

**Comment by spacether** [comment]
@richardwhiuk do you agree with my interpretation above?

**Comment by sebastien-rosset** [comment]
> For additionalProperties: True use
> additional_properties_type = (bool, date, datetime, dict, float, int, list, str,)

It should be dict. And if the property is also Nullable, add NoneType.

**Comment by spacether** [comment]
> > For additionalProperties: True use
> > additional_properties_type = (bool, date, datetime, dict, float, int, list, str,)
> 
> It should be dict. And if the property is also Nullable, add NoneType.

Can you point me to where the jsonschema spec says that?
https://json-schema.org/draft/2019-09/json-schema-core.html
Is it 4.3.2. Boolean JSON Schemas?

**Comment by sebastien-rosset** [comment]
Sorry I think I got confused. additionalProperties: true is the same as additionalProperties: {}
https://swagger.io/docs/specification/data-models/dictionaries/

Initially I thought you were referring to the difference between the two schemas below (from #5391)
```yaml
components:
  schema:
        stuff: {}

components:
  schema:
        stuff:
            type: object
```

**Comment by spacether** [comment]
> Sorry I think I got confused. additionalProperties: true is the same as additionalProperties: {}
> https://swagger.io/docs/specification/data-models/dictionaries/
> 
> Initially I thought you were referring to the difference between the two schemas below (from #5391)
> 
> ```yaml
> components:
>   schema:
>         stuff: {}
> 
> components:
>   schema:
>         stuff:
>             type: object
> ```

No worries. This issue was originally only looking at the:
additionalProperties: True/False/{} use cases but I expanded it to the empty object cases that you included in your work because they are all relevant to python-experimental's additional_properties_type

**Comment by spacether** [comment]
This has been fixed by recent commits
