### ISSUE TITLE
[rust-server] allow Metaswitch to migrate to openapi-generator

### ISSUE THREAD

**Issue by bjgill** [OpenAPITools/openapi-generator#550]
##### Description

Once https://github.com/OpenAPITools/openapi-generator/issues/307 is fixed, `rust-server` will be usable in openapi-generator. At @metaswitch, we'd like to migrate across.

Currently, we're working on a branch of swagger-codegen. We need to work on a branch due to having some changes to `html2` we've not yet upstreamed, as well as having added some `rust-server`-specific CI.

Now that Travis is testing `rust-server`, we no longer need to be working in a branch. The work to allow us to migrate across is therefore:

- [x] upstream our `html2` changes: https://github.com/OpenAPITools/openapi-generator/pull/643
- [x] upstream a few contributions that have got stuck waiting for the migration. These enhance the current authentication/context handling: https://github.com/OpenAPITools/openapi-generator/pull/645 and https://github.com/OpenAPITools/openapi-generator/pull/612
- [x] we need reproducible builds, so create our own docker containers. There'll be some internal work to allow us to continue doing this for openapi-generator
- [x] test our internal swagger specs against openapi-generator and raise/fix any issues discovered
- [x] a bunch of internal education

My hope is that once we've finished all that, we'll be able to start contributing directly to the open source repo, rather than having to contribute to our internal fork and then upstream. This should mean that the community gets more visibility into what we're doing.

##### Suggest a fix/enhancement

EDIT: I'm planning to work on this over the next couple of weeks.

**Comment by jmini** [comment]
This sounds like a good plan... Thank you a lot for sharing it.

**Comment by bjgill** [comment]
OK - we're making progress. I'm now waiting on the following PRs:

- [ ] #612
- [ ] #643
- [ ] #645

**Comment by bjgill** [comment]
I've started regression testing of internal specs. Bugs found:

- [ ] #659

**Comment by bjgill** [comment]
OK - we've worked around one regression, and documented the other. Thanks for all the help - I think we're now ready to use openapi-generator.
