### ISSUE TITLE
[REQ] Generate BC friendly PHP client

### ISSUE THREAD

**Issue by ro0NL** [OpenAPITools/openapi-generator#5506]
### Is your feature request related to a problem? Please describe.

It's easy to break a project by regenerating the PHP API client, given the backend added a new  backwards compatible filter (i.e. optional).

This caused a new required argument in the generated argument list, changing the total order and thus breaking all calling sides.

## Describe the solution you'd like

Overall, i think the generated code is rather poor and clumsy. Though we dont really care, i guess. However for a BC friendly API i suggest to generate e.g. a `FilterSet` value object.

So

```
// currrent
public function getLocationCollection($newFilter = null, $oldFilter = null) {}

// proposal
public function getLocationCollection(?FilterSet $filters = null) {}
```

**Comment by wing328** [comment]
What about using `x-group-parameters` to group the parameters into a single object?

**Comment by ro0NL** [comment]
Hi @wing328, i didnt know about this option. I'm gonna try it ASAP to see if it works for us. Thanks.

**Comment by ro0NL** [comment]
Hi @wing328 this seems generally spoken what we're looking for :+1:
