### ISSUE TITLE
[REQ] Render all models in a single file

### ISSUE THREAD

**Issue by EvilBeaver** [OpenAPITools/openapi-generator#5522]
### Is your feature request related to a problem? Please describe.

I'm writing a new language generator and can't find a way to render all models in a single file, each model to a factory function like `ModelType CreateMyModel()`. All functions in a single file.

## Describe the solution you'd like

All models of API (**PetStore**) can be rendered to a single file which named as ApiClient name. For example, **PetStore**Models.txt

## Describe alternatives you've considered

I was experimenting with postProcessAllModels override of my generator, but haven't succeded

## Additional context

Language generator should create at least 2 files. One for all models and one for a client itself.

**Comment by wing328** [comment]
Please try the following:

1) add the following line in the generator (Java class) - `processOpts()`, e.g.
```java
        supportingFiles.add(new SupportingFile("all_model_in_one_file.mustache", "models", "all_modles.rb"));
```
2) Then create `all_model_in_one_file.mustache` with the following mustache tags to go through all models and properties:

```
{{#models}}
{{#model}}
{{classname}}
{{#vars}}
["{{baseName}}"] = {{name}};
{{/vars}}
{{/model}}
{{/models}}
```

**Comment by EvilBeaver** [comment]
Works! Thanks a lot
