### ISSUE TITLE
[REQ][typescript-inversify] Change 'optional' behavior

### ISSUE THREAD

**Issue by siada** [OpenAPITools/openapi-generator#5543]
### Is your feature request related to a problem? Please describe.

When generating models for a .net API, I have to add the [Required] attribute to every model property to avoid the typescript-inversify generator creating view model properties as optional.

The problem with them being optional is typescripts 'undefined by default' approach - you end up with a lot of undefined checks against properties that are **never** going to be undefined.

The problem this causes is the model validator on the .net side is validating properties as [Required] that are actually allowed to be null - but they're defined as [Required] so typescript-inversify doesn't try to make them undefined

## Describe the solution you'd like

Change the default behaviour of declaring a typescript-inversify model property from:

`name?: string`

to a union type:

`name: string | null`

**Comment by amakhrov** [comment]
Isn't [`nullable`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaNullable) what you are looking for?

However, in general I don't see a practical difference between undefined and null. Could you please clarify why do you want to handle them differently in your typescript code?

TSLint even [has a rule](https://palantir.github.io/tslint/rules/no-null-keyword/) that bans using `null` in a codebase (and provides some good reasons for that)

**Comment by siada** [comment]
You might be right that nullable is what I'm after, but that's not supported in the typescript-inversify generator:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-inversify/modelGeneric.mustache#L8

An example of the benefit's I can see to this change(whether it be nullable or changing the behavior of required) is on a view model, I've defined something such as:

    name: string;
    jobTitle: string;

It's perfectly acceptable for these fields to be null, however they will **never** be undefined. The problem I have is that I map from an api model, to this view model for rendering, and the api model generates as:

    name?: string;
    jobTitle?: string;

Which then forces me to do:

    const response: PersonViewModel = {
        name: apiResponse.name || null,
        jobTitle: apiResponse.jobTitle || null
    };

Otherwise the linter throws a bitch fit because `string | undefined` cannot be assigned to `string`.

The ? from the type disappears if I mark the fields as [Required] in my api, but this then breaks the contract because the api will reject if the properties are null, but I actually expect them on certain conditions to be null, they're only [Required] so that typescript-inversify doesn't generate them as ` | undefined`

**Comment by amakhrov** [comment]
Ok, so what I hear is that `typescript-inversify` generator lacks support for `nullable` (unlike some other typescript generators).
Would you want to file a PR fixing that?

**Comment by siada** [comment]
I'll submit the PR and see if that fixes my issue

**Comment by siada** [comment]
PR Submitted #5568

**Comment by macjohnny** [comment]
fixed with #5568
