### ISSUE TITLE
[REQ] Please describe each generator at generator list.

### ISSUE THREAD

**Issue by yuji38kwmt** [OpenAPITools/openapi-generator#5553]
I watched [generators list](https://openapi-generator.tech/docs/generators), but I did't know from the generator name waht code the following generator generate.

#### `python-blueplanet`
I don't know waht code `python-blueplanet` generate.
Thre is no library named `blueplanet`.

#### `python-experimental`
And, I don't know the difference betweeb `python` and `python-experimental`. 
What is "experimental" at `python-experimental`?

**Comment by spacether** [comment]
Our documentation for each generator now has a Metadata section that describes the generator language, type, and a description about that generator.

One can see it at
https://openapi-generator.tech/docs/generators/python-blueplanet#metadata
