### ISSUE TITLE
[BUG][Java] Support for int32 data type in Java

### ISSUE THREAD

**Issue by dev-chirag** [OpenAPITools/openapi-generator#5575]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
Currently, int32 types are converted as Integer types in Java. And since Java doesn't support unsigned numbers, I am getting an error for input values greater than Integer.MAX
##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

```yaml
      format: int32
      type: integer
      minimum: 0
```
##### Command line used for generation

N.A
##### Steps to reproduce

N.A

##### Suggest a fix

Not sure, if int32 can be converted to Long?

**Comment by wing328** [comment]
Use --type-mappings: https://openapi-generator.tech/docs/usage/#type-mappings-and-import-mappings
