### ISSUE TITLE
Getting threading-error when starting generated server on windows

### ISSUE THREAD

**Issue by markusbartel1** [OpenAPITools/openapi-generator#5586]
#### Bug Report Checklist

- Qt 5.14.1 
- MSVC 2017 / x64
- openapi-generator-maven-plugin 4.2.3

##### Description

Command-Line:
cpp-qt5-qhttpengine-server --port 5010 --address 127.0.17.2

Output:
Serving on  "127.0.17.2" : 5010
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QHttpEngine::Server(0x7ff195f988), parent's thread is QThread(0x218ad46dbe0), current thread is QThread(0x218ad43b4c0)

##### openapi-generator version

- openapi-generator-maven-plugin 4.2.3

##### Command line used for generation

via Maven-Plugin

##### Steps to reproduce

- Generate a Qt-Server via Maven-Plugin
- Run server from comman-line -> cpp-qt5-qhttpengine-server --port 5010 --address 127.0.17.2
-> Threading-Errir

##### Related issues/PRs

N/A

##### Suggest a fix

N/A

**Comment by wing328** [comment]
Can you try the petstore server to see if you still encounter the same errors? https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/cpp-qt5-qhttpengine-server/server

Just want to know if it's a spec issue or it happens to all auto-generated server in Windows as well.

**Comment by wing328** [comment]
Closed as there's no update
