### ISSUE TITLE
[BUG] in CodegenModel.java line: 121 .append("isNullable", isEnum) 

### ISSUE THREAD

**Issue by winterbesos** [OpenAPITools/openapi-generator#5607]
as title

`.append("isNullable", isEnum) ` should be `.append("isNullable", isNullable) `

**Comment by wing328** [comment]
@winterbesos thanks for reporting the issue. I wonder if you can file a PR to fix the issue when you've time.

**Comment by winterbesos** [comment]
> as title
> 
> `.append("isNullable", isEnum) ` should be `.append("isNullable", isNullable)`

**Comment by winterbesos** [comment]
oh it has been fixed in 4.2.2. closed it. Thank you for your reply.
