### ISSUE TITLE
I changed my username in github

### ISSUE THREAD

**Issue by michelealbano** [OpenAPITools/openapi-generator#5616]
Hi,
I changed my user id from "micheleISEP" to "michelealbano". Would you update it in the following?
- michelealbano as Members of Technical Committee for Ada in here:
https://github.com/OpenAPITools/openapi-generator#62---openapi-generator-technical-committee
- link to https://github.com/michelealbano as Founding member in here:
https://github.com/OpenAPITools/openapi-generator#63---history-of-openapi-generator

Thank you,
Michele

**Comment by jimschubert** [comment]
@michelealbano I've opened #5625 to rename.
