### ISSUE TITLE
[REQ] How to add the label "Client: C" to the issue or PR

### ISSUE THREAD

**Issue by ityuhui** [OpenAPITools/openapi-generator#5639]
Hello

I notice that some issues (e.g. https://github.com/OpenAPITools/openapi-generator/issues/2338) are added the label "Client: C" by the auto-labeler bot.

But my PR (e.g. https://github.com/OpenAPITools/openapi-generator/pull/5626 ) are never added. Could somebody help me how to add the label to my PR or issue ? I think some key-words in title will trigger the auto-labeler ...

**Comment by ityuhui** [comment]
Hello @wing328 @zhemant @

Do you know this ?

**Comment by zhemant** [comment]
I am not sure but I believe they are added by the core members.

**Comment by ityuhui** [comment]
Thank you @zhemant
