### ISSUE TITLE
[Golang][client] fix linter issues

### ISSUE THREAD

**Issue by grokify** [OpenAPITools/openapi-generator#565]
##### Description

Go client code fails various linters. This issue tracks a number of these for resolution.

1/ Comments

The following type of error looks like simple improvement opportunities for our templates, e.g. `response.mustache`.

```
client/response.go:16:6: exported type APIResponse should have comment or be unexported
client/response.go:33:1: exported function NewAPIResponse should have comment or be unexported
client/response.go:39:1: exported function NewAPIResponseWithError should have comment or be unexported
```

2/ Capitalization Convention

The following is an algorithm update. This will also make the client SDK more consistent because `APIClient` is not `ApiClient` so converting `user_id` to `userID` would make the generated code more consistent as well.

```
examples/scim_users_get/get_scim_users.go:217:3: var userId should be userID
```

3/ `gofmt`

The generated code is not formatted per `gofmt -s` specifications.

I currently generate my code using a shell script with:

```
java -jar openapi-generator-cli.jar generate ...
gofmt -s -w client/*.go
```

I've investigated this and a new `postProcess` hook appears to be needed per https://github.com/OpenAPITools/openapi-generator/issues/507.

##### openapi-generator version

`master` branch /  `3.2.0-SNAPSHOT`

##### OpenAPI declaration file content or url

Example is below for 2/, but 1/ and 3/ exist in any generated code:

https://github.com/grokify/go-ringcentral/blob/master/codegen/swagger_spec.yaml

##### Command line used for generation

Any.

##### Steps to reproduce

1. Generate code
1. Run `golint`
1. Run `gofmt`

##### Related issues/PRs

* https://github.com/OpenAPITools/openapi-generator/pull/555
* https://github.com/OpenAPITools/openapi-generator/issues/507

##### Suggest a fix/enhancement

1/ Add comments
2/ Update capitalization algorithm
3/ Add post generation hook per https://github.com/OpenAPITools/openapi-generator/issues/507

**Comment by grokify** [comment]
Here's the list of `commonInitialisms` used by Go Lint:

https://github.com/golang/lint/blob/master/lint.go#L749-L788

```go
var commonInitialisms = map[string]bool{
	"ACL":   true,
	"API":   true,
	"ASCII": true,
	"CPU":   true,
	"CSS":   true,
	"DNS":   true,
	"EOF":   true,
	"GUID":  true,
	"HTML":  true,
	"HTTP":  true,
	"HTTPS": true,
	"ID":    true,
	"IP":    true,
	"JSON":  true,
	"LHS":   true,
	"QPS":   true,
	"RAM":   true,
	"RHS":   true,
	"RPC":   true,
	"SLA":   true,
	"SMTP":  true,
	"SQL":   true,
	"SSH":   true,
	"TCP":   true,
	"TLS":   true,
	"TTL":   true,
	"UDP":   true,
	"UI":    true,
	"UID":   true,
	"UUID":  true,
	"URI":   true,
	"URL":   true,
	"UTF8":  true,
	"VM":    true,
	"XML":   true,
	"XMPP":  true,
	"XSRF":  true,
	"XSS":   true,
}
```

**Comment by wing328** [comment]
We've added file post-processing hook so I think this can be closed. 

If that won't meet your requirement, please let us know and we can reopen the issue.

**Comment by olvlvl** [comment]
@wing328 I see this issue has been closed a long time ago, but I'm facing the same issue with the likes of `Id`, `MenuId`… also, although I'm running the command with `GO_POST_PROCESS_FILE="gofmt -w"`, the files are not properly formatted.

> We've added file post-processing hook so I think this can be closed.

Can you provide a link to the documentation to use that hook?

PS: I'm using the generator `go-server`.

**Comment by sbnarra** [comment]
Looks like this is a generic option from the openapi cli, see GO_POST_PROCESS_FILE in https://openapi-generator.tech/docs/file-post-processing/

Though it doesn't look like it's clearly documented anywhere but here's the source code, you can see it simply executes the command on the host in #postProcessFile so in theory you can add anything you like here.

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractGoCodegen.java

@olvlvl i think you need to use the full path like /usr/local/bin/gofmt (just taking that from the log line)
