### ISSUE TITLE
[BUG] [DART] Wrong structure with wrong paths

### ISSUE THREAD

**Issue by SimonIT** [OpenAPITools/openapi-generator#5650]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I wanted to generate a dart lib for flutter with the provided swagger yaml config and the provided code generator config. The problem is, that the api and model directories are outside of the lib directory, which is not valid. Another problem is, that the path to the dart files within the `part` includings inside the _api.dart_ are not changed to match the directory structure.
![dart generation](https://user-images.githubusercontent.com/11720038/77195850-9731d500-6ae2-11ea-85c6-67d2500a2552.png)

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

https://code.wbt-solutions.de/sbu/openproject_dart_sdk/raw/branch/master/openProject_swagger.yaml
https://code.wbt-solutions.de/sbu/openproject_dart_sdk/raw/branch/master/swagger-codegen-config.json

##### Command line used for generation

I used the command `java -jar .\openapi-generator-cli-4.2.3.jar generate -g dart -i openProject_swagger.yaml  -o openproject_dart_sdk/ -c .\swagger-codegen-config.json` inside the Windows Powershell.

##### Steps to reproduce

Execute the command with the provided configs.

##### Related issues/PRs

Haven't found any.

##### Suggest a fix

Move the _org_ directory inside _lib_ and correct the path to the model and api dart files.

**Comment by gasugesu** [comment]
I couldn't repro this.
You have tried this in any container or vm like docker with volume settings?

**Comment by SimonIT** [comment]
I have no docker setup available, but I tried it on Xubuntu and again on my Windows and both have the same org directory in the root of the project with the api and models.
![image](https://user-images.githubusercontent.com/11720038/77627924-ee530200-6f47-11ea-89df-ccaf60c9ef58.png)
![image](https://user-images.githubusercontent.com/11720038/77627967-fe6ae180-6f47-11ea-82a8-a0bd6a5a89c0.png)
Do you used my provided `swagger-codegen-config.json`?

**Comment by gasugesu** [comment]
@SimonIT 
Sorry, I forgot to use your provided code.
With your config file, I have reproduced your problem.

OK, I have checked your config file, and it turns out that your config file can not be used in code generation of Dart Lang.
Please check config option with below command.
`java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar config-help -g dart`
If you change `dart` into `java` in this command, you can see you used wrong option.
Config option of dart code generation is total different from java.

Please use appropriate options of dart.

**Comment by SimonIT** [comment]
Oh okay, I thought these options were not language dependant and only applied if supported
