### ISSUE TITLE
[CORE] Referenced Enums incorrectly tagged isEnum = false

### ISSUE THREAD

**Issue by LukeMarlin** [OpenAPITools/openapi-generator#5676]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

With a referenced enum (meaning, a $ref pointing to an enum), a model that uses it in a property will have `isEnum = false`. Following a discussion with @jimschubert on slack, it seems that it should be `true`.

Expected output: a model property refering to an enum should have `"isEnum" : "true"`
Acutal output: `"isEnum" : "false"` (more precisely, everything seems to be false, but `allowableValues` are present: https://gist.github.com/LukeMarlin/1c521cdafe4e7a885e0a79ba221da135#file-extract-of-acutal-output-txt)

##### openapi-generator version

branch master, commit [47e24af369477](https://github.com/OpenAPITools/openapi-generator/commit/47e24af3694770dbddfc00b40c4d9bb049d28982)

Based on the related issues I've found, this might exist since one or two years already.

##### OpenAPI declaration file content or url

https://gist.github.com/LukeMarlin/1c521cdafe4e7a885e0a79ba221da135#file-gistfile1-yaml

##### Command line used for generation

`java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i enumSample.yaml -g java -o any`

Note: I also tried with a generator I'm writing and I'm not modifying `isEnum`, that's why I labelled this CORE. Also, there are existing issues for other generators.

##### Steps to reproduce

Run the command line with the given file and -DdebugModels to confirm that `isEnum` is `false`

##### Related issues/PRs

Actually, there are quite some existing issues, but none reached an actual conclusion nor had an official statement about the situation. It is clear that the situation is at least confusing.

Open issues:
https://github.com/OpenAPITools/openapi-generator/issues/5610
https://github.com/OpenAPITools/openapi-generator/issues/2645
https://github.com/OpenAPITools/openapi-generator/issues/1783
https://github.com/OpenAPITools/openapi-generator/issues/1559

Also, possibly relevant PR merged by error and reverted:
https://github.com/OpenAPITools/openapi-generator/pull/3186 by @jmini 

It seems that it's supposed to be included in 4.1.0, but there is no link to the actual commit. It looks like this was incorrectly marked as "included in 4.1.0" because of the merged by error situation.

##### Suggest a fix

Based on the other issues, it might be a case of backward compatibility stuff. If this is the case, it would be nice to at least know the preferred way to detect a referenced enum. For instance, is the solution proposed [here](https://github.com/OpenAPITools/openapi-generator/issues/2645#issuecomment-521712466) good enough, will that cover corner cases?

If this is not problematic, I'd rather have `isEnum = true`, allowing us to easily create the models instead of using a combination of `if`s

**Comment by LukeMarlin** [comment]
I can't edit labels, but "Client: Java" is probably not correct here as mentioned in the issue body

**Comment by timtraversy** [comment]
Yes, seeing this on Swift5 as well, not unique to Java.

**Comment by LukeMarlin** [comment]
Still present in most recent commit (748190a0498d2c8a6005bb13eabc6112b9517684).

**Comment by LukeMarlin** [comment]
As a side note, I just ran into a case where checking for `{{^allowableValues.empty}}` isn't good: an array where items are a referenced enum. Because in that case, `allowableValues` is not empty, so I had to add {{^isContainer}}`.

Baseline: this is really hard to know for sure whether or not a property is a referenced enum. And I'm sure there are other corner cases I've not seen yet

**Comment by LukeMarlin** [comment]
In the end, this wasn't good enough either, and I did the same fix that exists for AbstractCSharp and AbstractFSharp generator: we modify ourselves the `isEnum` property in `postProcessAllModels`.
Would that be OK to create `CodegenProperty.isReferencedEnum` and set it in core itself? That way there will be no issue of backward compatibility, and we can drop big chunks in generators.

(Also, please can someone change the labels to `core` instead of `java`?)

**Comment by rivancic** [comment]
With this PR https://github.com/OpenAPITools/openapi-generator/pull/12860 we have `isInnerEnum `on `CodegenProperty `so it should be easier to distinguish between inline and referenced enum https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L3687. (I think inline and inner definition is mixed up, see inline word is used in comment, but later we have isInnerEnum property.)

**Comment by flowstef** [comment]
This is actually giving me trouble when trying to re-use enums rather than defining them inline multiple times.
I'm using `python-fastapi` and my issue is related to but different from [this](https://github.com/OpenAPITools/openapi-generator/issues/4300) and I assume this is the core issue.

For references enum properties, I end up getting empty data classes (without properties) instead of enums.

Hoping the pull request makes it into the next release.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/13880 offering a way to address the issue so that users can update the template accordingly.

**Comment by wing328** [comment]
closed via https://github.com/OpenAPITools/openapi-generator/pull/13880
