### ISSUE TITLE
[BUG] typescript-axios can't pass date-time as strings

### ISSUE THREAD

**Issue by zanonnicola** [OpenAPITools/openapi-generator#5683]
##### Description

I have this schema definition:

```
"payPeriodStart": {
      example: "2020-02-12T06:00:00Z",
      required: true,
      description: "Start of the pay period",
      schema: {
        type: "string",
        format: "date-time",
      },
    }
}
```

When the type have a `date-time` format, the interface generated says that it requires a `Date` object.
Should be a `string.`

```ts
/**
         * 
         * @param {string} a
         * @param {Date} payPeriodStart Start of the pay period
         * @param {Date} payPeriodEnd End of the pay period
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reportsControllerGetRepaymentInstructionReport(a: string, payPeriodStart: Date, payPeriodEnd: Date, options?: any): (axios?: AxiosInstance, basePath?: string) => AxiosPromise<string> {
```

I tried to use add `--type-mappings DateTime=string` to the CLI but then it will convert both Date and date-time to string, regardless.

This happens in typescript-axios generator

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

```json
{
"parameters": [
{
"name": "payPeriodStart",
"in": "query",
"schema": {
"type": "string",
"format": "date-time"
},
"example": "2020-02-12T06:00:00Z",
"required": true,
"description": "Start of the pay period"
}
]
}
```

##### Command line used for generation

```bash
java  -Dcolor -jar openapi-generator-4.2.3.jar generate  -i http://localhost:8080/openapi.json -g typescript-axios --remove-operation-id-prefix -t ../src/api_client/typescript-axios -c ../src/api_client/config.json -o ../src/api_client
```

##### Related issues/PRs

Not sure if this is the intended behaviour but maybe the mapping in the CLI should recognise the difference between `date` and `date-time`.

Thanks!

**Comment by amakhrov** [comment]
Mapping OAS `date` and `date-time` types to Typescript `Date` object was an error that is fixed in `master` (and will be released in 4.3.0 soon).

Please see the PR with the fix for more details: https://github.com/OpenAPITools/openapi-generator/pull/5314

The recommendation in the meantime is to set `--type-mappings DateTime=string` and do the date serialization in the app code instead.

**Comment by zanonnicola** [comment]
Thanks @amakhrov that's great news!

I tried to use `--type-mappings DateTime=string` with the CLI but it converted all the types defined and `Date` to string. Not just `date-time`.

**Comment by amakhrov** [comment]
Both `date` and `date-time` have the same issue - they are not properly supported by typescript-axios generator. Hence the right move is keep them as strings (using `--type-mappings`), and do conversion in the app code as needed.

**Comment by zanonnicola** [comment]
Got it! Thanks for the quick reply and fix!
