### ISSUE TITLE
Problem with kotlin keywords as enum values 

### ISSUE THREAD

**Issue by Pe-te** [OpenAPITools/openapi-generator#5689]
I got this output from the generator, but Android Studio complains about external being a keyword in kotlin. Unfortunatelly we have a legacy API and cannot change the field name there.

    enum class Type(val value: kotlin.String){
        @SerializedName(value="icon")  icon("icon"),
        @SerializedName(value="external")  external("external");
    }

macOS, homebrew, openapi-generator 4.2.3

**Comment by stapel** [comment]
Should be fixed, duplicate of https://github.com/OpenAPITools/openapi-generator/issues/5221

**Comment by toXel** [comment]
Follow-up on this issue: `open` is also a reserved Kotlin keyword. But it is not written in backticks when generating an enum value called "open" so this is still a problem on Generator version 4.3.0.
