### ISSUE TITLE
[BUG] Missing dependencies in java generator

### ISSUE THREAD

**Issue by mariomac** [OpenAPITools/openapi-generator#5690]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When I try to run the generated gradle, some dependencies are missing. I get some errors like the following:

```
/path/File.java:xx: error: package org.openapitools.jackson.nullable does not exist
import org.openapitools.jackson.nullable.JsonNullableModule;
```

Which is solved by adding the following line to the `dependencies` section:

```
    compile "org.openapitools:jackson-databind-nullable:0.2.1"
```

This is the configuration of the gradle task that generates the failing gradle script:

```groovy
task openApiJavaClient(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    generatorName = "java"
    inputSpec = specFile
    outputDir = generatedSubproject
    invokerPackage = "com.foo"
    modelPackage = "com.foo"

    configOptions = [
                      dateLibrary    : "java8",
                      library        : "native",
                      artifactId     : "java-api-client",
                      artifactVersion: project.version,
                      java8          : "true",
    ]
    systemProperties = [
            modelDocs: "false"
    ]
}

javadoc {
    failOnError = false
}

jar.dependsOn tasks.openApiJavaClient
```

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

./gradlew clean build

##### Steps to reproduce

./gradlew clean build

##### Related issues/PRs

It seems this issue was fixed in v4.1.2 but it happens again in v4.2.3:

https://github.com/OpenAPITools/openapi-generator/pull/3793

##### Suggest a fix

N/A

**Comment by jhandguy** [comment]
I am also facing this issue 👍

**Comment by mariomac** [comment]
@jhandguy you just have to add the following lines to the generated gradle project:
```gradle
dependencies {
    compile "org.openapitools:jackson-databind-nullable:0.2.1"
}
```

If you need to automate this task because the client project is automatically generated and built from other gradle parent project, you can include this within the task of the parent project that needs to use the openapi gradle subproject:
```gradle
    doFirst {
        // Fix for issue: https://github.com/OpenAPITools/openapi-generator/issues/5690
        def f = new File("$generatedSubproject/build.gradle")
        f.append("""
dependencies {
    compile "org.openapitools:jackson-databind-nullable:0.2.1"
}
""")
    }
```

**Comment by egemenvardar** [comment]
I also encountered the same issue with OpenAPI generator v4.3.0 in a Spring Boot project. It could be reproduced by using the Pet API and the following plugin configuration:
```
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>4.3.0</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>spring</generatorName>
                <configOptions>
                    <sourceFolder>src/gen/java/main</sourceFolder>
                    <interfaceOnly>true</interfaceOnly>
                    <java8>true</java8>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by kierans** [comment]
@wing328 Given you merged the original fix for this (https://github.com/OpenAPITools/openapi-generator/pull/3793) do you know what happened to have it dropped? I'm using 4.3.0

I can fix this, but it might be better to know more about why the regression happened.

Should this issue also be assigned to someone?

**Comment by wing328** [comment]
> I can fix this, but it might be better to know more about why the regression happened.

can you please submit a PR to start with?

would be great if you can use `git bisect` to identify the commit causing the issue?

moving forward, it will be better to test it in the CI so as to catch the issue moving forward.

**Comment by kierans** [comment]
Doing some more investigation, looking at the [blame log](https://github.com/OpenAPITools/openapi-generator/blame/master/modules/openapi-generator/src/main/resources/Java/build.gradle.mustache) it seems that the template snippet for `compile "org.openapitools:jackson-databind-nullable:0.2.1"` is still there on `master` (from https://github.com/OpenAPITools/openapi-generator/commit/ad6c8321621dd41e1dd7412cd00b12c6e480918) and was released in `4.3.0`. Pulling the 4.3.0 JAR out of my Gradle cache and looking inside, the `Java/build.gradle.mustache` template is correct. Yet when [generating Java code](https://github.com/kierans/openapi-generator-java-sample/blob/master/build.gradle#L19) (using Gradle plugin `id 'org.openapi.generator' version '4.3.0'`) the resulting `build.gradle` does not match the template at all.

I've created a sample project https://github.com/kierans/openapi-generator-java-sample

**Comment by kierans** [comment]
For those using Gradle here's a quick snippet to see what's on the `buildscript` classpath so that you can see what version of openapi JARs Gradle is using to generate the code

```gradle
task dumpScriptClasspath {
    doLast {
        buildscript.configurations.classpath.each { println it }
    }
}
```

**Comment by Patouche** [comment]
This should be fix by #2901 .

In the attached PR, I add a property to remove `org.openapitools:jackson-databind-nullable` from classpath.

I also try to add this dependency in the generated `build.gradle` when it was missing.

**Comment by gausnes** [comment]
I'm seeing this as well using `4.3.1`. #2901 appears to just be cleaning up this import is not used. Model generation is still failing if properties are flagged with `nullable: true`

**Comment by Patouche** [comment]
@gausnes : In fact, it is more than that.

The may objective of #2901 was to remove a jar (and also all associated imports) from the generated code. When I made this PR, I ensure that all dependencies was properly in the classpath (pom.xml or build.gradle) when you enable the property `openApiNullable`. In this case, I noticed that the dependencies were missing and I added.

In the future release of openapi-generator (the 5.0.0), this should be fix.

**Comment by black-snow** [comment]
I'm playing around with latest version 4 and `5.0.0-beta2` and I hade to manually add the following dependencies:

* GSON (I try 2.8.6)
* swagger-annotations (I try 1.6.2)
* findbugs / jsr305 (I try 3.0.2

```
	implementation 'com.google.code.gson:gson:2.8.6'
	implementation group: 'io.swagger', name: 'swagger-annotations', version: '1.6.2'
	implementation 'com.google.code.findbugs:jsr305:3.0.2'
```

**Comment by black-snow** [comment]
Now I'm trying `webclient` instead of `resttemplate` and again dependencies are missing and I don't know which yet:

```
org.apache.commons.logging.*
org.springframework.core.*
org.springframework.http.*
org.springframework.util.*
org.springframework.web.*
reactor.core.*
```

**Comment by wing328** [comment]
I tested `resttemplate` in the latest master with [petstore spec](https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) and could run `mvn clean package`, `gradle build` without issues.

**Comment by wing328** [comment]
@black-snow I've filed https://github.com/OpenAPITools/openapi-generator/pull/7777 to fix the missing dependency issue in Java `webclient` client

**Comment by wing328** [comment]
If there's still an issue with missing dependencies, please PM me via Slack channel, which can be found in the project's README.

**Comment by scothale** [comment]
Could this issue be reworded to "Plugin tries to compile the separate generated project when it should only generate the project"?

**Comment by black-snow** [comment]
@scothale could you elaborate that?

**Comment by bodograumann** [comment]
Just wanted to note, that this issue might still occur in the JavaJaxRS code generator, when no `type: …` field is given for a property of a schema. The JsonNullable is not actually used in code, but it is imported and no dependency for it is added to the pom.xml.
We just added the missing type and everything was fine again.

**Comment by rupert-jung-mw** [comment]
Still facing `package org.openapitools.jackson.nullable does not exist` with 7.2.0

**Comment by wiesnery** [comment]
This is still an issue in 7.3.0 but can be solved with the property: `openApiNullable=false`

**Comment by durcon** [comment]
Why is this issue closed? The bug is still there. Although `openApiNullable=false` seems to work.

**Comment by winrid** [comment]
With `openApiNullable=false` it still imports `import com.fasterxml.jackson.databind.util.StdDateFormat;` which is not defined in dependencies.
