### ISSUE TITLE
[REQ] [Qt5][client][server] Use a particular DateTime format during saving model as a JSON string

### ISSUE THREAD

**Issue by DevASG** [OpenAPITools/openapi-generator#5708]
### Is your feature request related to a problem? Please describe.

I'm using c++ Qt5 client and server in a network mediator application.
The app receives JSONs, collects them and resends to the Java server using a schedule.
The Java server is generated with OpenAPI also.
The problem is there is a DateTime format mismatch between Qt5 [client/server] and JAVA.
- Java server excepts Jsons with such DateTime format:
 with 
 "2017-07-08T22:35:29.771Z" - suffix Z, means UTC time
 "2017-07-08T22:35:29+02:30" - time zone
 "2017-07-08T22:35:29.771+02:30" - with a suffix and a timezone
- Qt5 generates by default in such way:
" 2017-07-08T22:35:29" - withnout Z and a timezone.

## Describe the solution you'd like

Currently, QDateTime transforms into a string using a Qt::ISODate format.
_QString toStringValue( const QDateTime& value ) {
    // ISO 8601
    return value.toString( Qt::ISODate );
}_

It would be useful for me to set a particular DateTime format option during code generation.
Example for cpp-qt5-client:
useQDateTimeFormat="yyyy-MM-ddTHH:mm:ss.zzzZ";
Smth like this:
_QString const DateTimeFormat = "yyyy-MM-ddTHH:mm:ss.zzzZ";
QString toStringValue( const QDateTime& value ) {
    return value.toString( QtDateTimeFormat );
}_

**Comment by etherealjoy** [comment]
@DevASG 
> useQDateTimeFormat="yyyy-MM-ddTHH:mm:ss.zzzZ";

I tried this and this does seem to work. **QDateTime::toString**  does not support these

```
"2017-07-08T22:35:29.771Z" - suffix Z, means UTC time
"2017-07-08T22:35:29+02:30" - time zone
"2017-07-08T22:35:29.771+02:30" - with a suffix and a timezone
```
[See here](https://doc.qt.io/qt-5/qtime.html#toString)
`Z` is not supported, instead `t` is supported but it only shows `CET` or `PST` or something.

It is lame. It would need to build a custom solution.

**Comment by DevASG** [comment]
```
 namespace OpenAPI {
 
+QString const DateTimeFormat = "yyyy-MM-ddTHH:mm:ss.zzzZ";
-
 QString toStringValue(const QString &value) {
     return value;
 }
 
 QString toStringValue(const QDateTime &value) {
     // ISO 8601
+    return value.toString(DateTimeFormat);
-    return value.toString("yyyy-MM-ddTHH:mm:ss[Z|[+|-]HH:mm]");
 }
 
 QString toStringValue(const QByteArray &value) {
     return QString(value);
 }
@@ -71,11 +69,11 @@ QString toStringValue(const OAIHttpFileElement &value) {
 QJsonValue toJsonValue(const QString &value) {
     return QJsonValue(value);
 }
 
 QJsonValue toJsonValue(const QDateTime &value) {
+    return QJsonValue(value.toString(DateTimeFormat));
-    return QJsonValue(value.toString(Qt::ISODate));
 }
 
 QJsonValue toJsonValue(const QByteArray &value) {
     return QJsonValue(QString(value.toBase64()));
 }
@@ -124,11 +122,11 @@ bool fromStringValue(const QString &inStr, QString &value) {
 
 bool fromStringValue(const QString &inStr, QDateTime &value) {
     if (inStr.isEmpty()) {
         return false;
     } else {
+        auto dateTime = QDateTime::fromString(inStr, DateTimeFormat);
-        auto dateTime = QDateTime::fromString(inStr, "yyyy-MM-ddTHH:mm:ss[Z|[+|-]HH:mm]");
         if (dateTime.isValid()) {
             value.setDate(dateTime.date());
             value.setTime(dateTime.time());
         } else {
             qDebug() << "DateTime is invalid";
@@ -229,11 +227,11 @@ bool fromJsonValue(QString &value, const QJsonValue &jval) {
 }
 
 bool fromJsonValue(QDateTime &value, const QJsonValue &jval) {
     bool ok = true;
     if (!jval.isUndefined() && !jval.isNull() && jval.isString()) {
+        value = QDateTime::fromString(jval.toString(), DateTimeFormat);
-        value = QDateTime::fromString(jval.toString(), Qt::ISODate);
         ok = value.isValid();
     } else {
         ok = false;
     }
     return ok;
```

**Comment by DevASG** [comment]
**Let me shed light on problem details using a real example.**

Currently, after serialization an OpenAPIObject it looks like **"2020-03-30T08:59:31[Z|[+|-]08:59]"**.
This view doesn't reflect any ISO DateTime format!

A possible correct ISO::DateTime view is **"2020-03-30T08:59:31.474Z" (UTC time format)**.
**This view can be generated just after making small changes in several lines in OAIHelpers.cpp.**

```
 namespace OpenAPI {
 
+QString const DateTimeFormat = "yyyy-MM-ddTHH:mm:ss.zzzZ";
-
 QString toStringValue(const QString &value) {
     return value;
 }
 
 QString toStringValue(const QDateTime &value) {
     // ISO 8601
+    return value.toString(DateTimeFormat);
-    return value.toString("yyyy-MM-ddTHH:mm:ss[Z|[+|-]HH:mm]");
 }
 
 QString toStringValue(const QByteArray &value) {
     return QString(value);
 }
@@ -71,11 +69,11 @@ QString toStringValue(const OAIHttpFileElement &value) {
 QJsonValue toJsonValue(const QString &value) {
     return QJsonValue(value);
 }
 
 QJsonValue toJsonValue(const QDateTime &value) {
+    return QJsonValue(value.toString(DateTimeFormat));
-    return QJsonValue(value.toString(Qt::ISODate));
 }
 
 QJsonValue toJsonValue(const QByteArray &value) {
     return QJsonValue(QString(value.toBase64()));
 }
@@ -124,11 +122,11 @@ bool fromStringValue(const QString &inStr, QString &value) {
 
 bool fromStringValue(const QString &inStr, QDateTime &value) {
     if (inStr.isEmpty()) {
         return false;
     } else {
+        auto dateTime = QDateTime::fromString(inStr, DateTimeFormat);
-        auto dateTime = QDateTime::fromString(inStr, "yyyy-MM-ddTHH:mm:ss[Z|[+|-]HH:mm]");
         if (dateTime.isValid()) {
             value.setDate(dateTime.date());
             value.setTime(dateTime.time());
         } else {
             qDebug() << "DateTime is invalid";
@@ -229,11 +227,11 @@ bool fromJsonValue(QString &value, const QJsonValue &jval) {
 }
 
 bool fromJsonValue(QDateTime &value, const QJsonValue &jval) {
     bool ok = true;
     if (!jval.isUndefined() && !jval.isNull() && jval.isString()) {
+        value = QDateTime::fromString(jval.toString(), DateTimeFormat);
-        value = QDateTime::fromString(jval.toString(), Qt::ISODate);
         ok = value.isValid();
     } else {
         ok = false;
     }
     return ok;
```

**Comment by etherealjoy** [comment]
> Currently, after serialization an OpenAPIObject with QDateTime field indise will look like "2020-03-
> 30T08:59:31[Z|[+|-]08:59]".
> This view doesn't reflect any ISO DateTime format!

This one I fixed here already.
https://github.com/OpenAPITools/openapi-generator/compare/master...etherealjoy:serialization_settings

> A possible correct ISO::DateTime view is "2020-03-30T08:59:31.474Z" (UTC time format).

This did not work. But I did provide a way to set the string though.

**Comment by DevASG** [comment]
@etherealjoy 
Looks good to me, but as I see this patch is only for cpp-qt5-client _(
modules/openapi-generator/src/main/resources/cpp-qt5-client/helpers-body.mustache)_.
I think this patch must be applied to qt5-server also.
