### ISSUE TITLE
[REQ] [JAVA - FEIGN CLIENT] Allow selection of the feign httpClient

### ISSUE THREAD

**Issue by gaetPax** [OpenAPITools/openapi-generator#5709]
An improvement to the feign client generation would be to be able to select the HttpClient of the generated Feign client.
Feign modules are present to provide different http client implementation for your feign client.

Apache httpClient: https://github.com/OpenFeign/feign/tree/master/httpclient
OkHttp, Ribbon, etc....: https://github.com/OpenFeign/feign#okhttp

Use of different httpClient implementations becomes necessary in case your client requires features that are not supported by the default.
A problem i have in my project is that the default httpClient does not support Http PATCH method out of the box. 

Ideal solution would be to add a 'feignHttpClient' property to the configOptions in order to set the desired feign httpClient implementation and update the templates accordingly.
Selection could be initially limited to the Apache httpClient (which supports PATCH) and extend it progressively to the other implementations.

**Comment by GianniGiglio** [comment]
HI,

Do we have an update regarding this pull request? Any chance this could be included in the next release?

Thanks

**Comment by gaetPax** [comment]
Support to better HttpClient has been added by #8484 which sets OkHttp as the default feign client, which should be the most complete one (even better than ApacheHttpClient) and capable to handle most of the use cases.
[Comparison [here](https://www.mocklab.io/blog/which-java-http-client-should-i-use-in-2020/)]
So adding the choice of select the HttpClient implementation could be really not necessary and just adding complexity to the source code.
