### ISSUE TITLE
[BUG] URI encoded $ref not properly decoded

### ISSUE THREAD

**Issue by SimonIT** [OpenAPITools/openapi-generator#5720]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I wanted to generate a dart lib for flutter with the provided swagger yaml config. The problem is, that some of the generated class names contain spaces which are not valid. After writing a fix for it (PR #5693), I used swagger to edit the yaml. Swagger suggests to use `%20` instead of normal spaces inside `$ref` definition links because it's an URI (see [docs](https://swagger.io/docs/specification/using-ref/)). Now I got the problem, that some class names contain `%20`.

##### openapi-generator version

4.2.3

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/wbt-solutions/openproject_dart_sdk/master/openProject_swagger.yaml

##### Command line used for generation

I used the command `java -jar .\openapi-generator-cli-4.2.3.jar generate -g dart -i openProject_swagger.yaml  -o openproject_dart_sdk/` inside the Windows Powershell.

##### Steps to reproduce

Execute the command with the provided config and look for example in the *model\work_package.dart*.

##### Related issues/PRs

Haven't found any.

##### Suggest a fix

Properly decode the $ref attribute as URI.

**Comment by SimonIT** [comment]
I don't know, why the bot added the dart label. The problem is for every language, I think. I tried also Java and there is the problem, too.
I would also provide a PR for fixing this problem, but I can't find the code for parsing the open api config. If someone would give me a hint, I will try to fix this.

**Comment by bzmw** [comment]
Having a similar issue here: https://github.com/PagerDuty/api-schema/issues/82

Was there any resolution that you found @SimonIT

**Comment by SimonIT** [comment]
I discovered now that if you replace this line
https://github.com/OpenAPITools/openapi-generator/blob/c9939a2754f22aa747e51d45398aa51a3211e86f/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/ModelUtils.java#L389
with 
```java
        return URLDecoder.decode(ref);
```
the name gets properly encoded. I will make a PR

**Comment by SimonIT** [comment]
Okay, I tested it myself with the provided command from your issue and this didn't fix your problem.
I think your problem is, that `#/paths/` is nowhere handled by the generator because IntelliJ couldn't find any occurrences of it in the whole project. I think you have to change you specification or you make a PR which solves this.
