### ISSUE TITLE
[BUG][TYPESCRIPT-AXIOS] Undeclared package dependency for generated typescript-axios apis 

### ISSUE THREAD

**Issue by PierreREN** [OpenAPITools/openapi-generator#5729]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Does 'url' mentioned in all generated api files refer to [https://www.npmjs.com/package/url](url) as there seems no other url package in npm library? And if so, when building my project using "npm run build" which actually refers to "vue-cli-service build", such error occurs:
`Could not find a declaration file for module 'url'. 'XXX/node_modules/url/url.js' implicitly has an 'any' type. Try npm install @types/urlif it exists or add a new declaration (.d.ts) file containingdeclare module 'url';`
How do you solve such a problem? 
##### openapi-generator version
openapi-generator-cli-4.2.3

**Comment by PierreREN** [comment]
Problem solve by "npm i @types/node" which wasn't proposed by HBuilderX but VS Code.
Stupid question.

**Comment by alenf** [comment]
Installing @types/node didn't resolve this problem for me. But when I replaced 
`import * as globalImportUrl from 'url';` 
in generated code with:
`const globalImportUrl = require('url')`
error has disappeared.

**Comment by JamesFaix** [comment]
I experienced the same thing as @alenf. I propose this issue be reopened.
