### ISSUE TITLE
[REQ] [Rust Server] Support OpenSSL 1.1.1

### ISSUE THREAD

**Issue by sverch** [OpenAPITools/openapi-generator#5733]
### Is your feature request related to a problem? Please describe.

I'm trying to use the `rust-server` code generator, but my system has the latest version of OpenSSL:

```
$ openssl version
OpenSSL 1.1.1  11 Sep 2018
```

This causes the build to fail with this error:

```
$ cargo build
error: failed to run custom build command for `openssl v0.9.24`

Caused by:
  process didn't exit successfully: `/home/sverch/projects/rust-server/generated/target/debug/build/openssl-8d20803225a7b5a7/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to detect OpenSSL version', /home/sverch/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-0.9.24/build.rs:16:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because this code depends on a version of the rust `openssl` package that doesn't support OpenSSL 1.1.1.

## Describe the solution you'd like

Update packages so that the new rust `openssl` package with 1.1.1 support is pulled in.

**Comment by chriskolenko** [comment]
Can confirm. Just got this same issue.

**Comment by richardwhiuk** [comment]
This should be fixed in the 5.0 release, which upgrades rust-openssl to 0.10.

**Comment by richardwhiuk** [comment]
(It's fixed by https://github.com/OpenAPITools/openapi-generator/pull/5564 )

**Comment by Foorack** [comment]
If this has been fixed, can this issue be closed?
