### ISSUE TITLE
[REQ] Typescript: Generate pure models as Typescript interfaces

### ISSUE THREAD

**Issue by jepetko** [OpenAPITools/openapi-generator#5754]
### Problem to solve

The currently available generators for Typescript are:
* framework agnostic
* specific for the direction of the HTTP communication (e.g. client API)

However, there are situations in which API is not needed or provided manually. In this case, pure Typescript interfaces for describing the model are enough.

## Generate pure Typescript models

usual Typescript model (generated by `typescript-node`):

```
import { RequestFile } from '../api';

export class Dog {
    'age': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dog",
            "baseName": "dog",
            "type": "number"
        }];

    static getAttributeTypeMap() {
        return Balance.attributeTypeMap;
    }
}
```

requested Typescript model (to be implemented):

```
export interface Dog {
    'age': number;
}
```

## Current alternatives

One of the current generators, for instance `typescript-node` can be used. However, the model has to be cleaned up: the line `import { RequestFile } from '../api';` needs to be removed (because the API part is not used) + also the `discriminator` is confusing in that case.

**Comment by amakhrov** [comment]
@jepetko perhaps you could use models produced by generators like `typescript-anglar` or `typescript-axios` (with separate models and apis option turned on). Generated models do not refer any http-related code, and won't require the cleanup you describe.

**Comment by jepetko** [comment]
works well with this command:

```
openapi-generator generate -i swagger/consumption-adapter-api.yaml -g typescript-angular -o swagger-to-types --additional-properties=stringEnums=true
```

* generates interfaces
* no meta data generated (such as attribute maps)
* API generated but contained in a separated folder
* generates native enums (`stringEnums=true`) instead of constant

👍

**Comment by sfc-gh-jchernandez** [comment]
I am still having this very same issue when executing

```
docker run --rm -v "${PWD}/lsp_api_contracts:/lsp_api_contracts" openapitools/openapi-generator-cli generate \
		--global-property models \
		-p modelPackage=lsp_api_contracts \
		-i /lsp_api_contracts/lsp_api_contracts.yaml \
		-g typescript-node \
		-o /lsp_api_contracts/auto_generated/ts
```

I am using the latest openapitools/openapi-generator-cli docker img

I get `import { RequestFile } from './models';` line and no models.ts file
