### ISSUE TITLE
Generated Lumen code can contain dots in routes

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#576]
##### Description

According to @philip 

> Lumen does not allow . in routes. The generator allows them without warning. Dots in URLs are common though, for example /api/v1.1/, but Lumen insists on not allowing them.
> Confirmation about dots being disallowed in routes: laravel/framework#6180

The current behaviour is to throw an exception if the path contains dot so that the user is aware of the known limitation.

##### openapi-generator version

Latest master

##### Related issues/PRs

Ref: https://github.com/swagger-api/swagger-codegen/issues/6897

**Comment by ackintosh** [comment]
> Lumen does not allow . in routes

It is due to the PHP built-in web server. ( not related to Lumen )

```php
// app/Http/routes.php
$app->get('/v2/foo.bar/pet/{petId}', 'PetApi@getPetById');
```

#### Invoke built-in server without specifying router script

```bash
$ pwd
~/openapi-generator/samples/server/petstore/php-lumen/lib/public
$ php -S localhost:9999
Listening on http://localhost:9999
```

- 404 Not Found

```bash
$ curl -D - http://localhost:9999/v2/foo.bar/pet/123
HTTP/1.1 404 Not Found
```

#### Invoke built-in server with router script

the sample below specifies the index.php as a router script.

```bash
$ php -S localhost:9999 index.php
Listening on http://localhost:9999
```

- 200 OK 👌 

```bash
$ curl -D - http://localhost:9999/v2/foo.bar/pet/123
HTTP/1.0 200 OK
```

**Comment by ackintosh** [comment]
#### Quick idea

1. Add the sample command runs built-in server like below to [the README](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/php-lumen/lib/readme.md).

```
### Running the generated server stub

php -S localhost:8080 public/index.php
```

2. Remove [the codes checking dots contained in path](https://github.com/ackintosh/openapi-generator-1/blob/27426f7b522c1b55f6ebe6c90d41d77e3c7ab589/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PhpLumenServerCodegen.java#L124-L130).

**Comment by wing328** [comment]
@ackintosh thanks for the explanation. I liked your ideas!

**Comment by ackintosh** [comment]
Sorry for late 💦 I'll file a PR!
