### ISSUE TITLE
[BUG][typescript-axios] Unnecessary imports occurs when using withSeparateModelsAndApi

### ISSUE THREAD

**Issue by tanmen** [OpenAPITools/openapi-generator#5796]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

If withSeparateModelsAndApi is used, it tries to import a model that is not used.
import must be used or deleted.

###### api response
target
```yaml
            200:
              description: Box list
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/BoxesResponse'
            403:
              description: Forbidden
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ForbiddenResponse'
```

##### openapi-generator version
4.3.0

##### OpenAPI declaration file content or url
<details><summary>OpenAPI schema</summary>
<p>

###### Schema

```yaml
openapi: 3.0.2
info:
  title: My application
  version: 1.0.0
  description: My application
tags:
  - name: Box
paths:
  /boxes:
    get:
      summary: Box list
      description: Box list
      operationId: showBoxes
      tags:
        - Box
      responses:
        200:
          description: Box list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BoxesResponse'
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
components:
  schemas:
    Response:
      type: string
      example: success
      enum:
        - success
        - error
    Box:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: inbox
        box:
          $ref: '#/components/schemas/BoxInBox'
    BoxInBox:
      type: object
      properties:
        id:
          type: number
          example: 1
        name:
          type: string
          example: inbox
    BoxesResponse:
      allOf:
        - $ref: '#/components/schemas/Response'
        - $ref: '#/components/schemas/Box'
    ForbiddenResponse:
      type: object
      properties:
        status:
          type: number
          example: 403
        message:
          type: string
          example: please signin
```

</p>
</details>

##### Command line used for generation
openapi-generator generate -i openapi.yml -g typescript-axios -o apis -p withSeparateModelsAndApi=true --api-package apis --model-package models

##### Steps to reproduce
N/A

##### Related issues/PRs
N/A

##### Suggest a fix
#5797

**Comment by amakhrov** [comment]
Is it a regression since the previously fixed https://github.com/OpenAPITools/openapi-generator/issues/4804 ?

**Comment by tanmen** [comment]
@amakhrov 
no.
i fixed type error if multi response schema :)
