### ISSUE TITLE
Path in `phpunit.xml.dist` is platform dependent

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#585]
In PR #578 the samples were generated on windows, and when the ensure-up-to-date scripts run (see #80) we have the following diff on Shippable:

```diff
diff --git a/samples/server/petstore/php-slim/phpunit.xml.dist b/samples/server/petstore/php-slim/phpunit.xml.dist
index a9fd1a3ad..4a44f5ac1 100644
--- a/samples/server/petstore/php-slim/phpunit.xml.dist
+++ b/samples/server/petstore/php-slim/phpunit.xml.dist
@@ -11,16 +11,16 @@
 >
     <testsuites>
         <testsuite name="Apis">
-            <directory>.\test\Api</directory>
+            <directory>./test/Api</directory>
         </testsuite>
         <testsuite name="Models">
-            <directory>.\test\Model</directory>
+            <directory>./test/Model</directory>
         </testsuite>
     </testsuites>
     <filter>
         <whitelist processUncoveredFilesFromWhitelist="true">
-            <directory suffix=".php">.\lib\Api</directory>
-            <directory suffix=".php">.\lib\Model</directory>
+            <directory suffix=".php">./lib/Api</directory>
+            <directory suffix=".php">./lib/Model</directory>
         </whitelist>
     </filter>
 </phpunit>
\ No newline at end of file
```

Our output should be platform independent.

**Comment by wing328** [comment]
One "workaround" is to put phpunit.xml.dist in .gitignore as the file is not being used in the test at the moment and I seldom see changes made to that particular file

cc @ackintosh

**Comment by ackintosh** [comment]
Oh... 

Should we use `/` instead of `File.separator`?

[phpunit.xml.mustache#L23](https://github.com/ackintosh/openapi-generator-1/blob/925ae681678c9000ff65fd19f46c8b3457894275/modules/openapi-generator/src/main/resources/php-slim-server/phpunit.xml.mustache#L23)
[modelSrcPath](https://github.com/ackintosh/openapi-generator-1/blob/ab8ec45b50968d6df9a8de699d82219d4a341687/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPhpCodegen.java#L223)

**Comment by jmini** [comment]
I do not think that `.gitignore` can be a solution. If I remember well how git works you have 2 situations:

1) the file is in the repo, then `.gitignore` is ignored, meaning that you will see when there are some changes and I believe that the file is also displayed when you do a `git status`.
2) the file is not in the repo, to add it you need to do a `git add --force` and then you are back to case 1.

---

I tend to prefer @ackintosh solution, because I consider that generator output should be independent from the platform. Imagine cases where you have Win/Mac/Linux in the same team (it is my case). I do not want to commit changes like changing `path/to/file.php` to `path\to\file.php` just because of the OS of the user doing the update.
