### ISSUE TITLE
[BUG] RustServer can't find crate tokio

### ISSUE THREAD

**Issue by paladinzh** [OpenAPITools/openapi-generator#5887]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

error[E0463]: can't find crate for `tokio`
  --> output/petstore-with-fake-endpoints-models-for-testing/src/lib.rs:45:1
   |
45 | extern crate tokio;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `petstore-with-fake-endpoints-models-for-testing`.
warning: build failed, waiting for other jobs to finish...
error: build failed

##### Suggest a fix

+++ b/modules/openapi-generator/src/main/resources/rust-server/Cargo.mustache
@@ -87,7 +87,7 @@ mime_multipart = {version = "0.5", optional = true}
 hyper_0_10 = {package = "hyper", version = "0.10", default-features = false, optional=true}
 {{/apiUsesMultipartRelated}}
 serde_ignored = {version = "0.0.4", optional = true}
-tokio = {version = "0.1.17", optional = true}
+tokio = {version = "0.1.17", optional = false}
 url = {version = "1.5", optional = true}
 
 # Client-specific

**Comment by richardwhiuk** [comment]
This is fixed in https://github.com/OpenAPITools/openapi-generator/pull/5831

**Comment by paladinzh** [comment]
OK.Thx
