### ISSUE TITLE
Small problem with dataType in the python client generation

### ISSUE THREAD

**Issue by mwilby** [OpenAPITools/openapi-generator#5909]
Version 4.3.0
Urgency low

There is a small issue with the generation of python client code using the option

```
-g python
```

It is of little urgency because it only effects certain objects and only if the default `model.mustache` template is modified to use type information.

A variable defined to be a list, eg:

```json
address:
  type: object
  properties:
    al:
      type: array
      items:
        type: string
```

will generate the following "vars" element

```json
"vars" : [ {
"openApiType" : "array",
"baseName" : "al",
"getter" : "getAl",
"setter" : "setAl",
"dataType" : "list[str]",
"datatypeWithEnum" : "list[str]",
"name" : "al",
"defaultValueWithParam" : " = data.al;",
"baseType" : "list",
```

It shoud be

```json
"vars" : [ {
"openApiType" : "array",
"baseName" : "al",
"getter" : "getAl",
"setter" : "setAl",
"dataType" : "List[str]",
"datatypeWithEnum" : "List[str]",
"name" : "al",
"defaultValueWithParam" : " = data.al;",
"baseType" : "List",
```

The standard python template `model.mustache` will then generate 

```python
    openapi_types = {
        'al': 'list[str]',
        'did': 'str',
        'sid': 'int'
    }
```

Because its embedded in a string, it does not matter that its wrong. But if you wanted to use the Type assignment, it will cause an error. You also technically need to add to the generated python

```python
from typing import List
```

But only if you wanted to change `'al': 'list[str]'` to  `'al': List[str]`.

There is the same problem with `dict` and `Dict`. It is probably a problem with all collector classes.

**Comment by mwilby** [comment]
I looked at your code and the simple solution is trivial, change lines 129 and 130 in

```python
org.openapitools.codegen.languages.PythonClientCodegen
```
to

```python
        ...
        typeMapping.put("array", "List");
        typeMapping.put("map", "Dict");
        ...
```

But the problem outlines a slightly bigger problem of redundancy

`PythonClientCodegen` is derived from `DefaultCodegen`, where as all the other python based generators are derived from `PythonAbstractConnexionServerCodegen`, which itself is derived from `DefaultCodegen`. This separates the base definitions of `languageSpecificPrimitives` and `typeMapping` for python based systems.

It would seem sensible to create a base `PythonAbstractCodegen` containing the common definitions and methods, which then acts as base to both `PythonClientCodegen` and `PythonAbstractConnexionServerCodegen`. In this way you reduce the redundancy in the definitions of Python objects into one location, improving the reliability and maintainability.

**Comment by wing328** [comment]
> It would seem sensible to create a base PythonAbstractCodegen containing the common definitions and methods, which then acts as base to both PythonClientCodegen and PythonAbstractConnexionServerCodegen

Totally agreed. That's what we planned to do but no one has found the time yet. 

I wonder if you can help us to create PythonAbstractCodegen class.

**Comment by mwilby** [comment]
Yep, sure I can do that.

The refactoring into a new class is simple.But its going to take me some
time to track down all your test cases and I guess some of the
associated documentation needs to change as well.

Also I am lazy, so could you point me at some documentation I can use to
check your contribution policy, rather than me trying to dig it out.

Thanks

Mark

**Comment by mwilby** [comment]
I said I would merge the python language generators, so there was a common set up of working definitions. This in principle was an easy task to allow me to learn something about the code structure. The merging literally was trivial, but to do it I had to address the original issue of different definitions of type. This opened up a large set of problems.

The obvious first approach is defining a common set of terms. This was my approach

```java
        languageSpecificPrimitives.add("list");
        languageSpecificPrimitives.add("dict");
        ...

        typeMapping.put("array", "List");
        typeMapping.put("map", "Dict");
        ...
        //
        // Add the type mappings
        importMapping.put("List", "from typing import List");
        importMapping.put("Dict", "from typing import Dict");
```

In theory, (based on my guess of what the original design was) this should have done it. The import mapping should have added the correct library import to the imports list in the model object, when the objects are exported. And this is where it starts to go wrong. It doesn't export these imports. In fact it doesn't apply the mapping. So I stole a trick form `PythonClientExperimentalCodegen` that overrides `postProcessAllModels` to fix the import strings. The change is below, just in case this is part of the problem.

```java
        for (Map.Entry<String, String> entry : importMapping.entrySet()) {
        	if (imports.contains(entry.getKey())) {
        		imports.remove(entry.getKey());
        		imports.add(entry.getValue());
        	}
        }
```

this is applied before the base `postProcessAllModels` is run. I don't think its the main problem, because the changes don't get propagated through anyway.

**Side Problem**. The above shouldn't be necessary, the mappings should be made in the base system. The location which I think is the best candidate is in `DefaultGenerator.processModels` The models are looped over and and the import list is added to `allImports`. The mappings are only expanded after the full list is built and the original values are left in the model. Something along the lines of above in the model loop will apply the expansions to the imports list. There are things to consider:

- To make this change could have serious implications to the template developers. They have been developing with it present, so I don't know what effect it could have.

- Its not my decision to make.

- The above points are probably irrelevant, because import list doesn't seem to be exported.

- The logic that expands the imports looks a bit dodgy. There is no reason in principle why an element cannot be expanded more that once and I am not sure that's a good idea.

**Main Problem**

The model import list seems to be empty. I checked with the Python and Java.

The referenced objects within the definition are included in the models import list, but I don't know how.

Referenced objects appear in imports list (in the debug file) as unexpanded objects. In this example

```json
"imports" : [ "FilePath", "ReportOptions" ]`
```

They appear in the code as

```python
from openapi_server.models.file_path import FilePath  # noqa: E501
from openapi_server.models.report_options import ReportOptions  # noqa: E501
```

Which supposedly is generated from this template entry:

```moustache
{{#imports}}
{{{import}}}  # noqa: E501
{{/imports}}
```

So it would seem that either the log file is lying, the mustache expansion is a little more sophisticated than it should be, or ...

In the case of `PythonClientExperimentalCodegen` the imports list has been expanded correctly for the referenced objects, but the other entries, i.e, the Dict and List have been removed. Despite the fact they were added to the model, so I suspect its the same basic code as with python its just that `PythonClientExperimentalCodegen` expands the entry in imports itself. However, there is a difference. In the case of the python the imports are not expanded. This may be because I allow the base `postProcessAllModels` to run after the expansion and `PythonClientExperimentalCodegen` overrides it completely.

In the case of the Java the the expanded imports get into the generated model files as well, again through a similar imports template and the log file does not report the correct import list. So I am inclined to think ts the the log file is lying.

Does Anybody have any hints on where I can find the actual import list generation?

**Summary**

Fixing this is not my call. I am not even sure its broken in the sense of how you want it to operate.

My above fix will work (assuming you fix the test cases on expected type count and import list size), if you hack all the templates with the additional line

```python
from typing import Dict, List
```

But from my point of view its a hack waiting to go wrong.

Even just confining it to the Python generators, it has some wider consequences. For example the `PythonClientExperimentalCodegen` project has problems because of this.

So my main question is what o you want to do?

**Comment by mwilby** [comment]
In the end I realised that the problem I was having, were caused by imports from different generators being defined at different levels of the data bundle passed to the mustache parser.

I have tried to not only merge the definitions, but also the logic of import definitions. In the case of the generators derived from `PythonAbstractConnexionServerCodegen` that means the removal of `pyImports`. The modifications to `PythonClientExperimentalCodegen` are optional. I included them because it makes it constant with all the other generators, but it is a question of design and placing the imports in a different location may be the desired option. The unmodified version, will still work. It just wraps the type imports with a try block.

The templates are modified, only to match the level of the import list.

**Comment by spacether** [comment]
@mwilby in the python client generator model property data types are defined as strings. In python-experimental they are defined as python classes. Python-experimental (client generator) uses model imports, the python (client generator) does not.

**Comment by mwilby** [comment]
Yep. The python client version from which the Python-experimental is
derived redefines them back to strings, so it does not kill the
experimental version.

I guess at some point someone will figure out how to change the mappings
and then the re-assignment can be removed.

On the other hand I have just realised that removing pyImports might
effect some users who have extended their templates, so a link should be
put back in so import and model.pyImports are point to the same list.

**Comment by mwilby** [comment]
Sorry, in my last comment I was thinking of the assignment of byte and
bytearray types and I realised you were making a different point. The
python client generator doesn't really make use of types, but it does
have the information. It wrapped the type information in quotes inside
the template, so it doesn't matter what they are. I originally I just
wanted to change "dict" to "Dict" to make generators consistent.
However, as I explain below, this is no longer the reason for the code
change and actually is now kind of irrelevant.

As far as I could see the Python-experimental version was doing its own
thing. It was not using the Lib/typing.py library to build type
descriptors, which is fine, and I was trying to make sure I didn't
interfere with it (if I failed, I am sorry).

So what I could see was that PythonClientExperimentalCodegen made no use
of typeMapping other than the ones that were defined in
PythonClientCodegen, which in the proposed code have been moved to
PythonAbstractCodegen. PythonClientCodegen is using these definitions
because it depends on some code in DefaultCodegen which uses it to build
the import list. PythonClientCodegen doesn't use the generate imports
because, as you said, it treats the types as strings, but the
information is there. I added some entries to importMapping, which
neither PythonClientCodegen nor PythonClientExperimentalCodegen was
using. The importMapping provides a facility to map a type to an import
library, rather than expect it to be a language primitive. This is
probably much more useful in typed languages, than it is in python.

There was a question of how PythonClientExperimentalCodegen built its
type hints, which, as I said, I tried not to interfere with. As far as I
know there is no absolute standard for providing type info in python. I
am sure you have an internal design strategy in mind, but I don't know
what it is. I built the import mapping to match
https://www.python.org/dev/peps/pep-0484/ (but only very superficially.)
This matches the strategies in the other generators.
PythonClientExperimentalCodegen can override this mapping, or ultimately
decide its type mapping is the base definition and the other generators
should override the mappings, or they could share the same mapping,
wherever it is finally decided to be. However, the important thing for
this submission is that the design of the base code is a lot cleverer
than I first thought and my job here was just to do a bit of tidying up.
Any system that's derived from a previous one can switch the mapping to
whatever it wants simply by changing the mappings in typeMapping and
importMapping.

In theory the changes I needed to make to get the mappings I wanted were
just the entries I added to, or changed in  typeMapping and
importMapping. But it didn't work. I first thought it was some
fundamental design problem in the base classes. However, it was just the
usual problem of lots of different people doing what they had to do to
make things work. The different template developers had built different
solutions to the type imports. They were all basically the same, but
they put them in different places in the data bundle, and/or they hard
coded them into the templates. The PythonClientCodegen didn't use them,
so it didn't care and the framework versions put some into imports, some
into model.pyImports and some hard coded into the templates. If I
remember correctly PythonClientExperimentalCodegen put some of them into
model.imports and had them as a list not a map. All I tried to do was
put them in the same place, using the same format, so if they did exist,
they were where you expect to find them.

It was suggested I create a base for the python based templates to have
a common source of definitions. But in the end that wasn't the most
important, or interesting thing. It was sorting out the import
definitions. And I think ultimately it could provide better code
consistency by reducing the number of generators and relegating
differences to the templates, but I I realise I am am being very optimist.

I think there are a set of important questions you need to ask
yourselves, based around what exactly is the base type definitions you
want to work from and what they might be changed into as new generators
are constructed, but that, from the point of view of the code should be
fine tuning. And I am trying very hard not to interfere with those
options. Those decisions are way above my pay grade anyway.

**Comment by mbardwell** [comment]
I have a similar issue:

```python
OPENAPI_GENERATOR_VERSION=4.3.1 ./openapi-generator-cli.sh generate \
                                --input-spec hi.yaml \
				--generator-name python \
				--additional-properties generateSourceCodeOnly=True \
				--template-dir templates \
				--type-mappings array=List \
				--import-mappings List="from typing import List" \
				--type-mappings map=Dict \
				--import-mappings Dict="from typing import Dict" \
				--output ../mydir
```

`list` gets typed as `List` but the import statement does not show up

**Comment by mwilby** [comment]
I was staying out of this because I was causing so much trouble with the Github interface (not at all experienced with open source), I thought it would be better for people if I stopped messing it up.

However, I know what the problem identified by @mbardwell  is. The template files in the python generator `model.mustache` does not have an import, i.e. it needs to change the entry

```
import pprint
import re  # noqa: F401
```

to look something like

```
import pprint
{{#imports}}
{{{import}}}
{{/imports}}
import re  # noqa: F401
```

But the import object on the bundle exported to mustache is not i the right place.

I did fix it when I tried to merge the  `PythonAbstractConnexionServerCodegen` and `PythonCodegen`, but it entailed too many changes and conflicted with with the work in `PythonClientExperimentalCodegen.` So it was never going to be easy to accept the change. (I wouldn't have done if it was my project)

This problem happens across all python generators as the import object is set up in different locations, so for example in python-flask the imports are often imported twice.

The issue here is twofold. The different locations of import objects and the different definitions of Types. The new PythonClientExperimentalCodegen has its own and the Servers have another. And the python client has none because it treats the incorrect types as strings.

In my opinion, there should only be one and it should be defined as much as possible in the common code. So if it was my choice I would use the model in python-flask, which relies on the base code and uses the python typing definition.

**Comment by mbardwell** [comment]
> I did fix it when I tried to merge the PythonAbstractConnexionServerCodegen and PythonCodegen

Can you link your PR?

I agree with your proposed solution. It does sound time consuming to implement though.

**Comment by mwilby** [comment]
Did I mention not good with github?
#6065
Its out of data and I didn't add the fix to the template, so it looked like it hadn't changed anything in the generated code. Simply change the imports to the one stated in my previous comment and it should work.
Its only a couple of lines to make it consistent with the current version.

**Comment by spacether** [comment]
In the latest python generator types are now defined using classes. `"list[str]"` became `[str]`
We welcome PRs adding type definition and that is a big task especially if supporting composed schemas.
Variable types can collide when composing a schemas and variable types can come from a variety fo schemas at many level of inheritance.
Our code at least does strict run time type checking which is better than python-legacy which does no checking.
