### ISSUE TITLE
[BUG][csharp-netcore] bearerAuth is interpreted as basicAuth

### ISSUE THREAD

**Issue by FaFre** [OpenAPITools/openapi-generator#5915]
##### Description

I added a bearer authentication in my description according to the the [swagger docs](https://swagger.io/docs/specification/authentication/bearer-authentication/):

```json
"components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
...
"security": [
    {
      "bearerAuth": []
    }
  ]
```

But for some reasons the generated code contains an basicAuth with username/password instead of the bearer expected as `Authorization: Bearer <token>`:

`DefaultApi.cs`:
```csharp
// authentication (bearerAuth) required
            // http basic authentication required
            if (!String.IsNullOrEmpty(this.Configuration.Username) || !String.IsNullOrEmpty(this.Configuration.Password))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Basic " + Org.OpenAPITools.Client.ClientUtils.Base64Encode(this.Configuration.Username + ":" + this.Configuration.Password));
            }
```

##### openapi-generator version

I use the docker image:

```bash
$ openapi-generator-cli version
4.3.1-SNAPSHOT
```

##### OpenAPI declaration file content or url

[Gist](https://gist.githubusercontent.com/FaFre/b15e59572a974a9f453d14e5cdaf3bec/raw/d40a46cb20d70dd41abbf19691745f2ffb5a1f04/test.json)

##### Command line used for generation

```bash
docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli generate -i https://gist.githubusercontent.com/FaFre/b15e59572a974a9f453d14e5cdaf3bec/raw/d40a46cb20d70dd41abbf19691745f2ffb5a1f04/test.json -g csharp-netcore -o /local/
```

**Comment by wing328** [comment]
@FaFre thanks for reporting the issue. I've filed #5921 to fix it.

**Comment by codemnk** [comment]
Looks like it is still not fixed in async client

**Comment by wing328** [comment]
@codemnk my bad that I missed it in my previous PR. I've filed https://github.com/OpenAPITools/openapi-generator/pull/6136 to fix it.

**Comment by wing328** [comment]
@codemnk the fix has been merged into master. Please give it another try.
