### ISSUE TITLE
Support obtain all server URLs for OAS 3.x 

### ISSUE THREAD

**Issue by haitongz** [OpenAPITools/openapi-generator#592]
##### Description
When running generator on an openapi 3.x document, if you use a variable for the port, generator print a warning. The warning does not block the generation, but does support openapi 3.x new feature. In addition it use default value instead in this circumstance. 

Error looks like:
`[main] WARN  o.o.codegen.utils.URLPathUtils - Not valid URL: http://example.com:{port}/v1. Default to http://localhost.`

##### openapi-generator version
OpenAPI Generator 3.1.0

##### Command line used for generation
openapi-generator generate -i sample.yaml -g python -o /tmp/test1/

##### Steps to reproduce
can use yaml from: https://raw.githubusercontent.com/douglasbgray/code-gen-server-issue/master/src/main/resources/openapi.yaml

##### Related issues/PRs
Did not find any open issues related to this, but find related from swagger-codegen:
https://github.com/swagger-api/swagger-codegen/issues/8412

##### Suggest a fix/enhancement
Error is coming from URLPathUtil.java. Before checking if the url can be converted into a java.net.URL, it needs to perform the variable substitution, which would resolve the {port} and generate a URL that would be valid. 
I find the source code URLPathUtil.java added TODO comments(TODO need a way to obtain all server URLs). I am not familiar with java. How I can finish the task myself？ thanks for your great job.

**Comment by jmini** [comment]
Thank you a lot for this issue. It is important for us to support the most OAS3 concept we can.

Your analysis is right, I have modified the method with #614.

The TODO line in `URLPathUtils` is about something else:

https://github.com/OpenAPITools/openapi-generator/blob/0da55081c934704f24c702659e93e640fadf006c/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L42

In our models and template we have only one server URL. This is why we pick the first one.
Same idea with changes in my PR only one variable substitution is made (with the default value or if missing with the first value of the enum).

Take this example (adapted from the official) OAS3 spec:
```yaml
servers:
- url: https://api.gigantic-server.com:{port}/{basePath}
  description: The production API server
  variables:
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
```
In theory out of the enum value we could generate multiple server URLs. But for that the generators needs to handle multiple server values, which is not the case at the moment.
