### ISSUE TITLE
[BUG][csharp-netcore] Ctor validation end with double semicolon

### ISSUE THREAD

**Issue by migpfernandes** [OpenAPITools/openapi-generator#5927]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

In the Constructor generated mandatory fields are being checked for  null values. Line ends with a double semicolon like this:
```
`this.AddressId = addressId ?? throw new ArgumentNullException("addressId is a required property for Address and cannot be null");;`
```
##### openapi-generator version

4.3.0

##### Command line used for generation

java -jar .\openapi-generator-cli.jar generate -i .\checkoutrestriction.yaml -g csharp-netcore -o solution -c .\config.json
```json
{
"targetFramework":"netstandard2.0",
"optionalMethodArgument":"false",
"validatable":"false",
"netCoreProjectFile":"true"
}
```

##### Steps to reproduce

Execute previous statement and check generated models

##### Related issues/PRs

Couldn't find any

##### Suggest a fix

Just one semicolon should appear at the end of the line

**Comment by wing328** [comment]
@migpfernandes thanks for reporting the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/5934 to fix it.

**Comment by migpfernandes** [comment]
Thanks for the fix 👍
