### ISSUE TITLE
[BUG][JAVA] setBearerToken method not generated

### ISSUE THREAD

**Issue by toymachiner62** [OpenAPITools/openapi-generator#5959]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Generating a Java client with version 4.3.0 does not generate the method `setBearerToken`. I have the security scheme defined in my .oas file.

The example petstore has this method generated here https://github.com/OpenAPITools/openapi-generator/blob/5740348902a29e2ad1e538b1f27bf13ec8031a23/samples/client/petstore/java/resttemplate/src/main/java/org/openapitools/client/ApiClient.java#L160-L172

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url

```json
"securitySchemes": {
      "Bearer": {
        "type": "http",
        "description": "Bearer Authorization using User Token credentials",
        "scheme": "bearer"
      }
    }
```

##### Command line used for generation

```sh
$ openapi-generator generate -i https://sdk.catalytic.com/v1.0.1-pre-35/swagger/v1/swagger.json -g java -o new --additional-properties=apiPackage=org.catalytic.sdk.api,modelPackage=org.catalytic.sdk.model,dateLibrary=java8,groupId=org.catalytic,invokerPackage=org.catalytic.sdk,java8=true,hideGenerationTimestamp=true
```

**Comment by agilob** [comment]
Has this been fixed? Should it be closed?

**Comment by wing328** [comment]
I think so: https://github.com/OpenAPITools/openapi-generator/blob/32adeddd8fd6e217eca2092f4bf370e6d6e7ea33/samples/client/petstore/java/okhttp-gson/src/main/java/org/openapitools/client/auth/HttpBearerAuth.java#L44

**Comment by toymachiner62** [comment]
Uhh what version was this released in?

**Comment by wing328** [comment]
@toymachiner62 can you try the latest master or v5.0.0-beta2?

**Comment by toymachiner62** [comment]
Please reopen. This is still not working in v5.0.0-beta2.

**Comment by srknkbs** [comment]
I also had the same problem.

The issue is openapi-generator uses `okhttp-gson` client library by default and the `ApiClient.mustache` template of this library does not have `setBearerToken` method. 

So, I have to fetch `HttpBearerAuth` instance from ApiClient and set the bearer token there. 

```java
apiClient.getAuthentication("bearerAuth");
```

IMHO this is a workaround and it would be better to have `setBearerToken` method in all `ApiClient.mustache` templates.

**Comment by toymachiner62** [comment]
@wing328 are you going to reopen? This is still an issue..

**Comment by agilob** [comment]
Thanks for the info @srknkbs 
I opened a PR for this https://github.com/OpenAPITools/openapi-generator/pull/8200
