### ISSUE TITLE
[BUG] "Found unexpected parameters" when trying simple example

### ISSUE THREAD

**Issue by godlessendeavor** [OpenAPITools/openapi-generator#5962]
Hi, I'm trying to generate a client from an OpenAPI 3.0 spec but I found the "Found unexpected parameters". The spec validates successfully in other places.
openapi-generator version is 4.3.0, on Linux platform installed with npm, but I tried the Java generator before and I got the same issue.

Here's my spec
```yaml
openapi: 3.0.1
info:
  title: Music Database Server
  version: 1.0.1
servers:
- url: /
  description: "Music Database Server"
security:
- oauth2: []
tags:
- name: public
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - public
      summary: Rootpath get for supporting health check on GKE
      operationId: api.generic.get
      responses:
        200:
          description: OK
          content: {}
 
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://example.com/oauth2/dialog
          scopes:
            uid: Unique identifier of the user accessing the service.
      x-tokenInfoFunc: app.token_info
```
And the command and result:
`openapi-generator -g go -o out -i ./app_definition.yaml` 
`[error] Found unexpected parameters: [-g, go, -o, out, -i, ./app_definition.yaml]`

**Comment by jacobkeith** [comment]
You're missing the command itself. Try `openapi-generator generate -g go -o out -i ./app_definition.yaml`

**Comment by godlessendeavor** [comment]
Correct, working too late.... Thanks!
