### ISSUE TITLE
[Dart] Cannot access tmp folder

### ISSUE THREAD

**Issue by cctyylmzz** [OpenAPITools/openapi-generator#5980]
I have a problem like this.

{
  "timestamp": "2020-04-19T19:23:00.981Z",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Cannot access tmp folder",
  "path": "/api/gen/clients/dart"
}

Can anybody help me?

**Comment by StasiShulvi** [comment]
Facing the same issue.
Any updates?
I'm using `typescript-axios`, not dart.

Related issues:
- https://github.com/OpenAPITools/openapi-generator/issues/6500
- https://github.com/OpenAPITools/openapi-generator/issues/6426

**Comment by wing328** [comment]
I have fixed it. Please give it another try

**Comment by StasiShulvi** [comment]
@wing328 hi! thank you, it works now fine!

**Comment by wing328** [comment]
UPDATE: I've setup monitoring using [checkly](https://checklyhq.com/) to catch the issue moving forward.
