### ISSUE TITLE
[Question] [C++] [Qt5] [Client] Presence of optional elements

### ISSUE THREAD

**Issue by ChrisAfaik** [OpenAPITools/openapi-generator#5991]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

How can one determine whether **optional** model properties are present or not? Especially if the model object is part of a response, it seems to be essential to have this information being available at the API somewhere.

I noticed the members `<ModelClass>::m_<PropertyName>_isSet` being generated in the model classes. However, they are private:

```
class OAIComplex_response : public OAIObject {
    ...
private:
    ...
    QString property1;
    bool m_property1_isSet;
    bool m_property1_isValid;

    qint32 property2;
    bool m_property2_isSet;
    bool m_property2_isValid;
};
```

BTW: What is the goal of the `<ModelClass>::IsSet` method? It seems to return true if at least one property has been set, regardless of whether it is a required or optional property.

##### openapi-generator version
4.3.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  description: Example
  version: "1.0.0"
  title: Example
servers:
  - url: http://localhost/
paths:
  /example/:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/complex-response'

components:
  schemas:
    complex-response:
      type: object
      properties:
        property1:
          type: string
          format: string
        property2:
          type: integer
          format: int32
      required:
        - property1
        #- property2
```

##### Command line used for generation
`java -jar openapi-generator-cli-4.3.0.jar generate -g cpp-qt5-client -i example\example.yaml -o example\generated`

##### Steps to reproduce
Generate as stated above.

##### Related issues/PRs
n.a.

##### Suggest a fix
Make the `<ModelClass>::m_<PropertyName>_isSet` accessible publicly.

**Comment by etherealjoy** [comment]
> What is the goal of the <ModelClass>::IsSet method? It seems to return true if at least one property has been set, regardless of whether it is a required or optional property.

The **isSet** method is used to check if a property has been set by the user and can be used to serialized for sending otherwise it is not serialized and send if not set. Serializing properties which are not set is not correct because values like *int* types has default init values of *0*

The **isValid** method is used to check if a property/object has all the required fields set

**Comment by ChrisAfaik** [comment]
> The isSet method is used to check if a property...

Thanks @etherealjoy. However, when serializing, I would generally evaluate those `<ModelClass>::m_<PropertyName>_isSet` members. This is being done for simple types, but for complex types the '<ModelClass>::isSet' method is used instead. Should we create a separate discussion issue for that?

My main concern is still how to detect the presence of **optional** model properties - in particular when dealing with responses. In my opinion those `<ModelClass>::m_<PropertyName>_isSet` members should be exposed by public getters.

**Comment by etherealjoy** [comment]
> In my opinion those <ModelClass>::m_<PropertyName>_isSet members should be exposed by public getters.

This we can do if needed.

**Comment by ChrisAfaik** [comment]
Created a feature request for that: [#6014](https://github.com/OpenAPITools/openapi-generator/issues/6014)
