### ISSUE TITLE
[BUG] [typescript-anguar] allOf broken

### ISSUE THREAD

**Issue by daniel-sc** [OpenAPITools/openapi-generator#5998]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

In the latest version, generating with typescript-angular, models that use "allOf" do not contain the inherited properties any more.

##### openapi-generator version

This occurs with v4.3.0. 
With v4.1.2 this worked fine.

##### OpenAPI declaration file content or url

Api spec:
```yaml
openapi: 3.0.2
info:
  title: api
  version: 1.0.0
paths:
  /pet:
    get:
      summary: list all pets
      responses:
        200:
          description: pet with name
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetName'

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: string
          
    PetName:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            name:
              type: string
```

Result:
```ts
import { PetNameAllOf } from './petNameAllOf';
import { Pet } from './pet';


export interface PetName { 
    name?: string;
}
```

Expected result would be along:
```ts
export interface PetName { 
    id?: string;
    name?: string;
}
```

##### Command line used for generation

```
java -jar openapi-generator-cli-4.3.0.jar generate -g typescript-angular -i api.yml
```

##### Steps to reproduce

Use commandline and example from above

##### Related issues/PRs

Maybe related:
* https://github.com/OpenAPITools/openapi-generator/pull/5182
* https://github.com/OpenAPITools/openapi-generator/issues/4146

**Comment by wing328** [comment]
@daniel-sc can you please try the latest master? I just merged https://github.com/OpenAPITools/openapi-generator/pull/5992 which may have fixed the issue for you.

**Comment by daniel-sc** [comment]
@wing328 yes, with current master (8661ed3c0422897b0b3dfc7dcc73f20288f117ad) it works as expected.
For when can we expect a release containing this fix?

**Comment by wing328** [comment]
Roughly a week assuming no postponement.

**Comment by wing328** [comment]
Thanks for confirming the latest master works for you.
