### ISSUE TITLE
[REQ] [C++] [Qt5] [Client] Provide the http status code

### ISSUE THREAD

**Issue by ChrisAfaik** [OpenAPITools/openapi-generator#6018]
It would be great if the generated API exposed the http status code received.
Currently only the `QNetworkReply::NetworkError` error is available which doesn't always represent the actual http status code.

This change only relates to C++ Qt5 client generator (cpp-qt5-client).

**Comment by etherealjoy** [comment]
There are two signals to connect to 
```C++
void getUserByNameSignal(PFXUser summary);
void getUserByNameSignalFull(PFXHttpRequestWorker *worker, PFXUser summary);
```
Same for error as well.
```C++
void getUserByNameSignalE(PFXUser summary, QNetworkReply::NetworkError error_type, 
QString error_str);
void getUserByNameSignalEFull(PFXHttpRequestWorker *worker, 
QNetworkReply::NetworkError error_type, QString error_str);
```
You can connect to *only* one of each.

The differences between the two is that you can can access the **QNetworkReply::NetworkError** with **worker->error**.
