### ISSUE TITLE
[REQ] Javascript client: allow dot in path parameters

### ISSUE THREAD

**Issue by mrnitoqq** [OpenAPITools/openapi-generator#6030]
### Is your feature request related to a problem? Please describe.

I'm using grpc-gateway [patch feature]( https://grpc-ecosystem.github.io/grpc-gateway/docs/patch.html) so it generates following openapi spec

```
"/v1/public/auth/user/{user.id}": {
      "put": {
        "summary": "Update user",
        "operationId": "AuthService_UpdateUser",
        "responses": {
          ...
        },
        "parameters": [
          {
            "name": "user.id",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "uint64"
          },
          ...
        ]
      },
      "patch": {
        "summary": "Update user",
        "operationId": "AuthService_UpdateUser2",
        "responses": {
          ...
        },
        "parameters": [
          {
            "name": "user.id",
            "in": "path",
            "required": true,
            "type": "string",
            "format": "uint64"
          },
          ...
        ],
      }
    },
```

As we can see  there is `{user.id}` parameter in the path, but js client does not replace it with correct variable.
According to this lines
[Javascript/ApiClient.mustache#L147](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Javascript/ApiClient.mustache#L147)
[Javascript/es6/ApiClient.mustache#L137](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Javascript/es6/ApiClient.mustache#L137)
it replaces only `{user_id}` like params

## Describe the solution you'd like

Changing regexp to `/\{([\w-\.]+)\}/g` will solve the problem

**Comment by wing328** [comment]
> Changing regexp to /\{([\w-\.]+)\}/g will solve the problem

can you please file a PR with the suggested fix so that we can review it more easily?

**Comment by nitoqq** [comment]
Hi, please look PR ^^
