### ISSUE TITLE
[BUG] Regression: Compilation fails with git worktree

### ISSUE THREAD

**Issue by bodograumann** [OpenAPITools/openapi-generator#6072]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

When checking out the openapi-generator code in a git worktree, compilation will not work.

##### openapi-generator version

* **master**

Bug was introduced in e14e5fccf395c939176cb44d51a870afeefa1ee8 due to the inclusion of git-commit-id-plugin.

##### Steps to reproduce

```
git clone https://github.com/openapitools/openapi-generator
cd openapi-generator
git worktree add ../openapi-generator-dev
cd ../openapi-generator-dev
mvn clean package
```

This will throw an error:
> [ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:4.0.0:revision (get-the-git-infos) on project openapi-generator: Could not complete Mojo execution...: Error: Could not
 get HEAD Ref, are you sure you have some commits in the dotGitDirectory? -> [Help 1]

##### Related issues/PRs

This is caused by [missing git worktree support](https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/215) in git-commit-id-maven-plugin.
That in turn is caused by the feature [missing in JGit](https://bugs.eclipse.org/bugs/show_bug.cgi?id=477475)

##### Suggest a fix

A possible approach would be to [disable the plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/268) `-Dmaven.gitcommitid.skip=true` during compilation. This will make `openapi-generator (core library)` compile successfully, but cause test errors in `openapi-generator (executable)` unfortunately.

Not sure how a proper fix would look like. At least this behaviour should be documented somewhere.

**Comment by jimschubert** [comment]
I have a fix for this in #6094

**Comment by bodograumann** [comment]
Thanks for the quick response. I have tested the PR and it works well for me.

**Comment by jimschubert** [comment]
Thanks for validating!
