### ISSUE TITLE
[BUG][Java] allOf inheritence generates duplicate field if a property is redeclared

### ISSUE THREAD

**Issue by gravelld** [OpenAPITools/openapi-generator#6117]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
When using `allOf` in a model schema, the referenced model is set as the superclass. Therefore the subclass inherits members from the superclass.

In the subclass, inside the OAS API, I wanted to provide a more specific example for the subclass. AIUI you can simply redeclare the property from the superclass, and specify a new `example`.

However, when the code is generated this generates a duplicate member in the subclass. This is not a compile error, but at deserialisation time:

```
Invalid JSON: class com.elsten.bliss.baas.assessment.model.ImageStorageNode declares multiple JSON fields named path
```

##### openapi-generator version
4.3.0

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    StorageNode:
      type: object
      required:
        - path
      properties:
        path:
          type: string
          description: The path to this storage node
          example: /First album/1
    ImageStorageNode:
      type: object
      description: A container for information about images.
      allOf:
      - $ref: '#/components/schemas/StorageNode'
      - type: object
        properties:
          path:
            type: string
            description: The path, relative to the root of the music library, to this storage node
            example: /First album/cover.jpg

```

##### Command line used for generation

```
npx openapi-generator generate \
-i path/to/model.yaml \
-g java \
-o build/open-api-generated/ \
--additional-properties=modelPackage=my.package,dateLibrary=java8 \
-Dmodels \
-DsupportingFiles=JSON.java
```

##### Suggest a fix
I think the re-declared property simply shouldn't be generated in the subclass.

**Comment by wing328** [comment]
> When using allOf in a model schema, the referenced model is set as the superclass. Therefore the subclass inherits members from the superclass.

There's a bug (regression in 4.30), which has been addressed in the latest master. Please give it a try and let us know if you still face the same issue.

**Comment by gravelld** [comment]
Thanks - if this is a duplicate, please mark it as so and feel free to close (I didn't find it when I searched).
