### ISSUE TITLE
[REQ] [Maven] Introduce addTestCompileSourceRoot

### ISSUE THREAD

**Issue by famod** [OpenAPITools/openapi-generator#6119]
### Is your feature request related to a problem? Please describe.

I have to use `build-helper-maven-plugin` or fiddle around with `maven-compiler-plugin` when I am generating only for test execution (phase `generate-test-sources`) because there is only `addCompileSourceRoot` but no `addTestCompileSourceRoot` parameter.

## Describe the solution you'd like

Introduce `addTestCompileSourceRoot` in analogy to `addTestCompileSourceRoot`.

## Describe alternatives you've considered

`build-helper-maven-plugin`

## Additional context

n/a

**Comment by feech** [comment]
Hello Famod
Could you please describe the use case around these parameters -
addCompileSourceRoot  and addTestCompileSourceRoot.

What would you say if we can redo this implementation?
I am thinking about the next solution

1. APIs and model generate into output - which is ${project.build.directory}/generated-sources/openapi  by default
2. test for APIs and model generate into testOutput which is ${project.build.directory}/generated-**test**-sources/openapi
3. each of the paths adds into corresponsent source root - runtime or test
Following this scenario I do not see even necessety to parametrize this behaviour. Generated files will appear in appropriate root.

I already started to work on the proposal https://github.com/OpenAPITools/openapi-generator/pull/11503/files, But it seems I am missing your use-case.


Do you have a use-case when runtime APIs and models (from 1) should sit in test source root?
