### ISSUE TITLE
[BUG][JAVA] Multipart form with array of files doesn't work

### ISSUE THREAD

**Issue by toymachiner62** [OpenAPITools/openapi-generator#6134]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

With a POST endpoint with multipart form body to upload an array of files, the generated code doesn't account for an array of files so it doesn't send any files across the wire.

##### openapi-generator version

4.3.0
##### Suggest a fix

[This line](https://github.com/OpenAPITools/openapi-generator/blob/b1aecaded0afe8b213955389b13a5c72576e327c/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L1324) doesn't account for the `param.getValue()` being an `ArrayList`

**Comment by toymachiner62** [comment]
Replacing [this method](https://github.com/OpenAPITools/openapi-generator/blob/b1aecaded0afe8b213955389b13a5c72576e327c/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L1314-L1335) with this method seems to work. It accounts for the case that `formParams.value` is a List.

```java
/**
     * Build a multipart (file uploading) request body with the given form parameters,
     * which could contain text fields and file fields.
     *
     * @param formParams Form parameters in the form of Map
     * @return RequestBody
     */
    public RequestBody buildRequestBodyMultipart(Map<String, Object> formParams) {
        MultipartBody.Builder mpBuilder = new MultipartBody.Builder().setType(MultipartBody.FORM);
        for (Entry<String, Object> param : formParams.entrySet()) {
            if (param.getValue() instanceof List) {
                for (Object value : (List) param.getValue()) {
                    if (value instanceof File) {
                        File file = (File) value;
                        Headers partHeaders = Headers.of("Content-Disposition", "form-data; name=\"" + param.getKey() + "\"; filename=\"" + file.getName() + "\"");
                        MediaType mediaType = MediaType.parse(guessContentTypeFromFile(file));
                        mpBuilder.addPart(partHeaders, RequestBody.create(mediaType, file));
                    } else {
                        Headers partHeaders = Headers.of("Content-Disposition", "form-data; name=\"" + param.getKey() + "\"");
                        mpBuilder.addPart(partHeaders, RequestBody.create(null, parameterToString(param.getValue())));
                    }
                }
            } else {
                if (param.getValue() instanceof File) {
                    File file = (File) param.getValue();
                    Headers partHeaders = Headers.of("Content-Disposition", "form-data; name=\"" + param.getKey() + "\"; filename=\"" + file.getName() + "\"");
                    MediaType mediaType = MediaType.parse(guessContentTypeFromFile(file));
                    mpBuilder.addPart(partHeaders, RequestBody.create(mediaType, file));
                } else {
                    Headers partHeaders = Headers.of("Content-Disposition", "form-data; name=\"" + param.getKey() + "\"");
                    mpBuilder.addPart(partHeaders, RequestBody.create(null, parameterToString(param.getValue())));
                }
            }
        }
        return mpBuilder.build();
    }
```

**Comment by jorgerod** [comment]
Hi
Could you put **OpenAPI declaration file content** and **Command line used for generation**?

Thank you

**Comment by toymachiner62** [comment]
Command used to generate along with the swagger.json file url
```sh
openapi-generator generate -i https://sdk.catalytic.com/v1.0.1-pre-35/swagger/v1/swagger.json \
    -g java \
    -o new \
    --additional-properties=apiPackage=org.catalytic.sdk.generated.api,modelPackage=org.catalytic.sdk.generated.model,dateLibrary=java8,groupId=org.catalytic,invokerPackage=org.catalytic.sdk.generated,java8=true,hideGenerationTimestamp=true;
```

**Comment by toymachiner62** [comment]
Any update on this? A working solution is right here https://github.com/OpenAPITools/openapi-generator/issues/6134#issuecomment-622566458
