### ISSUE TITLE
[BUG] [typescript-fetch] Circular import generated

### ISSUE THREAD

**Issue by ajaska** [OpenAPITools/openapi-generator#6140]
#### Bug Report Checklist

- [x] Have you provided a full/**minimal** spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

The typescript-fetch generator is generating a circular import. In my provided reproducible example, it's

models/index.ts -> models/HTTPValidationError.ts -> models/index.ts

The actual code is:
```
// models/HTTPValidationError.ts
import {
    ValidationError,
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
} from './';
```
This produces some annoying warning messages but doesn't seem to actually break the code.

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url

<details>
<summary>Click to expand</summary>

```json
{
  "openapi": "3.0.2",
  "info": {
    "title": "Some API",
    "version": "0.1.0"
  },
  "paths": {
  },
  "components": {
    "schemas": {
      "HTTPValidationError": {
        "title": "HTTPValidationError",
        "type": "object",
        "properties": {
          "detail": {
            "title": "Detail",
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/ValidationError"
            }
          }
        }
      },
      "ValidationError": {
        "title": "ValidationError",
        "required": ["loc", "msg", "type"],
        "type": "object",
        "properties": {
          "loc": {
            "title": "Location",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "msg": {
            "title": "Message",
            "type": "string"
          },
          "type": {
            "title": "Error Type",
            "type": "string"
          }
        }
      }
    }
  }
}
```

</details>

##### Command line used for generation

`openapi-generator generate -g typescript-fetch -i test-input.json -o api-client`

##### Steps to reproduce

Run command line with provided input.

##### Related issues/PRs

Nope

##### Suggest a fix

I'm pretty sure this can be fixed by re-working the import statements in `modelGeneric.mustache` and `modelOneOf.mustache`. Instead of importing from `./`, it should be possible to import directly from the thing you're importing. For example, in the code above, it could import from `./ValidationError` instead of `./`.

A diff might look like (forgive me, I'm not entirely familiar with mustache syntax):

```diff
diff --git a/modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache b/modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
index bd593da1..263f80ac 100644
--- a/modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
+++ b/modules/openapi-generator/src/main/resources/typescript-fetch/modelGeneric.mustache
@@ -1,13 +1,13 @@
 import { exists, mapValues } from '../runtime';
 {{#hasImports}}
+{{#imports}}
 import {
-    {{#imports}}
     {{{.}}},
     {{.}}FromJSON,
     {{.}}FromJSONTyped,
     {{.}}ToJSON,
-    {{/imports}}
-} from './';
+} from './{{.}}';
+{{/imports}}
 
 {{/hasImports}}
 {{#discriminator}}
```

**Comment by amakhrov** [comment]
Note that even with direct imports from the individual model files (as you suggested), it's possible to get circular reference if actual models in api-spec have such a circular reference.

**Comment by ajaska** [comment]
True, though I guess that would sort of be expected at that point.

Do you think this is worth fixing for this case? It only seems to cause warnings and not errors as long as the dependencies aren't truly circular (i.e. actually circularly referential), so I suppose I could live with just ignoring the warnings, but it also seems like a pretty small and easy fix?

**Comment by amakhrov** [comment]
Yeah I don't see how such a change can hurt in any way. Would you want to make a PR with the fix?

**Comment by dngconsulting** [comment]
Hello, any update on this ? Living with a warning is a bit painful...

**Comment by gerardo-navarro** [comment]
Hi, I also stumbled upon this today. Are there any plans to address this warning?

**Comment by lingster** [comment]
I'm sure the maintainers would welcome a PR.

**Comment by BeryJu** [comment]
I've just created a PR to fix this issue based on the work of @ajaska , and you can try it using this docker container `ghcr.io/beryju/openapi-generator` (based on master so might be buggy)
