### ISSUE TITLE
[typescript-axios] attribute components.schemas.XXXX is missing but it isn't

### ISSUE THREAD

**Issue by paulfrench** [OpenAPITools/openapi-generator#6145]
I download API as JSON resolved (https://app.swaggerhub.com/apis/AdvancedComputerSoft/e-commerce/1.0.25)

Using generator version 4.3.0 installed via npm I run....

```
openapi-generator generate -i openapi.json -g typescript-axios -o clientSDK
```
I get...
```
There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 13, Warning count: 0
Errors:
        -attribute components.schemas.allDeliveryAddresses.items is missing
        -attribute components.schemas.allVatRates.items is missing
        -attribute components.schemas.allProducts.items is missing
        -attribute components.schemas.allCustomers.items is missing
        -attribute components.schemas.allStockCategories.items is missing
        -attribute components.schemas.allBankAccounts.items is missing
        -attribute components.schemas.allCompanies.items is missing
        -attribute components.schemas.allLocations.items is missing
        -attribute components.schemas.allExchangeRates.items is missing
        -attribute components.schemas.allVatTypes.items is missing
        -attribute components.schemas.allReceipts.items is missing
        -attribute components.schemas.allSalesInvoices.items is missing
        -attribute components.schemas.allSalesOrders.items is missing
```
However the open API is marked as valid on swaggerhub and imports fine into POSTMAN. I'm a newbie so apologies if this is stupid question but why can't I generate an SDK for this valid spec.

If I inspect the file visually I can see local $ref that should resolve fine to the above named attributes.

Many Thanks

**Comment by paulfrench** [comment]
mistake in my open api spec

**Comment by PSchubertMHP** [comment]
Hi @paulfrench, what was your solution? I've experiencing the same issue and I can't wrap my head around. Thanks in advance!

**Comment by paulfrench** [comment]
I simply had mistakes in my spec e.g. I had...
```
    allReceipts:
      type: array
      properties:
        items:
          $ref: '#/components/schemas/receipt'
```
...and it should have been...
```
    allReceipts:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/receipt'
```
What confused me at the time was I had a property named "items" in my json yet "items" is also used by the OAS spec when specifying an array.

You may have similar issue. Hope it helps.

**Comment by PSchubertMHP** [comment]
Hi, thanks for your resolution. I had a similar problem. One of the schema properties `value` had a list of permitted types. Amongst others an `array` type which had no `items` definition. 
```
"properties": {
  "value": {
    "oneOf": [
      {
        "type": "string"
      },
      {
        "type": "number"
      },
      {
        "type": "boolean"
      },
      {
        "type": "array"
      },
      {
        "type": "object"
      }
    ]
  }
}
```
I removed the `type` definition altogether.
```
"properties": {
  "value": {}
}
```
Which resolved my problem.
