### ISSUE TITLE
[BUG] Kotlin generators should have use-site target field for @JsonProperty annotation

### ISSUE THREAD

**Issue by m-kay** [OpenAPITools/openapi-generator#6185]
In the generated Kotlin data classes there is no use-site target specified on the @JsonProperty annotation. Since constructor paramters are used, Jackson does not recognize this annotation because it is only scanning for field and getter/setter annotations. 
In my case im having problems with a property which should be serialized as `eMailAddress`, but with the default bean naming strategy of Jackson, the serialized property is called `emailAddress`. 
##### OpenAPI declaration file
```yaml
openapi: 3.0.1
info:
  title: Test API
  version: v1
paths:
  /test:
    post:
      tags:
        - User
      operationId: createUser
      requestBody:
        description: The data for the account creation.
        content:
          application/json;charset=utf-8:
            schema:
              $ref: '#/components/schemas/UserInfo'

      responses:
        '201':
          description: The account was created.
components:
  schemas:
    UserInfo:
      required:
        - eMailAddress
      type: object
      properties:
        eMailAddress:
          maxLength: 256
          type: string
          description: The email address of the user.
      description: request object

```
##### Actual generated data class
```kotlin
data class UserInfo(
    @get:NotNull @get:Size(max=256) 
    @JsonProperty("eMailAddress") val eMailAddress: kotlin.String
) {}
```
##### Expected generated data class
```kotlin
data class UserInfo(
    @get:NotNull @get:Size(max=256) 
    @field:JsonProperty("eMailAddress") val eMailAddress: kotlin.String
) {}
```

I'm using the current version 4.3.0 of the generator.

**Comment by DALDEI** [comment]
an alternative (or addition) is to explictly use the kotlin-jackson module which handles data classes and other native kotlin types much better then the core jackson.
With this https://github.com/FasterXML/jackson-module-kotlin
and the no-arg plugin https://kotlinlang.org/docs/reference/compiler-plugins.html
and 1 custom annotation of your choice (for the noarg plugin)
Then data classes work well with no additional annotations or changes.

**Comment by m-kay** [comment]
My problem is not that data classes do not work at all. It's just that properties with a single lowercase letter before the first uppercase (e.g. eMailAddress) are not serialized as configured on the @JsonProperty annotation. This is because Jackson does not read the annotations on the constructor parameters even with the kotlin-jackson module.
Actually I'm already using the kotlin-jackson module since I'm using the generated classes in a spring boot project.
