### ISSUE TITLE
[cpp-restsdk] Dots and dashes are allowed in C++ identifiers. 

### ISSUE THREAD

**Issue by Jauler** [OpenAPITools/openapi-generator#621]
##### Description

When generating cpprest dots and dashes are allowed for C++ identifier names which causes uncompilable code like:
``` C++
class  Io.k8s.kubernetes.pkg.api.v1.Service
    : public ModelBase
{
...
```

##### openapi-generator version

3.1.2-SNAPSHOT

##### openapi declaration file content or url

https://raw.githubusercontent.com/kubernetes/kubernetes/v1.10.4/api/openapi-spec/swagger.json

##### Command line used for generation

```
java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate --generator-name cpp-restsdk --output output -i https://raw.githubusercontent.com/kubernetes/kubernetes/v1.10.4/api/openapi-spec/swagger.json
```

##### Steps to reproduce

Just running above command reproduces the issue.

##### Suggest a fix/enhancement

Maybe map dots to "_", but care must be taken to avoid name clashes.

**Comment by etherealjoy** [comment]
Same issue is solved in Qt5 with #388

**Comment by Jauler** [comment]
Nice, later I will be able to backport those changes to cpprestsdk :).

**Comment by etherealjoy** [comment]
You could make the changes in `AbstractCppCodegen` so that all changes are available for all `C++` generators.

**Comment by Jauler** [comment]
As #631 has been merged, I believe this issue can be closed :)
