### ISSUE TITLE
[BUG] Extra bracket in generate help for --http-user-agent option example

### ISSUE THREAD

**Issue by DiscoPYF** [OpenAPITools/openapi-generator#6210]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When running the following command:
`openapi-generator help generate`

The example of the `--http-user-agent` option contains an extra closing curly bracket:

```
--http-user-agent <http user agent>
            HTTP user agent, e.g. codegen_csharp_api_client, default to
            'OpenAPI-Generator/{packageVersion}}/{language}'
```
It seems `{packageVersion}}` should be `{packageVersion}`.  I assume this is a typo, given that `{language}` contains only one bracket.

This is trivial but I figured it's worth fixing anyway.

##### openapi-generator version

4.3.1

##### Command line used for generation

`openapi-generator help generate`

##### Steps to reproduce

1. Install openapi-generator:

`npm install @openapitools/openapi-generator-cli -g`

2. Run the generate help:

`openapi-generator help generate`

##### Related issues/PRs

I searched but haven't found a similar issue.

##### Suggest a fix

Simply remove the extra closing curly bracket.

**Comment by wing328** [comment]
Yes, it's a typo. I wonder if you can file a PR to fix it when you've time.

**Comment by DiscoPYF** [comment]
Sure, I should be able to have a look before the end of the week.

**Comment by wing328** [comment]
@DiscoPYF thanks. https://github.com/OpenAPITools/openapi-generator/search?q=codegen_csharp_api_client&unscoped_q=codegen_csharp_api_client is a good starting point.

**Comment by DiscoPYF** [comment]
@wing328 Thank you, that was helpful. I will create a PR soon.
