### ISSUE TITLE
[BUG][PHP] Array is not taken into account when content is multipart/form-data

### ISSUE THREAD

**Issue by atanasiuk-hubspot** [OpenAPITools/openapi-generator#6217]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Array is not taken into account when content is multipart/form-data (PHP client). Exception is thrown:
```
Fatal error: Uncaught RuntimeException: Unable to open Array using mode rb: fopen() expects parameter 1 to be a valid path, array given
```

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```json

"requestBody" : {
  "content" : {
    "multipart/form-data" : {
      "schema" : {
        "properties" : {
          "files": {
            "type": "array",
            "items": {
              "type": "string",
              "format": "binary"
            },
            "description": "A list of files containing the data to import"
          }
        }
      }
    }
  }
}
```

##### Command line used for generation

Generating `php` client with
```
java -jar openapi-generator-cli-4.3.1.jar -g php
```

**Comment by ybelenko** [comment]
Closed via #7067
