### ISSUE TITLE
[jersey2-experimental] Generated Java code does not compile when using AnyType

### ISSUE THREAD

**Issue by sebastien-rosset** [OpenAPITools/openapi-generator#6237]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When using the OAS document provided as a link, the generated Java code with the jersey2-experimental library does not compile. 

```
[ERROR]   location: class AaaAbstractAuditRecord
[ERROR] /home/serosset/goroot/src/bitbucket-eng-sjc1.cisco.com/an/ui-an-apidocs/.build/sdk/intersight_java/src/main/java/com/cisco/intersight/client/model/AaaAbstractAuditRecord.java:[253,39] error: cannot find symbol
[ERROR]   symbol:   class oas_any_type_not_mapped
[ERROR]   location: class AaaAbstractAuditRecord
```

##### openapi-generator version

master branch 5/9

##### OpenAPI declaration file content or url

Full OAS document:
https://github.com/CiscoM31/intersight-openapi/blob/master/intersight-openapi-v3.yaml

##### Steps to reproduce

java -jar ./modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java -o tmp -i intersight-openapi-v3.yaml -c codegen/config.json

Configuration:
```
library: jersey2-experimental
java8: true
dateLibrary: java8
fullJavaUtil: false
```

**Comment by sebastien-rosset** [comment]
@wing328

**Comment by wing328** [comment]
Fixed via https://github.com/OpenAPITools/openapi-generator/pull/6246. Let me know if it's still an issue.

**Comment by wing328** [comment]
I found the issue. oneOf (and probably anyOf) doesn't support `null` type at the moment. Will file a fix shortly to make it work with `null`

**Comment by wing328** [comment]
Closing this one as the AnyType issue has been fixed.

I've opened https://github.com/OpenAPITools/openapi-generator/issues/6257 to track the `null` support in oneOf/anyOf in the Java (jersey2-experimental) client instead

**Comment by JohnLimHTL** [comment]
How exactly did you fix the problem? I have the same issue and don't know how i can sole the problem...

**Comment by CyberSteve738** [comment]
@wing328  I have the same question as @JohnLimHTL ! how was it solved?
