### ISSUE TITLE
Invalid Java code generated for inline schemas

### ISSUE THREAD

**Issue by madhead** [OpenAPITools/openapi-generator#624]
##### Description

I'm trying to generate model and API for this schema: http://api.adx1.com/v1.0.2/schema.json using Gradle plugin.

A few of the models are generated incorrectly, making it impossible to compile the code.

I guess, part that error (unminified) is: https://gist.github.com/madhead/ac2cc3fb029db795bfbc6488f315e517#file-swagger-json

The error is:

https://gist.github.com/madhead/ac2cc3fb029db795bfbc6488f315e517#file-gradle-log

This is probably due to using inline style of model definitions?

The resulting Java code is:

https://gist.github.com/madhead/ac2cc3fb029db795bfbc6488f315e517#file-generated-java

As you see, codegen generates `UNKNOWN_BASE_TYPE UNKNOWN_BASE_TYPE` class and parameter which does not compile.

##### openapi-generator version

3.1.1

##### OpenAPI declaration file content or url

http://api.adx1.com/v1.0.2/schema.json

##### Command line used for generation

`./gradlew clean assemble`

##### Steps to reproduce

See description

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

N/A

**Comment by jmini** [comment]
Thank you for reporting this issue, isn't it a duplicate of #8?

**Comment by madhead** [comment]
@jmini Thanks. Sorry, it's a duplicate.

**Comment by jmini** [comment]
There was some work made with #736 for version `3.2.1` can you give this version a try?
(#736 is a start, maybe more use cases needs to be covered as discuss in #8)
