### ISSUE TITLE
[BUG] [Java][jersey2] null type is not supported in oneOf/anyOf

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#6257]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] What's the version of OpenAPI Generator used?
- [ ] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Details of the issue: https://github.com/OpenAPITools/openapi-generator/issues/6237#issuecomment-626584153

##### openapi-generator version

Last master

##### OpenAPI declaration file content or url

https://github.com/CiscoM31/intersight-openapi/blob/master/intersight-openapi-v3.yaml

**Comment by briceburg** [comment]
@wing328 I am getting the following error in plugin 4.3.1, need to revert to 4.3.0 to fix.

```
.../generated/openapi-client/src/main/java/org/openapitools/client/model/OperationResult.java:29: error: cannot find symbol
import org.openapitools.client.model.oas_any_type_not_mapped;
                                    ^
  symbol:   class oas_any_type_not_mapped
  location: package org.openapitools.client.model
```

Config:

```
openApiGenerate {
    generatorName = "java" // https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/java.md
    inputSpec = "$projectDir/openapi.json"
    configOptions = [
            "dateLibrary": "java8",
            "library": "native",
            "java8": "true",
    ]
}
```
