### ISSUE TITLE
[C#] Issue with enum members

### ISSUE THREAD

**Issue by albator1932** [OpenAPITools/openapi-generator#635]
I very recently started to study the migration of our API from _swagger-codegen_ to _openapi-generator_ and I encounter a problem with enumeration members.

Our API is C# .NET Core based and the Swagger JSON is generated through the latest _swashbuckle-aspnetcore_ I believe almost everyone is using in this context.

I'm using the latest stable of openapi-generator: 3.1.1

##### What the swagger-codegen generation looks like:

```
/// <summary>
/// Enum DataMatrix for value: DataMatrix
/// </summary>
[EnumMember(Value = "DataMatrix")]
DataMatrix = 2
```

##### What the openapi-generator generation looks like:

```
/// <summary>
/// Enum DataMatrix for value: DataMatrix
/// </summary>            
DataMatrix = DataMatrix
```

This generation does not compile and gives a "The evaluation of the constant value for 'BarcodeInfo.TypeEnum.DataMatrix' involves a circular definition" error.

Any idea what is going on ?

**Comment by albator1932** [comment]
Nobody even acknowledge that there is indeed an issue with the C# generator being broken?

**Comment by wing328** [comment]
@albator1932 let me look into this...

**Comment by albator1932** [comment]
While browsing the pull requests I found out that Jim made the same observation: https://github.com/OpenAPITools/openapi-generator/pull/737

**Comment by wing328** [comment]
@albator1932 I've filed https://github.com/OpenAPITools/openapi-generator/pull/774. Please review when you've time.

**Comment by albator1932** [comment]
Looks like it's good, I regenerated the client from our project and there is no more enumeration problems, good job!

I do have issues with float values though, they are missing a "f" so it's not confused with double. Not sure if it's related, going to dig this a bit if I have some time today.

**Comment by wing328** [comment]
@albator1932 do you mean float value in enum? or just float in general (model properties, parameters)?

**Comment by albator1932** [comment]
It is always in model properties afaik, for instance I do have this JSON generated in my API:
```
FunctionParameters:{  
   description:"Represents the parameters for a function.",
   required:[  
      "dummy"
   ],
   type:"object",
   properties:{  
      dummy:{  
         format:"float",
         description:"Dummy value for illustration.",
         default:15,
         type:"number"
      }
   }
}
```

And the generated C# result will be:

```
public FunctionParameters(float? dummy = 15.0)
```

**Comment by wing328** [comment]
@albator1932 thanks for the details. Please open a separate issue if you don't mind.

For this PR, if @jimschubert has no concern, I'll merge it later tonight.

**Comment by albator1932** [comment]
Sure, will do.

**Comment by jimschubert** [comment]
@wing328 what PR are you referring to? Looks like you've merged the enum one, and I don't see one for the float issue mentioned.

**Comment by wing328** [comment]
@jimschubert https://github.com/OpenAPITools/openapi-generator/pull/774 (still open)

For the float issue, I've not filed any PR yet.

**Comment by wing328** [comment]
@albator1932 PR merged into master. Thanks again for reporting the issue and sorry for the delay in fixing it.

**Comment by zdarovka** [comment]
Hello all, the problem seem to be still present in all version above 5.1.1

I have just tried to generate csharp-netcore client from the onfido yml specs available here 
https://github.com/onfido/onfido-openapi-spec
![image](https://user-images.githubusercontent.com/5191607/123135225-d5d6dd80-d451-11eb-889f-4f6cb81df15f.png)
