### ISSUE TITLE
[BUG] Plantuml documentation generator not available

### ISSUE THREAD

**Issue by volphy** [OpenAPITools/openapi-generator#6359]
I am trying to build PlantUML documentation from my API specification:
https://openapi-generator.tech/docs/generators/plantuml

I use 4.3.1 release.

`
$ java -jar openapi-generator-cli.jar version
4.3.1
$ java -jar openapi-generator-cli.jar generate -v -i my_api.yaml -g plantuml -o plantuml/
`

Unfortunately, plantuml generator is not found:
`
Can't load config class with name 'plantuml'
Available:
[...]
[error] Check the spelling of the generator's name and try again.
`

Other documentation generators (e.g. html, html2, dynamic-html) work for me.

Is there a special version of Open API generator with bundled plantuml support needed?

**Comment by wing328** [comment]
`plantuml` generator was added after the 4.3.1 release. Please use the latest snapshot version of 5.0.0 instead: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.0.0-SNAPSHOT/

**Comment by volphy** [comment]
Thanks. I used the latest 5.0.0 SNAPSHOT and plantuml generator works (tested with Atlassian Confluence).

Is 5.0.0 going to be released in the near future?

**Comment by wing328** [comment]
Please refer to https://github.com/OpenAPITools/openapi-generator#table-of-contents for the release date.
