### ISSUE TITLE
[BUG] [typescript-axios] Schema requirements from free-form objects not applied to composite schema objects

### ISSUE THREAD

**Issue by chandra-gh** [OpenAPITools/openapi-generator#6369]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

This seems to be a regression in v4.3.1. I use the following method to generate multiple copies of the same schema with different requirements.

```
components:
  schemas:
    BaseProps:
      # object with optional properties id, name and email.
    CreateRequirements:
      # free-form object that requires name.
    CreateObject:
       allOf: BaseProps and CreateRequirements
```

The above code produces an interface called `CreateObject` with one required parameter `name` in v4.3.0 but not in v.4.3.1 and above. It looks like v.4.3.1 and above ignore `CreateRequirements` free-form object. 

##### openapi-generator version

I have tried with v4.3.1 and v5.0.0-SNAPSHOT. Both versions seems to have the issue.

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.3"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      responses:
        '200':
          description: Schema A
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/PetSchemaA"
    post:
      summary: Create a pet
      operationId: createPets
      tags:
        - pets
      responses:
        '201':
          description: Schema B
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PetSchemaB"
components:
  schemas:
    PetProps:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    PetSchemaAReqs:
      type: object
      required:
        - id
    PetSchemaA:
      type: object
      allOf:
        - $ref: '#/components/schemas/PetProps'
        - $ref: '#/components/schemas/PetSchemaAReqs'
    PetSchemaBReqs:
      type: object
      required:
        - name
        - tag
    PetSchemaB:
      type: object
      allOf:
        - $ref: '#/components/schemas/PetProps'
        - $ref: '#/components/schemas/PetSchemaBReqs'
```

##### Command line used for generation

```bash
sudo docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:v4.3.1 generate -i /local/openapi_specs/pet_store.yaml -g typescript-axios -p supportsES6=true -o /local/out/ps-431
```
##### Steps to reproduce

1. Define a free-form object (i.e. without any properties), define some required fields.
2. Define a composite object that combines the free-form object with another object using `allOf`.
3. Generate api client for typescript-axios. The composite object will not inherit any field requirements from the free-form object.

**Comment by amakhrov** [comment]
```
PetSchemaAReqs:
      type: object
      required:
        - id
```

shouldn't you define the id property explicitly here?

**Comment by chandra-gh** [comment]
Hi @amakhrov,
Thanks for reviewing and sharing your thoughts on the bug report. Ultimately, I need the generator to produce the following models.

```
interface PetSchemaA {
  id: number;
  name?: string;
  tag?: string;
}

interface PetSchemaB {
  id?: number;
  name: string;
  tag: string;
}
```

PetSchemaB is used to create a pet. Strictly speaking *id* is not needed in PetSchemaB. 
PetSchemaA is used to update a pet.

I am trying to avoid duplicating the `property` definitions in the API spec like below.

```
schemas:
 PetSchemaA:
    type: object
    required: [id]
    properties:
      id: ..
      name: ..
      tag: ..
 PetSchemaB:
   type: object
   required: [name, tag]
   properties:
     name: ..  # Duplicate
     tag: ..      # Duplicate
```

The real world use case is operating on a user object. In my case create-user, get-user, update-user operations use three different schemas. All the 3 schemas have the same fields but differ in required fields. I used to be able to compose the "final" schemas using free-form objects as shown in the bug description but I can't with v4.3.1.

If the recommended approach is to duplicate the property in each schema then that is fine with me. I will just follow the recommended approach.

**Comment by amakhrov** [comment]
I understand the problem now.
Yeah, I don't have a better answer than duplicating the prop definition right now. That's what we ended up doing in our app also in a similar scenario (using a model for Update with optional fields, while the response should always include all required fields)

**Comment by chandra-gh** [comment]
@amakhrov thanks for sharing your thoughts. Closing the bug.
