### ISSUE TITLE
[C++][Pistache-server] (Type string - format binary) are not well handled - compilation failed

### ISSUE THREAD

**Issue by CyrilleBenard** [OpenAPITools/openapi-generator#638]
##### Description

The use of a _[type string, format binary]_ inside a body generates a miscalled method \<string\>::fromJson(). 

The method generated is as below (see the call to _newItem.fromJson_)
```
void Body::fromJson(nlohmann::json& val)
{
    if(val.find("binaryDataN2Information") != val.end())
    {
        if(!val["binaryDataN2Information"].is_null())
        {
            std::string newItem;
            newItem.fromJson(val["binaryDataN2Information"]);
            setBinaryDataN2Information( newItem );
        }
    }  
}
```

The compilation error looks like :

```
model/Body.cpp: In member function ‘virtual void com::bcom::amf::microservice::server::ms1::model::Body::fromJson(nlohmann::json&)’:
model/Body.cpp:59:21: error: ‘std::__cxx11::string {aka class std::__cxx11::basic_string<char>}’ has no member named ‘fromJson’
             newItem.fromJson(val["binaryDataN2Information"]);
                     ^
```

##### openapi-generator version

3.1.2-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Check wrong generation of a body containing string/binary type
servers:
  - url: http://localhost:8080
paths:
  /check:
    post:
      summary: see title
      tags:
        - Non UE N2 Message Transfer
      operationId: NonUeN2MessageTransfer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: # Request parts
                binaryDataN2Information:
                  type: string
                  format: binary
        required: true
      responses:
        '200':
          description: Non UE N2 Message Transfer successfully initiated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/content'
        default:
          description: Unexpected error


components:
  schemas:
    Bytes:
      format: byte
      type: string

    Content:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Bytes'
```

```json
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Check wrong generation of a body containing string/binary type"
  },
  "servers": [
    {
      "url": "http://localhost:8080"
    }
  ],
  "paths": {
    "/check": {
      "post": {
        "summary": "see title",
        "tags": [
          "Non UE N2 Message Transfer"
        ],
        "operationId": "NonUeN2MessageTransfer",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "binaryDataN2Information": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Non UE N2 Message Transfer successfully initiated.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/content"
                }
              }
            }
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Bytes": {
        "format": "byte",
        "type": "string"
      },
      "Content": {
        "type": "object",
        "properties": {
          "type": {
            "$ref": "#/components/schemas/Bytes"
          }
        }
      }
    }
  }
}
```

##### Command line used for generation

Generate :
```
openapi-generator-cli.sh generate -i ./openapi.yaml -g cpp-pistache-server -c ./config.json -o .
```

Compile :
```
g++ -c  -I./api -I./model -I./impl -Wall -g -std=c++11 -o obj/model/Body.o model/Body.cpp
```

##### Steps to reproduce

Generate & compile

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

Not sure what we are supposed to do :/

**Comment by CyrilleBenard** [comment]
I am not yet able to do a suitable proposal but the idea would be to declare an "Object" class that exposes a fromJson method. The wrong code is probably due to the specialization of the OpenApi type string in a binary format that seems to be ignored by the generator but I may be wrong.

A good idea would be to see how this type is handle in another "lang" and imitate what have been done, if any.

**Comment by CyrilleBenard** [comment]
Ok, after investigating, I may write a proposal. One of right code should be as below :

```
void Body::fromJson(nlohmann::json& val)
{
    if(val.find("binaryDataN2Information") != val.end())
    {
        if(!val["binaryDataN2Information"].is_null())
        {
            setBinaryDataN2Information( val.at("binaryDataN2Information") );
        }
    }  
}
```

There is no need to declare a new type (class) because the type is already well known (std::string), even if its content is binary, so that we can process it immediately.

That's my proposal

**Comment by wing328** [comment]
Shall we use the following tag to handle `binary` format by simply copying the string into the property?
```
{{#isbinary}}
...
{{/isBiinary}}
{{^isBinary}}
...
{{/isBinary}}
```

FYI: "type: string, format: binary" in OAS3 is equivalent to the `file` type in OAS2

**Comment by CyrilleBenard** [comment]
I need some others developers mind / opinion and first, does std::string is the right type to hold string:binary OpenApi type ? 

@etherealjoy @stkrwork

**Comment by etherealjoy** [comment]
@CyrilleBenard 
This is dependent on how this is to be done.
In Qt5 Client the binary is mapped to a file and read as a binary stream

**Comment by Lakhan-123** [comment]
> @CyrilleBenard
> I have generated the client code using cpp-restsdk , with following command
> openapi-generator-cli generate -i ../TS29512_Npcf_SMPolicyControl.yaml -g cpp-restsdk -o .
> but while building the generated code, I am getting the following error .

[82%] Building CXX object CMakeFiles/CppRestOpenAPIClient.dir/src/model/SmPolicyContextData.cpp.o
In file included from /home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/model/SmPolicyContextData.h:22:0,
                 from /home/amantya/5GC_APIs/rough/src/model/SmPolicyContextData.cpp:14:
/home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/ModelBase.h: In instantiation of ‘static web::json::value org::openapitools::client::model::ModelBase::toJson(const std::shared_ptr<_Tp>&) [with T = std::__cxx11::basic_string<char>]’:
/home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/ModelBase.h:199:9:   required from ‘static web::json::value org::openapitools::client::model::ModelBase::toJson(const std::vector<_RealType>&) [with T = std::shared_ptr<std::__cxx11::basic_string<char> >]’
/home/amantya/5GC_APIs/rough/src/model/SmPolicyContextData.cpp:125:99:   required from here
/home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/ModelBase.h:189:23: error: ‘using element_type = class std::__cxx11::basic_string<char> {aka class std::__cxx11::basic_string<char>}’ has no member named ‘toJson’
         retVal = val->toJson();
                  ~~~~~^~~~~~
/home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/ModelBase.h: In instantiation of ‘static bool org::openapitools::client::model::ModelBase::fromJson(const web::json::value&, std::shared_ptr<_Tp>&) [with T = std::__cxx11::basic_string<char>]’:
/home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/ModelBase.h:250:16:   required from ‘static bool org::openapitools::client::model::ModelBase::fromJson(const web::json::value&, std::vector<_RealType>&) [with T = std::shared_ptr<std::__cxx11::basic_string<char> >]’
/home/amantya/5GC_APIs/rough/src/model/SmPolicyContextData.cpp:335:72:   required from here
/home/amantya/5GC_APIs/rough/include/CppRestOpenAPIClient/ModelBase.h:237:22: error: ‘using element_type = class std::__cxx11::basic_string<char> {aka class std::__cxx11::basic_string<char>}’ has no member named ‘fromJson’
         ok = outVal->fromJson(val);
              ~~~~~~~~^~~~~~~~
CMakeFiles/CppRestOpenAPIClient.dir/build.make:3782: recipe for target 'CMakeFiles/CppRestOpenAPIClient.dir/src/model/SmPolicyContextData.cpp.o' failed
make[2]: *** [CMakeFiles/CppRestOpenAPIClient.dir/src/model/SmPolicyContextData.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/CppRestOpenAPIClient.dir/all' failed
make[1]: *** [CMakeFiles/CppRestOpenAPIClient.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

can you please help ?

**Comment by CyrilleBenard** [comment]
Hi @Lakhan-123, 
You're probably facing with a wrong code generation but with so small information, it's hard to bring some support. I would need all the generated code. 
I'm ready to bet that the variables `val` and `outVal` are from `std::string` type and so, the `toJson()` method call can't succeed 😁 
Upload your files under a live storage and give us access or use the "attach files" function on this website (not sure it works for large files - ie zip files)
