### ISSUE TITLE
[python-experimental] loading package cause maximum recursion depth error

### ISSUE THREAD

**Issue by sebastien-rosset** [OpenAPITools/openapi-generator#6402]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When I run codegen against our OpenAPI document, about 2500 files are generated under the 'models' directory, and each of these files have a lot of generated imports.

When the following import line is called from the application code, the import itself causes deep recursion. Obviously it depends on the OAS doc, in my case the recursion depth is around 1015.
```python
import the_package_name
```

The following error occurs:
"RecursionError: maximum recursion depth exceeded"

##### openapi-generator version

master as of May 22.

##### Suggest a fix

A workaround is to increase recursion limit by using  sys.setrecursionlimit:
```python
import sys
sys.setrecursionlimit(1100)
```

**Comment by sebastien-rosset** [comment]
Notes from @spacether : If we want we could make it so models exist only in a sub package
so it would be from petstore.all_models import Cat, Dog (edited) 
That would make loading the package super quick.
Model loading will take as long as it takes to load the related models in memory.
If we removed this loop:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/python-experimental/__init__package.mustache#L37
Package loading will be super quick and will not load any of the models by default.

**Comment by spacether** [comment]
This is caused by loading every model that is possible at the same time.
a good solution here is to
- make a new module, all_models which loads all models into its namespace
- remove the loop importing all models into the package root
- change all documentation and test examples to selectively import specific models rather than importing all models
