### ISSUE TITLE
[REQ] Use NamedParameters in Javascript API calls

### ISSUE THREAD

**Issue by RafaRochaS91** [OpenAPITools/openapi-generator#6410]
### Is your feature request related to a problem? Please describe.
My organisation has been having broken builds because of the changes in the parameter order in the generated `axios` API call methods. 

## Describe the solution you'd like

The most straightforward solution, from the usage perspective, would be having these API calls having named parameters (object arguments) since the order would become irrelevant and wouldn't break the functionality. I.E.:

```javascript
api.someServiceEndpoint.someMethod({ ...params }) {}

```

## Describe alternatives you've considered
We can just manually change the order of the parameters in the generated method calls whenever our pipeline job of building/testing breaks.

## Additional context
Could be interesting to add a flag on generation to have an opt-in way of choosing named parameters or keeping the existing behaviour.

**Comment by wing328** [comment]
We just added an option for that. Can you test with the latest master using the option?

Ref: https://github.com/OpenAPITools/openapi-generator/pull/6288

**Comment by RafaRochaS91** [comment]
Thank you! Will test it :)

**Comment by wing328** [comment]
No problem. Let us know if you need help. closing the issue for the time being.
