### ISSUE TITLE
Generate server by API call is producing "Cannot access tmp folder" message

### ISSUE THREAD

**Issue by LevinGuy** [OpenAPITools/openapi-generator#6426]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When calling for POST server to generate a server (go-server) I am getting the following response:

{"timestamp":"2020-05-25T14:40:03.218Z","status":500,"error":"Internal Server Error","message":"Cannot access tmp folder","path":"/api/gen/servers/go-server"}

curl -X POST "http://api.openapi-generator.tech/api/gen/servers/go-server" -H "Accept: */*" -H "Content-Type: application/json" -d "{\t\"openAPIUrl\": \"\",\t\"options\": {\t\t\"packageName\": \"openapi\",\t\t\"packageVersion\": \"1.0.0\",\t\t\"hideGenerationTimestamp\": \"true\",\t\t\"sourceFolder\": \"go\",\t\t\"serverPort\": \"8080\",\t\t\"featureCORS\": \"false\"\t},\t\"spec\": {\t\t\"openapi\": \"3.0.3\",\t\t\"info\": {\t\t\t\"title\": \"test\",\t\t\t\"description\": \"test\",\t\t\t\"version\": \"0.1\"\t\t},\t\t\"paths\": {},\t\t\"components\": {\t\t\t\"schemas\": {},\t\t\t\"responses\": {},\t\t\t\"parameters\": {},\t\t\t\"examples\": {},\t\t\t\"requestBodies\": {},\t\t\t\"headers\": {},\t\t\t\"securitySchemes\": {},\t\t\t\"links\": {},\t\t\t\"callbacks\": {}\t\t},\t\t\"security\": [],\t\t\"tags\": [{\t\t\t\"name\": \"Alpha\",\t\t\t\"description\": \"\"\t\t}],\t\t\"servers\": []\t}}"

##### openapi-generator version

4.3.0

##### OpenAPI declaration file content or url
```json
{
	"openAPIUrl": "",
	"options": {
		"packageName": "openapi",
		"packageVersion": "1.0.0",
		"hideGenerationTimestamp": "true",
		"sourceFolder": "go",
		"serverPort": "8080",
		"featureCORS": "false"
	},
	"spec": {
		"openapi": "3.0.3",
		"info": {
			"title": "test",
			"description": "test",
			"version": "0.1"
		},
		"paths": {},
		"components": {
			"schemas": {},
			"responses": {},
			"parameters": {},
			"examples": {},
			"requestBodies": {},
			"headers": {},
			"securitySchemes": {},
			"links": {},
			"callbacks": {}
		},
		"security": [],
		"tags": [{
			"name": "Alpha",
			"description": ""
		}],
		"servers": []
	}
}
```

##### Command line used for generation

{
	"openAPIUrl": "",
	"options": {
		"packageName": "openapi",
		"packageVersion": "1.0.0",
		"hideGenerationTimestamp": "true",
		"sourceFolder": "go",
		"serverPort": "8080",
		"featureCORS": "false"
	}
}

##### Steps to reproduce

curl -X POST "http://api.openapi-generator.tech/api/gen/servers/go-server" -H "Accept: */*" -H "Content-Type: application/json" -d "{\t\"openAPIUrl\": \"\",\t\"options\": {\t\t\"packageName\": \"openapi\",\t\t\"packageVersion\": \"1.0.0\",\t\t\"hideGenerationTimestamp\": \"true\",\t\t\"sourceFolder\": \"go\",\t\t\"serverPort\": \"8080\",\t\t\"featureCORS\": \"false\"\t},\t\"spec\": {\t\t\"openapi\": \"3.0.3\",\t\t\"info\": {\t\t\t\"title\": \"test\",\t\t\t\"description\": \"test\",\t\t\t\"version\": \"0.1\"\t\t},\t\t\"paths\": {},\t\t\"components\": {\t\t\t\"schemas\": {},\t\t\t\"responses\": {},\t\t\t\"parameters\": {},\t\t\t\"examples\": {},\t\t\t\"requestBodies\": {},\t\t\t\"headers\": {},\t\t\t\"securitySchemes\": {},\t\t\t\"links\": {},\t\t\t\"callbacks\": {}\t\t},\t\t\"security\": [],\t\t\"tags\": [{\t\t\t\"name\": \"Alpha\",\t\t\t\"description\": \"\"\t\t}],\t\t\"servers\": []\t}}"

##### Suggest a fix

Perhaps it is a permission problem or disk space?

**Comment by hilfor** [comment]
+1

**Comment by nuno-silva** [comment]
Any update on this? :cry: I'm getting the same error:

> {"timestamp":"2020-06-27T19:52:00.241Z","status":500,"error":"Internal Server Error","message":"Cannot access tmp folder","path":"/api/gen/servers/go-server"

**Comment by wing328** [comment]
Fixed and setup monitoring using [checkly](https://checklyhq.com/) to catch the issue moving forward.
