### ISSUE TITLE
[REQ][typescript-angular] Angular 9 providedIn support

### ISSUE THREAD

**Issue by UnleashSpirit** [OpenAPITools/openapi-generator#6432]
Hello,
Angular 9 brings new level for @Injectable, 'any' and 'platform'

### Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
Removing the 'providedInRoot' option as boolean and gives a new one.
Something like 'providedIn' with all the choices :
- none
- root
- any
- platform

May be with keeping default as root ?
And may be a ApiModule.forPlatform() ? (don't even know if it makes sense)

## Additional context

I face that 'issue', which is not a real one for now more an improvement, during Angular Elements creation (WebComponent).
In my case I have a service provided un 'platform' level which also depend on generated service from openapi v3. But a 'platform' service can't use a root level service (null injector)

In any case I think that supporting the new levels of Angular 9 Injectable would be appreciate

**Comment by macjohnny** [comment]
@UnleashSpirit would you like to implement this?

**Comment by UnleashSpirit** [comment]
Waow hmm yeah I can try.
Don't know when but I could be fun :)
How it works ? Fork then modify then pull request right ?

**Comment by macjohnny** [comment]
> Waow hmm yeah I can try.

great

> How it works ? Fork then modify then pull request right ?

exactly, here are some starting points:
https://github.com/OpenAPITools/openapi-generator/blob/b87c927fc26120c8a36ef44b063cb5ffad2f76a7/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L99-L101

https://github.com/OpenAPITools/openapi-generator/blob/b87c927fc26120c8a36ef44b063cb5ffad2f76a7/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L46-L53

**Comment by jogelin** [comment]
@UnleashSpirit did you progress on this one ?

**Comment by UnleashSpirit** [comment]
Hi, unfortunately not yet :(
Trying to find time but hard these days
