### ISSUE TITLE
[BUG][dart-dio] Do not manage to run petstore with dart-dio

### ISSUE THREAD

**Issue by villqrd** [OpenAPITools/openapi-generator#6439]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Cannot run simple petstore exmaple with dart-io. Complains about `*.g.dart` files

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url
 https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml

##### Command line used for generation
```
java -jar openapi-generator-cli.jar generate    -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml    -g dart-dio    -o ./petstore
```
##### Steps to reproduce

Generate the client using the command above, follow the installation guidelines provided in the generated `README.md` and the it fails on import
```
Compiler message:
../deployment/dart/petstore/lib/serializers.dart:13:6: Error: Error when reading '../deployment/dart/petstore/lib/serializers.g.dart': No such file or directory
part 'serializers.g.dart';
     ^
../deployment/dart/petstore/lib/model/error.dart:4:6: Error: Error when reading '../deployment/dart/petstore/lib/model/error.g.dart': No such file or directory
part 'error.g.dart';
     ^
../deployment/dart/petstore/lib/model/pet.dart:4:6: Error: Error when reading '../deployment/dart/petstore/lib/model/pet.g.dart': No such file or directory
part 'pet.g.dart';
     ^
../deployment/dart/petstore/lib/serializers.dart:13:6: Error: Can't use '../deployment/dart/petstore/lib/serializers.g.dart' as a part, because it has no 'part of' declaration.
part 'serializers.g.dart';
     ^
../deployment/dart/petstore/lib/model/error.dart:4:6: Error: Can't use '../deployment/dart/petstore/lib/model/error.g.dart' as a part, because it has no 'part of' declaration.
part 'error.g.dart';
     ^
../deployment/dart/petstore/lib/model/pet.dart:4:6: Error: Can't use '../deployment/dart/petstore/lib/model/pet.g.dart' as a part, because it has no 'part of' declaration.
part 'pet.g.dart';
```

##### Related issues/PRs

Could not find any.

**Disclaimer**
Fairly new to dart and I do not know about those `.g.dart` files, I suppose these are some auto generated files. But they are not present in generated client. The `README.md` does not indicate that I should be doing any additional actions.

**Comment by wing328** [comment]
cc @ircecho (2017/07) @swipesight (2018/09) @jaumard (2018/09) @athornz (2019/12) @amondnet (2019/12)

**Comment by athornz** [comment]
You'll need to run `pub get` and then `pub run build_runner build --delete-conflicting-outputs` to generate those files.

We should add that to the readme

**Comment by freshteapot** [comment]
How I fixed this.

- goto the folder on your local machine that you want to include.
- run 
```
flutter pub get
```

- then run
```
flutter pub run build_runner build --delete-conflicting-outputs
```

**Comment by kuhnroyal** [comment]
I have added https://github.com/OpenAPITools/openapi-generator/pull/8025 which add integration tests that can be run and showcase the usage. I think this issue can be closed.
