### ISSUE TITLE
[REQ] [Gradle] Support Gradle Cache for Gradle Plugin "org.openapi.generator"

### ISSUE THREAD

**Issue by HenningWaack** [OpenAPITools/openapi-generator#6472]
##### Description

The Gradle Plugin "org.openapi.generator" does not support caching, since build inputs and outputs are not declared and the task types are not cachable, see https://docs.gradle.org/current/userguide/custom_gradle_types.html and https://docs.gradle.org/current/userguide/build_cache.html#sec:task_output_caching_details

##### openapi-generator version

v4.x

##### Steps to reproduce

Run `gradle openApiGenerate --info` multiple times. The generator tasks are executed every time, no caching is done.

##### Suggest a fix/enhancement

Enhance current Gradle plugin to support Caching by declaring @Input and @OutputDirectory annotations.

**Comment by sesamzoo** [comment]
Looks like this duplicates #4492.
