### ISSUE TITLE
[BUG] Online generator exits with HTTP-500

### ISSUE THREAD

**Issue by truschival** [OpenAPITools/openapi-generator#6500]
##### Description

Requests to generate client code for languages fails with HTTP error 500:
```
{"timestamp":"2020-05-30T11:05:36.329Z","status":500,"error":"Internal Server Error","message":"Cannot access tmp folder","path":"/api/gen/clients/python"}
    link = request_client_module(build_document_url())
  File "buildscripts/get_openapi_client.py", line 47, in request_client_module
    req.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error:  for url: https://api.openapi-generator.tech/api/gen/clients/python
``` 
This fails for a previously working version of my openapi.yaml file [https://raw.githubusercontent.com/truschival/DigitalRoosterGui/250d0ea04df98e04154ef9551f19adf1de3f4b06/REST/openapi.yml] 

This also fails for the default minimum working request using the gui frontend at (http://api.openapi-generator.tech/index.html) trying to generate clients for python or node.

With this front end generated example request body
```
curl -X POST "http://api.openapi-generator.tech/api/gen/clients/node" -H "Accept: */*" -H "Content-Type: application/json" -d "{ \"openAPIUrl\": \"https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml\"}" 
```

the api responds:
```
{
  "timestamp": "2020-05-30T11:18:25.678Z",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Cannot access tmp folder",
  "path": "/api/gen/clients/node"
}
```

##### openapi-generator version
Today's versions, don't know

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml

**Comment by wing328** [comment]
Rollback to 4.3.0 for the time being.

Btw `node` is not a valid client generator name. Please try `javascript` instead.

**Comment by ashutoshkumr** [comment]
Hello, thank you for tracking this issue.
- Seeing this issue for python as well.
- Seeing this even when I pass JSON spec in payload instead of openAPIUrl

Is there any workaround currently ? (apart from using offline generators)

```
curl -X POST "http://api.openapi-generator.tech/api/gen/clients/python" -H "Accept: */*" -H "Content-Type: application/json" -d "{ \"openAPIUrl\": \"https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml\"}"

{"timestamp":"2020-06-23T18:42:15.324Z","status":500,"error":"Internal Server Error","message":"Cannot access tmp folder","path":"/api/gen/clients/python"}
```

**Comment by truschival** [comment]
@ashutoshkumr : My original issue also was with python, the error however is not language specific.  It was fixed for a short while (about three weeks ago) but last weekend my CI-build was broken again with the same issue.

**Comment by ashutoshkumr** [comment]
Thanks @truschival for the context. @wing328 could you please suggest what should be done next here ?

**Comment by wing328** [comment]
Fixed and setup monitoring using [checkly](https://checklyhq.com/) to catch the issue moving forward.
