### ISSUE TITLE
[BUG] [java][asyncNative] failed to build the client generated with null async return

### ISSUE THREAD

**Issue by bgong-mdsol** [OpenAPITools/openapi-generator#6550]
##### Description

Failed to build the client generated on Java11 with null async return via `mvn`. Please see below for detail.

##### openapi-generator version

Tried the both openapi-generator 4.3.0 and 5.0.0

##### OpenAPI declaration file content or url

I am able to reproduce the issue with `petstore.yaml` provided by openapi-generator

##### Command line used for generation

openapi-generator generate -g java --library native -p asyncNative=true

##### Steps to reproduce

1. `git clone` to get the latest source of openapi-generator (5.0.0);
2. `mvn clean install`to build the modules of openapi-generator;
3. launch the command to generate the client of petstore
```
templateDir=<openapi-generator folder>/modules/open-apigenerator/src/main/resources/Java/libraries/native
apiSpecFile=/<openapi-generator folder>/modules/openapi-generator/src/test/resources/3_0/petstore.yaml
openapi-generator generate -g java --library native -p asyncNative=true -t $templateDir $apiSpecFile -o myclient
```
4. check `myclient`generated, failed to compile with `mvn clclean install`, got errors:
```
[ERROR] myclient/src/main/java/org/openapitools/client/api/PetApi.java:[164,17] exception java.io.IOException is never thrown in body of corresponding try statement
[ERROR]  myclient/src/main/java/org/openapitools/client/api/PetApi.java:[433,17] exception java.io.IOException is never thrown in body of corresponding try statement
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/6168/files#diff-d348a3a8a0ce0b350a361a7d81856de3R192-R194

##### Suggest a fix

```
              {{#returnType}}
              try {
                  return CompletableFuture.completedFuture(
                      memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<{{{returnType}}}>() {})
                  );
              } catch (IOException e) {
                  return CompletableFuture.failedFuture(new ApiException(e));
              }
              {{/returnType}}{{^returnType}}
              return CompletableFuture.completedFuture(null);
              {{/returnType}}
```

**Comment by wing328** [comment]
Can you please file a PR so that we can review more easily?

I would suggest
```
              {{/returnType}}
              {{^returnType}}
```
instead of
```
              {{/returnType}}{{^returnType}}
```

**Comment by bgong-mdsol** [comment]
> Can you please file a PR so that we can review more easily?
> 
> I would suggest
> 
> ```
>               {{/returnType}}
>               {{^returnType}}
> ```
> 
> instead of
> 
> ```
>               {{/returnType}}{{^returnType}}
> ```

Here is [the fix](https://github.com/OpenAPITools/openapi-generator/blob/2a0e4abdf0dc9f25c4fe0c804afd930bdf7fa8e8/modules/openapi-generator/src/main/resources/Java/libraries/native/api.mustache#L213-L223)

**Comment by bgong-mdsol** [comment]
@wing328 Can you review [the PR](https://github.com/OpenAPITools/openapi-generator/pull/5961) above? Thanks a lot
