### ISSUE TITLE
[BUG][JAVA] Exception in thread "main" java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by cobraz** [OpenAPITools/openapi-generator#6597]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?

##### Description

Trying to generate a quite large ~1mb Swagger-file. It had some validation issues, and I tried to fix them. Don't know if those are relevant, since no matter if it's fixed or not, no dice. Still «Java heap space» issue.

Relevant issue: bjerkio/tripletexjs#14
Reproduce the issue with this repository: https://github.com/bjerkio/tripletexjs/tree/reproduce

##### openapi-generator version

`4.3.1`

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/bjerkio/tripletexjs/reproduce/swagger-fixed.json

##### Command line used for generation

`make generate` or

```shell
java -Xmx4G -jar openapi-generator-cli.jar \
	generate \
	-i ./swagger-fixed.json \
	-g typescript-fetch \
	-o ./out -v
```

##### Steps to reproduce

```shell
> git clone git@github.com:bjerkio/tripletexjs.git
> git checkout reproduce
> make generate
```

##### Related issues/PRs

- OpenAPITools/openapi-generator#2503
- OpenAPITools/openapi-generator#4398
- OpenAPITools/openapi-generator#5201.

##### Suggest a fix

I'm lost.

@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

**Comment by cobraz** [comment]
Any updates on this?

**Comment by jtrueblood-anaqua** [comment]
Hey cobraz,

We are experiencing the same issue. I'm going to gather info an post in a few.

Thanks,
Jeff

**Comment by cobraz** [comment]
@jtrueblood-anaqua Did you get some info to post?

**Comment by cobraz** [comment]
Bump ❤️

**Comment by cobraz** [comment]
Closing this. We have moved away from this library.

**Comment by davija** [comment]
Can we please re-open this?  The issue still exists and should be fixed without respect to the original poster using this library or not.

**Comment by davija** [comment]
FYI, one thing I found to get around this was:
* Use a 64-bit JDK/JRE
* Set an environment variable for JAVA_OPTS="-Xmx4g"
  * (or some other amount of memory... starting at 2g and incrementing until you can get one to finish)

**Comment by cobraz** [comment]
@agilob @davija reopened. Hope we'll get this fixed :)

re
@bbdouglas @sreeshas @jfiala @lukoyanov @cbornet @jeff9finger @karismann @Zomzog @lwlee2608 @bkabrda

**Comment by agilob** [comment]
I will be slowly looking into it step after step, trying to pick low hanging fruits first, one PR is ready #8181 reduces number of open files, closes resources much sooner. Should help, but I didn't do any professional profiling for it.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/8731 to workaround the issue for the time being.
