### ISSUE TITLE
[BUG] Generation of go client gives uncompilable code

### ISSUE THREAD

**Issue by cscetbon** [OpenAPITools/openapi-generator#6610]
#### Bug Report Checklist

You can use code at https://github.com/cscetbon/cassandrasidecar-go-client to reproduce the issue.  tried with go [a59bbf](https://github.com/cscetbon/cassandrasidecar-go-client/commit/a59bbf58bfa6f739e3984cbb255f7caa839c94d8) and go-experimental [e06d67](https://github.com/cscetbon/cassandrasidecar-go-client/commit/e06d6701a2afe01e604080bc18b8fb0d05c623d6)

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
I did but it works with swagger-codegen except it forgets to import github.com/antihax/optional in files where it uses that type for some reason.
- What's the version of OpenAPI Generator used?
http://api.openapi-generator.tech/api/gen
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
The first one gives me [this output](https://pastebin.com/raw/qbW3qBQC) when trying to use in a sample code like https://play.golang.org/p/gHxTLTU6GN4 (be careful I added one more commit for go-experimental so the playground might download the latest instead of  v0.0.0-20200610023546-a59bbf58bfa6). It complains about unknown types.

Trying use go-experimental I an error about an undefined type 

```
../pkg/mod/github.com/cscetbon/cassandrasidecar-go-client@v0.0.0-20200610030457-e06d6701a2af/pkg/cassandrasidecar/api_operations.go:244:19: undefined: UNKNOWN_BASE_TYPE
note: module requires Go 1.14
```

##### Description

go client fails to compile.

##### openapi-generator version

I used the API http://api.openapi-generator.tech/api/gen

##### OpenAPI declaration file content or url
https://raw.githubusercontent.com/instaclustr/cassandra-sidecar/master/spec.yaml

##### Steps to reproduce

Code is available in each commit I mentioned and you can even regenerate it using the script located at the root level.

**Comment by wing328** [comment]
@cscetbon can you please give it another try with the latest master? SNAPSHOT version available in the README.

Will reopen if it's still an issue.
