### ISSUE TITLE
TypeError: Object has no member 'delete'

### ISSUE THREAD

**Issue by PoojaKokilXor** [OpenAPITools/openapi-generator#6623]
I have created the K6 test script using open api generator but while running it getting following error only for delete request:
TypeError: Object has no member 'delete'

**Comment by mostafa** [comment]
Hi @PoojaKokilXor,

Thanks for reporting this. The actual HTTP verb in k6 is `del`. I'll fix it.

**Comment by mostafa** [comment]
Hi @ybelenko, @wing328 and @PoojaKokilXor,

The issue is fixed and can be closed.
