### ISSUE TITLE
[PHP] Generate SDK into root directory not into a folder 

### ISSUE THREAD

**Issue by developersteve** [OpenAPITools/openapi-generator#663]
##### Description

Currently PHP generation is one of the only libs to generate into a folder inside the nominated root directory

##### openapi-generator version

3.1.1 but has been doing it since 2

##### Steps to reproduce

Generate a standard PHP SDK

##### Suggest a fix/enhancement

Generation to occur in the base directory rather than the named folder inside the base directory

**Comment by wing328** [comment]
@developersteve thanks for the suggestion. I also agree we should make the generators more consistent.

I've filed #681 to remove package path from the default output folder (path)

**Comment by wing328** [comment]
@developersteve PR merged into master and you can find the change in the v3.2.0 released yesterday.

**Comment by developersteve** [comment]
Awesome thank you
