### ISSUE TITLE
[typescript-fetch] Set credentials parameter on fetchApi

### ISSUE THREAD

**Issue by siada** [OpenAPITools/openapi-generator#6639]
Does anyone have an example of how to pass my own fetch function to the Configuration object of typescript-fetch?

I've run into an issue that I believe is caused by 'credentials' being set to 'omit' by default on older versions of edge, so I'd like to explicitly set this to same-origin

It looks like I can override the default behaviour by setting the fetchApi property, but I can't work out what I need to set this to

An example of what I'm after, instead of:
```
fetch("https://www.google.com/")
```

I need
```
fetch("https://www.google.com/", {
  credentials: 'same-origin'
})
```

**Comment by siada** [comment]
nevermind - as I posted this i looked at the line of code I needed 🤦‍♂️

**Comment by kbroncel** [comment]
Could you answer your own question? I'm currently having the same problem.

**Comment by marcelkorpel** [comment]
Can you please show how you did this?
