### ISSUE TITLE
[BUG] typescript-angular package.json missing

### ISSUE THREAD

**Issue by FlorianLudwig** [OpenAPITools/openapi-generator#6655]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The `typescript-angular` generator does have a `package.mustache` file but no `package.json` is generated.

##### openapi-generator version

```
openapi-generator-cli 5.0.0-SNAPSHOT
  commit : 3f38684
  built  : 2020-06-14T10:20:10Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/

```

##### OpenAPI declaration file content or url
any

##### Command line used for generation

```
generate  -i any_openapi.json -g typescript-angular 
```

##### Suggest a fix

One of:
- Remove the package.mustache and references (at least in README)
- Actually

**Comment by macjohnny** [comment]
the package.json is generated if the configuration property `npmName` is defined, see
https://github.com/OpenAPITools/openapi-generator/blob/2460cfccfa16c099583c25562efdb2f4a84b1b3e/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptAngularClientCodegen.java#L154-L156

https://github.com/OpenAPITools/openapi-generator/blob/2460cfccfa16c099583c25562efdb2f4a84b1b3e/bin/configs/typescript-angular-with-npm-v8.yaml#L7

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-angular-v8-provided-in-root/builds/with-npm/package.json

**Comment by FlorianLudwig** [comment]
@macjohnny the README.md lists to use `npm install` as first step - with won't work without the package.json. So maybe remove that part of the readme? Or point out that npmName is missing?

**Comment by macjohnny** [comment]
You are right, The readme could be improved. However, it is recommended to look at the generated code as well
