### ISSUE TITLE
[REQ][Go] Pass r.Context into handlers

### ISSUE THREAD

**Issue by metalmatze** [OpenAPITools/openapi-generator#6657]
### Is your feature request related to a problem? Please describe.

I would like to propagate the request context through all levels of my application, so that I can use consistent request tracing across applications.

## Describe the solution you'd like

Right now the generated handlers do not pass along the request or at least the request context. This can easily be fixed by:

```diff
func (c *DeploymentApiController) GetCurrentDeployment(w http.ResponseWriter, r *http.Request) {
-	result, err := c.service.GetCurrentDeployment()
+	result, err := c.service.GetCurrentDeployment(r.Context)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
```

Then all handlers of the services we need to implement have `ctx context.Context` as first argument. This should also make it possible for requests to close longer taking requests. If that's possible we could even cancel pretty heavy SQL queries etc.

## Describe alternatives you've considered

Didn't really consider an alternative, as this is pretty much what every one in Go does these days. :blush:

**Comment by metalmatze** [comment]
Ah, I didn't mention that his is for the Go Server and not the client.

**Comment by metalmatze** [comment]
Anyone to take a look. I'm happy to work on a PR, but want to know if that's wanted first.

**Comment by metalmatze** [comment]
Hey @antihax @bvwells @grokify @kemokemo @bkabrda :blush:

**Comment by kemokemo** [comment]
@metalmatze Thank you for registering the issue. 😄 
I feel that this is a very good suggestion indeed. It would be great if you could make a pull request.
