### ISSUE TITLE
[Question] How can a extension Tags (x-...) be accessed in mustache

### ISSUE THREAD

**Issue by emreakca** [OpenAPITools/openapi-generator#666]
##### Description

Hello, I want to use my extension
```yaml
responses:
  201:
    x-isReturnTypeModel: true
```
in the java (resttemplate library) mustache template. 
I already tried 
```yaml
{{extensions}}
{{{extensions}}}
{{#extensions}}{{/extensions}}
```
inside the operation tag, but with no success.
 
How can I get the wanted value?

**Comment by wing328** [comment]
Please try the following:
```
{{^vendorExtensions.x-isReturnTypeModel}}
The extension is not set
{{/vendorExtensions.x-isReturnTypeModel}}
{{#vendorExtensions.x-isReturnTypeModel}}
{{{.}}}
{{/vendorExtensions.x-isReturnTypeModel}}
```

**Comment by wing328** [comment]
@emreakca If you don't mind, can you contact me via the email address in my Github profile? Just a few quick questions if you don't mind.
