### ISSUE TITLE
 [BUG] Rxjava 2 is not used 

### ISSUE THREAD

**Issue by oberstrike** [OpenAPITools/openapi-generator#6664]
Hello, everyone,
I am trying to create a Kotlin client with Open api (NPM version: 6.12.1).
For this I use the following Config.

`{ "groupId": "de.example", "packageName": "source", "artartifactId": "Generated-Server", "artifactVersion": "0.0.1", "library": "jvm-retrofit2", "useRxJava2": true, "modelMutable": true }`

The command i use:
`openapi-generator generate -i main.yml -c config.json -g kotlin`

In the end Retrofit is used, but not rxJava.
Even with the (currently) newest Jar version it does not work.
I hope we can solve the problem.
Thanks a lot

**Comment by wing328** [comment]
> Open api (NPM version: 6.12.1).

How did you install `openapi-generator`?

For JAR, are you building it from the latest master?

**Comment by oberstrike** [comment]
Hi wing328,

Thank you for adding the Client label!
I installed the generator with npm (npm install) and the CLI is the jar with version 4.3.1.

Many thanks for your quick response.

**Comment by wing328** [comment]
Can you please try the latest snapshot version instead?

https://github.com/OpenAPITools/openapi-generator#11---compatibility

**Comment by oberstrike** [comment]
Yeah, that works. Maybe it should be indicated somewhere that it only works with the snapshot version!

**Comment by wing328** [comment]
The enhancement (PR) was recently merged and will be included in the upcoming stable release.
