### ISSUE TITLE
[BUG] PHP unknown symbols

### ISSUE THREAD

**Issue by ro0NL** [OpenAPITools/openapi-generator#6668]
```diff
- * OpenAPI Generator version: 4.2.3
+ * OpenAPI Generator version: 4.3.1
```

After re-generating, the SDK contains `AnyType` symbols, which are - by default - unknown symbols in PHP.

**Comment by ro0NL** [comment]
i figure most of https://github.com/OpenAPITools/openapi-generator/search?q=anytype&type=Issues is related :sweat_smile:

**Comment by wing328** [comment]
`AnyType` is something we recently added.

What about mapping `AnyType` to `mixed` in the Abstract PHP Codegen class?
