### ISSUE TITLE
[dart-dio] multi-part file should accept filename

### ISSUE THREAD

**Issue by ayushin** [OpenAPITools/openapi-generator#6671]
Right now multipart forms methods are generated with `Uint8List` type fields and hard-coded filename as the field name:

 ```
        Map<String, dynamic> formData = {};
                if (image != null) {
                    formData[r'image'] = MultipartFile.fromBytes(image, filename: r'image');
                }
        bodyData = FormData.fromMap(formData);
```

Which is incorrect, unsuitable for certain backends.

I think it is more suitable to generate these fields as  `MultipartFile` and let the upstream handle the MultipartFile generation, just like `dart` generator does.

**Comment by kuhnroyal** [comment]
This should be working by now, can you check on master?

**Comment by ayushin** [comment]
Hi, this is still not working, because the generated methods still take Uint8List so there is no way to pass the filename to them, like this:

```
      if (avatar != null) r'avatar': MultipartFile.fromBytes(avatar, filename: r'avatar'),
```
Here I would expect to pass MultipartFile and do fromBytes in my application with the filename.

**Comment by ayushin** [comment]
@kuhnroyal how this supposed to work?

**Comment by kuhnroyal** [comment]
Yea looks like this needs more work, filename is always the same as the parameter name.

**Comment by ayushin** [comment]
Can we please re-open this issue?

**Comment by ayushin** [comment]
The fix is very easy - pass entire MultipartFile as argument not the Uint8List.

We can make it dynamic for backward compatibility and check type

**Comment by ayushin** [comment]
Here is a pull request with a breaking change: the generated api methods now accept MultipartFile instead of Uint8List which I think is more logical.

https://github.com/OpenAPITools/openapi-generator/pull/9149

**Comment by kuhnroyal** [comment]
This is your issue, you should be able to re-open it? It is not locked.
Need to think how we can handle the breaking change, dynamic is not a good solution.

**Comment by ayushin** [comment]
@kuhnroyal I can't re-open it because I did not close it myself
