### ISSUE TITLE
[BUG] [typescript-jquery] Code-generator optional array query parameter results in push on undefined array

### ISSUE THREAD

**Issue by Nalaxon** [OpenAPITools/openapi-generator#6692]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Defining an optional query parameter (```configurationRevision``` in the shown yml) as array, the serialization seems to be wrong, and result in runtime error:
```"Cannot read property 'push' of undefined"```

Serialized code (api/MeasurementsApi.ts):
```typescript
if (configurationRevision) {
            configurationRevision.forEach((element: any) => {
                queryParameters['configurationRevision[]'].push(element);
            });
        }
```

It does not work with https://editor.swagger.io/ either, see Issue: https://github.com/swagger-api/swagger-codegen/issues/10280

##### openapi-generator version

openapi-generator version: 4.3.1
openjdk build: 10.0.2+13
Windows 10

##### OpenAPI declaration file content or url

```yaml
swagger: '2.0'
info:
  description: Interface of REST Service for the Webclient
  version: 2.0.0
  title: REST Interface for Webclient
basePath: /api
tags:
  - name: configurations
paths:
  /measurements:
    get:
      tags:
        - measurements
      description: Returns all measurements
      parameters:
        - name: configurationId
          in: query
          description: Configuration ID
          required: false
          type: integer
          format: int32
        - name: configurationRevision[]
          in: query
          description: Configuration Revision
          required: false
          type: array
          items:
            type: integer
            format: int32
          collectionFormat: multi
      operationId: measurements
      produces:
        - application/json
      responses:
        '200':
          description: All available measurements
          schema:
            type: array
            items:
              type: integer
```

##### Command line used for generation

```openapi-generator generate -i test.yaml -g typescript-jquery -o out\ts-test\```

##### Suggest a fix

Create an emtpy array, to make push available.
```typescript
if (configurationRevision) {
  queryParameters['configurationRevision[]'] = new Array<number>();
  configurationRevision.forEach((element: any) => {
    queryParameters['configurationRevision[]'].push(element);
  });
 }
```

**Comment by macjohnny** [comment]
@Nalaxon would you like to file a PR to fix this?

**Comment by Nalaxon** [comment]
@macjohnny I would like to try yes, because it seems like a one liner, but I am unsure if I am capable to do it.
William already pointed me in a direction (refactored typescript generator), I will have a look on that on the weekend. And let you know if I am not able to do it

**Comment by Nalaxon** [comment]
> @Nalaxon would you like to file a PR to fix this?

I fixed the issue and working through the PR template.

`mvn -Pstatic-analysis clean install`
raises errors in both my branch and the master.

The examples do not include optional query with style` collectionFormat : multi`
Should I add it?

**Comment by macjohnny** [comment]
> I fixed the issue and working through the PR template.

thanks 
> `mvn -Pstatic-analysis clean install`
> raises errors in both my branch and the master.

you can also run
```
mvn clean package -DskipTests=true
```

> The examples do not include optional query with style` collectionFormat : multi`
> Should I add it?

if you want, you can add it, but it is not required
