### ISSUE TITLE
NullPointerException when run "validate" with OAS2 spec

### ISSUE THREAD

**Issue by ackintosh** [OpenAPITools/openapi-generator#67]
##### Description

```
$ java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar validate -i modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml
Validating spec file (modules/openapi-generator/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml)
Exception in thread "main" java.lang.NullPointerException
        at java.util.HashSet.<init>(HashSet.java:118)
        at org.openapitools.codegen.cmd.Validate.run(Validate.java:44)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:52)
```

##### openapi-generator version

Latest master

##### Suggest a fix/enhancement

It may caused by [SwaggerConverter](https://github.com/ackintosh/swagger-parser/blob/c959d1df580b8af37f4ffd3a1ee04f6c172499cc/modules/swagger-parser-v2-converter/src/main/java/io/swagger/v3/parser/converter/SwaggerConverter.java#L123) as the converter doesn't [set message](https://github.com/ackintosh/swagger-parser/blob/8acfafa6a4dd2e808b0c2f6067d2860810f3c9dc/modules/swagger-parser-core/src/main/java/io/swagger/v3/parser/core/models/SwaggerParseResult.java#L19).

In case of parsing OAS3, OpenAPIDeserializer [sets message](https://github.com/ackintosh/swagger-parser/blob/0a51b0baa92b5889e5ebe3bdf666961d39b83104/modules/swagger-parser-v3/src/main/java/io/swagger/v3/parser/util/OpenAPIDeserializer.java#L105).

I think that SwaggerConverter should set the message as well.

**Comment by ackintosh** [comment]
I'll file the PR that fixes the issue to https://github.com/OpenAPITools/swagger-parser

**Comment by jmini** [comment]
This depends from swagger-api/swagger-parser#710

**Comment by ackintosh** [comment]
I changed my mind, I'll file a PR to original swagger-parser.

**Comment by jmini** [comment]
With #123 we use `swagger-parser` version `2.0.1-SNAPSHOT`. This should fix this issue.

**Comment by ackintosh** [comment]
Confirmed this issue is fixed with #123 👍 This issue will be closed after 3.0.0 release.

**Comment by jmini** [comment]
Anything left to do here? or can we close this issue?

**Comment by ackintosh** [comment]
Nothing to do for this issue.  🎉
