### ISSUE TITLE
Java/RestTemplate - Allow flexible options in generated client when a file is needed

### ISSUE THREAD

**Issue by MosheElisha** [OpenAPITools/openapi-generator#6715]
Hi,

I have an API that requires a org.springframework.web.multipart.MultipartFile parameter (Swagger 2.0 API spec is below).

I am using generatorName=java and library=resttemplate to generate the client.

The generated Api client looks like:

```
public ResponseEntity<Template> createTemplateWithHttpInfo(File file, com.example.model.CreateTemplateRequest request) throws RestClientException {
...
    if (file != null)
            formParams.add("file", new FileSystemResource(file));
...
```

I would like to have the option to generate a client that takes an `org.springframework.core.io.AbstractResource` instead of a `File`.
The user will be able to pass a `new FileSystemResource(file)` to have same behavior as now but if the user does not have the file on disk, he/she can use an `InputStreamResource` or a `ByteArrayResource` or ... For example:

```
    api.createTemplateWithHttpInfo(
        new ByteArrayResource(byteArray) {
          @Override
          public String getFilename() {
            return "memoryBytes";
          }
        },
        ...
    );
```

From the source code it seems that there is no such option: https://github.com/OpenAPITools/openapi-generator/blob/5cdc9e9e35b737b04a5a201446fb430a554ef5db/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache#L133

I'm proposing a new configOption (something like "useAbstractionForFiles") and every library can try to support as possible (My first priority is to have the resttemplate library support this).

Swagger 2.0 API spec:
```
      "post" : {
        "operationId" : "createTemplate",
        "consumes" : [ "multipart/form-data" ],
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "file",
          "in" : "formData",
          "required" : true,
          "type" : "ref"
        }, {
          "name" : "request",
          "in" : "formData",
          "required" : true,
          "type" : "ref"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/Template"
            }
          },
          "201" : {
            "description" : ""
          }
        }
      }
    }
```

**Comment by MosheElisha** [comment]
@wing328 Can you please start the discussion or assign to / tag relevant engineers? Thanks.

**Comment by wing328** [comment]
As discussed, it looks reasonable to me to add another option to meet the requirement. Please go ahead to submit a PR and we'll review the change accordingly.

**Comment by nrgraham23** [comment]
Hello,

Is there documentation on how this is used?

I am using gradle and have done the following:

Added this to my dependencies: 

`compile group: 'org.springframework.android', name: 'spring-android-rest-template', version: '1.0.1.RELEASE'`

Updated our generator:

`id "org.openapi.generator" version "5.0.0-beta"`

And added this option to the configOptions:

`    configOptions = [
            dateLibrary: "java8",
            serializationLibrary: "jackson",
            useAbstractionForFiles: "true"
      ]`

However, the method signature still returns a File:

`public File dooFoo(String foo) throws ApiException`

Thanks for adding this feature!

**Comment by MosheElisha** [comment]
Hi,

The feature is not included in 5.0.0-beta and will be included in 5.0.0-beta2 that is expected to be released in 30.07.2020.
If you would like to test this feature earlier, you should use the latest 5.0.0-SNAPSHOT.

**Comment by ogerardin** [comment]
This is a good idea, but is there a reason for not using the interface Resource instead of AbstractResource ?

**Comment by MosheElisha** [comment]
> This is a good idea, but is there a reason for not using the interface Resource instead of AbstractResource ?

Good question :-). No good reason except it was just missed. I will change it to Resource soon. Thanks!

**Comment by iyzana** [comment]
It seems like this option should be present for the webclient generator as well

**Comment by sblumenstock-doubleSlash** [comment]
How can I use this with the command line?
`openapi-generator-cli generate -i petstore.yaml -g java --library=resttemplate --useAbstractionForFiles=true -o ./Desktop/OpenApi/test1`

This is not working: `[error] Found unexpected parameters: [--useAbstractionForFiles=true]`

**Comment by MosheElisha** [comment]
@sblumenstock-doubleSlash  Because this is a config option, I believe you should use the `additional-properties` flag:

```
--additional-properties=useAbstractionForFiles=true
```

More details here: https://openapi-generator.tech/docs/usage/#additional-properties

**Comment by sblumenstock-doubleSlash** [comment]
Ahh thank you! :) 
I missed that.

**Comment by sblumenstock-doubleSlash** [comment]
Is this only implemented when uploading a file?
When I generate a client, the downloads are still files.
Doesn't it also make sense to implement this in the downloads?

**Comment by MosheElisha** [comment]
It is currently implemented for uploading files. That was my immediate need. Agree that it will be useful to get an InputStream (or similar) when downloading as well.

I don't have time to do it now but maybe in the future. If it is important for you, please feel free.

**Comment by sblumenstock-doubleSlash** [comment]
I tried to solve it by myself, but I got an issue.
` public {{#returnType}}{{#isFile}}{{#useAbstractionForFiles}}...` 
IsFile cannot be used for returnType. How do I implement this?

**Comment by sblumenstock-doubleSlash** [comment]
> I tried to solve it by myself, but I got an issue.
> ` public {{#returnType}}{{#isFile}}{{#useAbstractionForFiles}}...`
> IsFile cannot be used for returnType. How do I implement this?

How can I check if the `returnType` is a file?
Is there a `boolean` that checks this?
