### ISSUE TITLE
[REQ][core] Add Mock feature to feature matrix

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#6718]
### Is your feature request related to a problem? Please describe.

Feature matrix created by @jimschubert is great. I would love to see `Mock` feature there, because I've spent so many hours on the first release of PHP Data Mocker and it will be really disappointing if nobody notice it.

## Describe the solution you'd like

I think `Mock Server` or just `Mock` feature fits `modules/openapi-generator-core/src/main/java/org/openapitools/codegen/meta/features/GlobalFeature.java` class.

**Comment by jimschubert** [comment]
You're welcome to add mock server generation as a feature metadata. We'll just want to make sure it's not set to enabled by default if it's not a generic solution.

**Comment by ybelenko** [comment]
> You're welcome to add mock server generation as a feature metadata.

How should I do that? Is there any guide?

> We'll just want to make sure it's not set to enabled by default if it's not a generic solution.

Right now it's included in PHP Slim4 server only and yeah, it's disabled by default. It's disabled by default configuration, but mock package is installed.

**Comment by ybelenko** [comment]
@jimschubert All I ask for:
## FEATURE SET

### Client Modification Feature

| Name | Supported | Defined By |
|:------:|:----------:|:----------:|
| Mock Server | ✅ | Tooling Extension |

All rest server generators obviously will have ❌ icon next to that feature.

I don't mind if you'll add it to different feature category or if you'll rename the feature itself.

**Comment by jimschubert** [comment]
Thanks for contributing the change! I was just about to do this really quick and you'd already done it!
