### ISSUE TITLE
[REQ] Evolutive openapi to protobuf conversion

### ISSUE THREAD

**Issue by dobl1** [OpenAPITools/openapi-generator#6756]
Hello,

### Is your feature request related to a problem? Please describe.

The converter from OAS to PB works great but only once !
Indeed if I update the original OAS file, let's say adding an attribute, then the .proto generated will have all the index shifted (and so not backward compatible).

## Describe the solution you'd like

One solution, certainly the simplest is to have attribute key hash as index, with some mechanics (increment ?) in case of conflict.
Also would be great to have the generated file named with the major version (ex : contact.v1.proto).

Regards.

**Comment by dobl1** [comment]
Anyone ⁉️

**Comment by wing328** [comment]
done by #7002.

@dobl1 let us know if that won't meet your requirement.
