### ISSUE TITLE
[BUG][JAVA] ApiException error code is private without getter

### ISSUE THREAD

**Issue by Xendar** [OpenAPITools/openapi-generator#6830]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The [ApiException.mustache template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy/ApiException.mustache) provides a useful exception with code and name, but unfortunately the code is private (well, that's good actually) but there is no getter to access it, so we cannot really use it...

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml

##### Command line used for generation

java -jar openapi-generator-cli-4.3.1.jar generate -i https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml -g jaxrs-resteasy -o gen

##### Steps to reproduce

Run the generator and open gen/java/org/openapitools/api/ApiException.java

##### Related issues/PRs

None found

##### Suggest a fix

Adding a basic getter should be enough

**Comment by wing328** [comment]
> Adding a basic getter should be enough

Your suggestion sounds good. I wonder if you can submit a PR with the proposed fix so that we can review it more easily.

**Comment by Xendar** [comment]
> 
> 
> > Adding a basic getter should be enough
> 
> Your suggestion sounds good. I wonder if you can submit a PR with the proposed fix so that we can review it more easily.

I'll try :)

**Comment by Xendar** [comment]
Pull Request #7150 created
