### ISSUE TITLE
No @JsonProperty on setters of generated java model

### ISSUE THREAD

**Issue by Metalmix** [OpenAPITools/openapi-generator#6856]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

JsonProperty annotations can be found in generated model classes only on "getters" but not on setter methods. This has the consequence that e.g. resteasy cannot transfer a json response into the model if a property in the json does not follow the camel case notation. Example:

Json: 
```json
{ "ObjId": "1", "ObjName": "test" }
```

Generated client code:
```java
  public static final string JSON_PROPERTY_OBJ_I_D = "ObjID";
  private integer objID;

  public static final string JSON_PROPERTY_OBJ_NAME = "ObjName
  private string objName;

  @javax.annotation.Nullable
  @ApiModelProperty(value = "The id")
  @JsonProperty(JSON_PROPERTY_OBJ_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public integer getObjID() {
    return objID;
  }

  public void setObjID(Integer objID) {
    this.objID = objID;
  }
```

In this case "ObjId" cannot be mapped to the property "objId", because the corresponding "setter" is not annotated with ```java
@JsonProperty(JSON_PROPERTY_OBJ_I_D)```

##### openapi-generator version

tried with
- 4.3.1
- 5.0.0-beta

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.2'
info:
  title: Test API
  version: '1.0'
servers:
  - url: https://xxx
paths:
  /someget/{testobj}:
    get:
      parameters:
        - in: path
          name: testobj
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyTestObj'
components:
  schemas:
    MyTestObj:
      type: object
      properties:
        ObjID:
          type: integer
          readOnly: false
          description: The id
        ObjName:
          type: string
          readOnly: false
          description: The name
```

##### Command line used for generation

docker run --rm  -v ${PWD}:/local openapitools/openapi-generator-cli generate -i /local/test.yaml -g java --library native -o /local/out

##### Steps to reproduce

Take a look at the generated source and find the class out/src/main/java/org/openapitools/client/model/MyTestObj.java will not have @JsonProperty annotations on any setter.

##### Related issues/PRs

none

##### Suggest a fix

Generate @JsonProperty on setter too or move annotation from getter to field level.

**Comment by SoMuchForSubtlety** [comment]
This issues still persists with jersey2 in v5.1.0  and makes the generated classes unusable.

I believe the jersey2 template is simply missing `{{#jackson}}{{> jackson_annotations}}{{/jackson}}` before this segment.  https://github.com/OpenAPITools/openapi-generator/blob/39f0177ede6ade8a7511d77bf97384294cbe32f2/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/pojo.mustache#L236-L249
