### ISSUE TITLE
[REQ] Android client - response headers

### ISSUE THREAD

**Issue by davidfrancisandroidemul** [OpenAPITools/openapi-generator#6862]
Hi,

Can the Android client generated code access response headers?
I am calling a simple POST endpoint which returns a CREATED response with a Location header
This is a very basic use-case so I'm concerned that it's not been seen before.

PS What generator is recommended for use with Android?
I am using Android with Volley at the moment

TIA

**Comment by davidfrancisandroidemul** [comment]
Note: Similar issue: https://github.com/swagger-api/swagger-codegen/issues/3654

Maybe the answer is in there - someone has recommended a different client be used on Android

**Comment by davidfrancisandroidemul** [comment]
closed by accident - sorry

**Comment by wing328** [comment]
Not at the moment. We welcome PRs for the enhancement.

As a workaround, you can use the java (okhttp-gson) client generator instead.

**Comment by connorsadler** [comment]
Yep I just used a different generator

**Comment by wing328** [comment]
FYI. I've filed https://github.com/OpenAPITools/openapi-generator/pull/8968 with various enhancements to the android (volley) generator. It does not yet cover the enhancement you're looking but appreciate if you can give it a try later after we merge the PR into master and let us know if you've any feedback.
