### ISSUE TITLE
Cannot import api class from a generated openapi dependency (kotlin-spring)

### ISSUE THREAD

**Issue by sassit** [OpenAPITools/openapi-generator#6870]
##### Description

I've generated an artifact that I declare as a dependency, a kotlin-spring generated artifact, the dependency is resolved but I cannot import the api interface of it so I can implement it. 

The dependency is for example /home/sassit/.gradle/caches/modules-2/files-2.1/com.acme/rest-api-acme-server/0.2-SNAPSHOT/3c0a10ce0a6e9510107f5c28dc4ca11e14bdc828/rest-api-acme-server-0.2-SNAPSHOT.jar!/BOOT-INF/classes/com/acme/rest/acme/server/api/DevicesApi.class

In Intellij it does not get resolved and I cannot implement the interface.

I assume it's something trivial that I am missing.

##### openapi-generator version

gradle plugin 5.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

The OpenAPI yaml file is valid

##### Command line used for generation

task generateServerApi(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask){
    generatorName = "kotlin-spring"
    inputSpec = "$rootDir/rest-acme.yaml".toString()
    outputDir = "$buildDir/kotlin".toString()
    invokerPackage = "com.acme.rest.server"
    apiPackage = "com.acme.rest.server.api"
    modelPackage = "com.acme.rest.server.model"
    configOptions = [
            dateLibrary: "java8",
            interfaceOnly: "true",
            exceptionHandler: "true",
            swaggerAnnotations: "true",
            useBeanValidation: "true",
    ]
    skipValidateSpec = false
    logToStderr = true
    generateAliasAsModel = false
    groupId = "com.acme.rest.corda"
    id = "rest-api-acme-server"
    version = "0.2-SNAPSHOT"
    // set to true and set environment variable {LANG}_POST_PROCESS_FILE
    // (e.g. SCALA_POST_PROCESS_FILE) to the linter/formatter to be processed.
    // This command will be passed one file at a time for most supported post processors.
    enablePostProcessFile = false
    templateDir = "$rootDir/templates/kotlin-spring"
}

**Comment by sassit** [comment]
The issue is with the default packaging of Spring boot or rather the build.gradle.kts template, in case you run into the same issue you can package the dependency like this: https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable-and-normal

**Comment by stefan-niedermann** [comment]
@sassit i have the same issue, but unfortunately I couldn't get the point of the spring documentation you linked above. Would you mind pointing me out to the section that explains what actually goes wrong and prohibits the generated files from being imported?

Or share the actual step you performed to solve the issue on your side? :innocent:

**Comment by sassit** [comment]
@stefan-niedermann the anchor has changed, the new anchor would be:

[4.3. Packaging Executable and Plain Archives](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#packaging-executable.and-plain-archives)

it has been a while back but I think I had to change the way it was packaging like in the link described, the original link is archived there:

[4.3. Packaging Executable and Normal Archives](https://web.archive.org/web/20200529080929/https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/html/#packaging-executable)  

Specifically, I can see in the old source that I have enabled this, this way it would be a plain jar instead of a boot jar if I remember correctly:

```
jar {
	enabled = true
}
```

Hope it helps.

**Comment by stefan-niedermann** [comment]
Thank you for your response. Just for documentation in case someone else stumbles upon this issue: I also had to mark the generated folder explicitly as sources by adding the following snippet to the `build.gradle` file:

```kotlin
sourceSets {
    main {
        java {
            srcDir("$buildDir/gen/src/main/java")
        }
    }
}
```
