### ISSUE TITLE
[BUG] scala-play-server apiTrait.scala.mustache does not contain json import

### ISSUE THREAD

**Issue by Alex-e** [OpenAPITools/openapi-generator#6889]
#### Bug Report Checklist

- [+] Have you provided a full/minimal spec to reproduce the issue?
- [+] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [+] What's the version of OpenAPI Generator used?
- [+] Have you search for related issues/PRs?
- [+] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

project generation fails with error
`...UserApi.scala:22:25:  not found: type JsObject
[error]   def searchUsers(body: JsObject): Future[Seq[User]]`

##### openapi-generator version

4.3.1

##### Command line used for generation

sbt plugin used. No special options needed.

##### Steps to reproduce

generate scala-play-server project with at least one api endpoint

##### Suggest a fix
add to apiTrait.scala.mustache following import:
`import play.api.libs.json._`

**Comment by wing328** [comment]
@Alex-e thanks for reporting the issue. Can you please file a PR with the suggested fix so that we can review more easily?

**Comment by jimschubert** [comment]
Thanks for the report. #6891 has been merged to master.
