### ISSUE TITLE
[REQ] Add mock payload support for python

### ISSUE THREAD

**Issue by mdavis-xyz** [OpenAPITools/openapi-generator#6897]
### Is your feature request related to a problem? Please describe.

I would like to test the code I wrote which invokes the python client code generated by this tool.

## Describe the solution you'd like

I would like for the ability to invoke my code (that decides which API call to make, what the argument values are etc),
then have that invoke the client code to check the arguments are valid,
then have the client code *not* send a packet over the network, but instead respond with some fake payload (e.g. hard coded, or calling some other function), which then is validated by the client and passed back to my hand-written code.

I'm not sure what it should do with authentication.
It should at least check that any provided authentication (e.g. client certificate) is in the right format (e.g. is it a string of the content, a file-like object, a string file path?)

## Additional context

@wing328

**Comment by spacether** [comment]
Auto written model testing in python and python-legacy produces payloads for some models. Those payloads can be used in the way that you describe.
