### ISSUE TITLE
[BUG] [JAVA] okhttp-gson generates broken method in ApiClient.java

### ISSUE THREAD

**Issue by bseiller** [OpenAPITools/openapi-generator#6934]
##### Description

The current Okhttp3 - ApiClient [Mustache](https://github.com/OpenAPITools/openapi-generator/blob/1a2097e81d17da9c74bc8c93facbb4f768f455bd/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache#L533) generates a broken method.
The method setDebugging(boolean debugging) tries to remove the logging interceptor from an immutable list.
This results in a java.lang.UnsupportedOperationException

Okhttp made the HttpClient immutable and provided a builder-pattern which already captures the current state.

##### openapi-generator version

4.3.1

##### Steps to reproduce
- Configure Generator to use okhttp-gson
- Generate some API
- Prepare ApiClient
- Call setDebugging(true) on ApiClient instance
- Call setDebugging(false) on ApiClient instance

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/3054

##### Suggest a fix
```
final OkHttpClient.Builder builder = httpClient.newBuilder();
builder.interceptors().remove(loggingInterceptor);
httpClient = builder.build();
```
or add new method removeInterceptor to OkHttpClient.Builder and 
`httpClient = httpClient.newBuilder().removeInterceptor.(loggingInterceptor).build();`

**Comment by wing328** [comment]
@bseiller thanks for reporting the issue. I wonder if you can file a PR so that we can review the fix more easily.

**Comment by bseiller** [comment]
@wing328 Thanks for the fast reply. 
It might take me a while. If that's fine then sure I'll file a PR.

**Comment by bseiller** [comment]
Ok, one question: Should I base the PR on master or on the tag of 4.3.1?

**Comment by wing328** [comment]
Latest master please
