### ISSUE TITLE
[BUG] C# GetHashCode is using not read only properties to calculate hash

### ISSUE THREAD

**Issue by dziedrius** [OpenAPITools/openapi-generator#6935]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I've tried to use 5.0 beta version of generator, but I think issue exists in previous versions too.
When models are generated, GetHashCode method is overriden and it uses non read only properties to genereate hash:

```
/// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    
                    hashCode = hashCode * 59 + Right.GetHashCode();
                return hashCode;
            }
        }
```
Jetbrains Resharper marks such places with a warning and [documentation](https://www.jetbrains.com/help/resharper/NonReadonlyMemberInGetHashCode.html) states:

> You can override GetHashCode for immutable reference types. In general, for mutable reference types, you should override GetHashCode only if:

> You can compute the hash code from fields that are not mutable; or
> You can ensure that the hash code of a mutable object does not change while the object is contained in a collection that relies on its hash code.

Those rules exists because breaking it this might lead to very nasty bugs because of broken for example HashSet state, here is article that goes into details:

https://vkontech.com/gethashcode-pitfalls/

##### openapi-generator version

5.0 beta, I'm sure it is like that in older versions too.

##### Command line used for generation

openapi-generator generate -g aspnetcore -i api.yaml -o . -c openapi-generator-config.json --global-property apis --global-property models

##### Code to reproduce

```
    var distinctPeople = new HashSet<Person>();
    var person = new Person{FirstName = "John"};
    distinctPeople.Add(person);
    person.FirstName = "Peter";
    var lookFor = new Person {FirstName = "Peter"};
    Console.WriteLine(distinctPeople.Contains(lookFor)); // False
```

##### Suggest a fix

I would say if generated models calculate hash from properties, at least I should be able to disable this override.

**Comment by wing328** [comment]
@dziedrius thanks for reporting the issue. As a workaround for the time being, please use customized templates (`-t` option in the CLI) with the `GetHashCode` code removed.

**Comment by devhl-labs** [comment]
If yml has a way to specify which property of the mutable type is the key, that could help decide what should be in GetHashCode.  I just tried setting my id property isId: true and that produced no change in the GetHashCode.

**Comment by wing328** [comment]
@devhl-labs what about using vendor extensions (e.g. x-csharp-mutable-type) to annotate the property?

**Comment by devhl-labs** [comment]
I don't know what that is and I don't see it online anywhere.  However, I tried adding this to 

`{{^vendorExtensions.x-is-id}}
// this is an id {{name}}
{{/vendorExtensions.x-is-id}}`

It puts the text for all properties, so I'm not sure how to check if it has the x-is-id property.
