### ISSUE TITLE
[BUG][typescript-angular] Unable to use multiple access tokens

### ISSUE THREAD

**Issue by djnalluri** [OpenAPITools/openapi-generator#6944]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

All security schemes that use the HTTP Bearer and OAuth2 schemes rely on the single `accessToken` field of the configuration object. Using API's that use multiple of this scheme become tricky to use as you must swap out the access token to the correct one prior to each request.

##### openapi-generator version

<= 5.0.0-beta

##### OpenAPI declaration file content or url

https://gist.github.com/djnalluri/1a6ae2ad99f8f198620cb262432d4615

##### Command line used for generation

openapi-generator generate -g typescript-angular -i openapi.yml

##### Steps to reproduce

Use the spec file and command provided above to generate a client.

##### Related issues/PRs

None for typescript-angular

##### Suggest a fix

I suggest unifying the configuration for API Key, Basic, Bearer, and OAuth2 schemes into a single map for lookup just like the `apiKeys` property currently in the configuration object. The type of the map can be adjusted to also accept functions returning strings like `accessToken` currently does; OAuth2 scheme behaviour can be kept mostly the same in this way. Basic authentication can be adjusted to first check for an already prepared base64 string in the map and fall back to existing behaviour.

**Comment by djnalluri** [comment]
I can work on a PR if the suggested changes are suitable.

**Comment by macjohnny** [comment]
sounds good. keep in mind that this should be backwards compatible

**Comment by djnalluri** [comment]
Does this mean version 5.0 is no longer accepting new breaking changes?

**Comment by macjohnny** [comment]
@wing328 hoe about breaking changes for version 5, are they still allowed?
