### ISSUE TITLE
[BUG] Generated R client code does not allow multiple Query Params with the same argument name

### ISSUE THREAD

**Issue by jsilverpa** [OpenAPITools/openapi-generator#6990]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I have an API that allows requests like the following:
`http://localhost:5004/hello/?names=val1&names=val2`

I'm expecting that I can pass a list to the R client function like below:
`tester$Hello(names=c('val1', 'val2'))`

but the R client code throws the following error:
`Warning message:
In queryParams["names"] <- names :
  number of items to replace is not a multiple of replacement length
`
It then sends the request:
`"GET /hello/?names=val1 HTTP/1.1"`
##### openapi-generator version

4.2.3

I don't think it's a regression

##### OpenAPI declaration file content or url

[https://gist.github.com/jsilverpa/59bd21295a2818c3d3a60aa2650a8292](https://gist.github.com/jsilverpa/59bd21295a2818c3d3a60aa2650a8292)

##### Steps to reproduce

`curl 'localhost:5004/openapi.json'> main.openapi.json
openapi-generator generate -i main.openapi.json -g r --package-name mytest -o r-client`

**Comment by wing328** [comment]
I think you will need the following to describe your query parameter(s):

```
"style": "form",
"explode": true
```

Ref: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#style-examples

(but I don't think that's currently supported by the R client)

**Comment by jsilverpa** [comment]
Thanks for the comment.   Can you clarify what you mean by "I think you will need"?  According to https://swagger.io/docs/specification/serialization/ 
`
"style": "form",
"explode": true
`

is the default value so it does not need to be included.   You are saying even the default is not supported by the R client?

**Comment by wing328** [comment]
This should be fixed by https://github.com/OpenAPITools/openapi-generator/pull/13348. Please pull the latest master to give it another try.
