### ISSUE TITLE
[BUG] [nodejs-express-server] Generated output does not include api-docs path

### ISSUE THREAD

**Issue by littlespex** [OpenAPITools/openapi-generator#7004]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description
When generating server code using `nodejs-express-server` as the generator, the README file states that API documentation can be viewed at `http://localhost:3000/api-docs/`. Loading that url in a browser produces the following result:

`{"message":"not found","errors":[{"path":"/api-docs/","message":"not found"}]}`

Looking at the code generated in `expressServer.js`, it looks like the path is registered as `api-doc`, without the trailing `"s"`.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

[service-copy.yaml.zip](https://github.com/OpenAPITools/openapi-generator/files/4950640/service-copy.yaml.zip)

##### Command line used for generation

`openapi-generator generate -g nodejs-express-server -i service-copy.yaml -o ./service-copy`

##### Steps to reproduce

1. Generate the node server with the command provided
1. Run `npm start`
1. Browse to `http://localhost:3000/api-docs/`

##### Suggest a fix

Update the README to reflect the path that does not contain the trailing `"s"`, or update the route's path to include the trailing `"s"`.

**Comment by wing328** [comment]
We've merged https://github.com/OpenAPITools/openapi-generator/pull/6977 to fix it. Please pull the latest master or use the snapshot to give it a try.

Happy to reopen the issue if it still exists.
