### ISSUE TITLE
[BUG] Revert update to Feign 11

### ISSUE THREAD

**Issue by ChristianCiach** [OpenAPITools/openapi-generator#7007]
https://github.com/OpenAPITools/openapi-generator/pull/6068 updated the Feign library to 11, but this artifact has been pushed to Maven Central by accident. See here: https://github.com/OpenFeign/feign/issues/1218#issuecomment-621766031

There is still no official release of Feign 11 on their Github page. Feign 11 is extremely buggy for us, so we had to downgrade our generated api clients.

Please rollback to Feign 10 as soon as possible.

**Comment by ChristianCiach** [comment]
@wing328

**Comment by wing328** [comment]
@ChristianCiach thanks for pointing it out. I'll update it tomorrow.

**Comment by wing328** [comment]
@ChristianCiach I've filed https://github.com/OpenAPITools/openapi-generator/pull/7012 to rollback Feign version.
