### ISSUE TITLE
[BUG] [Java]: Wrapper class with generic type can't be compiled successfully because of a special character "«»" present in the equals method

### ISSUE THREAD

**Issue by thepipeman** [OpenAPITools/openapi-generator#7016]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used? 
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I have a class that wraps a generic type which I use as a response object. 

Now when I generate using the CLI, the class that gets created is `OutputWrapperOperationOutput`  but it contains the special characters in equals method

```java
OutputWrapperOperationOuput outputWrapper«OperationPut» = (OutputWrapperOperationOutput) o;
```

Note: I tried this with swagger-codegen, the characters are removed when I execute the generation. But I want to use openapi-generator so if someone has a workaround or if I have some missing param in my generation, please let me know.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

The problematic class looks like this in the spec
spec is swagger 2.0 (springfox)

```json
"OutputWrapper«OperationOutput»": {
   "type": "object",
   "properties": {
      "output": {
         "description": "Execution output value",
         "$ref": "#/definitions/OperationOutput"
       }
    },
  "title": "OutputWrapper«OperationOutput»"
```

##### Command line used for generation
java -jar openapi-generator-cli.jar 
 -g java -i http://localhost:8000/documentation/swagger-v2
 -DdateLibrary=java8-localdatetime 
 -Dlibrary=resttemplate 
 -DhideGenerationTimestamp=true 
 -DserializableModel=true 

##### Actual ouput vs expected
Expected: class should not contain the special characters «»
Actual: class contains «», it's used in equals method

##### Related issues/PRs

[issue#3808](https://github.com/OpenAPITools/openapi-generator/issues/3808)
[issue#1157](https://github.com/OpenAPITools/openapi-generator/pull/1157)

**Comment by helt** [comment]
Just in case that the openapi spec has been generated by springfox, you can change the generation docket like this:

```diff
diff --git a/be/data-processing-pipeline/src/main/java/de/fraunhofer/igdr/config/SwaggerConfig.java b/be/data-processing-pipeline/src/main/java/de/fraunhofer/igdr/config/SwaggerConfig.java
index b3cfafe7f..78b0620b0 100755
--- a/src/main/java/config/SwaggerConfig.java
+++ b/src/main/java/config/SwaggerConfig.java
    return new Docket(DocumentationType.OAS_30)
       .apiInfo(apiInfo())
       .securityContexts(securityContexts())
       .securitySchemes(securitySchemas())
+      .forCodeGeneration(true)
       .select()
       .apis(RequestHandlerSelectors.basePackage(Application.class.getPackageName() + ".controllers"))
       .paths(regex("/.*"))
```

See http://springfox.github.io/springfox/docs/current/#changing-how-generic-types-are-named

**Comment by thepipeman** [comment]
The root cause of this is the `equals` method generation.

To fix the issue, as mentioned in other bug reports, springfox should be set with `forCodeGeneration(true)`.

Another option is to modify the `equals` method generation, in my case I was using Lombok, so I modified the templates:

1. [Model](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/model.mustache) - I added lombok annotation `@EqualsAndHashCode` 
2. [POJO](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/pojo.mustache) - I removed `equals` and `hashCode` methods.

See code sample at https://gist.github.com/thepipeman/b7e4b9d5103d1c2ecaed4b4d38d349ee
