### ISSUE TITLE
[BUG][Java][jersey2] Incorrect import mapping for arrays

### ISSUE THREAD

**Issue by ioannisioannou16** [OpenAPITools/openapi-generator#7018]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Hello,

I am trying to use importMappings with arrays but it doesn't work properly.  I have the following example:

```
openapi: 3.0.0
info:
  title: Sample API
  description: API description
  version: 1.0.0
paths:
  /test:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyType1'
components:
  schemas:
    MyType1:
      type: object
      properties:
        arrayProperty:
          $ref: '#/components/schemas/MyType2'
        otherProperty:
          $ref: '#/components/schemas/MyType4'
    MyType2:
      type: array
      items:
        $ref: '#/components/schemas/MyType3'
    MyType3:
      type: string
    MyType4:
      type: string
```

and I defined the following importMappings:

```
<importMappings>
    <importMapping>MyType3=com.example.MyType3</importMapping>
    <importMapping>MyType4=com.example.MyType4</importMapping>
</importMappings>
```

It replaces successfully the MyType4 but for the MyType3 it generates a String as the type of the array.  

Generated response types:

```
private List<String> arrayProperty = null;
private com.example.MyType4 otherProperty;
``` 

I was expecting the response to be `List<com.example.MyType3>` for the `arrayProperty`.

##### openapi-generator version
openapi-generator-maven-plugin
5.0.0-beta
jaxrs-jersey

##### Related issues/PRs
I think this issue https://github.com/OpenAPITools/openapi-generator/issues/3589 is related. It was for simple types though. Here is for arrays.

##### Suggest a fix/enhancement

I think the following changes fix the issue.

```
diff --git a/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java b/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
index bbf9a3004a..ae27927211 100644
--- a/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
+++ b/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java
@@ -759,7 +759,7 @@ public abstract class AbstractJavaCodegen extends DefaultCodegen implements Code
     public String getTypeDeclaration(Schema p) {
         if (ModelUtils.isArraySchema(p)) {
             Schema<?> items = getSchemaItems((ArraySchema) p);
-            return getSchemaType(p) + "<" + getTypeDeclaration(ModelUtils.unaliasSchema(this.openAPI, items)) + ">";
+            return getSchemaType(p) + "<" + getTypeDeclaration(ModelUtils.unaliasSchema(this.openAPI, items, importMapping)) + ">";
         } else if (ModelUtils.isMapSchema(p) && !ModelUtils.isComposedSchema(p)) {
             // Note: ModelUtils.isMapSchema(p) returns true when p is a composed schema that also defines
             // additionalproperties: true
diff --git a/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java b/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
index 0a694cffd6..b4e6fbfa53 100644
--- a/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
+++ b/modules/openapi-generator/src/test/java/org/openapitools/codegen/java/AbstractJavaCodegenTest.java
@@ -423,6 +423,16 @@ public class AbstractJavaCodegenTest {
         Assert.assertEquals(defaultLocalDate, LocalDate.parse(defaultValue));
     }
 
+    @Test
+    public void getTypeDeclarationGivenStringImportMappingTest() {
+        final P_AbstractJavaCodegen codegen = new P_AbstractJavaCodegen();
+        codegen.importMapping().put("MyStringType", "com.example.foo");
+        codegen.setOpenAPI(new OpenAPI().components(new Components().addSchemas("MyStringType", new StringSchema())));
+        Schema<?> schema = new ArraySchema().items(new Schema().$ref("#/components/schemas/MyStringType"));
+        String defaultValue = codegen.getTypeDeclaration(schema);
+        Assert.assertEquals(defaultValue, "List<com.example.foo>");
+    }
+
     @Test
     public void getTypeDeclarationTest() {
         final P_AbstractJavaCodegen codegen = new P_AbstractJavaCodegen();

```

**Comment by magnuskvalheim** [comment]
👍  We are seeing exact same issue for v4.3.0 & 4.3.1. 
Have made a workaround, but interested to follow progress of this

**Comment by ioannisioannou16** [comment]
Updated post to suggest a fix

**Comment by ioannisioannou16** [comment]
@magnuskvalheim What is your workaround?

My workaround to this is to change MyType3 in the above example to type object (from string) and add a single property. By doing that, it replaces correctly MyType3 to com.example.MyType3

**Comment by magnuskvalheim** [comment]
After upgrading from 3.3.4 to 4.3.1 the importmappings for Lists generated List<Object> types and we got a few compiler errors.
We have temporarily made workaround by simply upcasting objects in the request payload to List<Object> as well. 
Jackson, of course, serializes the payload just fine through reflection - but I'll revisit in order to remove the duct tape when we have a bit of time ;)

Thumbs up, and kudos for the pull request!
