### ISSUE TITLE
[REQ][php-ze-ph] Add Mock Server optional feature

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#7023]
### Is your feature request related to a problem? Please describe.

I've successfully integrated Mock Server in `php-slim4` and I'm going to add this feature to rest PHP server generators. If there are users or contributors who against it, please leave a comment.

## Describe the solution you'd like

Add Mock Server feature(optional, disabled by default) to `php-ze-ph` server generator.

## Additional context

Related issues #3545 and #6718

**Comment by ybelenko** [comment]
@Articus can you shed some light on how we can create `before` middleware with your `articus/path-handler`?

Does this generator support PSR-15 `Psr\Http\Server\MiddlewareInterface`?

Basically I need to execute my data mocker before each request and return fake response or pass response without any modification(when feature is disabled).

**Comment by Articus** [comment]
Yep, you can pipe additional PSR-15 middleware inside App\Factory class - template is [here](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-ze-ph/Factory.php.mustache#L51) and generated sample [here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/server/petstore/php-ze-ph/src/App/Factory.php#L51). 

But personally I am not sure that adding mocking inside server stub is really convenient and useful - it seems easier to use separate standalone mocking solution like https://github.com/stoplightio/prism instead.

**Comment by ybelenko** [comment]
> But personally I am not sure that adding mocking inside server stub is really convenient and useful - it seems easier to use separate standalone mocking solution like https://github.com/stoplightio/prism instead.

First of all, you didn't try my library :smile:

Disadvantages of `prism`:
1. It's written with TypeScript so I have to setup Node.js on server.
2. It requires shell access to web hosting and requires addition domain/subdomain for Mocking Server.
3. Additional configuration.

My package(`OpenapiDataMocker`) is pure PHP and has been developed not for mock server, but for automatic testing. I cannot create fake request with `prism` to send it to my dev API server.

**Comment by ybelenko** [comment]
@Articus Just noticed another php library to generate fake data from OAS specs - [canvural/php-openapi-faker](https://github.com/canvural/php-openapi-faker). I can't even say how it gained 44(❗) stars already(first release at June 15th, 2020). I think it means that there are people who need PHP based mockers.

**Comment by Articus** [comment]
> My package(OpenapiDataMocker) is pure PHP and has been developed not for mock server, but for automatic testing. I cannot create fake request with prism to send it to my dev API server.

Guess we have slightly different workflows then :)

I use full HTTP-mocking only during development when you need to develop web service consumer before web service is created and there is only its OAS specification. So Prism works pretty well in this case - just one more container in docker-compose.yml for your development environment that has access to local copy of specification (to manage "examples" for static responses during development).

For automatic tests I find easier to use pure mocking libraries like `phpspec/prophecy` or ` mockery/mockery`. It is usually more convenient to use web service client mocks in web service consumer tests and server request mocks in web service tests than to perform real HTTP requests. 

> I think it means that there are people who need PHP based mockers.

I mentioned Prism only as example and I am not speaking against PHP based mockers :) My point is that server stub created with OpenAPIGenerator is a basis for your production application that should handle requests, not mock responses. So 

> it seems easier to use separate standalone mocking solution

that can be written in any language you like :)

**Comment by ybelenko** [comment]
@Articus since you showed no interest in my mocker implementation I'm closing this issue. No hard feelings 😄 
Maybe someone from actual users will vote for the built-in mock feature in current topic to reopen this.
