### ISSUE TITLE
[REQ][csharp-netcore] Cancellation Tokens

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#7048]
Please consider adding an optional CancellationToken to async calls similar to https://github.com/OpenAPITools/openapi-generator/pull/6243.

**Comment by wing328** [comment]
@devhl-labs thanks for the suggestion. May I know if you've time to contribute a PR with the enhancement?

**Comment by devhl-labs** [comment]
I can give it a go.  Do I do a pr for master or 5.0?  In the issue I referenced there is a pr checklist, I don't understand the last bullet.  Copy the technical committee.  Sorry, copy what?

**Comment by wing328** [comment]
Please target the current master (5.0.0-snapshot)

Please copy (cc or tag) the C# technical committee stated in https://github.com/OpenAPITools/openapi-generator#62---openapi-generator-technical-committee to review the PR.

**Comment by devhl-labs** [comment]
I'm running `mvn clean install` which appears to succeed, then from .\bin\windows `& ".\typescript.bat` to update the samples, but that gives me an error of `The goal you specified requires a project to execute but there is no POM in this directory (E:\repos\openapi-generator\bin\windows). Please verify you invoked Maven from the correct directory.`  I'm not sure how to update the samples.
