### ISSUE TITLE
[python-experimental] models + endpoints, replace allowed_values with enums

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#7058]
Include python Enums when the schema defines an enum

This applies to:
- endpoints
    - inline enum
    - $ref enum
- enums in object type models
    - inline enum
    - $ref enum
- models of type enum (ModelSimple models)

**Comment by cgfarmer4** [comment]
@spacether Any movement here? Accessing enums should be as simple as Type.VALUE but I can't seem to get this to work.

**Comment by spacether** [comment]
No progress here yet in the python-generator or the python-legacy generator.

This is difficult to implement because:
- Enums can be combined in composed schemas
- Composed schemas can contain any type (oneOf: - null, -int -StrEnum
I am slowly making progress on this at https://github.com/OpenAPITools/openapi-generator/pull/8325
If you look in that branch at [StrEnum](https://github.com/spacether/openapi-generator/blob/adds_python_experimental_dynamic_base_classes/samples/openapi3/client/petstore/python-experimental/petstore_api/model/string_enum.py#L58) my code there allows
Type.OPTION
In that branch I am working to get that working on the java classes CodegenModel, CodegenProperty and probably CodegenResponse and CodegenParameter.

**Comment by cgfarmer4** [comment]
Thanks for the quick reply @spacether. So what is the proper way to access them currently?

The model serialization fails if they aren't passed as `Type('stringvalue')` however this emits incorrect values in the JSON.

I get `{value: 'stringvalue'}` when I would expect it to be `'stringvalue'`

**Comment by spacether** [comment]
The way to access them now is through allowed_values.

**Comment by spacether** [comment]
If there is a bug can you open up a separate issue with a reproducible example?

**Comment by cgfarmer4** [comment]
Thanks @spacether. Filed https://github.com/OpenAPITools/openapi-generator/issues/8377

**Comment by spacether** [comment]
Closing this because python-experimental implements a singleton class which stores enum options and it will be merged soon.
