### ISSUE TITLE
[REQ][PHP] Patch "null" values

### ISSUE THREAD

**Issue by ro0NL** [OpenAPITools/openapi-generator#7065]
We are unable to perform an API patch request, to change a field value to "NULL" (as supported in JSON and openapi schema).

This is caused by https://github.com/OpenAPITools/openapi-generator/blob/fa75469828fdfe6b43487b7826655e1d15432d7a/samples/client/petstore/php/OpenAPIClient-php/lib/ObjectSerializer.php#L91-L93

and im generally curious why those fields are ignored.

**Comment by jorissteyn** [comment]
The client currently does not distinguish between "field not set in request" and "nullable field explicitly set to null". This is a problem for PATCH but also for "partial PUT" operations. A solution is proposed in #2199 but no real work has been put in it yet, so it seems.
