### ISSUE TITLE
[BUG] PlantUML generation produces a lot of warnings

### ISSUE THREAD

**Issue by typhoon2k** [OpenAPITools/openapi-generator#7070]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

When running plantuml generation we are getting a lot of these 2 warnings:

`[main] WARN  o.o.codegen.DefaultCodegen - escapeQuotationMark should be overridden in the code generator with proper logic to escape single/double quote`
`[main] WARN  o.o.codegen.DefaultCodegen - escapeUnsafeCharacters should be overridden in the code generator with proper logic to escape unsafe characters`

##### openapi-generator version

5.0.0-beta

##### OpenAPI declaration file content or url

[petstore.yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml) can be used to repeat this problem.

##### Command line used for generation

```bash
    java \
        -jar openapi-generator-cli-5.0.0-beta.jar \
            generate \
            --input-spec $input_file \
            --generator-name plantuml \
            --output $output_folder
```

##### Steps to reproduce

1. run generator
2. check logs

##### Related issues/PRs

N/A

##### Suggest a fix

Provide overrides for **escapeQuotationMark** and **escapeUnsafeCharacters**.

**Comment by wing328** [comment]
@typhoon2k thanks for reporting the issue. I've filed #7071 to fix it.

**Comment by wing328** [comment]
@typhoon2k fixed. Please pull the latest master to give it another try.

**Comment by typhoon2k** [comment]
Looks good now, there are no warnings anymore. Thanks!
