### ISSUE TITLE
[REQ] Support for rate limiting

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#7082]
I don't see a way to implement rate limits.  I have the following changes to my templates to support this in my csharp-netcore template that uses bearer tokens.

## Configuration.cs
```
public Func<System.Threading.Tasks.Task<string>> GetTokenAsync { get; set; } = DefaultTokenProvider;

private static System.Threading.Tasks.Task<string> DefaultTokenProvider()
{
	return System.Threading.Tasks.Task.FromResult("my-token");
}
```

## ModelApi.cs
```
// authentication (JWT) required
localVarRequestOptions.HeaderParameters.Add("authorization", "Bearer " + await this.Configuration.GetTokenAsync());
```

This allows the consumer to set the GetTokenAsync function to one of their own that handles rate limits.  It also has the benefit that it allows the consumer to use multiple bearer tokens where applicable.  I'm not sure if this approach is the best or if it works for other security configurations, but it does work for me, but I did hard code the Bearer text in the given example.

**Comment by devhl-labs** [comment]
Supported in new httpclient library.

**Comment by nickhammond** [comment]
@devhl-labs Can you link to that change or version?

**Comment by devhl-labs** [comment]
It's the generichost library. 
[templates](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/csharp-netcore/libraries/generichost)
[readme](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/client/petstore/csharp-netcore/OpenAPIClient-generichost-net6.0-nrt/src/Org.OpenAPITools)

**Comment by nickhammond** [comment]
@devhl-labs Great, thank you!
