### ISSUE TITLE
[dart-dio]need sample of how to set model's property

### ISSUE THREAD

**Issue by a22349** [OpenAPITools/openapi-generator#7109]
need sample to know how to use api to create model and set property
there is only empty object in readme, which is "Pet pet   =new Pet()" . i can't find other sample in repo . 

how to set the "name" property of it ? 
the code only has "get" of it :
        @nullable
    @BuiltValueField(wireName: r'name')
    String get name;
to set it i     tried 
pet()..name = "testname"
but 
"There isn’t a setter named name . "

and the builder of the pet is private , import the .g file not work also . 

how to new one pet with contents ?

**Comment by kuhnroyal** [comment]
The dart-dio generator uses https://pub.dev/packages/built_value

You need to do something like this:
```dart
final pet = (PetBuilder()..name = 'testname').build();
```

**Comment by kuhnroyal** [comment]
@wing328 I think this can be closed.

**Comment by a22349** [comment]
can't even find the clas of "Petbuilder"

**Comment by kuhnroyal** [comment]
You need to run `pub run build_runner build` in the generated project.
