### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by GregTheGreek** [OpenAPITools/openapi-generator#7138]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used? Latest npm
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

Installing the latest version with node 12 results in the package being unusable with the error:
```bash
$ openapi-generator
/bin/sh: 1: java: not found
```

**Comment by ybelenko** [comment]
Seems like you didn't install Java Runtime Environment. You need Java 8 or higher to run generator.
