### ISSUE TITLE
[BUG] [Python] arrays validation problems for maxItems/minItems

### ISSUE THREAD

**Issue by SapMaria** [OpenAPITools/openapi-generator#7142]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Validation rules are not added for lists (maxItems/minItems values) to the generated Python SDK (I tested  only for Python). 

I also tried to add validation rules for string, number and integer. It's ok.

##### openapi-generator version

4.3.1 (additionaly checked on latest 5.0.0-beta)

##### OpenAPI declaration file content or url

```yaml
requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                os:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                packages:
                  type: array
                  minItems: 1
                  maxItems: 5
                  items:
                    type: string
```

##### Generation Details

```
java -jar openapi-generator-cli-4.3.1.jar generate  -i v1.yaml -g python -o ~/projects/sdk-openapi
```

##### Steps to reproduce

Just use generator script with default options for python.

##### Related issues/PRs

Not found.

**Comment by spacether** [comment]
This ticket is stale and should be fixed in master.
maxItems and minItems validations are checked here:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model_utils.py#L777-L797
