### ISSUE TITLE
[BUG] Incorrect Request Mapping for Kotlin-Spring generated API

### ISSUE THREAD

**Issue by SarangKanabargi** [OpenAPITools/openapi-generator#7155]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I encountered this issue many times when I generate the API using Gradle openApiGenerate tasks on intellij when the generation language was kotlin-spring. when I use the generation language as spring the API controller class comes out fine.

output with generation language as kotlin-spring
@RequestMapping("\${api.base-path:/api}")
interface NewsApi {

output with generation language as spring (there is no requestmapping at interface)
@Api(value = "News", description = "the News API")
public interface NewsApi {

##### openapi-generator version
4.3.1

##### OpenAPI declaration file content or url
openapi: '3.0.0'
servers:
  - url: http://localhost:8080/api
    description:  Prod Server
  - url: http://dev.localhost:8080/api
    description: Dev Server
info:
  version: 1.0.0
  title: Gaming News API
paths:
  /news:
    summary: Get list of latest gaming news
    get:
      tags:
        - News
      summary: Get list of latest gaming news
      operationId: getNews
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArticleList'

components:
  schemas:
    ArticleList:
      type: array
      items:
        $ref: '#/components/schema/Article'
    Article:
      required:
        - id
        - title
        - date
        - description
        - imageUrl
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        date:
          type: string
          format: date
        description:
          type: string
        imageUrl:
          type: string

```
(for YAML code) or
##### Generation Details

<!-- 
    Prefer CLI steps, including the language, libraries and various options. 
    Providing config-based settings allows for simpler testing across CLI and plugins. 
    For examples, see https://github.com/OpenAPITools/openapi-generator/tree/master/bin/configs
-->

##### Steps to reproduce

gradle openApiGenerate 

##### Related issues/PRs

<!-- has a similar issue/PR been reported/opened before? Please do a search in https://github.com/openapitools/openapi-generator/issues?utf8=%E2%9C%93&q=is%3Aissue%20 -->

##### Suggest a fix

There should be no request mapping annotation generated at the interface/class level; at this level swagger annotation for Api should be generate like what's coming out when the generation language of spring is selected

**Comment by brnhrdt** [comment]
Did you managed to fix this?
