### ISSUE TITLE
openapi-generator-cli generating requests with empty body data for Jmeter

### ISSUE THREAD

**Issue by ankugarg** [OpenAPITools/openapi-generator#7158]
#### Bug Report Checklist

- Description - openapi-generator-cli.jar is generating jmeter tests with requests which have empty body data. 
Used API `java -jar openapi-generator-cli.jar generate -i petstore.json -g jmeter` to generate tests.

- Used https://petstore.swagger.io/v2/swagger.json to generate jmeter tests.

- Screenshot of request from Swagger:
![SwaggerRequest](https://user-images.githubusercontent.com/13931015/89609571-e9a73e80-d895-11ea-83dd-a5e79ecad6c0.png)

- Generated Jmeter request with empty body:
![JmeterTest](https://user-images.githubusercontent.com/13931015/89609579-eca22f00-d895-11ea-915e-ca69b9465056.png)

- Actual Result - Body data is empty in generated Jmeter's requests.

- Expected Result - Body data should not be empty in generated Jmeter's requests.

**Comment by kannkyo** [comment]
I guess that mustache file is mistaken.

JMeter mustache file (1) use queryParams tag, but python-flask mustache file (2) use bodyParam tag.

1. [resources/jmeter-client/api.mustache#L94](https://github.com/OpenAPITools/openapi-generator/blob/0eb385c0d6497c38c09b42158b2d66109b78b15b/modules/openapi-generator/src/main/resources/jmeter-client/api.mustache#L94)
2. [resources/python-flask/controller_test.mustache#L26](https://github.com/OpenAPITools/openapi-generator/blob/08fb59009a8565295b1e091eb0c514b7439245e8/modules/openapi-generator/src/main/resources/python-flask/controller_test.mustache#L26)

**Comment by wing328** [comment]
@kannkyo thanks for the findings. Do you mind filing a PR with the suggested fix?

**Comment by kannkyo** [comment]
> @kannkyo thanks for the findings. Do you mind filing a PR with the suggested fix?

I send PR.

**Comment by burgcons** [comment]
Hi @kannkyo 
Please share the latest openapi executable jar link with above fix, which supports petstore v3
