### ISSUE TITLE
[BUG][Kotlin] Generated Serializer for ApiClient does not support BigDecimal

### ISSUE THREAD

**Issue by nilskuhn** [OpenAPITools/openapi-generator#7196]
#### Description
Generating a Kotlin client for an API that uses BigDecimal in the model, the generated ApiClient doesn't work because the generated Moshi serializer does not have a type adapter for BigDecimal. Unfortunately, there is no way to inject the type adapter yourself.

#### openapi-generator version
4.3.1

#### Steps to reproduce
Any API with BigDecimal should demonstrate the problem. Generate Kotlin API and try to send message. I get exception:

```
java.lang.IllegalArgumentException: Platform class java.math.BigDecimal (with no annotations) requires explicit JsonAdapter to be registered
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:60) ~[moshi-1.8.0.jar:na]
	at com.squareup.moshi.Moshi.adapter(Moshi.java:137) ~[moshi-1.8.0.jar:na]
```
#### Suggest a fix
Add BigDecimal adapter here: com.kn.containerDashboard.backend.client.rgs.infrastructure.Serializer

**Comment by wing328** [comment]
@nilskuhn thanks for reporting the issue. Do you mind filing a PR with the suggested fix?

**Comment by nilskuhn** [comment]
Yes, I will try to find the time.

**Comment by zarr** [comment]
#### Possible workaround

Set the `serializationLibrary` to `jackson` in the generator configuration as described in https://openapi-generator.tech/docs/generators/kotlin

**Comment by kuFEAR** [comment]
Hi, I added BigDecimal/BigInteger in my fork https://github.com/kuFEAR/openapi-generator/commit/05bd4e17600f45a3dffaff364db03f5b4c6975f2, I'll send it later to parent repo after merge another one pr

**Comment by codymikol** [comment]
@kuFEAR did you ever send in a PR for this?
