### ISSUE TITLE
[BUG] angular: incompatible with v10

### ISSUE THREAD

**Issue by davidkarlsen** [OpenAPITools/openapi-generator#7201]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] What's the version of OpenAPI Generator used?
- [X] Have you search for related issues/PRs?
- [X] What's the actual output vs expected output?
- [] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

The generated code is not compatible with angular 10.
Typing was added in v9, and required in v10.

##### openapi-generator version

1.0.15-4.3.1

##### OpenAPI declaration file content or url

N/A

##### Generation Details

```
ERROR in target/generated-sources/openapi/api.module.ts:19:71 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

19     public static forRoot(configurationFactory: () => Configuration): ModuleWithProviders {
                                                                         ~~~~~~~~~~~~~~~~~~~
```

##### Steps to reproduce

Generate code in a ng10 project and see it fail.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator-cli/issues/37

##### Suggest a fix

Add the required typing to the provider.

**Comment by juristr** [comment]
@wing328 from a quick check it looks like this change is not included in the latest beta 2. Would it be possible to have another release to include the Angular 10 compatibility?
