### ISSUE TITLE
Resource files are not referenced correctly

### ISSUE THREAD

**Issue by jmaister** [OpenAPITools/openapi-generator#7216]
https://github.com/OpenAPITools/openapi-generator/blob/55f928a82ef619e607b4377f262b820944f3a305/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/SpringCodegen.java#L357

The reference to the .mustache files do not reference an unique file in the JAR file.

i.e.

    new SupportingFile("pom.mustache", ...)

In the JAR file for the templates, there are several pom.mustache files. How the right one is decided between them?

    JavaSpring\libraries\spring-boot\pom.mustache
    JavaSpring\libraries\spring-cloud\pom.mustache
    JavaSpring\libraries\spring-mvc\pom.mustache

**Comment by borsch** [comment]
based on "active" library: spring-boot, spring-cloud etc.

**Comment by jmaister** [comment]
https://github.com/OpenAPITools/openapi-generator/blob/3199ddc6152effe92aa8fa5ba4918d9054337bcb/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L665

However, I can't see how the active library is used when the the supporting files are generated.

**Comment by borsch** [comment]
@jmaister 

https://github.com/OpenAPITools/openapi-generator/blob/58ed6afc0dc51a341cad01420274752b6ec31bff/modules/openapi-generator/src/main/java/org/openapitools/codegen/templating/GeneratorTemplateContentLocator.java#L44

**Comment by jmaister** [comment]
Great. It's more clear now.

Thank you @borsch
