### ISSUE TITLE
Custom classes generation using openapi-generator-cli.jar

### ISSUE THREAD

**Issue by harshad5498** [OpenAPITools/openapi-generator#7227]
Hello all, 
We need to add some additional Java classes(for ex. our own custom HTTPInterceptor) in our project, which we generate using openapi-generator-cli.jar.
Can anyone help us how this can be done ?

**Comment by jimschubert** [comment]
@harshad5498 you'd need to create a custom generator which extends the existing generator to add new file outputs. You'll need to provide a new name in `getName`, register the new class in the META-INF location in your project, and finally add all templates plus your new templates. The key part would be to add your new files to the `supportingFiles` list.

The process is fairly simple. You can check out my sample project here: https://github.com/jimschubert/custom-generator-example. My project doesn't add to supporting files, but is small enough to digest easily.

For a full walkthrough, check out our docs at https://openapi-generator.tech/docs/customization

**Comment by harshad5498** [comment]
Thanks Jim will go through your project , and let you know .

**Comment by harshad5498** [comment]
@jimschubert  That worked for me , have another question . Can you tell me how i can create docs created by open api generator or should i write new mustache files and add then in supporting files as i did previously  to create and modify java files .

**Comment by jimschubert** [comment]
> @jimschubert That worked for me , have another question . Can you tell me how i can create new docs and modify docs which are generated by open api generator...

I don't understand the question. Could you provide an example?

In general, if you'd like to modify the documentation then you'd do so after generation and add all docs to the `.openapi-generator-ignore` file in the output directory. This allows regeneration without overwriting your work.

**Comment by jimschubert** [comment]
@harshad5498 haven't heard back on this in a bit. I'm assuming you figured things out.

Since you've responded that my initial response solved the question asked in the issue, I'll go ahead and close. If you have any other questions, please open another issue or ping us in slack.
