### ISSUE TITLE
[Bug][typescript-axios] When Multiple File Uploaded, it does not work as isCollectionFormatMulti

### ISSUE THREAD

**Issue by shrkw** [OpenAPITools/openapi-generator#7247]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

I want to define api for 'Multiple File Upload' which refer the part in swagger document [File Upload](https://swagger.io/docs/specification/describing-request-body/file-upload/).
But the generated script deals with binaries as simple string.

`localVarFormParams.append('files', files.join(COLLECTION_FORMATS.csv));`

##### openapi-generator version

v4.3.1

##### OpenAPI declaration file content or url

I added encoding parameter to force form style but not works well.

```yaml
openapi: 3.0.3
info:
  title: test
  version: '0.1'
tags:
  - name: test
    description: test
servers:
  - url: 'http://localhost:3000'
paths:
  /api/upload:
    post:
      tags: []
      operationId: upload files
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                message:
                  type: string
                files:
                  type: array
                  items:
                    type: string
                    format: binary
              required:
                - message
            encoding:
              files:
                style: form
                explode: true
      responses:
        '200':
          description: ok
```

##### Generation Details

use this command.

```
docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli:v4.3.1 generate \
    -p supportsES6=true \
    -p modelPropertyNaming=camelCase \
    -i /local/doc/test.yaml \
    -g typescript-axios \
    -o /local/app/javascript --verbose
```

##### Steps to reproduce

just run by above command, then it generate following script.

```typescript
                if (files) {
                       localVarFormParams.append('files', files.join(COLLECTION_FORMATS.csv));
            }
```

here is verbose output https://gist.github.com/shrkw/5002c71e33177b99c0529f1506d6ff22

and api.ts https://gist.github.com/shrkw/5002c71e33177b99c0529f1506d6ff22#file-api-ts-L77

##### Related issues/PRs

Not sure but may be same issue.

[BUG multi file upload not implemented fully · Issue #6752 · OpenAPITools/openapi-generator · GitHub](https://github.com/OpenAPITools/openapi-generator/issues/6752)

Same issue is facing to this guy.
[BUGJavaSpring multiple files upload · Issue #4803 · OpenAPITools/openapi-generator · GitHub](https://github.com/OpenAPITools/openapi-generator/issues/4803#issuecomment-654077304)

##### Suggest a fix

I want to set isCollectionFormatMulti attribute, but not sure how to do it.

[openapi-generator/apiInner.mustache at f752f29af202885e6b817e5ec002facee1ef0c33 · OpenAPITools/openapi-generator · GitHub](https://github.com/OpenAPITools/openapi-generator/blob/f752f29af202885e6b817e5ec002facee1ef0c33/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L161)

```mustache
            {{#isCollectionFormatMulti}}
                {{paramName}}.forEach((element) => {
                    localVarFormParams.append('{{baseName}}', element as any);
                })
            {{/isCollectionFormatMulti}}
```

**Comment by imcloudf** [comment]
having the same issue with version 5.0.0-beta

**Comment by imcloudf** [comment]
`//TODO collectionFormat for form parameter not yet supported`
[at DefaultCodegen](https://github.com/OpenAPITools/openapi-generator/blob/681e821b719065099470fe4df69f4d3df95ba75c/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5824) 
and 
and 
`                // default to csv:
                collectionFormat = StringUtils.isEmpty(collectionFormat) ? "csv" : collectionFormat;`

**Comment by imcloudf** [comment]
I read some code and found that `isCollectionFormatMulti` currently is not support for form params. 

`//TODO collectionFormat for form parameter not yet supported`
[at DefaultCodegen.java Line 5832](https://github.com/OpenAPITools/openapi-generator/blob/681e821b719065099470fe4df69f4d3df95ba75c/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5823) 
and 
```java
String collectionFormat = null;
// ... some lines do not assign other value to collectionFormat
//TODO fix collectformat for form parameters
//collectionFormat = getCollectionFormat(s);
// default to csv:
codegenParameter.collectionFormat = StringUtils.isEmpty(collectionFormat) ? "csv" : collectionFormat;
``` 
[at DefaultCodegen.java Line 5712](https://github.com/OpenAPITools/openapi-generator/blob/681e821b719065099470fe4df69f4d3df95ba75c/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L5713)

But, how do we specify a collectionFormat for Request Body Object ? I can only see collectionFormat for Parameter Object in OpenApi Specification  (using `style` property) and [this merge](https://github.com/OpenAPITools/openapi-generator/commit/068ad02bc8c8b4e5def11f46db0fcd93e9c74e9f) did not check collectionFormat.

Should we just remove the `isCollectionFormatMulti` check and some other lines?
