### ISSUE TITLE
[jaxrs-spec*] samples/server/petstore/jaxrs-spec* are not compilable

### ISSUE THREAD

**Issue by fujigon** [OpenAPITools/openapi-generator#726]
##### Description
Sample maven projects of `jaxrs-spec`, `jaxrs-spec-interface`, `jaxrs-spec-interface-response` are not compilable.

- https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/jaxrs-spec
- https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/jaxrs-spec-interface
- https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/jaxrs-spec-interface-response

##### openapi-generator version

master branch (a258cf3fc6e8a04280fd89ad07a7223048d53fca)

##### OpenAPI declaration file content or url

master branch (a258cf3fc6e8a04280fd89ad07a7223048d53fca)

##### Command line used for generation

I used the example on the master branch.

##### Steps to reproduce

*environment*
- Windows 10
- git bash
- Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T03:33:14+09:00)
- Java(TM) SE Runtime Environment (build 1.8.0_161-b12)

*patch*
Changed `samples/server/petstore/jaxrs-spec/jaxrs-spec/pom.xml` to add the generated sources into its compilation. (https://github.com/fujigon/openapi-generator/commit/69d51fd5870296b6d88eeda2e6f2751fe43c3bbd#diff-4b89ff23dee396d29fbaa7412736b5bf)

And I kick

```bash
cd samples/server/petstore/jaxrs-spec
mvn test
```

then, I get compile error https://gist.github.com/fujigon/f5c8e591548e0e8ec30bc019be73ad9d.

##### Related issues/PRs
N/A

##### Suggest a fix/enhancement
Currently, the whole project is buildable because it doesn't add sub-projects `jaxrs-spec`, `jaxrs-spec-interface`, and `jaxrs-spec-interface-response` into the root project.

I think these sub-projects should be integrated to the root project with profile as the other sample projects are, so that CI confirms that the sub-projects are buildable. (like https://github.com/fujigon/openapi-generator/commit/69d51fd5870296b6d88eeda2e6f2751fe43c3bbd#diff-600376dffeb79835ede4a0b285078036)
And then, we need to modify the `jaxrs-spec` language mustache template so that the generated code is compilable.

**Comment by wing328** [comment]
@fujigon thanks for reporting the issue. You're right and please file a PR with the patch to fix the pom.xml to start with. We'll then work together to fix the remaining issues.
