### ISSUE TITLE
[BUG] Rust generator does not do the local variable protection

### ISSUE THREAD

**Issue by UkonnRa** [OpenAPITools/openapi-generator#7269]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] What's the version of OpenAPI Generator used?
- [x] Have you search for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Bounty to sponsor the fix ([example](https://www.bountysource.com/issues/66123212-javascript-client-produces-a-wrong-object-for-a-string-enum-type-that-is-used-with-ref))

##### Description

Rust generator does not protect the local variables, so something like the followings will be generated:

```rust
    // Here, both input and local var have the param `client`, so the second one will shadow the first one
    fn revoke_consent_sessions(&self, subject: &str, client: Option<&str>, all: Option<bool>) -> Result<(), Error> {
        let configuration: &configuration::Configuration = self.configuration.borrow();
        // Maybe something like `localVarClient` is better
        // It would be better if conflict detection can be provided by the generator?
        let client = &configuration.client;

        let uri_str = format!("{}/oauth2/auth/sessions/consent", configuration.base_path);
        let mut req_builder = client.delete(uri_str.as_str());

        req_builder = req_builder.query(&[("subject", &subject.to_string())]);

        // Wrong `client`
        if let Some(ref s) = client {
            req_builder = req_builder.query(&[("client", &s.to_string())]);
        }
        if let Some(ref s) = all {
            req_builder = req_builder.query(&[("all", &s.to_string())]);
        }
        if let Some(ref user_agent) = configuration.user_agent {
            req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
        }

        // send request
        let req = req_builder.build()?;

        client.execute(req)?.error_for_status()?;
        Ok(())
    }

```

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

https://raw.githubusercontent.com/ory/hydra/master/.schema/api.swagger.json

##### Generation Details

**config.yaml**

```yaml
library: reqwest
```

**command**

```
  openapi-generator generate -i https://raw.githubusercontent.com/ory/hydra/master/.schema/api.swagger.json -g rust -o output -c config.yaml
```

##### Steps to reproduce

* Run the command before
* You will see the error part in `output/src/apis/admin_api.rs`, function `revoke_consent_sessions`

##### Suggest a fix

* Maybe something like `localVarClient` is better
* It would be better if conflict detection can be provided by the generator?

**Comment by wing328** [comment]
> Maybe something like localVarClient is better

Right, other clients are already using similar prefix. For Rust, what bout using `local_var_` prefix instead?

Would you have time to contribute the enhancement?

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/7299
