### ISSUE TITLE
[PYTHON] migration problems from swagger-codegen with PATCH call parameters

### ISSUE THREAD

**Issue by Amoki** [OpenAPITools/openapi-generator#729]
##### Description
I migrated from swagger-codegen (too many critical fix in merge pending) but now I face a big change in generated code.
PATCH requests now require to have an instance of the object in parameters or an exception is raised 

```python
TypeError: update_user() missing 1 required positional argument: 'user'
```

In many case, I don't care about the previous values so I never retrieve the object before the PATCH call.

I can't find when this change append. Is there a parameter during generation to keep the old behavior ?

##### openapi-generator version

3.1.2

##### Command line used for generation

java -jar openapi-generator.jar generate -i swagger.json -l python -o ~/libs/python-lib

##### Steps to reproduce

java -jar swagger-codegen-2.3.1.jar generate -i swagger.json -l python -o ~/libs/python-lib
`update_user(id=1, name='new name')` -> works
java -jar openapi-generator.jar generate -i swagger.json -l python -o ~/libs/python-lib
`update_user(id=1, name='new name')` -> TypeError: update_user() missing 1 required positional argument: 'user'

##### Related issues/PRs

Not able to find one :(

##### Suggest a fix/enhancement

Parameter to chose behavior ?

Thanks !

**Comment by wing328** [comment]
@Amoki Do you mind sharing the spec to reproduce the issue?

**Comment by Amoki** [comment]
Sure !
You can found it here: https://api-staging.bimdata.io/doc?format=openapi

**Comment by wing328** [comment]
I tried with the spec you provided but in the auto-generated Python client (using OpenAPI Generator), I couldn't find `update_user`. In the spec, I did a search for update_user or updateUser (case insensitive) but no luck.

**Comment by Amoki** [comment]
Oops, sorry. It was an example with common names instead of my work related names. 
If found the bug with the operation `updateIfc` but it applies with with other calls

**Comment by wing328** [comment]
```
update_user(id=1, name='new name') -> TypeError: update_user() missing 1 required positional argument: 'user'
```
From the error message, looks like the function/operation has a required parameter "user" to start with.

Does the spec of that operation include a required parameter?

By reviewing the change in https://github.com/OpenAPITools/openapi-generator/pulls?q=is%3Apr+is%3Aclosed+label%3A%22Client%3A+Python%22, I don't see any PRs that impact required/optional parameters in the Python client.

You may also want to try OpenAPI Generator 3.0.0 version to see if the first stable release has similar issue.

**Comment by Amoki** [comment]
I dug a little deeper, and I was wrong.

![screenshot from 2018-08-06 11-54-39](https://user-images.githubusercontent.com/1349751/43710293-8ab04eba-996f-11e8-8252-e82417854d4f.png)
The parameter name is "data" in the swagger.

![screenshot from 2018-08-06 13-35-44](https://user-images.githubusercontent.com/1349751/43714565-abe3b2bc-997d-11e8-88b3-70084b4f88c1.png)
And it is named "ifc" in the generated code (it was "data" with swagger-codegen).

It seems to use the snake cased definition's name.

I will update my code base to use these new functions signatures (Yay!) but I don't know where this comes from !

**Comment by wing328** [comment]
> And it is named "ifc" in the generated code (it was "data" with swagger-codegen).

There's no "body" parameter in OAS3. To retain the old body parameter name, please refer to https://github.com/OpenAPITools/openapi-generator/blob/master/docs/migration-from-swagger-codegen.md#body-parameter-name

**Comment by Amoki** [comment]
Oops, I missed that part.

Thank you very much :)

**Comment by wing328** [comment]
@Amoki no problem. Let us know if you need any help with the migration.
