### ISSUE TITLE
[REQ] Update the Vert.x Web codegen to Vert.x 4

### ISSUE THREAD

**Issue by slinkydeveloper** [OpenAPITools/openapi-generator#7352]
### Is your feature request related to a problem? Please describe.

Vert.x 4 includes a brand new support for OpenAPI, while this project supports only Vert.x 3

## Describe the solution you'd like

Migrate the existing vertx web codegen to vert.x 4

## Additional context

Should this live under a new codegen copy pasted from the previous one and migrated? Or should I just migrate the existing one?

**Comment by wing328** [comment]
> Or should I just migrate the existing one?

Please migrate/update the existing one instead of creating a new generator.

If you need help, please let us know. Thanks for your help on this.
