### ISSUE TITLE
[BUG][javascript-flowtyped] Flow check error (node.js)

### ISSUE THREAD

**Issue by zole40** [OpenAPITools/openapi-generator#7382]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
I found the following problem in the generated code when tried to  run the `flow check`:

```
Cannot delete localVarUrlObj.search because undefined [1] is incompatible with null [2]. [incompatible-type]

     openapi/src/api.js
   
              localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
                 // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
 [1]              delete localVarUrlObj.search;
           localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
      
                 return {

     /private/tmp/flow/flowlib_34e1ce2/node.js
 [2] 2191│     search: string | null,

```

##### OpenAPI declaration file content or url
```yaml
openapi: '3.0.3'
info:
  version: 0.1.0
  title: Test
servers:
  - url: /api
tags:
  - name: test
    description: |
paths:
  /dummy:
    get:
      summary:  Dummy endpoint.
      operationId: dummy
      tags:
        - simulation
      description: |
        Dummy endpoint.
      responses:
        '200':
          description: Success call
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummySuccess'
        default:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyError'

components:
  schemas:
    DummySuccess:
      type: string
      example: ok
    DummyError:
      properties:
        errorMassage:
          type: string
          example: error
```

##### Generation Details
* generatorName = "javascript-flowtyped"

##### Steps to reproduce
* run generator javascript-flowtyped
* run flow check
##### Suggest a fix
Change this line `delete localVarUrlObj.search;` to this `localVarUrlObj.search = null;` It could solve the flow issue. It is seen to be ok, but I did not test it all possibilities yet.

**Comment by wing328** [comment]
@zole40 thanks for reporting the issue. I wonder if you can file a PR with the suggested fix so that we can review it more easily.
