### ISSUE TITLE
[BUG][ruby-client] Body variable not properly serialized when named `body`

### ISSUE THREAD

**Issue by zippolyte** [OpenAPITools/openapi-generator#7412]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When the body variable is named `body`, this [line of code](https://github.com/ota42y/openapi-generator/blob/ddf3e503f5fe86de5b0c929ef85a8acacaf00ce2/modules/openapi-generator/src/main/resources/ruby-client/api.mustache#L176) makes it bypass the call to `@api_client.object_to_http_body`, which prevents the transformation of the object into a hash, thus making `to_json` return invalid JSON.

At Datadog, we make extensive use of the `x-codegen-request-body-name` extension and set it to `body` for consistency and ease of use across our different endpoints, which causes this issue.

##### openapi-generator version

5.0.0-beta

##### OpenAPI declaration file content or url

The following example will generate

```yaml
paths:
  /send_body:
    post:
      x-codegen-request-body-name: body
      requestBody:
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/BodyParam"
      responses:
        "200":
          description: OK
components:
  schemas:
    BodyParam:
      type: object
      properties:
        prop:
          type: string 
```

##### Steps to reproduce

Generating the ruby client for the above endpoint will create this code:

```ruby
      # http body (model)
      post_body = opts[:body] || @api_client.object_to_http_body(opts[:'body']) 
```

Now when using the endpoint, you would do something like the following

```ruby
body_param = BodyParam.new
body_param.prop = "foo"
api.send_body({body: body_param})
```

Because of the generated line of code above, the object will be passed as is to the `call_api` method, and the JSON serialization will produce invalid JSON, as the object did not go through the `object_to_http_body` method:

```
"{:prop=>\"foo\"}"
```

##### Suggest a fix

Looking for suggestions on how to fix this. I'd be happy to implement it.

**Comment by wing328** [comment]
@zippolyte thanks for reporting the issue. I've filed a quick fix (https://github.com/OpenAPITools/openapi-generator/pull/7413)

I wonder if you can pull the fix locally and see if it addresses the issue in your use case:
```
git checkout -b ruby-fix-body master
git pull https://github.com/OpenAPITools/openapi-generator.git ruby-fix-body
```

**Comment by zippolyte** [comment]
Yeah that fixes the issue for my use case, but I'm afraid this will break the use case introduced specifically in this PR https://github.com/OpenAPITools/openapi-generator/pull/2754

**Comment by wing328** [comment]
I'll talk to that PR author about the additional logic to pass various options (parameter values) to the method.

(other clients do not have similar logic as the method should work according to the contract/spec)

**Comment by wing328** [comment]
@zippolyte I've filed another PR (https://github.com/OpenAPITools/openapi-generator/pull/7422) to avoid naming conflicts for the time being as I've not heard from the author of the PR #2754. Please have a look to see if the fix looks good to you.

**Comment by zippolyte** [comment]
Thanks, this solves my use case as well, so I'd be okay to merge. I just hope no one has a body variable named `debug_body` 😅.
For the time being though I'm 👍
