### ISSUE TITLE
[ASPNETCORE] Multiple files

### ISSUE THREAD

**Issue by johnfg10** [OpenAPITools/openapi-generator#742]
##### Description
I am trying to split my project up and in doing so I'm using $ref quite extensively but when I run the generator it does seem to build it, I suspect I'm doing something incorrect as this is the first time I've created a project with openapi 3. it generates no controllers or models.

##### openapi-generator version
3.1.2

##### OpenAPI declaration file content or url
```yaml
paths: 
  /seller/{sellerId}:
    $ref: 'seller.yml#/paths/get'
```
which links to another file in the same directory: https://gist.github.com/johnfg10/53f1ccc88fc57d91474c93fad965639c

##### Command line used for generation
generate -i schemas.yml -i store.yml -i seller.yml -i jshop.yml -g aspnetcore -o ./out

**Comment by wing328** [comment]
@johnfg10 can you try adding "./" to the path instead: `$ref: './seller.yml#/paths/get'`?

**Comment by johnfg10** [comment]
ahh that appears to have got it but rather than `$ref: './seller.yml#/paths/get'` i used `$ref: './seller.yml#/paths'`, thanks a lot for your help

**Comment by wing328** [comment]
@johnfg10 no problem. Let us know if you need further assistance.
