### ISSUE TITLE
[TYPO] [Java] Comment in webclient ApiClient.mustache refers to RestTemplate

### ISSUE THREAD

**Issue by dtiller** [OpenAPITools/openapi-generator#7425]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

A comment in webclient ApiClient.mustache refers to RestTemplate. 

##### openapi-generator version

5.0.0-beta2

##### Steps to reproduce

See lines 146-149 in the [webclient ApiClient.mustache template](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache)

```java
 /**
    * Build the RestTemplate used to make HTTP requests.
    * @return RestTemplate
    */
public static WebClient buildWebClient(ObjectMapper mapper) {
...
}
```

##### Related issues/PRs

None that I found.

##### Suggest a fix

```java
 /**
    * Build the WebClient used to make HTTP requests.
    * @return WebClient
    */
public static WebClient buildWebClient(ObjectMapper mapper) {
...
}
```

**Comment by wing328** [comment]
@dtiller thanks for catching the typo. May I know if you've time to file a PR to fix the typo?

**Comment by dtiller** [comment]
Hello William. I’ll be glad to create a PR for that.
