### ISSUE TITLE
[BUG] [Kotlin] useRxJava options not applied

### ISSUE THREAD

**Issue by remvst** [OpenAPITools/openapi-generator#7428]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Am currently trying to generate a Kotlin client using retrofit2 and RxJava2. Retrofit works, however the output does not seem to use RxJava at all.

My config:
```json
{
  "library": "jvm-retrofit2",
  "useRxJava2": true
}
```

API definition:

```yaml
openapi: 3.0.0
info:
  title: Test API
  description: A cool API to test with
  version: 0.0.1
paths:
  /my-api:
    get:
      tags:
        - test-service
      operationId: getSomething
      summary: Get something
      responses:
        '200':
          description: A JSON array of exercise requests
          content:
            application/json:
              schema:
                type: string
```

I use this command to generate the code:

```sh
npx @openapitools/openapi-generator-cli generate -i exercise-requests.yaml -g kotlin -c kotlin-config.json -o code
```

The output I'm getting:

```kotlin
interface TestServiceRemoteService {
    @GET("/my-api")
    fun getSomething(): Call<kotlin.String>

}
```

Notice how the return type is `Call<kotlin.String>`, however I would expect it to be `Single<kotlin.String>` or `Observable<kotlin.String>`

##### openapi-generator version

```sh
$ npx @openapitools/openapi-generator-cli version
npx: installed 1 in 1.566s
4.3.1
```

**Comment by wing328** [comment]
Can you please try the latest master or 5.0.0-beta2 version instead?

**Comment by remvst** [comment]
@wing328 that seems to fix it indeed. If I may, the KDoc is however slightly inaccurate:

```kotlin
interface TestServiceRemoteService {
    /**
     * Get something
     * 
     * Responses:
     *  - 200: A JSON array of exercise requests
     * 
    * @return [Call]<[kotlin.String]>
     */
    @GET("my-api")
    fun getSomething(): Single<kotlin.String>

}
```

The @return line is referring to the non-Rx version, but that's not an issue for us. 

Closing this ticket.
