### ISSUE TITLE
cwiki isn't an option

### ISSUE THREAD

**Issue by pkkr** [OpenAPITools/openapi-generator#7436]
Hey coudn't find any comment on that in the documentation but it seems like the -l cwiki flag is currently not working. is that as expected or an issue ?

Thanks

**Comment by wing328** [comment]
Use `-g` instead, e.g.:
```
openapi-generator generate -g cwiki -i https://raw.githubusercontent.com/OpenAPITools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml -o /tmp/cwiki
```

Migration guide: https://github.com/OpenAPITools/openapi-generator/blob/master/docs/migration-from-swagger-codegen.md
