### ISSUE TITLE
[REQ] Java - Spring JPA support

### ISSUE THREAD

**Issue by kydreth** [OpenAPITools/openapi-generator#7486]
### Is your feature request related to a problem? Please describe.

The Spring solution doesn't quickly connect to a variety of databases

## Describe the solution you'd like

The Spring implementation doesn't directly tie into a database driver or solution. Using Java based Spring Data JPA would support many SQL database drivers. https://spring.io/projects/spring-data-jpa

## Describe alternatives you've considered

manually typing the JPA with spring/bean annotations and getters/setters with lombok

## Additional context

https://www.callicoder.com/spring-boot-jpa-hibernate-postgresql-restful-crud-api-example/

**Comment by codymikol** [comment]
This project is for automatically generating clients that can make requests to applications based on their openapi spec. Spring data would be an implementation detail for your application rather than the generated client.

**Comment by macjohnny** [comment]
see also https://github.com/OpenAPITools/openapi-generator/issues/2972
