### ISSUE TITLE
[BUG][Python] Stackoverflow error when using required recursive properties

### ISSUE THREAD

**Issue by vincent-raman** [OpenAPITools/openapi-generator#7532]
##### Description

If we want to define a recursive type (like a tree), the client generation for python crashes with a StackOverflowError in the `PythonClientCodegen.toExampleValueRecursive` method.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```json
{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "Test swagger file"
  },
  "paths": {
    "/tree": {
      "post": {
        "description": "Create",
        "operationId": "createTree",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Tree"
              }
            }
          },
          "description": "The tree to create",
          "required": true
        },
        "tags": [
          "Test"
        ],
        "responses": {
          "200": {
            "description": "Successfully created the tree",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/Tree"
                }
              }
            }
          },
          "400": {
            "description": "Bad request"
          }
        }
      },
    }
  },
  "components": {
    "schemas": {
      "Tree": {
        "type": "object",
        "required": [
          "id",
          "name",
          "children"
        ],
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "children": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tree"
            }
          }
        }
      }
    }
  }
}
```
##### Generation Details

Generation of a client with language "python" and this schema definition

##### Steps to reproduce

Try to generate a python client

##### Suggest a fix

In the method `PythonClientCodegen.toExampleValueRecursive`, when treating an object (`if (ModelUtils.isObjectSchema(schema))`, the already treated properties are removed.

```java
for (String toRemove : included_schemas) {
    if (reqs.contains(toRemove)) {
        reqs.remove(toRemove);
    }
}
```

But, just after, the "required" properties are added back, making this safeguard useless

```java
if (null != schema.getRequired()) for (Object toAdd : schema.getRequired()) {
    reqs.add((String) toAdd);
}
```

**Comment by delenius** [comment]
I was just about to file a report for the same issue. It is still there in the latest master as of writing this (now at 5.1.0-SNAPSHOT).

[Here is a repo](https://github.com/delenius/openapi-issues/tree/main/python-example-rec) to easily reproduce, in case it helps.

Note: The [suggested validator](https://apidevtools.org/swagger-parser/online/) in the issue filing system complains about the recursive type, but e.g. the [Swagger online editor](https://editor.swagger.io/) does not. In any case, clearly one has to be allowed to have recursive types for trees etc.

@vincent-raman, could you file a PR, since you found a fix? Otherwise, I might take a crack at it

**Comment by ethan92429** [comment]
Also fails in `python-experimental`

**Comment by spacether** [comment]
The above PR fixes the java layer of python clients
Similar PRs may be needed to prevent infinite recursion in python clientsy

**Comment by RichiCoder1** [comment]
I still appear to be getting this error (or at least one very similiar to it) when using `python-experimental` and https://instana.github.io/openapi/openapi.yaml

**Comment by vincent-raman** [comment]
It seems fixed in python-previous (renamed from python) in v6.2.0
