### ISSUE TITLE
[BUG] [Python] it handles servers urls trailing slash incorrectly

### ISSUE THREAD

**Issue by ksvirkou-hubspot** [OpenAPITools/openapi-generator#7533]
##### Description
Sample spec(swagger):
```json
"servers": [
{
"url": "https://api.*.com/"
}
],
```
Generated code sends requests to urls with double slashes and It returns 404
Example endpoint url: “https://api.*.com//crm/v3/objects/contacts” 

#### openapi-generator version
5.0.0-SNAPSHOT

**Comment by ksvirkou-hubspot** [comment]
@spacether
I am not sure but I can't find a similar issue 
what do you think about it ?

**Comment by atanasiuk-hubspot** [comment]
Any updates on this?

**Comment by spacether** [comment]
Per the spec here:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#serverObject
It looks like full paths are:
servers + path
And the examples that they give lack a trailing slash in servers and include a leading slash in paths

**Comment by atanasiuk-hubspot** [comment]
Hi, @spacether, thank you for the response!

The [OpenAPI Specification](https://swagger.io/specification/) indicates no limitations on the form of the servers URLs, but does indicate that just a slash "/" is a valid URL.
![image](https://user-images.githubusercontent.com/57258334/95307640-93547d00-0891-11eb-8040-1aa3c9c0fcd0.png)

The Specification also notes that paths MUST start with a /.

Therefore, a server of "/" and path of /example is a valid OpenAPI spec, which means OpenAPI Generator should be able to handle this multiple / case.

**Comment by atanasiuk-hubspot** [comment]
The [latest](https://github.com/OpenAPITools/openapi-generator/tree/v4.3.1) stable build handles trailing slash correctly. The issue appears in 5.0.0.

**Comment by spacether** [comment]
Thanks for sharing that. I stand corrected. We welcome any PRs fixing this issue.

**Comment by ksvirkou-hubspot** [comment]
**PR**
https://github.com/OpenAPITools/openapi-generator/pull/7940
