### ISSUE TITLE
[BUG][typescript-axios] attempts to serialize Node `Buffer` using `JSON.stringify` and corrupts the file upload

### ISSUE THREAD

**Issue by therockstorm** [OpenAPITools/openapi-generator#7537]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

We use `application/octet-stream` stream to upload files to our API. This works fine with `axios` by itself, but the files end up with added bytes when using `typescript-axios` because it's using `JSON.stringify` on the file.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

```yaml
openapi: '3.0.3'
info:
  title: test-api
  version: '1.0'
paths:
  '/files/{id}':
    post:
      operationId: uploadFile
      parameters:
        - in: path
          name: id
          description: The `file` ID.
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
        required: true
      responses:
        '204':
          description: No Content
```

##### Generation Details

`openapi-generator generate --input-spec spec.yml -g typescript-axios -c config.yml`

```yaml
npmName: 'testing123'
npmVersion: '0.0.1'
snapshot: false
supportsES6: true
```

##### Steps to reproduce

Generate the SDK, observe error. Here's some code that spots the error,

```
import { strictEqual } from 'assert';
import { readFileSync } from 'fs';
import { Configuration } from '.';
import { FilesApiAxiosParamCreator } from './api';

const main = async () => {
  const config = new Configuration();
  const fileAsBuffer = readFileSync('package.json');
  const uploadFileParams = await FilesApiAxiosParamCreator(config).uploadFile(
    'id',
    fileAsBuffer
  );

  try {
    strictEqual(uploadFileParams.options.data, fileAsBuffer);
    console.log('[success] SDK verification passed.');
  } catch {
    console.error('[error] SDK verification failed');
    process.exit(1);
  }
};
```

##### Suggest a fix

This generator produces,

```ts
const needsSerialization =
  typeof body !== 'string' ||
  localVarRequestOptions.headers['Content-Type'] === 'application/json';
localVarRequestOptions.data = needsSerialization
  ? JSON.stringify(body !== undefined ? body : {})
  : body || '';
```

Changing this to the following fixes the issue,

```ts
const needsSerialization = false;
localVarRequestOptions.data = needsSerialization
  ? JSON.stringify(body !== undefined ? body : {})
  : body || '';
```

However, I'm not sure a more robust solution as checking `Buffer.isBuffer(x)` isn't browser safe. Maybe just leave the body alone if `content-type` is `application/octet-stream`?

**Comment by macjohnny** [comment]
@therockstorm would you like to file a PR to fix this?
