### ISSUE TITLE
[BUG] Python response fails to deserialize when $ref is used inside additionalProperties

### ISSUE THREAD

**Issue by keymone** [OpenAPITools/openapi-generator#7545]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When response schema uses additionalProperties with $ref, the generated return type for request method is `dict(str, list)`, which fails to deserialize because `list` doesn't specify item types.

##### openapi-generator version

4.3.1, 5.0.0-beta, master

##### OpenAPI declaration file content or url

```yaml
components:
  schemas:
    a: {type: object, additionalProperties: {$ref: '#/components/schemas/b'}}
    b: {type: array, items: {type: string}}
paths:
  /z:
    get:
      responses:
        "200":
          description: z
          content: {application/json: {schema: {$ref: '#/components/schemas/a'}}}
```

##### Generation Details

```shell
rm -rf api
docker run --rm -i --user `id -u`:`id -g` -v `pwd`:/src \
  openapitools/openapi-generator-cli generate \
    -i /src/oapi.yaml \
    -g python \
    --package-name foo \
    -o /src/api
```

##### Steps to reproduce

Observe that:

```
cat api/foo/api/default_api.py | grep rtype
```

lists a return type `dict(str, list)`.

##### Related issues

I would expect this to have been fixed by https://github.com/OpenAPITools/openapi-generator/pull/7383, but it still fails on master.

cc @spacether

**Comment by spacether** [comment]
@keymone can you try using the `python-experimental` generator?
The fix that you referred to is for the python-experimental generator, not the python generator.

**Comment by keymone** [comment]
ah, i see. i didn't try experimental because there isn't a version tag i can refer to for deterministic builds, so i switched to normal python. will try in a sec.

**Comment by keymone** [comment]
yeah, looks correct in experimental, sorry for bothering.

**Comment by keymone** [comment]
is there a schedule for beta releases?
