### ISSUE TITLE
[BUG] [Typescript] allow body on DELETE

### ISSUE THREAD

**Issue by dartzki** [OpenAPITools/openapi-generator#7557]
##### Description

The typescript api currently does not support passing a body to a delete request.
DELETE Requests may have a body as per specification.
Generated services for a DELETE Request with a body simply drop the 'body' argument, leading to a wrong request.

##### openapi-generator version

5.0.0-beta2

##### Suggest a fix

the templates should be adapted to use `httpClient.request` instead of `httpClient.{{httpMethod}}` and pass the `{{httpMethod}}` as first, and the body as third argument.

Also, looking at the repo it seems that the openapi-generator suggests that DELETE request do not allow for a body by default:
https://github.com/OpenAPITools/openapi-generator/blob/ff68128c15363ece22d7b6376952eb4eabc1f0bd/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenOperation.java#L203

Imo this is very misleading.

**Comment by FelixCoutinho** [comment]
OpenAPI Spec is going to introduce body as optional in DELETE operations in their version 3.1.0

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md
