### ISSUE TITLE
[REQ] Add a new property "baseDataType" for containers

### ISSUE THREAD

**Issue by noordawod** [OpenAPITools/openapi-generator#7560]
### Is your feature request related to a problem? Please describe.

For arrays and maps, the `dataType` property currently holds the complete definition of the container, as in:

List&lt;ModelType&gt;
Map&lt;ModelType&gt;

There is a property for the container type (`baseType`), but there's no property for the type itself: `ModelType`

## Describe the solution you'd like

Add a new property in the generator, specifically when dealing with containers, that holds the generic type of the list/map. I propose to call it `baseDataType`.

## Additional context

This is needed for Dart, as an example, when generating code for the constructors.

```dart
class AClass {
  AClass({
    this.prop = const <AnotherClass>[],    // this line cannot be created today.
  });

  final List<AnotherClass> prop;
}
```

**Comment by kuhnroyal** [comment]
From my experience this is usually the property `complexType`.

```
      "openApiType" : "array",
      "baseName" : "tags",
      "complexType" : "Tag",
      "getter" : "getTags",
      "setter" : "setTags",
      "dataType" : "List<Tag>",
      "datatypeWithEnum" : "List<Tag>",
      "name" : "tags",
      "defaultValue" : "const []",
      "defaultValueWithParam" : " = data.tags;",
```

**Comment by noordawod** [comment]
I'll check it, thanks @kuhnroyal!
