### ISSUE TITLE
[Dart] Use resources/3_0/petstore.yaml in dart2 generators

### ISSUE THREAD

**Issue by agilob** [OpenAPITools/openapi-generator#7588]
Simple as that, move dart generators to use more complex schema from openapi 3.0.
New files are more complex and expose new bugs in Dart.

**Comment by wing328** [comment]
Agreed with using another spec with more test cases.

We can consider https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml but likely it will uncover issues that take some time to address.

**Comment by agilob** [comment]
Mentioned resources/3_0/petstore.yaml only because it's the most popular.

**Comment by kuhnroyal** [comment]
The simple petstore example is now merged and integration test for the fake-api are alos merged but are not working yet.
