### ISSUE TITLE
[BUG] Use of GlobalSettings in gradle-plugin leads to race conditions in Gradle 6.6+

### ISSUE THREAD

**Issue by nhoughto** [OpenAPITools/openapi-generator#7601]
##### Description

On the latest version of Gradle 6.6 and latest generator 4.3.1 I am seeing inconsistent generation of outputs, some projects where model generation is disabled, intermittently models appear and the next run they do not appear. I believe this is due to running my multi-module gradle project with a number of openapi generator tasks running at once, the current problem is with ~5 concurrent generations running.

It appears that there is a race condition in the GeneratorTask and the use of a global singleton GlobalSettings:

https://github.com/OpenAPITools/openapi-generator/blob/61b543f03dc546386467c9a7afe8864f6f609ed1/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt#L513

GlobalSettings appears to defend against this via a ThreadLocal map which seems to work in Gradle 6.5, but fail in Gradle 6.6+. I'm not sure whats changed in Gradle land but it seems like any settings configured via GlobalSettings conflict/collide with each other when running concurrently, if I set `--max-workers 1` everything works as expected, if workers is > 1 then the problems start.

##### openapi-generator version

4.3.1

##### OpenAPI declaration file content or url

n/a

##### Generation Details

n/a

##### Steps to reproduce

n/a

##### Related issues/PRs

None that I can see 

##### Suggest a fix

Not sure, it seems like something in upstream Gradle has changed in the 6.5 -> 6.6 upgrade, I was able to work around it by moving from configuration that ended up in GlobalSettings and re-implemented it in ignore files.

**Comment by wing328** [comment]
@nhoughto thanks for reporting the issue. Have you tried the latest master to see if the issue is reproducible?

**Comment by nhoughto** [comment]
Indirectly, the file in question hasn't changed between the link (https://github.com/OpenAPITools/openapi-generator/blob/61b543f03dc546386467c9a7afe8864f6f609ed1/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt#L513) and master, so yes?

This was more an FYI that gradle have changed something that means you can't safely use static singletons anymore, like GlobalSettings. I assume it has something to do with the classloading of gradle tasks, previously the openapi generator classes must have got their own classloader, so the GlobalSettings static variables weren't shared between tasks but now it appears they are.

**Comment by chschu** [comment]
I just reported a bug against Gradle that causes this issues: https://github.com/gradle/gradle/issues/17344

In `org.openapitools.codegen.config.GlobalSettings`, a call to `System.getProperties().clone()` is used to create a independent `Properties` instance. Due to the Gradle bug, the cloned instances are all connected to each other via the shared JVM system properties instance.

As a workaround, `GlobalSettings` can create the copy by other means.
