### ISSUE TITLE
[BUG] [swift5] 5.0.0-beta2 generates AnyType

### ISSUE THREAD

**Issue by hyunoosung** [OpenAPITools/openapi-generator#7618]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Our api doesn't provide enum types on query params.
Version 5.0.0-beta2 cast these enums as AnyType which is not usable in Swift project.

Same issue has reported and resolved for typescript-axos https://github.com/OpenAPITools/openapi-generator/issues/6273

##### openapi-generator version

@openapitools/openapi-generator-cli@cli-5.0.0-beta2

and master branch

##### OpenAPI declaration file content or url
https://api-int.icloudhospital.com/swagger/v1/swagger.json

##### Generation Details

With master branch

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g swift5 -i https://api-int.icloudhospital.com/swagger/v1/swagger.json -o src --skip-validate-spec

With 5.0.0-beta2

openapi-generator generate -g swift5 -i https://api-int.icloudhospital.com/swagger/v1/swagger.json -o src --skip-validate-spec   

##### Steps to reproduce

Since our api doesn't provide enum type on it's query params, I had to add skip-validate-spec

Version 5.0.0-beta2 cast these enums as AnyType which is default for all generator and my Swift project can't find this type.

When I build the master branch and generated client, my project throws below error.

The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions
![image](https://user-images.githubusercontent.com/9585318/95298802-9c584500-08b7-11eb-8353-61b7e93c7536.png)

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/6273

**Comment by wing328** [comment]
Thanks for reporting the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/7644 to fix it.

**Comment by teameh** [comment]
@wing328 same here, this issue can be closed
