### ISSUE TITLE
[BUG] [typescript-angular] Query param key is undefined when using queryParamObjectFormat=json

### ISSUE THREAD

**Issue by thccorni** [OpenAPITools/openapi-generator#7619]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generating the client with `queryParamObjectFormat` set to `json` breaks the query string resulting in request urls like:
`https://example.com/pizzas?undefined={someJSON}` instead of `https://example.com/pizzas?filter={someJSON}`.

##### openapi-generator version

v5.0.0-beta2

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: 'Sample-API'
  version: '1.0.0'
paths:
  /pizzas:
    get:
      parameters:
        - name: filter
          in: query
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PizzaFilter'
      responses:
        200:
          description: Delicious pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  schemas:
    PizzaFilter:
      type: object
      additionalProperties: true
```

##### Steps to reproduce

```bash
npx @openapitools/openapi-generator-cli version-manager set 5.0.0-beta2
npx @openapitools/openapi-generator-cli generate -i spec.yaml -g typescript-angular -o ./generated --additional-properties=queryParamObjectFormat=json
```

##### Suggest a fix

I think the Problem is that the key parameter is not passed here:
https://github.com/OpenAPITools/openapi-generator/blob/d8ba49b267d7bfe9d558631d2888a6d54a1c3bf8/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L97

Therefore it is undefined here:
https://github.com/OpenAPITools/openapi-generator/blob/d8ba49b267d7bfe9d558631d2888a6d54a1c3bf8/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L111

A possible fix could be to move the distinction of the query param format to `addToHttpParams` instead of `addToHttpParamsRecursive`

```mustache
private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
    if (typeof value === "object" && value instanceof Date === false) {
        {{#isQueryParamObjectFormatJson}}
        httpParams = httpParams.append(key, JSON.stringify(value));
        {{/isQueryParamObjectFormatJson}}
        {{^isQueryParamObjectFormatJson}}
        httpParams = this.addToHttpParamsRecursive(httpParams, value);
        {{/isQueryParamObjectFormatJson}}
    } else {
        httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
    }
    return httpParams;
}

private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
    if (value == null) {
        return httpParams;
    }

    if (typeof value === "object") {
        if (Array.isArray(value)) {
            (value as any[]).forEach( elem => httpParams = this.addToHttpParamsRecursive(httpParams, elem, key));
        } else if (value instanceof Date) {
            if (key != null) {
                httpParams = httpParams.append(key,
                    (value as Date).toISOString(){{^isDateTime}}.substr(0, 10)){{/isDateTime}};
            } else {
                throw Error("key may not be null if value is Date");
            }
        } else {
            Object.keys(value).forEach( k => httpParams = this.addToHttpParamsRecursive(
                httpParams, value[k], key != null ? `${key}{{#isQueryParamObjectFormatDot}}.{{/isQueryParamObjectFormatDot}}{{#isQueryParamObjectFormatKey}}[{{/isQueryParamObjectFormatKey}}${k}{{#isQueryParamObjectFormatKey}}]{{/isQueryParamObjectFormatKey}}` : k));
        }
    } else if (key != null) {
        httpParams = httpParams.append(key, value);
    } else {
        throw Error("key may not be null if value is not object or array");
    }
    return httpParams;
}
```

**Comment by godfryd** [comment]
I'm not sure if this is the same. I'm observing the same wrong result when I pass an array as argument.

```typescript
private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
        if (typeof value === "object" && value instanceof Date === false) {
            httpParams = this.addToHttpParamsRecursive(httpParams, value);
        } else {
            httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
        }
        return httpParams;
    }
```
this function does not recognize that value is an array and it goes into the first condition (as array is object type). And then key is missed and then `throw Error("key may not be null if value is not object or array");` happens.

From debugger:
![image](https://user-images.githubusercontent.com/176567/95670891-62c25b00-0b91-11eb-9346-f60b50e4cab2.png)
you can see that the value is an array and it gets into the first condition and then `key` is dropped.
