### ISSUE TITLE
[Docker] openapi-generator-cli code gernator does not respect packageName for AbstractOpenAPISchema

### ISSUE THREAD

**Issue by marcelloceschia** [OpenAPITools/openapi-generator#7645]
##### Description

We are generating the client code with the following comand:

`/usr/local/bin/docker-entrypoint.sh generate -i ${SWAGGER_FILE} -g csharp-netcore --skip-validate-spec --additional-properties=targetFramework=${TARGET_FRAMEWORK} --additional-properties=netCoreProjectFile=true --additional-properties=packageName=${PACKAGE} --additional-properties=packageVersion=${MODULE_VERSION} -o dotnet`

where `PACKAGE` is `EXAMPLE.NAME.API`

The generation went well, but compiling is not posible because of:
```
Fehler	CS0246	Der Typ- oder Namespacename "Org" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).	EXAMPLE.NAME.API	
```
source:
```
 public string Serialize(object obj)
        {
            if (obj != null && obj is Org.OpenAPITools.Model.AbstractOpenAPISchema)
            {
                // the object to be serialized is an oneOf/anyOf schema
                return ((Org.OpenAPITools.Model.AbstractOpenAPISchema)obj).ToJson();
            }
            else
            {
                return JsonConvert.SerializeObject(obj, _serializerSettings);
            }
        }
```
the correct source has to be:

```
public string Serialize(object obj)
        {
            if (obj != null && obj is EXAMPLE.NAME.API.Model.AbstractOpenAPISchema)
            {
                // the object to be serialized is an oneOf/anyOf schema
                return ((EXAMPLE.NAME.API.Model.AbstractOpenAPISchema)obj).ToJson();
            }
            else
            {
                return JsonConvert.SerializeObject(obj, _serializerSettings);
            }
        }
```

##### openapi-generator version
```
Pulling docker image openapitools/openapi-generator-cli ...
Using docker image sha256:fdf80265f1dc9f87464c146b2e2ff494e666c409583323ec8d50c519725d85e4 for openapitools/openapi-generator-cli 
```

Time: `2020-10-09T19:39:25.605+02:00`

##### OpenAPI declaration file content or url

-

##### Command line used for generation

see above

##### Suggest a fix/enhancement

Use `packageName` for this namespace

**Comment by wing328** [comment]
@marcelloceschia thanks for reporting the issue. I've included the fix in https://github.com/OpenAPITools/openapi-generator/pull/7626.

**Comment by wing328** [comment]
Meged #7626 into master. Please pull the latest to give it another try.

Thanks again for reporting the issue.

**Comment by marcelloceschia** [comment]
@wing328 Thank you, its working again.
