### ISSUE TITLE
[BUG][typescript-fetch] Complex values are serialized as the string [object Object] in multipart/form-data

### ISSUE THREAD

**Issue by verokarhu** [OpenAPITools/openapi-generator#7658]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Complex types are incorrectly serialized as the string `[object Object]` when they are used as a part in a `multipart/form-data` request body.

##### openapi-generator version

4.3.1 / 5.0.0-beta2 / 2ec96f7f9057ea67f7362d7d23d39a00e430410a

##### OpenAPI declaration file content or url

```yaml
---
openapi: "3.0.0"
info:
  title: Bug test case
  version: "1.0"
paths:
  /example:
    post:
      operationId: exampleOperation
      requestBody:
        content:
          multipart/form-data:
            schema:
              properties:
                complexvalue:
                  properties:
                    value1:
                      type: number
                    value2:
                      type: string
                  type: object
              type: object
      responses:
        "201":
          description: Created
```

##### Generation Details

`java -jar openapi-generator-cli.jar generate -g typescript-fetch -i testcase.yml -o generated`

##### Suggest a fix

The generated model (`models/ExampleComplexvalue.ts, 21-34`) is correct:
```
export interface ExampleComplexvalue {
    /**
     * 
     * @type {number}
     * @memberof ExampleComplexvalue
     */
    value1?: number;
    /**
     * 
     * @type {string}
     * @memberof ExampleComplexvalue
     */
    value2?: string;
}
```

However, the generated serialization code (`apis/DefaultApi.ts, 53-55`) is incorrect:
```
        if (requestParameters.complexvalue !== undefined) {
            formParams.append('complexvalue', requestParameters.complexvalue as any);
        }
```

As you can see from the [documentation of FormData.append()](https://developer.mozilla.org/en-US/docs/Web/API/FormData/append#Syntax), all other types than Blob or subclasses will be converted into string:
```
value
The field's value. This can be a USVString or Blob (including subclasses such as File). If none of these are specified the value is converted to a string.
```

The correct way to serialize this would be to convert the complex type into a JSON Blob before serializing it:
```
new Blob([JSON.stringify(requestParameters.complexvalue)], { type: "application/json", }
```

This should not be done to simple string types though, since they need to be appended as-is and should have the [default](https://tools.ietf.org/html/rfc7578#section-4.4) `text/plain` Content-Type.

**Comment by pmfonsecatdx** [comment]
I found this exact same bug in typescript-axios.
I think this solution would work for typescript-axios as well!
Any plans on fixing it for the other typescript generators?

**Comment by macjohnny** [comment]
@pmfonsecatdx it would be great if you could file a PR for implementing this in typescript-axios.
