### ISSUE TITLE
[REQ] Configurable download link

### ISSUE THREAD

**Issue by UnleashSpirit** [OpenAPITools/openapi-generator#7660]
### Is your feature request related to a problem? Please describe.

I started a new project, anuglar, and with the last version I have to download the {version}.jar
On the jenkins server, I have no internet so it can't download from hard coded https://repo1.maven.org/maven2/${group}/${artifact}/${versionName}/${artifact}-${versionName}.jar

## Describe the solution you'd like

A parameter to set the repo targert (like company nexus).

## Describe alternatives you've considered

None I can't set internet access for jenkins server. But I'm open to any solution.
I may have missed an already existing parameter ?

**Comment by UnleashSpirit** [comment]
Hi,

Any information about a workaround ?
I tried with openapitools.json and local nexus but without any success.
```json
{
  "$schema": "node_modules/@openapitools/openapi-generator-cli/config.schema.json",
  "spaces": 2,
  "generator-cli": {
    "version": "4.3.1",
    "queryUrl": "http://[nexus.local]/repository/maven-public/solrsearch/select?q=g:${group.id}+AND+a:${artifact.id}&core=gav&start=0&rows=200",
    "downloadUrl": "http://[nexus.local]/repository/maven-public/"
  }
}

```

**Comment by wing328** [comment]
Can the jenkin server connect to the internal network of your company? If yes, can you copy the JAR over from internal storage to the jenkin server?

**Comment by UnleashSpirit** [comment]
> Can the jenkin server connect to the internal network of your company? If yes, can you copy the JAR over from internal storage to the jenkin server?

I guess yes but I don't have access to the jenkins' storage. And even if I have it, the jenkins workspace is cleaned from time to time.

**Comment by wing328** [comment]
Well just copy the JAR over every time a new job is started.

**Comment by UnleashSpirit** [comment]
That could be a workaround (and not a solution) if i have access to the storage which I don't.
I can copy the jar in git and then copy after npm install and before openapi genreration but that's not awesome ^^

**Comment by wing328** [comment]
Do you have the full URL to the openapi-generator-cli.jar hosted in your company nexus?

**Comment by UnleashSpirit** [comment]
> Do you have the full URL to the openapi-generator-cli.jar hosted in your company nexus?

It seems not. But I may can asj for it.

> If yes, can you not use `wget` or some other tools to download the JAR to your jenkin server?

The solution of using openapitools.json and the overload of downloadUrl can't work ? (if I use local nexus full url ?
