### ISSUE TITLE
[BUG][Ruby] undefined method in api_client.rb

### ISSUE THREAD

**Issue by tsuwatch** [OpenAPITools/openapi-generator#7708]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
ref: https://github.com/OpenAPITools/openapi-generator/pull/3564

In this PR, merged faraday and typehouse mustache files.
`build_request` requires `request` object of `Typehouse`, but using `faraday`.
So, `request.on_headers` in `download_file` does not exist.

@wing328 
I need your thoughts on this.

Thank you.

##### openapi-generator version
v5.0.0-beta2 released

**Comment by tsuwatch** [comment]
It's possible that it couldn't be used originally.

**Comment by tsuwatch** [comment]
Looks like it...
https://github.com/OpenAPITools/openapi-generator/pull/3405

**Comment by wing328** [comment]
@tsuwatch thanks for reporting the issue. When you've time, can you please PM me via Slack?

https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by wing328** [comment]
@tsuwatch the fix has been merged into master. Please give it a try to see if you still experience the same issue.
