### ISSUE TITLE
[BUG] Generated TypeScript client fails to handle HTTP 204 No Content

### ISSUE THREAD

**Issue by astraljava** [OpenAPITools/openapi-generator#7720]
##### Description

When we generate a TypeScript API client from our schema, it generates a correct call for fetching data from backend systems and expects to receive a list in return. This works fine, when we receive HTTP 200 OK and deserialize a JSON object with the aforementioned list.

But if there aren't any data to return, we expect to see HTTP 204 No Content, but the client fails as it attempts to deserialize an empty JSON object.

The schema passes online validation. 

##### openapi-generator version
4.3.1 

have tested also with 5.0.0-beta2

**Comment by macjohnny** [comment]
@astraljava would you like to fix this?

**Comment by astraljava** [comment]
I'll try to find time. :)

**Comment by IrateGod** [comment]
Hey, my team recently stumbled across this issue as well. In the plain Javascript generator, this behaviour would yield a `null` response from the generated function.
To replicate this behaviour, you can override the `runtime.mustache` template, such that the JSONApiResponse can handle the 204 No Response response. An example would be editing it on line 282 with: `if (this.raw.status === 204) { /* handle 204 */ }`.

I tested this on 5.1.1, and it works well within my team's ecosystem now. I can commit and create a PR with this change if desired.

**Comment by xsorifc28** [comment]
What is the status of this fix?

**Comment by xsorifc28** [comment]
Incase anyone if running into this with Spring+Springfox, add the following to your `ResponseType<Void>` api methods:
```java
@ApiResponse(code = 204, response = void.class, message = "No Content")
```

**Comment by Radha-rog** [comment]
Hi, even we are facing similar issue with Java native client library.

I have an api with 200 and 204 (no content) response code and the client code generated is as follows,

......
if (localVarResponse.statusCode()/ 100 != 2) {
              return CompletableFuture.failedFuture(getApiException("error", localVarResponse));
            }
            try {
              return CompletableFuture.completedFuture(
                  memberVarObjectMapper.readValue(localVarResponse.body(), new TypeReference<SampleResponse>() {})
              );
            } catch (IOException e) {
              return CompletableFuture.failedFuture(new ApiException(e));
            }
........

Due to which when we get 204 response , we end up with IOException "No content to map due to end-of-input"

Any solution or suggestion to fix this is much appreciated.

**Comment by eodeg** [comment]
I also have this issue and have implemented workaround described here: https://stackoverflow.com/questions/70924236/openapi-generator-cant-handle-status-code-204

The workaround is OK but would be good to solve it in the generated client?

**Comment by sindremb** [comment]
To properly resolve this issue i propose a couple of minor changes to the `apis.mustache` template used by the `typescript-fetch` generator to properly make use of the `isResponseOptional` value. But please note that this solution depends on a related bug with  `isResponseOptional` being fixed first[^1].

First, change the response types for each method to potentially be nullable / undefined if the response is optional by adding the following to each response type definition

```
{{#returnType}}{{#isResponseOptional}} | null | undefined {{/isResponseOptional}}{{/returnType}}
```

You would then get 2 parts of the template with the following response definition template (useSingleRequestParameter true vs false)
```
: Promise<{{{returnType}}}{{#returnType}}{{#isResponseOptional}} | null | undefined {{/isResponseOptional}}{{/returnType}}{{^returnType}}void{{/returnType}}>
```

And one Raw method template with the response
```
: Promise<runtime.ApiResponse<{{{returnType}}}{{#returnType}}{{#isResponseOptional}} | null | undefined {{/isResponseOptional}}{{/returnType}}{{^returnType}}void{{/returnType}}>>
```

In addition, I suggest replacing the current `return await response.value();` (2 locations) with the following:

```
{{#isResponseOptional}}
switch (response.raw.status) {
    {{#responses}}
    {{#is2xx}}
    case {{code}}:
        return {{#dataType}}await response.value(){{/dataType}}{{^dataType}}null{{/dataType}};
    {{/is2xx}}
    {{/responses}}
    default:
        return await response.value();
}
{{/isResponseOptional}}
{{^isResponseOptional}}
return await response.value();
{{/isResponseOptional}}
```

as this avoid getting an exception from `await this.raw.json()` inside `runtime.mustache` when a response with no response data is received. This could potentially be handled by the runtime template, but this could result in swallowing too many exceptions as well as the signature of the async value(): Promise<T> should then also be changed.

[^1]: currently there is a bug in the typescript generator where [isResponseOptional is always false](https://github.com/OpenAPITools/openapi-generator/issues/15457)

**Comment by MrKumaPants** [comment]
@sindremb Can you submit a fix for this? Hitting this in production code and am having to do some weird workarounds. 

This is a pretty high sev bug as it doesn't handle the openapi spec properly for this instance.

**Comment by sindremb** [comment]
@MrKumaPants I'll see what I can do. For the above workaround the be able to work at all, the linked bug will have to be fixed first, so I'll start there. Once that is in place, you can use custom mustache templates with the modifications described above from the originals to make it work, but this should ideally be included in the default templates as well.

**Comment by sindremb** [comment]
I've now created a PR #17635 that hopefully can resolve this issue for the typescript-fetch generator. @MrKumaPants
