### ISSUE TITLE
[BUG] spaces missing from type hints in generated ocaml code

### ISSUE THREAD

**Issue by bobpoekert** [OpenAPITools/openapi-generator#7738]
##### Description

Running the ocaml code generator generates code that fails to build because spaces have been removed from type declarations that should have space. Eg: `string option` becomes `stringoption`

##### openapi-generator version

Both git master and 4.3.1 release

##### OpenAPI declaration file content or url

https://github.com/stripe/openapi/blob/master/openapi/spec3.yaml, though I'm sure a simpler spec would also fail

**Comment by wing328** [comment]
Thanks @Zomzog for filing a fix (#7742)

@bobpoekert can you please also review the fix when you've time?

**Comment by wing328** [comment]
👌 

We can consider using https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml to generate the OCaml client and test it in the CI.
