### ISSUE TITLE
[BUG][cpp-restsdk] Numbers without dots (integers) are not converted to double

### ISSUE THREAD

**Issue by tzickel** [OpenAPITools/openapi-generator#7751]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Trying to use the cpp-restsdk client generator I have a few issues. I'll write them in order of importance:

1. **If I define a property as a type number, format double, it will only accept JSON numbers with dot, and not parse integers!!.** The csharp-nancyfx server encodes 0 as 0 and not 0.0 which ofcourse causes this not to work. I guess the ModelBase for float/double should need a check for double casting and if not, than int casting.

2. The modelbase seems to ignore required flags in the model, and in the situation above it will put NaNs in the model instead of erroring that not all required fields have been set (in this case it's a bug, bug in other cases where it can't convert?). The ok result of fromJson should be checked, and an exception raised if the required fields have been specified ?

3. The new CMake modifications for this client for some reason declare the model/modules header files as private and require manual addition of them in the client that uses the autogen code, is that a mistake ? (why would I want to use this generated code, if not to use it's header files, and those I don't want I can disable in generation part ?) Make them non-private in the cmake script ?

##### openapi-generator version

master

##### Suggest a fix

Written above.

**Comment by tzickel** [comment]
Also for "cpp-restsdk" in the topic it didn't seem to put the correct client issue tag.

**Comment by wing328** [comment]
1.  I guess the ModelBase for float/double should need a check for double casting and if not, than int casting.

Right. Without dot should cause issues. 

2. The ok result of fromJson should be checked, and an exception raised if the required fields have been specified ?

Agreed. That's how other clients handle required fields. 


3. Make them non-private in the cmake script ?

Sounds good to me. 

We would appreciate separate PRs for the issues above. Let me know if you need help with the PR.
