### ISSUE TITLE
[REQ][Kotlin] Use Moshi codegen instead of reflection for generating JSON adapters

### ISSUE THREAD

**Issue by stephen-mojo** [OpenAPITools/openapi-generator#7773]
## Is your feature request related to a problem? Please describe.

Moshi can generate JSON adapters two different ways. The old way used reflection. There is a newer way that avoids reflection and uses code generation instead. Typically, code generation performs better than reflection. 

OpenAPI uses the reflection approach when generating Kotlin Moshi code.

## Describe the solution you'd like

Ideally, OpenAPI Generator would use the code generation approach over reflection. 

Remove `com.squareup.moshi:moshi-kotlin` dependency.
Remove `Moshi.Builder().add(KotlinJsonAdapterFactory())`
Add `com.squareup.moshi:moshi-kotlin-codegen` dependency.
Annotate each generated model with `@JsonClass(generateAdapter = true)`
 

## Describe alternatives you've considered

The alternative is leaving it as is, but that may affect performance.

## Additional context
See: [https://github.com/square/moshi#kotlin](url)

**Comment by kuFEAR** [comment]
Hi, you can try use "moshiCodeGen : true" option in configuration

**Comment by stephen-mojo** [comment]
@kuFEAR Thank you so much! I didn't know that was an option. That worked perfectly. Closing the issue.

**Comment by stephen-mojo** [comment]
I am re-opening this. It seems I celebrated too soon. While adding this to my config does in fact generate the models in the way that I want, I now face a new error. When I build, I get the following error in my Android Studio project.

```
Execution failed for task ':app:kaptDevelopmentDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)
```

**Comment by stephen-mojo** [comment]
And closing again. Sorry about the back and forth! Once again, I spoke before thinking hard enough.

My issue was that I had the following dependency...
`implementation "com.squareup.moshi:moshi-kotlin-codegen:$moshi_version"
`
..when I should have had this:
`kapt "com.squareup.moshi:moshi-kotlin-codegen:$moshi_version"

Thanks again for your help!
`

**Comment by alexfacciorusso** [comment]
Hi all!

I think the `moshiCodeGen : true` option is not listed anywhere, and it should be added to the doc!

**Comment by flipch** [comment]
Wouldn't the `Serializer` object also have to change to register the adapters? This is currently not adding the added adapters into the object from which the template builds upon.

```object Serializer {
    @JvmStatic
    val moshiBuilder: Moshi.Builder = Moshi.Builder()
        .add(OffsetDateTimeAdapter())
        .add(LocalDateTimeAdapter())
        .add(LocalDateAdapter())
        .add(UUIDAdapter())
        .add(ByteArrayAdapter())
        .add(URIAdapter())
        .add(BigDecimalAdapter())
        .add(BigIntegerAdapter())

    @JvmStatic
    val moshi: Moshi by lazy {
        moshiBuilder.build()
    }
}
```

**Comment by stephen-mojo** [comment]
@flipch I don't follow. When you reference `Serializer.moshi`, if the initialization block hasn't run yet, it runs and builds a Moshi instance off `moshiBuilder` that already has the adapters registered. If the init block has already run, it just returns the same instance. So aren't the adapters correctly registered?

**Comment by flipch** [comment]
I might be misunderstanding but the above snippet was the generated code from open-api.

After applying the code-gen ksp code we have adapters generated from the `model` package. However wouldn't the `Moshi` instance still only contain the adapters I wrote above?

That's the case for my local instance. So the adapters were generated, the annotations are there, however the `moshi` builder was never modified to also have `.add(ModelXXAdapter)` etc...

**Comment by stephen-mojo** [comment]
They are automatigically added to Moshi. No need to manually register code-genned adapters!
