### ISSUE TITLE
[REQ][Gradle Plugin] Load input spec from remote URL rather than local file

### ISSUE THREAD

**Issue by stephen-mojo** [OpenAPITools/openapi-generator#7778]
### Is your feature request related to a problem? Please describe.

I have looked through the existing issues and documentation and cannot seem to find any way to specify an input spec to the Gradle plugin as a URL rather than a path to a local file.

## Describe the solution you'd like

It would be great if I could load the input spec from my server rather than having to have the spec as a local file that is read in.

## Describe alternatives you've considered

The alternative is simply providing a path to a local spec file.

**Comment by wing328** [comment]
Did you try putting an URL in `inputSpec`? What error(s) did you get?

**Comment by stephen-mojo** [comment]
@wing328 I just tried a URL again. This time it worked. I could have sworn I did it exactly the same way earlier today and was getting errors. Weird. Anyways, thanks for your help! Closing this issue.
