### ISSUE TITLE
[Ruby] multi line path description breaking gem if 'in' appears

### ISSUE THREAD

**Issue by developersteve** [OpenAPITools/openapi-generator#781]
##### Description

Ruby generation breaking if 'in' is in any path multi line description, only seems to be ruby that has an issue language wise. 

##### openapi-generator version

3.2.0

##### OpenAPI declaration file content or url

```yaml
          description: |
            A JSON or XML payload containing the recipient's phone number and MMS message.
            The recipient number should be in the format '04xxxxxxxx' where x is a digit.
```
##### Steps to reproduce

Generate ruby lib then try to use it, for any description text on a new line the text wont be parsed 

##### Suggest a fix/enhancement

Allow for multi line text to be parsed (check for CR)

**Comment by wing328** [comment]
@developersteve thanks for reporting the issue, which should be fixed by #866 

Please give it a try and let us know if you still experience the issue.

SNAPSHOT version: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/3.2.2-SNAPSHOT/
