### ISSUE TITLE
[BUG][dart] --type-mappings ignored in version 4.3.1+

### ISSUE THREAD

**Issue by JFreakDK** [OpenAPITools/openapi-generator#7819]
##### Description

We generate dart client code using this script:
```#!/bin/bash -v
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
docker run --rm \
-v ${DIR}:/swagger-api/out -v ${DIR}:/swagger-api/json openapitools/openapi-generator-cli:v4.3.1 generate \
--type-mappings Instant=String \
-i /swagger-api/json/swagger.json \
-g dart \
--additional-properties browserClient=false,useEnumExtension=true \
--enable-post-process-file \
-o /swagger-api/out \
```
We used to generate the dart code with version v4.2.3. When it found a parameter it could not map it defaulted to the type `Object`. In version v4.3.1 the default type changes to AnyType.

##### openapi-generator version

It works with version v4.2.3 and fails with version v4.3.1

##### OpenAPI declaration file content or url

[swagger.json](https://gist.github.com/JFreakDK/62b3843ed0869b2999f430506005da5f)

##### Steps to reproduce

Run the command mentioned in the description with the different tags.

##### Suggest a fix

The default value for unknown dart types should be `Object` instead of `AnyType` which does not compile.

**Comment by wing328** [comment]
@JFreakDK thanks for reporting the issue. I've filed #7822 to fix it.

**Comment by JFreakDK** [comment]
Thank you @wing328 for the quick response
