### ISSUE TITLE
Multiple executions of openapi-generator-maven-plugin with skipIfSpecIsUnchanged

### ISSUE THREAD

**Issue by zshlomyz** [OpenAPITools/openapi-generator#7820]
### Is your feature request related to a problem? Please describe.

I am using the openapi-generator-maven-plugin to generate the source code twice (2 executions):

1. For the backend code - java - generatorName = spring
2. For the client code - generator name = typescript-redux-query

I also use the skipIfSpecIsUnchanged to skip the compilation if not needed.

When the parameter skipIfSpecIsUnchanged is true, the first execution (generating the java code) is working while the second (the client code) is skipped with the message - Code generation is skipped because input was unchanged.

## Describe the solution you'd like

Enable multiple executions of the plugin

Thanks!

**Comment by wing328** [comment]
@zshlomyz the fix by @Zomzog has been merged into master. Please pull the latest master or use the SNAPSHOT version to give it a try.
