### ISSUE TITLE
csharp-netcore generator not compatible with RestSharp 106.11.0 or greater

### ISSUE THREAD

**Issue by RubberChickenParadise** [OpenAPITools/openapi-generator#7832]
##### Description

When attempting to build with the latest version of `RestSharp` an error is raised at compile time that `No overload for AddHandler takes 6 arguments`

The Api Client generated for csharp-netcore creates the following partial chunk of code

```c#
public partial class ApiClient : ISynchronousClient, IAsynchronousClient
{
         //Lots of other code
        private ApiResponse<T> Exec<T>(RestRequest req, IReadableConfiguration configuration)
        {
            RestClient client = new RestClient(_baseUrl);

            client.ClearHandlers();
            var existingDeserializer = req.JsonSerializer as IDeserializer;
            if (existingDeserializer != null)
            {
                client.AddHandler(() => existingDeserializer, "application/json", "text/json", "text/x-json", "text/javascript", "*+json");
            }
            else
            {
                client.AddHandler(() => new CustomJsonCodec(configuration), "application/json", "text/json", "text/x-json", "text/javascript", "*+json");
            }

            client.AddHandler(() => new XmlDeserializer(), "application/xml", "text/xml", "*+xml", "*");

            client.Timeout = configuration.Timeout;
//Lots of other code
    }
}
```

In version 106.10.1 the `RestSharp` class `RestClient` had a public overload for the `AddHandler`  `public void AddHandler(Func<IDeserializer> deserializerFactory, params string[] contentTypes)`.  in version 106.11.0 this overload was removed from the public api.

##### openapi-generator version

Open Api Generator CLI version 4.3.1

##### OpenAPI declaration file content or url

Can reproduce with the petstore api.  issue is in the base `ApiClient`

##### Command line used for generation

npx @openapitools/openapi-generator-cli generate -i petstore.json -g csharp-netcore -o out

##### Steps to reproduce

generate the api client

install the latest version of restsharp 106.11.7

##### Suggest a fix/enhancement

Update the library to generate the correct api code to instantiate the `RestClient` or open a pull request in the `RestSharp` repo to add the public overload back.

**Comment by wing328** [comment]
Can you please try the latest master, which should have the issue fixed?

**Comment by RubberChickenParadise** [comment]
@wing328 The update from a couple months ago where you updated the dependencies does fix the issue.  Guess im on the older rest sharp till the next release of the generator.

**Comment by olabodeaguda** [comment]
@RubberChickenParadise, please, how did you fix this issue?
