### ISSUE TITLE
[REQ] Add error on duplicated path placeholders in CLI validate command

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#7853]
### Is your feature request related to a problem? Please describe.

Just figured out that my Slim server generation breaks immediately when spec contains operation path like:
```yml
paths:
  '/tags/{id}/learners/{id}':
    get:
      operationId: getLearnersByTag
```
Error from PHP Slim4 application:
```json
{
  "message": "Slim Application Error",
  "exception": [
    {
      "type": "FastRoute\\BadRouteException",
      "code": 0,
      "message": "Cannot use the same placeholder \"id\" twice",
      "file": "/Users/ybelenko/Sites/ca_back_slim/vendor/nikic/fast-route/src/DataGenerator/RegexBasedAbstract.php",
      "line": 139
    }
  ]
}
```

## Describe the solution you'd like

I think that CLI `validate` command should throw error when path contains duplicated placeholders. It could be an issue for most of the generators. I don't know how spec with duplicated placeholders can be valid at all... you have to add two parameters from path and they has to be named differently.

cc @jimschubert

**Comment by wing328** [comment]
As discussed, the `validate` functionality is provided by swagger parser so the enhancement needs to be done there instead.
