### ISSUE TITLE
[BUG] The operand of a 'delete' operator must be optional.

### ISSUE THREAD

**Issue by marikaner** [OpenAPITools/openapi-generator#7865]
##### Description

Currently when using the typescript-axios generator the generated typescript code does not compile, because it contains this line of code:
```ts
// fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
delete localVarUrlObj.search;
```

I can see that this has been fixed on your main branch internally, but it was not yet released:
https://github.com/OpenAPITools/openapi-generator/pull/6960

It would be great if there was a new release soon.

##### openapi-generator version

2.0.3

##### OpenAPI declaration file content or url

works (or doesn't) with any file

##### Generation Details

default generation

##### Steps to reproduce

just use -g typescript-axios

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/6960

##### Suggest a fix

Release a new version

**Comment by macjohnny** [comment]
@marikaner would you like to fix this?

**Comment by marikaner** [comment]
As far as I can see this is already fixed. It needs to be released only.

**Comment by macjohnny** [comment]
you can already use the fixed `5.0.0-SNAPSHOT` version

**Comment by marikaner** [comment]
@macjohnny But this is not stable right? I can't use this in production. Can this be fixed for the stable version somehow?

**Comment by macjohnny** [comment]
version 5.0.0 will be released in december I guess.
you can use the beta versions: https://github.com/OpenAPITools/openapi-generator/milestone/20

**Comment by marikaner** [comment]
Ok, thanks

**Comment by marikaner** [comment]
Hey @macjohnny,

I am trying to use the latest beta version, but it seems that there is no way to get it through the npm packaged CLI. The versioning system is not 100% clear to me, but it seems that there are no current beta versions available, correct?

**Comment by macjohnny** [comment]
```
PS D:\> openapi-generator-cli version-manager list                                                                                                                ? The following releases are available: (Use arrow keys)
  ☐  releasedAt  version      installed  versionTags
  -  ----------  -----------  ---------  ----------------------------
> ☐  2020-09-04  5.0.0-beta2  yes        5.0.0-beta2 5.0.0 beta2 beta
  ☐  2020-06-29  5.0.0-beta   no         5.0.0-beta 5.0.0 beta beta
  ☒  2020-05-06  4.3.1        yes        4.3.1 stable latest
```

**Comment by macjohnny** [comment]
however, the beta does not contain the changes you are looking for, you need the snapshot version: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.0.0-SNAPSHOT/

see also https://github.com/OpenAPITools/openapi-generator#11---compatibility

**Comment by marikaner** [comment]
Ok, now I got how the versions of the CLI relate to the versions of the generator. They don't ;)
Seems that actually adjusting the openapitools.json to 5.0.0-beta2 does the trick.

**Comment by scscgit** [comment]
Is there a reason why this can't be integrated within the stable version 4?

**Comment by macjohnny** [comment]
@scscgit as far as i know there will be no more patch releases of the version 4 branch

**Comment by scscgit** [comment]
@macjohnny so the existing version will forever cause compile errors in all TS projects that won't upgrade, making debugging painful and causing linters to be useless, and there's no chance of a stable solution for at least a month, huh...

Well, luckily I've at least found one quick hack of adding `@ts-nocheck` that we can use in our generate script in the meantime; the `replace-in-file` can't prepend text or add newlines, so if anyone has a better alternative, please share it :)
`npx @openapitools/openapi-generator-cli@cli-4.3.1 generate -i schema.yaml -g typescript-axios -o generated/path --type-mappings DateTime=Date && npx replace-in-file \"// tslint:disable\" \"/* eslint-disable */ // @ts-nocheck\" generated/path/*`

**Comment by macjohnny** [comment]
@scscgit due to the variety of sub-projects (i.e. the language-specific generators), patch-releases including a specific set of changes only would require a different setup and more effort from the contributors and maintainers. but looking at the `5.0.0-beta2` release, you should be able to use it without expecting serious breaking changes.

**Comment by MehranTaheri** [comment]
Just add
`declare module 'url' {
	interface Url {
		search: string | null | undefined;
	}
}
`
