### ISSUE TITLE
[REQ][PHP] Bump guzzle to version 7

### ISSUE THREAD

**Issue by toymachiner62** [OpenAPITools/openapi-generator#7869]
I have built a lib for others to use and it's using guzzle version 6.x b/c that's what openapi-generator uses. When other devs are consuming my project they are unable to use guzzle 7 since version 6 is what's being used in my lib generated from openapi-generator.

I come from node.js for the 8 years so i'm used to all of a projects dependencies using their own versions, but I guess php land is not like this. 

Can you bump guzzle to version to 7? Or is there another way to handle this dependency of a dependency issue that i'm unaware of?

**Comment by wing328** [comment]
> Can you bump guzzle to version to 7? Or is there another way to handle this dependency of a dependency issue that i'm unaware of?

One way is to use customized templates (CLI options: `-t`)

**Comment by atanasiuk-hubspot** [comment]
Hi, same question: Would the generated client be compatible with guzzle 7?

**Comment by jeffski** [comment]
+1, have users affected by this issue.

**Comment by jaap** [comment]
Issue already exists: https://github.com/OpenAPITools/openapi-generator/pull/7950

**Comment by jason-o-matic** [comment]
+1 here as well, with our users being affected.

**Comment by christianl-das** [comment]
+1 as one of the users @jason-o-matic is referring to :)

**Comment by christianl-das** [comment]
Is there any update on this?

**Comment by krzaczek** [comment]
Hi, it can be easly fixied by adding a custom composer template

Just create a `resources` dir and place a `composer.mustache` file in it.

```json
{
    "name": "{{gitUserId}}/{{gitRepoId}}",
    {{#artifactVersion}}
    "version": "{{artifactVersion}}",
    {{/artifactVersion}}
    "description": "{{{appDescription}}}",
    "keywords": [
        "openapitools",
        "openapi-generator",
        "openapi",
        "php",
        "sdk",
        "rest",
        "api"
    ],
    "homepage": "https://openapi-generator.tech",
    "license": "unlicense",
    "authors": [
        {
            "name": "OpenAPI-Generator contributors",
            "homepage": "https://openapi-generator.tech"
        }
    ],
    "require": {
        "php": ">=7.3",
        "ext-curl": "*",
        "ext-json": "*",
        "ext-mbstring": "*",
        "guzzlehttp/guzzle": "^6.2 || ^7.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^7.4",
        "friendsofphp/php-cs-fixer": "^2.12"
    },
    "autoload": {
        "psr-4": { "{{escapedInvokerPackage}}\\" : "{{srcBasePath}}/" }
    },
    "autoload-dev": {
        "psr-4": { "{{escapedInvokerPackage}}\\Test\\" : "{{testBasePath}}/" }
    }
}
```

And then use this template when building the API by adding `-t ./resources` to CLI command:

> java -jar openapi-generator-cli-5.1.0.jar generate -t ./resources -i openapi.yml -g php`

**Comment by grizzm0** [comment]
If you do this, don't forget to add `"guzzlehttp/psr7": "^1.8"` as the generated code uses functions that has been deprecated in 2.0.

**Comment by SamMousa** [comment]
Shouldn't we make it guzzle agnostic?
Nowadays we have PSR17 (Request factories) and PSR18 (HTTP Client), should make it a lot easier to plug in any client library version.

**Comment by stevenbuehner** [comment]
> If you do this, don't forget to add `"guzzlehttp/psr7": "^1.8"` as the generated code uses functions that has been deprecated in 2.0.

As far as I understand, the deprecated statuc functions from  guzzle/psr7 ^1.8 have been listed here with their guzzle/psr7 ^2.0 equivalent: https://github.com/guzzle/psr7/tree/2.0.0#upgrading-from-function-api
Wouldn't it make sense to upgrade right away to 2.0 ?

This is needed anyways to fix another bug handling ObjectSerialization of boolean query vars https://github.com/OpenAPITools/openapi-generator/issues/2204.

**Comment by jeffski** [comment]
Worth noting that with Guzzle 7.3, you will get an error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\Psr7\build_query()
```

build_query() has been deprecated in favor of `Query::build`

So https://github.com/OpenAPITools/openapi-generator/blob/5d68bd6a03f0c48e838b4fe3b98b7e30858c0373/modules/openapi-generator/src/main/resources/php/api.mustache will need to be updated to support Guzzle 7.3

**Comment by wing328** [comment]
@jeffski can you please submit a PR with the suggested fix when you've time? Thank you.

**Comment by heissb2342** [comment]
Hi there, 
I can supply a PR shortly as I was already looking into the guzzle 7 update a few weeks ago for swagger-codegen. 

Also another side note to deprecated function being in the code, there is also a reference in https://github.com/OpenAPITools/openapi-generator/blob/5d68bd6a03f0c48e838b4fe3b98b7e30858c0373/modules/openapi-generator/src/main/resources/php/api.mustache line 563 to `try_fopen()`, which needs to be replaced by `Utils::tryFopen`.

As I said PR should be coming in a few days so @jeffski should be off the hook ;)

**Comment by wing328** [comment]
Please pull the latest master to give it a try.

Thank you @heissb2342 for his contributions 👍

**Comment by rezapirighadim** [comment]
when I generate php still giving me guzzle 6.2
command that I used for generate 
`swagger-codegen generate -i https://x.com/api-docs -l php -o ~/Downloads/client`
