### ISSUE TITLE
[BUG][cpp-restsdk] Segmentation fault and error compilation when trying to receive binary data

### ISSUE THREAD

**Issue by tzickel** [OpenAPITools/openapi-generator#7898]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When receiving an binary string as a result, the C++ resksdk generator does not allocate the HttpContent it returns to the user, causing a Segmentation fault.

autogen/api/DefaultApi.cpp
```cpp
    .then([=](std::vector<unsigned char> localVarResponse)
    {
        std::shared_ptr<HttpContent> localVarResult; // <-- Here is the bug, there is no allocation for HttpContent.
        std::shared_ptr<std::stringstream> stream = std::make_shared<std::stringstream>(std::string(localVarResponse.begin(), localVarResponse.end()));
        localVarResult->setData(stream);
        return localVarResult;
    });
```

Another related bug, is that in the api/model dirs, if the code returns an HttpContent, it adds in autogen/api/DefaultApi.h:
```cpp
#include "HttpContent.h"
```

Which is wrong, and should point to:
```cpp
#include "../HttpContent.h"
```
instead.

##### openapi-generator version

The docker image openapitools/openapi-generator-cli:latest as of 5/11/2020
The docker image openapitools/openapi-generator-cli:v5.0.0-beta2

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"
info:
  title: "test"
host: "localhost:8080"
paths:
  /GetBackBinaryData:
    get:
      operationId: "GetBackBinaryData"
      produces:
      - "application/octet-stream"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: string
            format: binary
```

##### Generation Details

generate -i /local/bug.yaml -g cpp-restsdk -o /local/autogen

##### Steps to reproduce

Generate, try to call the:
```cpp
api.getBackBinaryData().wait()
```

##### Related issues/PRs

None

##### Suggest a fix

A fix would be to construct the HttpContent being used.

But a better fix, since this might be large data involved is to remove all this code, and simply return the std::vector<unsigned char> from the previous stage (it's not like any of HttpContent other properties are used in this code base anyhow). But if it's used maybe in OpenAPI 3, then maybe allow for it to maybe hold the original std::vector<unsigned char> anyhow ?

**Comment by wing328** [comment]
@tzickel thanks for reporting the issue.

cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

**Comment by etherealjoy** [comment]
@tzickel 
Thanks for the hint, I had a look at it, and for different platforms we could leave the handling of the httpcontent as is because the underlying stream is quite different.
