### ISSUE TITLE
[BUG][Java][spring][webclient] webclient metrics contains actual query parameters, resulting in OOM

### ISSUE THREAD

**Issue by cdmatta** [OpenAPITools/openapi-generator#7899]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generate the spring webclient implementation for an open api endpoint which is using query parameters.
Use the generated ApiClient to make calls to the endpoint with different query parameters in a spring webflux application (with micrometer metrics).

Check the uri tag for the metric http_client_requests.
This uri tag contains the query parameter. This will continue to grow as different values are used.
Eventually, leading to an OutOfMemory error.

##### openapi-generator version

openapi-generator version: 4.3.1

This is not a regression.

##### OpenAPI declaration file content or url

This can be reproduced with the sample petstore fake endpoints yaml file in the project

[/fake/body-with-query-params](https://github.com/OpenAPITools/openapi-generator/blob/9377dbca56afcc32901262e94ba4d7af4379ba94/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L939-L949)

##### Steps to reproduce

1. Generate the spring webclient implementation for the yaml
2. Use it in a Spring boot project with actuator and metrics
3. Call the endpoint with query parameters

Actual

- Query parameter values are present in the http_client_requests metric
![Screenshot from 2020-11-08 13-17-35](https://user-images.githubusercontent.com/1005989/98463579-df624c80-21c4-11eb-8077-0f187b0e63a9.png)

Expected

- Query parameters values *must* not be present in the metrics.

##### Suggest a fix

Solution for this is available in [spring framework 5.2 webclient](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.UriSpec.html#uri-java.lang.String-java.util.function.Function-)

I could provide a PR, but that means the minimum required version of spring framework will be 5.2.
Or, we need to make rules in the template to add the following code on spring 5.2+ only, hence leaving it for you to decide.

Here is the fix to the ApiClient.mustache template required to fix this. [webclient-ApiClient.patch.txt](https://github.com/OpenAPITools/openapi-generator/files/5506223/webclient-ApiClient.patch.txt)

```diff
diff --git a/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache b/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
index 98f4bfb2..080b6fbd 100644
--- a/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
+++ b/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache
@@ -564,11 +564,13 @@ public class ApiClient{{#java8}} extends JavaTimeFormatter{{/java8}} {
         updateParamsForAuth(authNames, queryParams, headerParams, cookieParams);
 
         final UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(basePath).path(path);
-        if (queryParams != null) {
-            builder.queryParams(queryParams);
-        }
 
-        final WebClient.RequestBodySpec requestBuilder = webClient.method(method).uri(builder.build(false).toUriString(), pathParams);
+        final WebClient.RequestBodySpec requestBuilder = webClient.method(method).uri(builder.build(false).toUriString(), uriBuilder -> {
+            if (queryParams == null) {
+                return uriBuilder.build(pathParams);
+            }
+            return uriBuilder.queryParams(queryParams).build(pathParams);
+        });
         if(accept != null) {
             requestBuilder.accept(accept.toArray(new MediaType[accept.size()]));
         }
```

**Comment by admoca60** [comment]
> 👍 Thanks for opening this issue!
> 🏷 I have applied any labels matching special text in your issue.
> 
> The team will review the labels and make any necessary changes.

Maybe the right label should be "Client: Spring" because this affect to the client. The client can be used in a Server (with Spring obviously) or in Batch process.

**Comment by admoca60** [comment]
Dear @cdmatta 
You have suggested that the query parameters should be removed from uriTag, but in my opinion, that should't be so.
Maybe, the best approach could be create a uriTag with queryParams parametrized as path params.

For example, the path  "/cars". That resource can be queried by one or two queryParams, the "color" or the "model" and the operation is different in each case.
Taking previous example, this is a relationshipt between the request and the uriTag proposed.

URI REQUEST           -----------------------> URI TAG
/cars?color=black    -----------------------> /cars?color={colorParamValue}
/cars?color=white    -----------------------> /cars?color={colorParamValue}
/cars?color=blue    -----------------------> /cars?color={colorParamValue}
/cars?model=ford    ----------------------->/cars?model={modelParamValue}
/cars?model=seat&color=yellow ----------------------->/cars?model={modelParamValue}&color={colorParamValue}


The first three request go to the same "uriTag".

What do you think about it?

**Comment by cdmatta** [comment]
Definitely, having the query parameter templatized for metrics would be a good thing.

In my experience of using spring webclient + metrics, I only had 2 options

1. Drop query parameters from metrics, like the example patch above.
1. Follow the below mechanism to get the templatized url.

The only way to get the url template with query parameters in metrics was, to use this api call, setting up everything by hand.
```java
webclient.method(method).uri("/cars/{id}?feature={featureValue}", "toyota", "automatic")
```

As you can see above, this requires custom parameters for the api call. Given that the api can have more than a few parameters + can also contain array parameters (which I have not used, thus cannot comment on what is needed for its support), one can see how it quickly becomes unwieldy in the generator

The generator template had a [single entry point for the webclient call](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/webclient/ApiClient.mustache#L571).

This means the generator need to generate code for each such combination of query parameters accounting for these challenges.

**Comment by admoca60** [comment]
> This means the generator need to generate code for each such combination of query parameters accounting for these challenges.

Yes, I'm aware of that, but it could be easy to do. In runtime, the ApiClient can generate the queryParams templatized string and append it to base url. The generator has the parameter "MultiValueMap<String, String> queryParams" which can be used to build this "queryParams uri templatized string". In fact, is the same behaviour that Spring does when we use "builder.queryParams(queryParams);"

What do you think?

**Comment by cdmatta** [comment]
Sure, generating the templatized url is not the challenge IMHO.

Passing the query parameters is. Last I tried the builder did not lend itself to supporting query parameters with templates.

The [varargs mechanism in my previous comment](https://github.com/OpenAPITools/openapi-generator/issues/7899#issuecomment-737336907) was the only way I got the metrics to work correctly for query parameters with uri templates. Either standalone or inside uriBuilder

```java
webclient.method(method).uri("/cars/{id}?feature={featureValue}", "toyota", "automatic")
// OR
webclient.method(method).uri("/cars/{id}?feature={featureValue}", builder -> builder.build("toyota", "automatic"))
```

**Comment by admoca60** [comment]
Did you test with this?

`webclient.method(method).uri("/cars/{id}?feature={featureValue}", uriMapParameters)`

We can include the pathParams and queryParams in the same map `Map<String, Object> pathParams`, so in that case the code could do that:

```
   final UriComponentsBuilder builder = UriComponentsBuilder.fromHttpUrl(basePath).path(path);
      String finalUri = builder.build(false).toUriString();
      Map<String,Object> uriParams = new HashMap();
      uriParams.putAll(pathParams);
      
       if (queryParams != null) {
           //Include queryParams in uriParams taking into account the paramName
          //Append to finalUri the templatized query string like "?param1={param1Value}&.......
        }

        final WebClient.RequestBodySpec requestBuilder = webClient.method(method).uri(finalUri, uriParams );
```

**Comment by cdmatta** [comment]
Oh forgot that one. Yes, that works. Indeed then it is fairly easy to get that working in the generator.

**Comment by admoca60** [comment]
I'm realised that for RestTemplate happends the same: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/ApiClient.mustache#L606

But in that case the approach to fix it is sligtly different. In the custom api client this [line ](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/resttemplate/api.mustache#L113) is executed before Invoke method in ApiClient, so the right solution here should be generate the templatized path (with queryParams) before that line. In addition of that, the invokeMethod parameters should also change to exclude "queryParams" because they would be included in the global "uriParams" map.

**Comment by admoca60** [comment]
Maybe, the case of RestTemplate should be in another different issue. What do you think @wing328 ?

Can anybody generate a PR to solve this (webclient) fix?

**Comment by jorgerod** [comment]
Hi @admoca60 @cdmatta 
I can contribute for fix this issue.

**Comment by admoca60** [comment]
Go ahead!! Maybe your solution could be very familiar for me!!! xD
