### ISSUE TITLE
Python client broken when using `oneOf` in the specification

### ISSUE THREAD

**Issue by CarstenLeue** [OpenAPITools/openapi-generator#7915]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I would like to create a python client based on an open api specification that uses the `oneOf` keyword to describe the payload. 

It turns out that the generated client is unusable because it will fail client side validation of the input. Disabling client side validation does not help either, because the `oneOf` construct is also used for the response content and there is no way to disable validation for responses. 

The problem is that the generated code requires values for **all** alternatives of the `oneOf` variation, not just one. So it has the semantic of `allOf` instead of `oneOf`. 

##### openapi-generator version

```
v4.3.1
```

via its docker wrapper

```
openapitools/openapi-generator:cli-v4.3.1
```

##### OpenAPI declaration file content or url

Minimal sample to reproduce the error:

```json
{
  "openapi": "3.0.2",
  "info": {
    "title": "Test Spec",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://example.com"
    }
  ],
  "paths": {
    "/test": {
      "post": {
        "operationId": "test",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Sample"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "sample",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Sample"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Sample": {
        "oneOf": [
          { "$ref": "#/components/schemas/Value1" },
          { "$ref": "#/components/schemas/Value2" }
        ]
      },
      "Value1": {
        "properties": {
          "content1": {
            "type": "string"
          }
        },
        "required": ["content1"],
        "type": "object"
      },
      "Value2": {
        "properties": {
          "content2": {
            "type": "string"
          }
        },
        "required": ["content2"],
        "type": "object"
      }
    }
  }
}
```
(for JSON code), so it becomes more readable. If it is longer than about ten lines,
please create a Gist (https://gist.github.com) or upload it somewhere else and
link it here.
  -->

##### Generation Details

```bash
docker run -it --rm -v "%cd%:/local" openapitools/openapi-generator:cli-v4.3.1 generate -i /local/spec.json -g python -o /local/build 
```

##### Steps to reproduce

Run this to produce the project

```bash
docker run -it --rm -v "%cd%:/local" openapitools/openapi-generator:cli-v4.3.1 generate -i /local/spec.json -g python -o /local/build 
```

edit the generated testcase `build/test/test_sample.py`: 

before:

```python
    def make_instance(self, include_optional):
        """Test Sample
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.sample.Sample()  # noqa: E501
        if include_optional :
            return Sample(
                content1 = '0', 
                content2 = '0'
            )
        else :
            return Sample(
                content1 = '0',
                content2 = '0'
        )
```

after

```python
    def make_instance(self, include_optional):
        """Test Sample
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.sample.Sample()  # noqa: E501
        if include_optional :
            return Sample(
                content1 = '0', 
            )
        else :
            return Sample(
                content1 = '0',
        )
```

According to the schema **either** `content1` or `content2` may be specified but not both. So the originally produced testcase was already incorrect.
The fixed testcase however breaks, because the generated `Sample` model requires both values to be set. 

The actual error message when running the fixed test is

```
ValueError: Invalid value for `content2`, must not be `None`
```

##### Suggest a fix

I have no deeper understanding of the model generator but it appears to me that the approach to validate the model in the setters is not valid for this case because the validation has a dependency on the value for another property, that could be set independently. It would be more promising to do input validation on the serialized model right before it gets sent to the REST service.

**Comment by wing328** [comment]
Please try the `python-experimental` generator in the latest master, which has better support for oneOf, anyOf, etc

**Comment by Carsten-Leue** [comment]
hmm, but `python-experimental` produces completely different client code, with different model imports etc.

**Comment by lsaavedr** [comment]
I have the same problem and with `-g python-experimental`:

```
[main] WARN  o.o.c.languages.PythonClientCodegen - Type null not handled properly in toExampleValue
Exception in thread "main" java.lang.RuntimeException: Could not process model 'NullEnum'.Please make sure that your schema is correct!
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:496)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:1005)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:431)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
Caused by: java.lang.NullPointerException
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValueRecursive(PythonClientCodegen.java:736)
	at org.openapitools.codegen.languages.PythonClientCodegen.toExampleValue(PythonClientCodegen.java:703)
	at org.openapitools.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:2846)
	at org.openapitools.codegen.languages.PythonClientExperimentalCodegen.fromProperty(PythonClientExperimentalCodegen.java:429)
	at org.openapitools.codegen.languages.PythonClientExperimentalCodegen.fromModel(PythonClientExperimentalCodegen.java:810)
	at org.openapitools.codegen.DefaultGenerator.processModels(DefaultGenerator.java:1289)
	at org.openapitools.codegen.DefaultGenerator.generateModels(DefaultGenerator.java:491)
```

**Comment by spacether** [comment]
The client generates without issue using the latest `python` generator. That generator includes composition support.
