### ISSUE TITLE
[BUG] [Maven] [Java] requestBodies component with multipart content type UNKNOWN_BASE_TYPE

### ISSUE THREAD

**Issue by tonymurphy** [OpenAPITools/openapi-generator#7922]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

using a '#/components/requestBodies/..' definition for binary file upload doesn't work. requestBody has to be inlined 

more details... https://stackoverflow.com/questions/64774051/open-api-maven-plugin-how-to-generate-code-for-file-upload/64784370#64784370

##### openapi-generator version

```               
               <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.3.0</version>
```

##### OpenAPI declaration file content or url

```
openapi: 3.0.0
info:
  version: 3.0-SNAPSHOT
  title: Demo broken file upload code generation
tags:
  - name: image
    description: Image API
paths:
  "/image":
    post:
      tags:
        - image
      summary: upload images
      operationId: uploadImages
      requestBody:
        $ref: '#/components/requestBodies/FilesUploadRequest'
      responses:
        "201":
          $ref: '#/components/responses/ImagesResponse'

components:
  requestBodies:
    FilesUploadRequest:
      description: Array of files
      content:
        multipart/form-data:
          schema:
            type: object
            properties:
              files:
                type: array
                items:
                  type: string
                  format: binary
  responses:
    ImagesResponse:
      description: Images Uploaded
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Images"
  schemas:
    Images:
      type: object
      properties:
        images:
          type: array
          items:
            $ref: "#/components/schemas/Image"
    Image:
      type: object
      properties:
        id:
          type: integer
          format: int64
        size:
          type: string
        thumbnailUrl:
          type: string
        url:
          type: string

```

##### Generation Details

I created a repo on github to reproduce 

https://github.com/tonymurphy/imageapi

```
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <version>4.3.0</version>
                <executions>
                    <execution>
                        <id>generate-api-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                            <language>java</language>
                            <output>${project.build.directory}/generated-sources</output>
                            <library>feign</library>
                            <configOptions>
                                <dateLibrary>java8</dateLibrary>
                            </configOptions>
                            <generateApiTests>false</generateApiTests>
                            <generateModelTests>false</generateModelTests>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
##### Steps to reproduce

``` mvn clean install ```

##### Suggest a fix

workaround is to not use a component $ref, inline the requestBody

**Comment by wing328** [comment]
@tonymurphy thanks for the issue details and the workaround. I've filed a PR to improve the error message: https://github.com/OpenAPITools/openapi-generator/pull/8493

I wonder if you can report the issue to https://github.com/swagger-api/swagger-parser as it seems to be an issue with how Swagger Parser handles reference schemas.

**Comment by rockymontana** [comment]
> ##### Suggest a fix
> 
> workaround is to not use a component $ref, inline the requestBody

Unfortunately if you're using the schema to generate TypeScript for communication layer to the backend (we generate both the Java client and a TypeScript client because our backend communicates with another service) it'll generate an InlineObject0<number> if you inline the request body. If you don't you'll get this. And defining requestBodies in schemas seems wrong when there's both a requestBodies and responses section for OpenAPI.

**Comment by dlkj** [comment]
I've dug into this a little. swagger-parser is parsing requestBodies ref correctly but it looks like a bug in DefaultCodegen failing to get a request body by reference in some code paths. A cursory review indicates that some generators may have similar issues. I may have some time later to investigate into this further, but for anyone else who would like to try to fix it take a look at https://github.com/OpenAPITools/openapi-generator/blob/d2b80984ed910a51f029346b005ab4620ccb2786/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L4067

I think it should be:

`RequestBody requestBody = ModelUtils.getReferencedRequestBody(openAPI, operation.getRequestBody());`

While this is annoying it's not currently on my critical path.

**Comment by wing328** [comment]
Fixed in the latest master. Please pull the latest to give it another try. You will need to set `skipFormModel=false`, e.g.
```
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g java --library feign -i https://raw.githubusercontent.com/tonymurphy/imageapi/main/src/main/resources/api.yaml -o /tmp/feign/ --global-property skipFormModel=false
```
