### ISSUE TITLE
[BUG] [PYTHON][securitySchemes:jwtAuth] 'Configuration' object has no attribute 'access_token'

### ISSUE THREAD

**Issue by lsaavedr** [OpenAPITools/openapi-generator#7929]
#### Bug Report 
- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
In Configuration class its needed define `self.access_token = None` in `__init__` function to use it in `auth_settings` function, without this its was generated  an error:

```
Traceback (most recent call last):
  File "src/test.py", line 13, in <module>
    ok = api.organizacion_activos_list()
  File "/home/jidj85/envpi/lib/python3.7/site-packages/smi/api/organizacion_api.py", line 338, in organizacion_activos_list
    return self.organizacion_activos_list_with_http_info(**kwargs)  # noqa: E501
  File "/home/jidj85/envpi/lib/python3.7/site-packages/smi/api/organizacion_api.py", line 444, in organizacion_activos_list_with_http_info
    _request_auth=local_var_params.get('_request_auth'))
  File "/home/jidj85/envpi/lib/python3.7/site-packages/smi/api_client.py", line 381, in call_api
    _request_auth)
  File "/home/jidj85/envpi/lib/python3.7/site-packages/smi/api_client.py", line 170, in __call_api
    request_auth=_request_auth)
  File "/home/jidj85/envpi/lib/python3.7/site-packages/smi/api_client.py", line 559, in update_params_for_auth
    auth_setting = self.configuration.auth_settings().get(auth)
  File "/home/jidj85/envpi/lib/python3.7/site-packages/smi/configuration.py", line 423, in auth_settings
    if self.access_token is not None:
AttributeError: 'Configuration' object has no attribute 'access_token'
```
##### openapi-generator version
openapi-generator-cli-5.0.0-20201112.170402-866.jar

##### OpenAPI declaration file content or url
https://smi.enerlink.cl/api/schema

##### Generation Details
```console
jidj85@~$ java -jar openapi-generator-cli-5.0.0-20201112.170402-866.jar generate \
  -i https://smi.enerlink.cl/api/schema/ \
  --package-name smi \
  -g python \
  -o smi
```

##### Steps to reproduce

```console
jidj85@~$ pip3 install smi/
jidj85@~$ python
>>> from smi import Configuration
>>> from smi.api_client import ApiClient
>>> from smi.api.organizacion_api import OrganizacionApi
>>> conf = Configuration(host='https://smi.enerlink.cl')
>>> api = OrganizacionApi(ApiClient(conf))
>>> ok = api.organizacion_activos_list()
```
##### Related issues/PRs
None

##### Suggest a fix
In Configuration class its needed define `self.access_token = None` in `__init__` function to use it in `auth_settings` function

**Comment by spacether** [comment]
Note: this is for:
```
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: Bearer
```
Which is probable `{{#isBasicBearer}}` here:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/python/configuration.mustache#L508

**Comment by spacether** [comment]
This was fixed by https://github.com/OpenAPITools/openapi-generator/pull/7469
