### ISSUE TITLE
[OAS 3.0.0] Variables in "servers" object 

### ISSUE THREAD

**Issue by TiFu** [OpenAPITools/openapi-generator#793]
##### Description

The generator currently produces the following output for `-DdebugSupportingFiles`:

```
"servers" : [ {
      "url" : "http://petstore.swagger.io:{port}/{basePath}",
      "description" : "The production API server",
      "variables" : {
        "port" : {
          "default" : "8443",
          "enum" : [ "8443", "443" ]
        },
        "basePath" : {
          "default" : "v2"
        }
      }
    } ],
```
for the following input:

```
openapi: 3.0.0
servers:
  - url: 'http://petstore.swagger.io:{port}/{basePath}'
    description: The production API server
    variables:
      port:
        enum:
          - '8443'
          - '443'
        default: '8443'
      basePath:
        default: v2
```
([full spec](https://gist.github.com/TiFu/086608e56d01c685e03a275e72557314)

AFAIK mustache does not allow iterating objects (Correct me if I'm wrong - I tried a lot of different combinations and couldn't get it to work). 
This is problematic because the entries of `variables` are user defined, so they can't be referenced in the template by hardcoding variable names.

Problem Example:
I wanted to write a template which generates a class for each server with one setter per variable e.g. `setBasePath(path: string)` and `setPort(port: 8443 | 443)`

##### Command line used for generation

`-DdebugSupportingFiles` with any language.

##### Suggest a fix/enhancement
Change the variables object to an array of objects, each containing a `name` property.
```
"servers" : [ {
      "url" : "http://petstore.swagger.io:{port}/{basePath}",
      "description" : "The production API server",
      "variables" : [
              {
               "name": "port",
               "default" : "8443",
               "enum" : [ "8443", "443" ]
        },
        {    
             "name": "basePath",
             "default" : "v2"
        }
      ]
    } ],
```

**Comment by wing328** [comment]
It's not supported and a good starting point is [URLPathUtils.java#L43-L51](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L43-L51)

[L50](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/URLPathUtils.java#L50) returns only the first "server".

We probably need to add another function "getServers" to return an array of hash and make these values available to the mustache.

**Comment by jmini** [comment]
There are 2 related topic

* Without using variables, you can define multiple servers
* When using variables, with the combination of possible value in the enum, you can derive multiple server URL from one server declaration (see discussion in #592)

And of course the 2 topics can be combined.

The problem is that none of the generators can do something with multiple servers... And some of them also accept input as parameter (to override what is present in the spec).

But of course we should support this OAS3 feature.

**Comment by TiFu** [comment]
I thought about this mainly because I'm rewriting the typescript generators and am designing them so that variables can be supported quite easily.
