### ISSUE TITLE
[JAVA MAVEN PLUGIN] Is it possible to use already existing DTO's?

### ISSUE THREAD

**Issue by sblumenstock-doubleSlash** [OpenAPITools/openapi-generator#7947]
I'm using the OpenApi Maven Generator Plugin to generate a client for my server. Is it possible to use custom already existing DTO's in this automatic generation?
Can I specify the location, where the already existing DTO's are located?

**Comment by agilob** [comment]
Yes, you add a property like:

```
        member:
          type: Member
```

and then in 

generator settigns
something like this:

```
openApiGenerate {
    importMappings = [
        MemberDTO:"net.agilob.dto.Member"
    ]
}
```

Above is an example from gradle, so you need to convert it to maven syntax. Generated code will use static inline imports for the mapped imports.

**Comment by agilob** [comment]
Please next time use stackoverflow for such question and close this issue.
