### ISSUE TITLE
[BUG][typescript-axios] Multi-value query params are incorrectly encoded as a comma separated string

### ISSUE THREAD

**Issue by sambernard** [OpenAPITools/openapi-generator#7966]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The generated code improperly converts query list params to comma-separated strings.

If passing an array to a query param - eg `include=["relation_1", "relation_2"]` I expect it would output `include=relation_1&include=relation_2` in the query string. Instead, it returns `include=relation_1,relation_2`.

##### openapi-generator version

* `5.0.0-beta2`

##### OpenAPI declaration file content or url

If you post the code inline, please wrap it with
```yaml
info:
  title: API
  version: 1.0.0
openapi: 3.0.0
paths:
  /some-resource:
    get:
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: string
                type: object
      parameters:
        - in: query
          name: include
          required: false
          schema:
            default: []
            type: array
            items:
              enum:
                - relation_1
                - relation_2
              type: string
```
##### Generation Details

Use [typescript-axios] with default options.

```yaml
generatorName: typescript-axios
```

##### Steps to reproduce

1. Run generator
2. Call `await DefaultApiAxiosParamCreator().someResourceGet(["relation_1", "relation_2"])`.
3. Observe that called url has `include=relation_1,relation_2` in the querystring.

##### Suggest a fix
The problematic code is here:

https://github.com/OpenAPITools/openapi-generator/blob/v5.0.0-beta2/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L191-L194

```typescript
const localVarQueryParameter = {} as any;

if (include) {
    localVarQueryParameter['include'] = include;
}

const query = new URLSearchParams(localVarUrlObj.search);
for (const key in localVarQueryParameter) {
    query.set(key, localVarQueryParameter[key]);
}
```

This line `query.set(key, localVarQueryParameter[key]);`  converts the second argument to a string, so the array gets converted to `relation_1,relation_2`.

The proper approach would be to check if the value of the given `localVarQueryParameter` is an array, and if so, to loop over it and append, eg:

```
for (const key in localVarQueryParameter) {
    if(Array.isArray(localVarQueryParameter[key])) {
        localVarQueryParameter[key].forEach(v => {
            query.append(key, v)
        })
    } else {
        query.set(key, localVarQueryParameter[key]);
    }
}
```

**Comment by dantman** [comment]
The code uses `new URLSearchParams(localVarUrlObj.search);` which means `include` could already have a value. To avoid incorrectly merging values I'd recommend adding `query.delete(key);` before the `forEach`.

We might as well also do the same thing to the `for (const key in options.query) {` code.

**Comment by arnaud-cortisse** [comment]
What's the status?

**Comment by arnaud-cortisse** [comment]
Would it also make sense to do something like this?
```
if (include) {
    localVarQueryParameter['include[]'] = include;
}
```
(pay attention to "[]" appended to "include" in the key). 

That way, even an array with a single element would be considered as an array in major frameworks such as NestJS. 
Otherwise, the array is parsed as a string if it only contains 1 element, which would make things less predictable.

**Comment by dantman** [comment]
@arnaud-cortisse That's a spec thing, not a generator issue. Doing that in the generator would make it behave incorrectly.

I think you're supposed to just include the `[]` in the OpenAPI file if that's needed.

**Comment by Lakkanna** [comment]
Hi, I'm facing still this similar issue in POST method, is this fix works for POST method too?

**Comment by vanwagenenj** [comment]
Is there a way to specify that you want an array to be sent as a single query param?
