### ISSUE TITLE
[BUG][typescript-angular] Generating client library with ngVersion=10.2 

### ISSUE THREAD

**Issue by DmytroMysak** [OpenAPITools/openapi-generator#8013]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generator typescript-angular delivers incompatible versions for Angular 10.x in package.json. This causes npm run build to fail.

New dependencies in Angular Compiler requires TypeScript >=4.0.0 and <4.1.0.

##### openapi-generator version

v4.3.1 / The last stable version of OpenAPITools/openapi-generator using [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli)

##### OpenAPI declaration file content or url

 Example: https://github.com/OAI/OpenAPI-Specification/edit/master/examples/v3.0/petstore.yaml

##### Command line used for generation
`openapi-generator-cli generate -i petstore.yaml -g typescript-angular -o petstore --additional-properties="npmName=petstore,npmVersion=0.9.0,withInterfaces=true,providedInRoot=true,ngVersion=10.2.0"`

##### Steps to reproduce

    

- Run the command to generate the output (see above)
- Install the dependencies npm install, which creates these warnings:

![image](https://user-images.githubusercontent.com/22196591/100093529-556ee080-2e60-11eb-87ee-013f7c14c352.png)
- Run npm run build and error in result:
**ERROR: The Angular Compiler requires TypeScript >=3.9.2 and <4.1.0 but 3.7.5 was found instead.**

![image](https://user-images.githubusercontent.com/22196591/100093644-7f280780-2e60-11eb-952a-74425e61994e.png)

Expected result:
![image](https://user-images.githubusercontent.com/22196591/100094308-7be14b80-2e61-11eb-8231-7ab8a44b123f.png)

##### Suggest a fix

Update typescript version in package.json from "typescript": ">=3.6.0 <3.8.0", to "typescript":  ">=3.9.2 <=4.1.0"

**Comment by macjohnny** [comment]
this is already implemented and will be released in version 5.0.0. it is already part of version 5.0.0-beta3

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/client/petstore/typescript-angular-v10-provided-in-root/builds/with-npm/package.json#L19-L28
