### ISSUE TITLE
[REQ] Java MicroPofile Rest client with Jackson serialization?

### ISSUE THREAD

**Issue by hrstoyanov** [OpenAPITools/openapi-generator#8015]
### Is your feature request related to a problem? Please describe.

Quarkus, an up-and-coming Java Microprofile implementation will soon allow users to use JAX-RS with Jackson, instead of the standard JSONB as discussed [here](https://groups.google.com/g/quarkus-dev/c/RTnvH6LSdxs)

Currently this generator cannot generate Microprofile rest client code  based on JAX-RS+jackson code. I tried this (in my Gradle):
```
   ...
    openApiGenerate {
        generatorName = "java"       
        configOptions = [
                dateLibrary: "java8",
                java8: "true",
                library:"microprofile",
                serializationLibrary:"jackson"
        ]
     
    }
```
but the generated code is still JAX-RS/JSONB, not JAX-RS/Jackson

## Describe the solution you'd like

This should do the trick:
```
 openApiGenerate {
        generatorName = "java"       
        configOptions = [
                ...
                library:"microprofile",
                serializationLibrary:"jackson"
        ]
```

**Comment by jtnord** [comment]
this had me confused for a while as the [docs](https://github.com/OpenAPITools/openapi-generator/blame/39f0177ede6ade8a7511d77bf97384294cbe32f2/docs/generators/java.md#L39) say if using `library` = `microprofile` then the json processing is "JSON processing: Jackson 2.9.x"

**Comment by najibk** [comment]
It would be nice to address this 6 month old issue. is there any way to use jackson with microprofile rest client ?

**Comment by plevart** [comment]
My workarround currently is to configure two executions of openapi-generator-maven-plugin. The 1st execution generates just the model classes and I configure it with say "native" client which by default selects Jackson serialization, while the 2nd execution generates just the Api classes (interfaces). So it shouldn't be to hard to implement this combo in one execution, I think...

**Comment by lostiniceland** [comment]
> My workarround currently is to configure two executions of openapi-generator-maven-plugin. The 1st execution generates just the model classes and I configure it with say "native" client which by default selects Jackson serialization, while the 2nd execution generates just the Api classes (interfaces) which I configure to use "microprofile" client. The resulting classes compile correctly and the client works. So it shouldn't be to hard to implement this combo in one execution, I think...

Unfortunately in this case, the generated code has a dependency on Swagger-Annotations instead of Microprofile-Annotations.

So it would be nice if the generator would support using Jackson instead of JSONB (which currently is very frustrating when you want to use Java 17 records)

**Comment by plevart** [comment]
> 
> Unfortunately in this case, the generated code has a dependency on Swagger-Annotations instead of Microprofile-Annotations.
> 
> So it would be nice if the generator for microprofile would support using Jackson instead of JSONB (which currently is very frustrating when you want to use Java 17 records)

The API classes (interfaces) are generated for "microprofile" client, so they are annotated with microprofile (RegisterProvider, RegisterRestClient) and JAX-RS (Path, GET, POST, ...) annotations. Generated classes also specify a wildcard include for `org.apache.cxf.jaxrs.ext.multipart.*`, but I've never seen any annotation used from that package, so I specify the dependency as "optional". These are the dependencies I use in such maven API module:

```XML
        <dependency>
            <groupId>org.jboss.spec.javax.ws.rs</groupId>
            <artifactId>jboss-jaxrs-api_2.1_spec</artifactId>
        </dependency>

        <dependency>
            <groupId>org.eclipse.microprofile.rest.client</groupId>
            <artifactId>microprofile-rest-client-api</artifactId>
        </dependency>

        <dependency>
            <groupId>org.apache.cxf</groupId>
            <artifactId>cxf-rt-frontend-jaxrs</artifactId>
            <optional>true</optional>
        </dependency>
```

 The model classes get a mix of Jackson, Swagger and Findbugs (jsr305) annotations. In runtime, only Jackson annotations are needed so other dependencies can be specified as "optional" in pom.xml If you can do without them at runtime (you are not using Swagger GUI for example), and they won't be included in the app. I use the following in pom.xml for such maven model module:
 
 ```XML
         <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-annotations</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>
```
 
 Are there any other annotations you would like to be present? Where? In the API or model classes?

I agree that it would be nice to have proper support for microprofile/Jackson combo so these workarounds would not be necessary.

**Comment by jonsalvas** [comment]
I would also be interested in this. We are generating our sources for Quarkus and JSONB is too restricted for our use cases. Any updates?

**Comment by melloware** [comment]
+1 for this as well

**Comment by ssaip** [comment]
> Generated classes also specify a wildcard include for org.apache.cxf.jaxrs.ext.multipart.*, but I've never seen any annotation used from that package, so I specify the dependency as "optional"

It looks like there was a property planned to remove these imports, but its neither documented nor implemented:
```
{{^disableMultipart}}
import org.apache.cxf.jaxrs.ext.multipart.*;
{{/disableMultipart}}
```

**Comment by jonsalvas** [comment]
I know this thread is old, but maybe I can help someone who is desperate as I was. I can confirm @plevart 's workaround is working. To avoid having the multipart annotations being generated you can add the additionalProperty disableMultipart

<additionalProperties>disableMultipart="true"</additionalProperties>
