### ISSUE TITLE
[REQ] Will the 5.0 final release include a server-stub generator for C# .NET 5?

### ISSUE THREAD

**Issue by KenCollins-Skkynet** [OpenAPITools/openapi-generator#8017]
The current 'aspnetcore' generator is not compatible with .NET 5. Specifically, the definition of the Filter 'Apply' method now expects an OpenApiDocument instead of a SwaggerDocument. I'm sure there are other improvements that can be added. Nonetheless, it would be nice to have a C# ASP.NET Core .NET 5 server-stub generator. Of course, I know I can create a custom template, but I'd rather not go down that path if something is already in work. Thanks.

**Comment by wing328** [comment]
We want to make the aspnetcore generator compatible with .NET 5
```
	aspnetCoreVersion
	    ASP.NET Core version: 3.1, 3.0, 2.2, 2.1, 2.0 (deprecated) (Default: 2.2)

```

Is that something you can help with? I can show you some good starting points to begin with.

**Comment by KenCollins-Skkynet** [comment]
Hi William.

I was hoping someone else had already done the work.
:-)

Sorry, I cannot commit; however, if I decide to create a custom template for my own project, I’ll consider contributing that solution. My priority is my current project.

**Comment by wing328** [comment]
No problem. Let's wait to see if someone from the community has the time to make the contributions.

Of course, you're welcome to sponsor the enhancement to make it a higher priority :)

**Comment by KenCollins-Skkynet** [comment]
Noted. Thanks William.
:-)

FYI: We’ve decided to start by creating a custom solution (per https://openapi-generator.tech/docs/customization/). Once we have that working, we can decide whether to contribute to the OpenAPI Generator project.
                ...Ken

**Comment by etherealjoy** [comment]
@KenCollins-Skkynet 
To make it work with .NET 5 you have to select the framework version. Default .NET Core framework in the tool is 2.1 which is not compatible with .NET 5.
`--additional-properties targetFramework=netcoreapp3.0`
.NET Core 3.1 is compatible with .NET 5

**Comment by KenCollins-Skkynet** [comment]
Yes...I recently figured that out. Thank you!
                ...Ken
