### ISSUE TITLE
[JavascriptFlowtyped] snapshot property

### ISSUE THREAD

**Issue by SixYearsInFebruary** [OpenAPITools/openapi-generator#803]
```
if (additionalProperties.containsKey(SNAPSHOT) && Boolean.valueOf(additionalProperties.get(SNAPSHOT).toString())) {
     this.setNpmVersion(npmVersion + "-SNAPSHOT." + SNAPSHOT_SUFFIX_FORMAT.format(new Date()));
}
```
If the version in pom.xml is x.x.x-SNAPSHOT, the config of openapi-generator-maven-plugin like below:
```
<additionalProperty>npmVersion=${project.version}</additionalProperty>
<additionalProperty>snapshot=true</additionalProperty>
```
the generate code in package.json will be x.x.x-SNAPSHOT-SHAPSHOT.yyyyMMddHHmm.
May be, if the version contains SNAPSHOT, should not append `-SNAPSHOT` to it again.

**Comment by wing328** [comment]
@SixYearsInFebruary thanks for reporting the issue. May I know if you've time to contribute the enhancement? Let me know if you need any help.

**Comment by SixYearsInFebruary** [comment]
@wing328 Sorry, I tried to clone the fork repo at home. But the network of Unicom is too slow. Behind of XX-Net, the clonw is also slow. Later, I will try to edit code in web browser IDE to fix. In addition, I had checked the current code, `x.x.x-SNAPSHOT-SNAPSHOT.yyyyMMddHHmm` is works for `^x.x.x-SNAPSHOT*` in package.json.

**Comment by wing328** [comment]
@SixYearsInFebruary please take your time. Just ping me if you need any help.

Thanks for offering help to improve this.
