### ISSUE TITLE
[BUG][SPRING] Reactive paramter ServerWebExchange's properties appear in Swagger-UI

### ISSUE THREAD

**Issue by stephanpelikan** [OpenAPITools/openapi-generator#8031]
##### Description

Building a reactive Spring service adds an additional Java parameter `ServerWebExchange exchange` which brings a long list of additional input parameters in the Swagger-UI:

![ServerWebExchange](https://user-images.githubusercontent.com/5190548/100360451-40798500-2ff9-11eb-96d2-db7e18b61f65.png)

##### Generation Details

pom.xml:

```<plugin>
  <groupId>org.openapitools</groupId>
  <artifactId>openapi-generator-maven-plugin</artifactId>
  ...
  <executions>
    <execution>
    ...
    <configuration>
      <generatorName>spring</generatorName>
      ...
      <configOptions>
        ...
        <reactive>true</reactive>
        ...
      </configOptions>
```

Actual output:

```java
default Mono<ResponseEntity<Void>> doSomething(
    @ApiParam(value = "" ,required=true )  @Valid @RequestBody Mono<Whatever> whatever,
    ServerWebExchange exchange) {
```

Expected output:

```java
default Mono<ResponseEntity<Void>> doSomething(
    @ApiParam(value = "" ,required=true )  @Valid @RequestBody Mono<Whatever> whatever,
    @ApiIgnore ServerWebExchange exchange) {
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/4273

##### openapi-generator version

4.3.1 and 5.0

##### Suggest a fix

Add annotation `@ApiIgnore` to the parameter.

**Comment by wing328** [comment]
Closed via https://github.com/OpenAPITools/openapi-generator/pull/8032
