### ISSUE TITLE
[BUG] [ruby] port `:-1` generated in configuration.rb

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [OpenAPITools/openapi-generator#8047]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In the case _no port_ is defined in the server's URL, in the generated `configuration.rb` file the `@host` variable would feature `:-1` as the port, which is of course invalid in a URL.

##### openapi-generator version

master @ cb1a620628

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: test api
  version: v1
servers:
  - url: https://hello-{stage}.world.{tld}{basePath}
    variables:
      stage:
        default: sandbox
      tld:
        default: net
      basePath:
        default: /v1
paths:
  /test:
    get:
      description: this is a test
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
```

##### Generation Details

```sh
openapi-generator generate -i port-openapi.yml -g ruby --library faraday -o ./port-client
```

##### Steps to reproduce

1. run the above command with the above openapi.yaml file
2. `cat port-client/lib/openapi_client/configuration.rb | grep -n hello-sandbox`
3. prints out: `137:      @host = 'hello-sandbox.world.net:-1'`

##### Related issues/PRs

- https://github.com/OpenAPITools/openapi-generator/pull/7464
- https://github.com/OpenAPITools/openapi-generator/pull/7531

@cliffano (2017/07) @zlx (2017/09) @autopp (2019/02) @wing328

**Comment by wing328** [comment]
@jfeltesse-mdsol thanks for the details. I'll take a look later today.

**Comment by wing328** [comment]
UPDATE: filed #8049 to fix it. Local tests using the spec you provided look good.
