### ISSUE TITLE
[BUG] Stackoverflow in toExampleValue()

### ISSUE THREAD

**Issue by fbl100** [OpenAPITools/openapi-generator#8052]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
Expected output is not crashing
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When processing recursive data structures, the PythonClientCodeGen throws a StackOverflowException in toExampleValue().

##### openapi-generator version

5.0.0-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  version: 01.01.00
  title: APITest API documentation.
  termsOfService: http://api.apitest.com/party/tos/
servers:
  - url: https://api.apitest.com/v1
paths:
  /geojson:
    post:
      summary: Add a GeoJson Object
      operationId: post-geojson
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                description: GeoJson ID
        '400':
          description: Bad Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeoJsonGeometry'
      parameters: []
components:
  schemas:
    GeoJsonGeometry:
      title: GeoJsonGeometry
      description: GeoJSON geometry
      oneOf:
        - $ref: '#/components/schemas/Point'
        - $ref: '#/components/schemas/GeometryCollection'
      discriminator:
        propertyName: type
        mapping:
          Point: '#/components/schemas/Point'
          GeometryCollection: '#/components/schemas/GeometryCollection'
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometry-objects
    Point:
      title: Point
      type: object
      description: GeoJSON geometry
      externalDocs:
        url: http://geojson.org/geojson-spec.html#id2
      properties:
        coordinates:
          title: Point3D
          type: array
          description: Point in 3D space
          externalDocs:
            url: http://geojson.org/geojson-spec.html#id2
          minItems: 2
          maxItems: 3
          items:
            type: number
            format: double
        type:
          type: string
          default: Point
      required:
        - type
    GeometryCollection:
      title: GeometryCollection
      type: object
      description: GeoJSon geometry collection
      required:
        - type
        - geometries
      externalDocs:
        url: http://geojson.org/geojson-spec.html#geometrycollection
      properties:
        type:
          type: string
          default: GeometryCollection
        geometries:
          type: array
          items:
            $ref: '#/components/schemas/GeoJsonGeometry'
```

##### Generation Details

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i [yaml file] -g python -o python-test

##### Steps to reproduce

java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -i [yaml file] -g python -o python-test

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/5229
https://github.com/OpenAPITools/openapi-generator/issues/7532
https://github.com/OpenAPITools/openapi-generator/issues/7861

##### Suggest a fix

Add a new Set<String> to the toExampleValueRecursive() method.  This set would represent the models that have already been processed.  When the modelName is already contained in this set, then the recursion can stop and an example value can be generated.  Otherwise, add the model to the set so that future calls can check for termination.

**Comment by fbl100** [comment]
@spacether I submitted a new PR as this one was closed when you merged the original.

**Comment by spacether** [comment]
New PR is at https://github.com/OpenAPITools/openapi-generator/pull/8326#issuecomment-754248387
