### ISSUE TITLE
[BUG] @JsonBproperty on getter instead of fields for JAVA MICROPROFILE

### ISSUE THREAD

**Issue by FuoriDiTesta** [OpenAPITools/openapi-generator#8056]
##### Description
Generating classes for JAVA MICROPROFILE language, i find out that the @JsonBProperty annotation are placed on the getter methods, not on the fields. As described in the Json Binding user guide,  @JsonbProperty can be placed

- on field, in this case it will affect serialization and deserialization
- on getter, in this case it will affect serialization only
- on setter, in this case it will affect deserialization only

This create some problems in case the fields name in the json are not the same generated (for example field-first in json will be translated in fieldFirst in java class). 

##### openapi-generator version

I using the maven plugin openapi-generator-maven-plugin in version 5.0.0-beta3

##### Suggest a fix
I do a test, changing the openapi-generator/modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache file, moving the 
```
{{^withXml}}
  @JsonbProperty("{{baseName}}")
  {{/withXml}}

```

from the getField method to the field declaration, just after the xml definition

```
{{#withXml}}
  @XmlElement(name="{{baseName}}"{{#required}}, required = {{required}}{{/required}})
{{/withXml}}
  {{^withXml}}
  @JsonbProperty("{{baseName}}")
  {{/withXml}}
{#description}}
 /**
   * {{{description}}}
  **/
{{/description}}
{{#isContainer}}
  private {{{datatypeWithEnum}}} {{name}}{{#required}} = {{{defaultValue}}}{{/required}}{{^required}} = null{{/required}};
{{/isContainer}}

```
And it seems to work. It's not possible to follow this approach?

**Comment by texag93** [comment]
I second this request. Here is the modified file from openapi-generator/modules/openapi-generator/src/main/resources/Java/libraries/microprofile/pojo.mustache
[pojo.mustache.zip](https://github.com/OpenAPITools/openapi-generator/files/6873846/pojo.mustache.zip)

**Comment by wing328** [comment]
The PR by @texag93 has been merged into the master.
