### ISSUE TITLE
[BUG][GO] Missing vendor extensions in inlined objects

### ISSUE THREAD

**Issue by mcdoker18** [OpenAPITools/openapi-generator#8064]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Initially, I found that custom Golang tags are not created for inlined objects. I use the `x-go-custom-tag` vendor extension for the tags.
But after some investigation in the source code, I found that InlineModelResolver doesn't copy vendor extensions, description, and a couple of other options from an inlined object to a new one.

##### openapi-generator version

The issue reproduces in both 4.3.1 and 5.0.0-beta3 versions.

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.2
info:
  version: "1.0.0"
  title: Test
paths:
  /config:
    get:
      tags:
        - test
      description: ""
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
components:
  schemas:
    Entity:
      type: object
      properties:
        string_field:
          x-go-custom-tag:
            - 'test:"true"'
          type: string
        object_field:
          x-go-custom-tag:
            - 'test:"true"'
          type: object
          properties:
            string_field:
              x-go-custom-tag:
                - 'test:"true"'
              type: string
        allOf_field:
          allOf:
            - $ref: "#/components/schemas/Entity2"
            - type: object
              x-go-custom-tag:
                - 'test:"true"'
        array_field:
          x-go-custom-tag:
            - 'test:"true"'
          type: array
          items:
            type: string
    Entity2:
      type: object
      properties:
        string_field:
          x-go-custom-tag:
            - 'test:"true"'
          type: string
```

##### Steps to reproduce

```bash
openapi-generator generate -g go -o output/go/ -i output/test.yaml --git-host=test --git-user-id=test --global-property models,debugModels=true --additional-properties=isGoSubmodule=false,packageName=dto,generateInterfaces=true,useOneOfDiscriminatorLookup=true,enumClassPrefix=true
```
Actual:
```go
type Entity struct {
       //...
	ObjectField *EntityObjectField `json:"object_field,omitempty"`
       //...
}
```

Expected:
```go
type Entity struct {
       //...
	ObjectField *EntityObjectField `json:"object_field,omitempty" test:"true"`
       //...
}
```

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/1125

##### Suggest a fix

If you confirm this bug, I'd like to push my fix.

**Comment by wing328** [comment]
Please give it another try with the latest master.

Thanks @katsuya for the PR.

**Comment by mcdoker18** [comment]
Thanks @wing328  and @katsuya !
