### ISSUE TITLE
[REQ] typescript-axios basePath to be passed as config

### ISSUE THREAD

**Issue by sahanatroam** [OpenAPITools/openapi-generator#8065]
### Is your feature request related to a problem? Please describe.
having to pass base path as a new parm where as you could simply pass the BASE_PATH as axios config
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L244

## Describe the solution you'd like
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-axios/apiInner.mustache#L244

Ideally we should change the line above to do the following
```
return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
  const axiosRequestArgs = {...localVarAxiosArgs.options, url: (basePath || configuration?.basePath) + localVarAxiosArgs.url};
  return axios.request(axiosRequestArgs);
};
```

**Comment by macjohnny** [comment]
would you like to implement this?

**Comment by sahanatroam** [comment]
Yeap, Let me give this a try today @macjohnny
