### ISSUE TITLE
[BUG][swift5] Comma missing when using allOf:

### ISSUE THREAD

**Issue by Pe-te** [OpenAPITools/openapi-generator#8071]
##### Description

When generating a Schema DEF that uses "allOf:" another Schema ABC, then there is a comma missing between the fields from DEF and those from ABC.

##### openapi-generator version

openapi-generator version
4.3.1

##### OpenAPI declaration file content or url

```yaml
    ABC:
      required:
        - jkl
        - mno
      properties:
        jkl:
          type: string
        mno:
          type: string
    DEF:
      allOf:
        - $ref: "#/components/schemas/ABC"
      type: object
      required:
        - pqr
      properties:
        pqr:
          $ref: "#/components/schemas/GHI"
    GHI:
      type: array
      items:
        type: integer
```

##### Generation Details

```
openapi-generator generate -g swift5 -i test1.yaml -o outputPath1
```

Generates it without the comma and whitespace:
```
public init(pqr: [Int]jkl: String, mno: String) {
```
Expected with comma and whitespace:
```
public init(pqr: [Int], jkl: String, mno: String) {
```

**Comment by wing328** [comment]
Can you please try the latest master or 5.0.0-beta3 to see if it's still an issue?

**Comment by Pe-te** [comment]
Yes, there's no comma problem when using this jar file, thanks!

https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/5.0.0-beta3/openapi-generator-cli-5.0.0-beta3.jar
