### ISSUE TITLE
[BUG][Go] Erroneous type assertion handling in client.mustache

### ISSUE THREAD

**Issue by fuxs** [OpenAPITools/openapi-generator#8072]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

func decode() in client.mustache does not handle type assertion correctly due to missing return command (row 418). 

https://github.com/OpenAPITools/openapi-generator/blob/634c4c09e46271c5baba28439f12424b562a5e34/modules/openapi-generator/src/main/resources/go/client.mustache#L397-L426

##### openapi-generator version
Master

##### Suggest a fix

Add a return to this line

https://github.com/OpenAPITools/openapi-generator/blob/634c4c09e46271c5baba28439f12424b562a5e34/modules/openapi-generator/src/main/resources/go/client.mustache#L418

**Comment by wing328** [comment]
@fuxs thanks for reporting the issue. Can you please file a PR with the suggested fix?
