### ISSUE TITLE
[PHP] DataType conversion discussion

### ISSUE THREAD

**Issue by ybelenko** [OpenAPITools/openapi-generator#808]
After a lot of thinking about what is perfect representation of Openapi Data Types in PHP.
I'm working on data mocking, so any examples of how fake data should look like are welcome.

### Openapi Data Types

| Common Name | Type | Format | Comments |
|---|---|---|---|
| integer | integer | int32 | signed 32 bits |
| long | integer | int64 | signed 64 bits |
| float | number | float |  |
| double | number | double |  |
| string | string |   |  |
| byte | string | byte | base64 encoded characters |
| binary | string | binary | any sequence of octets |
| boolean | boolean |   |  |
| date | string | date | As defined by full-date - [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) |
| dateTime | string | date-time | As defined by date-time - [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) |
| password | string | password | Used to hint UIs the input needs to be obscured. |

#### int32 and int64
Quote from [PHP doc](http://php.net/manual/en/language.types.integer.php):
> The size of an integer is platform-dependent, although a maximum value of about two billion is the usual value (that's 32 bits signed). 64-bit platforms usually have a maximum value of about 9E18, except on Windows prior to PHP 7, where it was always 32 bit. PHP does not support unsigned integers. Integer size can be determined using the constant PHP_INT_SIZE, maximum value using the constant PHP_INT_MAX since PHP 5.0.5, and minimum value using the constant PHP_INT_MIN since PHP 7.0.0.
```php
$int32 = 2147483647;
var_dump($int32); // int(2147483647)

$int64 = 9223372036854775807;
var_dump($int64); // int(9223372036854775807)
```
:question: How we should store `int64`? Should we store it as a string to avoid unexpected convertion on 32bit systems? 

#### float and double
Quote from [PHP doc](http://php.net/manual/en/language.types.float.php):
> Floating point numbers (also known as "floats", "doubles", or "real numbers") can be specified using any of the following syntaxes:

```php
$a = 1.234;
var_dump($a); // double(1.234)
$b = 1.2e3; 
var_dump($b); // double(1200)
$c = 7E-10;
var_dump($c); // double(7.0E-10)
```
:question: Since there is no difference between `float` and `double` in PHP can we say that it `double` always?

#### string, byte, binary, date, date-time, password
```php
$string = 'foobar';
var_dump($string); // string(6) "foobar"

$byte = 'Zm9vYmFy';
var_dump($byte); // string(8) "Zm9vYmFy"

$binary = "\x04\x00\xa0\x00";
var_dump($binary); // string(4) "�"

$date = new \DateTime('2018-10-03');
var_dump($date);
/*
class DateTime#1 (3) {
  public $date =>
  string(26) "2018-10-03 00:00:00.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(3) "UTC"
}
*/

$dateTime = new \DateTime('2018-10-03 08:30:00');
var_dump($dateTime);
/*
class DateTime#1 (3) {
  public $date =>
  string(26) "2018-10-03 08:30:00.000000"
  public $timezone_type =>
  int(3)
  public $timezone =>
  string(3) "UTC"
}
*/

$password = 'qwerty';
var_dump($password); // string(6) "qwerty"
```
:question: PHP doesn't have special types for `byte` and `binary`, but there is `DateTime` class which can be applied to both `date` and `date-time`. How we should store all these data types? Maybe better to store `date` and `date-time` as plain string and don't wrap it with `DateTime` class?
:question: Maybe we should add extra getter in models `getCreatedAtAsDateTime()` which returns `DateTime`?

By the way, `DateTime` class is the only stupid exception in JSON serialization. All other types transforms to JSON correctly:
```php
echo json_encode(new StdClass());
// {}

echo json_encode(new array());
// []

echo json_encode(new DateTime());
// {"date":"2018-08-14 07:54:03.121940","timezone_type":3,"timezone":"UTC"}
```
It's one more point to store `date` and `date-time` as string, not as `DateTime` class.

#### boolean
```php
$bool = true;
var_dump($bool); // bool(true)
```
Perfect :laughing: 

#### file
> An additional primitive data type "file" is used by the Parameter Object and the Response Object to set the parameter type or the response as being a file.

:question: Can anybody give any example of `file`  in PHP?

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh

**Comment by wing328** [comment]
> ❓ Can anybody give any example of file in PHP?

`file` (in OpenAPI spec v2) has been replaced with `type: string, format: binary` in OpenAPI spec v3 so both file in OAS2 and `type: string, format: binary` should be mapped to the same type in OpenAPI 
Generator.
