### ISSUE TITLE
[BUG][GO] Generating golang models from openapi 3.3 containing oneOf results in undefined struct

### ISSUE THREAD

**Issue by codedevstem** [OpenAPITools/openapi-generator#8086]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Using the generator to generate models for golang it generates models that are not defined.
I am unsure if this is configuration or limitation.

##### openapi-generator version

Openapi-generator-cli docker-hub: Digest:sha256:829f0b601005c28950ed55c65d853f2caead265730782b2c7c48812bf8135222

##### OpenAPI declaration file content or url

```json
{
  "openapi": "3.0.3",
  "info": {
    "title": "Exampleapi",
    "version": "2.0.0"

  },
  "paths": {
    "/temp": {
      "get": {
        "responses": {
          "200": {
            "description":"Tmp",
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Foo": {
        "type": "object",
        "properties": {
          "Bar": {
            "oneOf": [
              {"$ref": "#/components/schemas/FooBar"},
              {"$ref": "#/components/schemas/BarFoo"}
            ]
          }
        }
      },
      "FooBar": {
        "type": "object",
        "title": "FooBar",
        "properties": {
          "example": {
            "type": "string"
          }
        }
      },
      "BarFoo": {
        "type": "object",
        "title": "BarFoo",
        "properties": {
          "example": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

##### Generation Details

 
Generation command
```
openapi-generator-cli generate \
        -i "/swagger.json" \
        -g go \
        --global-property models,supportingFiles=utils.go,modelDocs=false \
        --additional-properties  \
        --minimal-update \
        -p enumClassPrefix=true \
        --enable-post-process-file \
        --additional-properties packageName="Some Name" \
        -o "/Some_Location"
```
##### Steps to reproduce

Run above code on above swagger to replicate.
The result given the expectations will result in:
```
type Foo struct {
    Bar *OneOfFooBarBarFoo `json:"Bar,omitempty"` <-- Undefined
}
```
Where OneOfFooBarBarFoo is not defined.

##### Related issues/PRs

No

##### Suggest a fix

Given go does not support generics a resonable response would be:
```
type Foo struct {
    Bar *interface{} `json:"Bar,omitempty"`
}
```

**Comment by codedevstem** [comment]
Solved in the latest release, important sidenote: If you have trouble with your resulting models, move the insulting component out to a seperate component.

**Comment by mohassanhosny** [comment]
I am facing the same issue with `OneOf*` definitions not being generated. Is there a way to maybe fallback to plain `interface{}` in such cases?

I am using v5.0.1

**Comment by bmason42** [comment]
Same issue, any progress seen on this?

**Comment by lzyLuke** [comment]
Have this issue too, any solutions?

**Comment by Segflow** [comment]
Any update on this please?

**Comment by batas** [comment]
I have the same problem

**Comment by buinguyenlyprinciple** [comment]
I have the same problem too. I'm considering to use http call normally for Golang, not using OpenAPI.

**Comment by ligertsicat** [comment]
Leaving this in case anyone else runs into this bug, since it's unclear.

Using `oneOf` directly causes problems when generating the sdk

>   requestBody:
>     content:
>       application/json:
>         schema:
>           oneOf:
>             - $ref: '#/components/schemas/Object1'
>             - $ref: '#/components/schemas/Object2'

 However, this can be fixed by placing the above into a separate object 
>   requestBody:
>     content:
>       application/json:
>         schema:
>           $ref: '#/components/schemas/Object3'
>           
> Object3:
>   oneOf:
>     - $ref: '#/components/schemas/Object1'
>     - $ref: '#/components/schemas/Object2'
