### ISSUE TITLE
[REQ] [dart] Generate classes with full args constructor

### ISSUE THREAD

**Issue by bartektartanus** [OpenAPITools/openapi-generator#8092]
### Is your feature request related to a problem? Please describe.

Using generated classes of requests is currently not convenient. Let's assume that class looks like this:
```dart
class RequestDto {
  num amount = null;

  String text = null;
  RequestDto();

  RequestDto.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    amount = json['amount'];
    text = json['text'];
  }
  // rest of the methods not relevant for this issue
}
```

To fully initialise this class we can use setters:
```dart
final request = RequestDto();
request.amount = 15;
request.text = "abc";
```

or use fromJson method which is not type-safe. 
```dart
final request = RequestDto.fromJson({'amount': 15, 'text': 'abc'});
```

## Describe the solution you'd like

Class should also have full arguments constructor. The desired class should look like this:

```dart
class RequestDto {
  num amount = null;

  String text = null;

  RequestDto();

  RequestDto({this.amount, this.text});

  RequestDto.fromJson(Map<String, dynamic> json) {
    if (json == null) return;
    amount = json['amount'];
    text = json['text'];
  }
}
```

## Describe alternatives you've considered

None.

## Additional context

Not needed.

**Comment by kuhnroyal** [comment]
Since you didn't post a generator version that you used, I would assume it was some 4.x version. This is now working in 5.0.0 - please confirm and close if that is the case.

**Comment by bartektartanus** [comment]
It might be hard to confirm right now as I'm using dart package https://github.com/gibahjoe/openapi-generator-dart which uses OpenAPI Dart Generator jar, which uses openapi-generator version 4.2.2.

Looks like I need to contact with package maintainer. I think you can close this issue now and if this won't work after update to 5.0 I will reopen it. :) 

Thank you!

**Comment by bartektartanus** [comment]
@kuhnroyal yes, now I can confirm - it works in 5.0.0 version. 
Thank you.

Closing this issue. :)
