### ISSUE TITLE
[BUG] [Dart] Problem with enum generation.  Generated identifier is used multiple times

### ISSUE THREAD

**Issue by vasilich6107** [OpenAPITools/openapi-generator#8097]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

While running the `flutter pub run build_runner build --delete-conflicting-outputs` I get the next errors.

```
1. Generated identifier "_$short" is used multiple times in , change to something else.
2. Generated identifier "_$email" is used multiple times in , change to something else.
```

##### openapi-generator version

5.0.0-beta3

##### OpenAPI declaration file content or url

Gist with json schema 
https://gist.github.com/vasilich6107/c511a8e185e4a8aac4d7112e8282fa9d

##### Generation Details

Command 

`java -jar openapi-generator-cli.jar generate -i api.json -g dart-dio -c config.yaml --enable-post-process-file`

Config

```yaml
pubName: api
pubVersion: 1.0.0+1
pubDescription: "api"
useEnumExtension: true
```

##### Steps to reproduce

1. Run open api generation
2. Run `flutter pub run build_runner build --delete-conflicting-outputs`

**Comment by kuhnroyal** [comment]
This is fixed in 5.0.0, inner enum private fields are now prefixed with the enum name.
Please confirm and close the issue if it works for you.

**Comment by vasilich6107** [comment]
Thanks, I'll check.

**Comment by vasilich6107** [comment]
@kuhnroyal thanks everything works fine.
