### ISSUE TITLE
[REQ] Fix default Content-Type Header in Python client

### ISSUE THREAD

**Issue by telday** [OpenAPITools/openapi-generator#8116]
### Is your feature request related to a problem? Please describe.

Currently in the Python client (at least, I have not verified for other generated clients) when there is no `requestBody` key specified for a given path in the spec file the generated client will automatically set the `Content-Type` header to `application/json`. The biggest issue with this is that an empty request body is NOT valid JSON. Therefore the client effectively sends an invalid request to the server each time there is no request body specified. This is not a problem most of the time, however I have encountered issues with this when running against a Rails server. 

## Describe the solution you'd like

The `Content-Type` header should default to either `text/plain` or should be omitted if it is unnecessary.

**Comment by Kylmakalle** [comment]
# API Client **must not force** `application/json` content-type

https://github.com/OpenAPITools/openapi-generator/blob/e00ac502f1cf51287a6e8f79c1fec20ba5d03c97/modules/openapi-generator/src/main/resources/python/api_client.mustache#L590-L591



Another approach is to have an interface to select a content-type for each request

```python
api_instance = pet_api.PetApi(api_client)
body = ...
api_instance.add_pet(body, content_type='custom/header')
```

**Comment by jmadler** [comment]
A sampling of a few API clients suggest that the de facto standard behavior is to fallback to 'application/json' in all cases.  I would recommend instead falling back to 'text/plain' in the specific case of a zero-length request body.

Does that behavior change seem appropriate?  If so, we'd be happy to prep PRs for all applicable clients.

**Comment by wing328** [comment]
Thanks for starting a discussion on this. I think it's a "historical" (wrong) reason to default to "application/json". I remember fixing similar issues myself in some generators (e.g. Ruby?)

If the content-type/accept is not defined in the spec, then the corresponding header should not be set in the HTTP request/response.

If it's not clear, please PM me via Slack and I'm happy to answer questions you may have.
