### ISSUE TITLE
How to generate just ONE api?

### ISSUE THREAD

**Issue by marikaner** [OpenAPITools/openapi-generator#8121]
##### Description

I am currently generating a typescript-axios client. The generator creates multiple apis, one for each tag. There is also a DefaultApi when there is no tag. I would like to have one API for the whole service. Is it possible to configure it as such? I didn't find anything regarding this.

##### openapi-generator version

5.0.0-beta2

**Comment by jenswegar** [comment]
Writing off memory here, but you could put the same tag on each api service, and then use the ```operationId``` property to distinguish the different endpoint methods in the generated code?

**Comment by marikaner** [comment]
@jenswegar thanks for the quick response. This is what I am currently doing, but that means, that I have to involve IO, parse my input and write it back before I can generate. This works, but I was wondering if there is a cleaner way.
The OpenApi documentation states that "tags can be used for logical grouping of operations by resources or any other qualifier". That sounds like the separation is rather optional whereas in the generator I can't seem to find a way to make it optional.

**Comment by miparnisari** [comment]
We recently needed something similar, we are doing this:

```
cat original.swagger.json | \
docker run --rm -i stedolan/jq '(.. | .operationId? | select(.)) |= sub("OurCoolService_"; "") | (.. | .tags? | select(.)) |= ["OurCoolTag"]' > \
modified.swagger.json
```

**Comment by kbbqiu** [comment]
Looks like this may have been solved by using a normalizer config,`SET_TAGS_FOR_ALL_OPERATIONS`. See [customization README](https://github.com/OpenAPITools/openapi-generator/blob/bab67e44e49422f51aca84d0ac1cc3987f443c62/docs/customization.md?plain=1#L543).

I was able to successfully do this in my java pom.xml file
```xml
    <openapiNormalizer>
      SET_TAGS_FOR_ALL_OPERATIONS=<SOME_TAG>
    </openapiNormalizer>
```

**Comment by wing328** [comment]
yes, please use `SET_TAGS_FOR_ALL_OPERATIONS` in openapi normalizer for this use case.
