### ISSUE TITLE
[BUG] [JAVA] Generate primitives instead of wrapper

### ISSUE THREAD

**Issue by JurajMlich** [OpenAPITools/openapi-generator#8146]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

Java best practises say that when you don't need a nullable type and a primitive type can be used instead (i.e. boolean instead of Boolean), you should. So when I have a property of type boolean which is nullable and required, I would expect the generator to use the primitive type when possible. But that's not the case, however. `Boolean` is used anyway. 

##### openapi-generator version

5.0.0-beta3 (openapi-generator-maven-plugin)

#### 

Is there any way to do this? If not, is there something that can prevent me from implementing this myself? If not, could you push me in the right direction? I'm happy to provide a PR myself. Thanks.

**Comment by JurajMlich** [comment]
Well, I've actually managed to do it by creating my own generator
```
        this.typeMapping.put("boolean", "boolean");
        this.typeMapping.put("Boolean", "Boolean");
```

But I've just realised that it's actually stupid do it. If the user forgot to include a parameter, then as it's a primitive, it would be unknowingly-to-the-user set to false, which can cause troubles. It's better for it to be set to null and validated. 

Thanks anyways :D

**Comment by wing328** [comment]
You can do it directly from the command line for example using the `--type-mappings` option
