### ISSUE TITLE
[BUG] [Kotlin] jvm-retrofit2 with Jackson issues

### ISSUE THREAD

**Issue by Sam-Kruglov** [OpenAPITools/openapi-generator#8147]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

When generating kotlin retrofit client with Jackson, the ApiClient doesn't compile and other small issues.

Here's what I have:
```kotlin
class ApiClient(
    private var baseUrl: String = defaultBasePath,
    private val okHttpClientBuilder: OkHttpClient.Builder? = null,
    private val serializerBuilder: Builder = Serializer.Builder, // Builder is unresolved, serializerBuilder isn't used in the class
    private val okHttpClient: OkHttpClient? = null
) { 
...
    // in my spec I have 3 requirements: basic, jwt, and oauth2. So, one of these should be fulfilled to access the api
    fun setCredentials(username: String, password: String): ApiClient {
        apiAuthorizations.values.runOnFirst<Interceptor, HttpBasicAuth> {
            setCredentials(username, password)
        }
        apiAuthorizations.values.runOnFirst<Interceptor, OAuth> {
            tokenRequestBuilder.setUsername(username).setPassword(password)
        }
        return this
    }

    // this method should not be here, it's already handled above in the setCredentials
    // this method should only be present when the is oauth but there is no basic auth
    fun setCredentials(username: String, password: String): ApiClient { 
        apiAuthorizations.values.runOnFirst<Interceptor, OAuth> {
            tokenRequestBuilder.setUsername(username).setPassword(password)
        }
        return this
    }
...
}
```
Also, okhttp version collision, logging-interceptor wants 4.4.0, retrofit wants 3.14.9 (https://github.com/square/retrofit/issues/3384). So, given I fix the interceptor version to 3.14.9 as well, I still have to fix some issues. 
`ApiKeyAuth.kt` doesn't compile:
```kotlin
...
if ("query" == location) {
    var newQuery = request.url.toUri().query // request.url does not exist, request.url() returns okhttp3.HttpUrl
    val paramValue = "$paramName=$apiKey"
    if (newQuery == null) {
        newQuery = paramValue
    } else {
        newQuery += "&$paramValue"
    }

    val newUri: URI
    try {
        val oldUri = request.url.toUri()
        newUri = URI(
            oldUri.scheme, oldUri.authority,
            oldUri.path, newQuery, oldUri.fragment
        )
    } catch (e: URISyntaxException) {
        throw IOException(e)
    }

    request = request.newBuilder().url(newUri.toURL()).build()
} else ...
...
```
Here's how it should be (I think):
```kotlin
if ("query" == location) {
    val newUrl = request.url().newBuilder().addQueryParameter(paramName, apiKey).build()
    request = request.newBuilder().url(newUrl).build()
} else ...
```
Also, `OAuth.kt` doesn't compile because it uses `request.url` and `request.body` instead of `request.url()` and `request.body()`.
Also `OAuthOkHttpClient.kt` doesn't compile because of `request.body` and because it uses a non-existent extension `toMediaTypeOrNull()` which I think can be replaced by static call `MediaType.parse(...)`.
Also, `ApiClient#retrofitBuilder` should really be public to allow customizations. 
Also, maybe `ApiClient` should be `open` for extension? I can extend it if generated by Java.
Also, there are empty files which only contain a package: `ByteArrayAdapter.kt`, `ResponseExt.kt`.
Also, there is a `Serializer.kt`which has a method but it's not used either:
```kotlin
object Serializer {
    @JvmStatic
    val jacksonObjectMapper: ObjectMapper = jacksonObjectMapper()
        .registerModule(Jdk8Module())
        .registerModule(JavaTimeModule())
        .setSerializationInclusion(JsonInclude.Include.NON_ABSENT)
        .configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
}
```
Also, the resulting code cannot serialize JSON, so I had to add the dependency`compile "com.squareup.retrofit2:converter-jackson:$retrofitVersion"` and this line to the `ApiClient`: 
```kotlin
private val retrofitBuilder: Retrofit.Builder by lazy {
    Retrofit.Builder()
        .baseUrl(baseUrl)
        .addConverterFactory(ScalarsConverterFactory.create())
        .addConverterFactory(JacksonConverterFactory.create(Serializer.jacksonObjectMapper)) // I added this line
}
```
Also, the markdown docs for each API class seem to document all authentication methods at the same time (but oauth is missing):
```kotlin
val apiClient = ApiClient()
apiClient.setCredentials("USERNAME", "PASSWORD")
apiClient.setBearerToken("TOKEN")
val webService = apiClient.createWebservice(...
```
Also, logging interceptor doesn't do anything by default. Could be refactoring like this (default constructor take care of it):
```kotlin
.addInterceptor(
    (if (logger != null) HttpLoggingInterceptor(logger) else HttpLoggingInterceptor()).apply {
        level = HttpLoggingInterceptor.Level.BODY
    }
)
```
Also, `ApiClient` accepts `authName` in specialized constructor even though it is redundant. For example, it asks for username and password, so it already knows that the authentication method is basic and there is no need to explicitly ask for its name.
Also, method `ApiClient#createService` accepts java class but it should accept kotlin class for convenience. 
Also, this line contains multiple statements a looks weird, should be reformatted:
https://github.com/OpenAPITools/openapi-generator/blob/9e5610488f8b649856a72cd25695fc071b0ca1c4/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache#L106

Links to mustache: [ApiClient](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ApiClient.kt.mustache), [ResponseExt.kt](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/infrastructure/ResponseExt.kt.mustache), [Serializer.kt](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/Serializer.kt.mustache), [ByteArrayAdapter.kt](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/jvm-common/infrastructure/ByteArrayAdapter.kt.mustache), [ApiKeyAuth.kt](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/auth/ApiKeyAuth.kt.mustache)

And I am not sure if this is relevant but on the Retrofit's homepage they say there is a Jackson converter at `com.squareup.retrofit2:converter-jackson` that we could use.

##### openapi-generator version

latest build from master

##### Steps to reproduce

```bash
openapi-generator generate \
  --generator-name kotlin \
  ... 
  --library jvm-retrofit2 \
  --additional-properties serializationLibrary=jackson
```
the `...` is ambiguous but I think the only thing that matters here is that it's a combination of retrofit and Jackson but let me know.

**Comment by andrgn** [comment]
Has it been fixed fix? Is it planned to fix ? 

I want to use retrofit2 + jackson but I have the same problems with serialization builder and auth 😟

**Comment by Sam-Kruglov** [comment]
@andrgn you can manually edit ApiClient as I suggested as a workaround. It won't get overwritten on the generation command since it already exists (I think). Or you can include it in the ignore list.
