### ISSUE TITLE
[BUG] [Elixir] Missing .t() for struct specs.

### ISSUE THREAD

**Issue by carrascoacd** [OpenAPITools/openapi-generator#8150]
### Bug Report Checklist

- [x]  Have you provided a full/minimal spec to reproduce the issue?
- [x]  Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x]  Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x]  Have you searched for related issues/PRs?
- [x]  What's the actual output vs expected output?
- [x]  [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

### Description

When generating the Elixir specs `dyalizer` complains about the types of custom structs. I guess that there is a missing t() when generating the datatype for this specific case.

For example:

```
  @type t :: %__MODULE__{
    :"world" => World | nil
  }
```

vs

```
  @type t :: %__MODULE__{
    :"world" => World.t() | nil
  }
```

I found a TODO comment which could be the culprit.

### openapi-generator version

4.1.2

### OpenAPI declaration file content or url
[example.txt](https://github.com/OpenAPITools/openapi-generator/files/5672222/example.txt)

### Generation Details

`openapi-generator generate -i example.txt -g elixir -o .`

### Steps to reproduce
Just generate the API

### Suggest a fix

[https://github.com/carrascoacd/openapi-generator/commit/8ec120b781240254d67efc71bd6e20c8a161b90d](https://github.com/carrascoacd/openapi-generator/commit/8ec120b781240254d67efc71bd6e20c8a161b90d)

**Comment by wing328** [comment]
@carrascoacd thanks for reporting the issue. Can you please file a PR with the suggested fix?

**Comment by carrascoacd** [comment]
Sure. I didn't do it since I was unable to build the JAR and I didn't have a lot of time to investigate it, but if you help me to find the error the better. 

Here is the PR https://github.com/OpenAPITools/openapi-generator/pull/8159/files
