### ISSUE TITLE
[BUG] [java] [resttemplate] Generated alias models missing JsonTypeName import

### ISSUE THREAD

**Issue by mikesaurus** [OpenAPITools/openapi-generator#8157]
##### Description
When generating client code with openapi-generator and the `generateAliasAsModel` option set to `true`, model classes generated from aliases are missing an import statement for the JsonTypeName annotation and fail to compile.

##### openapi-generator version
5.0.0-x

##### OpenAPI declaration file content or url
Example [swagger contract](https://github.com/mikesaurus/openapi-gen-alias-type-bug/blob/main/src/main/resources/swagger.json).

##### Generation Details
The code is being generated using the Maven plugin.  See [example project](https://github.com/mikesaurus/openapi-gen-alias-type-bug).

##### Steps to reproduce
1. See example project [README](https://github.com/mikesaurus/openapi-gen-alias-type-bug/blob/main/README.md).
2. Change the `openapi-generator-maven-plugin.version` in the POM file to any 5.0.0-x version and build.

##### Related issues/PRs
None.

##### Suggest a fix
Include the JsonTypeName import for both standard and alias model classes.

**Comment by grzegorz-moto** [comment]
+1

**Comment by unnamedsos** [comment]
also in version 5.0.1 !

**Comment by wing328** [comment]
Please test the fix by @jakubskopal to see if it fixes the issue for you: https://github.com/OpenAPITools/openapi-generator/pull/8815

**Comment by grzegorz-moto** [comment]
Yes, the fix #8815 is working as expected

**Comment by mikesaurus** [comment]
@wing328 Yes. The changes in #8815 appear to fix this issue.

**Comment by Richard-Mathie** [comment]
CI CD job errored. Dose this need a rebase?
