### ISSUE TITLE
[Qt5][C++] pass global server as object to mustache to support parameterized and multiple servers.

### ISSUE THREAD

**Issue by basyskom-dege** [OpenAPITools/openapi-generator#8164]
### Is your feature request related to a problem? Please describe.
I will give you some context to understand my problem.
I am working on an parameterized and multi server implementation for the Qt5 generator. To archive this, I looked at the java generator and used similar classes. There is a ServerConfiguration class and a ServerVariable class. The first one stores the different servers for each endpoint in each API, the second one describes a variable of a server. Every ServerConfiguration has a map of &lt;QString,ServerVariable> that maps the name of the variable to its value. Each API has a map of &lt;QString QList&lt;ServerConfiguration&gt;&gt;  that maps different operationsIDs to one or more ServerConfigurations. Furthermore there is another map <QString,int> called serverIndices that maps for every operationID the default server index in the QList&lt;ServerConfiguration&gt; that should be used when there are multiple servers. 
An example server config in an API could be this: 
```
servers:
- url: http://{server}:8080/
  description: Description of the Server
  variables:
    server:
        enum:
          - 'petstore'
          - 'qa-petstore'
          - 'dev-petstore'
        default: 'petstore'
- url: https://localhost:8080/v1
```
If this server object is defined for an endpoint, everything works fine. Standard server is the first one with the different hosts and you can choose to use the other server or change the default variable with suitable getters and setters. 

However, the global server will only be passed as three mustache variables: ``` {{serverPort}} {{serverHost}} {{scheme}}```

## Describe the solution you'd like

My question is, where  do i have to change the generator code on java level so that the global server will be passed as a server object, just like the ones that are passed for each endpoint.
I would like to have a {{globalServer}} object with an {{url}} {{description}} and an array of {{variables}} that each contain a {{name}} {{description}} {{defaultValue}} and an array {{enumValue}}

## Describe alternatives you've considered
Right now I am parsing the global server as following: 
```
QList<ServerConfiguration> defaultConf = QList<ServerConfiguration>{ServerConfiguration(
    "{protocol}://{server}:{port}/{basePath}",
    "Default Server",
    QMap<QString, ServerVariable> { 
          {"server", ServerVariable("Default Server","{{serverHost}}",
          QSet<QString>{ {"{{serverHost}}"} })}, 

          {"port", ServerVariable("Default Port","{{serverPort}}",
          QSet<QString>{ {"{{serverPort}}"} })}, 

          {"basePath", ServerVariable("Default BasePath","{{basePathWithoutHost}}",
          QSet<QString>{ {"{{basePathWithoutHost}}"} })}, 

          {"protocol", ServerVariable("Default Protocol","{{scheme}}",
          QSet<QString>{ {"{{scheme}}"} })}, 
})};

I will just hardcode the url and parse the three mustache variables to the missing variables.
```
## Additional context

I found this function in AbstactCppCodegen.java on line 328f. I guess this is the function that does the magic. Should i just change this to fit my expectations?
```
 @Override
    public void preprocessOpenAPI(OpenAPI openAPI) {
        URL url = URLPathUtils.getServerURL(openAPI, serverVariableOverrides());
        String port = URLPathUtils.getPort(url, "");
        String host = url.getHost();
        String scheme = url.getProtocol();

        if (!port.isEmpty()) {
            this.additionalProperties.put("serverPort", port);
        }
        if (!host.isEmpty()) {
            this.additionalProperties.put("serverHost", host);
        }
        if (!scheme.isEmpty()) {
            this.additionalProperties.put("scheme", scheme);
        }
    }
```

**Comment by etherealjoy** [comment]
@basyskom-dege 
I understood you want to pass the servers parsed from the spec to the mustache template?
You need to create a new mustache variable for it. Modifying the current ones would break all other generators for example.

From what I understand, the URLPathUtils return only one.

**Comment by basyskom-dege** [comment]
Thanks for the reply. Yes. I know i need to create a new variable. The OpenAPI object can give me a List<Server> that i can work with. But i have to "manually" cast this list to a List<CodegenServer> since the "Server" object cant be parsed in mustache like the CodegenServer. I create the List<CodegenServer> like this. Do you think thats the way to go or is there a more elegant way?
```
 List<Server> serverList = openAPI.getServers();
        if (!serverList.isEmpty()) {
            for (Server server : serverList) {
                CodegenServer s = new CodegenServer();
                s.description = server.getDescription();
                s.url = server.getUrl();
                s.variables = new ArrayList<CodegenServerVariable>();
                ServerVariables ServerVars = server.getVariables();
                ServerVars.forEach((key,value) -> {
                    CodegenServerVariable codegenServerVar= new CodegenServerVariable();
                    ServerVariable ServerVar = value;
                    codegenServerVar.name = key;
                    codegenServerVar.description = ServerVar.getDescription();
                    codegenServerVar.defaultValue = ServerVar.getDefault();
                    codegenServerVar.enumValues = ServerVar.getEnum();
                    s.variables.add(codegenServerVar);
                });
                CodegenServerList.add(s);
            }
        this.additionalProperties.put("globalServerList", CodegenServerList);
        }
```

**Comment by etherealjoy** [comment]
Something like that could work, but probably you need to rework it a bit and add use the format like this for example `vendorExtensions.x-codegen-pistache-is-parsing-supported`.. you can check in the code for examples

**Comment by basyskom-dege** [comment]
Okay. so you mean that i should not call the additional property `globalSeverList` but rather something like `x-codegen-cpp-parameterized-server` ? I will check if the server is a parameterized server and if it has multiple servers. My implementations is nearly done and works with OAS2 and OAS3 server specifications. I do these checks at mustach level. I will do a pull request later today and link this issue.
