### ISSUE TITLE
[REQ][JAVA][Spring] Allow choosing which headers to set as implicit in implicitHeaders configProps

### ISSUE THREAD

**Issue by M3lkior** [OpenAPITools/openapi-generator#8166]
### Is your feature request related to a problem? Please describe.

Today, my team use OpenApi-generator with an API first approach so we use the java maven plugin to generate the code
We need to manage some headers globally thanks to Spring HTTP interceptor (for example, a `tenant` header) and so we don't want to add `@ApiParam` attribute on each controller method

The solution is to use `ApiImplicitParam` to allow users using swagger-ui to set our headers. But the configProp `implicitHeaders` set all existing headers, it is not possible to select certain headers and keep all remaining headers (like date headers, etc) declared explicitly

## Describe the solution you'd like

The idea is to list, into `implicitHeaders` configProps property, the headers to set implicit like this :  

```
 <implicitHeaders>
                                    <X-Tetant-Code>true</X-Tetant-Code>
                                </implicitHeaders>
```

## Describe alternatives you've considered

The configuration can handle wildcard or pattern (like `*`) to apply this configuration on targeted headers : 

```
 <implicitHeaders>
                                    <X-*-Code>true</X-Tetant-Code>
                                </implicitHeaders>
```

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/11819 by @borsch has been merged into master. Please pull the latest master to give it another try.
