### ISSUE TITLE
[BUG] Jersey2 Client setting debug doesn't rebuild the httpClient

### ISSUE THREAD

**Issue by nmuesch** [OpenAPITools/openapi-generator#8185]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Setting the debug option in the ApiClient doesn't fully enable debug logging. 
There is a comment here about rebuilding the client when setDebugging is enabled - https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L603. However this continues to use the previously built clientConfig - https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L1239 that was initialized from the constructor. 

The result is not seeing the request/response being logged after calling `setDebugging` to True. One possible solution would be to not have the null check in the above link and always rebuild the http client, but that may not be desired. 

##### openapi-generator version

Latest master commit

##### Generation Details

No specific spec needed, this is generated currently in the existing petStore jersey2 example.

##### Related issues/PRs

I couldn't find another similar reported issue. 

##### Suggest a fix

More details in the Description section.

**Comment by davidmoten** [comment]
I've noticed this too. No logging at all despite calling `ApiClient.setDebugging(true)` with *openapi-generator-maven-plugin* 5.0.0-beta3.

**Comment by nmuesch** [comment]
I believe the issue is around this nil check - https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/jersey2/ApiClient.mustache#L1239-L1241, removing that check lets the httpclient fully rebuild with the debug flag enabled, and sets up the logging for the request/response. 
Though I'm not sure if it will cause any issues removing this cache. From the other parts of the template that call this, it looks like the intent is to trigger a refresh.

**Comment by nmuesch** [comment]
Closing, as this should be solved by #8756
