### ISSUE TITLE
[KOTLIN] Spring Boot Server Generator

### ISSUE THREAD

**Issue by dr4ke616** [OpenAPITools/openapi-generator#819]
##### Description

Hey everyone,

I'd like to propose a new server generator for Kotlin using the Spring Boot framework.

##### openapi-generator version

Based off `master` - next minor release

**Comment by mikezx6r** [comment]
There is a kotlin-spring language generator under development. Have you checked it out? Depending on your needs, it may be adequate.

I'm watching it right now, but there's still a few issues/changes I'd like to see. Going to provide feedback/proposals to people working on it.

If you have `allOf` in an object reference, and depending on which commit you're on, it either attempts to use inheritance of a data class, or it produces duplicate properties.

I also like the delegate pattern that the Java Spring generator uses where everything is defined in one interface (as I only want API and Models generated, and manage the Controllers etc myself).

Or was this to track the effort currently taking place?

**Comment by dr4ke616** [comment]
@mikezx6r this issue can actually be closed now, as the first implementation of a Kotlin spring-boot was implemented in PR #820
