### ISSUE TITLE
[REQ][Java] I would like to be able to skip generation for toString or be able to change it template

### ISSUE THREAD

**Issue by borsch** [OpenAPITools/openapi-generator#8210]
### Is your feature request related to a problem? Please describe.
Some times I want simply to log DTO object as is(via `toString()`). Because of `\n` that is present in to string my log can became very huge and unreadable(imagine DTO with 7-10 fields each started from new line)

## Describe the solution you'd like
I would like either to be able to remove toString from DTO classes(boolean switcher) or to be able somehow to pass my own template for toString

**Comment by Sudharshun** [comment]
Was this ever merged into a Release? We are trying to skip toString() generation and it doesn't seem to work.
