### ISSUE TITLE
[BUG] default(Type) in the constructor causes a Json serialization issue on Net5.0

### ISSUE THREAD

**Issue by HeshamMeneisi** [OpenAPITools/openapi-generator#8211]
This is already tracking the underlying cause https://github.com/dotnet/runtime/pull/45457

It seems that it will be released with dotnet 5.102

Just wanted to mention this here for anyone having the issue to know the root cause (It's super vague when debugging, just a random NullReferenceException).

**Comment by wing328** [comment]
@HeshamMeneisi thanks for sharing this issue with the community. Hopefully it will be covered in the dotnet 5.102 release as you've mentioned.
