### ISSUE TITLE
[REQ] typescriptThreePlus should be true

### ISSUE THREAD

**Issue by strowk** [OpenAPITools/openapi-generator#8222]
### Is your feature request related to a problem? Please describe.

New projects start with new versions of typescript. Typescript 3.6 is out for more than a year. Still, using generator with typescript requires a long process of finding the correct option (typescriptThreePlus) and placing it in proper place, which could  be simplified.

## Describe the solution you'd like

Option typescriptThreePlus should be true by default. Users of older versions could opt-out. 

## Describe alternatives you've considered

Detect typescript version automatically from package.json file (too complex).

**Comment by macjohnny** [comment]
it would be great if you could file a PR to change the default, as this is a breaking change with fallback, this can be included in the upcoming 5.0.0 release

**Comment by komtaki** [comment]
This request seems to have been resolved by [v5.4.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v5.4.0). 👏 

This pull request. https://github.com/OpenAPITools/openapi-generator/pull/11331
