### ISSUE TITLE
Make Powershell verb parsing for cmdlets optional (or skip it optionally)

### ISSUE THREAD

**Issue by EngineerCoding** [OpenAPITools/openapi-generator#8233]
### Is your feature request related to a problem? Please describe.

My API contains several endpoints which for example start with `Out`, which means that a `Out-X` cmdlet is generated for these particular endpoints. I don't want this to happen.

## Describe the solution you'd like

I would like to make this verb parsing opt-out, so that one can supply an additional argument and this verb parsing is skipped completely. Then the cmdlet would be generated as `Invoke-[endpoint]`.

## Describe alternatives you've considered

Post processing my files, but this is hard since I then also have to update all documentation files.

## Additional context

I want `Out-goingInfo` to be named `Invoke-OutgoingInfo`

**Comment by wing328** [comment]
Can you try with extension: https://github.com/OpenAPITools/openapi-generator/wiki/Vendor-Extensions#x-powershell-method-name ?

**Comment by EngineerCoding** [comment]
I unfortunately don't have control of the swagger endpoint, because this endpoint is updated frequently (and thus need to regerenate frequently), I'd like not post process that swagger constantly.
