### ISSUE TITLE
[bug][dart-dio] Allow models to be serialized within a map using `MapBuilder`

### ISSUE THREAD

**Issue by ahmednfwela** [OpenAPITools/openapi-generator#8270]
##### Description

Currently the generator adds all possible List builders for each model, but another viable option is to add Map builders (`Map<String,{{Model}}>`)
Ref:
https://github.com/OpenAPITools/openapi-generator/blob/c3220848f24bbc5e5441f53846916eaa82e6673c/modules/openapi-generator/src/main/resources/dart-dio/serializers.mustache#L20-L27

##### openapi-generator version

v5.0.0

##### Suggested fix:
```
{{#models}}{{#model}}..addBuilderFactory(
const FullType(BuiltMap, const [const FullType(String),const FullType({{classname}})]),
() => new MapBuilder<String,{{classname}}>())
```

**Comment by kuhnroyal** [comment]
So you do have `Map<String, ,{{Model}}>` as return type from an API call?

**Comment by ahmednfwela** [comment]
yes, I do

**Comment by kuhnroyal** [comment]
My PR should fix this, would be great if you can review or build and test it.
