### ISSUE TITLE
[BUG][dart-dio] add package:built_collection/built_collection.dart to imports

### ISSUE THREAD

**Issue by ahmednfwela** [OpenAPITools/openapi-generator#8273]
##### Description

API end points that require sending `BuiltList<String>` will fail since this is missing from the imports
```dart
package:built_collection/built_collection.dart
```

Ref: https://github.com/OpenAPITools/openapi-generator/blob/c3220848f24bbc5e5441f53846916eaa82e6673c/modules/openapi-generator/src/main/resources/dart-dio/api.mustache#L1-L5

##### openapi-generator version

V5.0.0

**Comment by kuhnroyal** [comment]
Yes I have just had this happen to me with `BuiltMap`, this is my bad. I will add a fix shortly.
