### ISSUE TITLE
[dart-dio][client] Generated code for property that is array type with default value does not compile

### ISSUE THREAD

**Issue by adg-mh** [OpenAPITools/openapi-generator#8285]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?

##### Description

Support for default values was added in #8201 by @kuhnroyal. Now when array type with default value which is an empty array `[]` is in the spec, dart code that does not compile is generated:

```yaml
pets:
  type: array
  items:
    $ref: '#/components/schemas/Pet'
  default: []
```

Error as follows:

`A value of type 'List<dynamic>' can't be assigned to a variable of type 'ListBuilder<Pet>'.`

Snippet of generated code causing the issue:

```dart
@nullable
@BuiltValueField(wireName: r'pets')
BuiltList<Pet> get pets;

static void _initializeBuilder(OrderBuilder b) => b
    ..pets = [] // <-- line causing error
    ..complete = false;
```

##### openapi-generator version

`master`

##### Steps to reproduce

You can reproduce the issue by running the dart-dio generator for this modified petstore example [here](https://gist.github.com/adg-mh/6a61d68dd1b81123d39fbaedf1ffe128)

##### Related issues/PRs

#8201 by @kuhnroyal is where the issue appears to be introduced

@swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)

**Comment by kuhnroyal** [comment]
I see, there is also a problem with Date/DateTime default values for dart/dart-dio. I will see what I can do.
Non-empty array default values will not work either.

**Comment by kuhnroyal** [comment]
I am actually not sure if an array with values can be defined as default value. I also have never seen a map/object default value. An empty array should be `ListBuilder().build()`.

**Comment by adg-mh** [comment]
Example with complex default value [here](https://gist.github.com/adg-mh/0368f25394a185d0aa12c0abc567e892) does validate, but it seems the JSON representing the object ends up in the dart output.

**Comment by agilob** [comment]
From line 617 https://gist.github.com/adg-mh/0368f25394a185d0aa12c0abc567e892#file-petstore-array-default-complex-yaml-L617 creates two pets by default

**Comment by kuhnroyal** [comment]
> Example with complex default value [here](https://gist.github.com/adg-mh/0368f25394a185d0aa12c0abc567e892) does validate, but it seems the JSON representing the object ends up in the dart output.

Yes, that is definitely the problem, there is a default to a plain string. Before my changes default values were not supported at all. I am now wondering to what extend I want to implement this, many generators don't seem to support this beyond simple values.

Thanks for the examples, maybe we should add/generate them for dart/dart-dio.

**Comment by kuhnroyal** [comment]
@adg-mh Where is this config from that you have there?

**Comment by adg-mh** [comment]
@kuhnroyal That was the petstore example I just cobbled in the extra bits to see how it would act. I don't actually need that functionality now, I was just checking to see if it validated.

Haven't tested yet but it looks like the fixes in your PR cover my case.

**Comment by kuhnroyal** [comment]
@vasilich6107 Can you please check if https://github.com/OpenAPITools/openapi-generator/pull/17500 works for you?
