### ISSUE TITLE
[BUG] Redundant JSDoc attributes in typescript-fetch

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OpenAPITools/openapi-generator#8292]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- ~[ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))~

##### Description

There are quite a few JSDoc attributes in the [generated typescript-fetch code](https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts). TypeScript can infer doc tags such as `@memberof` and `@type`; it's redundant and visually wasteful to include them in the generated files.

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts

##### Generation Details

See example docs.

##### Steps to reproduce

See example docs.

##### Related issues/PRs

* #6474 is fine and good; `@deprecated` is a recognized [TSDoc](https://github.com/microsoft/tsdoc) tag
* #8259 is in the same area but looks to be an unrelated bug in the generation of informative info.

##### Suggest a fix

I'd be happy to send a PR in if a maintainer can confirm this is acceptable 😄. Looking through some basic model files, these are the tags I think can be remove for being redundant (self-explanatory from generated TypeScript code):

* [`@enum {string}`](https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts#L94)
* [`@export`](https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts#L4)
* [`@interface {Name}`](https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts#L5)
* [`@memberof {Name}`](https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts#L11)
* [`@type {{Name}}`](https://github.com/OpenAPITools/openapi-generator/blob/36aba267a077ea9a64242d4c6bbeb8837b5eb8e4/samples/client/petstore/typescript-fetch/builds/without-runtime-checks/src/models/index.ts#L5)

**Comment by London804** [comment]
I see this is still open from almost three years ago. Has this been addressed? I would love to remove the redundant JSDoc annotations from my code.

**Comment by JoshuaKGoldberg** [comment]
Closing out my old issues for repos I no longer have context on. If anybody has a need for what this issue was asking about, I'd encourage them/you to file a new issue. Cheers!
