### ISSUE TITLE
[Enhancement][JAVA] Replace apache oltu with scribejava

### ISSUE THREAD

**Issue by hugo-ma-alves** [OpenAPITools/openapi-generator#8297]
##### Description

Hello

Currently the Java feign generator is using apache oltu to construct the oauth requests. 
Since oltu is now deprecated I was making some changes on my branch to replace it with scribejava, the same used in jersey2 generator.

For now I just have implemented the client credentials flow, but I believe I can keep implementing the others.

Do you think it can be useful? I can open a PR with these changes.
The current status of this migration is available in this fork https://github.com/hugo-ma-alves/openapi-generator/tree/feature/feign-replace-oault-with-scribejava

##### openapi-generator version

5.0.0

**Comment by wing328** [comment]
@hugo-ma-alves thanks for offering help on this. Yes we welcome PR with the suggested change. Let me know if you need help with the PR.

**Comment by hugo-ma-alves** [comment]
Since the PR https://github.com/OpenAPITools/openapi-generator/pull/8318 is now merged I will close this ticket.
