### ISSUE TITLE
[BUG][Python] Generated python client fails to correctly process optional response bodies

### ISSUE THREAD

**Issue by telday** [OpenAPITools/openapi-generator#8300]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Attempting to use optional request bodies in the Python generated client, then passing nothing in for the body kwarg, causes the client to crash and output:

```
Reason: Cannot prepare a request message for provided
                             arguments. Please check that your arguments match
                             declared content type.
```

This is because in the rest client the if statement choosing how to format the request body fails to account for a body = `None`

##### openapi-generator version

4.3.1 However the offending portion of the rest client generates identically in the latest version.

##### OpenAPI declaration file content or url

```yaml
paths:
  '/test/':
    post:
      operationId: 'testing'
      requestBody:
        required: false
        content:
          text/plain:
            schema:
              type: string
      responses:
        "200":
          description: "The secret value was added successfully"
```

##### Steps to reproduce

Create a spec file with the above path in it, generate a python client, then attempt to make a request without passing the body kwarg

**Comment by spacether** [comment]
Please upgrade to v5.0.0 and use the python genertor and set nullable to True for your response body schema.
Nullable schemas are supported in v5.0.0 python.

**Comment by spacether** [comment]
If you need this behavior, please use the `python-experimental` generator
This feature exists in that generator
One can see that option request bodies are only included if they are set per this code: https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/paths/fake_refs_number/post.py#L71
