### ISSUE TITLE
[BUG] Dart - generated enum class overrides == so it can't be used in switch cases

### ISSUE THREAD

**Issue by agilob** [OpenAPITools/openapi-generator#8307]
Getting the following error with enum generator:

![image](https://user-images.githubusercontent.com/2544251/103462654-9d660a80-4d1e-11eb-9b4a-65ab213ff385.png)

openapi 5.0.0

**Comment by kuhnroyal** [comment]
Well these are no real enums, these are normal classes, you cant really switch on them.
