### ISSUE TITLE
[REQ] Update gradle example

### ISSUE THREAD

**Issue by feenr** [OpenAPITools/openapi-generator#8311]
### Small update to gradle example code.

As a new user to this project I had simply copy, pasted and modified the openApiGenerate example to suite my needs, but I struggled a bit to understand why absolutely nothing was being generated in the generated  folder. I tried a few different OAS definitions, info logging, and verbose output in an attempt to debug.
 
What ended up being the problem is that my OpenAPI content did not have a model called error included. Once I removed the modelFilesConstrainedTo configuration it worked fine.

This makes sense in retrospect, but perhaps the example should not include this configuration? I imagine most new users would want all swagger models included until they refine their process anyway.

## Describe the solution you'd like

I'd like to remove modelFilesConstrainedTo from the gradle example

**Comment by falk-stefan** [comment]
@feenr Any chance you can help me [on this](https://stackoverflow.com/questions/65628873/using-org-openapi-generator-in-gradle-project)?

**Comment by jimschubert** [comment]
@falk-stefan fix is to remove the option from the example. The example assumed use of the example spec. Any spec with different model names or targeting different language or framework options would require updates to any settings values. I think it's obvious in the other configurations in the example, but I agree the model constraint wouldn't be obvious to new users.

I've merged #8312 with the doc update.
