### ISSUE TITLE
[Question] DataType

### ISSUE THREAD

**Issue by devhl-labs** [OpenAPITools/openapi-generator#8313]
In C#, {{dataType}} returns `string`. For parameters that are not required, how do I get it to return `string?`

**Comment by macjohnny** [comment]
you could use `{{^required}}` 
https://github.com/OpenAPITools/openapi-generator/blob/caf52641f01539496876d716445b3d8e32d649e8/modules/openapi-generator/src/main/resources/typescript-angular/modelGeneric.mustache#L8
