### ISSUE TITLE
[erlang-client] Inline schema not handled

### ISSUE THREAD

**Issue by leonardb** [OpenAPITools/openapi-generator#832]
##### Description

When a body is defined in-line the 'type' is not automatically created and the body is excluded as a function argument

##### openapi-generator version

openapi-generator-cli.jar version
3.2.2-SNAPSHOT

##### OpenAPI declaration file content or url

https://gist.github.com/leonardb/7647fb11158b1d53a95dbffc079909ba

##### Command line used for generation

java -jar openapi-generator-cli.jar generate -i minimal.json -g erlang-client --additional-properties packageName=test

##### Steps to reproduce

generate the code and look at the `-spec` for add_pet/3 and add_pet2/2

in the first case (body by ref), the type is there and included
```erlang
-spec add_pet(ctx:ctx(), test_new_pet:test_new_pet(), maps:map()) -> {ok, test_pet:test_pet(), test_utils:response_info()} | {ok, hackney:client_ref()} | {error, term(), test_utils:response_info()}.
add_pet(Ctx, TestNewPet, Optional) ->
....
    Body1 = TestNewPet,
....
```
in the second case, the type and variable are excluded, but the `TestInlineObject` is included in the function body
```erlang
-spec add_pet2(ctx:ctx(), maps:map()) -> {ok, test_pet:test_pet(), test_utils:response_info()} | {ok, hackney:client_ref()} | {error, term(), test_utils:response_info()}.
add_pet2(Ctx, Optional) ->
....
    Body1 = TestInlineObject,
....
```

##### Suggest a fix/enhancement

This does not occur in swagger-codegen. In swagger-codegen the `type` is automatically created and included in the function arguments

**Comment by wing328** [comment]
@leonardb I tried the latest master and got the following:
```
-spec add_pet2(ctx:ctx(), openapi_inline_object:openapi_inline_object(), maps:map()) -> {ok, openapi_pet:openapi_pet(), openapi_utils:response_info()} | {ok, hackney:client_ref()} | {error, term(), openapi_utils:response_info()}.
add_pet2(Ctx, Pet, Optional) ->
    _OptionalParams = maps:get(params, Optional, #{}),
    Cfg = maps:get(cfg, Optional, application:get_env(kuberl, config, #{})),

    Method = post,
    Path = ["/pets2"],
    QS = [],
    Headers = [],
    Body1 = Pet,
``

Please give it another try and let me know if it's still an issue to you.
