### ISSUE TITLE
[BUG][Powershell] -WithHttpInfo ContentTypes issue

### ISSUE THREAD

**Issue by EngineerCoding** [OpenAPITools/openapi-generator#8329]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The `-WithHttpInfo` uses the `$Response.Headers['Content-Type']` which may not always be set. Therefore this may result in Null which is not accepted by the DeserializeResponse function.

##### openapi-generator version

v5.0.0

##### Steps to reproduce

1. Generate any Powershell client
2. Run -WithHttpInfo on an endpoint that doesnt set the content type

##### Suggest a fix
(ApiClient.ps1)
Either let DeserializeResponse accept null values or use the following for the content type:
```
$contentTypes = $Response.Headers["Content-Type"]
if ($null -eq $contentTypes) {
    $contentTypes = [string[]]@()
}

# Use this in subsequent DeserializeResponse
```

**Comment by wing328** [comment]
Please submit a PR with the suggested fix and we'll review accordingly
