### ISSUE TITLE
Support for RxSwift 6.0.0

### ISSUE THREAD

**Issue by vandadnp** [OpenAPITools/openapi-generator#8332]
RxSwift 6.0.0 has now been released and we want to move our entire project to using it. Would it be possible to add support for RxSwift 6.0.0 code generation?

**Comment by wing328** [comment]
Definitely, May I know if you've time to make the contribution? The swift5 template is a good starting point: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/swift5

**Comment by vandadnp** [comment]
@wing328 yes sure I’ll have a look at it
