### ISSUE TITLE
[BUG][ASPNETCORE] The aspnetcore generator doesn't generate essential authorization import 

### ISSUE THREAD

**Issue by leonluc-dev** [OpenAPITools/openapi-generator#8341]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description
The current version of the aspnetcore generator has an issue with authorized calls.

In ASP.NET authorized calls are marked with the Authorize attribute. The generator generates this properly:

```
[HttpGet]
[Route("/api/testauthorize")]
[Authorize]
[ValidateModelState]
public abstract IActionResult TestCall();
```

However, the required `using Microsoft.AspNetCore.Authorization;` directive is missing at the top of the generated file if Swashbuckle generation is disabled. This causes compilation to fail due to the Authorize attribute's dependency on this directive.

##### openapi-generator version
5.0.0

##### OpenAPI declaration file content or url

[Swagger.json](https://gist.github.com/leonluc-dev/d393750fbfa2f389e1c42454326a641e)
 
##### Generation Details
Example generation CLI command:

`java -jar openapi-generator-cli.jar generate -i ./swagger.json -g aspnetcore -o ./output  --additional-properties=generateBody=false,classModifier=abstract,aspnetCoreVersion=3.1,buildTarget=library,isLibrary=true,packageName=TestGeneratedStubs,useSwashbuckle=false `

##### Steps to reproduce

Generate a simple ASP.NET Core solution using the above swagger.json and cli command (the `useSwashbuckle=false` parameter is the important part).
Try to build the resulting project using the `dotnet build output/TestGeneratedStubs.sln` command

##### Suggest a fix

It seems the mustache template for the generated ASP.NET Core controllers has the `using Microsoft.AspNetCore.Authorization;` directive wrapped in a `useSwashbuckle` condition, even though the directive is often necessary even without swashbuckle enabled.
https://github.com/OpenAPITools/openapi-generator/blob/04dfff83e0717e693afb61499c62440491c1ac9c/modules/openapi-generator/src/main/resources/aspnetcore/3.0/controller.mustache#L9-L13

**Comment by wing328** [comment]
@leonluc-dev thanks for reporting the issue. Do you mind filing a PR with the suggested fix for us to review it more easily?

**Comment by leonluc-dev** [comment]
@wing328 I've filed a PR for the issue ( #8368 )
