### ISSUE TITLE
[BUG] Python not serializing enums correctly

### ISSUE THREAD

**Issue by cgfarmer4** [OpenAPITools/openapi-generator#8377]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I have an endpoint that accepts an enum as part of its request body. Whenever I pass `Products.allowed_values[('value',)]["TRANSACTIONS"]` as the value I get the failure:

```
E               name.exceptions.ApiTypeError: Invalid type for variable '0'. Required value type is Products and passed type was str at ['initial_products'][0]
```

Python model serialization fails when type is not `Products('transactions')`.

##### openapi-generator version

[Docker CLI v5 ](https://hub.docker.com/layers/openapitools/openapi-generator-cli/v5.0.0/images/sha256-d56af277878fa02d7f0e087e286973a7a060383c6cb13fadc55c1eb087b45807?context=explore)

##### OpenAPI declaration file content or url

```yaml

    initial_products:
      type: array
      items:
        $ref: '#/components/schemas/Products'
        
    Products:
      title: Products
      enum:
      - transactions
      type: string
```

##### Generation Details

```
docker run --rm -v /mydrive:/local openapitools/openapi-generator-cli:v5.0.0 generate -g python -i local/api.yml -o local/build/generated-python \
		-p packageName=name 
```

##### Steps to reproduce

Pass in `Products('transactions')` to the endpoint and get JSON as `{value: 'transactions'}`.  Should be just `'transactions'`.

Pass in `Products.allowed_values[('value',)]["TRANSACTIONS"]` and get the failure mentioned above.

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/issues/7058

**Comment by spacether** [comment]
So I see this working in our tests here:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L133
What version of openapi-generator are you using?

**Comment by spacether** [comment]
Values are strictly typed in the python generator. A string will not be accepted, you have to pass in an instance of Products.

**Comment by cgfarmer4** [comment]
> What version of openapi-generator are you using?
`openapitools/openapi-generator-cli:v5.0.0`
> Have you tried passing in `InitialProducts([Products('transactions')])`?
The request body is as follows:
```
    request = CreateRequest(
        initial_products=[Products('transactions')]
    )
```

`InitialProducts` is not a model, its simply a request body parameter name.

**Comment by spacether** [comment]
Can you provide the endoint definition also?

**Comment by cgfarmer4** [comment]
```yaml
SandboxPublicTokenCreateRequest:
  type: object
  properties:
    initial_products:
      type: array
      items:
        $ref: '#/components/schemas/Products'
            
/sandbox/public_token/create:
  post:
    requestBody:
      required: true
      description: ""
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/SandboxPublicTokenCreateRequest'
            
Products:
  title: Products
  enum:
  - transactions
  type: string
```

**Comment by spacether** [comment]
Thanks!

**Comment by spacether** [comment]
@cgfarmer4 can you try moving your initial_products definition into a component and $refing it?

**Comment by cgfarmer4** [comment]
Thanks so much for jumping in to fix here @spacether. Will keep an eye on the merge.

**Comment by spacether** [comment]
All merged

**Comment by cgfarmer4** [comment]
@spacether do you expect this to land in `5.1`? Looks like I'll get a new docker build tomorrow so Ill pull latest but hoping to settle on a version in the next month or so.

**Comment by spacether** [comment]
This should land in 5.0.1. How do you use versions of openapi generator?

**Comment by cgfarmer4** [comment]
Trying to stabilize on `5.0.0` as we have been using the betas to develop over the past few months. I'll make an exception for `python` and pull latest from docker CLI. Thanks again for jumping on this promptly!

**Comment by spacether** [comment]
You're welcome. Thank you for submitting the issue. :)
