### ISSUE TITLE
[BUG][Rust Client] Duplicated crate::models in Params struct

### ISSUE THREAD

**Issue by alesharik** [OpenAPITools/openapi-generator#8380]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
Generated rust client has duplicated `crate::models` string in enum field types. But rust doesn't like it and fails with `'crate' in paths can only be used in start position` in compilation phase. Also tested with `a` as query parameter, same results

##### openapi-generator version
5.0.0
5.0.1-SNAPSHOT
6.0.0-SNAPSHOT

##### OpenAPI declaration file content or url
```yaml
---
openapi: 3.0.1
info:
  title: v3
  version: 3.0.0
servers:
  - url: https://example.com
paths:
  /v3/{a}:
    get:
      parameters:
        - name: a
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/ReleaseType'
      responses:
        "200":
          description: search results matching criteria
components:
  schemas:
    ReleaseType:
      default: ga
      enum:
        - ga
        - ea
      type: string
```

##### Generation Details
Generator: `rust`
Config:
```json
{
  "library": "reqwest",
  "packageName": "api",
  "packageVersion": "1.0.0",
  "supportAsync": "true",
  "useSingleRequestParameter": "true"
}
```
##### Expected output (`src/apis/default_api.rs`)
```rust
/// struct for passing parameters to the method `v3_a_get`
#[derive(Clone, Debug)]
pub struct V3AGetParams {
    pub a: crate::models::ReleaseType
}
```

##### Actual output (`src/apis/default_api.rs`)
```rust
/// struct for passing parameters to the method `v3_a_get`
#[derive(Clone, Debug)]
pub struct V3AGetParams {
    pub a: crate::models::crate::models::ReleaseType
}
```

**Comment by ahl** [comment]
@alesharik can you try the code here to see if this work for you?

https://github.com/oxidecomputer/openapi-generator/tree/rust

**Comment by alesharik** [comment]
@ahl Hi! Yes, your code fixes this problem
