### ISSUE TITLE
[BUG] [OCaml] Generation of `unknown_base_type:UNKNOWN_BASE_TYPE` isn't valid

### ISSUE THREAD

**Issue by davesnx** [OpenAPITools/openapi-generator#8398]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The issue happens when I tried with stripe and github apis, which It could happen to any spec as well.

##### openapi-generator version

v5.0.0

##### OpenAPI declaration file content or url

https://github.com/stripe/openapi/blob/master/openapi/spec3.yaml

##### Generation Details

```bash
openapi-generator-cli generate -i stripe.yaml -g ocaml -o stripe --enable-post-process-file
```

##### Steps to reproduce

Run `dune build` inside the root project

##### Suggest a fix

The main issue happens to use a capital letter for a record type since OCaml reserves capital letters for variants. If it's as easy as renaming it, I would suggest using lower-case for the unknown-types.

**Comment by davesnx** [comment]
I'm not familiar with the project, but I might be able to give it a try. Is there anything you could guide me here? @cgensoul

I opened 2 issues regarding code-gen and both seem straight forward, but I can't be sure, seems the templating needs to change the formating to lower case?

**Comment by cgensoul** [comment]
Hello David,

I am not able to help you out much these days (being on holidays far from a
computer) but feel free to give it a try, I’ll review the code when I’ll
get back.

As a super rough guide though, there are only two kind of artefacts you
might touch : either the ocaml generator java source code (the only java
source file with OCaml in its name) or the moustache template files for the
aforementioned  generator (the project documentation should help you to
locate those files if you haven’t located them already).

Sorry for not being able to do more for now, I’ll look into it next week.

Christophe


Le ven. 15 janv. 2021 à 08:27, David Sancho <notifications@github.com> a
écrit :

**Comment by davesnx** [comment]
Hey @cgensoul, no worries and enjoy your vacations!

I will give it a shot and try to post any question that I might here.

Thanks for the fast response

**Comment by wing328** [comment]
@davesnx thanks for reporting the issue. This issue seems related: https://github.com/OpenAPITools/openapi-generator/issues/7922.

**Comment by wing328** [comment]
tested with https://github.com/OpenAPITools/openapi-generator/pull/12369 and no longer be able to repeat the issue.

**Comment by davesnx** [comment]
Thanks @wing328
