### ISSUE TITLE
[REQ] Upgrade Hyper/packages in Rust Client

### ISSUE THREAD

**Issue by andrew-s** [OpenAPITools/openapi-generator#8400]
### Is your feature request related to a problem? Please describe.

The hyper package used in the rust client "rust" generator is very old, sat at version 0.11 - there was a big shift in the way it works between 0.11 and 0.12. It makes sense to upgrade this to 0.14.

## Describe the solution you'd like

Upgrade the package to a newer version beyond 0.12

## Describe alternatives you've considered

The alternative to not upgrading is a real pain, where my application relies heavily upon `hyper` so I have that package within my application - to work with an older version I'd need to import `hyper 0.11` and the `tokio_core` packages (for the handler to connect). It was easier to just use `reqwest` (1 extra library vs 2) however, it would be nice to not have to use any extra packages when I already have a newer hyper on hand.

Granted, I need to make these changes because I'm changing the default configuration of `apis` within my application, as the `Configuration` struct is immutable I'm unable to change it after the fact. Ideally, configuration should be decoupled from the http client library creation but, that's probably a larger task than it is to just upgrade the packages (also unsure how other packages are built and if `configuration + client` is a commonality)

**Comment by DartMen** [comment]
I as well feel some pain using the outdated hyper package. 

Any progress on this request?

**Comment by softdevca** [comment]
Pull request #9919 addresses this issue. Please consider testing the changes if you are able.
