### ISSUE TITLE
[BUG] Dart dio-http DateTime serialization parameterToString becomes weird JSON serialized object 

### ISSUE THREAD

**Issue by gerardsimons** [OpenAPITools/openapi-generator#8407]
##### Description

The code generator works just fine for dart-dio but I am getting some strange datetime serialization. I was expecting some kind of ISO date string but rather it becomes this weird JSON serialized string when I use a DateTime type

`{\"$\":\"DateTime\",\"\":\"2021-01-11T11:30:52.387885Z\"}`

That looks more like a raw data dump than something you would want to send to the server. 

##### openapi-generator version

I am using version 5.0.0 of the NPM tool

##### OpenAPI declaration file content or url

The OpenAPI really isn't the issue but here is a sample that I use for datetime stuff

```yaml
Measurement:
      title: Measurement
      type: object
      properties:
        type:
          type: string
        startTime:
          type: string
          format: date-time
          example: '2021-01-30T08:30:00Z'
        annotations:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/Annotation'
        endTime:
          type: string
          format: date-time
          example: '2021-02-08T09:30:12Z'
        id:
          type: integer
        blobUrl:
          type: string
          format: uri
          description: ''
        blob:
          type: string
          format: binary
        orgId:
          type: string
        deviceConfigId:
          type: string
      required:
        - type
        - startTime
        - endTime
```

##### Generation Details

Nothing special:

`openapi-generator-cli generate -g dart-dio -i <...>`

##### Steps to reproduce

Define any object with datetime and observe the default serialization in `default_api.dart` 

`formData[r'startTime'] = parameterToString(_serializers, startTime);`

##### Related issues/PRs

Nope

##### Suggest a fix

I think the serializer should just take the datetime ISO string, but drop the rest. I did that now by adding a clause to `parameterToString` function so it looks like this:

```dart
String parameterToString(Serializers serializers, dynamic value) {
	if (value == null) {
		return '';
	} else if (value is String || value is num) {
		return value.toString();
	}else if (value is DateTime) {
		return value.toIso8601String();
	} else {
		final val = serializers.serialize(value);
		return json.encode(val);
	}
}
```

**Comment by kuhnroyal** [comment]
Duplicate of https://github.com/OpenAPITools/openapi-generator/issues/8271

**Comment by gerardsimons** [comment]
Very true @kuhnroyal . Sorry I missed that. I can close this issue
