### ISSUE TITLE
[BUG] kotlin-spring generator doesn't generate comments on api methods

### ISSUE THREAD

**Issue by rainmanhhh** [OpenAPITools/openapi-generator#8424]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
kotlin-spring generator doesn't generate comments on api methods(but java spring generator does)

##### openapi-generator version

5.0.0

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: TRTC
  description: TRTC
  version: 1.0.0
  contact:
    name: sfy
servers:
  - url: 'http://localhost:8080'
paths:
  '/userSignature/{userId}':
    get:
      summary: generate signature for user
      tags:
        - TRTC
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
      operationId: get-userSignature
      description: generate signature for user with sha256
      parameters:
        - schema:
            type: string
          in: query
          name: test
          description: Test param
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        description: id of user
        required: true
tags:
  - name: TRTC
```

##### Generation Details

config.yaml:
```yaml
apiPackage: trtc.apis
artifactId: trtc-server-api
basePackage: trtc
bigDecimalAsString: true
booleanGetterPrefix: true
configPackage: trtc.config
dateLibrary: java8
ensureUniqueParams: false
groupId: trtc
hideGenerationTimestamp: true
interfaceOnly: false
modelPackage: trtc.models
serviceInterface: true
title: trtc-server-api
unhandledException: true
useTags: true
```

**Comment by wing328** [comment]
> kotlin-spring generator doesn't generate comments on api methods(but java spring generator does)

I wonder if you've time to file a PR to port those comments in java spring generator's template to the one in kotlin-spring

**Comment by rainmanhhh** [comment]
> > kotlin-spring generator doesn't generate comments on api methods(but java spring generator does)
> 
> I wonder if you've time to file a PR to port those comments in java spring generator's template to the one in kotlin-spring

sorry but I'm not familiar with openapi-generator template.
BTS, java-spring comments are in Controller files, but kotlin-spring commentes should be generated into Api files(XXXApiService.kt which contain interfaces), so that those who write XXXApiServiceImpl could see comments inherited from parent interface XXXApiService

**Comment by wing328** [comment]
no worry. let's see if anyone from the community can help out on this.

kotlin-spring templates: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/kotlin-spring
java spring templates: https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/JavaSpring
