### ISSUE TITLE
[REQ] Update OkHTTP dependency

### ISSUE THREAD

**Issue by cgfarmer4** [OpenAPITools/openapi-generator#8425]
### Is your feature request related to a problem? Please describe.

https://github.com/plaid/plaid-java/issues/257

## Describe the solution you'd like

The OkHTTP dependency updated for Java to latest.

## Describe alternatives you've considered

Manual updates inside of the templates or a forked version of the generator.

**Comment by wing328** [comment]
May I know if you've time to contribute a PR to update the dependencies to newer versions?

https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson is a good starting point.

**Comment by cgfarmer4** [comment]
hi @wing328, unfortunately I dont have the bandwidth or enough Java experience to make this update without creating regressions in the process.

**Comment by wing328** [comment]
That's ok. Let's see someone from the community has time to contribute the enhancement.

(of course you can also sponsor the task to give it a higher priority)

**Comment by cgfarmer4** [comment]
@wing328 how would we go about sponsoring this request? Think we could do that.

**Comment by wing328** [comment]
I've added an FAQ about sponsorship: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-sponsor-a-task-eg-bug-fixes-enhancements-new-generators-etc

Please have a look and let me know if you've further questions.

**Comment by GORA-SAG** [comment]
Hi @wing328 can you explain a bit on what to do for this enhancement. I will take this forward.

**Comment by wing328** [comment]
https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson is a good starting point.

Then you will need to compile the project (`mvn clean package -DskipTests`) and update the samples (`./bin/generate-samples.sh`) so that CI can verify the change.
