### ISSUE TITLE
[REQ] [typescript-axios] Bump axios to version v0.21.1

### ISSUE THREAD

**Issue by codyhutchens** [OpenAPITools/openapi-generator#8432]
### Is your feature request related to a problem? Please describe.

Axios version v0.19.2 has known Server-Side Request Forgery vulnerability
https://github.com/axios/axios/issues/3407
https://snyk.io/vuln/SNYK-JS-AXIOS-1038255

## Describe the solution you'd like

This can be fixed by bumping the version in the package.mustache to 0.21.1 for typescript-axios

## Describe alternatives you've considered

After generating the code, do an update to version v0.21.1

**Comment by macjohnny** [comment]
would you like to fix this?

**Comment by StefanCenusa** [comment]
I've added this [PR](https://github.com/OpenAPITools/openapi-generator/pull/8445) to fix this issue.

cc: @macjohnny

**Comment by codyhutchens** [comment]
Thanks for getting that done so fast. I was trying to do it myself but I had some issues with the tests failing for the typescript-axios pet store sample. I was getting 404s and I feel like I was missing a step. lol

**Comment by StefanCenusa** [comment]
@macjohnny When will this fix be available on the `openapi-generator-cli` npm package? Thanks!

**Comment by macjohnny** [comment]
probably in february, see https://github.com/OpenAPITools/openapi-generator/milestone/33

if you want to use it now, you can use the latest snapshot version: https://oss.sonatype.org/content/repositories/snapshots/org/openapitools/openapi-generator-cli/5.0.1-SNAPSHOT/
