### ISSUE TITLE
[BUG] MavenReportException: Error while generating Javadoc

### ISSUE THREAD

**Issue by spacether** [OpenAPITools/openapi-generator#8455]
#### Bug Report Checklist

Unable to run `mvn clean install` without getting this error:
```
MavenReportException: Error while generating Javadoc: Project contains Javadoc Warnings
```
on master branch

Environment:
```
justins-air:openapi-generator justinblack$ mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 10.0.2, vendor: Oracle Corporation, runtime: /Users/justinblack/.sdkman/candidates/java/10.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"

justins-air:openapi-generator justinblack$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment 18.3 (build 10.0.2+13)
OpenJDK 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

**Comment by spacether** [comment]
This was happening because I had the wrong version of java installed.
Using Java 8 or Java 11 works.
When I switched to Java 11 this issue went away.
The readme says to use Java 8.

**Comment by averche** [comment]
I had the same error message. Switching to Java 11 did not resolve the issue for me but using the [maven docker image](https://hub.docker.com/_/maven/) did the trick:

```shell-session
docker run -it --rm --name my-maven-project -v "$(pwd)":/usr/src/mymaven -w /usr/src/mymaven maven:3.3-jdk-8 mvn clean install
```
