### ISSUE TITLE
[BUG] Using `allOf` and `$ref` generates an `object` in the python model when it should be a `string`

### ISSUE THREAD

**Issue by cgfarmer4** [OpenAPITools/openapi-generator#8457]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### openapi-generator version

Docker CLI latest

##### OpenAPI declaration file content or url

```yaml

BankTransferCreateRequest:
  title: BankTransferCreateRequest
  type: object
  description: BankTransferCreateRequest defines the request schema for `/bank_transfer/create`
  properties:
    access_token:
      description: Some Description
      allOf:
        - $ref: '#/components/schemas/AccessToken'
 
AccessToken:
  title: AccessToken
  type: string
  description: The access token associated with the Item data is being requested for.

/bank_transfer/create:
  post:
    operationId: bankTransferCreate
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BankTransferCreateRequest'

```

##### Generation Details

$(OPENAPI_GENERATOR_LATEST) -g python -i local/$(OPENAPI_FILE) -o local/$(OUTPUT_FOLDER)/generated-python 

##### Steps to reproduce

Run the generator, try accessing the `BankTransferCreateRequest` model. See that `access_token` is `object` instead of `string`.

```python
return {
    'access_token': (object,),  # noqa: E501
}
```

**Comment by spacether** [comment]
Why not change your spec to have access_token point directly to the referenced #/components/schemas/AccessToken without using allOf? That should solve your problem.

**Comment by cgfarmer4** [comment]
@spacether reading here: 

https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

All of should reference the subschema and its not. Its transforming it to object when the `$ref` schema is a string.

**Comment by spacether** [comment]
Yes, I agree that there is a bug here.
Inline composed schemas are not yet very well supported in openapi-generator.

My suggestion is a work around which may work for you.
Another work-around would be to place your composed schema in a component and ref it.

**Comment by cgfarmer4** [comment]
Oh I see. Yep that does fix my problem :D!

**Comment by cgfarmer4** [comment]
Hmm spoke too soon. Any timeline on better `$ref` support? Can workaround for now, just curious

**Comment by spacether** [comment]
No firm timeline here. I am slowly working on a number of improvementss to the Python generator in a new generator python-experimental. This feature will be included in that.

**Comment by spacether** [comment]
For this use case you and delete your AccessToken schema and just define it as `type: string` in BankTransferCreateRequest.access_token. Python does not produce a model because it is an alias to a primitive type and does not include any validations or enums. If there is a validation or enum in AccessToken it will be made as a model.

**Comment by cgfarmer4** [comment]
@spacether I see. May have to make a workaround for just `python`. We'd prefer not to have to hack for one language as we are generating a bunch of things with this file.

**Comment by cgfarmer4** [comment]
Ruby, Node, Python, Go, Java and js client side SwaggerParser for our docs.

Ive run into another issue with using `anyOf` again today and have confirmed its only `python` and doesn't effect ruby/node. Dont have the other ones tested yet.

**Comment by cgfarmer4** [comment]
Going off the Swagger docs this format should be valid.

**Comment by spacether** [comment]
It is a valid spec, our tooling just isn't there yet.
The main composed schema use case that the generator supports is a component object schema that contains allOf or oneOf or anyOf.
Additionally, python supports the use cases where:
- oneOf can have mixed types
- allOf is combined with oneOf or anyOf

**Comment by cgfarmer4** [comment]
I think we have a workaround for now. Thanks for talking through it @spacether!! Hoping to get a sponsorship going here soon for you all.

**Comment by alfechner** [comment]
I've got the same issue but slightly different. I've got a `$ref` to a schema of type object.

```yaml
PatientScanDto:
  type: object
  patient:
  allOf:
    - $ref: '#/components/schemas/PatientInfoDto'
  nullable: true
  readOnly: true
```

```yaml
PatientInfoDto:
  type: object
  properties:
    patientId:
      type: string
```

Python classes `PatientScanDto` and `PatientInfoDto` are generated appropriately.

However the property `patient` in class `PatientScanDto` has the wrong type.

In generator version `5.1.0` the type is `object` which causes an `ApiValueError: Unsupported type: <class 'object'>`.

Generator version `5.1.1` considers `patient` to be of type `dict`. While that doesn't raise an exception it is the wrong type and accessing properties from a dict works probably around type checks.

**Comment by spacether** [comment]
If you define patient as its own component and then $ref to patient in PatientScanDto does this work?
I suspect that this is an openapi inline schema issue and is not specific to the python generator.

**Comment by spacether** [comment]
Just for clarity here, I want to describe the openapi definition of your specs
@cgfarmer4 
```
BankTransferCreateRequest:
  type: object
  properties:
    access_token:
      description: Some Description
      allOf:
        - $ref: '#/components/schemas/AccessToken'
 
AccessToken:
  type: string
```
BankTransferCreateRequest.access_token does not define a type so it allows in any type in the 
BankTransferCreateRequest.access_token schema. The allOf schema which must also be validated against further constrains the property to be type string only.

@alfechner 
```
PatientScanDto:
  type: object
  patient:
  allOf:
    - $ref: '#/components/schemas/PatientInfoDto'
  nullable: true
  readOnly: true

PatientInfoDto:
  type: object
  properties:
    patientId:
      type: string
```
PatientScanDto seeks to allow in type object and type null. However because PatientInfoDto further constrains the payload to only be type object, type null will never pass the validations of both PatientScanDto AND PatientInfoDto schemas.

**Comment by spacether** [comment]
This is working in the [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/1f7eebd52d495e1a9843467ab6046c2726358fec/docs/generators/python-experimental.md#metadata) generator.
In the [Cat schema](https://github.com/OpenAPITools/openapi-generator/blob/1f7eebd52d495e1a9843467ab6046c2726358fec/modules/openapi-generator/src/test/resources/3_0/python-experimental/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml#L1734) Cat is anyType where the allOf schemas in it will only allow in type: object payloads.
One can see this in the [Cat model](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/model/cat.py#L62) which inherits from [ComposedSchema](https://github.com/OpenAPITools/openapi-generator/blob/1f7eebd52d495e1a9843467ab6046c2726358fec/samples/openapi3/client/petstore/python-experimental/petstore_api/schemas.py#L1638) which allows in any type.  And the [Animal](https://github.com/OpenAPITools/openapi-generator/blob/1f7eebd52d495e1a9843467ab6046c2726358fec/samples/openapi3/client/petstore/python-experimental/petstore_api/model/animal.py#L62) and [CatAllOf](https://github.com/OpenAPITools/openapi-generator/blob/1f7eebd52d495e1a9843467ab6046c2726358fec/samples/openapi3/client/petstore/python-experimental/petstore_api/model/cat_all_of.py#L61) classes which are also validated against are constrained to type object, shown by their

**Comment by alfechner** [comment]
@spacether thanks for your reply, you are right, `allOf` was supposed to be indented. I fixed that.

I guess you're also right about your assumption that it's an inline issue. You mentioned that in an older answer already. In my use case the spec is generated by another framework with inline objects and then serves to generated kind of a proxy server. Currently I need to modify the spec manually before generating the server.

**Comment by spacether** [comment]
Can you try your spec with python-experimental and see if it works?

In the future I will add more inline examples to the python-experimental generator to see how well it is handling them in all locations. Endpoints are definitely sometimes generating inline schemas in the endpoint files. If any locations are not working I will have to turn the inline model resolver off for python experimental so the generator will handle the spec exactly as it was defined by the user.

**Comment by spacether** [comment]
Re opening this until examples have been added in python-experimental verifying that this is working at levels deeper than a root component with compositions. Tests are needed of:
1. component property with composition
2. parameter with composition
3. request body with composition
4. response body with composition
5. parameter property with composition
6. request body property with composition
7. response body property with composition

**Comment by spacether** [comment]
The merged PR https://github.com/OpenAPITools/openapi-generator/pull/11420
adds verification schemas and test of 

- component property with composition
- parameter with composition
- request body with composition
- response body with composition
- parameter property with composition
- request body property with composition
- response body property with composition

So this feature works in `python-experimental`
Closing this issue because we have a python client generator which supports this inline composed schema use case
