### ISSUE TITLE
[Bug Bounty] Fix a bug related to binary response in csharp-netcore client

### ISSUE THREAD

**Issue by DeniskaAbr** [OpenAPITools/openapi-generator#8524]
I am generate APIClient With "-g csharp-netcore --additional-properties=targetFramework=netstandard2.1,netCoreProjectFile=true" parameters.

OpenApi specification contains  
`"responses": {
          "200": {
            "description": "Success",
            "content": {
              "image/jpeg": {
                "schema": {
                  "type": "string",
                  "format": "binary"
                }
              }
            }
          },
`

In backend server endpoint:

`   public async Task<IActionResult> GetAvatar()
        { var result = await _service.GetAvatar();
            if (result == null) return NoContent();
            var (content, contentType) = result.Value;
            return File(content, contentType);
        }
`

`  public async Task<(byte[], string)?> GetAvatar()
        {   var user = await _userManager.GetUserAsync(_claims);
            var profile = user.Profile;
            var avatar = profile.Avatar;
            var content = Convert.FromBase64String(avatar.File.Content);
            var contentType = avatar.File.ContentType;
            return (content, contentType);
        }
`

After fetch data from server with _apiService.ProfileApi.ApiProfileGetAvatarGet() in request no Data. In Client request is transformed as 
![изображение](https://user-images.githubusercontent.com/68537068/105634924-7ad49680-5e71-11eb-95a6-2d3ee29e3546.png)
![изображение](https://user-images.githubusercontent.com/68537068/105634933-858f2b80-5e71-11eb-90e2-e2fd5d7b3750.png)

How to use generator? Need byte[] or Stream byte[] in request. And uploading for upload binary files in multipart/form-data? In 91 row in generator is contains code for checking datatype https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/csharp-netcore/ApiClient.mustache

Why is there an attempt to deserialize what am I doing wrong?

My sponsorship for this request is 50$

UPDATED: Also not work fetch multiple type data from response. Generator supported ASP.NET Core ProblemDetails? 

Example (see StatusCodes.Status400BadRequest):

```
HttpPatch]
[Route("[action]")]
[Authorize(Roles = "User,Admin")]
[ProducesResponseType(StatusCodes.Status200OK)]
[ProducesResponseType(typeof(IdentityProblemDetails), StatusCodes.Status400BadRequest)]
[ProducesResponseType(typeof(LanguageUsageProblemDetails), StatusCodes.Status400BadRequest)]
[ProducesResponseType(typeof(LanguageNotFoundProblemDetails), StatusCodes.Status404NotFound)]
public async Task<OkResult> UpdateProfile(UpdateProfileModel model)
{
await _service.UpdateProfile(model);

return Ok();
}

```

**Comment by wing328** [comment]
cc @mandrean (2017/08) @frankyjuang (2019/09) @shibayan (2020/02) (C# tech committee)

**Comment by wing328** [comment]
Given that no one have time to work on this bug bounty after a week, I'll give it a try to come up with a fix.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/issues/8524 to fix the issue. My local test result looks good.

**Comment by DeniskaAbr** [comment]
How to make build with this fix for testing?

**Comment by wing328** [comment]
```
git clone -b csharp-fix-binary-response https://github.com/OpenAPITools/openapi-generator
cd openapi-generator
./mvnw clean package
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate  -i your_spec.yaml -g csharp-netcore --additional-properties=targetFramework=netstandard2.1,netCoreProjectFile=true -o C:\temp\client\
```
(assuming you're using Windows and you've GIT bash installed)

**Comment by DeniskaAbr** [comment]
Not working with binary format
![изображение](https://user-images.githubusercontent.com/68537068/107614683-d9648780-6c5b-11eb-804d-923b46b6ee67.png)
