### ISSUE TITLE
[REQ] Java vertx template should be deprecated

### ISSUE THREAD

**Issue by slinkydeveloper** [OpenAPITools/openapi-generator#8527]
### Is your feature request related to a problem? Please describe.

Java vertx uses a library which is not maintained anymore since 2 years https://github.com/phiz71/vertx-swagger and doesn't work with recent Vert.x. This template should be marked as deprecated and [java-vertx-web](https://github.com/OpenAPITools/openapi-generator/tree/master/samples/server/petstore/java-vertx-web) (the one updated to latest Vert.x) should be suggested instead in the generators list: https://openapi-generator.tech/docs/generators/

## Describe the solution you'd like

Mark as deprecated the old java-vertx template

**Comment by slinkydeveloper** [comment]
@wing328 Any way i can help here? Can you point me out how I can mark a generator as deprecated?

**Comment by wing328** [comment]
@slinkydeveloper thanks for offering help. The goal is to mark `java-vertx` as deprecated and mark `java-vertx-web` as stable, right?

**Comment by slinkydeveloper** [comment]
> The goal is to mark java-vertx as deprecated and mark java-vertx-web as stable, right?

Yep, or better, we can mark java-vertx-web as stable in a second moment, but marking java-vertx ad deprecated IMO it's important to don't lead users to already old code.

**Comment by wing328** [comment]
OK. Let me do it later today.

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/8609

**Comment by phiz71** [comment]
Hi. I agree with @slinkydeveloper. The generator I did should be deprecated.
I will add a note on my project's README.
