### ISSUE TITLE
[BUG] Gradle deprecation warning, scheduled for removal in Gradle 7.0

### ISSUE THREAD

**Issue by patricklucas** [OpenAPITools/openapi-generator#8530]
##### Description

When I build a Java client using 5.0.0 of the Gradle plugin, I receive the following warning:

```
Property 'input' annotated with @Internal should not be also annotated with @Input. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.7.1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

This appears to be referring to [this property](https://github.com/OpenAPITools/openapi-generator/blob/v5.0.0/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/GenerateTask.kt#L83-L90) in `GenerateTask.kt`, complaining that the `@get:Internal` and `@Input` annotations should not be used on the same property.

This isn't a blocking issue for me now, but will presumably cause builds to fail once Gradle 7 is released. (I'm not sure of the Gradle 7 release timeline, though more time has passed since the 6.0 release than the duration between the 5.0 and 6.0 releases)

##### openapi-generator version

5.0.0 of the Gradle plugin

##### OpenAPI declaration file content or url

Unrelated to a particular spec, but in case it helps: https://developer.here.com/documentation/geocoding-search-api/swagger/open-search-v1-external-spec.json

##### Generation Details

Gradle 6.7.1

```gradle
openApiGenerate {
  generatorName = 'java'
  inputSpec = "${projectDir}/src/main/resources/here-geocoding-search-api-v1.json"
  outputDir = "${buildDir}/generated"
  apiPackage = 'com.here.geocoding.api'
  invokerPackage = 'com.here.geocoding.invoker'
  modelPackage = 'com.here.geocoding.model'
  configOptions = [
    dateLibrary: 'java8'
  ]
}
```

##### Steps to reproduce

Run a build using the configuration above on Gradle >= 6.7.1 and you should receive the warning.

##### Related issues/PRs

I was unable to find one using the text from the warning, apologies if this is a duplicate.

##### Suggest a fix

I'm not familiar enough with Gradle plugin programming to suggest a fix.

**Comment by phejl** [comment]
There seems to be this PR https://github.com/OpenAPITools/openapi-generator/pull/9059

**Comment by wing328** [comment]
Please see https://github.com/OpenAPITools/openapi-generator/issues/9253
