### ISSUE TITLE
[BUG][Dart] How to force generator to use String instead of EnumClass for enums

### ISSUE THREAD

**Issue by vasilich6107** [OpenAPITools/openapi-generator#8536]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
I'm trying to use `--type-mappings enum=String` to force generator to use `String` instead of `EnumClass` for enums.
But there is no difference in output. May be I'm doing something wrong...

##### openapi-generator version
5.0.0

##### OpenAPI declaration file content or url
Gist with json schema
https://gist.github.com/vasilich6107/c511a8e185e4a8aac4d7112e8282fa9d

##### OpenAPI declaration file content or url

```yaml
pubName: api
pubVersion: 1.0.0+1
pubDescription: "api"
```

##### Generation Details

`java -jar openapi-generator-cli.jar generate -i api.json -g dart-dio -c config.yaml --enable-post-process-file --type-mappings enum=String`

##### Steps to reproduce

1. Run open api generation

**Comment by kuhnroyal** [comment]
I am not sure what you are trying to achieve but this is not how it works.
`enum` is not a type in OpenAPI, which means you can not map it:

```yaml
schema:
    type: string
    enum: [asc, desc]
```

Besides that, I don't see a way to generate enums as Strings with dio/built_value atm.
Your best bet is to modify your spec by removing the `enum: ...`. That should result in a String field but then it is no enumeration anymore.

**Comment by vasilich6107** [comment]
Thanks for the reply!

**Comment by kuhnroyal** [comment]
I think this can be closed unless you need more clarification. I don't think there is much we can do.

**Comment by ktnishide** [comment]
I am not sure if this is related but...

Is there any workaround for handling an array of enums on query parameters like below? 
![image](https://user-images.githubusercontent.com/39504484/148490454-7293033b-1b66-4b26-9e5e-c8284d1190fa.png)


I am getting the following error:

```
[log] type 'String' is not a subtype of type 'SearchType' in type cast
[log] #0      _CastListBase.[] (dart:_internal/cast.dart:99:46)
#1      ListMixin.elementAt (dart:collection/list.dart:78:33)
#2      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#3      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#4      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#5      new List.of (dart:core-patch/array_patch.dart:51:28)
#6      encodeCollectionQueryParameter
package:studentedge_app/src/api_util.dart:75
```
