### ISSUE TITLE
Simpler json response

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#856]
##### Description

When adding an example to the spec and generating the documentation, I have such answer:

```
{
  "name" : "{\"value\":\"Martin Delille\"}",
  "id" : "{\"value\":\"01srv001\”}”
}
```

Would it be possible to have less verbose answer like:

```
{
  "name" : "Martin Delille",
  "id" : "01srv001”
}
```

##### openapi-generator version

`3.2.2-SNAPSHOT`

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  description: This is OpenAPI test
  version: 1.0.0
  title: OpenAPI test
  contact:
    url: https://github.com/MartinDelille/openapi-test
    email: "martin@lylo.tv"
components:
  schemas:
    User:
      title: An user
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example:
            value: '01srv001'
        name:
          type: string
          example:
            value: 'Martin Delille'
paths:
  /users/me:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
```

##### Command line used for generation

```
$ openapi-generator generate -i api.yaml -g html -o html
```

##### Steps to reproduce

1. Generate the doc
1. Look at the generated doc example for the `/users/me` route (https://martindelille.github.io/openapi-test/#usersMeGet)

##### Related issues/PRs

Not that I now

##### Suggest a fix/enhancement

I don't know if we can fix this since it might be part of the OpenAPI specification.

**Comment by jmini** [comment]
Have you tried the other static html generator ? 

I think it is called `html2`

**Comment by jmini** [comment]
> I don't know if we can fix this since it might be part of the OpenAPI specification.

I had a look at what https://editor.swagger.io/ is displaying for your spec. And I think that your spec not defining the example as expected.

If your property is just a string, then your example must also be a string. So like this:

```yaml
openapi: 3.0.1
info:
  description: This is OpenAPI test
  version: 1.0.0
  title: OpenAPI test
  contact:
    url: https://github.com/MartinDelille/openapi-test
    email: "martin@lylo.tv"
components:
  schemas:
    User:
      title: An user
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: '01srv001'
        name:
          type: string
          example: 'Martin Delille'
paths:
  /users/me:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
```

Because you have indicated the example value to be `value: '01srv001'`, then you get this value (converted to JSON and then escaped) in the HTML spec generated by OpenAPI Generator. 

This makes sense to me.

**Comment by MartinDelille** [comment]
Ok thanks ! That was the trick!
