### ISSUE TITLE
[BUG][JAVA] AbstractOpenApiSchema package output and declaration missmatch

### ISSUE THREAD

**Issue by BenjaminKlatt** [OpenAPITools/openapi-generator#8583]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
The class AbstractOpenApiSchema is generated into the model package but declares a model package within the invoker package

Not sure if you prefer a pull request over a bug report. so starting with a bug report and a suggested fix below,

##### openapi-generator version
openapi-generator-maven-plugin 5.0.0

##### OpenAPI declaration file content or url
Does not depend on a specific openapi spec

##### Generation Details
Maven Plugin Configuration
```xml
<plugin>
	<groupId>org.openapitools</groupId>
	<artifactId>openapi-generator-maven-plugin</artifactId>
	<version>5.0.0</version>
	<executions>
		<execution>
			<goals>
				<goal>generate</goal>
			</goals>
			<configuration>
				<generatorName>java</generatorName>
				<inputSpec>${openapi.spec.path}</inputSpec>
				<apiPackage>com.example.api</apiPackage>
				<invokerPackage>com.example.invoker</invokerPackage>
				<modelPackage>com.example.model</modelPackage>
				<configOptions>
					<library>native</library>
					<dateLibrary>java8</dateLibrary>
				</configOptions>
			</configuration>
		</execution>
	</executions>
</plugin>
```

##### Steps to reproduce

1. add plugin definition above to a maven project's pom
2. reference any json based openapi spec as ${openapi.spec.path} property
3. run mvn mvn clean generate-sources
4. check AbstractOpenApiSchema.java file for valid package declaration (is generated into com.example.model but declares com.example.invoker.model as package

##### Related issues/PRs
-

##### Suggest a fix
Depending the result expected, the mustach template should use the model package declaration instead of {{invokerPackage}}.model
https://github.com/OpenAPITools/openapi-generator/blob/edf153eedef58bd04ffa02a56ecbe60a7165bf0f/modules/openapi-generator/src/main/resources/Java/libraries/native/AbstractOpenApiSchema.mustache#L3
as this is also the case in the native petstore example: https://github.com/OpenAPITools/openapi-generator/blob/edf153eedef58bd04ffa02a56ecbe60a7165bf0f/samples/client/petstore/java/native/src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java

**Comment by wing328** [comment]
@BenjaminKlatt thanks for reporting the issue. I wonder if you can file a PR with the suggested fix so that we can review the fix more easily?

**Comment by BenjaminKlatt** [comment]
> @BenjaminKlatt thanks for reporting the issue. I wonder if you can file a PR with the suggested fix so that we can review the fix more easily?

@wing328 yes, I will prepare one

**Comment by BenjaminKlatt** [comment]
PR created: https://github.com/OpenAPITools/openapi-generator/pull/8635
