### ISSUE TITLE
[Q] How can I run openApiGenerate twice in gradle?

### ISSUE THREAD

**Issue by falk-stefan** [OpenAPITools/openapi-generator#8592]
So far, I generated the code for my web client like this:

```groovy
openApiGenerate {
    generatorName = 'typescript-angular'
    inputSpec = webSwaggerFilePath
    outputDir = webApiClientOutputDir
    configOptions = [
            npmName   : 'web-rest-client',
            npmVersion: '0.0.0',
            ngVersion : '11.0.6'
    ]
}

// I created a dependency like this:
tasks.getByName('openApiGenerate').dependsOn(tasks.generateSwaggerYaml)
```

This has been working so far but I am now at a point where I need to generate another client.

However, I have no idea how I can run `openApiGenerate` twice using `org.openapi.generator:5.0.0`. The following would be how I'd configure both tasks:

```groovy
openApiGenerate {
    generatorName = 'typescript-angular'
    inputSpec = webSwaggerFilePath
    outputDir = webApiClientOutputDir
    configOptions = [
            npmName   : 'web-rest-client',
            npmVersion: '0.0.0',
            ngVersion : '11.0.6'
    ]
}

openApiGenerate {
    generatorName = 'java'
    inputSpec = banalSwaggerFilePath
    outputDir = banalApiClientOutputDir
    configOptions = [
            npmName   : 'banal-rest-client'
    ]
}
```

But, obviously, I cannot create a depdendency the way I did before. How would I do that?

**Comment by agilob** [comment]
In gradle you have have a task and task type. What you want here is to create two tasks of the same type and run them twice. This is SO question not issue for repo.

It would be something like
```
task generateJava(type: org.openapi.generator.task_name_here {
    generatorName = 'java'
    inputSpec = banalSwaggerFilePath
    outputDir = banalApiClientOutputDir
    configOptions = [
            npmName   : 'banal-rest-client'
    ]
}
```

**Comment by agilob** [comment]
pls close

**Comment by falk-stefan** [comment]
@agilob Thank you!

**Comment by falk-stefan** [comment]
Unfortunately, this is not working. I'm getting

```none
A problem occurred evaluating root project 'server-client-template'.
> Could not get unknown property 'org' for root project 'server-client-template' of type org.gradle.api.Project.
```

Which appears to be related to https://discuss.gradle.org/t/could-not-get-unknown-property-task-error/18556

**Comment by agilob** [comment]
I noticed this question is often asked here and on stackoverflow, I wrote a quick post about it https://b.agilob.net/programming/java/gradle-two-tasks-openapi/

**Comment by RingoDev** [comment]
Just as a heads-up for anyone stumblin into this. If you specify the same output or overlapping directories for both gradle tasks, gradle will not cache the results and run the generation on every re-build even if it wouldn't be necessary.
