### ISSUE TITLE
New Generator: Crystal client generator

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#86]
If anyone is interested in contributing a [Crystal](https://crystal-lang.org/) client generator, please reply to let us know. We can use reverse engineering to create the Crystal generator and template based on a functional Crystal Petstore client similar to what we did before for PowerShell, Lua, etc.

Please reply to let us know if you want to work on this. Thanks.

**Comment by impatienttraveller** [comment]
Hi, anyone working on this? I may be able to help

**Comment by ddcprg** [comment]
Hi, anyone working on this yet? I may be able to help

**Comment by wing328** [comment]
@ddcprg I don't think anyone has started on this yet.

Do you mind PM'ing me on Slack so that we can formulate a plan?

https://join.slack.com/t/openapi-generator/shared_invite/enQtNzAyNDMyOTU0OTE1LTY5ZDBiNDI5NzI5ZjQ1Y2E5OWVjMjZkYzY1ZGM2MWQ4YWFjMzcyNDY5MGI4NjQxNDBiMTlmZTc5NjY2ZTQ5MGM

**Comment by wing328** [comment]
Similar to how some other generators (e.g. R, Lua, PowerShell) are created, we will use the reverse engineering process to create the Crystal client generator.

- create NodeJS Express petstore server samples (implemented at least 2 endpoints to start with: getPetById, addPet)
- reverse engineer the templates and the generator (Java class)
- test the auto-generated code and revise the generator, templates
- alpha/beta release

Petstore spec:
- OAS v2: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/2_0/petstore.yaml
- OAS v3: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml

**Comment by ndbroadbent** [comment]
Hello! My company has just [decided to support Crystal language](https://twitter.com/getdocspring/status/1201456718556717056), and we use openapi-generator, so I would love to work on this and release a Crystal API client for my service. 

(I just realized that I should be supporting openapi-generator as well, so I've also [set up a monthly donation on opencollect](https://opencollective.com/getdocspring)!)

**Comment by wing328** [comment]
@ndbroadbent thanks for becoming a sponsor of openapi-generator.

Looking forward to your PR for the Crystal client generator. If you need help, please let me know.

**Comment by ddcprg** [comment]
@ndbroadbent do you still want to go ahead and contribute this?

**Comment by ndbroadbent** [comment]
Hi @ddcprg, sorry unfortunately I didn't have time to start working on this! Anyone else can please feel free to take over if you might be interested

**Comment by ddcprg** [comment]
hi @ndbroadbent no problem, I'll try to take over then although is busy times for me as well

**Comment by wing328** [comment]
I've filed https://github.com/OpenAPITools/openapi-generator/pull/8304 to start with. `add_pet` and `get_pet_by_id` work and are tested as part of the CI.

There's still a lot needs to be done and I'll create a TODO list later.

For the time being, please try it out and let me know if you've any feedback.

**Comment by wing328** [comment]
Closed via #8304
