### ISSUE TITLE
[BUG][typescript-angular] Binary string response leads to json parse error

### ISSUE THREAD

**Issue by joggeli34** [OpenAPITools/openapi-generator#8601]
##### Description

When generating the api with a binary/string response, the generated code tries to parse it as json. Which will lead to an SytnaxException.

##### openapi-generator version

Occurs newly on 5.0.0
It worked correctly on 4.3.1

##### OpenAPI declaration file content or url

```yaml
  /api/image:
    get:
      description: Returns an image
      operationId: getImage
      responses:
        default:
          description: the Image
          content:
            image/jpeg:
              schema:
                format: binary
                type: string
```

##### Suggest a fix

when generating with 4.3.1 a part of the code snipped looked as following:
```typescript
        return this.httpClient.get(`${this.configuration.basePath}/api/image`,
            {
                responseType: "blob",
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
```
 but with 5.0.0 it changes to: (which is not correct)

```typescript
        let responseType: 'text' | 'json' = 'json';
        if(httpHeaderAcceptSelected && httpHeaderAcceptSelected.startsWith('text')) {
            responseType = 'text';
        }

        return this.httpClient.get<Blob>(`${this.configuration.basePath}/api/image`,
            {
                responseType: <any>responseType,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
```

**Comment by macjohnny** [comment]
@joggeli34 would you like to fix this?

**Comment by macjohnny** [comment]
@wing328 this seems like a general problem, since the line
https://github.com/OpenAPITools/openapi-generator/blob/1b440e191cb98d7895aee4554b3c808b1dcefb06/modules/openapi-generator/src/main/resources/typescript-angular/api.service.mustache#L349-L351

seems ok.
any idea?

**Comment by joggeli34** [comment]
I found out that when I change the response from "default" to "200" it works correctly. So it probably doesn't consider the "default" response in the "isResponseFile" function.

I'm not even sure if "default" is a correct value and should be considered?

**Comment by macjohnny** [comment]
@joggeli34 thanks for investigating this.

The `default` value is allowed according to 

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#responses-object
> The default MAY be used as a default response object for all HTTP codes that are not covered individually by the specification.

@wing328 so I guess this should be considered a general bug concerning the `default` support, right?

**Comment by runenielsen** [comment]
Any new development on this? I have the same issue.

**Comment by runenielsen** [comment]
I also fixed the problem by using the "200" response code instead of the "default" value. But it should also work for "default".

**Comment by EmhyrVarEmreis** [comment]
This issue seems to be fixed but it is not included in latest available release of openapi-generator-cli
