### ISSUE TITLE
[BUG] [PHP] oneOf problem with the similar field names in different models 

### ISSUE THREAD

**Issue by maranqz** [OpenAPITools/openapi-generator#8628]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Model have the similar fields (is_catchall and is_catch_all), after generation of api

##### openapi-generator version

5.0.1-SNAPSHOT

##### OpenAPI declaration file content or url

https://github.com/go-email-validator/email-validator-sdk/blob/e99fe82d3c9d6d520687cf499688112e86acfe03/ev.openapiv3.yaml#L227
```yaml
oneOf:
        - $ref: '#/components/schemas/CheckIfEmailExistResult'
        - $ref: '#/components/schemas/MailboxvalidatorResult'
        - $ref: '#/components/schemas/PromptEmailVerificationApiResult'
...
is_catchall:
        type: string
...
is_catch_all:
        type: boolean
```

##### Steps to reproduce

```bash
docker run  --rm -v ${PWD}/php:/local/out -v $(OPENAPI_PATH):/local/openapi.yaml  openapitools/openapi-generator-cli:latest generate \
	-i /local/openapi.yaml \
	-g php \
	-o /local/out/
```

**Comment by wing328** [comment]
Can you try the option `ensureUniqueParams` to see if it resolves the issue for you?

**Comment by maranqz** [comment]
Thank you it is work; however, `ensureUniqueParams` is true by default in [documentation](https://openapi-generator.tech/docs/generators/php/).

**Comment by maranqz** [comment]
In addition, there is problem with field with same name different type.

```yaml
....
is_disposable:
    type: bool
....
is_disposable:
    type: string
```
1. [bool](https://github.com/go-email-validator/email-validator-sdk/blob/e99fe82d3c9d6d520687cf499688112e86acfe03/ev.openapiv3.yaml#L146)
2. [string](https://github.com/go-email-validator/email-validator-sdk/blob/e99fe82d3c9d6d520687cf499688112e86acfe03/ev.openapiv3.yaml#L110)

**Comment by wing328** [comment]
Looks like it's true by default:

https://github.com/OpenAPITools/openapi-generator/blob/1006d2f21e41cf2f78f3e984fd8dd1127c392cbd/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultCodegen.java#L207

**Comment by wing328** [comment]
We recently merged a fix related to `ensureUniqueParams`. Please give it another try with the latest master.
