### ISSUE TITLE
[JS] the replace statement in parseDate is too greedy

### ISSUE THREAD

**Issue by tray2100** [OpenAPITools/openapi-generator#8632]
##### Description

Currently in the parseDate() function it uses `replace('/T/', ' ')` to convert date strings into something that the Date class can use for construction. This works well for [ISO_8601](https://en.wikipedia.org/wiki/ISO_8601) date strings but it also has the side effect of ruining date strings that have GMT in it.

##### openapi-generator version

5.0.0

##### Suggest a fix/enhancement

Current: 
```
new Date(str.replace(/T/i, ' ')) => Wed Apr 15 2020 00:00:00 GM -0700 (Pacific Daylight Time)
```

Fix:
```
new Date(str.replace(/(\d)(T)(\d)/i, '$1 $3')) => Wed Apr 15 2020 00:00:00 GMT-0700 (Pacific Daylight Time)
```

This allows GMT based date strings to work without issue.

**Comment by wing328** [comment]
Can you please file a PR with the suggested fix?

**Comment by tray2100** [comment]
Yep just filed it. https://github.com/OpenAPITools/openapi-generator/pull/8633
