### ISSUE TITLE
Preserve custom settings in analysis_options.yaml [dart]

### ISSUE THREAD

**Issue by MihaMarkic** [OpenAPITools/openapi-generator#8637]
### Is your feature request related to a problem? Please describe.

Dart here.
After running generator the file `analysis_options.yaml` gets overwritten.

## Describe the solution you'd like

I have few custom settings in `analysis_options.yaml` file, such as option for linter to ignore unused_imports to avoid dart reporting unused imports.
Perhaps add an option to generate `analysis_options.yaml` from a template and merge it to output.

## Describe alternatives you've considered

I have to add my options to `analysis_options.yaml` each time after I run generator.

**Comment by MihaMarkic** [comment]
Oh, I see that you are adding `// ignore_for_file: unused_import` directive at least from 5.1.0 on. So that solves my problem I guess. Not sure if added flexibility might still be useful, so feel free to close this request if not.

**Comment by wing328** [comment]
Another way is https://github.com/OpenAPITools/openapi-generator/blob/master/docs/customization.md#ignore-file-format
