### ISSUE TITLE
[BUG] [C++][Qt5] Optional parameters are not optional in generated code for API

### ISSUE THREAD

**Issue by xconverge** [OpenAPITools/openapi-generator#8648]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The qt5 generator does not output optional parameters to the api. All parameters are still required and the client code does not provide a way of omitting them.

##### openapi-generator version

5.0.1

##### OpenAPI declaration file content or url
```yaml
openapi: 3.0.0
info:
  version: 0.0.1
  title: Test
paths:
  /endpoint:
    get:
      operationId: getEndpoint
      description: "-"
      parameters:
        - name: param1
          required: true
          in: query
          description: required parameter 1
          schema:
            type: string
        - name: param2
          required: false
          in: query
          description: should be optional parameter 2
          schema:
            type: string
      responses:
        200:
          description: Success
```

##### Generation Details

```
openapi-generator-cli generate -i test.yaml -g cpp-qt5-client --additional-properties=optionalProjectFile=false  -o te
stOutput
```

##### Steps to reproduce

header:
```cpp
    void getEndpoint(const QString &param1, const QString &param2);
```

and the implementation::
```cpp

void OAIDefaultApi::getEndpoint(const QString &param1, const QString &param2) {
    QString fullPath = QString(_serverConfigs["getEndpoint"][_serverIndices.value("getEndpoint")].URL()+"/endpoint");


    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("param1")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(param1)));

    if (fullPath.indexOf("?") > 0)
        fullPath.append("&");
    else
        fullPath.append("?");
    fullPath.append(QUrl::toPercentEncoding("param2")).append("=").append(QUrl::toPercentEncoding(::OpenAPI::toStringValue(param2)));
```

##### Related issues/PRs

Similar to these bugs/associated PRs, but for qt5 of course...
https://github.com/OpenAPITools/openapi-generator/issues/2012
https://github.com/OpenAPITools/openapi-generator/issues/3052

##### Suggest a fix

cpp-rest-sdk-client uses boost::optional and cpp-ue4 uses TOptional, so using std::optional with a flag to utilize c++17 seems pretty clean to me

QVariant could also potentially be used but then you lose a lot of the self documenting niceties of the types

Could also just be a change to the api mustache files to utilize the required parameter from the definition, and then either create an overload or utilize some sort of default parameters and detect it and not append to the fullpath if it is set to these defaults (probably not a good idea). I think std::optional is the best answer though, even though it should have a flag.

I am willing to put some legwork into this if someone wants to push me in the right direction

**Comment by wing328** [comment]
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @martindelille (2018/03) @muttleyxd (2019/08)

**Comment by MartinDelille** [comment]
I'm fine with the std::optional way.

**Comment by xconverge** [comment]
and a flag in https://openapi-generator.tech/docs/generators/cpp-qt5-client/?

```useCpp17``` with a default value of false? Will need to check if this is set to true in cmakelists.txt (cpp14 is set currently), the implementation (to populate if optional param is populated) and header (to use optional)

Sounds pretty messy, but I don't want to be the one to decide that we "need" cpp17 vs cpp14...so this solution at least gets things started...

**Comment by xconverge** [comment]
also std::optional would mess up the passing of parameters by const&, thoughts on this? One could also use std::reference_wrapper along with std::optional  (I believe this is similar to how boost::optional works) but things are starting to get a bit crazy here...

What if we just take in a pointer and default the optional parameters to Q_NULLPTR... Not a huge fan of this either, but I wouldn't have scoffed at it if it was the way it had been done from the start...

Aghh there is not a super obvious clean way out of this, I will wait on some more input since I have not contributed to the project before.

**Comment by etherealjoy** [comment]
What about `QVariant` being passed with empty as default.
If we could construct a Qvaraint from an int being passed would be much more intuitive.

**Comment by xconverge** [comment]
Qvariant would take away a lot of the type information I like when using the client IMO

**Comment by xconverge** [comment]
I have thought about this a bit more and I think QVariant is a strong contender. I don't know how many users you guys have/how disruptive a change can be, but QVariant would definitely be the least disruptive (since you can just swap a QVariant in and no one will "know" or need to make compilation changes). I like std::optional better still, but am not sure how to manage the cpp 17 flag/dependency nicely.

**Comment by etherealjoy** [comment]
If you know the data type you are expecting, you can probe the QVariant and get the type info. Not super intuitive, but at least no breaking changes.

**Comment by MartinDelille** [comment]
I'm fine with the QVariant way.

**Comment by xconverge** [comment]
I am pretty green to this stuff, indentation and spacing seems to be a huge pain, any tips would be appreciated...

Here is the std::optional version (that would be somewhat tedious and difficult to enable/disable with a useCpp17 flag because of how many places there are changes)

https://github.com/OpenAPITools/openapi-generator/compare/master...xconverge:supportOptionalParamsQt5

I will try QVariant next

**Comment by MartinDelille** [comment]
Your work would be more readable if you'll generate the sample code by typing `bin/generate-samples.sh bin/configs/cpp-qt5-client.yaml` from the root directory.

**Comment by xconverge** [comment]
@MartinDelille thanks for the tip, done!

There is obviously some work that could be done with whitespace that I could use some advice with how to handle, but this presents 2 possible solutions that could be discussed as part of this issue. I am also not super familiar with all of the different param types, I really only use query parameters.
