### ISSUE TITLE
[BUG][DART] API with path parameter named `format` produces incorrect paths.

### ISSUE THREAD

**Issue by tombowers** [OpenAPITools/openapi-generator#8676]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
If a resource contains a path parameter named `format`, the generated library replaces the parameter with the word `json` prior to normal parameter substitution, breaking the API.

Here is an example of the code produced.

```dart
final path = '/things/{format}'.replaceAll('{format}', 'json')
    .replaceAll('{' + 'format' + '}', format.toString());
```

##### openapi-generator version
5.0.0
(also tested with 5.0.1-20210206.073348-97)

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.4
info:
  title: Sample API
  version: 0.1.1
paths:
  /things/{format}:
    get:
      summary: Returns a list of things.
      parameters:
        - in: path
          name: format
          schema:
            type: string
          required: true
      responses:
        '200':
          description: A JSON array of things
```

##### Generation Details

Generated using compiled jar. e.g.
```pwsh
java -cp openapi-generator-cli-5.0.1-20210206.073348-97.jar org.openapitools.codegen.OpenAPIGenerator generate -i "format-issue.yml" -g dart -o formatissue
```

##### Suggest a fix

I am unfamiliar with the codebase, but it appears to be happening here.
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart/api.mustache#L28

And it seems to be present in many languages, for example.
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/android/api.mustache#L63

**Comment by kuhnroyal** [comment]
This was copied when the Dart generator was created and then again when the Dart2 generator was created. I am not sure why and what it is meant for tbh.
@agilob @wing328 any ideas?

**Comment by wing328** [comment]
That's an old behaviour. I remember first seeing it in the Ruby client generator when I started. We've since removed it to address issues similar to this one.

Please feel free to remove this old behaviour from the Dart generators.

**Comment by kuhnroyal** [comment]
@tombowers Care to make a PR?

**Comment by tombowers** [comment]
@kuhnroyal Sure. I should have some time this week. Thanks.

**Comment by kuhnroyal** [comment]
When you touch this please also update it for the `dart-dio` templates.

**Comment by kuhnroyal** [comment]
Created a PR, this was already removed from dart-dio at some point.
