### ISSUE TITLE
Not working with binary and byte[] formats

### ISSUE THREAD

**Issue by DeniskaAbr** [OpenAPITools/openapi-generator#8678]
Not working with binary and byte[] formats
![изображение](https://user-images.githubusercontent.com/68537068/107614683-d9648780-6c5b-11eb-804d-923b46b6ee67.png)

_Originally posted by @DeniskaAbr in https://github.com/OpenAPITools/openapi-generator/issues/8524#issuecomment-777275173_

**Comment by wing328** [comment]
Are you using the latest stable version v5.0.1?

**Comment by DeniskaAbr** [comment]
Sorry, my mistake.

**Comment by wing328** [comment]
No problem. Closing this for now.
