### ISSUE TITLE
[BUG] [Qt5] Parameterized servers complicated the interface and left unused code

### ISSUE THREAD

**Issue by xconverge** [OpenAPITools/openapi-generator#8694]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

This PR added a neat feature:

https://github.com/OpenAPITools/openapi-generator/pull/8183

But made a whole bunch of things useless/nonfunctional...

host, username, port, scheme, basepath, password, apikeys, all now seem to do nothing. You can set them with setters or via the constructor, but the generated code never uses them that I can see. 

There is no way to change the host at runtime now, it must be done in the .yml when generating and then selected with the server index PER operation, there is not a way to set an entire api object to use a specific server from the consumer of the client.

That means you MUST know your server information at compile time and cannot change it in anyway after that as a consumer... this seems like an oversight to me unless I am missing something

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/8183

##### Suggest a fix

Maybe have the constructor values for these parameters put an entry into the server list (that is set to be index 0 and is the one used) and have a way of easily changing the server index for all operations within the class to use the parameterized server selector separately if desired?

**Comment by xconverge** [comment]
@basyskom-dege any input you have on this would be much appreciated! I am not sure how to best tackle this in a way that works nicely by the side of parameterized servers and work you have already done. I am thinking cleanup the constructor, and add a function like setServer(scheme,host, port, etc) that adds an entry to the serverlist, and iterates over all operations and updates them to be using it as the index.

Then if you want to use the old way, you can use this function, and if you want to use the server selector way, you can as well. But I am open to any other ideas here as well

**Comment by basyskom-dege** [comment]
I will look into that today. So basically you want to set different servers that are not in the OpenAPI file?

**Comment by basyskom-dege** [comment]
I created a PR #8725 that will fix this. I added a function to add servers that are not in the OpenAPI file. Checkout this small program and the output to see how you can use this. If this is the solution you was searching for, feel free to close this issue

main.cpp
```
#include <QCoreApplication>
#include "../client/PFXUsageApi.h"
#include "../client/PFXServerVariable.h"
using namespace test_namespace;
int main(int argc, char *argv[]) {
    QCoreApplication a(argc, argv);

    PFXUsageApi b;
    b.customServer();
    b.defaultServer(); 
    //add two new servers
    int newDefaultServerIndex =  b.addServerConfiguration("defaultServer","DEFAULT{server}:{port}","newly added default server", 
        QMap<QString, PFXServerVariable>{ 
        {"server", PFXServerVariable("No description provided","custom-petstore",
        QSet<QString>{ {"custom-petstore"},{"custom-qa-petstore"},{"custom-dev-petstore"} })}, 
    
        {"port", PFXServerVariable("No description provided","8080",
        QSet<QString>{ {"80"},{"8080"} })},  });
    
    int newCustomServerIndex = b.addServerConfiguration("customServer","{server}:{port}","newly added custom server", 
        QMap<QString, PFXServerVariable>{ 
        {"server", PFXServerVariable("No description provided","custom-petstore",
        QSet<QString>{ {"custom-petstore"},{"custom-qa-petstore"},{"custom-dev-petstore"} })}, 

        {"port", PFXServerVariable("No description provided","8080",
        QSet<QString>{ {"80"},{"8080"} })},  });

    //still using the original servers
    b.customServer();
    b.defaultServer(); 
    //using the new servers
    b.setServerIndex("defaultServer",newDefaultServerIndex);
    //change the port from 8080 to 80
    b.setDefaultServerValue(newDefaultServerIndex,"defaultServer","port","80");
    b.setServerIndex("customServer",newCustomServerIndex);

    //new Servers are used
    b.customServer();
    b.defaultServer(); 

    return 0;
}
```

output:
```
custom server path: https://custom-petstore.swagger.io:8080/v2/custom description: No description provided

default server path: http://petstore.swagger.io:80/v2/default description: No description provided

custom server path: https://custom-petstore.swagger.io:8080/v2/custom description: No description provided

default server path: http://petstore.swagger.io:80/v2/default description: No description provided

custom server path: CUSTOMcustom-petstore:8080/custom description: newly added default server

default server path: DEFAULTcustom-petstore:80/default description: newly added default server

```

**Comment by xconverge** [comment]
Thanks @basyskom-dege  this looks good and is what I had in mind. Would it be possible to also add a setServerIndex(int serverIndex) that has the operation as optional or overloaded and not needed, that sets all operations to that server?

**Comment by basyskom-dege** [comment]
Since every Operation has its own List of serverConfigureations, you need to loop through all your operations and add it. Something like:
`list` stores all your operationid srings.
```
PFXUsageApi b;
for (auto operationString : list){
    b.setServerIndex(operationString, b.addServerConfiguration(operationString,"{server}:{port}","newly added server", 
        QMap<QString, PFXServerVariable>{ [...]});
}

**Comment by xconverge** [comment]
I am proposing putting that loop and code into the generated code as a convenience function since it might have more knowledge/all of the knowledge needed to do it and the user may not easily. For example, how did you get the contents of "list" in your example code? I don't have any way of extracting that information from the qt5 c++ client that I can see yet you are implying I should already have it or know it in my c++ code/user of the client.

**Comment by basyskom-dege** [comment]
A quick look at the constructor would show you that every operationid string is stored as a key in the `_serverIndices` object, so iterating through it could fill this list. Since its just one function I will provide it but I think most API descriptions know their servers when they generate a client.
