### ISSUE TITLE
[REQ] Server stub code using FastAPI

### ISSUE THREAD

**Issue by Minyus** [OpenAPITools/openapi-generator#8697]
### Is your feature request related to a problem? Please describe.

FastAPI is a Python web framework built on top of Starlette and Pydantic inspired by other frameworks explained at: https://fastapi.tiangolo.com/alternatives/

Unfortunately, OpenAPI Generator does not support to generate server stub code using FastAPI yet.

## Describe the solution you'd like

Add option to generate server stub using FastAPI.

**Comment by wing328** [comment]
@Minyus we definitely want to support but I don't think anyone has started yet.

Would you have time to contribute the new generator? I can work with you on this and use the "python-flask" templates as starting point.

**Comment by krjakbrjak** [comment]
@wing328 @Minyus I created a PR (#9611) for this feature.

**Comment by Minyus** [comment]
Thank you, @krjakbrjak ! Looking forward to it being merged.

**Comment by wing328** [comment]
Closing it as it has been merged. Thanks @krjakbrjak again for the contribution.

@Minyus if you've any feedback, please open a new issue for tracking. Thanks.
