### ISSUE TITLE
[REQ] [VERTX_WEB] Use DefaultApiHandler with an own implementation of ApiImpl 

### ISSUE THREAD

**Issue by thobi73** [OpenAPITools/openapi-generator#8710]
### Description:
DefaultApiHandler contains DefaultApi which is set in the default constructor and it is not accessible from outside the class. So, it is impossible to use the generated DefaultApiHandler with an own implementation of DefaultApi.  

### Openapi-generator version
5.0.1

### Suggested Solution:
Generate a second constructor to DefaultApiHandler  

```java
public DefaultApiHandler (final DefaultApi apiImpl) {
   this.apiImpl = apiImpl;
}
```

### Workaround for now
use gradle copy task to manipulate generated code

**Comment by slinkydeveloper** [comment]
I'm working on it
