### ISSUE TITLE
[BUG] Description

### ISSUE THREAD

**Issue by dmitriy-pisarevskiy** [OpenAPITools/openapi-generator#8734]
#### Bug Report Checklist
Hi! How I can keep original names in models like that:

![image](https://user-images.githubusercontent.com/70516019/108311610-48a82180-71f0-11eb-8278-498c8b70da19.png)

![image](https://user-images.githubusercontent.com/70516019/108311717-77be9300-71f0-11eb-832b-805195479d59.png)

Instead of '@odata.count' got odata_count 

How can I fix it?

**Comment by dmitriy-pisarevskiy** [comment]
Hi all, Fixed by custom scripts in solution

**Comment by wing328** [comment]
another way is to use the `nameMappings` option to map property name to a different name:

https://github.com/openapitools/openapi-generator/blob/master/docs/customization.md#name-mapping
