### ISSUE TITLE
[Symfony] [spec 3.0] No support for API keys in Cookies

### ISSUE THREAD

**Issue by Addvilz** [OpenAPITools/openapi-generator#875]
##### Description

Symfony code generator lacks support for API keys in cookies as per 3.0+ spec.

In addition to that, generated code does not fail gracefully either, instead just skipping the definition of the variable. That leads to runtime errors if left unchecked.

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-symfony/api_controller.mustache#L79

##### openapi-generator version

Affects all (issue is present in master and 4x)

##### Suggest a fix/enhancement

Fix should be trivial to implement in the template directly, but I have yet to confirm that in reality.

I will open a PR on this issue as soon as I get a chance (tomorrow or in next couple of days).

**Comment by wing328** [comment]
Closed via #884
