### ISSUE TITLE
JMeter generator renames HTTP header parameter to camel case

### ISSUE THREAD

**Issue by gwsch** [OpenAPITools/openapi-generator#8768]
HTTP header parameter named in the form 'X-Some-Custom-Header' are renamed to 'xSomeCustomHeader'

##### openapi-generator version

version 5.0.1

##### OpenAPI declaration file content or url

https://gist.github.com/gwsch/d55b2112c6ec149a9320552391fc4ffc

##### Command line used for generation

java -jar .....\openapi-generator-cli.jar generate -i openapi_.yaml -g jmeter --additional-properties=allowUnicodeIdentifiers=true

##### Steps to reproduce

X-PB-App-Id becomes xPbAppId, X-Reload becomes xReload 

##### Suggest a fix/enhancement

Keep original parameter names

**Comment by wing328** [comment]
@gwsch thanks for reporting the issue. I've filed https://github.com/OpenAPITools/openapi-generator/pull/8861 to fix it.
