### ISSUE TITLE
Update CI config to support Elm 0.19

### ISSUE THREAD

**Issue by wing328** [OpenAPITools/openapi-generator#878]
##### Description

Elm 0.19 has been released: https://elm-lang.org/blog/small-assets-without-the-headache

- no longer support --yes
- we will need to add elm.json or run `elm init`

##### openapi-generator version

Latest master

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/877

##### Suggest a fix/enhancement

If anyone wants to help on this, please reply to let us know and we'll show you some good starting points.

**Comment by trenneman** [comment]
I've started working on upgrading the generator to 0.19. There are also some changes required to the generated files. Can the CI config be used to support both a 0.18 and 0.19 version?

**Comment by wing328** [comment]
>  Can the CI config be used to support both a 0.18 and 0.19 version?

We can use different CI provider to test different versions of Elm, e.g. Travis for 0.18 and Shippable for 0.19

**Comment by trenneman** [comment]
OK, thanks, I'll use that one as a reference.
