### ISSUE TITLE
[BUG][csharp-netcore] ParameterToMultiMap method generates inconsistent MultiMap for Dictionary as compared to Swagger UI

### ISSUE THREAD

**Issue by aaronxu6** [OpenAPITools/openapi-generator#8798]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

In my GET API, I have a Dictionary<string, string> as parameter. 
When I run it in Swagger UI, the URL it generated does not include the name of the dictionary and my controller is able to receive the KeyValues of the dictionary.
When I use the codegen to generate the client library and run the same method. The URL includes the name of the dictionary itself and my controller is not able to receive any value in the dictionary.

##### openapi-generator version

I use openapi-generator-cli-5.0.0-beta3

##### OpenAPI declaration file content or url

Parameter part of the schema
```json
"parameters": [
          {
            "name": "args",
            "in": "query",
            "required": true,
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }
          }
        ]
```

##### Steps to reproduce

1. Run the API in swagger UI with dictionary parameter:
args : {
  "key1": "value1",
  "key2": "value2"
}
2. URL generated is http://localhost:5050/api/v1/pitos/option?key1=value1&key2=value2
3. Generate client library using the codegen
4. Run the same API in the client code with the same parameter
5. URL generated in client code becomes http://localhost:5050/api/v1/pitos/option?args=%5bkey1%2c%20value1%5d%2c%5bkey2%2c%20value2%5d 

##### Suggest a fix

It seems to be the problem within the query parameter generation process i.e. ParameterToMultiMap. Please fix it to be consistent with Swagger UI ASAP. Thank you.

**Comment by Blackclaws** [comment]
Interesting. I think Swagger UI might actually be in the wrong here.

**Comment by Blackclaws** [comment]
I just tested it out by adding another parameter to the list. Without the change I made to the aspnetcore generator it gets picked up as an additional dictionary entry, which makes no sense, as its supposed to be a separate parameter. Swagger UI indeed creates a flat object there (which is wrong).

**Comment by Blackclaws** [comment]
After further investigation it appears you are also right in that the generated client code ALSO doesn't bind correctly to the query parameter.

**Comment by Blackclaws** [comment]
What you actually want as an api spec is the following:
```
"parameters": [
          {
            "name": "args",
            "in": "query",
            "style": "deepObject",
            "required": true,
            "schema": {
              "type": "object",
              "additionalProperties": {
                "type": "string"
              }
            }
          }
        ]
```

Note the added deepObject. This currently breaks with the default codegen in general however, as deepObject expects (though according to the spec might not need) a schema. I'll try to fix that.

**Comment by Blackclaws** [comment]
This seems related: https://github.com/OAI/OpenAPI-Specification/issues/1006, as does this: https://github.com/OpenAPITools/openapi-generator/issues/469

**Comment by Blackclaws** [comment]
Pull request to fix this is up
