### ISSUE TITLE
[REQ][PowerShell] Revisit list of reserved words for PowerShell

### ISSUE THREAD

**Issue by SimeonGerginov** [OpenAPITools/openapi-generator#8805]
##### Description

For **PowerShell** the list of reserved words contains words like **filter**, which for **PowerShell** Advanced functions can be passed as parameters without appending the **Var** prefix. Currently if the parameter name is **filter**, the function parameter is generated as **VarFilter** which adds an additional prefix which can be simplified.

For example the following is a valid PowerShell Advanced function:

```powershell
function Initialize-MyFilterSpec {
    [CmdletBinding()]
    Param (
        [Parameter(Mandatory = $true)]
        [string]
        $Filter
    )
    
    $Filter
}

Initialize-MyFilterSpec -Filter 'MyFilterSpec'
```

For other reserved keywords like **true**, the above mechanism is not working.

##### openapi-generator version

5.0.0

##### Related issues/PRs

I could not find anything in open issues.

##### Suggest a fix/enhancement

I would suggest revisiting the list of reserved words for **PowerShell** and for reserved words that are generated as parameters to Advanced functions and can be parameters without the **Var** prefix, to be generated without adding the prefix. As a first step, all reserved words which could be generated without the prefix should be identified and then an additional check can be added to the [escapeReservedWord()](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/PowerShellClientCodegen.java#L837). I'd be happy to contribute the fix if it's approved.

**Comment by wing328** [comment]
I'm totally ok that you review and revise the powershell reserved word list. A PR updating the list in PowerShellClientCodegen file would be a good starting point. 

Let me know if you need help.

Thanks for offering help on this.
