### ISSUE TITLE
[BUG][KOTLIN][Retrofit2] Generator should support optional header parameter

### ISSUE THREAD

**Issue by alitams** [OpenAPITools/openapi-generator#8809]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Header parameters can be optional, like path parameters. See the code below. What I experience, despite of the required attribute is false, it generates the parameter as required. I expect that it should be optional with null default value.

Experienced:
```java
@PUT("verify")
fun verify(@Body verifyRequest: VerifyRequest, @Header("Token") verifyData: String): Single<VerifyResponse>
```
Expected:
```java
@PUT("verify")
fun verify(@Body verifyRequest: VerifyRequest, @Header("Token") verifyData: String? = null): Single<VerifyResponse>
```

##### openapi-generator version

5.0.1

##### OpenAPI declaration file content or url

```yaml
   /verify:
    put:
      tags:
        - verify
      operationId: verifyData
      parameters:
        - $ref: '#/components/parameters/optionalToken'
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyRequest"
        required: true
      responses:
        "200":
          description: Successfully verifed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifyResponse"

components:
  parameters:
    optionalToken:
      name: Token
      in: header
      required: false
      description: OptionalToken description
      schema:
        type: string
```

##### Suggest a fix

The kotlin-client/libraries/jvm-retrofit2/headerParams.mustache should be changed from this:
```
{{#isHeaderParam}}@Header("{{baseName}}") {{{paramName}}}: {{{dataType}}}{{/isHeaderParam}}
```
to this:
```
{{#isHeaderParam}}@Header("{{baseName}}") {{paramName}}: {{{dataType}}}{{#required}}{{#defaultValue}} = {{{.}}}{{/defaultValue}}{{/required}}{{^required}}?{{#defaultValue}} = {{{.}}}{{/defaultValue}}{{^defaultValue}} = null{{/defaultValue}}{{/required}}{{/isHeaderParam}}
```

**Comment by shanselm-ergon** [comment]
Same issue here. 

I like your proposal, I'll create a pull request for it.
