### ISSUE TITLE
html2 generator doesn't handles examples

### ISSUE THREAD

**Issue by MartinDelille** [OpenAPITools/openapi-generator#881]
##### Description

The `html2` generator should handle `example` for better documentation purposes.

##### openapi-generator version

`3.2.2-SNAPSHOT`

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.1
info:
  description: This is OpenAPI test
  version: 1.0.0
  title: OpenAPI test
  contact:
    url: https://github.com/MartinDelille/openapi-test
    email: "martin@lylo.tv"
components:
  schemas:
    User:
      title: An user
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
          example: '01srv001'
        name:
          type: string
          example: 'Martin Delille'
paths:
  /users/me:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users:
    get:
      responses:
        '200':
          description: array of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
                example:
                  - id: 'aaa'
                    name: 'Martin'
                  - id: 'bbb'
                    name: 'Thibaut'
```

##### Command line used for generation

```
openapi-generator generate -i api.yaml -g html2 -o html2
```

##### Steps to reproduce

Simply try to generate the documentation with the information above.

##### Related issues/PRs

#880 

##### Suggest a fix/enhancement

No idea.

**Comment by jmini** [comment]
> Suggest a fix/enhancement

The `html` generator generates sections for example, see:
https://github.com/OpenAPITools/openapi-generator/blob/f2b0adfa0502f308fed134240e6deb9d67aa250b/samples/documentation/html/index.html#L777-L786

This can probably be ported to `html2`

**Comment by MartinDelille** [comment]
I can't manage to find the code generating this here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/StaticHtmlGenerator.java

Any idea?

**Comment by MartinDelille** [comment]
@jhitchcock Could you point me where to start to fix this?

**Comment by ndjensen** [comment]
I think you need to update the mustache template.  https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/htmlDocs2/index.mustache

**Comment by IAXES** [comment]
Good day,

I recently was able to reproduce the exact same behavior with release v4.2.2, but the issue is gone (i.e. `-g html` and `-g html2` both yield "pretty"/thorough documentation with examples present) when upgrading to v4.3.1. Seems safe to close this issue now, since the 4.x releases (and likely 5.x) have a fix already in place.

Cheers!

**Comment by MartinDelille** [comment]
Indeed
