### ISSUE TITLE
[REQ] [Qt5] Emit a generic signal anytime an api call is completed

### ISSUE THREAD

**Issue by xconverge** [OpenAPITools/openapi-generator#8864]
The current callback in the API interface emits signals specific to the API, for example

```
    if (worker->error_type == QNetworkReply::NoError) {
        emit createUsersWithArrayInputSignal();
        emit createUsersWithArrayInputSignalFull(worker);
    } else {
        emit createUsersWithArrayInputSignalE(error_type, error_str);
        emit createUsersWithArrayInputSignalEFull(worker, error_type, error_str);
    }
```

From the outside we can then connect to these signals

The API has different signals per function call.

I would like to be able to know if the API did "any work" not just some "specific work"

For example I would add a signal called ```void workDone()```

```
    if (worker->error_type == QNetworkReply::NoError) {
        emit createUsersWithArrayInputSignal();
        emit createUsersWithArrayInputSignalFull(worker);
    } else {
        emit createUsersWithArrayInputSignalE(error_type, error_str);
        emit createUsersWithArrayInputSignalEFull(worker, error_type, error_str);
    }

    emit workDone();
```

```
    if (worker->error_type == QNetworkReply::NoError) {
        emit createUsersWithListInputSignal();
        emit createUsersWithListInputSignalFull(worker);
    } else {
        emit createUsersWithListInputSignalE(error_type, error_str);
        emit createUsersWithListInputSignalEFull(worker, error_type, error_str);
    }

    emit workDone();
```

and this would be added to ALL of the callback functions. From the outside then we could connect to know if the API class has done anything yet without needing to connect to a whole bunch of individual signals

This would be trivial for me to add so I wanted to open it up for discussion before just adding a PR

**Comment by xconverge** [comment]
cc @ravinikam (2017/07) @stkrwork (2017/07) @etherealjoy (2018/02) @MartinDelille (2018/03) @muttleyxd (2019/08)

I am open to other ideas here too, not sure how unique this issue/feature is to my application

**Comment by etherealjoy** [comment]
When a callback arrives how do you know for which API call it is? Supposing you invoked a bunch of API calls. Because these are not synchronous calls.

**Comment by MartinDelille** [comment]
For me it would make sence to have a generic error signal since `{{operationId}}SignalEFull()` has a constant signature: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/cpp-qt5-client/api-header.mustache#L75

**Comment by etherealjoy** [comment]
What is missing in the code right now is the generation of error signals based on statuses defined in the spec.
Generic error signal is needed to catch other responses otherwise the user may be waiting indefinitely.
Generic error signal is also emitted when a timeout is set.

But for the original request, what I am trying to say is that how useful is it if a signal is emitted when something is done, when we dont know which API call did something.  Each api object has many API calls. In single API call scenario maybe it is useful, but for most usecases where users call a lot of APIs with the same object the `workDone()` signal could have been triggered from anywhere.

**Comment by xconverge** [comment]
I personally need it and am connecting manually to all signals currently. I create the api object dynamically as I need to make a call and then connect to the signals to delete later. I keep a list of api objects so that I know if stuff is in process. This signal allows me to cleanup

**Comment by xconverge** [comment]
See my commit ^ for my intention

**Comment by xconverge** [comment]
I will get really specific with an example where this could be useful:


Place where random work will be done with the API objects dynamically
```
void doThing1Somewhere() {
  PFXUserApi* api = new PFXUserApi();
  api.addPet(petToAdd);
  connect(api, &PFXUserApi::addPetSignal, this, function to process doing this);
  connect(api, &PFXUserApi::addPetSignalE, this, function to process an error when doing this);
  m_manager->addTask(api);
}

void doThing2Somewhere(){
  PFXUserApi* api = new PFXUserApi();
  api.doOtherThing(otherThing);
  connect(api, &PFXUserApi::doOtherThingSignal, this, function to process doing this);
  connect(api, &PFXUserApi::doOtherThingSignalE, this, function to process an error when doing this);
  m_manager->addTask(api);
}
```

And then separately a manager:

```
void Manager::addTask(PFXUserApi* task)
{
  QUuid uuid = generateUuid();
  tasks[uuid] = task;
  connect(task, &PFXUserApi::callbackExecutedSignal, task, &PFXUserApi::deleteLater);
  connect(task, &QObject::destroyed, this, [this, uuid] { taskDelete(uuid); });
}
```

The manager allows you to do interesting stuff like
```
bool Manager::isProcessingSomething() const {
  return tasks.size() > 0
}
```

Without this feature, the manager will need to do this and be manually updated (or use weird metatype logic to find signals by name):

```
void Manager::addTask(PFXUserApi* task)
{
  QUuid uuid = generateUuid();
  tasks[uuid] = task;

  connect(task, &PFXUserApi::addPetSignal, task, &PFXUserApi::deleteLater);
  connect(task, &PFXUserApi::addPetSignalE, task, &PFXUserApi::deleteLater);
  connect(task, &PFXUserApi::doOtherThingSignal, task, &PFXUserApi::deleteLater);
  connect(task, &PFXUserApi::doOtherThingSignalE, task, &PFXUserApi::deleteLater);

  connect(task, &QObject::destroyed, this, [this, uuid] { taskDelete(uuid); });
}
```

**Comment by etherealjoy** [comment]
OK thank you for elaborating the use case. What I was trying to say is that, using your example

```
void doThing1Somewhere() {
  PFXUserApi* api = new PFXUserApi();
  connect(api, &PFXUserApi::addPetSignal, this, function to process doing this);
  connect(api, &PFXUserApi::addPetSignalE, this, function to process an error when doing this);
  api.addPet(pet1ToAdd);
  api.deletePet(pet2ToDelete);
  m_manager->addTask(api);
}
```
In the above case, It is unknown whether callback comes from `deletePet` or `addPet`. Maybe not an issue in this case since you only care if the call was completed.
But if we were to make a feature we should handle the case where we have to emit the signal when all pending request from that object have been done or timed out.

**Comment by xconverge** [comment]
> 
> 
> OK thank you for elaborating the use case. What I was trying to say is that, using your example
> 
> ```
> void doThing1Somewhere() {
>   PFXUserApi* api = new PFXUserApi();
>   connect(api, &PFXUserApi::addPetSignal, this, function to process doing this);
>   connect(api, &PFXUserApi::addPetSignalE, this, function to process an error when doing this);
>   api.addPet(pet1ToAdd);
>   api.deletePet(pet2ToDelete);
>   m_manager->addTask(api);
> }
> ```
> 
> In the above case, It is unknown whether signal `callbackExecutedSignal()` comes from `deletePet()` or `addPet()`. Maybe not an issue in this case since you only care if the call was completed.
> But if we were to make a feature we should handle the case where we have to emit the signal when all pending request from that object have been done or timed out.

could do something like:

std::atomic<unsigned int> m_workCount = 0

then whenever we call something that will execute a callback we m_workCount++

and finally in each callback we m_workCount-- and if it is 0, emit a workDone() signal

I would be ok with doing that instead of what I did in my commit, it might be even more useful

**Comment by etherealjoy** [comment]
> could do something like:
> 
> ```
> std::atomic<unsigned int> m_workCount = 0
> ```
> 
> then whenever we call something that will execute a callback we m_workCount++
> 
> and finally in each callback we m_workCount-- and if it is 0, emit a workDone() signal
> 
> I would be ok with doing that instead of what I did in my commit, it might be even more useful

How about something in this direction, _abort_, _timeout_, and all _network responses_ will be covered.
```
signals:
    void allPendingRequestCompleted();
```

```
    connect(worker, &QObject::destroyed, [this](){
        if(findChildren<PFXHttpRequestWorker>().count() == 0){
            emit allPendingRequestCompleted();
        }
    });
    worker->execute(&input);
```
This signal will fire when there are no pending request on any of the API operations of that API object. It will be triggered after the current callback has finished and when going back to idle loop.

**Comment by xconverge** [comment]
We don't use the same worker for all calls to a single api class necessarily though? We create one dynamically in each function, so the find children would only apply to that one worker

**Comment by etherealjoy** [comment]
> We don't use the same worker for all calls to a single api class necessarily though? We create one dynamically in each function, so the find children would only apply to that one worker

That is right, so whenever any worker is destroyed we check in the `lambda` if `this` which is the API object has any worker remaining. When all workers are destroyed (triggered by _abort_, _timeout_ and _network responses_) the current API object will have no more workers and therefore no more active request.

**Comment by xconverge** [comment]
O yea of course, I like it!
