### ISSUE TITLE
Bearer auth seems to not work with python codegen

### ISSUE THREAD

**Issue by 4c74356b41** [OpenAPITools/openapi-generator#8865]
#### Bug Report Checklist

my spec has this:

```
components:
  securitySchemes:
    xxx:
      type: http
      scheme: bearer

  responses:
    GenericApiError:
      description: this object is returned in the cases when an API throws an exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JsonSerializedException'

security:
 - xxx: []

```

after generating the code, i see this in the code:

```
configuration.py:
    def get_basic_auth_token(self):
        """Gets HTTP basic authentication header (string).

        :return: The token for basic HTTP authentication.
        """
        return urllib3.util.make_headers(
            basic_auth=self.username + ':' + self.password
        ).get('authorization')

    def auth_settings(self):
        """Gets Auth Settings dict for api client.

        :return: The Auth Settings information dict.
        """
        return {
        }
```

##### Description
code doesn't use bearer token in the requests

##### openapi-generator version
```
java -jar openapi-generator-cli.jar  version           
5.0.1
```

##### OpenAPI declaration file content or url
https://github.com/Telecominfraproject/wlan-cloud-services/blob/master/portal-services/src/main/resources/portal-services-openapi.yaml

##### Generation Details
```
java -jar openapi-generator-cli.jar generate -i portal-services-openapi.yaml -g python -o portal_client
```

##### Related issues/PRs
https://github.com/OpenAPITools/openapi-generator/issues/1577

**Comment by 4c74356b41** [comment]
we decided against modifying the generated code itself, we are just passing extra headers to the calls, that way we can still use the generated code. @AlfredoCubitos 

```
self.api_client = swagger_client.ApiClient(self.configuration)
self.api_client.default_headers['Authorization'] = "Bearer " + self.bearer._access_token
```

**Comment by AlfredoCubitos** [comment]
@4c74356b41 Yes, this is a better solution :+1:

**Comment by spacether** [comment]
Auth is working in the v6.2.0 python client and onward. One can see it working in this test:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_paths/test_pet_pet_id/test_get.py#L55
which is generated from [this spec](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/python/petstore-with-fake-endpoints-models-for-testing-with-http-signature.yaml)

**Comment by spacether** [comment]
Re-opening this because api key auth is different than bearer auth

**Comment by spacether** [comment]
This has been working from v5.0.0 (Dec 20, 2020) and onward in the 'python' client
One can see the bearer `access_token` property here:
https://github.com/OpenAPITools/openapi-generator/blob/v5.0.0/samples/openapi3/client/petstore/python/petstore_api/configuration.py#L213
Which must be set after Configuration is instantiated.
After that, it will be used in spec defined oath/bearer endpoint calls.
For the v6.2.0 and onward python client, which will [long term be moving to a new repo](https://github.com/OpenAPITools/openapi-generator/pull/13501#issuecomment-1256170624) I have fixed the configuration class where `access_token` can be passed into Configuration init. Fix is [here](https://github.com/openapi-json-schema-tools/openapi-json-schema-generator/pull/68)
