### ISSUE TITLE
[BUG][dart-dio][client] new analysis_options.yaml triggers error on response which is bytes

### ISSUE THREAD

**Issue by adg-mh** [OpenAPITools/openapi-generator#8878]
The `analysis_options.yaml`  additions from #8231 now cause an error on code generated for an endpoint which returns bytes.

After generating the dart-dio client for [this spec](https://gist.github.com/adg-mh/d4b62ddd457ae97628a0db9ea8057133), dart will now throw an error when building:

```
A value of type 'dynamic' can't be assigned to a variable of type 'Uint8List'.
Try changing the type of the variable, or casting the right-hand type to 'Uint8List'.
```

Seems like it could be remedied with an `as {{{returnType}}}` added to the template.

.
@swipesight (2018/09) @jaumard (2018/09) @josh-burton (2019/12) @amondnet (2019/12) @sbu-WBT (2020/12) @kuhnroyal (2020/12) @agilob (2020/12)

**Comment by agilob** [comment]
Works as expected!

**Comment by kuhnroyal** [comment]
I'll take a look.
