### ISSUE TITLE
[REQ] Add AsciiDoc as an option for client library documentation

### ISSUE THREAD

**Issue by tballast** [OpenAPITools/openapi-generator#8891]
### Is your feature request related to a problem? Please describe.

We would like to generate SDK libraries, as well as a documentation website with the use of this generator. We would also like to use [Antora ](https://antora.org/)to generate a documentation website. Antora however generates pages based on Asciidoc files, not markdown. The SDKs that are generated typically only use markdown for their documentation. I would like to be able to choose between Markdown or Asciidoc for the SDK documentation library. 

## Describe the solution you'd like

When I generate a Client SDK library, I would like to have a command line option that allows be to choose the language that the documentation will be generated in, such as `[--documentation-lang <documentation-lang>]` 

Our primary interest is AsciiDoc, however if this option is present then it also opens up the ability to use other languages as well.

Some potential usages: 
`openapi-generator generate -i petstore.yaml -g java --documentation-lang asciidoc -o /tmp/test/`
`openapi-generator generate -i petstore.yaml -g java --documentation-lang html -o /tmp/test/`
`openapi-generator generate -i petstore.yaml -g java --documentation-lang pdf -o /tmp/test/`
`openapi-generator generate -i petstore.yaml -g java --documentation-lang latex -o /tmp/test/`

## Describe alternatives you've considered

We have experimented with simply converting the already generated markdown documentation into asciidoc, however this carries it's own set of issues as most of the generated documentation uses tables, which are not officially supported in the markdown specification, and thus don't always convert properly into asciidoc. 

## Additional context

No additional context that I can think of.

**Comment by wing328** [comment]
What about converting the auto-generated markdown doc to asciidoc using https://pandoc.org/ ?

**Comment by tballast** [comment]
@wing328 Yea, this is what we've already tried. In some cases it works fine, but with the tables for example, it fails. They're not officially supported in Markdown, and thus the syntax isn't consistent in the Mustache files used in the OpenApi generator. 

For example: 
https://github.com/OpenAPITools/openapi-generator/blob/641ddc7cee3f2e728f9e85c931d734fc8a35ad0b/modules/openapi-generator/src/main/resources/python/api_doc.mustache#L65

https://github.com/OpenAPITools/openapi-generator/blob/641ddc7cee3f2e728f9e85c931d734fc8a35ad0b/modules/openapi-generator/src/main/resources/python/api_doc.mustache#L43

Both of these are tables, but they are using different syntax. Pandoc doesn't properly recognize the latter example as a table and renders it incorrectly.

**Comment by wing328** [comment]
What about updating the latter one using the former one with leading and trailing `|`  so that the conversion to asciidoc works without issues?

**Comment by tballast** [comment]
We took a closer look, and the issue is actually coming from a lack of spacing between the table title and the text above it. 

When the spaces are added to the following section then the generation works properly. 

https://github.com/OpenAPITools/openapi-generator/blob/641ddc7cee3f2e728f9e85c931d734fc8a35ad0b/modules/openapi-generator/src/main/resources/python/model_doc.mustache#L5


For instance, the following .md file
```
# Category

A category for a pet
## Properties
| Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**id** | **int** |  | [optional] 
**name** | **str** |  | [optional] 

[[Back to Model list]](../README.md#documentation-for-models) [[Back to API list]](../README.md#documentation-for-api-endpoints) [[Back to README]](../README.md)
```
 produces the following .adoc file:
```
== Category

A category for a pet ## Properties | Name | Type | Description | Notes
———— | ————- | ————- | ————- *id* | *int* | | [optional] *name* | *str*
| | [optional]

link:../README.md#documentation-for-models[[Back to Model list]]
link:../README.md#documentation-for-api-endpoints[[Back to API list]]
link:../README.md[[Back to README]]
```

Which is not properly generated. 

However, the following .md file:
```
# Category

A category for a pet

## Properties
| Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------
**id** | **int** |  | [optional] 
**name** | **str** |  | [optional] 

[[Back to Model list]](../README.md#documentation-for-models) [[Back to API list]](../README.md#documentation-for-api-endpoints) [[Back to README]](../README.md)
```

produces the following .adoc file:
```
== Category

A category for a pet

=== Properties

[cols=",,,",options="header",]
|===
|Name |Type |Description |Notes
|*id* |*int* | |[optional]
|*name* |*str* | |[optional]
|===

link:../README.md#documentation-for-models[[Back to Model list]]
link:../README.md#documentation-for-api-endpoints[[Back to API list]]
link:../README.md[[Back to README]]
```

The only difference is a space added between the description and the title. Adding that space would be a fine solution.

**Comment by wing328** [comment]
@tballast thanks for investigating this. Do you mind filing a PR with the suggested fix? We'll try to review over the weekend.

**Comment by tballast** [comment]
@wing328 Yea gladly, sorry for the potentially foolish question, but do I need to do anything in particular to push by branch?

I've created a local one, made my changes, and every time I try to push it just tells me that I don't have permission. (See screenshot). 
![image](https://user-images.githubusercontent.com/5382820/110166281-6b435880-7df4-11eb-8694-dce6091004da.png)

I've checked my remotes and credentials and everything seems to be in order so I'm not sure what's going on.

**Comment by wing328** [comment]
You need to fork this repo first: https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-can-i-submit-a-pr-to-fix-bugs-or-make-enhancements

**Comment by tballast** [comment]
@wing328 thanks for the help. Sorry for the late submission, I was unavailable on the weekend.

**Comment by wing328** [comment]
@tballast your submission is not late and we appreciate your contributions to improve the project. Have a good day.
