### ISSUE TITLE
[BUG][PYTHON] Using Openapi 3.0 Inheritance/Polymorphism keywords (allOf, anyOf, oneOf) causes generation of UNKNOWNBASETYPE model.

### ISSUE THREAD

**Issue by danaelhe** [OpenAPITools/openapi-generator#8892]
#### Bug Report Checklist

- [y] Have you provided a full/minimal spec to reproduce the issue?
- [y] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [y] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [y] Have you searched for related issues/PRs?
- [y] What's the actual output vs expected output?
- [maybe ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Can’t use allof, anyof, or oneof keywords in request body → Will result in generating "UNKNOWNBASETYPE" which makes that client endpoint unusable. This is specific to Openapi 3.0. In Openapi 2.0 (swagger 2.0) one could get away with using "produces" and "consumes" (kubernetes api uses that) in POST requests. With Openapi 3.0, that has been replaced with requestBody and the use of the inheritance keywords (allOf, anyOf, oneOf). This problem also doesn't seem specific to Python.

The following spec causes the issue:

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.0
info:
  title: Sample API
  version: '2.0'
paths:
  /v2/projects:
    post:
      operationId: create_project
      summary: Create a Project
      description: 'To create a project, send a POST request to `/v2/projects`.'
      tags:
        - Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/project_base'
              required:
              - name
              - purpose
      responses:
        '200':
          description: OK
components:
  schemas:
    project_base:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: 4e1bfbc3
          description: The unique universal identifier of this project.
        name:
          type: string
          maxLength: 175
          example: my-web-api
          description: >-
            The human-readable name for the project. The maximum length is 175
            characters and the name must be unique.
        description:
          type: string
          maxLength: 255
          example: My website API
          description: >-
            The description of the project. The maximum length is 255
            characters.
        purpose:
          type: string
          maxLength: 255
          example: Service or API
```

##### Generation Details

Generates a client that imports:
`from openapi_client.model.unknownbasetype import UNKNOWNBASETYPE`
and uses it in place of the schema described in requestbody (project_base).

If you rework the POST request as such to remove the use of allOf, you are able to create a POST request but you lose the ability to specify which properties are required for that specific endpoint:

```yaml
paths:
  /v2/projects:
    post:
      operationId: create_project
      summary: Create a Project
      description: 'To create a project, send a POST request to `/v2/projects`.'
      tags:
        - Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/project_base'
      responses:
        '200':
          description: OK
```

^This will generate the expected import statements in the client:
`from openapi_client.model.project_base import ProjectBase`
 
...but you lose the ability to specify which inherited properties are required for that specific endpoint). Also, if you were using oneOf or anyOf, I don't think you'd be able to maintain their behavior with this workaround. I've seen people suggest creating a specific model for each endpoint and specify the required properties there, but that will cause the spec to be super clunky and generate weird model names.

##### Steps to reproduce

Create a file with the following spec:
```yaml
openapi: 3.0.0
info:
  title: Sample API
  version: '2.0'
paths:
  /v2/projects:
    post:
      operationId: create_project
      summary: Create a Project
      description: 'To create a project, send a POST request to `/v2/projects`.'
      tags:
        - Projects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/project_base'
              required:
              - name
              - purpose
      responses:
        '200':
          description: OK
components:
  schemas:
    project_base:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          example: 4e1bfbc3
          description: The unique universal identifier of this project.
        name:
          type: string
          maxLength: 175
          example: my-web-api
          description: >-
            The human-readable name for the project. The maximum length is 175
            characters and the name must be unique.
        description:
          type: string
          maxLength: 255
          example: My website API
          description: >-
            The description of the project. The maximum length is 255
            characters.
        purpose:
          type: string
          maxLength: 255
          example: Service or API
```

run the following:

`docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate -i/local/projects_allof.yaml -g python -o /local/last-try`

Inspect the openapi_client/api/projects_api.py file and see if UNKNOWNBASETYPE is imported and used.

##### Related issues/PRs

This problem has been described in many issues: [#2892](https://github.com/OpenAPITools/openapi-generator/issues/2892) [#5903](https://github.com/OpenAPITools/openapi-generator/issues/5903) #[7256](https://github.com/OpenAPITools/openapi-generator/issues/7256) #[7339](https://github.com/OpenAPITools/openapi-generator/issues/7339). Also not specific to just Python.

##### openapi-generator version

Openapi 5.0.1, also used the latest master via docker

**Comment by sanjothmr** [comment]
having same issue, any fix so far?

**Comment by davidraleigh** [comment]
having the same issue in golang

**Comment by kkliebersbach** [comment]
lol this issue seems to be in literally every single generator... not a very good look for a "spec-compliant" program!

**Comment by benpjohnson** [comment]
Also happening in ruby

**Comment by stonecharioteer** [comment]
Has anyone figured out how to get around this?

**Comment by davidraleigh** [comment]
@stonecharioteer if you have the opportunity use protobuf + gRPC instead.

**Comment by spacether** [comment]
I think that this bug is happening in the addBodyModelSchema method.
This bug was fixed in the python-experimental generator in this PR: https://github.com/OpenAPITools/openapi-generator/pull/11420/files
And one can see examples of it working in the inline composition examples in that PR.

**Comment by ytjohn** [comment]
> Has anyone figured out how to get around this?

I have a shell script that generates the code, and then runs sed to convert Anyofstringstring to str. It's not the greatest, but it works for our use cases.  

```
sed -i 's/AnyOfstringstring/str/g' src/clientname/models/*.py
sed -i 's/AnyOfstringstring/str/g' src/clientname/docs/*.md
````

**Comment by meawoppl** [comment]
Migrate to openapi3 they said, it will be fun they said...

**Comment by meawoppl** [comment]
I should note that the `python-experimental` generator is super broken right now as well: https://github.com/OpenAPITools/openapi-generator/issues/12189

I am genuinely unsure if there is a road for generating python clients from the current openapi3 spec :grimacing:

**Comment by wing328** [comment]
Should be fixed via #12348. Please give it a try with the latest master (snapshot version can be found  in the project's readme)

Happy to reopen if it's still an issue.

**Comment by C0deZLee** [comment]
This still remains an issue in 6.2.0.

**Comment by spacether** [comment]
@C0deZLee please provide a sample spec.
This PR https://github.com/OpenAPITools/openapi-generator/pull/13819
fixes the type hint for this use case.
