### ISSUE TITLE
[BUG] Virtualan plugin (additional property "virtualService") has old version that does not work with 5.x.x 

### ISSUE THREAD

**Issue by networkinss** [OpenAPITools/openapi-generator#8909]
#### Bug Report Checklist
Virtualan version 1.0.0 is too old. That version has minor bugs that are resolved in later versions.
The old version 1.0.0 is not working with OpenAPI tools version 5.x.x and fails to start the spring boot application.

- [x ] Have you provided a full/minimal spec to reproduce the issue?
Generate with generator "spring" and additional property virtualService=true.
mvn spring-boot:run fails to start the Spring Boot application. 
- [x ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
It is the common petstore sample.
- [x ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
It works with version 4.3.1 but not anymore in version 5.x.x.
- [x ] Have you searched for related issues/PRs?
Yes,
- [x ] What's the actual output vs expected output?
Spring Boot fails to start with old version of virtualan.
- [x ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The old version 1.0.0 has minor bugs and does not work with OpenAPI tools 5.x.x.
Version must be updated to 2.1.7 which is the most current version of virtualan.

```
        <dependency>
            <groupId>io.virtualan</groupId>
            <artifactId>virtualan-plugin</artifactId>
            <version>2.1.7</version>
        </dependency>
```

##### openapi-generator version

5.0.1 and 5.1.0

##### OpenAPI declaration file content or url
Petstore yaml is quite sufficient. It is a more general problem and not from specification.
https://github.com/OpenAPITools/openapi-petstore/blob/master/src/main/resources/openapi.yaml

##### Generation Details

java -jar openapi-generator-cli.jar generate -i petstoreoas3.yaml -g spring -o ./output/petstoreoas3 --additional-properties=virtualService=true

##### Steps to reproduce

mvn spring-boot:run

##### Related issues/PRs

https://github.com/OpenAPITools/openapi-generator/pull/8910

##### Suggest a fix

Just update the pom.xml with new version.
```
         <dependency>
             <groupId>io.virtualan</groupId>
             <artifactId>virtualan-plugin</artifactId>
             <version>2.1.7</version>
     ``    </dependency>
```

**Comment by wing328** [comment]
Can you please file a PR to update virtualan to a newer version? Let me know if you need help with the PR.

**Comment by networkinss** [comment]
I am already working on it :).

**Comment by networkinss** [comment]
https://github.com/OpenAPITools/openapi-generator/pull/8910

**Comment by wing328** [comment]
Merged. Thanks for the contribution.
