### ISSUE TITLE
[REQ] [Swift5] Encode a user-defined model to Json when using multipart/form-data

### ISSUE THREAD

**Issue by 0x0c** [OpenAPITools/openapi-generator#8925]
### Is your feature request related to a problem? Please describe.

When sending any user-defined models as `multipart/form-data`, Xcode could not build generated codes because of missing a method called `encodeToJSON` that is a member of `JSONEncodable` protocol.
Although existing primitive types conforms to this protocol, user-defined model does not.

For example, Xcode could not build this API.

```yml
openapi: 3.0.0
info:
  title: test
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /postModel:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples: {}
        '400':
          description: Missing Required Information
      description: Create a new user.
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Request'
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples: {}
      properties:
        integerValue:
          type: integer
    Request:
      title: Request
      type: object
      properties:
        user1:
          $ref: '#/components/schemas/User'
```

<img width="1015" alt="Screen Shot 2021-03-09 at 1 14 33" src="https://user-images.githubusercontent.com/154327/110348280-d4390380-8074-11eb-8b9a-1101a8850c1d.png">

## Describe the solution you'd like

Implement `encodeToJSON` method for any user-defined models by protocol extension.

```swift
extension JSONEncodable where Self: Encodable {
    func encodeToJSON() -> Any {
        let encoder = JSONEncoder()
        guard let data = try? encoder.encode(self) else {
            fatalError("Could not encode to json: \(self)")
        }
        return data.base64EncodedString(options: Data.Base64EncodingOptions())
    }
}
```
Then, to confirm `JSONEncodable` for user-defined model, edit `modelObject.mustache`.

I already implement these codes and tested using 101da6e43446cd13b078b0b56465a19f980cb9e2
If this request is acceptable, I will send PR.

**Comment by 4brunu** [comment]
Hey, could you please open a PR, so that we can try to fix this issue? Thanks 👍

**Comment by 0x0c** [comment]
@4brunu I open PR https://github.com/OpenAPITools/openapi-generator/pull/11202. Would you review the PR?

**Comment by kimdv** [comment]
Hi! 
With the latest version of the generator, 5.4.0 it add `JSONEncodable` to all our models. 
Is there a way do disable adding `JSONEncodable`?

**Comment by 4brunu** [comment]
Currently no.
The 5.4.0 has a known issue that will be fixed in the next version.
So maybe you want to keep using 5.3.X while the next version is not released.
Otherwise you could create a jar by building this project from source.
