### ISSUE TITLE
Invalid enum var names are generated by multi-byte characters

### ISSUE THREAD

**Issue by osjupiter** [OpenAPITools/openapi-generator#893]
##### Description

Hi. I have been using openapi-generator with definitions which contains multi-byte characters.
When I wrote enum definitions  which names contain only non-word characters(RegExp \W), invalid code generated. 
(All of enum names become "_".)

Are double-byte characters not allowed for enum names in OAS ?
If it is valid, I hope these characters will be supported.

##### generated code

java
```java
@JsonAdapter(PetType.Adapter.class)
public enum PetType {
  _("猫"), // cat   --compile error
  _("犬"); // dog
```
go
```golang
type PetType string
// List of PetType
const (
	 PetType = "猫" // compile error
	 PetType = "犬"
)
```

##### openapi-generator version
3.2.3-SNAPSHOT

##### OpenAPI declaration file content or url

```yaml
swagger: "2.0"
info:
  title: "example"
  version: "1.0"
paths:
  /pet:
    post:
      parameters:
        - in: body
          name: data
          schema:
            type: object
            properties:
              animal:
                $ref: "#/definitions/PetType"
      responses:
        "200":
          description: ok
definitions:
  PetType:
    type: string
    enum:
      - 猫
      - 犬
    x-enum-names:
      - Cat
      - Dog
```

##### Command line used for generation
```cmd
java -jar openapi-generator-cli-3.2.3-20180824.092221-7.jar generate  -i sample.yaml -g java -o dest
```
##### Steps to reproduce
just generated

##### Related issues/PRs
I could not find it.

##### Suggest a fix/enhancement

I always create a customized config class and add `x-enum-names` extension by overriding  `postProcessModelsEnum` and `updateCodegenPropertyEnum` like [this](https://github.com/osjupiter/swagger-codegen-gradle-sample/blob/master/mytemplate/logic/MySwaggerLogic.groovy).

I think it is not good to positively use multi-byte characters as an api parameter.  
So it is enough to be able to use it by extension.

Thanks.

**Comment by wing328** [comment]
> Are double-byte characters not allowed for enum names in OAS ?

Double-byte characters are allowed for num names in OAS v2, v3.

> I always create a customized config class and add x-enum-names extension by overriding postProcessModelsEnum and updateCodegenPropertyEnum like this.

@osjupiter thanks for the details in reporting the issue. I agree with you the existing solution we'd in place won't meet your requirement and I like your idea of using extensions to control the naming of the enum parameter name.

Would you have time to contribute a PR to fix the Go or Java client generator as a starting point?

(It's late night in Japan so let's resume the conversation over the weekend or on Monday.  Have a nice weekend!)

**Comment by osjupiter** [comment]
Thanks for your agreement!
I'll send a PR.

**Comment by osjupiter** [comment]
I send PR! 
I changed  the extension name to "x-enum-varnames".

With this extension, users will be able to control  names of enum property for more diverse purposes.

exmaple
```yaml
      EnumProp:
        type: string
        enum:
          - "1"
          - "2"
        x-enum-varnames:
          - ONE
          - TWO
```
gererates
```java
  public enum EnumPropEnum {
    ONE("1"),  // without extension : _1
    
    TWO("2"); // without extension : _2
```

Note that this feature affects output of all languages.

**Comment by akhileshnair08** [comment]
ABCEnum:
      enum:
        -{0,"aum"}
        -{1,"gautham"}
        -{2,"Buddha"}
      x-enum-varnames:
       - AUM
       - GAUTHAM
       - BUDDHA
      type: object
      properties:
        num_value:
          type: integer
          format: int32
        str_value:
          type: string

Why is this not working???
