### ISSUE TITLE
[BUG] Generator Qt5 - QStringList parameter fails

### ISSUE THREAD

**Issue by Jazzco** [OpenAPITools/openapi-generator#8934]
Qt version: `5.15.2`

#### Description
Lately the parameters has been changed to `QVariant`. The conversions fails to work for `QStringList`.

#### Details
Passing a `QStringList` or a `QList<QString>` as a parameter is converted to a `QVariant`. Inside the generated method there is an attempt to convert `QVariant` back via `var.value<QList<QString>>()` which fails to work.

#### Solution
After patching the `var.value<QList<QString>>()` to `var.value<QStringList>()` the interface works as intended.

**Comment by Jazzco** [comment]
More explicit: In file `modules/openapi-generator/src/main/resources/cpp-qt5-client/api-body.mustache` the line 317:
```
 if ({{{paramName}}}{{^required}}.value<{{{dataType}}}>(){{/required}}.size() > 0) {
```
generates the following code in our interface:
```
   if (arguments.value<QList<QString>>().size() > 0) {
```

which skips because the size is always 0.

**Comment by etherealjoy** [comment]
> This is the current masters behavior. From the latest commits I guess #8733 may has introduced the issue. As far as I understand the code (having an input type of `QStringList`) `{{{dataType}}}` is replaced by `QList<QString>` instead of the enhanced `QStringList`. The latest Qt5.15 versions seems to fail converting the `QVariant` to `QList<QString>`.
> 
> This can be seen in the other direction too. Passing a `QStringList` to a method which takes a `QVariant` works, it's implicitly converted - where passing a `QList<QString>` fails.

@Jazzco 
Many thanks for opening this issue. Does this happen for other types, lets say `QMap` and `QList` (but the type is not `QString`)

**Comment by etherealjoy** [comment]
OK, I made a test seems it is not working for non standard types like in the api body for example, 
If it take a bit more time for us to fix it we could revert that PR.

**Comment by etherealjoy** [comment]
@Jazzco 
When you have time could you please check the linked PR if it solves your issue now.

**Comment by Jazzco** [comment]
@etherealjoy   
- A major issue: The interface now crashes inside the lambda at the end of the method where the deallocation takes place.  
- and a minor: `char*` are not converted implicitly into `QString` any more

**Comment by etherealjoy** [comment]
@Jazzco 
![image](https://user-images.githubusercontent.com/33183834/110979280-aef21100-8364-11eb-87db-b6fc9de615c4.png)

I made a quick test with the sample, seems good.

Are you debugging with Qt Creator?

> @etherealjoy
> 
> * A major issue: The interface now crashes inside the lambda at the end of the method where the deallocation takes place.

Qt raise a `SIGSTOP` if you debug in terminal with QtCreator. This is because contention for accessing the object. You could remove the option to debug in terminal if it helps.
> * and a minor: `char*` are not converted implicitly into `QString` any more

This we can check later, if it actually makes sense to handle, but not a good idea to pass `char*`, because of encoding problems anyway.

**Comment by etherealjoy** [comment]
@Jazzco
I hit the crash with complex types, now checking.

**Comment by etherealjoy** [comment]
I found the reason of the crash, it was from a different commit
```
        if(findChildren<PFXHttpRequestWorker>().count() == 0){
```
should be 
```
        if(findChildren<PFXHttpRequestWorker*>().count() == 0){
```

Now it is fine.

**Comment by Jazzco** [comment]
This fix now works and produces the expected result. 👍  The need to convert a `char*` to a `QString` is just a question of convenience.
