### ISSUE TITLE
[Scala] [scala-play-server] [question] generate partial project

### ISSUE THREAD

**Issue by rafhuys-klarrio** [OpenAPITools/openapi-generator#8952]
##### Description

I notice the scala-play-server generator generates a full Play project. My use case is to generate models/routes/controller trait in the project build (so each time the projects compiles).

This way a change in the openapi.yaml spec would require appropriate changes in the implementation.
The current behaviour is that code generation of scala-play-server generates a new project on each run.

I don't see a way of accomplishing this. Would this be in any way possible?

##### openapi-generator version

5.0.1

**Comment by wing328** [comment]
Use .openapi-generator-ignore to skip generating files that you don't need.

It works similar to .gitignore.

**Comment by rafhuys-klarrio** [comment]
of course :100: 

tx!
