### ISSUE TITLE
[BUG] Unknown class imported 

### ISSUE THREAD

**Issue by dpomaresp** [OpenAPITools/openapi-generator#8974]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
I'm trying to generate the client API for kotlin and java but I get an unknown class imported in one of the generated classes: `OneOfLessThanArrayCommaRestApiErrorGreaterThan`

![image](https://user-images.githubusercontent.com/8425171/111175948-d2090480-85a0-11eb-9a32-5c3ef934b74a.png)

##### openapi-generator version
org.openapi.generator version 5.01

Also using the following dependencies and versions:
- com.github.johnrengelman.processes version 0.5.0
- org.springdoc.openapi-gradle-plugin version 1.3.1
- org.springdoc:springdoc-openapi-ui version 1.5.5
- org.springdoc:springdoc-openapi-kotlin version 1.5.5
- org.springdoc:springdoc-openapi-security version 1.5.5
- org.springdoc:springdoc-openapi-data-rest version 1.5.5

##### OpenAPI declaration file content or url

Swagger.json produced: https://gist.github.com/dpomaresp/3b27e0fb88f75d9ad8e048b3a2573349

##### Generation Details

Properties for GenerateTask gradle task:
       id.set("comments-client-api")
        generatorName.set("kotlin")
        inputSpec.set("$documentationPath/$swaggerJsonFile")
        outputDir.set("$clientApiPath/kotlin")
        packageName.set("${project.group}.comments")
        apiPackage.set("api")
        modelPackage.set("model")
        groupId.set(project.group.toString())
        version.set(project.version.toString())
        configOptions.put("dateLibrary", "java8")

##### Steps to reproduce

Run generateOpenApiDocs gradle task and then openApiGenerate gradle task

##### Suggest a fix

I noticed the issue is with the Spring controller advice as it has 2 methods:
-  One retrieves a single RestApiError object 
- The other one retrieves a list of RestApiError objects

If I get rid of this 2 methods, the unknown class doesn't show up in the generated class. My guess is that the `oneOf` doesn't work as expected

**Comment by saurcery** [comment]
@dpomaresp faced the same issue recently.
Workaround I used for this is to declare oneOf schemas as a separate object and $ref them wherever required.

**Comment by dpomaresp** [comment]
> @dpomaresp faced the same issue recently.
> Workaround I used for this is to declare oneOf schemas as a separate object and $ref them wherever required.

Thanks for the info! I decided not to do work arounds as I was planning to auto generate client API based on the json produced by swagger so other projects could consume that auto generated API without having to maintain it. I don't want to face this kind of issues and block our development because of it

**Comment by wing328** [comment]
The issue should be fixed in the latest master. Please give it another try. Closing it for now.
