### ISSUE TITLE
Query Parameters of type integer in format int64 seem to create a broken rest easy API

### ISSUE THREAD

**Issue by lucafuji2** [OpenAPITools/openapi-generator#8986]
##### Description
Very similar to https://github.com/OpenAPITools/openapi-generator/issues/1226, but for rest easy instead.
Created a API Spec with a query parameter of type integer, with format int64 which results to Long in Java. Leads to a broken resteasy Api with the following signature:
@DefaultValue("0l") @QueryParam("offset") Long offset,

##### openapi-generator version

5.1.0

  causing the problem (line of code or commit), or simply make a suggestion -->
remove the suffix for long, float, double etc, as in 
https://github.com/OpenAPITools/openapi-generator/pull/4969
https://github.com/OpenAPITools/openapi-generator/pull/4969/files#diff-9de34b4aad5de707e8aa0c031f20a6573f8f50826a437f0652c54b3788b37d41R869

**Comment by wing328** [comment]
Can you please file a PR to start with so that we can review the fix more easily?

**Comment by lucafuji** [comment]
@wing328 Thanks for merging the PR. A qq, when will be the next release including this PR?

**Comment by wing328** [comment]
@lucafuji thanks for the fix. Please refer to https://github.com/OpenAPITools/openapi-generator/milestones for the release schedule (tentative)
