### ISSUE TITLE
[Elm] Upgrade to version 0.19

### ISSUE THREAD

**Issue by andys8** [OpenAPITools/openapi-generator#900]
Recently after a long period Elm was released in a new version `0.19`. There are some changes which have to be done. The package json files was renamed to `elm.json` and the format changed.

Blog: 
http://elm-lang.org/blog/small-assets-without-the-headache

Release Notes: 
https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md

### Related
https://github.com/OpenAPITools/openapi-generator/blob/4401407c7c9a6c0ce2fabfe3b13f6f7c6aa23c5a/.travis.yml#L62

**Comment by wing328** [comment]
@andys8 thanks. We'll instead use https://github.com/OpenAPITools/openapi-generator/issues/878 to track it instead.

**Comment by andys8** [comment]
Thanks, I've overlooked that one.

**Comment by wing328** [comment]
@andys8 no problem :) If you want to work on that one, please reply to let us know to avoid duplicated effort.
