### ISSUE TITLE
[Dart-dio] Generator force using built_value

### ISSUE THREAD

**Issue by jaumard** [OpenAPITools/openapi-generator#9082]
Currently dart dio generator is using built_value to serialize/deserialize the json, would be nice to have more choice.

I'm thinking about freezed for example, because if we use this one in your app, you probably don't want to include built_value too... 

Also a new feature will come soon to dart for meta programming, it will probably change the way we serialize/deserialize and maybe offer a full dart way of doing it. So preparing for multi serializer is probably a good thing

**Comment by kuhnroyal** [comment]
I started working on this already in the new dart-dio-next generator that is experimentally available in 5.1.0. See #8869 and specifically https://github.com/OpenAPITools/openapi-generator/pull/8869#issuecomment-792275002 regarding freezed.

**Comment by jaumard** [comment]
nice @kuhnroyal ! I totally miss that dart-dio-next ! I'll take a look, about enums not being supported, it's not really a big deal as they can be at first step be translated into int or string primitives until freeze support them :) that's basically what I did at the time with jaguar generator because it wasn't supported enums. 
Thanks for pointing that out!

**Comment by kuhnroyal** [comment]
Feel free to add a freezed implementation :)
I am sure there are still some built_value left overs that need to be moved since it is just the ground work for now.

**Comment by kuhnroyal** [comment]
Related https://github.com/OpenAPITools/openapi-generator/pull/9980

**Comment by bahag-chandrana** [comment]
@kuhnroyal I have sort of created a version with freezed as an additional serializer option. Can I raise a draft PR to verify the changes or do I need to open a new issue for this?

**Comment by kuhnroyal** [comment]
> @kuhnroyal I have sort of created a version with freezed as an additional serializer option. 
> here:  https://github.com/bahag-chandrana/openapi-generator
> 
> Can I raise a draft PR to verify the changes or do I need to open a new issue for this?
> 
> 

Just go for a draft PR and mention me. Looking forward to a freezed option and how you solved Enums support :)

**Comment by bahag-chandrana** [comment]
> > @kuhnroyal I have sort of created a version with freezed as an additional serializer option.
> > here:  https://github.com/bahag-chandrana/openapi-generator
> > Can I raise a draft PR to verify the changes or do I need to open a new issue for this?
> 
> Just go for a draft PR and mention me. Looking forward to a freezed option and how you solved Enums support :)

Thanks for the quick feedback. 👍 

Well enums I haven't solved yet, because I am yet to understand the full problem regarding that. Also I noticed @jaumard mentioned he solved it in jaguar implementation perhaps we could borrow that. Freezed can work with the default enum's. I am looking forward to understand that and see if it can be solved. But the general enums works well with pets store api as I understood.

I will raise a draft PR and post further queries there. 😄

**Comment by kuhnroyal** [comment]
@bahag-chandrana Just something I cam across today: https://twitter.com/craig_labenz/status/1491583794054270976

**Comment by bahag-chandrana** [comment]
Yeah, I saw it and this seems good.. But I think soon dart itself will bring it as it is already being [implemented](https://github.com/dart-lang/language/projects/1) . Until then I could have a logic to enable this kind of sealed unions as enums.

**Comment by kuhnroyal** [comment]
We are gonna have a json_serializable option with 6.0.0 and can add a freezed version later. I think this issue can be closed.
