### ISSUE TITLE
[cpprestsdk] If the pthread dependency was removed, can we remove it from the CMakeLists.txt?

### ISSUE THREAD

**Issue by saterHATER** [OpenAPITools/openapi-generator#9101]
https://github.com/OpenAPITools/openapi-generator/blob/5abf020be31669396fbb36ff9696d4006444b2fb/modules/openapi-generator/src/main/resources/cpp-rest-sdk-client/cmake-lists.mustache#L42

I can't fully automate my cppresetSDK generation without having to remove this. Either I don't know what pthread NuGet package I need or this is a faulty template.

**Comment by wing328** [comment]
https://www.cplusplus.com/forum/windows/85295/

looks like you need to install http://www.sourceware.org/pthreads-win32/

**Comment by saterHATER** [comment]
Could either this pre-condition be updated in the generated `README.md` or could there be a way to have the vcpkg pre-install command will install a `pthread-config.cmake` file necessary to get my CMake setup working. Was this library how you got `pthread-config.cmake` file in your cmake modules?

**Comment by wing328** [comment]
Definitely one way is to use customized templates via the `-t`CLI option for the time being.

**Comment by saterHATER** [comment]
Will do. that dependency Solely for windows is a bit strange, though.

**Comment by wing328** [comment]
I've merged https://github.com/OpenAPITools/openapi-generator/pull/9130 to remove pthread from CMakeLists.txt

Please pull the latest master to give it a try.

**Comment by saterHATER** [comment]
I can confirm that I can configure/generate without the need of a custom template. Thank you!
