### ISSUE TITLE
[REQ] Enhancement: support isPassword variable for strings with format: password

### ISSUE THREAD

**Issue by SimeonGerginov** [OpenAPITools/openapi-generator#9124]
### Is your feature request related to a problem? Please describe.

Currently the **isPassword Mustache variable** is only used in the [CodegenSecurity](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/CodegenSecurity.java#L44). However for **strings** with **format: password** there isn't any way to use this information in the **Mustache templates**. My request is for extending the usage of the **isPassword Mustache variable** for **strings** with **format: password**. This way for those **strings** using **isPassword** would indicate that the **string** is of the specified **format**. This will allow specific behaviour for **passwords** in different languages and to differentiate a normal **string** from a **password**.

For example in **C#** and **PowerShell**, **strings** that are **passwords** can be of type [System.Security.SecureString](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring?view=netcore-3.1). I think this is applicable for all other languages as well and will allow differentiating **passwords** in the **OpenAPI** specs.

## Describe the solution you'd like

Add the **isPassword Mustache variable** for **strings** with **format: password** to differentiate them from normal **strings**. The pattern would be the same as for the **isDateTime Mustache variable**.

## Additional context

I'd be happy to contribute this feature if it's approved.

**Comment by rbioteau** [comment]
I'd like to see this feature implemented. Can I submit a PR ?
