### ISSUE TITLE
open-api generator for python not working for subtypes or anyOf/allOf

### ISSUE THREAD

**Issue by thomastack** [OpenAPITools/openapi-generator#9127]
##### Description

I've written a full description of the problem on [stackoverflow](https://stackoverflow.com/questions/63375278/open-api-generator-for-python-not-working-for-subtypes-or-anyof-allof?noredirect=1#comment112189229_63375278).

##### openapi-generator version

openapi-generator-cli-4.3.1

##### OpenAPI declaration file content or url

See [stackoverflow](https://stackoverflow.com/questions/63375278/open-api-generator-for-python-not-working-for-subtypes-or-anyof-allof?noredirect=1#comment112189229_63375278).

##### Command line used for generation

See [stackoverflow](https://stackoverflow.com/questions/63375278/open-api-generator-for-python-not-working-for-subtypes-or-anyof-allof?noredirect=1#comment112189229_63375278).

##### Steps to reproduce

[stackoverflow](https://stackoverflow.com/questions/63375278/open-api-generator-for-python-not-working-for-subtypes-or-anyof-allof?noredirect=1#comment112189229_63375278).

**Comment by wing328** [comment]
Please try the stable version v5.10 or the latest master which should have better support for anyOf and allOf

**Comment by spacether** [comment]
The current python-experimental client generates primitive models with validations. One can see an example of it here:
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python-experimental/petstore_api/model/integer_max10.py#L71

And the current python generator also supports it
https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/number_with_validations.py#L56
