### ISSUE TITLE
[BUG] [cpp-pistache-server] Generated cmake project does not build

### ISSUE THREAD

**Issue by JulianGmp** [OpenAPITools/openapi-generator#9148]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

A recent [pull request](https://github.com/pistacheio/pistache/pull/870) in the pistache repository made changes to their build system, in which the `install` target was removed from the `CMakeLists.txt` (see [diff](https://github.com/pistacheio/pistache/commit/9dc080b9ebbe6fc1726b45e9db1550305938313e#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL107) ).

That target is used by the pistache templates, and thus building the server will currently fail.
Tested on current master (7bf792a3485b967a2ae74f6b3bb3a337ba47e1bb).

Build commands used
```sh
cmake -S . -B build/
cmake --build build/ -j 1 --target all
```

Last bits of the output:
```
[ 16%] Performing build step for 'PISTACHE'
[ 91%] Built target pistache
[ 95%] Built target pistache_static
[100%] Built target pistache_shared
[ 20%] Performing install step for 'PISTACHE'
gmake[3]: *** No rule to make target 'install'.  Stop.
gmake[2]: *** [CMakeFiles/PISTACHE.dir/build.make:93: PISTACHE-prefix/src/PISTACHE-stamp/PISTACHE-install] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:154: CMakeFiles/PISTACHE.dir/all] Error 2
gmake: *** [Makefile:103: all] Error 2
```

##### openapi-generator version

openapi-generator-cli 5.1.1-SNAPSHOT
commit : 7bf792a
built : 2021-04-01T11:56:22+02:00

##### OpenAPI declaration file content or url

The yaml was the sample from https://swagger.io/docs/specification/basic-structure/
```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
```

##### Generation Details

```sh
java -jar modules/openapi-generator-cli/target/openapi-generator-cli.jar generate -g cpp-pistache-server -o out_temp2 -i ./sample.yaml
```

##### Steps to reproduce

1. Clone and build latest master
2. Generate any cpp-pistache-server
3. Run cmake build

##### Related issues/PRs

N/A

##### Suggest a fix

N/A

**Comment by stangerm2** [comment]
Any design reason why the project clones from HEAD? Would it make more sense to lock down pistache by commit hash? New to project and wanted to see this working so hacked `tag='0d09ab982edd03bc8457fa6351af7d0c4a135da2'` into `PISTACHE-gitinfo.txt` after trying to add `GIT_TAG 0d09ab982edd03bc8457fa6351af7d0c4a135da2` into `cmake.mustache`. Not sure the right approach here but if I got some guidance I'd be happy to send PR. Brand new thx :)

**Comment by stangerm2** [comment]
`From e551d2aec48925fc7ee40b0815863e309ebf80ad Mon Sep 17 00:00:00 2001
From: Matthew Stanger <stangerm2@gmail.com>
Date: Tue, 15 Jun 2021 21:34:55 -0700
Subject: [PATCH] Lock PISTACHE fetch to working commit

A recent pull request in the pistache repository made changes to
their build system, in which the install target was removed from
the CMakeLists.txt. That target is used by the pistache templates,
and thus building the server will currently fail.

https://github.com/OpenAPITools/openapi-generator/issues/9148

To avoid this lock the PISTACHE git fetch to the last known
working commit. In the future, once install is resolved upstream,
the rev should be bumped to a currrent or versioned tag/branch/
release.
---
 .../src/main/resources/cpp-pistache-server/cmake.mustache        | 1 +
 1 file changed, 1 insertion(+)

diff --git a/modules/openapi-generator/src/main/resources/cpp-pistache-server/cmake.mustache b/modules/openapi-generator/src/main/resources/cpp-pistache-server/cmake.mustache
index 8fc1b19b7e7..fe80d316438 100644
--- a/modules/openapi-generator/src/main/resources/cpp-pistache-server/cmake.mustache
+++ b/modules/openapi-generator/src/main/resources/cpp-pistache-server/cmake.mustache
@@ -11,6 +11,7 @@ set(EXTERNAL_INSTALL_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/external)

 ExternalProject_Add(PISTACHE
     GIT_REPOSITORY https://github.com/oktal/pistache.git
+    GIT_TAG 0d09ab982edd03bc8457fa6351af7d0c4a135da2
     CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}
 )

-- 
2.25.1

`

**Comment by stangerm2** [comment]
@JulianGmp ^ thoughts?

**Comment by wing328** [comment]
> Pistache hasn't yet hit the 1.0 release. This means that the project is unstable but not unusable. In fact, most of the code is production ready; you can use Pistache to develop a RESTful API without issues, but the HTTP client has a few issues in it that make it buggy.

ref: https://github.com/pistacheio/pistache#project-status

Usually we use stable releases in the auto-generated code but this project hasn't released one yet.

Personally I like the current approach as it allows us to spot issues with ease when there's a change to the official Pistache

> Any design reason why the project clones from HEAD? Would it make more sense to lock down pistache by commit hash?

If one prefer to lock down pistache by commit hash, they can definitely do so using customized templates (e.g. with the `-t` CLI option)

**Comment by wing328** [comment]
Welcome PR to add an option to specify a particular commit or release (default to the latest master for the time being to make it backward-compatible)

**Comment by JulianGmp** [comment]
The option to specify the commit would be nice, but I don't think it fixed this issue.

The Pistache team has removed the install target, which openapi-generators relies on.

I'm no expert in cmake, so I can't really comment on how to fix this though.

**Comment by stangerm2** [comment]
> I didn't actually know pistache hasn't had a stable release yet, which kind of worries me...
> 
> In my use case I actually seperate pistache from the generated code, essentially I only use generated API and model files.
> 
> I think having an option to select a specific commit could be useful.

Agree'd, but I have at least 3 issue's/PR's due with build errors which are hard to gauge if they are really broken b/c of the commit being used for Pistache. Would be great to at least document what the last working setup is considered, as a newbe here I don't have a baseline to go do bug's/PR's against. Anyone have suggested info?
