### ISSUE TITLE
Can it support zh-cn?

### ISSUE THREAD

**Issue by aidensuen** [OpenAPITools/openapi-generator#9160]

**Comment by wing328** [comment]
Not entirely sure about your question but you can use double-byte characters in the spec: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/test/resources/3_0/petstore-with-fake-endpoints-models-for-testing.yaml#L689

**Comment by aidensuen** [comment]
I'm sorry I didn't express myself clearly. I'd like to ask if this tool can support Chinese.
