### ISSUE TITLE
[BUG] [DART] dart-dio-next generator is not truly null safe

### ISSUE THREAD

**Issue by harsimranmaan** [OpenAPITools/openapi-generator#9197]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The current dart-dio-next generator brings it one step closer to null-safety implementation but the current builder pattern delegates the null checks to runtime which are not ideal as dart offers first class support for checking this at compile time. This puts the burden back on the developer to initialize all values that are not null or face issues at runtime

##### openapi-generator version

5.1.1

##### Generation Details
A generated class example
```dart
abstract class Carrier implements Built<Carrier, CarrierBuilder> {
  @BuiltValueField(wireName: r'id')
  String? get id;

  @BuiltValueField(wireName: r'created_at')
  DateTime? get createdAt;

  @BuiltValueField(wireName: r'updated_at')
  DateTime? get updatedAt;

  @BuiltValueField(wireName: r'created_by')
  String? get createdBy;

  @BuiltValueField(wireName: r'tenant_id')
  String get tenantId;

  @BuiltValueField(wireName: r'name')
  String get name;

  @BuiltValueField(wireName: r'eta')
  DateTime? get eta;

  @BuiltValueField(wireName: r'type')
  CarrierType get type;
  // enum typeEnum {  Air,  Rail,  Vessel,  Road,  };

  Carrier._();

  static void _initializeBuilder(CarrierBuilder b) => b;

  factory Carrier([void updates(CarrierBuilder b)]) = _$Carrier;

  @BuiltValueSerializer(custom: true)
  static Serializer<Carrier> get serializer => _$CarrierSerializer();
}
```

##### Steps to reproduce

For the example above, use the generated CarrierBuilder and don't initialize the not-null tenantId value. Note that this is checked only at runtime and is not statically validated, thus bypassing the safety net offered by null-safety in dart.

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following BuiltValueNullFieldError was thrown building Builder(dirty):
flutter: Tried to construct class "Carrier" with null field "tenantId". This is forbidden; to allow it, mark
flutter: "tenantId" with @nullable.
flutter:
flutter: The relevant error-causing widget was:
flutter:   MaterialApp
lib/main_common.dart:145
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      BuiltValueNullFieldError.checkNotNull
package:built_value/built_value.dart:342
flutter: #1      CarrierBuilder.build
package:trober_sdk/…/model/carrier.g.dart:174
```

##### Suggest a fix

I think the fix would be involved requiring an overhaul of the generation is done. The current serializing/deserializing patters would likely not work. Eliminating the builder altogether might be an option but it would impact the extensibility. I'll think more about the use-case and add more details here.

cc: @kuhnroyal

**Comment by kuhnroyal** [comment]
I am afraid this is a limitation but also an advantage of built_value. It allows you to use the builder to build incomplete objects, for example while mapping and with this also provides the ability to partially update an object.

But it only validates once `build()` is called.

There is no way to change this with `built_value` as model/serialization library but the new generator would theoretically allow other implementations. Other generation libraries also partially have this problem, no matter if you use a builder or a `copyWith` function. Currently the only way I can think of is using pure Dart objects with something like `json_serializable`.

You are welcome to provide a different serialization option for the generator :)

**Comment by harsimranmaan** [comment]
I have switched back to https://github.com/dart-ogurets/dart-openapi-maven via https://github.com/bigpanther/trober/pull/113

**Comment by kuhnroyal** [comment]
@wing328 I think this can be closed
