### ISSUE TITLE
[BUG] dart-dio generator fails to generate runnable code with custom classes as parameters or return value of endpoints

### ISSUE THREAD

**Issue by kivan-mih** [OpenAPITools/openapi-generator#9287]
#### Bug Report Checklist

- [ + ] Have you provided a full/minimal spec to reproduce the issue?
- [ + ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ - ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ + ] Have you searched for related issues/PRs?
- [ + ] What's the actual output vs expected output?
- [ - ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
I tried to generate Dart api client using dart-dio generator, but failed to get runable results when input parameters or return value of any endpoint contain custom classes. The root cause of the problem is in that generator doesn't generate "*.g.dart" files which are needed by generated class model files.

**Actual output**
Here is the beginning of sample generated model file:
```
...imports...

part 'some_class4.g.dart';

abstract class SomeClass4 implements Built<SomeClass4, SomeClass4Builder> {
...
```
File some_class4.g.dart does not exist at all.
SomeClass4Builder class does not exist (probably it have to be in some_class4.g.dart)

**Expected output**
File some_class4.g.dart exists.
SomeClass4Builder class exists.

##### openapi-generator version
5.1.0
##### OpenAPI declaration file content or url
[openapi.json](https://gist.githubusercontent.com/kivan-mih/e0d497aa2a3ccf6e2d7f73c0df9c6905/raw/551366381630ef45c5783f0b50ba5e0cf1ba8dc7/sample.json)
##### Generation Details
I generate API directly from Java using code like this:
```
OpenAPIGenerator.main(new String[]{
                        "generate",
                        "-i", "input.json",
                        "-o", "output/",
                        "-g", "dart-dio",
                        "--global-property","skipFormModel=false"
                });
```

##### Steps to reproduce

1. Generate Api client
2. In generated classes you will see model classes with parts like: "part 'some_class4.g.dart'", but the mentioned part files are not present. Also Builder classes for models are absent.

##### Related issues/PRs

Not found.

##### Suggest a fix

Probably g classes are missed somewhy, so they have to be generated.

**Comment by slellampati** [comment]
You need to run dart run build `pub get` and then `dart run build_runner build` to generate .g.dart files
