### ISSUE TITLE
[BUG][TypeScript] Given a model whose name matches a language type, when another model mentions that type, the mention is mistakenly generated as the language type, but should be the renamed model type

### ISSUE THREAD

**Issue by jeremy-w** [OpenAPITools/openapi-generator#9289]
#### Bug Report Checklist

- [X] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs? There's one about renaming of properties open now #1943 but nothing about model names entirely, and a collision of model defs in https://github.com/OpenAPITools/openapi-generator/issues/8187, but nothing that matches this issue.
- [X] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

# Description
When codegen renames a model type to avoid a language type, it appears not to rename all references to that model in other types to match. Those broken references then resolve to the `any` type.

If you have a Folder that references an array of File, when generating the API, you will see:

> [main] WARN  o.o.c.l.AbstractTypeScriptClientCodegen - File (model name matches existing language type) cannot be used as a model name. Renamed to ModelFile

and when you examine the generated API, you will find something like:

```ts
files: Array<any>
```

instead of the expected:

```ts
files: Array<ModelFile>
```

I've tested this with both typescript-fetch (which I'm targeting) and typescript-node (which I tried to see if the issue was bigger than just the template). The core "ModelFile became any" bug showed up in both.

# openapi-generator version

Reproduces against latest HEAD:

openapi-generator-cli 5.1.1-SNAPSHOT
  commit : aa5adbf
  built  : 2021-04-19T06:46:59Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/

# OpenAPI declaration file content or url

```json
{
  "swagger": "2.0",
  "info": {
    "title": "Test swagger",
    "version": "0.1.0"
  },
  "definitions": {
    "File": {
      "title": "File",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "Folder": {
      "title": "Folder",
      "type": "object",
      "properties": {
        "files": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/File"
          }
        }
      }
    }
  },
  "paths": {},
  "host": "localhost:3000",
  "schemes": ["http"]
}
```

Also available as a gist at: https://git.io/JO2vn

Note that, if you rename `File` to `Fiche` throughout, then the generated `Folder` model properly has an `Array<Fiche>`, which points to the renaming being the issue.

Also observed:

- With the type Error, it gets renamed to ModelError, but all refs to Error in another model remain as Error - so the underlying Error, rather than the model. (At least this is less confusing than with File => any.)

# Generation Details

```
#!/bin/bash
SPEC="${SPEC:=/local/swagger.json}"
GENERATOR="${GENERATOR:=typescript-fetch}"
docker run --rm \
    -v "$PWD:/local" \
    openapitools/openapi-generator-cli generate \
        -i /local/swagger.json \
        -g "$GENERATOR" \
        -o "/local/out/$GENERATOR"
echo "If it's been a while, you might want to run: docker pull openapitools/openapi-generator-cli:latest"
```

# Steps to reproduce

- Drop the linked spec into the file `swagger.json` alongside the script from generation details
- Run the script
- Examine the output in out/typescript-fetch/Folder.json to see if files is an Array<ModelFile> or not.

# Related issues/PRs

There's one about renaming of properties open now #1943 but nothing about model names entirely, and a collision of model defs in https://github.com/OpenAPITools/openapi-generator/issues/8187, but nothing that matches this issue.

# Suggest a fix

This looks to be an issue at the core codegen level, rather than a template problem.

Specifically, it seems something is probably forgetting to call [toModelName()](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java#L403), and so the [type mapping of File => any](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/TypeScriptClientCodegen.java#L150) is being applied.

**Comment by AlexMarchini** [comment]
Has there been any workaround found for this? I'm encountering this now where a schema definition named `number` does not get correctly mapped to the model `Number`, and is instead just a primitive `number`.

**Comment by acrantel** [comment]
I am also encountering this error with a schema definition named `Map`. The generated API contains `Array<any>` instead of the expected `Array<ModelMap>`
```
[main] WARN  o.o.c.l.AbstractTypeScriptClientCodegen - Map (model name matches existing language type) cannot be used as a model name. Renamed to ModelMap
```

Workaround was to change the name of the Map definition in the schema.

**Comment by wing328** [comment]
Looks like an issue in getTypeDeclaration in AbstractTypeScriptCodegen.

If anyone wants to contribute or sponsor a fix, please reply to let us know.

**Comment by wing328** [comment]
UPDATE: I've filed https://github.com/OpenAPITools/openapi-generator/pull/16392 to fix it using modelNameMappings
