### ISSUE TITLE
[Bug][Android][Volley] Volley default version (1.0.19) is deprecated

### ISSUE THREAD

**Issue by swapnild-ithena** [OpenAPITools/openapi-generator#9293]
#### Bug Report Checklist

- [ ] Checked for android code generator docs (https://openapi-generator.tech/docs/generators/android/)
- [ ] Checked for volley version documentation (https://github.com/mcxiaoke/android-volley)

##### Description

We tried to generate code for android using library volley. Tool pointing to default version of volley is 1.0.19, after generating code unable to implement/use code.

##### openapi-generator version

Using openapi-generator version 5.1.0

##### updates required
Change volley default version to latest 1.2.0

**Comment by enekonieto** [comment]
Default version now is 1.2.1 (latest as october 2023), I think issue should be closed.
