### ISSUE TITLE
[BUG] Doesn't work GenerateTask on project with Gradle 7.0, @Internal input

### ISSUE THREAD

**Issue by kuFEAR** [OpenAPITools/openapi-generator#9297]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Steps to reproduce

configure gradle task on any gradle project

```
openApiGenerate {
...
}
```
and run `GenerateTask` (`openApiGenerate`) and receive an error 

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':social_model:openApiGenerate' (type 'GenerateTask').
  - Type 'GenerateTask' property 'input' annotated with @Internal should not be also annotated with @Input.
    
    Reason: A property is ignored but also has input annotations.
    
    Possible solutions:
      1. Remove the input annotations.
      2. Remove the @Internal annotation.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#ignored_property_must_not_be_annotated for more details about this problem.
```

##### Suggest a fix

```kotlin
@Suppress("UnstableApiUsage")
@CacheableTask
open class GenerateTask : DefaultTask() {

    @Suppress("unused")
    @set:Option(option = "input", description = "The input specification.")
    @Internal 
    var input: String? = null
        set(value) {
            inputSpec.set(value)
        }
}
```

    Possible solutions:
      1. Remove the input annotations.
      2. Remove the @Internal annotation.

**Comment by wing328** [comment]
Please see https://github.com/OpenAPITools/openapi-generator/issues/9253
