### ISSUE TITLE
[REQ] Static typing in Python client

### ISSUE THREAD

**Issue by HeshamMeneisi** [OpenAPITools/openapi-generator#9302]
### Is your feature request related to a problem? Please describe.

Python clients contain types in the method docs but not in the definition

## Describe the solution you'd like

Types should be included in the definition. 

## Additional context

This can be controlled by a Python target version config (3.7+ contains static types)

I'm ready to work on this if someone just points me to where to start (docs, project setup instructions, etc).

**Comment by wing328** [comment]
> Types should be included in the definition.

Can you please elaborate with an example (current output vs expected output)?

**Comment by HeshamMeneisi** [comment]
# Output

```python
def query_skus(self, **kwargs):  # noqa: E501
        """query_skus  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.query_skus(async_req=True)
        >>> result = thread.get()
        :param brand_id:
        :type brand_id: int
        :param brand_code:
        :type brand_code: str
        :param seller_id:
        :type seller_id: int
        :param page:
        :type page: int
        :param per_page:
        :type per_page: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :type _preload_content: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: QueryInventoryResponse
        """
        kwargs['_return_http_data_only'] = True
        return self.query_skus_with_http_info(**kwargs)  # noqa: E501
```

# Desired

```python
def query_skus(self, brand_id: int, brand_code: str, seller_id: int, per_page: int, page: int, **kwargs) -> QueryInventoryResponse: 
...
```

@wing328

**Comment by spacether** [comment]
@HeshamMeneisi please check your spec definition.
Optional parameters are in kwargs. Required parameters are set as positional args. If you make your args positional they will be in the fn signature.

**Comment by bflaton** [comment]
@HeshamMeneisi I think part of what you'd like to see changed was done recently by one of my pull requests ([10339](https://github.com/OpenAPITools/openapi-generator/pull/10339). I was actually considering making additional improvements to also add method return type hints.

**Comment by HeshamMeneisi** [comment]
@bflaton It helps a lot with IDE support yes! What I was describing here would require a `static_typing` config flag to be backward compatible. Then the format [here](https://github.com/bflaton/openapi-generator/blob/bc3ee3249899cc26567da77cf08ba85a64cf5049/modules/openapi-generator/src/main/resources/python/api.mustache#L37) would be quite different based on that. For example, all parameters have to be defined, not just required. It would look something like `{{paramName}}:{{dataType}} = {{{defaultValue}}}` for params and `): -> {{returnType}}` for return type. When it's not a required param (or default is `None`, generally speaking) the type should be `Optional[{{returnType}}]`.

I'm no longer working with the Python generator though so unlikely to add this myself soon 😅

**Comment by spacether** [comment]
@HeshamMeneisi @shotat @johnthagen @mcdenhoed @theryangeary can you try the python-experimental generator?
It includes type hints for model instantiation and endpoints. It was added in: #8325

**Comment by spacether** [comment]
Closing this issue because the [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata) generator has type hints for all model instantiation, endpoint inputs, and endpoint responses.
