### ISSUE TITLE
[BUG] ValidateTask does not work under Gradle 7.0

### ISSUE THREAD

**Issue by ilya40umov** [OpenAPITools/openapi-generator#9328]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

ValidateTask stops working if gradle version is upgraded to 7.0.

The following task definition works under 6.8.3, but fails under 7.0:

```
val validateOpenApi by registering(ValidateTask::class) {
    group = "verification"
    description = "Validate openapi.yaml"
    recommend.set(true)
    input = "$rootDir/openapi.yaml"
}
val check by registering {
    dependsOn(validateOpenApi)
}
```

Here is the output:
```
* What went wrong:
Some problems were found with the configuration of task ':validateOpenApi' (type 'ValidateTask').
  - Type 'ValidateTask' property 'inputSpec' of mutable type 'org.gradle.api.provider.Property' is writable.

    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.

    Possible solution: Remove the 'setInputSpec' method.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.
  - Type 'ValidateTask' property 'recommend' of mutable type 'org.gradle.api.provider.Property' is writable.

    Reason: Properties of type 'org.gradle.api.provider.Property' are already mutable.

    Possible solution: Remove the 'setRecommend' method.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#mutable_type_with_setter for more details about this problem.
```

##### openapi-generator version

`id("org.openapi.generator") version "5.1.0" apply false`

##### Suggest a fix

Apparently the following properties of ValidateTask should not be declared as `var` as they are already mutable properties anyway:
```
@get:InputFile
@PathSensitive(PathSensitivity.RELATIVE)
var inputSpec = project.objects.property<String>()

@Optional
@Input
var recommend = project.objects.property<Boolean?>()
```

**Comment by wing328** [comment]
Please see https://github.com/OpenAPITools/openapi-generator/issues/9253

**Comment by ilya40umov** [comment]
@wing328 I've checked the MR mentioned in #9253 and as far as I can tell it only deals with `GenerateTask`. Am I missing something?

**Comment by wing328** [comment]
Yes, you're right. That PR only updated `GenerateTask.kt`

I wonder if you've time to file a PR to update `ValidateTask.kt` as well

**Comment by wing328** [comment]
Please submit a PR

**Comment by rm3l** [comment]
> Please submit a PR
>
PR submitted here : #9453

**Comment by fmartinou** [comment]
Hi,

When can we expect to get a release compatible with Gradle7?
