### ISSUE TITLE
[REQ][python] Globally deactivate response check-type and body check-type for production environment

### ISSUE THREAD

**Issue by gbmarc1** [OpenAPITools/openapi-generator#9330]
@spacether 

### Is your feature request related to a problem? Please describe.

I want to use the generated client in a production app. I don't want to check the response type in production because it may fail for nothing.

I don't want to check input type in production because it could slow down the process for nothing. My app should be tested with the checks before deployment.

## Describe the solution you'd like

2 env vars:

CHECK_RESPONSE_TYPE=true|false
CHECK_BODY_TYPE=true|false

## Describe alternatives you've considered

Now I need to individually deactivate the check on each call of any endpoints

**Comment by spacether** [comment]
Some questions here:

When receiving a response with no type checking, isn't that just the same as getting back the raw response? We have a parameter to do that. That can be passed into request calls.

If no types are checked, then the code will not know which schemas apply, which means it will not know what validations to check. For example:
```
composedSchema:
  oneOf:
    - type: string
      minLength: 3
    - type: number
      min: 4 
```
If types are not checked, how will the above model know what validations to check? It will not know so this is the same as receiving the raw response json data.

These parameters could be stored in the python Configuration class.
Endpoint inputs would accept any types with this turned on, responses would return raw json results or binary data (not model instances) with these turned on.
Does that line up with what you are thinking?

**Comment by spacether** [comment]
> it may fail for nothing
It's failing because the server is not conforming with the contract (spec) that you have. Why not update the spec to correctly define what the server does?

**Comment by gbmarc1** [comment]
> > it may fail for nothing
> 
> It's failing because the server is not conforming with the contract (openapi spec) that you have. Why not update the spec to correctly define what the server does?

I don't know if it is good practice but, the specification come from an external party. I generate the client from their specification. However, their specification may change more often than my client. So, if they add a parameter in an endpoint (which is in theory backward compatible), the response check would make the client fail... However, I would not use that new parameter because ( i did not need it before).  The app would "fail for nothing". I would need to update the client while I don't really need it.

But I guess I could use the raw. I did not see that.

**Comment by spacether** [comment]
Another solution for you is to delete the parameters from your spec that you are using. That way everything else is an additional property and any type will be allowed for it. Then there should be no exceptions.

**Comment by spacether** [comment]
Closing this issue because one can skip deserialization by passing arguments that skip response deserialization
in the `python-experimental` and the `python` generators
