### ISSUE TITLE
[BUG][dart-dio-next] Generator uses url encoded contentType even if the server content type requires application/json

### ISSUE THREAD

**Issue by TheMisir** [OpenAPITools/openapi-generator#9334]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I'm using Asp.Net Core Swashbuckle to generate openapi scheme for my backend. The backend supports multiple content-type variants of `application/json`. But generated code uses url encoded content type instead of application/json.

Here's generated code output which picks first match which is "application/json-patch+json". 

```dart
contentType: [
  'application/json-patch+json',
  'application/json',
  'text/json',
  'application/_*+json',
].first
```

But then Did checks if content-type is `application/json` then uses json encoding but if it isn't, it uses url encoding and my server returns **HTTP 415 Unsupported Media Type** status.

##### openapi-generator version

**5.1.0**

##### OpenAPI declaration file content or url

The OpenAPI declaration that caused this issue was used for private api. So I couldn't share it here.

##### Suggest a fix

1. Overriding content-type header using command line options provided to generator CLI
2. Updating `contentType` matching part to choose most suitable match rather than first one

**Comment by kuhnroyal** [comment]
Thanks for the report.
You can try changing the order of the content-types in the spec around, not sure if that works.

But yea this needs some fixing.

**Comment by TheMisir** [comment]
> Thanks for the report.
> You can try changing the order of the content-types in the spec around, not sure if that works.

I've already fixed the issue by manually modifying generated dart code (since scheme is generated on runtime on our backend, modifying dart generated code is way easier for me).

But I think this needs to be fixed. Actually I can work on this issue but I might need a bit of direction for contributing (for example which file(s) implements dart-dio-next generation).

**Comment by kuhnroyal** [comment]
@TheMisir Do you need some help or pointers to get started?

**Comment by TheMisir** [comment]
> @TheMisir Do you need some help or pointers to get started?

Actually the issue is I'm not sure how can I implement it. Currently thinking about continuing the loop below until one of the known types is found.

https://github.com/OpenAPITools/openapi-generator/blob/c966b5fe1f558ff71a7dab98004d33ff3dc4138e/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/DartDioNextClientCodegen.java#L321-L329

I can implement the logic like this.

```java
for (Map<String, String> consume : op.consumes) {
    if (consume.containsKey("mediaType")) {
        String type = consume.get("mediaType");
        isJson = type.equalsIgnoreCase("application/json");
        isForm = type.equalsIgnoreCase("application/x-www-form-urlencoded");
        isMultipart = type.equalsIgnoreCase("multipart/form-data");
        if (isJson || isForm || isMultipart) {
            break;
        }
    }
}
```

So the loop will continue until it matches any known request content type.

What do you think about that?

**Comment by TheMisir** [comment]
> No, I don't think so.
> Basically for dio and Dart, we only care about `application/json`, `application/x-www-form-urlencoded` and `multipart/form-data`.
> Everything else we need to directly filter out and if none of these match we should probably add a warning and default to json.

You're right, thanks for the hint. I'll work on it.
