### ISSUE TITLE
[BUG] DART Generator dependencies are outdated

### ISSUE THREAD

**Issue by lewcianci** [OpenAPITools/openapi-generator#9366]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

The DART code generator has outdated dependencies, namly `intl` and `http`. These outdated dependencies affect the use of generated Dart clients in Flutter projects.

##### openapi-generator version

5.1.2-master

##### Generation Details

java -jar openapi-generator-cli.jar  generate -i http://localhost:8080/swagger/OpenApiDocument/swagger.json -g dart -o ./apiclient -p pubName=apiclient --enable-post-process-file --skip-validate-spec

##### Steps to reproduce

Generate a DART api client and try to use it in a Flutter project.

##### Suggest a fix

Update the dependenies in the pubspec.yaml to a newer version, and slightly adjust the way URI's are handled by the API client. I have a PR coming in shortly for this.

**Comment by wing328** [comment]
What about the `dart-dio` generator? Would that work better for your use cases?

**Comment by lewcianci** [comment]
Thanks for the quick response! I did look at `dart-dio` but I didn't want to rewrite all my api invocations to use `dart-dio` if the fix for the original `dart` generator was simple. Plus, it also commits me to have a dependency on `dio` at a certain version, and I've experienced dependency hell with Flutter quite recently.

Of course, if the original `dart` generator is deprecated and I should move to `dart-dio`, then that's a pretty strong reason to move. But it seemed like the original `dart` generator was still supported.

Would you accept a PR to fix this?

**Comment by wing328** [comment]
> Would you accept a PR to fix this?

Definitely. Always welcome PRs.

The reason I suggested `dart-dio` is that it's pretty active and I saw lots of PRs (enhancements, bug fixes, etc) to it. Understood that you prefer to stick with `dart` generator for the time being.

**Comment by lewcianci** [comment]
I opened the PR. It's my first time contributing to an open-source project, so if I've made a meal of it just let me know 😊

**Comment by lewcianci** [comment]
I opened #9369 against the `master` branch with new commit info. Hopefully that's closer to the mark @wing328 😄

**Comment by kuhnroyal** [comment]
This is related: https://github.com/OpenAPITools/openapi-generator/pull/9392
@lewcianci @Adi1231234 Maybe you 2 can get together for this so we don't have duplicated work.

FYI @agilob @jaumard

**Comment by kuhnroyal** [comment]
@lewcianci Thank you for you work on the dependencies! Unfortunately I have not seen your PR earlier and it looks like we have now settled with #9392. If you mention the Dart technical committee in your next PR and/or issue, we will get notified directly.
It would be much appreciated if you can review and possibly test #9392 to see if it meets your requirements.

**Comment by kuhnroyal** [comment]
@lewcianci @wing328 I think this can be closed
