### ISSUE TITLE
[BUG] Python generator mutates input arguments to endpoints (not thread safe)

### ISSUE THREAD

**Issue by frejonb** [OpenAPITools/openapi-generator#9396]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [ ] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

If you look at this line https://github.com/OpenAPITools/openapi-generator/blob/60dcf8613f6b75b606757c4a991fe018ad10ee99/modules/openapi-generator/src/main/resources/python/api_client.mustache#L741, we're mutating the reference of the input argument with the result of `fixed_val`. This is an issue if passing mutable objects in, for example, async code.

##### openapi-generator version

v5.1.0

##### Suggest a fix

Prefer removing side effects from `__validate_inputs`

**Comment by spacether** [comment]
In the v6.2.0 python generator and onward, input arguments passed in to `__new__` and `from_openapi_data_oapg` are not mutated. Copies are made of all data using cast_to_allowed_types
