### ISSUE TITLE
Chinese characters cannot be identified  .  Resulting in the generated TypeScript code error

### ISSUE THREAD

**Issue by lhtuling** [OpenAPITools/openapi-generator#9436]
I am very sorry that my English is not good. I use the translation software to ask questions.

Chinese characters cannot be identified  .  Resulting in the generated TypeScript code error

You look at the picture 
It should be clearly understood. The variable name is Chinese string. The generated code variable is named empty
![image](https://user-images.githubusercontent.com/44140500/117601093-f982e480-b17f-11eb-8182-738a3c643e05.png)

It is recommended to modify the regular expression, you should solve this problem.
`[a-zA-Z0-9\.\-_]`
↓
`[a-zA-Z0-9\u4e00-\u9fa5\.\-_]`

**Comment by wing328** [comment]
so the property names are in Chinese? Does typescript/javascript itself support double-byte characters in the property name?

**Comment by lhtuling** [comment]
> so the property names are in Chinese? Does typescript/javascript itself support double-byte characters in the property name?
yes typescript/javascript All support

**Comment by lhtuling** [comment]
JavaScript
`
var 测试="test"
console.log(测试)
`
typescript
`
const 测试 : string = "test"
console.log(测试)
`
