### ISSUE TITLE
Gradle 7.x fails on ValidateTask

### ISSUE THREAD

**Issue by surfing** [OpenAPITools/openapi-generator#9452]
https://github.com/OpenAPITools/openapi-generator/blob/c966b5fe1f558ff71a7dab98004d33ff3dc4138e/modules/openapi-generator-gradle-plugin/src/main/kotlin/org/openapitools/generator/gradle/plugin/tasks/ValidateTask.kt#L67

to have a setInputSpec method is not allowed in gradle 7 anymore. See
https://docs.gradle.org/7.0/userguide/validation_problems.html#mutable_type_with_setter

The same problem is reported on the recommend property

**Comment by Deepu978** [comment]
@surfing do you know is this is still an issue or fixed ?

**Comment by surfing** [comment]
Fixed by 5.2.0 with issue #9453
