### ISSUE TITLE
Java Codegen throws NullPointerException

### ISSUE THREAD

**Issue by vladaman** [OpenAPITools/openapi-generator#9474]
Not sure why, but this line causes Nullpointer Exception when generating OpenAPI:

https://github.com/OpenAPITools/openapi-generator/blob/ecedd28e4eab2cfb7c1aabe50ff7383c6b064a32/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractJavaCodegen.java#L1106

Solution which worked for me:
```java
if (p.items != null && p.items.defaultValue != null) {
```

**Comment by wing328** [comment]
Please open a PR with the suggested fix so that the change will be tested by the CIs
