### ISSUE TITLE
[Kotlin][Retrofit2] Runtime error occurs when Retrofit2 query parameter is an enum list

### ISSUE THREAD

**Issue by alitams** [OpenAPITools/openapi-generator#9481]
##### Description

There is a problem in Retrofit2: https://github.com/square/retrofit/issues/2457 It won't be fixed, it needs to be handled ourself in Kotlin. The problem occurs when one of the @Query parameter is a list of enums. It is generated by the compiler to this form: 
`java.util.List<? extends com.orange.datashare.api.EnumQueryParameter>`
It makes the following error: 
`java.lang.IllegalArgumentException: Parameter type must not include a type variable or wildcard: java.util.List<? extends com.orange.datashare.api.EnumQueryParameter> (parameter #1)`

So I think the solution is to generate `@JvmSuppressWildcard` when a Collection is used.

##### openapi-generator version

5.1.0

##### OpenAPI declaration file content or url

```yaml
paths:
  "/getcards":
    get:
      summary: "Get the cars"
      description: >-
        The endpoint returns all of the available cars.
      operationId: getCarList
      tags:
        - cars
      parameters:
        - name: type
          in: query
          description: Type filter
          required: false
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CarTypeEnum"
```
``` yaml
components:
  schemas:
    CarTypeEnum:
      type: string
      description: >-
        Offer type
      enum:
        - OPEL
        - AUDI
        - KIA
```
##### Steps to reproduce

Try to generate similar code of above. 

##### Suggest a fix/enhancement

Replace the jvm-retrofit2/queryParams.mustache template with this:

`{{#isQueryParam}}@Query("{{baseName}}") {{{paramName}}}: {{#collectionFormat}}{{#isCollectionFormatMulti}}@JvmSuppressWildcards {{{dataType}}}{{/isCollectionFormatMulti}}{{^isCollectionFormatMulti}}{{{collectionFormat.toUpperCase}}}Params{{/isCollectionFormatMulti}}{{/collectionFormat}}{{^collectionFormat}}{{{dataType}}}{{/collectionFormat}}{{^required}}? = null{{/required}}{{/isQueryParam}}`

**Comment by gretzki** [comment]
Thanks for the tip. Will give it a try.
I want to add to the solution:
If the enum type is declared inplace w/o using a ref, it is somehow working.

**Comment by magnussp** [comment]
This is still an issue. Would a PR with this proposed fix be needed for this to be reviewed and accepted?

**Comment by wing328** [comment]
Yes, please file a PR and we'll start from there.

**Comment by ivanvasheka-intellias** [comment]
The issue is still active. Please check - https://github.com/OpenAPITools/openapi-generator/pull/17892
