### ISSUE TITLE
[BUG] Python client API test not functional

### ISSUE THREAD

**Issue by jkupferer** [OpenAPITools/openapi-generator#9482]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

There is a logic error in the Python manual test `test_fake_api.py`

https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/tests_manual/test_fake_api.py#L78-L85

In the method `assert_request_called_with`:

```
        if 'body' in kwargs:
            used_kwargs['body'] = kwargs['body']
        else:
            mock_method.assert_called_with(
                http_method,
                url,
                **used_kwargs
            )
```

This logic results in no assertion test being applied when the `body` keyword arg is passed.

Fixing this unmasks other errors in the library. For example, the actual request for className ends up sending a body with both className and class_name:

```
AssertionError: expected call not found.
Expected: request('POST', 'http://petstore.swagger.io:80/v2/fake/refs/arraymodel', _preload_content=True, _request_timeout=None, headers=HTTPHeaderDict({'Accept': 'application/json', 'User-Agent': 'OpenAPI-Generator/1.0.0/python', 'Content-Type': 'application/json'}), query_params=[], post_params=[], body=[{'className': 'Cat', 'color': 'black'}])
Actual: request('POST', 'http://petstore.swagger.io:80/v2/fake/refs/arraymodel', headers=HTTPHeaderDict({'User-Agent': 'OpenAPI-Generator/1.0.0/python', 'Accept': 'application/json', 'Content-Type': 'application/json'}), query_params=[], post_params=[], _preload_content=True, _request_timeout=None, body=[{'className': 'Cat', 'color': 'black', 'class_name': 'Cat'}])
```

##### openapi-generator version

Latest version in master branch

##### OpenAPI declaration file content or url

n/a

##### Generation Details

n/a

##### Steps to reproduce

n/a

##### Suggest a fix

Fix logic error in `assert_request_called_with` to make call to `assert_called_with` not depend on `body` keyword arg, then run `nosetests -v`:

```
        if 'body' in kwargs:
            used_kwargs['body'] = kwargs['body']
        mock_method.assert_called_with(
            http_method,
            url,
            **used_kwargs
        )
```

This uncovers a number of other problems both with the tests and the library which likely need to be reported in separate issues.

**Comment by spacether** [comment]
Thanks for reporting this 👍

**Comment by spacether** [comment]
All fixed
