### ISSUE TITLE
[REQ] [typescript-angular] Support Angular 12

### ISSUE THREAD

**Issue by MaurizioCasciano** [OpenAPITools/openapi-generator#9511]
### Is your feature request related to a problem? Please describe.

I want to have the API clients generated using ngVersion=12.0.0.
## Describe the solution you'd like
Update the typescript and ngpackagr dependencies if ngVersion is set to 12.
Here are the only changes required in the _package.json_ file.
![Screenshot from 2021-05-24 18-40-13](https://user-images.githubusercontent.com/12021064/119379369-b10b1100-bcbf-11eb-97d3-ae3a2d173088.png)

**Comment by xCryzed** [comment]
Didn't you have any problems with tsickle?

**Comment by MaurizioCasciano** [comment]
@xCryzed luckly not. Maybe because it is just a minor version update from ^0.39.1 to ^0.40.0

**Comment by arrigod** [comment]
Hello, I would also be interested in this feature. Is this going to be integrated soon?

**Comment by mimkorn** [comment]
Also interested. For now, you can modify it like this manually:
```
  "devDependencies": {
    "@angular/common": "^12.0.0",
    "@angular/compiler": "^12.0.0",
    "@angular/compiler-cli": "^12.0.0",
    "@angular/core": "^12.0.0",
    "@angular/platform-browser": "^12.0.0",
    "ng-packagr": "^12.0.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "^6.6.0",
    "tsickle": "^0.39.1",
    "typescript": ">=4.2.3 <4.3.0",
    "zone.js": "^0.11.3"
  }}
```

and put `package.json` into `.openapi-generator-ignore` file in the root of the output folder, if you want to avoid having it rewritten everytime you generate.

**Comment by Geigerkind** [comment]
+1

**Comment by letmejustfixthat** [comment]
Maybe for some ending here. I had a hard time to figure out how to actually overwrite the template as the files option linked in mimkorn's answer doesn't exist in the maven plugin (the docs are kinda misleading). So here's a how to:
 
Set the template directory in the execution in the pom.xml

```
<execution>
    <goals>
        <goal>generate</goal>
    </goals>
    <phase>generate-sources</phase>
    <id>Generate angular service</id>
    <configuration>
        <inputSpec>${project.basedir}/src/main/resources/hcl-types.yaml</inputSpec>
        <generatorName>typescript-angular</generatorName>
        <configOptions>
            ...
        </configOptions>
        <output>${project.build.directory}/generated-sources/angular</output>
        ...
        <templateDirectory>${project.basedir}/templates/angular</templateDirectory>
    </configuration>
</execution>
```

Inside of the template directory we can now overwrite the template, the filename is important here (that was what I was missing): `package.mustache`

You can find the original file here: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/typescript-angular/package.mustache

**Comment by mimkorn** [comment]
@letmejustfixthat maven plugin does support it, see:

ignoreFileOverride | openapi.generator.maven.plugin.ignoreFileOverride | specifies the full path to a .openapi-generator-ignore used for pattern based overrides of generated outputs
-- | -- | --

from https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin#general-configuration-parameters 

can be used like

```
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <!-- RELEASE_VERSION -->
    <version>5.1.0</version>
    <!-- /RELEASE_VERSION -->
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/api.yaml</inputSpec>
                <generatorName>java</generatorName>
<ignoreFileOverride>your/path/to/.openapi-generator-ignore</ignoreFileOverride>
                <configOptions>
                   <sourceFolder>src/gen/java/main</sourceFolder>
                </configOptions>
            </configuration>
        </execution>
    </executions>
</plugin>
```

**Comment by jogelin** [comment]
Angular 12 also add the possibility to set the context for interceptors: https://netbasal.com/new-in-angular-v12-passing-context-to-http-interceptors-308a1ca2f3dd

However, we don't have access directly to the HTTP service call. Would it be possible to include this feature too?

**Comment by macjohnny** [comment]
anybody willing to contribute angular 12 support, similar to https://github.com/OpenAPITools/openapi-generator/pull/7937?
