### ISSUE TITLE
[BUG] [PYTHON] Array of objects has incorrect openapi_types

### ISSUE THREAD

**Issue by timothyjlaurent** [OpenAPITools/openapi-generator#9514]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [X] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-paser/online/))?
- [X] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [X] Have you searched for related issues/PRs?
- [X] What's the actual output vs expected output?

##### Description

An openapi model with a field that is an array of objects gets compiled to expect a dictionary in the python generator.

Here is the resultant part of the generated model:

```python   
    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            'outputs': ({str: (bool, date, datetime, dict, float, int, list, str, none_type)},),  # noqa: E501
        }
```

So instead of expecting a list of any type, it expects a dict of any type which of course fails validation.

##### openapi-generator version

0.5.1 and latsest
##### OpenAPI declaration file content or url

(for YAML code) or
```json
      "OCRResponse": {
        "title": "OCRResponse",
        "required": [
          "outputs"
        ],
        "type": "object",
        "properties": {
          "outputs": {
            "title": "Outputs",
            "type": "array",
            "items": {
              "type": "object"
            },
            "additionalProperties": true,
            "description": "OCR output from google."
          }
        },
        "additionalProperties": false,
        "description": "Custom base model class with default configuration settings. "
      },
```

##### Generation Details

```bash
#!/usr/bin/env bash

# Usage:
#
#     ./generate_client.sh $client_language
#
#     where client language is one of python (default), scala, javascript

set -e

CLIENT_LANG=${1:-python}

OPENAPI_CLI_VERSION_TAG=v5.1.1
OPENAPI_CLI_VERSION_TAG=latest

OUTPUT_DIR="${PWD}/generated_${CLIENT_LANG}"

rm -rf "${OUTPUT_DIR}"
mkdir -p "${OUTPUT_DIR}"

docker run --rm \
    -v "${OUTPUT_DIR}:/local/out" \
    -v "${PWD}:/local/conf" \
    -i "openapitools/openapi-generator-cli:${OPENAPI_CLI_VERSION_TAG}" \
    generate -i /local/conf/openapi.json -g "${CLIENT_LANG}" -o /local/out --config /local/conf/config.json

```

##### Steps to reproduce

Genera

**Comment by spacether** [comment]
It looks like there is an error in your source spec.
`"additionalProperties": true,` should not be defined in your array definition
It only applies to object types, not array types.

**Comment by spacether** [comment]
All types in models and properties are not consistent with openapi spec types in the openapi-generator v6.2.0 python client
