### ISSUE TITLE
[typescript-fetch] Missing configuration option for CORS

### ISSUE THREAD

**Issue by miguescri** [OpenAPITools/openapi-generator#9518]
##### Description

The typescript-fetch main class `BaseAPI` implemented in [runtime.mustache](https://github.com/OpenAPITools/openapi-generator/blob/f48311dac4738716ec808c6544971d3fdb765f35/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache) is not able to use the `mode` atribute of `fetch`. As a result, it is not posible to enable CORS.

The fetch implementation used in the template for Typescript 3+, `WindowOrWorkerGlobalScope['fetch']` 

https://github.com/OpenAPITools/openapi-generator/blob/f48311dac4738716ec808c6544971d3fdb765f35/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache#L117 

is defined [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch) and includes `mode` as one of the keys of the `init` dictionary, used to specify if the request should allow CORS or not.

Neither the `RequestOpts` interface nor the `createFetchParams` method take that into consideration, making the functionality inaccessible in the generated code.

##### openapi-generator version

Running latest Docker image (5.2.0-SNAPSHOT), but also present in latest main branch.

##### Suggest a fix/enhancement

I'm not familiar with the codebase, so I don't know if there are more changes to propagate (maybe test files?), but I think this diff in [runtime.mustache](https://github.com/OpenAPITools/openapi-generator/blob/f48311dac4738716ec808c6544971d3fdb765f35/modules/openapi-generator/src/main/resources/typescript-fetch/runtime.mustache) should be enough to make the functionality usable by the client.

```diff
@@ -59,6 +59,7 @@ export class BaseAPI {
             method: context.method,
             headers: headers,
             body,
+            mode: context.mode,
             credentials: this.configuration.credentials
         };
         return { url, init };
@@ -186,6 +187,7 @@ export type HTTPMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'OPTIONS'
 export type HTTPHeaders = { [key: string]: string };
 export type HTTPQuery = { [key: string]: string | number | null | boolean | Array<string | number | null | boolean> | HTTPQuery };
 export type HTTPBody = Json | FormData | URLSearchParams;
+export type HTTPMode = 'cors' | 'no-cors' | 'same-origin';
 export type ModelPropertyNaming = 'camelCase' | 'snake_case' | 'PascalCase' | 'original';
 
 export interface FetchParams {
@@ -199,6 +201,7 @@ export interface RequestOpts {
     headers: HTTPHeaders;
     query?: HTTPQuery;
     body?: HTTPBody;
+    mode?: HTTPMode;
 }
```

**Comment by miguescri** [comment]
I just realized that these changes do not make it possible for the user to specify that the generated functions use CORS or not. 

I'm not sure which would be the best approach for this, but maybe adding a field in `ConfigurationParameters` that functions read when calling `BaseAPI.request()` or `BaseAPI.fetchApi()`? In a similar fashion to when they call `BaseAPI.configuration.accessToken` to obtain OAuth tokens.

**Comment by miguescri** [comment]
After a while I've realized that the problem with CORS was on my code.

For future reference of people like me, if the server properly specifies the allowed origins, there is no need to use the `mode` parameter of `fetch`.

**Comment by gormonn** [comment]
you can change mode by adding middleware:
```
const API = new Api().withPreMiddleware(preMiddleware);

function preMiddleware(context: ResponseContext): Promise<FetchParams | void> {
  return Promise.resolve({
    url: context.url,
    init: {
      ...context.init,
      mode: "cors"
    },
  });
}
```

**Comment by ollyde** [comment]
<img width="917" alt="Screenshot 2024-01-28 at 13 18 52" src="https://github.com/OpenAPITools/openapi-generator/assets/6940726/7b908b42-7bc2-483f-9b0f-983f57cb1808">
