### ISSUE TITLE
[REQ][Dart][dioNext]:  Add toJson and fromJson to models

### ISSUE THREAD

**Issue by markbeij** [OpenAPITools/openapi-generator#9534]
I want to save certain models that I receive from the api. Therefor I want to serialise and deserialise the models to json.
Although this is possible, the code would be more readable when `toJson()` and `fromJson()` are generated by the dioNext generator.

**Comment by kuhnroyal** [comment]
I don't think thats possible. To (de)serialize with `built_value` a `Serializers` instance is needed. We have a static instance but in most cases this gets overridden by the user with additional serializer and then we don't have the correct instance available.

**Comment by kuhnroyal** [comment]
Some work has started in #9980 to support `json_serializable` as a new serialization library which has `toJson()/fromJson()` methods.
But as I said, with the current `built_value` based implementation this is not really possible.
