### ISSUE TITLE
[REQ][Dart] dioNext: Replace `dynamic` with `Object?`

### ISSUE THREAD

**Issue by mzdm** [OpenAPITools/openapi-generator#9548]
## Describe the solution you'd like

Thank you, this dart lib is the only one, which supports null safety.

With null safety, we can replace `dynamic` type with `Object?` type, which is safer.

## Additional context

https://twitter.com/remi_rousselet/status/1362202496773615616?s=20

**Comment by kuhnroyal** [comment]
This is very broad and not very actionable for me. I know there are very few places where we actually use `dynamic`. Header maps come to mind.

**Comment by mzdm** [comment]
> This is very broad and not very actionable for me. I know there are very few places where we actually use `dynamic`. Header maps come to mind.

I see 👍

**Comment by kuhnroyal** [comment]
If you have a specific place where you notice this, feel free to create a PR or open an issue with specifics.
