### ISSUE TITLE
[REQ] Support `Set` in python for array w/ uniqueItems=True

### ISSUE THREAD

**Issue by Gidgidonihah** [OpenAPITools/openapi-generator#9552]
### Is your feature request related to a problem? Please describe.

In upgrading from 5.0.1 to 5.1.0 I found that the types changed for arrays with `uniqueItems=True` from `Set` to `list`. For us, this was a breaking change as we rely upon type hints.

## Describe the solution you'd like

IMO, **`Set` should be mapped to `set` in python**, rather than to `list`. The tradeoff is that the array is not ordered, but it enforces (or rather easily allows us to enforce when deserializing using the supplied type) the `uniqueItems` constraint.

## Describe alternatives you've considered

Alternatively, we don't marshall with set, and alter to the templates to handle duplicate values with `uniqueItems`.

## Additional context

[The refactor to add a python ABC](https://github.com/OpenAPITools/openapi-generator/pull/8817) in essence added a `Set` to `list` mapping to the `AbstractPythonConnexionServerCodegen ` class via `AbstractPythonCodegen`, whereas previously it assumed a model of `Set`. This worked well as we could `from typing import Set`.

We then had custom templates that looked at `__origin__` and applied mutations. As of 5.1 `Set` is now mapped to `list` and no longer allows us to do so.

Additionally, when using the python-flask templates, `Set` [is currently mapped][mapping-set] to `list` whereas `array` [is currently mapped][mapping-array] to `List`.

[mapping-array]: https://github.com/OpenAPITools/openapi-generator/blob/6daecb88c2cad654da8fdca37c71bb7c2b5db709/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonConnexionServerCodegen.java#L78
[mapping-set]: https://github.com/OpenAPITools/openapi-generator/blob/6daecb88c2cad654da8fdca37c71bb7c2b5db709/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/AbstractPythonCodegen.java#L86

See also https://github.com/OpenAPITools/openapi-generator/issues/8784

**Comment by wing328** [comment]
Thanks for reporting the issue. I'll see what I can do to fix it this week.

**Comment by spacether** [comment]
uniqueItems has been added to the python-experimental generator in https://github.com/OpenAPITools/openapi-generator/pull/8325
The data type was kept as tuple to allow other schemas with type list->(enforced as tuple) lacking uniqueItems to correctly validate against a list payload with unique items.
That way data like 
[0, 1]
will validate against: UniqueList + ListWithMinitems
```
UniqueList:
  type: array
  uniqueItems: true
ListWithMinitems:
  type: array
  minItems: 2
```

**Comment by spacether** [comment]
Closing this issue because it is implement in [python-experimental](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/python-experimental.md#metadata)
