### ISSUE TITLE
Discussion: change the release frequency?

### ISSUE THREAD

**Issue by jmini** [OpenAPITools/openapi-generator#956]
Since the start of the project we have used following release schedule:

In average **one release each week**.

* Each month a release containing breaking changes with fallback:
  - [3.0.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.0.0) June 2018
  - [3.1.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.1.0) July 2018
  - [3.2.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.2.0) August 2018
  - `3.3.0` September 2018
* After each of those release, we provided 3 bugfix release. if we have a look at the 3.2.x release :
  - [3.2.0](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.2.0) 2018-08-06
  - [3.2.1](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.2.1) 2018-08-14
  - [3.2.2](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.2.2) 2018-08-22
  - [3.2.3](https://github.com/OpenAPITools/openapi-generator/releases/tag/v3.2.3) 2018-08-30

Is this release frequency appropriate ?

If the time between two releases was changed to 10 days or 2 weeks, would it impact your project ?

More generally, are you switching to a release when it is published ? Or are you waiting ? Are you using Snapshots builds ?

Feedback is appreciated.

We need to understand what we need to do about release cycles. Every input is welcomed.

**Comment by jmini** [comment]
I forgot to say that the consideration to change the release schedule is not for `3.3.0`. A new schedule could be used starting with `3.3.1`.

cc: @OpenAPITools/generator-core-team, @OpenAPITools/openapi-generator-collaborators

**Comment by wing328** [comment]
I vote for a bi-weekly patch release and bi-monthly minor release.

**Comment by grokify** [comment]
I like frequent releases as it helps get new fixes in and provides feedback to contributors making updates. It's a big difference from other projects. One or two weeks apart is fine, though I'd prefer if it wasn't longer, e.g. a month or more.

**Comment by wing328** [comment]
If we decide to update the release schedule, we'll need to update our documentation. Here is a list for tacking:

- https://github.com/OpenAPITools/openapi-generator/blob/master/docs/qna.md#why-was-it-decided-to-fork-swagger-codegen-and-to-maintain-a-community-driven-version
- https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-long-does-it-take-to-release-a-stable-version-eg-305--306

**Comment by wing328** [comment]
OK. Let's start with the upcoming minor release 3.3.0, which has been rescheduled to Oct 1st (Mon) to follow the bi-monthly release schedule

**Comment by wing328** [comment]
> If there's a track record of patch releases not introducing regressions, I'd be sold on upgrading optimistically every time there's a new release

Thanks for the feedback. So far we've not heard any report of regressions between patch release.

We hope the smaller patch release will be easier to upgrade.
