### ISSUE TITLE
[BUG] java-feign client compile breaks since 5.0.1

### ISSUE THREAD

**Issue by rainmanhhh** [OpenAPITools/openapi-generator#9589]
generate java-feign client with 5.0.0, everything is ok
but with 5.0.1~5.1.1, compile failed. (**NOTICE**: errors are in common code like ApiClient and OauthPasswordGrant, so it's not related to api doc definition, a petstore sample can reproduce the same errors)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project baseinfo-client: Compilation failure: Compilation failure:
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\ApiClient.java:[111,58] 错误: 找不到符号
[ERROR]   符号:   类 OAuthFlow
[ERROR]   位置: 类 ApiClient
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\auth\OauthPasswordGrant.java:[7,40] 错误: 找不到符号
[ERROR]   符号: 类 OAuth
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\auth\OauthPasswordGrant.java:[26,12] 错误: 找不到符号
[ERROR]   符号:   类 OAuthFlow
[ERROR]   位置: 类 OauthPasswordGrant
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\auth\OauthClientCredentialsGrant.java:[7,49] 错误: 找不到符号
[ERROR]   符号: 类 OAuth
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\auth\OauthClientCredentialsGrant.java:[23,12] 错误: 找不到符号
[ERROR]   符号:   类 OAuthFlow
[ERROR]   位置: 类 OauthClientCredentialsGrant
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\ApiClient.java:[113,11] 错误: 找不到符号
[ERROR]   符号:   变量 password
[ERROR]   位置: 类 ApiClient
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\ApiClient.java:[114,15] 错误: 不兼容的类型: OauthPasswordGrant无法转换为RequestInterceptor
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\ApiClient.java:[115,11] 错误: 找不到符号
[ERROR]   符号:   变量 application
[ERROR]   位置: 类 ApiClient
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\ApiClient.java:[116,15] 错误: 不兼容的类型: OauthClientCredentialsGrant无法转换为RequestInterceptor
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\auth\OauthPasswordGrant.java:[16,2] 错误: 方法不会覆盖或实现超类型的方法
[ERROR] E:\workspace\microServices\base-info\base-info\java-feign\out\src\main\java\fy\baseinfo\client\auth\OauthPasswordGrant.java:[19,13] 错误: 找不到符号

**Comment by wing328** [comment]
Have you tried the latest master? You can find the link to the SNAPSHOT version in the readme.

**Comment by rainmanhhh** [comment]
> Have you tried the latest master? You can find the link to the SNAPSHOT version in the readme.

just tried 20210513 jar and it reports the same errors

**Comment by rainmanhhh** [comment]
my config.yml:
```yaml
groupId: fy
artifactId: baseinfo-client
apiPackage: fy.baseinfo.client.api
artifactDescription: baseinfo java client
artifactVersion: 1.0.0-SNAPSHOT
asyncNative: true
dateLibrary: java8
hideGenerationTimestamp: true
invokerPackage: fy.baseinfo.client
java8: true
library: feign
modelPackage: fy.baseinfo.client.model
```

**Comment by caponord** [comment]
Same issue, I am on version 5.1.1

```
plugins {
    id "org.openapi.generator" version "5.1.1"
}
```


`task buildCommissions(type: org.openapitools.generator.gradle.plugin.tasks.GenerateTask) {
    verbose = true
    validateSpec = true
    generatorName = "java"
    library = "feign"
    inputSpec = "$project.projectDir/api_specs/service_api.json".toString()
    outputDir = "$buildDir/service_api".toString()
    apiPackage = "eldorado.restclient.service_api"
    modelPackage = "eldorado.restclient.service_api.model"
    generateApiTests = false
    generateApiDocumentation = false
    configOptions = [
            dateLibrary: "java8"
    ]
}`

Any tips, need assistance very badly.

**Comment by caponord** [comment]
Right, to use the open api generator snapshot in gradle,  in settings.gradle add:

```
pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots'
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id == "org.openapi.generator") {
                useModule("org.openapitools:openapi-generator-gradle-plugin:${requested.version}")
            }
        }
    }
}

```
And then in build.gradle:
```
plugins {
    id "org.openapi.generator" version "5.2.0-SNAPSHOT"
}
```
