### ISSUE TITLE
[REQ][Dart] dioNext: .toString() for builders

### ISSUE THREAD

**Issue by markbeij** [OpenAPITools/openapi-generator#9592]
In unit tests comparing builders with expected builders gets me errors like 

>    Which: at location [1] is TrackerStoppedState:<TrackerStoppedState(Instance of 'MobileTransactionBuilder')> instead of TrackerStoppedState:<TrackerStoppedState(Instance of 'MobileTransactionBuilder')>

When `.toString()` is implemented I get more detailed exceptions which makes it a lot easier to solve issues.

**Comment by kuhnroyal** [comment]
`toString()` for builders is automatically generated by built_value

**Comment by kuhnroyal** [comment]
@markbeij  Can you please check if the `toString` method is correctly generated by `built_value`?
The OpenAPI generator does not generate the `MobileTransactionBuilder`, `built_value` does.

**Comment by kuhnroyal** [comment]
Sorry, `toString()` is not generated for builders but this is also not something we can do on our end. You will have to open an issue in `built_value`.
