### ISSUE TITLE
[BUG][Python] readOnly property inside of allOf causes "The input data was invalid for the allOf schema"

### ISSUE THREAD

**Issue by mfmarche** [OpenAPITools/openapi-generator#9596]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [x] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

This is related specifically to the python generator.

Here is an example schema:

##### openapi-generator version

master

##### OpenAPI declaration file content or url

```
openapi: 3.0.0
info:
  title: Sample test
  version: '2.0'
paths:
  /v2/projects:
    post:
      operationId: sample_post
      summary: sample
      tags:
        - Samplek
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/parent'
      responses:
        '200':
          description: OK
components:
  schemas:
    parent:
      allOf:
        - $ref: '#/components/schemas/child'
    child:
      type: object
      properties:
        test_readonly:
          type: string
          readOnly: true
          example: 4e1bfbc3
```

##### Generation Details

```
java -jar openapi-generator-cli.jar generate -i test.yaml -g python
```

##### Steps to reproduce

```
from openapi_client.model import parent
parent.Parent._from_openapi_data(test_readonly="foobar")
<snip>
openapi_client.exceptions.ApiValueError: Invalid inputs given to generate an instance of 'Child'. The input data was invalid for the allOf schema 'Child' in the composed schema 'Parent'. Error=`test_readonly` is a read-only attribute. Use `from_openapi_data` to instantiate class with read only attributes.
```

##### Suggest a fix

I made a quick fix to model_utils.mustache as follows:

https://github.com/mfmarche/openapi-generator/commit/eb28082c6187d638b590c0dc75adce78a1153444#diff-5378d085f86e7e92f3e0044670bce659d30efdfe1f0c31a502b5da22ba6e2070R1458

But likely inappropriate since it now always calls _from_openapi_data, but rather it should likely use either__init__ or _from_openapi_data depending on the caller.

**Comment by spacether** [comment]
Yes it should definitely call either `__init__` or _from_openapi_data depending on the caller

**Comment by languitar** [comment]
Does anyone know when this issue was introduced?

**Comment by languitar** [comment]
Ah, with 5.2.0. This is a serious blocker for using 5.2.0 when generating Python clients. Any chance to get this fixed?

**Comment by mfmarche** [comment]
#9735 has a fix for this that should address this issue. That fix is currently in review and fixes are pending.

**Comment by spacether** [comment]
Fixed per PR
