### ISSUE TITLE
[BUG][KOTLIN] StackOverflowError when printing a schema that contains the `allOf` property

### ISSUE THREAD

**Issue by Murrx** [OpenAPITools/openapi-generator#9616]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
  - Expect: a generated model. Actual: StackOverflowError

##### Description

Given a schema that contains the `allOf` property
When I use the Kotlin generator to output this schema in a template using {{this}}
Then an StackOverflowError occurs

##### openapi-generator version
v5.1.1

##### OpenAPI declaration file content or url

```yaml
openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
paths: {}
components:
  schemas:
    Pet:
      type: object
      discriminator:
        propertyName: petType
      properties:
        petType:
          type: string
      required: [ petType ]

    Dog:
      allOf:
        - $ref: "#/components/schemas/Pet"
        - type: object
          properties:
            name:
              type: string
```
##### Used template

data_class.mustache:
``` mustache
{{this}}
``` 

##### Generation Details
generator: `kotlin-server` or `kotlin`
template: see above
input spec: see abote 

##### Steps to reproduce
`openapi-generator generate -i openapi.yaml -g kotlin -t templates/`

##### Suggest a fix

`CodegenModel.toString()` runs into an infinite loop between printing `parentSchema` and `children`. However this error seems to happen in the Kotlin generator and not in all other generators, so the root of the problem must lie somewhere else

**Comment by wing328** [comment]
tested with the latest master and no longer seeing the same issue

please give it another try with the latest master

happy to reopen the issue if needed
