### ISSUE TITLE
[openapi-generator-gradle-plugin] - Failure with Gradle 4.10

### ISSUE THREAD

**Issue by fmartinou** [OpenAPITools/openapi-generator#962]
##### Description
Hello, the openapi-generator-gradle-plugin seems to be broken with Gradle 4.10.
```
org.gradle.kotlin.dsl.NamedDomainObjectContainerScope.invoke(Ljava/lang/String;Lkotlin/reflect/KClass;)Ljava/lang/Object;
```

##### openapi-generator version
org.openapitools:openapi-generator-gradle-plugin:3.2.3

##### Platform
------------------------------------------------------------
Gradle 4.10
------------------------------------------------------------

Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Oracle Corporation 25.181-b13)
OS:           Linux 4.15.0-32-generic amd64

##### OpenAPI declaration file content or url

build.gradle
```
buildscript {
    dependencies {
        classpath "org.openapitools:openapi-generator-gradle-plugin:3.2.3"
    }
}

apply plugin: 'org.openapi.generator'
openApiGenerate {
...
}
```

##### Command line used for generation
./gradlew build

##### Steps to reproduce
It works with gradlew 4.8 and 4.9.
It fails with gradlew 4.10.

**Comment by jimschubert** [comment]
Looks like we'll need to update Kotlin and Kotlin DSL in the plugin as it looks like ABI incompatibility with the versions in Gradle 4.10.

I have a lot of stuff going on this week, but I'll try to get to this and test the changes as soon as I can.

**Comment by jimschubert** [comment]
I've looked into this, and it doesn't seem like a simple version update resolved the issue. The newer version of Kotlin DSL is not binary compatible with the version consumed by the gradle-plugin, and it causes failures on `TaskContainerScope`. Naively updating the versions would make 4.10 the minimal supported version of gradle. I'll open a PR with a potential fix for evaluation in a bit.

**Comment by sylvainmoindron** [comment]
if i use "org.openapitools:openapi-generator-gradle-plugin:3.3.0-SNAPSHOT" I will have your change ? how do i have to compile your commit localy ?

**Comment by jimschubert** [comment]
@sylvainmoindron you can compile on this branch by changing to 
modules/openapi-generator-gradle-plugin and installing the artifact

```
./gradlew assemble install
```

To test this, you can use the sample under the modules/openapi-generator-gradle-plugin/samples/local-spec directory. You _might_ need to comment out the sonatype snapshots resolver in that file to pull the local snapshot (at least, I have to do this with Gradle 4.7). To run the samples:

```
gradle -PopenApiGeneratorVersion=3.3.0-SNAPSHOT openApiValidate
```

See the README in that samples/local-spec directory for a list of the samples.

To test in your own project, you should only need the maven local resolver and to change the plugin version to 3.3.0-SNAPSHOT.

**Comment by sylvainmoindron** [comment]
@jimschubert thank for your help (i'm new to gitlab i fumbled a little to find your branch).
Your code compile and install on my PC succefuly.
And my gradle 4.10 project now générate correctly my class from my apenapi.yml file.
(I also tested with gradle 4.9 and it work)

**Comment by fmartinou** [comment]
Hello @jimschubert ,
I've tested your branch on my project with Gradle 4.9 and 4.10 and it works well as expected.
Thank you!

**Comment by wing328** [comment]
Please test with v3.3.0, which has resolved a similar issue reported by another user.

Closing this for the time being. We'll reopen it if it's still an issue.

**Comment by sylvainmoindron** [comment]
i switched to version 3.3.0 with gradle 3.10 and it work fine
