### ISSUE TITLE
[BUG][Protocol Buffer] Large Protocol Buffer Field Numbers

### ISSUE THREAD

**Issue by daniel-vera-g** [OpenAPITools/openapi-generator#9646]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description

I want to use openapi-generator to generate Protocol Buffer definitions.
The files are generated, but the field numbers in the models are very high. F.ex:

```protobuf
message User {

  int64 id = 3355;

  string username = 265713450;

  string firstName = 132835675;
```

##### openapi-generator version

openapitools/openapi-generator-cli:latest 

##### OpenAPI declaration file content or url

I used the [petstore.yaml](https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml) from this reository.

##### Generation Details

```
docker run --rm \
  -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate \
  -i /local/petstore.yaml \
  -g protobuf-schema \
  -o /local/out
```

##### Steps to reproduce

1. Get the Yaml spec above
2. Run the generation command above
3. See the generated Proto Files in `./out`

##### Suggest a fix

I expect to have model field numbers starting from 1 onwards for messages. Taking the output from above, I expect:

```protobuf
message User {

  int64 id = 1;

  string username = 2;

  string firstName = 3;
```

See: https://developers.google.com/protocol-buffers/docs/overview#assigning_field_numbers

**Comment by blackplane** [comment]
You can explicitly define the field numbers by using [Specification Extensions](https://swagger.io/specification/#specification-extensions). For the protobuf generator the relevant extension key is called `x-protobuf-index`.

Example:
```
username:
  type: string
  x-protobuf-index: 2
```
