### ISSUE TITLE
[BUG] [Python][Template] client default headers override explicitly passed headers

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [OpenAPITools/openapi-generator#9648]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

https://github.com/OpenAPITools/openapi-generator/blob/b9e75951e76eea7149333de6420c98e33beb1924/modules/openapi-generator/src/main/resources/python/api_client.mustache#L137-L139

this piece of code ensures that the given parameters for a call always override the rest
i believe it should start with  a copy of the defaults and update with the given parameters

but i'd like to get upstream confirmation

##### openapi-generator version
all i'm aware of (4.x.y, 5.x.y)

##### OpenAPI declaration file content or url
not needed yet

##### Generation Details
not needed yet
##### Steps to reproduce

1. create a client object with some default headers
2. call the api with a override to the headers
3. observe the overrides being replaced with the defaults

##### Related issues/PRs

haven't found any

##### Suggest a fix

based on upstream response i'll either contribute a fix or change the way we call the code in our project

**Comment by spacether** [comment]
@RonnyPfannschmidt our handling of headers can definitely be improved.
Yes, we should definitely start with the default and then override with user provided.
Looking forward to any improvements on this.
