### ISSUE TITLE
[BUG][typescript-axios] Incorrect request body name

### ISSUE THREAD

**Issue by epidemia** [OpenAPITools/openapi-generator#9676]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?

##### Description
Request body name from **x-codegen-request-body-name** is ignored for composed schema.

##### openapi-generator version
5.1.1

##### OpenAPI declaration file content or url
```json
{
  "post": {
    "tags": [
      "entities"
    ],
    "summary": "Creates a new entity",
    "operationId": "createEntity",
    "x-codegen-request-body-name": "body",
    "requestBody": {
      "content": {
        "application/json": {
          "schema": {
            "description": "Input data",
            "oneOf": [
              {
                "$ref": "#/components/schemas/First"
              },
              {
                "$ref": "#/components/schemas/Second"
              },
              {
                "$ref": "#/components/schemas/Third"
              }
            ]
          }
        }
      }
    }
  }
}
```

##### Generation Details

openapi-generator-maven-plugin:5.1.1

Expected request param name: body
Actual request param name: firstSecondThird

##### Steps to reproduce

Use the openapi-generator-maven-plugin and typescript-axios template

**Comment by andreiciceu** [comment]
Hello,

This might be related. When using external $ref on requestBody, e.g.
```yaml
  /contracts/{id}/sign/{tokenId}:
    put:
      tags:
        - Contracts
      description: Update a contract signature as anonymous user
      operationId: updateAsAnonymous
      parameters:
        - name: id
          in: path
          description: ID of the contract to update
          required: true
          schema:
            type: string
            format: uuid
        - name: tokenId
          description: the token ID
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: The signature file for the beneficiary
        required: true
        content:
          application/json:
            schema:
              $ref: './whp-common.yaml#/components/schemas/AdditionalFileDTO'
```

the generated Type name for the body looks like this:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/9255607/131364749-7c5422e0-16b8-4707-b1fa-2bb0d99cbd4b.png">

and does not exist in the generated file
