### ISSUE TITLE
[BUG][KOTLIN] API class has multiple imports of 'okhttp3.ResponseBody'

### ISSUE THREAD

**Issue by p33t** [OpenAPITools/openapi-generator#9682]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] The issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
If a group of paths (grouped by a tag) has multiple "file" type responses then the `import okhttp3.ResponseBody` line is repeated n-times and will not compile.
The bug exists in:  `src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache`

##### openapi-generator version
5.1.1

##### OpenAPI declaration file content or url
[petstore-minimal2.json](https://gist.github.com/p33t/d518225d4b117ff8b94fff4b0fbe30b2)

##### Generation Details
[open-api-generator-conf.json](https://gist.github.com/p33t/9e70fb6d2a3bbbe52375f3f40ac00c12)

##### Steps to reproduce

1. In an empty temporary folder
1. Copy [petstore-minimal2.json](https://gist.github.com/p33t/d518225d4b117ff8b94fff4b0fbe30b2) to the folder
1. Copy [open-api-generator-conf.json](https://gist.github.com/p33t/9e70fb6d2a3bbbe52375f3f40ac00c12) to the folder
1. Generation command: `openapi-generator-cli generate -g kotlin -i petstore-minimal2.json -c open-api-config.json -o petstore-client-proj`
1. `cd petstore-client-proj`
1. `./gradlew --no-daemon assemble`
1. Will not succeed because imports are duplicated in `src\main\kotlin\com\example\bug\apis\DefaultApi.kt`

##### Related issues/PRs

N-A

##### Suggest a fix
An [updated api.mustache](https://gist.github.com/p33t/76690ca6f1e4421d06ea4291c5caba40) worked for me but a more skilled mustache dev might come up with something cleaner as I couldn't get `{{#-first}}` to work in the imports section.

Originally from [jvm-retrofit2/api.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache)

**Comment by p33t** [comment]
#9239 affects this template too.  Fix should not cause regression.

**Comment by AlexTrotsenko** [comment]
Unfortunately I have faced this issue myself.  @wing328  I see, that you have mentioned this issue in your comment for PR in https://github.com/OpenAPITools/openapi-generator/pull/9239/files#r614514630 . 

Do you possibly know if the suggested fix from @p33t should be sufficient? 


@p33t Did you find the way work-around to fix broken compilation because of this duplicated imports?

**Comment by p33t** [comment]
@AlexTrotsenko , yes I found a fix. It's at the bottom of the bug report.
>An [updated api.mustache](https://gist.github.com/p33t/76690ca6f1e4421d06ea4291c5caba40) worked for me but a more skilled mustache dev might come up with something cleaner as I couldn't get {{#-first}} to work in the imports section.
>Originally from [jvm-retrofit2/api.mustache](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/kotlin-client/libraries/jvm-retrofit2/api.mustache)

**Comment by AlexTrotsenko** [comment]
@p33t  thanks for the hint! Can you possibly explain how to use this modified mustache template?
Should I copy-paste this single file and specify via [`templateDir `](https://openapi-generator.tech/docs/templating/#modifying-templates) in gradle or?

Also do I understand correctly, that from time-to-time I need to merge this local change with changes from the master branch, right?
Btw, if it's the case - would you mind sending your changes as PR so that there is no need to re-merge such changes?

**Comment by noemier** [comment]
Hi,
I have the exactly same issue with openapi-generator version 6.4.0.
@AlexTrotsenko Did you found how to use the modified mustache template ?
Thanks for the updates

**Comment by AlexTrotsenko** [comment]
@noemier no unfortunately I have not. As the quick work-around I have added the manual processing of the generated Kotlin file and remove redundant import.

e.g.

````Groovy
tasks.openApiGenerate {
	doLast {
              // do the manual processing of the files in the $buildDir
	}
}
````

**Comment by noemier** [comment]
@AlexTrotsenko Thank you so much for your answer
Yes I hope an expert can solve this problem one day

**Comment by ivanvasheka-intellias** [comment]
Have the same exact problem. Thinking to use gradle task to optimize imports, like it is done in Android Studio... 
Spotless has [RemoveUnusedImports](https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/java/RemoveUnusedImportsStep.java) gradle task. Haven't tried yet, but can be good temporary solution.
