### ISSUE TITLE
[REQ] Migrate to travis-ci.com before June 15

### ISSUE THREAD

**Issue by amakhrov** [OpenAPITools/openapi-generator#9712]
### Is your feature request related to a problem? Please describe.

Looks like openapi-generator repo is currently configured to run on travis-ci.org. Recent CI jobs show this banner:
![Screen Shot 2021-06-07 at 10 49 36 AM](https://user-images.githubusercontent.com/1004015/121065868-15c57180-c77e-11eb-910a-8f0c9901ff41.png)

## Describe the solution you'd like

Apparently, we need to migrate to travis-ci.org to keep CI functioning.

## Additional context

Announcement on Travis blog: https://blog.travis-ci.com/2021-05-07-orgshutdown

(Sorry if it's already being tracked somewhere - I couldn't find it across existing issues or PRs)

**Comment by kuhnroyal** [comment]
FYI @wing328

**Comment by wing328** [comment]
Thanks for the reminder. Should be done.
