### ISSUE TITLE
[BUG] [rust-client] Unable to generate rust client for kubernetes api

### ISSUE THREAD

**Issue by HongjiangHuang** [OpenAPITools/openapi-generator#9732]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
![image](https://user-images.githubusercontent.com/20190812/121363712-c5ab0280-c969-11eb-8d7a-fd9161c80a8e.png)

related: https://github.com/kubernetes-client/gen/pull/192

**Comment by HongjiangHuang** [comment]
The reason is [that](https://raw.githubusercontent.com/HongjiangHuang/kube-rust/master/crates/kubernetes-client/swagger.json)#18874 a recursive structure is created here. And the generator does not handle recursive structures correctly.

references:

https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/rust/model.mustache#L66

https://doc.rust-lang.org/book/ch15-01-box.html#enabling-recursive-types-with-boxes

**Comment by HongjiangHuang** [comment]
After I tried to use the latest version, the problem was solved

**Comment by gotakk** [comment]
Hello is it possible to re-open this issue ?
I'm facing the exact problem
Tested with the last stable and the last 6.0.0 SNAPSHOT openapi-generator jar

Here my yml 
[census.yml.txt](https://github.com/OpenAPITools/openapi-generator/files/7183254/census.yml.txt)
:
