### ISSUE TITLE
BUG [JAVA] Generated java client code from openapi-generator-maven-plugin using okhttp-gson library failing to serialize RequestBody with contentType text/plain

### ISSUE THREAD

**Issue by prkumarm** [OpenAPITools/openapi-generator#9734]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs? 
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

Generated java client code from openapi-generator-maven-plugin using okhttp-gson library failing to serialize RequestBody with contentType text/plain.

When using httpok library(okhttp-gson) openapi-generator throws  ApiException with message "Content type text/plain is not supported" for contentType text/plain.

I see below related mustache template code in serialize(Object obj, String contentType) method in ApiClient.mustache 
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/okhttp-gson/ApiClient.mustache

Is this a expected behavior? if so, what is the work around to serialize RequestBody of type text/plain

##### openapi-generator version
5.1.0

OpenApi generator dependency
       <groupId>org.openapitools</groupId>
       <artifactId>openapi-generator-maven-plugin</artifactId>
       <version>4.3.1</version>

okhttp dependency - 
<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
        </dependency>

##### OpenAPI declaration file content or url
N/A

##### Generation Details
Please refer steps defined below in "Steps to reproduce" section

##### Steps to reproduce
Step1 - Springfox generated contract with contentType text/plain

"/endPoint" : {
      "post" : {
        "tags" : [ "controller" ],
        "summary" : "summary",
        "operationId" : "operationId",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "string"
              }
            },
            "text/plain" : {
              "schema" : {
                "type" : "string"
              }
            }
          }
        }

Step 2: 
Generate client code using below Maven plugin for okhttp-gson library,
       <groupId>org.openapitools</groupId>
       <artifactId>openapi-generator-maven-plugin</artifactId>
       <version>4.3.1</version>

Step3. 
Invoke rest endpoint using generated client code.

Output: Below error message is thrown by the generatened ApiClient class in serialize method.

"Content type text/plain is not supported" for contentType text/plain"

##### Related issues/PRs
NA

##### Suggest a fix
NA

**Comment by fabiohecht** [comment]
Here is a workaround:

```
import java.nio.charset.Charset;
import java.nio.charset.StandardCharsets;
import javax.activation.MimeType;
import javax.activation.MimeTypeParseException;
import okhttp3.RequestBody;

public class MyApiClient extends ApiClient {
    @Override
    public RequestBody serialize(Object obj, String contentType) throws ApiException {

        try {
            MimeType contentMimeType = new MimeType(contentType);

            if ("text/plain".equals(contentMimeType.getBaseType()) && obj instanceof String) {
                obj = ((String) obj).getBytes(getCharset(contentMimeType));
            }

        } catch (MimeTypeParseException e) {
            log.warn("Can't parse mime type: {}", contentType);
        }

        return super.serialize(obj, contentType);
    }

    private Charset getCharset(MimeType contentMimeType) {
        String charsetParameter = contentMimeType.getParameter("charset");
        if (null == charsetParameter) {
            return StandardCharsets.UTF_8;
        }
        return Charset.forName(charsetParameter);
    }
}
```
