### ISSUE TITLE
[CORE] Pragmatically Extending Generators(?)

### ISSUE THREAD

**Issue by dr4ke616** [OpenAPITools/openapi-generator#975]
Hey,

There is a situation where there is a need to pragmatically extend an existing code generator, and provide custom templates and behaviours within a project that has the core `openapi-generator` dependency. 

Initial attempts are as follows:

- Create a class that extends a given generator:

```java
public class KotlinSpringServerCodegenExt implements KotlinSpringServerCodegen {

    @Override
    public void processOpts() {
        super.processOpts();

        // Note the use of `GlobalSupportingFile`, we'll come to this in a second
        supportingFiles.add(new GlobalSupportingFile(
            "some-additional-file.mustache", "", "some-additional-file"));
    }

}
```

- Create an instance of the generator providing some configuration and passing in the classpath to the extended code generator:

```java
final CodegenConfigurator ops =
    new CodegenConfigurator()
        .setLibrary(...)
        .setGroupId(...)
        .setOutputDir(...)
        .setGeneratorName("foo.bar.KotlinSpringServerCodegenExt")
        .toClientOptInput()

DefaultGenerator()
    .opts(opts)
    .generate()
```

### Problem

Notice above; `GlobalSupportingFile` is used instead of `SupportingFile`, because of this condition in the [`DefaultGenerator`](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/java/org/openapitools/codegen/DefaultGenerator.java#L638-L640):

```java
if (support instanceof GlobalSupportingFile) {
    templateFile = config.getCommonTemplateDir() + File.separator + support.templateFile;
}
```

Therefore creating an instance of a `GlobalSupportingFile`, and setting `commonTemplateDir` in the extended `KotlinSpringServerCodegen` class should give the ability to add custom local templates. The problem is however, that `GlobalSupportingFile` has private constructors.

### Solution

Simply by making the constructors in `GlobalSupportingFile` public should fix this. Unless of course this was not the intended use of this class. If this is true, could someone please suggest a solution or possibly point me to a more commonly used approach to pragmatically extend generators?

### openapi-generator version

- `org.openapitools:openapi-generator:3.2.3`

**Comment by jmini** [comment]
Thank you a lot for all the details you put in the question.

May I ask why you need to use a `GlobalSupportingFile`, can't you just use a `SupportingFile` in your generator instead:

```java
    @Override
    public void processOpts() {
        super.processOpts();

        supportingFiles.add(new SupportingFile(
            "some-additional-file.mustache", "", "some-additional-file"));
    }
```

PS: I am like you, trying to understand the goals behind the `GlobalSupportingFile` design...

**Comment by dr4ke616** [comment]
@jmini you are right. I can just use `SupportingFile`. Thanks for your help. I'll close this off.
