### ISSUE TITLE
[BUG] [dart] [docs] which dart generators use which template?

### ISSUE THREAD

**Issue by NANASHI0X74** [OpenAPITools/openapi-generator#9761]
This isn't a bug in the strict sense of the word but something which has confused and frustrated me for a while-
running `openapi-generator-cli list` indicates there are four different dart client generators: 
```
dart
dart-dio
dart-dio-next (experimental)
dart-jaguar
```

When I look into modules/openapi-generator/src/main/resources, I see a different set of four template folder names:
```
dart-dio
dart-jaguar
dart
dart2 
```
Further confusing is that looking at both the dart and dart2 pubspec.mustache templates it's revealed that they both depend on dart >=2.0, which is exactly what I don't expect looking at the folder names.
This causes quite substantial confusion as to which generator corresponds to which template folder... From a cursory glance it looks like the mapping is dart -> dart2 and dart-dio-next -> dart and the other two like the name suggests but I think this should be either cleaned up/ renamed so that all generator names are identical to the template folder names or at least documented somewhere. If there is documentation about this that I've overlooked please point me to it

**Comment by kuhnroyal** [comment]
I hope I can clean this up for you.

`dart-jaguar` and `dart-dio` and their template folders are pretty clear.
`dart-dio` is basically deprecated as it will be replaced by `dart-dio-next` in 6.0.
The `dart` template folder used to contain old Dart 1.x templates, leading to the `dart2` folder being created.
The `dart` generator only supports Dart 2.x and uses the `dart2` template folder.

In an attempt to clean this up, I removed the old Dart 1.x templates from the `dart` folder and added new templates for `dart-dio-next` in there. With the hope of someday having all Dart templates under the `dart` folder.

So `dart-jaguar` and `dart-dio` folders will be removed at some point as both are either deprecated or will be replaced.
And the `dart2` folder should be migrated to the `dart/native` folder.

**Comment by NANASHI0X74** [comment]
ok, that seems to make sense
