### ISSUE TITLE
Java Feign template doesn't work with Feign 10

### ISSUE THREAD

**Issue by ihrankouski** [OpenAPITools/openapi-generator#977]
Hello,

Currently Java Feign template generates code for Feign 9.4.0. 
I'd like the generated client to work with Feign 10.0.1 since I already use that version in my project.
However that not possible currently because of [breaking change in Feign](https://github.com/OpenFeign/feign/releases/tag/10.0.1): 
> #744 [Core] Added HttpMethod to RetryableException

https://github.com/OpenFeign/feign/pull/744/files#diff-64c69768b214213c25fd1246bae90adaR33 - `RetryableException` constructor wants HTTP method now.

Looks like it's only thrown here in this file: https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/Java/libraries/feign/auth/OAuth.mustache#L95

So I had to overwrite original template with my own to generate working code right now.

But is it possible to update the template to support newer Feign out of box?

**Comment by jmini** [comment]
> But is it possible to update the template to support newer Feign out of box?

Yes feel free to file a pull request for that.

Please also update the corresponding dependencies for the generated pom.xml:

https://github.com/OpenAPITools/openapi-generator/blob/3abeb826851aeeb53db5f56accab50ad939c9d7e/modules/openapi-generator/src/main/resources/Java/libraries/feign/pom.mustache#L296-L297

the generated gradle file:

https://github.com/OpenAPITools/openapi-generator/blob/3abeb826851aeeb53db5f56accab50ad939c9d7e/modules/openapi-generator/src/main/resources/Java/libraries/feign/build.gradle.mustache#L126-L127

and the generated sbt file:

https://github.com/OpenAPITools/openapi-generator/blob/3abeb826851aeeb53db5f56accab50ad939c9d7e/modules/openapi-generator/src/main/resources/Java/libraries/feign/build.sbt.mustache#L13-L16

Thank you in advance, do not hesitate to ping us if you need help with something.

**Comment by wing328** [comment]
For this one, I suggest we add an option "feignOption" to allow users setting the Feign version: 9.x, 10.x, with the following mustache tags:
```
{{#isFeign10}} ... {{/isFeign10}}

{{#isFeign9}} ... {{/isFeign9}}
```

Please let me know if you need help on this.
