### ISSUE TITLE
[BUG][Dart] client.post string cant be assigned to uri

### ISSUE THREAD

**Issue by MichalNemec** [OpenAPITools/openapi-generator#9770]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

openapi-generator-cli generate --api-name-suffix xyz -c openapi-config.json -g dart -i http://localhost/swagger/v1/Swagger.json -o apis/xyz --additional-properties="pubName=api_xyz"

via this command im trying to generate c# backend for flutter, we use the backend in ionic, so its not a problem.
Upon generating and installing all packages i get around 1k issues, mainly oneof files missing and errors with argument_type_not_assignable

is there an option to disable oneof or allof?

then i can actually use it before this get fixed permanently

##### openapi-generator version
5.1.1

##### Generation Details

openapi-config.json
{
    "taggedUnions": false,
    "supportsES6": false,
    "providedInRoot": true,
    "ensureUniqueParams": false,
    "modelSuffix": "",
    "fileNaming": "kebab-case"
}

**Comment by kuhnroyal** [comment]
OneOf/AllOf/AnyOf is not supported atm, if your schema relies heavily on this, then you are out of luck.

**Comment by MichalNemec** [comment]
Damn, we are relying on this heavily. Is there some roadmap for dart when this could be implemented?
Otherwise is flutter useless for us.

**Comment by kuhnroyal** [comment]
Not from my end, I mostly work on the dart-dio generator but there is also no support there yet. This is a fairly complex problem to tackle.
You are free to provide a PR, I can help somewhat when you have a basis.

**Comment by alevinetx** [comment]
I'm having the same issue as in the subject, due to `http` introducing a breaking change in 0.13.0+:

```
Breaking All APIs which previously allowed a String or Uri to be passed now require a Uri.
```

and `api_client.dart` is generating using `String` in `Future<Response> invokeAPI`

```dart
Future<Response> invokeAPI(
...
final url = '$basePath$path$queryString';`
...
    switch(method) {
        case 'POST': return await _client.post(url, headers: nullableHeaderParams, body: msgBody,);
        case 'PUT': return await _client.put(url, headers: nullableHeaderParams, body: msgBody,);
...
```

I see the question in the OP changed to inquire about `OneOf/AllOf`, so did you find a way to resolve the `String` vs `Uri` issue?

Thank you!

**Comment by MichalNemec** [comment]
@alevinetx Good find! what i did was basically fix this uri and removed all oneof allof import missing files, so flutter does not yell at me that the project has  problems. otherwise im not skilled to make this fix/pr. I really dont understand how openapi works and generates stuff, it would take me ages to fix it.

**Comment by kuhnroyal** [comment]
This should be fixed on master, give it a try.

**Comment by alevinetx** [comment]
My first instinct would be to edit:
https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/dart2/api_client.mustache

and in lines 128-133 do an inline `Uri(url)` for the first parameter

or, add
```dart
      Uri url2 = Uri.dataFromString(url);
```
before the switch on 127 and then changing all the calls to use `url2` instead of `url`

**Comment by alevinetx** [comment]
@kuhnroyal : I cloned from master.  Now not sure if I'm supposed to use new.sh / mvn install / mvnw / help?

**Comment by kuhnroyal** [comment]
You can use https://hub.docker.com/r/openapitools/openapi-generator-cli or mvn install if you want to make changes.

**Comment by kuhnroyal** [comment]
@MichalNemec Is this solved for you?

**Comment by kuhnroyal** [comment]
Feel free to open a new ticket if you have something actionable.
