### ISSUE TITLE
[BUG][python] nullable list simple model is turned non-nullable in code

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [OpenAPITools/openapi-generator#9781]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description
when generating python models for nullable arrays, the resulting code is non-nullable

##### openapi-generator version

5.x

##### OpenAPI declaration file content + generation steps + output

https://gist.github.com/RonnyPfannschmidt/8e174ec5f5812ff718a60605152d7334

##### Suggest a fix

correctly passing over nullable to those models

at first glance it seems like a the java side handles the openapi type correct (none + str) but returns nullable=false to the template,
in turn triggering the confused code (see example model)

**Comment by spacether** [comment]
This was fixed in the python generator in v6.2.0 and onward
One can see an example of a [nullable list here](https://github.com/OpenAPITools/openapi-generator/blob/master/samples/openapi3/client/petstore/python/petstore_api/model/nullable_class.py#L176)
