### ISSUE TITLE
[SWIFT4] CodableHelper's encode() does not use dateFormatter property

### ISSUE THREAD

**Issue by manhhavu** [OpenAPITools/openapi-generator#982]
##### Description

The current Swift4's [CodeableHelper](https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/swift4/CodableHelper.mustache)'s **encode()** method does not into account the class' property dateFormatter. The consequence is that we are unable to customize the encoding format for date. 

##### openapi-generator version

3.2.3

##### Suggest a fix/enhancement

Take into account the property dateFormatter, which is already the case for **decode()** method. For example: 

```swift
if let df = self.dateformatter {
    encoder.dateEncodingStrategy = .formatted(df)
} else {
    encoder.dataEncodingStrategy = .base64
    let formatter = DateFormatter()
    formatter.calendar = Calendar(identifier: .iso8601)
    formatter.locale = Locale(identifier: "en_US_POSIX")
    formatter.timeZone = TimeZone(secondsFromGMT: 0)
    formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSXXXXX"
    encoder.dateEncodingStrategy = .formatted(formatter)
}
```

I'm happy to create a PR if you'd like 😁

**Comment by wing328** [comment]
@manhhavu please submit a PR so that we can review the fix more easily.

**Comment by manhhavu** [comment]
@wing328 : I've created the PR #984
