### ISSUE TITLE
[REQ][PowerShell] Improve generated PowerShell examples

### ISSUE THREAD

**Issue by SimeonGerginov** [OpenAPITools/openapi-generator#9826]
### Is your feature request related to a problem? Please describe.

Currently **`PowerShell`** examples can be used in the **`mustache templates`** through the **`x-powershell-example`** vendor extension. This is very useful for generating and showing an example for a specific cmdlet. However there're a few issues with the current approach:

1. Currently **`Models`** are nested inside the generated example which could result in the following code:
```powershell
Invoke-Api -Model1 (Initialize-Model1 -Model2 (Initialize-Model2 -Model3 (Initialize-Model3)))
```
2. Enums are generated through **`Initialize-*`** cmdlets.
3. Maps which in **`PowerShell`** are hashtables are not covered in the examples.
4. Currently all parameters are generated in the examples regardless if they're required or optional. For larger specs, this results in a very long and hard to read example.

## Describe the solution you'd like

I would suggest refactoring the example code and addressing the issues listed above: **`Model`** initialization can occur before the **`Invoke-*`** call which would result in a more readable example. Also adding support for Enums and Maps will definetely improve the example. And lastly, adding an additional vendor extension like  **`x-powershell-example-required`** could only generate examples with required parameters. This way the consumer can choose in the templates on whether to receive the full example or the minimal one that is needed to invoke an **`API Operation`**.

## Additional context

I'd be happy to contribute the improved example structure for **`PowerShell`**.

**Comment by wing328** [comment]
@SimeonGerginov thanks for the suggestion, which looks reasonable to me. 

Please submit PRs to implement these suggestions one by one and let us know if you need any help.
