### ISSUE TITLE
[Question] How to add attribute for webclient?

### ISSUE THREAD

**Issue by uhushcha** [OpenAPITools/openapi-generator#9833]
In case when i generate client with library weblicent generator name java.

How i can add attribute with auth client registration id.

>      Mono<String> response = webClient.get()
>             .uri(WIREMOCK_PATH + "/test")
 >               .attributes(clientRegistrationId(NAME_AUTH_PROFILE))
 >               .retrieve()
 >               .bodyToMono(String.class);

How it possible to do with openapi-generator-maven-plugin.

**Comment by stojsavljevic** [comment]
Lack of ability to set custom client registration id becomes a big limitation in the case when api needs to be called with different Spring Security oauth clients. As generated code doesn't set attribute like in the example above, only the default client will be used to invoke api.

**Comment by z0rb** [comment]
Was this solved? Is there documentation how to do it?

**Comment by uhushcha** [comment]
@domids No, I generate different web client from builder on Configuration level with different default client
