### ISSUE TITLE
[BUG] GenerateTask' property 'input' annotated with @Internal should not be also annotated with @Input.

### ISSUE THREAD

**Issue by liuzqt** [OpenAPITools/openapi-generator#9835]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [ ] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [ ] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I init a gradle project and follow the tutorial here https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin and try to generate server stub code.
run `./gradlew openApiGenerate` got this error:

```
> Task :app:openApiGenerate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':app:openApiGenerate' (type 'GenerateTask').
  - Type 'org.openapitools.generator.gradle.plugin.tasks.GenerateTask' property 'input' annotated with @Internal should not be also annotated with @Input.
    
    Reason: A property is ignored but also has input annotations.
    
    Possible solutions:
      1. Remove the input annotations.
      2. Remove the @Internal annotation.
    
    Please refer to https://docs.gradle.org/7.0.2/userguide/validation_problems.html#ignored_property_must_not_be_annotated for more details about this problem.
```

##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url

The repo to reproduce this error : https://github.com/liuzqt/openapi-gradle

##### Generation Details

gradle version: 7.0.2

##### Steps to reproduce

clone repo https://github.com/liuzqt/openapi-gradle and run 
```
./gradlew openApiGenerate
```

**Comment by toby-murray-snow-software** [comment]
Is this a duplicate of #9253?

**Comment by liuzqt** [comment]
@toby-murray-snow-software yeah the same issue, sorry I was mixing 5.1.1 and 5.1.0, after I upgrade all to 5.1.1 the issue was gone. Will mark this as resolved.
