### ISSUE TITLE
[REQ] [Kotlin] Use kotlin.Set for an array with uniqueItems set to true

### ISSUE THREAD

**Issue by marcdejonge** [OpenAPITools/openapi-generator#9848]
When defining an array with uniqueItems set to true, I expect that the type is a `Set`. But right now it's always a `List`.

## Describe the solution you'd like

Add support for the `Set` type.

## Describe alternatives you've considered

Right now I'm using I'm using custom templates to generate this. I think this would be useful to be part of the default templates.

**Comment by wing328** [comment]
Please submit a PR to start with. Let me know if you need help with the PR.

**Comment by marcdejonge** [comment]
Yes, I'm working on a PR, just need a bit of time to find my way around the code :)
