### ISSUE TITLE
[dart][dart-dio][dart-dio-next] Add support for classes that extend EnumClass to encodeCollectionQueryParameter

### ISSUE THREAD

**Issue by tfbsza** [OpenAPITools/openapi-generator#9854]
### Is your feature request related to a problem? Please describe.

Recent additions to the dart-dio and dart-dio-next generators (https://github.com/OpenAPITools/openapi-generator/commit/fdbf02764d144ff1469ce3905dff5b19352b6447) fixed encoding query parameters correctly. It doesn't seem to support classes that extend EnumClass though.

## Describe the solution you'd like

Please add support for classes that extend EnumClass.

## Describe alternatives you've considered

As a temporary fix, I manually changed line 64 of generated file api_util.dart which fixed the issue in the meantime:

Changed from:
`ListParam<T> encodeCollectionQueryParameter<T>`

Changed To:
`ListParam<String> encodeCollectionQueryParameter<T>`

**Comment by tfbsza** [comment]
@kuhnroyal

**Comment by kuhnroyal** [comment]
Thanks for creating the issue.
Can you please provide me with a minimal spec that generates enum parameters.

**Comment by kuhnroyal** [comment]
I tested the serialization and it seems to work. One problem might be that a correct `TypeFactory` for the enum may be missing from the built_value `serializers`.
Also not sure why your suggested fix has any effect.
