### ISSUE TITLE
[REQ] [JAVA] Apache httpcomponents client library

### ISSUE THREAD

**Issue by harrywhite4** [OpenAPITools/openapi-generator#9866]
### Is your feature request related to a problem? Please describe.

Support generating a java client using the apache [httpcomponents client][lib]

## Describe the solution you'd like

A new library option for the java client

## Describe alternatives you've considered

N/A

## Additional context

I am working in a project that already makes use of httpcomponents so we were interested in generating a client using that library. Have already started some work looking into this, just wanted to open an issue see if this is something that could be contributed here.

[lib]: https://hc.apache.org/httpcomponents-client-4.5.x/index.html

**Comment by wing328** [comment]
Yup, we welcome contributions to add `httpcomponents` library option to the existing Java client.

**Comment by harrywhite4** [comment]
This was merged in #10218
