### ISSUE TITLE
[BUG][Erlang] Faulty regexp 

### ISSUE THREAD

**Issue by lixen-wg2** [OpenAPITools/openapi-generator#9869]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue?
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

regex match on pattern doesnt work

```
re:run("imsi-123456789", proplists:get_value(pattern, maps:get(rules, openapi_api:request_param_info('GetSupiOrGpsi', 'ueId')))).
nomatch
```

expected behavior without "/" 
```
1> re:run("imsi-123456789", proplists:get_value(pattern, maps:get(rules, openapi_api:request_param_info('GetSupiOrGpsi', 'ueId')))).
{match,[{0,14},{0,14}]}
```

##### openapi-generator version

5.2.0-SNAPSHOT

##### OpenAPI declaration file content or url

openapi-generator-cli generate -i https://www.3gpp.org/ftp/Specs/archive/OpenAPI/Rel-16/TS29503_Nudm_SDM.yaml  -g erlang-server

##### Steps to reproduce

`openapi-generator-cli generate -i https://www.3gpp.org/ftp/Specs/archive/OpenAPI/Rel-16/TS29503_Nudm_SDM.yaml  -g erlang-server`

##### Suggest a fix

```
request_param_info('GetSmfSelData', 'supi') ->
    #{
        source =>  binding ,
        rules => [
            {type, 'binary'},
            {pattern, "/^(imsi-[0-9]{5,15}|nai-.+|.+)$/" },
            required
        ]
    };
```

should instead be

```
request_param_info('GetSmfSelData', 'supi') ->
    #{
        source =>  binding ,
        rules => [
            {type, 'binary'},
            {pattern, "^(imsi-[0-9]{5,15}|nai-.+|.+)$" },
            required
        ]
    };
```

**Comment by wing328** [comment]
@lixen-wg2 thanks for reporting the issue. I've filed #9892 to fix it

**Comment by lixen-wg2** [comment]
@wing328 great, thanks!

**Comment by wing328** [comment]
The fix has been merged into the master. Can you please give it another try with the latest master? You can find the JAR snapshot versions in the project's README.
