### ISSUE TITLE
CLI option to control logging level

### ISSUE THREAD

**Issue by skydoctor** [OpenAPITools/openapi-generator#989]
##### Description

There doesn't seem to be a way to control the verbosity of the output logs printed by the generator-cli, even though each line has a level defined. There should be a way to limit the output logs to errors or warnings only as desired.

##### openapi-generator version

3.1.2

##### OpenAPI declaration file content or url

N/A

##### Command line used for generation

java -jar /usr/share/java/openapi-generator-cli-3.1.2.jar generate -t cpprest -g cpp-restsdk

##### Steps to reproduce

Run any CLI command to generate code from yaml/json

**Comment by ackintosh** [comment]
Thanks for reporting this issue. I'll file a PR later.

**Comment by ackintosh** [comment]
@skydoctor 
The enhancement will be released on Oct 1st (v3.3.0). Thanks for reporting this issue!

**Comment by kimamula** [comment]
Is this available with the docker image?
I tried the following command which does not work.

```sh
$ docker run --rm -v ${PWD}:/local -e JAVA_OPTS="-Dlog.level=error" \
openapitools/openapi-generator-cli:v3.3.2 generate \
-i /local/openapi.yaml \
-g typescript-angular \
-o /local/out \
-c /local/openapitools/config.json
```

**Comment by ackintosh** [comment]
hmm...

As @kimamula said, the option does not work on the docker image. 👀 

On the other hand, it works on the image which is built locally. 🤔 

```bash
$ cd openapi-generator
$ docker build -t openapi-generator-test .
...
$ docker run --rm -v (PWD):/local -e JAVA_OPTS="-Dlog.level=warn" \
      openapi-generator-test generate \
      ...
```

**Comment by kimamula** [comment]
I have created [a new issue](https://github.com/OpenAPITools/openapi-generator/issues/1410) for this problem.
I am guessing that this is because https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-cli/Dockerfile is not using `JAVA_OPTS` environment variable.
