### ISSUE TITLE
Inline Models get typed as `Object`

### ISSUE THREAD

**Issue by eriktim** [OpenAPITools/openapi-generator#99]
##### Description

When I generate code using the attached yaml file I still run into the issue from #79. The difference seems to be my `Pet`'s `name` object is inline.

##### openapi-generator version

`3.0.0-SNAPSHOT` (current master)

##### OpenAPI declaration file content or url

```yaml
swagger: '2.0'

info:
  version: '1.0.0'
  title: Test
  description: test

paths:
  /pet:
    get:
      operationId: search
      produces:
        - 'application/json'
      parameters: []
      responses:
        200:
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'

definitions:
  Pet:
    type: object
    properties:
      name:
        type: object
        properties:
          firstName:
            type: string
          lastName:
            type: string
      favoriteFood:
        type: string
```

##### Command line used for generation

```
$ mvn clean install
$ java -jar target/openapi-generator-cli.jar generate -i openapi.yaml -l typescript-angular -o /tmp/generated
$ cat generated/model/pet.ts 
/**
 * Test
 * test
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Pet { 
    name?: any;
    favoriteFood?: string;
}
```

##### Steps to reproduce

* Save the file
* Run the commands

cc: @jimschubert @jmini

**Comment by jmini** [comment]
Thank you for this report.

I think this is broken at a lot of places (not just Kotlin). The behavior is often not the same for inline and for not inline stuff (an other example that goes in a similar direction is #8, there new OAS3 concepts are used).

Does swagger-codegen version `2.3.1` does a better job on this use case? I would like to know if this is a regression or not.

For me part that computes which types should be generated should be reworked... But this is not an easy task.

**Comment by jmini** [comment]
An other example of things that goes wrong with inlined schema: #108

**Comment by trenneman** [comment]
I found the issue to be present with at least `typescript-angular`, `spring`, `kotlin` and `elm`. I just checked the same YAML file with both v2.3.1 and the master of Swagger Codegen and in both cases it seems to work fine.

**Comment by jmini** [comment]
There was some work made with #736 for version `3.2.2-SNAPSHOT` can you give this version a try?
