### ISSUE TITLE
[BUG] [kotlin-spring] Kotlin generator server stubs may not compile with reactive option on

### ISSUE THREAD

**Issue by ffffionn** [OpenAPITools/openapi-generator#9902]
##### Description

Using the maven plugin with the reactive option and the delegate pattern enabled, one of the endpoints defined in the OpenApiSpec doc requiring an input of Array<Int> doesn't compile.

The delegate class function has an input of `kotlin.collections.List<kotlin.Long>` whereas the V1Api controller class is passing through a `Flow<kotlin.Long>`

##### openapi-generator version

5.1.1

##### OpenAPI declaration file content or url

https://gist.github.com/ffffionn/bd8c8cd9fbd2edce348e3029928f621d

##### Command line used for generation

Maven plugin

##### Steps to reproduce

Generate the files and compile.

**Comment by ffffionn** [comment]
V1ApiDelegate here should have an input of `Flow<kotlin.Long>`

**Comment by ffffionn** [comment]
I've tried workarounds such as using typeMappings of array=Flow, but then I get types such as Flow<Flow<Long>>  which is wrong also..

**Comment by ffffionn** [comment]
workaround for now is to set delegatePattern to false and use interfaceOnly and extend that

**Comment by giveadamakick** [comment]
I've identified the problem and created a PR to fix: https://github.com/OpenAPITools/openapi-generator/pull/11695
