### ISSUE TITLE
[BUG][dart-dio] wrong value sent for integer enums in query parameters 

### ISSUE THREAD

**Issue by bmxbandita** [OpenAPITools/openapi-generator#9905]
#### Bug Report Checklist

- [x] Have you provided a full/minimal spec to reproduce the issue? [https://gist.github.com/bmxbandita/5c162d525a82c769e3329d09d23d40ff](https://gist.github.com/bmxbandita/5c162d525a82c769e3329d09d23d40ff)
- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))? valid
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists? yes, and still exists
- [x] Have you searched for related issues/PRs?
- [ ] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

My spec has an integer type enum schema, and the generator generates an enumClass, with the following:
`@BuiltValueEnumConst(wireName: r'36')
static const Country n36 = _$n36;`

If there is an endpoint with this integer enum model as query parameter, it will send 'n36', not '36' what the server would accept.
It seems that the serialization is completely ignored for Enum query parameters, and the literal field name is sent.

##### openapi-generator version

5.1.1 and latest master branch 

##### OpenAPI declaration file content or url

[https://gist.github.com/bmxbandita/5c162d525a82c769e3329d09d23d40ff](https://gist.github.com/bmxbandita/5c162d525a82c769e3329d09d23d40ff)

##### Generation Details

java  -jar openapi-generator-cli.jar generate -i spec_sample.yml --additional-properties generateAliasAsModel=true,nullableFields=true -g dart-dio-next
 
I tried with dart-dio and dart dio-next generators as well, all the same results.

##### Steps to reproduce

Generate a dart-dio or dart-dio-next client with the provided spec. 
Call the '/user/invoice_address' endpoint that has an integer type enum as query parameter like so:
`getUserAccountApi().invoiceAddressUserInvoiceAddressPut(country: Country.n36, currency: Currency.HUF);`
 The 'currency' param has the correct value 'HUF', but the 'country' param has the wrong 'n36' value, instead of the correct '36'.

##### Suggest a fix

Serialize EnumClasses for query parameters as well.

cc: @kuhnroyal

**Comment by kuhnroyal** [comment]
Probably related https://github.com/OpenAPITools/openapi-generator/issues/9854
Support for enums in parameters does not exist yet. I will try to implement this asap.

Thanks for the spec, that will help.

**Comment by kuhnroyal** [comment]
Can you make that spec available again?

**Comment by bmxbandita** [comment]
> Can you make that spec available again?

I made it public:
https://gist.github.com/bmxbandita/5c162d525a82c769e3329d09d23d40ff

**Comment by kuhnroyal** [comment]
Generating this spec does not generate the `Country` or `Currency` model for me. Not with any generator, Java, Go, whatever. Did you change the spec?

**Comment by bmxbandita** [comment]
I didnt change the spec, i used the same when tested with a dart client and python server.

**Comment by kuhnroyal** [comment]
Well I don't get the `Country` and `Currency` enums generated at all so I can't test how they get serialized :/

**Comment by bmxbandita** [comment]
Ohh, i think i know whats the problem, did you use the --additional-properties generateAliasAsModel=true  property for the generator?

**Comment by kuhnroyal** [comment]
No, will give that a try.

**Comment by kuhnroyal** [comment]
`generateAliasAsModel` was the key to generating the spec. `County` is an integer enum but it gets generated with `wireName`. This happens because `additionalProperties` is declared which effectively makes this a map object, and then the correct wire type can not be detected. `additionalProperties` usage is also why `generateAliasAsModel` is needed in the first place.

Removing `additionalProperties` generates:
```dart
  @BuiltValueEnumConst(wireNumber: 36)
  static const Country number36 = _$number36;
````

Nevertheless, I was not able to find anything that should cause `n36` to be serialized even with `additionalProperties` in place.
