### ISSUE TITLE
[Kotlin-Client] Support for cookie-based security schemas in Kotlin clients

### ISSUE THREAD

**Issue by puneetugru** [OpenAPITools/openapi-generator#9915]
##### Description

While trying to generate Kotlin Client code for cookie-based security schema with OpenAPI Spec version 3.0.0, the below lines were seen in the ApiClient.kt file.

``` kotlin
constructor(
        baseUrl: String = defaultBasePath,
        okHttpClientBuilder: OkHttpClient.Builder? = null,
        serializerBuilder: GsonBuilder = Serializer.gsonBuilder,
        authNames: Array<String>
    ) : this(baseUrl, okHttpClientBuilder, serializerBuilder) {
        authNames.forEach { authName ->
            val auth = when (authName) {
                "cookieAuth" -> ApiKeyAuth("cookie", "sess")
                else -> throw RuntimeException("auth name $authName not found in available auth names")
            }
            addAuthorization(authName, auth);
        }
    }
```
**But, the file _ApiKeyAuth.kt_ was not found in the generated code.**

##### openapi-generator version

``` terminal
openapi-generator version
5.1.1
```

##### OpenAPI declaration file content or URL

https://gist.github.com/puneetugru/ec65183b4ad2da3ee8a7b43def2eea4a

##### Command line used for generation

``` terminal
openapi-generator generate -i TestCookieAuthInAPI.yaml -g kotlin -c config_android.json
```

##### Steps to reproduce

1. Create a config file like below to put the Kotlin client code in a required directory and use some required libraries.

``` json
{
    "packageName": "com.test",
    "serializationLibrary": "gson",
    "sourceFolder": "src/main/java",
    "library": "jvm-retrofit2"
}

```

2. Run the command, **openapi-generator generate -i TestCookieAuthInAPI.yaml -g kotlin -c config_android.json**

##### Related issues/PRs

None

##### Suggest a fix/enhancement

Is there support for cookie-based security schemas in Kotlin clients?

The generated code is as below,

[KOTLIN_TEST_ISSUE_9915.zip](https://github.com/OpenAPITools/openapi-generator/files/6783733/KOTLIN_TEST_ISSUE_9915.zip)

**Comment by flipch** [comment]
Why was this closed? How did you fix this?
