### ISSUE TITLE
HTML2 generator outputs "undefined" DTOs

### ISSUE THREAD

**Issue by antonio-petricca** [OpenAPITools/openapi-generator#9923]
Hi, I am using Open API generator plugin 5.1.1.

I instrumented my projects to generate HTML2 documentation. 

It works fine for all of them but one which, for the response DTOs, prints an **undefined** statement as for the attached snapshot:

![image](https://user-images.githubusercontent.com/6660386/125090393-9229d800-e0cf-11eb-9bff-a42465c4e8cd.png)

I opened the browser debug console and I found the following error:

```
SyntaxError: Error resolving $ref pointer "http://localhost:7001/my-api/help#/components/schemas/NickNameTypeDTO". 
Token "components" does not exist.
    at Function.syntax (help:8110)
    at Pointer.resolve (help:7898)
    at $Ref.resolve (help:7901)
    at $Refs._resolve (help:7904)
    at dereference$Ref (help:7856)
    at help:7856
    at Array.forEach (<anonymous>)
    at crawl (help:7856)
    at help:7856
    at Array.forEach (<anonymous>)
```

How can I further investigate on the causes of that issue?

Thank you so much!

**Comment by fspreck-indiscale** [comment]
Same her with openapi-generator-cli 5.2.0.  The problem seem to be $refs inside of refs, e.g.,

```yaml
# ...
      responses:
        '200':
          description: Some description
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Response"
# ...
components:
  schemas:
    Response:
      type: object
      description: Server response
      properties:
        UserInfo:
          $ref: `"#/components/schemas/UserInfo"`
    UserInfo:
      type: object
      description: Information about the user that submitted the request
      properties:
        username:
          $ref: "#/components/schemas/username"
    username:
      type: string
      example: admin
      xml:
        attribute: true
```

`Response` which contains a `UserInfo` will be rendered but the value of `UserInfo` will be undefined and `username` will not be shown at all.

**Comment by K-Menki** [comment]
I have the same problem when I use openapi-generator-maven-plugin V 5.4.0 .
