### ISSUE TITLE
[BUG][Java] Reference to Consumer is ambiguous

### ISSUE THREAD

**Issue by Tomboyo** [OpenAPITools/openapi-generator#9928]
#### Bug Report Checklist

- [x] Have you validated the input using an OpenAPI validator ([example](https://apidevtools.org/swagger-parser/online/))?
- [x] Have you [tested with the latest master](https://github.com/OpenAPITools/openapi-generator/wiki/FAQ#how-to-test-with-the-latest-master-of-openapi-generator) to confirm the issue still exists?
- [x] Have you searched for related issues/PRs?
- [x] What's the actual output vs expected output?
- [ ] [Optional] Sponsorship to speed up the bug fix or feature request ([example](https://github.com/OpenAPITools/openapi-generator/issues/6178))

##### Description

I generated a client for a specification with a component called `Consumer`. The generator produced a client with import statements for both `java.util.function.Consumer` and a `...model.Consumer`. As a result, the code cannot compile because the `reference to Consumer is ambiguous` wherever the `Consumer` type is referenced:

```java
// in file org/openapitools/client/api/DefaultApi.java

import org.openapitools.client.model.Consumer;
import java.util.function.Consumer; 
```

##### openapi-generator version

My project uses the latest release of the OpenAPI generator maven plugin:
```
<groupId>org.openapitools</groupId>
<artifactId>openapi-generator-maven-plugin</artifactId>
<version>5.2.0</version>
```

##### OpenAPI declaration file content or url

Found in the [example project here](https://github.com/Tomboyo/openapigen-bug-exmaple/blob/main/openapi.yml)

##### Generation Details

The client is generated using the maven plugin. See the [pom.xml](https://github.com/Tomboyo/openapigen-bug-exmaple/blob/main/pom.xml)

##### Steps to reproduce

```
git clone git@github.com:Tomboyo/openapigen-bug-exmaple.git
cd openapigen-bug-exmaple
./mvnw clean compile
```

##### Related issues/PRs

I could not find any.

##### Suggest a fix

One approach is to use fully-qualified names for all types that otherwise rely on generated import statements. For each generated method, we would qualify the return type and parameter types. (Or, similarly, we could fully-qualify only the types used in the verbatim template.)

**Comment by borsch** [comment]
@Tomboyo there are few workarounds
1. Rename component name in yours yaml specification
2. In case you don't want to change name, then you can simply customize maven plugin with option `modelNameSuffix` (check this [doc](https://github.com/OpenAPITools/openapi-generator/tree/ab688d4c3a1d558a1c6f6b9116caf3cd0798ef0c/modules/openapi-generator-maven-plugin#general-configuration-parameters)). Yo can add something like `<modelNameSuffix>Dto</modelNameSuffix>`. In this case component name in yaml will remain the same but in you code you will get model called `ConsumerDto`

**Comment by baurchanu** [comment]
Created a PR for avoiding the problem with an enabled config option 'fullJavaUtil'
