### ISSUE TITLE
[REQ] Allow option for "stream" keyword when generating protocol buffer (.proto) files.

### ISSUE THREAD

**Issue by runxuanjiang** [OpenAPITools/openapi-generator#9941]
### Is your feature request related to a problem? Please describe.

I am trying to generate protocol buffers from an OpenAPI yaml file. However, the service I am describing returns data back to the client through a stream. This can be expressed in a protocol buffer by using the "stream" keyword when describing the service, such as in the third example code snippet in the [GRPC tutorial](https://grpc.io/docs/what-is-grpc/core-concepts/) :

```
rpc LotsOfReplies(HelloRequest) returns (stream HelloResponse);
```

It is not clear to me where to specify this "stream" keyword in the OpenAPI yaml file such that the generated protocol buffer's service response will include the "stream" keyword, or if this is even supported at all.

## Describe the solution you'd like

Perhaps some option or flag to include in the OpenAPI yaml to specify whether the response or request is a stream. Or maybe some option to include any generic prefix to a request or response data type.

## Describe alternatives you've considered

Of course, I can simply manually add in the "stream" keyword using a bash script, but this can get tedious for larger projects and when trying to deploy a project automatically.

**Comment by wing328** [comment]
what about adding `x-grpc-response: stream` in the spec file to override the response type?

**Comment by runxuanjiang** [comment]
I actually tried adding `x-grpc-response: stream` in several places in the OpenAPI .yaml file but everything I tried seemed to have no effect (I have tried adding it under the HTTP status code, under "content", and under "schema"). 
```
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestResponse'
```

Would you mind giving me an example spec file or code snippet where `x-grpc-response` is being overridden?

Thank you!

**Comment by runxuanjiang** [comment]
Update: I was able to get it to work with the following by putting `x-grpc-response: stream string` under the `get` label, as follows:

```
openapi: 3.0.0
info:
  title: test
  description: API for testing adding stream keyword in generated protocol buffer file
  version: 0.1.9
paths:
  /users:
    get:
      summary: test
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':    # status code
          description: test
          content:
            application/json:
              schema:
                type: string
      x-grpc-response: stream string
```

Also for some reason this only works if the response type is not set to `object` or isn't a reference to another type.

**Comment by morvencao** [comment]
Encountered a similar issue, looks like the `x-grpc-response` still can't support object or reference.
