### ISSUE TITLE
Unable to generate Retrofit 2 code using openapi-generator kotlin 

### ISSUE THREAD

**Issue by anus-ali** [OpenAPITools/openapi-generator#9949]
I am using this command 
java -jar openapi-generator-cli.jar generate -i path/api.yaml -g kotlin -o kotlin-test/ -c config.yaml

This my config.yaml 
additionalProperties:
  artifactId: kotlin-client
  serializableModel: "true"
  library: jvm-retrofit2
  useCoroutines: "true"
  
  Can somebody help me why it is still using okhttp3 in APIClient.kt

**Comment by anus-ali** [comment]
I was able to find the solution in other reported issues. Closing this issue.

**Comment by AleksandarAleksandrov** [comment]
@anus-ali can you please share what the fix was. I'm having the same issue.

**Comment by sampengilly** [comment]
Could you link the issue you found with the solution? I'm struggling to spot it
