### ISSUE TITLE
[C#] Support Asp.net core 2.1

### ISSUE THREAD

**Issue by SeanFarrow** [OpenAPITools/openapi-generator#999]
It would be nice if the generator supported Asp.Net Core 2.1.

I'm happy to do the work for this, but have a few questions:

Firstly, is there a way to completely exclude files from the output if they are not needed. The case where SwashBuckle is not included is the example I'm thinking of, so we should probably exclude wwroot.
 Secondly, how does the generator indicate that authorization is needed on an endpoint to the code that generates files from the templates. I'm assuming the starting point of an API with no authorization specified.
 Thanks for any help.
 Sean.

**Comment by wing328** [comment]
@SeanFarrow thanks for offering help to improve this project.

To exclude files, have you considered using .openapi-generator-ignore files to prevent files from being overwritten/generated?

> I'm assuming the starting point of an API with no authorization specified.

Whether authorization is required depends on the OpenAPI specification. We can consider authorization as a day 2 requirement.

Have you tried the `aspnetcore` generator? Does the output meet your requirement?

We can add an option to support ASP.Net Core 2.1 if 2.1 does not introduce a lot of changes.

**Comment by wing328** [comment]
@SeanFarrow thanks for the details. Sounds like we should support 2.1 directly and drop the support for 2.0.

@jimschubert @mandrean do you have an option on this topic?

**Comment by SeanFarrow** [comment]
@wing328,
As well as everything I’ve previously mentioned, 2.1 provides the capability to support open api through attributes directly.
Perhaps we should allow a user to specify a version when generating the code?
Is this something that would be feasible?

**Comment by wing328** [comment]
> Perhaps we should allow a user to specify a version when generating the code?

Yup, that's usually what we do.

We can add an option "aspNetCoreVersion" to support future version (e.g. 2.2, 2.3, etc).

**Comment by wing328** [comment]
@SeanFarrow as a starting point, what about updating the templates in https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/aspnetcore to make it work with ASP.net core 2.1 ?

**Comment by SeanFarrow** [comment]
@wing328,
Yes, I'll do that. Do you want me to just update the template and then look at other things later, like the fact that if UseSwashbuckle is not specified, we don't need to generate some of the filters, so they shouldn't be present in the final output in my view.

**Comment by wing328** [comment]
>  then look at other things later, like the fact that if UseSwashbuckle is not specified

Yup, we can deal with those later as it should not be difficult to skip with a CLI option.

**Comment by SeanFarrow** [comment]
Ok,I’ll work on that today/tomorrow.
Does the C# generator support authorization, or is that something we need to add later?
Finally, is there a sample spec I can use to generate code to check the template is working as expected?

**Comment by wing328** [comment]
Seems like there's no authorization support at the moment as I couldn't find the mustache tag `authMethods` in  https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/aspnetcore

**Comment by SeanFarrow** [comment]
Ok,that’s whatI thought, but just wanted to check.

**Comment by wing328** [comment]
@SeanFarrow we can work with you to add the authorization support later (which should be pretty straightforward)

**Comment by SeanFarrow** [comment]
@wing328,
Do we want to upgrade swashbuckle, the current version is 3.0.0 and we are currently referencing 2.4. It makes sense to upgrade everything if we are going to move frameworks. I'm assuming this will ship in v3.3.0 of the generator?

**Comment by wing328** [comment]
Sure as Swashbuckle 3.0.0 also contains breaking changes: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v3.0.0

>  I'm assuming this will ship in v3.3.0 of the generator?

It's scheduled on this coming Friday so we'll definitely include it if it's ready by that time.

**Comment by SeanFarrow** [comment]
Ok, should be able to get a pr out by the end of the day.
How do I generate a pet store sample server, so I can test the changes quickly? I’m running on Windows.

**Comment by wing328** [comment]
To update the petstore sample, please run `bin\windows\aspnetcore-petstore-server.bat` at the root folder of this project.

**Comment by SeanFarrow** [comment]
Ok, I can’t seem to find that bat file.
Everything seems to build though.
I’ll submit a pr in the next few hours.

**Comment by wing328** [comment]
Here is the URL to the batch file: https://github.com/OpenAPITools/openapi-generator/blob/master/bin/windows/aspnetcore-petstore-server.bat

**Comment by SeanFarrow** [comment]
Ok, got, give me an hour or so to update the sample.

**Comment by wing328** [comment]
Please take your time. Let us know if you need any help.

**Comment by wing328** [comment]
> Do you want commits squashed into a single commit?

Nope, we'll squash your commits into one as part of the merge.

**Comment by jimschubert** [comment]
To comment on this as far as ASP.NET Core 2.1, I'd prefer to just update fully to 2.1 and not leave support for 2.0. 2.1 is LTS while 2.0 is not, so I don't see a reason for us to maintain a 2.0 option. I wouldn't consider this a breaking change as the generator isn't currently written with an intention to regenerate over existing code. 

.NET Core 2.0 will end-of-life at the end of this month.

**Comment by wing328** [comment]
@jimschubert thanks for reviewing this.

After I reviewed #1008 (only changes to mustache templates), I would suggest adding an option to select the framework with ASP.NET core 2.1 being the default and we'll mark 2.0 as deprecated so that we can remove it in the future release. That way we can merge the enhancement into 3.3.x branch targeted to be released this Friday.

**Comment by SeanFarrow** [comment]
@jimschubert,
That’s exactly what I was thinking. I’ve upgraded everything to Asp.Net Core 2.1.

**Comment by SeanFarrow** [comment]
@wing328,
What do I need to do to make that happen, I’m assuming this will need updates to the generater? Therefore should we do this as a separate issue/pr?
Could we do this after Friday, given that 2.2 will be coming later this year, so it would make sense then.
If we did this after Friday, could we still merge the template changes for 2.1 for Friday?

**Comment by wing328** [comment]
@SeanFarrow I can add it after merging your PR (as I just did something similar for another enhancement related to Java Feign version upgrade)

**Comment by SeanFarrow** [comment]
@wing328,
I’m happy to do the work, as it gives me more exposure to Java, I’d just need to understand what would be required.

**Comment by wing328** [comment]
@SeanFarrow sure, you will need to add a CLI option (e.g. aspNetCoreVersion) to support "2.0", "2.1" and put the templates (the existing one for v2.0) in a separate folder. We'd a very similar change for Dart to support Dart v2 recently and https://github.com/OpenAPITools/openapi-generator/pull/754/files#diff-79347eb38a35fa462a0c2b03aa771e75R129 is a good starting point.

Please let me know if you need help adding the option.

**Comment by SeanFarrow** [comment]
@wing328,
That sounds doable.
I’ll do this either later in the week or this weekend, if that works for you given the release on Friday?

**Comment by wing328** [comment]
@SeanFarrow if we (you or me) add it after the minor release (3.3.x) this Friday, we may need to wait for 2 months as we plan to change the minor release schedule to bi-monthly: https://github.com/OpenAPITools/openapi-generator/issues/956

**Comment by SeanFarrow** [comment]
@wing328,
OK, given my currently available time this week, it’s probably best you tackle this, sorry!

**Comment by wing328** [comment]
No worry. I'll do it later today and keep you posted.

**Comment by wing328** [comment]
I've updated https://github.com/OpenAPITools/openapi-generator/pull/1008 with the option "aspnetCoreVersion" (default to 2.1). Please have a look when you've time.

**Comment by SeanFarrow** [comment]
@wing328,
This looks good, can we close/merge? Have the docs been updated?

**Comment by wing328** [comment]
@SeanFarrow PR merged. Thanks for your PR.

Do you have a Twitter account? We'll promote the enhancement via https://twitter.com/oas_generator

I'll update the documentation later if needed.

**Comment by SeanFarrow** [comment]
@wing328,
No problem, I’ve just followed that account. My twitter handle is @SeanRFarrow

**Comment by wing328** [comment]
👌

**Comment by wing328** [comment]
Tweet: https://twitter.com/oas_generator/status/1039932534258167808

Please help retweet to promote the enhancement
